FortreeCity_Text_167577:: @ 8167577
	.string "Schnüffel...\n"
	.string "Äh... Du, uh... riechst angesengt.\p"
	.string "Warst du auf einem Vulkan oder so?$"

FortreeCity_Text_1675C2:: @ 81675C2
	.string "Ich wollte zur POKéMON ARENA, aber\n"
	.string "irgendetwas blockiert den Weg.\p"
	.string "Und das, nachdem ich auf der ROUTE 120\n"
	.string "so fleißig trainiert habe...$"

FortreeCity_Text_167642:: @ 8167642
	.string "Dieses POKéMON ist mein ganzer Stolz!\n"
	.string "Diesmal werde ich WIBKE besiegen!$"

FortreeCity_Text_16768A:: @ 816768A
	.string "Der Boden nimmt das Regenwasser auf,\n"
	.string "die Bäume trinken es und wachsen...\p"
	.string "Unser BAUMHAUSEN CITY existiert, weil\n"
	.string "es genügend Wasser und Boden gibt.$"

FortreeCity_Text_16770E:: @ 816770E
	.string "Die STADT besteht aus Häusern, die auf\n"
	.string "Bäumen gebaut sind.\p"
	.string "Aufgrund dieser Lebensweise ist jeder\n"
	.string "hier gesund und munter.\p"
	.string "Und auch ich fühle mich, als sei ich\n"
	.string "30 Jahre jünger geworden.$"

FortreeCity_Text_1677BD:: @ 81677BD
	.string "Auf Bäumen zu leben ist klasse.\p"
	.string "Aber manchmal kommen KÄFER-POKéMON\n"
	.string "durch die Fenster herein.\l"
	.string "Das kann einen ganz schön erschrecken.$"

FortreeCity_Text_16782C:: @ 816782C
	.string "Manche POKéMON entwickeln sich, wenn\n"
	.string "sie durch ein Verbindungskabel laufen.$"

FortreeCity_Text_167868:: @ 8167868
	.string "Etwas Unsichtbares blockiert den Weg.$"

FortreeCity_Text_16788B:: @ 816788B
	.string "Etwas Unsichtbares blockiert den Weg.\p"
	.string "Willst du das DEVON-SCOPE einsetzen?$"

FortreeCity_Text_1678CB:: @ 81678CB
	.string "{PLAYER} setzt das DEVON-SCOPE ein.\p"
	.string "Ein unsichtbares POKéMON ist sichtbar\n"
	.string "geworden!\p"
	.string "Das erschrockene POKéMON flieht!$"

FortreeCity_Text_16792F:: @ 816792F
	.string "BAUMHAUSEN CITY\n"
	.string "“Die Stadt in den Baumkronen,\l"
	.string "verbrüdert mit der Natur.”$"

FortreeCity_Text_167969:: @ 8167969
	.string "POKéMON ARENA von BAUMHAUSEN CITY\n"
	.string "LEITERIN: WIBKE\p"
	.string "“Die Vogel-Liebhaberin hebt ab zum\n"
	.string "Flug in die Welt.”$"
