	.align 2
DirectSoundWaveData_Tone1:: @ 8456330
	.incbin "sound/direct_sound_samples/synth/tone1.bin"

	.align 2
DirectSoundWaveData_SC88_Organ2:: @ 84569D4
	.incbin "sound/direct_sound_samples/synth/sc88_18_organ_2.bin"

	.align 2
DirectSoundWaveData_SC88_FretlessBass:: @ 84571CC
	.incbin "sound/direct_sound_samples/synth/sc88_36_fretless_bass.bin"

	.align 2
DirectSoundWaveData_SC88_FingerSlap:: @ 8457D98
	.incbin "sound/direct_sound_samples/synth/sc88_34_finger_slap.bin"

	.align 2
DirectSoundWaveData_SC88_SynthBass1:: @ 8458CD0
	.incbin "sound/direct_sound_samples/synth/sc88_39_synth_bass_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitTimbale2:: @ 8459944
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_timbale_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitBassDrum:: @ 845AE14
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_bass_drum.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare1:: @ 845B2B4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitHandClap:: @ 845B9A8
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_hand_clap.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare2:: @ 845C238
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitHiMidTom:: @ 845CAB0
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_hi_mid_tom.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitClosedHiHat:: @ 845DAF0
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_closed_hi_hat.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitOpenHiHat:: @ 845DF04
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_open_hi_hat.bin"

	.align 2
DirectSoundWaveData_HiHatRattle:: @ 845ED34
	.incbin "sound/direct_sound_samples/synth/hi_hat_rattle.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCabasa:: @ 845FCC8
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_cabasa.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCrashCymbal2:: @ 846057C
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_crash_cymbal_2.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitCrashCymbal1:: @ 8460E60
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_crash_cymbal_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitMuteHiConga:: @ 8461D8C
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_mute_hi_conga.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitLowConga:: @ 84622A4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_low_conga.bin"

	.align 2
DirectSoundWaveData_SC88_SteelStringGuitar:: @ 846286C
	.incbin "sound/direct_sound_samples/synth/sc88_26_steel_string_guitar.bin"

	.align 2
DirectSoundWaveData_SC88_Piano3:: @ 84637CC
	.incbin "sound/direct_sound_samples/synth/sc88_3_piano_3.bin"

	.align 2
DirectSoundWaveData_SC88_Piano2:: @ 8464E2C
	.incbin "sound/direct_sound_samples/synth/sc88_2_piano_2.bin"

	.align 2
DirectSoundWaveData_SC88_UnisonSlap:: @ 8466388
	.incbin "sound/direct_sound_samples/synth/sc88_37_unison_slap.bin"

	.align 2
DirectSoundWaveData_SC88_Strings:: @ 8466F14
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings.bin"

	.align 2
DirectSoundWaveData_SC88_StringsPlusFlute:: @ 846A4B8
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings_plus_flute.bin"

	.align 2
DirectSoundWaveData_SC88_StringsPlusHorn:: @ 846C7D4
	.incbin "sound/direct_sound_samples/synth/sc88_49_strings_plus_horn.bin"

	.align 2
DirectSoundWaveData_SC88_Trumpet:: @ 846FEA0
	.incbin "sound/direct_sound_samples/synth/sc88_57_trumpet.bin"

	.align 2
DirectSoundWaveData_SC88_Trombone:: @ 84711F0
	.incbin "sound/direct_sound_samples/synth/sc88_58_trombone.bin"

	.align 2
DirectSoundWaveData_SC88_Tuba:: @ 8472700
	.incbin "sound/direct_sound_samples/synth/sc88_59_tuba.bin"

	.align 2
DirectSoundWaveData_SC88_CupMutedTrumpet:: @ 8473B20
	.incbin "sound/direct_sound_samples/synth/sc88_60_cup_muted_trumpet.bin"

	.align 2
DirectSoundWaveData_SC88_MutedTrumpet3:: @ 8474BBC
	.incbin "sound/direct_sound_samples/synth/sc88_60_muted_trumpet_3.bin"

	.align 2
DirectSoundWaveData_SC88_FrenchHorns:: @ 8475C18
	.incbin "sound/direct_sound_samples/synth/sc88_61_french_horns.bin"

	.align 2
DirectSoundWaveData_SC88_WideFrenchHorns:: @ 847CBAC
	.incbin "sound/direct_sound_samples/synth/sc88_61_wide_french_horns.bin"

	.align 2
DirectSoundWaveData_SC88_NylonStringGuitar:: @ 8481130
	.incbin "sound/direct_sound_samples/synth/sc88_25_nylon_string_guitar.bin"

	.align 2
DirectSoundWaveData_SC88_Flute:: @ 84830A0
	.incbin "sound/direct_sound_samples/synth/sc88_74_flute.bin"

	.align 2
DirectSoundWaveData_SC88_FingeredBass:: @ 8483804
	.incbin "sound/direct_sound_samples/synth/sc88_34_fingered_bass.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitTimbale1:: @ 8485454
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_timbale_1.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare4:: @ 8486924
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_4.bin"

	.align 2
DirectSoundWaveData_SC88_SquareWave:: @ 8487330
	.incbin "sound/direct_sound_samples/synth/sc88_81_square_wave.bin"

	.align 2
DirectSoundWaveData_Ring:: @ 8488F44
	.incbin "sound/direct_sound_samples/synth/ring.bin"

	.align 2
DirectSoundWaveData_SC88_DrumKitSnare3:: @ 848A8A4
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_snare_3.bin"

	.align 2
DirectSoundWaveData_SC88_PizzicatoStrings:: @ 848BD68
	.incbin "sound/direct_sound_samples/synth/sc88_46_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_MachineSound2:: @ 848C4A4
	.incbin "sound/direct_sound_samples/synth/machine_sound2.bin"

	.align 2
DirectSoundWaveData_MachineSound1:: @ 848E094
	.incbin "sound/direct_sound_samples/synth/machine_sound1.bin"

	.align 2
DirectSoundWaveData_SC88_Applause2:: @ 848F448
	.incbin "sound/direct_sound_samples/synth/sc88_127_applause_2.bin"

	.align 2
DirectSoundWaveData_Noise3:: @ 8491ACC
	.incbin "sound/direct_sound_samples/synth/noise3.bin"

	.align 2
DirectSoundWaveData_SC88_Bubble:: @ 8492D10
	.incbin "sound/direct_sound_samples/synth/sc88_123_bubble.bin"

	.align 2
DirectSoundWaveData_SC88_CarCrash:: @ 8493D20
	.incbin "sound/direct_sound_samples/synth/sc88_126_car_crash.bin"

	.align 2
DirectSoundWaveData_SC88_PinkNoise:: @ 8495028
	.incbin "sound/direct_sound_samples/synth/sc88_123_pink_noise.bin"

	.align 2
DirectSoundWaveData_SC88_WaspySynth:: @ 8497134
	.incbin "sound/direct_sound_samples/synth/sc88_82_waspy_synth.bin"

	.align 2
DirectSoundWaveData_SC88_WhiteNoise:: @ 8499110
	.incbin "sound/direct_sound_samples/synth/sc88_123_white_noise.bin"

	.align 2
DirectSoundWaveData_SC88_DrumkitGuiro:: @ 849B320
	.incbin "sound/direct_sound_samples/synth/sc88_drumkit_guiro.bin"

	.align 2
DirectSoundWaveData_SC88_TubularBell:: @ 849BAEC
	.incbin "sound/direct_sound_samples/synth/sc88_15_tubular_bell.bin"

	.align 2
DirectSoundWaveData_Noise1:: @ 849D45C
	.incbin "sound/direct_sound_samples/synth/noise1.bin"

	.align 2
DirectSoundWaveData_SC88_JPSuperSaw:: @ 849F40C
	.incbin "sound/direct_sound_samples/synth/sc88_82_jp_super_saw.bin"

	.align 2
DirectSoundWaveData_SC88_Piano1:: @ 84A26EC
	.incbin "sound/direct_sound_samples/synth/sc88_1_piano_1.bin"

	.align 2
DirectSoundWaveData_SC88_Marimba:: @ 84A311C
	.incbin "sound/direct_sound_samples/synth/sc88_13_marimba.bin"

	.align 2
DirectSoundWaveData_Noise2:: @ 84A3B50
	.incbin "sound/direct_sound_samples/synth/noise2.bin"

	.align 2
DirectSoundWaveData_SC88_HorseGallop:: @ 84A5690
	.incbin "sound/direct_sound_samples/synth/sc88_124_horse_gallop.bin"

	.align 2
DirectSoundWaveData_SC88_AccordianFr:: @ 84A5F58
	.incbin "sound/direct_sound_samples/synth/sc88_22_accordion_fr.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel1:: @ 84A7328
	.incbin "sound/direct_sound_samples/phonemes/vowel_1.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel2:: @ 84A7F38
	.incbin "sound/direct_sound_samples/phonemes/vowel_2.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel3:: @ 84A8AC8
	.incbin "sound/direct_sound_samples/phonemes/vowel_3.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel4:: @ 84A9564
	.incbin "sound/direct_sound_samples/phonemes/vowel_4.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel5:: @ 84A9EAC
	.incbin "sound/direct_sound_samples/phonemes/vowel_5.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel6:: @ 84AA8F4
	.incbin "sound/direct_sound_samples/phonemes/vowel_6.bin"

	.align 2
Cry_Bulbasaur:: @ 84AB57C
	.incbin "sound/direct_sound_samples/cries/cry_bulbasaur.bin"

	.align 2
Cry_Ivysaur:: @ 84AC608
	.incbin "sound/direct_sound_samples/cries/cry_ivysaur.bin"

	.align 2
Cry_Venusaur:: @ 84AD698
	.incbin "sound/direct_sound_samples/cries/cry_venusaur.bin"

	.align 2
Cry_Charmander:: @ 84AE9F0
	.incbin "sound/direct_sound_samples/cries/cry_charmander.bin"

	.align 2
Cry_Charmeleon:: @ 84AF860
	.incbin "sound/direct_sound_samples/cries/cry_charmeleon.bin"

	.align 2
Cry_Charizard:: @ 84B06E0
	.incbin "sound/direct_sound_samples/cries/cry_charizard.bin"

	.align 2
Cry_Squirtle:: @ 84B1A28
	.incbin "sound/direct_sound_samples/cries/cry_squirtle.bin"

	.align 2
Cry_Wartortle:: @ 84B289C
	.incbin "sound/direct_sound_samples/cries/cry_wartortle.bin"

	.align 2
Cry_Blastoise:: @ 84B39DC
	.incbin "sound/direct_sound_samples/cries/cry_blastoise.bin"

	.align 2
Cry_Caterpie:: @ 84B4D24
	.incbin "sound/direct_sound_samples/cries/cry_caterpie.bin"

	.align 2
Cry_Metapod:: @ 84B557C
	.incbin "sound/direct_sound_samples/cries/cry_metapod.bin"

	.align 2
Cry_Butterfree:: @ 84B6CCC
	.incbin "sound/direct_sound_samples/cries/cry_butterfree.bin"

	.align 2
Cry_Weedle:: @ 84B76D4
	.incbin "sound/direct_sound_samples/cries/cry_weedle.bin"

	.align 2
Cry_Kakuna:: @ 84B8718
	.incbin "sound/direct_sound_samples/cries/cry_kakuna.bin"

	.align 2
Cry_Beedrill:: @ 84B9954
	.incbin "sound/direct_sound_samples/cries/cry_beedrill.bin"

	.align 2
Cry_Pidgey:: @ 84BACB0
	.incbin "sound/direct_sound_samples/cries/cry_pidgey.bin"

	.align 2
Cry_Pidgeotto:: @ 84BB098
	.incbin "sound/direct_sound_samples/cries/cry_pidgeotto.bin"

	.align 2
Cry_Pidgeot:: @ 84BBFA0
	.incbin "sound/direct_sound_samples/cries/cry_pidgeot.bin"

	.align 2
Cry_Rattata:: @ 84BD0D4
	.incbin "sound/direct_sound_samples/cries/cry_rattata.bin"

	.align 2
Cry_Raticate:: @ 84BD8B4
	.incbin "sound/direct_sound_samples/cries/cry_raticate.bin"

	.align 2
Cry_Spearow:: @ 84BE238
	.incbin "sound/direct_sound_samples/cries/cry_spearow.bin"

	.align 2
Cry_Fearow:: @ 84BF3DC
	.incbin "sound/direct_sound_samples/cries/cry_fearow.bin"

	.align 2
Cry_Ekans:: @ 84C0518
	.incbin "sound/direct_sound_samples/cries/cry_ekans.bin"

	.align 2
Cry_Arbok:: @ 84C1864
	.incbin "sound/direct_sound_samples/cries/cry_arbok.bin"

	.align 2
Cry_Pikachu:: @ 84C2BBC
	.incbin "sound/direct_sound_samples/cries/cry_pikachu.bin"

	.align 2
Cry_Raichu:: @ 84C3C64
	.incbin "sound/direct_sound_samples/cries/cry_raichu.bin"

	.align 2
Cry_Sandshrew:: @ 84C5424
	.incbin "sound/direct_sound_samples/cries/cry_sandshrew.bin"

	.align 2
Cry_Sandslash:: @ 84C5D78
	.incbin "sound/direct_sound_samples/cries/cry_sandslash.bin"

	.align 2
Cry_NidoranF:: @ 84C6B08
	.incbin "sound/direct_sound_samples/cries/cry_nidoran_f.bin"

	.align 2
Cry_Nidorina:: @ 84C74B8
	.incbin "sound/direct_sound_samples/cries/cry_nidorina.bin"

	.align 2
Cry_Nidoqueen:: @ 84C8180
	.incbin "sound/direct_sound_samples/cries/cry_nidoqueen.bin"

	.align 2
Cry_NidoranM:: @ 84C9260
	.incbin "sound/direct_sound_samples/cries/cry_nidoran_m.bin"

	.align 2
Cry_Nidorino:: @ 84C9CC8
	.incbin "sound/direct_sound_samples/cries/cry_nidorino.bin"

	.align 2
Cry_Nidoking:: @ 84CA8DC
	.incbin "sound/direct_sound_samples/cries/cry_nidoking.bin"

	.align 2
Cry_Clefairy:: @ 84CC148
	.incbin "sound/direct_sound_samples/cries/cry_clefairy.bin"

	.align 2
Cry_Clefable:: @ 84CC9B8
	.incbin "sound/direct_sound_samples/cries/cry_clefable.bin"

	.align 2
Cry_Vulpix:: @ 84CD448
	.incbin "sound/direct_sound_samples/cries/cry_vulpix.bin"

	.align 2
Cry_Ninetales:: @ 84CEC18
	.incbin "sound/direct_sound_samples/cries/cry_ninetales.bin"

	.align 2
Cry_Jigglypuff:: @ 84D0484
	.incbin "sound/direct_sound_samples/cries/cry_jigglypuff.bin"

	.align 2
Cry_Wigglytuff:: @ 84D09E8
	.incbin "sound/direct_sound_samples/cries/cry_wigglytuff.bin"

	.align 2
Cry_Zubat:: @ 84D10B0
	.incbin "sound/direct_sound_samples/cries/cry_zubat.bin"

	.align 2
Cry_Golbat:: @ 84D241C
	.incbin "sound/direct_sound_samples/cries/cry_golbat.bin"

	.align 2
Cry_Oddish:: @ 84D3780
	.incbin "sound/direct_sound_samples/cries/cry_oddish.bin"

	.align 2
Cry_Gloom:: @ 84D461C
	.incbin "sound/direct_sound_samples/cries/cry_gloom.bin"

	.align 2
Cry_Vileplume:: @ 84D5298
	.incbin "sound/direct_sound_samples/cries/cry_vileplume.bin"

	.align 2
Cry_Paras:: @ 84D6C34
	.incbin "sound/direct_sound_samples/cries/cry_paras.bin"

	.align 2
Cry_Parasect:: @ 84D8828
	.incbin "sound/direct_sound_samples/cries/cry_parasect.bin"

	.align 2
Cry_Venonat:: @ 84DA690
	.incbin "sound/direct_sound_samples/cries/cry_venonat.bin"

	.align 2
Cry_Venomoth:: @ 84DB610
	.incbin "sound/direct_sound_samples/cries/cry_venomoth.bin"

	.align 2
Cry_Diglett:: @ 84DC614
	.incbin "sound/direct_sound_samples/cries/cry_diglett.bin"

	.align 2
Cry_Dugtrio:: @ 84DD984
	.incbin "sound/direct_sound_samples/cries/cry_dugtrio.bin"

	.align 2
Cry_Meowth:: @ 84DECF0
	.incbin "sound/direct_sound_samples/cries/cry_meowth.bin"

	.align 2
Cry_Persian:: @ 84DF680
	.incbin "sound/direct_sound_samples/cries/cry_persian.bin"

	.align 2
Cry_Psyduck:: @ 84E095C
	.incbin "sound/direct_sound_samples/cries/cry_psyduck.bin"

	.align 2
Cry_Golduck:: @ 84E1684
	.incbin "sound/direct_sound_samples/cries/cry_golduck.bin"

	.align 2
Cry_Mankey:: @ 84E21CC
	.incbin "sound/direct_sound_samples/cries/cry_mankey.bin"

	.align 2
Cry_Primeape:: @ 84E322C
	.incbin "sound/direct_sound_samples/cries/cry_primeape.bin"

	.align 2
Cry_Growlithe:: @ 84E425C
	.incbin "sound/direct_sound_samples/cries/cry_growlithe.bin"

	.align 2
Cry_Arcanine:: @ 84E4FC0
	.incbin "sound/direct_sound_samples/cries/cry_arcanine.bin"

	.align 2
Cry_Poliwag:: @ 84E60FC
	.incbin "sound/direct_sound_samples/cries/cry_poliwag.bin"

	.align 2
Cry_Poliwhirl:: @ 84E6C18
	.incbin "sound/direct_sound_samples/cries/cry_poliwhirl.bin"

	.align 2
Cry_Poliwrath:: @ 84E72C0
	.incbin "sound/direct_sound_samples/cries/cry_poliwrath.bin"

	.align 2
Cry_Abra:: @ 84E7DE4
	.incbin "sound/direct_sound_samples/cries/cry_abra.bin"

	.align 2
Cry_Kadabra:: @ 84E9548
	.incbin "sound/direct_sound_samples/cries/cry_kadabra.bin"

	.align 2
Cry_Alakazam:: @ 84EB030
	.incbin "sound/direct_sound_samples/cries/cry_alakazam.bin"

	.align 2
Cry_Machop:: @ 84ECFCC
	.incbin "sound/direct_sound_samples/cries/cry_machop.bin"

	.align 2
Cry_Machoke:: @ 84EDD30
	.incbin "sound/direct_sound_samples/cries/cry_machoke.bin"

	.align 2
Cry_Machamp:: @ 84EEAC0
	.incbin "sound/direct_sound_samples/cries/cry_machamp.bin"

	.align 2
Cry_Bellsprout:: @ 84EFB48
	.incbin "sound/direct_sound_samples/cries/cry_bellsprout.bin"

	.align 2
Cry_Weepinbell:: @ 84F02D4
	.incbin "sound/direct_sound_samples/cries/cry_weepinbell.bin"

	.align 2
Cry_Victreebel:: @ 84F1174
	.incbin "sound/direct_sound_samples/cries/cry_victreebel.bin"

	.align 2
Cry_Tentacool:: @ 84F24C0
	.incbin "sound/direct_sound_samples/cries/cry_tentacool.bin"

	.align 2
Cry_Tentacruel:: @ 84F34B0
	.incbin "sound/direct_sound_samples/cries/cry_tentacruel.bin"

	.align 2
Cry_Geodude:: @ 84F4BAC
	.incbin "sound/direct_sound_samples/cries/cry_geodude.bin"

	.align 2
Cry_Graveler:: @ 84F6360
	.incbin "sound/direct_sound_samples/cries/cry_graveler.bin"

	.align 2
Cry_Golem:: @ 84F7F48
	.incbin "sound/direct_sound_samples/cries/cry_golem.bin"

	.align 2
Cry_Ponyta:: @ 84F8D74
	.incbin "sound/direct_sound_samples/cries/cry_ponyta.bin"

	.align 2
Cry_Rapidash:: @ 84F9C84
	.incbin "sound/direct_sound_samples/cries/cry_rapidash.bin"

	.align 2
Cry_Slowpoke:: @ 84FAF24
	.incbin "sound/direct_sound_samples/cries/cry_slowpoke.bin"

	.align 2
Cry_Slowbro:: @ 84FB68C
	.incbin "sound/direct_sound_samples/cries/cry_slowbro.bin"

	.align 2
Cry_Magnemite:: @ 84FC3FC
	.incbin "sound/direct_sound_samples/cries/cry_magnemite.bin"

	.align 2
Cry_Magneton:: @ 84FD740
	.incbin "sound/direct_sound_samples/cries/cry_magneton.bin"

	.align 2
Cry_Farfetchd:: @ 84FEF28
	.incbin "sound/direct_sound_samples/cries/cry_farfetchd.bin"

	.align 2
Cry_Doduo:: @ 84FF6A4
	.incbin "sound/direct_sound_samples/cries/cry_doduo.bin"

	.align 2
Cry_Dodrio:: @ 85009E8
	.incbin "sound/direct_sound_samples/cries/cry_dodrio.bin"

	.align 2
Cry_Seel:: @ 8501D60
	.incbin "sound/direct_sound_samples/cries/cry_seel.bin"

	.align 2
Cry_Dewgong:: @ 8502F50
	.incbin "sound/direct_sound_samples/cries/cry_dewgong.bin"

	.align 2
Cry_Grimer:: @ 8504474
	.incbin "sound/direct_sound_samples/cries/cry_grimer.bin"

	.align 2
Cry_Muk:: @ 8504EFC
	.incbin "sound/direct_sound_samples/cries/cry_muk.bin"

	.align 2
Cry_Shellder:: @ 8505DBC
	.incbin "sound/direct_sound_samples/cries/cry_shellder.bin"

	.align 2
Cry_Cloyster:: @ 8506D30
	.incbin "sound/direct_sound_samples/cries/cry_cloyster.bin"

	.align 2
Cry_Gastly:: @ 85081F4
	.incbin "sound/direct_sound_samples/cries/cry_gastly.bin"

	.align 2
Cry_Haunter:: @ 8509944
	.incbin "sound/direct_sound_samples/cries/cry_haunter.bin"

	.align 2
Cry_Gengar:: @ 850B0C4
	.incbin "sound/direct_sound_samples/cries/cry_gengar.bin"

	.align 2
Cry_Onix:: @ 850BF84
	.incbin "sound/direct_sound_samples/cries/cry_onix.bin"

	.align 2
Cry_Drowzee:: @ 850D848
	.incbin "sound/direct_sound_samples/cries/cry_drowzee.bin"

	.align 2
Cry_Hypno:: @ 850F560
	.incbin "sound/direct_sound_samples/cries/cry_hypno.bin"

	.align 2
Cry_Krabby:: @ 8511264
	.incbin "sound/direct_sound_samples/cries/cry_krabby.bin"

	.align 2
Cry_Kingler:: @ 8512AB0
	.incbin "sound/direct_sound_samples/cries/cry_kingler.bin"

	.align 2
Cry_Voltorb:: @ 8514308
	.incbin "sound/direct_sound_samples/cries/cry_voltorb.bin"

	.align 2
Cry_Electrode:: @ 8515BCC
	.incbin "sound/direct_sound_samples/cries/cry_electrode.bin"

	.align 2
Cry_Exeggcute:: @ 8517504
	.incbin "sound/direct_sound_samples/cries/cry_exeggcute.bin"

	.align 2
Cry_Exeggutor:: @ 85187E4
	.incbin "sound/direct_sound_samples/cries/cry_exeggutor.bin"

	.align 2
Cry_Cubone:: @ 851A7C8
	.incbin "sound/direct_sound_samples/cries/cry_cubone.bin"

	.align 2
Cry_Marowak:: @ 851B6E8
	.incbin "sound/direct_sound_samples/cries/cry_marowak.bin"

	.align 2
Cry_Hitmonlee:: @ 851C558
	.incbin "sound/direct_sound_samples/cries/cry_hitmonlee.bin"

	.align 2
Cry_Hitmonchan:: @ 851D804
	.incbin "sound/direct_sound_samples/cries/cry_hitmonchan.bin"

	.align 2
Cry_Lickitung:: @ 851E9DC
	.incbin "sound/direct_sound_samples/cries/cry_lickitung.bin"

	.align 2
Cry_Koffing:: @ 851F904
	.incbin "sound/direct_sound_samples/cries/cry_koffing.bin"

	.align 2
Cry_Weezing:: @ 8520D60
	.incbin "sound/direct_sound_samples/cries/cry_weezing.bin"

	.align 2
Cry_Rhyhorn:: @ 852230C
	.incbin "sound/direct_sound_samples/cries/cry_rhyhorn.bin"

	.align 2
Cry_Rhydon:: @ 8523678
	.incbin "sound/direct_sound_samples/cries/cry_rhydon.bin"

	.align 2
Cry_Chansey:: @ 8524AE4
	.incbin "sound/direct_sound_samples/cries/cry_chansey.bin"

	.align 2
Cry_Tangela:: @ 85259B0
	.incbin "sound/direct_sound_samples/cries/cry_tangela.bin"

	.align 2
Cry_Kangaskhan:: @ 85268CC
	.incbin "sound/direct_sound_samples/cries/cry_kangaskhan.bin"

	.align 2
Cry_Horsea:: @ 8527B80
	.incbin "sound/direct_sound_samples/cries/cry_horsea.bin"

	.align 2
Cry_Seadra:: @ 85284FC
	.incbin "sound/direct_sound_samples/cries/cry_seadra.bin"

	.align 2
Cry_Goldeen:: @ 8528D68
	.incbin "sound/direct_sound_samples/cries/cry_goldeen.bin"

	.align 2
Cry_Seaking:: @ 8529740
	.incbin "sound/direct_sound_samples/cries/cry_seaking.bin"

	.align 2
Cry_Staryu:: @ 852AA98
	.incbin "sound/direct_sound_samples/cries/cry_staryu.bin"

	.align 2
Cry_Starmie:: @ 852BE80
	.incbin "sound/direct_sound_samples/cries/cry_starmie.bin"

	.align 2
Cry_MrMime:: @ 852D35C
	.incbin "sound/direct_sound_samples/cries/cry_mr_mime.bin"

	.align 2
Cry_Scyther:: @ 852E64C
	.incbin "sound/direct_sound_samples/cries/cry_scyther.bin"

	.align 2
Cry_Jynx:: @ 852F3A8
	.incbin "sound/direct_sound_samples/cries/cry_jynx.bin"

	.align 2
Cry_Electabuzz:: @ 853231C
	.incbin "sound/direct_sound_samples/cries/cry_electabuzz.bin"

	.align 2
Cry_Magmar:: @ 8534200
	.incbin "sound/direct_sound_samples/cries/cry_magmar.bin"

	.align 2
Cry_Pinsir:: @ 853517C
	.incbin "sound/direct_sound_samples/cries/cry_pinsir.bin"

	.align 2
Cry_Tauros:: @ 8535DD8
	.incbin "sound/direct_sound_samples/cries/cry_tauros.bin"

	.align 2
Cry_Magikarp:: @ 853702C
	.incbin "sound/direct_sound_samples/cries/cry_magikarp.bin"

	.align 2
Cry_Gyarados:: @ 8538334
	.incbin "sound/direct_sound_samples/cries/cry_gyarados.bin"

	.align 2
Cry_Lapras:: @ 8539768
	.incbin "sound/direct_sound_samples/cries/cry_lapras.bin"

	.align 2
Cry_Ditto:: @ 853A63C
	.incbin "sound/direct_sound_samples/cries/cry_ditto.bin"

	.align 2
Cry_Eevee:: @ 853B158
	.incbin "sound/direct_sound_samples/cries/cry_eevee.bin"

	.align 2
Cry_Vaporeon:: @ 853BF90
	.incbin "sound/direct_sound_samples/cries/cry_vaporeon.bin"

	.align 2
Cry_Jolteon:: @ 853D5A8
	.incbin "sound/direct_sound_samples/cries/cry_jolteon.bin"

	.align 2
Cry_Flareon:: @ 853E57C
	.incbin "sound/direct_sound_samples/cries/cry_flareon.bin"

	.align 2
Cry_Porygon:: @ 853F500
	.incbin "sound/direct_sound_samples/cries/cry_porygon.bin"

	.align 2
Cry_Omanyte:: @ 854090C
	.incbin "sound/direct_sound_samples/cries/cry_omanyte.bin"

	.align 2
Cry_Omastar:: @ 8541664
	.incbin "sound/direct_sound_samples/cries/cry_omastar.bin"

	.align 2
Cry_Kabuto:: @ 85423B8
	.incbin "sound/direct_sound_samples/cries/cry_kabuto.bin"

	.align 2
Cry_Kabutops:: @ 854300C
	.incbin "sound/direct_sound_samples/cries/cry_kabutops.bin"

	.align 2
Cry_Aerodactyl:: @ 8543DC8
	.incbin "sound/direct_sound_samples/cries/cry_aerodactyl.bin"

	.align 2
Cry_Snorlax:: @ 8545624
	.incbin "sound/direct_sound_samples/cries/cry_snorlax.bin"

	.align 2
Cry_Articuno:: @ 8545B60
	.incbin "sound/direct_sound_samples/cries/cry_articuno.bin"

	.align 2
Cry_Zapdos:: @ 8547308
	.incbin "sound/direct_sound_samples/cries/cry_zapdos.bin"

	.align 2
Cry_Moltres:: @ 8548280
	.incbin "sound/direct_sound_samples/cries/cry_moltres.bin"

	.align 2
Cry_Dratini:: @ 8549A2C
	.incbin "sound/direct_sound_samples/cries/cry_dratini.bin"

	.align 2
Cry_Dragonair:: @ 854A5C8
	.incbin "sound/direct_sound_samples/cries/cry_dragonair.bin"

	.align 2
Cry_Dragonite:: @ 854B670
	.incbin "sound/direct_sound_samples/cries/cry_dragonite.bin"

	.align 2
Cry_Mewtwo:: @ 854C97C
	.incbin "sound/direct_sound_samples/cries/cry_mewtwo.bin"

	.align 2
Cry_Mew:: @ 854E7E4
	.incbin "sound/direct_sound_samples/cries/cry_mew.bin"

	.align 2
Cry_Chikorita:: @ 855064C
	.incbin "sound/direct_sound_samples/cries/cry_chikorita.bin"

	.align 2
Cry_Bayleef:: @ 8550B8C
	.incbin "sound/direct_sound_samples/cries/cry_bayleef.bin"

	.align 2
Cry_Meganium:: @ 8551458
	.incbin "sound/direct_sound_samples/cries/cry_meganium.bin"

	.align 2
Cry_Cyndaquil:: @ 8552490
	.incbin "sound/direct_sound_samples/cries/cry_cyndaquil.bin"

	.align 2
Cry_Quilava:: @ 8552B94
	.incbin "sound/direct_sound_samples/cries/cry_quilava.bin"

	.align 2
Cry_Typhlosion:: @ 855377C
	.incbin "sound/direct_sound_samples/cries/cry_typhlosion.bin"

	.align 2
Cry_Totodile:: @ 8555D8C
	.incbin "sound/direct_sound_samples/cries/cry_totodile.bin"

	.align 2
Cry_Croconaw:: @ 8556FE4
	.incbin "sound/direct_sound_samples/cries/cry_croconaw.bin"

	.align 2
Cry_Feraligatr:: @ 8558420
	.incbin "sound/direct_sound_samples/cries/cry_feraligatr.bin"

	.align 2
Cry_Sentret:: @ 8559DA4
	.incbin "sound/direct_sound_samples/cries/cry_sentret.bin"

	.align 2
Cry_Furret:: @ 855A1CC
	.incbin "sound/direct_sound_samples/cries/cry_furret.bin"

	.align 2
Cry_Hoothoot:: @ 855A814
	.incbin "sound/direct_sound_samples/cries/cry_hoothoot.bin"

	.align 2
Cry_Noctowl:: @ 855B2F8
	.incbin "sound/direct_sound_samples/cries/cry_noctowl.bin"

	.align 2
Cry_Ledyba:: @ 855C828
	.incbin "sound/direct_sound_samples/cries/cry_ledyba.bin"

	.align 2
Cry_Ledian:: @ 855CF20
	.incbin "sound/direct_sound_samples/cries/cry_ledian.bin"

	.align 2
Cry_Spinarak:: @ 855D784
	.incbin "sound/direct_sound_samples/cries/cry_spinarak.bin"

	.align 2
Cry_Ariados:: @ 855E4E8
	.incbin "sound/direct_sound_samples/cries/cry_ariados.bin"

	.align 2
Cry_Crobat:: @ 855F13C
	.incbin "sound/direct_sound_samples/cries/cry_crobat.bin"

	.align 2
Cry_Chinchou:: @ 856086C
	.incbin "sound/direct_sound_samples/cries/cry_chinchou.bin"

	.align 2
Cry_Lanturn:: @ 856151C
	.incbin "sound/direct_sound_samples/cries/cry_lanturn.bin"

	.align 2
Cry_Pichu:: @ 8561FA8
	.incbin "sound/direct_sound_samples/cries/cry_pichu.bin"

	.align 2
Cry_Cleffa:: @ 85626FC
	.incbin "sound/direct_sound_samples/cries/cry_cleffa.bin"

	.align 2
Cry_Igglybuff:: @ 8562CEC
	.incbin "sound/direct_sound_samples/cries/cry_igglybuff.bin"

	.align 2
Cry_Togepi:: @ 85633E8
	.incbin "sound/direct_sound_samples/cries/cry_togepi.bin"

	.align 2
Cry_Togetic:: @ 8563ED0
	.incbin "sound/direct_sound_samples/cries/cry_togetic.bin"

	.align 2
Cry_Natu:: @ 85645D0
	.incbin "sound/direct_sound_samples/cries/cry_natu.bin"

	.align 2
Cry_Xatu:: @ 8565060
	.incbin "sound/direct_sound_samples/cries/cry_xatu.bin"

	.align 2
Cry_Mareep:: @ 8565F2C
	.incbin "sound/direct_sound_samples/cries/cry_mareep.bin"

	.align 2
Cry_Flaaffy:: @ 8566684
	.incbin "sound/direct_sound_samples/cries/cry_flaaffy.bin"

	.align 2
Cry_Ampharos:: @ 8567438
	.incbin "sound/direct_sound_samples/cries/cry_ampharos.bin"

	.align 2
Cry_Bellossom:: @ 85684B8
	.incbin "sound/direct_sound_samples/cries/cry_bellossom.bin"

	.align 2
Cry_Marill:: @ 85692D0
	.incbin "sound/direct_sound_samples/cries/cry_marill.bin"

	.align 2
Cry_Azumarill:: @ 8569FE4
	.incbin "sound/direct_sound_samples/cries/cry_azumarill.bin"

	.align 2
Cry_Sudowoodo:: @ 856B0D0
	.incbin "sound/direct_sound_samples/cries/cry_sudowoodo.bin"

	.align 2
Cry_Politoed:: @ 856C100
	.incbin "sound/direct_sound_samples/cries/cry_politoed.bin"

	.align 2
Cry_Hoppip:: @ 856D344
	.incbin "sound/direct_sound_samples/cries/cry_hoppip.bin"

	.align 2
Cry_Skiploom:: @ 856DBB0
	.incbin "sound/direct_sound_samples/cries/cry_skiploom.bin"

	.align 2
Cry_Jumpluff:: @ 856E8B8
	.incbin "sound/direct_sound_samples/cries/cry_jumpluff.bin"

	.align 2
Cry_Aipom:: @ 856F8F4
	.incbin "sound/direct_sound_samples/cries/cry_aipom.bin"

	.align 2
Cry_Sunkern:: @ 8570714
	.incbin "sound/direct_sound_samples/cries/cry_sunkern.bin"

	.align 2
Cry_Sunflora:: @ 8570F28
	.incbin "sound/direct_sound_samples/cries/cry_sunflora.bin"

	.align 2
Cry_Yanma:: @ 8571F08
	.incbin "sound/direct_sound_samples/cries/cry_yanma.bin"

	.align 2
Cry_Wooper:: @ 8573010
	.incbin "sound/direct_sound_samples/cries/cry_wooper.bin"

	.align 2
Cry_Quagsire:: @ 8573770
	.incbin "sound/direct_sound_samples/cries/cry_quagsire.bin"

	.align 2
Cry_Espeon:: @ 85744D0
	.incbin "sound/direct_sound_samples/cries/cry_espeon.bin"

	.align 2
Cry_Umbreon:: @ 8575884
	.incbin "sound/direct_sound_samples/cries/cry_umbreon.bin"

	.align 2
Cry_Murkrow:: @ 8576804
	.incbin "sound/direct_sound_samples/cries/cry_murkrow.bin"

	.align 2
Cry_Slowking:: @ 85778C8
	.incbin "sound/direct_sound_samples/cries/cry_slowking.bin"

	.align 2
Cry_Misdreavus:: @ 85790AC
	.incbin "sound/direct_sound_samples/cries/cry_misdreavus.bin"

	.align 2
Cry_Unown:: @ 8579C4C
	.incbin "sound/direct_sound_samples/cries/cry_unown.bin"

	.align 2
Cry_Wobbuffet:: @ 857A974
	.incbin "sound/direct_sound_samples/cries/cry_wobbuffet.bin"

	.align 2
Cry_Girafarig:: @ 857BE10
	.incbin "sound/direct_sound_samples/cries/cry_girafarig.bin"

	.align 2
Cry_Pineco:: @ 857CCC4
	.incbin "sound/direct_sound_samples/cries/cry_pineco.bin"

	.align 2
Cry_Forretress:: @ 857DA24
	.incbin "sound/direct_sound_samples/cries/cry_forretress.bin"

	.align 2
Cry_Dunsparce:: @ 857EE2C
	.incbin "sound/direct_sound_samples/cries/cry_dunsparce.bin"

	.align 2
Cry_Gligar:: @ 857FE0C
	.incbin "sound/direct_sound_samples/cries/cry_gligar.bin"

	.align 2
Cry_Steelix:: @ 8580A2C
	.incbin "sound/direct_sound_samples/cries/cry_steelix.bin"

	.align 2
Cry_Snubbull:: @ 8583054
	.incbin "sound/direct_sound_samples/cries/cry_snubbull.bin"

	.align 2
Cry_Granbull:: @ 8583EC8
	.incbin "sound/direct_sound_samples/cries/cry_granbull.bin"

	.align 2
Cry_Qwilfish:: @ 858566C
	.incbin "sound/direct_sound_samples/cries/cry_qwilfish.bin"

	.align 2
Cry_Scizor:: @ 8586208
	.incbin "sound/direct_sound_samples/cries/cry_scizor.bin"

	.align 2
Cry_Shuckle:: @ 8587904
	.incbin "sound/direct_sound_samples/cries/cry_shuckle.bin"

	.align 2
Cry_Heracross:: @ 8588338
	.incbin "sound/direct_sound_samples/cries/cry_heracross.bin"

	.align 2
Cry_Sneasel:: @ 858958C
	.incbin "sound/direct_sound_samples/cries/cry_sneasel.bin"

	.align 2
Cry_Teddiursa:: @ 8589EB0
	.incbin "sound/direct_sound_samples/cries/cry_teddiursa.bin"

	.align 2
Cry_Ursaring:: @ 858AF3C
	.incbin "sound/direct_sound_samples/cries/cry_ursaring.bin"

	.align 2
Cry_Slugma:: @ 858CD14
	.incbin "sound/direct_sound_samples/cries/cry_slugma.bin"

	.align 2
Cry_Magcargo:: @ 858DE2C
	.incbin "sound/direct_sound_samples/cries/cry_magcargo.bin"

	.align 2
Cry_Swinub:: @ 858F334
	.incbin "sound/direct_sound_samples/cries/cry_swinub.bin"

	.align 2
Cry_Piloswine:: @ 858FFDC
	.incbin "sound/direct_sound_samples/cries/cry_piloswine.bin"

	.align 2
Cry_Corsola:: @ 8590CD0
	.incbin "sound/direct_sound_samples/cries/cry_corsola.bin"

	.align 2
Cry_Remoraid:: @ 85919B0
	.incbin "sound/direct_sound_samples/cries/cry_remoraid.bin"

	.align 2
Cry_Octillery:: @ 8592440
	.incbin "sound/direct_sound_samples/cries/cry_octillery.bin"

	.align 2
Cry_Delibird:: @ 8593E84
	.incbin "sound/direct_sound_samples/cries/cry_delibird.bin"

	.align 2
Cry_Mantine:: @ 8594EB8
	.incbin "sound/direct_sound_samples/cries/cry_mantine.bin"

	.align 2
Cry_Skarmory:: @ 8595E80
	.incbin "sound/direct_sound_samples/cries/cry_skarmory.bin"

	.align 2
Cry_Houndour:: @ 8597688
	.incbin "sound/direct_sound_samples/cries/cry_houndour.bin"

	.align 2
Cry_Houndoom:: @ 8598330
	.incbin "sound/direct_sound_samples/cries/cry_houndoom.bin"

	.align 2
Cry_Kingdra:: @ 85996E0
	.incbin "sound/direct_sound_samples/cries/cry_kingdra.bin"

	.align 2
Cry_Phanpy:: @ 859A4B8
	.incbin "sound/direct_sound_samples/cries/cry_phanpy.bin"

	.align 2
Cry_Donphan:: @ 859B008
	.incbin "sound/direct_sound_samples/cries/cry_donphan.bin"

	.align 2
Cry_Porygon2:: @ 859C12C
	.incbin "sound/direct_sound_samples/cries/cry_porygon2.bin"

	.align 2
Cry_Stantler:: @ 859D0E4
	.incbin "sound/direct_sound_samples/cries/cry_stantler.bin"

	.align 2
Cry_Smeargle:: @ 859E760
	.incbin "sound/direct_sound_samples/cries/cry_smeargle.bin"

	.align 2
Cry_Tyrogue:: @ 859F194
	.incbin "sound/direct_sound_samples/cries/cry_tyrogue.bin"

	.align 2
Cry_Hitmontop:: @ 85A01BC
	.incbin "sound/direct_sound_samples/cries/cry_hitmontop.bin"

	.align 2
Cry_Smoochum:: @ 85A0F9C
	.incbin "sound/direct_sound_samples/cries/cry_smoochum.bin"

	.align 2
Cry_Elekid:: @ 85A1B50
	.incbin "sound/direct_sound_samples/cries/cry_elekid.bin"

	.align 2
Cry_Magby:: @ 85A25DC
	.incbin "sound/direct_sound_samples/cries/cry_magby.bin"

	.align 2
Cry_Miltank:: @ 85A344C
	.incbin "sound/direct_sound_samples/cries/cry_miltank.bin"

	.align 2
Cry_Blissey:: @ 85A4328
	.incbin "sound/direct_sound_samples/cries/cry_blissey.bin"

	.align 2
Cry_Raikou:: @ 85A53BC
	.incbin "sound/direct_sound_samples/cries/cry_raikou.bin"

	.align 2
Cry_Entei:: @ 85A652C
	.incbin "sound/direct_sound_samples/cries/cry_entei.bin"

	.align 2
Cry_Suicune:: @ 85A79A0
	.incbin "sound/direct_sound_samples/cries/cry_suicune.bin"

	.align 2
Cry_Larvitar:: @ 85A8BE8
	.incbin "sound/direct_sound_samples/cries/cry_larvitar.bin"

	.align 2
Cry_Pupitar:: @ 85A9898
	.incbin "sound/direct_sound_samples/cries/cry_pupitar.bin"

	.align 2
Cry_Tyranitar:: @ 85AA108
	.incbin "sound/direct_sound_samples/cries/cry_tyranitar.bin"

	.align 2
Cry_Lugia:: @ 85AB868
	.incbin "sound/direct_sound_samples/cries/cry_lugia.bin"

	.align 2
Cry_HoOh:: @ 85ADE60
	.incbin "sound/direct_sound_samples/cries/cry_ho_oh.bin"

	.align 2
Cry_Celebi:: @ 85AF4F4
	.incbin "sound/direct_sound_samples/cries/cry_celebi.bin"

	.align 2
Cry_Kecleon:: @ 85B036C
	.incbin "sound/direct_sound_samples/cries/cry_kecleon.bin"

	.align 2
Cry_Roselia:: @ 85B0BCC
	.incbin "sound/direct_sound_samples/cries/cry_roselia.bin"

	.align 2
Cry_Torkoal:: @ 85B168C
	.incbin "sound/direct_sound_samples/cries/cry_torkoal.bin"

	.align 2
Cry_Electrike:: @ 85B1FD8
	.incbin "sound/direct_sound_samples/cries/cry_electrike.bin"

	.align 2
Cry_Manectric:: @ 85B2C34
	.incbin "sound/direct_sound_samples/cries/cry_manectric.bin"

	.align 2
Cry_Duskull:: @ 85B413C
	.incbin "sound/direct_sound_samples/cries/cry_duskull.bin"

	.align 2
Cry_Latias:: @ 85B4BD4
	.incbin "sound/direct_sound_samples/cries/cry_latias.bin"

	.align 2
Cry_Wynaut:: @ 85B5804
	.incbin "sound/direct_sound_samples/cries/cry_wynaut.bin"

	.align 2
Cry_Seviper:: @ 85B65E4
	.incbin "sound/direct_sound_samples/cries/cry_seviper.bin"

	.align 2
Cry_Sharpedo:: @ 85B7184
	.incbin "sound/direct_sound_samples/cries/cry_sharpedo.bin"

	.align 2
Cry_Zangoose:: @ 85B8890
	.incbin "sound/direct_sound_samples/cries/cry_zangoose.bin"

	.align 2
Cry_Azurill:: @ 85B9220
	.incbin "sound/direct_sound_samples/cries/cry_azurill.bin"

	.align 2
Cry_Swablu:: @ 85B9C88
	.incbin "sound/direct_sound_samples/cries/cry_swablu.bin"

	.align 2
Cry_Altaria:: @ 85BA220
	.incbin "sound/direct_sound_samples/cries/cry_altaria.bin"

	.align 2
Cry_Unused265:: @ 85BAD3C
	.incbin "sound/direct_sound_samples/cries/cry_unused_265.bin"

	.align 2
Cry_Taillow:: @ 85BB690
	.incbin "sound/direct_sound_samples/cries/cry_taillow.bin"

	.align 2
Cry_Swellow:: @ 85BBC90
	.incbin "sound/direct_sound_samples/cries/cry_swellow.bin"

	.align 2
Cry_Unused268:: @ 85BC594
	.incbin "sound/direct_sound_samples/cries/cry_unused_268.bin"

	.align 2
Cry_Spinda:: @ 85BD744
	.incbin "sound/direct_sound_samples/cries/cry_spinda.bin"

	.align 2
Cry_Torchic:: @ 85BE3B0
	.incbin "sound/direct_sound_samples/cries/cry_torchic.bin"

	.align 2
Cry_Combusken:: @ 85BED58
	.incbin "sound/direct_sound_samples/cries/cry_combusken.bin"

	.align 2
Cry_Blaziken:: @ 85C0A2C
	.incbin "sound/direct_sound_samples/cries/cry_blaziken.bin"

	.align 2
Cry_Treecko:: @ 85C29AC
	.incbin "sound/direct_sound_samples/cries/cry_treecko.bin"

	.align 2
Cry_Grovyle:: @ 85C3554
	.incbin "sound/direct_sound_samples/cries/cry_grovyle.bin"

	.align 2
Cry_Sceptile:: @ 85C49C8
	.incbin "sound/direct_sound_samples/cries/cry_sceptile.bin"

	.align 2
Cry_Mudkip:: @ 85C63E4
	.incbin "sound/direct_sound_samples/cries/cry_mudkip.bin"

	.align 2
Cry_Marshtomp:: @ 85C6B68
	.incbin "sound/direct_sound_samples/cries/cry_marshtomp.bin"

	.align 2
Cry_Swampert:: @ 85C7C6C
	.incbin "sound/direct_sound_samples/cries/cry_swampert.bin"

	.align 2
Cry_Pelipper:: @ 85C92EC
	.incbin "sound/direct_sound_samples/cries/cry_pelipper.bin"

	.align 2
Cry_Wingull:: @ 85C9EB4
	.incbin "sound/direct_sound_samples/cries/cry_wingull.bin"

	.align 2
Cry_Banette:: @ 85CAAF4
	.incbin "sound/direct_sound_samples/cries/cry_banette.bin"

	.align 2
Cry_Shuppet:: @ 85CB79C
	.incbin "sound/direct_sound_samples/cries/cry_shuppet.bin"

	.align 2
Cry_Lotad:: @ 85CBFDC
	.incbin "sound/direct_sound_samples/cries/cry_lotad.bin"

	.align 2
Cry_Lombre:: @ 85CC444
	.incbin "sound/direct_sound_samples/cries/cry_lombre.bin"

	.align 2
Cry_Ludicolo:: @ 85CD2D8
	.incbin "sound/direct_sound_samples/cries/cry_ludicolo.bin"

	.align 2
Cry_Seedot:: @ 85CE3A8
	.incbin "sound/direct_sound_samples/cries/cry_seedot.bin"

	.align 2
Cry_Nuzleaf:: @ 85CEBD4
	.incbin "sound/direct_sound_samples/cries/cry_nuzleaf.bin"

	.align 2
Cry_Shiftry:: @ 85CF73C
	.incbin "sound/direct_sound_samples/cries/cry_shiftry.bin"

	.align 2
Cry_Carvanha:: @ 85D0B00
	.incbin "sound/direct_sound_samples/cries/cry_carvanha.bin"

	.align 2
Cry_Wurmple:: @ 85D1514
	.incbin "sound/direct_sound_samples/cries/cry_wurmple.bin"

	.align 2
Cry_Silcoon:: @ 85D1DE0
	.incbin "sound/direct_sound_samples/cries/cry_silcoon.bin"

	.align 2
Cry_Beautifly:: @ 85D2E0C
	.incbin "sound/direct_sound_samples/cries/cry_beautifly.bin"

	.align 2
Cry_Cascoon:: @ 85D3644
	.incbin "sound/direct_sound_samples/cries/cry_cascoon.bin"

	.align 2
Cry_Dustox:: @ 85D4688
	.incbin "sound/direct_sound_samples/cries/cry_dustox.bin"

	.align 2
Cry_Ralts:: @ 85D5334
	.incbin "sound/direct_sound_samples/cries/cry_ralts.bin"

	.align 2
Cry_Kirlia:: @ 85D5D50
	.incbin "sound/direct_sound_samples/cries/cry_kirlia.bin"

	.align 2
Cry_Gardevoir:: @ 85D6980
	.incbin "sound/direct_sound_samples/cries/cry_gardevoir.bin"

	.align 2
Cry_Slakoth:: @ 85D81E4
	.incbin "sound/direct_sound_samples/cries/cry_slakoth.bin"

	.align 2
Cry_Vigoroth:: @ 85D8A68
	.incbin "sound/direct_sound_samples/cries/cry_vigoroth.bin"

	.align 2
Cry_Slaking:: @ 85D98C0
	.incbin "sound/direct_sound_samples/cries/cry_slaking.bin"

	.align 2
Cry_Nincada:: @ 85DA2AC
	.incbin "sound/direct_sound_samples/cries/cry_nincada.bin"

	.align 2
Cry_Ninjask:: @ 85DA91C
	.incbin "sound/direct_sound_samples/cries/cry_ninjask.bin"

	.align 2
Cry_Shedinja:: @ 85DB544
	.incbin "sound/direct_sound_samples/cries/cry_shedinja.bin"

	.align 2
Cry_Makuhita:: @ 85DBCFC
	.incbin "sound/direct_sound_samples/cries/cry_makuhita.bin"

	.align 2
Cry_Hariyama:: @ 85DC458
	.incbin "sound/direct_sound_samples/cries/cry_hariyama.bin"

	.align 2
Cry_Nosepass:: @ 85DD510
	.incbin "sound/direct_sound_samples/cries/cry_nosepass.bin"

	.align 2
Cry_Glalie:: @ 85DE274
	.incbin "sound/direct_sound_samples/cries/cry_glalie.bin"

	.align 2
Cry_Plusle:: @ 85DF758
	.incbin "sound/direct_sound_samples/cries/cry_plusle.bin"

	.align 2
Cry_Minun:: @ 85E0054
	.incbin "sound/direct_sound_samples/cries/cry_minun.bin"

	.align 2
Cry_Surskit:: @ 85E105C
	.incbin "sound/direct_sound_samples/cries/cry_surskit.bin"

	.align 2
Cry_Masquerain:: @ 85E1ADC
	.incbin "sound/direct_sound_samples/cries/cry_masquerain.bin"

	.align 2
Cry_Skitty:: @ 85E2E90
	.incbin "sound/direct_sound_samples/cries/cry_skitty.bin"

	.align 2
Cry_Delcatty:: @ 85E35A4
	.incbin "sound/direct_sound_samples/cries/cry_delcatty.bin"

	.align 2
Cry_Gulpin:: @ 85E4ABC
	.incbin "sound/direct_sound_samples/cries/cry_gulpin.bin"

	.align 2
Cry_Swalot:: @ 85E52C0
	.incbin "sound/direct_sound_samples/cries/cry_swalot.bin"

	.align 2
Cry_Numel:: @ 85E6420
	.incbin "sound/direct_sound_samples/cries/cry_numel.bin"

	.align 2
Cry_Camerupt:: @ 85E6D6C
	.incbin "sound/direct_sound_samples/cries/cry_camerupt.bin"

	.align 2
Cry_Barboach:: @ 85E848C
	.incbin "sound/direct_sound_samples/cries/cry_barboach.bin"

	.align 2
Cry_Whiscash:: @ 85E8DC8
	.incbin "sound/direct_sound_samples/cries/cry_whiscash.bin"

	.align 2
Cry_Corphish:: @ 85E9EC4
	.incbin "sound/direct_sound_samples/cries/cry_corphish.bin"

	.align 2
Cry_Crawdaunt:: @ 85EAAC8
	.incbin "sound/direct_sound_samples/cries/cry_crawdaunt.bin"

	.align 2
Cry_Spoink:: @ 85EC380
	.incbin "sound/direct_sound_samples/cries/cry_spoink.bin"

	.align 2
Cry_Grumpig:: @ 85ECAC0
	.incbin "sound/direct_sound_samples/cries/cry_grumpig.bin"

	.align 2
Cry_Trapinch:: @ 85ED760
	.incbin "sound/direct_sound_samples/cries/cry_trapinch.bin"

	.align 2
Cry_Vibrava:: @ 85EE184
	.incbin "sound/direct_sound_samples/cries/cry_vibrava.bin"

	.align 2
Cry_Flygon:: @ 85EEF88
	.incbin "sound/direct_sound_samples/cries/cry_flygon.bin"

	.align 2
Cry_Cacnea:: @ 85F0990
	.incbin "sound/direct_sound_samples/cries/cry_cacnea.bin"

	.align 2
Cry_Cacturne:: @ 85F1280
	.incbin "sound/direct_sound_samples/cries/cry_cacturne.bin"

	.align 2
Cry_Baltoy:: @ 85F2930
	.incbin "sound/direct_sound_samples/cries/cry_baltoy.bin"

	.align 2
Cry_Claydol:: @ 85F35B4
	.incbin "sound/direct_sound_samples/cries/cry_claydol.bin"

	.align 2
Cry_Lunatone:: @ 85F4914
	.incbin "sound/direct_sound_samples/cries/cry_lunatone.bin"

	.align 2
Cry_Solrock:: @ 85F6110
	.incbin "sound/direct_sound_samples/cries/cry_solrock.bin"

	.align 2
Cry_Feebas:: @ 85F713C
	.incbin "sound/direct_sound_samples/cries/cry_feebas.bin"

	.align 2
Cry_Milotic:: @ 85F7910
	.incbin "sound/direct_sound_samples/cries/cry_milotic.bin"

	.align 2
Cry_Absol:: @ 85FA054
	.incbin "sound/direct_sound_samples/cries/cry_absol.bin"

	.align 2
Cry_Meditite:: @ 85FAAD0
	.incbin "sound/direct_sound_samples/cries/cry_meditite.bin"

	.align 2
Cry_Medicham:: @ 85FB2F0
	.incbin "sound/direct_sound_samples/cries/cry_medicham.bin"

	.align 2
Cry_Spheal:: @ 85FC374
	.incbin "sound/direct_sound_samples/cries/cry_spheal.bin"

	.align 2
Cry_Sealeo:: @ 85FC928
	.incbin "sound/direct_sound_samples/cries/cry_sealeo.bin"

	.align 2
Cry_Walrein:: @ 85FD500
	.incbin "sound/direct_sound_samples/cries/cry_walrein.bin"

	.align 2
Cry_Clamperl:: @ 85FF94C
	.incbin "sound/direct_sound_samples/cries/cry_clamperl.bin"

	.align 2
Cry_Huntail:: @ 8600B9C
	.incbin "sound/direct_sound_samples/cries/cry_huntail.bin"

	.align 2
Cry_Gorebyss:: @ 8601B84
	.incbin "sound/direct_sound_samples/cries/cry_gorebyss.bin"

	.align 2
Cry_Lileep:: @ 86031F0
	.incbin "sound/direct_sound_samples/cries/cry_lileep.bin"

	.align 2
Cry_Cradily:: @ 8603B98
	.incbin "sound/direct_sound_samples/cries/cry_cradily.bin"

	.align 2
Cry_Anorith:: @ 86058C8
	.incbin "sound/direct_sound_samples/cries/cry_anorith.bin"

	.align 2
Cry_Armaldo:: @ 8606480
	.incbin "sound/direct_sound_samples/cries/cry_armaldo.bin"

	.align 2
Cry_Beldum:: @ 8607B54
	.incbin "sound/direct_sound_samples/cries/cry_beldum.bin"

	.align 2
Cry_Metang:: @ 86084F4
	.incbin "sound/direct_sound_samples/cries/cry_metang.bin"

	.align 2
Cry_Metagross:: @ 86097C8
	.incbin "sound/direct_sound_samples/cries/cry_metagross.bin"

	.align 2
Cry_Bagon:: @ 860BF40
	.incbin "sound/direct_sound_samples/cries/cry_bagon.bin"

	.align 2
Cry_Shelgon:: @ 860C714
	.incbin "sound/direct_sound_samples/cries/cry_shelgon.bin"

	.align 2
Cry_Regirock:: @ 860DB1C
	.incbin "sound/direct_sound_samples/cries/cry_regirock.bin"

	.align 2
Cry_Regice:: @ 860FAF8
	.incbin "sound/direct_sound_samples/cries/cry_regice.bin"

	.align 2
Cry_Registeel:: @ 8611AF8
	.incbin "sound/direct_sound_samples/cries/cry_registeel.bin"

	.align 2
Cry_Castform:: @ 86131FC
	.incbin "sound/direct_sound_samples/cries/cry_castform.bin"

	.align 2
Cry_Volbeat:: @ 8613E94
	.incbin "sound/direct_sound_samples/cries/cry_volbeat.bin"

	.align 2
Cry_Illumise:: @ 8614A1C
	.incbin "sound/direct_sound_samples/cries/cry_illumise.bin"

	.align 2
Cry_Poochyena:: @ 8615B34
	.incbin "sound/direct_sound_samples/cries/cry_poochyena.bin"

	.align 2
Cry_Mightyena:: @ 861647C
	.incbin "sound/direct_sound_samples/cries/cry_mightyena.bin"

	.align 2
Cry_Dusclops:: @ 8617808
	.incbin "sound/direct_sound_samples/cries/cry_dusclops.bin"

	.align 2
Cry_Sableye:: @ 86185C0
	.incbin "sound/direct_sound_samples/cries/cry_sableye.bin"

	.align 2
Cry_Mawile:: @ 8619164
	.incbin "sound/direct_sound_samples/cries/cry_mawile.bin"

	.align 2
Cry_Aron:: @ 8619CE4
	.incbin "sound/direct_sound_samples/cries/cry_aron.bin"

	.align 2
Cry_Lairon:: @ 861A610
	.incbin "sound/direct_sound_samples/cries/cry_lairon.bin"

	.align 2
Cry_Aggron:: @ 861BAE8
	.incbin "sound/direct_sound_samples/cries/cry_aggron.bin"

	.align 2
Cry_Relicanth:: @ 861D48C
	.incbin "sound/direct_sound_samples/cries/cry_relicanth.bin"

	.align 2
Cry_Luvdisc:: @ 861E8BC
	.incbin "sound/direct_sound_samples/cries/cry_luvdisc.bin"

	.align 2
Cry_Groudon:: @ 861ED98
	.incbin "sound/direct_sound_samples/cries/cry_groudon.bin"

	.align 2
Cry_Kyogre:: @ 86212A4
	.incbin "sound/direct_sound_samples/cries/cry_kyogre.bin"

	.align 2
Cry_Rayquaza:: @ 862365C
	.incbin "sound/direct_sound_samples/cries/cry_rayquaza.bin"

	.align 2
Cry_Salamence:: @ 8625388
	.incbin "sound/direct_sound_samples/cries/cry_salamence.bin"

	.align 2
Cry_Breloom:: @ 8626CA4
	.incbin "sound/direct_sound_samples/cries/cry_breloom.bin"

	.align 2
Cry_Shroomish:: @ 8627964
	.incbin "sound/direct_sound_samples/cries/cry_shroomish.bin"

	.align 2
Cry_Linoone:: @ 862823C
	.incbin "sound/direct_sound_samples/cries/cry_linoone.bin"

	.align 2
Cry_Tropius:: @ 862A0D8
	.incbin "sound/direct_sound_samples/cries/cry_tropius.bin"

	.align 2
Cry_Wailmer:: @ 862C19C
	.incbin "sound/direct_sound_samples/cries/cry_wailmer.bin"

	.align 2
Cry_Zigzagoon:: @ 862DDFC
	.incbin "sound/direct_sound_samples/cries/cry_zigzagoon.bin"

	.align 2
Cry_Exploud:: @ 862E98C
	.incbin "sound/direct_sound_samples/cries/cry_exploud.bin"

	.align 2
Cry_Loudred:: @ 86305D4
	.incbin "sound/direct_sound_samples/cries/cry_loudred.bin"

	.align 2
Cry_Wailord:: @ 86312FC
	.incbin "sound/direct_sound_samples/cries/cry_wailord.bin"

	.align 2
Cry_Whismur:: @ 8633D0C
	.incbin "sound/direct_sound_samples/cries/cry_whismur.bin"

	.align 2
Cry_Snorunt:: @ 8634530
	.incbin "sound/direct_sound_samples/cries/cry_snorunt.bin"

	.align 2
Cry_Latios:: @ 8635638
	.incbin "sound/direct_sound_samples/cries/cry_latios.bin"

	.align 2
Cry_Jirachi:: @ 8636C30
	.incbin "sound/direct_sound_samples/cries/cry_jirachi.bin"

	.align 2
Cry_Deoxys:: @ 86379B4
	.incbin "sound/direct_sound_samples/cries/cry_deoxys.bin"

	.align 2
Cry_Chimecho:: @ 8638E88
	.incbin "sound/direct_sound_samples/cries/cry_chimecho.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel7:: @ 8639898
	.incbin "sound/direct_sound_samples/phonemes/vowel_7.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel8:: @ 8639EF8
	.incbin "sound/direct_sound_samples/phonemes/vowel_8.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel9:: @ 863A3DC
	.incbin "sound/direct_sound_samples/phonemes/vowel_9.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel10:: @ 863AD2C
	.incbin "sound/direct_sound_samples/phonemes/vowel_10.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel11:: @ 863B79C
	.incbin "sound/direct_sound_samples/phonemes/vowel_11.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel12:: @ 863BABC
	.incbin "sound/direct_sound_samples/phonemes/vowel_12.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel13:: @ 863C744
	.incbin "sound/direct_sound_samples/phonemes/vowel_13.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel14:: @ 863CD64
	.incbin "sound/direct_sound_samples/phonemes/vowel_14.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel15:: @ 863D0EC
	.incbin "sound/direct_sound_samples/phonemes/vowel_15.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel16:: @ 863DED0
	.incbin "sound/direct_sound_samples/phonemes/vowel_16.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel17:: @ 863E840
	.incbin "sound/direct_sound_samples/phonemes/vowel_17.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel18:: @ 863EBDC
	.incbin "sound/direct_sound_samples/phonemes/vowel_18.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel19:: @ 863F390
	.incbin "sound/direct_sound_samples/phonemes/vowel_19.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel20:: @ 86400EC
	.incbin "sound/direct_sound_samples/phonemes/vowel_20.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel21:: @ 8640330
	.incbin "sound/direct_sound_samples/phonemes/vowel_21.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel22:: @ 8641170
	.incbin "sound/direct_sound_samples/phonemes/vowel_22.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel23:: @ 8641AC4
	.incbin "sound/direct_sound_samples/phonemes/vowel_23.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel24:: @ 8641E18
	.incbin "sound/direct_sound_samples/phonemes/vowel_24.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel25:: @ 864244C
	.incbin "sound/direct_sound_samples/phonemes/vowel_25.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel26:: @ 86430B8
	.incbin "sound/direct_sound_samples/phonemes/vowel_26.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel27:: @ 8643650
	.incbin "sound/direct_sound_samples/phonemes/vowel_27.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel28:: @ 8644154
	.incbin "sound/direct_sound_samples/phonemes/vowel_28.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel29:: @ 8644758
	.incbin "sound/direct_sound_samples/phonemes/vowel_29.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel30:: @ 8644950
	.incbin "sound/direct_sound_samples/phonemes/vowel_30.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel31:: @ 86452B4
	.incbin "sound/direct_sound_samples/phonemes/vowel_31.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel32:: @ 8646240
	.incbin "sound/direct_sound_samples/phonemes/vowel_32.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel33:: @ 8646878
	.incbin "sound/direct_sound_samples/phonemes/vowel_33.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel34:: @ 864734C
	.incbin "sound/direct_sound_samples/phonemes/vowel_34.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel35:: @ 8648290
	.incbin "sound/direct_sound_samples/phonemes/vowel_35.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel36:: @ 8648808
	.incbin "sound/direct_sound_samples/phonemes/vowel_36.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel37:: @ 8649654
	.incbin "sound/direct_sound_samples/phonemes/vowel_37.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel38:: @ 864A55C
	.incbin "sound/direct_sound_samples/phonemes/vowel_38.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel39:: @ 864B030
	.incbin "sound/direct_sound_samples/phonemes/vowel_39.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel40:: @ 864BBC4
	.incbin "sound/direct_sound_samples/phonemes/vowel_40.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel41:: @ 864C59C
	.incbin "sound/direct_sound_samples/phonemes/vowel_41.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel42:: @ 864CBDC
	.incbin "sound/direct_sound_samples/phonemes/vowel_42.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel43:: @ 864D6BC
	.incbin "sound/direct_sound_samples/phonemes/vowel_43.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel44:: @ 864DCF8
	.incbin "sound/direct_sound_samples/phonemes/vowel_44.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel45:: @ 864E410
	.incbin "sound/direct_sound_samples/phonemes/vowel_45.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel46:: @ 864ED4C
	.incbin "sound/direct_sound_samples/phonemes/vowel_46.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel47:: @ 864F508
	.incbin "sound/direct_sound_samples/phonemes/vowel_47.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel48:: @ 864FA6C
	.incbin "sound/direct_sound_samples/phonemes/vowel_48.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel49:: @ 86507E0
	.incbin "sound/direct_sound_samples/phonemes/vowel_49.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel50:: @ 8650C5C
	.incbin "sound/direct_sound_samples/phonemes/vowel_50.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel51:: @ 8651148
	.incbin "sound/direct_sound_samples/phonemes/vowel_51.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel52:: @ 8651910
	.incbin "sound/direct_sound_samples/phonemes/vowel_52.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel53:: @ 865250C
	.incbin "sound/direct_sound_samples/phonemes/vowel_53.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel54:: @ 8652884
	.incbin "sound/direct_sound_samples/phonemes/vowel_54.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel55:: @ 8653040
	.incbin "sound/direct_sound_samples/phonemes/vowel_55.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel56:: @ 8653CA4
	.incbin "sound/direct_sound_samples/phonemes/vowel_56.bin"

	.align 2
DirectSoundWaveData_Phoneme_Vowel57:: @ 8654170
	.incbin "sound/direct_sound_samples/phonemes/vowel_57.bin"

	.align 2
DirectSoundWaveData_SC88_AccordionFr_Copy:: @ 8654C20
	.incbin "sound/direct_sound_samples/synth/sc88_22_accordion_fr.bin"
