Route110_TrickHousePuzzle3_Text_JustinIntro:: @ 819CF76
	.string "I keep coming back to this same place!$"

Route110_TrickHousePuzzle3_Text_JustinDefeat:: @ 819CF9D
	.string "I'm already having trouble, and then\n"
	.string "you have to beat me? It's not fair!$"

Route110_TrickHousePuzzle3_Text_JustinPostBattle:: @ 819CFE6
	.string "It's full of doors here!\n"
	.string "It's too small and dark in here! Help!$"

Route110_TrickHousePuzzle3_Text_MarthaIntro:: @ 819D026
	.string "I don't know what's going on here.\n"
	.string "I'm starting to feel sad...$"

Route110_TrickHousePuzzle3_Text_MarthaDefeat:: @ 819D065
	.string "You... You're awful!$"

Route110_TrickHousePuzzle3_Text_MarthaPostBattle:: @ 819D07A
	.string "I know I'm weak!\n"
	.string "And, I have no sense of direction!$"

Route110_TrickHousePuzzle3_Text_AlanIntro:: @ 819D0AE
	.string "I don't get it. What would anyone want\n"
	.string "with a house this bizarre?$"

Route110_TrickHousePuzzle3_Text_AlanDefeat:: @ 819D0F0
	.string "I don't get it.\n"
	.string "How did I lose?$"

Route110_TrickHousePuzzle3_Text_AlanPostBattle:: @ 819D110
	.string "I don't get it.\n"
	.string "How many traps are in this house?\p"
	.string "You may be the one to solve that.$"

Route110_TrickHousePuzzle3_Text_WroteSecretCodeLockOpened: @ 819D164
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is cool.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "The lock clicked open!$"
