LilycoveCity_CoveLilyMotel_1F_Text_186B71:: @ 8186B71
	.string "Hm, so haben sie also die Anzahl der\n"
	.string "Gäste verdoppelt. Indem sie POKéMON\l"
	.string "als Attraktion präsentieren?\p"
	.string "Hm, vielleicht sollte ich ein niedliches\n"
	.string "POKéMON zum Maskottchen meines\l"
	.string "Gasthofes machen...\p"
	.string "Ich frage mich, ob ich so mehr\n"
	.string "Gäste hätte?$"

LilycoveCity_CoveLilyMotel_1F_Text_186C2B:: @ 8186C2B
	.string "Oh, tut mir Leid, tut mir Leid!\n"
	.string "Ich habe so konzentriert ferngesehen!\p"
	.string "Seit TEAM {EVIL_TEAM} in diesem Ort ist,\n"
	.string "bleiben die Gäste aus.$"

LilycoveCity_CoveLilyMotel_1F_Text_186CA6:: @ 8186CA6
	.string "Hey, geh weg da!\n"
	.string "Du bist doch nicht aus Glas!$"

LilycoveCity_CoveLilyMotel_1F_Text_186CCE:: @ 8186CCE
	.string "Interessant! Du sagst, ein POKéMON\n"
	.string "hat ein Item gefunden, das jemand ver-\l"
	.string "loren hat?\p"
	.string "Das ist ja was! Wenn wir auch so clevere\n"
	.string "POKéMON hätten...\p"
	.string "Dann könnten wir alles wiederfinden, was\n"
	.string "unsere Gäste verloren haben.$"

LilycoveCity_CoveLilyMotel_1F_Text_186D7F:: @ 8186D7F
	.string "Oh, tut mir Leid, tut mir Leid!\n"
	.string "Ich habe so konzentriert ferngesehen!\p"
	.string "Ich habe gehört, dass jemand das VER-\n"
	.string "STECK von TEAM {EVIL_TEAM} auffliegen ließ.\p"
	.string "Gut! Dadurch haben wir endlich Gäste.\n"
	.string "Eine ganze Gruppe hat reserviert!\p"
	.string "Das sind Angestellte einer Firma... Äh...\n"
	.string "GAME irgendwas...$"

LilycoveCity_CoveLilyMotel_1F_Text_186E57:: @ 8186E57
	.string "Irre! Ein POKéMON, das das Haus be-\n"
	.string "wachte, hat Einbrecher geschnappt?\p"
	.string "Klasse! Wir sollten auch über einen\n"
	.string "Wachschutz durch POKéMON nachdenken.\p"
	.string "Dadurch könnten wir unseren Gästen\n"
	.string "viel mehr Sicherheit bieten.$"

LilycoveCity_CoveLilyMotel_1F_Text_186F09:: @ 8186F09
	.string "Oh, tut mir Leid, tut mir Leid!\n"
	.string "Ich habe so konzentriert ferngesehen!\p"
	.string "Oh, ja. Eine große Gruppe von Gästen\n"
	.string "ist vor kurzem hier eingetroffen.\p"
	.string "Sie haben sich als GAME FREAK einge-\n"
	.string "tragen. Ich denke, sie entwickeln\l"
	.string "Spiele.\p"
	.string "Oh oh, ich sollte mich besser um ihr\n"
	.string "Abendessen kümmern!$"
