AbandonedShip_Corridors_B1F_Text_DuncanIntro::
	.string "Wenn wir zur See fahren, nehmen wir\n"
	.string "MATROSEN immer unsere POKéMON mit.\l"
	.string "Wie wäre es mit einem schnellen Kampf?$"

AbandonedShip_Corridors_B1F_Text_DuncanDefeat::
	.string "Huups, da bin ich abgesoffen.$"

AbandonedShip_Corridors_B1F_Text_DuncanPostBattle::
	.string "Der Schiffsrumpf liegt tief unter der\n"
	.string "Wasserlinie.\p"
	.string "Wenn ein POKéMON wissen würde, wie\n"
	.string "man taucht, würden wir Fortschritte\l"
	.string "machen.$"

AbandonedShip_Corridors_B1F_Text_YayItsAShip::
	.string "Jahaa!\n"
	.string "Ein Schiff!$"

AbandonedShip_Corridors_B1F_Text_DoorIsLocked::
	.string "Die Tür ist verschlossen.\p"
	.string "“LAGER” steht auf dem Schild.$"

AbandonedShip_Corridors_B1F_Text_InsertedStorageKey::
	.string "{PLAYER} steckt den SCHLÜSSEL zum\n"
	.string "LAGER ins Schlüsselloch und dreht ihn.\p"
	.string "Der SCHLÜSSEL ist schwergängig, aber\n"
	.string "das Schloss lässt sich öffnen.$"

AbandonedShip_Text_TheDoorIsOpen::
	.string "Die Tür ist offen.$"
