### Stub Makefile to protect IDE configurations ###

$(error Your environment is not setup correctly if this is being executed. Please remember to navigate up one folder and call the correct Makefile to compile pokeruby.)
