AbandonedShip_Corridors_B1F_Text_19856F:: @ 819856F
	.string "Wenn wir zur See fahren, nehmen wir\n"
	.string "MATROSEN immer unsere POKéMON mit.\l"
	.string "Wie wäre es mit einem schnellen Kampf?$"

AbandonedShip_Corridors_B1F_Text_1985C5:: @ 81985C5
	.string "Huups, da bin ich abgesoffen.$"

AbandonedShip_Corridors_B1F_Text_1985D7:: @ 81985D7
	.string "Der Schiffsrumpf liegt tief unter der\n"
	.string "Wasserlinie.\p"
	.string "Wenn ein POKéMON wissen würde, wie\n"
	.string "man taucht, würden wir Fortschritte\l"
	.string "machen.$"

AbandonedShip_Corridors_B1F_Text_19864A:: @ 819864A
	.string "Jahaa!\n"
	.string "Ein Schiff!$"

AbandonedShip_Corridors_B1F_Text_19865C:: @ 819865C
	.string "Die Tür ist verschlossen.\p"
	.string "“LAGER” steht auf dem Schild.$"

AbandonedShip_Corridors_B1F_Text_198692:: @ 8198692
	.string "{PLAYER} steckt den SCHLÜSSEL zum\n"
	.string "LAGER ins Schlüsselloch und dreht ihn.\p"
	.string "Der SCHLÜSSEL ist schwergängig, aber\n"
	.string "das Schloss lässt sich öffnen.$"
