AbandonedShip_Rooms2_1F_Text_1987C1:: @ 81987C1
	.string "PIT: Wir haben nach Schätzen gesucht\n"
	.string "- und einen TRAINER gefunden!$"

AbandonedShip_Rooms2_1F_Text_1987FE:: @ 81987FE
	.string "PIT: Wir konnten nicht gewinnen, obwohl\n"
	.string "wir zusammengearbeitet haben...$"

AbandonedShip_Rooms2_1F_Text_198835:: @ 8198835
	.string "PIT: Wir konnten keine Schätze finden.\n"
	.string "Ob uns jemand zuvorgekommen ist?$"

AbandonedShip_Rooms2_1F_Text_19887F:: @ 819887F
	.string "PIT: Du hast keine zwei POKéMON.\n"
	.string "So kannst du nicht gegen uns antreten.$"

AbandonedShip_Rooms2_1F_Text_1988CC:: @ 81988CC
	.string "GESA: Oh? Wir haben nach Schätzen\n"
	.string "gesucht und einen TRAINER gefunden.$"

AbandonedShip_Rooms2_1F_Text_198916:: @ 8198916
	.string "GESA: Oh, wow, bist du stark!$"

AbandonedShip_Rooms2_1F_Text_198934:: @ 8198934
	.string "GESA: Ich frage mich, wo die Schätze\n"
	.string "versteckt sind...\p"
	.string "Ich weiß, was ich mir alles kaufen\n"
	.string "würde, wenn ich reich wäre...$"

AbandonedShip_Rooms2_1F_Text_19899A:: @ 819899A
	.string "GESA: Hast du keine zwei POKéMON?\n"
	.string "Dann können wir jetzt nicht kämpfen.$"

AbandonedShip_Rooms2_1F_Text_1989DF:: @ 81989DF
	.string "PIT: Wir haben die ganze Zeit nur nach\n"
	.string "Schätzen gesucht.\p"
	.string "Aber unsere POKéMON sind auch stärker\n"
	.string "geworden. Dürfen wir dir das zeigen?$"

AbandonedShip_Rooms2_1F_Text_198A53:: @ 8198A53
	.string "PIT: Du bist stark wie immer.$"

AbandonedShip_Rooms2_1F_Text_198A70:: @ 8198A70
	.string "PIT: Wir haben keine Schätze gefunden,\n"
	.string "sondern gegen POKéMON verloren...\p"
	.string "Ich will nach Hause... Aber wenn ich das\n"
	.string "laut sage, wird sie sauer auf mich.$"

AbandonedShip_Rooms2_1F_Text_198AEE:: @ 8198AEE
	.string "PIT: Du hast keine zwei POKéMON.\n"
	.string "So können wir nicht kämpfen.$"

AbandonedShip_Rooms2_1F_Text_198B3B:: @ 8198B3B
	.string "GESA: Oh, da bist du ja wieder!\p"
	.string "Genau wie wir, hast du die Suche nach\n"
	.string "Schätzen auch nicht aufgegeben, was?\p"
	.string "Wie wäre es mit einem Kampf? Und der\n"
	.string "Verlierer gibt die Suche auf?$"

AbandonedShip_Rooms2_1F_Text_198BCF:: @ 8198BCF
	.string "GESA: Ach, wir haben wieder verloren...$"

AbandonedShip_Rooms2_1F_Text_198BEA:: @ 8198BEA
	.string "GESA: Wir müssen unsere POKéMON mehr\n"
	.string "trainieren.\p"
	.string "Wir gehen nicht ohne Schatz nach Hause!$"

AbandonedShip_Rooms2_1F_Text_198C40:: @ 8198C40
	.string "GESA: Hast du keine zwei POKéMON?\n"
	.string "Dann müssen wir später kämpfen.$"
