BattleTower_Outside_Text_199C6F:: @ 8199C6F
	.string "DUELLTURM\n"
	.string "“Besiege alle und werde der beste\l"
	.string "TRAINER!”$"

BattleTower_Outside_Text_199CA4:: @ 8199CA4
	.string "Dies ist der DUELLTURM.\p"
	.string "TRAINER tragen mit ihren besten\n"
	.string "POKéMON Ausscheidungskämpfe aus.$"

BattleTower_Outside_Text_199D06:: @ 8199D06
	.string "Hallo! Möchtest du mit der Fähre fahren?\n"
	.string "Darf ich bitte dein TICKET sehen?$"

BattleTower_Outside_Text_199D40:: @ 8199D40
	.string "{PLAYER} hat kein TICKET...\p"
	.string "Es tut mir schrecklich Leid.\p"
	.string "Du brauchst ein TICKET, um mit der\n"
	.string "Fähre fahren zu dürfen.$"

BattleTower_Outside_Text_199D9D:: @ 8199D9D
	.string "{PLAYER} zeigt das TICKET.\p"
	.string "Wunderbar! Das ist gut!\p"
	.string "Und wohin möchtest du reisen?$"

BattleTower_Outside_Text_199DF2:: @ 8199DF2
	.string "Also nach GRAPHITPORT CITY, richtig?$"

BattleTower_Outside_Text_199E0E:: @ 8199E0E
	.string "Also nach SEEGRASULB CITY, richtig?$"

BattleTower_Outside_Text_199E29:: @ 8199E29
	.string "Bitte beehre uns bald wieder!$"

BattleTower_Outside_Text_199E4B:: @ 8199E4B
	.string "Bitte geh auf die Fähre. Wir legen in\n"
	.string "Kürze ab.$"

BattleTower_Outside_Text_199E7A:: @ 8199E7A
	.string "Und? Wo soll die Reise hingehen?$"

BattleTower_Outside_Text_199E9C:: @ 8199E9C
	.string "Ich gehe nicht eher hier weg, bis ich 35\n"
	.string "TRAINER in Folge besiegt habe!$"

BattleTower_Outside_Text_199ED4:: @ 8199ED4
	.string "Hui, sind das aber viele stark\n"
	.string "aussehende TRAINER... Ich bin\l"
	.string "nicht gut genug, hier anzutreten...$"
