DewfordTown_PokemonCenter_1F_Text_174CDB:: @ 8174CDB
	.string "Am Rande des Ortes befindet sich eine\n"
	.string "steinerne Höhle.\p"
	.string "Dort soll man seltene Steine finden\n"
	.string "können.$"

DewfordTown_PokemonCenter_1F_Text_174D32:: @ 8174D32
	.string "Auch wenn in deinem Team ein kampf-\n"
	.string "unfähiges POKéMON ist, kann es außer-\p"
	.string "halb des Kampfes eine Versteckte\n"
	.string "Maschine, eine VM, anwenden.$"
