DewfordTown_House2_Text_175EFE:: @ 8175EFE
	.string "Wirf dein Auge mal hierauf!\p"
	.string "Das ist ein SEIDENSCHAL. Das ist\n"
	.string "der letzte Schrei in der Mode. Yeah!\p"
	.string "Oh, deine Augen blitzen.\n"
	.string "Du magst meinen Stil, nicht wahr?\p"
	.string "Hihi, du machst mir eine Freude!\n"
	.string "Hier, das möchte ich dir schenken!$"

DewfordTown_House2_Text_175FDA:: @ 8175FDA
	.string "Och, du hast ja gar keinen Platz mehr.\p"
	.string "Nun, hör gut zu... Diesen SCHAL musst\n"
	.string "du einfach haben! Ich würde alle meine\l"
	.string "Items verkaufen, um ihn zu bekommen!$"

DewfordTown_House2_Text_176055:: @ 8176055
	.string "Dieser SEIDENSCHAL steigert die Stärke\n"
	.string "der NORMALEN Attacken.\p"
	.string "Dieser wunderbare SCHAL passt einfach\n"
	.string "zu fast allen POKéMON!$"

DewfordTown_House2_Text_1760C8:: @ 81760C8
	.string "Wow, du hast die beschwerliche Reise\n"
	.string "über das Meer auf dich genommen, um\l"
	.string "nach FAUSTAUHAVEN zu gelangen?\p"
	.string "Bist du hier, weil du von KAMILLO\n"
	.string "gehört hast?\p"
	.string "Er ist sooo cool...\n"
	.string "Er ist ein Idol für jeden!$"
