EverGrandeCity_PhoebesRoom_Text_1908F5:: @ 81908F5
	.string "Ahahahahaha!\p"
	.string "Ich bin ANTONIA von den TOP VIER.\n"
	.string "Ich habe am PYROBERG trainiert.\p"
	.string "Während des Trainings habe ich die\n"
	.string "Fähigkeit erworben, mit GEIST-POKéMON\l"
	.string "zu kommunizieren.\p"
	.string "In der Tat ist das Band zwischen mir und\n"
	.string "den POKéMON sehr stark.\p"
	.string "Komm und schau, ob du irgendetwas\n"
	.string "gegen meine POKéMON ausrichten kannst.$"

EverGrandeCity_PhoebesRoom_Text_190A0C:: @ 8190A0C
	.string "Oh, verdammt.\n"
	.string "Aus und vorbei. Verloren.$"

EverGrandeCity_PhoebesRoom_Text_190A2A:: @ 8190A2A
	.string "Das Band zwischen dir und deinen\n"
	.string "POKéMON ist ebenfalls sehr stark.\p"
	.string "Das habe ich gar nicht bemerkt, daher\n"
	.string "konnte ich nur verlieren.\p"
	.string "Ja, jetzt möchte ich sehen, wie weit\n"
	.string "dieses Band euch bringt.\p"
	.string "Geh und betrete den nächsten Raum.$"
