LavaridgeTown_Gym_1F_Text_176312:: @ 8176312
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "Die ARENALEITERIN von BAD LAVA-\n"
	.string "STADT, FLAVIA, setzt FEUER-POKéMON\l"
	.string "ein.\p"
	.string "Ihre Leidenschaft für POKéMON brennt\n"
	.string "heißer und stärker als ein Vulkan.\p"
	.string "Komm ihr nicht zu nahe - du verbrennst\n"
	.string "dich! Lösche die Glut mit Wasser und\l"
	.string "dann besiege sie!$"

LavaridgeTown_Gym_1F_Text_17640C:: @ 817640C
	.string "Hui! Das war ein glühend heißer Kampf!$"

LavaridgeTown_Gym_1F_Text_176432:: @ 8176432
	.string "Auauauauau!\n"
	.string "Hach, ist das heiß!$"

LavaridgeTown_Gym_1F_Text_17644F:: @ 817644F
	.string "Der Schweiß lief mir in die Augen...$"

LavaridgeTown_Gym_1F_Text_176472:: @ 8176472
	.string "Ein Bad im heißen Sand regt den\n"
	.string "Kreislauf an.\p"
	.string "Auch Gelenkschmerzen lassen sich damit\n"
	.string "kurieren.$"

LavaridgeTown_Gym_1F_Text_1764D1:: @ 81764D1
	.string "Ich versuche, Stress abzubauen.\n"
	.string "Komm her. Ich will mich abreagieren.$"

LavaridgeTown_Gym_1F_Text_176516:: @ 8176516
	.string "Ich hoffe, FLAVIA wird dich rösten!$"

LavaridgeTown_Gym_1F_Text_176537:: @ 8176537
	.string "Haaah... Huuuuh...\p"
	.string "Bleibt man zu lange im heißen Sand,\n"
	.string "macht einen das ganz schön fertig.$"

LavaridgeTown_Gym_1F_Text_17658D:: @ 817658D
	.string "Du musst ganz schön müde sein.\n"
	.string "Willst du dich nicht hier im heißen\l"
	.string "Sand ausruhen?\p"
	.string "Aber du solltest wissen, dass\n"
	.string "Willenskraft ganz wichtig für einen\l"
	.string "TRAINER ist.$"

LavaridgeTown_Gym_1F_Text_17663F:: @ 817663F
	.string "Spiele mit Feuer und du verbrennst dich.$"

LavaridgeTown_Gym_1F_Text_176660:: @ 8176660
	.string "Dein Können ist gut... Aber unsere\n"
	.string "LEITERIN FLAVIA ist stark.\p"
	.string "Wenn du nicht aufpasst, verbrennst\n"
	.string "du dich ernsthaft.$"

LavaridgeTown_Gym_1F_Text_1766D2:: @ 81766D2
	.string "Kann dein POKéMON 200 Grad aushalten?$"

LavaridgeTown_Gym_1F_Text_1766FE:: @ 81766FE
	.string "Die Hitze war nicht stark genug...$"

LavaridgeTown_Gym_1F_Text_17671D:: @ 817671D
	.string "Die Temperatur von Magma beträgt\n"
	.string "über 200 Grad.\p"
	.string "Deine POKéMON haben mich besiegt, sie\n"
	.string "sollten auch in Magma überleben können.$"

LavaridgeTown_Gym_1F_Text_176784:: @ 8176784
	.string "Ähm...\n"
	.string "Okay, ich kämpfe mit dir.$"

LavaridgeTown_Gym_1F_Text_1767A6:: @ 81767A6
	.string "Oh, du bist zu stark.$"

LavaridgeTown_Gym_1F_Text_1767C1:: @ 81767C1
	.string "Ich will einmal so eine starke TRAINERIN\n"
	.string "werden wie FLAVIA.$"

LavaridgeTown_Gym_1F_Text_176801:: @ 8176801
	.string "Willkommen... Halt, warte!\p"
	.string "Hallo, du Winzling von TRAINER, wie\n"
	.string "schön, dich hier zu sehen!\p"
	.string "Ich bin verantwortlich für, äh...\n"
	.string "Nein, warte.\p"
	.string "Ich bin FLAVIA und ich bin die ARENA-\n"
	.string "LEITERIN hier!\p"
	.string "Äh... Du solltest mich nicht\n"
	.string "unterschätzen, nur weil ich noch nicht\l"
	.string "so lange LEITERIN bin!\p"
	.string "Ich habe das Talent meines Großvaters\n"
	.string "geerbt und daher... äh... kann ich dir die\l"
	.string "heißen Attacken zeigen, die wir hier\l"
	.string "entwickelt haben!$"

LavaridgeTown_Gym_1F_Text_176960:: @ 8176960
	.string "Äh...\n"
	.string "Ich glaube, ich habe es übertrieben...\p"
	.string "Ich... Ich bin ja auch noch nicht lange\n"
	.string "ARENALEITERIN!\p"
	.string "Ich habe zu sehr versucht, jemand zu\n"
	.string "sein, der ich gar nicht bin.\p"
	.string "Ich muss die Dinge auf meine eigene Art\n"
	.string "angehen. Sonst verwirre ich nur meine\l"
	.string "POKéMON.\p"
	.string "Danke, dass du mich das gelehrt hast!\n"
	.string "Du hast dir das hier wohl verdient!$"

LavaridgeTown_Gym_1F_Text_176A62:: @ 8176A62
	.string "{PLAYER} erhält den HITZEORDEN\n"
	.string "von FLAVIA.$"

LavaridgeTown_Gym_1F_Text_176A8C:: @ 8176A8C
	.string "Mit dem HITZEORDEN gehorchen dir alle\n"
	.string "POKéMON bis Level 50, auch die, die du\l"
	.string "durch Tausch erhalten hast.\p"
	.string "Und du kannst ab sofort STÄRKE auch\n"
	.string "außerhalb eines Kampfes einsetzen.\p"
	.string "Dies ist das Zeichen meiner\n"
	.string "Anerkennung. Nimm es ruhig an!$"

LavaridgeTown_Gym_1F_Text_176B8F:: @ 8176B8F
	.string "Die TM50 enthält HITZEKOLLER.\p"
	.string "Diese Attacke richtet beim Gegner\n"
	.string "großen Schaden an.\p"
	.string "Aber gleichzeitig wird der SP. ANG.\n"
	.string "des POKéMON, das die Attacke\p"
	.string "anwendet, herabgesetzt. Für längere\n"
	.string "Kämpfe ist sie daher nicht geeignet.$"

LavaridgeTown_Gym_1F_Text_176C4A:: @ 8176C4A
	.string "Deine Stärke erinnert mich an\n"
	.string "jemanden...\p"
	.string "Jetzt weiß ich’s! Du kämpfst wie NORMAN,\n"
	.string "der ARENALEITER von BLÜTENBURG CITY.$"

LavaridgeTown_Gym_1F_Text_176CAF:: @ 8176CAF
	.string "POKéMON ARENA von BAD LAVASTADT$"

LavaridgeTown_Gym_1F_Text_176CCA:: @ 8176CCA
	.string "POKéMON ARENA von BAD LAVASTADT\p"
	.string "FLAVIAS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
