LavaridgeTown_Text_16BDA4:: @ 816BDA4
	.string "MAIKE: {PLAYER}{KUN}! Wir haben uns lange\n"
	.string "nicht gesehen!\p"
	.string "Oh? Als ich die Heißen Quellen aufge-\n"
	.string "sucht habe, habe ich den ORDEN der\p"
	.string "ARENA von BAD LAVASTADT erhalten.\n"
	.string "Du hast anscheinend viele POKéMON\p"
	.string "gefangen... Äh, ich meine, du hast ja\n"
	.string "schon einige POKéMON aufgezogen. \p"
	.string "Ich denke, das hier wirst du gut\n"
	.string "gebrauchen können.$"

LavaridgeTown_Text_16BE7D:: @ 816BE7D
	.string "MAIKE: Mit diesem WÜSTENGLAS wirst du\n"
	.string "keine Probleme haben, durch die Wüste in\l"
	.string "der Nähe von ROUTE 111 zu gehen.\p"
	.string "Aber, wow, {PLAYER}{KUN}...\n"
	.string "In ARENEN antreten...\p"
	.string "Du strengst dich bestimmt sehr an, weil\n"
	.string "du nicht gegen mich verlieren willst!\p"
	.string "{PLAYER}{KUN}, ich glaube, ich sollte deinen\n"
	.string "Vater in der ARENA von BLÜTENBURG\l"
	.string "CITY herausfordern.\p"
	.string "{PLAYER}{KUN}, man sieht sich!$"

LavaridgeTown_Text_16BF92:: @ 816BF92
	.string "BRIX: {PLAYER}, wie geht es dir?\p"
	.string "Hmm... Das ist eine beachtliche\n"
	.string "Sammlung von ORDEN.\p"
	.string "Also gut.\n"
	.string "Hier, dies schenke ich dir.$"

LavaridgeTown_Text_16C020:: @ 816C020
	.string "BRIX: Nimm das mit, wenn du in die\n"
	.string "Wüste in der Nähe von ROUTE 111 willst.\p"
	.string "Da sollten sich einige POKéMON fangen\n"
	.string "lassen, die Wüstenbewohner sind. Schau\l"
	.string "dich nach ihnen um.\p"
	.string "Und ich...\n"
	.string "Ich werde wohl NORMAN, den ARENALEITER\l"
	.string "in BLÜTENBURG CITY herausfordern.\p"
	.string "Im Gegensatz zu dir, macht dein Vater\n"
	.string "einen sehr starken Eindruck.\p"
	.string "Man sieht sich!$"

LavaridgeTown_Text_16C174:: @ 816C174
	.string "Ich habe hier ein EI.\p"
	.string "Ich dachte, ich könnte es ausbrüten,\n"
	.string "indem ich es in den heißen Sand bei den\p"
	.string "Heißen Quellen vergrabe. Aber das reicht\n"
	.string "offensichtlich nicht aus.\p"
	.string "Jemand erzählte mir, dass man es\n"
	.string "zusammen mit den POKéMON tragen\l"
	.string "soll.\p"
	.string "Du bist ein TRAINER, nicht wahr? Und\n"
	.string "deine POKéMON strahlen Vitalität aus.\p"
	.string "So, was meinst du? Wirst du das EI mit-\n"
	.string "nehmen und zum Ausschlüpfen bringen?$"

LavaridgeTown_Text_16C2B6:: @ 816C2B6
	.string "Gut! Ich hoffe, du hast mehr Glück\n"
	.string "mit diesem EI!$"

LavaridgeTown_Text_16C2EA:: @ 816C2EA
	.string "{PLAYER} erhält ein EI.$"

LavaridgeTown_Text_16C2FF:: @ 816C2FF
	.string "Oh! Du hast zu viele POKéMON dabei.\n"
	.string "Du hast keinen Platz für das EI...$"

LavaridgeTown_Text_16C33C:: @ 816C33C
	.string "Ganz, wie du willst...\p"
	.string "Wenn dein Herz sich anders entscheidet\n"
	.string "und das EI haben möchte, ich bin hier.$"

LavaridgeTown_Text_16C398:: @ 816C398
	.string "Von Zeit zu Zeit findet man in der\n"
	.string "PENSION ein EI.\p"
	.string "So zumindest erzählt man es sich.$"

LavaridgeTown_Text_16C3FD:: @ 816C3FD
	.string "Wir nehmen uns so viel heißes Wasser,\n"
	.string "wie wir brauchen, und trotzdem trocknen\l"
	.string "die Heißen Quellen nicht aus.\p"
	.string "Ist das nicht schon fast Magie?\p"
	.string "Diese Heißen Quellen bilden sich in der\n"
	.string "Nähe von aktiven Vulkanen. Wasseradern\l"
	.string "im Boden werden durch das Magma\l"
	.string "erhitzt und kommen als heiße Quellen\l"
	.string "an die Erdoberfläche.$"

LavaridgeTown_Text_16C4DB:: @ 816C4DB
	.string "Hier im heißen Sand vergraben zu sein,\n"
	.string "ist...  Seufz...\p"
	.string "So warm und einfach himmlisch... Seufz...\p"
	.string "Äh? Gyaah! Aua!\p"
	.string "Ein POKéMON hat meinen Rücken ange-\n"
	.string "knabbert!$"

LavaridgeTown_Text_16C54E:: @ 816C54E
	.string "Ach, du magst auch heiße Quellen?\p"
	.string "Das ist überraschend bei einem so\n"
	.string "jungen Menschen wie dir.$"

LavaridgeTown_Text_16C59B:: @ 816C59B
	.string "Ich bade jeden Tag in den\n"
	.string "Heißen Quellen.\p"
	.string "Ich will ein wunderschöner und starker\n"
	.string "ARENALEITER wie FLAVIA werden.$"

LavaridgeTown_Text_16C603:: @ 816C603
	.string "Wenn Leute ihre POKéMON in die Heißen\n"
	.string "Quellen setzen, ist das schon\l"
	.string "merkwürdig.\p"
	.string "Nun, es könnte auch ein Bad in\n"
	.string "Elektrizität, ein Schaumbad oder sogar\l"
	.string "ein Bad in Lava sein...$"

LavaridgeTown_Text_16C694:: @ 816C694
	.string "Man sagt, diese Heißen Quellen seien gut\n"
	.string "gegen nervöse Anspannungen, gegen\l"
	.string "Muskelkrämpfe, sie sollen bei roman-\l"
	.string "tischen Problemen helfen und auch bei\l"
	.string "Geldsorgen...$"

LavaridgeTown_Text_16C72F:: @ 816C72F
	.string "BAD LAVASTADT\p"
	.string "“POKéMON-CENTER - HEISSE QUELLEN\n"
	.string "Der ideale Ort zum Entspannen!”$"

LavaridgeTown_Text_16C77C:: @ 816C77C
	.string "POKéMON ARENA von BAD LAVASTADT\n"
	.string "LEITERIN: FLAVIA\l"
	.string "“Die mit der brennenden Leidenschaft!”$"

LavaridgeTown_Text_16C7CF:: @ 816C7CF
	.string "POKéMON KRÄUTERLADEN\n"
	.string "“Bitterer Geschmack - Bessere Kur!”$"
