LilycoveCity_DepartmentStore_1F_Text_18BFB5:: @ 818BFB5
	.string "Willkommen im EINKAUFSZENTRUM von\n"
	.string "SEEGRASULB CITY.$"

LilycoveCity_DepartmentStore_1F_Text_18BFDB:: @ 818BFDB
	.string "Immer wenn ich in das EINKAUFSZENTRUM\n"
	.string "gehe, endet das damit, dass ich tausend\l"
	.string "Dinge kaufe, weil es so viel Spaß macht.$"

LilycoveCity_DepartmentStore_1F_Text_18C044:: @ 818C044
	.string "Heute wird mir meine Mama ein paar\n"
	.string "schöne Möbel kaufen.$"

LilycoveCity_DepartmentStore_1F_Text_18C07A:: @ 818C07A
	.string "Ich kaufe etwas Schönes für mein\n"
	.string "AZUMARILL, weil es einen WETTBEWERB\l"
	.string "gewonnen hat.$"

LilycoveCity_DepartmentStore_1F_Text_18C0C3:: @ 818C0C3
	.string "AZUMARILL: Maririroo!$"

LilycoveCity_DepartmentStore_1F_Text_18C0D9:: @ 818C0D9
	.string "EG: INFORMATION\n"
	.string "      LOTTERIE\p"
	.string "1S: ALLES FÜR DEN TRAINER\p"
	.string "2S: ALLES FÜR DEN KAMPF\p"
	.string "3S: TM\p"
	.string "4S: POKéPUPPEN\p"
	.string "DACH: DACHTERRASSE$"
