LilycoveCity_DepartmentStore_3F_Text_18C24B:: @ 818C24B
	.string "Um POKéMON schnell stärker zu machen,\n"
	.string "eignen sich Items hervorragend.\p"
	.string "PROTEIN steigert den ANGRIFF und\n"
	.string "KALZIUM den SPEZ. ANGRIFF.$"

LilycoveCity_DepartmentStore_3F_Text_18C2B5:: @ 818C2B5
	.string "Ich möchte, dass mein POKéMON mehr\n"
	.string "Ausdauer hat.\p"
	.string "Ich frage mich, ob ich lieber die\n"
	.string "VERTEIDIGUNG mit EISEN oder die SPEZ.\l"
	.string "VER. mit ZINK steigern soll.$"

LilycoveCity_DepartmentStore_3F_Text_18C32E:: @ 818C32E
	.string "Ich habe meinem POKéMON CARBON\n"
	.string "gegeben, um die INIT. zu erhöhen.$"

UnknownString_818C363: @ 818C363
	.string "UNVERZICHTBARES FÜR UNBESIEGBARE\n"
	.string "TRAINER\l"
	.string "2S: ALLES FÜR DEN KAMPF$"
