UnknownString_8173A9D: @ 8173A9D
	.string "POKéMON & IHRE LEBENSRÄUME...\n"
	.string "DIE KOEXISTENZ VON MENSCH & POKéMON...\l"
	.string "POKéMONOLOGIE FÜR ANFÄNGER...\p"
	.string "Es biegt sich unter der Last der Bücher,\n"
	.string "die PROF. BIRK geschrieben hat.$"

LittlerootTown_ProfessorBirchsLab_Text_173B29:: @ 8173B29
	.string "Wie? PROF. BIRK?\p"
	.string "Der PROF arbeitet an einer Feld-Studie.\n"
	.string "Also ist er nicht hier.\p"
	.string "Oh, ich erkläre dir, was eine Feld-Studie\n"
	.string "in diesem Falle ist:\p"
	.string "Man beobachtet und studiert Dinge in\n"
	.string "ihrem natürlichen Umfeld. In Feldern\l"
	.string "oder auf Bergen, anstatt im Labor.\p"
	.string "Der PROF ist kein Typ, der am Schreib-\n"
	.string "tisch arbeiten kann. Er muss einfach\l"
	.string "draußen in der freien Natur die Dinge\l"
	.string "beobachten und studieren.$"

LittlerootTown_ProfessorBirchsLab_Text_173C88:: @ 8173C88
	.string "Der PROF ist kein Typ, der am Schreib-\n"
	.string "tisch arbeiten kann. Er muss einfach\l"
	.string "draußen in der freien Natur die Dinge\l"
	.string "beobachten und studieren.$"

LittlerootTown_ProfessorBirchsLab_Text_173D15:: @ 8173D15
	.string "PROF. BIRK studiert den Lebensraum\n"
	.string "und die Verbreitung von POKéMON.\p"
	.string "Der PROF freut sich über die Mitarbeit\n"
	.string "von {RIVAL}. Da spürt man Zuneigung!$"

LittlerootTown_ProfessorBirchsLab_Text_173D94:: @ 8173D94
	.string "PROF. BIRK: Du bist also {PLAYER}{KUN}!\p"
	.string "Dein Vater hat mir schon viel von dir\n"
	.string "erzählt.\p"
	.string "Ich habe auch erfahren, dass du noch\n"
	.string "kein eigenes POKéMON besitzt.\p"
	.string "Aber wie du eben gekämpft hast...\n"
	.string "Diese Gelassenheit...\p"
	.string "In deinen Adern fließt wirklich das Blut\n"
	.string "deines Vaters!\p"
	.string "Als Dank dafür, dass du mich gerettet\n"
	.string "hast, möchte ich dir das POKéMON\l"
	.string "schenken, das du dabei benutzt hast.\p"
	.string "{PLAYER} erhält {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_173EF8:: @ 8173EF8
	.string "PROF. BIRK: Willst du dem\n"
	.string "{STR_VAR_1} einen Kosenamen geben?$"

LittlerootTown_ProfessorBirchsLab_Text_173F3D:: @ 8173F3D
	.string "PROF. BIRK: Wenn du dich erst einmal\n"
	.string "mit POKéMON beschäftigst und Er-\l"
	.string "fahrungen sammelst, wirst du bestimmt\l"
	.string "ein verdammt guter TRAINER!\p"
	.string "Mein Nachwuchs, {RIVAL}, studiert an\n"
	.string "der ROUTE 103 POKéMON.\p"
	.string "Hast du nicht Lust, {RIVAL} dort\n"
	.string "zu suchen?$"

LittlerootTown_ProfessorBirchsLab_Text_174015:: @ 8174015
	.string "PROF. BIRK: Großartig!\n"
	.string "{RIVAL} wird sich auch sehr freuen.\p"
	.string "{RIVAL} soll dir beibringen, was es\n"
	.string "bedeutet, ein TRAINER zu sein.$"

LittlerootTown_ProfessorBirchsLab_Text_174075:: @ 8174075
	.string "PROF. BIRK: Ach, sei doch nicht so!\n"
	.string "Du solltest dich wirklich mit meinem\l"
	.string "Sprössling treffen!$"

LittlerootTown_ProfessorBirchsLab_Text_1740B4:: @ 81740B4
	.string "PROF. BIRK: {RIVAL} muss irgendwo\n"
	.string "auf der ROUTE 103 zu finden sein.\p"
	.string "Falls du müde bist - oder deine\n"
	.string "POKéMON - ruh dich zu Hause aus.$"

LittlerootTown_ProfessorBirchsLab_Text_17411F:: @ 817411F
	.string "PROF. BIRK: Oh, hallo, {PLAYER}{KUN}!\p"
	.string "Ich habe gehört, du hast {RIVAL} \n"
	.string "besiegt! Super! Das war dein erster\l"
	.string "Kampf gegen einen TRAINER!\p"
	.string "{RIVAL} hilft mir schon sehr lange bei\n"
	.string "meinen Forschungen.\p"
	.string "{RIVAL} besitzt eine respektable\n"
	.string "Geschichte als TRAINER.\p"
	.string "Hier, das hilft mir bei meinen For-\n"
	.string "schungen. Aber ich denke, du kannst\l"
	.string "den POKéDEX auch gebrauchen.$"

LittlerootTown_ProfessorBirchsLab_Text_17422F:: @ 817422F
	.string "{PLAYER} erhält den POKéDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_174248:: @ 8174248
	.string "PROF. BIRK: Der POKéDEX ist ein hoch\n"
	.string "entwickeltes, technisches Gerät, das\l"
	.string "automatisch jedes POKéMON, das du\l"
	.string "siehst oder fängst, registriert.\p"
	.string "{RIVAL} geht nie ohne ihn aus dem Haus.\p"
	.string "Immer wenn mein Kind ein seltenes\n"
	.string "POKéMON fängt, kommt es und\l"
	.string "zeigt mir den Eintrag im POKéDEX,\l"
	.string "während ich draußen forsche.$"

LittlerootTown_ProfessorBirchsLab_Text_17436C:: @ 817436C
	.string "PROF. BIRK: Unzählige POKéMON erwarten\n"
	.string "dich bereits.\p"
	.string "Hach, ich muss jetzt auch dringend\n"
	.string "wieder meinen Forschungen nachgehen.$"

LittlerootTown_ProfessorBirchsLab_Text_1743D4:: @ 81743D4
	.string "MAIKE: Oh, wow, {PLAYER}{KUN}!\n"
	.string "Jetzt hast du auch einen POKéDEX!\p"
	.string "Das ist ja toll! Genau wie ich!\n"
	.string "Ich habe hier etwas für dich!$"

LittlerootTown_ProfessorBirchsLab_Text_17443D:: @ 817443D
	.string "MAIKE: Es macht unheimlich viel Spaß, all\n"
	.string "die verschiedenen POKéMON zu fangen!\p"
	.string "Ich schaue mich wirklich überall um, denn\n"
	.string "ich will die unterschiedlichsten POKéMON\l"
	.string "fangen.\p"
	.string "Sobald ich niedliche POKéMON entdecke,\n"
	.string "fange ich sie mit POKéBÄLLEN.$"

LittlerootTown_ProfessorBirchsLab_Text_1744F0:: @ 81744F0
	.string "Oh! Dein BEUTEL ist voll.$"

LittlerootTown_ProfessorBirchsLab_Text_174505:: @ 8174505
	.string "MAIKE: Ich frage mich, wo ich jetzt nach\n"
	.string "weiteren POKéMON suchen soll.$"

LittlerootTown_ProfessorBirchsLab_Text_17453C:: @ 817453C
	.string "BRIX: Ach...\n"
	.string "Du hast auch einen POKéDEX.\p"
	.string "Na, dann.\n"
	.string "Ich gebe dir dies.$"

LittlerootTown_ProfessorBirchsLab_Text_17458C:: @ 817458C
	.string "BRIX: Weißt du, je mehr POKéMON du\n"
	.string "besitzt, desto mehr Spaß macht es.\p"
	.string "Ich reise viel umher, um die unter-\n"
	.string "schiedlichsten POKéMON zu finden.\p"
	.string "Und wenn ich ein cooles POKéMON sehe,\n"
	.string "versuche ich natürlich, es zu fangen.$"

LittlerootTown_ProfessorBirchsLab_Text_17465B:: @ 817465B
	.string "Hey, dein BEUTEL ist voll.$"

LittlerootTown_ProfessorBirchsLab_Text_174671:: @ 8174671
	.string "BRIX: Und wo soll ich jetzt mal nach\n"
	.string "POKéMON suchen?$"

LittlerootTown_ProfessorBirchsLab_Text_1746A2:: @ 81746A2
	.string "Das ist eine kompliziert aussehende\n"
	.string "Maschine. Der PROF wird sie für seine\l"
	.string "Forschungen brauchen...$"

LittlerootTown_ProfessorBirchsLab_Text_1746E7:: @ 81746E7
	.string "Ein PC, der in der Forschung eingesetzt\n"
	.string "wird. Besser nicht damit spielen!$"

LittlerootTown_ProfessorBirchsLab_Text_174724:: @ 8174724
	.string "Es ist voll mit Büchern über POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_174748:: @ 8174748
	.string "Dieses Buch ist viel zu kompliziert...$"
