LittlerootTown_BrendansHouse_1F_Text_1730C2:: @ 81730C2
LittlerootTown_MaysHouse_1F_Text_1730C2:: @ 81730C2
	.string "Oh, hallo. Wer bist du?\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ... ...\p"
	.string "Oh, du bist {PLAYER}{KUN}, unser neuer\n"
	.string "Nachbar! Hallo!\p"
	.string "Wir haben ein Kind in deinem Alter.\p"
	.string "Mein/e {STR_VAR_1} freut sich schon\n"
	.string "darauf, mit dir Freundschaft zu\l"
	.string "schließen.\p"
	.string "Lauf doch mal die Treppe hoch...$"

LittlerootTown_BrendansHouse_1F_Text_1731C6:: @ 81731C6
	.string "Mein/e {STR_VAR_1} ist oben.$"

LittlerootTown_BrendansHouse_1F_Text_1731E3:: @ 81731E3
	.string "Wo ist denn nur mein Mann? Und gerade\n"
	.string "jetzt, wo {PLAYER}{KUN} uns besucht...\p"
	.string "Dieser Mann kann einfach nicht\n"
	.string "entspannen... Er ist wohl im LABOR.$"

LittlerootTown_BrendansHouse_1F_Text_173262:: @ 8173262
	.string "Oh, {RIVAL} ist irgendwohin gegangen.\p"
	.string "Wie der Vater, so das Kind.\n"
	.string "{RIVAL} kann einfach nicht stillsitzen\l"
	.string "oder zu Hause bleiben.$"

LittlerootTown_BrendansHouse_1F_Text_1732B9:: @ 81732B9
	.string "Ich glaube, es ist wunderbar für Leute,\n"
	.string "mit ihren POKéMON zu reisen.\p"
	.string "Aber du solltest öfter nach Hause\n"
	.string "gehen und deiner Mutter zeigen, dass es\l"
	.string "dir gut geht.\p"
	.string "Sie lässt es sich nicht anmerken, aber\n"
	.string "sie macht sich bestimmt Sorgen!$"
