MauvilleCity_House2_Text_18244E:: @ 818244E
	.string "Wenn ich doch nur ein RAD hätte...\n"
	.string "Dann könnte ich nach GRAPHITPORT\l"
	.string "CITY zum Einkaufen fahren.\p"
	.string "Dort würde ich mir dann einen HAFEN-\n"
	.string "BRIEF im PKMN-SUPERMARKT kaufen...$"

MauvilleCity_House2_Text_1824D8:: @ 81824D8
	.string "Oh! Du besitzt einen HAFENBRIEF!!!\n"
	.string "Würdest du den gegen einen MÜNZKORB\l"
	.string "tauschen?$"

MauvilleCity_House2_Text_182515:: @ 8182515
	.string "Oh, ich bin so glücklich!\n"
	.string "Okay, ich gebe dir diesen MÜNZKORB!$"

MauvilleCity_House2_Text_182549:: @ 8182549
	.string "Diesen MÜNZKORB brauchst du in der\n"
	.string "SPIELHALLE.$"

MauvilleCity_House2_Text_182578:: @ 8182578
	.string "Oh, das ist schade.\p"
	.string "In der SPIELHALLE benötigt man einen\n"
	.string "MÜNZKORB.$"
