MauvilleCity_Mart_Text_1827D3:: @ 81827D3
	.string "Es gibt Items, die den Status eines\n"
	.string "POKéMON kurzzeitig erhöhen.\p"
	.string "Ich weiß, dass man X-ANGRIFF und\n"
	.string "X-VERTEIDIGUNG im Kampf einsetzen\l"
	.string "kann...\p"
	.string "Ich glaube, es gibt aber auch noch\n"
	.string "andere.$"

MauvilleCity_Mart_Text_18287F:: @ 818287F
	.string "Setze eine bestimmte Attacke ein,\n"
	.string "oder stattdessen ein Item...\p"
	.string "Ich glaube, die Entscheidungen des\n"
	.string "TRAINERS bestimmen, wie ein Kampf\l"
	.string "verläuft.$"
