MeteorFalls_1F_1R_Text_193237:: @ 8193237
	.string "Hähähä!\p"
	.string "Mit diesem METEORITEN wird\n"
	.string "SCHLOTBERG...$"

MeteorFalls_1F_1R_Text_193268:: @ 8193268
	.string "Häh?\p"
	.string "Ich weiß zwar nicht, wer du bist. Aber\n"
	.string "wenn du dich TEAM {EVIL_TEAM} in den Weg\l"
	.string "stellst, erwarte keine Gnade!$"

MeteorFalls_1F_1R_Text_1932C5:: @ 81932C5
	.string "Bleibt sofort stehen, TEAM {EVIL_TEAM}!\p"
	.string "Wir, TEAM {GOOD_TEAM}, lassen euch nicht so \n"
	.string "einfach mit euren Missetaten davon-\l"
	.string "kommen.$"

MeteorFalls_1F_1R_Text_193320:: @ 8193320
	.string "Hähähä!\n"
	.string "Sogar TEAM {GOOD_TEAM} leistet uns\l"
	.string "Gesellschaft!\p"
	.string "Aber es ist viel zu anstrengend, sich\n"
	.string "mit allen auseinander zu setzen...\p"
	.string "Hey, das spielt auch keine Rolle!\p"
	.string "Wir haben den METEORITEN und so\n"
	.string "machen wir uns auf zum SCHLOTBERG!\p"
	.string "Hähähä! Wir sehen uns, ihr Würstchen\n"
	.string "vom TEAM {GOOD_TEAM}!$"

MeteorFalls_1F_1R_Text_1933EC:: @ 81933EC
	.string "Und du bist?\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Schön, du bist also {PLAYER}{KUN}.\p"
	.string "Ich bin MARC. Als Kopf vom TEAM MAGMA\n"
	.string "widme ich mich hingebungsvoll der\l"
	.string "Aufgabe, die gefährlichen Pläne von\l"
	.string "TEAM AQUA zu durchkreuzen.\p"
	.string "Warum? Weil TEAM AQUA unser aller\n"
	.string "Sargnagel ist, deshalb!\p"
	.string "Sie haben schon etliche gefährliche\n"
	.string "Dinge unternommen, um die Meere zu\l"
	.string "vergrößern.\p"
	.string "Wir, TEAM MAGMA, lieben trockenes Land\n"
	.string "über alles! TEAM AQUA? Unser Erzfeind!$"

MeteorFalls_1F_1R_Text_193584:: @ 8193584
	.string "Wer bist du denn???\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ah ja, du bist {PLAYER}{KUN}.\p"
	.string "Ich bin ADRIAN. Als Kopf von TEAM AQUA\n"
	.string "setze ich alles daran, die gefährlichen\l"
	.string "Pläne von TEAM MAGMA zu vereiteln.\p"
	.string "Warum? Weil TEAM MAGMA uns alle noch\n"
	.string "zugrunde richtet!\p"
	.string "Sie führen waghalsige und gefährliche\n"
	.string "Pläne aus, um die Landmassen zu\l"
	.string "vergrößern.\p"
	.string "Wir, TEAM AQUA, lieben das Meer über\n"
	.string "alles. TEAM MAGMA ist unser Erzfeind!$"

MeteorFalls_1F_1R_Text_193720:: @ 8193720
	.string "{GOOD_LEADER}, wir sollten TEAM {EVIL_TEAM}\n"
	.string "verfolgen...$"

MeteorFalls_1F_1R_Text_193747:: @ 8193747
	.string "{GOOD_LEADER}: Ja, ja. Das müssen wir!\n"
	.string "Wir müssen uns beeilen.\p"
	.string "Nicht auszudenken, was TEAM {EVIL_TEAM} am\n"
	.string "SCHLOTBERG anrichten will!$"

MeteorFalls_1F_1R_Text_1937AA:: @ 81937AA
	.string "{GOOD_LEADER}: {PLAYER}{KUN}, du solltest\n"
	.string "TEAM {EVIL_TEAM} im Auge behalten.\p"
	.string "Leb wohl!$"

MeteorFalls_1F_1R_Text_1937EB:: @ 81937EB
	.string "Ich... Ich bin KOSMO...\n"
	.string "Ich bin Professor...\p"
	.string "Eigentlich studiere ich METEORITEN in\n"
	.string "LAUBWECHSELFELD...\p"
	.string "Dann haben mich einige Typen vom\n"
	.string "TEAM {EVIL_TEAM} überredet, sie zu METEOR-\l"
	.string "FÄLLE zu führen...\p"
	.string "Sie haben mir versprochen, für mich\n"
	.string "einen METEORITEN auszugraben...\p"
	.string "Aber ich...\n"
	.string "TEAM {EVIL_TEAM} hat mich hereingelegt...\p"
	.string "Oh... Dieser METEORIT... Der wird\n"
	.string "jetzt wohl nie mehr mir gehören...\p"
	.string "Aber TEAM {EVIL_TEAM}...\p"
	.string "Was haben sie mit dem METEORITEN am\n"
	.string "SCHLOTBERG vor?$"

MeteorFalls_1F_1R_Text_19396A:: @ 819396A
	.string "PROF. KOSMO: Dieses TEAM {EVIL_TEAM}...\p"
	.string "Was haben sie mit dem METEORITEN am\n"
	.string "SCHLOTBERG vor?$"
