MossdeepCity_House2_Text_18D536:: @ 818D536
	.string "Meine kleine Schwester tauscht immer\n"
	.string "BRIEFE mit ihrem Freund in BAUMHAUSEN\l"
	.string "CITY aus.\p"
	.string "Ich beneide sie kein bisschen darum.$"

MossdeepCity_House2_Text_18D596:: @ 818D596
	.string "Auch wenn ich meinen Freund in\n"
	.string "BAUMHAUSEN CITY nicht sehen kann...\l"
	.string "Mein POKéMON bringt uns unsere BRIEFE.\p"
	.string "Ich bin nicht einsam, auch wenn wir\n"
	.string "getrennt sind.$"

MossdeepCity_House2_Text_18D61E:: @ 818D61E
	.string "WINGULL: Pihyoh!$"
