MossdeepCity_Mart_Text_18D758:: @ 818D758
	.string "BELEBER ist einfach fantastisch!\p"
	.string "Gib es einem besiegten POKéMON und\n"
	.string "es ist wieder fit.\p"
	.string "Aber Vorsicht! BELEBER füllt nicht die\n"
	.string "verbrauchten AP neu auf!$"

MossdeepCity_Mart_Text_18D7E7:: @ 818D7E7
	.string "TOP-SCHUTZ hält alle schwachen POKéMON\n"
	.string "auf Distanz.\p"
	.string "Von allen SCHUTZ-Sprays hält dieses am\n"
	.string "längsten an.$"

MossdeepCity_Mart_Text_18D841:: @ 818D841
	.string "Der NETZ- und der TAUCHBALL sind\n"
	.string "seltene POKéBÄLLE, die in\l"
	.string "MOOSBACH CITY hergestellt werden.\p"
	.string "Ein NETZBALL ist höchst wirkungsvoll\n"
	.string "bei KÄFER- und WASSER-POKéMON.\p"
	.string "Der TAUCHBALL ist wirkungsvoll bei\n"
	.string "POKéMON, die in der Tiefsee leben.$"
