MossdeepCity_House3_Text_18D909:: @ 818D909
	.string "Hey, du da! TRAINER!\n"
	.string "Eine SUPERANGEL ist wirklich super!\p"
	.string "Man kann sagen, was man will, aber mit\n"
	.string "diesem Baby kann man POKéMON vom\l"
	.string "Meeresboden weg fangen!\p"
	.string "Na? Du würdest doch zu gerne auch so\n"
	.string "eine Angel haben, oder?$"

MossdeepCity_House3_Text_18D9A9:: @ 818D9A9
	.string "Sicher, sicher!\n"
	.string "Schließlich ist eine SUPERANGEL super!$"

MossdeepCity_House3_Text_18D9E3:: @ 818D9E3
	.string "Stehst du am Wasser, dann wirf die\n"
	.string "ANGEL aus und schau, was anbeißt!$"

MossdeepCity_House3_Text_18DA26:: @ 818DA26
	.string "Was???\n"
	.string "Liebst du das Angeln nicht?$"

MossdeepCity_House3_Text_18DA44:: @ 818DA44
	.string "Mit deiner SUPERANGEL kannst du die\n"
	.string "POKéMON am Meeresboden fangen.$"
