MtPyre_6F_Text_1969FE:: @ 81969FE
	.string "Wenn ich hier bin... Dann durchströmt\n"
	.string "mich eine seltsame Macht...$"

MtPyre_6F_Text_196A30:: @ 8196A30
	.string "Die Macht ebbt ab...$"

MtPyre_6F_Text_196A4C:: @ 8196A4C
	.string "Die Geister der hier ruhenden POKéMON\n"
	.string "erfüllen mich mit ihrer Macht...$"

MtPyre_6F_Text_196A95:: @ 8196A95
	.string "Hinter dir...\n"
	.string "W... Was ist das?$"

MtPyre_6F_Text_196AB1:: @ 8196AB1
	.string "Etwas war da und verschwand...$"

MtPyre_6F_Text_196AC9:: @ 8196AC9
	.string "Die POKéMON, die hier ruhen...\n"
	.string "Manchmal spielen sie...$"
