OldaleTown_Mart_Text_174A8A:: @ 8174A8A
	.string "Der Verkäufer sagt, es sei alles ausver-\n"
	.string "kauft. Jetzt stehe ich ohne\l"
	.string "POKéBÄLLE da.$"

OldaleTown_Mart_Text_174ACB:: @ 8174ACB
	.string "Ich will mir viele POKéBÄLLE kaufen und\n"
	.string "damit genauso viele POKéMON fangen!$"

OldaleTown_Mart_Text_174B10:: @ 8174B10
	.string "Wird ein POKéMON verletzt und verliert\n"
	.string "alle KP, so ist es kampfunfähig.\p"
	.string "Um das zu vermeiden, solltest du die KP\n"
	.string "bei Bedarf mit einem TRANK auffüllen.$"
