PacifidlogTown_Text_16CFC5:: @ 816CFC5
	.string "Im Meer zwischen FLOSSBRUNN und\n"
	.string "GRAPHITPORT CITY befinden sich\l"
	.string "reißende Strömungen.\p"
	.string "Wenn du dort SURFER einsetzt, kann es\n"
	.string "sein, dass du fortgetrieben wirst.$"

PacifidlogTown_Text_16D04A:: @ 816D04A
	.string "Schau mal. Ist das nicht hübsch?\n"
	.string "Die Häuser stehen auf dem Wasser.\p"
	.string "Ich wurde hier geboren.$"

PacifidlogTown_Text_16D08A:: @ 816D08A
	.string "Das Volk von FLOSSBRUNN fischt und\n"
	.string "taucht. Das gehört zu ihrem Leben.$"

PacifidlogTown_Text_16D0CE:: @ 816D0CE
	.string "FLOSSBRUNN\p"
	.string "“Wo die Morgensonne ein Lächeln auf\n"
	.string "das Meer zaubert.”$"
