PetalburgCity_Mart_Text_17BFFD:: @ 817BFFD
	.string "Auch wenn ein POKéMON jetzt noch\n"
	.string "schwach ist - es wird ständig stärker.\p"
	.string "Das Schlüsselwort heißt Liebe!\n"
	.string "Liebe für deine POKéMON!$"

PetalburgCity_Mart_Text_17C06C:: @ 817C06C
	.string "Setzt du SCHUTZ ein?\n"
	.string "Das hält POKéMON fern und ist sehr\l"
	.string "nützlich, wenn du es eilig hast.$"

PetalburgCity_Mart_Text_17C0BC:: @ 817C0BC
	.string "Hast du etwas GEGENGIFT dabei?\p"
	.string "Ein vergiftetes POKéMON verliert\n"
	.string "ständig KP, bis es kampfunfähig wird.\l"
	.string "Halte deshalb stets GEGENGIFT bereit!$"
