Route114_LanettesHouse_Text_192A0D:: @ 8192A0D
	.string "LANETTE: Oh! {PLAYER}{KUN}!\p"
	.string "Entschuldige, dass es hier so chaotisch\n"
	.string "aussieht. Immer, wenn ich forsche,\l"
	.string "vergesse ich aufzuräumen...\p"
	.string "Das ist echt peinlich... Erzähl das bloß\n"
	.string "niemandem! Ich gebe dir auch dies hier...$"

Route114_LanettesHouse_Text_192ACC:: @ 8192ACC
	.string "Soll ich dir einige Hinweise zum POKéMON-\n"
	.string "Lagerungs-System geben?\p"
	.string "Du solltest deine BOXEN gut verwalten,\n"
	.string "damit du weißt, welche POKéMON sich \l"
	.string "in welcher BOX befinden...$"

Route114_LanettesHouse_Text_192B4A:: @ 8192B4A
	.string "LANETTES Forschungs-Aufzeichnungen.\n"
	.string "Das sind Informationen zu den BOXEN.\p"
	.string "Es sollten BOXEN eingerichtet werden,\n"
	.string "die jeweils 30 POKéMON aufnehmen\l"
	.string "können.\p"
	.string "Jeder TRAINER sollte in der Lage sein,\n"
	.string "420 POKéMON im PC-System zu lagern.\p"
	.string "Weiterlesen?$"

Route114_LanettesHouse_Text_192C01:: @ 8192C01
	.string "Es muss ein Markierungssystem einge-\n"
	.string "richtet werden, mit dem man eine gute\l"
	.string "Übersicht über die POKéMON bekommt.\p"
	.string "Der Name und der Hintergrund jeder BOX\n"
	.string "lässt sich verändern, zur Freude der\l"
	.string "darin gelagerten POKéMON.\p"
	.string "Weiterlesen?$"

Route114_LanettesHouse_Text_192CB4:: @ 8192CB4
	.string "Immer, wenn ein POKéMON gelagert wird,\n"
	.string "wird es in der BOX gelagert, die als\l"
	.string "Letzte geöffnet wurde.\p"
	.string "Ist diese BOX voll, wird das POKéMON in\n"
	.string "der nächsten BOX gelagert.\p"
	.string "Mit anderen Worten, die zuletzt ge-\n"
	.string "öffnete BOX wird automatisch gewählt,\l"
	.string "um ein POKéMON zu lagern.$"

Route114_LanettesHouse_Text_192DA9:: @ 8192DA9
	.string "{PLAYER} schließt das Notizbuch.$"

Route114_LanettesHouse_Text_192DC1:: @ 8192DC1
	.string "Da ist eine E-Mail von jemandem\n"
	.string "auf dem PC.\p"
	.string "“... ... ... ... ... ... ...\p"
	.string "Dein Lagerungs-System bietet viel mehr\n"
	.string "Komfort als meines.\p"
	.string "Es besitzt viele anwenderfreundliche\n"
	.string "Features, die nützlich sind und Spaß\l"
	.string "machen.\p"
	.string "Es macht mich stolz, dass ich Teil\n"
	.string "dieser Entwicklung war.\p"
	.string "Ich hoffe sehr, du setzt deine For-\n"
	.string "schungen in diesem Bereich weiter fort.\p"
	.string "BILL\n"
	.string "... ... ... ... ... ... ... ...”$"
