Route110_TrickHouseEnd_Text_19C281:: @ 819C281
	.string "Argh!\n"
	.string "Du hast mich gefunden?\l"
	.string "Hmmm... Du bist verdammt clever!$"

Route110_TrickHouseEnd_Text_19C2B2:: @ 819C2B2
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "all die Bäume zu pflanzen...\p"
	.string "Du bist meiner Größe fast ebenbürtig,\n"
	.string "bis auf ein, zwei, drei, vier, fünf, sechs\l"
	.string "Punkte!$"

Route110_TrickHouseEnd_Text_19C333:: @ 819C333
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "das Labyrinth anzulegen...\p"
	.string "Du bist meiner Größe fast ebenbürtig,\n"
	.string "bis auf ein, zwei, drei, vier, fünf \l"
	.string "Punkte!$"

Route110_TrickHouseEnd_Text_19C3A7:: @ 819C3A7
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "die Felsen zu platzieren...\p"
	.string "Du bist meiner Größe fast ebenbürtig,\n"
	.string "bis auf ein, zwei, drei, vier Punkte!$"

Route110_TrickHouseEnd_Text_19C41F:: @ 819C41F
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "die Felsen hin- und herzuschieben...\p"
	.string "Du bist meiner Größe fast ebenbürtig,\n"
	.string "bis auf ein, zwei, drei Punkte!$"

Route110_TrickHouseEnd_Text_19C491:: @ 819C491
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "die ROBOPUPPEN zu konstruieren und\l"
	.string "mir das Quiz auszudenken...\p"
	.string "Du bist meiner Größe fast ebenbürtig,\n"
	.string "bis auf ein oder zwei Punkte!$"

Route110_TrickHouseEnd_Text_19C515:: @ 819C515
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "die Türen zu installieren...\p"
	.string "Du bist meiner Größe fast ebenbürtig!$"

Route110_TrickHouseEnd_Text_19C567:: @ 819C567
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "die Pfeile anzubringen.\p"
	.string "Du bist meiner Größe ebenbürtig!$"

Route110_TrickHouseEnd_Text_19C5AF:: @ 819C5AF
	.string "Ich habe die ganze Nacht gebraucht,\n"
	.string "den Boden zu polieren...\p"
	.string "Du bist mir weit überlegen!\n"
	.string "Unmöglich...$"

Route110_TrickHouseEnd_Text_19C602:: @ 819C602
	.string "Was soll ich nur tun?\n"
	.string "Die Quelle der Ideen für meine Tricks\l"
	.string "ist trocken gelegt...\p"
	.string "Vielleicht ist es an der Zeit, durch die\n"
	.string "Lande zu reisen und mich für neue\l"
	.string "Tricks inspirieren zu lassen...$"

Route110_TrickHouseEnd_Text_19C691:: @ 819C691
	.string "Ich hasse es, zuzugeben, dass ich be-\n"
	.string "siegt wurde. Du hast mich geschlagen!\p"
	.string "Mein Charisma muss dich gefangen\n"
	.string "genommen haben, da du immer wieder\l"
	.string "herkommst. Ja, so muss es sein!\p"
	.string "Aber das hat nichts mit meiner\n"
	.string "Niederlage zu tun!\p"
	.string "Als Zeichen der Freundschaft zwischen\n"
	.string "dir, dem Aufstrebenden und mir, dem\l"
	.string "Genie, überreiche ich dir dieses\l"
	.string "Andenken!$"

Route110_TrickHouseEnd_Text_19C7D7:: @ 819C7D7
	.string "Was? Du hast keinen Platz im PC?\n"
	.string "Und was soll ich jetzt damit machen?\p"
	.string "Sei froh, dass ich so nett und rück-\n"
	.string "sichtsvoll bin. Ich verwahre es für\l"
	.string "dich. Komm einfach später wieder.$"

Route110_TrickHouseEnd_Text_19C85C:: @ 819C85C
	.string "... ... ... ... ... ...\p"
	.string "Ich gehe jetzt auf eine Entdeckungs-\n"
	.string "reise. Auf die Suche nach neuen Tricks.\p"
	.string "Ich hoffe, du besuchst mich eines\n"
	.string "Tages wieder und unterhältst mich.\p"
	.string "Für heute lebe wohl!$"

Route110_TrickHouseEnd_Text_19C90B:: @ 819C90B
	.string "Gut!\n"
	.string "Du hast dir diese Belohnung verdient!$"

Route110_TrickHouseEnd_Text_19C92E:: @ 819C92E
	.string "Was? Du hast keinen Platz dafür?\n"
	.string "Wie viele Items schleppst du denn mit?\p"
	.string "Aber du kannst dir deine Belohnung\n"
	.string "auch später bei mir abholen.$"

Route110_TrickHouseEnd_Text_19C9BD:: @ 819C9BD
	.string "Putz dir das selbstgefällige Grinsen von\n"
	.string "der Backe! Noch hast du nicht gewonnen!\p"
	.string "Ich werde neue Tricks erfinden, die\n"
	.string "dich zu Fall bringen werden. Zum Grinsen\p"
	.string "hast du erst Grund, wenn du es\n"
	.string "geschafft hast.\p"
	.string "Komm wieder, wenn ich die nächste\n"
	.string "interessante Installation fertig habe.$"

Route110_TrickHouseEnd_Text_19CA8B:: @ 819CA8B
	.string "Nun, nun! Du ignorierst mich?\n"
	.string "Das bricht mir glatt das Herz!$"

UnknownString_819CAD1: @ 819CAD1
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist sagenhaft.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
