Route118_Text_170D66:: @ 8170D66
	.string "TROY: Hi!\p"
	.string "Du bist der TRAINER, den ich in\n"
	.string "FAUSTAUHAVEN getroffen habe!\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Oh, okay, du bist {PLAYER}{KUN}.\n"
	.string "Ich erinnere mich.\p"
	.string "{PLAYER}{KUN}.\p"
	.string "In dieser großen Welt gibt es viele ver-\n"
	.string "schiedene Arten von POKéMON mit\l"
	.string "vielen verschiedenen Elementklassen.\p"
	.string "Ziehst du verschiedene Elementklassen\n"
	.string "auf? Oder nur POKéMON einer bestimmten\l"
	.string "Elementklasse?\p"
	.string "Was denkst du als TRAINER darüber?\p"
	.string "Tut mir Leid, ich bombardiere dich hier\n"
	.string "mit Fragen...\p"
	.string "Nun, ich hoffe wir sehen uns bald wieder.$"

Route118_Text_170F12:: @ 8170F12
	.string "Hmm!\n"
	.string "Eine PROFIANGEL ist wirklich gut!\p"
	.string "Meinst du nicht auch?$"

Route118_Text_170F46:: @ 8170F46
	.string "Hmm!\n"
	.string "Da sind wir ja der gleichen Meinung!\p"
	.string "Hmm!\n"
	.string "Ich schenke dir diese PROFIANGEL!$"

Route118_Text_170F7E:: @ 8170F7E
	.string "Wo immer du Wasser findest, versuche\n"
	.string "dein Glück mit Angeln.$"

Route118_Text_170FB0:: @ 8170FB0
	.string "Magst du keinen Fisch?$"

Route118_Text_170FC8:: @ 8170FC8
	.string "Versuche, alle möglichen Arten von\n"
	.string "POKéMON mit der PROFIANGEL zu fangen.$"

Route118_Text_170FFE:: @ 8170FFE
	.string "Auch wenn gerade kein Schiff in der\n"
	.string "Nähe ist, kannst du mit einem POKéMON,\l"
	.string "das SURFER kennt, das Meer überqueren.\p"
	.string "Auf POKéMON kann man sich immer\n"
	.string "verlassen!$"

Route118_Text_17108B:: @ 817108B
	.string "ROUTE 118\n"
	.string "{LEFT_ARROW} MALVENFROH CITY$"

Route118_Text_1710A5:: @ 81710A5
	.string "ROUTE 118\n"
	.string "{UP_ARROW} ROUTE 119$"
