Route110_TrickHousePuzzle5_Text_19D423:: @ 819D423
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 1 ICH BIN!\p"
	.string "GIBST DU IM QUIZ RICHTIGE ANTWORTEN,\n"
	.string "ERREICHST DU BALD ROBOPUPPE 5.\l"
	.string "DORT ERHÄLTST DU DEN GEHEIMEN CODE.$"

Route110_TrickHousePuzzle5_Text_19D4AE:: @ 819D4AE
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON kann man nicht\n"
	.string "auf der ROUTE 103 finden. Welches?$"

Route110_TrickHousePuzzle5_Text_19D501:: @ 819D501
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON ist kein\n"
	.string "PFLANZEN-POKéMON. Welches?$"

Route110_TrickHousePuzzle5_Text_19D553:: @ 819D553
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON setzt\n"
	.string "KRATZER ein. Welches?$"

Route110_TrickHousePuzzle5_Text_19D599:: @ 819D599
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_19D5CF:: @ 819D5CF
	.string "BZZZT. ENTTÄUSCHEND.\n"
	.string "FEHLER.$"

Route110_TrickHousePuzzle5_Text_19D5ED:: @ 819D5ED
	.string "WAHAHAHAHA! WAHAHAHAHA!\n"
	.string "KLICK-KLACK!$"

Route110_TrickHousePuzzle5_Text_19D615:: @ 819D615
	.string "DEINE NÄCHSTE HERAUSFORDERUNG WIR\n"
	.string "ERWARTEN.$"

Route110_TrickHousePuzzle5_Text_19D636:: @ 819D636
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 2 ICH BIN!\p"
	.string "ROBOPUPPE 1 QUIZ-SCHWIERIGKEITS-\n"
	.string "GRAD IST ZU NIEDRIG.$"

Route110_TrickHousePuzzle5_Text_19D68E:: @ 819D68E
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "In PROF. BIRKS Beutel befanden sich\n"
	.string "drei POKéMON. Welches lag ganz rechts?$"

Route110_TrickHousePuzzle5_Text_19D6EC:: @ 819D6EC
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "Welches POKéMON wurde in der POKéMON\n"
	.string "TRAINERSCHULE zum Tausch angeboten?$"

Route110_TrickHousePuzzle5_Text_19D745:: @ 819D745
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "Welches POKéMON hat der FORSCHER von\n"
	.string "DEVON im BLÜTENBURGWALD gesucht?$"

UnknownString_819D79D: @ 819D79D
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_19D7D3:: @ 819D7D3
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 3 ICH BIN!\p"
	.string "FÜR MICH ZÄHLT NUR GELD.$"

Route110_TrickHousePuzzle5_Text_19D81B:: @ 819D81B
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Was ist teurer?\n"
	.string "Drei POKéBÄLLE oder ein SUPERTRANK?$"

Route110_TrickHousePuzzle5_Text_19D865:: @ 819D865
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Verkaufe ein FLUCHTSEIL und kaufe ein\n"
	.string "GEGENGIFT. Wie viel Geld bleibt übrig?$"

Route110_TrickHousePuzzle5_Text_19D8BA:: @ 819D8BA
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Kosten ein HYPERHEILER und ein\n"
	.string "SUPERBALL mehr als ein BELEBER?$"

UnknownString_819D907: @ 819D907
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_19D93D:: @ 819D93D
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 4 ICH BIN!\p"
	.string "ICH INTERESSIERE MICH FÜR SCHÖNES.$"

Route110_TrickHousePuzzle5_Text_19D987:: @ 819D987
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "ARENALEITERIN FELIZIA in METAROST\n"
	.string "CITY kämpft mit KLEINSTEIN. Ist es\l"
	.string "männlich oder weiblich?$"

Route110_TrickHousePuzzle5_Text_19D9DC:: @ 819D9DC
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "Befanden sich in der FAUSTAUHAVEN\n"
	.string "HALLE mehr Männer oder mehr Frauen?$"

Route110_TrickHousePuzzle5_Text_19DA1D:: @ 819DA1D
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "Der erste TRAINER in der ARENA von\n"
	.string "FAUSTAUHAVEN, war der männlich oder\l"
	.string "weiblich?$"

UnknownString_819DA64: @ 819DA64
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_19DA9A:: @ 819DA9A
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 5 ICH BIN!\p"
	.string "DES MEISTERS BESTE UND STOLZESTE\n"
	.string "ERFINDUNG ICH BIN.$"

Route110_TrickHousePuzzle5_Text_19DAEF:: @ 819DAEF
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Wie viele RÄDER stehen bei\n"
	.string "RADLA vor dem Laden?$"

Route110_TrickHousePuzzle5_Text_19DB43:: @ 819DB43
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Von wie vielen Leuten bekommst du im\n"
	.string "BLÜTENTRAUM BLUMENLADEN BEEREN?$"

Route110_TrickHousePuzzle5_Text_19DB97:: @ 819DB97
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Wie viele Schilder gibt es in\n"
	.string "SEEGRASULB CITY?$"

UnknownString_819DBD4: @ 819DBD4
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

UnknownString_819DC0A: @ 819DC0A
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist mein Leben.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
