Route110_Text_16E6C0:: @ 816E6C0
	.string "TEAM {EVIL_TEAM}S Aktivitäten müssen im\n"
	.string "Moment geheim bleiben!$"

Route110_Text_16E6F2:: @ 816E6F2
	.string "Ich würde liebend gerne nach\n"
	.string "GRAPHITPORT CITY gehen und ein\l"
	.string "bisschen Krawall machen.$"

Route110_Text_16E729:: @ 816E729
	.string "Das ist mein erster Job, seit ich dem\n"
	.string "TEAM {EVIL_TEAM} beigetreten bin. Ich bin\l"
	.string "ganz tatterig.$"

Route110_Text_16E76A:: @ 816E76A
	.string "TEAM {EVIL_TEAM}S Aktionen zaubern ein\n"
	.string "Lächeln auf jedes Gesicht!$"

Route110_Text_16E7A1:: @ 816E7A1
	.string "MAIKE: Hi, {PLAYER}{KUN}, wir haben uns ja\n"
	.string "lange nicht gesehen!\p"
	.string "Während ich auf der Suche nach\n"
	.string "weiteren POKéMON war, sind meine\l"
	.string "POKéMON stärker geworden.\p"
	.string "Daher...\n"
	.string "Wie wäre es mit einem kleinen Kampf?$"

Route110_Text_16E826:: @ 816E826
	.string "AchDuSchande!\n"
	.string "Du bist besser als ich gedacht habe.$"

Route110_Text_16E84C:: @ 816E84C
	.string "MAIKE: {PLAYER}{KUN}, du hast auch fleißig\n"
	.string "trainiert, nicht wahr?\p"
	.string "Ich denke, du verdienst eine Belohnung!\n"
	.string "Hier, dies ist von mir für dich!$"

Route110_Text_16E8B3:: @ 816E8B3
	.string "MAIKE: Das ist ein DETEKTOR.\p"
	.string "Probier ihn mal aus. Wenn irgendwo ein\n"
	.string "Item versteckt ist, gibt er ein\l"
	.string "Geräusch von sich.\p"
	.string "Bis zum nächsten Mal, {PLAYER}{KUN}.\p"
	.string "Es hört sich aus meinem Munde zwar blöd\n"
	.string "an, aber bis dahin solltest du viel mehr\l"
	.string "trainiert haben.$"

Route110_Text_16E99A:: @ 816E99A
	.string "BRIX: Hey, {PLAYER}.\n"
	.string "Hier treibst du dich also herum.\l"
	.string "Wie geht es?\p"
	.string "Hast du deine POKéMON gut aufgezogen?\n"
	.string "Ich werde das für dich überprüfen.$"

Route110_Text_16EA0F:: @ 816EA0F
	.string "Hmm...\n"
	.string "Du bist sehr gut.$"

Route110_Text_16EA2A:: @ 816EA2A
	.string "BRIX: {PLAYER}, du hast trainiert,\n"
	.string "ohne dass ich etwas davon\l"
	.string "mitbekommen habe...\p"
	.string "Aber genug!\n"
	.string "Hier, das ist für dich!$"

Route110_Text_16EA7B:: @ 816EA7B
	.string "BRIX: Das ist ein DETEKTOR.\p"
	.string "Probier ihn mal aus. \p"
	.string "Ist irgendwo ein Item versteckt, gibt\n"
	.string "er ein Geräusch von sich.\p"
	.string "Wie auch immer, ich suche jetzt weiter\n"
	.string "nach POKéMON.$"

Route110_Text_16EB22:: @ 816EB22
	.string "Wäre das nicht ein Spaß, mit einem FAHR-\n"
	.string "RAD volle Pulle den RADWEG\l"
	.string "entlangzudüsen?$"

Route110_Text_16EB65:: @ 816EB65
	.string "Gefällt es dir, wie mein raben-\n"
	.string "schwarzes Haar im Wind weht?\p"
	.string "Ich habe nur deshalb die Haare wachsen\n"
	.string "lassen!$"

Route110_Text_16EBC9:: @ 816EBC9
	.string "Oh, hey, du hast ein RAD von RADLA!\p"
	.string "Oh, das ist mehr als offensichtlich.\n"
	.string "Es steht ja dort geschrieben...\p"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\n"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\p"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\n"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\p"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\n"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\p"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\n"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA,\p"
	.string "RADLA, RADLA, RADLA, RADLA, RADLA...\n"
	.string "Der Name steht überall.\p"
	.string "Du solltest damit überall herumfahren,\n"
	.string "eine bessere Werbung gibt es nicht!$"

Route110_Text_16EDC5:: @ 816EDC5
	.string "Zwei Straßen, eine oben, eine unten...\p"
	.string "Eine Straße für Menschen und eine für\n"
	.string "POKéMON. Das ist nur recht und billig.$"

Route110_Text_16EE30:: @ 816EE30
	.string "Ich habe kein RAD, ich werde gemüt-\n"
	.string "lich über die untere Straße schlendern.$"

Route110_Text_16EE74:: @ 816EE74
	.string "Neue Techniken zu lernen, geben dem\n"
	.string "Radfahren erst die richtige Würze.\p"
	.string "Einige Orte kannst du nur erreichen,\n"
	.string "wenn du die richtige Technik anwendest.$"

Route110_Text_16EEF6:: @ 816EEF6
	.string "Was soll ich tun?\p"
	.string "Schnurstracks über den RADWEG nach\n"
	.string "MALVENFROH CITY fahren oder die untere\p"
	.string "Straße nehmen und nach POKéMON\n"
	.string "suchen?$"

Route110_Text_16EF65:: @ 816EF65
	.string "Anzahl der Zusammenstöße:\n"
	.string "... ... {STR_VAR_1}!\p"
	.string "Zeit:\n"
	.string "... ... {STR_VAR_2}!$"

Route110_Text_16EF9F:: @ 816EF9F
	.string "Bravo! Eine hervorragende Leistung!\p"
	.string "Ich glaube, dein Talent zum Radfahren\n"
	.string "kommt tief aus deinem innersten Herzen.\l"
	.string "Du hast mich bis in die Seele getroffen!$"

Route110_Text_16F012:: @ 816F012
	.string "Deine Technik ist bemerkenswert.\p"
	.string "Achte stets darauf, dass du nicht zu\n"
	.string "schnell fährst und mit niemandem zu-\l"
	.string "sammenstößt.$"

Route110_Text_16F069:: @ 816F069
	.string "Ich rate dir, weiter zu üben.\p"
	.string "Und ich wünsche dir, dass du das Ver-\n"
	.string "gnügen des Radfahrens nie vergisst.$"

Route110_Text_16F0D0:: @ 816F0D0
	.string "Ich sage... Dein Talent zum Radfahren\n"
	.string "ist einfach miserabel.\p"
	.string "Du brauchst wirklich noch viel mehr\n"
	.string "Übung im Radfahren.$"

Route110_Text_16F139:: @ 816F139
	.string "...Ich bin entgeistert...\p"
	.string "Du hast wirklich kein Talent zum\n"
	.string "Radfahren.\p"
	.string "Du solltest ernsthaft darüber nach-\n"
	.string "denken, dein RAD bei RADLA\l"
	.string "zurückzugeben.$"

Route110_Text_16F1D0:: @ 816F1D0
	.string "Dies ist der RADWEG.\p"
	.string "Wenn du mit einem EILRAD von MALVEN-\n"
	.string "FROH CITY nach GRAPHITPORT CITY\p"
	.string "fährst, wirst du nach der Anzahl der\n"
	.string "Zusammenstöße und deiner Zeit\l"
	.string "bewertet.$"

Route110_Text_16F26A:: @ 816F26A
	.string "Unabhängig von den Resultaten möchte\n"
	.string "ich mehr Herausforderungen von dir\l"
	.string "sehen. Immer das höchste Ziel im Auge\l"
	.string "behalten!$"

Route110_Text_16F2C4:: @ 816F2C4
	.string "Auf diesem RADWEG werden die, die\n"
	.string "EILRÄDER fahren, nach ihren Zu-\l"
	.string "sammenstößen und ihrer Zeit bewertet.\p"
	.string "KUNSTRÄDER nehmen nicht an der\n"
	.string "Qualifikation teil. Sie sind zu einfach\l"
	.string "zu lenken.$"

Route110_Text_16F381:: @ 816F381
	.string "ROUTE 110\n"
	.string "{DOWN_ARROW} GRAPHITPORT CITY$"

Route110_Text_16F39C:: @ 816F39C
	.string "KÜSTENRADWEG$"

Route110_Text_16F3B1:: @ 816F3B1
	.string "“TEAM {EVIL_TEAM} HÄRRSCHD!”\p"
	.string "Das hat jemand auf das Schild\n"
	.string "gekritzelt...$"

Route110_Text_16F3E9:: @ 816F3E9
	.string "ROUTE 110\n"
	.string "{LEFT_ARROW} ROUTE 103$"

Route110_Text_16F3FF:: @ 816F3FF
	.string "KÜSTENPARKPLATZ$"

Route110_Text_16F40F:: @ 816F40F
	.string "ROUTE 110\n"
	.string "{UP_ARROW} MALVENFROH CITY$"

Route110_Text_16F429:: @ 816F429
	.string "TIPPS für TRAINER\p"
	.string "Der Gegner kann paralysiert oder\n"
	.string "in Schlaf versetzt werden und ist damit\l"
	.string "wehrlos.\p"
	.string "Das sind wichtige Techniken in einem\n"
	.string "POKéMON-Kampf.$"

Route110_Text_16F4AE:: @ 816F4AE
	.string "TIPPS für TRAINER\p"
	.string "Die Items in dem BEUTEL können mit\n"
	.string "SELECT neu geordnet werden.$"

Route110_Text_16F4F7:: @ 816F4F7
	.string "“Drei Schritte {RIGHT_ARROW} und zwei Schritte {UP_ARROW}\n"
	.string "und du erreichst das wundersame\l"
	.string "RÄTSELHAUS.”$"

Route110_Text_16F53A:: @ 816F53A
	.string "DAS BESTE ERGEBNIS...\p"
	.string "Anzahl der Zusammenstöße: {STR_VAR_1}\p"
	.string "Zeit: {STR_VAR_2}$"

Route110_Text_16F57C:: @ 816F57C
	.string "DAS BESTE ERGEBNIS...\p"
	.string "Niemand scheint sich bis jetzt der He-\n"
	.string "rausforderung gestellt zu haben...$"

UnknownString_816F5D7: @ 816F5D7
	.string "Ich gieße die Pflanzen jeden Tag.\n"
	.string "Dann bekommen sie viele Blüten.\p"
	.string "Und daraus werden dann viele BEEREN.\p"
	.string "Hier, die ist für dich.\n"
	.string "Du kannst sie haben.$"

UnknownString_816F657: @ 816F657
	.string "Ich versuche {POKEBLOCK} ROT zu machen!\n"
	.string "Ich hoffe, das versuchst du auch!$"

UnknownString_816F68A: @ 816F68A
	.string "Deine BEEREN-TASCHE ist voll.\p"
	.string "Ich gebe sie dir ein anderes Mal.$"

UnknownString_816F6CF: @ 816F6CF
	.string "Ich suche nach roten BEEREN, um\n"
	.string "{POKEBLOCK} ROT herzustellen.$"
