Route113_Text_16FF7F:: @ 816FF7F
	.string "Wahahaha! Die heutige Technologie ist\n"
	.string "schon eine wundersame Sache!\p"
	.string "Nimm zum Beispiel diese Vulkanasche\n"
	.string "hier. Aus ihr kann man Glas machen!$"

Route113_Text_16FFEE:: @ 816FFEE
	.string "Es macht Spaß, durch die Vulkanasche zu\n"
	.string "laufen, über Boden und Gras.\p"
	.string "Du kannst genau erkennen, wo du her-\n"
	.string "gelaufen bist - total klasse!$"

Route113_Text_170065:: @ 8170065
	.string "ROUTE 113\n"
	.string "{RIGHT_ARROW} ROUTE 111$"

Route113_Text_17007B:: @ 817007B
	.string "ROUTE 113\n"
	.string "{LEFT_ARROW} LAUBWECHSELFELD$"

Route113_Text_170096:: @ 8170096
	.string "TIPPS für TRAINER\p"
	.string "Du kannst eines deiner BASIS-ITEMS in\n"
	.string "deinem BEUTEL auf SELECT legen.\p"
	.string "Durch Drücken von SELECT kannst du\n"
	.string "so ganz bequem das Item einsetzen.$"

Route113_Text_17011D:: @ 817011D
	.string "GLASWERKSTATT\n"
	.string "“Glasdekor aus Vulkanasche.”$"
