RustboroCity_Mart_Text_184C76:: @ 8184C76
	.string "Ich habe einige PARA-HEILER und\n"
	.string "etwas GEGENGIFT gekauft.\p"
	.string "Nur für den Fall, dass mir ein\n"
	.string "KNILZ im BLÜTENBURGWALD\l"
	.string "über den Weg läuft.$"

RustboroCity_Mart_Text_184CD8:: @ 8184CD8
	.string "Mein POKéMON hat sich entwickelt.\n"
	.string "Es hat jetzt sehr viele KP.\p"
	.string "Ich sollte nun einige SUPERTRÄNKE\n"
	.string "anstelle der normalen TRÄNKE kaufen.$"

RustboroCity_Mart_Text_184D43:: @ 8184D43
	.string "Ich habe ein FLUCHTSEIL besorgt, falls\n"
	.string "ich mich mal in einer Höhle verlaufe.\p"
	.string "Damit kann ich zurück zum Eingang der\n"
	.string "Höhle gelangen.$"
