RustboroCity_DevonCorp_1F_Text_1828EE:: @ 81828EE
	.string "Hallo und Willkommen in der\n"
	.string "DEVON CORPORATION.\p"
	.string "Wir sind die stolzen Entwickler von\n"
	.string "Medizin und Items, die das Leben\l"
	.string "bereichern.$"

RustboroCity_DevonCorp_1F_Text_18295E:: @ 818295E
	.string "Einem Mitglied unseres Forschungsteams\n"
	.string "ist blöderweise ein wichtiges Paket\l"
	.string "gestohlen worden.$"

RustboroCity_DevonCorp_1F_Text_1829A4:: @ 81829A4
	.string "Hey, diese TURBOTRETER!\n"
	.string "Die haben wir auch entwickelt!\p"
	.string "Ich freue mich immer, wenn ich jemanden\n"
	.string "treffe, der eines unserer Produkte\l"
	.string "benutzt.$"

RustboroCity_DevonCorp_1F_Text_182A19:: @ 8182A19
	.string "Das gestohlene Paket...\p"
	.string "Nun, es ist natürlich sehr wichtig, aber\n"
	.string "mit dem Inhalt kann niemand etwas\l"
	.string "anfangen.\p"
	.string "Meiner Einschätzung nach ist der Dieb\n"
	.string "wirklich nicht sehr schlau gewesen...$"

RustboroCity_DevonCorp_1F_Text_182AB3:: @ 8182AB3
	.string "Klingt, als hätten wir die gestohlenen\n"
	.string "DEVON-WAREN zurückerhalten.$"

RustboroCity_DevonCorp_1F_Text_182AF0:: @ 8182AF0
	.string "Tut mir Leid, aber nur autorisierte\n"
	.string "Personen haben hier Zutritt.$"

RustboroCity_DevonCorp_1F_Text_182B2D:: @ 8182B2D
	.string "Das ist mehr als blöd.\n"
	.string "Wie konnten wir nur ausgeraubt werden?$"

RustboroCity_DevonCorp_1F_Text_182B5A:: @ 8182B5A
	.string "Hi, du da!\n"
	.string "Du bist hier jederzeit willkommen!$"
