RusturfTunnel_Text_194159:: @ 8194159
	.string "Was? Du willst gegen uns antreten?\n"
	.string "Na, dann hol dir eine Tracht Prügel.$"

RusturfTunnel_Text_194188:: @ 8194188
	.string "PECKO: Pii pihyoh!$"

RusturfTunnel_Text_19419B:: @ 819419B
	.string "Grrr, man sollte sie alle kielholen.\p"
	.string "Das als Geisel genommene POKéMON hat\n"
	.string "sich als völlig wertlos erwiesen!\p"
	.string "Und dafür habe ich nun einen Flucht-\n"
	.string "weg in diesem Tunnel nach Nirgendwo\l"
	.string "gegraben!\p"
	.string "Hey! Du!\n"
	.string "Forderst du mich etwa heraus?$"

RusturfTunnel_Text_194243:: @ 8194243
	.string "Aargh! Und so läuft eine viel ver-\n"
	.string "sprechende kriminelle Karriere in eine\l"
	.string "Sackgasse!$"

RusturfTunnel_Text_194274:: @ 8194274
	.string "Das ist einfach nicht fair...\p"
	.string "Der BOSS hat doch gesagt, der Job sei\n"
	.string "ein wahres Kinderspiel.\p"
	.string "Alles was ich zu tun hatte, war ein\n"
	.string "Paket von DEVON zu stehlen.\p"
	.string "Tse! Wenn du es so dringend wieder-\n"
	.string "haben willst, dann nimm es halt!$"

RusturfTunnel_Text_19432A:: @ 819432A
	.string "PECKO! Bin ich froh, dass du unversehrt\n"
	.string "wieder bei mir bist.$"

RusturfTunnel_Text_19434F:: @ 819434F
	.string "PECKO verdankt dir ihr Leben!\p"
	.string "Man nennt mich MR. BRACK.\n"
	.string "Und du bist...\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ah, du bist also {PLAYER}{KUN}!\n"
	.string "Ich danke dir von ganzem Herzen!\p"
	.string "Wenn du irgendein Problem hast, zögere\n"
	.string "nicht, mich um Hilfe zu bitten!\p"
	.string "Ich wohne in dem kleinen Haus am Meer\n"
	.string "in der Nähe des BLÜTENBURGWALDS.\p"
	.string "Komm, PECKO, wir sollten uns auf den\n"
	.string "Heimweg machen.\p"
	.string "PECKO: Pihyoh!$"

RusturfTunnel_Text_1944C5:: @ 81944C5
	.string "... ...\p"
	.string "Warum graben sie nicht weiter?\n"
	.string "Ist das Gestein zu hart?\p"
	.string "Meine Geliebte wartet in WIESENFLUR\n"
	.string "auf mich, gleich hinter diesen\l"
	.string "Felsen...\p"
	.string "Wenn METAROST CITY und WIESENFLUR\n"
	.string "durch diesen Tunnel verbunden wären,\l"
	.string "könnte ich sie jeden Tag besuchen!\p"
	.string "Aber so...\n"
	.string "Was soll ich nur machen?$"

RusturfTunnel_Text_1945B2:: @ 81945B2
	.string "Um von METAROST CITY nach WIESENFLUR\n"
	.string "zu gelangen, muss man nach FAUSTAU-\l"
	.string "HAVEN und dann über GRAPHITPORT CITY\l"
	.string "und MALVENFROH CITY reisen...$"

RusturfTunnel_Text_19461D:: @ 819461D
	.string "Wow! Du hast den Felsen, der den Weg\n"
	.string "blockierte, einfach zertrümmert.\p"
	.string "Darüber bin ich überglücklich und daher\n"
	.string "möchte ich dir diese VM geben.$"

RusturfTunnel_Text_194693:: @ 8194693
	.string "Diese VM enthält STÄRKE.\p"
	.string "Wenn ein kräftiges POKéMON diese VM\n"
	.string "lernt, ist es in der Lage, sogar die\l"
	.string "schwersten Felsen zu bewegen.$"

RusturfTunnel_Text_194706:: @ 8194706
	.string "HEIKE!\n"
	.string "Nun kann ich dich jederzeit besuchen!\p"
	.string "HEIKE: Das ist... wunderbar.\p"
	.string "Bitte, ruh dich ein bisschen in meinem\n"
	.string "Haus aus.$"

RusturfTunnel_Text_194766:: @ 8194766
	.string "Auf der anderen Seite dieses Felsens\n"
	.string "wartet mein Freund.\p"
	.string "Er... Er gräbt den Tunnel nicht nur, um\n"
	.string "mich zu sehen.\p"
	.string "Er reißt sich die Hände auf zum Wohle\n"
	.string "aller.$"

RusturfTunnel_Text_194814:: @ 8194814
	.string "Wie nennt man einen ungestümen Mann\n"
	.string "hoch im Gebirge? Einen Bergfreund.\p"
	.string "So, warum nennt man dann nicht auch ein\n"
	.string "POKéMON in den Bergen ein Berg-\l"
	.string "POKéMON?$"

RusturfTunnel_Text_1948A2:: @ 81948A2
	.string "Meine POKéMON...\n"
	.string "Haben alle Energie verloren...$"

RusturfTunnel_Text_1948C4:: @ 81948C4
	.string "Sie haben das Projekt hier einge-\n"
	.string "stellt, um die POKéMON zu schützen,\l"
	.string "nicht wahr? Eine rührende Story.$"
