RustboroCity_DevonCorp_2F_Text_182B81:: @ 8182B81
	.string "Wir wollen ein Gerät entwickeln, mit dem\n"
	.string "wir mit POKéMON reden können.\p"
	.string "Aber bisher waren wir nicht sehr\n"
	.string "erfolgreich...$"

RustboroCity_DevonCorp_2F_Text_182BD8:: @ 8182BD8
	.string "Ich entwickle neue Arten von\n"
	.string "POKéBÄLLEN...\p"
	.string "Aber noch bin ich nicht sonderlich weit\n"
	.string "mit der Entwicklung gekommen...$"

RustboroCity_DevonCorp_2F_Text_182C25:: @ 8182C25
	.string "Wir haben endlich neue POKéBÄLLE\n"
	.string "entwickelt!\p"
	.string "Mit dem WIEDERBALL lassen sich\n"
	.string "POKéMON leichter fangen, die du\l"
	.string "vorher schon mal gefangen hattest.\p"
	.string "Mit dem TIMERBALL lassen sich POKéMON\n"
	.string "umso leichter fangen, je länger der\l"
	.string "Kampf dauert.\p"
	.string "Beide werden voller Stolz von der\n"
	.string "DEVON CORPORATION präsentiert.\p"
	.string "Probiere sie bitte unbedingt aus!$"

RustboroCity_DevonCorp_2F_Text_182D2A:: @ 8182D2A
	.string "Ich habe den POKéNAV entwickelt!\p"
	.string "Als Ingenieur erfüllt es mich mit Stolz,\n"
	.string "so etwas Großartiges entwickelt zu\l"
	.string "haben.$"

RustboroCity_DevonCorp_2F_Text_182D7E:: @ 8182D7E
	.string "Oh, wow!\n"
	.string "Das ist ein POKéNAV!\p"
	.string "Er ist das Resultat der Wissbegierde\n"
	.string "unseres PRÄSIDENTEN, der etwas über\l"
	.string "die Gefühle der POKéMON lernen möchte.\p"
	.string "Soll ich dir die Funktionen im Einzelnen\n"
	.string "erklären?\p"
	.string "Ach was, du findest sie schon ganz\n"
	.string "alleine heraus.$"

RustboroCity_DevonCorp_2F_Text_182E6B:: @ 8182E6B
	.string "Ich arbeite an einer Vorrichtung, die\n"
	.string "die Träume der POKéMON visualisieren\l"
	.string "kann...\p"
	.string "Aber so richtig geht es nicht voran.$"

RustboroCity_DevonCorp_2F_Text_182ED5:: @ 8182ED5
	.string "Ich arbeite an einer Vorrichtung, die\n"
	.string "POKéMON aus Fossilien wieder zum Leben\l"
	.string "erweckt.\p"
	.string "Und... Es klappt!!!$"

RustboroCity_DevonCorp_2F_Text_182F35:: @ 8182F35
	.string "Warte! Das Teil dort...\n"
	.string "Ist das ein POKéMON-Fossil?\p"
	.string "Möchtest du das POKéMON wieder zum\n"
	.string "Leben erwecken?\p"
	.string "Ich kann dir mit meiner neuesten Ent-\n"
	.string "wicklung, dem FOSSIL-REGENERATOR,\l"
	.string "dabei helfen.$"

RustboroCity_DevonCorp_2F_Text_182FD7:: @ 8182FD7
	.string "Ehrlich?\p"
	.string "DEVON besitzt einen hervorragenden\n"
	.string "Ruf in Sachen Technik. \l"
	.string "Das versichere ich dir!$"

RustboroCity_DevonCorp_2F_Text_183023:: @ 8183023
	.string "Exzellent!\n"
	.string "Dann lass uns sofort zur Tat schreiten.\p"
	.string "{PLAYER} gibt dem FORSCHER von DEVON\n"
	.string "{STR_VAR_1}.$"

RustboroCity_DevonCorp_2F_Text_183072:: @ 8183072
	.string "Der FOSSIL-REGENERATOR, den ich ent-\n"
	.string "wickelt habe, ist einfach unglaublich.\p"
	.string "Aber einen Nachteil gibt es: Es dauert\n"
	.string "eine Weile, bis der Prozess\l"
	.string "abgeschlossen ist.\p"
	.string "Also, äh... Warum schaust du dich in der\n"
	.string "Zeit nicht ein wenig um?$"

RustboroCity_DevonCorp_2F_Text_183124:: @ 8183124
	.string "Danke für deine Geduld!\p"
	.string "Dein fossiles POKéMON wurde zu neuem\n"
	.string "Leben erweckt!\p"
	.string "Das Fossil war ein altertümliches\n"
	.string "POKéMON. Ein {STR_VAR_2}!$"

RustboroCity_DevonCorp_2F_Text_18319E:: @ 818319E
	.string "{PLAYER} erhält das {STR_VAR_2} vom\n"
	.string "FORSCHER von DEVON.$"

RustboroCity_DevonCorp_2F_Text_1831C8:: @ 81831C8
	.string "Oh oh, du hast zu viele POKéMON bei dir.\n"
	.string "Du hast keinen Platz für dieses hier.$"
