SeafloorCavern_Room1_Text_1974BA:: @ 81974BA
	.string "Wir können hier keine Kinder\n"
	.string "gebrauchen! Geh nach Hause! Sofort!$"

SeafloorCavern_Room1_Text_1974EA:: @ 81974EA
	.string "Ich will nach Hause zu meiner Mami...$"

SeafloorCavern_Room1_Text_1974FF:: @ 81974FF
	.string "Ich möchte befördert werden, dann kann\n"
	.string "ich all die RÜPEL herumkommandieren!$"

SeafloorCavern_Room1_Text_19753C:: @ 819753C
	.string "Dieses U-Boot... Es ist sehr eng.\n"
	.string "Ich habe deshalb überall blaue Flecken.$"

SeafloorCavern_Room1_Text_197573:: @ 8197573
	.string "Verlieren verursacht mir Muskelkater!$"

SeafloorCavern_Room1_Text_197589:: @ 8197589
	.string "Das U-Boot, das wir aufgetrieben haben,\n"
	.string "ist fürchterlich eng. Brutal eng, sage\l"
	.string "ich. Man stößt sich überall den Kopf.$"
