SeafloorCavern_Room3_Text_1975DC:: @ 81975DC
	.string "Ahahahahaha!\p"
	.string "Wie bist du uns ohne U-Boot gefolgt?\n"
	.string "Was für ein bemerkenswertes Kind!\p"
	.string "Aber... Das berechtigt dich nicht, hier\n"
	.string "herumzuschnüffeln!\p"
	.string "Jetzt kann ich dir die Sache vom\n"
	.string "KLIMA-INSTITUT heimzahlen...\p"
	.string "Ich gebe dir eine Lektion in Sachen\n"
	.string "Schmerz! Pass gut auf!$"

SeafloorCavern_Room3_Text_1976F3:: @ 81976F3
	.string "Ahahahahaha!\p"
	.string "Auuuaaa!$"

SeafloorCavern_Room3_Text_197704:: @ 8197704
	.string "Ahahahaha!\n"
	.string "Du bist unglaublich stark!\p"
	.string "Es ist verdammt schade, dass du kein\n"
	.string "Mitglied vom TEAM {EVIL_TEAM} bist!\p"
	.string "So könntest du an der wunderbaren,\n"
	.string "neuen Welt, die unser BOSS seinen\l"
	.string "Leuten versprochen hat, teilhaben...$"
