SlateportCity_SternsShipyard_2F_Text_17C7A2:: @ 817C7A2
	.string "Die Konstruktion eines großen Schiffes\n"
	.string "ist eher vergleichbar mit der eines\l"
	.string "Gebäudes, als eines Transportmittels.$"

SlateportCity_SternsShipyard_2F_Text_17C80C:: @ 817C80C
	.string "Findest du es nicht auch seltsam, dass\n"
	.string "ein Schiff aus Eisen gebaut wird?\p"
	.string "Es schwimmt aufgrund des so genannten\n"
	.string "Auftriebs.$"

UnknownString_817C882: @ 817C882
	.string "Die See zwischen GRAPHITPORT CITY und\n"
	.string "FLOSSBRUNN hat einen starken Ge- \l"
	.string "zeitenwechsel.\p"
	.string "Normale Schiffe können dort nicht\n"
	.string "fahren.\p"
	.string "Man braucht einen starken Antrieb,\n"
	.string "um diese Wasser befahren zu können...$"
