SlateportCity_ContestHall_Text_17CB71:: @ 817CB71
	.string "Soll ich dir einen klitzekleinen Tipp für\n"
	.string "den WETTBEWERB geben?\p"
	.string "Wenn du eine besondere Attacke nach\n"
	.string "einer bestimmten Attacke einsetzt,\l"
	.string "weckst du besondere Aufmerksamkeit.\p"
	.string "Solange du genau weißt, was du wie zu\n"
	.string "tun hast, wirst du erfolgreich sein.\p"
	.string "Natürlich werden die Mitstreiter\n"
	.string "versuchen, deinem POKéMON die Show zu\l"
	.string "stehlen.$"

SlateportCity_ContestHall_Text_17CC80:: @ 817CC80
	.string "Mein Papa ist ein JUROR des\n"
	.string "WETTBEWERBS.\p"
	.string "Ich frage mich, was ich mal werden soll:\n"
	.string "Ein JUROR oder ein ARENALEITER?$"

SlateportCity_ContestHall_Text_17CCE2:: @ 817CCE2
	.string "Hey, also, das ist wohl Künstlerpech,\n"
	.string "Mann. Ich will einfach wissen, warum\l"
	.string "mein POKéMON nie gewinnt.\l"
	.string "Weißt du, Mann?\p"
	.string "Daher, Mann, habe ich dem JUROR meinen\n"
	.string "Senf dazugegeben.\p"
	.string "Und der hat nicht einmal zugehört, Mann!\n"
	.string "Das ist vielleicht eine Niete.\p"
	.string "Hey! Zieh dir das mal rein!\n"
	.string "Hier, Mann, das ist für dich!$"

SlateportCity_ContestHall_Text_17CE28:: @ 817CE28
	.string "Das ist die TM41, weißt du?\n"
	.string "Hey, das ist FOLTERKNECHT, sag ich dir.\p"
	.string "Der Gegner wird so daran gehindert, eine\n"
	.string "Attacke zweimal hintereinander\l"
	.string "auszuführen.\p"
	.string "Aber nun hör mir gut zu. Ich würde NIE\n"
	.string "FOLTERKNECHT gegen dich einsetzen.$"

SlateportCity_ContestHall_Text_17CEF3:: @ 817CEF3
	.string "MC: Oh, meine Güte!\n"
	.string "Ist das nicht ein Dandy von POKéMON?\p"
	.string "Bitte! Tritt näher und nimm an unserem\n"
	.string "großartigen WETTBEWERB teil!\p"
	.string "Ich bin sicher, du wirst hervorragend\n"
	.string "abschneiden. Meine Augen täuschen\l"
	.string "mich nie!$"

SlateportCity_ContestHall_Text_17CFA7:: @ 817CFA7
	.string "JUROR: Hallo, du da!\n"
	.string "Wie ich sehe, bist du ein TRAINER!\p"
	.string "Nun, dann kannst du es dir eigentlich\n"
	.string "nicht leisten, einen WETTBEWERB zu\l"
	.string "verpassen!\p"
	.string "Hol dir in WIESENFLUR eine\n"
	.string "WETTBEWERBSKARTE und nimm teil!$"

SlateportCity_ContestHall_Text_17D054:: @ 817D054
	.string "Showtime!\n"
	.string "Womit soll ich beginnen?$"

SlateportCity_ContestHall_Text_17D07F:: @ 817D07F
	.string "Der Auftritt meines POKéMON fand\n"
	.string "nicht viel Beachtung...\p"
	.string "Männo, der Juror hat wohl Tomaten auf\n"
	.string "den Augen!?!$"

SlateportCity_ContestHall_Text_17D0F9:: @ 817D0F9
	.string "Oh, hi! Du musst ein wirklich großer Fan\n"
	.string "sein, wenn du so nah herangehst.\p"
	.string "Ich belohne deinen Enthusiasmus mit\n"
	.string "einem weisen Rat.\p"
	.string "Wenn eine Attacke wirklich gut gelingt,\n"
	.string "ist das Publikum begeistert.\p"
	.string "Wenn alle begeistert sind, hat das\n"
	.string "POKéMON einen tollen Auftritt gehabt.\p"
	.string "Dann weißt du, dass etwas Tolles\n"
	.string "passieren wird!$"

SlateportCity_ContestHall_Text_17D222:: @ 817D222
	.string "Ich kann es einfach nicht! Ich bin\n"
	.string "nervöser als mein POKéMON.\p"
	.string "Ich zittere und mein Herz rast!$"

SlateportCity_ContestHall_Text_17D27F:: @ 817D27F
	.string "Ein Kampf und ein WETTBEWERB sind nicht\n"
	.string "dasselbe, aber sie sind sich ähnlich.\p"
	.string "Du musst hart arbeiten und an die\n"
	.string "POKéMON, die du aufziehst, glauben.$"

SlateportCity_ContestHall_Text_17D300:: @ 817D300
	.string "Dieses POKéMON scheint an der Spitze\n"
	.string "zu stehen, was?\p"
	.string "Ein POKéMON, das im zweiten Durchgang\n"
	.string "gut abschneidet, wird im Wettbewerb\l"
	.string "viel ruhiger auftreten.$"

SlateportCity_ContestHall_Text_17D39A:: @ 817D39A
	.string "Guck dir mal diese jämmerlichen\n"
	.string "Gestalten an.\p"
	.string "Mein POKéMON ist viel, viel besser als\n"
	.string "dieser Haufen!$"

SlateportCity_ContestHall_Text_17D3F0:: @ 817D3F0
	.string "Geht es dir nicht auch so? Wenn ein\n"
	.string "POKéMON all seine Energie in eine\l"
	.string "Attacke steckt, bewegt mich das enorm.$"

SlateportCity_ContestHall_Text_17D447:: @ 817D447
	.string "POKéMON WETTBEWERBE\n"
	.string "BÜHNE für die HYPER-KLASSE!$"
