SlateportCity_OceanicMuseum_2F_Text_17ECFD:: @ 817ECFD
	.string "Ja? Wenn du BRIGG suchst... Der\n"
	.string "bin ich.\p"
	.string "Ah! Das müssen die Stücke sein, die ich\n"
	.string "bei MR. TRUMM von DEVON bestellt habe.\p"
	.string "Danke schön! Das ist großartig!\n"
	.string "Nun können wir unsere Expedition\l"
	.string "vorbereiten.$"

SlateportCity_OceanicMuseum_2F_Text_17EDAE:: @ 817EDAE
	.string "Hähähähä! Wartet! Das ist doch viel zu\n"
	.string "schwer für euch! Wir nehmen das an uns!$"

SlateportCity_OceanicMuseum_2F_Text_17EDD7:: @ 817EDD7
	.string "KAPT. BRIGG: W... Was?\n"
	.string "Wer seid ihr?$"

SlateportCity_OceanicMuseum_2F_Text_17EE01:: @ 817EE01
	.string "Wir sind TEAM {EVIL_TEAM}!\p"
	.string "Unser BOSS will diese Dinge haben!\n"
	.string "Also hört auf zu labern und lasst die\l"
	.string "Teile rüberwachsen!$"

SlateportCity_OceanicMuseum_2F_Text_17EE4E:: @ 817EE4E
	.string "Oooaaah!\n"
	.string "Geschlagen von einem KIND!$"

SlateportCity_OceanicMuseum_2F_Text_17EE66:: @ 817EE66
	.string "Oh, Mann! Was für ein Desaster...\n"
	.string "Der BOSS wird verdammt wütend sein...$"

SlateportCity_OceanicMuseum_2F_Text_17EEA5:: @ 817EEA5
	.string "Pah, du Waschlappen!\n"
	.string "Ich werde das Ding schon schaukeln!$"

SlateportCity_OceanicMuseum_2F_Text_17EED6:: @ 817EED6
	.string "Was?!?\n"
	.string "Ich habe auch verloren?!?$"

SlateportCity_OceanicMuseum_2F_Text_17EEEA:: @ 817EEEA
	.string "Und nun? Wenn wir die Stücke nicht\n"
	.string "bekommen, können wir uns auf etwas\l"
	.string "gefasst machen!\p"
	.string "Argh, ich hatte nicht damit gerechnet,\n"
	.string "dass ein nervendes Kind meine Nerven\l"
	.string "nervt.$"

SlateportCity_OceanicMuseum_2F_Text_17EF62:: @ 817EF62
	.string "Ich bin gekommen, um zu sehen, warum ihr\n"
	.string "so lange braucht. Und was sehe ich? Ihr\l"
	.string "Idioten lasst euch von einem kleinen\l"
	.string "Kind die Suppe versalzen!$"

SlateportCity_OceanicMuseum_2F_Text_17EFC9:: @ 817EFC9
	.string "Ich bin ADRIAN vom TEAM AQUA.\p"
	.string "Kannst du mir verraten, warum du dich in\n"
	.string "die ehrbaren Pläne von TEAM AQUA ein-\l"
	.string "mischst?\p"
	.string "POKéMON, Menschen - alles Leben\n"
	.string "basiert auf den Kräften des Meeres.\p"
	.string "Daher setzt TEAM AQUA sich für die\n"
	.string "Ausweitung des Meeres ein.\p"
	.string "Meinst du nicht auch, dass wir uns eine\n"
	.string "großartige Aufgabe gestellt haben?\p"
	.string "Mhm...\n"
	.string "Du bist wahrscheinlich noch zu klein.\p"
	.string "Du kannst unsere Ideale einfach noch\n"
	.string "nicht verstehen.\p"
	.string "Aber: Wenn du dich jemals wieder gegen\n"
	.string "uns stellst, wirst du die Konsequenzen\l"
	.string "zu spüren bekommen!\p"
	.string "Das ist eine Warnung!\n"
	.string "Leb wohl!$"

SlateportCity_OceanicMuseum_2F_Text_17F17E:: @ 817F17E
	.string "Ich bin MARC vom TEAM MAGMA.\p"
	.string "Himmel noch mal! Warum mischst du dich in\n"
	.string "die Pläne von TEAM MAGMA ein?\p"
	.string "POKéMON, Menschen - alles lebt an Land...\p"
	.string "Deshalb versucht TEAM MAGMA, die Land-\n"
	.string "massen der Welt zu vergrößern.\p"
	.string "Meinst du nicht auch, dass wir wirklich\n"
	.string "etwas Großartiges vorhaben?\p"
	.string "Nun, wie auch immer...\n"
	.string "Du bist noch sehr jung.\p"
	.string "Daher kannst du unsere noblen Ideale\n"
	.string "noch nicht verstehen. Da kann man\l"
	.string "nichts machen...\p"
	.string "Aber, solltest du uns noch einmal in\n"
	.string "die Quere kommen, werden wir keine\l"
	.string "Rücksicht nehmen!\p"
	.string "Das solltest du nicht vergessen!\n"
	.string "Leb wohl!$"

SlateportCity_OceanicMuseum_2F_Text_17F352:: @ 817F352
	.string "KAPT. BRIGG: Du bist...\n"
	.string "Aah, du bist {PLAYER}{KUN}...\p"
	.string "Wow, das war eine kritische Situation!\n"
	.string "Danke, dass du uns gerettet hast!\p"
	.string "Oh, fast hätte ich vergessen, dass du\n"
	.string "uns die Teile von DEVON gebracht hast!$"

UnknownString_817F404: @ 817F404
	.string "{PLAYER} gibt die DEVON-WAREN an\n"
	.string "KAPT. BRIGG.$"

SlateportCity_OceanicMuseum_2F_Text_17F433:: @ 817F433
	.string "KAPT. BRIGG: Hoppla!\n"
	.string "Wir dürfen keine Zeit mehr verlieren!\p"
	.string "Wir müssen so schnell wie möglich zur Ex-\n"
	.string "pedition zum Meeresgrund aufbrechen.\p"
	.string "Danke! Und entschuldige mich nun!$"

SlateportCity_OceanicMuseum_2F_Text_17F4B6:: @ 817F4B6
	.string "Ich habe hier ein Schiffsmodell\n"
	.string "gesehen.\p"
	.string "Es erinnert mich an das SCHIFFSWRACK\n"
	.string "in der Nähe von FAUSTAUHAVEN...$"

SlateportCity_OceanicMuseum_2F_Text_17F50E:: @ 817F50E
	.string "Es ist strikt verboten, im MUSEUM\n"
	.string "zu rennen!$"

SlateportCity_OceanicMuseum_2F_Text_17F53B:: @ 817F53B
	.string "Wow, das U-Boot ist der helle Wahnsinn!\n"
	.string "Damit würde ich gerne auf Fahrt gehen!$"

SlateportCity_OceanicMuseum_2F_Text_17F572:: @ 817F572
	.string "“KANTO WASSERQUALITÄT”\n"
	.string "steht auf dem Schild.\p"
	.string "Das Meer ist grenzübergreifend, aber\n"
	.string "das Wasser scheint in jeder Region eine\l"
	.string "andere Qualität zu haben.$"

SlateportCity_OceanicMuseum_2F_Text_17F5E3:: @ 817F5E3
	.string "“JOHTO WASSERQUALITÄT”\n"
	.string "steht auf dem Schild.\p"
	.string "Anscheinend ist der Salzgehalt in jeder\n"
	.string "Region anders.$"

SlateportCity_OceanicMuseum_2F_Text_17F653:: @ 817F653
	.string "Ein Gummiball wird größer und kleiner.\p"
	.string "“Im Meer sorgt das Gewicht des Wassers\n"
	.string "für ständigen Druck.\p"
	.string "In seichtem Wasser ist der Druck nicht\n"
	.string "sehr hoch.\p"
	.string "In extrem tiefem Wasser kann der\n"
	.string "Druck zehntausende von Tonnen inner-\l"
	.string "halb eines kleinen Bereiches betragen.”$"

SlateportCity_OceanicMuseum_2F_Text_17F754:: @ 817F754
	.string "“MODELL DER HOENN-REGION”\p"
	.string "Ein Diorama der HOENN-Region.\p"
	.string "Wo liegt hier WURZELHEIM?$"

SlateportCity_OceanicMuseum_2F_Text_17F7BC:: @ 817F7BC
	.string "Dies ist eine Anzeige der Meeres-\n"
	.string "strömungen.\p"
	.string "“In der Nähe des Meeresbodens sind die\n"
	.string "Strömungen abhängig von Faktoren wie\l"
	.string "Temperatur und Salzgehalt.”$"

SlateportCity_OceanicMuseum_2F_Text_17F84E:: @ 817F84E
	.string "Dies ist eine Anzeige der Meeres-\n"
	.string "strömungen.\p"
	.string "“An der Oberfläche sind die Strömungen\n"
	.string "abhängig vom Einfluss des Windes.”$"

SlateportCity_OceanicMuseum_2F_Text_17F8BC:: @ 817F8BC
	.string "“DIE FÄHRE MS TIDE”\p"
	.string "“Ein maßstabsgetreues Modell eines\n"
	.string "Schiffes unter Konstruktion in der\l"
	.string "BRIGGWERFT.”$"

SlateportCity_OceanicMuseum_2F_Text_17F918:: @ 817F918
	.string "“TIEFSEE-FORSCHUNGSBOOT 1”\p"
	.string "“Ein Replikat des Hochleistungs-\n"
	.string "U-Bootes zur Erforschung des\l"
	.string "Meeresbodens.”$"

SlateportCity_OceanicMuseum_2F_Text_17F975:: @ 817F975
	.string "“TAUCHBOOT”\p"
	.string "“Ein Replikat eines kompakten,\n"
	.string "unbemannten Spezial-U-Bootes zur Er-\l"
	.string "forschung des Meeresbodens.”$"

SlateportCity_OceanicMuseum_2F_Text_17F9C7:: @ 817F9C7
	.string "“MS ANNE”\p"
	.string "“Ein Replikat eines Luxusliners, der\n"
	.string "um den Globus kreuzt.”$"
