SlateportCity_Harbor_Text_17FA0A:: @ 817FA0A
	.string "Verzeihung?\n"
	.string "Du suchst nach einem Schiff?\p"
	.string "Oh, das tut mir Leid, aber die Fähre\n"
	.string "steht momentan nicht zur Verfügung...$"

SlateportCity_Harbor_Text_17FA73:: @ 817FA73
	.string "Hallo! Möchtest du mit der Fähre fahren?\n"
	.string "Zeigst du mir bitte dein TICKET?$"

SlateportCity_Harbor_Text_17FAAD:: @ 817FAAD
	.string "{PLAYER} hat kein TICKET...\p"
	.string "Das tut mir schrecklich Leid.\p"
	.string "Nur mit einem TICKET kannst du mit der\n"
	.string "Fähre fahren.$"

SlateportCity_Harbor_Text_17FB0A:: @ 817FB0A
	.string "{PLAYER} zückt das TICKET.\p"
	.string "Perfekt! Damit kannst du an Bord!\p"
	.string "Und wo soll die Reise hingehen?$"

SlateportCity_Harbor_Text_17FB5F:: @ 817FB5F
	.string "Bitte komm später noch einmal wieder!$"

SlateportCity_Harbor_Text_17FB81:: @ 817FB81
	.string "Nach SEEGRASULB CITY?$"

SlateportCity_Harbor_Text_17FB9C:: @ 817FB9C
	.string "Zum DUELLTURM?$"

SlateportCity_Harbor_Text_17FBB6:: @ 817FBB6
	.string "Bitte komm an Bord. Wir legen bald ab.$"

SlateportCity_Harbor_Text_17FBE5:: @ 817FBE5
	.string "Und wo soll die Reise hingehen?$"

SlateportCity_Harbor_Text_17FC07:: @ 817FC07
	.string "Eine Reise zum Meeresboden...\n"
	.string "Ich frage mich, wie es dort wohl ist?\p"
	.string "Eines Tages möchte ich auch einmal so\n"
	.string "tief unter Wasser reisen.$"

SlateportCity_Harbor_Text_17FC7C:: @ 817FC7C
	.string "Ich wäre gerne mit KAPT. BRIGG auf die\n"
	.string "Expedition zum Meeresboden gegangen.\p"
	.string "Aber das U-Boot ist zu klein für mich.\p"
	.string "Ich könnte mich ja reinquetschen, aber\n"
	.string "dann hätte der KAPITÄN keinen Platz\l"
	.string "mehr...$"

SlateportCity_Harbor_Text_17FD1C:: @ 817FD1C
	.string "KAPT. BRIGG: Diese Schlägertypen...\p"
	.string "Das sind die gleichen Typen, die\n"
	.string "versucht haben, die DEVON-WAREN aus\l"
	.string "dem MUSEUM zu stehlen.$"

SlateportCity_Harbor_Text_17FD7D:: @ 817FD7D
	.string "{EVIL_LEADER}: Ahahahahaha!!!!!\n"
	.string "Du tust mir ja so Leid!\p"
	.string "All die Mühen, um mir vom PYROBERG\n"
	.string "bis hierher zu folgen...\p"
	.string "Und nun...\n"
	.string "Niemand kann uns stoppen! Niemand!!!\p"
	.string "Oder willst du uns etwa in unser VER-\n"
	.string "STECK in SEEGRASULB CITY folgen?\p"
	.string "Ahahahahaha!!!!!$"

SlateportCity_Harbor_Text_17FE60:: @ 817FE60
	.string "KAPT. BRIGG: Warum...\p"
	.string "Warum sollte TEAM {EVIL_TEAM} mein TIEF-\n"
	.string "SEE-FORSCHUNGSBOOT 1 stehlen wollen?\p"
	.string "Sie können doch nicht hinter dem\n"
	.string "schlafenden POKéMON am Meeresgrund\l"
	.string "her sein...\p"
	.string "Selbst wenn ich sie verfolgen würde...\n"
	.string "Ich hätte keine Chance gegen sie...$"

SlateportCity_Harbor_Text_17FF35:: @ 817FF35
	.string "KAPT. BRIGG: Oh, {PLAYER}{KUN}...\p"
	.string "Okay... Du konntest TEAM {EVIL_TEAM} nicht\n"
	.string "aufhalten...\p"
	.string "Oh, nein, mach dir bitte keine Vorwürfe!\n"
	.string "Die Schuld liegt nicht bei dir.\p"
	.string "Ein U-Boot zu verfolgen und aufzu-\n"
	.string "halten ist für die meisten Menschen\l"
	.string "unmöglich.\p"
	.string "Du benötigst ein POKéMON, das weiß, wie\n"
	.string "man TAUCHER ausführt...\p"
	.string "Vielleicht, wenn du dich nach\n"
	.string "MOOSBACH CITY begibst...\p"
	.string "Dort trifft man auf viele Taucher.\n"
	.string "Vielleicht kann dir einer das\l"
	.string "beibringen...$"

SlateportCity_Harbor_Text_1800A0:: @ 81800A0
	.string "KAPT. BRIGG: Ein U-Boot einzuholen und\n"
	.string "aufzuhalten... Das ist unmöglich.\p"
	.string "Du benötigst ein POKéMON, das weiß, wie\n"
	.string "man TAUCHER ausführt...\p"
	.string "Vielleicht, wenn du dich nach\n"
	.string "MOOSBACH CITY begibst...\p"
	.string "Dort trifft man auf viele Taucher, \n"
	.string "vielleicht kann dir einer das bei-\l"
	.string "bringen...$"

SlateportCity_Harbor_Text_18017B:: @ 818017B
	.string "KAPT. BRIGG: Oh, ja.\n"
	.string "MR. BRACK kam in unsere WERFT.\p"
	.string "Nun dauert es nicht mehr lange, bis wir\n"
	.string "unsere Fähre fertig stellen!$"

SlateportCity_Harbor_Text_1801EA:: @ 81801EA
	.string "KAPT. BRIGG: {PLAYER}{KUN}!\p"
	.string "Wir haben die Fähre MS TIDE endlich\n"
	.string "fertig gestellt.\p"
	.string "Ohne die Hilfe deines Freundes MR.\n"
	.string "BRACK hätten wir das nicht geschafft.\p"
	.string "Bitte, nimm an einer kurzen Fahrt teil!$"

SlateportCity_Harbor_Text_18028B:: @ 818028B
	.string "KAPT. BRIGG: Oh?\n"
	.string "{PLAYER}{KUN}, das Item, das du da hast...\p"
	.string "Das ist ein SCANNER! Der würde uns\n"
	.string "sicher bei unseren Forschungen helfen.\p"
	.string "{PLAYER}{KUN}, würdest du ihn gegen etwas\n"
	.string "anderes eintauschen?\p"
	.string "Zum Beispiel gegen einen ABYSSZAHN\n"
	.string "oder eine ABYSSPLATTE?$"

SlateportCity_Harbor_Text_180360:: @ 8180360
	.string "KAPT. BRIGG: Bist du sicher? Aber damit\n"
	.string "kannst du doch nichts anfangen...\p"
	.string "Also gut. Wenn du aber den SCANNER doch\n"
	.string "noch gegen etwas anderes tauschen\l"
	.string "willst, dann lass es mich wissen!$"

SlateportCity_Harbor_Text_1803DD:: @ 81803DD
	.string "KAPT. BRIGG: Du möchtest den\n"
	.string "ABYSSZAHN dafür haben?$"

SlateportCity_Harbor_Text_180412:: @ 8180412
	.string "KAPT. BRIGG: Du möchtest die\n"
	.string "ABYSSPLATTE dafür haben?$"

SlateportCity_Harbor_Text_180447:: @ 8180447
	.string "KAPT. BRIGG: Was hättest du gerne?$"

SlateportCity_Harbor_Text_18046B:: @ 818046B
	.string "{PLAYER} gibt KAPT. BRIGG den SCANNER.$"

SlateportCity_Harbor_Text_180491:: @ 8180491
	.string "KAPT. BRIGG: Danke, {PLAYER}{KUN}!\n"
	.string "Das wird unsere Forschungen weiter-\l"
	.string "bringen!$"
