SlateportCity_House2_Text_1804CF:: @ 81804CF
	.string "Mein POKéMON hat ein HASTIGES Wesen.\p"
	.string "Seine INITIATIVE ist im Vergleich\n"
	.string "zu meinen anderen POKéMON höher.\p"
	.string "Vielleicht hat ihr Wesen etwas mit den\n"
	.string "Statusvorteilen der POKéMON zu tun.$"

SlateportCity_House2_Text_180567:: @ 8180567
	.string "Um an dem WETTBEWERB teilnehmen zu\n"
	.string "können, brauchst du eine\l"
	.string "WETTBEWERBSKARTE.\p"
	.string "Die bekommst du leicht. Jeder, der ein\n"
	.string "POKéMON hat, bekommt eine.$"

SlateportCity_House2_Text_1805CD:: @ 81805CD
	.string "Oh, eine WETTBEWERBSKARTE!\n"
	.string "Bist du auch ein Bewerber?$"
