SSTidalRooms_Text_19956B:: @ 819956B
	.string "Ein warmes, weiches Bett...\n"
	.string "Machen wir doch ein kleines Schläfchen.$"

SSTidalRooms_Text_19958A:: @ 819958A
	.string "Ich pendle ständig zwischen\n"
	.string "SEEGRASULB CITY und GRAPHITPORT CITY.\p"
	.string "Das ist mein Hobby - ich gehe von Stadt\n"
	.string "zu Stadt und nehme an POKéMON\l"
	.string "WETTBEWERBEN teil.$"

SSTidalRooms_Text_199613:: @ 8199613
	.string "Das war ein wunderbarer Kampf!$"

SSTidalRooms_Text_199630:: @ 8199630
	.string "Ich bin schon ganz aufgeregt, wenn ich\n"
	.string "mir vorstelle, welche POKéMON ich im\l"
	.string "nächsten WETTBEWERB sehen werde!$"

SSTidalRooms_Text_1996A6:: @ 81996A6
	.string "Sind deine Freunde stark?$"

SSTidalRooms_Text_1996BF:: @ 81996BF
	.string "Deine Freunde sind in der Tat stark.$"

SSTidalRooms_Text_1996E1:: @ 81996E1
	.string "Freunde müssen nicht unbedingt\n"
	.string "menschlich sein. Für mich sind\l"
	.string "POKéMON die besten Freunde.$"

SSTidalRooms_Text_199723:: @ 8199723
	.string "Kind...\n"
	.string "Hast du an der Tür geklopft?$"

SSTidalRooms_Text_199747:: @ 8199747
	.string "Eine Niederlage muss mit aufrechtem\n"
	.string "Kopf akzeptiert werden.$"

SSTidalRooms_Text_199778:: @ 8199778
	.string "In jeder Situation die absolute Ruhe zu\n"
	.string "bewahren, ist die Devise des GENTLEMAN.$"

SSTidalRooms_Text_1997C1:: @ 81997C1
	.string "UWE: Eigentlich bin ich ja schüchtern...\n"
	.string "Aber die Liebe gibt einem Kraft!$"

SSTidalRooms_Text_199813:: @ 8199813
	.string "UWE: Seufz...$"

SSTidalRooms_Text_199820:: @ 8199820
	.string "UWE: Zum ersten Mal war unsere Kraft\n"
	.string "der Liebe unterlegen!\l"
	.string "Du bist ein unglaublicher TRAINER!$"

SSTidalRooms_Text_199887:: @ 8199887
	.string "UWE: Du hast nur ein POKéMON?\n"
	.string "Fühlt es sich nicht sehr einsam?$"

SSTidalRooms_Text_1998C5:: @ 81998C5
	.string "LENA: Ich fühle mich etwas albern,\n"
	.string "aber... Aber die Liebe gibt mir Kraft!$"

SSTidalRooms_Text_19990E:: @ 819990E
	.string "LENA: Oh, buuuuh!$"

SSTidalRooms_Text_19991C:: @ 819991C
	.string "LENA: Ich kann es einfach nicht fassen!\n"
	.string "Die Kraft unserer Liebe reichte nicht...\l"
	.string "Du bist ein unglaublicher TRAINER!$"

SSTidalRooms_Text_199975:: @ 8199975
	.string "LENA: Ich möchte kämpfen...\n"
	.string "Aber du hast nur ein POKéMON...$"

SSTidalRooms_Text_1999B7:: @ 81999B7
	.string "Ah, du kommst gerade rechtzeitig.\p"
	.string "Ich langweile mich schrecklich.\n"
	.string "Du musst mich jetzt unterhalten.$"

SSTidalRooms_Text_1999FF:: @ 81999FF
	.string "...Das reicht.$"

SSTidalRooms_Text_199A10:: @ 8199A10
	.string "Ich muss meinen Vater unbedingt\n"
	.string "fragen, ob er mir eine Yacht schenkt.\l"
	.string "Eine Yacht für mich und meine POKéMON!$"

SSTidalRooms_Text_199A62:: @ 8199A62
	.string "Oh, du bist so ein wunderbarer TRAINER.\n"
	.string "Möchtest du eine Tasse Tee?\l"
	.string "Oder möchtest du lieber kämpfen?$"

SSTidalRooms_Text_199ABF:: @ 8199ABF
	.string "Ich verstehe.\n"
	.string "Du bist eher der aktive Typ.$"

SSTidalRooms_Text_199ADE:: @ 8199ADE
	.string "Eine Weltreise auf einem Luxusliner hat\n"
	.string "etwas für sich, das muss ich sagen...\p"
	.string "Aber auch eine Fahrt auf der Fähre\n"
	.string "durch HOENN hat etwas.$"

SSTidalRooms_Text_199B65:: @ 8199B65
	.string "Äh... Hallo! Ich... Ich verhalte mich über-\n"
	.string "haupt nicht verdächtig! Äh... hier, das\l"
	.string "ist für dich! Es kostet dich nichts!\p"
	.string "Es... Ehrlich! Ich habe es nicht von\n"
	.string "jemandem ÜBERNOMMEN! Das würde ich\l"
	.string "nie tun! Es ist sauber! Nimm es ruhig!$"

SSTidalRooms_Text_199C1A:: @ 8199C1A
	.string "ÜBERNAHME raubt die nächste Attacke\n"
	.string "eines POKéMON und setzt sie dann\l"
	.string "gegen diesen Gegner ein.$"
