VerdanturfTown_Mart_Text_1781C9:: @ 81781C9
	.string "X-SPEZIAL ist für jeden POKéMON-Kampf\n"
	.string "äußerst wichtig.\p"
	.string "Es erhöht die Stärke mancher Attacken.\n"
	.string "Aber leider nur für einen Kampf.$"

VerdanturfTown_Mart_Text_178240:: @ 8178240
	.string "Sie verkaufen keine Items, mit denen\n"
	.string "man einen WETTBEWERB gewinnen kann...\p"
	.string "Und das bedeutet, dass du deine\n"
	.string "POKéMON mit äußerster Sorgfalt\l"
	.string "aufziehen musst.$"

VerdanturfTown_Mart_Text_1782C0:: @ 81782C0
	.string "Der NESTBALL ist bei schwächeren\n"
	.string "POKéMON hervorragend geeignet.\p"
	.string "Den kannst du nur in WIESENFLUR\n"
	.string "kaufen.$"
