VerdanturfTown_Text_16CAEB:: @ 816CAEB
	.string "Mein Papa hat mir das erzählt.\p"
	.string "Er sagt, der Tunnel sei voller scheuer\n"
	.string "POKéMON.\p"
	.string "Sie haben Angst vor lauten Geräuschen\n"
	.string "und machen einen Aufruhr.\p"
	.string "Daher musste das Tunnelprojekt\n"
	.string "gestoppt werden.\p"
	.string "Aber es gibt da einen Mann. Der ver-\n"
	.string "sucht, den Tunnel alleine zu graben.$"

VerdanturfTown_Text_16CBCE:: @ 816CBCE
	.string "Da war ein Mann, der hat den Tunnel\n"
	.string "ganz alleine für die Frau seines Herzens\l"
	.string "gegraben.\p"
	.string "Ich habe das nie so ganz verstanden.\n"
	.string "Aber, hey, ich finde es trotzdem klasse.$"

VerdanturfTown_Text_16CC24:: @ 816CC24
	.string "Der Wind steht immer so günstig, dass\n"
	.string "die Asche vom Vulkan nie hierher\l"
	.string "geweht wird.\p"
	.string "Die Luft ist sauber und klar.\n"
	.string "Hier zu leben hilft auch den schwachen\l"
	.string "und kränklichen Menschen.$"

VerdanturfTown_Text_16CCD0:: @ 816CCD0
	.string "Ich bin doch zufrieden mit der Anmut\n"
	.string "meiner POKéMON.\p"
	.string "Ich möchte hier zum ersten Mal an einem\n"
	.string "WETTBEWERB teilnehmen.$"

VerdanturfTown_Text_16CD4D:: @ 816CD4D
	.string "Siehst du die Höhle neben dem PKMN-\n"
	.string "SUPERMARKT?\p"
	.string "Da ist ein Typ drin, der die Felsbrocken\n"
	.string "sprengen will, damit er auf die andere\l"
	.string "Seite gehen kann.\p"
	.string "Wäre das toll, wenn ich auch dort durch-\n"
	.string "gehen könnte... Ein Besuch in\l"
	.string "METAROST CITY wäre dann ganz einfach.$"

VerdanturfTown_Text_16CE30:: @ 816CE30
	.string "Die Höhle neben dem PKMN-SUPERMARKT\n"
	.string "ist nun ein Tunnel zur anderen Seite.\p"
	.string "Das ist toll! Jetzt kommt man ganz\n"
	.string "einfach nach METAROST CITY, um\l"
	.string "DEVON-WAREN zu kaufen.$"

VerdanturfTown_Text_16CEC0:: @ 816CEC0
	.string "WIESENFLUR\p"
	.string "“Das vom Wind gestreichelte Hoch-\n"
	.string "land mit dem süßen Duft des Grases.”$"

VerdanturfTown_Text_16CF0D:: @ 816CF0D
	.string "HEIKES HAUS$"

VerdanturfTown_Text_16CF1B:: @ 816CF1B
	.string "POKéMON WETTBEWERBE\n"
	.string "NORMAL-KLASSE REGISTRIERUNGEN\p"
	.string "“Kommt her, all ihr POKéMON-TRAINER!”$"

VerdanturfTown_Text_16CF6D:: @ 816CF6D
	.string "METAFLURTUNNEL\n"
	.string "“Die Verbindung zwischen\l"
	.string "METAROST CITY und WIESENFLUR.\p"
	.string "Das Tunnelprojekt wurde abgebrochen.”$"
