VictoryRoad_B1F_Text_197CE9:: @ 8197CE9
	.string "Der Gedanke, dass ich der POKéMON LIGA\n"
	.string "immer näher komme...\p"
	.string "Ich bekomme Lampenfieber...$"

VictoryRoad_B1F_Text_197D42:: @ 8197D42
	.string "Ich konnte gar nichts machen...$"

VictoryRoad_B1F_Text_197D5B:: @ 8197D5B
	.string "Die POKéMON LIGA rückt in weite Ferne...\n"
	.string "Was für eine Enttäuschung...$"

VictoryRoad_B1F_Text_197D98:: @ 8197D98
	.string "Um dich siegreich durch die POKéMON\n"
	.string "LIGA zu kämpfen, brauchst du das\l"
	.string "Vertrauen deiner POKéMON.$"

VictoryRoad_B1F_Text_197DE8:: @ 8197DE8
	.string "Eure Beziehung ist auf solidem\n"
	.string "Vertrauen aufgebaut.$"

VictoryRoad_B1F_Text_197E13:: @ 8197E13
	.string "Das Vertrauen zwischen POKéMON und\n"
	.string "TRAINER wächst beständig, da sie immer\l"
	.string "zusammen sind.$"

VictoryRoad_B1F_Text_197E5D:: @ 8197E5D
	.string "Das ist nicht das Ziel. Nur eine\n"
	.string "Zwischenstation auf dem Weg zur\l"
	.string "POKéMON LIGA.$"

VictoryRoad_B1F_Text_197EA6:: @ 8197EA6
	.string "Das ist der Weg!$"

VictoryRoad_B1F_Text_197EB6:: @ 8197EB6
	.string "Du wirst dich sehr gut schlagen, das ist\n"
	.string "sicher. Deine POKéMON lieben dich!$"
