SootopolisCity_House2_EventObjects:: @ 838AFF8
	object_event 1, EVENT_OBJ_GFX_OLD_WOMAN_1, 0, 3, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SootopolisCity_House2_EventScript_15B2E5, 0

SootopolisCity_House2_MapWarps:: @ 838B010
	warp_def 3, 6, 0, 5, MAP_SOOTOPOLIS_CITY
	warp_def 4, 6, 0, 5, MAP_SOOTOPOLIS_CITY

SootopolisCity_House2_MapEvents:: @ 838B020
	map_events SootopolisCity_House2_EventObjects, SootopolisCity_House2_MapWarps, 0x0, 0x0
