SootopolisCity_House2_Text_DidYouKnowAboutMtPyreOrbs:: @ 818FA66
	.string "MT. PYRE...\p"
	.string "At its peak are two orbs placed side\n"
	.string "by side. Did you know?$"

SootopolisCity_House2_Text_YesTwoOrbsSideBySide:: @ 818FAAE
	.string "Yes, two orbs side by side...\p"
	.string "The sight of them together...\n"
	.string "It is somehow soothing...$"

SootopolisCity_House2_Text_OughtToVisitAndSee:: @ 818FB04
	.string "Is that so?\n"
	.string "Perhaps you ought to visit and see...$"
