SlateportCity_SternsShipyard_1F_Text_17C14B:: @ 817C14B
	.string "Ähmm... Wenn das hierhin gehört und das\n"
	.string "dahin...\p"
	.string "Wo gehört dieses dann hin?\n"
	.string "Und was ist mit diesem Dingsbums?\p"
	.string "Aaargh! Ich werde daraus einfach nicht\n"
	.string "schlau!$"

SlateportCity_SternsShipyard_1F_Text_17C1EC:: @ 817C1EC
	.string "Hm?\n"
	.string "Hallo, ich bin BOOTMAR.\p"
	.string "KAPT. BRIGG hat mich damit\n"
	.string "beauftragt, eine Fähre zu konstruieren.\p"
	.string "Oh! Das da...\n"
	.string "Sind das DEVON-WAREN?\p"
	.string "Aber, ähm... Das ist ein ungünstiger\n"
	.string "Zeitpunkt...\p"
	.string "KAPT. BRIGG ist irgendwohin ge-\n"
	.string "gangen. Er sagte, er müsse was\l"
	.string "erledigen.\p"
	.string "Kann ich dich bitten, KAPT. BRIGG zu\n"
	.string "suchen und ihm das Paket zu bringen?$"

SlateportCity_SternsShipyard_1F_Text_17C2F2:: @ 817C2F2
	.string "BOOTMAR: Wo könnte KAPT. BRIGG wohl\n"
	.string "hingegangen sein?\p"
	.string "Kannst du bitte KAPT. BRIGG suchen und\n"
	.string "ihm die Waren übergeben?$"

SlateportCity_SternsShipyard_1F_Text_17C360:: @ 817C360
	.string "BOOTMAR: Der Schiffsbau ist eine Kunst.\p"
	.string "Manche Dinge lassen sich auch durch\n"
	.string "Berechnungen nicht vorhersehen.\p"
	.string "Jemand, der das Meer kennt wie seine\n"
	.string "Westentasche, müsste mir helfen...$"

SlateportCity_SternsShipyard_1F_Text_17C3F7:: @ 817C3F7
	.string "BOOTMAR: Hallo! MR. BRACK hat sich bereit\n"
	.string "erklärt, uns zu helfen.\p"
	.string "Dank dieses erfahrenen Seemannes\n"
	.string "kommen wir zügig voran.$"

SlateportCity_SternsShipyard_1F_Text_17C472:: @ 817C472
	.string "BOOTMAR: Die Fähre ist bald fertig!\p"
	.string "Die neue MS TIDE ist ein wahres\n"
	.string "Technikwunder!\p"
	.string "Aber ich denke doch, dass wir noch\n"
	.string "einiges besser machen können.\p"
	.string "Weißt du, die technische Entwicklung\n"
	.string "wird niemals abgeschlossen sein.$"

SlateportCity_SternsShipyard_1F_Text_17C53D:: @ 817C53D
	.string "MR. BRACK: Ah, {PLAYER}{KUN}!\n"
	.string "Es ist schon lange her!\p"
	.string "Aye, seit ich dich kennen gelernt habe,\n"
	.string "bin ich wieder voller Tatendrang.\p"
	.string "Also habe ich mich entschlossen,\n"
	.string "BOOTMAR beim Bau der Fähre zu helfen.\p"
	.string "Aye, so wie es aussieht, wird die Fähre\n"
	.string "viele Passagiere befördern können.\p"
	.string "Aber, weißt du, BOOTMAR ist wirklich\n"
	.string "eine besondere Persönlichkeit.\p"
	.string "Mit seinem technischen Wissen und\n"
	.string "meiner Erfahrung auf See werden wir\l"
	.string "ein ganz besonderes Schiff bauen, aye.$"

UnknownString_817C6A6: @ 817C6A6
	.string "PECKO: Pii piihyoro!$"

SlateportCity_SternsShipyard_1F_Text_17C6BB:: @ 817C6BB
	.string "Die Jahreszeit, das Wetter, der Mond,\n"
	.string "der vom Himmel herabstrahlt...\p"
	.string "Das sind die Bedingungen, die die See\n"
	.string "so wechselhaft machen.\p"
	.string "Ganz genau!\n"
	.string "Die See ist wie ein lebendiges Wesen!$"

SlateportCity_SternsShipyard_1F_Text_17C764:: @ 817C764
	.string "Ich werde sehr schnell seekrank.\n"
	.string "Deshalb helfe ich lieber hier aus.$"
