Underwater_SeafloorCavern_EventObjects:: @ 838D018
	object_event 1, EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 5, 4, 3, MOVEMENT_TYPE_INVISIBLE, 1, 1, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, FLAG_HIDE_UNDERWATER_SUBMARINE_INTERACTION
	object_event 2, EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 6, 4, 3, MOVEMENT_TYPE_INVISIBLE, 1, 1, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, FLAG_HIDE_UNDERWATER_SUBMARINE_INTERACTION
	object_event 3, EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 7, 4, 3, MOVEMENT_TYPE_INVISIBLE, 1, 1, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, FLAG_HIDE_UNDERWATER_SUBMARINE_INTERACTION
	object_event 4, EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 8, 4, 3, MOVEMENT_TYPE_INVISIBLE, 1, 1, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, FLAG_HIDE_UNDERWATER_SUBMARINE_INTERACTION

Underwater_SeafloorCavern_MapWarps:: @ 838D078
	warp_def 6, 7, 0, 0, MAP_UNDERWATER4

Underwater_SeafloorCavern_MapEvents:: @ 838D080
	map_events Underwater_SeafloorCavern_EventObjects, Underwater_SeafloorCavern_MapWarps, 0x0, 0x0
