EverGrandeCity_SidneysRoom_Text_190728:: @ 8190728
	.string "Willkommen, Herausforderer!\n"
	.string "Ich bin ULRICH von den TOP VIER.\p"
	.string "Ich mag deinen herausfordernden Blick.\n"
	.string "Ich denke, das wird ein guter Kampf.\l"
	.string "Gut! Das sieht gut aus!\p"
	.string "Schön! Dann lass uns beide einen Kampf\n"
	.string "erleben, wie man ihn nur hier in der\l"
	.string "POKéMON LIGA erleben kann!$"

EverGrandeCity_SidneysRoom_Text_190823:: @ 8190823
	.string "Ich habe verloren! Ich, ULRICH von den\n"
	.string "TOP VIER. Macht nichts, es war lustig.$"

EverGrandeCity_SidneysRoom_Text_19086D:: @ 819086D
	.string "Nun, hör dir an, was dieser Verlierer\n"
	.string "zu sagen hat.\p"
	.string "Du bist bestens ausgerüstet.\n"
	.string "Daher solltest du nun in den nächsten\l"
	.string "Raum gehen - zum nächsten Kampf.$"
