FallarborTown_ContestLobby_Text_177141:: @ 8177141
	.string "Dort hing mal eine Zeichnung von meinem\n"
	.string "POKéMON, aber nun hängt dort die\l"
	.string "Zeichnung eines anderen POKéMON.\p"
	.string "Ich werde mein HANA am WETTBEWERB\n"
	.string "teilnehmen lassen, dann gibt es eine\l"
	.string "neue Zeichnung von ihm!$"

FallarborTown_ContestLobby_Text_1771F2:: @ 81771F2
	.string "Hallo, willst du {POKEBLOCK} herstellen?\p"
	.string "Dann komm doch mal wieder vorbei und\n"
	.string "bring genug BEEREN mit.$"

FallarborTown_ContestLobby_Text_177246:: @ 8177246
	.string "Siehst du, wie sie hier die Zeichnungen\n"
	.string "des Sieger-POKéMON aushängen?\p"
	.string "Ich bin der Zeichner dieser Werke!\p"
	.string "Sobald eines deiner POKéMON einen\n"
	.string "WETTBEWERB gewinnt, werde ich es mit\l"
	.string "Vergnügen zeichnen!$"

FallarborTown_ContestLobby_Text_1772D8:: @ 81772D8
	.string "Hallo und herzlichen Glückwunsch!\p"
	.string "Ich habe eine Zeichnung deines POKéMON\n"
	.string "hier aufgehängt, damit jeder es sieht.$"
