Route126_EventObjects:: @ 8384F1C
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 55, 22, 1, 51, 10, 3, 1, 3, Route126_EventScript_15200E, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_M, 0, 33, 63, 1, 28, 9, 0, 1, 3, Route126_EventScript_152025, 0
	object_event 3, EVENT_OBJ_GFX_SWIMMER_F, 0, 9, 49, 1, 7, 0, 0, 1, 3, Route126_EventScript_15203C, 0
	object_event 4, EVENT_OBJ_GFX_SWIMMER_F, 0, 64, 44, 1, 24, 0, 0, 1, 3, Route126_EventScript_152053, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 14, 1, 3, 1, 1, 1, 0, 0, Route126_EventScript_1B16B6, FLAG_ITEM_ROUTE126_1

Route126_MapEvents:: @ 8384F94
	map_events Route126_EventObjects, 0x0, 0x0, 0x0
