VictoryRoad_1F_Text_WallyNotGoingToLoseAnymore:: @ 819782B
	.string "HEIKO: Hallo, {PLAYER}!\p"
	.string "Du bist bestimmt überrascht, mich hier\n"
	.string "zu treffen!\p"
	.string "Ich habe es bis hierher geschafft und\n"
	.string "das verdanke ich dir!\p"
	.string "{PLAYER}, meine Niederlage gegen dich\n"
	.string "hat mich viel stärker gemacht!\p"
	.string "Ich werde nie wieder verlieren!\p"
	.string "Ich werde gewinnen! Für die POKéMON,\n"
	.string "die mir Mut und Kraft gegeben haben!\p"
	.string "Okay... Jetzt komme ich!$"

VictoryRoad_1F_Text_WallyEntranceDefeat:: @ 8197943
	.string "Wow!\n"
	.string "{PLAYER}, du wirst immer stärker!$"

VictoryRoad_1F_Text_WallyPostEntranceBattle:: @ 8197967
	.string "HEIKO: Ich konnte dich heute nicht be-\n"
	.string "siegen, aber eines Tages werde ich es\l"
	.string "mit dir aufnehmen!$"

VictoryRoad_1F_Text_WallyIntro:: @ 81979BA
	.string "HEIKO: Hallo, {PLAYER}!\p"
	.string "Ich bin viel stärker geworden! Das\n"
	.string "möchte ich dir zeigen, {PLAYER}!\p"
	.string "Okay... Jetzt komme ich!$"

VictoryRoad_1F_Text_WallyDefeat:: @ 8197A23
	.string "Wow!\n"
	.string "{PLAYER}, du bist immer noch zu stark!$"

VictoryRoad_1F_Text_WallyPostBattle:: @ 8197A47
	.string "HEIKO: Ich konnte dich wieder nicht\n"
	.string "besiegen... Aber eines Tages, {PLAYER},\l"
	.string "eines Tages...\p"
	.string "Da werde ich sogar die POKéMON LIGA\n"
	.string "herausfordern!$"

VictoryRoad_1F_Text_EdgarIntro:: @ 8197AD1
	.string "Ich habe es innerhalb kürzester Zeit\n"
	.string "bis hierher geschafft, aber das letzte\l"
	.string "Stück zieht sich wie Kaugummi...$"

VictoryRoad_1F_Text_EdgarDefeat:: @ 8197B1A
	.string "Hier enden meine Träume...$"

VictoryRoad_1F_Text_EdgarPostBattle:: @ 8197B36
	.string "Du bist weit gekommen. Lasse nicht nach\n"
	.string "und versuche, der CHAMP zu werden!\l"
	.string "Wenn einer das kann, dann du!$"

VictoryRoad_1F_Text_AlbertIntro:: @ 8197B99
	.string "Ich bin nicht hierher gekommen, um zu\n"
	.string "verlieren. Diese Option existiert nicht!$"

VictoryRoad_1F_Text_AlbertDefeat:: @ 8197BE1
	.string "Unmöglich...\n"
	.string "Ich habe verloren???$"

VictoryRoad_1F_Text_AlbertPostBattle:: @ 8197BF7
	.string "Ich habe hier verloren...\p"
	.string "Das heißt, mir fehlt noch eine Menge,\n"
	.string "um CHAMP werden zu können.$"

VictoryRoad_1F_Text_HopeIntro:: @ 8197C45
	.string "Diese unendliche, raue Straße wird\n"
	.string "ihrem Namen - SIEG - gerecht.$"

VictoryRoad_1F_Text_HopeDefeat:: @ 8197C8D
	.string "Dein Kampfstil ist fantastisch...$"

VictoryRoad_1F_Text_HopePostBattle:: @ 8197CAF
	.string "Du hast wirklich das Potential, der\n"
	.string "CHAMP zu werden.$"
