FortreeCity_Mart_Text_SuperRepelBetter:: @ 81861EF
	.string "SUPER REPEL lasts a long time, and\n"
	.string "it gets the job done.\p"
	.string "It's much better than an ordinary\n"
	.string "REPEL.$"

FortreeCity_Mart_Text_StockUpOnItems:: @ 8186251
	.string "I always stock up on more items than\n"
	.string "I'm sure I'll need.\p"
	.string "You never know what might happen.\n"
	.string "Better to be safe than sorry!$"

FortreeCity_Mart_Text_RareCandyMakesMonGrow:: @ 81862CA
	.string "A RARE CANDY makes a POKéMON grow\n"
	.string "immediately by one level.$"
