gEasyChatGroupWords_Speech: @ 83DCB82
	.string "ZUHÖREN$"
	.string "NICHT SEHR$"
	.string "GEMEIN$"
	.string "LÜGEN$"
	.string "GELOGEN$"
	.string "EMPFOHLEN$"
	.string "BLÖDKOPF$"
	.string "WIRKLICH$"
	.string "VON$"
	.string "FÜHLEN$"
	.string "ABER$"
	.string "JEDOCH$"
	.string "FALL$"
	.string "DER$"
	.string "DANEBEN$"
	.string "GENAU WIE$"
	.string "TREFFER$"
	.string "REICHT AUS$"
	.string "VIEL$"
	.string "EIN BISSCHEN$"
	.string "DIE$"
	.string "UND$"
	.string "NUR$"
	.string "ETWA$"
	.string "EVENTUELL$"
	.string "WENN$"
	.string "SEHR$"
	.string "WENIG$"
	.string "WILD$"
	.string "NOCH MAL$"
	.string "BLOSS$"
	.string "TROTZDEM$"
	.string "MUSS$"
	.string "VERSTÄNDLICH$"
	.string "FÜR NUN$"
	.string "VERSTANDEN$"
	.string "SCHERZEN$"
	.string "BEREIT$"
	.string "ETWAS$"
	.string "IRGENDWIE$"
	.string "OBWOHL$"
	.string "ALSO$"
	.string "PERFEKT$"
	.string "SO VIEL WIE$"
	.string "EHRLICH$"
	.string "WAHRHAFTIG$"
	.string "ERNST$"
	.string "NOCH$"
	.string "BIS$"
	.string "ALS OB$"
	.string "LAUNE$"
	.string "EHER$"
	.string "FURCHTBAR$"
	.string "DENKE$"
	.string "MEHR$"
	.string "ZU SPÄT$"
	.string "ENDLICH$"
	.string "IRGENDEIN$"
	.string "STATT$"
	.string "FANTASTISCH$"
	.string "$"
