FortreeCity_House4_Text_BringsWorldCloserTogether:: @ 81867AF
	.string "Wenn sie mit POKéMON zusammen sind,\n"
	.string "finden die Menschen schnell Freunde.\p"
	.string "Und so rücken die Menschen weltweit\n"
	.string "näher zusammen. Wunderbar, nicht wahr?$"

FortreeCity_House4_Text_GoBirdPokemon:: @ 8186835
	.string "Fertig!\n"
	.string "Los, VOGEL-POKéMON!$"

FortreeCity_House4_Text_AskedWingullToRunErrand:: @ 818684E
	.string "Hähähä, mein WINGULL macht\n"
	.string "Besorgungen für mich.$"

FortreeCity_House4_Text_WelcomeWingullTakeMentalHerb:: @ 8186881
	.string "Gut!\n"
	.string "Komm zurück, WINGULL!\p"
	.string "Huch! Was ist das?\n"
	.string "Was trägt es denn da?\p"
	.string "Ein MENTALKRAUT?\n"
	.string "Das muss es irgendwo gefunden haben.\p"
	.string "Aber, ich bin kein TRAINER, daher kannst\n"
	.string "du es haben.$"

FortreeCity_House4_Text_FriendsFarAwayThanksToWingull:: @ 8186924
	.string "Dank meines WINGULL habe ich Freunde,\n"
	.string "die sehr weit weg von hier wohnen.$"

FortreeCity_House4_Text_Wingull:: @ 818695C
	.string "WINGULL: Pihyoh!$"
