MossdeepCity_House4_Text_BrotherLikesToFindBases:: @ 818E0E3
	.string "My little brother says he likes to go\n"
	.string "find people's SECRET BASES.$"

MossdeepCity_House4_Text_BrotherLikesToVisitBasesAndBattle:: @ 818E125
	.string "My little brother says he likes to\n"
	.string "visit people's SECRET BASES and have\l"
	.string "POKéMON battles.$"

MossdeepCity_House4_Text_YouMadeSecretBaseNearX:: @ 818E17E
	.string "Was it you who made a SECRET BASE in\n"
	.string "{STR_VAR_1}?$"

MossdeepCity_House4_Text_MakeSecretBase:: @ 818E1A7
	.string "You should make a SECRET BASE\n"
	.string "somewhere. I'll go find it!$"

MossdeepCity_House4_Text_Delcatty:: @ 818E1E1
	.string "DELCATTY: Miyaan?$"
