SecretBase_Text_SmallIndentInWall:
	.string "In der Wand ist eine kleine Einkerbung.$"

SecretBase_Text_IndentUseSecretPower:
	.string "In der Wand ist eine kleine Einkerbung.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

SecretBase_Text_DiscoveredSmallCavern:
	.string "Eine kleine Höhle wird sichtbar.$"

SecretBase_Text_WantToMakeYourSecretBaseHere::
	.string "Möchtest du hier deine GEHEIMBASIS\n"
	.string "einrichten?$"
