Route110_TrickHousePuzzle8_Text_19E178:: @ 819E178
	.string "Nicht viele TRAINER haben es bis\n"
	.string "hierher geschafft.$"

Route110_TrickHousePuzzle8_Text_19E1A1:: @ 819E1A1
	.string "Das bedeutet, dass du sehr stark bist...$"

Route110_TrickHousePuzzle8_Text_19E1C5:: @ 819E1C5
	.string "Du hast den CHAMP der POKéMON LIGA\n"
	.string "besiegt? Das ist zu viel für mich!$"

Route110_TrickHousePuzzle8_Text_19E201:: @ 819E201
	.string "Sieh es als Glücksfall an, dass du gegen\n"
	.string "mich antreten darfst.$"

Route110_TrickHousePuzzle8_Text_19E22C:: @ 819E22C
	.string "Das ist nicht korrekt!\n"
	.string "Ich darf nicht verlieren!$"

Route110_TrickHousePuzzle8_Text_19E24C:: @ 819E24C
	.string "Nur ein Wunder hat dir zu diesem Sieg\n"
	.string "verholfen. Prahl doch damit...$"

Route110_TrickHousePuzzle8_Text_19E284:: @ 819E284
	.string "Du schleichst hier auch durch das\n"
	.string "RÄTSELHAUS?$"

Route110_TrickHousePuzzle8_Text_19E2C1:: @ 819E2C1
	.string "Ich verstehe...\n"
	.string "Du hast einen außergewöhnlichen Stil.$"

Route110_TrickHousePuzzle8_Text_19E2EE:: @ 819E2EE
	.string "Dein Anblick wird den RÄTSELMEISTER\n"
	.string "bestimmt erfreuen.$"
