Route133_EventObjects:: @ 83853D0
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 6, 4, 1, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 1, 3, Route133_EventScript_152542, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 68, 24, 1, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 1, 3, Route133_EventScript_152570, 0
	object_event 3, EVENT_OBJ_GFX_SWIMMER_F, 0, 69, 24, 1, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 1, 3, Route133_EventScript_152559, 0
	object_event 4, EVENT_OBJ_GFX_ITEM_BALL, 0, 58, 15, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, Route133_EventScript_1B16EA, FLAG_ITEM_ROUTE133_1
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 8, 10, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, Route133_EventScript_1B16F7, FLAG_ITEM_ROUTE133_2
	object_event 6, EVENT_OBJ_GFX_MAN_6, 0, 37, 16, 3, MOVEMENT_TYPE_FACE_DOWN_AND_UP, 1, 1, 1, 1, Route133_EventScript_15259E, 0
	object_event 7, EVENT_OBJ_GFX_MAN_4, 0, 7, 14, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 4, Route133_EventScript_152587, 0

Route133_MapEvents:: @ 8385478
	map_events Route133_EventObjects, 0x0, 0x0, 0x0
