Route133_MapScripts:: @ 8152541
	.byte 0

Route133_EventScript_152542:: @ 8152542
	trainerbattle 0, TRAINER_FRANKLIN, 0, Route133_Text_1C2DA5, Route133_Text_1C2DF4
	msgbox Route133_Text_1C2E09, 6
	end

Route133_EventScript_152559:: @ 8152559
	trainerbattle 0, TRAINER_DEBRA, 0, Route133_Text_1C2E61, Route133_Text_1C2EBD
	msgbox Route133_Text_1C2ECD, 6
	end

Route133_EventScript_152570:: @ 8152570
	trainerbattle 0, TRAINER_LINDA, 0, Route133_Text_1C2EF7, Route133_Text_1C2F19
	msgbox Route133_Text_1C2F25, 6
	end

Route133_EventScript_152587:: @ 8152587
	trainerbattle 0, TRAINER_WARREN, 0, Route133_Text_1C2F53, Route133_Text_1C2FA3
	msgbox Route133_Text_1C2FC7, 6
	end

Route133_EventScript_15259E:: @ 815259E
	trainerbattle 0, TRAINER_BECK, 0, Route133_Text_1C302D, Route133_Text_1C305F
	msgbox Route133_Text_1C307E, 6
	end
