Route116_Text_17032A:: @ 817032A
	.string "Oooh, was mache ich nur?!?\p"
	.string "PECKO und ich waren auf einem Spazier-\n"
	.string "gang und da kam so ein Schlägertyp...\p"
	.string "Der Schurke hat mir meinen Liebling\n"
	.string "PECKO geklaut!\p"
	.string "Ooooooooooooaaaargh! PECKO!$"

Route116_Text_1703CF:: @ 81703CF
	.string "Nnn... Brüll!\p"
	.string "Ich will diesen vermaledeiten Tunnel\n"
	.string "graben!$"

Route116_Text_1703F7:: @ 81703F7
	.string "Nnn... Brüll!\n"
	.string "Was ist hier los?\p"
	.string "Ich war dabei, einen Tunnel ohne Werk-\n"
	.string "zeug zu graben, als so ein Idiot mich\l"
	.string "verjagt hat!\p"
	.string "Dieser Tunnel ist voller POKéMON, die\n"
	.string "sensibel auf Lärm reagieren. Sie können\l"
	.string "einen Aufruhr veranstalten.\p"
	.string "Daher arbeiten wir ohne schwere\n"
	.string "Maschinen an dem Tunnel...\p"
	.string "Ich befürchte, dieser Idiot wird\n"
	.string "irgendetwas Dummes tun und die\l"
	.string "POKéMON in Aufruhr versetzen.$"

Route116_Text_170556:: @ 8170556
	.string "Nnn... Brüll!\p"
	.string "Dieser dämliche Idiot ist aus dem Tunnel\n"
	.string "abgehauen. Ich kann weitergraben!$"

Route116_Text_1705AE:: @ 81705AE
	.string "Oh! Du bist das!\p"
	.string "Du hast mir nicht nur im BLÜTEN-\n"
	.string "BURGWALD geholfen, sondern auch\l"
	.string "mein gestohlenes Paket zurückgeholt\l"
	.string "und nach GRAPHITPORT CITY gebracht!\p"
	.string "KAPT. BRIGG hat uns über die Ankunft\n"
	.string "des Paketes unterrichtet!\p"
	.string "Vielen, vielen Dank!\p"
	.string "Wäre ich ein Meer, würde ich\n"
	.string "dich in Dankbarkeit baden und als\l"
	.string "Held auf meinen Wellen tragen!\p"
	.string "Ich habe für dich, den wunderbarsten\n"
	.string "TRAINER, gute Nachrichten!\p"
	.string "Unsere Firma hat vor kurzem eine\n"
	.string "neue Art von POKéBALL entwickelt...\p"
	.string "Als Zeichen meiner Dankbarkeit\n"
	.string "schenke ich ihn dem wunderbarsten\l"
	.string "TRAINER!$"

Route116_Text_1707B8:: @ 81707B8
	.string "Unser neuer POKéBALL wird im PKMN-\n"
	.string "MARKT in METAROST CITY erhältlich sein.\p"
	.string "Bitte, probiere ihn aus!\n"
	.string "Vielen Dank und Lebewohl.$"

Route116_Text_17082A:: @ 817082A
	.string "Dein BEUTEL ist brechend voll.\n"
	.string "Ich kann dir diesen WIEDERBALL nicht\l"
	.string "geben.$"

Route116_Text_170865:: @ 8170865
	.string "Als Zeichen unseres Dankes für die\n"
	.string "Überbringung unseres Paketes, habe ich\l"
	.string "eine neue Art von POKéBALL für dich.\l"
	.string "Für unseren wunderbarsten TRAINER!$"

Route116_Text_1708EE:: @ 81708EE
	.string "Ich habe meine Brille fallen lassen...\n"
	.string "Kannst du mir helfen, sie zu finden?$"

Route116_Text_170921:: @ 8170921
	.string "Deine Brille...\n"
	.string "Darf ich sie mal kurz ausprobieren?$"

Route116_Text_17094D:: @ 817094D
	.string "Hmm...\n"
	.string "Das ist ein SCHATTENGLAS.\l"
	.string "Das habe ich nicht gesucht...\p"
	.string "Vielleicht ist meine Brille gar nicht hier\n"
	.string "zu finden...$"

Route116_Text_1709B7:: @ 81709B7
	.string "Hmm...\n"
	.string "Ich kann meine Brille nirgends finden...\l"
	.string "Vielleicht liegt sie gar nicht hier...$"

Route116_Text_170A03:: @ 8170A03
	.string "Hmm...\n"
	.string "Das ist ein SCHATTENGLAS.\l"
	.string "Das habe ich nicht gesucht...$"

Route116_Text_170A46:: @ 8170A46
	.string "ROUTE 116\n"
	.string "{LEFT_ARROW} METAROST CITY$"

Route116_Text_170A60:: @ 8170A60
	.string "METAFLURTUNNEL\n"
	.string "“Verbindet METAROST CITY und\p"
	.string "WIESENFLUR.\n"
	.string "Das Tunnelprojekt wurde abgebrochen.”$"

Route116_Text_170AB8:: @ 8170AB8
	.string "BERGRASTHAUS$"

Route116_Text_170ACE:: @ 8170ACE
	.string "TIPPS für TRAINER\p"
	.string "Wenn du die Entwicklung eines POKéMON\n"
	.string "stoppen willst, musst du den B-Knopf\l"
	.string "drücken, während es sich entwickeln will.\l"
	.string "Das POKéMON entwickelt sich dann nicht.\p"
	.string "Das nennt man Entwicklungsstopp.$"

Route116_Text_170B7D:: @ 8170B7D
	.string "TIPPS für TRAINER\p"
	.string "Dein BEUTEL hat mehrere TASCHEN.\p"
	.string "Items werden automatisch in die dafür\n"
	.string "vorgesehene TASCHE gelegt.\p"
	.string "Kein TRAINER kann auf einen eigenen\n"
	.string "BEUTEL verzichten.$"
