gEasyChatGroupWords_Greetings: @ 83DC70F
	.string "DANK$"
	.string "JA$"
	.string "HIER KOMMT$"
	.string "HIER BIN ICH$"
	.string "HIER IST ES$"
	.string "YEAH$"
	.string "WILLKOMMEN$"
	.string "AU$"
	.string "WIE$"
	.string "GLÜCKWUNSCH$"
	.string "GIB$"
	.string "SORRY$"
	.string "VERZEIHUNG$"
	.string "SCHON GUT$"
	.string "HEY DA$"
	.string "HALLO$"
	.string "TSCHÜSS$"
	.string "DANKE SCHÖN$"
	.string "ICH BIN DA$"
	.string "PARDON$"
	.string "TAGCHEN$"
	.string "BIS DANN$"
	.string "ENTSCHULDIGE$"
	.string "NUN, DANN$"
	.string "WEITER SO$"
	.string "SCHÄTZEN$"
	.string "HEY?$"
	.string "WAS IST LOS?$"
	.string "WIE?$"
	.string "NEIN$"
	.string "TAG AUCH$"
	.string "YEAH, YEAH$"
	.string "TSCHAU$"
	.string "BIS BALD$"
	.string "HEY$"
	.string "GERUCH$"
	.string "HÖR ZU$"
	.string "HUH HAH$"
	.string "JUCHUU$"
	.string "JEPP$"
	.string "ACH, KOMM$"
	.string "ZÄHLEN AUF$"
	.string "$"
