PetalburgCity_Gym_Text_179DF6:: @ 8179DF6
	.string "VATER: Hm?\p"
	.string "Na, wenn das nicht {PLAYER} ist!\n"
	.string "Dann habt ihr also den Umzug beendet?\p"
	.string "Ich bin überrascht, dass du ganz\n"
	.string "alleine hierher gefunden hast.\p"
	.string "Oh, so ist das.\n"
	.string "Du bist in POKéMON-Begleitung.\p"
	.string "Ich glaube, du wirst einmal in meine Fuß-\n"
	.string "stapfen als TRAINER treten, {PLAYER}.\p"
	.string "Das sind großartige Aussichten!\n"
	.string "Ich kann es kaum erwarten!$"

PetalburgCity_Gym_Text_179F07:: @ 8179F07
	.string "Äh... Ich... Ich hätte so gerne ein\n"
	.string "POKéMON. Bitte...$"

PetalburgCity_Gym_Text_179F37:: @ 8179F37
	.string "VATER: Wie? Du... Ach... Gut.\n"
	.string "Du bist HEIKO, nicht wahr?$"

PetalburgCity_Gym_Text_179F70:: @ 8179F70
	.string "HEIKO: Ich werde meine Verwandten\n"
	.string "in WIESENFLUR besuchen.\p"
	.string "Ich glaube, ich werde mich da doch\n"
	.string "einsam fühlen, daher würde ich gerne ein\l"
	.string "POKéMON mitnehmen.\p"
	.string "Aber ich habe noch nie eines gefangen.\n"
	.string "Ich weiß nicht, wie das geht...$"

PetalburgCity_Gym_Text_17A03A:: @ 817A03A
	.string "VATER: Oh, ich verstehe...$"

PetalburgCity_Gym_Text_17A04A:: @ 817A04A
	.string "VATER: {PLAYER}, hast du das gehört?\p"
	.string "Hilf doch bitte HEIKO dabei,\n"
	.string "ein POKéMON zu fangen.$"

PetalburgCity_Gym_Text_17A0A8:: @ 817A0A8
	.string "HEIKO, hier, ich leihe dir mein\n"
	.string "POKéMON.\p"
	.string "HEIKO hat ein ZIGZACHS erhalten.$"

PetalburgCity_Gym_Text_17A0EB:: @ 817A0EB
	.string "HEIKO: Oh, wow!!!\n"
	.string "Ein POKéMON!\p"
	.string "VATER: Hm. Ich gebe dir auch diesen\n"
	.string "POKéBALL. Dann leg los!\p"
	.string "HEIKO erhält einen POKéBALL!$"

PetalburgCity_Gym_Text_17A156:: @ 817A156
	.string "HEIKO: Oh, wow!!!\n"
	.string "Danke schön!$"

PetalburgCity_Gym_Text_17A171:: @ 817A171
	.string "{PLAYER}... Kommst du wirklich mit mir???$"

PetalburgCity_Gym_Text_17A196:: @ 817A196
	.string "VATER: Und? Hat es geklappt?$"

PetalburgCity_Gym_Text_17A1B0:: @ 817A1B0
	.string "HEIKO: Danke. Ja, wunderbar.\n"
	.string "Hier haben Sie Ihr POKéMON zurück.\p"
	.string "Danke, {PLAYER}, dass du mit mir\n"
	.string "gegangen bist.\p"
	.string "Euch beiden habe ich es zu verdanken,\n"
	.string "dass ich mein erstes POKéMON fangen\l"
	.string "konnte.\p"
	.string "Ich verspreche, ich werde mich gut\n"
	.string "darum kümmern!\p"
	.string "Oh! Meine Mama wartet sicher schon auf\n"
	.string "mich! Ich muss nach Hause!\p"
	.string "Bis bald, {PLAYER}!$"

PetalburgCity_Gym_Text_17A2A4:: @ 817A2A4
	.string "VATER: Nun...\p"
	.string "{PLAYER}, wenn du ein guter TRAINER\n"
	.string "werden willst - hier ist mein Rat.\p"
	.string "Gehe nach METAROST CITY, gleich hinter\n"
	.string "diesem Ort.\p"
	.string "Dort solltest du die ARENALEITERIN\n"
	.string "FELIZIA herausfordern.\p"
	.string "Danach suche die anderen POKéMON\n"
	.string "ARENEN auf und besiege die LEITER.\p"
	.string "Sammle die ORDEN der verschiedenen\n"
	.string "ARENEN, verstehst du?\p"
	.string "Ich bin natürlich auch ein ARENALEITER.\n"
	.string "Auch wir werden eines Tages\l"
	.string "gegeneinander antreten.\p"
	.string "Aber erst, wenn du stärker geworden\n"
	.string "bist, {PLAYER}.$"

PetalburgCity_Gym_Text_17A41E:: @ 817A41E
	.string "VATER: Hm? Wolltest du nicht zur\n"
	.string "POKéMON ARENA in METAROST CITY?\p"
	.string "Für mich ist es keine Herausforderung,\n"
	.string "gegen einen Grünschnabel anzutreten.\p"
	.string "{PLAYER}, ich möchte, dass du mich he-\n"
	.string "rausforderst, sobald du stärker bist.\p"
	.string "Ich werde gegen dich kämpfen, {PLAYER},\n"
	.string "sobald du vier ORDEN erhalten hast, ja?$"

PetalburgCity_Gym_Text_17A518:: @ 817A518
	.string "VATER: Oh, ich sehe schon... Du hast die\n"
	.string "ARENALEITERIN in METAROST CITY\l"
	.string "besiegt.\p"
	.string "Aber es gibt weitere TRAINER, die\n"
	.string "stärker sind als du, {PLAYER}.\p"
	.string "Wenn du das Meer überquerst, kommst du\n"
	.string "nach FAUSTAUHAVEN. Dort triffst du auf\l"
	.string "den ARENALEITER KAMILLO.\p"
	.string "Du solltest ihn wirklich herausfordern...$"

PetalburgCity_Gym_Text_17A5F3:: @ 817A5F3
	.string "VATER: Hm... {PLAYER}, du bist stärker\n"
	.string "geworden.\p"
	.string "Das sehe ich an der Anzahl der ORDEN,\n"
	.string "die du dir verdient hast.$"

PetalburgCity_Gym_Text_17A653:: @ 817A653
	.string "VATER: Hm...\n"
	.string "Du besitzt vier ORDEN.\p"
	.string "Fein. Wie versprochen werden wir nun\n"
	.string "einen POKéMON-Kampf ausfechten.\p"
	.string "{PLAYER}...\p"
	.string "Ich bin so glücklich, dass mein eigenes\n"
	.string "Kind stark genug ist, gegen\l"
	.string "mich zu kämpfen!\p"
	.string "Aber: Kampf ist Kampf!\p"
	.string "Ich werde als ARENALEITER alles tun, um\n"
	.string "diesen Kampf zu gewinnen!\p"
	.string "{PLAYER}, du solltest ebenfalls dein\n"
	.string "Bestes geben!$"

PetalburgCity_Gym_Text_17A77A:: @ 817A77A
	.string "...\p"
	.string "Ich... Ich kann es nicht...\p"
	.string "Ich kann es nicht glauben, {PLAYER}...\p"
	.string "Ich habe gegen {PLAYER} verloren?\p"
	.string "Nun, Regeln sind Regeln!\n"
	.string "Hier, das ist für dich.$"

PetalburgCity_Gym_Text_17A7DD:: @ 817A7DD
	.string "{PLAYER} hat den BALANCEORDEN vom\n"
	.string "VATER erhalten!$"

PetalburgCity_Gym_Text_17A805:: @ 817A805
	.string "VATER: Mit diesem ORDEN erhöht sich die\n"
	.string "VERTEIDIGUNG all deiner POKéMON.\p"
	.string "POKéMON, die die VM SURFER erlernt\n"
	.string "haben, können diese auch zum Reisen\l"
	.string "über das Wasser einsetzen.\p"
	.string "{PLAYER}, das ist mein Geschenk für\n"
	.string "dich. Ich bin sicher, du wirst es gut\l"
	.string "nutzen.$"

PetalburgCity_Gym_Text_17A8CF:: @ 817A8CF
	.string "VATER: TM42 enthält FASSADE.\p"
	.string "Sie verdoppelt die Stärke der Attacken,\n"
	.string "wenn das POKéMON vergiftet,\l"
	.string "paralysiert oder verbrannt wurde.\p"
	.string "So kann eine vermeintlich aussichtslose\n"
	.string "Situation vielleicht gerettet werden.$"

PetalburgCity_Gym_Text_17A976:: @ 817A976
	.string "VATER: Als ARENALEITER kann ich gar\n"
	.string "nicht sagen, wie bestürzt ich bin...\p"
	.string "Als Vater macht es mich einerseits sehr\n"
	.string "stolz, andererseits aber auch traurig...$"

PetalburgCity_Gym_Text_17A9F6:: @ 817A9F6
	.string "VATER: Oh, ja...\p"
	.string "Die Eltern von HEIKO sind vor\n"
	.string "kurzem hier gewesen.\p"
	.string "Sie sagten, dass sie dir etwas schenken\n"
	.string "möchten, {PLAYER}.$"

PetalburgCity_Gym_Text_17AA6B:: @ 817AA6B
	.string "VATER: {PLAYER}, du solltest deine\n"
	.string "Mutter öfter mal besuchen.\p"
	.string "Ich bleibe hier und werde mein Training\n"
	.string "verdoppeln.\p"
	.string "Als TRAINER lässt es mir keine Ruhe. Ich\n"
	.string "möchte irgendwann gegen dich gewinnen.$"

PetalburgCity_Gym_Text_17AB17:: @ 817AB17
	.string "VATER: {PLAYER}! Wie geht es dir?\p"
	.string "Die Welt der POKéMON ist vielfältig.\p"
	.string "Ich bin überzeugt, dass selbst das \n"
	.string "härteste Training dieser Vielfalt nicht\l"
	.string "gerecht wird.$"

PetalburgCity_Gym_Text_17AB96:: @ 817AB96
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "Die Türen dieser ARENA öffnen sich,\n"
	.string "wenn du die einzelnen TRAINER besiegst.\p"
	.string "Huups! Die Türen in diesem Raum sind ja\n"
	.string "schon offen, greif mich bitte nicht an!\p"
	.string "Die TRAINER der ARENA von BLÜTENBURG\n"
	.string "CITY setzen die verschiedensten\l"
	.string "Items ein.\p"
	.string "Die Tür auf der linken Seite führt in den\n"
	.string "INIT.-RAUM.\p"
	.string "Die Tür auf der rechten Seite führt in\n"
	.string "den RAUM der GENAUIGKEIT.\p"
	.string "Die Türen sind beschriftet, lies genau\n"
	.string "und treffe eine überlegte Wahl.\p"
	.string "Hast du dich für eine Tür entschieden...\n"
	.string "Nun, ähm, genug der Worte!$"

PetalburgCity_Gym_Text_17AD49:: @ 817AD49
	.string "{PLAYER}! Hui! Du hast sogar deinen\n"
	.string "eigenen Vater besiegt!\p"
	.string "Wie... Unglaublich!\n"
	.string "Die Ereignisse überschlagen sich!$"

PetalburgCity_Gym_Text_17ADA5:: @ 817ADA5
	.string "Die Fähigkeit, dem Gegner mit einer\n"
	.string "Attacke zuvorzukommen...\p"
	.string "Das alleine gibt einem doch schon einen\n"
	.string "enormen Vorteil, meinst du nicht auch?$"

PetalburgCity_Gym_Text_17AE11:: @ 817AE11
	.string "Das war ein unglaublicher Kampf!$"

PetalburgCity_Gym_Text_17AE30:: @ 817AE30
	.string "Geh weiter in den nächsten Raum, wo\n"
	.string "eine neue Herausforderung wartet.\p"
	.string "Auf der linken Seite befindet sich der\n"
	.string "KP-SAUGER-RAUM.\p"
	.string "Auf der rechten Seite findest du den\n"
	.string "RAUM der VERTEIDIGUNG.$"

PetalburgCity_Gym_Text_17AEBB:: @ 817AEBB
	.string "Ob du siegst oder verlierst... Du darfst\n"
	.string "dein Training und das deiner POKéMON\l"
	.string "auf keinen Fall vernachlässigen.\p"
	.string "Das macht für mich einen wahren\n"
	.string "ARENALEITER aus.$"

PetalburgCity_Gym_Text_17AF5A:: @ 817AF5A
	.string "Verschwende deine kostbare Zeit nicht\n"
	.string "damit, die Fähigkeiten meines POKéMON\l"
	.string "zu blockieren!$"

PetalburgCity_Gym_Text_17AF98:: @ 817AF98
	.string "Die Fähigkeiten meines POKéMON wurden\n"
	.string "nicht blockiert, und doch habe ich\l"
	.string "verloren...$"

PetalburgCity_Gym_Text_17AFD3:: @ 817AFD3
	.string "Der nächste Raum ist der RAUM der\n"
	.string "STÄRKE. Kommst du gegen pure\l"
	.string "Gewalt an?$"

PetalburgCity_Gym_Text_17B016:: @ 817B016
	.string "Nachdem du unseren ARENALEITER be-\n"
	.string "siegt hast, wurde unser Training härter.$"

PetalburgCity_Gym_Text_17B058:: @ 817B058
	.string "Immer, wenn du den Sieg in greifbarer\n"
	.string "Nähe siehst, füllt dein Gegner KP auf...\p"
	.string "Kannst du dir vorstellen, wie man sich in\n"
	.string "so einer Situation fühlt?\p"
	.string "Ich werde dir so eine Situation\n"
	.string "demonstrieren!$"

PetalburgCity_Gym_Text_17B0F7:: @ 817B0F7
	.string "Ich konnte nicht genügend KP\n"
	.string "auffüllen... Welch eine ANGRIFFskraft...$"

PetalburgCity_Gym_Text_17B12C:: @ 817B12C
	.string "Ich hatte vom Kind unseres ARENA-\n"
	.string "LEITERS nichts anderes erwartet!\p"
	.string "Nein! Die Fähigkeiten eines TRAINERS\n"
	.string "entwickeln sich mit dem Training.\p"
	.string "Ich habe mich offensichtlich nicht\n"
	.string "genug angestrengt.\p"
	.string "Geh! Der nächste Raum ist der K.O.-\n"
	.string "TREFFER-RAUM.$"

PetalburgCity_Gym_Text_17B1F4:: @ 817B1F4
	.string "Ich werde auch weiterhin in den ARENEN\n"
	.string "trainieren. Und ARENALEITER werden!$"

PetalburgCity_Gym_Text_17B237:: @ 817B237
	.string "Ich werde es dir nicht leicht machen,\n"
	.string "nur weil du das Kind unseres LEITERS\l"
	.string "bist.\p"
	.string "Ich werde dir beibringen, was es für ein\n"
	.string "POKéMON bedeutet, einen kritischen\l"
	.string "Schlag zu erhalten.$"

PetalburgCity_Gym_Text_17B2C0:: @ 817B2C0
	.string "Deine Stärke...\n"
	.string "Du kämpfst großartig!$"

PetalburgCity_Gym_Text_17B2E4:: @ 817B2E4
	.string "Dein Vater ist stark. Als TRAINER\n"
	.string "erweise ich ihm den größten Respekt.\p"
	.string "Und ich sehe, dass die gleiche Stärke\n"
	.string "auch in dir ruht.\p"
	.string "Ich fühle, dass du dich nun einem\n"
	.string "Kampf mit deinem Vater stellen kannst.$"

PetalburgCity_Gym_Text_17B39B:: @ 817B39B
	.string "Seit dein Vater der LEITER der ARENA\n"
	.string "von BLÜTENBURG CITY ist, sind die\l"
	.string "TRAINER dort viel stärker geworden.$"

PetalburgCity_Gym_Text_17B3F7:: @ 817B3F7
	.string "Kicher...\n"
	.string "Dies ist der RAUM der GENAUIGKEIT.\p"
	.string "Es ist schon ziemlich fies, wenn jede\n"
	.string "Attacke ein Treffer ist.$"

PetalburgCity_Gym_Text_17B454:: @ 817B454
	.string "Du bist ein bisschen stärker als ich...$"

PetalburgCity_Gym_Text_17B46F:: @ 817B46F
	.string "Es warten noch weitaus stärkere\n"
	.string "TRAINER auf dich.\p"
	.string "Der linke ist der RAUM der VERTEIDIGUNG\n"
	.string "und der rechte der RAUM der ERHOLUNG.\p"
	.string "Die ATTACKEN deiner POKéMON werden\n"
	.string "in beiden Räumen auf die Probe gestellt.$"

PetalburgCity_Gym_Text_17B521:: @ 817B521
	.string "Weißt du, wonach wir als TRAINER\n"
	.string "streben?\p"
	.string "Wir streben danach, die Seelenfreunde\n"
	.string "unserer POKéMON zu werden.$"

PetalburgCity_Gym_Text_17B58D:: @ 817B58D
	.string "Je stärker die VERTEIDIGUNG ist, desto\n"
	.string "rücksichtsloser kann ich angreifen.$"

PetalburgCity_Gym_Text_17B5CB:: @ 817B5CB
	.string "Unsere Verteidigung reichte nicht aus...$"

PetalburgCity_Gym_Text_17B5EA:: @ 817B5EA
	.string "Ich denke, du hast mir eine wertvolle\n"
	.string "Lektion erteilt.\p"
	.string "Nun, geh weiter. Die linke Tür führt in\n"
	.string "den RAUM der STÄRKE.\p"
	.string "Die rechte Tür öffnet den K.O.-TREFFER-\n"
	.string "RAUM.\p"
	.string "In beiden warten äußerst talentierte\n"
	.string "TRAINER.$"

PetalburgCity_Gym_Text_17B6B5:: @ 817B6B5
	.string "Hallo! Hast du mal SURFER ausprobiert?$"

PetalburgCity_Gym_Text_17B6D4:: @ 817B6D4
	.string "Unser ARENALEITER hat uns angewiesen,\n"
	.string "alles zu geben und dich zu besiegen.\p"
	.string "Auch wenn du das Kind des LEITERS bist!$"

PetalburgCity_Gym_Text_17B732:: @ 817B732
	.string "Aber... Das war wohl nichts!$"

PetalburgCity_Gym_Text_17B749:: @ 817B749
	.string "Wie du deine POKéMON einsetzt...\n"
	.string "Du bist wie dein Vater.\p"
	.string "Geh weiter! Der ARENALEITER, dein\n"
	.string "Vater, erwartet dich bereits!$"

PetalburgCity_Gym_Text_17B7C0:: @ 817B7C0
	.string "Sicher, es ist immer von Vorteil, die\n"
	.string "POKéMON stärker werden zu lassen.\p"
	.string "Aber was macht einen Gewinner aus?\p"
	.string "Nun, das sind die Gefühle, die ein\n"
	.string "TRAINER seinen POKéMON entgegen-\l"
	.string "bringt.$"

PetalburgCity_Gym_Text_17B844:: @ 817B844
	.string "Die Tür ist noch verschlossen...$"

PetalburgCity_Gym_Text_17B870:: @ 817B870
	.string "“INITIATIVE-RAUM” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

UnknownString_817B8A8: @ 817B8A8
	.string "Die Tür ist noch verschlossen...$"

PetalburgCity_Gym_Text_17B8D4:: @ 817B8D4
	.string "“RAUM der GENAUIGKEIT” steht\n"
	.string "auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17B90F:: @ 817B90F
	.string "“KP-SAUGER-RAUM”\n"
	.string "steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17B950:: @ 817B950
	.string "“RAUM der VERTEIDIGUNG” steht\n"
	.string "auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17B98A:: @ 817B98A
	.string "“RAUM der ERHOLUNG” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17B9C5:: @ 817B9C5
	.string "“RAUM der STÄRKE” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17BA00:: @ 817BA00
	.string "“K.O.-TREFFER-RAUM”\n"
	.string "steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17BA3D:: @ 817BA3D
	.string "“ARENALEITER”\p"
	.string "“Sieh selbst, welche POKéMON dich\n"
	.string "erwarten!” steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_17BAA5:: @ 817BAA5
	.string "POKéMON ARENA von BLÜTENBURG CITY$"

PetalburgCity_Gym_Text_17BAC0:: @ 817BAC0
	.string "POKéMON ARENA von BLÜTENBURG CITY\p"
	.string "NORMANS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
