SSTidalLowerDeck_MapScripts:: @ 815FED6
	.byte 0

SSTidalLowerDeck_EventScript_15FED7:: @ 815FED7
	trainerbattle 0, TRAINER_PHILLIP, 0, SSTidalLowerDeck_Text_1993C1, SSTidalLowerDeck_Text_19941A
	msgbox SSTidalLowerDeck_Text_19942E, 6
	end

SSTidalLowerDeck_EventScript_15FEEE:: @ 815FEEE
	trainerbattle 0, TRAINER_LEONARD, 0, SSTidalLowerDeck_Text_199491, SSTidalLowerDeck_Text_1994F7
	msgbox SSTidalLowerDeck_Text_199508, 6
	end
