SSTidalLowerDeck_MapScripts:: @ 815FED6
	.byte 0

SSTidalLowerDeck_EventScript_15FED7:: @ 815FED7
	trainerbattle_single TRAINER_PHILLIP, SSTidalLowerDeck_Text_1993C1, SSTidalLowerDeck_Text_19941A
	msgbox SSTidalLowerDeck_Text_19942E, MSGBOX_AUTOCLOSE
	end

SSTidalLowerDeck_EventScript_15FEEE:: @ 815FEEE
	trainerbattle_single TRAINER_LEONARD, SSTidalLowerDeck_Text_199491, SSTidalLowerDeck_Text_1994F7
	msgbox SSTidalLowerDeck_Text_199508, MSGBOX_AUTOCLOSE
	end
