	.align 2
gBerryPic_Cheri:: @ 8E78D00
	.incbin "graphics/berries/cheri.4bpp.lz"

	.align 2
gBerryPic_Oran:: @ 8E78E54
	.incbin "graphics/berries/oran.4bpp.lz"

	.align 2
gBerryPic_Pecha:: @ 8E78FC8
	.incbin "graphics/berries/pecha.4bpp.lz"

	.align 2
gBerryPic_Rawst:: @ 8E7913C
	.incbin "graphics/berries/rawst.4bpp.lz"

	.align 2
gBerryPic_Aspear:: @ 8E792D4
	.incbin "graphics/berries/aspear.4bpp.lz"

	.align 2
gBerryPic_Leppa:: @ 8E7947C
	.incbin "graphics/berries/leppa.4bpp.lz"

	.align 2
gBerryPic_Chesto:: @ 8E795EC
	.incbin "graphics/berries/chesto.4bpp.lz"

	.align 2
gBerryPic_Persim:: @ 8E797D0
	.incbin "graphics/berries/persim.4bpp.lz"

	.align 2
gBerryPic_Lum:: @ 8E79920
	.incbin "graphics/berries/lum.4bpp.lz"

	.align 2
gBerryPic_Sitrus:: @ 8E79A3C
	.incbin "graphics/berries/sitrus.4bpp.lz"

	.align 2
gBerryPic_Figy:: @ 8E79BE0
	.incbin "graphics/berries/figy.4bpp.lz"

	.align 2
gBerryPic_Wiki:: @ 8E79D8C
	.incbin "graphics/berries/wiki.4bpp.lz"

	.align 2
gBerryPic_Mago:: @ 8E79F80
	.incbin "graphics/berries/mago.4bpp.lz"

	.align 2
gBerryPic_Aguav:: @ 8E7A134
	.incbin "graphics/berries/aguav.4bpp.lz"

	.align 2
gBerryPic_Iapapa:: @ 8E7A2A8
	.incbin "graphics/berries/iapapa.4bpp.lz"

	.align 2
gBerryPic_Razz:: @ 8E7A560
	.incbin "graphics/berries/razz.4bpp.lz"

	.align 2
gBerryPic_Bluk:: @ 8E7A790
	.incbin "graphics/berries/bluk.4bpp.lz"

	.align 2
gBerryPic_Nanab:: @ 8E7A978
	.incbin "graphics/berries/nanab.4bpp.lz"

	.align 2
gBerryPic_Wepear:: @ 8E7AAEC
	.incbin "graphics/berries/wepear.4bpp.lz"

	.align 2
gBerryPic_Pinap:: @ 8E7ACB4
	.incbin "graphics/berries/pinap.4bpp.lz"

	.align 2
gBerryPic_Pomeg:: @ 8E7AEC8
	.incbin "graphics/berries/pomeg.4bpp.lz"

	.align 2
gBerryPic_Kelpsy:: @ 8E7B070
	.incbin "graphics/berries/kelpsy.4bpp.lz"

	.align 2
gBerryPic_Qualot:: @ 8E7B218
	.incbin "graphics/berries/qualot.4bpp.lz"

	.align 2
gBerryPic_Hondew:: @ 8E7B3E4
	.incbin "graphics/berries/hondew.4bpp.lz"

	.align 2
gBerryPic_Grepa:: @ 8E7B63C
	.incbin "graphics/berries/grepa.4bpp.lz"

	.align 2
gBerryPic_Tamato:: @ 8E7B7CC
	.incbin "graphics/berries/tamato.4bpp.lz"

	.align 2
gBerryPic_Cornn:: @ 8E7BA90
	.incbin "graphics/berries/cornn.4bpp.lz"

	.align 2
gBerryPic_Magost:: @ 8E7BC94
	.incbin "graphics/berries/magost.4bpp.lz"

	.align 2
gBerryPic_Rabuta:: @ 8E7BE38
	.incbin "graphics/berries/rabuta.4bpp.lz"

	.align 2
gBerryPic_Nomel:: @ 8E7C12C
	.incbin "graphics/berries/nomel.4bpp.lz"

	.align 2
gBerryPic_Spelon:: @ 8E7C308
	.incbin "graphics/berries/spelon.4bpp.lz"

	.align 2
gBerryPic_Pamtre:: @ 8E7C4F8
	.incbin "graphics/berries/pamtre.4bpp.lz"

	.align 2
gBerryPic_Watmel:: @ 8E7C748
	.incbin "graphics/berries/watmel.4bpp.lz"

	.align 2
gBerryPic_Durin:: @ 8E7CA2C
	.incbin "graphics/berries/durin.4bpp.lz"

	.align 2
gBerryPic_Belue:: @ 8E7CDF8
	.incbin "graphics/berries/belue.4bpp.lz"

	.align 2
gBerryPic_Liechi:: @ 8E7D0D0
	.incbin "graphics/berries/liechi.4bpp.lz"

	.align 2
gBerryPic_Ganlon:: @ 8E7D328
	.incbin "graphics/berries/ganlon.4bpp.lz"

	.align 2
gBerryPic_Salac:: @ 8E7D4C0
	.incbin "graphics/berries/salac.4bpp.lz"

	.align 2
gBerryPic_Petaya:: @ 8E7D704
	.incbin "graphics/berries/petaya.4bpp.lz"

	.align 2
gBerryPic_Apicot:: @ 8E7D9AC
	.incbin "graphics/berries/apicot.4bpp.lz"

	.align 2
gBerryPic_Lansat:: @ 8E7DB3C
	.incbin "graphics/berries/lansat.4bpp.lz"

	.align 2
gBerryPic_Starf:: @ 8E7DD30
	.incbin "graphics/berries/starf.4bpp.lz"

	.align 2
gBerryPic_Enigma:: @ 8E7DF00
	.incbin "graphics/berries/enigma.4bpp.lz"

	.align 2
gBerryPalette_Cheri:: @ 8E7E118
	.incbin "graphics/berries/cheri.gbapal.lz"

	.align 2
gBerryPalette_Oran:: @ 8E7E140
	.incbin "graphics/berries/oran.gbapal.lz"

	.align 2
gBerryPalette_Pecha:: @ 8E7E168
	.incbin "graphics/berries/pecha.gbapal.lz"

	.align 2
gBerryPalette_Rawst:: @ 8E7E190
	.incbin "graphics/berries/rawst.gbapal.lz"

	.align 2
gBerryPalette_Aspear:: @ 8E7E1B8
	.incbin "graphics/berries/aspear.gbapal.lz"

	.align 2
gBerryPalette_Leppa:: @ 8E7E1E0
	.incbin "graphics/berries/leppa.gbapal.lz"

	.align 2
gBerryPalette_Chesto:: @ 8E7E208
	.incbin "graphics/berries/chesto.gbapal.lz"

	.align 2
gBerryPalette_Persim:: @ 8E7E230
	.incbin "graphics/berries/persim.gbapal.lz"

	.align 2
gBerryPalette_Lum:: @ 8E7E258
	.incbin "graphics/berries/lum.gbapal.lz"

	.align 2
gBerryPalette_Sitrus:: @ 8E7E280
	.incbin "graphics/berries/sitrus.gbapal.lz"

	.align 2
gBerryPalette_Figy:: @ 8E7E2A8
	.incbin "graphics/berries/figy.gbapal.lz"

	.align 2
gBerryPalette_Wiki:: @ 8E7E2D0
	.incbin "graphics/berries/wiki.gbapal.lz"

	.align 2
gBerryPalette_Mago:: @ 8E7E2F8
	.incbin "graphics/berries/mago.gbapal.lz"

	.align 2
gBerryPalette_Aguav:: @ 8E7E320
	.incbin "graphics/berries/aguav.gbapal.lz"

	.align 2
gBerryPalette_Iapapa:: @ 8E7E348
	.incbin "graphics/berries/iapapa.gbapal.lz"

	.align 2
gBerryPalette_Razz:: @ 8E7E370
	.incbin "graphics/berries/razz.gbapal.lz"

	.align 2
gBerryPalette_Bluk:: @ 8E7E398
	.incbin "graphics/berries/bluk.gbapal.lz"

	.align 2
gBerryPalette_Nanab:: @ 8E7E3C0
	.incbin "graphics/berries/nanab.gbapal.lz"

	.align 2
gBerryPalette_Wepear:: @ 8E7E3E8
	.incbin "graphics/berries/wepear.gbapal.lz"

	.align 2
gBerryPalette_Pinap:: @ 8E7E410
	.incbin "graphics/berries/pinap.gbapal.lz"

	.align 2
gBerryPalette_Pomeg:: @ 8E7E438
	.incbin "graphics/berries/pomeg.gbapal.lz"

	.align 2
gBerryPalette_Kelpsy:: @ 8E7E460
	.incbin "graphics/berries/kelpsy.gbapal.lz"

	.align 2
gBerryPalette_Qualot:: @ 8E7E488
	.incbin "graphics/berries/qualot.gbapal.lz"

	.align 2
gBerryPalette_Hondew:: @ 8E7E4B0
	.incbin "graphics/berries/hondew.gbapal.lz"

	.align 2
gBerryPalette_Grepa:: @ 8E7E4D8
	.incbin "graphics/berries/grepa.gbapal.lz"

	.align 2
gBerryPalette_Tamato:: @ 8E7E500
	.incbin "graphics/berries/tamato.gbapal.lz"

	.align 2
gBerryPalette_Cornn:: @ 8E7E528
	.incbin "graphics/berries/cornn.gbapal.lz"

	.align 2
gBerryPalette_Magost:: @ 8E7E550
	.incbin "graphics/berries/magost.gbapal.lz"

	.align 2
gBerryPalette_Rabuta:: @ 8E7E578
	.incbin "graphics/berries/rabuta.gbapal.lz"

	.align 2
gBerryPalette_Nomel:: @ 8E7E5A0
	.incbin "graphics/berries/nomel.gbapal.lz"

	.align 2
gBerryPalette_Spelon:: @ 8E7E5C8
	.incbin "graphics/berries/spelon.gbapal.lz"

	.align 2
gBerryPalette_Pamtre:: @ 8E7E5F0
	.incbin "graphics/berries/pamtre.gbapal.lz"

	.align 2
gBerryPalette_Watmel:: @ 8E7E618
	.incbin "graphics/berries/watmel.gbapal.lz"

	.align 2
gBerryPalette_Durin:: @ 8E7E640
	.incbin "graphics/berries/durin.gbapal.lz"

	.align 2
gBerryPalette_Belue:: @ 8E7E668
	.incbin "graphics/berries/belue.gbapal.lz"

	.align 2
gBerryPalette_Liechi:: @ 8E7E690
	.incbin "graphics/berries/liechi.gbapal.lz"

	.align 2
gBerryPalette_Ganlon:: @ 8E7E6B8
	.incbin "graphics/berries/ganlon.gbapal.lz"

	.align 2
gBerryPalette_Salac:: @ 8E7E6E0
	.incbin "graphics/berries/salac.gbapal.lz"

	.align 2
gBerryPalette_Petaya:: @ 8E7E708
	.incbin "graphics/berries/petaya.gbapal.lz"

	.align 2
gBerryPalette_Apicot:: @ 8E7E730
	.incbin "graphics/berries/apicot.gbapal.lz"

	.align 2
gBerryPalette_Lansat:: @ 8E7E758
	.incbin "graphics/berries/lansat.gbapal.lz"

	.align 2
gBerryPalette_Starf:: @ 8E7E780
	.incbin "graphics/berries/starf.gbapal.lz"

	.align 2
gBerryPalette_Enigma:: @ 8E7E7A8
	.incbin "graphics/berries/enigma.gbapal.lz"
