MossdeepCity_SpaceCenter_1F_Text_RocketLaunchImminent:: @ 818E1F3
	.string "Die Rakete wird in Kürze starten.$"

MossdeepCity_SpaceCenter_1F_Text_SuccessfulLaunchNumber:: @ 818E214
	.string "Die Rakete ist sicher gestartet!\n"
	.string "Das war der erfolgreiche Start Nr. {STR_VAR_1}!$"

MossdeepCity_SpaceCenter_1F_Text_RocketLaunchDemandsPerfection:: @ 818E251
	.string "Jeder Raketenstart verlangt\n"
	.string "sorgfältige Vorbereitungen. Die Fehler-\l"
	.string "quote darf nicht einmal 1% betragen.\p"
	.string "Selbst wenn 99% perfekt sind, kann 1%\n"
	.string "schon für ein Misslingen sorgen.\p"
	.string "Trotzdem versuchen wir es immer wieder.\n"
	.string "Warum? Weil es ein ewiger Traum ist.$"

MossdeepCity_SpaceCenter_1F_Text_FoundThisYouCanHaveIt:: @ 818E335
	.string "Ich schlenderte am Strand entlang, da\n"
	.string "habe ich dieses hier gefunden.\p"
	.string "Ich kann damit nichts anfangen, daher\n"
	.string "kannst du es haben.$"

MossdeepCity_SpaceCenter_1F_Text_HoennFamousForMeteorShowers:: @ 818E39B
	.string "Die HOENN-Region ist bekannt für die\n"
	.string "Häufigkeit der Meteoriteneinschläge.$"

MossdeepCity_SpaceCenter_1F_Text_DidPokemonComeFromSpace:: @ 818E3E5
	.string "Einige Menschen nehmen an, dass die\n"
	.string "POKéMON aus dem Weltall kommen. Ob das\l"
	.string "stimmt?$"

MossdeepCity_SpaceCenter_1F_Text_RocketsBoggleMyMind:: @ 818E427
	.string "Ein gigantischer Brocken Metall durch-\n"
	.string "bricht den Himmel und fliegt ins All...\p"
	.string "Das übersteigt jede Vorstellungskraft.$"
