Route110_TrickHousePuzzle7_Text_JoshuaIntro:: @ 819DF0B
	.string "Der RÄTSELMEISTER verschwindet immer\n"
	.string "wie Rauch. Wie macht er das nur?$"

Route110_TrickHousePuzzle7_Text_JoshuaDefeat:: @ 819DF4B
	.string "Aiijeeh! Du bist viel zu stark!\n"
	.string "Wie machst du das nur?$"

Route110_TrickHousePuzzle7_Text_JoshuaPostBattle:: @ 819DF7E
	.string "Ich wollte, ich könnte mich auch wie\n"
	.string "Rauch in Luft auflösen...$"

Route110_TrickHousePuzzle7_Text_PatriciaIntro:: @ 819DFBB
	.string "Immer am gleichen Ort herumgeistern...\n"
	.string "Das bringt Unglück...$"

Route110_TrickHousePuzzle7_Text_PatriciaDefeat:: @ 819DFF2
	.string "Besiegt!\n"
	.string "Das ist ein schlechtes Omen...$"

Route110_TrickHousePuzzle7_Text_PatriciaPostBattle:: @ 819E00F
	.string "Ich bin nun schon zehn Mal an diesem Ort\n"
	.string "herumgegeistert. Daher hatte ich Pech!$"

Route110_TrickHousePuzzle7_Text_AlexisIntro:: @ 819E054
	.string "Ich glaube, der Sieger wird der erste\n"
	.string "Gewinner an diesem Ort überhaupt sein.$"

Route110_TrickHousePuzzle7_Text_AlexisDefeat:: @ 819E098
	.string "Ah!\n"
	.string "Dann geh hurtig weiter!$"

Route110_TrickHousePuzzle7_Text_AlexisPostBattle:: @ 819E0B2
	.string "Ich glaube, du wirst alle Rätsel in\n"
	.string "diesem RÄTSELHAUS lösen!$"

Route110_TrickHousePuzzle7_Text_WroteSecretCodeLockOpened: @ 819E0FF
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“Ich liebe den RÄTSELMEISTER.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
