LavaridgeTown_HerbShop_Text_WelcomeToHerbShop:: @ 817615C
	.string "Willkommen im KRÄUTERLADEN! Dem Heim\n"
	.string "wirkungsvoller und preiswerter Medizin!$"

LavaridgeTown_HerbShop_Text_YouveComeToLookAtHerbalMedicine:: @ 81761A2
	.string "Du kommst nach BAD LAVASTADT, um\n"
	.string "Kräutermedizin zu kaufen?\p"
	.string "Das ist lobenswert!\p"
	.string "Ich finde dich nett! Hier, für dich!$"

LavaridgeTown_HerbShop_Text_ExplainCharcoal:: @ 8176209
	.string "Mit dieser HOLZKOHLE wird die Kräuter-\n"
	.string "medizin hergestellt.\p"
	.string "Sie wirkt auch Wunder, wenn sie von\n"
	.string "einem POKéMON getragen wird.\p"
	.string "Sie verstärkt FEUER-Attacken.$"

LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike:: @ 81762A3
	.string "Kräutermedizin ist erstaunlich\n"
	.string "wirkungsvoll. Aber deine POKéMON mögen\l"
	.string "sie nicht. Sie schmeckt bitter...$"
