#ifndef GUARD_BATTLEANIM_CONSTANTS_H
#define GUARD_BATTLEANIM_CONSTANTS_H

#define ANIM_BANK_ATTACKER    0
#define ANIM_BANK_TARGET      1
#define ANIM_BANK_ATK_PARTNER 2
#define ANIM_BANK_DEF_PARTNER 3

#endif
