MauvilleCity_BikeShop_Text_180F9F:: @ 8180F9F
	.string "Nun, was haben wir denn hier?\n"
	.string "Einen höchst energetischen Kunden!\p"
	.string "Ich? Du kannst RADLA zu mir sagen.\n"
	.string "Ich bin der Besitzer des Fahrrad-Shops.$"

MauvilleCity_BikeShop_Text_181016:: @ 8181016
	.string "RADLA: Deine TURBOTRETER...\n"
	.string "Die sehen ja wirklich schmuddelig aus...\p"
	.string "Kommst du von weit her?$"

MauvilleCity_BikeShop_Text_181067:: @ 8181067
	.string "RADLA: Stimmt das wirklich?\p"
	.string "Dann kannst du, glaube ich, keines\n"
	.string "meiner Fahrräder gebrauchen.$"

MauvilleCity_BikeShop_Text_1810B1:: @ 81810B1
	.string "RADLA: Hm, hm... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Du kommst den ganzen Weg von\n"
	.string "WURZELHEIM her?\p"
	.string "Meine Güte!\n"
	.string "Das ist unwahrscheinlich weit weg!\p"
	.string "Wenn du eines meiner RÄDER\n"
	.string "hättest, könntest du leicht überall hin\l"
	.string "und den Wind in den Haaren spüren!\p"
	.string "Ich sag dir was!\n"
	.string "Ich werde dir ein RAD geben!\p"
	.string "Oh, eine Sekunde!\p"
	.string "Ich sollte dir sagen, dass es zwei\n"
	.string "verschiedene RÄDER gibt!\p"
	.string "Das EILRAD und das KUNSTRAD!\p"
	.string "EILRÄDER für Leute, die den Wind in\n"
	.string "den Haaren spüren wollen!\p"
	.string "KUNSTRÄDER für Leute, die die\n"
	.string "Techniken des Radfahrens\l"
	.string "beherrschen wollen!\p"
	.string "Da ich ein richtig weiches Herz habe,\n"
	.string "darfst du dir eines aussuchen!\p"
	.string "Welches möchtest du haben?$"

MauvilleCity_BikeShop_Text_181332:: @ 8181332
	.string "{PLAYER} wählt das EILRAD.$"

MauvilleCity_BikeShop_Text_18134A:: @ 818134A
	.string "{PLAYER} wählt das KUNSTRAD.$"

MauvilleCity_BikeShop_Text_181362:: @ 8181362
	.string "RADLA: Wenn du die RÄDER tauschen\n"
	.string "möchtest, komm einfach wieder vorbei!$"

MauvilleCity_BikeShop_Text_1813A0:: @ 81813A0
	.string "RADLA: Oh. Du möchtest die RÄDER\n"
	.string "tauschen?$"

MauvilleCity_BikeShop_Text_1813D4:: @ 81813D4
	.string "RADLA: Kein Problem!\n"
	.string "Ich tausche die RÄDER für dich aus!$"

MauvilleCity_BikeShop_Text_181408:: @ 8181408
	.string "{PLAYER} bekommt für das EILRAD ein\n"
	.string "KUNSTRAD.$"

MauvilleCity_BikeShop_Text_181439:: @ 8181439
	.string "{PLAYER} bekommt für das KUNSTRAD ein\n"
	.string "EILRAD.$"

MauvilleCity_BikeShop_Text_181469:: @ 8181469
	.string "RADLA: Wunderbar!\n"
	.string "Ich freue mich, dass es dir gefällt!$"

MauvilleCity_BikeShop_Text_181498:: @ 8181498
	.string "Oh? Was ist mit dem RAD geschehen,\n"
	.string "das ich dir gegeben habe?\p"
	.string "Ach so, du hast es in deinem PC gelagert.\p"
	.string "Nun, hol es heraus und ich werde es mit\n"
	.string "Freuden gegen ein anderes tauschen!\p"
	.string "Möge der Wind dir stets im Rücken sein\n"
	.string "bei deinem Abenteuer!$"

MauvilleCity_BikeShop_Text_181568:: @ 8181568
	.string "Ich lerne etwas über RÄDER,\n"
	.string "während ich hier arbeite.\p"
	.string "Wenn du eine Anleitung brauchst, wie\n"
	.string "man RAD fährt - da vorne findest du\l"
	.string "einige Handbücher.$"

MauvilleCity_BikeShop_Text_1815EA:: @ 81815EA
	.string "Ein Handbuch zum EILRAD.\p"
	.string "Welche Seite möchtest du lesen?$"

MauvilleCity_BikeShop_Text_18162C:: @ 818162C
	.string "Mit Hilfe des + Steuerkreuzes lässt\n"
	.string "sich das RAD lenken.\p"
	.string "Es wird immer schneller, wenn es\n"
	.string "einmal fährt.\p"
	.string "Lass das Steuerkreuz los, um das\n"
	.string "RAD anzuhalten.\p"
	.string "Eine andere Seite lesen?$"

MauvilleCity_BikeShop_Text_1816F5:: @ 81816F5
	.string "Ein EILRAD ist sehr schnell und kann\n"
	.string "nicht schnell gestoppt werden.\p"
	.string "Das Kurvenfahren ist sehr schwierig.\p"
	.string "Lasse das + Steuerkreuz etwas los und\n"
	.string "bremse, bevor du an eine Kurve kommst.\p"
	.string "Eine andere Seite lesen?$"

MauvilleCity_BikeShop_Text_1817BF:: @ 81817BF
	.string "In der ganzen HOENN-Region gibt es\n"
	.string "sandige Gefälle.\p"
	.string "Der lose Sand erlaubt es nicht, diese\n"
	.string "Gefälle normal zu erklettern.\p"
	.string "Aber mit einem EILRAD können auch\n"
	.string "diese Gefälle gemeistert werden.\p"
	.string "Eine andere Seite lesen?$"

MauvilleCity_BikeShop_Text_181892:: @ 8181892
	.string "Ein Handbuch zum KUNSTRAD.\p"
	.string "Welche Seite möchtest du lesen?$"

MauvilleCity_BikeShop_Text_1818D4:: @ 81818D4
	.string "Drücke während des Fahrens den\n"
	.string "B-Knopf, um das Vorderrad anzuheben.\p"
	.string "Ist das Vorderrad angehoben, können\n"
	.string "mit Hilfe des Steuerkreuzes Sprünge\l"
	.string "ausgeführt werden.\p"
	.string "Diese Technik nennt sich Wheelie.\p"
	.string "Eine andere Seite lesen?$"

MauvilleCity_BikeShop_Text_18199A:: @ 818199A
	.string "Wird der B-Knopf gedrückt, kann auf der\n"
	.string "Stelle gehüpft werden.\p"
	.string "Diese Technik nennt sich Hoppeln.\p"
	.string "Dabei kann gleichzeitig gefahren\n"
	.string "werden.\p"
	.string "Eine andere Seite lesen?$"

MauvilleCity_BikeShop_Text_181A3D:: @ 8181A3D
	.string "Drücke gleichzeitig den B-Knopf und das\n"
	.string "Steuerkreuz, um zu springen.\p"
	.string "Drücke das + Steuerkreuz seitlich, um\n"
	.string "einen seitlichen Sprung auszuführen.\p"
	.string "Drücke es nach hinten, um die Richtung\n"
	.string "zu ändern.\p"
	.string "Eine andere Seite lesen?$"
