LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls:: @ 818C4F9
	.string "This place is full of cute DOLLS.\p"
	.string "I should buy some for me, instead of\n"
	.string "just for my children.$"

LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon:: @ 818C556
	.string "I'm not big enough to raise POKéMON,\n"
	.string "so I'm getting a cute DOLL instead.$"

LilycoveCity_DepartmentStore_5F_Text_SellManyCuteMatsHere:: @ 818C59F
	.string "They sell many cute MATS here.\p"
	.string "I wonder which one I should get?\n"
	.string "Maybe I'll buy them all...$"

LilycoveCity_DepartmentStore_5F_Text_UnusedFloorInfo: @ 818C5FA
	.string "ADORABLE FRIENDS\n"
	.string "5F: POKé DOLL FLOOR$"
