RivalsHouse_1F_Text_OhYoureTheNewNeighbor:: @ 81730C2
	.string "Oh, hello. And you are?\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ... ...\p"
	.string "Oh, you're {PLAYER}{KUN}, our new next-door\n"
	.string "neighbor! Hi!\p"
	.string "We have a {STR_VAR_1} about the same\n"
	.string "age as you.\p"
	.string "Our {STR_VAR_1} was excited about making\n"
	.string "a new friend.\p"
	.string "Our {STR_VAR_1} is upstairs, I think.$"

RivalsHouse_1F_Text_RivalIsUpstairsIThink:: @ 81731C6
	.string "Our {STR_VAR_1} is upstairs, I think.$"

RivalsHouse_1F_Text_WhereHasHusbandGone:: @ 81731E3
	.string "Where has my husband gone?\n"
	.string "Just when {PLAYER}{KUN} is visiting, too...\p"
	.string "That man can never sit still for long...\n"
	.string "He might be at his LAB.$"

RivalsHouse_1F_Text_WentOutSomewhere:: @ 8173262
	.string "Oh, {RIVAL} has gone out somewhere.\p"
	.string "Like father, like child.\n"
	.string "{RIVAL} can't stay quietly at home.$"

RivalsHouse_1F_Text_ShouldGoHomeEverySoOften:: @ 81732B9
	.string "I think it's wonderful for people to\n"
	.string "travel with POKéMON.\p"
	.string "But you should go home every so often\n"
	.string "to let your mother know you're okay.\p"
	.string "She might not say it, but I'm sure she\n"
	.string "worries about you, {PLAYER}{KUN}.$"
