PacifidlogTown_House5_Text_CantSeeMirageIslandToday:: @ 8179718
	.string "I can't see MIRAGE ISLAND today...$"

PacifidlogTown_House5_Text_CanSeeMirageIslandToday:: @ 817973B
	.string "Oh! Oh my!\n"
	.string "I can see MIRAGE ISLAND today!$"

PacifidlogTown_House5_Text_MirageIslandAppearDependingOnWeather:: @ 8179765
	.string "MIRAGE ISLAND...\p"
	.string "It must become visible and invisible\n"
	.string "depending on the weather conditions\l"
	.string "that make mirages appear.\p"
	.string "Or is it really appearing and\n"
	.string "disappearing?$"
