gEasyChatGroupWords_Trainer:
	.string "DU BIST DRAN$"
	.string "HAB DICH$"
	.string "TAUSCH$"
	.string "SAPHIR$"
	.string "ENTWICKELN$"
	.string "ENZYKLOPÄDIE$"
	.string "WESEN$"
	.string "CENTER$"
	.string "EI$"
	.string "LINK$"
	.string "FÄHIGKEIT$"
	.string "TRAINER$"
	.string "VERSION$"
	.string "POKéNAV$"
	.string "POKéMON$"
	.string "BEKOMMEN$"
	.string "POKéDEX$"
	.string "RUBIN$"
	.string "LEVEL$"
	.string "$"
