Route108_MapScripts:: @ 814F475
	.byte 0

Route108_EventScript_14F476:: @ 814F476
	trainerbattle_single TRAINER_JEROME, Route108_Text_1B97C3, Route108_Text_1B97EF
	msgbox Route108_Text_1B9823, 6
	end

Route108_EventScript_14F48D:: @ 814F48D
	trainerbattle_single TRAINER_MATTHEW, Route108_Text_1B9864, Route108_Text_1B989F
	msgbox Route108_Text_1B98BC, 6
	end

Route108_EventScript_14F4A4:: @ 814F4A4
	trainerbattle_single TRAINER_TARA, Route108_Text_1B98EC, Route108_Text_1B992C
	msgbox Route108_Text_1B9935, 6
	end

Route108_EventScript_14F4BB:: @ 814F4BB
	trainerbattle_single TRAINER_MISSY, Route108_Text_1B9986, Route108_Text_1B99BB
	msgbox Route108_Text_1B99E9, 6
	end
