Route110_TrickHousePuzzle5_Text_Mechadoll1Intro:: @ 819D423
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 1 ICH BIN!\p"
	.string "GIBST DU IM QUIZ RICHTIGE ANTWORTEN,\n"
	.string "ERREICHST DU BALD ROBOPUPPE 5.\l"
	.string "DORT ERHÄLTST DU DEN GEHEIMEN CODE.$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz1:: @ 819D4AE
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON kann man nicht\n"
	.string "auf der ROUTE 103 finden. Welches?$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz2:: @ 819D501
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON ist kein\n"
	.string "PFLANZEN-POKéMON. Welches?$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz3:: @ 819D553
	.string "ROBOPUPPE 1 QUIZ.\p"
	.string "Eines dieser POKéMON setzt\n"
	.string "KRATZER ein. Welches?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough1:: @ 819D599
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_DisappointmentError:: @ 819D5CF
	.string "BZZZT. ENTTÄUSCHEND.\n"
	.string "FEHLER.$"

Route110_TrickHousePuzzle5_Text_Wahahahaha:: @ 819D5ED
	.string "WAHAHAHAHA! WAHAHAHAHA!\n"
	.string "KLICK-KLACK!$"

Route110_TrickHousePuzzle5_Text_WaitForNextChallenge:: @ 819D615
	.string "DEINE NÄCHSTE HERAUSFORDERUNG WIR\n"
	.string "ERWARTEN.$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Intro:: @ 819D636
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 2 ICH BIN!\p"
	.string "ROBOPUPPE 1 QUIZ-SCHWIERIGKEITS-\n"
	.string "GRAD IST ZU NIEDRIG.$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz1:: @ 819D68E
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "In PROF. BIRKS Beutel befanden sich\n"
	.string "drei POKéMON. Welches lag ganz rechts?$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz2:: @ 819D6EC
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "Welches POKéMON wurde in der POKéMON\n"
	.string "TRAINERSCHULE zum Tausch angeboten?$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz3:: @ 819D745
	.string "ROBOPUPPE 2 QUIZ.\p"
	.string "Welches POKéMON hat der FORSCHER von\n"
	.string "DEVON im BLÜTENBURGWALD gesucht?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough2: @ 819D79D
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Intro:: @ 819D7D3
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 3 ICH BIN!\p"
	.string "FÜR MICH ZÄHLT NUR GELD.$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz1:: @ 819D81B
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Was ist teurer?\n"
	.string "Drei POKéBÄLLE oder ein SUPERTRANK?$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz2:: @ 819D865
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Verkaufe ein FLUCHTSEIL und kaufe ein\n"
	.string "GEGENGIFT. Wie viel Geld bleibt übrig?$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz3:: @ 819D8BA
	.string "ROBOPUPPE 3 QUIZ.\p"
	.string "Kosten ein HYPERHEILER und ein\n"
	.string "SUPERBALL mehr als ein BELEBER?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough3: @ 819D907
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Intro:: @ 819D93D
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 4 ICH BIN!\p"
	.string "ICH INTERESSIERE MICH FÜR SCHÖNES.$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz1:: @ 819D987
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "ARENALEITERIN FELIZIA in METAROST\n"
	.string "CITY kämpft mit KLEINSTEIN. Ist es\l"
	.string "männlich oder weiblich?$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz2:: @ 819D9DC
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "Befanden sich in der FAUSTAUHAVEN\n"
	.string "HALLE mehr Männer oder mehr Frauen?$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz3:: @ 819DA1D
	.string "ROBOPUPPE 4 QUIZ.\p"
	.string "Der erste TRAINER in der ARENA von\n"
	.string "FAUSTAUHAVEN, war der männlich oder\l"
	.string "weiblich?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough4: @ 819DA64
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Intro:: @ 819DA9A
	.string "KLICK-KLACK...\n"
	.string "ROBOPUPPE 5 ICH BIN!\p"
	.string "DES MEISTERS BESTE UND STOLZESTE\n"
	.string "ERFINDUNG ICH BIN.$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz1:: @ 819DAEF
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Wie viele RÄDER stehen bei\n"
	.string "RADLA vor dem Laden?$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz2:: @ 819DB43
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Von wie vielen Leuten bekommst du im\n"
	.string "BLÜTENTRAUM BLUMENLADEN BEEREN?$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz3:: @ 819DB97
	.string "ROBOPUPPE 5 QUIZ.\p"
	.string "Wie viele Schilder gibt es in\n"
	.string "SEEGRASULB CITY?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough5: @ 819DBD4
	.string "GLÜCKWUNSCH! RICHTIG.\n"
	.string "GEHE HINDURCH. BITTE.$"

Route110_TrickHousePuzzle5_Text_WroteSecretCodeLockOpened: @ 819DC0A
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist mein Leben.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
