VerdanturfTown_Mart_Text_XSpecialIsCrucial:: @ 81781C9
	.string "For any POKéMON match, X SPECIAL\n"
	.string "is crucial.\p"
	.string "It jacks up the power of some moves\n"
	.string "even though it's only for one battle.$"

VerdanturfTown_Mart_Text_NoStrategyGuidesForContest:: @ 8178240
	.string "They don't sell any items that will let\n"
	.string "you win CONTESTS...\p"
	.string "It means you have to raise POKéMON\n"
	.string "diligently on an everyday basis.$"

VerdanturfTown_Mart_Text_NestBallOnWeakenedPokemon:: @ 81782C0
	.string "The NEST BALL works better on\n"
	.string "weakened POKéMON.\p"
	.string "VERDANTURF is the only place you can\n"
	.string "buy it.$"
