PetalburgCity_House1_Text_17BAFB:: @ 817BAFB
	.string "Reisen ist einfach wundervoll!\p"
	.string "Als ich noch jung war, waren die See und\n"
	.string "die Berge mein Zuhause.$"

PetalburgCity_House1_Text_17BB4A:: @ 817BB4A
	.string "Seufz...\p"
	.string "Ich wünschte, ich könnte mit einigen\n"
	.string "POKéMON auf Abenteuerreise gehen...\p"
	.string "Sich durch hohes Gras schleichen...\n"
	.string "Steile, zerklüftete Berge erklimmen...\p"
	.string "Das tosende Meer überqueren...\n"
	.string "Dunkle Höhlen erforschen...\p"
	.string "Und manchmal ein wenig Heimweh haben...\p"
	.string "Reisen muss einfach toll sein!$"
