EverGrandeCity_DrakesRoom_MapObjects:: @ 838B2F8
	object_event 1, MAP_OBJ_GFX_DRAKE, 0, 6, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, EverGrandeCity_DrakesRoom_EventScript_15B764, 0, 0, 0

EverGrandeCity_DrakesRoom_MapWarps:: @ 838B310
	warp_def 6, 13, 3, 1, MAP_EVER_GRANDE_CITY_CORRIDOR3
	warp_def 6, 2, 0, 0, MAP_EVER_GRANDE_CITY_CORRIDOR4

EverGrandeCity_DrakesRoom_MapEvents:: @ 838B320
	map_events EverGrandeCity_DrakesRoom_MapObjects, EverGrandeCity_DrakesRoom_MapWarps, 0x0, 0x0
