FortreeCity_DecorationShop_MapObjects:: @ 83893E0
	object_event 1, MAP_OBJ_GFX_MAN_3, 0, 6, 0, 5, 0, 3, 1, 17, 0, 0, 0, 0, 0, FortreeCity_DecorationShop_EventScript_158258, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_GIRL_3, 0, 0, 0, 4, 0, 3, 9, 0, 0, 0, 0, 0, 0, FortreeCity_DecorationShop_EventScript_158261, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_MART_EMPLOYEE, 0, 1, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, FortreeCity_DecorationShop_EventScript_15826A, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_MART_EMPLOYEE, 0, 6, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, FortreeCity_DecorationShop_EventScript_158298, 0, 0, 0

FortreeCity_DecorationShop_MapWarps:: @ 8389440
	warp_def 3, 5, 0, 8, MAP_FORTREE_CITY
	warp_def 4, 5, 0, 8, MAP_FORTREE_CITY

FortreeCity_DecorationShop_MapEvents:: @ 8389450
	map_events FortreeCity_DecorationShop_MapObjects, FortreeCity_DecorationShop_MapWarps, 0x0, 0x0
