GraniteCave_StevensRoom_MapObjects:: @ 838C118
	object_event 1, MAP_OBJ_GFX_STEVEN, 0, 7, 0, 8, 0, 3, 1, 0, 0, 0, 0, 0, 0, GraniteCave_StevensRoom_EventScript_15CBFA, 833, 0, 0

GraniteCave_StevensRoom_MapWarps:: @ 838C130
	warp_def 7, 3, 3, 3, MAP_GRANITE_CAVE_1F

GraniteCave_StevensRoom_MapEvents:: @ 838C138
	map_events GraniteCave_StevensRoom_MapObjects, GraniteCave_StevensRoom_MapWarps, 0x0, 0x0
