LilycoveCity_DepartmentStoreElevator_MapObjects:: @ 838A624
	object_event 1, MAP_OBJ_GFX_TEALA, 0, 0, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_DepartmentStoreElevator_EventScript_15A39C, 0, 0, 0

LilycoveCity_DepartmentStoreElevator_MapWarps:: @ 838A63C
	warp_def 1, 5, 3, 127, None
	warp_def 2, 5, 3, 127, None

LilycoveCity_DepartmentStoreElevator_MapEvents:: @ 838A64C
	map_events LilycoveCity_DepartmentStoreElevator_MapObjects, LilycoveCity_DepartmentStoreElevator_MapWarps, 0x0, 0x0
