LilycoveCity_MapObjects:: @ 838016C
	object_event 1, MAP_OBJ_GFX_SAILOR, 0, 32, 0, 20, 0, 3, 3, 16, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CBEF, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_GIRL_1, 0, 15, 0, 18, 0, 3, 2, 17, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CBC7, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_MAN_1, 0, 28, 0, 28, 0, 3, 1, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CBBE, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_BOY_4, 0, 21, 0, 15, 0, 3, 2, 17, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CBE6, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_MAN_2, 0, 16, 0, 9, 0, 5, 5, 1, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CC2D, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_WOMAN_3, 0, 35, 0, 27, 0, 3, 2, 17, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CC0E, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_OLD_MAN_1, 0, 35, 0, 37, 0, 5, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CC36, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_OLD_WOMAN_1, 0, 34, 0, 37, 0, 5, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CC3F, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_OLD_MAN_1, 0, 57, 0, 17, 0, 3, 1, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CC48, 0, 0, 0
	object_event 10, 241, 0, 73, 0, 15, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CCE5, 852, 0, 0
	object_event 11, MAP_OBJ_GFX_ITEM_BALL, 0, 61, 0, 36, 0, 5, 1, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_1B1738, 1042, 0, 0
	object_event 12, 241, 0, 43, 0, 18, 0, 3, 5, 1, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CD3D, 852, 0, 0
	object_event 13, 241, 0, 46, 0, 12, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CD22, 852, 0, 0
	object_event 14, 241, 0, 45, 0, 12, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CD2B, 852, 0, 0
	object_event 15, 241, 0, 38, 0, 9, 0, 5, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CD34, 852, 0, 0
	object_event 16, MAP_OBJ_GFX_GENTLEMAN, 0, 50, 0, 7, 0, 5, 2, 17, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CB74, 0, 0, 0
	object_event 17, 240, 0, 27, 0, 7, 0, 5, 8, 17, 0, 0, 0, 0, 0, LilycoveCity_EventScript_14CD46, 971, 0, 0

LilycoveCity_MapWarps:: @ 8380304
	warp_def 27, 6, 0, 0, MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F
	warp_def 37, 24, 0, 0, MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F
	warp_def 24, 14, 0, 0, MAP_LILYCOVE_CITY_POKEMON_CENTER_1F
	warp_def 11, 5, 0, 0, MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F
	warp_def 23, 24, 0, 0, MAP_LILYCOVE_CITY_CONTEST_LOBBY
	warp_def 39, 14, 0, 1, MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB
	warp_def 70, 5, 1, 0, MAP_AQUA_HIDEOUT_1F
	warp_def 36, 6, 0, 0, MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE
	warp_def 42, 6, 0, 0, MAP_LILYCOVE_CITY_HOUSE1
	warp_def 55, 15, 0, 0, MAP_LILYCOVE_CITY_HOUSE2
	warp_def 11, 22, 0, 0, MAP_LILYCOVE_CITY_HOUSE3
	warp_def 12, 14, 0, 0, MAP_LILYCOVE_CITY_HOUSE4
	warp_def 12, 32, 0, 0, MAP_LILYCOVE_CITY_HARBOR
	warp_def 12, 5, 0, 1, MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F
	warp_def 71, 5, 1, 0, MAP_MAGMA_HIDEOUT_1F

LilycoveCity_MapBGEvents:: @ 838037C
	bg_event 19, 7, 0, 0, 0, LilycoveCity_EventScript_14CC82
	bg_event 25, 14, 0, 1, 0, LilycoveCity_EventScript_1A00EA
	bg_event 29, 7, 0, 0, 0, LilycoveCity_EventScript_14CCD3
	bg_event 26, 14, 0, 1, 0, LilycoveCity_EventScript_1A00EA
	bg_event 6, 15, 0, 0, 0, LilycoveCity_EventScript_14CC67
	bg_event 29, 24, 0, 0, 0, LilycoveCity_EventScript_14CC70
	bg_event 35, 24, 0, 0, 0, LilycoveCity_EventScript_14CC79
	bg_event 6, 30, 3, 0, 0, LilycoveCity_EventScript_14CCAC
	bg_event 36, 14, 0, 0, 0, LilycoveCity_EventScript_14CCCA
	bg_event 34, 6, 0, 0, 0, LilycoveCity_EventScript_14CCDC
	bg_event 36, 31, 3, 7, 0, ITEM_HEART_SCALE, 27, 0
	bg_event 61, 7, 0, 7, 0, ITEM_PP_UP, 43, 0
	bg_event 64, 31, 0, 7, 0, ITEM_POKE_BALL, 75, 0

LilycoveCity_MapEvents:: @ 8380418
	map_events LilycoveCity_MapObjects, LilycoveCity_MapWarps, 0x0, LilycoveCity_MapBGEvents
