LilycoveCity_CoveLilyMotel_2F_MapObjects:: @ 83894B8
	object_event 1, MAP_OBJ_GFX_MAN_4, 0, 4, 0, 6, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_1583A1, 925, 0, 0
	object_event 2, MAP_OBJ_GFX_SCIENTIST_1, 0, 1, 0, 4, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_1583F7, 925, 0, 0
	object_event 3, MAP_OBJ_GFX_FAT_MAN, 0, 7, 0, 7, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_158400, 925, 0, 0
	object_event 4, MAP_OBJ_GFX_MAN_5, 0, 10, 0, 3, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_1583EE, 925, 0, 0
	object_event 5, MAP_OBJ_GFX_BOY_5, 0, 7, 0, 3, 0, 3, 8, 17, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_158412, 925, 0, 0
	object_event 6, MAP_OBJ_GFX_WOMAN_3, 0, 4, 0, 4, 0, 3, 9, 17, 0, 0, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_158409, 925, 0, 0

LilycoveCity_CoveLilyMotel_2F_MapWarps:: @ 8389548
	warp_def 2, 1, 0, 2, MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F

LilycoveCity_CoveLilyMotel_2F_MapEvents:: @ 8389550
	map_events LilycoveCity_CoveLilyMotel_2F_MapObjects, LilycoveCity_CoveLilyMotel_2F_MapWarps, 0x0, 0x0
