LilycoveCity_ContestHall_MapObjects:: @ 8389A18
	object_event 1, MAP_OBJ_GFX_BOY_1, 0, 30, 0, 30, 0, 3, 2, 68, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15909B, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_BOY_3, 0, 11, 0, 7, 0, 3, 2, 51, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590A4, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_GIRL_3, 0, 40, 0, 8, 0, 3, 2, 34, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590AD, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_WOMAN_4, 0, 12, 0, 22, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590BF, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_CONTEST_JUDGE, 0, 15, 0, 22, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590D4, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_BLACK_BELT, 0, 10, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590E9, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_OLD_MAN_1, 0, 12, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590FE, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_MANIAC, 0, 14, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159113, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_WOMAN_6, 0, 16, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159128, 0, 0, 0
	object_event 10, MAP_OBJ_GFX_OLD_WOMAN_1, 0, 8, 0, 24, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15913D, 0, 0, 0
	object_event 11, MAP_OBJ_GFX_WOMAN_7, 0, 18, 0, 24, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159170, 0, 0, 0
	object_event 12, MAP_OBJ_GFX_BOY_1, 0, 8, 0, 22, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159146, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_WOMAN_4, 0, 24, 0, 10, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159185, 0, 0, 0
	object_event 14, MAP_OBJ_GFX_CONTEST_JUDGE, 0, 27, 0, 10, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15919A, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_WOMAN_5, 0, 22, 0, 13, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1591AF, 0, 0, 0
	object_event 16, MAP_OBJ_GFX_LITTLE_GIRL_1, 0, 24, 0, 13, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1591C4, 0, 0, 0
	object_event 17, MAP_OBJ_GFX_PSYCHIC_M, 0, 26, 0, 13, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1591D9, 0, 0, 0
	object_event 18, MAP_OBJ_GFX_WOMAN_2, 0, 28, 0, 13, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1591EE, 0, 0, 0
	object_event 19, MAP_OBJ_GFX_WOMAN_3, 0, 20, 0, 10, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159203, 0, 0, 0
	object_event 20, MAP_OBJ_GFX_WOMAN_1, 0, 30, 0, 11, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15922D, 0, 0, 0
	object_event 21, MAP_OBJ_GFX_MAN_1, 0, 26, 0, 8, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159218, 0, 0, 0
	object_event 22, MAP_OBJ_GFX_CAMPER, 0, 13, 0, 20, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15915B, 0, 0, 0
	object_event 23, MAP_OBJ_GFX_WOMAN_4, 0, 36, 0, 22, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159242, 0, 0, 0
	object_event 24, MAP_OBJ_GFX_CONTEST_JUDGE, 0, 39, 0, 22, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159257, 0, 0, 0
	object_event 25, MAP_OBJ_GFX_BOY_2, 0, 34, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15926C, 0, 0, 0
	object_event 26, MAP_OBJ_GFX_GIRL_2, 0, 36, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159281, 0, 0, 0
	object_event 27, MAP_OBJ_GFX_BOY_3, 0, 38, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159296, 0, 0, 0
	object_event 28, MAP_OBJ_GFX_OLD_WOMAN_1, 0, 40, 0, 25, 0, 3, 7, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1592AB, 0, 0, 0
	object_event 29, MAP_OBJ_GFX_WOMAN_3, 0, 32, 0, 23, 0, 3, 10, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1592C0, 0, 0, 0
	object_event 30, MAP_OBJ_GFX_MAN_1, 0, 37, 0, 20, 0, 3, 8, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1592F7, 0, 0, 0
	object_event 31, MAP_OBJ_GFX_LITTLE_GIRL_2, 0, 42, 0, 24, 0, 3, 9, 0, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1592E2, 0, 0, 0
	object_event 32, MAP_OBJ_GFX_SAILOR, 0, 23, 0, 26, 0, 3, 2, 17, 0, 0, 0, 0, 0, LilycoveCity_ContestHall_EventScript_1590B6, 0, 0, 0

LilycoveCity_ContestHall_MapWarps:: @ 8389D18
	warp_def 19, 32, 0, 2, MAP_LILYCOVE_CITY_CONTEST_LOBBY
	warp_def 30, 32, 0, 3, MAP_LILYCOVE_CITY_CONTEST_LOBBY
	warp_def 20, 32, 0, 2, MAP_LILYCOVE_CITY_CONTEST_LOBBY
	warp_def 31, 32, 0, 3, MAP_LILYCOVE_CITY_CONTEST_LOBBY

LilycoveCity_ContestHall_MapBGEvents:: @ 8389D38
	bg_event 27, 16, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15930C
	bg_event 39, 28, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159315
	bg_event 11, 28, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15931E
	bg_event 15, 28, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15931E
	bg_event 23, 16, 0, 0, 0, LilycoveCity_ContestHall_EventScript_15930C
	bg_event 35, 28, 0, 0, 0, LilycoveCity_ContestHall_EventScript_159315

LilycoveCity_ContestHall_MapEvents:: @ 8389D80
	map_events LilycoveCity_ContestHall_MapObjects, LilycoveCity_ContestHall_MapWarps, 0x0, LilycoveCity_ContestHall_MapBGEvents
