LinkContestRoom1_MapObjects:: @ 839149C
	object_event 1, MAP_OBJ_GFX_WOMAN_4, 0, 6, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_CONTEST_JUDGE, 0, 7, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_VAR_0, 0, 4, 0, 7, 0, 3, 7, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_VAR_1, 0, 6, 0, 7, 0, 3, 7, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_VAR_2, 0, 8, 0, 7, 0, 3, 7, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_VAR_4, 0, 2, 0, 6, 0, 3, 10, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_VAR_6, 0, 4, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_VAR_7, 0, 5, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_VAR_8, 0, 9, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 10, MAP_OBJ_GFX_VAR_9, 0, 10, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 11, MAP_OBJ_GFX_VAR_A, 0, 12, 0, 5, 0, 3, 9, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 12, MAP_OBJ_GFX_VAR_5, 0, 2, 0, 5, 0, 3, 10, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_ITEM_BALL, 0, 7, 0, 5, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0x0, FLAG_LINK_CONTEST_ROOM_POKEBALL, 0, 0
	object_event 14, MAP_OBJ_GFX_VAR_3, 0, 10, 0, 7, 0, 3, 7, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_ARTIST, 0, 12, 0, 6, 0, 3, 9, 0, 0, 0, 0, 0, 0, 0x0, 0, 0, 0

LinkContestRoom1_MapEvents:: @ 8391604
