Route132_EventObjects:: @ 8385344
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 7, 0, 3, 0, 1, 46, 51, 0, 1, 0, 2, 0, Route132_EventScript_1524E5, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 41, 0, 16, 0, 1, 49, 68, 0, 1, 0, 2, 0, Route132_EventScript_1524FC, 0, 0, 0
	object_event 3, EVENT_OBJ_GFX_ITEM_BALL, 0, 10, 0, 11, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route132_EventScript_1B16DD, FLAG_ITEM_ROUTE132_1, 0, 0
	object_event 4, EVENT_OBJ_GFX_BLACK_BELT, 0, 46, 0, 28, 0, 3, 10, 0, 0, 1, 0, 4, 0, Route132_EventScript_15252A, 0, 0, 0
	object_event 5, EVENT_OBJ_GFX_FISHERMAN, 0, 9, 0, 16, 0, 3, 8, 0, 0, 1, 0, 1, 0, Route132_EventScript_152513, 0, 0, 0

Route132_MapEvents:: @ 83853BC
	map_events Route132_EventObjects, 0x0, 0x0, 0x0
