Route116_TunnelersRestHouse_EventObjects:: @ 838B98C
	object_event 1, EVENT_OBJ_GFX_MAN_3, 0, 6, 0, 5, 0, 3, 10, 0, 0, 0, 0, 0, 0, Route116_TunnelersRestHouse_EventScript_15C2E8, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_MAN_3, 0, 3, 0, 6, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route116_TunnelersRestHouse_EventScript_15C2FA, 0, 0, 0
	object_event 3, EVENT_OBJ_GFX_MAN_3, 0, 7, 0, 2, 0, 3, 7, 1, 0, 0, 0, 0, 0, Route116_TunnelersRestHouse_EventScript_15C2F1, 0, 0, 0

Route116_TunnelersRestHouse_MapWarps:: @ 838B9D4
	warp_def 4, 8, 0, 1, MAP_ROUTE116
	warp_def 5, 8, 0, 1, MAP_ROUTE116

Route116_TunnelersRestHouse_MapEvents:: @ 838B9E4
	map_events Route116_TunnelersRestHouse_EventObjects, Route116_TunnelersRestHouse_MapWarps, 0x0, 0x0
