Route107_EventObjects:: @ 83819D0
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 27, 10, 1, 24, 17, 1, 3, Route107_EventScript_14F3BC, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_M, 0, 38, 11, 1, 52, 38, 1, 2, Route107_EventScript_14F3D3, 0
	object_event 3, EVENT_OBJ_GFX_SWIMMER_F, 0, 50, 6, 1, 14, 0, 1, 3, Route107_EventScript_14F411, 0
	object_event 4, EVENT_OBJ_GFX_SWIMMER_F, 0, 16, 11, 1, 7, 0, 1, 4, Route107_EventScript_14F428, 0
	object_event 5, EVENT_OBJ_GFX_SWIMMER_F, 0, 33, 4, 1, 8, 17, 1, 0, Route107_EventScript_14F43F, 0
	object_event 6, EVENT_OBJ_GFX_TUBER_M_SWIMMING, 0, 32, 4, 1, 8, 17, 1, 0, Route107_EventScript_14F45A, 0

Route107_MapEvents:: @ 8381A60
	map_events Route107_EventObjects, 0x0, 0x0, 0x0
