Route119_MapObjects:: @ 8383914
	object_event 1, MAP_OBJ_GFX_BERRY_TREE, 0, 24, 0, 5, 0, 3, 12, 0, 0, 0, 0, 34, 0, S_BerryTree, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_BERRY_TREE, 0, 25, 0, 5, 0, 3, 12, 0, 0, 0, 0, 35, 0, S_BerryTree, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_BERRY_TREE, 0, 26, 0, 5, 0, 3, 12, 0, 0, 0, 0, 36, 0, S_BerryTree, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_BUG_CATCHER, 0, 12, 0, 123, 0, 3, 59, 0, 0, 1, 0, 1, 0, Route119_EventScript_151491, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_MANIAC, 0, 26, 0, 123, 0, 3, 60, 0, 0, 1, 0, 1, 0, Route119_EventScript_151463, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_MANIAC, 0, 5, 0, 125, 0, 3, 62, 0, 0, 1, 0, 1, 0, Route119_EventScript_15144C, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_CAMPER, 0, 7, 0, 74, 0, 3, 18, 0, 0, 1, 0, 3, 0, Route119_EventScript_1514BF, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_MANIAC, 0, 28, 0, 116, 0, 3, 60, 0, 0, 1, 0, 1, 0, Route119_EventScript_151435, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_PICNICKER, 0, 35, 0, 83, 0, 4, 8, 0, 0, 1, 0, 2, 0, Route119_EventScript_1514FD, 0, 0, 0
	object_event 10, MAP_OBJ_GFX_BUG_CATCHER, 0, 34, 0, 122, 0, 3, 61, 0, 0, 1, 0, 1, 0, Route119_EventScript_15147A, 0, 0, 0
	object_event 11, MAP_OBJ_GFX_BUG_CATCHER, 0, 17, 0, 128, 0, 3, 61, 0, 0, 1, 0, 1, 0, Route119_EventScript_1514A8, 0, 0, 0
	object_event 12, MAP_OBJ_GFX_LITTLE_BOY_1, 0, 28, 0, 16, 0, 3, 57, 0, 0, 1, 0, 2, 0, Route119_EventScript_151569, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_LITTLE_BOY_1, 0, 19, 0, 49, 0, 3, 58, 0, 0, 1, 0, 3, 0, Route119_EventScript_151580, 0, 0, 0
	object_event 14, MAP_OBJ_GFX_MAN_6, 0, 10, 0, 50, 0, 4, 10, 0, 0, 1, 0, 3, 0, Route119_EventScript_15153B, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_MAN_6, 0, 8, 0, 62, 0, 3, 8, 0, 0, 1, 0, 3, 0, Route119_EventScript_151552, 0, 0, 0
	object_event 16, MAP_OBJ_GFX_VAR_0, 0, 25, 0, 32, 0, 3, 7, 0, 0, 0, 0, 0, 0, 0x0, FLAG_HIDE_RIVAL_ROUTE119, 0, 0
	object_event 17, MAP_OBJ_GFX_ITEM_BALL, 0, 12, 0, 121, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B15BF, FLAG_ITEM_ROUTE119_1, 0, 0
	object_event 18, MAP_OBJ_GFX_ITEM_BALL, 0, 4, 0, 96, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B15CC, FLAG_ITEM_ROUTE119_2, 0, 0
	object_event 19, MAP_OBJ_GFX_ITEM_BALL, 0, 29, 0, 53, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B15D9, FLAG_ITEM_ROUTE119_3, 0, 0
	object_event 20, MAP_OBJ_GFX_ITEM_BALL, 0, 25, 0, 76, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B15E6, FLAG_ITEM_ROUTE119_4, 0, 0
	object_event 21, MAP_OBJ_GFX_ITEM_BALL, 0, 8, 0, 18, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B15F3, FLAG_ITEM_ROUTE119_5, 0, 0
	object_event 22, MAP_OBJ_GFX_ITEM_BALL, 0, 33, 0, 117, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route119_EventScript_1B1600, FLAG_ITEM_ROUTE119_6, 0, 0
	object_event 23, MAP_OBJ_GFX_VAR_1, 0, 13, 0, 33, 0, 4, 10, 0, 0, 0, 0, 0, 0, Route119_EventScript_1515C5, FLAG_HIDE_EVIL_TEAM_WEATHER_INSTITUTE, 0, 0
	object_event 24, MAP_OBJ_GFX_VAR_1, 0, 13, 0, 34, 0, 4, 10, 0, 0, 0, 0, 0, 0, Route119_EventScript_1515DC, FLAG_HIDE_EVIL_TEAM_WEATHER_INSTITUTE, 0, 0
	object_event 25, MAP_OBJ_GFX_VAR_3, 0, 17, 0, 33, 0, 4, 7, 0, 0, 0, 0, 0, 0, 0x0, FLAG_HIDE_RIVAL_ROUTE119_ON_BIKE, 0, 0
	object_event 26, MAP_OBJ_GFX_BOY_3, 0, 31, 0, 109, 0, 3, 8, 17, 0, 0, 0, 0, 0, Route119_EventScript_1515F3, 0, 0, 0
	object_event 27, MAP_OBJ_GFX_BERRY_TREE, 0, 8, 0, 23, 0, 3, 12, 0, 0, 0, 0, 83, 0, S_BerryTree, 0, 0, 0
	object_event 28, MAP_OBJ_GFX_BERRY_TREE, 0, 9, 0, 23, 0, 3, 12, 0, 0, 0, 0, 84, 0, S_BerryTree, 0, 0, 0
	object_event 29, MAP_OBJ_GFX_BERRY_TREE, 0, 29, 0, 90, 0, 3, 12, 0, 0, 0, 0, 85, 0, S_BerryTree, 0, 0, 0
	object_event 30, MAP_OBJ_GFX_BERRY_TREE, 0, 30, 0, 90, 0, 3, 12, 0, 0, 0, 0, 86, 0, S_BerryTree, 0, 0, 0
	object_event 31, MAP_OBJ_GFX_CYCLING_TRIATHLETE_M, 0, 19, 0, 133, 0, 3, 5, 18, 0, 0, 0, 0, 0, Route119_EventScript_15141A, 0, 0, 0
	object_event 32, MAP_OBJ_GFX_ITEM_BALL, 0, 3, 0, 56, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route119_EventScript_1B160D, FLAG_ITEM_ROUTE119_7, 0, 0
	object_event 33, MAP_OBJ_GFX_BOY_2, 0, 35, 0, 93, 0, 4, 2, 17, 0, 0, 0, 0, 0, Route119_EventScript_1515FC, 0, 0, 0
	object_event 34, MAP_OBJ_GFX_LITTLE_BOY_1, 0, 29, 0, 6, 0, 3, 57, 17, 0, 1, 0, 3, 0, Route119_EventScript_151597, 0, 0, 0
	object_event 35, MAP_OBJ_GFX_KECLEON_1, 0, 31, 0, 6, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route119_EventScript_1A057A, FLAG_HIDE_KECLEON_ROUTE119_1, 0, 0
	object_event 36, MAP_OBJ_GFX_KECLEON_1, 0, 20, 0, 13, 0, 4, 76, 17, 0, 0, 0, 0, 0, Route119_EventScript_1A0587, FLAG_HIDE_KECLEON_ROUTE119_2, 0, 0
	object_event 37, MAP_OBJ_GFX_FISHERMAN, 0, 13, 0, 104, 0, 3, 10, 17, 0, 1, 0, 0, 0, Route119_EventScript_1515AE, 0, 0, 0

Route119_MapWarps:: @ 8383C8C
	warp_def 6, 32, 0, 0, MAP_ROUTE119_WEATHER_INSTITUTE_1F
	warp_def 33, 109, 0, 0, MAP_ROUTE119_HOUSE

Route119_MapCoordEvents:: @ 8383C9C
	coord_event 25, 31, 0, 0, VAR_ROUTE119_STATE, 0, 0, Route119_EventScript_1511C5
	coord_event 26, 31, 0, 0, VAR_ROUTE119_STATE, 0, 0, Route119_EventScript_1511D0
	coord_weather_event 28, 13, 0, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 29, 13, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 30, 13, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 31, 13, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 32, 13, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 33, 13, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 15, 133, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 16, 132, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 17, 131, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 18, 130, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 19, 131, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 20, 132, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 21, 133, 3, COORD_EVENT_WEATHER_ROUTE119_CYCLE
	coord_weather_event 36, 6, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 36, 7, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 35, 8, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 35, 9, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 34, 10, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 16, 137, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 17, 137, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 18, 137, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 19, 137, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 20, 137, 3, COORD_EVENT_WEATHER_SUNNY

Route119_MapBGEvents:: @ 8383E2C
	bg_event 9, 33, 0, 0, 0, Route119_EventScript_15142C
	bg_event 27, 19, 0, 0, 0, Route119_EventScript_151423
	bg_secret_base_event 5, 2, 0, SECRET_BASE_SHRUB1(1)
	bg_secret_base_event 4, 89, 0, SECRET_BASE_SHRUB1(2)
	bg_secret_base_event 5, 15, 0, SECRET_BASE_SHRUB2(1)
	bg_secret_base_event 7, 101, 3, SECRET_BASE_SHRUB2(2)
	bg_secret_base_event 34, 24, 3, SECRET_BASE_SHRUB3(1)
	bg_secret_base_event 31, 73, 3, SECRET_BASE_SHRUB4(1)
	bg_secret_base_event 16, 81, 0, SECRET_BASE_BLUE_CAVE3(3)
	bg_secret_base_event 16, 28, 0, SECRET_BASE_BLUE_CAVE4(3)
	bg_hidden_item_event 17, 82, 3, ITEM_CALCIUM, FLAG_HIDDEN_ITEM_5
	bg_hidden_item_event 38, 63, 3, ITEM_ULTRA_BALL, FLAG_HIDDEN_ITEM_6
	bg_secret_base_event 26, 81, 0, SECRET_BASE_RED_CAVE3(3)
	bg_secret_base_event 19, 76, 0, SECRET_BASE_TREE2(3)
	bg_secret_base_event 18, 76, 0, SECRET_BASE_TREE4(3)
	bg_secret_base_event 4, 15, 0, SECRET_BASE_SHRUB3(3)
	bg_secret_base_event 6, 2, 0, SECRET_BASE_SHRUB4(3)
	bg_hidden_item_event 26, 120, 3, ITEM_FULL_HEAL, FLAG_HIDDEN_ITEM_44
	bg_hidden_item_event 20, 29, 3, ITEM_MAX_ETHER, FLAG_HIDDEN_ITEM_57
	bg_event 28, 9, 0, 0, 0, Route119_EventScript_151605

Route119_MapEvents:: @ 8383F1C
	map_events Route119_MapObjects, Route119_MapWarps, Route119_MapCoordEvents, Route119_MapBGEvents
