Route123_MapObjects:: @ 83847F8
	object_event 1, MAP_OBJ_GFX_BERRY_TREE, 0, 11, 0, 3, 0, 3, 12, 0, 0, 0, 0, 58, 0, S_BerryTree, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_BERRY_TREE, 0, 12, 0, 3, 0, 3, 12, 0, 0, 0, 0, 59, 0, S_BerryTree, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_BERRY_TREE, 0, 14, 0, 3, 0, 3, 12, 0, 0, 0, 0, 60, 0, S_BerryTree, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_BERRY_TREE, 0, 15, 0, 3, 0, 3, 12, 0, 0, 0, 0, 61, 0, S_BerryTree, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_BERRY_TREE, 0, 81, 0, 1, 0, 3, 12, 0, 0, 0, 0, 62, 0, S_BerryTree, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_BERRY_TREE, 0, 82, 0, 1, 0, 3, 12, 0, 0, 0, 0, 63, 0, S_BerryTree, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_BERRY_TREE, 0, 83, 0, 1, 0, 3, 12, 0, 0, 0, 0, 64, 0, S_BerryTree, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_WOMAN_7, 0, 70, 0, 12, 0, 3, 24, 0, 0, 1, 0, 1, 0, Route123_EventScript_151CD1, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_MAN_4, 0, 58, 0, 7, 0, 3, 17, 0, 0, 1, 0, 2, 0, Route123_EventScript_151CE8, 0, 0, 0
	object_event 10, MAP_OBJ_GFX_BERRY_TREE, 0, 14, 0, 5, 0, 3, 12, 0, 0, 0, 0, 65, 0, S_BerryTree, 0, 0, 0
	object_event 11, MAP_OBJ_GFX_BERRY_TREE, 0, 15, 0, 5, 0, 3, 12, 0, 0, 0, 0, 72, 0, S_BerryTree, 0, 0, 0
	object_event 12, MAP_OBJ_GFX_BERRY_TREE, 0, 17, 0, 5, 0, 3, 12, 0, 0, 0, 0, 73, 0, S_BerryTree, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_BERRY_TREE, 0, 18, 0, 5, 0, 3, 12, 0, 0, 0, 0, 74, 0, S_BerryTree, 0, 0, 0
	object_event 14, MAP_OBJ_GFX_BERRY_TREE, 0, 17, 0, 3, 0, 3, 12, 0, 0, 0, 0, 79, 0, S_BerryTree, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_BERRY_TREE, 0, 18, 0, 3, 0, 3, 12, 0, 0, 0, 0, 14, 0, S_BerryTree, 0, 0, 0
	object_event 16, MAP_OBJ_GFX_BERRY_TREE, 0, 11, 0, 5, 0, 3, 12, 0, 0, 0, 0, 15, 0, S_BerryTree, 0, 0, 0
	object_event 17, MAP_OBJ_GFX_BERRY_TREE, 0, 12, 0, 5, 0, 3, 12, 0, 0, 0, 0, 30, 0, S_BerryTree, 0, 0, 0
	object_event 18, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 101, 0, 13, 0, 3, 1, 0, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_11, 0, 0
	object_event 19, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 129, 0, 14, 0, 3, 1, 0, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_12, 0, 0
	object_event 20, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 92, 0, 9, 0, 3, 1, 0, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_13, 0, 0
	object_event 21, MAP_OBJ_GFX_ITEM_BALL, 0, 31, 0, 8, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route123_EventScript_1B165B, FLAG_ITEM_ROUTE123_1, 0, 0
	object_event 22, MAP_OBJ_GFX_ITEM_BALL, 0, 139, 0, 18, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route123_EventScript_1B1668, FLAG_ITEM_ROUTE123_2, 0, 0
	object_event 23, MAP_OBJ_GFX_GIRL_3, 0, 108, 0, 13, 0, 3, 15, 0, 0, 0, 0, 0, 0, Route123_EventScript_151C5D, 0, 0, 0
	object_event 24, MAP_OBJ_GFX_BERRY_TREE, 0, 109, 0, 13, 0, 3, 12, 0, 0, 0, 0, 87, 0, S_BerryTree, 0, 0, 0
	object_event 25, MAP_OBJ_GFX_BERRY_TREE, 0, 110, 0, 13, 0, 3, 12, 0, 0, 0, 0, 88, 0, S_BerryTree, 0, 0, 0
	object_event 26, MAP_OBJ_GFX_BERRY_TREE, 0, 111, 0, 13, 0, 3, 12, 0, 0, 0, 0, 89, 0, S_BerryTree, 0, 0, 0
	object_event 27, MAP_OBJ_GFX_WOMAN_3, 0, 16, 0, 9, 0, 3, 23, 0, 0, 1, 0, 2, 0, Route123_EventScript_151CFF, 0, 0, 0
	object_event 28, MAP_OBJ_GFX_LITTLE_GIRL_1, 0, 38, 0, 13, 0, 3, 8, 0, 0, 1, 0, 0, 0, Route123_EventScript_151DAD, 0, 0, 0
	object_event 29, MAP_OBJ_GFX_LITTLE_GIRL_1, 0, 37, 0, 13, 0, 3, 8, 0, 0, 1, 0, 0, 0, Route123_EventScript_151D92, 0, 0, 0
	object_event 30, MAP_OBJ_GFX_PSYCHIC_M, 0, 138, 0, 12, 0, 3, 9, 0, 0, 1, 0, 6, 0, Route123_EventScript_151D16, 0, 0, 0
	object_event 31, MAP_OBJ_GFX_LASS, 0, 50, 0, 16, 0, 3, 8, 0, 0, 1, 0, 1, 0, Route123_EventScript_151D54, 0, 0, 0
	object_event 32, MAP_OBJ_GFX_HEX_MANIAC, 0, 87, 0, 14, 0, 3, 1, 0, 0, 1, 0, 3, 0, Route123_EventScript_151DC8, 0, 0, 0
	object_event 33, MAP_OBJ_GFX_ITEM_BALL, 0, 27, 0, 18, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route123_EventScript_1B1675, FLAG_ITEM_ROUTE123_3, 0, 0
	object_event 34, MAP_OBJ_GFX_ITEM_BALL, 0, 75, 0, 9, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route123_EventScript_1B1682, FLAG_ITEM_ROUTE123_4, 0, 0

Route123_MapWarps:: @ 8384B28
	warp_def 22, 6, 0, 0, MAP_ROUTE123_BERRY_MASTERS_HOUSE

Route123_MapCoordEvents:: @ 8384B30
	coord_weather_event 90, 16, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 92, 9, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 93, 12, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 92, 13, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 91, 14, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 19, 13, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 19, 12, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 34, 13, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 19, 14, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 19, 15, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 19, 16, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE
	coord_weather_event 108, 14, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 109, 15, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 110, 16, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 111, 17, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 112, 18, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 9, 12, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 9, 13, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 9, 14, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 9, 15, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 9, 16, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 94, 10, 3, COORD_EVENT_WEATHER_ROUTE123_CYCLE

Route123_MapBGEvents:: @ 8384C90
	bg_event 117, 10, 0, 0, 0, Route123_EventScript_151CBF
	bg_event 47, 3, 0, 8, 0, 82, 0, 0
	bg_event 49, 3, 0, 8, 0, 92, 0, 0
	bg_event 10, 12, 3, 0, 0, Route123_EventScript_151CB6
	bg_hidden_item_event 75, 1, 3, ITEM_SUPER_REPEL, FLAG_HIDDEN_ITEM_7
	bg_event 20, 7, 3, 0, 0, Route123_EventScript_151CC8
	bg_event 57, 5, 0, 8, 0, ITEM_SUPER_REPEL, 0, 0
	bg_hidden_item_event 12, 1, 3, ITEM_REVIVE, FLAG_HIDDEN_ITEM_29
	bg_hidden_item_event 91, 15, 3, ITEM_HYPER_POTION, FLAG_HIDDEN_ITEM_4A

Route123_MapEvents:: @ 8384CFC
	map_events Route123_MapObjects, Route123_MapWarps, Route123_MapCoordEvents, Route123_MapBGEvents
