Route130_EventObjects:: @ 838523C
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 7, 0, 26, 0, 1, 29, 99, 0, 1, 0, 3, 0, Route130_EventScript_152410, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 68, 0, 22, 0, 1, 13, 17, 0, 1, 0, 3, 0, Route130_EventScript_152427, 0, 0, 0
	object_event 3, EVENT_OBJ_GFX_BERRY_TREE, 0, 52, 0, 9, 0, 3, 12, 0, 0, 0, 0, 82, 0, S_BerryTree, FLAG_TEMP_11, 0, 0

Route130_MapEvents:: @ 8385284
	map_events Route130_EventObjects, 0x0, 0x0, 0x0
