Route130_EventObjects:: @ 838523C
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 7, 26, 1, 29, 99, 1, 3, Route130_EventScript_152410, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 68, 22, 1, 13, 17, 1, 3, Route130_EventScript_152427, 0
	object_event 3, EVENT_OBJ_GFX_BERRY_TREE, 0, 52, 9, 3, 12, 0, 0, 82, S_BerryTree, FLAG_TEMP_11

Route130_MapEvents:: @ 8385284
	map_events Route130_EventObjects, 0x0, 0x0, 0x0
