Route120_MapObjects:: @ 8383F30
	object_event 1, MAP_OBJ_GFX_BERRY_TREE, 0, 4, 0, 79, 0, 3, 12, 0, 0, 0, 0, 46, 0, S_BerryTree, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_BERRY_TREE, 0, 5, 0, 79, 0, 3, 12, 0, 0, 0, 0, 45, 0, S_BerryTree, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_BERRY_TREE, 0, 6, 0, 79, 0, 3, 12, 0, 0, 0, 0, 44, 0, S_BerryTree, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_BERRY_TREE, 0, 7, 0, 79, 0, 3, 12, 0, 0, 0, 0, 43, 0, S_BerryTree, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_BERRY_TREE, 0, 34, 0, 24, 0, 3, 12, 0, 0, 0, 0, 37, 0, S_BerryTree, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_BERRY_TREE, 0, 35, 0, 24, 0, 3, 12, 0, 0, 0, 0, 38, 0, S_BerryTree, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_BERRY_TREE, 0, 36, 0, 24, 0, 3, 12, 0, 0, 0, 0, 39, 0, S_BerryTree, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_BERRY_TREE, 0, 9, 0, 92, 0, 5, 12, 0, 0, 0, 0, 40, 0, S_BerryTree, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_BERRY_TREE, 0, 10, 0, 92, 0, 5, 12, 0, 0, 0, 0, 41, 0, S_BerryTree, 0, 0, 0
	object_event 10, MAP_OBJ_GFX_BERRY_TREE, 0, 11, 0, 92, 0, 5, 12, 0, 0, 0, 0, 42, 0, S_BerryTree, 0, 0, 0
	object_event 11, MAP_OBJ_GFX_MAN_6, 0, 5, 0, 22, 0, 3, 14, 0, 0, 1, 0, 3, 0, Route120_EventScript_1519B3, 0, 0, 0
	object_event 12, MAP_OBJ_GFX_MAN_6, 0, 32, 0, 14, 0, 3, 10, 0, 0, 1, 0, 3, 0, Route120_EventScript_1519CA, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_CAMPER, 0, 27, 0, 51, 0, 3, 9, 0, 0, 1, 0, 7, 0, Route120_EventScript_151A08, 0, 0, 0
	object_event 14, MAP_OBJ_GFX_PICNICKER, 0, 36, 0, 45, 0, 3, 9, 0, 0, 1, 0, 2, 0, Route120_EventScript_151A1F, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_MANIAC, 0, 19, 0, 80, 0, 5, 15, 0, 0, 1, 0, 3, 0, Route120_EventScript_151A36, 0, 0, 0
	object_event 16, MAP_OBJ_GFX_ITEM_BALL, 0, 20, 0, 55, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route120_EventScript_1B161A, FLAG_ITEM_ROUTE120_1, 0, 0
	object_event 17, MAP_OBJ_GFX_CAMERAMAN, 0, 37, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, Route120_EventScript_1AE4C2, FLAG_HIDE_GABBY_AND_TY_ROUTE120_1, 0, 0
	object_event 18, MAP_OBJ_GFX_REPORTER_F, 0, 36, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, Route120_EventScript_1AE4A2, FLAG_HIDE_GABBY_AND_TY_ROUTE120_1, 0, 0
	object_event 19, MAP_OBJ_GFX_REPORTER_F, 0, 36, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, Route120_EventScript_1AE562, FLAG_HIDE_GABBY_AND_TY_ROUTE120_2, 0, 0
	object_event 20, MAP_OBJ_GFX_CAMERAMAN, 0, 37, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, Route120_EventScript_1AE582, FLAG_HIDE_GABBY_AND_TY_ROUTE120_2, 0, 0
	object_event 21, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 35, 0, 32, 0, 3, 1, 0, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_11, 0, 0
	object_event 22, MAP_OBJ_GFX_ITEM_BALL, 0, 7, 0, 89, 0, 3, 1, 0, 0, 0, 0, 0, 0, Route120_EventScript_1B1627, FLAG_ITEM_ROUTE120_2, 0, 0
	object_event 23, MAP_OBJ_GFX_BEAUTY, 0, 14, 0, 92, 0, 5, 5, 1, 0, 0, 0, 0, 0, Route120_EventScript_151739, 0, 0, 0
	object_event 24, MAP_OBJ_GFX_WOMAN_7, 0, 28, 0, 35, 0, 3, 15, 0, 0, 1, 0, 4, 0, Route120_EventScript_151A74, 0, 0, 0
	object_event 25, MAP_OBJ_GFX_HIKER, 0, 9, 0, 60, 0, 3, 21, 0, 0, 1, 0, 4, 0, Route120_EventScript_151A8B, 0, 0, 0
	object_event 26, MAP_OBJ_GFX_WOMAN_7, 0, 16, 0, 6, 0, 3, 23, 0, 0, 1, 0, 4, 0, Route120_EventScript_151AA2, 0, 0, 0
	object_event 27, MAP_OBJ_GFX_WOMAN_7, 0, 18, 0, 34, 0, 3, 17, 0, 0, 1, 0, 3, 0, Route120_EventScript_151AB9, 0, 0, 0
	object_event 28, MAP_OBJ_GFX_ITEM_BALL, 0, 22, 0, 13, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route120_EventScript_1B1641, FLAG_ITEM_ROUTE120_4, 0, 0
	object_event 29, MAP_OBJ_GFX_ITEM_BALL, 0, 23, 0, 82, 0, 5, 1, 17, 0, 0, 0, 0, 0, Route120_EventScript_1B1634, FLAG_ITEM_ROUTE120_3, 0, 0
	object_event 30, MAP_OBJ_GFX_KECLEON_1, 0, 12, 0, 16, 0, 4, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_151998, FLAG_HIDE_KECLEON_ROUTE120_1, 0, 0
	object_event 31, MAP_OBJ_GFX_STEVEN, 0, 13, 0, 15, 0, 4, 8, 17, 0, 0, 0, 0, 0, Route120_EventScript_151853, FLAG_HIDE_STEVEN_ROUTE120, 0, 0
	object_event 32, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 20, 0, 1, 0, 3, 1, 17, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_14, 0, 0
	object_event 33, MAP_OBJ_GFX_CUTTABLE_TREE, 0, 15, 0, 1, 0, 3, 1, 17, 0, 0, 0, 0, 0, S_CuttableTree, FLAG_TEMP_12, 0, 0
	object_event 34, MAP_OBJ_GFX_LITTLE_BOY_1, 0, 10, 0, 72, 0, 3, 58, 17, 0, 1, 0, 3, 0, Route120_EventScript_151AD0, 0, 0, 0
	object_event 35, MAP_OBJ_GFX_LITTLE_BOY_1, 0, 19, 0, 28, 0, 3, 57, 17, 0, 1, 0, 3, 0, Route120_EventScript_151AE7, 0, 0, 0
	object_event 36, MAP_OBJ_GFX_KECLEON_2, 0, 12, 0, 16, 0, 3, 8, 17, 0, 0, 0, 0, 0, 0x0, FLAG_HIDE_KECLEON_ROUTE120_2, 0, 0
	object_event 37, MAP_OBJ_GFX_KECLEON_1, 0, 20, 0, 11, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_1A0539, FLAG_HIDE_KECLEON_ROUTE120_3, 0, 0
	object_event 38, MAP_OBJ_GFX_KECLEON_1, 0, 27, 0, 2, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_1A0546, FLAG_HIDE_KECLEON_ROUTE120_4, 0, 0
	object_event 39, MAP_OBJ_GFX_KECLEON_1, 0, 4, 0, 77, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_1A0553, FLAG_HIDE_KECLEON_ROUTE120_5, 0, 0
	object_event 40, MAP_OBJ_GFX_KECLEON_1, 0, 7, 0, 51, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_1A056D, FLAG_HIDE_KECLEON_ROUTE120_7, 0, 0
	object_event 41, MAP_OBJ_GFX_KECLEON_1, 0, 19, 0, 48, 0, 3, 76, 17, 0, 0, 0, 0, 0, Route120_EventScript_1A0560, FLAG_HIDE_KECLEON_ROUTE120_6, 0, 0

Route120_MapWarps:: @ 8384308
	warp_def 7, 55, 0, 0, MAP_ANCIENT_TOMB
	warp_def 19, 23, 1, 0, MAP_SCORCHED_SLAB

Route120_MapCoordEvents:: @ 8384318
	coord_weather_event 7, 15, 0, COORD_EVENT_WEATHER_RAIN_LIGHT
	coord_weather_event 7, 16, 0, COORD_EVENT_WEATHER_RAIN_LIGHT
	coord_weather_event 22, 61, 3, COORD_EVENT_WEATHER_RAIN_LIGHT
	coord_weather_event 12, 64, 3, COORD_EVENT_WEATHER_RAIN_LIGHT
	coord_weather_event 35, 63, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 36, 63, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 37, 63, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 38, 63, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 32, 88, 5, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 28, 15, 0, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 28, 16, 0, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 28, 17, 3, COORD_EVENT_WEATHER_SUNNY
	coord_weather_event 32, 89, 5, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 32, 90, 5, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 32, 91, 5, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 10, 75, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 11, 75, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 12, 75, 3, COORD_EVENT_WEATHER_CLOUDS
	coord_weather_event 13, 75, 3, COORD_EVENT_WEATHER_CLOUDS

Route120_MapBGEvents:: @ 8384448
	bg_event 27, 3, 3, 0, 0, Route120_EventScript_1519A1
	bg_event 38, 88, 3, 0, 0, Route120_EventScript_1519AA
	bg_event 28, 62, 0, 8, 0, 101, 0, 0
	bg_event 30, 62, 0, 8, 0, ITEM_HEART_SCALE, 0, 0
	bg_event 26, 10, 0, 8, 0, ITEM_LUCKY_PUNCH, 0, 0
	bg_event 29, 85, 5, 8, 0, 232, 0, 0
	bg_event 18, 12, 0, 8, 0, ITEM_SUN_STONE, 0, 0
	bg_event 38, 54, 0, 8, 0, ITEM_SOFT_SAND, 0, 0
	bg_event 31, 23, 0, 8, 0, ITEM_SPELL_TAG, 0, 0
	bg_event 9, 1, 3, 7, 0, ITEM_RARE_CANDY, 71, 0
	bg_event 31, 11, 3, 7, 0, ITEM_REVIVE, 84, 0
	bg_event 0, 86, 3, 7, 0, ITEM_RARE_CANDY, 69, 0
	bg_event 24, 42, 3, 7, 0, ITEM_ZINC, 70, 0
	bg_event 5, 76, 0, 8, 0, ITEM_HARD_STONE, 0, 0

Route120_MapEvents:: @ 83844F0
	map_events Route120_MapObjects, Route120_MapWarps, Route120_MapCoordEvents, Route120_MapBGEvents
