RustboroCity_House3_MapObjects:: @ 8388F40
	object_event 1, MAP_OBJ_GFX_OLD_MAN_2, 0, 4, 0, 5, 0, 3, 10, 0, 0, 0, 0, 0, 0, RustboroCity_House3_EventScript_157DED, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_OLD_WOMAN_2, 0, 7, 0, 5, 0, 3, 9, 0, 0, 0, 0, 0, 0, RustboroCity_House3_EventScript_157DF6, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_PIKACHU, 0, 4, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, RustboroCity_House3_EventScript_157DFF, 0, 0, 0

RustboroCity_House3_MapWarps:: @ 8388F88
	warp_def 5, 8, 0, 11, MAP_RUSTBORO_CITY
	warp_def 6, 8, 0, 11, MAP_RUSTBORO_CITY

RustboroCity_House3_MapEvents:: @ 8388F98
	map_events RustboroCity_House3_MapObjects, RustboroCity_House3_MapWarps, 0x0, 0x0
