RustboroCity_DevonCorp_2F_EventObjects:: @ 8388880
	object_event 1, EVENT_OBJ_GFX_SCIENTIST_1, 0, 6, 5, 3, 7, 0, 0, 0, RustboroCity_DevonCorp_2F_EventScript_1574E2, 0
	object_event 2, EVENT_OBJ_GFX_SCIENTIST_1, 0, 1, 5, 3, 10, 0, 0, 0, RustboroCity_DevonCorp_2F_EventScript_1574F9, 0
	object_event 3, EVENT_OBJ_GFX_SCIENTIST_1, 0, 2, 6, 3, 15, 0, 0, 0, RustboroCity_DevonCorp_2F_EventScript_157523, 0
	object_event 4, EVENT_OBJ_GFX_SCIENTIST_1, 0, 10, 5, 3, 7, 160, 0, 0, RustboroCity_DevonCorp_2F_EventScript_15754D, 0
	object_event 5, EVENT_OBJ_GFX_SCIENTIST_1, 0, 14, 8, 3, 7, 17, 0, 0, RustboroCity_DevonCorp_2F_EventScript_157564, 0

RustboroCity_DevonCorp_2F_MapWarps:: @ 83888F8
	warp_def 14, 1, 0, 2, MAP_RUSTBORO_CITY_DEVON_CORP_1F
	warp_def 2, 1, 0, 0, MAP_RUSTBORO_CITY_DEVON_CORP_3F

RustboroCity_DevonCorp_2F_MapEvents:: @ 8388908
	map_events RustboroCity_DevonCorp_2F_EventObjects, RustboroCity_DevonCorp_2F_MapWarps, 0x0, 0x0
