SafariZone_Northwest_EventObjects:: @ 83919E8
	object_event 1, EVENT_OBJ_GFX_MAN_1, 0, 8, 0, 8, 0, 5, 8, 0, 0, 0, 0, 0, 0, SafariZone_Northwest_EventScript_160007, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 33, 0, 7, 0, 3, 1, 17, 0, 0, 0, 0, 0, SafariZone_Northwest_EventScript_1B190C, FLAG_ITEM_SAFARI_ZONE_NORTHWEST_1, 0, 0

SafariZone_Northwest_MapEvents:: @ 8391A18
	map_events SafariZone_Northwest_EventObjects, 0x0, 0x0, 0x0
