SecretBase_BlueCave1_EventObjects:: @ 838F18C
	object_event 1, EVENT_OBJ_GFX_VAR_F, 0, 4, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, SecretBase_BlueCave1_EventScript_1A2FC0, FLAG_DECORATION_1, 0, 0
	object_event 2, EVENT_OBJ_GFX_VAR_0, 0, 0, 0, 0, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_2, 0, 0
	object_event 3, EVENT_OBJ_GFX_VAR_1, 0, 0, 0, 1, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_3, 0, 0
	object_event 4, EVENT_OBJ_GFX_VAR_2, 0, 0, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_4, 0, 0
	object_event 5, EVENT_OBJ_GFX_VAR_3, 0, 0, 0, 3, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_5, 0, 0
	object_event 6, EVENT_OBJ_GFX_VAR_4, 0, 0, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_6, 0, 0
	object_event 7, EVENT_OBJ_GFX_VAR_5, 0, 0, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_7, 0, 0
	object_event 8, EVENT_OBJ_GFX_VAR_6, 0, 0, 0, 6, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_8, 0, 0
	object_event 9, EVENT_OBJ_GFX_VAR_7, 0, 1, 0, 0, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_9, 0, 0
	object_event 10, EVENT_OBJ_GFX_VAR_8, 0, 1, 0, 1, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_10, 0, 0
	object_event 11, EVENT_OBJ_GFX_VAR_9, 0, 1, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_11, 0, 0
	object_event 12, EVENT_OBJ_GFX_VAR_A, 0, 1, 0, 3, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_12, 0, 0
	object_event 13, EVENT_OBJ_GFX_VAR_B, 0, 1, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_13, 0, 0
	object_event 14, EVENT_OBJ_GFX_VAR_C, 0, 1, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_14, 0, 0
	object_event 15, EVENT_OBJ_GFX_VAR_D, 0, 1, 0, 6, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_15, 0, 0

SecretBase_BlueCave1_MapWarps:: @ 838F2F4
	warp_def 5, 7, 0, 126, MAP_NONE

SecretBase_BlueCave1_MapEvents:: @ 838F2FC
	map_events SecretBase_BlueCave1_EventObjects, SecretBase_BlueCave1_MapWarps, 0x0, 0x0
