SecretBase_Tree3_MapObjects:: @ 83906C4
	object_event 1, 255, 0, 1, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, SecretBase_Tree3_EventScript_1A2FC0, FLAG_DECORATION_1, 0, 0
	object_event 2, 240, 0, 0, 0, 0, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_2, 0, 0
	object_event 3, 241, 0, 0, 0, 1, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_3, 0, 0
	object_event 4, 242, 0, 0, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_4, 0, 0
	object_event 5, 243, 0, 0, 0, 3, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_5, 0, 0
	object_event 6, 244, 0, 0, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_6, 0, 0
	object_event 7, 245, 0, 0, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_7, 0, 0
	object_event 8, 246, 0, 0, 0, 6, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_8, 0, 0
	object_event 9, 247, 0, 1, 0, 0, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_9, 0, 0
	object_event 10, 248, 0, 1, 0, 1, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_10, 0, 0
	object_event 11, 249, 0, 1, 0, 2, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_11, 0, 0
	object_event 12, 250, 0, 1, 0, 3, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_12, 0, 0
	object_event 13, 251, 0, 1, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_13, 0, 0
	object_event 14, 252, 0, 1, 0, 5, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_14, 0, 0
	object_event 15, 253, 0, 1, 0, 6, 0, 3, 8, 0, 0, 0, 0, 0, 0, 0x0, FLAG_DECORATION_15, 0, 0

SecretBase_Tree3_MapWarps:: @ 839082C
	warp_def 8, 6, 0, 126, MAP_NONE

SecretBase_Tree3_MapEvents:: @ 8390834
	map_events SecretBase_Tree3_MapObjects, SecretBase_Tree3_MapWarps, 0x0, 0x0
