ShoalCave_LowTideIceRoom_MapObjects:: @ 838EDE0
	object_event 1, MAP_OBJ_GFX_ITEM_BALL, 0, 12, 0, 8, 0, 3, 1, 17, 0, 0, 0, 0, 0, ShoalCave_LowTideIceRoom_EventScript_1B1A1D, 1112, 0, 0
	object_event 2, MAP_OBJ_GFX_ITEM_BALL, 0, 12, 0, 21, 0, 4, 1, 17, 0, 0, 0, 0, 0, ShoalCave_LowTideIceRoom_EventScript_1B1A2A, 1113, 0, 0

ShoalCave_LowTideIceRoom_MapWarps:: @ 838EE10
	warp_def 17, 10, 3, 3, MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM

ShoalCave_LowTideIceRoom_MapEvents:: @ 838EE18
	map_events ShoalCave_LowTideIceRoom_MapObjects, ShoalCave_LowTideIceRoom_MapWarps, 0x0, 0x0
