SlateportCity_MapObjects:: @ 837F7AC
	object_event 1, MAP_OBJ_GFX_FAT_MAN, 0, 21, 0, 11, 0, 3, 2, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BBD6, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_MAN_1, 0, 35, 0, 27, 0, 3, 5, 1, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BBF3, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_BOY_4, 0, 15, 0, 13, 0, 3, 2, 33, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BBB5, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_WOMAN_5, 0, 26, 0, 29, 0, 3, 1, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BC14, 0, 0, 0
	object_event 5, 240, 0, 31, 0, 27, 0, 3, 7, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD3A, 882, 0, 0
	object_event 6, MAP_OBJ_GFX_COOK, 0, 5, 0, 43, 0, 3, 8, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BB3F, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_OLD_WOMAN_2, 0, 20, 0, 37, 0, 3, 1, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BB60, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_GIRL_1, 0, 8, 0, 42, 0, 3, 2, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BB81, 0, 0, 0
	object_event 9, MAP_OBJ_GFX_CAMERAMAN, 0, 29, 0, 13, 0, 3, 9, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14C017, 835, 0, 0
	object_event 10, MAP_OBJ_GFX_REPORTER_F, 0, 28, 0, 14, 0, 3, 7, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14C020, 835, 0, 0
	object_event 11, MAP_OBJ_GFX_SCIENTIST_1, 0, 28, 0, 13, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BEBC, 840, 0, 0
	object_event 12, MAP_OBJ_GFX_SAILOR, 0, 35, 0, 36, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCE2, 0, 0, 0
	object_event 13, MAP_OBJ_GFX_SAILOR, 0, 28, 0, 46, 0, 3, 5, 1, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCEB, 0, 0, 0
	object_event 14, MAP_OBJ_GFX_WOMAN_2, 0, 9, 0, 50, 0, 3, 3, 16, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCF4, 0, 0, 0
	object_event 15, MAP_OBJ_GFX_MAN_4, 0, 16, 0, 46, 0, 3, 2, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCFD, 0, 0, 0
	object_event 16, MAP_OBJ_GFX_SCHOOL_KID_M, 0, 12, 0, 18, 0, 3, 2, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD06, 0, 0, 0
	object_event 17, MAP_OBJ_GFX_MANIAC, 0, 8, 0, 24, 0, 3, 3, 16, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCB8, 0, 0, 0
	object_event 18, MAP_OBJ_GFX_WOMAN_7, 0, 15, 0, 31, 0, 3, 1, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BCD9, 0, 0, 0
	object_event 19, 241, 0, 30, 0, 27, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD51, 882, 0, 0
	object_event 20, 241, 0, 29, 0, 27, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD68, 882, 0, 0
	object_event 21, MAP_OBJ_GFX_MART_EMPLOYEE, 0, 6, 0, 38, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BE20, 0, 0, 0
	object_event 22, MAP_OBJ_GFX_MART_EMPLOYEE, 0, 5, 0, 51, 0, 3, 8, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BDF2, 0, 0, 0
	object_event 23, MAP_OBJ_GFX_MAN_6, 0, 34, 0, 51, 0, 3, 8, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14C029, 0, 0, 0
	object_event 24, MAP_OBJ_GFX_WOMAN_7, 0, 4, 0, 47, 0, 3, 8, 0, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BAE0, 0, 0, 0
	object_event 25, MAP_OBJ_GFX_MART_EMPLOYEE, 0, 11, 0, 47, 0, 3, 8, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BE9A, 948, 0, 0
	object_event 26, MAP_OBJ_GFX_MAN_3, 0, 5, 0, 47, 0, 3, 8, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BAB6, 0, 0, 0
	object_event 27, 241, 0, 22, 0, 27, 0, 3, 10, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD7F, 882, 0, 0
	object_event 28, 241, 0, 23, 0, 27, 0, 3, 7, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BD96, 882, 0, 0
	object_event 29, 241, 0, 24, 0, 27, 0, 3, 10, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BDAD, 882, 0, 0
	object_event 30, 241, 0, 21, 0, 26, 0, 3, 10, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BDC4, 882, 0, 0
	object_event 31, 241, 0, 20, 0, 26, 0, 3, 10, 17, 0, 0, 0, 0, 0, SlateportCity_EventScript_14BDDB, 882, 0, 0

SlateportCity_MapWarps:: @ 837FA94
	warp_def 19, 19, 0, 0, MAP_SLATEPORT_CITY_POKEMON_CENTER_1F
	warp_def 13, 26, 0, 0, MAP_SLATEPORT_CITY_MART
	warp_def 26, 38, 0, 0, MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F
	warp_def 10, 12, 0, 0, MAP_SLATEPORT_CITY_CONTEST_LOBBY
	warp_def 4, 26, 0, 0, MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB
	warp_def 30, 26, 0, 0, MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F
	warp_def 5, 19, 0, 0, MAP_SLATEPORT_CITY_HOUSE1
	warp_def 31, 26, 0, 1, MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F
	warp_def 28, 12, 0, 0, MAP_SLATEPORT_CITY_HARBOR
	warp_def 40, 7, 0, 2, MAP_SLATEPORT_CITY_HARBOR
	warp_def 21, 44, 0, 0, MAP_SLATEPORT_CITY_HOUSE2

SlateportCity_MapBGEvents:: @ 837FAEC
	bg_event 8, 19, 0, 0, 0, SlateportCity_EventScript_14BCAF
	bg_event 20, 19, 0, 1, 0, SlateportCity_EventScript_1A00EA
	bg_event 21, 19, 0, 1, 0, SlateportCity_EventScript_1A00EA
	bg_event 14, 26, 0, 1, 0, SlateportCity_EventScript_1A00E1
	bg_event 24, 12, 0, 0, 0, SlateportCity_EventScript_14BC91
	bg_event 15, 26, 0, 1, 0, SlateportCity_EventScript_1A00E1
	bg_event 14, 51, 0, 0, 0, SlateportCity_EventScript_14BC88
	bg_event 26, 26, 0, 0, 0, SlateportCity_EventScript_14BC76
	bg_event 16, 22, 0, 0, 0, SlateportCity_EventScript_14BC7F
	bg_event 8, 26, 0, 0, 0, SlateportCity_EventScript_14BC6D
	bg_event 7, 13, 0, 0, 0, SlateportCity_EventScript_14BC33
	bg_event 23, 38, 0, 0, 0, SlateportCity_EventScript_14BC3C

SlateportCity_MapEvents:: @ 837FB7C
	map_events SlateportCity_MapObjects, SlateportCity_MapWarps, 0x0, SlateportCity_MapBGEvents
