SlateportCity_OceanicMuseum_1F_MapObjects:: @ 8387B38
	object_event 1, MAP_OBJ_GFX_BEAUTY, 0, 7, 0, 7, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155ADB, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_VAR_1, 0, 18, 0, 5, 0, 3, 7, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BA1, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 3, MAP_OBJ_GFX_VAR_1, 0, 12, 0, 2, 0, 3, 7, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BAA, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 4, MAP_OBJ_GFX_VAR_1, 0, 2, 0, 8, 0, 3, 7, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155B98, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 5, MAP_OBJ_GFX_VAR_0, 0, 3, 0, 4, 0, 3, 9, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155B8F, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 6, MAP_OBJ_GFX_VAR_1, 0, 14, 0, 4, 0, 3, 10, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BB3, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 7, MAP_OBJ_GFX_BEAUTY, 0, 12, 0, 7, 0, 3, 9, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155ADB, 0, 0, 0
	object_event 8, MAP_OBJ_GFX_VAR_1, 0, 8, 0, 3, 0, 3, 8, 0, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BBC, FLAG_HIDE_EVIL_TEAM_OCEANIC_MUSEUM, 0, 0
	object_event 9, MAP_OBJ_GFX_WOMAN_7, 0, 4, 0, 2, 0, 3, 1, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C16, FLAG_HIDE_OCEANIC_MUSEUM_VISITORS, 0, 0
	object_event 10, MAP_OBJ_GFX_MANIAC, 0, 10, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C1F, FLAG_HIDE_OCEANIC_MUSEUM_VISITORS, 0, 0
	object_event 11, MAP_OBJ_GFX_MAN_3, 0, 17, 0, 7, 0, 3, 10, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C28, FLAG_HIDE_OCEANIC_MUSEUM_VISITORS, 0, 0
	object_event 12, MAP_OBJ_GFX_LITTLE_GIRL_2, 0, 18, 0, 8, 0, 3, 7, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C31, FLAG_HIDE_OCEANIC_MUSEUM_VISITORS, 0, 0
	object_event 13, MAP_OBJ_GFX_VAR_1, 0, 9, 0, 4, 0, 3, 21, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C3A, FLAG_HIDE_SCARED_GRUNT_OCEANIC_MUSEUM, 0, 0
	object_event 14, MAP_OBJ_GFX_REPORTER_M, 0, 7, 0, 4, 0, 3, 1, 17, 0, 0, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_1ADEE0, FLAG_HIDE_OCEANIC_MUSEUM_VISITORS, 0, 0

SlateportCity_OceanicMuseum_1F_MapWarps:: @ 8387C88
	warp_def 9, 8, 0, 5, MAP_SLATEPORT_CITY
	warp_def 10, 8, 0, 7, MAP_SLATEPORT_CITY
	warp_def 6, 1, 0, 0, MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F

SlateportCity_OceanicMuseum_1F_MapCoordEvents:: @ 8387CA0
	coord_event 9, 7, 3, 0, VAR_SLATEPORT_MUSEUM_1F_STATE, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155AE4
	coord_event 10, 7, 3, 0, VAR_SLATEPORT_MUSEUM_1F_STATE, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155AF5

SlateportCity_OceanicMuseum_1F_MapBGEvents:: @ 8387CC0
	bg_event 2, 7, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BC5
	bg_event 2, 4, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BCE
	bg_event 9, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BD7
	bg_event 12, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BE0
	bg_event 10, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BD7
	bg_event 13, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BE0
	bg_event 15, 4, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BE9
	bg_event 18, 4, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BF2
	bg_event 18, 7, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155BFB
	bg_event 2, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C04
	bg_event 3, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C04
	bg_event 16, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C0D
	bg_event 17, 1, 0, 0, 0, SlateportCity_OceanicMuseum_1F_EventScript_155C0D

SlateportCity_OceanicMuseum_1F_MapEvents:: @ 8387D5C
	map_events SlateportCity_OceanicMuseum_1F_MapObjects, SlateportCity_OceanicMuseum_1F_MapWarps, SlateportCity_OceanicMuseum_1F_MapCoordEvents, SlateportCity_OceanicMuseum_1F_MapBGEvents
