SootopolisCity_House6_MapObjects:: @ 838B148
	object_event 1, MAP_OBJ_GFX_WOMAN_3, 0, 4, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, SootopolisCity_House6_EventScript_15B386, 0, 0, 0

SootopolisCity_House6_MapWarps:: @ 838B160
	warp_def 3, 6, 0, 9, MAP_SOOTOPOLIS_CITY
	warp_def 4, 6, 0, 9, MAP_SOOTOPOLIS_CITY

SootopolisCity_House6_MapEvents:: @ 838B170
	map_events SootopolisCity_House6_MapObjects, SootopolisCity_House6_MapWarps, 0x0, 0x0
