Underwater_SeafloorCavern_MapObjects:: @ 838D018
	object_event 1, MAP_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 5, 0, 4, 0, 3, 76, 17, 0, 0, 0, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, 980, 0, 0
	object_event 2, MAP_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 6, 0, 4, 0, 3, 76, 17, 0, 0, 0, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, 980, 0, 0
	object_event 3, MAP_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 7, 0, 4, 0, 3, 76, 17, 0, 0, 0, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, 980, 0, 0
	object_event 4, MAP_OBJ_GFX_RIVAL_BRENDAN_NORMAL, 0, 8, 0, 4, 0, 3, 76, 17, 0, 0, 0, 0, 0, Underwater_SeafloorCavern_EventScript_15DA3F, 980, 0, 0

Underwater_SeafloorCavern_MapWarps:: @ 838D078
	warp_def 6, 7, 0, 0, MAP_UNDERWATER4

Underwater_SeafloorCavern_MapEvents:: @ 838D080
	map_events Underwater_SeafloorCavern_MapObjects, Underwater_SeafloorCavern_MapWarps, 0x0, 0x0
