VerdanturfTown_House_EventObjects:: @ 8386DDC
	object_event 1, EVENT_OBJ_GFX_WOMAN_7, 0, 4, 0, 5, 0, 3, 7, 0, 0, 0, 0, 0, 0, VerdanturfTown_House_EventScript_1540ED, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_7, 0, 4, 0, 4, 0, 3, 8, 0, 0, 0, 0, 0, 0, VerdanturfTown_House_EventScript_1540F6, 0, 0, 0

VerdanturfTown_House_MapWarps:: @ 8386E0C
	warp_def 3, 8, 0, 6, MAP_VERDANTURF_TOWN
	warp_def 4, 8, 0, 6, MAP_VERDANTURF_TOWN

VerdanturfTown_House_MapEvents:: @ 8386E1C
	map_events VerdanturfTown_House_EventObjects, VerdanturfTown_House_MapWarps, 0x0, 0x0
