DexDescription_Dummy_1: @ 83A05F9
	.string "Dieses POKéMON wurde erst vor kurzem \n"
	.string "entdeckt und wird noch erforscht.$"

DexDescription_Dummy_2: @ 83A0642
	.string "Zur Zeit sind keine genauen\n"
	.string "Informationen über dieses\n"
	.string "POKéMON vorhanden.$"

DexDescription_Bulbasaur_1: @ 83A0675
	.string "BISASAM macht gern einmal ein\n"
	.string "Nickerchen im Sonnenschein.\n"
	.string "Auf seinem Rücken trägt es einen Samen.$"

DexDescription_Bulbasaur_2: @ 83A06C4
	.string "Indem es Sonnenstrahlen aufsaugt,\n"
	.string "wird der Samen zunehmend größer.$"

DexDescription_Ivysaur_1: @ 83A0707
	.string "BISAKNOSP hat eine Knospe auf seinem\n"
	.string "Rücken. Beine und Rumpf sind kräftig\n"
	.string "genug, um sein Gewicht zu tragen.$"

DexDescription_Ivysaur_2: @ 83A0775
	.string "Wenn es lange in der Sonne liegt, ist das\n"
	.string "ein Anzeichen dafür, dass die Knospe\n"
	.string "bald blüht.$"

DexDescription_Venusaur_1: @ 83A07EA
	.string "BISAFLOR hat eine Blume auf seinem\n"
	.string "Rücken. Wenn sie viel Nahrung und Sonne\n"
	.string "aufnimmt, verfärbt sie sich bunt.$"

DexDescription_Venusaur_2: @ 83A0860
	.string "Der Duft der Blume mildert die Emotionen\n"
	.string "der Menschen.$"

DexDescription_Charmander_1: @ 83A08A1
	.string "Die Flamme auf seiner Schweifspitze\n"
	.string "zeigt seine Gefühlslage an. Sie\n"
	.string "flackert, wenn GLUMANDA zufrieden ist.$"

DexDescription_Charmander_2: @ 83A0913
	.string "Wenn dieses POKéMON wütend wird, lodert\n"
	.string "die Flamme gewaltig.$"

DexDescription_Charmeleon_1: @ 83A095E
	.string "Gnadenlos besiegt GLUTEXO seine Geg-\n"
	.string "ner mit seinen scharfen Klauen. Wenn es \n"
	.string "auf starke Gegner trifft, wird es$"

DexDescription_Charmeleon_2: @ 83A09C6
	.string "wütend und die Flamme auf seiner\n"
	.string "Schweifspitze flackert in einem\n"
	.string "bläulichen Ton.$"

DexDescription_Charizard_1: @ 83A0A2C
	.string "GLURAK fliegt durch die Lüfte, um\n"
	.string "starke Gegner aufzuspüren. Sein heißer\n"
	.string "Feueratem bringt alles zum Schmelzen.$"

DexDescription_Charizard_2: @ 83A0A90
	.string "Aber es richtet seinen Feueratem nie\n"
	.string "auf schwächere Gegner.$"

DexDescription_Squirtle_1: @ 83A0AF5
	.string "SCHIGGYs Panzer dient nicht nur zum\n"
	.string "Schutz. Die runde Form und die Furchen\n"
	.string "auf der Oberfläche verringern den$"

DexDescription_Squirtle_2: @ 83A0B4B
	.string "Widerstand im Wasser, so dass dieses\n"
	.string "POKéMON sehr schnell schwimmen kann.$"

DexDescription_Wartortle_1: @ 83A0BB3
	.string "SCHILLOK hat einen langen, buschigen\n"
	.string "Schweif, dessen Farbe intensiver wird,\n"
	.string "wenn es altert.$"

DexDescription_Wartortle_2: @ 83A0C2A
	.string "Die Kratzer auf seinem Panzer zeugen\n"
	.string "von seiner Kampfkraft.$"

DexDescription_Blastoise_1: @ 83A0C7C
	.string "TURTOK besitzt Wasserdüsen, die aus\n"
	.string "seinem Panzer herausragen. Diese sind\n"
	.string "sehr präzise.$"

DexDescription_Blastoise_2: @ 83A0CD9
	.string "Es kann Wassergeschosse so genau\n"
	.string "verschießen, dass es damit aus fast\n"
	.string "50 Metern leere Dosen trifft.$"

DexDescription_Caterpie_1: @ 83A0D45
	.string "RAUPY ist sehr gefräßig, es kann\n"
	.string "Blätter verschlingen, die größer sind\n"
	.string "als es selbst.$"

DexDescription_Caterpie_2: @ 83A0DAA
	.string "Seine Antennen sondern einen\n"
	.string "übel riechenden Gestank ab.$"

DexDescription_Metapod_1: @ 83A0DEE
	.string "Der Panzer dieses POKéMON ist hart wie\n"
	.string "Stahl. SAFCON bewegt sich kaum,$"

DexDescription_Metapod_2: @ 83A0E52
	.string "da es das weiche Innere unter seiner\n"
	.string "harten Schale auf seine Entwicklung \n"
	.string "vorbereitet.$"

DexDescription_Butterfree_1: @ 83A0EAF
	.string "SMETTBOs größte Fähigkeit ist das Auf-\n"
	.string "spüren köstlichen Blütenhonigs.$"

DexDescription_Butterfree_2: @ 83A0EFD
	.string "Es findet sogar Honig in Blumen, die\n"
	.string "fast 10 km von seinem Nest entfernt\n"
	.string "blühen.$"

DexDescription_Weedle_1: @ 83A0F6B
	.string "HORNLIU verfügt über einen ausge-\n"
	.string "zeichneten Geruchssinn. So kann es\n"
	.string "seine Lieblingsblätter von denen$"

DexDescription_Weedle_2: @ 83A0FBD
	.string "unterscheiden, die es nicht mag, indem\n"
	.string "es mit seiner großen roten Nase daran\n"
	.string "schnuppert.$"

DexDescription_Kakuna_1: @ 83A1021
	.string "KOKUNA bewegt sich kaum, wenn es an\n"
	.string "einem Baum haftet. In seinem Inneren\n"
	.string "jedoch regt sich einiges, da es sich auf$"

DexDescription_Kakuna_2: @ 83A108E
	.string "seine bevorstehende Entwicklung vor-\n"
	.string "bereitet. Dabei wird seine Schale sehr\n"
	.string "heiß.$"

DexDescription_Beedrill_1: @ 83A10EE
	.string "BIBOR sind sehr wehrhaft. Es sollte sich\n"
	.string "besser niemand ihrem Nest nähern.$"

DexDescription_Beedrill_2: @ 83A1156
	.string "Wenn man sie ärgert, greifen sie in\n"
	.string "Schwärmen an.$"

DexDescription_Pidgey_1: @ 83A1187
	.string "TAUBSI verfügt über einen sehr ge-\n"
	.string "schulten Orientierungssinn. Es kehrt \n"
	.string "zielsicher zu seinem Nest zurück,$"

DexDescription_Pidgey_2: @ 83A11DF
	.string "egal, wie weit es sich von seiner\n"
	.string "gewohnten Umgebung entfernt hat.$"

DexDescription_Pidgeotto_1: @ 83A122F
	.string "TAUBOGA nennt ein großes Gebiet sein\n"
	.string "Eigen. Es fliegt umher und kontrolliert\n"
	.string "seinen Lebensraum.$"

DexDescription_Pidgeotto_2: @ 83A129B
	.string "Wenn jemand sein Gebiet betritt, zeigt\n"
	.string "es keine Gnade und greift seine Gegner\n"
	.string "mit seinen scharfen Krallen an.$"

DexDescription_Pidgeot_1: @ 83A1301
	.string "Dieses POKéMON hat ein wunderschönes, \n"
	.string "glänzendes Gefieder.\n"
	.string "Viele TRAINER sind von der auffälligen$"

DexDescription_Pidgeot_2: @ 83A1369
	.string "Schönheit seines Federkleids begeis-\n"
	.string "tert, so dass sie TAUBOSS als ihr\n"
	.string "POKéMON wählen.$"

DexDescription_Rattata_1: @ 83A13CA
	.string "RATTFRATZ ist extrem vorsichtig. Sogar\n"
	.string "im Schlaf nimmt es alles wahr, indem es\n"
	.string "seine Ohren bewegt.$"

DexDescription_Rattata_2: @ 83A1438
	.string "Es stellt keine großen Ansprüche an\n"
	.string "seinen Lebensraum und richtet sein\n"
	.string "Nest überall ein.$"

DexDescription_Raticate_1: @ 83A147F
	.string "RATTIKARLs kräftige Zähne wachsen\n"
	.string "ständig. Deshalb nagt es unablässig\n"
	.string "Steine und Baumstämme an,$"

DexDescription_Raticate_2: @ 83A14DC
	.string "um sie abzuwetzen. Manchmal knabbert\n"
	.string "es sogar Hauswände an.$"

DexDescription_Spearow_1: @ 83A1505
	.string "HABITAK kann einen sehr lauten Schrei\n"
	.string "ausstoßen, den man über die Entfernung\n"
	.string "von 1 km vernehmen kann.$"

DexDescription_Spearow_2: @ 83A156C
	.string "Durch das Echo seiner hohen, wehklagen-\n"
	.string "den Schreie warnt dieses POKéMON seine\n"
	.string "Artgenossen vor drohender Gefahr.$"

DexDescription_Fearow_1: @ 83A15B9
	.string "IBITAK erkennt man an seinem langen \n"
	.string "Hals und Schnabel. \n"
	.string "Er ist hervorragend dafür geeignet,$"

DexDescription_Fearow_2: @ 83A1614
	.string "im Erdreich oder im Wasser Beute zu\n"
	.string "jagen. Es setzt seinen langen, dünnen\n"
	.string "Schnabel dabei sehr geschickt ein.$"

DexDescription_Ekans_1: @ 83A166C
	.string "RETTAN rollt sich zu einer Spirale zu-\n"
	.string "sammen, wenn es sich ausruht.\n"
	.string "Aus dieser Haltung kann es blitzschnell$"

DexDescription_Ekans_2: @ 83A16C2
	.string "auf Bedrohungen aus allen Richtungen\n"
	.string "reagieren, indem es seinen Kopf hebt.$"

DexDescription_Arbok_1: @ 83A1716
	.string "Dieses POKéMON ist unheimlich stark. Es\n"
	.string "kann seine Beute mit seinem Körper um-\n"
	.string "wickeln und sogar Ölfässer zerdrücken.$"

DexDescription_Arbok_2: @ 83A178B
	.string "Wenn ARBOK einen Gegner umwickelt, ist\n"
	.string "es unmöglich, seinem Würgegriff zu ent-\n"
	.string "kommen.$"

DexDescription_Pikachu_1: @ 83A17E3
	.string "Immer wenn PIKACHU auf etwas Neues\n"
	.string "stößt, jagt es einen Elektroschock \n"
	.string "hindurch.$"

DexDescription_Pikachu_2: @ 83A1839
	.string "Wenn du eine verkohlte Beere findest,\n"
	.string "hat dieses POKéMON seine elektrische\n"
	.string "Ladung falsch eingeschätzt.$"

DexDescription_Raichu_1: @ 83A18A4
	.string "Wenn seine elektrische Ladung zu groß\n"
	.string "wird, entlädt RAICHU seine Energie ins\n"
	.string "Erdreich.$"

DexDescription_Raichu_2: @ 83A190D
	.string "Neben dem Nest dieses POKéMON findet\n"
	.string "man häufig versengtes Erdreich.$"

DexDescription_Sandshrew_1: @ 83A1950
	.string "SANDANs Körper kann sehr viel Wasser\n"
	.string "aufnehmen, so dass es auch in der\n"
	.string "Wüste überleben kann.$"

DexDescription_Sandshrew_2: @ 83A19B8
	.string "Dieses POKéMON rollt sich zusammen, um\n"
	.string "sich vor Feinden zu schützen.$"

DexDescription_Sandslash_1: @ 83A19F2
	.string "SANDAMERs Körper ist übersät\n"
	.string "mit spitzen Stacheln, die eigentlich\n"
	.string "Hauthärtungen darstellen.$"

DexDescription_Sandslash_2: @ 83A1A69
	.string "Einmal im Jahr fallen die alten Stacheln\n"
	.string "aus und werden durch neue ersetzt.$"

DexDescription_NidoranF_1: @ 83A1AB6
	.string "NIDORAN besitzt Widerhaken, die ein\n"
	.string "starkes Gift ausstoßen. Sie sind ver-\n"
	.string "mutlich zum Schutz dieses$"

DexDescription_NidoranF_2: @ 83A1B22
	.string "schmächtigen POKéMON entstanden.\n"
	.string "Wenn es wütend wird, stößt es ein\n"
	.string "gefährliches Gift aus seinem Horn aus.$"

DexDescription_Nidorina_1: @ 83A1B72
	.string "Wenn NIDORINA mit seinen Freunden oder\n"
	.string "seiner Familie zusammen ist, zieht\n"
	.string "es seine Widerhaken ein, damit es$"

DexDescription_Nidorina_2: @ 83A1BE3
	.string "niemanden verletzt. Dieses\n"
	.string "POKéMON wird nervös, wenn man es\n"
	.string "von seinen Artgenossen trennt.$"

DexDescription_Nidoqueen_1: @ 83A1C28
	.string "NIDOQUEENs Körper ist mit sehr harten\n"
	.string "Schuppen bedeckt. Es ist sehr ge-\n"
	.string "schickt darin, Gegner mit starken$"

DexDescription_Nidoqueen_2: @ 83A1C95
	.string "Attacken wegzuschleudern.\n"
	.string "Dieses POKéMON entwickelt am meisten\n"
	.string "Kraft, wenn es seine Jungen verteidigt.$"

DexDescription_NidoranM_1: @ 83A1CD6
	.string "Das männliche NIDORAN hat Muskeln ent-\n"
	.string "wickelt, um seine Ohren bewegen zu kön-\n"
	.string "nen. Dadurch kann es sie in jede beliebi-$"

DexDescription_NidoranM_2: @ 83A1D42
	.string "ge Richtung drehen. Diesem POKéMON \n"
	.string "entgeht nicht einmal das leiseste Ge-\n"
	.string "räusch.$"

DexDescription_Nidorino_1: @ 83A1D91
	.string "NIDORINO besitzt ein Horn, das sogar\n"
	.string "härter ist als ein Diamant. Wenn es\n"
	.string "einen Feind wahrnimmt, stellen sich$"

DexDescription_Nidorino_2: @ 83A1DFF
	.string "all die Widerhaken auf seinem Rücken\n"
	.string "auf und es schlägt den Gegner mit aller\n"
	.string "Kraft in die Flucht.$"

DexDescription_Nidoking_1: @ 83A1E41
	.string "NIDOKINGs Schweif ist enorm stark. Mit\n"
	.string "einer Bewegung kann es einen metalle-\n"
	.string "nen Sendemast zum Einsturz bringen.$"

DexDescription_Nidoking_2: @ 83A1EB5
	.string "Wenn es in Rage gerät, ist es nur schwer\n"
	.string "aufzuhalten.$"

DexDescription_Clefairy_1: @ 83A1EF3
	.string "In Vollmondnächten sammeln sich einige\n"
	.string "dieser POKéMON, um zu spielen. Wird es \n"
	.string "Tag, kehrt PIEPI zu seinem Zufluchts-$"

DexDescription_Clefairy_2: @ 83A1F61
	.string "ort in den Bergen zurück und\n"
	.string "schläft eingekuschelt neben\n"
	.string "seinen Artgenossen ein.$"

DexDescription_Clefable_1: @ 83A1FB8
	.string "PIXI bewegt sich fort, indem es leicht\n"
	.string "mit den Flügeln schlägt. Durch seinen\n"
	.string "federnden Gang kann es sogar über$"

DexDescription_Clefable_2: @ 83A202D
	.string "Wasser gehen. Bei Mondschein \n"
	.string "unternimmt es Spaziergänge auf Seen.$"

DexDescription_Vulpix_1: @ 83A206C
	.string "VULPIX kommt mit einem weißen Schweif\n"
	.string "zur Welt. Dieser teilt sich sechsfach, \n"
	.string "wenn das POKéMON von seinem TRAINER$"

DexDescription_Vulpix_2: @ 83A20E5
	.string "viel Zuneigung bekommt.\n"
	.string "Seine sechs Schweife kräuseln sich\n"
	.string "schließlich.$"

DexDescription_Ninetales_1: @ 83A2122
	.string "VULNONA sendet einen unheimlichen\n"
	.string "Lichtstrahl aus seinen hellroten Augen\n"
	.string "aus, um totale Kontrolle über die$"

DexDescription_Ninetales_2: @ 83A2187
	.string "Gedanken seines Gegners zu erlangen.\n"
	.string "Man sagt, dieses POKéMON könne 1000\n"
	.string "Jahre leben.$"

DexDescription_Jigglypuff_1: @ 83A21BA
	.string "PUMMELUFFs Stimmbänder können die\n"
	.string "Tonlage seiner Stimme beliebig vari-\n"
	.string "ieren. Dieses POKéMON benutzt diese$"

DexDescription_Jigglypuff_2: @ 83A222A
	.string "Fähigkeit, um seine Gegner mit monoto-\n"
	.string "nem Gesang in Tiefschlaf zu versetzen.$"

DexDescription_Wigglytuff_1: @ 83A226A
	.string "KNUDDELUFF hat handtellergroße Augen,\n"
	.string "die immer mit Tränenflüssigkeit bedeckt\n"
	.string "sind. Gerät Staub in die Augen dieses$"

DexDescription_Wigglytuff_2: @ 83A22D9
	.string "POKéMON, so wird dieser sofort ausge-\n"
	.string "spült.$"

DexDescription_Zubat_1: @ 83A231D
	.string "Tagsüber bleibt ZUBAT an einem dunklen\n"
	.string "Ort und bewegt sich kaum. Wenn es dem \n"
	.string "Sonnenlicht längere Zeit ausgesetzt$"

DexDescription_Zubat_2: @ 83A238A
	.string "wird, zieht es sich Verbrennungen an\n"
	.string "seinem Körper zu.$"

DexDescription_Golbat_1: @ 83A23C9
	.string "GOLBAT hat es auf das Blut von Lebe-\n"
	.string "wesen abgesehen. Im Schutze der Nacht\n"
	.string "wird es besonders aktiv.$"

DexDescription_Golbat_2: @ 83A2432
	.string "Dieses POKéMON fliegt durch die\n"
	.string "Nacht, um nach frischem Blut zu\n"
	.string "suchen.$"

DexDescription_Oddish_1: @ 83A2475
	.string "Am Tage vergräbt sich MYRAPLA im Boden,\n"
	.string "um mit seinem ganzen Körper Nahrung\n"
	.string "aufzunehmen.$"

DexDescription_Oddish_2: @ 83A24E2
	.string "Je fruchtbarer der Boden ist, desto\n"
	.string "glänzender werden seine Blätter.$"

DexDescription_Gloom_1: @ 83A251D
	.string "DUFLOR produziert einen Ekel\n"
	.string "erregenden Gestank aus dem Stempel\n"
	.string "seiner Blume. Wenn es in Gefahr gerät,$"

DexDescription_Gloom_2: @ 83A2588
	.string "wird der Gestank noch unerträglicher. \n"
	.string "Wenn sich dieses POKéMON in Sicherheit\n"
	.string "befindet, stößt es keinen Gestank aus.$"

DexDescription_Vileplume_1: @ 83A25E0
	.string "GIFLORs giftige Pollen rufen böse\n"
	.string "allergische Anfälle hervor. Deshalb ist\n"
	.string "es ratsam, sich keiner schönen Blume im$"

DexDescription_Vileplume_2: @ 83A264E
	.string "Dschungel zu nähern, so anziehend sie\n"
	.string "auch sein mag.$"

DexDescription_Paras_1: @ 83A268A
	.string "Auf PARAS’ Rücken wachsen parasitäre\n"
	.string "Pilze, die Tochukaso genannt werden.\n"
	.string "Sie wachsen, indem sie dem$"

DexDescription_Paras_2: @ 83A2700
	.string "KÄFER/PFLANZEN-PKMN Nährstoffe\n"
	.string "entziehen. Sie sind sehr wertvoll als\n"
	.string "lebensverlängernde Medizin.$"

DexDescription_Parasect_1: @ 83A2747
	.string "PARASEK sucht große Bäume heim und\n"
	.string "entzieht Nährstoffe aus Stamm und \n"
	.string "Wurzeln.$"

DexDescription_Parasect_2: @ 83A27AC
	.string "Wenn ein befallener Baum stirbt, sucht\n"
	.string "es sich zusammen mit seinen Artge-\n"
	.string "nossen einen neuen Wirt.$"

DexDescription_Venonat_1: @ 83A27F1
	.string "BLUZUK hat einen Pelz aus dünnen\n"
	.string "Borsten entwickelt, der dem Schutz\n"
	.string "seines Körpers dient.$"

DexDescription_Venonat_2: @ 83A285D
	.string "Es hat große Augen, denen auch winzig\n"
	.string "kleine Beute nicht entgeht.$"

DexDescription_Venomoth_1: @ 83A28A2
	.string "OMOT ist ein nachtaktives POKéMON.\n"
	.string "Kleine Insekten, die vom Licht in der\n"
	.string "Dunkelheit angezogen Straßenlaternen$"

DexDescription_Venomoth_2: @ 83A2911
	.string "umschwärmen, sind seine bevorzugte\n"
	.string "Beute.$"

DexDescription_Diglett_1: @ 83A295A
	.string "DIGDA wird zumeist auf Farmen\n"
	.string "gezüchtet. Denn wo auch immer dieses\n"
	.string "POKéMON zu graben beginnt, hinterlässt$"

DexDescription_Diglett_2: @ 83A29C3
	.string "es Erde, die für das Anpflanzen von\n"
	.string "Feldfrüchten perfekt geeignet und für\n"
	.string "den Anbau köstlichen Gemüses ideal ist.$"

DexDescription_Dugtrio_1: @ 83A2A22
	.string "DIGDRI sind Drillinge, die aus einem\n"
	.string "Körper entstanden sind. Daher denken\n"
	.string "alle Köpfe gleich.$"

DexDescription_Dugtrio_2: @ 83A2A8E
	.string "Sie arbeiten so gut zusammen, dass sie \n"
	.string "endlos graben können.$"

DexDescription_Meowth_1: @ 83A2ACF
	.string "MAUZI zieht seine scharfen Krallen ein,\n"
	.string "um umherschleichen zu können, ohne\n"
	.string "verräterische Spuren zu hinterlassen.$"

DexDescription_Meowth_2: @ 83A2B42
	.string "Dieses POKéMON hat eine Vorliebe für\n"
	.string "Münzen, die im Licht glitzern.$"

DexDescription_Persian_1: @ 83A2B8B
	.string "SNOBILIKAT hat sechs dicke Schnurr-\n"
	.string "haare, wodurch es Furcht einflößend\n"
	.string "wirkt. Durch diese nimmt es wahr, wenn$"

DexDescription_Persian_2: @ 83A2C00
	.string "sich etwas in seiner Nähe bewegt. Es\n"
	.string "wird sehr zutraulich, wenn man es an den\n"
	.string "Schnurrhaaren berührt.$"

DexDescription_Psyduck_1: @ 83A2C58
	.string "ENTON verwendet eine geheimnisvolle\n"
	.string "Kraft. Dabei erzeugt es Gehirnströme,\n"
	.string "die man sonst nur von Schlafenden$"

DexDescription_Psyduck_2: @ 83A2CB7
	.string "kennt. Diese Entdeckung führte zu \n"
	.string "einer umstrittenen Diskussion unter\n"
	.string "Wissenschaftlern.$"

DexDescription_Golduck_1: @ 83A2D0C
	.string "Die schwimmhäutigen Flossen an seinen\n"
	.string "Vorder- und Hinterbeinen und der \n"
	.string "stromlinienförmige Körper machen$"

DexDescription_Golduck_2: @ 83A2D7D
	.string "ENTORON unheimlich schnell. Dieses\n"
	.string "POKéMON ist auf jeden Fall schneller als\n"
	.string "die meisten Hochleistungsschwimmer.$"

DexDescription_Mankey_1: @ 83A2DC9
	.string "Wenn MENKI sich schüttelt und schwer\n"
	.string "durch die Nase atmet, dann ist es \n"
	.string "wütend. Da es blitzartig in Raserei$"

DexDescription_Mankey_2: @ 83A2E35
	.string "gerät, ist es unmöglich seinem Zorn\n"
	.string "zu entkommen.$"

DexDescription_Primeape_1: @ 83A2EA4
	.string "Wenn RASAFF wütend ist, wird seine Blut-\n"
	.string "zirkulation gesteigert und seine Mus-\n"
	.string "keln werden noch stärker.$"

DexDescription_Primeape_2: @ 83A2F12
	.string "Allerdings mindert das auch die \n"
	.string "Fähigkeit zum logischen Denken.$"

DexDescription_Growlithe_1: @ 83A2F53
	.string "FUKANO hat einen ausgezeichneten Ge-\n"
	.string "ruchssinn. Wenn dieses POKéMON ein-\n"
	.string "mal einen Geruch wahrgenommen hat,$"

DexDescription_Growlithe_2: @ 83A2FC8
	.string "vergisst es ihn nicht mehr. Es benutzt\n"
	.string "diese Fähigkeit dazu, die Gefühlslage\n"
	.string "von Lebewesen auszuloten.$"

DexDescription_Arcanine_1: @ 83A301F
	.string "ARKANI ist sehr schnell. Es kann an\n"
	.string "einem Tag fast 10.000 km zurücklegen.\n"
	.string "Das Feuer, das im Innern dieses POKéMON$"

DexDescription_Arcanine_2: @ 83A3095
	.string "lodert, dient ihm als Energiequelle.$"

DexDescription_Poliwag_1: @ 83A30E4
	.string "QUAPSEL hat eine sehr dünne Haut.\n"
	.string "Durch sie hindurch kann man sogar sein\n"
	.string "spiralförmiges Inneres sehen.$"

DexDescription_Poliwag_2: @ 83A314D
	.string "Obwohl seine Haut so dünn ist, ist sie\n"
	.string "sehr elastisch. Selbst scharfe Reiß-\n"
	.string "zähne können sie nicht durchdringen.$"

DexDescription_Poliwhirl_1: @ 83A31B2
	.string "QUAPUTZIs Körper ist immer feucht und\n"
	.string "glitschig. Dadurch kann es während\n"
	.string "eines Kampfes leicht der Umklammerung$"

DexDescription_Poliwhirl_2: @ 83A3226
	.string "eines Gegners entkommen.$"

DexDescription_Poliwrath_1: @ 83A3268
	.string "QUAPPO besitzt hochentwickelte, starke\n"
	.string "Muskeln, die niemals ermüden, egal, wie\n"
	.string "sehr es sie auch beansprucht.$"

DexDescription_Poliwrath_2: @ 83A32C5
	.string "Es ist so kräftig, dass es mühelos den\n"
	.string "Pazifik durchschwimmen kann.$"

DexDescription_Abra_1: @ 83A332F
	.string "ABRA schläft 18 Stunden am Tag.\n"
	.string "Es nimmt die Gegenwart von Feinden\n"
	.string "aber auch im Schlaf wahr.$"

DexDescription_Abra_2: @ 83A339B
	.string "In einer solchen Situation bringt es\n"
	.string "sich umgehend mit TELEPORT in\n"
	.string "Sicherheit.$"

DexDescription_Kadabra_1: @ 83A33DE
	.string "KADABRA sendet Alphawellen aus, wenn es\n"
	.string "Kopfschmerzen hat. Nur wer eine beson-\n"
	.string "ders starke Psyche hat, kann$"

DexDescription_Kadabra_2: @ 83A344A
	.string "dieses POKéMON unter seine Fittiche\n"
	.string "nehmen.$"

DexDescription_Alakazam_1: @ 83A347F
	.string "SIMSALAs Gehirn hört nicht auf zu\n"
	.string "wachsen, so dass sein Kopf zu schwer\n"
	.string "für seine Nackenmuskulatur wird.$"

DexDescription_Alakazam_2: @ 83A34DB
	.string "Dieses POKéMON hält seinen Kopf mit\n"
	.string "psychokinetischer Energie aufrecht.$"

DexDescription_Machop_1: @ 83A3521
	.string "MACHOLLOs Muskeln sind etwas Beson-\n"
	.string "deres. Sie schmerzen nie, egal, wie sehr\n"
	.string "sie beansprucht werden.$"

DexDescription_Machop_2: @ 83A3582
	.string "Dieses POKéMON hat genug Kraft, um 100\n"
	.string "Erwachsene umherzuwerfen.$"

DexDescription_Machoke_1: @ 83A35C4
	.string "MASCHOCKs starke Muskeln sind so hart\n"
	.string "wie Stahl. Dieses POKéMON hat so viel\n"
	.string "Kraft, dass es mit nur einem Finger$"

DexDescription_Machoke_2: @ 83A3629
	.string "einen Sumo-Ringer in der Luft halten\n"
	.string "kann.$"

DexDescription_Machamp_1: @ 83A3666
	.string "MACHOMEI hat genug Kraft, um alles \n"
	.string "Mögliche zu stemmen. Bei Tätigkeiten,\n"
	.string "die Geschick und Sorgfalt erfordern,$"

DexDescription_Machamp_2: @ 83A36D7
	.string "machen es ihm seine Arme jedoch nicht\n"
	.string "leicht. Dieses POKéMON neigt dazu,\n"
	.string "zuerst zu handeln und dann zu denken.$"

DexDescription_Bellsprout_1: @ 83A3729
	.string "KNOFENSAs schlanker und elastischer\n"
	.string "Körper ermöglicht es ihm, jedem\n"
	.string "Angriff auszuweichen, so heftig dieser$"

DexDescription_Bellsprout_2: @ 83A3792
	.string "auch sein mag. Dieses POKéMON spuckt\n"
	.string "eine ätzende Flüssigkeit aus, die sogar\n"
	.string "Eisen zersetzen kann.$"

DexDescription_Weepinbell_1: @ 83A37DD
	.string "ULTRIGARIA hat einen großen Haken\n"
	.string "an seinem Hinterteil. Nachts hängt\n"
	.string "sich dieses POKéMON zum Schlafen an$"

DexDescription_Weepinbell_2: @ 83A384D
	.string "einen Ast. Wenn es sich im Schlaf be-\n"
	.string "wegt, kann es passieren, dass es auf\n"
	.string "dem Boden wieder aufwacht.$"

DexDescription_Victreebel_1: @ 83A389B
	.string "Aus SARZENIAs Kopf ragt eine lange\n"
	.string "Ranke hervor. Diese schwingt hin und \n"
	.string "her, als ob sie etwas fangen$"

DexDescription_Victreebel_2: @ 83A3905
	.string "möchte. Wenn sich ahnungslose Beute \n"
	.string "nähert, wird sie von diesem POKéMON\n"
	.string "im Ganzen verschlungen.$"

DexDescription_Tentacool_1: @ 83A3966
	.string "TENTACHAs Körper setzt sich zum größ-\n"
	.string "ten Teil aus Wasser zusammen. Wenn es\n"
	.string "das Meer verlässt, vertrocknet es.$"

DexDescription_Tentacool_2: @ 83A39D0
	.string "Wenn dieses POKéMON auszutrocknen be-\n"
	.string "ginnt, sollte man es schnell wieder ins\n"
	.string "Wasser zurückbringen.$"

DexDescription_Tentacruel_1: @ 83A3A18
	.string "TENTOXA hat große, rote Kugeln auf \n"
	.string "seinem Kopf. Sie glühen auf, bevor sie \n"
	.string "seine Gegner mit Ultraschall$"

DexDescription_Tentacruel_2: @ 83A3A8C
	.string "erschüttern. Ein Ausbruch dieses \n"
	.string "POKéMON erzeugt starke Wellen \n"
	.string "in seiner Umgebung.$"

DexDescription_Geodude_1: @ 83A3AC3
	.string "Je länger ein KLEINSTEIN lebt, desto\n"
	.string "mehr wird seine raue Oberfläche ab-\n"
	.string "geschliffen, so dass es runder wird.$"

DexDescription_Geodude_2: @ 83A3B33
	.string "Das Herz dieses POKéMON bleibt aber\n"
	.string "für immer versteinert, hart und rau.$"

DexDescription_Graveler_1: @ 83A3B7D
	.string "GEOROK wächst, indem es sich von Stei-\n"
	.string "nen ernährt. Am liebsten mag es Steine,\n"
	.string "die mit Moos überzogen sind.$"

DexDescription_Graveler_2: @ 83A3BDF
	.string "Dieses POKéMON frisst sich täglich\n"
	.string "durch eine riesige Menge von Steinen.$"

DexDescription_Golem_1: @ 83A3C22
	.string "GEOWAZ lebt hoch in den Bergen. Gibt es \n"
	.string "ein starkes Erdbeben, rollt dieses\n"
	.string "POKéMON so lange den Berg hinunter,$"

DexDescription_Golem_2: @ 83A3C87
	.string "bis es schließlich unten angekommen ist.$"

DexDescription_Ponyta_1: @ 83A3CB6
	.string "Nach seiner Geburt ist PONITA so\n"
	.string "schwach, dass es kaum von alleine\n"
	.string "aufstehen kann. Dieses POKéMON wird$"

DexDescription_Ponyta_2: @ 83A3D0D
	.string "dadurch schnell stärker, dass es sich\n"
	.string "beim Versuch, mit seinen Eltern Schritt\n"
	.string "zu halten, immer wieder aufrappeln muss.$"

DexDescription_Rapidash_1: @ 83A3D3F
	.string "Man kann GALLOPA dabei beobachten, \n"
	.string "wie es lässig über Felder und Wiesen\n"
	.string "galoppiert. Wenn dieses POKéMON$"

DexDescription_Rapidash_2: @ 83A3DAA
	.string "jedoch Ernst macht, erreicht es bis zu\n"
	.string "240 km/h. Dann beginnt seine Mähne\n"
	.string "zu lodern.$"

DexDescription_Slowpoke_1: @ 83A3DF8
	.string "FLEGMON benutzt seinen Schweif, um \n"
	.string "Beute zu fangen, indem es ihn an einem \n"
	.string "Flussufer ins Wasser taucht.$"

DexDescription_Slowpoke_2: @ 83A3E4C
	.string "Dieses POKéMON vergisst häufig, was es\n"
	.string "gerade tun wollte, und verbringt ganze \n"
	.string "Tage damit, am Ufer herumzutrödeln.$"

DexDescription_Slowbro_1: @ 83A3EBB
	.string "An LAHMUS’ Rute hat sich ein MUSCHAS\n"
	.string "festgebissen. Daher kann es ihn nicht\n"
	.string "mehr zum Angeln benutzen$"

DexDescription_Slowbro_2: @ 83A3F2F
	.string "und es ist dazu gezwungen, umherzu-\n"
	.string "schwimmen und nach Beute Ausschau\n"
	.string "zu halten.$"

DexDescription_Magnemite_1: @ 83A3F6E
	.string "MAGNETILO ernährt sich von Elektri-\n"
	.string "zität aus Stromleitungen. Dieses\n"
	.string "POKéMON hängt sich gern an$"

DexDescription_Magnemite_2: @ 83A3FD1
	.string "Sicherungskästen. Wenn es in deinem\n"
	.string "Haus zu einem Stromausfall kommt,\n"
	.string "solltest du die Sicherungen überprüfen.$"

DexDescription_Magneton_1: @ 83A4037
	.string "MAGNETON erzeugt ein sehr starkes Mag-\n"
	.string "netfeld, das Maschinen zerstören kann.\n"
	.string "Deshalb hört man in großen Städten oft$"

DexDescription_Magneton_2: @ 83A40A5
	.string "Sirenen, die die Bürger vor Scharen\n"
	.string "dieses POKéMON warnen sollen.$"

DexDescription_Farfetchd_1: @ 83A40E7
	.string "PORENTA trifft man immer mit einer\n"
	.string "Lauchstange an. Es gibt gute und\n"
	.string "schlechte Stangen.$"

DexDescription_Farfetchd_2: @ 83A415B
	.string "Dieses POKéMON kämpft mit Hilfe seiner\n"
	.string "Stange gegen seine Gegner.$"

DexDescription_Doduo_1: @ 83A4199
	.string "DODU hat zwei Köpfe, die nie zur \n"
	.string "selben Zeit, sondern abwechselnd\n"
	.string "schlafen. Während ein Kopf schläft,$"

DexDescription_Doduo_2: @ 83A41EC
	.string "hält der andere Ausschau nach Feinden.$"

DexDescription_Dodrio_1: @ 83A4236
	.string "DODRIs drei Köpfe blicken in drei ver-\n"
	.string "schiedene Richtungen. Es ist immer auf\n"
	.string "der Hut.$"

DexDescription_Dodrio_2: @ 83A42AC
	.string "Du solltest dich diesem POKéMON nicht\n"
	.string "nähern, wenn es bereits misstrauisch \n"
	.string "ist. Es könnte nach dir hacken.$"

DexDescription_Seel_1: @ 83A42F7
	.string "JUROB jagt unter der eisigen Ober-\n"
	.string "fläche des Eismeeres nach Beute. Zum\n"
	.string "Luft holen schlägt es mit dem$"

DexDescription_Seel_2: @ 83A435C
	.string "vorstehenden Teil seines Kopfes ein \n"
	.string "Loch ins Eis.$"

DexDescription_Dewgong_1: @ 83A43A4
	.string "JUGONG liebt es, auf bitterkalten Eis-\n"
	.string "schollen ein Nickerchen zu machen.\n"
	.string "Ein Seemann, der einmal ein solches$"

DexDescription_Dewgong_2: @ 83A43F8
	.string "POKéMON schlafend auf einem\n"
	.string "Eisberg sah, hielt es irrtümlicherweise\n"
	.string "für eine Meerjungfrau.$"

DexDescription_Grimer_1: @ 83A4440
	.string "SLEIMAs glitschiger, gummiartiger\n"
	.string "Körper passt durch jede noch so kleine\n"
	.string "Öffnung. Dieses POKéMON steigt in die$"

DexDescription_Grimer_2: @ 83A449D
	.string "Kanalisation hinab, um fauliges\n"
	.string "Abwasser zu trinken.$"

DexDescription_Muk_1: @ 83A44D9
	.string "SLEIMOK scheidet eine widerlich\n"
	.string "stinkende Substanz aus. Ein einziger\n"
	.string "Tropfen seiner Körpersubstanz reicht$"

DexDescription_Muk_2: @ 83A452D
	.string "aus, um ein Gewässer zu verseuchen.$"

DexDescription_Shellder_1: @ 83A457D
	.string "Nachts benutzt dieses POKéMON seine\n"
	.string "breite Zunge, um ein Loch in den \n"
	.string "Meeresboden zu graben.$"

DexDescription_Shellder_2: @ 83A45E6
	.string "Darin schläft es. Dabei schließt es\n"
	.string "seine Schale, aber die Zunge hängt\n"
	.string "heraus.$"

DexDescription_Cloyster_1: @ 83A463A
	.string "AUSTOS kann im Meerwasser schwimmen,\n"
	.string "indem es Wasser schluckt und wieder\n"
	.string "herausspritzt.$"

DexDescription_Cloyster_2: @ 83A46AB
	.string "Dieses POKéMON kann sich auch ver- \n"
	.string "teidigen, indem es spitze Stacheln mit\n"
	.string "Hilfe des Wasserdrucks verschießt.$"

DexDescription_Gastly_1: @ 83A46EC
	.string "NEBULAK hat einen gasförmigen Körper.\n"
	.string "Wenn es starkem Wind ausgesetzt wird,\n"
	.string "kann es davongeweht werden.$"

DexDescription_Gastly_2: @ 83A4761
	.string "Scharen dieses POKéMON sammeln sich\n"
	.string "unter Dachrinnen, um sich vor dem\n"
	.string "gefährlichen Wind zu schützen.$"

DexDescription_Haunter_1: @ 83A47B9
	.string "ALPOLLO ist ein gefährliches POKéMON.\n"
	.string "Wenn es dich zu sich lockt, während es\n"
	.string "durch die Dunkelheit schwebt, darfst$"

DexDescription_Haunter_2: @ 83A4824
	.string "du ihm keinesfalls zu nahe kommen.\n"
	.string "Dieses POKéMON wird versuchen, an dir\n"
	.string "zu lecken und dein Leben zu stehlen.$"

DexDescription_Gengar_1: @ 83A4870
	.string "Nachts kann es passieren, dass dich\n"
	.string "dein Schatten im Licht einer\n"
	.string "Straßenlaterne plötzlich überholt.$"

DexDescription_Gengar_2: @ 83A48DC
	.string "Dann ist es ein GENGAR, das an dir\n"
	.string "vorbeiläuft und sich als dein Schatten\n"
	.string "ausgibt.$"

DexDescription_Onix_1: @ 83A4924
	.string "ONIX hat einen Magneten in seinem\n"
	.string "Gehirn. Er dient ihm als Kompass,\n"
	.string "so dass es beim Graben von Tunneln$"

DexDescription_Onix_2: @ 83A499D
	.string "nicht die Orientierung verliert. Wenn es\n"
	.string "älter wird, wird sein Körper immer\n"
	.string "runder und glatter.$"

DexDescription_Drowzee_1: @ 83A49E4
	.string "Wenn dir im Schlaf die Nase juckt, ist\n"
	.string "das ein sicheres Zeichen dafür, dass\n"
	.string "eines dieser POKéMON auf deinem$"

DexDescription_Drowzee_2: @ 83A4A54
	.string "Kissen sitzt, um deinen Traum durch\n"
	.string "deine Nasenlöcher hindurch zu\n"
	.string "verspeisen.$"

DexDescription_Hypno_1: @ 83A4A94
	.string "HYPNO hält ein Pendel in der Hand. Das\n"
	.string "Schwingen und Glitzern des Pendels \n"
	.string "versetzt seine Feinde in eine tiefe$"

DexDescription_Hypno_2: @ 83A4B07
	.string "Hypnose. Während dieses POKéMON auf \n"
	.string "der Suche nach Beute ist, poliert es \n"
	.string "sein Pendel.$"

DexDescription_Krabby_1: @ 83A4B54
	.string "KRABBY lebt an Stränden, in Löchern im \n"
	.string "Sand. An Sandstränden, an denen es\n"
	.string "wenig Nahrung findet, sieht man dieses$"

DexDescription_Krabby_2: @ 83A4BBD
	.string "POKéMON mit Artgenossen um sein\n"
	.string "Revier streiten.$"

DexDescription_Kingler_1: @ 83A4C0B
	.string "KINGLER hat eine riesige Schere. Es\n"
	.string "winkt damit, um mit anderen zu \n"
	.string "kommunizieren.$"

DexDescription_Kingler_2: @ 83A4C73
	.string "Da seine Schere aber so schwer ist, wird\n"
	.string "dieses POKéMON schnell müde.$"

DexDescription_Voltorb_1: @ 83A4CB5
	.string "VOLTOBAL wurde zuerst bei einer Firma\n"
	.string "beobachtet, die POKéBÄLLE herstellt.\n"
	.string "Der Zusammenhang zwischen dieser$"

DexDescription_Voltorb_2: @ 83A4D1D
	.string "Beobachtung und der Tatsache, dass\n"
	.string "dieses POKéMON wie ein POKéBALL\n"
	.string "aussieht, ist noch ungeklärt.$"

DexDescription_Electrode_1: @ 83A4D6D
	.string "LEKTROBAL ernährt sich von\n"
	.string "Elektrizität aus der Atmosphäre. An\n"
	.string "Tagen, an denen es blitzt, explodiert$"

DexDescription_Electrode_2: @ 83A4DD4
	.string "dieses POKéMON dauernd, da es zu viel\n"
	.string "Elektrizität zu sich nimmt.$"

DexDescription_Exeggcute_1: @ 83A4E13
	.string "Dieses POKéMON besteht aus sechs\n"
	.string "Eiern, die ein engmaschiges Netz\n"
	.string "bilden. Die sechs Eier ziehen sich$"

DexDescription_Exeggcute_2: @ 83A4E88
	.string "gegenseitig an und drehen sich. Wenn\n"
	.string "die Eier Risse bekommen, steht OWEI\n"
	.string "kurz vor seiner Entwicklung.$"

DexDescription_Exeggutor_1: @ 83A4ED6
	.string "KOKOWEI stammt ursprünglich aus den\n"
	.string "Tropen. Seine Köpfe wachsen stetig,\n"
	.string "wenn es starkem Sonnenlicht$"

DexDescription_Exeggutor_2: @ 83A4F43
	.string "ausgesetzt ist. Wenn seine Köpfe\n"
	.string "abfallen, bilden sie zusammen ein OWEI.$"

DexDescription_Cubone_1: @ 83A4F93
	.string "TRAGOSSO sehnt sich nach seiner\n"
	.string "Mutter, die nicht mehr da ist. Wenn es\n"
	.string "im Vollmond das Ebenbild seiner Mutter$"

DexDescription_Cubone_2: @ 83A5004
	.string "erblickt, muss es weinen. Die Flecken\n"
	.string "auf dem Totenkopf, den es trägt,\n"
	.string "stammen von vergossenen Tränen.$"

DexDescription_Marowak_1: @ 83A504E
	.string "KNOGGA ist eine entwickelte Form von\n"
	.string "TRAGOSSO, die den Verlust der Mutter\n"
	.string "überwunden hat und stärker geworden$"

DexDescription_Marowak_2: @ 83A50BF
	.string "ist. Die temperamentvolle und\n"
	.string "gestärkte Seele dieses POKéMON ist\n"
	.string "nur schwer zu brechen.$"

DexDescription_Hitmonlee_1: @ 83A5101
	.string "KICKLEE kann seine Beine ausfahren\n"
	.string "und einziehen. Es verblüfft seine\n"
	.string "Gegner mit brutalen Tritten.$"

DexDescription_Hitmonlee_2: @ 83A5177
	.string "Nach einem Kampf massiert es seine\n"
	.string "Beine und lockert die Muskeln, um der\n"
	.string "Erschöpfung vorzubeugen.$"

DexDescription_Hitmonchan_1: @ 83A51C8
	.string "NOCKCHAN besitzt das Herz eines\n"
	.string "Boxers, der sich auf eine\n"
	.string "Weltmeisterschaft vorbereitet.$"

DexDescription_Hitmonchan_2: @ 83A522F
	.string "Dieses POKéMON hat einen unbeugsamen\n"
	.string "Willen und gibt niemals auf.$"

DexDescription_Lickitung_1: @ 83A5287
	.string "Wenn SCHLURP etwas Neues entdeckt,\n"
	.string "leckt es daran. Es merkt sich \n"
	.string "Gegenstände anhand der Struktur und$"

DexDescription_Lickitung_2: @ 83A52FA
	.string "des Geschmacks.\n"
	.string "Saure Sachen schrecken es eher ab.$"

DexDescription_Koffing_1: @ 83A5341
	.string "Wenn SMOGON sich aufregt, lässt es\n"
	.string "das giftige Gas in seinem Inneren\n"
	.string "entweichen. Wenn es sich zu sehr$"

DexDescription_Koffing_2: @ 83A53B5
	.string "aufbläht, explodiert dieses POKéMON.$"

DexDescription_Weezing_1: @ 83A53F5
	.string "SMOGMOG liebt die Gase verrottender,\n"
	.string "fauler Küchenabfälle. Dieses POKéMON\n"
	.string "sucht sich ein vernachlässigtes,$"

DexDescription_Weezing_2: @ 83A5464
	.string "schmutziges Gebäude und richtet sich\n"
	.string "dort häuslich ein. Nachts, wenn die\n"
	.string "Menschen schlafen, wühlt es im Müll.$"

DexDescription_Rhyhorn_1: @ 83A54C7
	.string "RIHORN läuft immer geradeaus und\n"
	.string "zerstampft alles, was ihm in die Quere\n"
	.string "kommt. Es macht ihm auch nichts aus,$"

DexDescription_Rhyhorn_2: @ 83A552E
	.string "wenn es mit dem Kopf voran gegen einen\n"
	.string "Stahlklotz rennt. Am nächsten Tag\n"
	.string "allerdings könnte es Schmerzen haben.$"

DexDescription_Rhydon_1: @ 83A5598
	.string "Mit seinem Horn kann RIZEROS selbst\n"
	.string "Diamanten zerbrechen. Ein einziger\n"
	.string "Hieb mit seinem Schweif kann ein Haus$"

DexDescription_Rhydon_2: @ 83A55FA
	.string "zum Einsturz bringen. Die Haut dieses\n"
	.string "POKéMON ist so hart, dass nicht einmal\n"
	.string "Kanonenkugeln Kratzer hinterlassen.$"

DexDescription_Chansey_1: @ 83A5651
	.string "CHANEIRA legt täglich ausgesprochen\n"
	.string "nahrhafte Eier. Sie sind so köstlich,\n"
	.string "dass sie sogar von Menschen verspeist$"

DexDescription_Chansey_2: @ 83A56B5
	.string "werden, die gar keinen Appetit haben.$"

DexDescription_Tangela_1: @ 83A5704
	.string "Wenn man TANGELAs Ranken berührt, \n"
	.string "fallen diese sofort ab. Das tut ihm\n"
	.string "aber nicht weh und es kann$"

DexDescription_Tangela_2: @ 83A5779
	.string "sich schnell in Sicherheit bringen. \n"
	.string "Verliert es Ranken, werden diese am\n"
	.string "nächsten Tag durch neue ersetzt.$"

DexDescription_Kangaskhan_1: @ 83A57BD
	.string "Wenn du auf ein spielendes KANGAMA\n"
	.string "stößt, solltest du es nicht stören oder\n"
	.string "versuchen, es einzufangen.$"

DexDescription_Kangaskhan_2: @ 83A5828
	.string "Die Mutter dieses Baby-POKéMON ist\n"
	.string "bestimmt in Reichweite und könnte\n"
	.string "sehr wütend auf dich werden.$"

DexDescription_Horsea_1: @ 83A588A
	.string "SEEPER ernährt sich von kleinen\n"
	.string "Insekten und dem Moos auf Steinen.\n"
	.string "Bei unruhiger See verankert sich$"

DexDescription_Horsea_2: @ 83A58FB
	.string "dieses POKéMON mit seinem Schweif an\n"
	.string "Steinen oder Korallen, damit es nicht\n"
	.string "weggespült wird.$"

DexDescription_Seadra_1: @ 83A5941
	.string "Sobald sich SEEMON um eine Koralle\n"
	.string "gewickelt hat, schläft es. Von Zeit zu\n"
	.string "Zeit werden Menschen durch die$"

DexDescription_Seadra_2: @ 83A59A7
	.string "Widerhaken dieses POKéMON verletzt, \n"
	.string "wenn sie versuchen, Korallen zu ernten\n"
	.string "und es dabei nicht bemerken.$"

DexDescription_Goldeen_1: @ 83A59F4
	.string "GOLDINI ist ein wunderschönes POKéMON,\n"
	.string "dessen Flossen sich elegant im Wasser\n"
	.string "wiegen. Aber man muss auf dieses$"

DexDescription_Goldeen_2: @ 83A5A65
	.string "POKéMON Acht geben. Es könnte einen\n"
	.string "sonst heftig mit seinem Horn rammen.$"

DexDescription_Seaking_1: @ 83A5AA6
	.string "Im Herbst kann man männliche GOLKING\n"
	.string "dabei beobachten, wie sie Balztänze in \n"
	.string "Flussbetten aufführen, um die$"

DexDescription_Seaking_2: @ 83A5B08
	.string "weiblichen Exemplare zu beeindrucken.\n"
	.string "Während dieser Zeit ist die Farbe\n"
	.string "dieser POKéMON am schönsten.$"

DexDescription_Staryu_1: @ 83A5B55
	.string "In STERNDUs Körpermitte befindet sich\n"
	.string "ein hellrot leuchtendes Organ - \n"
	.string "sein Kern. Wenn du im Spätsommer$"

DexDescription_Staryu_2: @ 83A5BC2
	.string "an einen Strand gehst, sehen die\n"
	.string "leuchtenden Kerne dieser POKéMON aus\n"
	.string "wie Sterne.$"

DexDescription_Starmie_1: @ 83A5C14
	.string "STARMIEs Mittelteil, sein Kern, leuchtet\n"
	.string "in sieben Farben. Aufgrund dieser\n"
	.string "Eigenschaft wird es auch$"

DexDescription_Starmie_2: @ 83A5C7F
	.string "“Juwel des Meeres” genannt.$"

DexDescription_Mrmime_1: @ 83A5CB9
	.string "PANTIMOS ist ein Meister der Pantomime.\n"
	.string "Seine Gesten und Bewegungen machen\n"
	.string "den Zuschauer glauben, dass etwas$"

DexDescription_Mrmime_2: @ 83A5D20
	.string "Unsichtbares tatsächlich existiert.\n"
	.string "Wenn ein Objekt für real gehalten wird,\n"
	.string "beginnt es wirklich zu existieren.$"

DexDescription_Scyther_1: @ 83A5D70
	.string "SICHLOR ist unheimlich schnell. Dadurch\n"
	.string "werden die beiden Sensen an seinen\n"
	.string "Unterarmen noch effektiver.$"

DexDescription_Scyther_2: @ 83A5DDE
	.string "Dieses POKéMON kann mit seinen Sensen\n"
	.string "in Sekundenschnelle Baumstämme\n"
	.string "zerteilen.$"

DexDescription_Jynx_1: @ 83A5E3F
	.string "ROSSANA bewegt sich rhythmisch fort.\n"
	.string "Es wiegt und schwingt seine Hüften, als\n"
	.string "würde es tanzen. Seine Bewegungen$"

DexDescription_Jynx_2: @ 83A5EB4
	.string "wirken so anziehend auf Menschen, dass\n"
	.string "diese beginnen, mit den Hüften zu\n"
	.string "schwingen, ohne darüber nachzudenken.$"

DexDescription_Electabuzz_1: @ 83A5F1A
	.string "Bei Gewitter konkurrieren diese\n"
	.string "POKéMON darum, wie viele\n"
	.string "Spannungseinheiten sie erreichen,$"

DexDescription_Electabuzz_2: @ 83A5F85
	.string "wenn sie vom Blitz getroffen werden.\n"
	.string "Einige Ortschaften benutzen ELEKTEK\n"
	.string "an Stelle von Blitzableitern.$"

DexDescription_Magmar_1: @ 83A5FD8
	.string "Im Kampf stößt MAGMAR glühend heiße\n"
	.string "Flammen aus, um seinen Gegner\n"
	.string "einzuschüchtern.$"

DexDescription_Magmar_2: @ 83A603C
	.string "Diese Feuersalven erzeugen Hitzewellen,\n"
	.string "die das Gras und die Bäume der Umgebung\n"
	.string "in Brand setzen.$"

DexDescription_Pinsir_1: @ 83A609B
	.string "PINSIR ist erstaunlich stark. Es kann\n"
	.string "einen Feind, der doppelt so viel wiegt\n"
	.string "wie es selbst, mit seinen Hörnern$"

DexDescription_Pinsir_2: @ 83A6107
	.string "packen und hochheben. Bei niedrigen\n"
	.string "Temperaturen werden die Bewegungen\n"
	.string "dieses POKéMON schwerfällig.$"

DexDescription_Tauros_1: @ 83A613E
	.string "Dieses POKéMON ist nur zufrieden, wenn\n"
	.string "es kämpfen kann. Wenn TAUROS keinen\n"
	.string "Gegner findet, sucht es sich starke$"

DexDescription_Tauros_2: @ 83A61A7
	.string "Bäume und lässt sich an ihnen aus,\n"
	.string "um sich abzureagieren.$"

DexDescription_Magikarp_1: @ 83A61F1
	.string "KARPADOR ist ein armseliges POKéMON,\n"
	.string "das nur platschen kann. Sein\n"
	.string "merkwürdiges Verhalten hat so manchen$"

DexDescription_Magikarp_2: @ 83A624D
	.string "Wissenschaftler zum Forschen\n"
	.string "angeregt.$"

DexDescription_Gyarados_1: @ 83A628E
	.string "Wenn sich KARPADOR zu GARADOS\n"
	.string "entwickelt, durchlaufen seine\n"
	.string "Gehirnzellen eine strukturelle$"

DexDescription_Gyarados_2: @ 83A62FD
	.string "Veränderung, was wohl der Grund für die\n"
	.string "zügellose, gewalttätige Natur dieses\n"
	.string "POKéMON ist.$"

DexDescription_Lapras_1: @ 83A6342
	.string "Die Menschen sind dafür verantwortlich,\n"
	.string "dass LAPRAS fast ausgestorben wäre.\n"
	.string "Abends singt es traurige Klagelieder,$"

DexDescription_Lapras_2: @ 83A63B9
	.string "da nur noch wenige seiner Artgenossen\n"
	.string "übrig sind.$"

DexDescription_Ditto_1: @ 83A63EF
	.string "DITTO verändert seine Zellstruktur, um\n"
	.string "sich in eine andere Form zu verwandeln.\n"
	.string "Wenn es sich dabei jedoch auf sein$"

DexDescription_Ditto_2: @ 83A6463
	.string "Gedächtnis verlässt, unterlaufen \n"
	.string "diesem POKéMON schon mal Fehler.$"

DexDescription_Eevee_1: @ 83A64B7
	.string "EVOLIs genetisches Erbmaterial ist so\n"
	.string "instabil, dass die Umgebung plötzliche\n"
	.string "Mutationen auslösen kann.$"

DexDescription_Eevee_2: @ 83A651C
	.string "Die Wirkung verschiedener \n"
	.string "STEINE führt zur Entwicklung dieses \n"
	.string "POKéMON.$"

DexDescription_Vaporeon_1: @ 83A6559
	.string "AQUANA hat eine spontane Mutation\n"
	.string "durchgemacht und ihm sind Flossen und \n"
	.string "Kiemen gewachsen. Dadurch kann es$"

DexDescription_Vaporeon_2: @ 83A65BD
	.string "unter Wasser leben.\n"
	.string "Dieses POKéMON kann Wasser nach\n"
	.string "Belieben manipulieren.$"

DexDescription_Jolteon_1: @ 83A65F3
	.string "BLITZAs Zellen erzeugen schwache\n"
	.string "Elektrizität. Diese wird aber durch die\n"
	.string "statische Aufladung seines Fells$"

DexDescription_Jolteon_2: @ 83A6666
	.string "verstärkt, so dass es Blitzschläge\n"
	.string "erzeugen kann. Sein Fell besteht aus \n"
	.string "elektrisch geladenen Nadeln.$"

DexDescription_Flareon_1: @ 83A66CC
	.string "FLAMARAs flauschiges Fell dient einem\n"
	.string "besonderen Zweck. Es gibt Hitze an die\n"
	.string "Luft ab, damit sein Körper nicht$"

DexDescription_Flareon_2: @ 83A6738
	.string "zu heiß wird. Die Körpertemperatur \n"
	.string "dieses POKéMON kann bis auf 900 Grad\n"
	.string "ansteigen.$"

DexDescription_Porygon_1: @ 83A6793
	.string "PORYGON ist in der Lage, sich in Daten\n"
	.string "zurückzuverwandeln und in den\n"
	.string "Cyberspace zu gelangen.$"

DexDescription_Porygon_2: @ 83A67F1
	.string "Dieses POKéMON ist kopiergeschützt, so\n"
	.string "dass es durch Kopieren nicht\n"
	.string "vervielfältigt werden kann.$"

DexDescription_Omanyte_1: @ 83A6837
	.string "AMONITAS ist ein POKéMON, das seit\n"
	.string "langer Zeit ausgestorben war, aber\n"
	.string "von den Menschen aus Fossilien$"

DexDescription_Omanyte_2: @ 83A68A8
	.string "reproduziert wurde. Wenn es von einem\n"
	.string "Feind angegriffen wird, zieht es sich in\n"
	.string "sein hartes Gehäuse zurück.$"

DexDescription_Omastar_1: @ 83A68EC
	.string "AMOROSO benutzt seine Tentakel, um\n"
	.string "Beute einzufangen. Man nimmt an,\n"
	.string "dass es ausgestorben ist, weil seine$"

DexDescription_Omastar_2: @ 83A6963
	.string "Schale zu groß und zu schwer geworden\n"
	.string "war, so dass seine Bewegungen immer\n"
	.string "langsamer und schwerfälliger wurden.$"

DexDescription_Kabuto_1: @ 83A69A6
	.string "KABUTO ist ein POKéMON, das aus einem\n"
	.string "Fossil reproduziert wurde. Höchst\n"
	.string "selten wurden lebende Exemplare dieser$"

DexDescription_Kabuto_2: @ 83A6A15
	.string "Art entdeckt.\n"
	.string "Dieses POKéMON hat sich seit 300 Mio.\n"
	.string "Jahren überhaupt nicht verändert.$"

DexDescription_Kabutops_1: @ 83A6A65
	.string "In der Antike jagte KABUTOPS unter\n"
	.string "Wasser nach Beute. Es hat sich von\n"
	.string "einem Meeresbewohner zu einem Land-$"

DexDescription_Kabutops_2: @ 83A6AC9
	.string "bewohner entwickelt, was man an den\n"
	.string "Veränderungen seiner Kiemen und\n"
	.string "Beine sehen kann.$"

DexDescription_Aerodactyl_1: @ 83A6B36
	.string "AERODACTYL ist ein POKéMON aus dem\n"
	.string "Zeitalter der Dinosaurier. Es wurde aus\n"
	.string "genetischem Material reproduziert, das$"

DexDescription_Aerodactyl_2: @ 83A6BA8
	.string "aus Bernstein gewonnen wurde.\n"
	.string "Man geht davon aus, dass es in der\n"
	.string "Antike der König der Lüfte war.$"

DexDescription_Snorlax_1: @ 83A6BEC
	.string "Der typische Tagesablauf von RELAXO\n"
	.string "besteht lediglich aus Essen und\n"
	.string "Schlafen. Es ist so zutraulich, dass$"

DexDescription_Snorlax_2: @ 83A6C5C
	.string "Kinder seinen dicken Bauch als Platz\n"
	.string "zum Spielen nutzen.$"

DexDescription_Articuno_1: @ 83A6C99
	.string "ARKTOS ist ein sagenumwobenes\n"
	.string "Vogel-POKéMON, das Eis manipulieren\n"
	.string "kann. Das Schlagen seiner Flügel$"

DexDescription_Articuno_2: @ 83A6CFE
	.string "bringt die Luft zum Gefrieren. Es wird\n"
	.string "behauptet, dass es zu schneien\n"
	.string "beginnt, wenn dieses POKéMON fliegt.$"

DexDescription_Zapdos_1: @ 83A6D44
	.string "ZAPDOS ist ein legendäres\n"
	.string "Vogel-POKéMON, das die Fähigkeit\n"
	.string "besitzt, Elektrizität zu manipulieren.$"

DexDescription_Zapdos_2: @ 83A6DB7
	.string "Es lebt in Gewitterwolken.\n"
	.string "Dieses POKéMON nimmt Energie auf,\n"
	.string "wenn es vom Blitz getroffen wird.$"

DexDescription_Moltres_1: @ 83A6DF5
	.string "LAVADOS ist ein legendäres\n"
	.string "Vogel-POKéMON, das Feuer manipulieren\n"
	.string "kann. Wenn es verletzt wird, taucht es$"

DexDescription_Moltres_2: @ 83A6E69
	.string "seinen Körper in das Magma eines\n"
	.string "Vulkans, um sich zu verbrennen\n"
	.string "und selbst zu heilen.$"

DexDescription_Dratini_1: @ 83A6EB0
	.string "DRATINI häutet sich ständig und\n"
	.string "entledigt sich so seiner Haut, da die\n"
	.string "Lebensenergie in seinem Körper$"

DexDescription_Dratini_2: @ 83A6F0B
	.string "stetig und unkontrollierbar ansteigt.$"

DexDescription_Dragonair_1: @ 83A6F4B
	.string "DRAGONIR speichert eine enorme Menge\n"
	.string "an Energie in seinem Körper. Es kann die\n"
	.string "Witterung in seiner Umgebung ändern,$"

DexDescription_Dragonair_2: @ 83A6FB1
	.string "indem es Energie aus den Kristallen an\n"
	.string "seinem Nacken und an seinem Schweif\n"
	.string "entlädt.$"

DexDescription_Dragonite_1: @ 83A6FFF
	.string "DRAGORAN kann die Welt innerhalb\n"
	.string "von 16 Stunden umkreisen.\n"
	.string "Es ist ein gutherziges POKéMON, das$"

DexDescription_Dragonite_2: @ 83A7068
	.string "vermisste und sinkende Schiffe bei\n"
	.string "Unwetter sicher an Land zurückbringt.$"

DexDescription_Mewtwo_1: @ 83A70A4
	.string "MEWTU ist ein POKéMON, das durch\n"
	.string "Genmanipulation entstanden ist. Die\n"
	.string "Menschen haben es zwar mit ihrem$"

DexDescription_Mewtwo_2: @ 83A7106
	.string "wissenschaftlichen Sachverstand\n"
	.string "erzeugt, aber nicht mit einem\n"
	.string "mitfühlenden Herzen ausgestattet.$"

DexDescription_Mew_1: @ 83A716B
	.string "MEW soll die genetische\n"
	.string "Zusammensetzung aller POKéMON\n"
	.string "besitzen. Es kann sich unsichtbar$"

DexDescription_Mew_2: @ 83A71D3
	.string "machen, so dass es sich auch Menschen\n"
	.string "nähern kann, ohne bemerkt zu werden.$"

DexDescription_Chikorita_1: @ 83A7217
	.string "Im Kampf wedelt ENDIVIE mit seinem\n"
	.string "Blatt, um den Feind fern zu halten. Von\n"
	.string "dem Blatt geht auch ein süßlicher Duft$"

DexDescription_Chikorita_2: @ 83A7280
	.string "aus, der die kämpfenden POKéMON\n"
	.string "beruhigt und eine gemütliche,\n"
	.string "freundliche Atmosphäre schafft.$"

DexDescription_Bayleef_1: @ 83A72E3
	.string "LORBLATTs Nacken ist mit\n"
	.string "zusammengerollten Blättern behangen.\n"
	.string "In jedem Blatt befindet sich ein kleiner$"

DexDescription_Bayleef_2: @ 83A7346
	.string "Trieb eines Baumes.\n"
	.string "Der Duft dieses Triebes bringt\n"
	.string "Menschen auf Trab.$"

DexDescription_Meganium_1: @ 83A7376
	.string "Der Duft von MEGANIEs Blume besänftigt\n"
	.string "Gemüter. Im Kampf gibt dieses POKéMON\n"
	.string "mehr von seinem beruhigenden$"

DexDescription_Meganium_2: @ 83A73DC
	.string "Duftstoff ab, um den Kampfgeist des\n"
	.string "Gegners zu schwächen.$"

DexDescription_Cyndaquil_1: @ 83A7417
	.string "FEURIGEL lässt Flammen aus seinem\n"
	.string "Rücken lodern, wenn es sich schützen\n"
	.string "muss. Die Flammen sind sehr verzehrend,$"

DexDescription_Cyndaquil_2: @ 83A747E
	.string "wenn dieses POKéMON wütend ist. Ist es\n"
	.string "aber müde, flackern die Flammen nur\n"
	.string "unregelmäßig und schwach.$"

DexDescription_Quilava_1: @ 83A74DA
	.string "IGELAVAR hält seine Gegner mit Flammen\n"
	.string "und Böen heißer Luft auf Distanz.\n"
	.string "Dieses POKéMON nutzt seine$"

DexDescription_Quilava_2: @ 83A7537
	.string "außergewöhnliche Gewandtheit dazu,\n"
	.string "Angriffen auszuweichen und seinen\n"
	.string "Gegner gleichzeitig zu versengen.$"

DexDescription_Typhlosion_1: @ 83A75A2
	.string "TORNUPTO versteckt sich hinter einem\n"
	.string "flimmernden Hitzeschild, den es mit\n"
	.string "Hilfe seiner heißen Flammen erzeugt.$"

DexDescription_Typhlosion_2: @ 83A760B
	.string "Dieses POKéMON erzeugt Explosionen,\n"
	.string "die alles in Schutt und Asche\n"
	.string "legen.$"

DexDescription_Totodile_1: @ 83A765A
	.string "KARNIMANI ist zwar sehr klein, aber\n"
	.string "seine Kiefer sind sehr stark. Wenn\n"
	.string "die POKéMON denken, dass es nur$"

DexDescription_Totodile_2: @ 83A76C7
	.string "spielerisch an ihnen knabbert, sollten\n"
	.string "sie vorsichtig sein, denn sein Biss \n"
	.string "kann zu schweren Verletzungen führen.$"

DexDescription_Croconaw_1: @ 83A770D
	.string "Wenn TYRACROC einen Feind mit seinen\n"
	.string "Kiefern eingeklemmt hat, lässt es ihn\n"
	.string "nicht mehr los. Da seine Zahnspitzen$"

DexDescription_Croconaw_2: @ 83A777D
	.string "wie Angelhaken gebogen sind, kann man\n"
	.string "sie nicht mehr entfernen, wenn sie\n"
	.string "sich verfangen haben.$"

DexDescription_Feraligatr_1: @ 83A77DA
	.string "IMPERGATOR schüchtert seine Feinde\n"
	.string "dadurch ein, dass es sein riesiges Maul\n"
	.string "aufreißt. Im Kampf erschüttert es den$"

DexDescription_Feraligatr_2: @ 83A783D
	.string "Boden mit seinen kräftigen Hinterbei-\n"
	.string "nen, wenn es mit unglaublicher Geschwin-\n"
	.string "digkeit auf seinen Gegner losrennt.$"

DexDescription_Sentret_1: @ 83A7890
	.string "Wenn WIESOR schläft, hält immer jemand\n"
	.string "Wache. Beim ersten Anflug von Gefahr\n"
	.string "weckt die Wache die anderen auf.$"

DexDescription_Sentret_2: @ 83A7905
	.string "Wenn dieses POKéMON von seinen\n"
	.string "Artgenossen getrennt wird, kann es\n"
	.string "vor Angst nicht mehr schlafen.$"

DexDescription_Furret_1: @ 83A7963
	.string "WIESENIOR ist sehr schlank. Wenn es\n"
	.string "angegriffen wird, kann es sich durch\n"
	.string "enge Zwischenräume schlängeln und$"

DexDescription_Furret_2: @ 83A79CE
	.string "entkommen. Trotz seiner kurzen\n"
	.string "Gliedmaßen ist dieses POKéMON sehr\n"
	.string "wendig und flink.$"

DexDescription_Hoothoot_1: @ 83A7A12
	.string "HOOTHOOT besitzt ein inneres Organ, das\n"
	.string "die Erdumdrehung wahrnimmt. Dieses\n"
	.string "besondere Organ ermöglicht es diesem$"

DexDescription_Hoothoot_2: @ 83A7A85
	.string "POKéMON, jeden Tag zur selben Zeit zu\n"
	.string "schreien.$"

DexDescription_Noctowl_1: @ 83A7ABA
	.string "Dank seines hervorragenden\n"
	.string "Sehvermögens, mit dem es auch bei\n"
	.string "geringer Beleuchtung sehen kann, und$"

DexDescription_Noctowl_2: @ 83A7B26
	.string "dank seiner geschmeidigen Flügel,\n"
	.string "mit denen es geräuschlos fliegt,\n"
	.string "entgeht NOCTUH keine Beute.$"

DexDescription_Ledyba_1: @ 83A7B86
	.string "LEDYBA sondert eine duftende\n"
	.string "Flüssigkeit ab. Darüber kommuniziert\n"
	.string "es mit anderen. Dieses POKéMON$"

DexDescription_Ledyba_2: @ 83A7BFD
	.string "übermittelt seine Gefühle, indem es die\n"
	.string "Duftnote des Sekrets verändert.$"

DexDescription_Ledian_1: @ 83A7C48
	.string "In Ländern mit frischer Luft und\n"
	.string "Sternen am Himmel leben unzählig viele\n"
	.string "LEDIAN.$"

DexDescription_Ledian_2: @ 83A7CB7
	.string "Dafür gibt es einen guten Grund:\n"
	.string "Dieses POKéMON nutzt das Licht der\n"
	.string "Sterne als Energie.$"

DexDescription_Spinarak_1: @ 83A7D10
	.string "Das von WEBARAK gesponnene Netz ist\n"
	.string "sein zweites Nervensystem. Dieses\n"
	.string "POKéMON kann anhand der feinen$"

DexDescription_Spinarak_2: @ 83A7D77
	.string "Vibrationen der Netzfäden bestimmen,\n"
	.string "welche Art Beute sich darauf befindet.$"

DexDescription_Ariados_1: @ 83A7DE7
	.string "ARIADOS hat kleine hakenförmige Krallen\n"
	.string "an seinen Füßen. Damit kann es an\n"
	.string "Decken und Wänden entlang flitzen.$"

DexDescription_Ariados_2: @ 83A7E52
	.string "Dieses POKéMON erdrückt seine Gegner\n"
	.string "mit starkem, dünnem Seidenfaden.$"

DexDescription_Crobat_1: @ 83A7E95
	.string "Wenn IKSBAT fliegt, indem es nur ein \n"
	.string "Paar Flügel, entweder an seinen Vorder-\n"
	.string "oder Hinterbeinen bewegt, ist dies ein$"

DexDescription_Crobat_2: @ 83A7F07
	.string "Anzeichen dafür, dass dieses POKéMON \n"
	.string "bereits eine lange Strecke hinter sich\n"
	.string "hat. Dann wechselt es die Flügel häufig.$"

DexDescription_Chinchou_1: @ 83A7F5D
	.string "LAMPI gibt positive und negative\n"
	.string "elektrische Ladungen durch seine\n"
	.string "Antennen ab, um seine Beute zu lähmen.$"

DexDescription_Chinchou_2: @ 83A7FC8
	.string "Dieses POKéMON lässt seine Lichter\n"
	.string "aufflackern und tauscht Signale mit\n"
	.string "seinen Artgenossen aus.$"

DexDescription_Lanturn_1: @ 83A8012
	.string "LANTURN wird auch “Tiefseestern”\n"
	.string "genannt, da es leuchtende Antennen\n"
	.string "besitzt. Dieses POKéMON erzeugt Licht,$"

DexDescription_Lanturn_2: @ 83A8077
	.string "indem es in den Antennen eine chemische\n"
	.string "Reaktion zwischen Bakterien und seinen\n"
	.string "Körperflüssigkeiten erzeugt.$"

DexDescription_Pichu_1: @ 83A80CE
	.string "An Gewittertagen oder Tagen, an denen\n"
	.string "die Luft sehr trocken ist, kann sich\n"
	.string "PICHU leichter mit Elektrizität$"

DexDescription_Pichu_2: @ 83A8138
	.string "aufladen. Dann kann man das Knistern\n"
	.string "statischer Aufladung hören.$"

DexDescription_Cleffa_1: @ 83A8182
	.string "In Nächten mit vielen Sternschnuppen,\n"
	.string "kann man PII im Kreis tanzen sehen. Es\n"
	.string "tanzt die ganze Nacht hindurch und$"

DexDescription_Cleffa_2: @ 83A81F2
	.string "hört erst bei Sonnenaufgang auf, um\n"
	.string "seinen Durst mit Morgentau zu stillen.$"

DexDescription_Igglybuff_1: @ 83A8249
	.string "FLUFFELUFFs Stimmbänder sind noch\n"
	.string "nicht voll entwickelt. Wenn es zu viel\n"
	.string "singt, schmerzt ihm die Kehle.$"

DexDescription_Igglybuff_2: @ 83A82B8
	.string "Dieses POKéMON gurgelt mit Süßwasser\n"
	.string "aus einem sauberen Fluss.$"

DexDescription_Togepi_1: @ 83A82F2
	.string "TOGEPI nutzt die positiven Emotionen,\n"
	.string "wie Freude und Mitgefühl, von Menschen\n"
	.string "und POKéMON als Energie.$"

DexDescription_Togepi_2: @ 83A835C
	.string "Dieses POKéMON speichert Glücksgefühle\n"
	.string "in seiner Schale und teilt sie mit\n"
	.string "anderen.$"

DexDescription_Togetic_1: @ 83A83B9
	.string "TOGETIC ist ein POKéMON, das Glück\n"
	.string "bringt. Wenn es jemanden trifft, der\n"
	.string "reinen Herzens ist, zeigt es sich und$"

DexDescription_Togetic_2: @ 83A8428
	.string "teilt sein Glück mit dieser Person.$"

DexDescription_Natu_1: @ 83A8467
	.string "NATU kann nicht fliegen, da seine Flügel\n"
	.string "noch nicht ausgewachsen sind. Wenn du\n"
	.string "diesem POKéMON in die Augen schaust,$"

DexDescription_Natu_2: @ 83A84DC
	.string "starrt es dich konzentriert an. Wenn du\n"
	.string "dich aber bewegst, hüpft es weg, um sich\n"
	.string "in Sicherheit zu bringen.$"

DexDescription_Xatu_1: @ 83A852D
	.string "XATU bleibt den ganzen Tag an ein und\n"
	.string "demselben Ort wie angewurzelt stehen. \n"
	.string "Die Menschen glauben, dass es dies aus$"

DexDescription_Xatu_2: @ 83A859C
	.string "Angst vor den Dingen tut, die es für die\n"
	.string "Zukunft vorausgesehen hat.$"

DexDescription_Mareep_1: @ 83A85CF
	.string "VOLTILAMMs flauschiges, wollenes Fell\n"
	.string "erzeugt Reibung und statische\n"
	.string "Aufladung. Je höher die elektrische$"

DexDescription_Mareep_2: @ 83A863E
	.string "Ladung wird, desto heller leuchtet die\n"
	.string "Glühbirne an seinem Schweif.$"

DexDescription_Flaaffy_1: @ 83A867C
	.string "Die Qualität von WAATYs Wolle verändert\n"
	.string "sich, so dass es mit nur wenig Wolle eine\n"
	.string "große statische Aufladung erzeugen$"

DexDescription_Flaaffy_2: @ 83A86F4
	.string "kann. Die kahlen Stellen in seinem Fell\n"
	.string "sind gegen Elektrizität abgeschirmt.$"

DexDescription_Ampharos_1: @ 83A873B
	.string "AMPHAROS strahlt so viel Licht aus,\n"
	.string "dass es sogar aus dem Weltraum noch \n"
	.string "gesehen werden kann. In der Antike$"

DexDescription_Ampharos_2: @ 83A87AA
	.string "benutzten die Menschen das Licht\n"
	.string "dieses POKéMON dazu, Signale über\n"
	.string "weite Entfernungen auszutauschen.$"

DexDescription_Bellossom_1: @ 83A87EC
	.string "Wenn BLUBELLA starkem Sonnenlicht\n"
	.string "ausgesetzt ist, beginnen sich die Blät-\n"
	.string "ter an seinem Körper zu drehen.$"

DexDescription_Bellossom_2: @ 83A8851
	.string "Der Tanz dieses POKéMON ist in\n"
	.string "südlichen Ländern sehr bekannt.$"

DexDescription_Marill_1: @ 83A888B
	.string "MARILLs Schweif ist mit Öl gefüllt und\n"
	.string "dient ihm als eine Art Rettungsring.\n"
	.string "Wenn nur sein Schweif an der$"

DexDescription_Marill_2: @ 83A88FE
	.string "Wasseroberfläche zu sehen ist, taucht\n"
	.string "dieses POKéMON gerade, um sich von\n"
	.string "Wasserpflanzen zu ernähren.$"

DexDescription_Azumarill_1: @ 83A895E
	.string "AZUMARILLs lange Ohren dienen ihm\n"
	.string "als unentbehrliche Sensoren. Wenn es\n"
	.string "sein Gehör fokussiert, kann dieses$"

DexDescription_Azumarill_2: @ 83A89D0
	.string "POKéMON auch in reißenden Flüssen\n"
	.string "identifizieren, welche Art von Beute\n"
	.string "sich in seiner Nähe befindet.$"

DexDescription_Sudowoodo_1: @ 83A8A08
	.string "MOGELBAUM tarnt sich als Baum, um\n"
	.string "Angriffen von Feinden aus dem Weg\n"
	.string "zu gehen. Da seine Vorderbeine aber$"

DexDescription_Sudowoodo_2: @ 83A8A78
	.string "das ganze Jahr über grün bleiben, fällt\n"
	.string "seine Tarnung im Winter leicht auf.$"

DexDescription_Politoed_1: @ 83A8AD1
	.string "QUAXO hat gelocktes Haar, das ihm den\n"
	.string "Status eines Königs bescheinigt. Je\n"
	.string "länger und lockiger sein Haar ist, desto$"

DexDescription_Politoed_2: @ 83A8B45
	.string "mehr Respekt erntet dieses POKéMON\n"
	.string "von seinen Artgenossen.$"

DexDescription_Hoppip_1: @ 83A8B7F
	.string "HOPPSPROSS lässt sich vom Wind\n"
	.string "treiben. Wenn es bemerkt, dass ein\n"
	.string "Sturm aufkommt, verbindet es seine$"

DexDescription_Hoppip_2: @ 83A8BF0
	.string "Blätter mit anderen HOPPSPROSS,\n"
	.string "damit es nicht davongeweht wird.$"

DexDescription_Skiploom_1: @ 83A8C27
	.string "HUBELUPFs Blume beginnt zu blühen, wenn\n"
	.string "die Temperatur über 18 Grad steigt. Wie\n"
	.string "weit sich die Blüte öffnet, hängt von$"

DexDescription_Skiploom_2: @ 83A8C96
	.string "der Höhe der Temperatur ab. Daher wird\n"
	.string "dieses POKéMON manchmal als\n"
	.string "Thermometer eingesetzt.$"

DexDescription_Jumpluff_1: @ 83A8CE9
	.string "PAPUNGHA nutzt den Südwind, um das\n"
	.string "Meer zu überqueren und in ferne\n"
	.string "Länder zu fliegen. Dieses POKéMON$"

DexDescription_Jumpluff_2: @ 83A8D5A
	.string "sinkt zu Boden, wenn es während seines\n"
	.string "Fluges auf kalte Luftschichten stößt.$"

DexDescription_Aipom_1: @ 83A8D8C
	.string "An GRIFFELs Schweif befindet sich ein\n"
	.string "handähnliches Anhängsel, mit dem es\n"
	.string "geschickt zu Werke gehen kann.$"

DexDescription_Aipom_2: @ 83A8DD9
	.string "Da dieses POKéMON sehr häufig seinen\n"
	.string "Schweif einsetzt, wirken seine Hände\n"
	.string "eher plump.$"

DexDescription_Sunkern_1: @ 83A8E37
	.string "SONNKERN versucht, sich so wenig wie\n"
	.string "möglich zu bewegen, um alle\n"
	.string "gespeicherten Nährstoffe für seine$"

DexDescription_Sunkern_2: @ 83A8EA8
	.string "Entwicklung aufzusparen. Außer\n"
	.string "Morgentau nimmt es nichts weiter zu\n"
	.string "sich.$"

DexDescription_Sunflora_1: @ 83A8F0C
	.string "SONNFLORA verwandelt Solarenergie in\n"
	.string "Nährstoffe. Tagsüber, wenn es warm ist,\n"
	.string "ist es sehr aktiv.$"

DexDescription_Sunflora_2: @ 83A8F74
	.string "Wenn aber die Sonne untergegangen ist,\n"
	.string "hört es auf sich zu bewegen.$"

DexDescription_Yanma_1: @ 83A8FB0
	.string "YANMA hat einen Blickwinkel von 360\n"
	.string "Grad, ohne die Augen bewegen zu müssen.\n"
	.string "Es ist ein großartiger Flieger und geübt$"

DexDescription_Yanma_2: @ 83A901D
	.string "darin, plötzlich anzuhalten oder\n"
	.string "Wendemanöver vorzunehmen. So kann es\n"
	.string "sich blitzschnell auf Beute stürzen.$"

DexDescription_Wooper_1: @ 83A908F
	.string "FELINO lebt eigentlich im Wasser.\n"
	.string "Manchmal kommt es jedoch an Land, um \n"
	.string "nach Nahrung zu suchen.$"

DexDescription_Wooper_2: @ 83A90EE
	.string "An Land bedeckt es seinen Körper mit\n"
	.string "einem schleimigen Giftfilm.$"

DexDescription_Quagsire_1: @ 83A9123
	.string "MORLORD jagt seine Nahrung, indem es im\n"
	.string "Wasser sein Maul weit aufmacht und\n"
	.string "auf unvorsichtige Beute wartet.$"

DexDescription_Quagsire_2: @ 83A9193
	.string "Da sich dieses POKéMON nicht bewegt,\n"
	.string "wird es auch nicht besonders hungrig.$"

DexDescription_Espeon_1: @ 83A91D3
	.string "PSIANA ist jedem TRAINER treu, dem es\n"
	.string "zugetan ist. Dieses POKéMON hat die\n"
	.string "Fähigkeit der Prophezeiung entwickelt,$"

DexDescription_Espeon_2: @ 83A923E
	.string "um seine TRAINER vor Unheil zu\n"
	.string "bewahren.$"

DexDescription_Umbreon_1: @ 83A9278
	.string "NACHTARA hat sich dadurch entwickelt,\n"
	.string "dass es den Mondwellen ausgesetzt war.\n"
	.string "Es versteckt sich im Schutze der$"

DexDescription_Umbreon_2: @ 83A92DD
	.string "Dunkelheit und wartet darauf, dass sich\n"
	.string "ein Feind bewegt. Die Ringe an seinem\n"
	.string "Körper leuchten auf, wenn es angreift.$"

DexDescription_Murkrow_1: @ 83A932E
	.string "KRAMURX wurde als vermeintlicher\n"
	.string "Überbringer des Unheils verabscheut\n"
	.string "und gefürchtet. Dieses POKéMON hat$"

DexDescription_Murkrow_2: @ 83A9399
	.string "ein großes Interesse an allem, was\n"
	.string "funkelt und glitzert. Es stiehlt auch\n"
	.string "Ringe von Frauen.$"

DexDescription_Slowking_1: @ 83A93E9
	.string "LASCHOKING betreibt jeden Tag \n"
	.string "Forschung, um die Geheimnisse der Welt\n"
	.string "zu lüften. Dieses POKéMON vergisst aber$"

DexDescription_Slowking_2: @ 83A9442
	.string "alles, was es bereits herausgefunden\n"
	.string "hat, wenn das MUSCHAS auf seinem\n"
	.string "Kopf abfällt.$"

DexDescription_Misdreavus_1: @ 83A94AC
	.string "TRAUNFUGIL erschreckt Menschen mit\n"
	.string "einem markerschütternden Schrei.\n"
	.string "Dieses POKéMON verwendet seine roten$"

DexDescription_Misdreavus_2: @ 83A9513
	.string "Kraftfelder dazu, die Ängste seiner\n"
	.string "Feinde aufzunehmen und sie in\n"
	.string "Nahrung umzuwandeln.$"

DexDescription_Unown_1: @ 83A9555
	.string "ICOGNITO hat die Form antiker\n"
	.string "Schriftzeichen. Bis heute ist unklar,\n"
	.string "was zuerst da war: Die antiken$"

DexDescription_Unown_2: @ 83A95C6
	.string "Schriftzeichen oder die vielen unter-\n"
	.string "schiedlichen ICOGNITO. Trotz umfang-\n"
	.string "reicher Forschung bleiben Fragen offen.$"

DexDescription_Wobbuffet_1: @ 83A960F
	.string "Wenn zwei oder mehr WOINGENAU \n"
	.string "aufeinander treffen, versuchen sie,\n"
	.string "gegenseitig ihre Geduld zu übertreffen.$"

DexDescription_Wobbuffet_2: @ 83A9672
	.string "Sie möchten herausfinden, welches\n"
	.string "POKéMON es am längsten ohne Nahrung\n"
	.string "aushält. Darauf müssen Trainer achten.$"

DexDescription_Girafarig_1: @ 83A96E5
	.string "Der Kopf an GIRAFARIGs Hinterteil hat\n"
	.string "ein eigenes Gehirn. Er reagiert mit\n"
	.string "Angriffen auf Gerüche und Geräusche.$"

DexDescription_Girafarig_2: @ 83A9756
	.string "Wenn man sich diesem POKéMON von\n"
	.string "hinten nähert, könnte der hintere Kopf\n"
	.string "plötzlich vorschnellen und zubeißen.$"

DexDescription_Pineco_1: @ 83A97B2
	.string "TANNZA hängt an Ästen und wartet auf\n"
	.string "Beute. Wenn man dieses POKéMON bei\n"
	.string "einer Mahlzeit stört, indem man den$"

DexDescription_Pineco_2: @ 83A9820
	.string "Baum, auf dem es sich befindet,\n"
	.string "schüttelt, fällt es herunter und\n"
	.string "explodiert ohne Vorwarnung.$"

DexDescription_Forretress_1: @ 83A987E
	.string "FORSTELLKA versteckt sich in seiner\n"
	.string "stahlharten Schale. Die Schale öffnet\n"
	.string "sich, wenn es nach Beute schnappt.$"

DexDescription_Forretress_2: @ 83A98F1
	.string "Dies geht jedoch so schnell, dass man\n"
	.string "das Innere der Schale nicht zu Gesicht\n"
	.string "bekommt.$"

DexDescription_Dunsparce_1: @ 83A993D
	.string "DUMMISEL hat einen Bohrer als Schweif.\n"
	.string "Diesen benutzt es, um sich rückwärts in\n"
	.string "den Boden einzugraben.$"

DexDescription_Dunsparce_2: @ 83A9998
	.string "Dieses POKéMON baut seinen \n"
	.string "Nestkomplex tief unter der\n"
	.string "Erdoberfläche auf.$"

DexDescription_Gligar_1: @ 83A99E8
	.string "SKORGLA segelt lautlos durch die Lüfte.\n"
	.string "Es verankert sich mit Hilfe der Krallen\n"
	.string "an seinen Hinterbeinen und der riesigen$"

DexDescription_Gligar_2: @ 83A9A52
	.string "Scheren an seinen Vorderbeinen am\n"
	.string "Gesicht eines Feindes fest und\n"
	.string "vergiftet ihn mit seinem Giftstachel.$"

DexDescription_Steelix_1: @ 83A9AC8
	.string "STAHLOS lebt noch tiefer unter der Erde\n"
	.string "als ONIX. Dieses POKéMON gräbt immer\n"
	.string "in Richtung des Erdkerns.$"

DexDescription_Steelix_2: @ 83A9B31
	.string "Nachweislich hat dieses POKéMON\n"
	.string "bereits Tiefen von einem Kilometer\n"
	.string "erreicht.$"

DexDescription_Snubbull_1: @ 83A9B8E
	.string "Indem es seine Zähne fletscht und\n"
	.string "ein Furcht erregendes Gesicht macht,\n"
	.string "schlägt SNUBBULL kleinere POKéMON$"

DexDescription_Snubbull_2: @ 83A9BF4
	.string "in die Flucht. Es scheint darüber jedoch\n"
	.string "etwas traurig zu sein.$"

DexDescription_Granbull_1: @ 83A9C36
	.string "GRANBULL besitzt einen besonders\n"
	.string "ausgeprägten Unterkiefer. Wegen seiner\n"
	.string "schweren Zähne wackelt es mit dem Kopf.$"

DexDescription_Granbull_2: @ 83A9CA6
	.string "Es beißt nur zu, wenn es erschreckt\n"
	.string "wird.$"

DexDescription_Qwilfish_1: @ 83A9D02
	.string "BALDORFISH saugt Wasser ein, um sich\n"
	.string "aufzublasen. Dieses POKéMON nutzt den\n"
	.string "Druck des Wassers dazu, giftige$"

DexDescription_Qwilfish_2: @ 83A9D6F
	.string "Stacheln aus seinem Körper zu\n"
	.string "verschießen. Es betrachtet Schwimmen\n"
	.string "als eine echte Herausforderung.$"

DexDescription_Scizor_1: @ 83A9DC8
	.string "SCHEROX’ Körper ist hart wie Stahl.\n"
	.string "Gewöhnliche Angriffe jagen ihm keine\n"
	.string "Angst ein. Dieses POKéMON schlägt$"

DexDescription_Scizor_2: @ 83A9E2B
	.string "mit den Flügeln, um seine\n"
	.string "Körpertemperatur zu regulieren.$"

DexDescription_Shuckle_1: @ 83A9E6A
	.string "POTTROTT versteckt sich leise unter\n"
	.string "Steinen und verbirgt seinen Körper in\n"
	.string "seiner harten Schale, wenn es$"

DexDescription_Shuckle_2: @ 83A9ED2
	.string "gesammelte Beeren zu sich nimmt. Die\n"
	.string "Beeren vermischen sich mit seinen\n"
	.string "Körperflüssigkeiten zu einem Saft.$"

DexDescription_Heracross_1: @ 83A9F26
	.string "SKARABORN geht direkt auf seinen\n"
	.string "Gegner los, rutscht auf ihn zu, um ihn\n"
	.string "auszuhebeln und mit seinem mächtigen$"

DexDescription_Heracross_2: @ 83A9F97
	.string "Horn wegzuschleudern. Dieses POKéMON\n"
	.string "hat genug Kraft, um einen massigen\n"
	.string "Baum umzustoßen.$"

DexDescription_Sneasel_1: @ 83A9FF3
	.string "SNIEBEL klettert an Bäumen hoch, indem\n"
	.string "es seine hakenförmigen Krallen in die\n"
	.string "Rinde schlägt. Dieses POKéMON sucht$"

DexDescription_Sneasel_2: @ 83AA055
	.string "nach unbewachten Nestern und stiehlt\n"
	.string "die Eier, wenn die Eltern auf Nahrungs-\n"
	.string "suche sind. Davon ernährt es sich.$"

DexDescription_Teddiursa_1: @ 83AA090
	.string "TEDDIURSA leckt gern seine mit Honig\n"
	.string "bedeckten Pranken ab. Dieses POKéMON\n"
	.string "bereitet seinen eigenen Honig zu, indem$"

DexDescription_Teddiursa_2: @ 83AA106
	.string "es die von BIBOR gesammelten Früchte\n"
	.string "und Pollen miteinander vermengt.$"

DexDescription_Ursaring_1: @ 83AA138
	.string "In den von URSARING bewohnten Wäldern\n"
	.string "gibt es viele Flüsse und hohe Bäume, in\n"
	.string "denen es Nahrung findet. Dieses$"

DexDescription_Ursaring_2: @ 83AA1A3
	.string "POKéMON läuft täglich durch den Wald,\n"
	.string "um nach Essbarem zu suchen.$"

DexDescription_Slugma_1: @ 83AA1F0
	.string "Durch SCHNECKMAGs Kreislaufsystem\n"
	.string "fließt Magma. Wenn dieses POKéMON\n"
	.string "erkältet ist, kühlt das Magma$"

DexDescription_Slugma_2: @ 83AA253
	.string "aus und erhärtet. Sein Körper wird\n"
	.string "spröde und es brechen Stücke heraus,\n"
	.string "so dass es kleiner wird.$"

DexDescription_Magcargo_1: @ 83AA2A5
	.string "MAGCARGOs Schale ist eigentlich seine\n"
	.string "Haut, die erhärtet ist, als es auskühlte.\n"
	.string "Seine Schale ist sehr spröde und$"

DexDescription_Magcargo_2: @ 83AA319
	.string "zerbrechlich. Schon bei einer leichten\n"
	.string "Berührung bricht sie auseinander. Dann\n"
	.string "muss es ein Bad in Magma nehmen.$"

DexDescription_Swinub_1: @ 83AA38C
	.string "Auf Nahrungssuche schnüffelt QUIEKEL\n"
	.string "am Boden entlang. Seine \n"
	.string "Lieblingsspeise ist ein Pilz, der unter$"

DexDescription_Swinub_2: @ 83AA3FC
	.string "verwesendem Gras wächst. \n"
	.string "Manchmal spürt dieses POKéMON heiße\n"
	.string "Quellen auf.$"

DexDescription_Piloswine_1: @ 83AA446
	.string "KEIFEL hat ein dichtes Fell aus langen\n"
	.string "Haaren. Dadurch ist es gegen eisige\n"
	.string "Kälte gewappnet.$"

DexDescription_Piloswine_2: @ 83AA4A5
	.string "Dieses POKéMON benutzt seine\n"
	.string "Hauer, um an Nahrung zu gelangen, die\n"
	.string "unter dem Eis eingeschlossen ist.$"

DexDescription_Corsola_1: @ 83AA4F0
	.string "Wenn CORASONNs Arme Sonnenlicht\n"
	.string "abbekommen, glitzern sie wunderschön\n"
	.string "in sieben Farben. Wenn ein Arm$"

DexDescription_Corsola_2: @ 83AA546
	.string "abbricht, wächst über Nacht ein neuer\n"
	.string "nach.$"

DexDescription_Remoraid_1: @ 83AA58E
	.string "REMORAID saugt Wasser ein und spritzt\n"
	.string "es unter Einsatz seiner Bauchmuskeln\n"
	.string "mit Hochdruck wieder heraus. So schießt$"

DexDescription_Remoraid_2: @ 83AA5FE
	.string "es fliegende Beute ab. Wenn seine\n"
	.string "Entwicklung näher rückt, wandert\n"
	.string "dieses POKéMON flussabwärts.$"

DexDescription_Octillery_1: @ 83AA646
	.string "OCTILLERY saugt sich mit seinen\n"
	.string "Tentakeln an einem Feind fest. Dieses\n"
	.string "POKéMON betäubt seinen Gegner,$"

DexDescription_Octillery_2: @ 83AA6B2
	.string "bevor es ihm den Rest gibt.\n"
	.string "Wenn ein Feind zu stark ist, speit es\n"
	.string "Tinte aus und flüchtet.$"

DexDescription_Delibird_1: @ 83AA708
	.string "BOTOGEL sammelt seine Nahrung in\n"
	.string "seinem Schweif. Es gab einmal einen\n"
	.string "berühmten Entdecker, der es dank eines$"

DexDescription_Delibird_2: @ 83AA779
	.string "BOTOGELs geschafft hat, einen der\n"
	.string "höchsten Berge der Welt zu besteigen.\n"
	.string "Es hatte seine Nahrung mit ihm geteilt.$"

DexDescription_Mantine_1: @ 83AA7B9
	.string "An schönen Tagen sieht man Schwärme\n"
	.string "von MANTAX elegant über die Wellen des\n"
	.string "Ozeans springen.$"

DexDescription_Mantine_2: @ 83AA80F
	.string "Durch REMORAID, die an ihm haften\n"
	.string "und ihn begleiten, fühlt sich dieses\n"
	.string "POKéMON nicht belästigt.$"

DexDescription_Skarmory_1: @ 83AA850
	.string "PANZAERON ist komplett in einen harten,\n"
	.string "schützenden Panzer eingehüllt. Dieses\n"
	.string "POKéMON fliegt 300 km/h.$"

DexDescription_Skarmory_2: @ 83AA8B0
	.string "Es greift seine Feinde mit seinen\n"
	.string "messerscharfen Flügeln an.$"

DexDescription_Houndour_1: @ 83AA8F5
	.string "HUNDUSTER jagen in Gruppen. Sie\n"
	.string "kommunizieren miteinander über\n"
	.string "verschiedene Arten von Geheul und$"

DexDescription_Houndour_2: @ 83AA96A
	.string "treiben ihre Feinde in die Enge.\n"
	.string "Die Zusammenarbeit dieser POKéMON\n"
	.string "ist einzigartig.$"

DexDescription_Houndoom_1: @ 83AA99E
	.string "In einer Gruppe von HUNDEMON ist\n"
	.string "dasjenige mit den nach hinten\n"
	.string "gebogenen Hörnern der Anführer.$"

DexDescription_Houndoom_2: @ 83AAA02
	.string "Diese POKéMON bestimmen ihren Anführer\n"
	.string "durch das Ausfechten von Kämpfen\n"
	.string "untereinander.$"

DexDescription_Kingdra_1: @ 83AAA44
	.string "SEEDRAKING lebt in den Tiefen des\n"
	.string "Ozeans, die ansonsten verwaist sind.\n"
	.string "Lange hat man geglaubt, dass das$"

DexDescription_Kingdra_2: @ 83AAAAD
	.string "Gähnen dieses POKéMON Strudel auslöst.$"

DexDescription_Phanpy_1: @ 83AAAE7
	.string "Um sich ein Nest zu bauen, gräbt\n"
	.string "PHANPY am Flussufer ein Loch ins\n"
	.string "Erdreich. Es markiert die Umgebung$"

DexDescription_Phanpy_2: @ 83AAB5E
	.string "seines Nests mit Hilfe seines Rüssels,\n"
	.string "damit seine Artgenossen wissen, dass\n"
	.string "dieses Gebiet vergeben ist.$"

DexDescription_Donphan_1: @ 83AAB9F
	.string "DONPHANs Lieblingsattacke ist es, als\n"
	.string "Ball zusammengerollt mit voller Wucht\n"
	.string "gegen seine Gegner zu krachen.$"

DexDescription_Donphan_2: @ 83AAC10
	.string "Wenn es erst einmal rollt, ist dieses\n"
	.string "POKéMON nur schwer aufzuhalten.$"

DexDescription_Porygon2_1: @ 83AAC4D
	.string "PORYGON2 wurde in einem\n"
	.string "wissenschaftlichen Experiment von\n"
	.string "Menschen erzeugt. Es verfügt über$"

DexDescription_Porygon2_2: @ 83AACB3
	.string "künstliche Intelligenz, wodurch es \n"
	.string "selbstständig neue Gesten und Gefühle\n"
	.string "erlernen kann.$"

DexDescription_Stantler_1: @ 83AAD0A
	.string "DAMHIRPLEX hat ein prächtiges Geweih,\n"
	.string "für das hohe Preise gezahlt werden, da\n"
	.string "sie als Kunstwerke gelten.$"

DexDescription_Stantler_2: @ 83AAD7A
	.string "Daher wurde dieses POKéMON gejagt und\n"
	.string "wäre beinahe ausgestorben.$"

DexDescription_Smeargle_1: @ 83AADBD
	.string "FARBEAGLE markiert sein Revier mit\n"
	.string "einer Flüssigkeit, die aus seiner\n"
	.string "Schweifspitze austritt.$"

DexDescription_Smeargle_2: @ 83AAE28
	.string "Es wurden über 5000 unterschiedliche\n"
	.string "Markierungen entdeckt, die dieses\n"
	.string "POKéMON hinterlassen hat.$"

DexDescription_Tyrogue_1: @ 83AAE69
	.string "RABAUZ muss jeden Tag trainieren,\n"
	.string "sonst ist es nicht ausgelastet und\n"
	.string "reagiert gestresst. Wenn man dieses$"

DexDescription_Tyrogue_2: @ 83AAED4
	.string "POKéMON trainiert, muss man\n"
	.string "zahlreiche Trainingsmethoden\n"
	.string "einsetzen und sie ständig ausbauen.$"

DexDescription_Hitmontop_1: @ 83AAF08
	.string "KAPOERA dreht sich auf dem Kopf\n"
	.string "stehend um die eigene Achse und teilt\n"
	.string "Tritte aus. Seine Technik ist eine$"

DexDescription_Hitmontop_2: @ 83AAF79
	.string "bemerkenswerte Mischung aus Angriff \n"
	.string "und Verteidigung. Es bewegt sich \n"
	.string "drehend schneller voran als laufend.$"

DexDescription_Smoochum_1: @ 83AAFDE
	.string "KUSSILLA läuft hektisch umher, fällt\n"
	.string "aber auch ziemlich oft hin. Es lässt\n"
	.string "keine Möglichkeit aus sein Spiegelbild$"

DexDescription_Smoochum_2: @ 83AB03D
	.string "zu betrachten, um sicherzustellen,\n"
	.string "dass sein Gesicht nicht schmutzig\n"
	.string "geworden ist.$"

DexDescription_Elekid_1: @ 83AB080
	.string "ELEKID speichert Elektrizität in seinem\n"
	.string "Körper. Wenn es Metall berührt und\n"
	.string "versehentlich die aufgestaute Energie$"

DexDescription_Elekid_2: @ 83AB0F5
	.string "entlädt, rotiert es mit den Armen, um\n"
	.string "sich wieder aufzuladen.$"

DexDescription_Magby_1: @ 83AB13A
	.string "MAGBYs Gesundheitszustand kann man\n"
	.string "am Feuer erkennen, das es ausatmet.\n"
	.string "Wenn es gelbe Flammen ausstößt, ist es$"

DexDescription_Magby_2: @ 83AB1A5
	.string "in guter Verfassung. Ist es erschöpft,\n"
	.string "vermischen sich die Flammen mit\n"
	.string "schwarzem Rauch.$"

DexDescription_Miltank_1: @ 83AB215
	.string "MILTANK gibt täglich 20 Liter Milch.\n"
	.string "Sie ist süßlich und wird von Kindern und\n"
	.string "Erwachsenen gleichermaßen genossen.$"

DexDescription_Miltank_2: @ 83AB28A
	.string "Menschen, die keine Milch trinken,\n"
	.string "essen sie stattdessen als Joghurt.$"

DexDescription_Blissey_1: @ 83AB2CE
	.string "HEITEIRA nimmt mit seinem flauschigen\n"
	.string "Fell Traurigkeit wahr. Es hastet zu\n"
	.string "einer traurigen Person, egal, wie weit$"

DexDescription_Blissey_2: @ 83AB340
	.string "diese entfernt ist und teilt ein \n"
	.string "GLÜCKS-EI mit ihr, um sie zum Lächeln\n"
	.string "zu bringen.$"

DexDescription_Raikou_1: @ 83AB397
	.string "RAIKOU ist so schnell wie der Blitz. Das\n"
	.string "Gebrüll dieses POKéMON sendet\n"
	.string "Schockwellen aus, die wie Donnerschläge$"

DexDescription_Raikou_2: @ 83AB409
	.string "durch die Luft beben und den Boden\n"
	.string "erschüttern.$"

DexDescription_Entei_1: @ 83AB448
	.string "ENTEI verfügt über die Leidenschaft\n"
	.string "von Magma. Dieses POKéMON wurde\n"
	.string "bei einem Vulkanausbruch geboren$"

DexDescription_Entei_2: @ 83AB4B5
	.string "und bringt Feuersbrünste hervor, die\n"
	.string "alles auslöschen, was mit ihnen in\n"
	.string "Kontakt kommt.$"

DexDescription_Suicune_1: @ 83AB502
	.string "SUICUNE wohnt die Reinheit einer\n"
	.string "Quelle inne. Es bewegt sich graziös und \n"
	.string "hat die Macht, schmutziges Wasser zu$"

DexDescription_Suicune_2: @ 83AB568
	.string "reinigen.$"

DexDescription_Larvitar_1: @ 83AB59A
	.string "LARVITAR wurde tief unter der Erde\n"
	.string "geboren. Um an die Oberfläche zu\n"
	.string "gelangen, muss es sich durch das$"

DexDescription_Larvitar_2: @ 83AB613
	.string "Erdreich fressen. Erst dann bekommt es\n"
	.string "seine Eltern zu Gesicht.$"

DexDescription_Pupitar_1: @ 83AB64C
	.string "PUPITAR erzeugt in seinem Körper ein\n"
	.string "Gas, das es komprimiert und kraftvoll\n"
	.string "ausstößt, um sich wie ein$"

DexDescription_Pupitar_2: @ 83AB6B8
	.string "Düsenflugzeug anzutreiben. Sein\n"
	.string "Körper ist sehr robust und er hält\n"
	.string "auch massivem Stahl stand.$"

DexDescription_Tyranitar_1: @ 83AB701
	.string "DESPOTAR ist erstaunlich stark. Es\n"
	.string "kann einen ganzen Berg vernichten, um\n"
	.string "sein Nest zu bauen. Dieses POKéMON$"

DexDescription_Tyranitar_2: @ 83AB75F
	.string "wandert in den Bergen umher und sucht\n"
	.string "nach Gegnern für einen Kampf.$"

DexDescription_Lugia_1: @ 83AB7A7
	.string "LUGIAs Flügel haben eine\n"
	.string "zerstörerische Kraft. Bereits ein\n"
	.string "leichtes Flattern kann Häuser$"

DexDescription_Lugia_2: @ 83AB80D
	.string "hinfortwehen. Daher hat sich dieses\n"
	.string "POKéMON dafür entschieden, tief unter\n"
	.string "dem Meer zu leben, wo es niemand sieht.$"

DexDescription_HoOh_1: @ 83AB858
	.string "HO-OHs Federn leuchten in sieben\n"
	.string "Farben, je nachdem aus welchem Winkel\n"
	.string "das Licht auf sie fällt.$"

DexDescription_HoOh_2: @ 83AB8B8
	.string "Die Federn sollen ihrem Besitzer Glück\n"
	.string "bringen. Dieses POKéMON lebt am Fuße\n"
	.string "eines Regenbogens.$"

DexDescription_Celebi_1: @ 83AB92A
	.string "Dieses POKéMON kommt aus der Zukunft\n"
	.string "und ist durch die Zeit gereist. Solange\n"
	.string "CELEBI auftaucht,$"

DexDescription_Celebi_2: @ 83AB988
	.string "ist der Menschheit angeblich eine\n"
	.string "rosige Zukunft beschieden.$"

DexDescription_Treecko_1: @ 83AB9B8
	.string "Mit den kleinen Haken unter seinen\n"
	.string "Füßen kann GECKARBOR an Wänden\n"
	.string "hochklettern. Dieses POKéMON greift$"

DexDescription_Treecko_2: @ 83ABA12
	.string "Feinde an, indem es mit seinem\n"
	.string "mächtigen Schweif zuschlägt.$"

DexDescription_Grovyle_1: @ 83ABA4D
	.string "REPTAIN kann sich mit den Blättern, die\n"
	.string "aus seinem Körper herauswachsen, im\n"
	.string "Wald hervorragend tarnen.$"

DexDescription_Grovyle_2: @ 83ABAB5
	.string "Dieses POKéMON ist ein wahrer Meister\n"
	.string "darin, auf die Bäume des Dschungels zu\n"
	.string "klettern.$"

DexDescription_Sceptile_1: @ 83ABAEC
	.string "Die Blätter, die auf GEWALDROs Körper\n"
	.string "wachsen, sind sehr scharfkantig. Dieses\n"
	.string "POKéMON ist sehr agil. Es hüpft von$"

DexDescription_Sceptile_2: @ 83ABB5B
	.string "Ast zu Ast und springt seine Feinde\n"
	.string "von oben oder hinten an.$"

DexDescription_Torchic_1: @ 83ABB98
	.string "FLEMMLI hängt an seinem Trainer wie\n"
	.string "eine Klette. Es schlurft immer hinter ihm\n"
	.string "her. Dieses POKéMON spuckt 1000 Grad$"

DexDescription_Torchic_2: @ 83ABBDF
	.string "heißes Feuer, das seinen Feinden\n"
	.string "ordentlich einheizt.$"

DexDescription_Combusken_1: @ 83ABC4A
	.string "JUNGGLUT trainiert seine Beine und\n"
	.string "Oberschenkel, indem es über Felder und\n"
	.string "Berge läuft. Die Beine dieses POKéMON$"

DexDescription_Combusken_2: @ 83ABC9D
	.string "sind sowohl schnell als auch kräftig,\n"
	.string "so dass es 10 Tritte pro Sekunde\n"
	.string "ausführen kann.$"

DexDescription_Blaziken_1: @ 83ABD00
	.string "LOHGOCK stößt heftige Flammen aus\n"
	.string "seinen Handgelenken aus und greift\n"
	.string "seine Feinde mutig an. Je stärker ein$"

DexDescription_Blaziken_2: @ 83ABD5C
	.string "Feind ist, desto stärker lodern die\n"
	.string "Handgelenke dieses POKéMON.$"

DexDescription_Mudkip_1: @ 83ABDA1
	.string "Die Flosse an HYDROPIs Kopf dient als\n"
	.string "hochempfindliches Radar. Damit kann es\n"
	.string "Bewegungen im Wasser und in der Luft$"

DexDescription_Mudkip_2: @ 83ABE13
	.string "wahrnehmen. So weiß es jederzeit, was\n"
	.string "in seiner Umgebung passiert, ohne\n"
	.string "dabei seine Augen zu benutzen.$"

DexDescription_Marshtomp_1: @ 83ABE60
	.string "MOORABBELs Körper ist mit einem\n"
	.string "klebrigen Film überzogen, durch den es\n"
	.string "an Land überleben kann. Dieses POKéMON$"

DexDescription_Marshtomp_2: @ 83ABEC5
	.string "spielt bei Ebbe in den Schlammpfützen\n"
	.string "am Strand.$"

DexDescription_Swampert_1: @ 83ABF06
	.string "SUMPEX ist sehr stark. Es kann mit\n"
	.string "Leichtigkeit einen Felsblock bewegen,\n"
	.string "der über eine Tonne wiegt.$"

DexDescription_Swampert_2: @ 83ABF66
	.string "Weiterhin ist es mit einem exzellenten\n"
	.string "Sehvermögen ausgestattet, wodurch es\n"
	.string "auch in trüben Gewässern sehen kann.$"

DexDescription_Poochyena_1: @ 83ABFB2
	.string "Sobald FIFFYEN eine Bewegung wahr-\n"
	.string "nimmt, schnappt es zu. Es jagt seine\n"
	.string "Beute so lange, bis sie vollkommen$"

DexDescription_Poochyena_2: @ 83AC016
	.string "erschöpft ist. Wenn sich die Beute\n"
	.string "allerdings wehrt, kann es passieren, \n"
	.string "dass FIFFYEN klein beigibt und flieht.$"

DexDescription_Mightyena_1: @ 83AC068
	.string "MAGNAYEN sendet deutliche Signale\n"
	.string "aus, wenn es sich auf einen Angriff\n"
	.string "vorbereitet. Es knurrt heftig und macht$"

DexDescription_Mightyena_2: @ 83AC0DE
	.string "sich flach. Dieses POKéMON kann mit\n"
	.string "seinen spitzen Zähnen brutal zubeißen.$"

DexDescription_Zigzagoon_1: @ 83AC11E
	.string "ZIGZACHS ist ein rastloser Wanderer.\n"
	.string "Dieses POKéMON ist nämlich sehr\n"
	.string "neugierig und es inspiziert alles,$"

DexDescription_Zigzagoon_2: @ 83AC185
	.string "was ihm zufällig begegnet.$"

DexDescription_Linoone_1: @ 83AC1BF
	.string "GERADAKS rennt immer mit vollem Tempo\n"
	.string "und nie im Zickzack, sondern nur gerade.\n"
	.string "Wenn ihm ein Hindernis im Weg ist,$"

DexDescription_Linoone_2: @ 83AC23A
	.string "läuft es rechtwinklig daran vorbei. Für\n"
	.string "dieses POKéMON stellen leichte Kurven\n"
	.string "eine große Herausforderung dar.$"

DexDescription_Wurmple_1: @ 83AC273
	.string "WAUMPEL kann mit den Stacheln an\n"
	.string "seinem Hinterteil die Rinde von Bäumen\n"
	.string "entfernen und ernährt sich von dem$"

DexDescription_Wurmple_2: @ 83AC2DD
	.string "austretenden Saft. An den Füßen dieses\n"
	.string "POKéMON befinden sich Saugnäpfe, mit\n"
	.string "denen es auch an Glas nicht abrutscht.$"

DexDescription_Silcoon_1: @ 83AC340
	.string "SCHALOKO bindet sich mit einem\n"
	.string "Seidenfaden an einen Ast. Es baumelt\n"
	.string "dort und wartet auf seine Entwicklung.$"

DexDescription_Silcoon_2: @ 83AC3B5
	.string "Durch ein kleines Loch in seinem\n"
	.string "Seidenkokon lugt es heraus.$"

DexDescription_Beautifly_1: @ 83AC3FD
	.string "PAPINELLAs Lieblingsspeise ist\n"
	.string "Blütenstaub. Wenn du dieses POKéMON\n"
	.string "beobachten möchtest, musst du bloß$"

DexDescription_Beautifly_2: @ 83AC46C
	.string "einen Blumentopf vor ein geöffnetes\n"
	.string "Fenster stellen. PAPINELLA wird sich\n"
	.string "diese Leckerei nicht entgehen lassen.$"

DexDescription_Cascoon_1: @ 83AC4B4
	.string "PANEKON baut seinen schützenden\n"
	.string "Kokon, indem es seinen Körper mit\n"
	.string "feiner Seide einwickelt, die aus seinem$"

DexDescription_Cascoon_2: @ 83AC525
	.string "Mund austritt. Wenn sein Körper mit\n"
	.string "Seide bedeckt ist, wird diese hart. Im\n"
	.string "Kokon wartet es auf seine Entwicklung.$"

DexDescription_Dustox_1: @ 83AC582
	.string "PUDOX wird instinktiv vom Licht\n"
	.string "angezogen. In hell erleuchteten \n"
	.string "Städten kann man Scharen dieses$"

DexDescription_Dustox_2: @ 83AC5F5
	.string "POKéMON dabei beobachten, die\n"
	.string "großen Schaden anrichten, indem sie die\n"
	.string "Blätter von Bäumen abfressen.$"

DexDescription_Lotad_1: @ 83AC63B
	.string "LOTURZEL lebt auf der Wasseroberfläche\n"
	.string "von Teichen oder Seen. Es wird\n"
	.string "schwächer, wenn sein breites Blatt$"

DexDescription_Lotad_2: @ 83AC6A1
	.string "abstirbt. Nur selten geht dieses\n"
	.string "POKéMON an Land, um nach sauberem\n"
	.string "Wasser Ausschau zu halten.$"

DexDescription_Lombre_1: @ 83AC6EB
	.string "LOMBRERO liebt die Nacht und wird mit\n"
	.string "Einbruch der Dunkelheit aktiv. Es spielt\n"
	.string "auch gerne Streiche.$"

DexDescription_Lombre_2: @ 83AC75E
	.string "Wenn es Angler sieht, zieht es unter\n"
	.string "Wasser an ihren Angelschnüren und\n"
	.string "erfreut sich an ihrer Entrüstung.$"

DexDescription_Ludicolo_1: @ 83AC7B6
	.string "KAPPALORES fängt sofort zu tanzen an,\n"
	.string "wenn es stimmungsvolle, feierliche Musik\n"
	.string "vernimmt. Dieses POKéMON erscheint$"

DexDescription_Ludicolo_2: @ 83AC822
	.string "angeblich, wenn es Kinder auf \n"
	.string "Wanderausflügen singen hört.$"

DexDescription_Seedot_1: @ 83AC853
	.string "SAMURZEL hängt sich mit dem Kopf an\n"
	.string "einen Ast. Dabei entzieht es dem Baum\n"
	.string "Feuchtigkeit. Je mehr Wasser es trinkt,$"

DexDescription_Seedot_2: @ 83AC8BC
	.string "desto glänzender wird der Körper dieses\n"
	.string "POKéMON.$"

DexDescription_Nuzleaf_1: @ 83AC918
	.string "BLANAS lebt in dichten Wäldern.\n"
	.string "Manchmal wagt es sich aus dem Wald\n"
	.string "heraus, um Menschen zu erschrecken.$"

DexDescription_Nuzleaf_2: @ 83AC982
	.string "Dieses POKéMON mag es überhaupt nicht,\n"
	.string "wenn man seine lange Nase zwickt.$"

DexDescription_Shiftry_1: @ 83AC9B6
	.string "TENGULIST ist ein geheimnisvolles\n"
	.string "POKéMON, das angeblich auf hohen\n"
	.string "Bäumen lebt, die tausende von Jahren$"

DexDescription_Shiftry_2: @ 83ACA23
	.string "alt sind. Mit den Blätterventilatoren an\n"
	.string "seinen Händen kann es heftige Stürme\n"
	.string "erzeugen.$"

DexDescription_Taillow_1: @ 83ACA5A
	.string "Mutig behauptet SCHWALBINI sein\n"
	.string "Territorium gegen Eindringlinge, so\n"
	.string "stark diese auch sein mögen.$"

DexDescription_Taillow_2: @ 83ACAAB
	.string "Dieses unerschrockene POKéMON bleibt\n"
	.string "trotz einer Niederlage angriffslustig,\n"
	.string "heult aber laut, wenn es Hunger hat.$"

DexDescription_Swellow_1: @ 83ACB1E
	.string "Dieses POKéMON taucht in einem steilen\n"
	.string "Winkel ab, sobald es Beute wahrgenommen\n"
	.string "hat. Es packt seine Beute mit$"

DexDescription_Swellow_2: @ 83ACB8A
	.string "seinen Krallen und lässt sie\n"
	.string "nicht mehr entkommen.$"

DexDescription_Wingull_1: @ 83ACBF6
	.string "Man sieht WINGULL oft mit seiner\n"
	.string "Beute oder seinen Besitztümern im\n"
	.string "Schnabel herumfliegen auf der Suche$"

DexDescription_Wingull_2: @ 83ACC62
	.string "nach geeigneten Verstecken. Dieses\n"
	.string "POKéMON fliegt durch die Lüfte, als\n"
	.string "würde es gleiten.$"

DexDescription_Pelipper_1: @ 83ACCAF
	.string "PELIPPER transportiert kleine POKéMON\n"
	.string "und Eier in seinem riesigen Schnabel\n"
	.string "durch die Lüfte. Dieses POKéMON baut$"

DexDescription_Pelipper_2: @ 83ACD0D
	.string "sein Nest auf steilen Klippen am Meer.$"

DexDescription_Ralts_1: @ 83ACD4A
	.string "TRASLA nimmt mit den Hörnern an seinem\n"
	.string "Kopf die Gefühle von Menschen wahr.\n"
	.string "Menschen bekommen dieses POKéMON$"

DexDescription_Ralts_2: @ 83ACDAE
	.string "nur selten zu Gesicht. Wenn es bemerkt,\n"
	.string "dass eine Person gut gelaunt ist, traut\n"
	.string "es sich näher an sie heran.$"

DexDescription_Kirlia_1: @ 83ACE11
	.string "Man sagt, dass ein KIRLIA, das häufig\n"
	.string "positive Emotionen seines TRAINERs\n"
	.string "wahrnimmt, sehr schön wird.$"

DexDescription_Kirlia_2: @ 83ACE73
	.string "Dieses POKéMON kontrolliert\n"
	.string "psychokinetische Energie mit seinem\n"
	.string "hochentwickelten Gehirn.$"

DexDescription_Gardevoir_1: @ 83ACEBF
	.string "GUARDEVOIR kann in die Zukunft\n"
	.string "schauen. Wenn es eine Gefahr für seinen\n"
	.string "TRAINER voraussieht, entlädt es seine$"

DexDescription_Gardevoir_2: @ 83ACF33
	.string "psychokinetische Energie mit voller\n"
	.string "Kraft.$"

DexDescription_Surskit_1: @ 83ACF63
	.string "GEHWEIHER scheidet aus seinen Zehen\n"
	.string "ein Öl aus, das es ihm ermöglicht, über\n"
	.string "Wasser zu gleiten. Dieses POKéMON$"

DexDescription_Surskit_2: @ 83ACFCE
	.string "ernährt sich von Mikroorganismen aus\n"
	.string "Teichen und Seen.$"

DexDescription_Masquerain_1: @ 83AD00E
	.string "MASKEREGEN schüchtert seine Feinde\n"
	.string "mit den augenähnlichen Mustern auf\n"
	.string "seinen Antennen ein. Dieses POKéMON$"

DexDescription_Masquerain_2: @ 83AD07D
	.string "kann mit seinen vier Flügeln wie ein\n"
	.string "Hubschrauber in jede Richtung fliegen,\n"
	.string "sogar seitwärts und rückwärts.$"

DexDescription_Shroomish_1: @ 83AD0D5
	.string "KNILZ lebt im feuchten Erdboden\n"
	.string "finsterer Wälder. Es wird oft reglos\n"
	.string "unter herabgefallenen Blättern$"

DexDescription_Shroomish_2: @ 83AD148
	.string "gefunden. Dieses POKéMON ernährt sich\n"
	.string "von Kompost aus verrotteten Blättern.$"

DexDescription_Breloom_1: @ 83AD190
	.string "Mit leichtfüßiger Beinarbeit nähert \n"
	.string "sich KAPILZ seinen Feinden und\n"
	.string "schlägt dann mit seinen dehnbaren$"

DexDescription_Breloom_2: @ 83AD1FC
	.string "Armen um sich. Die Kampftechnik dieses\n"
	.string "POKéMON treibt Profiboxern die\n"
	.string "Schamesröte ins Gesicht.$"

DexDescription_Slakoth_1: @ 83AD234
	.string "BUMMELZ geht zwanzig Stunden pro Tag\n"
	.string "müßig. Da es sich sehr wenig bewegt,\n"
	.string "braucht es auch nicht viel Nahrung.$"

DexDescription_Slakoth_2: @ 83AD2A2
	.string "Seine Tagesration besteht lediglich aus\n"
	.string "drei Blättern.$"

DexDescription_Vigoroth_1: @ 83AD2E0
	.string "MUNTIER brennt darauf, sich\n"
	.string "auszutoben. Es kann nicht einmal für\n"
	.string "eine Minute stillsitzen. Es gerät in$"

DexDescription_Vigoroth_2: @ 83AD35B
	.string "Stress, wenn es sich nicht andauernd\n"
	.string "bewegen kann.$"

DexDescription_Slaking_1: @ 83AD39F
	.string "LETARKING verbringt den Tag damit,\n"
	.string "herumzuliegen und nichts zu tun. Es \n"
	.string "ernährt sich von Gras, das in seiner$"

DexDescription_Slaking_2: @ 83AD3FC
	.string "Reichweite wächst. Hat es alles\n"
	.string "aufgefressen, so sucht es sich\n"
	.string "widerwillig ein anderes Plätzchen.$"

DexDescription_Nincada_1: @ 83AD453
	.string "NINCADA lebt viele Jahre in absoluter\n"
	.string "Dunkelheit unter der Erde. Dieses\n"
	.string "POKéMON nimmt Nährstoffe aus$"

DexDescription_Nincada_2: @ 83AD4B6
	.string "Baumwurzeln auf. Es rührt sich nicht,\n"
	.string "da es auf seine Entwicklung wartet.$"

DexDescription_Ninjask_1: @ 83AD4F9
	.string "NINJASK bewegt sich so schnell, dass\n"
	.string "man es nicht sehen kann. Seine Schreie\n"
	.string "sind aber laut und deutlich zu hören.$"

DexDescription_Ninjask_2: @ 83AD567
	.string "Deshalb hielt man dieses POKéMON lange\n"
	.string "für unsichtbar.$"

DexDescription_Shedinja_1: @ 83AD5A8
	.string "NINJATOMs harter Körper bewegt sich\n"
	.string "überhaupt nicht. Er scheint bloß eine\n"
	.string "hohle Schale zu sein. Dieses POKéMON$"

DexDescription_Shedinja_2: @ 83AD616
	.string "soll angeblich die Seele eines jeden\n"
	.string "stehlen, der hinterrücks einen Blick in\n"
	.string "seinen hohlen Körper riskiert.$"

DexDescription_Whismur_1: @ 83AD683
	.string "Normalerweise ist FLURMELs Stimme sehr\n"
	.string "leise, selbst mit größter Anstrengung\n"
	.string "ist sie kaum hörbar. Wenn dieses$"

DexDescription_Whismur_2: @ 83AD6E9
	.string "POKéMON jedoch eine Gefahr wittert,\n"
	.string "stößt es ohrenbetäubende Schreie aus.$"

DexDescription_Loudred_1: @ 83AD73D
	.string "KRAKEELOs Brüllen kann ein Holzhaus zum\n"
	.string "Einsturz bringen. Es setzt seine Stimme\n"
	.string "ein, um seine Gegner anzugreifen.$"

DexDescription_Loudred_2: @ 83AD7A3
	.string "Die runden Ohren dieses POKéMON dienen\n"
	.string "als Lautsprecher.$"

DexDescription_Exploud_1: @ 83AD7D4
	.string "KRAWUMMS kann durch sein Brüllen\n"
	.string "Erdbeben auslösen. Wenn dieses\n"
	.string "POKéMON durch seine Körperöffnungen$"

DexDescription_Exploud_2: @ 83AD846
	.string "kräftig einatmet, ist es kurz davor,\n"
	.string "ein mächtiges Brüllen von sich zu geben.$"

DexDescription_Makuhita_1: @ 83AD896
	.string "MAKUHITA ist sehr zäh. Selbst wenn es im\n"
	.string "Kampf mehrfach niedergeschlagen\n"
	.string "wurde, steht es immer wieder auf und$"

DexDescription_Makuhita_2: @ 83AD903
	.string "greift seinen Gegner an. Bei jedem Mal\n"
	.string "speichert es mehr Energie in seinem\n"
	.string "Körper für seine Entwicklung.$"

DexDescription_Hariyama_1: @ 83AD959
	.string "HARIYAMA führt seinen berüchtigten\n"
	.string "Streckarm-Schlag überall aus. Ein Schlag\n"
	.string "von diesem POKéMON reicht aus,$"

DexDescription_Hariyama_2: @ 83AD9C3
	.string "um einen Strommast zu zerlegen.$"

DexDescription_Azurill_1: @ 83ADA08
	.string "AZURILL schleudert seinen Schweif wie\n"
	.string "ein Lasso weit aus und fliegt dann \n"
	.string "selbst hinterher. Ein AZURILL$"

DexDescription_Azurill_2: @ 83ADA7F
	.string "hat es auf diese Weise geschafft, die\n"
	.string "Rekordweite von 10 Metern\n"
	.string "zurückzulegen.$"

DexDescription_Nosepass_1: @ 83ADAD7
	.string "NASGNET besitzt eine magnetische\n"
	.string "Nase, die immer nach Norden zeigt. Wenn\n"
	.string "sich zwei NASGNET treffen, können sie$"

DexDescription_Nosepass_2: @ 83ADB3F
	.string "sich einander nicht zuwenden, da ihre\n"
	.string "magnetischen Nasen sich gegenseitig\n"
	.string "abstoßen.$"

DexDescription_Skitty_1: @ 83ADB9D
	.string "ENECO ist davon fasziniert,\n"
	.string "Gegenstände zu bewegen und sie zu\n"
	.string "jagen. Dieses POKéMON jagt häufig$"

DexDescription_Skitty_2: @ 83ADBF4
	.string "seinen eigenen Schweif, so dass ihm\n"
	.string "schwindlig wird.$"

DexDescription_Delcatty_1: @ 83ADC38
	.string "ENEKORO liebt seine Eigenständigkeit.\n"
	.string "So kann es das tun, was es möchte, und\n"
	.string "kann selbst das Tempo bestimmen.$"

DexDescription_Delcatty_2: @ 83ADC9B
	.string "Da dieses POKéMON schläft und isst,\n"
	.string "wenn es Lust dazu hat, ist sein\n"
	.string "Tagesablauf eher zufälliger Natur.$"

DexDescription_Sableye_1: @ 83ADCFF
	.string "ZOBIRIS führt ein ruhiges, \n"
	.string "zurückgezogenes Leben tief im Innern\n"
	.string "einer Höhle. Es ist aber trotzdem sehr$"

DexDescription_Sableye_2: @ 83ADD6C
	.string "gefürchtet, da man sagt, es stehle die\n"
	.string "Seelen der Menschen, wenn seine Augen\n"
	.string "im Dunkeln Furcht erregend funkeln.$"

DexDescription_Mawile_1: @ 83ADDC3
	.string "FLUNKIFERs sagenhafte Kiefer sind\n"
	.string "eigentlich umgewandelte Stahlhörner.\n"
	.string "Sein unterwürfiger Gesichtsausdruck$"

DexDescription_Mawile_2: @ 83ADE33
	.string "dient dazu, seinen Gegner in Sicherheit\n"
	.string "zu wiegen, so dass er unaufmerksam\n"
	.string "wird. Dann schnappt es zu!$"

DexDescription_Aron_1: @ 83ADE9F
	.string "Dieses POKéMON hat einen Körper aus\n"
	.string "Stahl. STOLLUNIOR ernährt sich von\n"
	.string "Eisenerz aus den Bergen. Zuweilen$"

DexDescription_Aron_2: @ 83ADF07
	.string "richtet es großen Schaden an, weil es\n"
	.string "Brücken und Bahngleise auffrisst.$"

DexDescription_Lairon_1: @ 83ADF4A
	.string "STOLLRAK temperiert seinen Körper,\n"
	.string "indem es ausgesprochen nahrhaftes \n"
	.string "Quellwasser trinkt, bis es völlig$"

DexDescription_Lairon_2: @ 83ADFAF
	.string "aufgebläht ist. Dieses POKéMON baut\n"
	.string "sein Nest in der Nähe von Quellen, aus\n"
	.string "denen köstliches Wasser sprudelt.$"

DexDescription_Aggron_1: @ 83ADFF0
	.string "STOLLOSS nennt einen ganzen Berg sein\n"
	.string "Territorium. Gnadenlos schlägt es jeden\n"
	.string "in die Flucht, der sein Reich betritt.$"

DexDescription_Aggron_2: @ 83AE067
	.string "Dieses POKéMON behält sein Territorium\n"
	.string "jederzeit im Auge.$"

DexDescription_Meditite_1: @ 83AE0A3
	.string "MEDITIE unterzieht sich einem\n"
	.string "strikten mentalen Training tief in den\n"
	.string "Bergen. Wenn es meditiert, verliert es$"

DexDescription_Meditite_2: @ 83AE10C
	.string "jedoch immer seine Konzentration.\n"
	.string "Deshalb wird sein Training niemals\n"
	.string "ein Ende haben.$"

DexDescription_Medicham_1: @ 83AE164
	.string "Mittels Meditation erhöht MEDITALIS\n"
	.string "seine Körperenergie und schärft seinen\n"
	.string "sechsten Sinn. Dieses POKéMON$"

DexDescription_Medicham_2: @ 83AE1D0
	.string "verbirgt sich, indem es eins mit den\n"
	.string "Feldern und Bergen wird.$"

DexDescription_Electrike_1: @ 83AE21D
	.string "FRIZELBLIZ speichert Elektrizität in\n"
	.string "seiner langen Körperbehaarung. Dieses\n"
	.string "POKéMON stimuliert seine$"

DexDescription_Electrike_2: @ 83AE290
	.string "Beinmuskulatur durch Stromstöße.\n"
	.string "Dadurch ist es in der Lage, explosiv\n"
	.string "zu beschleunigen.$"

DexDescription_Manectric_1: @ 83AE2D7
	.string "VOLTENSO entlädt ständig Elektrizität\n"
	.string "aus seiner Mähne. Es fliegen dabei\n"
	.string "Funken, die zuweilen zu Waldbränden$"

DexDescription_Manectric_2: @ 83AE340
	.string "führen. In einem Kampf erzeugt dieses\n"
	.string "POKéMON Gewitterwolken.$"

DexDescription_Plusle_1: @ 83AE37D
	.string "PLUSLE dient seinen Artgenossen als\n"
	.string "Cheerleader. Wenn ein Teamkamerad\n"
	.string "im Kampf erfolgreich ist, erzeugt es$"

DexDescription_Plusle_2: @ 83AE3EE
	.string "das prasselnde Geräusch von Funken, um\n"
	.string "so seine Freude zu zeigen.$"

DexDescription_Minun_1: @ 83AE444
	.string "MINUN kümmert sich mehr um das\n"
	.string "Anfeuern seiner Partner als um seine\n"
	.string "eigene Sicherheit. Es nutzt die$"

DexDescription_Minun_2: @ 83AE4B5
	.string "Elektrizität in seinem Körper dazu,\n"
	.string "einen Funkenregen zu erzeugen und\n"
	.string "seine Teamkameraden anzufeuern.$"

DexDescription_Volbeat_1: @ 83AE4FB
	.string "Wenn es Nacht wird, beginnt VOLBEATs\n"
	.string "Schweif zu leuchten. Es kommuniziert\n"
	.string "mit anderen, indem es die Helligkeit$"

DexDescription_Volbeat_2: @ 83AE574
	.string "und das Blinken dieses Lichts reguliert.\n"
	.string "Dieses POKéMON wird vom süßen Duft\n"
	.string "der ILLUMISE angezogen.$"

DexDescription_Illumise_1: @ 83AE5C5
	.string "ILLUMISE zieht ganze VOLBEAT-Scharen\n"
	.string "mit seinem süßlichen Duft an. Dann\n"
	.string "führt es diesen hell leuchtenden$"

DexDescription_Illumise_2: @ 83AE630
	.string "Schwarm an, indem es geometrische\n"
	.string "Figuren an den Nachthimmel malt.$"

DexDescription_Roselia_1: @ 83AE684
	.string "ROSELIA verschießt scharfe Stacheln\n"
	.string "auf jeden Feind, der versucht, die\n"
	.string "Blumen an seinen Armen zu stehlen.$"

DexDescription_Roselia_2: @ 83AE6EC
	.string "Der Duft dieses POKéMON beruhigt\n"
	.string "Lebewesen.$"

DexDescription_Gulpin_1: @ 83AE728
	.string "Eigentlich besteht SCHLUPPUCKs Körper\n"
	.string "nur aus einem Magen. Daher kann es\n"
	.string "etwas verschlingen, das beinahe seine$"

DexDescription_Gulpin_2: @ 83AE78B
	.string "Größe hat. Sein Magen enthält eine\n"
	.string "spezielle Flüssigkeit, die wirklich alles\n"
	.string "verdauen kann.$"

DexDescription_Swalot_1: @ 83AE7D2
	.string "Wenn SCHLUKWECH Beute sichtet,\n"
	.string "verspritzt es eine höchst giftige\n"
	.string "Substanz aus seinen Poren und$"

DexDescription_Swalot_2: @ 83AE836
	.string "besprüht damit sein Ziel. Wenn die Beute\n"
	.string "geschwächt ist, schluckt es sie mit\n"
	.string "seinem riesigen Maul im Ganzen herunter.$"

DexDescription_Carvanha_1: @ 83AE88D
	.string "KANIVANHAs starke Kiefer und seine\n"
	.string "spitzen Zähne verfügen über die \n"
	.string "zerstörerische Kraft, Bootsrümpfe$"

DexDescription_Carvanha_2: @ 83AE900
	.string "verschlingen zu können. Dieses POKéMON\n"
	.string "hat schon viele Boote versenkt.$"

DexDescription_Sharpedo_1: @ 83AE938
	.string "TOHAIDO trägt den Spitznamen\n"
	.string "“Tyrann des Meeres” und ist\n"
	.string "sehr gefürchtet. Seine grausamen Zähne$"

DexDescription_Sharpedo_2: @ 83AE99B
	.string "wachsen sofort nach, wenn sie\n"
	.string "ausgebrochen sind. Es kann sogar einen\n"
	.string "Öltanker zerreißen.$"

DexDescription_Wailmer_1: @ 83AE9F0
	.string "WAILMERs Nasenlöcher liegen über\n"
	.string "seinen Augen. Dieses verspielte\n"
	.string "POKéMON erschreckt gern Menschen,$"

DexDescription_Wailmer_2: @ 83AEA63
	.string "indem es das Meerwasser, das es in\n"
	.string "seinem Körper speichert, mit aller Kraft\n"
	.string "herausprustet.$"

DexDescription_Wailord_1: @ 83AEA9F
	.string "WAILORD ist bisher das größte aller\n"
	.string "identifizierten POKéMON. Es schwimmt\n"
	.string "reglos auf dem offenen Meer und nimmt$"

DexDescription_Wailord_2: @ 83AEB01
	.string "mit seinem enormen Maul riesige Mengen\n"
	.string "an Nahrung auf.$"

DexDescription_Numel_1: @ 83AEB57
	.string "CAMAUB ist nicht besonders helle. Es\n"
	.string "nimmt nicht einmal wahr, wenn es\n"
	.string "getroffen wurde. Ein Hungergefühl$"

DexDescription_Numel_2: @ 83AEBC7
	.string "allerdings kann es nicht einmal eine\n"
	.string "Sekunde lang aushalten. In seinem\n"
	.string "Körper brodelt glühend heißes Magma.$"

DexDescription_Camerupt_1: @ 83AEC04
	.string "CAMERUPT trägt einen Vulkan in seinem\n"
	.string "Körper. 10.000 Grad heißes Magma fließt\n"
	.string "in ihm. Manchmal brechen die Höcker auf$"

DexDescription_Camerupt_2: @ 83AEC60
	.string "seinem Rücken aus und verspucken \n"
	.string "glühend heißes Magma.$"

DexDescription_Torkoal_1: @ 83AECB5
	.string "QURTEL schaufelt sich auf der Suche\n"
	.string "nach Kohle durch die Berge. Wenn es\n"
	.string "welche findet, füllt es die Hohlräume$"

DexDescription_Torkoal_2: @ 83AED2B
	.string "seines Panzers mit Kohle und verbrennt\n"
	.string "diese. Wenn es angegriffen wird, stößt\n"
	.string "es dicken schwarzen Rauch aus.$"

DexDescription_Spoink_1: @ 83AED85
	.string "SPOINK hüpft auf seinem Schweif durch\n"
	.string "die Gegend. Die Erschütterung des\n"
	.string "Hüpfens bringt sein Herz zum Schlagen.$"

DexDescription_Spoink_2: @ 83AEDF2
	.string "Deshalb kann dieses POKéMON das Hüpfen\n"
	.string "nicht sein lassen, ansonsten würde sein\n"
	.string "Herz aufhören zu schlagen.$"

DexDescription_Grumpig_1: @ 83AEE35
	.string "GROINK benutzt die schwarzen Perlen\n"
	.string "an seinem Körper dazu, die\n"
	.string "psychischen Kraftwellen zu verstärken.$"

DexDescription_Grumpig_2: @ 83AEEAA
	.string "Wenn es diese spezielle Fähigkeit nutzt,\n"
	.string "wird sein schnaubender Atem\n"
	.string "schwerfällig.$"

DexDescription_Spinda_1: @ 83AEEF7
	.string "Jedes PANDIR auf der Welt soll ein\n"
	.string "einzigartiges Fleckenmuster haben. Der\n"
	.string "schwankende Gang dieses POKéMON$"

DexDescription_Spinda_2: @ 83AEF4D
	.string "erweckt den Eindruck, es würde tanzen.$"

DexDescription_Trapinch_1: @ 83AEF9B
	.string "KNACKLIONs Bau ist eine Art in den Sand\n"
	.string "gegrabener Kessel. Dieses POKéMON\n"
	.string "wartet geduldig auf Beute, um sie in$"

DexDescription_Trapinch_2: @ 83AF011
	.string "seinen Bau zu werfen. Seine gigan-\n"
	.string "tischen Kiefer verfügen über genügend\n"
	.string "Kraft, um einen Felsen zu zerquetschen.$"

DexDescription_Vibrava_1: @ 83AF04D
	.string "Um seine Beute zu schwächen, erzeugt\n"
	.string "VIBRAVA Ultraschallwellen, indem es\n"
	.string "seine Flügel vibrieren lässt.$"

DexDescription_Vibrava_2: @ 83AF0B0
	.string "Die Ultraschallwellen dieses POKéMON \n"
	.string "sind so stark, dass sie bei Menschen\n"
	.string "Kopfschmerzen verursachen können.$"

DexDescription_Flygon_1: @ 83AF108
	.string "LIBELLDRA wird auch “Geist der\n"
	.string "Wüste” genannt. Da seine flatternden\n"
	.string "Flügel eine Sandwolke aufwirbeln, ist$"

DexDescription_Flygon_2: @ 83AF177
	.string "dieses POKéMON beim Fliegen immer\n"
	.string "von einem Sandsturm umgeben.$"

DexDescription_Cacnea_1: @ 83AF1B5
	.string "TUSKA lebt an trockenen Orten, z. B. in\n"
	.string "Wüsten. Es versprüht einen starken\n"
	.string "Duft aus seiner Blume, um Beute$"

DexDescription_Cacnea_2: @ 83AF221
	.string "anzuziehen. Wenn sich Beute nähert,\n"
	.string "verschießt es scharfe Stacheln, um\n"
	.string "seinen Gegner zu überwältigen.$"

DexDescription_Cacturne_1: @ 83AF280
	.string "Am Tage bleibt NOKTUSKA reglos, damit es\n"
	.string "in der brennenden Wüstenhitze keine\n"
	.string "Feuchtigkeit verliert.$"

DexDescription_Cacturne_2: @ 83AF2ED
	.string "Dieses POKéMON wird bei Nacht aktiv,\n"
	.string "wenn die Temperatur sinkt.$"

DexDescription_Swablu_1: @ 83AF32E
	.string "WABLU hat leichte, flauschige Flügel,\n"
	.string "die wie Schäfchenwolken aussehen.\n"
	.string "Dieses POKéMON hat keine Angst vor$"

DexDescription_Swablu_2: @ 83AF398
	.string "Menschen. Es landet auf ihren Köpfen \n"
	.string "und bleibt dort sitzen wie ein \n"
	.string "wattierter Hut.$"

DexDescription_Altaria_1: @ 83AF3E0
	.string "ALTARIA tanzt und dreht sich in der\n"
	.string "Luft durch viele Schäfchenwolken.\n"
	.string "Indem es mit seiner kristallklaren$"

DexDescription_Altaria_2: @ 83AF458
	.string "Stimme Melodien singt, versetzt es\n"
	.string "seine Zuhörer in verträumtes\n"
	.string "Erstaunen.$"

DexDescription_Zangoose_1: @ 83AF49E
	.string "Die Erinnerungen an den Kampf mit\n"
	.string "seinem Erzrivalen VIPITIS haben sich in\n"
	.string "jede Zelle von SENGOs Körper$"

DexDescription_Zangoose_2: @ 83AF4F9
	.string "eingebrannt. Dieses POKéMON weicht\n"
	.string "feindlichen Angriffen unheimlich\n"
	.string "raffiniert und geschickt aus.$"

DexDescription_Seviper_1: @ 83AF537
	.string "VIPITIS lebt seit Generationen in\n"
	.string "Fehde mit SENGO. Die Narben auf\n"
	.string "seinem Körper sind Zeugen grausamer$"

DexDescription_Seviper_2: @ 83AF5A4
	.string "Kämpfe. Dieses POKéMON greift seine\n"
	.string "Gegner mit seinem scharfkantigen\n"
	.string "Schweif an.$"

DexDescription_Lunatone_1: @ 83AF5D6
	.string "LUNASTEIN wurde in der Nähe eines\n"
	.string "Meteoritenkraters entdeckt. Daher\n"
	.string "nehmen einige Menschen an, dass$"

DexDescription_Lunatone_2: @ 83AF648
	.string "dieses POKéMON aus dem Weltall stammt.\n"
	.string "Diese Theorie konnte allerdings bisher\n"
	.string "noch nicht belegt werden.$"

DexDescription_Solrock_1: @ 83AF694
	.string "SONNFEL ist eine neue POKéMON-Spezies,\n"
	.string "die angeblich aus dem Weltall\n"
	.string "kam. Es gleitet durch die$"

DexDescription_Solrock_2: @ 83AF705
	.string "Luft und bewegt sich leise. Im Kampf\n"
	.string "setzt dieses POKéMON sehr helles Licht\n"
	.string "ein.$"

DexDescription_Barboach_1: @ 83AF73E
	.string "SCHMERBEs empfindliche Barthaare\n"
	.string "dienen ihm als hervorragendes\n"
	.string "Radarsystem. Dieses POKéMON versteckt$"

DexDescription_Barboach_2: @ 83AF7A4
	.string "sich im Schlamm, so dass nur noch seine\n"
	.string "Barthaare herausgucken, und wartet\n"
	.string "auf Beute.$"

DexDescription_Whiscash_1: @ 83AF7E4
	.string "WELSAR legt viel Wert auf sein\n"
	.string "Territorium. Ein einzelnes POKéMON\n"
	.string "dieser Art nennt einen Teich sein Eigen.$"

DexDescription_Whiscash_2: @ 83AF855
	.string "Wenn sich ein Feind nähert, schlägt es\n"
	.string "um sich und verursacht ein gewaltiges\n"
	.string "Erdbeben.$"

DexDescription_Corphish_1: @ 83AF8A2
	.string "KREBSCORPS ist kein heimisches\n"
	.string "POKéMON, sondern wurde als Haustier\n"
	.string "importiert. Schließlich verwilderte es.$"

DexDescription_Corphish_2: @ 83AF90E
	.string "Dieses POKéMON ist mittlerweile sehr\n"
	.string "robust und hat seine Population\n"
	.string "vergrößert.$"

DexDescription_Crawdaunt_1: @ 83AF953
	.string "KREBUTACK ist von Natur aus sehr\n"
	.string "gewalttätig, so dass es dauernd andere\n"
	.string "Lebewesen zum Kampf herausfordern$"

DexDescription_Crawdaunt_2: @ 83AF9B9
	.string "muss. Andere Lebensformen lehnen es ab,\n"
	.string "mit diesem POKéMON in ein und demselben\n"
	.string "Teich zu leben.$"

DexDescription_Baltoy_1: @ 83AFA1A
	.string "PUPPANCE bewegt sich, indem es sich auf\n"
	.string "seinem Fuß im Kreis dreht. In sehr alten\n"
	.string "Ruinen wurden primitive Wandmalereien$"

DexDescription_Baltoy_2: @ 83AFA8B
	.string "entdeckt, die dieses POKéMON in\n"
	.string "Begleitung von Menschen zeigen.$"

DexDescription_Claydol_1: @ 83AFAB9
	.string "LEPUMENTAS sind aus Schlamm gefertigte\n"
	.string "Puppen, die von primitiven Menschen\n"
	.string "hergestellt und durch mysteriöse$"

DexDescription_Claydol_2: @ 83AFB2B
	.string "Strahlen zum Leben erweckt wurden.\n"
	.string "Diese POKéMON bewegen sich\n"
	.string "schwebend fort.$"

DexDescription_Lileep_1: @ 83AFB56
	.string "Von LILIEP nahm man an, es sei seit\n"
	.string "etwa hundert Millionen Jahren\n"
	.string "ausgestorben. Mit seinen wie$"

DexDescription_Lileep_2: @ 83AFBBC
	.string "Blütenblätter geformten Tentakeln\n"
	.string "heftet es sich an einen Felsen auf dem\n"
	.string "Meeresboden und fängt Beute.$"

DexDescription_Cradily_1: @ 83AFC1F
	.string "WIELIE durchforstet den Meeresboden\n"
	.string "nach Beute. Dieses POKéMON fährt\n"
	.string "seinen baumstammartigen Nacken aus$"

DexDescription_Cradily_2: @ 83AFC90
	.string "und fängt mit seinen acht Tentakeln\n"
	.string "Beute.$"

DexDescription_Anorith_1: @ 83AFCC0
	.string "ANORITH wurde aus einem\n"
	.string "prähistorischen Fossil erzeugt. Dieses\n"
	.string "primitive POKéMON lebte einst in warmen$"

DexDescription_Anorith_2: @ 83AFD23
	.string "Gewässern. Es klemmt seine Beute\n"
	.string "fest zwischen seine beiden riesigen\n"
	.string "Klauen ein.$"

DexDescription_Armaldo_1: @ 83AFD59
	.string "Von ARMALDOs hartem Panzer prallen\n"
	.string "alle Angriffe ab. Dieses POKéMON\n"
	.string "hat zwei mächtige Klauen, die es$"

DexDescription_Armaldo_2: @ 83AFDC6
	.string "ausfahren oder einziehen kann. Es hat\n"
	.string "so viel Kraft, dass es damit eine\n"
	.string "Stahlplatte pulverisieren kann.$"

DexDescription_Feebas_1: @ 83AFE0E
	.string "BARSCHWAs Flossen waren schon immer\n"
	.string "zerfetzt. Wegen seines merkwürdigen\n"
	.string "Aussehens wird dieses POKéMON$"

DexDescription_Feebas_2: @ 83AFE77
	.string "weitgehend ignoriert. Es kann sowohl im\n"
	.string "Meer als auch in Flüssen leben.$"

DexDescription_Milotic_1: @ 83AFECA
	.string "MILOTIC soll das Schönste aller\n"
	.string "POKéMON sein. Es hat die Macht,\n"
	.string "Emotionen wie Wut und Feindseligkeit zu$"

DexDescription_Milotic_2: @ 83AFF27
	.string "besänftigen und somit erbitterten\n"
	.string "Streit zu vermeiden.$"

DexDescription_Castform_1: @ 83AFF60
	.string "FORMEOs Erscheinung ändert sich\n"
	.string "mit dem Wetter. Dieses POKéMON hat\n"
	.string "die Fähigkeit erworben, die mächtige$"

DexDescription_Castform_2: @ 83AFFB7
	.string "Kraft der Natur zu nutzen, um seinen\n"
	.string "winzigen Körper zu schützen.$"

DexDescription_Kecleon_1: @ 83AFFEA
	.string "KECLEON kann die Farbe seines Körpers\n"
	.string "bei Bedarf verändern, um sich seiner\n"
	.string "Umgebung anzupassen. Es gibt allerdings$"

DexDescription_Kecleon_2: @ 83B0044
	.string "eine Ausnahme: Das Zickzackmuster auf\n"
	.string "seinem Bauch kann es nicht verändern.$"

DexDescription_Shuppet_1: @ 83B0098
	.string "SHUPPET wird durch Gefühle wie Neid und\n"
	.string "Rachsucht angezogen. Wenn jemand\n"
	.string "starke Rachegelüste entwickelt,$"

DexDescription_Shuppet_2: @ 83B0100
	.string "erscheint dieses POKéMON in Scharen\n"
	.string "und reiht sich unter der Dachrinne der\n"
	.string "Person auf.$"

DexDescription_Banette_1: @ 83B0164
	.string "BANETTE belegt andere mit Flüchen,\n"
	.string "indem es Nadeln in seinen eigenen\n"
	.string "Körper sticht. Dieses POKéMON war$"

DexDescription_Banette_2: @ 83B01BA
	.string "ursprünglich eine Mitleid erregende\n"
	.string "Plüschpuppe, die weggeworfen wurde.$"

DexDescription_Duskull_1: @ 83B0201
	.string "ZWIRRLICHT kann durch jede Wand gehen,\n"
	.string "egal, wie dick diese ist. Wenn dieses\n"
	.string "POKéMON sich ein Ziel gesucht hat,$"

DexDescription_Duskull_2: @ 83B0266
	.string "verfolgt es seinen Feind unnachgiebig\n"
	.string "bis zum Sonnenaufgang.$"

DexDescription_Dusclops_1: @ 83B02AB
	.string "ZWIRRKLOPs Körper ist komplett hohl. Es\n"
	.string "wird auch mit einem Schwarzen Loch\n"
	.string "verglichen. Dieses POKéMON nimmt alles$"

DexDescription_Dusclops_2: @ 83B031B
	.string "in seinem Körper auf, es kommt jedoch\n"
	.string "nichts wieder heraus.$"

DexDescription_Tropius_1: @ 83B0377
	.string "Die Früchte am Nacken von TROPIUS\n"
	.string "sind bei Kindern sehr beliebt. Dieses\n"
	.string "POKéMON liebt Früchte und isst sie$"

DexDescription_Tropius_2: @ 83B03E8
	.string "ständig. Offensichtlich sind ihm wegen\n"
	.string "dieser Vorliebe selber Früchte\n"
	.string "gewachsen.$"

DexDescription_Chimecho_1: @ 83B043D
	.string "PALIMPALIMs Schreie hallen durch\n"
	.string "seinen hohlen Körper. Wenn dieses\n"
	.string "POKéMON wütend wird, erzeugen$"

DexDescription_Chimecho_2: @ 83B04A0
	.string "seine Schreie Ultraschallwellen, die\n"
	.string "seine Feinde buchstäblich wegfegen\n"
	.string "können.$"

DexDescription_Absol_1: @ 83B04E5
	.string "Jedes Mal, wenn ABSOL sich den Menschen\n"
	.string "zeigt, endet dies in einer Katastrophe\n"
	.string "wie Erdbeben oder Sturmflut.$"

DexDescription_Absol_2: @ 83B0551
	.string "Deswegen ist es auch als das\n"
	.string "Katastrophen-POKéMON bekannt.$"

DexDescription_Wynaut_1: @ 83B058B
	.string "ISSO hat immer ein breites, fröhliches\n"
	.string "Lächeln auf seinem Gesicht. Um \n"
	.string "festzustellen, ob es wütend ist, muss$"

DexDescription_Wynaut_2: @ 83B05F8
	.string "man seinen Schweif betrachten. Wenn es\n"
	.string "wütend ist, schlägt es damit auf den\n"
	.string "Boden.$"

DexDescription_Snorunt_1: @ 83B063E
	.string "SCHNEPPKE lebt in Gebieten mit heftigem\n"
	.string "Schneefall. In Jahreszeiten, in denen es\n"
	.string "nicht schneit, wie im Frühling oder im$"

DexDescription_Snorunt_2: @ 83B06AC
	.string "Sommer, nimmt das POKéMON Reißaus, um\n"
	.string "in einer Höhle ein ruhiges Leben unter\n"
	.string "Stalaktiten und Stalagmiten zu führen.$"

DexDescription_Glalie_1: @ 83B06FB
	.string "FIRNONTOR hat einen Körper aus Stein,\n"
	.string "den es mit einem Panzer aus Eis noch\n"
	.string "verstärkt. Dieses POKéMON kann$"

DexDescription_Glalie_2: @ 83B0769
	.string "die Luftfeuchtigkeit der Atmosphäre\n"
	.string "einfrieren und in jegliche Form\n"
	.string "verwandeln.$"

DexDescription_Spheal_1: @ 83B079F
	.string "SEEMOPS kann schneller rollen als laufen.\n"
	.string "Wenn Gruppen dieses POKéMON \n"
	.string "zusammen essen, klatschen sie$"

DexDescription_Spheal_2: @ 83B0811
	.string "gleichzeitig, um ihre Freude zu zeigen.\n"
	.string "Deswegen sind ihre Mahlzeiten sehr\n"
	.string "laut.$"

DexDescription_Sealeo_1: @ 83B0855
	.string "SEEJONG hat die Angewohnheit, alles,\n"
	.string "was es zum ersten Mal sieht, auf seiner \n"
	.string "Nasenspitze zu jonglieren. Dieses$"

DexDescription_Sealeo_2: @ 83B08B9
	.string "POKéMON hält sich bei Laune, indem es\n"
	.string "manchmal ein SEEMOPS auf seiner Nase\n"
	.string "balanciert und hin- und herrollt.$"

DexDescription_Walrein_1: @ 83B0914
	.string "WALRAISA hat zwei massive Stoßzähne,\n"
	.string "die mit einem Hieb Eisblöcke\n"
	.string "zertrümmern können, die bis zu$"

DexDescription_Walrein_2: @ 83B097F
	.string "10 Tonnen wiegen. Es besitzt eine dicke\n"
	.string "Speckschicht, die es vor eisigen\n"
	.string "Temperaturen schützt.$"

DexDescription_Clamperl_1: @ 83B09CC
	.string "PERLUs kräftige Schale dient nicht\n"
	.string "nur dem Schutz, es nutzt sie auch zum\n"
	.string "Fangen von Beute. Die ausgewachsene$"

DexDescription_Clamperl_2: @ 83B0A36
	.string "Schale eines PERLU weist viele\n"
	.string "Kerben und Kratzer auf.$"

DexDescription_Huntail_1: @ 83B0A87
	.string "AALABYSS entging lange der\n"
	.string "Aufmerksamkeit des Menschen, da es in\n"
	.string "extremen Tiefen des Meeres lebt.$"

DexDescription_Huntail_2: @ 83B0AF2
	.string "Die Augen dieses POKéMON können\n"
	.string "selbst in den dunklen und trüben Tiefen\n"
	.string "des Meeres einwandfrei sehen.$"

DexDescription_Gorebyss_1: @ 83B0B42
	.string "SAGANABYSS lebt in extremen Tiefen des\n"
	.string "Südmeeres. Sein Körper ist so angelegt,\n"
	.string "dass er dem enormen Wasserdruck dieser$"

DexDescription_Gorebyss_2: @ 83B0BB1
	.string "unglaublichen Tiefe standhalten kann.\n"
	.string "Daher übersteht dieses POKéMON\n"
	.string "gewöhnliche Attacken unbeschadet.$"

DexDescription_Relicanth_1: @ 83B0C13
	.string "RELICANTH ist eine POKéMON-Spezies,\n"
	.string "die vor hundert Millionen Jahren\n"
	.string "existierte, ohne jemals ihre Form zu$"

DexDescription_Relicanth_2: @ 83B0C7B
	.string "verändern. Dieses antike POKéMON\n"
	.string "hat ein zahnloses Maul und ernährt sich\n"
	.string "von Mikroorganismen.$"

DexDescription_Luvdisc_1: @ 83B0CC9
	.string "LIEBISKUS lebt in den seichten\n"
	.string "Gewässern der Tropen. Dieses herz-\n"
	.string "förmige POKéMON verdankt seinen Namen$"

DexDescription_Luvdisc_2: @ 83B0D32
	.string "der Tatsache, dass es hinter Liebes-\n"
	.string "paaren herschwamm, die es in den Wellen\n"
	.string "des Ozeans beobachtet hatte.$"

DexDescription_Bagon_1: @ 83B0D62
	.string "KINDWURM hat den Traum, fliegen zu\n"
	.string "können. In zahlreichen vergeblichen\n"
	.string "Versuchen stürzte es sich die Klippen$"

DexDescription_Bagon_2: @ 83B0DD3
	.string "herunter. Daher ist sein Kopf sehr\n"
	.string "robust und so hart wie Stahl geworden.$"

DexDescription_Shelgon_1: @ 83B0E26
	.string "In DRASCHELs panzerartiger Schale\n"
	.string "vollziehen seine Zellen eine\n"
	.string "Transformation, um einen völlig neuen$"

DexDescription_Shelgon_2: @ 83B0E92
	.string "Körper zu bilden. Die Schale dieses\n"
	.string "POKéMON ist ausgesprochen schwer, so\n"
	.string "dass seine Bewegungen träge wirken.$"

DexDescription_Salamence_1: @ 83B0EDA
	.string "BRUTALANDA träumte sehr lange davon,\n"
	.string "dass ihm Flügel wachsen mögen. Dieser\n"
	.string "sehnliche Wunsch hat wohl eine$"

DexDescription_Salamence_2: @ 83B0F48
	.string "plötzliche Mutation in den Zellen dieses\n"
	.string "POKéMON hervorgerufen, so dass ihm\n"
	.string "plötzlich prächtige Flügel wuchsen.$"

DexDescription_Beldum_1: @ 83B0FB0
	.string "Anstelle von Blut fließt eine starke\n"
	.string "magnetische Energie durch TANHELs\n"
	.string "Körper. Dieses POKéMON kommuniziert$"

DexDescription_Beldum_2: @ 83B101D
	.string "mit anderen, indem es kontrollierte\n"
	.string "magnetische Impulse aussendet.$"

DexDescription_Metang_1: @ 83B104F
	.string "Wenn zwei TANHEL miteinander\n"
	.string "verschmelzen, entsteht daraus METANG.\n"
	.string "Die Gehirne der TANHEL werden mit$"

DexDescription_Metang_2: @ 83B10C2
	.string "einem magnetischen Nervensystem\n"
	.string "verbunden. Dadurch erzeugt es starke\n"
	.string "psychokinetische Energie.$"

DexDescription_Metagross_1: @ 83B1119
	.string "METAGROSS hat insgesamt vier Gehirne.\n"
	.string "Diese können schwierige Berechnungen\n"
	.string "schneller lösen als ein Supercomputer.$"

DexDescription_Metagross_2: @ 83B1188
	.string "Dieses POKéMON kann durch die Lüfte\n"
	.string "schweben, indem es seine vier Beine\n"
	.string "einklappt.$"

DexDescription_Regirock_1: @ 83B11DD
	.string "REGIROCK wurde vor langer Zeit von\n"
	.string "Menschen weggeschlossen. Wenn der\n"
	.string "Körper dieses POKéMON im Kampf$"

DexDescription_Regirock_2: @ 83B124A
	.string "Schaden nimmt, sucht es nach\n"
	.string "passenden Steinen, um sich selber zu\n"
	.string "reparieren.$"

DexDescription_Regice_1: @ 83B127A
	.string "REGICEs tiefgefrorener Körper\n"
	.string "entstand während der Eiszeit. Es kann\n"
	.string "nicht einmal durch Feuer geschmolzen$"

DexDescription_Regice_2: @ 83B12D8
	.string "werden. Dieses POKéMON kontrolliert\n"
	.string "eisige Luft von minus 200 Grad.$"

DexDescription_Registeel_1: @ 83B1311
	.string "REGISTEEL hat einen Körper, der härter\n"
	.string "ist als jede Art von Metall. Sein Körper\n"
	.string "scheint hohl zu sein.$"

DexDescription_Registeel_2: @ 83B136C
	.string "Niemand hat eine Ahnung, was dieses\n"
	.string "POKéMON wohl frisst.$"

DexDescription_Latias_1: @ 83B1398
	.string "LATIAS ist in höchstem Maße empfindlich\n"
	.string "gegenüber den Emotionen der Menschen.\n"
	.string "Wenn es den Anflug von Feindseligkeit$"

DexDescription_Latias_2: @ 83B1403
	.string "wahrnimmt, werden seine Federn\n"
	.string "zerzaust und es stößt schrille Schreie\n"
	.string "aus, um seinen Gegner einzuschüchtern.$"

DexDescription_Latios_1: @ 83B1447
	.string "LATIOS kann seinem Feind ein Bild\n"
	.string "von etwas, das dieser einmal gesehen\n"
	.string "hat, in den Kopf projizieren. Dieses$"

DexDescription_Latios_2: @ 83B14A8
	.string "POKéMON ist intelligent und es versteht\n"
	.string "die menschliche Sprache.$"

DexDescription_Kyogre_1: @ 83B14E2
	.string "KYOGRE kann riesige Regenwolken\n"
	.string "erzeugen, die den gesamten Himmel\n"
	.string "bedecken, und wolkenbruchartige$"

DexDescription_Kyogre_2: @ 83B1555
	.string "Niederschläge hervorrufen. Dieses\n"
	.string "POKéMON hat vielen Menschen das Leben\n"
	.string "gerettet, die unter einer Dürre litten.$"

DexDescription_Groudon_1: @ 83B1591
	.string "GROUDON wurde lange Zeit in der\n"
	.string "Mythologie als ein POKéMON\n"
	.string "beschrieben, das Land erschaffen und$"

DexDescription_Groudon_2: @ 83B15F9
	.string "Kontinente vergrößern kann. Dieses\n"
	.string "POKéMON fiel nach einem erbitterten\n"
	.string "Kampf mit KYOGRE in den Schlaf.$"

DexDescription_Rayquaza_1: @ 83B163C
	.string "RAYQUAZA lebte für hunderte Millionen\n"
	.string "Jahre in der Ozonschicht und stieg nie\n"
	.string "zur Erde hinab. Dieses POKéMON$"

DexDescription_Rayquaza_2: @ 83B16AA
	.string "lebt von Wasser und Partikeln aus der\n"
	.string "Atmosphäre.$"

DexDescription_Jirachi_1: @ 83B16F1
	.string "Einer Legende nach erfüllt JIRACHI\n"
	.string "jeden Wunsch, der auf einen Notizzettel\n"
	.string "an seinem Kopf geschrieben wird. Wenn$"

DexDescription_Jirachi_2: @ 83B1765
	.string "dieses POKéMON Gefahr wittert, kämpft\n"
	.string "es bereits, bevor es überhaupt\n"
	.string "aufgewacht ist.$"

DexDescription_Deoxys_1: @ 83B17A5
	.string "Die DNS eines Weltraumvirus hat eine\n"
	.string "spontane Mutation erfahren, da sie\n"
	.string "einem Laserstrahl ausgesetzt wurde.$"

DexDescription_Deoxys_2: @ 83B1810
	.string "Daraus entstand DEOXYS. \n"
	.string "Das kristallartige Organ auf der Brust\n"
	.string "dieses POKéMON ist sein Gehirn.$"

@ Unfortunately, preproc doesn't allow us to use strings inside macros,
@ so the category names have to be on separate lines.

	.align 2
gPokedexEntries:: @ 83B1858
	.string "UNBEKANNT$", 12
	pokedex_entry      Dummy,   0,    0, 256,   0,  256,  0
	.string "SAMEN$", 12
	pokedex_entry  Bulbasaur,   7,   69, 356,  17,  256,  0
	.string "SAMEN$", 12
	pokedex_entry    Ivysaur,  10,  130, 335,  13,  256,  0
	.string "SAMEN$", 12
	pokedex_entry   Venusaur,  20, 1000, 256,   0,  388,  6
	.string "ECHSE$", 12
	pokedex_entry Charmander,   6,   85, 444,  18,  256,  0
	.string "FLAMME$", 12
	pokedex_entry Charmeleon,  11,  190, 302,   9,  256,  0
	.string "FLAMME$", 12
	pokedex_entry  Charizard,  17,  905, 256,   1,  302,  3
	.string "MINIKRÖTE$", 12
	pokedex_entry   Squirtle,   5,   90, 412,  18,  256,  0
	.string "KRÖTE$", 12
	pokedex_entry  Wartortle,  10,  225, 332,  10,  256,  0
	.string "PANZERTIER$", 12
	pokedex_entry  Blastoise,  16,  855, 256,  -1,  293,  2
	.string "WURM$", 12
	pokedex_entry   Caterpie,   3,   29, 549,  22,  256,  0
	.string "KOKON$", 12
	pokedex_entry    Metapod,   7,   99, 350,  18,  256,  0
	.string "FALTER$", 12
	pokedex_entry Butterfree,  11,  320, 312,   2,  256,  0
	.string "RAUPE$", 12
	pokedex_entry     Weedle,   3,   32, 455,  22,  256,  0
	.string "KOKON$", 12
	pokedex_entry     Kakuna,   6,  100, 424,  17,  256,  0
	.string "GIFTBIENE$", 12
	pokedex_entry   Beedrill,  10,  295, 366,   2,  256,  0
	.string "KLEINVOGEL$", 12
	pokedex_entry     Pidgey,   3,   18, 508,  -3,  256,  0
	.string "VOGEL$", 12
	pokedex_entry  Pidgeotto,  11,  300, 331,  10,  256,  0
	.string "VOGEL$", 12
	pokedex_entry    Pidgeot,  15,  395, 269,   0,  256,  0
	.string "MAUS$", 12
	pokedex_entry    Rattata,   3,   35, 481,  21,  256,  0
	.string "MAUS$", 12
	pokedex_entry   Raticate,   7,  185, 459,  18,  256,  0
	.string "KLEINVOGEL$", 12
	pokedex_entry    Spearow,   3,   20, 571,  22,  256,  0
	.string "PICKVOGEL$", 12
	pokedex_entry     Fearow,  12,  380, 278,   1,  256,  0
	.string "SCHLANGE$", 12
	pokedex_entry      Ekans,  20,   69, 298,  12,  256,  0
	.string "KOBRA$", 12
	pokedex_entry      Arbok,  35,  650, 256,   0,  296,  2
	.string "MAUS$", 12
	pokedex_entry    Pikachu,   4,   60, 479,  19,  256,  0
	.string "MAUS$", 12
	pokedex_entry     Raichu,   8,  300, 426,  13,  256,  0
	.string "MAUS$", 12
	pokedex_entry  Sandshrew,   6,  120, 365,  18,  256,  0
	.string "MAUS$", 12
	pokedex_entry  Sandslash,  10,  295, 341,  11,  256,  0
	.string "GIFTDORN$", 12
	pokedex_entry   NidoranF,   4,   70, 488,  21,  256,  0
	.string "GIFTDORN$", 12
	pokedex_entry   Nidorina,   8,  200, 381,  15,  256,  0
	.string "BOHRER$", 12
	pokedex_entry  Nidoqueen,  13,  600, 293,   4,  256,  0
	.string "GIFTDORN$", 12
	pokedex_entry   NidoranM,   5,   90, 511,  20,  256,  0
	.string "GIFTDORN$", 12
	pokedex_entry   Nidorino,   9,  195, 408,  15,  256,  0
	.string "BOHRER$", 12
	pokedex_entry   Nidoking,  14,  620, 256,   0,  256,  0
	.string "FEE$", 12
	pokedex_entry   Clefairy,   6,   75, 441,  20,  256,  0
	.string "FEE$", 12
	pokedex_entry   Clefable,  13,  400, 256,   5,  256,  0
	.string "FUCHS$", 12
	pokedex_entry     Vulpix,   6,   99, 542,  19,  256,  0
	.string "FUCHS$", 12
	pokedex_entry  Ninetales,  11,  199, 339,  10,  256,  0
	.string "BALLON$", 12
	pokedex_entry Jigglypuff,   5,   55, 433,   2,  256,  0
	.string "BALLON$", 12
	pokedex_entry Wigglytuff,  10,  120, 328,  11,  256,  0
	.string "FLEDERMAUS$", 12
	pokedex_entry      Zubat,   8,   75, 362,  -5,  256,  0
	.string "FLEDERMAUS$", 12
	pokedex_entry     Golbat,  16,  550, 256,   1,  256,  0
	.string "UNKRAUT$", 12
	pokedex_entry     Oddish,   5,   54, 423,  19,  256,  0
	.string "UNKRAUT$", 12
	pokedex_entry      Gloom,   8,   86, 329,  13,  256,  0
	.string "BLUME$", 12
	pokedex_entry  Vileplume,  12,  186, 256,   4,  256,  0
	.string "PILZ$", 12
	pokedex_entry      Paras,   3,   54, 593,  22,  256,  0
	.string "PILZ$", 12
	pokedex_entry   Parasect,  10,  295, 307,   8,  256,  0
	.string "INSEKT$", 12
	pokedex_entry    Venonat,  10,  300, 360,   0,  256, -1
	.string "GIFTMOTTE$", 12
	pokedex_entry   Venomoth,  15,  125, 285,   2,  256,  1
	.string "MAULWURF$", 12
	pokedex_entry    Diglett,   2,    8, 833,  25,  256,  0
	.string "MAULWURF$", 12
	pokedex_entry    Dugtrio,   7,  333, 406,  18,  256,  0
	.string "KATZE$", 12
	pokedex_entry     Meowth,   4,   42, 480,  19,  256,  0
	.string "RASSEKATZE$", 12
	pokedex_entry    Persian,  10,  320, 320,  10,  256,  0
	.string "ENTE$", 12
	pokedex_entry    Psyduck,   8,  196, 369,  15,  256,  0
	.string "ENTE$", 12
	pokedex_entry    Golduck,  17,  766, 256,   1,  273,  1
	.string "SCHW./ AFFE$", 12
	pokedex_entry     Mankey,   5,  280, 404,  19,  256,  0
	.string "SCHW./ AFFE$", 12
	pokedex_entry   Primeape,  10,  320, 326,  10,  256,  0
	.string "HUND$", 12
	pokedex_entry  Growlithe,   7,  190, 346,  14,  256,  0
	.string "LEGENDÄR$", 12
	pokedex_entry   Arcanine,  19, 1550, 256,   1,  312,  4
	.string "KAULQUAPPE$", 12
	pokedex_entry    Poliwag,   6,  124, 369,  20,  256,  0
	.string "KAULQUAPPE$", 12
	pokedex_entry  Poliwhirl,  10,  200, 288,  11,  256,  0
	.string "KAULQUAPPE$", 12
	pokedex_entry  Poliwrath,  13,  540, 256,   6,  256,  0
	.string "PSI$", 12
	pokedex_entry       Abra,   9,  195, 363,  14,  256,  0
	.string "PSI$", 12
	pokedex_entry    Kadabra,  13,  565, 256,   3,  256,  0
	.string "PSI$", 12
	pokedex_entry   Alakazam,  15,  480, 256,   3,  256,  0
	.string "KRAFTPROTZ$", 12
	pokedex_entry     Machop,   8,  195, 342,  14,  256,  0
	.string "KRAFTPROTZ$", 12
	pokedex_entry    Machoke,  15,  705, 323,   9,  257,  0
	.string "KRAFTPROTZ$", 12
	pokedex_entry    Machamp,  16, 1300, 280,   1,  269, -1
	.string "BLUME$", 12
	pokedex_entry Bellsprout,   7,   40, 354,  16,  256,  0
	.string "FLIEGENTOT$", 12
	pokedex_entry Weepinbell,  10,   64, 256,   0,  256,  0
	.string "FLIEGENTOT$", 12
	pokedex_entry Victreebel,  17,  155, 256,   1,  312,  3
	.string "QUALLE$", 12
	pokedex_entry  Tentacool,   9,  455, 256,   0,  256,  0
	.string "QUALLE$", 12
	pokedex_entry Tentacruel,  16,  550, 256,   0,  312,  1
	.string "GESTEIN$", 12
	pokedex_entry    Geodude,   4,  200, 347,  18,  256,  0
	.string "GESTEIN$", 12
	pokedex_entry   Graveler,  10, 1050, 256,   2,  256,  0
	.string "URGESTEIN$", 12
	pokedex_entry      Golem,  14, 3000, 256,   3,  296,  2
	.string "FEUERPFERD$", 12
	pokedex_entry     Ponyta,  10,  300, 283,   8,  256,  0
	.string "FEUERPFERD$", 12
	pokedex_entry   Rapidash,  17,  950, 256,   0,  289,  1
	.string "SCHNARCHER$", 12
	pokedex_entry   Slowpoke,  12,  360, 256,  10,  256,  0
	.string "SYMBIOSE$", 12
	pokedex_entry    Slowbro,  16,  785, 256,   6,  296,  2
	.string "MAGNET$", 12
	pokedex_entry  Magnemite,   3,   60, 288,  -9,  256,  0
	.string "MAGNET$", 12
	pokedex_entry   Magneton,  10,  600, 292,   1,  256,  0
	.string "WILDENTE$", 12
	pokedex_entry  Farfetchd,   8,  150, 330,   2,  293,  2
	.string "DUOVOGEL$", 12
	pokedex_entry      Doduo,  14,  392, 256,   3,  257, -1
	.string "TRIVOGEL$", 12
	pokedex_entry     Dodrio,  18,  852, 256,   0,  268,  0
	.string "SEEHUND$", 12
	pokedex_entry       Seel,  11,  900, 297,   8,  256,  0
	.string "SEEHUND$", 12
	pokedex_entry    Dewgong,  17, 1200, 256,   0,  275,  0
	.string "SCHLAMM$", 12
	pokedex_entry     Grimer,   9,  300, 258,  10,  256,  0
	.string "SCHLAMM$", 12
	pokedex_entry        Muk,  12,  300, 256,   2,  256,  0
	.string "MUSCHEL$", 12
	pokedex_entry   Shellder,   3,   40, 675,  24,  256,  0
	.string "MUSCHEL$", 12
	pokedex_entry   Cloyster,  15, 1325, 256,   0,  269,  1
	.string "GAS$", 12
	pokedex_entry     Gastly,  13,    1, 256,   0,  256,  0
	.string "GAS$", 12
	pokedex_entry    Haunter,  16,    1, 256,   2,  293,  2
	.string "SCHATTEN$", 12
	pokedex_entry     Gengar,  15,  405, 256,   2,  302,  2
	.string "FELSNATTER$", 12
	pokedex_entry       Onix,  88, 2100, 256,   1,  515, 14
	.string "HYPNOSE$", 12
	pokedex_entry    Drowzee,  10,  324, 274,   6,  256,  0
	.string "HYPNOSE$", 12
	pokedex_entry      Hypno,  16,  756, 256,   3,  257,  0
	.string "KRABBE$", 12
	pokedex_entry     Krabby,   4,   65, 469,  20,  256,  0
	.string "KNEIFER$", 12
	pokedex_entry    Kingler,  13,  600, 256,   2,  256,  0
	.string "BALL$", 12
	pokedex_entry    Voltorb,   5,  104, 364,  -8,  256,  0
	.string "BALL$", 12
	pokedex_entry  Electrode,  12,  666, 256,   0,  256,  0
	.string "EI$", 12
	pokedex_entry  Exeggcute,   4,   25, 489,  -4,  256,  0
	.string "PALMFRUCHT$", 12
	pokedex_entry  Exeggutor,  20, 1200, 256,   0,  309,  5
	.string "EINSAM$", 12
	pokedex_entry     Cubone,   4,   65, 545,  21,  256,  0
	.string "KNOCHENFAN$", 12
	pokedex_entry    Marowak,  10,  450, 293,  12,  256,  0
	.string "KICKER$", 12
	pokedex_entry  Hitmonlee,  15,  498, 256,   3,  259,  1
	.string "PUNCHER$", 12
	pokedex_entry Hitmonchan,  14,  502, 256,   2,  277,  2
	.string "SCHLECKER$", 12
	pokedex_entry  Lickitung,  12,  655, 256,   4,  256,  0
	.string "GIFTWOLKE$", 12
	pokedex_entry    Koffing,   6,   10, 369,  -1,  256,  0
	.string "GIFTWOLKE$", 12
	pokedex_entry    Weezing,  12,   95, 305,   3,  256,  0
	.string "STACHLER$", 12
	pokedex_entry    Rhyhorn,  10, 1150, 267,   6,  256,  0
	.string "BOHRER$", 12
	pokedex_entry     Rhydon,  19, 1200, 256,   1,  299,  2
	.string "EI$", 12
	pokedex_entry    Chansey,  11,  346, 257,   7,  256,  0
	.string "RANKE$", 12
	pokedex_entry    Tangela,  10,  350, 304,   1,  256,  0
	.string "MUTTERTIER$", 12
	pokedex_entry Kangaskhan,  22,  800, 256,   0,  387,  8
	.string "DRACHE$", 12
	pokedex_entry     Horsea,   4,   80, 399,  -1,  256,  0
	.string "DRACHE$", 12
	pokedex_entry     Seadra,  12,  250, 299,   3,  256,  0
	.string "GOLDFISCH$", 12
	pokedex_entry    Goldeen,   6,  150, 379,   4,  256,  0
	.string "GOLDFISCH$", 12
	pokedex_entry    Seaking,  13,  390, 256,   3,  256,  0
	.string "STERNFORM$", 12
	pokedex_entry     Staryu,   8,  345, 326,   1,  256,  0
	.string "MYSTERIÖS$", 12
	pokedex_entry    Starmie,  11,  800, 301,   3,  256,  0
	.string "SPERRE$", 12
	pokedex_entry     Mrmime,  13,  545, 258,   6,  256,  0
	.string "MANTIS$", 12
	pokedex_entry    Scyther,  15,  560, 256,   1,  293,  2
	.string "HUMANOTYP$", 12
	pokedex_entry       Jynx,  14,  406, 256,   3,  300,  1
	.string "ELEKTRO$", 12
	pokedex_entry Electabuzz,  11,  300, 351,   8,  256,  0
	.string "BRENNER$", 12
	pokedex_entry     Magmar,  13,  445, 277,   5,  256,  0
	.string "KNEIFKÄFER$", 12
	pokedex_entry     Pinsir,  15,  550, 256,   2,  257,  0
	.string "WILDBULLE$", 12
	pokedex_entry     Tauros,  14,  884, 256,   0,  256,  0
	.string "FISCH$", 12
	pokedex_entry   Magikarp,   9,  100, 310,   4,  256,  0
	.string "GRAUSAM$", 12
	pokedex_entry   Gyarados,  65, 2350, 256,   6,  481, 13
	.string "TRANSPORT$", 12
	pokedex_entry     Lapras,  25, 2200, 257,  10,  423,  8
	.string "TRANSFORM$", 12
	pokedex_entry      Ditto,   3,   40, 633,  23,  256,  0
	.string "EVOLUTION$", 12
	pokedex_entry      Eevee,   3,   65, 476,  18,  256,  0
	.string "BLUBBLASE$", 12
	pokedex_entry   Vaporeon,  10,  290, 316,   8,  256,  0
	.string "BLITZ$", 12
	pokedex_entry    Jolteon,   8,  245, 283,   8,  256,  0
	.string "FEUER$", 12
	pokedex_entry    Flareon,   9,  250, 306,  12,  256,  0
	.string "VIRTUELL$", 12
	pokedex_entry    Porygon,   8,  365, 328,  15,  256,  0
	.string "SPIRALE$", 12
	pokedex_entry    Omanyte,   4,   75, 521,  22,  256,  0
	.string "SPIRALE$", 12
	pokedex_entry    Omastar,  10,  350, 307,   7,  256,  0
	.string "PANZERTIER$", 12
	pokedex_entry     Kabuto,   5,  115, 454,  21,  256,  0
	.string "PANZERTIER$", 12
	pokedex_entry   Kabutops,  13,  405, 271,   3,  256,  0
	.string "FOSSIL$", 12
	pokedex_entry Aerodactyl,  18,  590, 256,   0,  302,  4
	.string "TAGTRÄUMER$", 12
	pokedex_entry    Snorlax,  21, 4600, 256,   4,  423, 11
	.string "EIS$", 12
	pokedex_entry   Articuno,  17,  554, 256,   0,  309,  2
	.string "ELEKTRO$", 12
	pokedex_entry     Zapdos,  16,  526, 256,   0,  318,  3
	.string "FLAMME$", 12
	pokedex_entry    Moltres,  20,  600, 270,   0,  387,  8
	.string "DRACHE$", 12
	pokedex_entry    Dratini,  18,   33, 256,   8,  386,  6
	.string "DRACHE$", 12
	pokedex_entry  Dragonair,  40,  165, 256,   0,  411,  5
	.string "DRACHE$", 12
	pokedex_entry  Dragonite,  22, 2100, 256,   0,  309,  4
	.string "GENMUTANT$", 12
	pokedex_entry     Mewtwo,  20, 1220, 256,   0,  309,  4
	.string "NEUE ART$", 12
	pokedex_entry        Mew,   4,   40, 457,  -2,  256,  0
	.string "LAUB$", 12
	pokedex_entry  Chikorita,   9,   64, 512,  20,  256,  0
	.string "LAUB$", 12
	pokedex_entry    Bayleef,  12,  158, 296,   4,  256,  0
	.string "KRÄUTER$", 12
	pokedex_entry   Meganium,  18, 1005, 256,   0,  277,  1
	.string "FEUERMAUS$", 12
	pokedex_entry  Cyndaquil,   5,   79, 539,  21,  256,  0
	.string "VULKAN$", 12
	pokedex_entry    Quilava,   9,  190, 329,  11,  256,  0
	.string "VULKAN$", 12
	pokedex_entry Typhlosion,  17,  795, 256,   0,  268,  1
	.string "GROSSMAUL$", 12
	pokedex_entry   Totodile,   6,   95, 487,  20,  256,  0
	.string "GROSSMAUL$", 12
	pokedex_entry   Croconaw,  11,  250, 378,  13,  256,  0
	.string "GROSSMAUL$", 12
	pokedex_entry Feraligatr,  23,  888, 256,   0,  342,  7
	.string "SPÄHER$", 12
	pokedex_entry    Sentret,   8,   60, 439,  12,  256,  0
	.string "LANGLEIB$", 12
	pokedex_entry     Furret,  18,  325, 346,  11,  256,  0
	.string "EULE$", 12
	pokedex_entry   Hoothoot,   7,  212, 380,  -2,  256,  0
	.string "EULE$", 12
	pokedex_entry    Noctowl,  16,  408, 278,   3,  256,  0
	.string "FÜNF-PUNKT$", 12
	pokedex_entry     Ledyba,  10,  108, 256,   4,  256,  0
	.string "FÜNF-PUNKT$", 12
	pokedex_entry     Ledian,  14,  356, 256,   2,  256,  0
	.string "FADENWURF$", 12
	pokedex_entry   Spinarak,   5,   85, 414,  21,  256,  0
	.string "LANGBEIN$", 12
	pokedex_entry    Ariados,  11,  335, 316,   8,  256,  0
	.string "FLEDERMAUS$", 12
	pokedex_entry     Crobat,  18,  750, 256,   0,  281,  1
	.string "ANGLER$", 12
	pokedex_entry   Chinchou,   5,  120, 424,  -2,  256,  0
	.string "LEUCHTE$", 12
	pokedex_entry    Lanturn,  12,  225, 269,   6,  256,  0
	.string "BABYMAUS$", 12
	pokedex_entry      Pichu,   3,   20, 508,  20,  256,  0
	.string "STERNFORM$", 12
	pokedex_entry     Cleffa,   3,   30, 462,  23,  256,  0
	.string "BALLON$", 12
	pokedex_entry  Igglybuff,   3,   10, 457,  -1,  256,  0
	.string "ZACKENBALL$", 12
	pokedex_entry     Togepi,   3,   15, 507,  23,  256,  0
	.string "FREUDE$", 12
	pokedex_entry    Togetic,   6,   32, 424,  17,  256,  0
	.string "KLEINVOGEL$", 12
	pokedex_entry       Natu,   2,   20, 610,  25,  256,  0
	.string "MYSTIK$", 12
	pokedex_entry       Xatu,  15,  150, 256,   6,  318,  4
	.string "WOLLE$", 12
	pokedex_entry     Mareep,   6,   78, 379,  18,  256,  0
	.string "WOLLE$", 12
	pokedex_entry    Flaaffy,   8,  133, 372,  15,  256,  0
	.string "LEUCHTE$", 12
	pokedex_entry   Ampharos,  14,  615, 256,   4,  256,  0
	.string "BLUME$", 12
	pokedex_entry  Bellossom,   4,   58, 472,  21,  256,  0
	.string "AQUAMAUS$", 12
	pokedex_entry     Marill,   4,   85, 476,  20,  256,  0
	.string "AQUAHASE$", 12
	pokedex_entry  Azumarill,   8,  285, 448,  16,  256,  0
	.string "IMITATION$", 12
	pokedex_entry  Sudowoodo,  12,  380, 305,   8,  256,  0
	.string "FROSCH$", 12
	pokedex_entry   Politoed,  11,  339, 289,   6,  256,  0
	.string "LÖWENZAHN$", 12
	pokedex_entry     Hoppip,   4,    5, 562,  -7,  256,  0
	.string "LÖWENZAHN$", 12
	pokedex_entry   Skiploom,   6,   10, 387,   0,  256,  0
	.string "LÖWENZAHN$", 12
	pokedex_entry   Jumpluff,   8,   30, 418,  -4,  256,  0
	.string "LANGSCHWEIF$", 12
	pokedex_entry      Aipom,   8,  115, 363,   6,  256,  0
	.string "SAMEN$", 12
	pokedex_entry    Sunkern,   3,   18, 541,   0,  256,  0
	.string "SONNE$", 12
	pokedex_entry   Sunflora,   8,   85, 444,  15,  256,  0
	.string "LIBELLE$", 12
	pokedex_entry      Yanma,  12,  380, 274,  -1,  256,  0
	.string "FISCH$", 12
	pokedex_entry     Wooper,   4,   85, 479,  21,  256,  0
	.string "FISCH$", 12
	pokedex_entry   Quagsire,  14,  750, 256,   4,  256,  0
	.string "SONNE$", 12
	pokedex_entry     Espeon,   9,  265, 363,  14,  256,  0
	.string "MONDSCHEIN$", 12
	pokedex_entry    Umbreon,  10,  270, 317,  11,  256,  0
	.string "FINSTERNIS$", 12
	pokedex_entry    Murkrow,   5,   21, 401,  -8,  256,  1
	.string "MONARCH$", 12
	pokedex_entry   Slowking,  20,  795, 256,   0,  309,  5
	.string "KREISCHER$", 12
	pokedex_entry Misdreavus,   7,   10, 407,  -8,  256,  0
	.string "SYMBOL$", 12
	pokedex_entry      Unown,   5,   50, 411,   2,  256,  0
	.string "GEDULD$", 12
	pokedex_entry  Wobbuffet,  13,  285, 274,   4,  256,  0
	.string "LANGHALS$", 12
	pokedex_entry  Girafarig,  15,  415, 281,   1,  256,  0
	.string "BEUTELWURM$", 12
	pokedex_entry     Pineco,   6,   72, 445,   2,  256,  0
	.string "BEUTELWURM$", 12
	pokedex_entry Forretress,  12, 1258, 293,   5,  256,  0
	.string "SCHLANGE$", 12
	pokedex_entry  Dunsparce,  15,  140, 316,  17,  256,  0
	.string "FLUGSKORPI$", 12
	pokedex_entry     Gligar,  11,  648, 350,  -1,  256,  0
	.string "STAHLBOA$", 12
	pokedex_entry    Steelix,  92, 4000, 256,   0,  516, 13
	.string "FEE$", 12
	pokedex_entry   Snubbull,   6,   78, 465,  19,  256,  0
	.string "FEE$", 12
	pokedex_entry   Granbull,  14,  487, 256,   4,  256,  0
	.string "BALLON$", 12
	pokedex_entry   Qwilfish,   5,   39, 430,   0,  256,  0
	.string "KNEIFER$", 12
	pokedex_entry     Scizor,  18, 1180, 278,   1,  256,  0
	.string "SCHIMMEL$", 12
	pokedex_entry    Shuckle,   6,  205, 485,  18,  256,  0
	.string "EINZELHORN$", 12
	pokedex_entry  Heracross,  15,  540, 256,   0,  256,  0
	.string "STICHKLAUE$", 12
	pokedex_entry    Sneasel,   9,  280, 413,  -3,  256,  0
	.string "KLEINBÄR$", 12
	pokedex_entry  Teddiursa,   6,   88, 455,  19,  256,  0
	.string "SCHLÄFER$", 12
	pokedex_entry   Ursaring,  18, 1258, 256,   0,  256,  0
	.string "LAVA$", 12
	pokedex_entry     Slugma,   7,  350, 329,  15,  256,  0
	.string "LAVA$", 12
	pokedex_entry   Magcargo,   8,  550, 332,  15,  256,  0
	.string "FERKEL$", 12
	pokedex_entry     Swinub,   4,   65, 324,  20,  256,  0
	.string "SCHWEIN$", 12
	pokedex_entry  Piloswine,  11,  558, 306,  10,  256,  0
	.string "KORALLE$", 12
	pokedex_entry    Corsola,   6,   50, 410,  15,  256,  0
	.string "HOCHDRUCK$", 12
	pokedex_entry   Remoraid,   6,  120, 316,   4,  256,  0
	.string "HOCHDRUCK$", 12
	pokedex_entry  Octillery,   9,  285, 296,   3,  256,  0
	.string "LIEFERANT$", 12
	pokedex_entry   Delibird,   9,  160, 293,  11,  256,  0
	.string "FLUGROCHEN$", 12
	pokedex_entry    Mantine,  21, 2200, 256,   0,  342,  7
	.string "FLUGSTAHL$", 12
	pokedex_entry   Skarmory,  17,  505, 256,   0,  271,  1
	.string "HADES$", 12
	pokedex_entry   Houndour,   6,  108, 393,  16,  256,  0
	.string "HADES$", 12
	pokedex_entry   Houndoom,  14,  350, 256,   4,  256,  0
	.string "DRACHE$", 12
	pokedex_entry    Kingdra,  18, 1520, 256,   0,  287,  0
	.string "LANGRÜSSEL$", 12
	pokedex_entry     Phanpy,   5,  335, 465,  21,  256,  0
	.string "PANZERTIER$", 12
	pokedex_entry    Donphan,  11, 1200, 313,   9,  256,  0
	.string "VIRTUELL$", 12
	pokedex_entry   Porygon2,   6,  325, 320,  17,  256,  0
	.string "VIELENDER$", 12
	pokedex_entry   Stantler,  14,  712, 256,   0,  256,  0
	.string "MALER$", 12
	pokedex_entry   Smeargle,  12,  580, 287,   5,  256,  0
	.string "RACKER$", 12
	pokedex_entry    Tyrogue,   7,  210, 292,   9,  256,  0
	.string "KOPFSTAND$", 12
	pokedex_entry  Hitmontop,  14,  480, 256,   2,  257,  0
	.string "KUSS$", 12
	pokedex_entry   Smoochum,   4,   60, 440,  20,  256,  0
	.string "ELEKTRO$", 12
	pokedex_entry     Elekid,   6,  235, 363,  14,  256,  0
	.string "GLUTHERD$", 12
	pokedex_entry      Magby,   7,  214, 284,  13,  256,  0
	.string "MILCHKUH$", 12
	pokedex_entry    Miltank,  12,  755, 280,   5,  256,  0
	.string "FREUDE$", 12
	pokedex_entry    Blissey,  15,  468, 256,   4,  310,  3
	.string "DONNER$", 12
	pokedex_entry     Raikou,  19, 1780, 256,   0,  345,  7
	.string "VULKAN$", 12
	pokedex_entry      Entei,  21, 1980, 259,   0,  345,  7
	.string "POLARLICHT$", 12
	pokedex_entry    Suicune,  20, 1870, 269,   0,  345,  7
	.string "FELSHAUT$", 12
	pokedex_entry   Larvitar,   6,  720, 472,  18,  256,  0
	.string "HARTSCHALE$", 12
	pokedex_entry    Pupitar,  12, 1520, 292,   8,  256,  0
	.string "PANZERTIER$", 12
	pokedex_entry  Tyranitar,  20, 2020, 256,   0,  345,  7
	.string "TAUCHER$", 12
	pokedex_entry      Lugia,  52, 2160, 256,   0,  721, 19
	.string "REGENBOGEN$", 12
	pokedex_entry       HoOh,  38, 1990, 256,   0,  610, 17
	.string "ZEITREISE$", 12
	pokedex_entry     Celebi,   6,   50, 393, -10,  256,  0
	.string "WALDGECKO$", 12
	pokedex_entry    Treecko,   5,   50, 541,  19,  256,  0
	.string "WALDGECKO$", 12
	pokedex_entry    Grovyle,   9,  216, 360,   5,  256,  0
	.string "DSCHUNGEL$", 12
	pokedex_entry   Sceptile,  17,  522, 256,  -1,  275,  2
	.string "KÜKEN$", 12
	pokedex_entry    Torchic,   4,   25, 566,  19,  256,  0
	.string "KLEINHAHN$", 12
	pokedex_entry  Combusken,   9,  195, 343,   5,  256,  0
	.string "GROSSBRAND$", 12
	pokedex_entry   Blaziken,  19,  520, 256,   0,  301,  4
	.string "LEHMHÜPFER$", 12
	pokedex_entry     Mudkip,   4,   76, 535,  20,  256,  0
	.string "LEHMHÜPFER$", 12
	pokedex_entry  Marshtomp,   7,  280, 340,   7,  256,  0
	.string "LEHMHÜPFER$", 12
	pokedex_entry   Swampert,  15,  819, 256,   0,  256,  0
	.string "BISS$", 12
	pokedex_entry  Poochyena,   5,  136, 481,  19,  256,  0
	.string "BISS$", 12
	pokedex_entry  Mightyena,  10,  370, 362,   9,  256,  0
	.string "KLEINDACHS$", 12
	pokedex_entry  Zigzagoon,   4,  175, 560,  22,  256,  0
	.string "SPRINTER$", 12
	pokedex_entry    Linoone,   5,  325, 321,   7,  256,  0
	.string "WURM$", 12
	pokedex_entry    Wurmple,   3,   36, 711,  24,  256,  0
	.string "KOKON$", 12
	pokedex_entry    Silcoon,   6,  100, 431,  19,  256,  0
	.string "FALTER$", 12
	pokedex_entry  Beautifly,  10,  284, 298,  -1,  256,  0
	.string "KOKON$", 12
	pokedex_entry    Cascoon,   7,  115, 391,  20,  256,  0
	.string "GIFTMOTTE$", 12
	pokedex_entry     Dustox,  12,  316, 269,   1,  256,  0
	.string "WASSERLINSE$", 12
	pokedex_entry      Lotad,   5,   26, 406,  19,  256,  0
	.string "FROHMUT$", 12
	pokedex_entry     Lombre,  12,  325, 277,   9,  256,  0
	.string "SORGLOS$", 12
	pokedex_entry   Ludicolo,  15,  550, 256,   0,  268, -1
	.string "EICHELNUSS$", 12
	pokedex_entry     Seedot,   5,   40, 472,  20,  256,  0
	.string "HINTERLIST$", 12
	pokedex_entry    Nuzleaf,  10,  280, 299,  10,  256,  0
	.string "VERSCHLAGEN$", 12
	pokedex_entry    Shiftry,  13,  596, 290,   4,  256,  0
	.string "SCHWÄLBLEIN$", 12
	pokedex_entry    Taillow,   3,   23, 465,  21,  256,  0
	.string "SCHWALBE$", 12
	pokedex_entry    Swellow,   7,  198, 428,  15,  256,  0
	.string "SEEMÖWE$", 12
	pokedex_entry    Wingull,   6,   95, 295,  -2,  256,  0
	.string "WASSERVOGEL$", 12
	pokedex_entry   Pelipper,  12,  280, 288,   1,  256,  0
	.string "GEFÜHL$", 12
	pokedex_entry      Ralts,   4,   66, 457,  -3,  256,  0
	.string "EMOTION$", 12
	pokedex_entry     Kirlia,   8,  202, 354,   0,  256,  0
	.string "UMARMUNG$", 12
	pokedex_entry  Gardevoir,  16,  484, 256,   0,  256,  0
	.string "WASSERGEHER$", 12
	pokedex_entry    Surskit,   5,   17, 375,  17,  256,  0
	.string "AUGE$", 12
	pokedex_entry Masquerain,   8,   36, 378,   8,  256,  0
	.string "PILZ$", 12
	pokedex_entry  Shroomish,   4,   45, 513,  22,  256,  0
	.string "PILZ$", 12
	pokedex_entry    Breloom,  12,  392, 324,   6,  256,  0
	.string "FAULPELZ$", 12
	pokedex_entry    Slakoth,   8,  240, 291,  16,  256,  0
	.string "WILDAFFE$", 12
	pokedex_entry   Vigoroth,  14,  465, 301,   2,  256,  0
	.string "MÜSSIG$", 12
	pokedex_entry    Slaking,  20, 1305, 256,   2,  300,  1
	.string "VORBEREITER$", 12
	pokedex_entry    Nincada,   5,   55, 405,  21,  256,  0
	.string "NINJA$", 12
	pokedex_entry    Ninjask,   8,  120, 383,  -9,  256,  0
	.string "HÄUTUNG$", 12
	pokedex_entry   Shedinja,   8,   12, 372,  -8,  256,  0
	.string "FLÜSTER$", 12
	pokedex_entry    Whismur,   6,  163, 373,  17,  256,  0
	.string "LAUTHALS$", 12
	pokedex_entry    Loudred,  10,  405, 356,  10,  256,  0
	.string "KRACH$", 12
	pokedex_entry    Exploud,  15,  840, 284,   1,  256,  0
	.string "COURAGE$", 12
	pokedex_entry   Makuhita,  10,  864, 256,  10,  256,  0
	.string "ARMWURF$", 12
	pokedex_entry   Hariyama,  23, 2538, 256,   0,  343,  7
	.string "GEPUNKTET$", 12
	pokedex_entry    Azurill,   2,   20, 603,  23,  256,  0
	.string "KOMPASS$", 12
	pokedex_entry   Nosepass,  10,  970, 256,   9,  289,  3
	.string "KÄTZCHEN$", 12
	pokedex_entry     Skitty,   6,  110, 492,  19,  256,  0
	.string "EINGEBILDET$", 12
	pokedex_entry   Delcatty,  11,  326, 322,  10,  256,  0
	.string "FINSTERNIS$", 12
	pokedex_entry    Sableye,   5,  110, 451,  17,  256,  0
	.string "SCHWINDLER$", 12
	pokedex_entry     Mawile,   6,  115, 466,  17,  256,  0
	.string "EISENPANZER$", 12
	pokedex_entry       Aron,   4,  600, 419,  23,  256,  0
	.string "EISENPANZER$", 12
	pokedex_entry     Lairon,   9, 1200, 275,  12,  256,  0
	.string "EISENPANZER$", 12
	pokedex_entry     Aggron,  21, 3600, 256,  -1,  350,  6
	.string "MEDITATION$", 12
	pokedex_entry   Meditite,   6,  112, 465,  17,  256,  0
	.string "MEDITATION$", 12
	pokedex_entry   Medicham,  13,  315, 298,   5,  256,  0
	.string "GEWITTER$", 12
	pokedex_entry  Electrike,   6,  152, 290,  15,  256,  0
	.string "ENTLADUNG$", 12
	pokedex_entry  Manectric,  15,  402, 256,   3,  257,  0
	.string "JUBEL$", 12
	pokedex_entry     Plusle,   4,   42, 515,  -9,  256,  0
	.string "JUBEL$", 12
	pokedex_entry      Minun,   4,   42, 512,  -7,  256,  0
	.string "LIBELLE$", 12
	pokedex_entry    Volbeat,   7,  177, 442,  16,  256,  0
	.string "LIBELLE$", 12
	pokedex_entry   Illumise,   6,  177, 572,  19,  256,  0
	.string "DORN$", 12
	pokedex_entry    Roselia,   3,   20, 677,  20,  256,  0
	.string "MAGEN$", 12
	pokedex_entry     Gulpin,   4,  103, 593,  23,  256,  0
	.string "GIFTBEUTEL$", 12
	pokedex_entry     Swalot,  17,  800, 256,   6,  345,  3
	.string "GNADENLOS$", 12
	pokedex_entry   Carvanha,   8,  208, 362,   0,  256,  0
	.string "BRUTAL$", 12
	pokedex_entry   Sharpedo,  18,  888, 256,   0,  317,  3
	.string "KUGELWAL$", 12
	pokedex_entry    Wailmer,  20, 1300, 256,   2,  493,  0
	.string "FLUTWAL$", 12
	pokedex_entry    Wailord, 145, 3980, 256,   0, 1352, 18
	.string "TAUBHEIT$", 12
	pokedex_entry      Numel,   7,  240, 342,  17,  256,  0
	.string "AUSBRUCH$", 12
	pokedex_entry   Camerupt,  19, 2200, 256,   7,  345,  6
	.string "KOHLE$", 12
	pokedex_entry    Torkoal,   5,  804, 390,   9,  256,  0
	.string "SPRUNGFEDER$", 12
	pokedex_entry     Spoink,   7,  306, 423,  17,  256,  0
	.string "MANIPULATOR$", 12
	pokedex_entry    Grumpig,   9,  715, 358,  10,  256,  0
	.string "PUNKT-PANDA$", 12
	pokedex_entry     Spinda,  11,   50, 321,   4,  256,  0
	.string "AMEISENLÖWE$", 12
	pokedex_entry   Trapinch,   7,  150, 298,  17,  256,  0
	.string "VIBRATION$", 12
	pokedex_entry    Vibrava,  11,  153, 370,  11,  256,  0
	.string "MYSTIK$", 12
	pokedex_entry     Flygon,  20,  820, 256,   0,  268,  1
	.string "KAKTUS$", 12
	pokedex_entry     Cacnea,   4,  513, 455,  20,  256,  0
	.string "VOGELSCHOCK$", 12
	pokedex_entry   Cacturne,  13,  774, 327,   5,  256,  0
	.string "WOLLVOGEL$", 12
	pokedex_entry     Swablu,   4,   12, 422,  -8,  256,  0
	.string "SUMMSEL$", 12
	pokedex_entry    Altaria,  11,  206, 327,   0,  256,  0
	.string "FRETTKATZ$", 12
	pokedex_entry   Zangoose,  13,  403, 256,   3,  256,  0
	.string "REISSZAHN$", 12
	pokedex_entry    Seviper,  27,  525, 275,   7,  256,  0
	.string "METEORIT$", 12
	pokedex_entry   Lunatone,  10, 1680, 300,   3,  256,  0
	.string "METEORIT$", 12
	pokedex_entry    Solrock,  12, 1540, 328,   0,  256,  0
	.string "BARTHAAR$", 12
	pokedex_entry   Barboach,   4,   19, 581,  -3,  256,  0
	.string "BARTHAAR$", 12
	pokedex_entry   Whiscash,   9,  236, 317,   1,  256,  0
	.string "GROBIAN$", 12
	pokedex_entry   Corphish,   6,  115, 484,  19,  256,  0
	.string "SCHLINGEL$", 12
	pokedex_entry  Crawdaunt,  11,  328, 365,   9,  256,  0
	.string "LEHMPUPPE$", 12
	pokedex_entry     Baltoy,   5,  215, 457,  21,  256,  0
	.string "LEHMPUPPE$", 12
	pokedex_entry    Claydol,  15, 1080, 256,   3,  280,  1
	.string "SEEANEMONE$", 12
	pokedex_entry     Lileep,  10,  238, 305,   8,  256,  0
	.string "RANKFÜSSER$", 12
	pokedex_entry    Cradily,  15,  604, 267,   0,  256,  0
	.string "KREBSSENIOR$", 12
	pokedex_entry    Anorith,   7,  125, 296,   4,  256,  0
	.string "SCHILD$", 12
	pokedex_entry    Armaldo,  15,  682, 312,   3,  271,  0
	.string "FISCH$", 12
	pokedex_entry     Feebas,   6,   74, 423,  -4,  256,  0
	.string "ZARTHEIT$", 12
	pokedex_entry    Milotic,  62, 1620, 256,   0,  360,  7
	.string "WETTER$", 12
	pokedex_entry   Castform,   3,    8, 435,  -5,  256,  0
	.string "FARBENSPIEL$", 12
	pokedex_entry    Kecleon,  10,  220, 316,  10,  256,  0
	.string "PUPPE$", 12
	pokedex_entry    Shuppet,   6,   23, 440,  20,  256,  0
	.string "MARIONETTE$", 12
	pokedex_entry    Banette,  11,  125, 262,   9,  256,  0
	.string "REQUIEM$", 12
	pokedex_entry    Duskull,   8,  150, 406,  -4,  256,  0
	.string "WINK$", 12
	pokedex_entry   Dusclops,  16,  306, 256,   3,  299,  1
	.string "OBST$", 12
	pokedex_entry    Tropius,  20, 1000, 256,   0,  344,  7
	.string "WINDSPIEL$", 12
	pokedex_entry   Chimecho,   6,   10, 505,   0,  256,  0
	.string "DESASTER$", 12
	pokedex_entry      Absol,  12,  470, 301,   3,  256,  0
	.string "STRAHLEKIND$", 12
	pokedex_entry     Wynaut,   6,  140, 484,  19,  256,  0
	.string "SCHNEEHUT$", 12
	pokedex_entry    Snorunt,   7,  168, 380,  15,  256,  0
	.string "ANTLITZ$", 12
	pokedex_entry     Glalie,  15, 2565, 256,   3,  344,  0
	.string "APPLAUS$", 12
	pokedex_entry     Spheal,   8,  395, 315,  16,  256,  0
	.string "SPIELBALL$", 12
	pokedex_entry     Sealeo,  11,  876, 338,  13,  256,  0
	.string "EISBRECHER$", 12
	pokedex_entry    Walrein,  14, 1506, 316,   4,  256,  0
	.string "MUSCHEL$", 12
	pokedex_entry   Clamperl,   4,  525, 691,  22,  256,  0
	.string "TIEFSEE$", 12
	pokedex_entry    Huntail,  17,  270, 307,   1,  256,  0
	.string "SÜDSEE$", 12
	pokedex_entry   Gorebyss,  18,  226, 278,   5,  256,  0
	.string "BESTAND$", 12
	pokedex_entry  Relicanth,  10,  234, 316,   7,  256,  0
	.string "RENDEZVOUS$", 12
	pokedex_entry    Luvdisc,   6,   87, 371,   2,  256,  0
	.string "STEINHAUPT$", 12
	pokedex_entry      Bagon,   6,  421, 448,  18,  256,  0
	.string "DURCHSTEHER$", 12
	pokedex_entry    Shelgon,  11, 1105, 311,  12,  256,  0
	.string "DRACHE$", 12
	pokedex_entry  Salamence,  15, 1026, 256,   0,  256,  0
	.string "EISENKUGEL$", 12
	pokedex_entry     Beldum,   6,  952, 414,  -1,  256,  0
	.string "EISENKLAUE$", 12
	pokedex_entry     Metang,  12, 2025, 256,   6,  256,  0
	.string "EISENFUSS$", 12
	pokedex_entry  Metagross,  16, 5500, 256,   4,  447,  9
	.string "STEINGIPFEL$", 12
	pokedex_entry   Regirock,  17, 2300, 256,   2,  309,  1
	.string "EISBERG$", 12
	pokedex_entry     Regice,  18, 1750, 256,   0,  301,  2
	.string "EISEN$", 12
	pokedex_entry  Registeel,  19, 2050, 256,   0,  359,  6
	.string "ÄON$", 12
	pokedex_entry     Latias,  14,  400, 304,   3,  256,  0
	.string "ÄON$", 12
	pokedex_entry     Latios,  20,  600, 256,   0,  294,  3
	.string "SEEGRÜNDLER$", 12
	pokedex_entry     Kyogre,  45, 3520, 256,   0,  614, 13
	.string "KONTINENT$", 12
	pokedex_entry    Groudon,  35, 9500, 256,   0,  515, 14
	.string "HIMMELHOCH$", 12
	pokedex_entry   Rayquaza,  70, 2065, 256,   0,  448, 12
	.string "WÜNSCHER$", 12
	pokedex_entry    Jirachi,   3,   11, 608,  -8,  256,  0
	.string "DNS$", 12
	pokedex_entry     Deoxys,  17,  608, 256,   0,  290,  2
