SlateportCity_EventObjects:: @ 837F7AC
	object_event 1, EVENT_OBJ_GFX_FAT_MAN, 0, 21, 11, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, SlateportCity_EventScript_14BBD6, 0
	object_event 2, EVENT_OBJ_GFX_MAN_1, 0, 35, 27, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 1, 0, 0, 0, SlateportCity_EventScript_14BBF3, 0
	object_event 3, EVENT_OBJ_GFX_BOY_4, 0, 15, 13, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 2, 0, 0, SlateportCity_EventScript_14BBB5, 0
	object_event 4, EVENT_OBJ_GFX_WOMAN_5, 0, 26, 29, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SlateportCity_EventScript_14BC14, 0
	object_event 5, EVENT_OBJ_GFX_VAR_0, 0, 31, 27, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, 0, 0, SlateportCity_EventScript_14BD3A, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 6, EVENT_OBJ_GFX_COOK, 0, 5, 43, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SlateportCity_EventScript_14BB3F, 0
	object_event 7, EVENT_OBJ_GFX_OLD_WOMAN_2, 0, 20, 37, 3, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, SlateportCity_EventScript_14BB60, 0
	object_event 8, EVENT_OBJ_GFX_GIRL_1, 0, 8, 42, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, SlateportCity_EventScript_14BB81, 0
	object_event 9, EVENT_OBJ_GFX_CAMERAMAN, 0, 29, 13, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 0, 0, SlateportCity_EventScript_14C017, FLAG_HIDE_GABBY_AND_TY_SLATEPORT
	object_event 10, EVENT_OBJ_GFX_REPORTER_F, 0, 28, 14, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, 0, 0, SlateportCity_EventScript_14C020, FLAG_HIDE_GABBY_AND_TY_SLATEPORT
	object_event 11, EVENT_OBJ_GFX_SCIENTIST_1, 0, 28, 13, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SlateportCity_EventScript_14BEBC, FLAG_HIDE_STERN_SLATEPORT
	object_event 12, EVENT_OBJ_GFX_SAILOR, 0, 35, 36, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SlateportCity_EventScript_14BCE2, 0
	object_event 13, EVENT_OBJ_GFX_SAILOR, 0, 28, 46, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 1, 0, 0, 0, SlateportCity_EventScript_14BCEB, 0
	object_event 14, EVENT_OBJ_GFX_WOMAN_2, 0, 9, 50, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 1, 0, 0, SlateportCity_EventScript_14BCF4, 0
	object_event 15, EVENT_OBJ_GFX_MAN_4, 0, 16, 46, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, SlateportCity_EventScript_14BCFD, 0
	object_event 16, EVENT_OBJ_GFX_SCHOOL_KID_M, 0, 12, 18, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, SlateportCity_EventScript_14BD06, 0
	object_event 17, EVENT_OBJ_GFX_MANIAC, 0, 8, 24, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 1, 0, 0, SlateportCity_EventScript_14BCB8, 0
	object_event 18, EVENT_OBJ_GFX_WOMAN_7, 0, 15, 31, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, SlateportCity_EventScript_14BCD9, 0
	object_event 19, EVENT_OBJ_GFX_VAR_1, 0, 30, 27, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SlateportCity_EventScript_14BD51, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 20, EVENT_OBJ_GFX_VAR_1, 0, 29, 27, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SlateportCity_EventScript_14BD68, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 21, EVENT_OBJ_GFX_MART_EMPLOYEE, 0, 6, 38, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, SlateportCity_EventScript_14BE20, 0
	object_event 22, EVENT_OBJ_GFX_MART_EMPLOYEE, 0, 5, 51, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SlateportCity_EventScript_14BDF2, 0
	object_event 23, EVENT_OBJ_GFX_MAN_6, 0, 34, 51, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SlateportCity_EventScript_14C029, 0
	object_event 24, EVENT_OBJ_GFX_WOMAN_7, 0, 4, 47, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SlateportCity_EventScript_14BAE0, 0
	object_event 25, EVENT_OBJ_GFX_MART_EMPLOYEE, 0, 11, 47, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, SlateportCity_EventScript_14BE9A, FLAG_HIDE_TM_SALESMAN_SLATEPORT
	object_event 26, EVENT_OBJ_GFX_MAN_3, 0, 5, 47, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, SlateportCity_EventScript_14BAB6, 0
	object_event 27, EVENT_OBJ_GFX_VAR_1, 0, 22, 27, 3, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 0, 0, SlateportCity_EventScript_14BD7F, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 28, EVENT_OBJ_GFX_VAR_1, 0, 23, 27, 3, MOVEMENT_TYPE_FACE_UP, 1, 1, 0, 0, SlateportCity_EventScript_14BD96, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 29, EVENT_OBJ_GFX_VAR_1, 0, 24, 27, 3, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 0, 0, SlateportCity_EventScript_14BDAD, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 30, EVENT_OBJ_GFX_VAR_1, 0, 21, 26, 3, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 0, 0, SlateportCity_EventScript_14BDC4, FLAG_HIDE_EVIL_TEAM_SLATEPORT
	object_event 31, EVENT_OBJ_GFX_VAR_1, 0, 20, 26, 3, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 0, 0, SlateportCity_EventScript_14BDDB, FLAG_HIDE_EVIL_TEAM_SLATEPORT

SlateportCity_MapWarps:: @ 837FA94
	warp_def 19, 19, 0, 0, MAP_SLATEPORT_CITY_POKEMON_CENTER_1F
	warp_def 13, 26, 0, 0, MAP_SLATEPORT_CITY_MART
	warp_def 26, 38, 0, 0, MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F
	warp_def 10, 12, 0, 0, MAP_SLATEPORT_CITY_CONTEST_LOBBY
	warp_def 4, 26, 0, 0, MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB
	warp_def 30, 26, 0, 0, MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F
	warp_def 5, 19, 0, 0, MAP_SLATEPORT_CITY_HOUSE1
	warp_def 31, 26, 0, 1, MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F
	warp_def 28, 12, 0, 0, MAP_SLATEPORT_CITY_HARBOR
	warp_def 40, 7, 0, 2, MAP_SLATEPORT_CITY_HARBOR
	warp_def 21, 44, 0, 0, MAP_SLATEPORT_CITY_HOUSE2

SlateportCity_MapBGEvents:: @ 837FAEC
	bg_event 8, 19, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BCAF
	bg_event 20, 19, 0, BG_EVENT_PLAYER_FACING_NORTH, SlateportCity_EventScript_1A00EA
	bg_event 21, 19, 0, BG_EVENT_PLAYER_FACING_NORTH, SlateportCity_EventScript_1A00EA
	bg_event 14, 26, 0, BG_EVENT_PLAYER_FACING_NORTH, SlateportCity_EventScript_1A00E1
	bg_event 24, 12, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC91
	bg_event 15, 26, 0, BG_EVENT_PLAYER_FACING_NORTH, SlateportCity_EventScript_1A00E1
	bg_event 14, 51, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC88
	bg_event 26, 26, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC76
	bg_event 16, 22, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC7F
	bg_event 8, 26, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC6D
	bg_event 7, 13, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC33
	bg_event 23, 38, 0, BG_EVENT_PLAYER_FACING_ANY, SlateportCity_EventScript_14BC3C

SlateportCity_MapEvents:: @ 837FB7C
	map_events SlateportCity_EventObjects, SlateportCity_MapWarps, 0x0, SlateportCity_MapBGEvents
