Route124_DivingTreasureHuntersHouse_Text_19F416:: @ 819F416
	.string "Ich bin der SCHATZTAUCHER!\p"
	.string "Ich bin der Typ, der in der Tiefsee\n"
	.string "taucht und nach Schätzen am Meeres-\l"
	.string "grund sucht.$"

Route124_DivingTreasureHuntersHouse_Text_19F48F:: @ 819F48F
	.string "Sag, hast du SCHERBEN antiker\n"
	.string "Werkzeuge gesehen?$"

Route124_DivingTreasureHuntersHouse_Text_19F4D1:: @ 819F4D1
	.string "Du hast keinerlei Schätze für mich...\p"
	.string "Wenn du Stücke findest, besonders\n"
	.string "PURPURSTÜCKE, tausche sie mit mir!$"

Route124_DivingTreasureHuntersHouse_Text_19F544:: @ 819F544
	.string "Oh, hey! Das... Das ist eine\n"
	.string "Scherbe! Genau die suche ich!\p"
	.string "Oh, du musst unbedingt mit mir\n"
	.string "tauschen! Ich gebe dir etwas\l"
	.string "Gutes dafür!$"

Route124_DivingTreasureHuntersHouse_Text_19F5C5:: @ 819F5C5
	.string "Was möchtest du tauschen?$"

Route124_DivingTreasureHuntersHouse_Text_19F5E0:: @ 819F5E0
	.string "Du tauschst dein {STR_VAR_1} gegen\n"
	.string "mein {STR_VAR_2}?$"

Route124_DivingTreasureHuntersHouse_Text_19F606:: @ 819F606
	.string "Das ist ein guter Tausch!\n"
	.string "Setze es wohl überlegt ein!$"

Route124_DivingTreasureHuntersHouse_Text_19F629:: @ 819F629
	.string "Möchtest du noch etwas tauschen?$"

Route124_DivingTreasureHuntersHouse_Text_19F64E:: @ 819F64E
	.string "Hups, dein BEUTEL ist voll.\n"
	.string "Schaffe Platz, mein Freund!$"

Route124_DivingTreasureHuntersHouse_Text_19F686:: @ 819F686
	.string "Nein? Das ist niederschmetternd.\n"
	.string "Wenn du deine Meinung änderst, ich\l"
	.string "bin hier!$"

Route124_DivingTreasureHuntersHouse_Text_19F6C5:: @ 819F6C5
	.string "Gesuchtes Item         Item zum Tausch\n"
	.string " PURPURSTÜCK      {LEFT_ARROW}{RIGHT_ARROW} FEUERSTEIN\p"
	.string "Gesuchtes Item         Item zum Tausch\n"
	.string " GELBSTÜCK          {LEFT_ARROW}{RIGHT_ARROW} DONNERSTEIN\p"
	.string "Gesuchtes Item         Item zum Tausch\n"
	.string " INDIGOSTÜCK        {LEFT_ARROW}{RIGHT_ARROW} WASSERSTEIN\p"
	.string "Gesuchtes Item         Item zum Tausch\n"
	.string " GRÜNSTÜCK           {LEFT_ARROW}{RIGHT_ARROW} BLATTSTEIN$"
