VerdanturfTown_ContestLobby_Text_177D6C:: @ 8177D6C
	.string "Ich bin hineingegangen und habe mich\n"
	.string "ein bisschen in der WETTBEWERBSHALLE\l"
	.string "umgeschaut.\p"
	.string "Wenn man da oben auf der riesigen Bühne\n"
	.string "steht... Das muss Aufregung pur sein!$"

VerdanturfTown_ContestLobby_Text_177DEC:: @ 8177DEC
	.string "Oh, die Liebe zu meinen POKéMON...\n"
	.string "Diese Anziehungskraft...\p"
	.string "Hups!\n"
	.string "Das war gar nicht für deine Ohren\l"
	.string "bestimmt! Nun, wie auch immer...\p"
	.string "Wenn du an einem WETTBEWERB teil-\n"
	.string "nimmst, probiere mal diese Attacke aus.$"

VerdanturfTown_ContestLobby_Text_177E98:: @ 8177E98
	.string "Meine Gefühle für POKéMON...\n"
	.string "Oh, POKéMON ziehen mich so an...$"

VerdanturfTown_ContestLobby_Text_177ECD:: @ 8177ECD
	.string "An welchem WETTBEWERB planst du teil-\n"
	.string "zunehmen?\p"
	.string "Wenn du an einem COOLNESS-WETTBE-\n"
	.string "WERB teilnehmen willst, muss das\l"
	.string "POKéMON cool sein!\p"
	.string "Wähle immer das POKéMON aus, das am\n"
	.string "besten zur Kategorie des WETTBE-\l"
	.string "WERBS passt und die passenden\l"
	.string "Attacken kennt.\p"
	.string "Das ist das Wesentliche!$"
