UnknownString_81C426C: @ 81C426C
	.string "Ich bin sehr interessiert an einer\n"
	.string "großen {STR_VAR_1}. Je größer, desto\l"
	.string "besser.\p"
	.string "Was? Du hast ein {STR_VAR_1}?\n"
	.string "B-b-bitte zeig es mir!!!$"

UnknownString_81C42CE: @ 81C42CE
	.string "Oh, du liebe Zeit, ist das groß!\n"
	.string "Das ist eine große {STR_VAR_1}!\p"
	.string "Danke, dass du es mir gezeigt hast.\n"
	.string "Dies ist mein Dankeschön!$"

UnknownString_81C432C: @ 81C432C
	.string "{PLAYER} erhält {STR_VAR_2}.$"

UnknownString_81C4340: @ 81C4340
	.string "Wie? Wo? Was?\n"
	.string "Dein BEUTEL ist megavoll.$"

UnknownString_81C4360: @ 81C4360
	.string "Hmm... Ich habe schon größere\n"
	.string "{STR_VAR_1} als dieses gesehen!$"

UnknownString_81C438C: @ 81C438C
	.string "Och, das ist schon ganz ansehnlich...\n"
	.string "Aber das ist kein {STR_VAR_1}!$"

UnknownString_81C43C2: @ 81C43C2
	.string "Du hast kein großes {STR_VAR_1}?\n"
	.string "Das ist aber schade...\p"
	.string "Sobald du ein großes {STR_VAR_1}\n"
	.string "besitzt, zeig es mir bitte.$"

UnknownString_81C4417: @ 81C4417
	.string "Das größte {STR_VAR_1} in der Ge-\n"
	.string "schichte! Der {STR_VAR_3} cm Koloss\l"
	.string "von {STR_VAR_2}!$"
