gTextBard_BardTesting: @ 81B0A83
	.string "BARD testing!$"

gTextBard_HiImTheBard:: @ 81B0A91
	.string "Hi, I’m the BARD.\n"
	.string "Would you like to hear my song?$"

gTextBard_OhYouveLeftMe:: @ 81B0AC3
	.string "Oh...\n"
	.string "You’ve left me feeling the blues...$"

gTextBard_OhWhatAMovingSong:: @ 81B0AED
	.string "Oh, what a moving song...\n"
	.string "I wish I could play it for others...$"

gTextBard_SoHowDoYouLikeMySong:: @ 81B0B2C
	.string "So?\n"
	.string "How do you like my song?\p"
	.string "But I’m none too happy about the\n"
	.string "lyrics.\p"
	.string "How would you like to write some new\n"
	.string "lyrics for me?$"

gTextBard_OhYouveLeftMe2:: @ 81B0BA6
	.string "Oh...\n"
	.string "You’ve left me feeling the blues...$"

gTextBard_ThankYouKindly:: @ 81B0BD0
	.string "Thank you kindly!\n"
	.string "Let me sing it for you.$"

gTextBard_WasThatHowYouWanted:: @ 81B0BFA
	.string "Was that how you wanted your song\n"
	.string "to go?$"

gTextBard_OkayThatsIt:: @ 81B0C23
	.string "Okay! That’s it, then.\n"
	.string "I’ll sing this song for a while.$"
