Route102_Text_1A16B6:: @ 81A16B6
	.string "Das ist weicher Lehmboden.$"

Route102_Text_1A16CD:: @ 81A16CD
	.string "Das ist weicher Lehmboden.\n"
	.string "Möchtest du eine BEERE pflanzen?$"

Route102_Text_1A16FB:: @ 81A16FB
	.string "{PLAYER} pflanzt eine\n"
	.string "{STR_VAR_1}BEERE in den Lehmboden.$"

Route102_Text_1A172C:: @ 81A172C
	.string "Eine {STR_VAR_1}BEERE wurde\n"
	.string "hier gepflanzt.$"

Route102_Text_1A174B:: @ 81A174B
	.string "{STR_VAR_1} blüht auf.$"

Route102_Text_1A175C:: @ 81A175C
	.string "Die {STR_VAR_1}pflanze wächst.$"

Route102_Text_1A177D:: @ 81A177D
	.string "Diese {STR_VAR_1}blumen sind\n"
	.string "{STR_VAR_2}.$"

Route102_Text_1A179F:: @ 81A179F
	.string "wunderschön$"

Route102_Text_1A17B0:: @ 81A17B0
	.string "zierlich$"

Route102_Text_1A17B7:: @ 81A17B7
	.string "hübsch$"

Route102_Text_1A17C0:: @ 81A17C0
	.string "{STR_VAR_2} {STR_VAR_1}BEERE/N!\p"
	.string "Möchtest du die {STR_VAR_1}BEERE/N\n"
	.string "pflücken?$"

Route102_Text_1A17FD:: @ 81A17FD
	.string "{PLAYER} pflückt die {STR_VAR_2}\n"
	.string "{STR_VAR_1}BEERE/N.$"

Route102_Text_1A181A:: @ 81A181A
	.string "{PLAYER} packt die {STR_VAR_1}BEERE/N\n"
	.string "in die BEERENTASCHE des BEUTELS.\p"
	.string "Der Boden ist wieder weich und lehmig.$"

Route102_Text_1A1881:: @ 81A1881
	.string "Die BEERENTASCHE des BEUTELS ist voll.\p"
	.string "Die {STR_VAR_1}BEERE/N können nicht\n"
	.string "mitgenommen werden.$"

Route102_Text_1A18C5:: @ 81A18C5
	.string "{PLAYER} pflückt keine\n"
	.string "{STR_VAR_1}BEEREN.$"

Route102_Text_1A18E6:: @ 81A18E6
	.string "Möchtest du die {STR_VAR_1} mit der\n"
	.string "WAILMERKANNE gießen?$"

Route102_Text_1A1912:: @ 81A1912
	.string "{PLAYER} gießt die {STR_VAR_1}.$"

Route102_Text_1A1925:: @ 81A1925
	.string "Die Pflanze scheint sich zu freuen.$"

Route102_Text_1A1946:: @ 81A1946
	.string "!$"
