Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 3, 6, 27, 13, 5, 9
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 11, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 10, 6, 18, 13, 14, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 11, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 10, 6, 18, 13, 14, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 5, 6, 25, 13, 7, 9
	.braille "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstRelicanthLastWailord:
	brailleformat 3, 0, 27, 19, 5, 3
	.braille "FIRST COMES\n"
	.braille "RELICANTH.\n"
	.braille "LAST COMES\n"
	.braille "WAILORD.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 6, 0, 22, 19, 8, 3
	.braille "IN THIS\n"
	.braille "CAVE WE\n"
	.braille "HAVE\n"
	.braille "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 4, 2, 26, 17, 6, 5
	.braille "WE OWE ALL\n"
	.braille "TO THE\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 5, 3
	.braille "BUT, WE\n"
	.braille "SEALED THE\n"
	.braille "POKEMON\n"
	.braille "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 1, 6, 29, 13, 3, 9
	.braille "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 4, 0, 26, 19, 6, 3
	.braille "THOSE WITH\n"
	.braille "COURAGE,\n"
	.braille "THOSE WITH\n"
	.braille "HOPE.$"

SealedChamber_InnerRoom_Braille_1C549B:
	brailleformat 2, 0, 28, 19, 4, 3
	.braille "OPEN A DOOR.\n"
	.braille "AN ETERNAL\n"
	.braille "POKEMON\n"
	.braille "WAITS.$"

DesertRuins_Braille_UseStrength:
	brailleformat 0, 0, 29, 19, 2, 3
	.braille "RIGHT, RIGHT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "STRENGTH.$"

IslandCave_Braille_WaitTwoMinutes:
	brailleformat 3, 0, 27, 19, 5, 3
	.braille "STOP AND\n"
	.braille "WAIT. WAIT\n"
	.braille "FOR TIME TO\n"
	.braille "PASS TWICE.$"

AncientTomb_Braille_AimToTheSkyInTheMiddle:
	brailleformat 0, 0, 29, 19, 1, 3
	.braille "WITH NEW TIME,\n"
	.braille "HOPE AND LOVE,\n"
	.braille "AIM TO THE SKY\n"
	.braille "IN THE MIDDLE.$"
