gTextGiddy_Introduction:: @ 81B092A
	.string "I’m GIDDY!\n"
	.string "I have a scintillating story for you!\p"
	.string "Would you like to hear my story?$"

gTextGiddy_YouveDeflatedMe:: @ 81B097C
	.string "Oh...\n"
	.string "You’ve deflated me...$"

gTextGiddy_AlsoIWasThinking:: @ 81B0998
	.string "Also, I was thinking...$"

gTextGiddy_ByeBye:: @ 81B09B0
	.string "That’s about it, I think...\p"
	.string "We should chat again!\n"
	.string "Bye-bye!$"
