gTextGiddy_Introduction:: @ 81B092A
	.string "Ich bin MÄRCHEN-MAN! Ich habe eine sehr\n"
	.string "geistreiche Geschichte für dich!\p"
	.string "Soll ich sie dir erzählen?$"

gTextGiddy_YouveDeflatedMe:: @ 81B097C
	.string "Oh...\n"
	.string "Du hast mir die Luft rausgelassen...$"

gTextGiddy_AlsoIWasThinking:: @ 81B0998
	.string "Und ich war in Gedanken vertieft...$"

gTextGiddy_ByeBye:: @ 81B09B0
	.string "Das wäre alles, glaube ich...\p"
	.string "Wir sollten bald wieder ein Schwätzchen\n"
	.string "halten! Tschüss!$"
