gGiftRibbonDescriptionPart1_2003RegionalTourney:
	.string "REGIONALTURNIER 2003$"

gGiftRibbonDescriptionPart2_Champion:
	.string "BAND des CHAMPS$"

gGiftRibbonDescriptionPart1_2003NationalTourney:
	.string "NATIONALTURNIER 2003$"

gGiftRibbonDescriptionPart1_2003GlobalCup:
	.string "WELTPOKAL 2003$"

gGiftRibbonDescriptionPart2_RunnerUp:
	.string "BAND für Platzierungen$"

gGiftRibbonDescriptionPart2_Semifinalist:
	.string "BAND für Halbfinalisten$"

gGiftRibbonDescriptionPart1_2004RegionalTourney:
	.string "REGIONALTURNIER 2004$"

gGiftRibbonDescriptionPart1_2004NationalTourney:
	.string "NATIONALTURNIER 2004$"

gGiftRibbonDescriptionPart1_2004GlobalCup:
	.string "WELTPOKAL 2004$"

gGiftRibbonDescriptionPart1_2005RegionalTourney:
	.string "REGIONALTURNIER 2005$"

gGiftRibbonDescriptionPart1_2005NationalTourney:
	.string "NATIONALTURNIER 2005$"

gGiftRibbonDescriptionPart1_2005GlobalCup:
	.string "WELTPOKAL 2005$"

gGiftRibbonDescriptionPart1_PokemonBattleCup:
	.string "POKéMON-KAMPF-POKAL$"

gGiftRibbonDescriptionPart2_Participation:
	.string "Teilnehmer-BAND$"

gGiftRibbonDescriptionPart1_PokemonLeague:
	.string "POKéMON LIGA$"

gGiftRibbonDescriptionPart1_AdvanceCup:
	.string "TALENTPOKAL$"

gGiftRibbonDescriptionPart1_PokemonTournament:
	.string "POKéMON-Turnier$"

gGiftRibbonDescriptionPart2_Participation2:
	.string "Teilnehmer-BAND$"

gGiftRibbonDescriptionPart1_PokemonEvent:
	.string "POKéMON-Wettkampf$"

gGiftRibbonDescriptionPart1_PokemonFestival:
	.string "POKéMON-Festival$"

gGiftRibbonDescriptionPart1_DifficultyClearing:
	.string "Schw.-Grad-Abschl.$"

gGiftRibbonDescriptionPart2_Commemorative:
	.string "Gedenk-BAND$"

gGiftRibbonDescriptionPart1_ClearingAllDifficulties:
	.string "BAND für erf. Abschluss$"

gGiftRibbonDescriptionPart2_ClearingAllDifficulties:
	.string "aller Schwierigk.-Grade.$"

gGiftRibbonDescriptionPart1_100StraightWin:
	.string "100. Sieg in Folge$"

gGiftRibbonDescriptionPart1_DarknessTower:
	.string "APOKELIPSE-TURM fertig$"

gGiftRibbonDescriptionPart1_RedTower:
	.string "ROTER TURM fertig$"

gGiftRibbonDescriptionPart1_BlackironTower:
	.string "EISERNER TURM fertig$"

gGiftRibbonDescriptionPart1_FinalTower:
	.string "FINAL-TURM-Abschluss$"

gGiftRibbonDescriptionPart1_LegendMaking:
	.string "Legendäres$"

gGiftRibbonDescriptionPart1_PokemonCenterTokyo:
	.string "POKéMON-CENTER TOKIO$"

gGiftRibbonDescriptionPart1_PokemonCenterOsaka:
	.string "POKéMON-CENTER OSAKA$"

gGiftRibbonDescriptionPart1_PokemonCenterNagoya:
	.string "POKéMON-CENTER NAGOYA$"

gGiftRibbonDescriptionPart1_PokemonCenterNY:
	.string "POKéMON-CENTER N. Y.$"

gGiftRibbonDescriptionPart1_SummerHolidays:
	.string "Sommerferien-BAND$"

gGiftRibbonDescriptionPart2_EmptyString:
	.string "$"

gGiftRibbonDescriptionPart1_WinterHolidays:
	.string "Weihnachtsferien-BAND$"

gGiftRibbonDescriptionPart1_SpringHolidays:
	.string "Osterferien-BAND$"

gGiftRibbonDescriptionPart1_Evergreen:
	.string "Evergreen-BAND$"

gGiftRibbonDescriptionPart1_SpecialHoliday:
	.string "Sonderurlaubs-BAND$"

gGiftRibbonDescriptionPart1_HardWorker:
	.string "Fleiß-BAND$"

gGiftRibbonDescriptionPart1_LotsOfFriends:
	.string "Beliebtheits-BAND$"

gGiftRibbonDescriptionPart1_FullOfEnergy:
	.string "Energie-BAND$"

gGiftRibbonDescriptionPart1_LovedPokemon:
	.string "Ein Gedenk-BAND für ein$"

gGiftRibbonDescriptionPart2_LovedPokemon:
	.string "beliebtes POKéMON.$"

gGiftRibbonDescriptionPart1_LoveForPokemon:
	.string "Ein BAND für POKéMON-$"

gGiftRibbonDescriptionPart2_LoveForPokemon:
	.string "Freunde.$"

	.align 2
gGiftRibbonDescriptions:: @ 83E158C
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonTournament,     gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonEvent,          gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonFestival,       gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_DifficultyClearing,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_ClearingAllDifficulties, gGiftRibbonDescriptionPart2_ClearingAllDifficulties
	.4byte gGiftRibbonDescriptionPart1_100StraightWin,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_DarknessTower,         gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_RedTower,              gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_BlackironTower,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_FinalTower,            gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_LegendMaking,          gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterTokyo,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterOsaka,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNagoya,   gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNY,       gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_SummerHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_WinterHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpringHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_Evergreen,             gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpecialHoliday,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_HardWorker,            gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LotsOfFriends,         gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_FullOfEnergy,          gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LovedPokemon,          gGiftRibbonDescriptionPart2_LovedPokemon
	.4byte gGiftRibbonDescriptionPart1_LoveForPokemon,        gGiftRibbonDescriptionPart2_LoveForPokemon
