MauvilleCity_PokemonCenter_1F_Text_1B0C5B:: @ 81B0C5B
	.string "Hey, yo! Man nennt mich TRENDWIG. Ich\n"
	.string "zeige dir, was hip ist und abgeht.$"

MauvilleCity_PokemonCenter_1F_Text_1B0CA7:: @ 81B0CA7
	.string "Aber, hey, ich habe dir doch schon ge-\n"
	.string "zeigt, was hip ist und abgeht.\p"
	.string "Ich will das auch anderen mitteilen.$"

MauvilleCity_PokemonCenter_1F_Text_1B0D11:: @ 81B0D11
	.string "Aber, hey, ich habe dir doch schon ge-\n"
	.string "zeigt, was hip ist und abgeht.\p"
	.string "Ich habe nichts mehr in petto.$"

MauvilleCity_PokemonCenter_1F_Text_1B0D75:: @ 81B0D75
	.string "Hast du schon von\n"
	.string "“{STR_VAR_1}” gehört?\p"
	.string "Was das heißt? Ähäm...\n"
	.string "Frag mal deinen Papi oder deine Mami, ja?$"
