gTextHipster_TheyCallMeTheHipster:: @ 81B0C5B
	.string "Hey, yo! They call me the HIPSTER.\n"
	.string "I’ll teach you what’s hip and happening.$"

gTextHipster_TaughtYouAlready:: @ 81B0CA7
	.string "But, hey, I taught you what’s hip and\n"
	.string "happening already.\p"
	.string "I’d like to spread the good word to\n"
	.string "other folks.$"

gTextHipster_YouAlreadyKnowALot:: @ 81B0D11
	.string "But, hey, you already know a lot about\n"
	.string "what’s hip and happening.\p"
	.string "I’ve got nothing new to teach you!$"

gTextHipster_HaveYouHeardAbout:: @ 81B0D75
	.string "Hey, have you heard about\n"
	.string "“{STR_VAR_1}”?\p"
	.string "What’s it mean? Well...\n"
	.string "Ask your daddy or mommy, okay?$"
