gLandmarkName_FlowerShop::
	.string "BLUMENLADEN$"

gLandmarkName_PetalburgWoods::
	.string "BLÜTENBURGWALD$"

gLandmarkName_MrBrineysCottage::
	.string "MR. BRACKS HÜTTE$"

gLandmarkName_AbandonedShip::
	.string "SCHIFFSWRACK$"

gLandmarkName_SeashoreHouse::
	.string "STRANDHAUS$"

gLandmarkName_SlateportBeach::
	.string "GRAPHITPORTSTRAND$"

gLandmarkName_CyclingRoad::
	.string "RADWEG$"

gLandmarkName_NewMauville::
	.string "NEU MALVENFROH$"

gLandmarkName_TrickHouse::
	.string "RÄTSELHAUS$"

gLandmarkName_OldLadysRestShop::
	.string "HOTEL DER ALTEN DAME$"

gLandmarkName_Desert::
	.string "WÜSTE$"

gLandmarkName_WinstrateFamily::
	.string "FAMILIE SIHGERS$"

gLandmarkName_CableCar::
	.string "SEILBAHN$"

gLandmarkName_GlassWorkshop::
	.string "GLASWERKSTATT$"

gLandmarkName_WeatherInstitute::
	.string "KLIMA-INSTITUT$"

gLandmarkName_MeteorFalls::
	.string "METEORFÄLLE$"

gLandmarkName_TunnelersRestHouse::
	.string "BERGRASTHAUS$"

gLandmarkName_RusturfTunnel::
	.string "METAFLURTUNNEL$"

gLandmarkName_PokemonDayCare::
	.string "POKéMON-PENSION$"

gLandmarkName_SafariZoneEntrance::
	.string "EINGANG SAFARI-ZONE$"

gLandmarkName_MtPyre::
	.string "PYROBERG$"

gLandmarkName_ShoalCave::
	.string "KÜSTENHÖHLE$"

gLandmarkName_SeafloorCavern::
	.string "TIEFSEEHÖHLE$"

gLandmarkName_GraniteCave::
	.string "GRANITHÖHLE$"

gLandmarkName_OceanCurrent::
	.string "MEERESSTRÖMUNG$"

gLandmarkName_LanettesHouse::
	.string "LANETTES HAUS$"

gLandmarkName_FieryPath::
	.string "FEURIGER PFAD$"

gLandmarkName_JaggedPass::
	.string "STEILPASS$"

gLandmarkName_SkyPillar::
	.string "HIMMELTURM$"

gLandmarkName_BerryMastersHouse::
	.string "BEERENMEISTER-VILLA$"

gLandmarkName_IslandCave::
	.string "INSELHÖHLE$"

gLandmarkName_DesertRuins::
	.string "WÜSTENRUINE$"

gLandmarkName_ScorchedSlab::
	.string "SONNENGROTTE$"

gLandmarkName_AncientTomb::
	.string "GRABMAL$"

gLandmarkName_SealedChamber::
	.string "SIEGELKAMMER$"

gLandmarkName_FossilManiacsHouse::
	.string "FOSSILMANIACS HAUS$"

gLandmarkName_HuntersHouse::
	.string "HAUS DES TAUCHERS$"
