LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:: @ 81C4B5E
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers visiting our DEPARTMENT\n"
	.string "STORE get to draw a POKéMON LOTO\l"
	.string "TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:: @ 81C4C6A
	.string "Please come back tomorrow.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:: @ 81C4C85
	.string "Please do visit us again.$"

UnknownString_81C4C9F: @ 81C4C9F
	.string "Please pick a LOTO TICKET.\n"
	.string "... ... ...$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:: @ 81C4CC6
	.string "Please pick a LOTO TICKET.\n"
	.string "...{PAUSE}{0x39} ...{PAUSE}{0x39} ...{PAUSE}{0x39}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:: @ 81C4CF6
	.string "The LOTO TICKET number is {STR_VAR_1}.\p"
	.string "I need to run a check on this number\n"
	.string "to see if it matches any of your\l"
	.string "POKéMON's ID numbers. Please wait.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:: @ 81C4D7D
	.string "Congratulations!\p"
	.string "The ID number of your team's\n"
	.string "{STR_VAR_1} matches your LOTO TICKET's\l"
	.string "number!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:: @ 81C4DD1
	.string "Congratulations!\p"
	.string "The ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your LOTO TICKET's\l"
	.string "number!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:: @ 81C4E27
	.string "I'm sorry.\n"
	.string "None of the numbers matched.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:: @ 81C4E4F
	.string "Two digits matched, so you win the\n"
	.string "third prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:: @ 81C4E92
	.string "Three digits matched, so you win the\n"
	.string "second prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:: @ 81C4ED8
	.string "Four digits matched, so you win the\n"
	.string "first prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:: @ 81C4F1C
	.string "Oh, my goodness, all five digits matched!\p"
	.string "You've won the jackpot prize!\n"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:: @ 81C4F77
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:: @ 81C4FCC
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "This is the prize we've been holding\n"
	.string "for you.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:: @ 81C501C
	.string "Please do visit again.$"
