MtPyre_Summit_Text_1B5CFD:: @ 81B5CFD
	.string "Ich werde dir zeigen, wie unheimlich\n"
	.string "gruselig TEAM MAGMA sein kann!$"

MtPyre_Summit_Text_1B5D30:: @ 81B5D30
	.string "Und du glaubst wirklich, du bist der\n"
	.string "Stärke TEAM MAGMAS gewachsen?!?$"

MtPyre_Summit_Text_1B5D6D:: @ 81B5D6D
	.string "Ja, du bist ganz schön stark...\n"
	.string "Aber wir sind viele...$"

MtPyre_Summit_Text_1B5DA2:: @ 81B5DA2
	.string "Was ist los mit dir? Was kann ein kleines\n"
	.string "Kind schon gegen uns ausrichten?$"

MtPyre_Summit_Text_1B5DDB:: @ 81B5DDB
	.string "Bumms...\n"
	.string "Zu stark... Viel zu stark...$"

MtPyre_Summit_Text_1B5DF1:: @ 81B5DF1
	.string "Du weißt doch gar nichts! Misch dich\n"
	.string "besser nicht in unsere Sachen ein!$"

MtPyre_Summit_Text_1B5E27:: @ 81B5E27
	.string "Hey, ich kenne dich vom SCHLOTBERG!\n"
	.string "Der Tag der Abrechnung ist gekommen!$"

MtPyre_Summit_Text_1B5E60:: @ 81B5E60
	.string "Aaaaargh!\n"
	.string "Schon wieder von einem Kind besiegt...$"

MtPyre_Summit_Text_1B5E84:: @ 81B5E84
	.string "Ach, das spielt keine Rolle.\n"
	.string "Wir haben Zeit herausgeschlagen!\p"
	.string "Der BOSS müsste mittlerweile haben, was\n"
	.string "er besorgen wollte!$"

MtPyre_Summit_Text_1B5EEC:: @ 81B5EEC
	.string "MARC: Nicht du schon wieder!\p"
	.string "Du bist uns ja sehr schnell auf die Spur\n"
	.string "gekommen, aber es ist schon zu spät.\p"
	.string "Die BLAUE KUGEL, die sich oben\n"
	.string "auf dem PYROBERG befindet...\l"
	.string "Ich, MARC, sage, sie gehört mir!\p"
	.string "Hahaha... Jetzt werden meine\n"
	.string "Visionen Wirklichkeit!\p"
	.string "Los, Mannschaft!\n"
	.string "GRAPHITPORT CITY heißt unser Ziel.$"

MtPyre_Summit_Text_1B5FE6:: @ 81B5FE6
	.string "Oh, neeeeiiinnn...\n"
	.string "Das darf nicht wahr sein!\p"
	.string "Wie konnten sie nur an die\n"
	.string "BLAUE KUGEL gelangen?!?\p"
	.string "Die BLAUE und die ROTE KUGEL dürfen nie\n"
	.string "getrennt sein. Sie gehören zusammen!!!\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "Hmm...\p"
	.string "Gut! Nimm die verbliebene\n"
	.string "ROTE KUGEL an dich.\p"
	.string "Bitte folge diesem Schurken und bring\n"
	.string "die KUGEL zurück!$"

MtPyre_Summit_Text_1B60F9:: @ 81B60F9
	.string "Die ROTE KUGEL, die dir anvertraut\n"
	.string "wurde, und die gestohlene\l"
	.string "BLAUE KUGEL...\p"
	.string "Sie dürfen niemals getrennt werden...\n"
	.string "Sonst passiert etwas Schreckliches!$"

MtPyre_Summit_Text_1B617B:: @ 81B617B
	.string "So...\n"
	.string "GROUDON wurde erweckt...\p"
	.string "Von der wundersamen KUGEL sagt\n"
	.string "man, dass sie das wütende GROUDON\l"
	.string "beruhigt.\p"
	.string "Es handelt sich um die ROTE KUGEL,\n"
	.string "die du bei dir trägst...\p"
	.string "Diese ROTE KUGEL fand man in der\n"
	.string "URZEITHÖHLE in XENEROVILLE...\p"
	.string "Es gibt anscheinend eine Verbindung\n"
	.string "zwischen GROUDON und der\l"
	.string "URZEITHÖHLE...$"

MtPyre_Summit_Text_1B6283:: @ 81B6283
	.string "Dieser Mann - er hat die BLAUE KUGEL\n"
	.string "zurückgebracht.\p"
	.string "Bringst du die ROTE KUGEL auch an ihren\n"
	.string "angestammten Platz zurück?$"

MtPyre_Summit_Text_1B62E7:: @ 81B62E7
	.string "Was soll das?\p"
	.string "Wenn das Gleichgewicht nicht wiederher-\n"
	.string "gestellt wird, weiß niemand, was\l"
	.string "passieren wird!\p"
	.string "Du wirst die ROTE KUGEL an ihren Platz\n"
	.string "zurückbringen, ja?$"

UnknownString_81B6374: @ 81B6374
	.string "{PLAYER} gibt der alten Frau die\n"
	.string "ROTE KUGEL.$"

MtPyre_Summit_Text_1B639C:: @ 81B639C
	.string "Ja...\n"
	.string "Die beiden KUGELN müssen hier bleiben.\p"
	.string "So soll es sein, zum Wohle aller in HOENN.$"

MtPyre_Summit_Text_1B63F8:: @ 81B63F8
	.string "Der Geist des Landes...\p"
	.string "Das, so heißt es, ist GROUDON in\n"
	.string "POKéMON-Gestalt...\p"
	.string "So wie wir und die POKéMON leben, ist\n"
	.string "auch dieses Land lebendig...\p"
	.string "GROUDON hat uns das gelehrt.$"

MtPyre_Summit_Text_1B64B3:: @ 81B64B3
	.string "Am PYROBERG legen wir die Geister der\n"
	.string "POKéMON, die von uns gegangen sind, zur\l"
	.string "Ruhe...\p"
	.string "Von hier aus hat man einen Ausblick über\n"
	.string "die ganze Region von HOENN...\p"
	.string "Die körperlosen Geister der POKéMON\n"
	.string "finden hier ihre Ruhe...\p"
	.string "Es ist Fügung, dass du jetzt hier bist...\p"
	.string "Möchtest du meine Geschichte hören?\n"
	.string "Eine lange, sehr alte Geschichte der\l"
	.string "HOENN-Region?$"

MtPyre_Summit_Text_1B65D6:: @ 81B65D6
	.string "Es geschah vor langer, langer Zeit...\p"
	.string "Die Welt erbebte unter der Auseinander-\n"
	.string "setzung der POKéMON des Landes mit den\l"
	.string "POKéMON des Meeres...\p"
	.string "Die POKéMON des Landes erschufen\n"
	.string "Berge und Kontinente...\p"
	.string "Die POKéMON des Meeres erschufen hohe\n"
	.string "Wellen und tiefe Meeresbecken...\p"
	.string "Das Duell wütete ohne absehbares Ende.\p"
	.string "Die Welt wurde von erbarmungslosen\n"
	.string "Stürmen und unglaublichen Infernos\l"
	.string "heimgesucht.\p"
	.string "Die BLAUE und die ROTE KUGEL setzten\n"
	.string "schließlich diesem Kampf ein Ende.\p"
	.string "Licht strahlte von den beiden KUGELN\n"
	.string "und beruhigte die Kontrahenten.\p"
	.string "Die beruhigten POKéMON verbargen sich\n"
	.string "in den Tiefen des Meeres und der Erde,\l"
	.string "und eines Tages verschwanden sie.$"

MtPyre_Summit_Text_1B6823:: @ 81B6823
	.string "Ich verstehe...\n"
	.string "Nun, das ist auch in Ordnung...$"

MtPyre_Summit_Text_1B6848:: @ 81B6848
	.string "MARC: Du...\n"
	.string "Du hast GROUDON aufgehalten...\p"
	.string "Das sollte mich nicht überraschen...\p"
	.string "Nun habe ich verstanden, dass es nicht\n"
	.string "an den Menschen ist, das Gleichgewicht\l"
	.string "zwischen Land und Meer zu stören...\p"
	.string "Daher bin ich hier, um die\n"
	.string "BLAUE KUGEL zurückzubringen...\p"
	.string "Ich glaube nicht, dass wir uns wieder\n"
	.string "sehen werden... Leb wohl...$"
