gMoveDescription_Pound: @ 83BC680
	.string "Ein Hieb mit den Vorder-\n"
	.string "beinen oder dem Schweif.$"

gMoveDescription_KarateChop: @ 83BC6A6
	.string "Gute Möglichkeit, einen\n"
	.string "Volltreffer zu landen.$"

gMoveDescription_DoubleSlap: @ 83BC6D8
	.string "Trifft den Gegner 2 - 5-mal\n"
	.string "hintereinander.$"

gMoveDescription_CometPunch: @ 83BC6FF
	.string "Trifft den Gegner 2 - 5-mal\n"
	.string "hintereinander.$"

gMoveDescription_MegaPunch: @ 83BC728
	.string "Ein unglaublich kräftiger\n"
	.string "Hieb.$"

gMoveDescription_PayDay: @ 83BC755
	.string "Wirft Münzen auf Gegner.\n"
	.string "Geld wird erstattet.$"

gMoveDescription_FirePunch: @ 83BC788
	.string "Schlag, der dem Gegner evtl.\n"
	.string "Verbrennungen zufügt.$"

gMoveDescription_IcePunch: @ 83BC7AD
	.string "Ein Schlag, der den Gegner\n"
	.string "evtl. einfriert.$"

gMoveDescription_ThunderPunch: @ 83BC7D3
	.string "Schlag, der den Gegner evtl.\n"
	.string "paralysiert.$"

gMoveDescription_Scratch: @ 83BC803
	.string "Der Gegner wird mit\n"
	.string "scharfen Klauen zerkratzt.$"

gMoveDescription_ViceGrip: @ 83BC827
	.string "Umklammert den Gegner mit\n"
	.string "großen, kräftigen Zangen.$"

gMoveDescription_Guillotine: @ 83BC856
	.string "Kräftige Scheren-Attacke.\n"
	.string "Führt evtl. zum K.O.$"

gMoveDescription_RazorWind: @ 83BC888
	.string "Eine Attacke, die auf 2\n"
	.string "Runden basiert.$"

gMoveDescription_SwordsDance: @ 83BC8BC
	.string "Erhöht den Angriffs-Wert\n"
	.string "drastisch.$"

gMoveDescription_Cut: @ 83BC8E9
	.string "Trifft den Gegner mit\n"
	.string "Klauen, Scheren o. ä.$"

gMoveDescription_Gust: @ 83BC916
	.string "Trifft den Gegner mit Wind-\n"
	.string "stoß durch Flügelschlag.$"

gMoveDescription_WingAttack: @ 83BC94F
	.string "Trifft den Gegner mit weit\n"
	.string "gespreizten Flügeln.$"

gMoveDescription_Whirlwind: @ 83BC977
	.string "Weht Gegner weg und be-\n"
	.string "endet den Kampf in Wildnis.$"

gMoveDescription_Fly: @ 83BC9A9
	.string "Steigt empor in der 1. Runde\n"
	.string "und trifft Gegner in der 2.$"

gMoveDescription_Bind: @ 83BC9E1
	.string "Umklammert und trifft den\n"
	.string "Gegner 2 - 5-mal.$"

gMoveDescription_Slam: @ 83BCA0E
	.string "Schlag mit einem langen\n"
	.string "Schweif, einer Ranke o. ä.$"

gMoveDescription_VineWhip: @ 83BCA39
	.string "Peitschenähnlicher Schlag\n"
	.string "mit Ranken.$"

gMoveDescription_Stomp: @ 83BCA67
	.string "Stampfen mit Fuß. Gegner\n"
	.string "schreckt evtl. zurück.$"

gMoveDescription_DoubleKick: @ 83BCA9E
	.string "Doppeltritt. Der Gegner\n"
	.string "wird zweimal getroffen.$"

gMoveDescription_MegaKick: @ 83BCAD2
	.string "Ein extrem heftiger Tritt.$"

gMoveDescription_JumpKick: @ 83BCB01
	.string "Sprung-Tritt. Selbstschä-\n"
	.string "digung bei Misserfolg.$"

gMoveDescription_RollingKick: @ 83BCB36
	.string "Schneller Tritt aus der\n"
	.string "Drehung.$"

gMoveDescription_SandAttack: @ 83BCB5F
	.string "Senkt Genauigkeit des Geg-\n"
	.string "ners durch Sand.$"

gMoveDescription_Headbutt: @ 83BCB97
	.string "Rammt den Gegner und lässt\n"
	.string "ihn evtl. zurückschrecken.$"

gMoveDescription_HornAttack: @ 83BCBC2
	.string "Spießt den Gegner mit\n"
	.string "spitzen Hörnern auf.$"

gMoveDescription_FuryAttack: @ 83BCBE1
	.string "Spießt den Gegner 2 - 5-mal\n"
	.string "mit spitzen Hörnern auf.$"

gMoveDescription_HornDrill: @ 83BCC12
	.string "K.O.-Attacke, die ein Horn\n"
	.string "als Bohrer einsetzt.$"

gMoveDescription_Tackle: @ 83BCC45
	.string "Trifft den Gegner mit vollem\n"
	.string "Körpereinsatz.$"

gMoveDescription_BodySlam: @ 83BCC6F
	.string "Körper-Ramme, kann\n"
	.string "Paralyse hervorrufen.$"

gMoveDescription_Wrap: @ 83BCC9A
	.string "Umwickelt Gegner 2 - 5-mal\n"
	.string "mit Ranken o. ä.$"

gMoveDescription_TakeDown: @ 83BCCD3
	.string "Rücksichtslose Attacke,\n"
	.string "mit Selbstschädigung.$"

gMoveDescription_Thrash: @ 83BCD06
	.string "Attacke in 2 bis 3 Runden,\n"
	.string "die Anwender verwirrt.$"

gMoveDescription_DoubleEdge: @ 83BCD38
	.string "Lebensgefährlicher Angriff\n"
	.string "mit Selbstschädigung.$"

gMoveDescription_TailWhip: @ 83BCD68
	.string "Hieb mit dem Schweif, senkt\n"
	.string "die VERT. des Gegners.$"

gMoveDescription_PoisonSting: @ 83BCD92
	.string "Angriff mit Widerhaken,\n"
	.string "kann Gegner vergiften.$"

gMoveDescription_Twineedle: @ 83BCDC4
	.string "Stacheln an den Vorderbei-\n"
	.string "nen treffen Gegner 2-mal.$"

gMoveDescription_PinMissile: @ 83BCDF0
	.string "Spitze Nadeln treffen den\n"
	.string "Gegner 2 - 5-mal.$"

gMoveDescription_Leer: @ 83BCE1D
	.string "Gegners VERT.-Wert wird\n"
	.string "durch Blick gesenkt.$"

gMoveDescription_Bite: @ 83BCE4D
	.string "Beißt zu und lässt den Geg-\n"
	.string "ner evtl. zurückschrecken.$"

gMoveDescription_Growl: @ 83BCE7C
	.string "Knurren, das den ANGR.-Wert\n"
	.string "des Gegners senkt.$"

gMoveDescription_Roar: @ 83BCEA6
	.string "Verjagt den Gegner und be-\n"
	.string "endet den Kampf in Wildnis.$"

gMoveDescription_Sing: @ 83BCECC
	.string "Ein Lied, das den Gegner\n"
	.string "in tiefen Schlaf versetzt.$"

gMoveDescription_Supersonic: @ 83BCEFF
	.string "Ausstoß bizarrer Schallwel-\n"
	.string "len. Verwirrt Gegner evtl.$"

gMoveDescription_SonicBoom: @ 83BCF33
	.string "Schockwellen. Richten immer\n"
	.string "20 KP Schaden an.$"

gMoveDescription_Disable: @ 83BCF6A
	.string "Psycho-Attacke. Blockiert\n"
	.string "eine Attacke des Gegners.$"

gMoveDescription_Acid: @ 83BCF97
	.string "Versprüht ätzende Flüssig-\n"
	.string "keit, senkt evtl. VERT.$"

gMoveDescription_Ember: @ 83BCFC6
	.string "Schwache Feuer-Attacke.\n"
	.string "Verbrennt Gegner evtl.$"

gMoveDescription_Flamethrower: @ 83BCFF2
	.string "Starke Feuer-Attacke.\n"
	.string "Verbrennt Gegner evtl.$"

gMoveDescription_Mist: @ 83BD022
	.string "Nebel, der die Änderung der\n"
	.string "Werte verhindert.$"

gMoveDescription_WaterGun: @ 83BD054
	.string "Der Gegner wird mit Wasser\n"
	.string "bespritzt.$"

gMoveDescription_HydroPump: @ 83BD075
	.string "Spritzt Wasser mit\n"
	.string "Hochdruck auf den Gegner.$"

gMoveDescription_Surf: @ 83BD0A3
	.string "Eine riesige Welle bricht\n"
	.string "über den Gegner herein.$"

gMoveDescription_IceBeam: @ 83BD0D9
	.string "Gegner wird von Eisstrahl\n"
	.string "getroffen, friert evtl. ein.$"

gMoveDescription_Blizzard: @ 83BD10D
	.string "Ein Schneesturm, der den\n"
	.string "Gegner einfrieren kann.$"

gMoveDescription_Psybeam: @ 83BD140
	.string "Feuert einen Strahl ab, der\n"
	.string "Gegner verwirren kann.$"

gMoveDescription_BubbleBeam: @ 83BD16F
	.string "Versprüht Blasen, die den\n"
	.string "INIT.-Wert evtl. senken.$"

gMoveDescription_AuroraBeam: @ 83BD19F
	.string "Regenbogenfarbener Strahl,\n"
	.string "senkt evtl. ANGR.-Wert.$"

gMoveDescription_HyperBeam: @ 83BD1D3
	.string "Starke Attacke. Angreifer\n"
	.string "setzt eine Runde aus.$"

gMoveDescription_Peck: @ 83BD209
	.string "Greift Gegner mit dem\n"
	.string "Schnabel an.$"

gMoveDescription_DrillPeck: @ 83BD233
	.string "Attacke, bei der der Schna-\n"
	.string "bel als Bohrer dient.$"

gMoveDescription_Submission: @ 83BD26A
	.string "Rücksichtsloser Rempler. \n"
	.string "Schädigt auch Angreifer.$"

gMoveDescription_LowKick: @ 83BD299
	.string "Tritt, der massigen Gegnern\n"
	.string "mehr Schaden zufügt.$"

gMoveDescription_Counter: @ 83BD2CB
	.string "Kontert physischen Tref-\n"
	.string "fer mit doppelter Kraft.$"

gMoveDescription_SeismicToss: @ 83BD2FE
	.string "Richtet Schaden gemäß\n"
	.string "Level d. Angreifers an.$"

gMoveDescription_Strength: @ 83BD32D
	.string "Erzeugt enorme Kraft und\n"
	.string "rammt den Gegner.$"

gMoveDescription_Absorb: @ 83BD358
	.string "Attacke, die die Hälfte des\n"
	.string "Schadens absorbiert.$"

gMoveDescription_MegaDrain: @ 83BD38A
	.string "Attacke, die die Hälfte des\n"
	.string "Schadens absorbiert.$"

gMoveDescription_LeechSeed: @ 83BD3BC
	.string "Gegner wird bepflanzt und\n"
	.string "verliert jede Runde KP.$"

gMoveDescription_Growth: @ 83BD3F0
	.string "Der Körper wächst und\n"
	.string "SPEZ. ANGR. wird erhöht.$"

gMoveDescription_RazorLeaf: @ 83BD41F
	.string "Trifft Gegner mit Blättern.\n"
	.string "Hohe Volltrefferquote.$"

gMoveDescription_SolarBeam: @ 83BD454
	.string "Absorbiert Licht in der 1.\n"
	.string "Runde, 2. Runde Angriff.$"

gMoveDescription_PoisonPowder: @ 83BD487
	.string "Verstreut giftigen Puder,\n"
	.string "der Gegner vergiften kann.$"

gMoveDescription_StunSpore: @ 83BD4B8
	.string "Verstreut Puder, der den\n"
	.string "Gegner evtl. paralysiert.$"

gMoveDescription_SleepPowder: @ 83BD4E5
	.string "Verstreut Puder, der Geg.\n"
	.string "evtl. in Schlaf versetzt.$"

gMoveDescription_PetalDance: @ 83BD518
	.string "Angriff in 2-3 Runden.\n"
	.string "Angreifer wird verwirrt.$"

gMoveDescription_StringShot: @ 83BD54A
	.string "Umwickelt Gegner mit Faden\n"
	.string "und senkt INIT.-Wert.$"

gMoveDescription_DragonRage: @ 83BD579
	.string "Stößt Schockwellen aus, die\n"
	.string "40 KP Schaden anrichten.$"

gMoveDescription_FireSpin: @ 83BD5B0
	.string "Schließt Gegner für 2-5\n"
	.string "Runden in Feuerkreis ein.$"

gMoveDescription_ThunderShock: @ 83BD5E2
	.string "Elektro-Attacke. Gegner\n"
	.string "evtl. paralysiert.$"

gMoveDescription_Thunderbolt: @ 83BD612
	.string "Starke Elektro-Attacke,\n"
	.string "Gegner evtl. paralysiert.$"

gMoveDescription_ThunderWave: @ 83BD648
	.string "Ein schwacher Stromstoß,\n"
	.string "der den Gegner paralysiert.$"

gMoveDescription_Thunder: @ 83BD67B
	.string "Elektro-Attacke, die den\n"
	.string "Gegner evtl. paralysiert.$"

gMoveDescription_RockThrow: @ 83BD6A8
	.string "Wirft kleine Steine auf den\n"
	.string "Gegner.$"

gMoveDescription_Earthquake: @ 83BD6CE
	.string "Mächtiges Beben. Ist bei\n"
	.string "fliegenden Feinden nutzlos.$"

gMoveDescription_Fissure: @ 83BD702
	.string "Sofort-K.O. Wirft Gegner\n"
	.string "in Gebirgsspalte.$"

gMoveDescription_Dig: @ 83BD735
	.string "Gräbt sich in der 1. Runde\n"
	.string "ein und trifft in der 2.$"

gMoveDescription_Toxic: @ 83BD76C
	.string "Vergiftet den Gegner mit \n"
	.string "einem starken Toxin.$"

gMoveDescription_Confusion: @ 83BD798
	.string "Psycho-Attacke, die den\n"
	.string "Gegner evtl. verwirrt.$"

gMoveDescription_Psychic: @ 83BD7C3
	.string "Starke Psycho-Attacke, die\n"
	.string "evtl. SPEZ. VERT. senkt.$"

gMoveDescription_Hypnosis: @ 83BD7F5
	.string "Hypno-Attacke, die Gegner\n"
	.string "evtl. in Schlaf versetzt.$"

gMoveDescription_Meditate: @ 83BD81F
	.string "Friedliche Meditation, um\n"
	.string "ANGR.-Wert zu steigern.$"

gMoveDescription_Agility: @ 83BD850
	.string "Entspannt den Körper, um\n"
	.string "INIT.-Wert. zu steigern.$"

gMoveDescription_QuickAttack: @ 83BD879
	.string "Sehr schneller Angriff mit\n"
	.string "Erstschlaggarantie.$"

gMoveDescription_Rage: @ 83BD8AD
	.string "Erhöht ANGR. des Anwenders\n"
	.string "bei jedem gegn. Treffer.$"

gMoveDescription_Teleport: @ 83BD8DC
	.string "Psycho-Angriff, um sofort\n"
	.string "aus einem Kampf zu fliehen.$"

gMoveDescription_NightShade: @ 83BD90E
	.string "Richtet Schaden gemäß\n"
	.string "Level d. Angreifers an.$"

gMoveDescription_Mimic: @ 83BD93D
	.string "Kopiert eine zuvor ausge-\n"
	.string "führte Attacke d. Gegners.$"

gMoveDescription_Screech: @ 83BD96E
	.string "Stößt einen Schrei aus, um\n"
	.string "gegn. VERT. zu senken.$"

gMoveDescription_DoubleTeam: @ 83BD9A3
	.string "Erzeugt Ebenbilder, um \n"
	.string "Fluchtwert zu erhöhen.$"

gMoveDescription_Recover: @ 83BD9D1
	.string "Max. KP des Anwenders w.\n"
	.string "bis zur Hälfte aufgefüllt.$"

gMoveDescription_Harden: @ 83BD9FC
	.string "Stärkt die Muskulatur und\n"
	.string "erhöht VERT.-Wert.$"

gMoveDescription_Minimize: @ 83BDA2B
	.string "Anwender schrumpft, um\n"
	.string "Fluchtwert zu erhöhen.$"

gMoveDescription_Smokescreen: @ 83BDA5B
	.string "Senkt Genauigkeit d. Geg-\n"
	.string "ners mit Rauch, Tinte o. ä.$"

gMoveDescription_ConfuseRay: @ 83BDA8C
	.string "Ein fieser Strahl, der den\n"
	.string "Gegner verwirrt.$"

gMoveDescription_Withdraw: @ 83BDAB2
	.string "Rückzug in den harten\n"
	.string "Panzer. Erhöht VERT.-Wert.$"

gMoveDescription_DefenseCurl: @ 83BDAEB
	.string "Verbirgt Schwächen durch\n"
	.string "Einrollen, VERT.-Wert hoch.$"

gMoveDescription_Barrier: @ 83BDB1D
	.string "Erzeugt Barriere, die den\n"
	.string "VERT.-Wert stark erhöht.$"

gMoveDescription_LightScreen: @ 83BDB4C
	.string "Erzeugt Lichtwand u. senkt\n"
	.string "SPEZ. ANGR.-Schaden.$"

gMoveDescription_Haze: @ 83BDB80
	.string "Erzeugt dunklen Dunst.\n"
	.string "Löscht alle Statusänder.$"

gMoveDescription_Reflect: @ 83BDBB7
	.string "Erzeugt Lichtwand, schützt\n"
	.string "teilweise vor phys. Angr.$"

gMoveDescription_FocusEnergy: @ 83BDBEE
	.string "Bündelt Kraft. Volltreffer-\n"
	.string "chance wird erhöht.$"

gMoveDescription_Bide: @ 83BDC1D
	.string "Erträgt 2 Runden Angriffe,\n"
	.string "schlägt doppelt zurück.$"

gMoveDescription_Metronome: @ 83BDC4D
	.string "Bewegt Finger und wählt\n"
	.string "PKMN-Attacke zufällig aus.$"

gMoveDescription_MirrorMove: @ 83BDC81
	.string "Erwidert gegn. Angriff mit\n"
	.string "derselben Attacke.$"

gMoveDescription_SelfDestruct: @ 83BDCAF
	.string "Richtet großen Schaden an.\n"
	.string "Anwender wird besiegt.$"

gMoveDescription_EggBomb: @ 83BDCE0
	.string "Ein Ei wird auf den Gegner\n"
	.string "abgefeuert.$"

gMoveDescription_Lick: @ 83BDD06
	.string "Leck-Attacke mit Zunge.\n"
	.string "Gegner evtl. paralysiert.$"

gMoveDescription_Smog: @ 83BDD3D
	.string "Angriff mit Gas. Gegner wird\n"
	.string "evtl. vergiftet.$"

gMoveDescription_Sludge: @ 83BDD69
	.string "Wirft Schlamm auf Gegner.\n"
	.string "Evtl. Vergiftung.$"

gMoveDescription_BoneClub: @ 83BDD9E
	.string "Schlägt Gegner mit Keule\n"
	.string "und verschreckt ihn evtl.$"

gMoveDescription_FireBlast: @ 83BDDCE
	.string "Feuersbrunst, die alles ver-\n"
	.string "sengt. Verbrennt Geg. evtl.$"

gMoveDescription_Waterfall: @ 83BDE01
	.string "Attacke basiert auf Tempo.\n"
	.string "Erklimmt Wasserfälle.$"

gMoveDescription_Clamp: @ 83BDE31
	.string "Fängt und drückt Gegner\n"
	.string "für 2-5 Runden.$"

gMoveDescription_Swift: @ 83BDE5E
	.string "Verschießt sternförmige\n"
	.string "Strahlen. Treffergarantie!$"

gMoveDescription_SkullBash: @ 83BDE87
	.string "Zieht Kopf ein und greift in\n"
	.string "der nächsten Runde an.$"

gMoveDescription_SpikeCannon: @ 83BDEB9
	.string "Verschießt spitze Stacheln\n"
	.string "und trifft 2 - 5-mal.$"

gMoveDescription_Constrict: @ 83BDEE9
	.string "Schmerzvoller Klammergriff.\n"
	.string "Senkt evtl. INIT.-Wert.$"

gMoveDescription_Amnesia: @ 83BDF16
	.string "Gedächtnisverlust, der\n"
	.string "SPEZ. VERT. deutlich erhöht.$"

gMoveDescription_Kinesis: @ 83BDF4A
	.string "Lenkt Gegner ab und senkt\n"
	.string "evtl. seine Genauigkeit.$"

gMoveDescription_SoftBoiled: @ 83BDF71
	.string "Max. KP des Anwenders w.\n"
	.string "bis zur Hälfte aufgefüllt.$"

gMoveDescription_HiJumpKick: @ 83BDF9C
	.string "Sprung-Tritt mit Knie. Miss-\n"
	.string "erfolg verletzt Anwender.$"

gMoveDescription_Glare: @ 83BDFD1
	.string "Schüchtert Gegner ein, so\n"
	.string "dass er paralysiert ist.$"

gMoveDescription_DreamEater: @ 83BE003
	.string "Schlafendem Gegner wird\n"
	.string "halber Schaden abgezogen.$"

gMoveDescription_PoisonGas: @ 83BE03A
	.string "Hüllt Gegner in giftiges Gas\n"
	.string "ein, kann vergiften.$"

gMoveDescription_Barrage: @ 83BE06B
	.string "Wirft 2 - 5-mal runde Gegen-\n"
	.string "stände auf den Gegner.$"

gMoveDescription_LeechLife: @ 83BE098
	.string "Ein Angriff, der die Hälfte\n"
	.string "des Schadens saugt.$"

gMoveDescription_LovelyKiss: @ 83BE0C9
	.string "Fordert Kuss mit bösem\n"
	.string "Blick. Evtl. Schlaf.$"

gMoveDescription_SkyAttack: @ 83BE0FE
	.string "Sucht nach Schwächen,\n"
	.string "Treffer nächste Runde.$"

gMoveDescription_Transform: @ 83BE133
	.string "Ändert die Anwenderzellen\n"
	.string "für ein Ebenbild d. Gegners.$"

gMoveDescription_Bubble: @ 83BE168
	.string "Angriff mit Blasen. INIT.-\n"
	.string "Wert wird evtl. gesenkt.$"

gMoveDescription_DizzyPunch: @ 83BE19C
	.string "Rhythmischer Schlag, der\n"
	.string "den Gegner verwirren kann.$"

gMoveDescription_Spore: @ 83BE1C7
	.string "Erzeugt eine Wolke aus ein-\n"
	.string "schläfernden Sporen.$"

gMoveDescription_Flash: @ 83BE1FC
	.string "Erzeugt helles Licht, das\n"
	.string "gegn. Genauigkeit senkt.$"

gMoveDescription_Psywave: @ 83BE231
	.string "Psycho-Welle mit unter-\n"
	.string "schiedlicher Intensität.$"

gMoveDescription_Splash: @ 83BE263
	.string "Nur ein Platscher..., der\n"
	.string "überhaupt nichts bewirkt.$"

gMoveDescription_AcidArmor: @ 83BE293
	.string "Verflüssigt Körper d. An-\n"
	.string "wenders. Erhört VERT.$"

gMoveDescription_Crabhammer: @ 83BE2C7
	.string "Schlägt mit Schere zu.\n"
	.string "Volltrefferchance hoch.$"

gMoveDescription_Explosion: @ 83BE2FD
	.string "Richtet großen Schaden an.\n"
	.string "Anwender wird besiegt.$"

gMoveDescription_FurySwipes: @ 83BE32E
	.string "Beharkt Gegner 2 - 5-mal\n"
	.string "mit scharfen Klauen o. ä.$"

gMoveDescription_Bonemerang: @ 83BE362
	.string "Ein Bumerang aus Knochen,\n"
	.string "der zweimal trifft.$"

gMoveDescription_Rest: @ 83BE38E
	.string "Anwender schläft 2 Runden,\n"
	.string "KP und Status erneuert.$"

gMoveDescription_RockSlide: @ 83BE3C4
	.string "Schleudert riesige Felsen.\n"
	.string "Verschreckt evtl. Gegner.$"

gMoveDescription_HyperFang: @ 83BE3F4
	.string "Angriff mit Zähnen.\n"
	.string "Verschreckt evtl. Gegner.$"

gMoveDescription_Sharpen: @ 83BE423
	.string "Reduziert Polygonzahl und\n"
	.string "erhöht ANGR.-Wert.$"

gMoveDescription_Conversion: @ 83BE450
	.string "Wandelt Typ d. Anwenders in\n"
	.string "eigenen Attacken-Typ.$"

gMoveDescription_TriAttack: @ 83BE481
	.string "Feuert 3 Arten von Strahlen\n"
	.string "gleichzeitig ab.$"

gMoveDescription_SuperFang: @ 83BE4AE
	.string "Greift mit scharfen Zähnen\n"
	.string "an. Halbiert gegnerische KP.$"

gMoveDescription_Slash: @ 83BE4E3
	.string "Hieb mit Klauen o. ä. Hohe\n"
	.string "Volltrefferquote.$"

gMoveDescription_Substitute: @ 83BE51B
	.string "Lockvogel, der 1/4 der max.\n"
	.string "KP des Anwenders besitzt.$"

gMoveDescription_Struggle: @ 83BE54F
	.string "Einsatz nur bei verbrauch-\n"
	.string "ten AP. Selbstschädigung!$"

gMoveDescription_Sketch: @ 83BE58B
	.string "Kopiert stets den zuletzt\n"
	.string "erlittenen Angriff.$"

gMoveDescription_TripleKick: @ 83BE5B3
	.string "Tritt Gegner 3-mal nach-\n"
	.string "einander. Härte nimmt zu.$"

gMoveDescription_Thief: @ 83BE5E9
	.string "Kann das vom Gegner\n"
	.string "gehaltene Item stehlen.$"

gMoveDescription_SpiderWeb: @ 83BE61C
	.string "Wickelt Gegner ein. Flucht \n"
	.string "oder Tausch unmöglich.$"

gMoveDescription_MindReader: @ 83BE653
	.string "Ahnt gegnerische Aktion.\n"
	.string "Nächste Attacke trifft.$"

gMoveDescription_Nightmare: @ 83BE68A
	.string "Bewirkt 1/4 Schaden pro\n"
	.string "Zug bei schlafendem Gegner.$"

gMoveDescription_FlameWheel: @ 83BE6BC
	.string "Feuer-Attacke, die Gegner\n"
	.string "evtl. verbrennt.$"

gMoveDescription_Snore: @ 83BE6EB
	.string "Laute Attacke. Kann nur im\n"
	.string "Schlaf benutzt werden.$"

gMoveDescription_Curse: @ 83BE71D
	.string "Ein Angriff, der bei GEIST-\n"
	.string "PKMN anders funktioniert.$"

gMoveDescription_Flail: @ 83BE74B
	.string "Richtet mehr Schaden an,\n"
	.string "wenn eigene KP niedrig sind.$"

gMoveDescription_Conversion2: @ 83BE77C
	.string "Anwender wird resistent\n"
	.string "gegen letzten Angr.-Typ.$"

gMoveDescription_Aeroblast: @ 83BE7B0
	.string "Erzeugt ein Vakuum.\n"
	.string "Hohe Volltrefferquote.$"

gMoveDescription_CottonSpore: @ 83BE7E4
	.string "Sporen heften sich an den\n"
	.string "Gegner. Senkt INIT.-Wert.$"

gMoveDescription_Reversal: @ 83BE815
	.string "Richtet mehr Schaden an,\n"
	.string "wenn eigene KP niedrig sind.$"

gMoveDescription_Spite: @ 83BE846
	.string "AP des letzten gegner.\n"
	.string "Angriffs werden gesenkt.$"

gMoveDescription_PowderSnow: @ 83BE875
	.string "Schnee auf Gegner, der\n"
	.string "evtl. eingefroren wird.$"

gMoveDescription_Protect: @ 83BE8AB
	.string "Weicht Angriff aus.\n"
	.string "Scheitert evtl. bei Wdh.$"

gMoveDescription_MachPunch: @ 83BE8DE
	.string "Schneller Hieb, der stets\n"
	.string "zuerst trifft.$"

gMoveDescription_ScaryFace: @ 83BE911
	.string "Erschreckt mit Grimasse. \n"
	.string "INIT.-Wert sinkt deutlich.$"

gMoveDescription_FaintAttack: @ 83BE946
	.string "Zieht Gegner heran und\n"
	.string "trifft mit Sicherheit.$"

gMoveDescription_SweetKiss: @ 83BE976
	.string "Fordert Kuss mit süßem\n"
	.string "Blick. Verwirrt Gegner evtl.$"

gMoveDescription_BellyDrum: @ 83BE9AC
	.string "Erhöht ANGR.-Wert,\n"
	.string "opfert jedoch KP.$"

gMoveDescription_SludgeBomb: @ 83BE9D3
	.string "Wirft Schlamm auf Gegner\n"
	.string "und vergiftet ihn evtl.$"

gMoveDescription_MudSlap: @ 83BEA08
	.string "Wirft Gegner Matsch ins Ge-\n"
	.string "sicht. Genauigkeit sinkt.$"

gMoveDescription_Octazooka: @ 83BEA3C
	.string "Verschießt Tinte und senkt\n"
	.string "dadurch Genauigkeit.$"

gMoveDescription_Spikes: @ 83BEA6C
	.string "Richtet bei Tausch Schaden\n"
	.string "mit Stacheln an.$"

gMoveDescription_ZapCannon: @ 83BEA98
	.string "Kräftige, ungenaue At-\n"
	.string "tacke, die evtl. paralysiert.$"

gMoveDescription_Foresight: @ 83BEACE
	.string "Verhindert Anstieg von\n"
	.string "gegnerischem Fluchtwert.$"

gMoveDescription_DestinyBond: @ 83BEB01
	.string "Wird der Angreifer besiegt,\n"
	.string "gilt das auch für d. Gegner.$"

gMoveDescription_PerishSong: @ 83BEB34
	.string "Wer dieses Lied hört, wird\n"
	.string "nach 3 Runden besiegt.$"

gMoveDescription_IcyWind: @ 83BEB65
	.string "Eis-Attacke, die den INIT.-\n"
	.string "Wert des Gegners senkt.$"

gMoveDescription_Detect: @ 83BEB94
	.string "Wendet Attacken ab, Erfolg\n"
	.string "sinkt bei Wiederholung.$"

gMoveDescription_BoneRush: @ 83BEBC7
	.string "Greift Gegner 2 - 5-mal in\n"
	.string "Folge mit einem Knochen an.$"

gMoveDescription_LockOn: @ 83BEBF9
	.string "Visiert Gegner an u. trifft\n"
	.string "in der nächsten Runde.$"

gMoveDescription_Outrage: @ 83BEC2B
	.string "Wiederholt Angriff 2-3 Run-\n"
	.string "den lang. Verwirrt Anwender.$"

gMoveDescription_Sandstorm: @ 83BEC5D
	.string "Erzeugt einen Sandsturm,\n"
	.string "der mehrere Runden wütet.$"

gMoveDescription_GigaDrain: @ 83BEC8E
	.string "Absorbiert die Hälfte des\n"
	.string "angerichteten Schadens.$"

gMoveDescription_Endure: @ 83BECBF
	.string "Hält jeder Attacke 1 Runde\n"
	.string "stand. 1 KP bleibt stets.$"

gMoveDescription_Charm: @ 83BECF4
	.string "Betört den Gegner u. redu-\n"
	.string "ziert seinen ANGR. deutlich.$"

gMoveDescription_Rollout: @ 83BED23
	.string "Attacke, die 5 Runden\n"
	.string "dauert. Die Härte nimmt zu.$"

gMoveDescription_FalseSwipe: @ 83BED54
	.string "Ein Angriff, der dem Gegner\n"
	.string "zumindest 1 KP lässt.$"

gMoveDescription_Swagger: @ 83BED86
	.string "Verwirrt den Gegner und\n"
	.string "erhöht ANGR.-Wert deutlich.$"

gMoveDescription_MilkDrink: @ 83BEDB8
	.string "Füllt bis zur Hälfte der max.\n"
	.string "KP des Benutzers auf.$"

gMoveDescription_Spark: @ 83BEDE3
	.string "Elektro-Hieb, der Gegner\n"
	.string "paralysieren kann.$"

gMoveDescription_FuryCutter: @ 83BEE14
	.string "Eine Attacke, deren Härte\n"
	.string "bei jedem Treffer zunimmt.$"

gMoveDescription_SteelWing: @ 83BEE47
	.string "Trifft den Gegner hart mit\n"
	.string "ausgebreiteten Flügeln.$"

gMoveDescription_MeanLook: @ 83BEE74
	.string "Böser Blick, der die Flucht\n"
	.string "des Gegners vereitelt.$"

gMoveDescription_Attract: @ 83BEEA9
	.string "Angriff des anderen Ge-\n"
	.string "schlechts unwahrscheinl.$"

gMoveDescription_SleepTalk: @ 83BEEDA
	.string "Benutzt per Zufall eine\n"
	.string "Attacke im Schlaf.$"

gMoveDescription_HealBell: @ 83BEF02
	.string "Läutet beruhigend, heilt\n"
	.string "alle Status-Veränderungen.$"

gMoveDescription_Return: @ 83BEF36
	.string "Angriff, dessen Kraft bei \n"
	.string "Freundschaft größer wird.$"

gMoveDescription_Present: @ 83BEF69
	.string "Eine Bombe als Geschenk. Es\n"
	.string "kann KP wiederherstellen.$"

gMoveDescription_Frustration: @ 83BEF97
	.string "Die Attacke ist stärker bei\n"
	.string "verhassten TRAINERn.$"

gMoveDescription_Safeguard: @ 83BEFCE
	.string "Mystische Kraft, die alle\n"
	.string "Statusprobleme verhindert.$"

gMoveDescription_PainSplit: @ 83BEFFD
	.string "Addiert KP v. Anwender u.\n"
	.string "Gegner, teilt gerecht auf.$"

gMoveDescription_SacredFire: @ 83BF033
	.string "Mystische Feuer-Attacke, \n"
	.string "die d. Geg. evtl. verbrennt.$"

gMoveDescription_Magnitude: @ 83BF063
	.string "Ein erdbebenartiger An-\n"
	.string "griff von zufälliger Stärke.$"

gMoveDescription_DynamicPunch: @ 83BF090
	.string "Kräftige Attacke, die ver-\n"
	.string "wirrt, aber ungenau ist.$"

gMoveDescription_Megahorn: @ 83BF0C6
	.string "Brutaler Frontalangriff\n"
	.string "mit spitzen Hörnern.$"

gMoveDescription_DragonBreath: @ 83BF0F6
	.string "Fegt den Gegner mit zer-\n"
	.string "störerisch heißem Atem weg.$"

gMoveDescription_BatonPass: @ 83BF12A
	.string "Tauscht PKMN aus. Alle Än-\n"
	.string "derungen bleiben bestehen.$"

gMoveDescription_Encore: @ 83BF15F
	.string "Gegner wiederholt letzten\n"
	.string "Angriff 2 - 6-mal.$"

gMoveDescription_Pursuit: @ 83BF195
	.string "Richtet großen Schaden bei\n"
	.string "Austausch des Gegners an.$"

gMoveDescription_RapidSpin: @ 83BF1C9
	.string "Trifft den Gegner durch\n"
	.string "Drehen mit max. Tempo.$"

gMoveDescription_SweetScent: @ 83BF1F9
	.string "Lockt Gegner an und senkt\n"
	.string "seinen Fluchtwert.$"

gMoveDescription_IronTail: @ 83BF220
	.string "Att. mit hartem Schweif. \n"
	.string "Senkt evtl. VERT.-Wert.$"

gMoveDescription_MetalClaw: @ 83BF252
	.string "Klauen-Attacke. Evtl. Er-\n"
	.string "höhung d. ANGR.-Wert d. Anw.$"

gMoveDescription_VitalThrow: @ 83BF282
	.string "Attacke stets gleich, aber\n"
	.string "mit Treffergarantie.$"

gMoveDescription_MorningSun: @ 83BF2B3
	.string "Füllt KP auf. Die Menge\n"
	.string "hängt vom Wetter ab.$"

gMoveDescription_Synthesis: @ 83BF2E4
	.string "Füllt KP auf. Die Menge\n"
	.string "hängt vom Wetter ab.$"

gMoveDescription_Moonlight: @ 83BF315
	.string "Füllt KP auf. Die Menge\n"
	.string "hängt vom Wetter ab.$"

gMoveDescription_HiddenPower: @ 83BF346
	.string "Die Wirkung dieser Attacke\n"
	.string "hängt vom Benutzer ab.$"

gMoveDescription_CrossChop: @ 83BF36E
	.string "Doppelter Hieb. Hohe \n"
	.string "Volltrefferquote.$"

gMoveDescription_Twister: @ 83BF3A1
	.string "Trifft Gegner mit\n"
	.string "heftigem Wirbelsturm.$"

gMoveDescription_RainDance: @ 83BF3D0
	.string "Erhöht Stärke von WASSER-\n"
	.string "Attacken 5 Runden lang.$"

gMoveDescription_SunnyDay: @ 83BF403
	.string "Erhöht Stärke von FEUER-\n"
	.string "Attacken 5 Runden lang.$"

gMoveDescription_Crunch: @ 83BF435
	.string "Beißt mit Reißzähnen zu und\n"
	.string "senkt evtl. SPEZ. VERT.$"

gMoveDescription_MirrorCoat: @ 83BF463
	.string "Kontert d. Spezial-Attacke\n"
	.string "d. Geg. mit 2-facher Kraft.$"

gMoveDescription_PsychUp: @ 83BF49A
	.string "Kopiert Effekte d. Gegners\n"
	.string "u. gibt sie dem Angreifer.$"

gMoveDescription_ExtremeSpeed: @ 83BF4CC
	.string "Extrem schnelle und kraft-\n"
	.string "volle Attacke.$"

gMoveDescription_AncientPower: @ 83BF4F3
	.string "Ein Angriff, der alle\n"
	.string "Status-Werte erhöhen kann.$"

gMoveDescription_ShadowBall: @ 83BF517
	.string "Bewirft Gegner und senkt\n"
	.string "evtl. SPEZ. VERT.$"

gMoveDescription_FutureSight: @ 83BF54C
	.string "Stärkt innere Kraft. Trifft\n"
	.string "2 Runden später.$"

gMoveDescription_RockSmash: @ 83BF57B
	.string "Zertrümmernder Angriff, \n"
	.string "der evtl. VERT.-Wert senkt.$"

gMoveDescription_Whirlpool: @ 83BF5AA
	.string "Hält Gegner 2-5 Züge in\n"
	.string "einem Strudel gefangen.$"

gMoveDescription_BeatUp: @ 83BF5E3
	.string "Ruft POKéMON hinzu, um an\n"
	.string "dem Angriff teilzuhaben.$"

gMoveDescription_FakeOut: @ 83BF610
	.string "Trifft schon mit dem ersten\n"
	.string "Schlag. Verjagt Gegner evtl.$"

gMoveDescription_Uproar: @ 83BF643
	.string "Erzeugt für 2-5 Züge einen\n"
	.string "Aufruhr. Verhindert Schlaf.$"

gMoveDescription_Stockpile: @ 83BF679
	.string "Lädt Kraft für bis zu 3\n"
	.string "Runden auf.$"

gMoveDescription_SpitUp: @ 83BF69D
	.string "Entlädt gehortete Kraft.\n"
	.string "Je mehr, desto besser.$"

gMoveDescription_Swallow: @ 83BF6CE
	.string "Absorbiert gehortete\n"
	.string "Kraft. Stellt KP wieder her.$"

gMoveDescription_HeatWave: @ 83BF6F8
	.string "Gegner wird von heißem Atem\n"
	.string "getroffen. Verbrennt evtl.$"

gMoveDescription_Hail: @ 83BF72D
	.string "Erzeugt Hagelsturm, der in\n"
	.string "jeder Runde trifft.$"

gMoveDescription_Torment: @ 83BF75A
	.string "Quält Gegner u. verhindert\n"
	.string "Wdh. eines Angriffs.$"

gMoveDescription_Flatter: @ 83BF78F
	.string "Verwirrt den Gegner, erhöht\n"
	.string "aber dessen SPEZ. ANGR.$"

gMoveDescription_WillOWisp: @ 83BF7B9
	.string "Fügt dem Gegner \n"
	.string "Verbrennungen zu.$"

gMoveDescription_Memento: @ 83BF7E7
	.string "Der Benutzer ist besiegt\n"
	.string "und senkt die gegn. Werte.$"

gMoveDescription_Facade: @ 83BF817
	.string "Erhöht ANGR. nach Verbren-\n"
	.string "nung, Paralyse o. Vergift.$"

gMoveDescription_FocusPunch: @ 83BF84A
	.string "Angriff, der später trifft.\n"
	.string "Ben. schreckt evtl. zurück.$"

gMoveDescription_SmellingSalt: @ 83BF87F
	.string "Effektiv geg. paralysierte\n"
	.string "Gegner. Heilt sie aber auch.$"

gMoveDescription_FollowMe: @ 83BF8B5
	.string "Zieht Aufmerksamkeit an.\n"
	.string "Gegner greift nur Anw. an.$"

gMoveDescription_NaturePower: @ 83BF8E8
	.string "Die Elementklasse des\n"
	.string "Angriffs hängt vom Ort ab.$"

gMoveDescription_Charge: @ 83BF91D
	.string "Lädt Energie für den kom-\n"
	.string "menden Elektro-Angr. auf.$"

gMoveDescription_Taunt: @ 83BF951
	.string "Legt den Gegner rein. Er\n"
	.string "benutzt nur noch Angriffe.$"

gMoveDescription_HelpingHand: @ 83BF97E
	.string "Steigert die Kraft der An-\n"
	.string "griffe des Getroffenen.$"

gMoveDescription_Trick: @ 83BF9A9
	.string "Betrügt beim Handel\n"
	.string "mit Gegenständen.$"

gMoveDescription_RolePlay: @ 83BF9D1
	.string "Parodiert Gegner u. kopiert\n"
	.string "seine Spezialfähigkeiten.$"

gMoveDescription_Wish: @ 83BFA03
	.string "Ein Wunsch, der KP auffüllt.\n"
	.string "Die Erfüllung braucht Zeit.$"

gMoveDescription_Assist: @ 83BFA33
	.string "Greift zufällig mit einem\n"
	.string "Angriff d. Partners an.$"

gMoveDescription_Ingrain: @ 83BFA65
	.string "Verwurzelung füllt KP auf.\n"
	.string "Austausch unmöglich.$"

gMoveDescription_Superpower: @ 83BFA9C
	.string "Steigert Stärke deutlich,\n"
	.string "senkt aber Status-Werte.$"

gMoveDescription_MagicCoat: @ 83BFACB
	.string "Gibt Spezialeffekte zurück\n"
	.string "an Benutzer.$"

gMoveDescription_Recycle: @ 83BFAFA
	.string "Recycling eines\n"
	.string "verwendeten Items.$"

gMoveDescription_Revenge: @ 83BFB21
	.string "Attacke wird stärker, wenn\n"
	.string "Anwender Schaden nimmt.$"

gMoveDescription_BrickBreak: @ 83BFB53
	.string "Durchbricht Barrieren und\n"
	.string "verursacht Schaden.$"

gMoveDescription_Yawn: @ 83BFB88
	.string "Gegner gähnt und schläft\n"
	.string "in der nächsten Runde ein.$"

gMoveDescription_KnockOff: @ 83BFBBD
	.string "Schlägt Gegner Item weg.\n"
	.string "Vereitelt so den Gebrauch.$"

gMoveDescription_Endeavor: @ 83BFBF1
	.string "Wird stärker, wenn Anw.-KP\n"
	.string "geringer als Gegner-KP ist.$"

gMoveDescription_Eruption: @ 83BFC2A
	.string "Je höher KP des Benutzers,\n"
	.string "desto mehr Schaden.$"

gMoveDescription_SkillSwap: @ 83BFC5C
	.string "Anw. tauscht Spezial-\n"
	.string "fähigkeit mit POKéMON.$"

gMoveDescription_Imprison: @ 83BFC8E
	.string "Hindert Gegner an Atta-\n"
	.string "cken, die d. Benutzer kennt.$"

gMoveDescription_Refresh: @ 83BFCC0
	.string "Kuriert Vergiftungen, Para-\n"
	.string "lyse und Verbrennung.$"

gMoveDescription_Grudge: @ 83BFCE7
	.string "Wenn Anw. bes., werden AP\n"
	.string "der Finalattacke gelöscht.$"

gMoveDescription_Snatch: @ 83BFD1D
	.string "Immunität geg. den Effekt\n"
	.string "d. nächsten gegn. Angriffs.$"

gMoveDescription_SecretPower: @ 83BFD4F
	.string "Angriff, dessen Auswirkung\n"
	.string "abhängig vom Ort ist.$"

gMoveDescription_Dive: @ 83BFD7D
	.string "Taucht in der 1. Runde\n"
	.string "unter u. trifft in der 2.$"

gMoveDescription_ArmThrust: @ 83BFDB4
	.string "Schläge mit geradem Arm, die\n"
	.string "Gegner 2 - 5-mal treffen.$"

gMoveDescription_Camouflage: @ 83BFDEB
	.string "Die Elementklasse des\n"
	.string "POKéMON hängt vom Ort ab.$"

gMoveDescription_TailGlow: @ 83BFE20
	.string "Ein blinkendes Licht. SPEZ.\n"
	.string "ANGR. wird deutlich erhöht.$"

gMoveDescription_LusterPurge: @ 83BFE4D
	.string "Angriff mit grellem Licht.\n"
	.string "Senkt evtl. SPEZ. VERT.$"

gMoveDescription_MistBall: @ 83BFE7F
	.string "Angriff m. Daunengestöber,\n"
	.string "Senkt evtl. SPEZ. ANGR.$"

gMoveDescription_FeatherDance: @ 83BFEB1
	.string "Hüllt Gegner in Daunen und\n"
	.string "senkt ANGR.-Wert deutlich.$"

gMoveDescription_TeeterDance: @ 83BFEE6
	.string "Verwirrt alle POKéMON im \n"
	.string "Kampf.$"

gMoveDescription_BlazeKick: @ 83BFF09
	.string "Hohe Volltrefferquote. Ver-\n"
	.string "ursacht evtl. Verbrennung.$"

gMoveDescription_MudSport: @ 83BFF43
	.string "Bedeckt Anw. mit Lehm u. er-\n"
	.string "höht Schutz geg. Elek.-Att.$"

gMoveDescription_IceBall: @ 83BFF7A
	.string "Angriff für 5 Runden. \n"
	.string "Stärker, wenn Treffer.$"

gMoveDescription_NeedleArm: @ 83BFFAF
	.string "Angriff mit dornigen Armen. \n"
	.string "Geg. schreckt evtl. zurück.$"

gMoveDescription_SlackOff: @ 83BFFDE
	.string "Durch Müßiggang wird die\n"
	.string "Hälfte d. max. KP aufgefüllt.$"

gMoveDescription_HyperVoice: @ 83C000B
	.string "Laute Attacke mit Schall-\n"
	.string "wellen.$"

gMoveDescription_PoisonFang: @ 83C003A
	.string "Angriff mit Reißzähnen. \n"
	.string "Gegner wird evtl. vergiftet.$"

gMoveDescription_CrushClaw: @ 83C006B
	.string "Angriff mit scharfen Klau-\n"
	.string "en. Senkt evtl. VERT.-Wert.$"

gMoveDescription_BlastBurn: @ 83C00A1
	.string "Starker Angriff. Angreifer\n"
	.string "muss eine Runde aussetzen.$"

gMoveDescription_HydroCannon: @ 83C00D7
	.string "Starker Angriff. Angreifer\n"
	.string "muss eine Runde aussetzen.$"

gMoveDescription_MeteorMash: @ 83C010D
	.string "Ein Schlag wie ein Meteor.\n"
	.string "Erhöht evtl. ANGR.-Wert.$"

gMoveDescription_Astonish: @ 83C013A
	.string "Angriff, der Gegner evtl.\n"
	.string "zurückschrecken lässt.$"

gMoveDescription_WeatherBall: @ 83C016B
	.string "Elementkl. u. Stärke der At-\n"
	.string "tacke sind wetterabhängig.$"

gMoveDescription_Aromatherapy: @ 83C019E
	.string "Heilt alle Status-Probleme\n"
	.string "mit beruhigendem Duft.$"

gMoveDescription_FakeTears: @ 83C01CF
	.string "Täuscht Weinen vor, um\n"
	.string "gegn. SPEZ. VERT. zu senken.$"

gMoveDescription_AirCutter: @ 83C0201
	.string "Greift mit heftigem Wind an.\n"
	.string "Hohe Volltrefferquote.$"

gMoveDescription_Overheat: @ 83C0235
	.string "Angriff mit voller Kraft.\n"
	.string "SPEZ. ANGR. sinkt deutlich.$"

gMoveDescription_OdorSleuth: @ 83C026D
	.string "Hindert Gegner daran, ihren\n"
	.string "Fluchtwert zu erhöhen.$"

gMoveDescription_RockTomb: @ 83C02A0
	.string "Hält den Feind mit Steinen\n"
	.string "auf u. senkt INIT.-Wert.$"

gMoveDescription_SilverWind: @ 83C02D5
	.string "Pulver-Attacke, die evtl.\n"
	.string "die Werte erhöht.$"

gMoveDescription_MetalSound: @ 83C0300
	.string "Stößt einen spitzen Schrei\n"
	.string "aus. Senkt SPEZ. VERT.$"

gMoveDescription_GrassWhistle: @ 83C0336
	.string "Versetzt Gegner mit schö-\n"
	.string "ner Melodie in den Schlaf.$"

gMoveDescription_Tickle: @ 83C0367
	.string "Bringt Gegner zum Lachen.\n"
	.string "ANGR. u. VERT. sinken.$"

gMoveDescription_CosmicPower: @ 83C0398
	.string "Erhöht VERT. u. SPEZ. VERT.\n"
	.string "durch mystische Kraft.$"

gMoveDescription_WaterSpout: @ 83C03C8
	.string "Ist wirkungsvoller, wenn KP\n"
	.string "des Benutzers hoch sind.$"

gMoveDescription_SignalBeam: @ 83C03F7
	.string "Seltsame Strahlenattacke.\n"
	.string "Verwirrt evtl. den Gegner.$"

gMoveDescription_ShadowPunch: @ 83C0427
	.string "Schattenhieb. Ausweichen\n"
	.string "unmöglich.$"

gMoveDescription_Extrasensory: @ 83C0459
	.string "Besonderer Angriff. Gegner\n"
	.string "schreckt evtl. zurück.$"

gMoveDescription_SkyUppercut: @ 83C048D
	.string "Kinnhaken, als würde man in\n"
	.string "die Luft springen.$"

gMoveDescription_SandTomb: @ 83C04BC
	.string "Gegner leidet für 2-5\n"
	.string "Runden in Sandhose.$"

gMoveDescription_SheerCold: @ 83C04F3
	.string "Eis-Attacke. Besiegt den\n"
	.string "Gegner, wenn sie trifft.$"

gMoveDescription_MuddyWater: @ 83C0526
	.string "Greift mit Matsch an und\n"
	.string "senkt evtl. Genauigkeit.$"

gMoveDescription_BulletSeed: @ 83C0554
	.string "Verschießt 2 bis 5 Samen\n"
	.string "gleichzeitig auf Gegner.$"

gMoveDescription_AerialAce: @ 83C0584
	.string "Eine extrem schnelle und\n"
	.string "unausweichbare Attacke.$"

gMoveDescription_IcicleSpear: @ 83C05B0
	.string "Feuert 2-5 Eiszapfen auf\n"
	.string "den Gegner.$"

gMoveDescription_IronDefense: @ 83C05E3
	.string "Stärkt den Körper.\n"
	.string "Erhöht VERT.-Wert deutlich.$"

gMoveDescription_Block: @ 83C0618
	.string "Versperrt den Fluchtweg\n"
	.string "des Gegners.$"

gMoveDescription_Howl: @ 83C0640
	.string "Jault, um in sich zu gehen.\n"
	.string "Erhöht ANGR.-Wert.$"

gMoveDescription_DragonClaw: @ 83C066D
	.string "Der Gegner wird mit\n"
	.string "scharfen Klauen verletzt.$"

gMoveDescription_FrenzyPlant: @ 83C068F
	.string "Starker Angriff. Angreifer\n"
	.string "muss eine Runde aussetzen.$"

gMoveDescription_BulkUp: @ 83C06C5
	.string "Pumpt den Körper auf. ANGR.\n"
	.string "u. VERT. werden erhöht.$"

gMoveDescription_Bounce: @ 83C06F9
	.string "Springt hoch u. landet in\n"
	.string "nächstem Zug. Evtl. Para.$"

gMoveDescription_MudShot: @ 83C072C
	.string "Bewirft den Gegner mit Lehm\n"
	.string "und senkt INIT.-Wert.$"

gMoveDescription_PoisonTail: @ 83C0754
	.string "Hohe Volltrefferquote.\n"
	.string "Gegner evtl. vergiftet.$"

gMoveDescription_Covet: @ 83C0784
	.string "Bittet charmant um das ge-\n"
	.string "haltene Item des Gegners.$"

gMoveDescription_VoltTackle: @ 83C07B3
	.string "Lebensgefährliche Attacke,\n"
	.string "leichte Selbstschädigung.$"

gMoveDescription_MagicalLeaf: @ 83C07E7
	.string "Magischer Blattangriff.\n"
	.string "Ausweichen unmöglich.$"

gMoveDescription_WaterSport: @ 83C081A
	.string "Benutzer wird nass, so dass\n"
	.string "er Feuer besser standhält.$"

gMoveDescription_CalmMind: @ 83C084F
	.string "Erhöht SPEZ. ANGR. u. SPEZ.\n"
	.string "VERT. durch Konzentration.$"

gMoveDescription_LeafBlade: @ 83C0880
	.string "Hieb mit scharfkantigem\n"
	.string "Blatt. Hohe Volltrefferqu.$"

gMoveDescription_DragonDance: @ 83C08B4
	.string "Ein mystischer Tanz, der\n"
	.string "ANGR.- u. INIT.-Wert erhöht.$"

gMoveDescription_RockBlast: @ 83C08E0
	.string "Wirft 2 - 5-mal in Folge\n"
	.string "Felsblöcke auf den Gegner.$"

gMoveDescription_ShockWave: @ 83C0911
	.string "Schnelle Elektro-Attacke\n"
	.string "mit Treffergarantie.$"

gMoveDescription_WaterPulse: @ 83C0939
	.string "Ultraschallwellen, die den\n"
	.string "Gegner verwirren können.$"

gMoveDescription_DoomDesire: @ 83C096C
	.string "Speichert Sonnenenergie.\n"
	.string "Angriff 2 Runden später.$"

gMoveDescription_PsychoBoost: @ 83C099D
	.string "Angriff mit voller Kraft.\n"
	.string "SPEZ. ANGR. sinkt deutlich.$"

	.align 2
gMoveDescriptions:: @ 83C09D8
	.4byte gMoveDescription_Pound
	.4byte gMoveDescription_KarateChop
	.4byte gMoveDescription_DoubleSlap
	.4byte gMoveDescription_CometPunch
	.4byte gMoveDescription_MegaPunch
	.4byte gMoveDescription_PayDay
	.4byte gMoveDescription_FirePunch
	.4byte gMoveDescription_IcePunch
	.4byte gMoveDescription_ThunderPunch
	.4byte gMoveDescription_Scratch
	.4byte gMoveDescription_ViceGrip
	.4byte gMoveDescription_Guillotine
	.4byte gMoveDescription_RazorWind
	.4byte gMoveDescription_SwordsDance
	.4byte gMoveDescription_Cut
	.4byte gMoveDescription_Gust
	.4byte gMoveDescription_WingAttack
	.4byte gMoveDescription_Whirlwind
	.4byte gMoveDescription_Fly
	.4byte gMoveDescription_Bind
	.4byte gMoveDescription_Slam
	.4byte gMoveDescription_VineWhip
	.4byte gMoveDescription_Stomp
	.4byte gMoveDescription_DoubleKick
	.4byte gMoveDescription_MegaKick
	.4byte gMoveDescription_JumpKick
	.4byte gMoveDescription_RollingKick
	.4byte gMoveDescription_SandAttack
	.4byte gMoveDescription_Headbutt
	.4byte gMoveDescription_HornAttack
	.4byte gMoveDescription_FuryAttack
	.4byte gMoveDescription_HornDrill
	.4byte gMoveDescription_Tackle
	.4byte gMoveDescription_BodySlam
	.4byte gMoveDescription_Wrap
	.4byte gMoveDescription_TakeDown
	.4byte gMoveDescription_Thrash
	.4byte gMoveDescription_DoubleEdge
	.4byte gMoveDescription_TailWhip
	.4byte gMoveDescription_PoisonSting
	.4byte gMoveDescription_Twineedle
	.4byte gMoveDescription_PinMissile
	.4byte gMoveDescription_Leer
	.4byte gMoveDescription_Bite
	.4byte gMoveDescription_Growl
	.4byte gMoveDescription_Roar
	.4byte gMoveDescription_Sing
	.4byte gMoveDescription_Supersonic
	.4byte gMoveDescription_SonicBoom
	.4byte gMoveDescription_Disable
	.4byte gMoveDescription_Acid
	.4byte gMoveDescription_Ember
	.4byte gMoveDescription_Flamethrower
	.4byte gMoveDescription_Mist
	.4byte gMoveDescription_WaterGun
	.4byte gMoveDescription_HydroPump
	.4byte gMoveDescription_Surf
	.4byte gMoveDescription_IceBeam
	.4byte gMoveDescription_Blizzard
	.4byte gMoveDescription_Psybeam
	.4byte gMoveDescription_BubbleBeam
	.4byte gMoveDescription_AuroraBeam
	.4byte gMoveDescription_HyperBeam
	.4byte gMoveDescription_Peck
	.4byte gMoveDescription_DrillPeck
	.4byte gMoveDescription_Submission
	.4byte gMoveDescription_LowKick
	.4byte gMoveDescription_Counter
	.4byte gMoveDescription_SeismicToss
	.4byte gMoveDescription_Strength
	.4byte gMoveDescription_Absorb
	.4byte gMoveDescription_MegaDrain
	.4byte gMoveDescription_LeechSeed
	.4byte gMoveDescription_Growth
	.4byte gMoveDescription_RazorLeaf
	.4byte gMoveDescription_SolarBeam
	.4byte gMoveDescription_PoisonPowder
	.4byte gMoveDescription_StunSpore
	.4byte gMoveDescription_SleepPowder
	.4byte gMoveDescription_PetalDance
	.4byte gMoveDescription_StringShot
	.4byte gMoveDescription_DragonRage
	.4byte gMoveDescription_FireSpin
	.4byte gMoveDescription_ThunderShock
	.4byte gMoveDescription_Thunderbolt
	.4byte gMoveDescription_ThunderWave
	.4byte gMoveDescription_Thunder
	.4byte gMoveDescription_RockThrow
	.4byte gMoveDescription_Earthquake
	.4byte gMoveDescription_Fissure
	.4byte gMoveDescription_Dig
	.4byte gMoveDescription_Toxic
	.4byte gMoveDescription_Confusion
	.4byte gMoveDescription_Psychic
	.4byte gMoveDescription_Hypnosis
	.4byte gMoveDescription_Meditate
	.4byte gMoveDescription_Agility
	.4byte gMoveDescription_QuickAttack
	.4byte gMoveDescription_Rage
	.4byte gMoveDescription_Teleport
	.4byte gMoveDescription_NightShade
	.4byte gMoveDescription_Mimic
	.4byte gMoveDescription_Screech
	.4byte gMoveDescription_DoubleTeam
	.4byte gMoveDescription_Recover
	.4byte gMoveDescription_Harden
	.4byte gMoveDescription_Minimize
	.4byte gMoveDescription_Smokescreen
	.4byte gMoveDescription_ConfuseRay
	.4byte gMoveDescription_Withdraw
	.4byte gMoveDescription_DefenseCurl
	.4byte gMoveDescription_Barrier
	.4byte gMoveDescription_LightScreen
	.4byte gMoveDescription_Haze
	.4byte gMoveDescription_Reflect
	.4byte gMoveDescription_FocusEnergy
	.4byte gMoveDescription_Bide
	.4byte gMoveDescription_Metronome
	.4byte gMoveDescription_MirrorMove
	.4byte gMoveDescription_SelfDestruct
	.4byte gMoveDescription_EggBomb
	.4byte gMoveDescription_Lick
	.4byte gMoveDescription_Smog
	.4byte gMoveDescription_Sludge
	.4byte gMoveDescription_BoneClub
	.4byte gMoveDescription_FireBlast
	.4byte gMoveDescription_Waterfall
	.4byte gMoveDescription_Clamp
	.4byte gMoveDescription_Swift
	.4byte gMoveDescription_SkullBash
	.4byte gMoveDescription_SpikeCannon
	.4byte gMoveDescription_Constrict
	.4byte gMoveDescription_Amnesia
	.4byte gMoveDescription_Kinesis
	.4byte gMoveDescription_SoftBoiled
	.4byte gMoveDescription_HiJumpKick
	.4byte gMoveDescription_Glare
	.4byte gMoveDescription_DreamEater
	.4byte gMoveDescription_PoisonGas
	.4byte gMoveDescription_Barrage
	.4byte gMoveDescription_LeechLife
	.4byte gMoveDescription_LovelyKiss
	.4byte gMoveDescription_SkyAttack
	.4byte gMoveDescription_Transform
	.4byte gMoveDescription_Bubble
	.4byte gMoveDescription_DizzyPunch
	.4byte gMoveDescription_Spore
	.4byte gMoveDescription_Flash
	.4byte gMoveDescription_Psywave
	.4byte gMoveDescription_Splash
	.4byte gMoveDescription_AcidArmor
	.4byte gMoveDescription_Crabhammer
	.4byte gMoveDescription_Explosion
	.4byte gMoveDescription_FurySwipes
	.4byte gMoveDescription_Bonemerang
	.4byte gMoveDescription_Rest
	.4byte gMoveDescription_RockSlide
	.4byte gMoveDescription_HyperFang
	.4byte gMoveDescription_Sharpen
	.4byte gMoveDescription_Conversion
	.4byte gMoveDescription_TriAttack
	.4byte gMoveDescription_SuperFang
	.4byte gMoveDescription_Slash
	.4byte gMoveDescription_Substitute
	.4byte gMoveDescription_Struggle
	.4byte gMoveDescription_Sketch
	.4byte gMoveDescription_TripleKick
	.4byte gMoveDescription_Thief
	.4byte gMoveDescription_SpiderWeb
	.4byte gMoveDescription_MindReader
	.4byte gMoveDescription_Nightmare
	.4byte gMoveDescription_FlameWheel
	.4byte gMoveDescription_Snore
	.4byte gMoveDescription_Curse
	.4byte gMoveDescription_Flail
	.4byte gMoveDescription_Conversion2
	.4byte gMoveDescription_Aeroblast
	.4byte gMoveDescription_CottonSpore
	.4byte gMoveDescription_Reversal
	.4byte gMoveDescription_Spite
	.4byte gMoveDescription_PowderSnow
	.4byte gMoveDescription_Protect
	.4byte gMoveDescription_MachPunch
	.4byte gMoveDescription_ScaryFace
	.4byte gMoveDescription_FaintAttack
	.4byte gMoveDescription_SweetKiss
	.4byte gMoveDescription_BellyDrum
	.4byte gMoveDescription_SludgeBomb
	.4byte gMoveDescription_MudSlap
	.4byte gMoveDescription_Octazooka
	.4byte gMoveDescription_Spikes
	.4byte gMoveDescription_ZapCannon
	.4byte gMoveDescription_Foresight
	.4byte gMoveDescription_DestinyBond
	.4byte gMoveDescription_PerishSong
	.4byte gMoveDescription_IcyWind
	.4byte gMoveDescription_Detect
	.4byte gMoveDescription_BoneRush
	.4byte gMoveDescription_LockOn
	.4byte gMoveDescription_Outrage
	.4byte gMoveDescription_Sandstorm
	.4byte gMoveDescription_GigaDrain
	.4byte gMoveDescription_Endure
	.4byte gMoveDescription_Charm
	.4byte gMoveDescription_Rollout
	.4byte gMoveDescription_FalseSwipe
	.4byte gMoveDescription_Swagger
	.4byte gMoveDescription_MilkDrink
	.4byte gMoveDescription_Spark
	.4byte gMoveDescription_FuryCutter
	.4byte gMoveDescription_SteelWing
	.4byte gMoveDescription_MeanLook
	.4byte gMoveDescription_Attract
	.4byte gMoveDescription_SleepTalk
	.4byte gMoveDescription_HealBell
	.4byte gMoveDescription_Return
	.4byte gMoveDescription_Present
	.4byte gMoveDescription_Frustration
	.4byte gMoveDescription_Safeguard
	.4byte gMoveDescription_PainSplit
	.4byte gMoveDescription_SacredFire
	.4byte gMoveDescription_Magnitude
	.4byte gMoveDescription_DynamicPunch
	.4byte gMoveDescription_Megahorn
	.4byte gMoveDescription_DragonBreath
	.4byte gMoveDescription_BatonPass
	.4byte gMoveDescription_Encore
	.4byte gMoveDescription_Pursuit
	.4byte gMoveDescription_RapidSpin
	.4byte gMoveDescription_SweetScent
	.4byte gMoveDescription_IronTail
	.4byte gMoveDescription_MetalClaw
	.4byte gMoveDescription_VitalThrow
	.4byte gMoveDescription_MorningSun
	.4byte gMoveDescription_Synthesis
	.4byte gMoveDescription_Moonlight
	.4byte gMoveDescription_HiddenPower
	.4byte gMoveDescription_CrossChop
	.4byte gMoveDescription_Twister
	.4byte gMoveDescription_RainDance
	.4byte gMoveDescription_SunnyDay
	.4byte gMoveDescription_Crunch
	.4byte gMoveDescription_MirrorCoat
	.4byte gMoveDescription_PsychUp
	.4byte gMoveDescription_ExtremeSpeed
	.4byte gMoveDescription_AncientPower
	.4byte gMoveDescription_ShadowBall
	.4byte gMoveDescription_FutureSight
	.4byte gMoveDescription_RockSmash
	.4byte gMoveDescription_Whirlpool
	.4byte gMoveDescription_BeatUp
	.4byte gMoveDescription_FakeOut
	.4byte gMoveDescription_Uproar
	.4byte gMoveDescription_Stockpile
	.4byte gMoveDescription_SpitUp
	.4byte gMoveDescription_Swallow
	.4byte gMoveDescription_HeatWave
	.4byte gMoveDescription_Hail
	.4byte gMoveDescription_Torment
	.4byte gMoveDescription_Flatter
	.4byte gMoveDescription_WillOWisp
	.4byte gMoveDescription_Memento
	.4byte gMoveDescription_Facade
	.4byte gMoveDescription_FocusPunch
	.4byte gMoveDescription_SmellingSalt
	.4byte gMoveDescription_FollowMe
	.4byte gMoveDescription_NaturePower
	.4byte gMoveDescription_Charge
	.4byte gMoveDescription_Taunt
	.4byte gMoveDescription_HelpingHand
	.4byte gMoveDescription_Trick
	.4byte gMoveDescription_RolePlay
	.4byte gMoveDescription_Wish
	.4byte gMoveDescription_Assist
	.4byte gMoveDescription_Ingrain
	.4byte gMoveDescription_Superpower
	.4byte gMoveDescription_MagicCoat
	.4byte gMoveDescription_Recycle
	.4byte gMoveDescription_Revenge
	.4byte gMoveDescription_BrickBreak
	.4byte gMoveDescription_Yawn
	.4byte gMoveDescription_KnockOff
	.4byte gMoveDescription_Endeavor
	.4byte gMoveDescription_Eruption
	.4byte gMoveDescription_SkillSwap
	.4byte gMoveDescription_Imprison
	.4byte gMoveDescription_Refresh
	.4byte gMoveDescription_Grudge
	.4byte gMoveDescription_Snatch
	.4byte gMoveDescription_SecretPower
	.4byte gMoveDescription_Dive
	.4byte gMoveDescription_ArmThrust
	.4byte gMoveDescription_Camouflage
	.4byte gMoveDescription_TailGlow
	.4byte gMoveDescription_LusterPurge
	.4byte gMoveDescription_MistBall
	.4byte gMoveDescription_FeatherDance
	.4byte gMoveDescription_TeeterDance
	.4byte gMoveDescription_BlazeKick
	.4byte gMoveDescription_MudSport
	.4byte gMoveDescription_IceBall
	.4byte gMoveDescription_NeedleArm
	.4byte gMoveDescription_SlackOff
	.4byte gMoveDescription_HyperVoice
	.4byte gMoveDescription_PoisonFang
	.4byte gMoveDescription_CrushClaw
	.4byte gMoveDescription_BlastBurn
	.4byte gMoveDescription_HydroCannon
	.4byte gMoveDescription_MeteorMash
	.4byte gMoveDescription_Astonish
	.4byte gMoveDescription_WeatherBall
	.4byte gMoveDescription_Aromatherapy
	.4byte gMoveDescription_FakeTears
	.4byte gMoveDescription_AirCutter
	.4byte gMoveDescription_Overheat
	.4byte gMoveDescription_OdorSleuth
	.4byte gMoveDescription_RockTomb
	.4byte gMoveDescription_SilverWind
	.4byte gMoveDescription_MetalSound
	.4byte gMoveDescription_GrassWhistle
	.4byte gMoveDescription_Tickle
	.4byte gMoveDescription_CosmicPower
	.4byte gMoveDescription_WaterSpout
	.4byte gMoveDescription_SignalBeam
	.4byte gMoveDescription_ShadowPunch
	.4byte gMoveDescription_Extrasensory
	.4byte gMoveDescription_SkyUppercut
	.4byte gMoveDescription_SandTomb
	.4byte gMoveDescription_SheerCold
	.4byte gMoveDescription_MuddyWater
	.4byte gMoveDescription_BulletSeed
	.4byte gMoveDescription_AerialAce
	.4byte gMoveDescription_IcicleSpear
	.4byte gMoveDescription_IronDefense
	.4byte gMoveDescription_Block
	.4byte gMoveDescription_Howl
	.4byte gMoveDescription_DragonClaw
	.4byte gMoveDescription_FrenzyPlant
	.4byte gMoveDescription_BulkUp
	.4byte gMoveDescription_Bounce
	.4byte gMoveDescription_MudShot
	.4byte gMoveDescription_PoisonTail
	.4byte gMoveDescription_Covet
	.4byte gMoveDescription_VoltTackle
	.4byte gMoveDescription_MagicalLeaf
	.4byte gMoveDescription_WaterSport
	.4byte gMoveDescription_CalmMind
	.4byte gMoveDescription_LeafBlade
	.4byte gMoveDescription_DragonDance
	.4byte gMoveDescription_RockBlast
	.4byte gMoveDescription_ShockWave
	.4byte gMoveDescription_WaterPulse
	.4byte gMoveDescription_DoomDesire
	.4byte gMoveDescription_PsychoBoost
