Text_ObtainedTheItem: @ 81A0C68
	.string "Obtained the {STR_VAR_2}.$"

Text_TheBagIsFull:: @ 81A0C79
	.string "The BAG is full...$"

Text_PutItemInPocket: @ 81A0C8C
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

Text_FoundOneItem: @ 81A0CB1
	.string "{PLAYER} found one {STR_VAR_2}!$"

Text_TooBadBagIsFull:
	.string "Too bad!\n"
	.string "The BAG is full...$"

Text_ObtainedTheDecor: @ 81A0CDE
	.string "Obtained the {STR_VAR_2}.$"

Text_NoRoomLeftForAnother:: @ 81A0CEF
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}...$"

Text_TheDecorWasTransferredToThePC: @ 81A0D1F
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
