Text_BootUpPC: @ 81A09EC
	.string "{PLAYER} booted up the PC.$"

Text_WhichPCShouldBeAccessed:: @ 81A0A01
	.string "Which PC should be accessed?$"

Text_AccessedSomeonesPC: @ 81A0A1E
	.string "Accessed someone's PC.$"

Text_StorageSystemOpened: @ 81A0A35
	.string "POKéMON Storage System opened.$"

Text_AccessedPlayersPC: @ 81A0A54
	.string "Accessed {PLAYER}'s PC.$"

Text_AccessedLanettesPC: @ 81A0A66
	.string "Accessed LANETTE's PC.$"
