Route101_Text_1C4449:: @ 81C4449
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Have you come to show me how your\n"
	.string "POKéDEX is coming along?$"

Route101_Text_1C449B:: @ 81C449B
	.string "Hm? Oh, you haven’t caught enough\n"
	.string "POKéMON to make it worthwhile.$"

Route101_Text_1C44DC:: @ 81C44DC
	.string "Hmhm...\p"
	.string "So, you’ve seen {STR_VAR_1} POKéMON,\n"
	.string "and you’ve caught {STR_VAR_2} POKéMON...$"

gBirchDexRatingText_LessThan10:: @ 81C4520
	.string "You should go into grassy areas more\n"
	.string "and look for POKéMON more carefully.$"

gBirchDexRatingText_LessThan20:: @ 81C456A
	.string "I guess you’re getting the hang of it.\n"
	.string "But, it gets harder from here.$"

gBirchDexRatingText_LessThan30:: @ 81C45B0
	.string "Some POKéMON only appear in certain\n"
	.string "areas. You’ll need to be persistent.$"

gBirchDexRatingText_LessThan40:: @ 81C45F9
	.string "Well, it could use more quantity, but\n"
	.string "this is looking more like a POKéDEX now.$"

gBirchDexRatingText_LessThan50:: @ 81C4648
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60:: @ 81C467E
	.string "Are you using any RODS?\n"
	.string "There are many POKéMON in the sea.$"

gBirchDexRatingText_LessThan70:: @ 81C46B9
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80:: @ 81C46FE
	.string "This is going to be a fantastic POKéDEX.\n"
	.string "That’s the feeling I’m getting.$"

gBirchDexRatingText_LessThan90:: @ 81C4747
	.string "You’ve collected this many...\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100:: @ 81C4780
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110:: @ 81C47DF
	.string "You’ve finally reached the 100-kind\n"
	.string "mark. This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120:: @ 81C4828
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130:: @ 81C4863
	.string "You should get some more POKéMON by\n"
	.string "trading with others.$"

gBirchDexRatingText_LessThan140:: @ 81C489C
	.string "I’ve heard of POKéMON that evolve when\n"
	.string "they come to fully love their TRAINERS.$"

gBirchDexRatingText_LessThan150:: @ 81C48EB
	.string "I had no idea that there were so many\n"
	.string "POKéMON species in the HOENN region.$"

gBirchDexRatingText_LessThan160:: @ 81C4936
	.string "On occasion, some POKéMON appear in\n"
	.string "large numbers like wild outbreaks.\l"
	.string "Don’t miss opportunities like those.$"

gBirchDexRatingText_LessThan170:: @ 81C49A2
	.string "One can get a very good idea about the\n"
	.string "POKéMON of the HOENN region by looking\l"
	.string "through your POKéDEX.$"

gBirchDexRatingText_LessThan180:: @ 81C4A06
	.string "I’d say you already qualify as a POKéMON\n"
	.string "PROFESSOR, and a good one, too!$"

gBirchDexRatingText_LessThan190:: @ 81C4A4F
	.string "With a POKéDEX this complete, you’re\n"
	.string "a real professional at this!$"

gBirchDexRatingText_LessThan200:: @ 81C4A91
	.string "You’re very close to completing this\n"
	.string "POKéDEX. I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted:: @ 81C4ADA
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"

Route101_Text_1C4B05:: @ 81C4B05
	.string "Hmhm...\n"
	.string "On a nationwide basis...\p"
	.string "You’ve seen {STR_VAR_1} POKéMON,\n"
	.string "and you’ve caught {STR_VAR_2} POKéMON...$"
