Route101_Text_1C4449:: @ 81C4449
	.string "PROF. BIRK: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte mit\n"
	.string "dem POKéDEX zeigen?$"

Route101_Text_1C449B:: @ 81C449B
	.string "Ach? Du hast erst so wenige POKéMON\n"
	.string "gefangen, dass es sich nicht lohnt,\l"
	.string "ihn mir zu zeigen?$"

Route101_Text_1C44DC:: @ 81C44DC
	.string "Hmhm...\p"
	.string "Oh, du hast {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen...$"

UnknownString_81C4520: @ 81C4520
gUnknown_081C4520:: @ 81C4520
	.string "Du solltest mehr ins hohe Gras gehen\n"
	.string "und mehr auf POKéMON achten.$"

UnknownString_81C456A: @ 81C456A
gUnknown_081C456A:: @ 81C456A
	.string "So langsam bekommst du den Bogen raus.\n"
	.string "Aber es wird immer schwieriger werden!$"

UnknownString_81C45B0: @ 81C45B0
gUnknown_081C45B0:: @ 81C45B0
	.string "Einige POKéMON tauchen nur in be-\n"
	.string "stimmten Regionen auf. Hab nur Geduld.$"

UnknownString_81C45F9: @ 81C45F9
gUnknown_081C45F9:: @ 81C45F9
	.string "Nun, er könnte mehr Einträge enthalten,\n"
	.string "aber es sieht schon eher nach einem\l"
	.string "POKéDEX aus.$"

UnknownString_81C4648: @ 81C4648
gUnknown_081C4648:: @ 81C4648
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

UnknownString_81C467E: @ 81C467E
gUnknown_081C467E:: @ 81C467E
	.string "Verwendest du irgendwelche ANGELN?\n"
	.string "Hier gibt es viele POKéMON im Meer.$"

UnknownString_81C46B9: @ 81C46B9
gUnknown_081C46B9:: @ 81C46B9
	.string "Statt die POKéMON nur zu fangen, wie\n"
	.string "wäre es, sie sich entwickeln zu lassen?$"

UnknownString_81C46FE: @ 81C46FE
gUnknown_081C46FE:: @ 81C46FE
	.string "Der POKéDEX wird einfach fantastisch.\n"
	.string "Das habe ich im Gefühl...$"

UnknownString_81C4747: @ 81C4747
gUnknown_081C4747:: @ 81C4747
	.string "Du hast so viele gefangen...\n"
	.string "Du hast ein außergewöhnliches Talent!$"

UnknownString_81C4780: @ 81C4780
gUnknown_081C4780:: @ 81C4780
	.string "Warst du schon mal in der SAFARI-ZONE?\p"
	.string "Ich habe gehört, es gibt POKéMON,\n"
	.string "die man nur dort finden kann.$"

UnknownString_81C47DF: @ 81C47DF
gUnknown_081C47DF:: @ 81C47DF
	.string "Du hast die 100er Marke überschritten!\n"
	.string "Das ist ein beeindruckender POKéDEX!$"

UnknownString_81C4828: @ 81C4828
gUnknown_081C4828:: @ 81C4828
	.string "Es gibt auch POKéMON, die man durch den\n"
	.string "Einsatz von ZERTRÜMMERER findet.$"

UnknownString_81C4863: @ 81C4863
gUnknown_081C4863:: @ 81C4863
	.string "Du solltest einige POKéMON fangen und\n"
	.string "sie mit anderen tauschen.$"

UnknownString_81C489C: @ 81C489C
gUnknown_081C489C:: @ 81C489C
	.string "Ich habe von POKéMON gehört, die sich\n"
	.string "entwickeln, wenn sie ihren TRAINER sehr\l"
	.string "lieben.$"

UnknownString_81C48EB: @ 81C48EB
gUnknown_081C48EB:: @ 81C48EB
	.string "Ich hatte keine Ahnung, dass es in der\n"
	.string "HOENN-Region so viele verschiedene\l"
	.string "POKéMON-Arten gibt.$"

UnknownString_81C4936: @ 81C4936
gUnknown_081C4936:: @ 81C4936
	.string "Manchmal erscheinen einige POKéMON in\n"
	.string "großer Anzahl, wie bei einem Ausbruch.\l"
	.string "Das solltest du nicht verpassen!$"

UnknownString_81C49A2: @ 81C49A2
gUnknown_081C49A2:: @ 81C49A2
	.string "Dein POKéDEX liefert einen erstaunlich\n"
	.string "guten Einblick in die POKéMON der\l"
	.string "HOENN-Region!$"

UnknownString_81C4A06: @ 81C4A06
gUnknown_081C4A06:: @ 81C4A06
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter POKéMON-PROFESSOR qualifiziert.$"

UnknownString_81C4A4F: @ 81C4A4F
gUnknown_081C4A4F:: @ 81C4A4F
	.string "Mit diesem POKéDEX, der schon so weit\n"
	.string "gediehen ist, bist du ein echter Profi.$"

UnknownString_81C4A91: @ 81C4A91
gUnknown_081C4A91:: @ 81C4A91
	.string "Du bist sehr nahe dran, den POKéDEX zu\n"
	.string "vervollständigen. Das fühle ich einfach.$"

UnknownString_81C4ADA: @ 81C4ADA
gUnknown_081C4ADA:: @ 81C4ADA
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein POKéDEX ist vollständig!$"

Route101_Text_1C4B05:: @ 81C4B05
	.string "Hmhm...\n"
	.string "Auf nationaler Ebene...\p"
	.string "Hast du {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen...$"
