UnknownString_81C34B2: @ 81C34B2
	.string "Möchtest du die SAFARI-ZONE jetzt\n"
	.string "verlassen?$"

UnknownString_81C34E4: @ 81C34E4
	.string "Ding Dong! Die Zeit ist abgelaufen!\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

UnknownString_81C3514: @ 81C3514
	.string "Du hast keine SAFARIBÄLLE mehr.\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

UnknownString_81C354E: @ 81C354E
	.string "Möchtest du einen {POKEBLOCK} in den\n"
	.string "{POKEBLOCK}NAPF legen?$"

UnknownString_81C3583: @ 81C3583
	.string "Dein {STR_VAR_1} befindet sich\n"
	.string "noch in unserer Obhut.$"

UnknownString_81C35A9: @ 81C35A9
	.string "{STR_VAR_1} wurde in den {POKEBLOCK}-\n"
	.string "NAPF gelegt.$"

Route121_SafariZoneEntrance_Text_1C35D0:: @ 81C35D0
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Hier bekommst du viele POKéMON zu\n"
	.string "Gesicht, die sehr selten in der HOENN-\l"
	.string "Region sind.\p"
	.string "Du kannst sie in ihrer ganzen Wildheit\n"
	.string "und ungezähmt in ihrer natürlichen\l"
	.string "Umgebung beobachten.\p"
	.string "Wir haben unsere Tore für die POKéMON-\n"
	.string "TRAINER geöffnet.\p"
	.string "Fangt euch POKéMON. Und behaltet sie!\p"
	.string "Kommt und genießt die Welt der\n"
	.string "SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_1C3704:: @ 81C3704
	.string "Willkommen in der SAFARI-ZONE!\n"
	.string "Bist du zum ersten Mal hier?$"

Route121_SafariZoneEntrance_Text_1C373C:: @ 81C373C
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_1C375F:: @ 81C375F
	.string "Sobald du die SAFARI-ZONE betrittst,\n"
	.string "stehen dir 30 SAFARIBÄLLE zur Ver-\l"
	.string "fügung, um POKéMON zu fangen.\p"
	.string "Das SAFARI-Spiel ist vorbei, sobald du\n"
	.string "deine SAFARIBÄLLE verbraucht oder\l"
	.string "500 Schritte gemacht hast.\p"
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_1C3832:: @ 81C3832
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Alles, was du fangen kannst für nur\n"
	.string "¥500! Möchtest du es einmal probieren?$"

Route121_SafariZoneEntrance_Text_1C3895:: @ 81C3895
	.string "Okay.\n"
	.string "Bitte beehre uns doch später einmal.$"

Route121_SafariZoneEntrance_Text_1C38B5:: @ 81C38B5
	.string "Du hast nicht genug Geld dabei.\n"
	.string "Tut mir Leid.$"

Route121_SafariZoneEntrance_Text_1C38D9:: @ 81C38D9
	.string "Das macht dann ¥500, bitte.$"

Route121_SafariZoneEntrance_Text_1C38F4:: @ 81C38F4
	.string "Hier sind deine SAFARIBÄLLE.$"

Route121_SafariZoneEntrance_Text_1C3910:: @ 81C3910
	.string "{PLAYER} erhält 30 SAFARIBÄLLE.$"

Route121_SafariZoneEntrance_Text_1C392D:: @ 81C392D
	.string "Wir geben dir Bescheid, wenn das Spiel\n"
	.string "vorbei ist.\p"
	.string "Bis dahin wünschen wir viel Spaß!\n"
	.string "Und auf geht’s in die Wildnis!$"

Route121_SafariZoneEntrance_Text_1C39A3:: @ 81C39A3
	.string "Entschuldigung!\n"
	.string "Deine PC-BOXEN sind voll.$"

Route121_SafariZoneEntrance_Text_1C39C3:: @ 81C39C3
	.string "Entschuldigung!\n"
	.string "Du besitzt keine {POKEBLOCK}BOX.\p"
	.string "Dein SAFARI-Spiel wäre viel erfolg-\n"
	.string "reicher, wenn du {POKEBLOCK} benutzen\l"
	.string "würdest.\p"
	.string "Bitte besorge dir doch eine {POKEBLOCK}BOX.$"

SafariZone_Southeast_Text_1C3A56:: @ 81C3A56
	.string "Du hast noch Zeit übrig. Möchtest du\n"
	.string "die SAFARI-ZONE jetzt verlassen?$"

SafariZone_Southeast_Text_1C3A9C:: @ 81C3A9C
	.string "Viel Vergnügen bei dem Rest deines\n"
	.string "wilden Abenteuers!$"

SafariZone_Southeast_Text_1C3ACA:: @ 81C3ACA
	.string "Okay.\p"
	.string "Ich nehme die verbleibenden\n"
	.string "SAFARIBÄLLE zurück.\p"
	.string "Vielen Dank für deine Teilnahme.\n"
	.string "Komm bald wieder!$"

SafariZone_Southeast_Text_1C3B2D:: @ 81C3B2D
	.string "Viel Glück!\p"
	.string "Wenn du irgendetwas brauchst, zögere\n"
	.string "nicht, mich anzusprechen!$"

SafariZone_Southeast_Text_1C3B71:: @ 81C3B71
	.string "Weißt du was?\p"
	.string "Wenn du einen {POKEBLOCK} in diese Kiste\n"
	.string "dort legst, werden POKéMON angelockt.$"

SafariZone_Southeast_Text_1C3BBD:: @ 81C3BBD
	.string "Ich wollte noch weiter hinein, aber\n"
	.string "ich habe mein RAD vergessen.\p"
	.string "Irgendetwas sagt mir, dass in den abge-\n"
	.string "legenen Gegenden seltene POKéMON\l"
	.string "leben.$"

SafariZone_Southwest_Text_1C3C39:: @ 81C3C39
	.string "Manchmal, wenn ich einem POKéMON einen\n"
	.string "{POKEBLOCK} zuwerfe, ignoriert es das total.\p"
	.string "Ob POKéMON auch manche Dinge mögen\n"
	.string "und manche nicht? Wie wir Menschen?$"

SafariZone_Northwest_Text_1C3CAE:: @ 81C3CAE
	.string "Hechel... Keuch...\n"
	.string "Ich... bin hierher gekommen... aber...\p"
	.string "Ich bin erschöpft... Japs... Ich habe\n"
	.string "keine Energie, ein POKéMON zu fangen.$"

SafariZone_Northeast_Text_1C3D19:: @ 81C3D19
	.string "Ich habe eine Mission. Ich will WASSER-\n"
	.string "POKéMON fangen, die es in HOENN nicht\l"
	.string "gibt.\p"
	.string "Weißt du zufällig, wo hier der See ist?$"

SafariZone_Northeast_Text_1C3D80:: @ 81C3D80
	.string "Ich will viele seltene POKéMON fangen\n"
	.string "und mit meinen Freunden tauschen.$"

SafariZone_Southeast_Text_1C3DCE:: @ 81C3DCE
	.string "Ich habe einen {POKEBLOCK} in den {POKEBLOCK}-\n"
	.string "NAPF gelegt. Er ist verschwunden.\p"
	.string "Ein POKéMON muss ihn gefuttert haben,\n"
	.string "ohne dass ich das gemerkt habe.$"

Route121_SafariZoneEntrance_Text_1C3E4B:: @ 81C3E4B
	.string "TIPP für TRAINER in der SAFARI-ZONE!\p"
	.string "Wirf POKéMON {POKEBLOCK} zu, dann ergreifen\n"
	.string "sie nicht so schnell die Flucht.$"

SafariZone_Southwest_Text_1C3EA3:: @ 81C3EA3
	.string "“Erhole deine gemarterten Füße.”\n"
	.string "RASTHAUS$"

SafariZone_RestHouse_Text_1C3EC9:: @ 81C3EC9
	.string "Ich habe keine {POKEBLOCK}, aber ich habe\n"
	.string "trotzdem viele POKéMON gefangen.\p"
	.string "Du kannst deine Chancen erhöhen, indem\n"
	.string "du näher an das POKéMON herangehst,\l"
	.string "bevor du den SAFARIBALL wirfst.$"

SafariZone_RestHouse_Text_1C3F71:: @ 81C3F71
	.string "POKéMON fliehen nicht so schnell, wenn\n"
	.string "man ihnen {POKEBLOCK} zuwirft.\p"
	.string "POKéMON, die von Natur aus nicht schnell\n"
	.string "fliehen, braucht man sie nicht\l"
	.string "unbedingt zuzuwerfen.$"

SafariZone_RestHouse_Text_1C3FF4:: @ 81C3FF4
	.string "Wird ein {POKEBLOCK} in den NAPF gelegt,\n"
	.string "werden POKéMON angelockt.\p"
	.string "Ich glaube, POKéMON mit der gleichen\n"
	.string "Wesensart werden von ähnlichen {POKEBLOCK}N\l"
	.string "angezogen.$"
