SecretBase_Text_AllDecorationsWillBeReturned: @ 81A38FB
	.string "All decorations and furniture in your\n"
	.string "SECRET BASE will be returned to your PC.\p"
	.string "Is that okay?$"

SecretBase_Text_WantToRegisterSecretBase: @ 81A3958
	.string "Do you want to register\n"
	.string "{STR_VAR_1}'s SECRET BASE?$"

SecretBase_Text_AlreadyRegisteredDelete: @ 81A3982
	.string "This data is already registered.\n"
	.string "Would you like to delete it?$"

SecretBase_Text_TooManyBasesDeleteSome: @ 81A39C0
	.string "Up to 10 locations can be registered.\p"
	.string "Delete a location if you want to\n"
	.string "register another location.$"

SecretBase_Text_RegistrationCompleted: @ 81A3A22
	.string "Registration completed.$"

SecretBase_Text_DataUnregistered: @ 81A3A3A
	.string "Data has been unregistered.$"

UnknownString_81A3A56: @ 81A3A56
	.string "There are no decorations...$"

SecretBase_Text_BootUpPC: @ 81A3A72
	.string "{PLAYER} booted up the PC.$"

SecretBase_Text_WhatWouldYouLikeToDo: @ 81A3A87
	.string "What would you like to do?$"

SecretBase_Text_RegistryInfo: @ 81A3AA2
	.string "The registered SECRET BASE will remain\n"
	.string "unless the owner moves away.\p"
	.string "If it is removed from the registry,\n"
	.string "another SECRET BASE may take its place.\p"
	.string "Up to ten locations can be registered.{PAUSE_UNTIL_PRESS}$"

SecretBase_Text_BattleTowerShield: @ 81A3B5B
	.string "A shield of {STR_VAR_2} that marks winning\n"
	.string "{STR_VAR_1} times in a row at the BATTLE TOWER.$"

SecretBase_Text_ToyTV: @ 81A3BA4
	.string "A realistic toy TV. It could be easily\n"
	.string "mistaken for the real thing.$"

SecretBase_Text_SeedotTV: @ 81A3BE8
	.string "A toy TV shaped like a SEEDOT.\n"
	.string "It looks ready to roll away on its own...$"

SecretBase_Text_SkittyTV: @ 81A3C31
	.string "A toy TV shaped like a SKITTY.\n"
	.string "It looks ready to stroll away...$"

UnknownString_81A3C71: @ 81A3C71
	.string "You may only make one SECRET BASE.\p"
	.string "Would you like to move from the SECRET\n"
	.string "BASE near {STR_VAR_1}?$"

UnknownString_81A3CC9: @ 81A3CC9
	.string "Moving completed.\p"
	.string "Would you like to use the SECRET POWER?$"
