Route111_Text_1A3520:: @ 81A3520
	.string "Was das ist?\n"
	.string "Was ich hier mache?\p"
	.string "Ich überlege, ob ich mir hier mein\n"
	.string "eigenes Refugium mit Hilfe einer\l"
	.string "POKéMON-Attacke einrichte.\p"
	.string "Genau! Ich gebe dir diese TM. Richte\n"
	.string "dir damit auch dein eigenes Reich ein!$"

Route111_Text_1A35C5:: @ 81A35C5
	.string "Suche dir einen Baum, der aussieht, als\n"
	.string "ob er einige Äste verlieren würde.\p"
	.string "Setze davor GEHEIMPOWER ein. Einige\n"
	.string "Äste werden sich öffnen und du\l"
	.string "kannst dann den Baum hinaufklettern.\p"
	.string "Du findest dort einen großen Raum, den\n"
	.string "du nach eigenem Geschmack einrichten\l"
	.string "kannst.\p"
	.string "Das ist dein eigener geheimer Raum...\n"
	.string "Eine GEHEIMBASIS!\p"
	.string "Du solltest dir auch eine einrichten.\p"
	.string "Du musst dir deine GEHEIMBASIS nicht\n"
	.string "unbedingt in einem Baum einrichten.\p"
	.string "Setze GEHEIMPOWER an steinigen\n"
	.string "Wänden ein, die Einkerbungen haben.\p"
	.string "Ich schaue mich jetzt nach weiteren\n"
	.string "Orten um. Tschüss!$"

Route111_Text_1A37B5:: @ 81A37B5
	.string "Oh, das willst du nicht haben? Wenn du\n"
	.string "deine Meinung änderst, sag Bescheid.$"

Route111_Text_1A37F6:: @ 81A37F6
	.string "Oh, dafür hast du keinen Platz mehr.\p"
	.string "Ich verwahre es für dich. Hol es dir\n"
	.string "später ab, einverstanden?$"
