MauvilleCity_PokemonCenter_1F_Text_1AECC6:: @ 81AECC6
	.string "Ich bin der GESCHICHTENERZÄHLER.\n"
	.string "Ich erzähle dir die Geschichten von\l"
	.string "legendären TRAINERN.\p"
	.string "Soll ich dir etwas erzählen?$"

MauvilleCity_PokemonCenter_1F_Text_1AED1D:: @ 81AED1D
	.string "Oh...\n"
	.string "Keiner mag mich...$"

MauvilleCity_PokemonCenter_1F_Text_1AED35:: @ 81AED35
	.string "Ich kenne viele dieser Legenden.\n"
	.string "Welche möchtest du hören?$"

MauvilleCity_PokemonCenter_1F_Text_1AED70:: @ 81AED70
	.string "Aber ich weiß nichts über legendäre\n"
	.string "TRAINER. Also habe ich keine Ge-\l"
	.string "schichte auf Lager.\p"
	.string "Wo findet man wohl einen TRAINER, der\n"
	.string "einer lebenden Legende gleicht?$"

MauvilleCity_PokemonCenter_1F_Text_1AEDE8:: @ 81AEDE8
	.string "Was ist?\n"
	.string "Du... Du...\p"
	.string "{STR_VAR_2}\n"
	.string "{STR_VAR_1}-mal?\p"
	.string "Das ist einfach großartig!\n"
	.string "Die Geburt einer neuen Legende!$"

MauvilleCity_PokemonCenter_1F_Text_1AEE50:: @ 81AEE50
	.string "Ich überlege, ob es nicht noch andere\n"
	.string "TRAINER gibt, die mir beeindruckende\l"
	.string "Geschichten erzählen können.$"

MauvilleCity_PokemonCenter_1F_Text_1AEEB4:: @ 81AEEB4
	.string "Bist du ein TRAINER?\p"
	.string "Dann sag mir, ob du Geschichten\n"
	.string "für mich hast, die legendär sind?$"

MauvilleCity_PokemonCenter_1F_Text_1AEF0A:: @ 81AEF0A
	.string "Übrigens... Möchtest du eine weitere\n"
	.string "legendäre Geschichte hören?$"

MauvilleCity_PokemonCenter_1F_Text_1AEF49:: @ 81AEF49
	.string "Hmm...\n"
	.string "Ich bin nicht zufrieden...\p"
	.string "Ich wünschte, du würdest mir Neuig-\n"
	.string "keiten erzählen, die den Titel Legende\l"
	.string "verdienen.$"

MauvilleCity_PokemonCenter_1F_Text_1AEFA5:: @ 81AEFA5
	.string "Ich wollte, mehr Leute würden sich für\n"
	.string "meine epischen Geschichten über\l"
	.string "legendäre TRAINER interessieren.$"

UnknownString_81AEFFC:: @ 81AEFFC
	.string "Der speicherfreudige TRAINER$"

UnknownString_81AF013:: @ 81AF013
	.string "Hast das Spiel gespeichert?$"

UnknownString_81AF022:: @ 81AF022
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat das Spiel\n"
	.string "{STR_VAR_1}-mal gespeichert!\p"
	.string "Einen vorsichtigeren TRAINER als\n"
	.string "{STR_VAR_3} wird man nicht finden!$"

UnknownString_81AF0A3:: @ 81AF0A3
	.string "Der TRAINER als Trendsetter$"

UnknownString_81AF0BB:: @ 81AF0BB
	.string "Hast Trends gesetzt?$"

UnknownString_81AF0CA:: @ 81AF0CA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "neue Trends gesetzt!\p"
	.string "{STR_VAR_3} setzt den Trend für alle - in\n"
	.string "der ganzen HOENN-Region!$"

UnknownString_81AF149:: @ 81AF149
	.string "Der BEEREN pflanzende TRAINER$"

UnknownString_81AF164:: @ 81AF164
	.string "Hast BEEREN gepflanzt?$"

UnknownString_81AF174:: @ 81AF174
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "BEEREN gepflanzt!\p"
	.string "{STR_VAR_3} ist ein legendärer Lieb-\n"
	.string "haber von BEEREN!$"

UnknownString_81AF1E5:: @ 81AF1E5
	.string "Der RAD verrückte TRAINER$"

UnknownString_81AF1FD:: @ 81AF1FD
	.string "Hast RÄDER getauscht?$"

UnknownString_81AF20A:: @ 81AF20A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "das RAD getauscht!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "Passion das RADfahren ist!$"

UnknownString_81AF281:: @ 81AF281
	.string "Der Interviews gebende TRAINER$"

UnknownString_81AF299:: @ 81AF299
	.string "Hast Interviews gegeben?$"

UnknownString_81AF2A9:: @ 81AF2A9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "interviewt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der überall\n"
	.string "Aufmerksamkeit erregt!$"

UnknownString_81AF32C:: @ 81AF32C
	.string "Der kampfliebende TRAINER$"

UnknownString_81AF345:: @ 81AF345
	.string "Hast oft gekämpft?$"

UnknownString_81AF34D:: @ 81AF34D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "gekämpft!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der zu\n"
	.string "einem Kampf nicht nein sagt!$"

UnknownString_81AF3D0:: @ 81AF3D0
	.string "Der POKéMON fangende TRAINER$"

UnknownString_81AF3ED:: @ 81AF3ED
	.string "Hast POKéMON gefangen?$"

UnknownString_81AF3FC:: @ 81AF3FC
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Fänger\n"
	.string "von POKéMON!$"

UnknownString_81AF46D:: @ 81AF46D
	.string "Der angelnde TRAINER$"

UnknownString_81AF481:: @ 81AF481
	.string "Hast POKéMON mit einer ANGEL gefangen?$"

UnknownString_81AF49B:: @ 81AF49B
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON beim Angeln gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Angel-\n"
	.string "experte!$"

UnknownString_81AF511:: @ 81AF511
	.string "Der EIER wärmende TRAINER$"

UnknownString_81AF529:: @ 81AF529
	.string "Hast EIER ausgebrütet?$"

UnknownString_81AF536:: @ 81AF536
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Es passierte {STR_VAR_1}-mal, dass der TRAINER\n"
	.string "ein POKéMON aus einem EI schlüpfen ließ!\p"
	.string "{STR_VAR_3} ist ein legendärer Pfleger\n"
	.string "von EIERN!$"

UnknownString_81AF5A9:: @ 81AF5A9
	.string "Der TRAINER der Entwicklungen$"

UnknownString_81AF5BD:: @ 81AF5BD
	.string "Hast POKéMON sich entwickeln lassen?$"

UnknownString_81AF5CD:: @ 81AF5CD
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON zur Entwicklung gebracht!\p"
	.string "{STR_VAR_3} ist der ultimative Ent-\n"
	.string "wickler von POKéMON!$"

UnknownString_81AF63F:: @ 81AF63F
	.string "Der PKMN-CENTER liebende TRAINER$"

UnknownString_81AF661:: @ 81AF661
	.string "Gingst in ein POKéMON-CENTER?$"

UnknownString_81AF676:: @ 81AF676
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal in einem POKéMON-CENTER\l"
	.string "heilen lassen!\p"
	.string "Es gibt keinen größeren Fan der\n"
	.string "POKéMON-CENTER als {STR_VAR_3}!$"

UnknownString_81AF711:: @ 81AF711
	.string "Der gastfreundliche TRAINER$"

UnknownString_81AF726:: @ 81AF726
	.string "POKéMON haben sich bei dir erholt?$"

UnknownString_81AF73D:: @ 81AF73D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal bei sich zu Hause ausruhen\l"
	.string "und heilen lassen.\p"
	.string "Kein TRAINER ist so gastfreundlich\n"
	.string "wie {STR_VAR_3}!$"

UnknownString_81AF7BF:: @ 81AF7BF
	.string "Der SAFARI liebende TRAINER$"

UnknownString_81AF7D9:: @ 81AF7D9
	.string "Bist in die SAFARI-ZONE gegangen?$"

UnknownString_81AF7F1:: @ 81AF7F1
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal in die\n"
	.string "SAFARI-ZONE gegangen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "wilde Seite in der SAFARI-ZONE zum\l"
	.string "Vorschein kommt!$"

UnknownString_81AF88A:: @ 81AF88A
	.string "Der TRAINER als ZERSCHNEIDER$"

UnknownString_81AF8A1:: @ 81AF8A1
	.string "Hast ZERSCHNEIDER eingesetzt?$"

UnknownString_81AF8AA:: @ 81AF8AA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERSCHNEIDER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, etwas zu ZERSCHNEIDEN.$"

UnknownString_81AF91B:: @ 81AF91B
	.string "Der TRAINER als ZERTRÜMMERER$"

UnknownString_81AF935:: @ 81AF935
	.string "Hast Felsen ZERTRÜMMERT?$"

UnknownString_81AF943:: @ 81AF943
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERTRÜMMERER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der keinen\n"
	.string "Felsen unbeschädigt lassen kann.$"

UnknownString_81AF9C8:: @ 81AF9C8
	.string "Der Umzüge liebende TRAINER$"

UnknownString_81AF9E0:: @ 81AF9E0
	.string "Bist du mit der GEHEIMBASIS umgezogen?$"

UnknownString_81AF9F6:: @ 81AF9F6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal mit\n"
	.string "seiner GEHEIMBASIS umgezogen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, sich ein neues Haus einzurichten.$"

UnknownString_81AFA79:: @ 81AFA79
	.string "Der PLATSCHER des TRAINERS$"

UnknownString_81AFA92:: @ 81AFA92
	.string "Hast PLATSCHER eingesetzt?$"

UnknownString_81AFA9E:: @ 81AFA9E
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "PLATSCHER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, zu PLATSCHEN.$"

UnknownString_81AFB17:: @ 81AFB17
	.string "Der verbissene TRAINER$"

UnknownString_81AFB2D:: @ 81AFB2D
	.string "Hast VERZWEIFLER angewendet?$"

UnknownString_81AFB48:: @ 81AFB48
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat sich {STR_VAR_1}-mal\n"
	.string "auf VERZWEIFLER verlassen!\p"
	.string "{STR_VAR_3}... Ein verbissener TRAINER,\n"
	.string "der auch in der Not nicht aufgibt.$"

UnknownString_81AFBD8:: @ 81AFBD8
	.string "Der König der EINARMIGEN BANDITEN$"

UnknownString_81AFBE7:: @ 81AFBE7
	.string "Hast den EINARMIGEN BANDITEN besiegt?$"

UnknownString_81AFC04:: @ 81AFC04
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "am EINARMIGEN BANDITEN gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der am\n"
	.string "EINARMIGEN BANDITEN Glück hat.$"

UnknownString_81AFC8A:: @ 81AFC8A
	.string "Der König des ROULETTES$"

UnknownString_81AFC9D:: @ 81AFC9D
	.string "Hast in Folge beim ROULETTE gewonnen,$"

UnknownString_81AFCBE:: @ 81AFCBE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal in Folge\n"
	.string "beim ROULETTE gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, dem die Kugel\n"
	.string "beim ROULETTE gehorcht.$"

UnknownString_81AFD44:: @ 81AFD44
	.string "Der Herausforderer im DUELLTURM$"

UnknownString_81AFD60:: @ 81AFD60
	.string "Hast Gegner im DUELLTURM gefordert?$"

UnknownString_81AFD80:: @ 81AFD80
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal Gegner\n"
	.string "im DUELLTURM herausgefordert!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der im DUELL-\n"
	.string "TURM nach Perfektion strebt.$"

UnknownString_81AFE1D:: @ 81AFE1D
	.string "Der mixende TRAINER$"

UnknownString_81AFE36:: @ 81AFE36
	.string "Hast {POKEBLOCK} hergestellt?$"

UnknownString_81AFE42:: @ 81AFE42
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "{POKEBLOCK} hergestellt!\p"
	.string "Niemand bedient den BEERENMIXER\n"
	.string "besser als {STR_VAR_3}.$"

UnknownString_81AFEC2:: @ 81AFEC2
	.string "Der Fan der WETTBEWERBE$"

UnknownString_81AFEDD:: @ 81AFEDD
	.string "Hast an WETTBEWERBEN teilgenommen?$"

UnknownString_81AFEEE:: @ 81AFEEE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "an einem WETTBEWERB teilgenommen!\p"
	.string "{STR_VAR_3} liebt es, anderen seine\n"
	.string "POKéMON zu zeigen.$"

UnknownString_81AFF68:: @ 81AFF68
	.string "Der Meister der WETTBEWERBE$"

UnknownString_81AFF7B:: @ 81AFF7B
	.string "Hast WETTBEWERBE gewonnen?$"

UnknownString_81AFF88:: @ 81AFF88
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "einen WETTBEWERB gewonnen!\p"
	.string "{STR_VAR_3} ist ein unvergleichlicher\n"
	.string "Meister der WETTBEWERBE.$"

UnknownString_81AFFFB:: @ 81AFFFB
	.string "Der glückliche Einkäufer$"

UnknownString_81B000D:: @ 81B000D
	.string "Bist einkaufen gegangen?$"

UnknownString_81B0015:: @ 81B0015
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in einem Geschäft Items gekauft!\p"
	.string "{STR_VAR_3} ein geborener Einkäufer.$"

UnknownString_81B009D:: @ 81B009D
	.string "Der TRAINER, der Items findet$"

UnknownString_81B00B6:: @ 81B00B6
	.string "Hast den DETEKTOR eingesetzt?$"

UnknownString_81B00C9:: @ 81B00C9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "den DETEKTOR eingesetzt!\p"
	.string "{STR_VAR_3} liebt es, den Boden nach\n"
	.string "verborgenen Items abzusuchen.$"

UnknownString_81B014D:: @ 81B014D
	.string "Der regennasse TRAINER$"

UnknownString_81B0165:: @ 81B0165
	.string "Wurdest nass geregnet?$"

UnknownString_81B0173:: @ 81B0173
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "nass geregnet!\p"
	.string "Das Charisma von {STR_VAR_3} zieht\n"
	.string "sogar den Regen an.$"

UnknownString_81B01E9:: @ 81B01E9
	.string "Der passionierte POKéDEX-Leser$"

UnknownString_81B0201:: @ 81B0201
	.string "Hast im POKéDEX nachgeschlagen?$"

UnknownString_81B0213:: @ 81B0213
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "im POKéDEX nachgeschlagen!\p"
	.string "{STR_VAR_3} liebt es, alles über\n"
	.string "POKéMON im POKéDEX nachzulesen.$"

UnknownString_81B0290:: @ 81B0290
	.string "Der Sammler der BÄNDER$"

UnknownString_81B02A5:: @ 81B02A5
	.string "Hast BÄNDER erhalten?$"

UnknownString_81B02B6:: @ 81B02B6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "BÄNDER erhalten!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, BÄNDER zu sammeln.$"

UnknownString_81B0337:: @ 81B0337
	.string "Der springende TRAINER$"

UnknownString_81B0351:: @ 81B0351
	.string "Bist Absätze heruntergesprungen?$"

UnknownString_81B0364:: @ 81B0364
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "einen Absatz hinabgesprungen!\p"
	.string "Sobald er an einen Absatz kommt, muss\n"
	.string "TRAINER {STR_VAR_3} einfach hinab-\l"
	.string "springen.$"

UnknownString_81B03E9:: @ 81B03E9
	.string "Der legendäre Fernsehzuschauer$"

UnknownString_81B0401:: @ 81B0401
	.string "Hast ferngeschaut?$"

UnknownString_81B040C:: @ 81B040C
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "Fernsehen geschaut!\p"
	.string "{STR_VAR_3} liebt es, fernzusehen.$"

UnknownString_81B046E:: @ 81B046E
	.string "Der zeitbewusste TRAINER$"

UnknownString_81B0489:: @ 81B0489
	.string "Hast nach der Uhrzeit gesehen?$"

UnknownString_81B049A:: @ 81B049A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "nach der Uhrzeit geschaut!\p"
	.string "{STR_VAR_3} ist ein pünktlicher\n"
	.string "TRAINER, der sich der Zeit bewusst ist.$"

UnknownString_81B0523:: @ 81B0523
	.string "Der Zauberer der POKéMON-LOTTERIE$"

UnknownString_81B053E:: @ 81B053E
	.string "Hast in der LOTTERIE gewonnen?$"

UnknownString_81B0554:: @ 81B0554
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in der POKéMON-LOTTERIE gewonnen!\p"
	.string "TRAINER {STR_VAR_3} hat viele Freunde,\n"
	.string "die mit ihm POKéMON tauschen.$"

UnknownString_81B05D8:: @ 81B05D8
	.string "Der TRAINER und die PENSION$"

UnknownString_81B05F3:: @ 81B05F3
	.string "Hast POKéMON in die PENSION gebracht?$"

UnknownString_81B0610:: @ 81B0610
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "seine POKéMON in die PENSION gegeben!\p"
	.string "{STR_VAR_3} ist ein Ellenbogentyp, der\n"
	.string "alles für die Entwicklung seiner\l"
	.string "POKéMON tut.$"

UnknownString_81B06A9:: @ 81B06A9
	.string "Der SEILBAHN verrückte TRAINER$"

UnknownString_81B06C6:: @ 81B06C6
	.string "Bist mit der SEILBAHN gefahren?$"

UnknownString_81B06D9:: @ 81B06D9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "mit der SEILBAHN gefahren!\p"
	.string "{STR_VAR_3} ein sehr beschäftigter\n"
	.string "TRAINER, der ständig rauf und runter\l"
	.string "fährt.$"

UnknownString_81B0763:: @ 81B0763
	.string "Der Liebhaber der Heißen Quellen$"

UnknownString_81B0781:: @ 81B0781
	.string "Hast in den Heißen Quellen gebadet?$"

UnknownString_81B0797:: @ 81B0797
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in den Heißen Quellen gebadet!\p"
	.string "{STR_VAR_3} wird eine babyweiche Haut\n"
	.string "haben.$"
