gTextStoryteller_Introduction:: @ 81AECC6
	.string "I’m the STORYTELLER.\n"
	.string "I’ll tell you tales of legendary\l"
	.string "TRAINERS.\p"
	.string "Will you hear my tale?$"

gTextStoryteller_OhIFeelStifled:: @ 81AED1D
	.string "Oh...\n"
	.string "I feel stifled...$"

gTextStoryteller_WhichTale:: @ 81AED35
	.string "I know of these legends.\n"
	.string "Which tale will you have me tell?$"

gTextStoryteller_ButIKnowOfNoLegendaryTrainers:: @ 81AED70
	.string "But, I know of no legendary TRAINERS.\n"
	.string "Hence, I know no tales.\p"
	.string "Where does one find a TRAINER worthy\n"
	.string "of a legendary tale?$"

gTextStoryteller_BirthOfANewLegend:: @ 81AEDE8
	.string "What’s that?!\n"
	.string "You... You...\p"
	.string "{STR_VAR_2}\n"
	.string "{STR_VAR_1} time(s)?!\p"
	.string "That is indeed magnificent!\n"
	.string "It’s the birth of a new legend!$"

gTextStoryteller_CouldThereBeOtherTrainers:: @ 81AEE50
	.string "It gets me thinking, could there be\n"
	.string "other TRAINERS with more impressive\l"
	.string "legends awaiting discovery?$"

gTextStoryteller_HaveYouAnyTales:: @ 81AEEB4
	.string "Are you a TRAINER?\p"
	.string "Then tell me, have you any tales that\n"
	.string "are even remotely legendary?$"

gTextStoryteller_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "Incidentally... Would you care to hear\n"
	.string "another legendary tale?$"

gTextStoryteller_ImNotSatisfied:: @ 81AEF49
	.string "Hmm...\n"
	.string "I’m not satisfied...\p"
	.string "I wish you would bring me news worthy\n"
	.string "of being called a legend.$"

gTextStoryteller_WishMorePeopleWould:: @ 81AEFA5
	.string "I wish more people would be interested\n"
	.string "in hearing my epic tales of legendary\l"
	.string "TRAINERS.$"

gTextStoryteller_Story1Title:: @ 81AEFFC
	.string "The Save-Happy TRAINER$"

gTextStoryteller_Story1Action:: @ 81AF013
	.string "Saved the game$"

gTextStoryteller_Story1Text:: @ 81AF022
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER saved the game\n"
	.string "{STR_VAR_1} times!\p"
	.string "A more cautious TRAINER than\n"
	.string "{STR_VAR_3} one will never find!$"

gTextStoryteller_Story2Title:: @ 81AF0A3
	.string "The Trendsetter TRAINER$"

gTextStoryteller_Story2Action:: @ 81AF0BB
	.string "Started trends$"

gTextStoryteller_Story2Text:: @ 81AF0CA
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER started new trends\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is setting trends for all\n"
	.string "the HOENN region!$"

gTextStoryteller_Story3Title:: @ 81AF149
	.string "The BERRY-Planting TRAINER$"

gTextStoryteller_Story3Action:: @ 81AF164
	.string "Planted BERRIES$"

gTextStoryteller_Story3Text:: @ 81AF174
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER planted BERRIES\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a legendary lover of\n"
	.string "BERRIES!$"

gTextStoryteller_Story4Title:: @ 81AF1E5
	.string "The BIKE-Loving TRAINER$"

gTextStoryteller_Story4Action:: @ 81AF1FD
	.string "Traded BIKES$"

gTextStoryteller_Story4Text:: @ 81AF20A
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER swapped BIKES\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love BIKES deeply\n"
	.string "and passionately!$"

gTextStoryteller_Story5Title:: @ 81AF281
	.string "The Interviewed TRAINER$"

gTextStoryteller_Story5Action:: @ 81AF299
	.string "Got interviewed$"

gTextStoryteller_Story5Text:: @ 81AF2A9
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER got interviewed\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a TRAINER who’s\n"
	.string "attracting much attention!$"

gTextStoryteller_Story6Title:: @ 81AF32C
	.string "The Battle-Happy TRAINER$"

gTextStoryteller_Story6Action:: @ 81AF345
	.string "Battled$"

gTextStoryteller_Story6Text:: @ 81AF34D
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER battled {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a TRAINER who can\n"
	.string "never refuse a chance to battle!$"

gTextStoryteller_Story7Title:: @ 81AF3D0
	.string "The POKéMON-Catching TRAINER$"

gTextStoryteller_Story7Action:: @ 81AF3ED
	.string "Caught POKéMON$"

gTextStoryteller_Story7Text:: @ 81AF3FC
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER caught\n"
	.string "{STR_VAR_1} POKéMON!\p"
	.string "{STR_VAR_3} is a legendary catcher of\n"
	.string "wild POKéMON!$"

gTextStoryteller_Story8Title:: @ 81AF46D
	.string "The Fishing TRAINER$"

gTextStoryteller_Story8Action:: @ 81AF481
	.string "Caught POKéMON with a ROD$"

gTextStoryteller_Story8Text:: @ 81AF49B
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER caught\n"
	.string "{STR_VAR_1} POKéMON while fishing!\p"
	.string "{STR_VAR_3} is a legendary fishing\n"
	.string "expert!$"

gTextStoryteller_Story9Title:: @ 81AF511
	.string "The EGG-Warming TRAINER$"

gTextStoryteller_Story9Action:: @ 81AF529
	.string "Hatched EGGS$"

gTextStoryteller_Story9Text:: @ 81AF536
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER hatched {STR_VAR_1} POKéMON\n"
	.string "from EGGS!\p"
	.string "{STR_VAR_3} is a legendary warmer\n"
	.string "of EGGS!$"

gTextStoryteller_Story10Title:: @ 81AF5A9
	.string "The Evolver TRAINER$"

gTextStoryteller_Story10Action:: @ 81AF5BD
	.string "Evolved POKéMON$"

gTextStoryteller_Story10Text:: @ 81AF5CD
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER made {STR_VAR_1} POKéMON\n"
	.string "evolve!\p"
	.string "{STR_VAR_3} is the ultimate evolver\n"
	.string "of POKéMON!$"

gTextStoryteller_Story11Title:: @ 81AF63F
	.string "The POKéMON CENTER-Loving TRAINER$"

gTextStoryteller_Story11Action:: @ 81AF661
	.string "Used POKéMON CENTERS$"

gTextStoryteller_Story11Text:: @ 81AF676
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER healed POKéMON\n"
	.string "{STR_VAR_1} times at POKéMON CENTERS!\p"
	.string "There could be no greater lover of\n"
	.string "POKéMON CENTERS than {STR_VAR_3}!$"

gTextStoryteller_Story12Title:: @ 81AF711
	.string "The Homebody TRAINER$"

gTextStoryteller_Story12Action:: @ 81AF726
	.string "Rested POKéMON at home$"

gTextStoryteller_Story12Text:: @ 81AF73D
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER healed POKéMON\n"
	.string "{STR_VAR_1} times at home!\p"
	.string "There could be no more of a homebody\n"
	.string "than {STR_VAR_3}!$"

gTextStoryteller_Story13Title:: @ 81AF7BF
	.string "The SAFARI-Loving TRAINER$"

gTextStoryteller_Story13Action:: @ 81AF7D9
	.string "Entered the SAFARI ZONE$"

gTextStoryteller_Story13Text:: @ 81AF7F1
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER went into the SAFARI ZONE\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a TRAINER whose wild side\n"
	.string "must come out in the SAFARI ZONE!$"

gTextStoryteller_Story14Title:: @ 81AF88A
	.string "The CUT-Frenzy TRAINER$"

gTextStoryteller_Story14Action:: @ 81AF8A1
	.string "Used CUT$"

gTextStoryteller_Story14Text:: @ 81AF8AA
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER used CUT\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a TRAINER who just must\n"
	.string "love to CUT!$"

gTextStoryteller_Story15Title:: @ 81AF91B
	.string "The ROCK-SMASHING TRAINER$"

gTextStoryteller_Story15Action:: @ 81AF935
	.string "Smashed rocks$"

gTextStoryteller_Story15Text:: @ 81AF943
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER used ROCK SMASH\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a TRAINER who\n"
	.string "can’t leave a stone unsmashed!$"

gTextStoryteller_Story16Title:: @ 81AF9C8
	.string "The Move-Loving TRAINER$"

gTextStoryteller_Story16Action:: @ 81AF9E0
	.string "Moved the SECRET BASE$"

gTextStoryteller_Story16Text:: @ 81AF9F6
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER moved the SECRET BASE\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a TRAINER who loves\n"
	.string "to move houses often!$"

gTextStoryteller_Story17Title:: @ 81AFA79
	.string "The SPLASH-Happy TRAINER$"

gTextStoryteller_Story17Action:: @ 81AFA92
	.string "Used SPLASH$"

gTextStoryteller_Story17Text:: @ 81AFA9E
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER used SPLASH\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a TRAINER who must love\n"
	.string "SPLASHING around!$"

gTextStoryteller_Story18Title:: @ 81AFB17
	.string "The Tenacious TRAINER$"

gTextStoryteller_Story18Action:: @ 81AFB2D
	.string "Resorted to using STRUGGLE$"

gTextStoryteller_Story18Text:: @ 81AFB48
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER had to rely on STRUGGLE\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a tenacious TRAINER\n"
	.string "who never gives in to adversity!$"

gTextStoryteller_Story19Title:: @ 81AFBD8
	.string "The SLOT Champ$"

gTextStoryteller_Story19Action:: @ 81AFBE7
	.string "Won the jackpot on the SLOTS$"

gTextStoryteller_Story19Text:: @ 81AFC04
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER won the jackpot on\n"
	.string "the SLOTS {STR_VAR_1} times.\p"
	.string "{STR_VAR_3} is a TRAINER who was lucky\n"
	.string "on the SLOTS!$"

gTextStoryteller_Story20Title:: @ 81AFC8A
	.string "The ROULETTE Champ$"

gTextStoryteller_Story20Action:: @ 81AFC9D
	.string "Had consecutive ROULETTE wins of$"

gTextStoryteller_Story20Text:: @ 81AFCBE
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER won in ROULETTE\n"
	.string "{STR_VAR_1} times in a row.\p"
	.string "{STR_VAR_3} was lucky when the ball\n"
	.string "bounced in ROULETTE!$"

gTextStoryteller_Story21Title:: @ 81AFD44
	.string "The BATTLE TOWER Challenger$"

gTextStoryteller_Story21Action:: @ 81AFD60
	.string "Took the BATTLE TOWER challenge$"

gTextStoryteller_Story21Text:: @ 81AFD80
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER took the BATTLE TOWER\n"
	.string "challenge {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a TRAINER who aspires\n"
	.string "for excellence in the BATTLE TOWER!$"

gTextStoryteller_Story22Title:: @ 81AFE1D
	.string "The Blend-Loving TRAINER$"

gTextStoryteller_Story22Action:: @ 81AFE36
	.string "Made {POKEBLOCK}S$"

gTextStoryteller_Story22Text:: @ 81AFE42
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER made {POKEBLOCK}S\n"
	.string "{STR_VAR_1} times!\p"
	.string "There is none better at using a BERRY\n"
	.string "BLENDER than {STR_VAR_3}!$"

gTextStoryteller_Story23Title:: @ 81AFEC2
	.string "The CONTEST-Loving TRAINER$"

gTextStoryteller_Story23Action:: @ 81AFEDD
	.string "Entered CONTESTS$"

gTextStoryteller_Story23Text:: @ 81AFEEE
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER entered CONTESTS\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love showing off\n"
	.string "POKéMON to others!$"

gTextStoryteller_Story24Title:: @ 81AFF68
	.string "The CONTEST Master$"

gTextStoryteller_Story24Action:: @ 81AFF7B
	.string "Won CONTESTS$"

gTextStoryteller_Story24Text:: @ 81AFF88
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER won CONTESTS\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be an incredible\n"
	.string "CONTEST master!$"

gTextStoryteller_Story25Title:: @ 81AFFFB
	.string "The Happy Shopper$"

gTextStoryteller_Story25Action:: @ 81B000D
	.string "Shopped$"

gTextStoryteller_Story25Text:: @ 81B0015
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER bought items in shops\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be one of those\n"
	.string "people who are born to shop.$"

gTextStoryteller_Story26Title:: @ 81B009D
	.string "The Item-Finding TRAINER$"

gTextStoryteller_Story26Action:: @ 81B00B6
	.string "Used an ITEMFINDER$"

gTextStoryteller_Story26Text:: @ 81B00C9
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER used an ITEMFINDER\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must enjoy scouring the\n"
	.string "ground for hidden items!$"

gTextStoryteller_Story27Title:: @ 81B014D
	.string "The Rain-Soaked TRAINER$"

gTextStoryteller_Story27Action:: @ 81B0165
	.string "Got rained on$"

gTextStoryteller_Story27Text:: @ 81B0173
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER got soaked by rain\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3}’s charisma must even\n"
	.string "attract rain!$"

gTextStoryteller_Story28Title:: @ 81B01E9
	.string "The Avid POKéDEX Reader$"

gTextStoryteller_Story28Action:: @ 81B0201
	.string "Checked a POKéDEX$"

gTextStoryteller_Story28Text:: @ 81B0213
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER checked a POKéDEX\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love inspecting\n"
	.string "POKéMON in a POKéDEX!$"

gTextStoryteller_Story29Title:: @ 81B0290
	.string "The RIBBON Collector$"

gTextStoryteller_Story29Action:: @ 81B02A5
	.string "Received RIBBONS$"

gTextStoryteller_Story29Text:: @ 81B02B6
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER received RIBBONS\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a TRAINER who\n"
	.string "loves to collect RIBBONS!$"

gTextStoryteller_Story30Title:: @ 81B0337
	.string "The Ledge-Jumping TRAINER$"

gTextStoryteller_Story30Action:: @ 81B0351
	.string "Jumped down ledges$"

gTextStoryteller_Story30Text:: @ 81B0364
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER jumped down ledges\n"
	.string "{STR_VAR_1} times!\p"
	.string "If there’s a ledge to be jumped,\n"
	.string "{STR_VAR_3} can’t ignore it!$"

gTextStoryteller_Story31Title:: @ 81B03E9
	.string "The Legendary TV Viewer$"

gTextStoryteller_Story31Action:: @ 81B0401
	.string "Watched TV$"

gTextStoryteller_Story31Text:: @ 81B040C
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER watched TV\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love watching TV!$"

gTextStoryteller_Story32Title:: @ 81B046E
	.string "The Time-Conscious TRAINER$"

gTextStoryteller_Story32Action:: @ 81B0489
	.string "Checked the time$"

gTextStoryteller_Story32Text:: @ 81B049A
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER checked the time\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a punctual TRAINER\n"
	.string "who’s conscious of the time.$"

gTextStoryteller_Story33Title:: @ 81B0523
	.string "The POKéMON LOTTERY Wizard$"

gTextStoryteller_Story33Action:: @ 81B053E
	.string "Won POKéMON LOTTERIES$"

gTextStoryteller_Story33Text:: @ 81B0554
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER won POKéMON LOTTERIES\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must have many friends\n"
	.string "to trade POKéMON with!$"

gTextStoryteller_Story34Title:: @ 81B05D8
	.string "The DAY CARE-Using Trainer$"

gTextStoryteller_Story34Action:: @ 81B05F3
	.string "Left POKéMON at the DAY CARE$"

gTextStoryteller_Story34Text:: @ 81B0610
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER left POKéMON with the\n"
	.string "DAY CARE {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a real go-getter\n"
	.string "who raises POKéMON aggressively!$"

gTextStoryteller_Story35Title:: @ 81B06A9
	.string "The CABLE CAR-Loving TRAINER$"

gTextStoryteller_Story35Action:: @ 81B06C6
	.string "Rode the CABLE CAR$"

gTextStoryteller_Story35Text:: @ 81B06D9
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER rode the CABLE CAR\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a busy TRAINER\n"
	.string "who’s up and down all the time!$"

gTextStoryteller_Story36Title:: @ 81B0763
	.string "The Hot Spring-Loving TRAINER$"

gTextStoryteller_Story36Action:: @ 81B0781
	.string "Bathed in hot springs$"

gTextStoryteller_Story36Text:: @ 81B0797
	.string "This is a tale of a TRAINER\n"
	.string "named {STR_VAR_3}.\p"
	.string "This TRAINER bathed in hot springs\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a TRAINER with\n"
	.string "baby-smooth skin!$"
