gTextTrader_Introduction:: @ 81AE88F
	.string "Hi, I’m the TRADER.\n"
	.string "Want to trade decorations with me?$"

gTextTrader_FeelUnwanted1:: @ 81AE8C6
	.string "Oh...\n"
	.string "I feel unwanted...$"

gTextTrader_TradedAlready:: @ 81AE8DF
	.string "But we’ve traded decorations already,\n"
	.string "you and I.$"

gTextTrader_MenuPrompt:: @ 81AE910
	.string "If you see any decorative item that\n"
	.string "you want of mine, speak up.$"

gTextTrader_DontWantAnything:: @ 81AE950
	.string "You don’t want anything?\n"
	.string "I feel unwanted...$"

gTextTrader_ItemOnceBelongedTo:: @ 81AE97C
	.string "That decorative item once belonged\n"
	.string "to {STR_VAR_1}.\p"
	.string "Do you want it?$"

gTextTrader_YouDontHaveDecorations:: @ 81AE9B6
	.string "Uh... Wait a second. You don’t have a\n"
	.string "single piece of decoration!$"

gTextTrader_PickDecorationYoullTrade:: @ 81AE9F8
	.string "Okay, pick the decoration that you’ll\n"
	.string "trade to me.$"

gTextTrader_FeelUnwanted2:: @ 81AEA2B
	.string "You won’t trade with me?\n"
	.string "I feel unwanted...$"

gTextTrader_NoRoomForThis:: @ 81AEA57
	.string "You’ve got all the {STR_VAR_2}S that can\n"
	.string "be stored. You’ve no room for this.$"

gTextTrader_SoWellTrade:: @ 81AEA9B
	.string "Okay, so we’ll trade my {STR_VAR_3}\n"
	.string "for your {STR_VAR_2}?$"

gTextTrader_InUseYouCantTradeIt:: @ 81AEAC3
	.string "That piece of decoration is in use.\n"
	.string "You can’t trade it.$"

gTextTrader_ThenWellTrade:: @ 81AEAFB
	.string "Then we’ll trade!\n"
	.string "I’ll send my decoration to your PC.$"

gTextTrader_ICantTradeThatOneAway:: @ 81AEB31
	.string "Oops! Sorry!\n"
	.string "That’s a really rare piece of decoration.\l"
	.string "I can’t trade that one away!\p"
	.string "Can I interest you in something else?$"
