Route102_Text_1B79C3:: @ 81B79C3
	.string "Wenn du POKéMON bei dir hast, bist du\n"
	.string "offiziell ein POKéMON-TRAINER! Daher\l"
	.string "kannst du meine Herausforderung nicht\l"
	.string "ablehnen!$"

Route102_Text_1B7A2C:: @ 81B7A2C
	.string "Aargh, ich habe verloren... Ich\n"
	.string "hätte fleißiger trainieren sollen.$"

Route102_Text_1B7A60:: @ 81B7A60
	.string "Hör mal! Du hättest mir vorher sagen\n"
	.string "sollen, dass du so stark bist.$"

Route102_Text_1B7A9F:: @ 81B7A9F
	.string "Seit ich gegen dich verloren habe,\n"
	.string "trainiere ich verzweifelt meine\l"
	.string "POKéMON. Sag nicht nein zu einem Kampf!$"

Route102_Text_1B7AFD:: @ 81B7AFD
	.string "Aaaah, ich habe schon wieder verloren...\n"
	.string "Ob ich nicht richtig trainiere?$"

Route102_Text_1B7B2F:: @ 81B7B2F
	.string "Wenn du stärker wirst, werde ich auch\n"
	.string "stärker.$"

Route102_Text_1B7B68:: @ 81B7B68
	.string "Bist du gerade erst TRAINER geworden?\n"
	.string "Dann sind wir ja beide Anfänger.$"

Route102_Text_1B7B9D:: @ 81B7B9D
	.string "Ich habe dich angesprochen, weil ich\n"
	.string "dachte, ich könnte dich besiegen.$"

Route102_Text_1B7BD0:: @ 81B7BD0
	.string "Ich habe noch nicht ein Mal gewonnen...\n"
	.string "Ich hoffe, ich werde bald gewinnen!$"

Route102_Text_1B7C05:: @ 81B7C05
	.string "Haha! Unsere Augen haben sich\n"
	.string "getroffen! Ich kämpfe mit meinen\l"
	.string "KÄFER-POKéMON gegen dich!$"

Route102_Text_1B7C40:: @ 81B7C40
	.string "Auaaa! Besiegt und verloren!$"

Route102_Text_1B7C52:: @ 81B7C52
	.string "Wenn du einem TRAINER in die Augen\n"
	.string "schaust, forderst du ihn heraus! Das\l"
	.string "ist die Regel!$"

Route102_Text_1B7C97:: @ 81B7C97
	.string "Mein Ziel? Stets gewinnen und der beste\n"
	.string "TRAINER aller Zeiten werden.\p"
	.string "Hilf mir bei meiner Karriere!$"

Route102_Text_1B7CEC:: @ 81B7CEC
	.string "Da habe ich wohl deine Karriere\n"
	.string "angekurbelt.$"

Route102_Text_1B7D11:: @ 81B7D11
	.string "Um auf der Straße der Sieger laufen zu\n"
	.string "können, brauche ich mehr POKéMON.$"

Route103_Text_1B7D55:: @ 81B7D55
	.string "Spürst du die wohlige Berührung\n"
	.string "unseres wohltuenden Wohlgeruches?$"

Route103_Text_1B7D8B:: @ 81B7D8B
	.string "Du hast dich vom Duft nicht ablenken\n"
	.string "lassen...$"

Route103_Text_1B7DB2:: @ 81B7DB2
	.string "Aromatherapie ist eine Form der\n"
	.string "mentalen Kur, die mit Düften arbeitet.$"

Route103_Text_1B7DF7:: @ 81B7DF7
	.string "NORA: Hallo, ich bin NORA.\n"
	.string "Und das ist meine kleine Schwester JO.\l"
	.string "Wir kämpfen stets zusammen!$"

Route103_Text_1B7E3B:: @ 81B7E3B
	.string "NORA: Oh, wir haben verloren.$"

Route103_Text_1B7E50:: @ 81B7E50
	.string "NORA: Du musst auf alles Mögliche\n"
	.string "achten, wenn du gegen zwei TRAINER\l"
	.string "antrittst.$"

Route103_Text_1B7EAC:: @ 81B7EAC
	.string "NORA: Oh oh, du hast nur ein POKéMON\n"
	.string "dabei. Damit kannst du nicht gegen uns\l"
	.string "beide antreten.$"

Route103_Text_1B7EFB:: @ 81B7EFB
	.string "JO: Wir kämpfen als Team...$"

Route103_Text_1B7F20:: @ 81B7F20
	.string "JO: Schwesterherz, wir haben verloren.$"

Route103_Text_1B7F40:: @ 81B7F40
	.string "JO: Wir arbeiten sehr gut zusammen, ich\n"
	.string "und meine große Schwester...\p"
	.string "Aber wir haben verloren...$"

Route103_Text_1B7F8E:: @ 81B7F8E
	.string "JO: Wenn du gegen uns kämpfen willst,\n"
	.string "brauchst du zwei POKéMON. Hast du die\l"
	.string "nicht, wäre der Kampf unfair!$"

Route103_Text_1B7FE7:: @ 81B7FE7
	.string "NORA: Hallo, weißt du noch? Ich bin NORA.\n"
	.string "Und das ist meine kleine Schwester JO.\l"
	.string "Wir kämpfen stets zusammen!$"

Route103_Text_1B802B:: @ 81B802B
	.string "NORA: Aahaaa, buuuh!\n"
	.string "Wir haben es nicht geschafft...$"

Route103_Text_1B8053:: @ 81B8053
	.string "NORA: Du musst auf alles Mögliche\n"
	.string "achten, wenn du gegen zwei TRAINER\l"
	.string "antrittst. Erwähnte ich das schon?$"

Route103_Text_1B80AF:: @ 81B80AF
	.string "NORA: Oh oh, du hast nur ein POKéMON\n"
	.string "dabei. Damit kannst du nicht gegen uns\l"
	.string "beide antreten.$"

Route103_Text_1B80FE:: @ 81B80FE
	.string "JO: Wir kämpfen als Team...$"

Route103_Text_1B8123:: @ 81B8123
	.string "JO: Heul... Große Schwester, wir haben\n"
	.string "schon wieder verloren.$"

Route103_Text_1B814D:: @ 81B814D
	.string "JO: Wir haben wieder perfekt zusammen-\n"
	.string "gearbeitet, ich und meine Schwester...\p"
	.string "Warum haben wir wieder verloren?$"

Route103_Text_1B81A1:: @ 81B81A1
	.string "JO: Wenn du gegen uns kämpfen willst,\n"
	.string "brauchst du zwei POKéMON. Hast du die\l"
	.string "nicht, wäre der Kampf unfair!$"

Route103_Text_1B81FA:: @ 81B81FA
	.string "Ach! Meine Angelschnur hat sich ver-\n"
	.string "heddert! Jetzt bin ich frustriert und\l"
	.string "wütend! So! Und du darfst es ausbaden!$"

Route103_Text_1B8258:: @ 81B8258
	.string "Ach! Verloren!\n"
	.string "Nun bin ich noch wütender...$"

Route103_Text_1B8281:: @ 81B8281
	.string "Ach! Ich koche vor Wut, Mann...\n"
	.string "Grrrr...$"

Route103_Text_1B82A9:: @ 81B82A9
	.string "Mein POKéMON ist einfach anbetungs-\n"
	.string "würdig. Nur keine Scheu, ich zeig’s dir.$"

Route103_Text_1B82EC:: @ 81B82EC
	.string "Oh, so was aber auch!\n"
	.string "Mein geliebtes POKéMON!$"

Route103_Text_1B830D:: @ 81B830D
	.string "Mein wunderbares POKéMON sieht sogar\n"
	.string "besiegt noch wunderbar aus.$"

Route103_Text_1B8349:: @ 81B8349
	.string "Hey, du! Mein anbetungswürdiges\n"
	.string "POKéMON ist noch anbetungswürdiger\l"
	.string "geworden.$"

Route103_Text_1B838C:: @ 81B838C
	.string "Oh!\n"
	.string "Mein geliebtes POKéMON.$"

Route103_Text_1B83A4:: @ 81B83A4
	.string "Je mehr Zeit ich mit ihm verbringe,\n"
	.string "desto anbetungswürdiger wird es.$"

Route104_Text_1B83E9:: @ 81B83E9
	.string "GINA: Okay, dann lass uns mit unseren\n"
	.string "POKéMON kämpfen.$"

Route104_Text_1B8414:: @ 81B8414
	.string "GINA: Wenn ich verliere, bin ich sauer.$"

Route104_Text_1B842C:: @ 81B842C
	.string "GINA: Du bist stark!\n"
	.string "Wir müssen doch mehr trainieren!$"

Route104_Text_1B845C:: @ 81B845C
	.string "GINA: Oh, nur ein POKéMON?\n"
	.string "Dann können wir nicht kämpfen.\p"
	.string "Wenn du nur ein POKéMON hast, wird es\n"
	.string "sich einsam fühlen. Das ist nicht gut.$"

Route104_Text_1B84DB:: @ 81B84DB
	.string "MIA: Wir sind Zwillinge und kämpfen auch\n"
	.string "mit unseren POKéMON zusammen.$"

Route104_Text_1B850D:: @ 81B850D
	.string "MIA: Wir haben zusammen gekämpft und\n"
	.string "auch zusammen verloren.$"

Route104_Text_1B853B:: @ 81B853B
	.string "MIA: Wir werden unsere POKéMON\n"
	.string "trainieren. Und dann gewinnen wir!$"

Route104_Text_1B8577:: @ 81B8577
	.string "MIA: Du willst gegen uns kämpfen?\p"
	.string "Ein dickes NEIN - da du weniger als zwei\n"
	.string "POKéMON bei dir hast. Wir sind zu\l"
	.string "stark für dich!$"

Route104_Text_1B85EB:: @ 81B85EB
	.string "Warum soll ich ein Geheimnis daraus\n"
	.string "machen? Ich bin der...\p"
	.string "WASSER-POKéMON-Experte!\n"
	.string "Wie?!? Du kennst mich nicht?!?$"

Route104_Text_1B8637:: @ 81B8637
	.string "Ich dachte, ich wäre gar nicht so\n"
	.string "schlecht. Aber... Ach, Mist...$"

Route104_Text_1B8680:: @ 81B8680
	.string "Über das Angeln habe ich glatt das\n"
	.string "Training meiner POKéMON vergessen.$"

Route104_Text_1B86BE:: @ 81B86BE
	.string "Spuren im Sand zu hinterlassen ist total\n"
	.string "lustig!$"

Route104_Text_1B86E8:: @ 81B86E8
	.string "Igitt! Ich habe Sand in den Schuhen!\n"
	.string "Das ist vielleicht unangenehm!$"

Route104_Text_1B871C:: @ 81B871C
	.string "Ich will meine Fußspuren im Sand hinter-\n"
	.string "lassen, aber sie verschwinden viel zu\l"
	.string "schnell wieder...$"

Route104_Text_1B8770:: @ 81B8770
	.string "Soll ich...\n"
	.string "Oder soll ich nicht?\p"
	.string "Okay, natürlich kämpfe ich!$"

Route104_Text_1B87A7:: @ 81B87A7
	.string "Ich hätte doch nicht kämpfen sollen...$"

Route104_Text_1B87C3:: @ 81B87C3
	.string "Wenn du vor einer Entscheidung stehst\n"
	.string "und einen anderen für dich entscheiden\l"
	.string "lässt, wirst du es bereuen. Egal, was\l"
	.string "dabei am Ende herauskommt.$"

Route104_Text_1B8839:: @ 81B8839
	.string "Komm schon, kämpf mit mir!$"

Route104_Text_1B8852:: @ 81B8852
	.string "Oohh...\n"
	.string "Ich dachte, ich könnte gewinnen...$"

Route104_Text_1B8872:: @ 81B8872
	.string "Ich kann diesen Verlust der Würde\n"
	.string "akzeptieren. Doch, doch...\p"
	.string "Aber trotzdem bin ich stinkig deswegen.$"

Route104_Text_1B88D4:: @ 81B88D4
	.string "Oh, natürlich nehme ich die Heraus-\n"
	.string "forderung an! Ich habe eine Menge Geld.$"

Route104_Text_1B8911:: @ 81B8911
	.string "Warum konnte ich nicht gewinnen?$"

Route104_Text_1B8925:: @ 81B8925
	.string "Manche Dinge kann man für Geld nicht\n"
	.string "kaufen. Das sind POKéMON...$"

Route104_Text_1B895E:: @ 81B895E
	.string "Nachdem ich gegen dich verloren hatte,\n"
	.string "habe ich viel über POKéMON gelernt.$"

Route104_Text_1B899E:: @ 81B899E
	.string "Ich habe schon wieder verloren???\n"
	.string "Warum... kann... ich... nicht... gewinnen?$"

Route104_Text_1B89C0:: @ 81B89C0
	.string "Ich bin unsagbar reich, aber einen\n"
	.string "Kampf kann ich nicht gewinnen...\p"
	.string "Sie ist so tiefgründig, die Welt der\n"
	.string "POKéMON.$"

Route104_Text_1B8A24:: @ 81B8A24
	.string "Das Schicksal hat uns zusammengeführt.\n"
	.string "Darf ich um einen Kampf bitten?$"

Route104_Text_1B8A61:: @ 81B8A61
	.string "Oh, meine Güte!$"

Route104_Text_1B8A69:: @ 81B8A69
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl.”\l"
	.string "Ich hoffe, wir sehen uns wieder.$"

Route104_Text_1B8AA7:: @ 81B8AA7
	.string "Hallo, so treffen wir uns wieder.\n"
	.string "Darf ich dich um einen Kampf bitten?$"

Route104_Text_1B8AD9:: @ 81B8AD9
	.string "Oh je...\n"
	.string "Ich habe mein Bestes gegeben...$"

Route104_Text_1B8B02:: @ 81B8B02
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl.”\l"
	.string "Ich hoffe, wir sehen uns wieder.$"

Route105_Text_1B8B40:: @ 81B8B40
	.string "Hier in der Gegend soll es einen\n"
	.string "mystischen Felsen geben. Weißt\l"
	.string "du etwas darüber?$"

Route105_Text_1B8B93:: @ 81B8B93
	.string "Ich habe zu sehr über den Felsen nach-\n"
	.string "gedacht, so dass meine POKéMON schwach\l"
	.string "blieben...$"

Route105_Text_1B8BDE:: @ 81B8BDE
	.string "Ich kann Stunden damit verbringen,\n"
	.string "einen Felsen anzustarren, ohne dass\l"
	.string "mir langweilig wird.$"

Route105_Text_1B8C28:: @ 81B8C28
	.string "Puuh! Als ich dich sah, habe ich zuerst\n"
	.string "gedacht, ein Kind würde ertrinken.\p"
	.string "Dir scheint nichts zu fehlen. Wie wäre\n"
	.string "es deshalb mit einem kleinen Kampf?$"

Route105_Text_1B8C99:: @ 81B8C99
	.string "Blubb... blubbb... blubb...$"

Route105_Text_1B8CA9:: @ 81B8CA9
	.string "Wenn du zu ertrinken drohst, musst du\n"
	.string "mit einem Arm in Richtung Strand winken.$"

Route105_Text_1B8CEE:: @ 81B8CEE
	.string "Im tiefen, blauen Meer schwimmen...\n"
	.string "Das ist das Größte überhaupt!$"

Route105_Text_1B8D23:: @ 81B8D23
	.string "Ich bin abgesoffen...$"

Route105_Text_1B8D45:: @ 81B8D45
	.string "Warum ist das Meer blau?\p"
	.string "Im MUSEUM in GRAPHITPORT CITY habe ich\n"
	.string "etwas dazu gelernt, habe es aber\l"
	.string "vergessen.$"

Route105_Text_1B8D99:: @ 81B8D99
	.string "Mein Körper fühlt sich im Wasser\n"
	.string "so leicht an, als hätte ich abgenommen.$"

Route105_Text_1B8DDD:: @ 81B8DDD
	.string "Ich lasse mich treiben...$"

Route105_Text_1B8DED:: @ 81B8DED
	.string "Dein Körpergewicht reduziert sich auf\n"
	.string "10 Prozent, wenn du im Wasser bist.\p"
	.string "Dann würde ich nur... Huups! Ich verrate\n"
	.string "dir doch nicht mein Gewicht!$"

Route105_Text_1B8E66:: @ 81B8E66
	.string "Der blaue, blaue Himmel...\n"
	.string "Das unendliche Meer...\l"
	.string "Es ist so friedlich...$"

Route105_Text_1B8EA0:: @ 81B8EA0
	.string "Ich habe verloren, weil ich hier nur\n"
	.string "herumhänge...$"

Route105_Text_1B8EBD:: @ 81B8EBD
	.string "So war der Kampf mit mir wenigstens\n"
	.string "entspannend. Kicher...$"

Route106_Text_1B8EF0:: @ 81B8EF0
	.string "Was bevorzugst du? Fischen im\n"
	.string "Meer oder im Fluss?$"

Route106_Text_1B8F25:: @ 81B8F25
	.string "Wie beim Tiefseefischen habe ich auch\n"
	.string "hier geradezu spektakulär verloren.$"

Route106_Text_1B8F55:: @ 81B8F55
	.string "Angeln ist das Größte, egal ob im Meer\n"
	.string "oder im Fluss. Stimmst du mir zu?$"

Route106_Text_1B8FAC:: @ 81B8FAC
	.string "Ich habe beim Angeln eine Menge\n"
	.string "POKéMON gefangen. Ich zeige sie dir!$"

Route106_Text_1B8FF5:: @ 81B8FF5
	.string "Ich habe wieder ganz famos verloren!$"

Route106_Text_1B9011:: @ 81B9011
	.string "Gewinnen, verlieren, POKéMON sind groß-\n"
	.string "artig! Stimmst du mir zu?$"

Route106_Text_1B9052:: @ 81B9052
	.string "Was machen Angler, wenn sie mal auf die\n"
	.string "Toilette müssen?\p"
	.string "Ich gehe nicht. Niemals! In der Zeit\n"
	.string "könnte ja etwas anbeißen.$"

Route106_Text_1B90D3:: @ 81B90D3
	.string "Ich habe verloren, weil ich nicht auf die\n"
	.string "Toilette gegangen bin.$"

Route106_Text_1B910A:: @ 81B910A
	.string "Oh! Ich habe das Gefühl, bald\n"
	.string "etwas Großes zu fangen.$"

Route106_Text_1B913D:: @ 81B913D
	.string "Hahaha! Ich bin ein lausiger Läufer,\n"
	.string "aber im Wasser fängst du mich nicht!$"

Route106_Text_1B917F:: @ 81B917F
	.string "Ich gebe auf!$"

Route106_Text_1B918A:: @ 81B918A
	.string "Beim Wettschwimmen wäre ich der Sieger!$"

Route106_Text_1B91AC:: @ 81B91AC
	.string "Das Meer ist mein Garten. Ich werde es\n"
	.string "dir nicht leicht machen, Kind!$"

Route106_Text_1B91F8:: @ 81B91F8
	.string "Konntest du es mir nicht leicht machen?$"

Route106_Text_1B9222:: @ 81B9222
	.string "Sich auf den Wellen treiben lassen...\n"
	.string "Ich liebe das! Versuch es doch auch mal!$"

Route107_Text_1B926B:: @ 81B926B
	.string "Gäähn...\p"
	.string "Ich muss wohl eingeschlafen sein, als\n"
	.string "ich mich auf den Wellen treiben ließ.$"

Route107_Text_1B92B7:: @ 81B92B7
	.string "Ahahaha, ich habe verloren...\n"
	.string "Ich mache jetzt ein Nickerchen...$"

Route107_Text_1B92E7:: @ 81B92E7
	.string "Sich treiben und von den Wellen\n"
	.string "schaukeln lassen - als ob man in einem\l"
	.string "weichen, bequemen Bett schläft.$"

Route107_Text_1B933A:: @ 81B933A
	.string "Das Meer ist wie mein Garten.\n"
	.string "Lass uns kämpfen.$"

Route107_Text_1B9365:: @ 81B9365
	.string "Ich habe in meinem eigenen Garten ver-\n"
	.string "loren... Ich bin geschockt!$"

Route107_Text_1B938E:: @ 81B938E
	.string "Ich schwimme im Meer, das Herz voller\n"
	.string "Träume...\p"
	.string "Das ist ein Lied!\n"
	.string "Wie auch immer, ich schwimme weiter.$"

Route107_Text_1B93EB:: @ 81B93EB
	.string "Durch das Schwimmen im Meer ist\n"
	.string "mein POKéMON stärker geworden!$"

Route107_Text_1B9429:: @ 81B9429
	.string "Was für ein Schock!\p"
	.string "Mein POKéMON ist stärker geworden,\n"
	.string "aber ich bin ein Weichei von TRAINER.$"

Route107_Text_1B9477:: @ 81B9477
	.string "Das, was du im Kampf lernst, macht dich\n"
	.string "zu einem starken TRAINER.\l"
	.string "Das haben mir die Wellen beigebracht.$"

Route107_Text_1B94C8:: @ 81B94C8
	.string "Kennst du einen kleinen Ort namens\n"
	.string "FAUSTAUHAVEN?$"

Route107_Text_1B94F2:: @ 81B94F2
	.string "Ich hasse das!$"

Route107_Text_1B94FF:: @ 81B94FF
	.string "Verrücktheiten zu erzählen ist der neue\n"
	.string "Trend in der FAUSTAUHAVEN HALLE.$"

Route107_Text_1B9538:: @ 81B9538
	.string "Willst du gegen mich kämpfen?\n"
	.string "Natürlich trete ich gegen dich an!$"

Route107_Text_1B956B:: @ 81B956B
	.string "Ich war nicht gut genug für dich.$"

Route107_Text_1B9589:: @ 81B9589
	.string "Ich denke, du wirst dich bemühen, noch\n"
	.string "besser zu werden. Das tue ich auch!$"

Route107_Text_1B95CB:: @ 81B95CB
	.string "BEA: Wir fordern dich als Bruder und\n"
	.string "Schwester heraus!$"

Route107_Text_1B95FB:: @ 81B95FB
	.string "BEA: Unglaublich.\n"
	.string "Du bist in einer anderen Stärke-Klasse.$"

Route107_Text_1B9630:: @ 81B9630
	.string "BEA: Hast du Freunde, die mit dir an den\n"
	.string "Strand gehen würden?$"

Route107_Text_1B9672:: @ 81B9672
	.string "BEA: Wenn du gegen uns kämpfen willst,\n"
	.string "bring mehr POKéMON mit.$"

Route107_Text_1B96AB:: @ 81B96AB
	.string "ERKO: Wir kämpfen immer mit POKéMON,\n"
	.string "meine Schwester und ich.\p"
	.string "Ich alleine verliere ständig, aber wir\n"
	.string "können dich 2-gegen-2 schlagen!$"

Route107_Text_1B9707:: @ 81B9707
	.string "ERKO: Huiuiui! Du kämpfst auf einem viel\n"
	.string "höheren Level als wir!$"

Route107_Text_1B9735:: @ 81B9735
	.string "ERKO: Meine Schwester hat mir mein\n"
	.string "POKéMON gegeben und nun ist es mein\l"
	.string "Partner!$"

Route107_Text_1B9788:: @ 81B9788
	.string "ERKO: Wenn du gegen uns antreten willst,\n"
	.string "bring mehr POKéMON mit.$"

Route108_Text_1B97C3:: @ 81B97C3
	.string "Mein Traum ist es, durch die sieben\n"
	.string "Weltmeere zu schwimmen.$"

Route108_Text_1B97EF:: @ 81B97EF
	.string "So werde ich niemals in der Lage sein,\n"
	.string "die sieben Weltmeere zu durchschwimmen.$"

Route108_Text_1B9823:: @ 81B9823
	.string "Mit maritimen POKéMON zu spielen, ist\n"
	.string "eine der Freuden beim Schwimmen.$"

Route108_Text_1B9864:: @ 81B9864
	.string "Ahoi, da! Willst du auch zum\n"
	.string "SCHIFFSWRACK?$"

Route108_Text_1B989F:: @ 81B989F
	.string "Ich gehe unter!\n"
	.string "Blubb... blubb... blubb...$"

Route108_Text_1B98BC:: @ 81B98BC
	.string "Einige Leute gehen sogar in das\n"
	.string "SCHIFFSWRACK hinein!$"

Route108_Text_1B98EC:: @ 81B98EC
	.string "Mein Freund, dieser Lügner, sagt,\n"
	.string "ich sähe klasse in dem Bikini aus...$"

Route108_Text_1B992C:: @ 81B992C
	.string "Oh, buuuh!$"

Route108_Text_1B9935:: @ 81B9935
	.string "Auch wenn es eine Lüge ist, liebe ich es,\n"
	.string "Komplimente zu bekommen.\l"
	.string "Wir Mädchen sind so komplex...$"

Route108_Text_1B9986:: @ 81B9986
	.string "Ich liebe das Meer! Ich vergesse all\n"
	.string "meine Probleme, wenn ich schwimme.$"

Route108_Text_1B99BB:: @ 81B99BB
	.string "Wenn ich verliere, bin ich total\n"
	.string "gestresst!$"

Route108_Text_1B99E9:: @ 81B99E9
	.string "Baue Stress durch Schwimmen ab.\n"
	.string "Das ist sehr gesund!$"

Route109_Text_1B9A1C:: @ 81B9A1C
	.string "Hiya! Schau dir meine gemeißelten \n"
	.string "Vollmatrosen an! Das nennt\l"
	.string "man einen “Schnitt”!$"

Route109_Text_1B9A59:: @ 81B9A59
	.string "Aiyah!\n"
	.string "Ausgerutscht.$"

Route109_Text_1B9A6D:: @ 81B9A6D
	.string "Hiyah!\p"
	.string "Meine gemeißelten Vollmatrosen haben\n"
	.string "nichts mit meinen Kämpfen zu tun!$"

Route109_Text_1B9AAD:: @ 81B9AAD
	.string "Hast du dich auch gut mit Sonnenmilch\n"
	.string "eingerieben?$"

Route109_Text_1B9AD9:: @ 81B9AD9
	.string "Aua, aua, aua.$"

Route109_Text_1B9AEB:: @ 81B9AEB
	.string "An den Wangen bekommt man als Erstes\n"
	.string "einen Sonnenbrand.$"

Route109_Text_1B9B11:: @ 81B9B11
	.string "Ich habe meinen Anker in vielen Häfen\n"
	.string "der Welt geworfen, aber GRAPHITPORT\l"
	.string "CITY ist der schönste Hafen.$"

Route109_Text_1B9B57:: @ 81B9B57
	.string "Du bist der Beste!$"

Route109_Text_1B9B68:: @ 81B9B68
	.string "Im besten Hafen gibt es auch den\n"
	.string "besten TRAINER...$"

Route109_Text_1B9B91:: @ 81B9B91
	.string "Urrrrppp...\n"
	.string "Kämpfen? Mit mir?$"

Route109_Text_1B9BAE:: @ 81B9BAE
	.string "Böör... Ooooooohhhhhh...\n"
	.string "Bööörrppp...$"

Route109_Text_1B9BD3:: @ 81B9BD3
	.string "Normalerweise bin ich viel stärker!\n"
	.string "Ich bin seekrank!\p"
	.string "Ich bin MATROSE, aber...$"

Route109_Text_1B9C23:: @ 81B9C23
	.string "Ich bin durstig... Ich könnte im\n"
	.string "STRANDHAUS etwas SPRUDEL kaufen...$"

Route109_Text_1B9C65:: @ 81B9C65
	.string "Grummel...$"

Route109_Text_1B9C6E:: @ 81B9C6E
	.string "Ich bin am Verhungern... Mein Schwimm-\n"
	.string "reifen sieht aus wie ein Schmalzkringel.$"

Route109_Text_1B9CB3:: @ 81B9CB3
	.string "Ich habe tierischen Hunger, aber ich\n"
	.string "habe genug Kraft für einen Kampf!$"

Route109_Text_1B9CEB:: @ 81B9CEB
	.string "Ich habe verloren...\n"
	.string "Und das nur, weil ich so hungrig bin...$"

Route109_Text_1B9D10:: @ 81B9D10
	.string "Wenn man am Strand sitzt und isst,\n"
	.string "schmeckt alles gleich viel besser.$"

Route109_Text_1B9D54:: @ 81B9D54
	.string "So ein Sonnenschirm sieht doch aus wie\n"
	.string "eine riesige Blume, findest du nicht?$"

Route109_Text_1B9D87:: @ 81B9D87
	.string "Maaaami!$"

Route109_Text_1B9D8E:: @ 81B9D8E
	.string "Ein Strand sieht aus der Luft be-\n"
	.string "trachtet wie ein Blumengarten aus.$"

Route109_Text_1B9DD8:: @ 81B9DD8
	.string "Ich verliere nicht wieder gegen dich!\n"
	.string "Schließlich habe ich einen Schwimm-\l"
	.string "reifen um!$"

Route109_Text_1B9E16:: @ 81B9E16
	.string "Maaaaaaaaaaamiiiii!$"

Route109_Text_1B9E1D:: @ 81B9E1D
	.string "Sobald ich den Schwimmreifen trage,\n"
	.string "sehen meine POKéMON und ich noch\l"
	.string "niedlicher aus!$"

Route109_Text_1B9E60:: @ 81B9E60
	.string "Ohne Schwimmreifen kann ich nicht\n"
	.string "schwimmen, aber im Kampf siege ich.$"

Route109_Text_1B9EA1:: @ 81B9EA1
	.string "Habe ich verloren, weil ich einen\n"
	.string "Schwimmreifen trage?$"

Route109_Text_1B9ECA:: @ 81B9ECA
	.string "Mein Schwimmreifen ist voll in Mode. Ohne\n"
	.string "ihn kann ich mich nicht sehen lassen!$"

Route109_Text_1B9F07:: @ 81B9F07
	.string "Hey, großer TRAINER!\n"
	.string "Kämpfst du mit mir?$"

Route109_Text_1B9F31:: @ 81B9F31
	.string "Oh, bist du aber stark!$"

Route109_Text_1B9F44:: @ 81B9F44
	.string "Wie bist du so stark geworden?$"

Route109_Text_1B9F65:: @ 81B9F65
	.string "Hahaha! Dieser Kerl hier wird jetzt\n"
	.string "einen großen Fang machen!$"

Route109_Text_1B9F9C:: @ 81B9F9C
	.string "Dieser Kerl hier hat ganz groß verloren.$"

Route109_Text_1B9FB7:: @ 81B9FB7
	.string "Dieser Kerl hier denkt, dass du ganz\n"
	.string "groß bist. Nein, ein Gernegroß bist!$"

Route109_Text_1B9FF6:: @ 81B9FF6
	.string "OLE: Nun, das ist ein Stimmungstöter!\p"
	.string "Ich wünschte, du würdest uns nicht \n"
	.string "unsere kostbare Zeit rauben!$"

Route109_Text_1BA052:: @ 81BA052
	.string "OLE: Nun, ich gebe mich geschlagen.$"

Route109_Text_1BA069:: @ 81BA069
	.string "OLE: Nun, sag niemandem, dass wir\n"
	.string "hier sind. Das ist unsere kleine, private\l"
	.string "Welt!$"

Route109_Text_1BA0BF:: @ 81BA0BF
	.string "OLE: Wir sind total heftig ineinander\n"
	.string "verliebt. Deshalb lassen wir unsere\l"
	.string "POKéMON auch gemeinsam kämpfen.$"

Route109_Text_1BA114:: @ 81BA114
	.string "GELI: Wir sind total ineinander verliebt.\n"
	.string "Unsere Romanze wärmt ganz HOENN!$"

Route109_Text_1BA15F:: @ 81BA15F
	.string "GELI: Wir haben verloren. Das ist meine\n"
	.string "Schuld. OLE wird mich hassen!$"

Route109_Text_1BA193:: @ 81BA193
	.string "GELI: Ähm, OLE, bist du böse auf mich?\n"
	.string "Bitte sei nicht böse auf mich!$"

Route109_Text_1BA1D0:: @ 81BA1D0
	.string "GELI: Wir sind total heftig ineinander\n"
	.string "verliebt. Daher kämpfen wir auch mit\l"
	.string "unseren POKéMON zusammen.$"

Route110_Text_1BA22C:: @ 81BA22C
	.string "Wow! Pass auf! Ich glaube, du hast\n"
	.string "keine Übung im RAD-Rennen.$"

Route110_Text_1BA264:: @ 81BA264
	.string "Wow! Pass auf!\n"
	.string "Meine Bremsen versagen!$"

Route110_Text_1BA27C:: @ 81BA27C
	.string "Platte Reifen und schwache Bremsen\n"
	.string "können zu Unfällen mit schweren Ver-\l"
	.string "letzungen führen! Also: Prüfe dein RAD!$"

Route110_Text_1BA2D4:: @ 81BA2D4
	.string "Hey, du!\n"
	.string "Kannst du mit mir mithalten?$"

Route110_Text_1BA2FC:: @ 81BA2FC
	.string "Du hast die Schallmauer durchbrochen!$"

Route110_Text_1BA30C:: @ 81BA30C
	.string "Geschwindigkeit alleine lässt mich nicht\n"
	.string "gewinnen. Das darf ich nicht vergessen.$"

Route110_Text_1BA352:: @ 81BA352
	.string "Nur keine Panik, wenn dein RAD immer\n"
	.string "schneller wird!$"

Route110_Text_1BA379:: @ 81BA379
	.string "Ich muss während eines POKéMON-\n"
	.string "Kampfes ruhig bleiben...$"

Route110_Text_1BA3A5:: @ 81BA3A5
	.string "Kein Grund zur Panik. Nimm’s leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_1BA3EF:: @ 81BA3EF
	.string "Bist du nicht ein wenig zu schnell? \n"
	.string "Brems ab und lass uns kämpfen.$"

Route110_Text_1BA432:: @ 81BA432
	.string "Ich war ganz ruhig und habe doch\n"
	.string "verloren...$"

Route110_Text_1BA456:: @ 81BA456
	.string "Kein Grund zur Panik. Nimm’s leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_1BA4A0:: @ 81BA4A0
	.string "Ein Triathlon ist extrem hart.\p"
	.string "Du musst schwimmen, Rad fahren und\n"
	.string "laufen.$"

Route110_Text_1BA50F:: @ 81BA50F
	.string "POKéMON-Kämpfe sind auch hart.$"

Route110_Text_1BA52E:: @ 81BA52E
	.string "Ich bin erschöpft und brauche eine\n"
	.string "Pause. Pausen sind extrem wichtig.$"

Route110_Text_1BA573:: @ 81BA573
	.string "Gibt es etwas Eleganteres, als einen\n"
	.string "Kampf während man Rad fährt?$"

Route110_Text_1BA5A1:: @ 81BA5A1
	.string "Wow...\n"
	.string "Wie kann man nur so stark sein?$"

Route110_Text_1BA5C4:: @ 81BA5C4
	.string "Bist du auf der Jagd nach Rekorden?\p"
	.string "Tut mir Leid, wenn ich dich dabei auf-\n"
	.string "gehalten habe.$"

Route110_Text_1BA5FF:: @ 81BA5FF
	.string "Ich radle ohne aufzuhören! Meine Ober-\n"
	.string "schenkel sind hart wie Stein!$"

Route110_Text_1BA63C:: @ 81BA63C
	.string "Muskelkrämpfe beunruhigen mich!$"

Route110_Text_1BA65F:: @ 81BA65F
	.string "Oh, du besitzt einige ORDEN der ARENEN.\n"
	.string "Kein Wunder, dass du so stark bist!$"

Route110_Text_1BA699:: @ 81BA699
	.string "Ich habe deine Absichten vorherge-\n"
	.string "sehen. Daher werde ich nicht verlieren!$"

Route110_Text_1BA6D2:: @ 81BA6D2
	.string "Ich konnte noch nicht einmal meine\n"
	.string "eigene Niederlage vorhersehen.$"

Route110_Text_1BA6F8:: @ 81BA6F8
	.string "Ich sehe deine Zukunft...\p"
	.string "Hmm...\n"
	.string "Ich sehe ein helles Licht...$"

Route110_Text_1BA72D:: @ 81BA72D
	.string "Ahahahahaha! Ich werde dich mit meinen\n"
	.string "Wundern verwirren!$"

Route110_Text_1BA759:: @ 81BA759
	.string "Ich habe ganz wunderlich verloren!$"

Route110_Text_1BA76C:: @ 81BA76C
	.string "Du konntest nur gewinnen, weil eben das\n"
	.string "das Wunder war! Ja, ein Wunder! Glaub ja\l"
	.string "nicht, dass du immer gewinnen kannst!$"

Route110_Text_1BA7D2:: @ 81BA7D2
	.string "Zeigst du mir deine POKéMON?\n"
	.string "Nur ganz kurz, ja?$"

Route110_Text_1BA803:: @ 81BA803
	.string "Ich möchte meine Sammlung\n"
	.string "vervollständigen...$"

Route110_Text_1BA829:: @ 81BA829
	.string "Wenn ich ein mir unbekanntes POKéMON\n"
	.string "sehe, kommt der Sammler in mir durch!$"

Route110_Text_1BA877:: @ 81BA877
	.string "Hi, hast du neue POKéMON gesammelt?\p"
	.string "Ich möchte einen Blick auf deine\n"
	.string "POKéMON werfen. Ganz kurz, bitte?$"

Route110_Text_1BA8CD:: @ 81BA8CD
	.string "Deine POKéMON...\n"
	.string "Ich bin richtig neidisch!$"

Route110_Text_1BA8E9:: @ 81BA8E9
	.string "Oh, ich möchte so gerne alle seltenen\n"
	.string "POKéMON besitzen.$"

Route110_Text_1BA913:: @ 81BA913
	.string "Hey!\n"
	.string "Schleich dich nicht so von hinten heran!$"

Route110_Text_1BA93C:: @ 81BA93C
	.string "Ich habe verloren!\n"
	.string "Verflixt!$"

Route110_Text_1BA94A:: @ 81BA94A
	.string "Angeln bedeutet höchste Konzentra-\n"
	.string "tion. Immer auf den Blinker achten!$"

Route110_Text_1BA990:: @ 81BA990
	.string "Ich würde überall hingehen, um meine\n"
	.string "elysischen POKéMON zu präsentieren.$"

Route110_Text_1BA9D0:: @ 81BA9D0
	.string "Oh, Schönheit reicht nicht aus...$"

Route110_Text_1BA9E9:: @ 81BA9E9
	.string "Ich sollte mich mehr auf WETTBEWERBE\n"
	.string "statt auf Kämpfe konzentrieren.$"

Route110_Text_1BAA2D:: @ 81BAA2D
	.string "Ich zeige dir meine elysischen\n"
	.string "POKéMON, sooft du willst!$"

Route110_Text_1BAA76:: @ 81BAA76
	.string "Oh, das war wieder nichts...$"

Route110_Text_1BAA8F:: @ 81BAA8F
	.string "WETTBEWERBE sind wunderbar, aber ich\n"
	.string "mag auch Kämpfe.$"

Route110_Text_1BAAC3:: @ 81BAAC3
	.string "Ich habe hier im hohen Gras einige coole\n"
	.string "POKéMON gefunden!$"

Route110_Text_1BAAF7:: @ 81BAAF7
	.string "Nur cool zu sein verhilft einem nicht\n"
	.string "zum Sieg...$"

Route110_Text_1BAB19:: @ 81BAB19
	.string "Mit POKéMON zu kämpfen, die man gerade\n"
	.string "erst gefangen hat, ist verdammt schwer.$"

Route111_Text_1BAB4B:: @ 81BAB4B
	.string "Das WÜSTENGLAS steht dir gut. Aber\n"
	.string "ich bin sicher, mir steht es besser!\p"
	.string "Wir entscheiden das besser in einem\n"
	.string "Kampf!$"

Route111_Text_1BABC7:: @ 81BABC7
	.string "Das WÜSTENGLAS hat meine Sicht\n"
	.string "eingeschränkt.$"

Route111_Text_1BAC10:: @ 81BAC10
	.string "Mit dem WÜSTENGLAS kann man durch\n"
	.string "Sandstürme laufen.\l"
	.string "Das macht mich richtig glücklich.$"

Route111_Text_1BAC60:: @ 81BAC60
	.string "Ich mache ein Picknick in der Wüste.\p"
	.string "Hier findet man überall TRAINER und so\n"
	.string "kann ich hier auch Kämpfe genießen.$"

Route111_Text_1BACC5:: @ 81BACC5
	.string "Oooh, du bist so gemein!$"

Route111_Text_1BACD8:: @ 81BACD8
	.string "Wenn du in einem Sandsturm kämpfst,\n"
	.string "achte auf die KP deiner POKéMON.\p"
	.string "Sie können vom Sandsturm verletzt\n"
	.string "werden und KP verlieren.$"

Route111_Text_1BAD4B:: @ 81BAD4B
	.string "Mit diesem WÜSTENGLAS fühle ich mich\n"
	.string "wie ein Superheld. Im Moment kann\l"
	.string "mich einfach niemand besiegen!$"

Route111_Text_1BADA3:: @ 81BADA3
	.string "Ich kann doch nicht nur im Geiste\n"
	.string "gewinnen...$"

Route111_Text_1BADC2:: @ 81BADC2
	.string "Eines Tages werde ich ein echter Held\n"
	.string "sein. Ich arbeite daran, mich und meine\l"
	.string "POKéMON richtig stark zu machen.$"

Route111_Text_1BAE24:: @ 81BAE24
	.string "Ich habe gehört, dass man in der Wüste\n"
	.string "Fossilien finden kann. Aber wo?$"

Route111_Text_1BAE6E:: @ 81BAE6E
	.string "Ich war in Gedanken bei den Fossilien...$"

Route111_Text_1BAE81:: @ 81BAE81
	.string "Da man in der Wüste Fossilien finden\n"
	.string "kann, war hier früher sicher ein Meer...$"

Route111_Text_1BAEC9:: @ 81BAEC9
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\l"
	.string "Werde ich jetzt herausgefordert?$"

Route111_Text_1BAF14:: @ 81BAF14
	.string "Ich habe nach Ruinen, aber leider nicht\n"
	.string "nach starken POKéMON gesucht...$"

Route111_Text_1BAF5B:: @ 81BAF5B
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Nee, warte... Seit 40 Jahren, oder? Oder\n"
	.string "doch 30 Jahre? Ach, ich weiß nicht...$"

Route111_Text_1BAFC1:: @ 81BAFC1
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Oder seit 40 Jahren???\n"
	.string "Egal! Forderst du mich heraus?$"

Route111_Text_1BB034:: @ 81BB034
	.string "Ich habe keine Ruinen, und auch keine\n"
	.string "starken POKéMON gefunden...$"

Route111_Text_1BB070:: @ 81BB070
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Glaube ich... Es können auch schon\n"
	.string "40 Jahre sein...\p"
	.string "Hmm... Andererseits kämen 50 Jahre auch\n"
	.string "hin... Mein Gedächtnis ist eine Ruine...$"

Route111_Text_1BB111:: @ 81BB111
	.string "Ich bin voller Schwung und Elan!\n"
	.string "Und mein POKéMON nicht minder!$"

Route111_Text_1BB140:: @ 81BB140
	.string "Mein POKéMON hat ausgeschwungen.$"

Route111_Text_1BB15B:: @ 81BB15B
	.string "Wenn ich einen TRAINER mit Schwung und\n"
	.string "Elan sehe, muss ich ihn anstarren.$"

Route111_Text_1BB199:: @ 81BB199
	.string "Ich weiß ja nicht, wo du hin willst, aber\n"
	.string "was sagst du zu einem Kämpfchen?$"

Route111_Text_1BB1D8:: @ 81BB1D8
	.string "Hui, du bist außergewöhnlich gut!$"

Route111_Text_1BB1F6:: @ 81BB1F6
	.string "Ich denke, ich sollte zum SCHLOTBERG\n"
	.string "gehen, aber hier ist es sooo schön...$"

Route111_Text_1BB250:: @ 81BB250
	.string "Ich trainiere ganz individuell: Ich for-\n"
	.string "dere alle TRAINER, die ich sehe, heraus.$"

Route111_Text_1BB27E:: @ 81BB27E
	.string "Ich gebe auf! Ich gebe auf!$"

Route111_Text_1BB290:: @ 81BB290
	.string "Alles was ich tun kann, ist weiter\n"
	.string "trainieren, bis ich starke TRAINER wie\l"
	.string "dich besiegen kann.$"

Route111_Text_1BB2E3:: @ 81BB2E3
	.string "Zeig mir, wie stark deine POKéMON\n"
	.string "geworden sind.$"

Route111_Text_1BB313:: @ 81BB313
	.string "Ich habe es zu spüren bekommen. Deine\n"
	.string "POKéMON sind viel stärker geworden.$"

Route111_Text_1BB33E:: @ 81BB33E
	.string "POKéMON und TRAINER lernen durch\n"
	.string "Kämpfe sehr viel.\p"
	.string "Wichtig ist, niemals aufzugeben, auch\n"
	.string "wenn du verlierst.$"

Route111_Text_1BB3A7:: @ 81BB3A7
	.string "Wir trainieren hier, um im Spiel einen\n"
	.string "Level weiterzukommen.\l"
	.string "Bleib hier und trainiere mit uns!$"

Route111_Text_1BB3FA:: @ 81BB3FA
	.string "Ooh, du bist unglaublich!$"

Route111_Text_1BB40E:: @ 81BB40E
	.string "Da du so stark bist, solltest du dir die\n"
	.string "POKéMON LIGA zum Ziel setzen.$"

Route111_Text_1BB44F:: @ 81BB44F
	.string "Oh, deine POKéMON machen den Eindruck\n"
	.string "ernsthafter Schauspieler.\l"
	.string "Ich möchte sie gerne engagieren.$"

Route111_Text_1BB49F:: @ 81BB49F
	.string "Sie sehen nicht nur stark aus, sie sind\n"
	.string "auch stark.$"

Route111_Text_1BB4CE:: @ 81BB4CE
	.string "Ich war überzeugt, meine POKéMON sorg-\n"
	.string "fältig aufgezogen zu haben. Aber nein,\l"
	.string "ich muss mich noch mehr anstrengen.$"

Route111_Text_1BB529:: @ 81BB529
	.string "Abhängig von den Attacken, die du ihnen\n"
	.string "beibringst, sind deine POKéMON stärker\l"
	.string "oder schwächer.\p"
	.string "Welche Attacken haben deine POKéMON\n"
	.string "auf Lager?$"

Route111_Text_1BB5A2:: @ 81BB5A2
	.string "Ihre Attacken sind wirklich gut.$"

Route111_Text_1BB5C1:: @ 81BB5C1
	.string "Meine POKéMON sollten sich vielleicht\n"
	.string "nicht eher entwickeln, bis sie wirklich\l"
	.string "gute Attacken gelernt haben...$"

Route112_Text_1BB619:: @ 81BB619
	.string "Hahahahahaha!\n"
	.string "Wie wäre es, wenn wir kämpfen?\l"
	.string "Du und ich!\l"
	.string "Hahahahahaha!$"

Route112_Text_1BB655:: @ 81BB655
	.string "Ich habe verloren!\n"
	.string "Hahahahahaha!$"

Route112_Text_1BB667:: @ 81BB667
	.string "Hahahahahaha! Irgendetwas ist mir in\n"
	.string "die Nase geflogen! Hahahahahaaatschiii!$"

Route112_Text_1BB6A0:: @ 81BB6A0
	.string "Meine Beine sind durch das Klettern in\n"
	.string "den Bergen richtig muskulös geworden.\p"
	.string "So leicht werden sie also nicht\n"
	.string "einknicken, mein Freund!$"

Route112_Text_1BB707:: @ 81BB707
	.string "Aua! Ich habe Muskelkrämpfe!$"

Route112_Text_1BB721:: @ 81BB721
	.string "Versuche mal, in den Bergen zu wandern.\n"
	.string "Und zwar mit richtig festem Schritt. Und\l"
	.string "das mit einem schweren Rucksack von\l"
	.string "mehreren Pfund Gewicht...\p"
	.string "So, mein Freund, bringst du deinen\n"
	.string "Körper richtig in Form.$"

Route112_Text_1BB7C7:: @ 81BB7C7
	.string "Ich halte mich mit Wandern fit!\n"
	.string "Dadurch habe ich viele Kräfte im Ärmel!$"

Route112_Text_1BB801:: @ 81BB801
	.string "Meine Ärmel waren wohl verknotet...$"

Route112_Text_1BB819:: @ 81BB819
	.string "Ich habe gehört, dass es am Gipfel vom\n"
	.string "SCHLOTBERG viele starke TRAINER gibt.\p"
	.string "Ich werde dort hochgehen und sie alle\n"
	.string "herausfordern!$"

Route112_Text_1BB893:: @ 81BB893
	.string "Ich bin stark. Ich weine bestimmt\n"
	.string "nicht, wenn ich verliere.$"

Route112_Text_1BB8B6:: @ 81BB8B6
	.string "Waaahaaa! Heul... Schluchz...$"

Route112_Text_1BB8BE:: @ 81BB8BE
	.string "Ich weine, weil ich meine Maaaaamiiii\n"
	.string "vermisse! Schluchz... Jammer...$"

Route112_Text_1BB8F0:: @ 81BB8F0
	.string "Machst du ein Picknick, dann musst du\n"
	.string "einfach vor Freude laut singen!\l"
	.string "Komm, wir singen zusammen.$"

Route112_Text_1BB942:: @ 81BB942
	.string "Oh, du triffst die Töne besser als ich!$"

Route112_Text_1BB958:: @ 81BB958
	.string "Es ist egal, ob du besser singst oder\n"
	.string "besser mit POKéMON kämpfen kannst.\p"
	.string "Wenn du Spaß hast, hast du schon\n"
	.string "gewonnen!$"

Route113_Text_1BB9BA:: @ 81BB9BA
	.string "Rate mal, warum es hier draußen so\n"
	.string "kühl ist.$"

Route113_Text_1BB9E6:: @ 81BB9E6
	.string "Puuuh äääh!\n"
	.string "Das stinkt!$"

Route113_Text_1BB9FB:: @ 81BB9FB
	.string "Die Vulkanasche lässt die Sonnen-\n"
	.string "strahlen nicht durch. Es bleibt kalt.\p"
	.string "Ich finde das angenehm, ich mag\n"
	.string "Hitze nicht.$"

Route113_Text_1BBA62:: @ 81BBA62
	.string "Der Vulkanausbruch ist der eindeutige\n"
	.string "Beweis, dass die Erde lebt.$"

Route113_Text_1BBA9B:: @ 81BBA9B
	.string "Du bist auf die eine oder andere\n"
	.string "Weise stark!$"

Route113_Text_1BBAB7:: @ 81BBAB7
	.string "Aua! Au au au! Ich kann nichts sehen!\n"
	.string "Ich habe ein Aschenauge!\p"
	.string "Hast du verstanden? Asche und Auge?\p"
	.string "Okay, blöder Witz, tut mir Leid...$"

Route113_Text_1BBB27:: @ 81BBB27
	.string "Ich habe einen Sonnenschirm, um diese\n"
	.string "staubige, widerliche Vulkanasche von\l"
	.string "meinem niedlichen CAMAUB fernzuhalten.$"

Route113_Text_1BBB7A:: @ 81BBB7A
	.string "Keuchl, pust...\n"
	.string "Ich bin total außer Atem...$"

Route113_Text_1BBB9A:: @ 81BBB9A
	.string "Du bist wirklich sehr gut. Ich muss\n"
	.string "sagen, ich bin schwer beeindruckt.$"

Route113_Text_1BBBCE:: @ 81BBBCE
	.string "Oh, hallo, wir haben uns ja ewig nicht ge-\n"
	.string "sehen. Ich lade dich zu einem Kampf ein.$"

Route113_Text_1BBC0D:: @ 81BBC0D
	.string "Oh, suuuuuper!$"

Route113_Text_1BBC1C:: @ 81BBC1C
	.string "Du bist immer noch sehr gut! Ich muss\n"
	.string "sagen, ich bin immer noch beeindruckt.$"

Route113_Text_1BBC59:: @ 81BBC59
	.string "Aus den Aschen erhebe ich mich! Kiyaih!\n"
	.string "Herausfordern tue ich dich! Kiyaih!$"

Route113_Text_1BBC90:: @ 81BBC90
	.string "Eine Ehre, von dir besiegt zu werden!$"

Route113_Text_1BBCAB:: @ 81BBCAB
	.string "Ich muss die Kunst des Versteckens\n"
	.string "verbessern. Mein Reimen auch. Leb wohl.$"

Route113_Text_1BBCE6:: @ 81BBCE6
	.string "Erhebe ich mich aus den Aschen, hast du\n"
	.string "nichts zu lachen. Kiyaih!$"

Route113_Text_1BBD1D:: @ 81BBD1D
	.string "Mein Versagen gereicht dir zur Ehre.$"

Route113_Text_1BBD38:: @ 81BBD38
	.string "Mein Versteck ist so lausig wie mein\n"
	.string "Kampfstil. Und meine Wortwahl erst...\p"
	.string "Ich lasse das Reimen und sage Lebwohl.$"

Route113_Text_1BBD92:: @ 81BBD92
	.string "Danke, dass du mich gefunden hast!\n"
	.string "Aber nun müssen wir kämpfen!$"

Route113_Text_1BBDC6:: @ 81BBDC6
	.string "Ich werde mein Ninjutsu gegen dich\n"
	.string "einsetzen...\p"
	.string "“VULKANASCHEN WIRBLER”!\n"
	.string "...Was? Es ist schon vorbei?$"

Route113_Text_1BBE1D:: @ 81BBE1D
	.string "Weißt du, was Sch... am Verstecken ist?\n"
	.string "Es ist einsam, wenn keiner vorbeikommt.$"

Route113_Text_1BBE65:: @ 81BBE65
	.string "LI: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_1BBEA1:: @ 81BBEA1
	.string "LI: Wir haben verloren... Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_1BBEE4:: @ 81BBEE4
	.string "LI: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_1BBF25:: @ 81BBF25
	.string "LI: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"

Route113_Text_1BBF62:: @ 81BBF62
	.string "FLO: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_1BBF9D:: @ 81BBF9D
	.string "FLO: Wir haben verloren... Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_1BBFE2:: @ 81BBFE2
	.string "FLO: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_1BC021:: @ 81BC021
	.string "FLO: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"

Route114_Text_1BC05B:: @ 81BC05B
	.string "Hollerididudljö!\p"
	.string "... ...\p"
	.string "Du musst jetzt mit “Hollerididudljö!”\n"
	.string "antworten, da es hier kein Echo gibt!$"

Route114_Text_1BC0B5:: @ 81BC0B5
	.string "Hollerididudljö!$"

Route114_Text_1BC0C3:: @ 81BC0C3
	.string "Als ich noch ein kleiner Lausbub war,\n"
	.string "habe ich immer gedacht, da wäre jemand,\l"
	.string "der mich ärgern will und \l"
	.string "“Hollerididudljö” antwortet.$"

Route114_Text_1BC125:: @ 81BC125
	.string "Ohne eine gute Ausrüstung solltest du\n"
	.string "dich nicht in die Berge wagen.$"

Route114_Text_1BC163:: @ 81BC163
	.string "Die Berge sind unerbittlich...$"

Route114_Text_1BC184:: @ 81BC184
	.string "Im Winter sind Berge lebensgefährlich,\n"
	.string "wegen der Blizzards und Lawinen.$"

Route114_Text_1BC1C8:: @ 81BC1C8
	.string "Campen macht Spaß! Du kannst angeln,\n"
	.string "Würstchen braten und andere mit\l"
	.string "Spukgeschichten zu Tode erschrecken!\p"
	.string "Aber das Beste sind die POKéMON-\n"
	.string "Kämpfe!$"

Route114_Text_1BC23F:: @ 81BC23F
	.string "Das war etwas zu schwer für mich!$"

Route114_Text_1BC24F:: @ 81BC24F
	.string "Ich finde es großartig, dass ich mit\n"
	.string "meinen POKéMON campen gehen kann.$"

Route114_Text_1BC289:: @ 81BC289
	.string "Nach dem Essen muss ich Sport treiben.\n"
	.string "Also lass uns kämpfen.$"

Route114_Text_1BC2BE:: @ 81BC2BE
	.string "Oh, nein!$"

Route114_Text_1BC2C6:: @ 81BC2C6
	.string "Ich hatte so ein leckeres Essen. Des-\n"
	.string "halb bin ich jetzt pappsatt und müde.$"

Route114_Text_1BC2F5:: @ 81BC2F5
	.string "Hufhufhufhufhufhuf...\n"
	.string "Komm, trete gegen mein POKéMON an.$"

Route114_Text_1BC327:: @ 81BC327
	.string "Mei... Mein POKéMON... hiiii...$"

Route114_Text_1BC337:: @ 81BC337
	.string "Einen großen Körper, der plump und hart\n"
	.string "ist, riesige Hörner und scharfe Fänge...\p"
	.string "Hufhufhufhuf...\n"
	.string "So ein POKéMON hätte ich gerne...$"

Route114_Text_1BC3B3:: @ 81BC3B3
	.string "Hufhufhufhufhuf...\n"
	.string "Komm, mein POKéMON ist bereit.$"

Route114_Text_1BC3E0:: @ 81BC3E0
	.string "Ich bin so froh, dass ich deine POKéMON\n"
	.string "sehen durfte...$"

Route114_Text_1BC40F:: @ 81BC40F
	.string "Hufhufhufhufhuf...\p"
	.string "Wenn ich POKéMON kämpfen sehe, fange\n"
	.string "ich an zu zittern und zu schaudern...$"

Route114_Text_1BC45A:: @ 81BC45A
	.string "Wenn du ein Lagerfeuer entzündest,\n"
	.string "muss immer Wasser in der Nähe sein.$"

Route114_Text_1BC499:: @ 81BC499
	.string "Gut, du hast mein Feuer gelöscht.$"

Route114_Text_1BC4B5:: @ 81BC4B5
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_1BC525:: @ 81BC525
	.string "Hast du gelernt, dass man immer Wasser\n"
	.string "neben einem Lagerfeuer stehen hat?$"

Route114_Text_1BC559:: @ 81BC559
	.string "Ich wurde schon gelöscht, bevor ich\n"
	.string "überhaupt zur Flamme ansetzen konnte.$"

Route114_Text_1BC58C:: @ 81BC58C
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_1BC5FC:: @ 81BC5FC
	.string "Wenn wir angeln wären, hättest du nicht\n"
	.string "den Hauch einer Chance gegen mich.\l"
	.string "Also, dann zeig mal deine POKéMON.$"

Route114_Text_1BC653:: @ 81BC653
	.string "Wären wir Angeln, hätte ich gewonnen!$"

Route114_Text_1BC679:: @ 81BC679
	.string "Ich werde mein Glück bei METEORFÄLLE\n"
	.string "versuchen und ein dickes Ding an Land\l"
	.string "ziehen.\p"
	.string "Da muss es etwas geben, das weiß ich\n"
	.string "genau!$"

Route114_Text_1BC6EC:: @ 81BC6EC
	.string "Ich liebe das Angeln. Aber ich liebe auch\n"
	.string "das Kämpfen!\p"
	.string "Wenn mich jemand herausfordern will, ich\n"
	.string "bin bereit. Auch wenn ich angle.$"

Route114_Text_1BC750:: @ 81BC750
	.string "Ich liebe Kämpfe, aber das heißt nicht,\n"
	.string "dass ich gut darin bin...$"

Route114_Text_1BC78A:: @ 81BC78A
	.string "Dieses Mal werde ich trainieren!\p"
	.string "Das denke ich jedes Mal und dann\n"
	.string "kann ich mich doch nicht von meiner\l"
	.string "Angel und meinen POKéMON trennen.$"

Route114_Text_1BC7E3:: @ 81BC7E3
	.string "TYRA: Natürlich. Ich bin in der\n"
	.string "richtigen Stimmung. Ich werde dir\l"
	.string "etwas über POKéMON beibringen.$"

Route114_Text_1BC834:: @ 81BC834
	.string "TYRA: Was für ein atemberaubender\n"
	.string "Kampfstil.$"

Route114_Text_1BC858:: @ 81BC858
	.string "TYRA: Ich bringe meiner Juniorin IVY\n"
	.string "etwas über POKéMON bei.$"

Route114_Text_1BC88A:: @ 81BC88A
	.string "TYRA: Kicher...\n"
	.string "Wenn du mit uns kämpfen willst, reicht\l"
	.string "ein POKéMON nicht aus.$"

Route114_Text_1BC8D8:: @ 81BC8D8
	.string "IVY: Wer hat dir das alles über POKéMON\n"
	.string "beigebracht?$"

Route114_Text_1BC8FB:: @ 81BC8FB
	.string "IVY: Was für ein unglaublicher Kampfstil!$"

Route114_Text_1BC91E:: @ 81BC91E
	.string "IVY: Ich habe angefangen, POKéMON zu\n"
	.string "trainieren, weil TYRA, meine Mentorin,\l"
	.string "es mir beigebracht hat!$"

Route114_Text_1BC96A:: @ 81BC96A
	.string "IVY: Hast du nur ein POKéMON? Ich\n"
	.string "glaube, das fühlt sich einsam!$"

Route115_Text_1BC9AC:: @ 81BC9AC
	.string "Hm...\n"
	.string "Du siehst ganz kompetent aus...\l"
	.string "Ich leiste dir Gesellschaft!$"

Route115_Text_1BC9E6:: @ 81BC9E6
	.string "Du bist viel stärker, als ich mir das\n"
	.string "vorgestellt hatte.$"

Route115_Text_1BCA0E:: @ 81BCA0E
	.string "Man wird nicht als Genie geboren!\n"
	.string "Alles basiert auf Anstrengung!\l"
	.string "Das ist meine Meinung...$"

Route115_Text_1BCA6B:: @ 81BCA6B
	.string "Hm... Deine Flinkheit spricht mal wieder\n"
	.string "für sich.\l"
	.string "Komm, leiste mir erneut Gesellschaft!$"

Route115_Text_1BCAB3:: @ 81BCAB3
	.string "Stark wie immer!$"

Route115_Text_1BCAC6:: @ 81BCAC6
	.string "Alles verlangt ein Maß an Anstrengung!\p"
	.string "Ich habe verloren, weil ich mich nicht\n"
	.string "genügend angestrengt habe.$"

Route115_Text_1BCB0D:: @ 81BCB0D
	.string "Du!\p"
	.string "Meine MACHOLLO!\p"
	.string "Verlangen einen Kampf!$"

Route115_Text_1BCB2E:: @ 81BCB2E
	.string "Aua aua aua aua!$"

Route115_Text_1BCB40:: @ 81BCB40
	.string "Meine MACHOLLO haben gejauchzt!\p"
	.string "Solange meine POKéMON nach Stärke\n"
	.string "suchen, werde auch ich stärker!$"

Route115_Text_1BCB8A:: @ 81BCB8A
	.string "Mein Talent ist, Ziegelsteine mit meiner\n"
	.string "Stirn zu zertrümmern.$"

Route115_Text_1BCBC1:: @ 81BCBC1
	.string "Uguaaah!\n"
	.string "Mein Kopf wurde zertrümmert.$"

Route115_Text_1BCBDE:: @ 81BCBDE
	.string "Ich bringe meinem POKéMON Karate bei.\p"
	.string "Und es sieht so aus, als wäre es darin\n"
	.string "viel besser als ich. Das freut mich.$"

Route115_Text_1BCC4C:: @ 81BCC4C
	.string "Nachdem du uns besiegt hattest, haben\n"
	.string "wir hart trainiert, um besser zu werden.\l"
	.string "Heute fordern wir Revanche!$"

Route115_Text_1BCCA2:: @ 81BCCA2
	.string "Uguaaah!\n"
	.string "Wir haben schon wieder verloren!$"

Route115_Text_1BCCBA:: @ 81BCCBA
	.string "Meine POKéMON werden stärker! Ich\n"
	.string "habe mein Trainingspensum verdoppelt.$"

Route115_Text_1BCCF4:: @ 81BCCF4
	.string "Dieser Strand ist mein geheimer\n"
	.string "Trainingsort. Du hast mich gestört!$"

Route115_Text_1BCD32:: @ 81BCD32
	.string "Ich habe nicht genug trainiert.$"

Route115_Text_1BCD4C:: @ 81BCD4C
	.string "Der Sand ist wie ein Kissen, das den\n"
	.string "Sturz abfängt und Verletzungen ver-\l"
	.string "hindert. Der perfekte Trainingsort.$"

Route115_Text_1BCDB0:: @ 81BCDB0
	.string "Okay, lass uns weiter kämpfen.$"

Route115_Text_1BCDD0:: @ 81BCDD0
	.string "Ich kann kämpfen, aber meine POKéMON...$"

Route115_Text_1BCDEF:: @ 81BCDEF
	.string "Sogar wenn ich verliere, habe ich meine\n"
	.string "Freude an dem Kampf. Wahrscheinlich\l"
	.string "weil ich die POKéMON liebe.$"

UnknownString_81BCE47: @ 81BCE47
	.string "Ich habe ein seltenes POKéMON.\n"
	.string "Möchtest du das mal sehen?$"

UnknownString_81BCE7D: @ 81BCE7D
	.string "Du...\n"
	.string "Du willst mein POKéMON haben, oder?$"

UnknownString_81BCEA4: @ 81BCEA4
	.string "Ich habe ein seltenes POKéMON. Das\n"
	.string "reicht mir, um zufrieden zu sein.$"

Route115_Text_1BCEE0:: @ 81BCEE0
	.string "Ich habe ein seltenes POKéMON.\n"
	.string "Willst du das mal sehen?$"

Route115_Text_1BCF16:: @ 81BCF16
	.string "Du... Du versuchst mir mein POKéMON\n"
	.string "abspenstig zu machen, oder?$"

Route115_Text_1BCF3D:: @ 81BCF3D
	.string "Und ich habe immer noch mein seltenes\n"
	.string "POKéMON, und damit bin ich zufrieden!$"

Route116_Text_1BCF79:: @ 81BCF79
	.string "Wenn es keinen Tunnel gibt, dann\n"
	.string "klettere ich eben über den Berg.$"

Route116_Text_1BCFBB:: @ 81BCFBB
	.string "Hechel... Keuch...\n"
	.string "Verlieren erschöpft mich...$"

Route116_Text_1BCFE3:: @ 81BCFE3
	.string "Macht auch nichts, wenn es keinen\n"
	.string "Tunnel gibt. Für WANDERER sind Berge\l"
	.string "wie Straßen.$"

Route116_Text_1BD02B:: @ 81BD02B
	.string "Meine POKéMON sind die Kings.\n"
	.string "Überzeug dich selbst!$"

Route116_Text_1BD04C:: @ 81BD04C
	.string "Auaaa! Ein Kratzer!\n"
	.string "Ich brauche dringend einen Verband.$"

Route116_Text_1BD078:: @ 81BD078
	.string "Verbände sind Zeichen von Rauheit!\n"
	.string "Ich brauche unbedingt einen weiteren!$"

Route116_Text_1BD0AF:: @ 81BD0AF
	.string "Meine KÄFER-POKéMON sind stark!\n"
	.string "Lass uns kämpfen!$"

Route116_Text_1BD0D7:: @ 81BD0D7
	.string "Ich habe verloren! Ich dachte,\n"
	.string "ich könnte dich am Kragen packen...$"

Route116_Text_1BD0F4:: @ 81BD0F4
	.string "KÄFER-POKéMON entwickeln sich schnell.\n"
	.string "So werden sie auch schnell stark.$"

Route116_Text_1BD131:: @ 81BD131
	.string "Ich bringe dir bei, wie stark mein\n"
	.string "geliebtes POKéMON ist!$"

Route116_Text_1BD165:: @ 81BD165
	.string "Du bist mir haushoch überlegen...$"

Route116_Text_1BD180:: @ 81BD180
	.string "POKéMON, die Anmut und Stärke besitzen,\n"
	.string "sind ideal, finde ich.$"

Route116_Text_1BD1C0:: @ 81BD1C0
	.string "Wir lernen alle möglichen Sachen in der\n"
	.string "TRAINERSCHULE.\p"
	.string "Ich will einiges jetzt mal ausprobieren.$"

Route116_Text_1BD21A:: @ 81BD21A
	.string "Ich habe in der Schule nicht aufge-\n"
	.string "passt. Daher habe ich verloren.$"

Route116_Text_1BD248:: @ 81BD248
	.string "Ich muss einige Kurse in der TRAINER-\n"
	.string "SCHULE wiederholen.\l"
	.string "Sonst wird FELIZIA vor Wut schäumen.$"

Route116_Text_1BD2A5:: @ 81BD2A5
	.string "Ich habe in der TRAINERSCHULE fleißig\n"
	.string "gelernt. Ich werde dieses Mal also mit\l"
	.string "Sicherheit nicht verlieren.$"

Route116_Text_1BD2FE:: @ 81BD2FE
	.string "Waaas?\n"
	.string "Aber ich habe doch so fleißig gelernt!$"

Route116_Text_1BD31A:: @ 81BD31A
	.string "Ich muss wohl erneut einige Kurse in der\n"
	.string "TRAINERSCHULE wiederholen.\l"
	.string "Sonst kocht FELIZIA über.$"

Route116_Text_1BD377:: @ 81BD377
	.string "Ich lerne in der Schule und auf dem\n"
	.string "Heimweg lerne ich auch!$"

Route116_Text_1BD3AC:: @ 81BD3AC
	.string "Ich bin geschockt! Ich habe verloren?!?$"

Route116_Text_1BD3C3:: @ 81BD3C3
	.string "Argh, so werde ich nie so ein eleganter\n"
	.string "TRAINER wie FELIZIA!$"

Route116_Text_1BD405:: @ 81BD405
	.string "Seit unserem letzten Kampf habe ich\n"
	.string "viel gelernt. Das musst du dir ansehen!$"

Route116_Text_1BD44A:: @ 81BD44A
	.string "Ach, das gibt es doch nicht...$"

Route116_Text_1BD466:: @ 81BD466
	.string "Du hast FELIZIA besiegt?!?\n"
	.string "Dann kann ich dich nicht besiegen. Nee...$"

Route117_Text_1BD49E:: @ 81BD49E
	.string "Du? Würdest du gegen meine POKéMON\n"
	.string "kämpfen?$"

Route117_Text_1BD4D9:: @ 81BD4D9
	.string "Du hast einfach großartige POKéMON...$"

Route117_Text_1BD4F9:: @ 81BD4F9
	.string "POKéMON sind nicht nur durch Stärke\n"
	.string "definiert.\p"
	.string "Jedes POKéMON hat seinen eigenen\n"
	.string "Charakter. Dadurch wird der Umgang\l"
	.string "mit ihnen noch viel interessanter.$"

Route117_Text_1BD569:: @ 81BD569
	.string "Die POKéMON, die ich aufgezogen habe,\n"
	.string "sehen gut aus. Genau wie immer.$"

Route117_Text_1BD5AB:: @ 81BD5AB
	.string "Du weißt, wie man sie richtig aufzieht.\n"
	.string "Du hast die Talente, die man in einer\l"
	.string "PENSION braucht.$"

Route117_Text_1BD5F2:: @ 81BD5F2
	.string "Deine POKéMON entwickeln sich gut.\n"
	.string "Du solltest sie zu einem WETTBEWERB\l"
	.string "anmelden!$"

Route117_Text_1BD634:: @ 81BD634
	.string "Bitte lass mich überprüfen, ob du deine\n"
	.string "POKéMON auch richtig aufgezogen hast.$"

Route117_Text_1BD67B:: @ 81BD67B
	.string "Ja, sie sehen sehr gut aus...$"

Route117_Text_1BD69B:: @ 81BD69B
	.string "Wenn du deinen POKéMON {POKEBLOCK}\n"
	.string "gibst, entwickeln sich ihre individuellen\l"
	.string "Charaktereigenschaften.$"

Route117_Text_1BD6F2:: @ 81BD6F2
	.string "Erlaube mir, noch einmal zu prüfen, ob\n"
	.string "du deine POKéMON richtig aufziehst.$"

Route117_Text_1BD733:: @ 81BD733
	.string "Sie wurden sehr, sehr gut aufgezogen...$"

Route117_Text_1BD74F:: @ 81BD74F
	.string "POKéMON mögen, abhängig von ihrem\n"
	.string "Wesen, die unterschiedlichsten {POKEBLOCK}.$"

Route117_Text_1BD79A:: @ 81BD79A
	.string "Ich bin mitten in einem Triathlon. Aber\n"
	.string "lass uns trotzdem kämpfen!$"

Route117_Text_1BD7E0:: @ 81BD7E0
	.string "Ich habe keine Energie mehr!$"

Route117_Text_1BD7F5:: @ 81BD7F5
	.string "Ich habe es wohl verpatzt...\p"
	.string "Ich habe in meinem letzten Kampf\n"
	.string "stark nachgelassen...$"

Route117_Text_1BD83F:: @ 81BD83F
	.string "Ich bin mitten in einem Triathlon, liege\n"
	.string "aber weit an der Spitze. Lass uns zu\l"
	.string "einem schnellen Kampf antreten.$"

Route117_Text_1BD8A2:: @ 81BD8A2
	.string "Ich habe schon wieder meine Energie\n"
	.string "verloren!$"

Route117_Text_1BD8BD:: @ 81BD8BD
	.string "Im Schwimmen und im Radfahren bin ich\n"
	.string "unschlagbar, aber meine Leistungen in\l"
	.string "POKéMON-Kämpfen sind unbefriedigend.$"

Route117_Text_1BD914:: @ 81BD914
	.string "Ich trainiere mit meinem POKéMON und\n"
	.string "bin mit meinen Fähigkeiten echt\l"
	.string "zufrieden.$"

Route117_Text_1BD965:: @ 81BD965
	.string "Ich glaube, ich muss wirklich mehr üben.$"

Route117_Text_1BD98F:: @ 81BD98F
	.string "Training zahlt sich nur aus, wenn man\n"
	.string "regelmäßig trainiert.\p"
	.string "Okay! Ich setze mein Training fort!\n"
	.string "Morgen!$"

Route117_Text_1BD9F1:: @ 81BD9F1
	.string "Trainierst du auch fleißig weiter?\n"
	.string "Ich trainiere sehr fleißig!\l"
	.string "Ich liefere dir den Beweis.$"

Route117_Text_1BDA41:: @ 81BDA41
	.string "Ich muss, glaube ich, doch noch mehr\n"
	.string "trainieren.$"

Route117_Text_1BDA6B:: @ 81BDA6B
	.string "Ich werde mein Training morgen fort-\n"
	.string "setzen. Lass uns bald wieder kämpfen!$"

Route117_Text_1BDAA7:: @ 81BDAA7
	.string "Einst war ich KÄFERSAMMLER.\n"
	.string "Heute bin ich ein KÄFERFREAK!\p"
	.string "Aber meine Liebe zu POKéMON hat sich\n"
	.string "nicht verändert!$"

Route117_Text_1BDAFC:: @ 81BDAFC
	.string "Meine Ungeschicktheit ist auch\n"
	.string "ungebrochen...$"

Route117_Text_1BDB24:: @ 81BDB24
	.string "Alles, was ich getan habe, war meinem\n"
	.string "Herzen zu folgen, und nun nennen sie\l"
	.string "mich den KÄFERFREAK...\p"
	.string "Aber ich bin ein Experte für KÄFER-\n"
	.string "POKéMON, daher ist es nur natürlich,\l"
	.string "dass sie mich KÄFERFREAK nennen.$"

Route117_Text_1BDBC3:: @ 81BDBC3
	.string "IRM: Ich bin hier mit meiner hübschen\n"
	.string "Junior-Studentin. Ich muss gut sein!$"

Route117_Text_1BDC07:: @ 81BDC07
	.string "IRM: Ich bin mit meiner hübschen\n"
	.string "Junior-Studentin hier. Ich wollte so\l"
	.string "gerne gewinnen!$"

Route117_Text_1BDC44:: @ 81BDC44
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_1BDC96:: @ 81BDC96
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "bring zwei POKéMON mit.$"

Route117_Text_1BDCD2:: @ 81BDCD2
	.string "IDA: Ich werde mich mit meiner Super-\n"
	.string "Senior-Studentin verbünden und siegen!$"

Route117_Text_1BDD1E:: @ 81BDD1E
	.string "IDA: Oh, nein! Tut mir Leid, IRM.\n"
	.string "Ich habe dich im Stich gelassen.$"

Route117_Text_1BDD4E:: @ 81BDD4E
	.string "IDA: Ich habe IRM in eine Niederlage\n"
	.string "gebracht. Ohne mich hätte sie gewonnen!$"

Route117_Text_1BDD8B:: @ 81BDD8B
	.string "IDA: Hast du nur ein POKéMON?\n"
	.string "Dann können wir nicht mit dir kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"

Route117_Text_1BDDEF:: @ 81BDDEF
	.string "IRM: Ich kann doch nicht ständig vor\n"
	.string "meiner Junior-Partnerin verlieren...$"

Route117_Text_1BDE2F:: @ 81BDE2F
	.string "IRM: Ich komme einfach nicht in Fahrt.$"

Route117_Text_1BDE55:: @ 81BDE55
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_1BDEA7:: @ 81BDEA7
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "brauchst du zwei POKéMON.$"

Route117_Text_1BDEE3:: @ 81BDEE3
	.string "IDA: Ich werde mich mit meiner\n"
	.string "Senior-Studentin verbünden und siegen!$"

Route117_Text_1BDF26:: @ 81BDF26
	.string "IDA: Viel zu stark!$"

Route117_Text_1BDF37:: @ 81BDF37
	.string "IDA: Ich habe mit meiner Senior-\n"
	.string "Partnerin gekämpft. Wir haben verloren.\p"
	.string "Das ist so entmutigend...$"

Route117_Text_1BDF90:: @ 81BDF90
	.string "IDA: Besitzt du nur ein POKéMON?\n"
	.string "Dann können wir nicht kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"

Route118_Text_1BDFF4:: @ 81BDFF4
	.string "Der Duft von Blumen hat eine magische\n"
	.string "Kraft. Er reinigt Körper und Geist.$"

Route118_Text_1BE03C:: @ 81BE03C
	.string "Oh, du meine Güte.\n"
	.string "Scheinbar habe ich verloren.$"

Route118_Text_1BE05E:: @ 81BE05E
	.string "Blumen, POKéMON...\n"
	.string "Ich liebe alles, was gut riecht.\p"
	.string "Stinkende Dinge...\n"
	.string "Bah, da muss ich passen.$"

Route118_Text_1BE0AB:: @ 81BE0AB
	.string "Hat dich der süße Duft hierher\n"
	.string "gebracht?$"

Route118_Text_1BE0D3:: @ 81BE0D3
	.string "Die Kraft des Duftes...\n"
	.string "Sie scheint nichts zu bewirken.$"

Route118_Text_1BE104:: @ 81BE104
	.string "Wenn du einen süßen Duft richtig ein-\n"
	.string "setzt, werden POKéMON davon\l"
	.string "angezogen.$"

Route118_Text_1BE148:: @ 81BE148
	.string "VOGEL-POKéMON, die elegant durch die\n"
	.string "Lüfte FLIEGEN... Sie sind die Besten!$"

Route118_Text_1BE188:: @ 81BE188
	.string "Argh... Das war eine Bruchlandung...$"

Route118_Text_1BE19D:: @ 81BE19D
	.string "Du hast großartige POKéMON.\n"
	.string "Ich muss meines besser trainieren.$"

Route118_Text_1BE1D7:: @ 81BE1D7
	.string "Erhebt euch!\n"
	.string "Meine VOGEL-POKéMON!$"

Route118_Text_1BE1F5:: @ 81BE1F5
	.string "Sie sind abgehoben...$"

Route118_Text_1BE20D:: @ 81BE20D
	.string "Wenn sie erst einmal stärker geworden\n"
	.string "sind, können sie auch freier fliegen.$"

Route118_Text_1BE24A:: @ 81BE24A
	.string "Ich bin ein ANGLER, aber auch ein\n"
	.string "TRAINER. Ich ziehe die POKéMON auf,\l"
	.string "die ich gefangen habe.$"

Route118_Text_1BE291:: @ 81BE291
	.string "Ich dachte, ich wäre gut im Training...$"

Route118_Text_1BE2BE:: @ 81BE2BE
	.string "Ich kann nicht gewinnen, wenn ich\n"
	.string "POKéMON trainiere, während ich angle.\p"
	.string "Habe ich alles nur halb getan?$"

Route118_Text_1BE318:: @ 81BE318
	.string "Für ANGLER ist die Ausrüstung\n"
	.string "entscheidend.\p"
	.string "Aber für TRAINER sind natürlich die\n"
	.string "POKéMON und das Herz entscheidend!$"

Route118_Text_1BE385:: @ 81BE385
	.string "Ich wurde im Herzen geschlagen?$"

Route118_Text_1BE39C:: @ 81BE39C
	.string "Wenn ich so darüber nachdenke, komme\n"
	.string "ich zu dem Schluss, dass Angeln ein\l"
	.string "Kampf zwischen ANGLER und POKéMON ist.$"

Route118_Text_1BE3E8:: @ 81BE3E8
	.string "Meine Melodie wird deine Seele\n"
	.string "erschüttern.$"

Route118_Text_1BE406:: @ 81BE406
	.string "La-lalala...$"

Route118_Text_1BE413:: @ 81BE413
	.string "Eine E-Gitarre muss nicht immer laut\n"
	.string "sein...\p"
	.string "Sie kann auch so gespielt werden, dass\n"
	.string "eine herzergreifende Melodie erklingt...$"

Route118_Text_1BE489:: @ 81BE489
	.string "Eine Melodie von meinen POKéMON und mir.\n"
	.string "Lass sie uns deiner Seele schenken.$"

Route118_Text_1BE4CC:: @ 81BE4CC
	.string "La-lalala...$"

Route118_Text_1BE4D9:: @ 81BE4D9
	.string "Wenn ich spiele, sollten dich meine Ge-\n"
	.string "fühle über meine E-Gitarre erreichen...$"

Route119_Text_1BE521:: @ 81BE521
	.string "Wir gehören zum Mimikry-Zirkel!\n"
	.string "Wir ahmen nach, was du machst!$"

Route119_Text_1BE54F:: @ 81BE54F
	.string "Huupsie!\n"
	.string "Ich habe verloren!$"

Route119_Text_1BE561:: @ 81BE561
	.string "Was so toll an Mimikry sein soll?\p"
	.string "Hähähä...\n"
	.string "Das wirst du nie verstehen...$"

Route119_Text_1BE5A4:: @ 81BE5A4
	.string "So trifft man sich! Meine KÄFER-POKéMON\n"
	.string "leisten dir Gesellschaft!$"

Route119_Text_1BE5DF:: @ 81BE5DF
	.string "Ich wünschte, wir hätten uns nie\n"
	.string "getroffen...$"

Route119_Text_1BE5F8:: @ 81BE5F8
	.string "Ich möchte noch Mimikry bei dir an-\n"
	.string "wenden.\p"
	.string "Kannst du dich mal ein bisschen\n"
	.string "bewegen?$"

Route119_Text_1BE632:: @ 81BE632
	.string "Trittst du einen Schritt vor, treten wir\n"
	.string "auch einen Schritt vor.\p"
	.string "Drehst du dich nach rechts, drehen wir\n"
	.string "uns auch nach rechts...$"

Route119_Text_1BE67B:: @ 81BE67B
	.string "Aber wenn du gewinnst, verliere ich...$"

Route119_Text_1BE695:: @ 81BE695
	.string "Ich kann nicht mit Mimikry nachahmen,\n"
	.string "wie du den Kampf gewinnst. Unmöglich!\l"
	.string "Das lässt mich kochen vor Wut.$"

Route119_Text_1BE6EA:: @ 81BE6EA
	.string "Hey, geschafft! Du hast mich gefunden!\n"
	.string "Oder wolltest du mir ausweichen?$"

Route119_Text_1BE729:: @ 81BE729
	.string "Hui, was für ein großartiger Kampf!$"

Route119_Text_1BE748:: @ 81BE748
	.string "Wir sind der Mimikry-Zirkel! Ich\n"
	.string "hoffe, dir gefiel unsere Vorstellung!$"

Route119_Text_1BE784:: @ 81BE784
	.string "Du weißt nicht, wer ich bin, stimmt’s?\p"
	.string "Aber... Ich kenne dich auch nicht.\n"
	.string "Lass uns kämpfen.$"

Route119_Text_1BE7D3:: @ 81BE7D3
	.string "Du bist ganz schön stark!$"

Route119_Text_1BE7E9:: @ 81BE7E9
	.string "Solange du hier bist, werden wir jede\n"
	.string "deiner Bewegungen nachahmen.$"

Route119_Text_1BE82F:: @ 81BE82F
	.string "Der Mimikry-Zirkel wurde von Leuten\n"
	.string "gegründet, die die Mimikry lieben.\p"
	.string "Der Kampf beginnt, sobald wir aufei-\n"
	.string "nander treffen!$"

Route119_Text_1BE88D:: @ 81BE88D
	.string "Ich gebe auf!$"

Route119_Text_1BE89A:: @ 81BE89A
	.string "Möchtest du nicht dem Mimikry-Zirkel\n"
	.string "beitreten?$"

Route119_Text_1BE8BB:: @ 81BE8BB
	.string "Wer besitzt das Wissen und die Technik,\n"
	.string "um zu überleben?\p"
	.string "Das sind die POKéMON-RANGER!$"

Route119_Text_1BE90E:: @ 81BE90E
	.string "Ich besitze nicht genügend Wissen über\n"
	.string "POKéMON...$"

Route119_Text_1BE937:: @ 81BE937
	.string "Aus der Zivilisation ausbrechen und die\n"
	.string "wilde Natur in uns erwecken!\p"
	.string "Das ist unsere Vision.$"

Route119_Text_1BE98D:: @ 81BE98D
	.string "Meine wilde Natur regt sich in mir, wenn\n"
	.string "ich mit POKéMON zusammen bin.$"

Route119_Text_1BE9D0:: @ 81BE9D0
	.string "Du bist immer noch sehr stark!$"

Route119_Text_1BE9E8:: @ 81BE9E8
	.string "Glaube an deine POKéMON.\n"
	.string "Glaube an dich.\p"
	.string "Dein Weg eröffnet sich von selbst.$"

Route119_Text_1BEA3A:: @ 81BEA3A
	.string "Oh! Schau dich nur an!\p"
	.string "Für einen Abenteurer hast du\n"
	.string "sehr leichtes Gepäck dabei!$"

Route119_Text_1BEA88:: @ 81BEA88
	.string "Unfälle passieren immer dann, wenn du\n"
	.string "nicht damit rechnest!$"

Route119_Text_1BEAB3:: @ 81BEAB3
	.string "Du hast leichtes Gepäck, aber alles, was\n"
	.string "du brauchst dabei.\p"
	.string "Du bist an der Spitze deiner geistigen\n"
	.string "und körperlichen Kraft angekommen.$"

Route119_Text_1BEB22:: @ 81BEB22
	.string "Wie läuft es auf deiner Reise mit den\n"
	.string "POKéMON?$"

Route119_Text_1BEB49:: @ 81BEB49
	.string "Bei mir fehlt irgendetwas...$"

Route119_Text_1BEB68:: @ 81BEB68
	.string "So wie du als TRAINER deinen POKéMON\n"
	.string "vertraust, vertrauen dir deine POKéMON.$"

Route119_Text_1BEBC0:: @ 81BEBC0
	.string "Die Weiten des Himmels strahlen die Aura\n"
	.string "unausgesprochener Versprechen ab.\p"
	.string "Nichts ist vergleichbar mit dem\n"
	.string "absoluten Glück des Fliegens!$"

Route119_Text_1BEC1C:: @ 81BEC1C
	.string "Abgewürgt und abgestürzt.$"

Route119_Text_1BEC2A:: @ 81BEC2A
	.string "Meine VOGEL-POKéMON lassen den Traum\n"
	.string "vom Fliegen für mich wahr werden!$"

Route119_Text_1BEC5E:: @ 81BEC5E
	.string "Ich zeige dir meine wahre Stärke und\n"
	.string "die meiner VOGEL-POKéMON!$"

Route119_Text_1BEC9A:: @ 81BEC9A
	.string "Uns fehlt es an Potential...$"

Route119_Text_1BECB1:: @ 81BECB1
	.string "Schon als kleines Kind habe ich VOGEL-\n"
	.string "POKéMON geliebt...$"

Route119_Text_1BECF1:: @ 81BECF1
	.string "Ich lauere in den Schatten und lebe in\n"
	.string "der Dunkelheit... Das ist mein Schicksal.\p"
	.string "Ich tauche auf, um dich heraus-\n"
	.string "zufordern!$"

Route119_Text_1BED4C:: @ 81BED4C
	.string "Ich gestehe meine Niederlage ein.$"

Route119_Text_1BED5C:: @ 81BED5C
	.string "Die, die im Kampf geschlagen wurden,\n"
	.string "verschwinden lautlos in der Dunkelheit.\l"
	.string "Auch das ist Schicksal...$"

Route119_Text_1BEDB6:: @ 81BEDB6
	.string "Wenn du nicht auf deine Deckung auf-\n"
	.string "passt, kommt der Schmerz zu dir!$"

Route119_Text_1BEDEC:: @ 81BEDEC
	.string "Du bist überraschend gut!$"

Route119_Text_1BEE06:: @ 81BEE06
	.string "Mein Überraschungsangriff endete in\n"
	.string "einer Niederlage...$"

Route119_Text_1BEE2D:: @ 81BEE2D
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald!$"

Route119_Text_1BEE4B:: @ 81BEE4B
	.string "Ich verneige mich vor deiner Stärke.$"

Route119_Text_1BEE66:: @ 81BEE66
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald. Um ein POKéMON zu verstecken,\l"
	.string "nutze ein POKéMON!\p"
	.string "Dahinter steckt keine tiefere\n"
	.string "Bedeutung.$"

Route119_Text_1BEED0:: @ 81BEED0
	.string "Du hast mich angesprochen...\n"
	.string "Also willst du mit mir kämpfen!\p"
	.string "Sicher! Ich will das POKéMON einsetzen,\n"
	.string "das ich gefangen habe, als ich SURFER\l"
	.string "einsetzte.$"

Route119_Text_1BEF37:: @ 81BEF37
	.string "Ich habe keine Ahnung, was verlangt\n"
	.string "wird, um zu gewinnen.$"

Route119_Text_1BEF67:: @ 81BEF67
	.string "Nutze ein POKéMON als SURFER...\p"
	.string "Dann angle von seinem Rücken aus...\p"
	.string "Ein äußerst angenehmer Zeitvertreib!$"

Route120_Text_1BEFC8:: @ 81BEFC8
	.string "Hast du Attacken auf Lager, die ein\n"
	.string "fliegendes POKéMON schlagen können?$"

Route120_Text_1BF000:: @ 81BF000
	.string "Du bist mir überlegen!$"

Route120_Text_1BF015:: @ 81BF015
	.string "Die Attacke FLIEGEN ist sehr praktisch,\n"
	.string "meinst du nicht auch?\p"
	.string "Wenn ein POKéMON fliegt, kann ihm fast\n"
	.string "keine Attacke Schaden zufügen.$"

Route120_Text_1BF07E:: @ 81BF07E
	.string "Mein POKéMON ist stark!\n"
	.string "Wie sieht es mit deinen aus?$"

Route120_Text_1BF0A5:: @ 81BF0A5
	.string "Deine POKéMON sind stärker...$"

Route120_Text_1BF0C3:: @ 81BF0C3
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig...$"

Route120_Text_1BF0FA:: @ 81BF0FA
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig...$"

Route120_Text_1BF131:: @ 81BF131
	.string "Deine POKéMON sind enorm stark.$"

Route120_Text_1BF154:: @ 81BF154
	.string "Meine POKéMON werden immer stärker.\n"
	.string "Ich muss auch immer stärker werden.$"

Route120_Text_1BF193:: @ 81BF193
	.string "Ich prüfe deine POKéMON und schaue, ob\n"
	.string "sie fit für das Leben im Freien sind.$"

Route120_Text_1BF1D4:: @ 81BF1D4
	.string "Mit solch starken POKéMON brauchst du\n"
	.string "in der Natur keine Angst zu haben.$"

Route120_Text_1BF215:: @ 81BF215
	.string "Mit POKéMON dorthin zu reisen, wohin\n"
	.string "man auch immer will... Das ist das\l"
	.string "Schöne an einem Leben als TRAINER.$"

Route120_Text_1BF26E:: @ 81BF26E
	.string "Wie sieht es mit deiner Fitness aus?\n"
	.string "Wenn du nicht fit bist, könnten \l"
	.string "harte Zeiten auf dich zukommen.$"

Route120_Text_1BF2D2:: @ 81BF2D2
	.string "Ich bin fit wie ein Turnschuh, aber...$"

Route120_Text_1BF2EA:: @ 81BF2EA
	.string "Fitnesstraining gehört zu meinem\n"
	.string "Leben. Ich laufe mit meinen POKéMON.$"

Route120_Text_1BF32B:: @ 81BF32B
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Kampf gefällig?$"

Route120_Text_1BF36B:: @ 81BF36B
	.string "... ... ... ... ... ...\n"
	.string "Ich habe verloren...$"

Route120_Text_1BF38D:: @ 81BF38D
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Muss mich mehr anstrengen...$"

Route120_Text_1BF3D0:: @ 81BF3D0
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Noch ein Kampf gefällig?$"

Route120_Text_1BF416:: @ 81BF416
	.string "... ... ... ... ... ...\n"
	.string "Ich habe wieder verloren...$"

Route120_Text_1BF43E:: @ 81BF43E
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Ich werde mich mehr anstrengen...\l"
	.string "Für meine kostbaren KÄFER-POKéMON...$"

Route120_Text_1BF4A0:: @ 81BF4A0
	.string "POKéMON haben viele spezielle Fähig-\n"
	.string "keiten. Wenn du ein klasse TRAINER\l"
	.string "werden willst, lerne etwas darüber.$"

Route120_Text_1BF504:: @ 81BF504
	.string "Du setzt offensichtlich dein Gehirn ein.$"

Route120_Text_1BF51F:: @ 81BF51F
	.string "Die speziellen Fähigkeiten eines\n"
	.string "POKéMON bestimmen den Kampfstil.$"

Route120_Text_1BF560:: @ 81BF560
	.string "Wer magst du sein?\p"
	.string "Suchst du etwa nach antiken Ruinen,\n"
	.string "von denen die Legende sagt, sie\l"
	.string "seien hier zu finden?$"

Route120_Text_1BF5D6:: @ 81BF5D6
	.string "Was für ein erbärmlicher Rückschritt...$"

Route120_Text_1BF5F4:: @ 81BF5F4
	.string "Dieser gigantische Felsen... Ich würde\n"
	.string "zu gerne glauben, er enthielte antike\l"
	.string "Schätze. Aber ich sehe keinen Eingang.$"

Route120_Text_1BF65B:: @ 81BF65B
	.string "Warum ich diesen Schirm trage?\p"
	.string "Das verrate ich dir, wenn du mich\n"
	.string "besiegen kannst.$"

Route120_Text_1BF6A4:: @ 81BF6A4
	.string "Ein Schirm kann nicht vor den Attacken\n"
	.string "der POKéMON schützen...$"

Route120_Text_1BF6D0:: @ 81BF6D0
	.string "Ich glaube nicht, dass starkes Sonnen-\n"
	.string "licht gut für meine POKéMON ist.\l"
	.string "Daher schütze ich sie mit meinem Schirm.$"

Route120_Text_1BF728:: @ 81BF728
	.string "Mein Schirm, mein POKéMON und ich...\p"
	.string "Würde eines dieser Elemente fehlen,\n"
	.string "wäre dieses Bild der Schönheit ruiniert.$"

Route120_Text_1BF78C:: @ 81BF78C
	.string "Du hast das Bild der Schönheit ruiniert!$"

Route120_Text_1BF7B2:: @ 81BF7B2
	.string "Mein Schirm würde dir überhaupt nicht\n"
	.string "stehen.\p"
	.string "Er wäre dir sogar hinderlich.$"

Route120_Text_1BF80B:: @ 81BF80B
	.string "Ich werde die Techniken der POKéMON\n"
	.string "übernehmen und neue Ninja-Techniken\l"
	.string "daraus entwickeln.$"

Route120_Text_1BF852:: @ 81BF852
	.string "Die Entwicklung neuer Ninja-Techniken\n"
	.string "bleibt ein Traum...$"

Route120_Text_1BF891:: @ 81BF891
	.string "Vielleicht sollte ich unter einem Ninja-\n"
	.string "Meister lernen...$"

Route120_Text_1BF8C5:: @ 81BF8C5
	.string "Wir Ninja verbergen uns unter unseren\n"
	.string "Tarnmänteln. Ich wette, du wusstest\l"
	.string "nicht, wo ich versteckt war!$"

Route120_Text_1BF920:: @ 81BF920
	.string "Ich habe verloren! Ich wünschte, mein\n"
	.string "Tarnmantel würde meine Schande tarnen.$"

Route120_Text_1BF946:: @ 81BF946
	.string "Unsere Tarnmäntel sind alle handge-\n"
	.string "arbeitet.$"

Route121_Text_1BF96E:: @ 81BF96E
	.string "Möchtest du mit meinem wunderhübschen\n"
	.string "POKéMON spielen?$"

Route121_Text_1BF9A1:: @ 81BF9A1
	.string "So habe ich das aber nicht gemeint!$"

Route121_Text_1BF9BA:: @ 81BF9BA
	.string "Ich gehe zu einem WETTBEWERB in\n"
	.string "SEEGRASULB CITY.\p"
	.string "Mein POKéMON sollte kein Problem haben,\n"
	.string "in der MASTER-KLASSE zu glänzen.$"

Route121_Text_1BFA1B:: @ 81BFA1B
	.string "Mit meinem POKéMON habe ich alle vier\n"
	.string "Ecken der Welt bereist.\p"
	.string "Man könnte sagen, dass ich viel\n"
	.string "Vertrauen in mein Können habe.$"

Route121_Text_1BFA8C:: @ 81BFA8C
	.string "Ah, gut gespielt.$"

Route121_Text_1BFA9D:: @ 81BFA9D
	.string "Ich möchte noch einmal die Welt mit\n"
	.string "meinem POKéMON umrunden.$"

Route121_Text_1BFADA:: @ 81BFADA
	.string "Mit meinem POKéMON habe ich erneut die\n"
	.string "vier Ecken der Welt bereist.\p"
	.string "Ich habe noch größeres Vertrauen in\n"
	.string "meine Fähigkeiten.$"

Route121_Text_1BFB4B:: @ 81BFB4B
	.string "Ah, gut gespielt.$"

Route121_Text_1BFB5C:: @ 81BFB5C
	.string "Deine POKéMON und du...\p"
	.string "Eure Fähigkeiten werden auch in\n"
	.string "Übersee als außerordentlich angesehen.$"

Route121_Text_1BFBB4:: @ 81BFBB4
	.string "Auf der Welt gibt es Dinge, die jenseits\n"
	.string "deines Verständnisses liegen...$"

Route121_Text_1BFBEE:: @ 81BFBEE
	.string "Ich habe verloren...$"

Route121_Text_1BFBFD:: @ 81BFBFD
	.string "PYROBERG...\n"
	.string "Dort ist eine geheimnisvolle Kraft am\l"
	.string "Werk...$"

Route121_Text_1BFC36:: @ 81BFC36
	.string "EVA: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_1BFC7A:: @ 81BFC7A
	.string "EVA: Ich habe vor den Augen meiner\n"
	.string "Juniorpartnerin versagt...$"

Route121_Text_1BFCB3:: @ 81BFCB3
	.string "EVA: Wenn sich jemand auf mich\n"
	.string "verlässt, versuche ich ihm gegenüber\l"
	.string "immer cool aufzutreten...$"

Route121_Text_1BFD08:: @ 81BFD08
	.string "EVA: Wenn du nur ein POKéMON hast,\n"
	.string "können wir nicht mit dir kämpfen.\p"
	.string "Das wäre äußerst unfair.$"

Route121_Text_1BFD60:: @ 81BFD60
	.string "UTE: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_1BFDA3:: @ 81BFDA3
	.string "UTE: Bitte vergib mir, EVA!$"

Route121_Text_1BFDC1:: @ 81BFDC1
	.string "UTE: Ehehehe, ich muss wohl noch etwas\n"
	.string "mit meiner Seniorpartnerin trainieren.$"

Route121_Text_1BFE0D:: @ 81BFE0D
	.string "UTE: Du brauchst mindestens zwei\n"
	.string "POKéMON, um gegen uns zu kämpfen.$"

Route121_Text_1BFE51:: @ 81BFE51
	.string "Stopp! Schau dir meine wunderbaren\n"
	.string "POKéMON gut an!$"

Route121_Text_1BFE80:: @ 81BFE80
	.string "Oh, wie konntest du nur! Nimm die\n"
	.string "Sache doch nicht gleich so ernst!$"

Route121_Text_1BFEAE:: @ 81BFEAE
	.string "Vielleicht werde ich in die SAFARI-ZONE\n"
	.string "gehen und mehr POKéMON fangen!$"

Route121_Text_1BFEDE:: @ 81BFEDE
	.string "Meine wertvollen POKéMON sind ge-\n"
	.string "wachsen! Schau mal!$"

Route121_Text_1BFF0A:: @ 81BFF0A
	.string "Oh, du hast es wieder getan!\n"
	.string "Du nimmst es wirklich zu ernst!$"

Route121_Text_1BFF3A:: @ 81BFF3A
	.string "Ich werde wohl wieder in die SAFARI-\n"
	.string "ZONE gehen und POKéMON fangen.$"

Route123_Text_1BFF6A:: @ 81BFF6A
	.string "Möchtest du wissen, wie stark du bist?\n"
	.string "Ich werde dich testen!$"

Route123_Text_1BFFA2:: @ 81BFFA2
	.string "Du hast glänzend abgeschnitten!$"

Route123_Text_1BFFC1:: @ 81BFFC1
	.string "Um gegen mich bestehen zu können...\n"
	.string "Deine Stärke ist einfach unglaublich!$"

Route123_Text_1BFFF0:: @ 81BFFF0
	.string "Du hast da aber eine große Sammlung an\n"
	.string "ORDEN der verschiedenen ARENEN!\p"
	.string "Zeig mir, dass du diese ORDEN auch\n"
	.string "zu Recht trägst!$"

Route123_Text_1C0057:: @ 81C0057
	.string "Oh, du bist ihrer würdig, wirklich!$"

Route123_Text_1C0075:: @ 81C0075
	.string "Du wurdest deinen ORDEN in diesem\n"
	.string "Kampf mehr als gerecht.$"

Route123_Text_1C009E:: @ 81C009E
	.string "Man sagt, dass gute Zeiten auch mit\n"
	.string "guten Aromen erfüllt sind.$"

Route123_Text_1C00D4:: @ 81C00D4
	.string "Oh... Ich rieche den bitteren Geruch\n"
	.string "der Niederlage...$"

Route123_Text_1C0100:: @ 81C0100
	.string "Der Garten des BEERENMEISTERS ist\n"
	.string "erfüllt mit den erhebendsten Aromen.$"

Route123_Text_1C013F:: @ 81C013F
	.string "Ein Psycho zu sein ist eine Frage des\n"
	.string "Willens.\p"
	.string "Mein Wille will gegen niemanden verlieren.\n"
	.string "Das macht mich stark.$"

Route123_Text_1C01A3:: @ 81C01A3
	.string "Mir ist schlecht...$"

Route123_Text_1C01B1:: @ 81C01B1
	.string "Es ist alles eine Frage des Willens. Ich\n"
	.string "dachte, ich würde gegen dich gewinnen.$"

Route123_Text_1C01F9:: @ 81C01F9
	.string "Ich habe mich selbst davon überzeugt,\n"
	.string "dass ich einfach nicht verlieren werde.$"

Route123_Text_1C0240:: @ 81C0240
	.string "So überzeugend war das gar nicht...$"

Route123_Text_1C024E:: @ 81C024E
	.string "Ich sollte am PYROBERG trainieren...\n"
	.string "So werde ich dich nie schlagen...$"

Route123_Text_1C028C:: @ 81C028C
	.string "Sei nicht zu erfreut, wenn deine\n"
	.string "POKéMON Psychokräfte entwickeln.\p"
	.string "Du musst diese Kräfte modellieren,\n"
	.string "um sie sinnvoll einsetzen zu können.$"

Route123_Text_1C0303:: @ 81C0303
	.string "Erstaunlich!$"

Route123_Text_1C030F:: @ 81C030F
	.string "Wir alle besitzen Psychokräfte. Wir\n"
	.string "haben nur vergessen, sie zu nutzen.$"

Route123_Text_1C0351:: @ 81C0351
	.string "Hast du die Psychokräfte in dir\n"
	.string "erweckt?$"

Route123_Text_1C0380:: @ 81C0380
	.string "Erstaunlich!$"

Route123_Text_1C038C:: @ 81C038C
	.string "Dein Einfluss auf deine POKéMON...\n"
	.string "Auch das sind Psychokräfte.$"

Route123_Text_1C03CB:: @ 81C03CB
	.string "LEA: Hallo, TRAINER. Ich hoffe, deine\n"
	.string "POKéMON fangen nicht an zu weinen,\l"
	.string "wenn sie verlieren.$"

Route123_Text_1C040E:: @ 81C040E
	.string "LEA: Oh oh, wir haben verloren.$"

Route123_Text_1C0423:: @ 81C0423
	.string "LEA: TRAINER, deine POKéMON sind stark,\n"
	.string "weil ihr eine starke Freundschaft teilt.$"

Route123_Text_1C0462:: @ 81C0462
	.string "LEA: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_1C049C:: @ 81C049C
	.string "GRIT: Okay!\n"
	.string "Wir schlagen die POKéMON des TRAINERS.$"

Route123_Text_1C04CD:: @ 81C04CD
	.string "GRIT: Oh oh. Wir haben verloren...$"

Route123_Text_1C04E3:: @ 81C04E3
	.string "GRIT: Wieso bist du so stark?\n"
	.string "Wir haben bisher noch nie verloren!$"

Route123_Text_1C0519:: @ 81C0519
	.string "GRIT: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_1C0554:: @ 81C0554
	.string "PYROBERG...\n"
	.string "Wo die Geister der POKéMON ruhen...\l"
	.string "Ruhen deine POKéMON auch?$"

Route123_Text_1C059F:: @ 81C059F
	.string "Überschäumend mit Leben...$"

Route123_Text_1C05BC:: @ 81C05BC
	.string "PYROBERG...\n"
	.string "Wo die Geister der POKéMON ruhen...\p"
	.string "Dort muss es eine Kraft geben, die die\n"
	.string "Geister beruhigt...$"

Route124_Text_1C0624:: @ 81C0624
	.string "Hey, hast du etwa auf dem Meer die\n"
	.string "Orientierung verloren?\p"
	.string "Wenn du meine POKéMON besiegst, zeige\n"
	.string "ich dir den richtigen Weg.$"

Route124_Text_1C0675:: @ 81C0675
	.string "Ich habe die Orientierung verloren...$"

Route124_Text_1C0693:: @ 81C0693
	.string "Viele Menschen verlieren auf dem Meer\n"
	.string "die Orientierung.\p"
	.string "Wenn du zu denen gehörst, solltest du\n"
	.string "die KARTE des POKéNAV zu Hilfe nehmen.$"

Route124_Text_1C06F7:: @ 81C06F7
	.string "Hm! Du sitzt auf einem POKéMON anstatt\n"
	.string "selbst zu schwimmen...\p"
	.string "Ich bin richtig neidisch!$"

Route124_Text_1C0741:: @ 81C0741
	.string "Oh!\n"
	.string "Ich kann doch nicht...$"

Route124_Text_1C0750:: @ 81C0750
	.string "Langsam bekomme ich eine Gänsehaut.\n"
	.string "Ich bin schon zu lange im Wasser.\p"
	.string "Ich wollte, ich könnte auf einem\n"
	.string "POKéMON reiten. So wie du!$"

Route124_Text_1C07B4:: @ 81C07B4
	.string "Wenn du dich einfach nur im Meer treiben\n"
	.string "lässt, kommen POKéMON, um zu spielen.$"

Route124_Text_1C07F9:: @ 81C07F9
	.string "Oh.\n"
	.string "Verschollen auf hoher See...$"

Route124_Text_1C080E:: @ 81C080E
	.string "Ich habe beim Schwimmen festgestellt,\n"
	.string "dass einige POKéMON angreifen und\l"
	.string "manche einen nur beobachten.\p"
	.string "Ich glaube, POKéMON haben unter-\n"
	.string "schiedliche Persönlichkeiten.$"

Route124_Text_1C0888:: @ 81C0888
	.string "Wenn du dich hier treiben lässt, triffst\n"
	.string "du auf TRAINER, die kämpfen wollen.$"

Route124_Text_1C08C8:: @ 81C08C8
	.string "Das ist sehr merkwürdig...\n"
	.string "Ich habe schon wieder verloren...$"

Route124_Text_1C08EA:: @ 81C08EA
	.string "Das hat zwar nichts damit zu tun, aber\n"
	.string "ich glaube, ich besuche das RÄTSELHAUS.$"

Route124_Text_1C0936:: @ 81C0936
	.string "Ich fange an, mich beim Schwimmen zu\n"
	.string "langweilen. Wie wär’s mit einem Kampf?$"

Route124_Text_1C096B:: @ 81C096B
	.string "Ich hatte ja keine Ahnung, dass du so\n"
	.string "stark bist!$"

Route124_Text_1C0994:: @ 81C0994
	.string "Alles was du bisher erreicht hast, hat\n"
	.string "dich so stark werden lassen.$"

Route124_Text_1C09CE:: @ 81C09CE
	.string "Hähähä... Ich tauche tief hinab, um mich\n"
	.string "tief und sicher zu verstecken.\l"
	.string "Die Tiefen auszuloten ist meine Mission.$"

Route124_Text_1C0A2F:: @ 81C0A2F
	.string "Blubb, blubb, blubb...\n"
	.string "So saufe ich ab...$"

Route124_Text_1C0A52:: @ 81C0A52
	.string "Aus zuverlässiger Quelle weiß ich, dass\n"
	.string "es hier in der Nähe einen Platz zum\l"
	.string "TAUCHEN gibt.\p"
	.string "Das gibt mir das Verlangen, mich tief\n"
	.string "fallen zu lassen...$"

Route124_Text_1C0ABD:: @ 81C0ABD
	.string "UTA: Seufz...\p"
	.string "Ich bin hier im Meer, aber wer ist bei\n"
	.string "mir? Mein kleiner Bruder!\p"
	.string "Lass uns kämpfen, dann brauche ich\n"
	.string "nicht darüber nachzudenken.$"

Route124_Text_1C0B36:: @ 81C0B36
	.string "UTA: TOM! Es ist deine Schuld, dass wir\n"
	.string "verloren haben! Das wirst du mir büßen!$"

Route124_Text_1C0B72:: @ 81C0B72
	.string "UTA: Seufz...\p"
	.string "Wenn anstelle meines kleinen\n"
	.string "Bruders ein hübscher Freund hier wäre...$"

Route124_Text_1C0BC8:: @ 81C0BC8
	.string "UTA: Du willst gegen uns antreten?\n"
	.string "Dann brauchst du aber mehr POKéMON.$"

Route124_Text_1C0C0E:: @ 81C0C0E
	.string "TOM: Meine Schwester ist stark!\p"
	.string "Heul bloß nicht, wenn du verlierst!$"

Route124_Text_1C0C4F:: @ 81C0C4F
	.string "TOM: Oh oh...\n"
	.string "Meine Schwester wird mich fressen...$"

Route124_Text_1C0C7F:: @ 81C0C7F
	.string "TOM: Meine Schwester wird richtig\n"
	.string "unheimlich, wenn sie wütend ist.\p"
	.string "Daher hat sie auch noch keinen Freund.$"

Route124_Text_1C0CE0:: @ 81C0CE0
	.string "TOM: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_1C0D1F:: @ 81C0D1F
	.string "UTA: Megaseufz... Ich bin hier mitten\n"
	.string "im Meer.\p"
	.string "Und mit wem? Meinem kleinen Bruder!\n"
	.string "Oh, dich habe ich lange nicht gesehen.\p"
	.string "Lass uns kämpfen, dann muss ich nicht\n"
	.string "länger über die Situation nachdenken.$"

Route124_Text_1C0DB5:: @ 81C0DB5
	.string "UTA: TOM!!! Du hast schon wieder für\n"
	.string "eine Niederlage gesorgt!\p"
	.string "Ich werde dir gleich eine Lektion\n"
	.string "erteilen!$"

Route124_Text_1C0E06:: @ 81C0E06
	.string "UTA: Seeeuuufz...\p"
	.string "Wenn ich einen netten Freund hätte,\n"
	.string "würden wir alle in Kombination schlagen.$"

Route124_Text_1C0E5C:: @ 81C0E5C
	.string "UTA: Du willst gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_1C0EA2:: @ 81C0EA2
	.string "TOM: Wenn wir verlieren, stecke ich tief\n"
	.string "in der Klemme. Dann flippe ich aus!$"

Route124_Text_1C0EE5:: @ 81C0EE5
	.string "TOM: Oh oh...\n"
	.string "Meine Schwester wird mich umbringen...$"

Route124_Text_1C0F19:: @ 81C0F19
	.string "TOM: Meine Schwester ist bizarr und\n"
	.string "Furcht erregend, wenn sie wütend ist.\p"
	.string "Sie wird mich später hart mit den\n"
	.string "POKéMON trainieren lassen...$"

Route124_Text_1C0F90:: @ 81C0F90
	.string "TOM: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route125_Text_1C0FCF:: @ 81C0FCF
	.string "Ich habe dich kommen hören und\n"
	.string "hier auf dich gewartet.$"

Route125_Text_1C1002:: @ 81C1002
	.string "Ich bitte um Frieden!$"

Route125_Text_1C1013:: @ 81C1013
	.string "Der Schall bewegt sich im Wasser\n"
	.string "schneller als in der Luft.$"

Route125_Text_1C104B:: @ 81C104B
	.string "Hey, du!\n"
	.string "Schau dir mein süßes POKéMON an!$"

Route125_Text_1C1073:: @ 81C1073
	.string "Da habe ich aber rumgewurstelt...$"

Route125_Text_1C1083:: @ 81C1083
	.string "SEEPERS Charme hat mich gefangen, so\n"
	.string "habe ich angefangen zu schwimmen.$"

Route125_Text_1C10C3:: @ 81C10C3
	.string "Das Schwimmen hat mich ermüdet.\n"
	.string "Willst du mit mir kämpfen?$"

Route125_Text_1C10FB:: @ 81C10FB
	.string "Du bist mir eine Nummer zu groß.$"

Route125_Text_1C110C:: @ 81C110C
	.string "Huuh... Wo geht es denn hier\n"
	.string "nach MOOSBACH CITY?$"

Route125_Text_1C1136:: @ 81C1136
	.string "Wie willst du gegen meine WASSER-\n"
	.string "POKéMON ankommen?$"

Route125_Text_1C1175:: @ 81C1175
	.string "Ich habe verloren...$"

Route125_Text_1C117F:: @ 81C117F
	.string "Deine Kraft... Absolut unglaublich.\n"
	.string "Ich bin begeistert!$"

Route125_Text_1C11AF:: @ 81C11AF
	.string "Ahoi! Ich bin ein raubeiniger MATROSE!\n"
	.string "Ich habe die Weltmeere umsegelt.$"

Route125_Text_1C11ED:: @ 81C11ED
	.string "Grrrrooooaaar!\n"
	.string "Ich konnte unmöglich gewinnen!$"

Route125_Text_1C1208:: @ 81C1208
	.string "Die Flut kommt und geht in der\n"
	.string "KÜSTENHÖHLE.\p"
	.string "Wusstest du eigentlich, dass zwischen\n"
	.string "Flut und Ebbe immer 6 Stunden liegen?$"

Route125_Text_1C1282:: @ 81C1282
	.string "Jetzt läuft die Flut ein und für dich ist\n"
	.string "Zahltag! Komm, wir kämpfen.$"

Route125_Text_1C12C5:: @ 81C12C5
	.string "Ich konnte nicht gewinnen!\n"
	.string "Die Flut hat mich davongetragen!$"

Route125_Text_1C12EE:: @ 81C12EE
	.string "Die KÜSTENHÖHLE...\p"
	.string "Es gibt Orte, die sind mal erreichbar und\n"
	.string "mal nicht. Ganz abhängig von Ebbe\l"
	.string "und Flut.\p"
	.string "Übrigens: Vergiss nicht, dass zwischen\n"
	.string "Flut und Ebbe sechs Stunden liegen!$"

Route125_Text_1C13A1:: @ 81C13A1
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "KÜSTENHÖHLE. Das hat mir jemand\l"
	.string "erzählt. Willst du ihn auch besuchen?$"

Route125_Text_1C13FF:: @ 81C13FF
	.string "ZOE: Ich dachte, wir könnten gewinnen.$"

Route125_Text_1C141C:: @ 81C141C
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "KÜSTENHÖHLE, stimmt’s?\p"
	.string "Komm, IRIS, wir besuchen ihn.$"

Route125_Text_1C146E:: @ 81C146E
	.string "ZOE: Nein, nein, nein! Du brauchst zwei\n"
	.string "POKéMON oder es funktioniert nicht!$"

Route125_Text_1C14AB:: @ 81C14AB
	.string "IRIS: ZOE, kannst du mir verraten, was\n"
	.string "wir hier draußen überhaupt wollen?$"

Route125_Text_1C14E7:: @ 81C14E7
	.string "IRIS: Oh, wir waren so nah dran.$"

Route125_Text_1C1508:: @ 81C1508
	.string "IRIS: ZOE, gehen wir wirklich zur\n"
	.string "KÜSTENHÖHLE?\l"
	.string "Dann werden wir ja ganz nass.$"

Route125_Text_1C154F:: @ 81C154F
	.string "IRIS: Oh, wir würden niemals einen\n"
	.string "2-gegen-1-Kampf ausfechten! Niemals!$"

Route126_Text_1C1590:: @ 81C1590
	.string "Schwimmen verlangt vollen Körperein-\n"
	.string "satz. Und so wird man fit!$"

Route126_Text_1C15C3:: @ 81C15C3
	.string "Ich gebe es zu! Du hast gewonnen!$"

Route126_Text_1C15D8:: @ 81C15D8
	.string "Dank meiner täglichen Schwimmrunden...\n"
	.string "Guck mal! Schau dir diesen Körperbau an!$"

Route126_Text_1C1627:: @ 81C1627
	.string "Dieser hohe weiße Berg dort ist\n"
	.string "XENEROVILLE.$"

Route126_Text_1C1660:: @ 81C1660
	.string "Wie, das war’s schon?$"

Route126_Text_1C166F:: @ 81C166F
	.string "Ich kann den Eingang zu XENEROVILLE\n"
	.string "nicht finden. Wo kann er sein?$"

Route126_Text_1C16AB:: @ 81C16AB
	.string "Hihihihihi!\n"
	.string "Ich bin eine Meerjungfrau!$"

Route126_Text_1C16C5:: @ 81C16C5
	.string "Mein Traum platzt wie Seifenblasen!\n"
	.string "Plopp, plopp, plopp...$"

Route126_Text_1C1702:: @ 81C1702
	.string "Du hast mich geschlagen... Ich möchte im\n"
	.string "Meer der Verzweiflung untergehen...$"

Route126_Text_1C1741:: @ 81C1741
	.string "Hallo, Kindchen!\n"
	.string "Willst du gegen mich antreten?$"

Route126_Text_1C1766:: @ 81C1766
	.string "Oh, neeeiiin!$"

Route126_Text_1C1773:: @ 81C1773
	.string "Ich liebe es, einfach so mit meinen \n"
	.string "POKéMON im Meer abzuhängen!$"

Route127_Text_1C17A8:: @ 81C17A8
	.string "Ich sehe es dir an. Du willst mich\n"
	.string "herausfordern!$"

Route127_Text_1C17DD:: @ 81C17DD
	.string "Auauauauahahaha!$"

Route127_Text_1C17EC:: @ 81C17EC
	.string "Ein gut gespieltes Match lässt immer ein\n"
	.string "frisches und heiteres Gefühl zurück.$"

Route127_Text_1C1828:: @ 81C1828
	.string "Hast du auch einen Rivalen, gegen den\n"
	.string "du es hasst zu verlieren?$"

Route127_Text_1C1860:: @ 81C1860
	.string "Aaargh! Ich hasse es, zu verlieren!$"

Route127_Text_1C1877:: @ 81C1877
	.string "Wenn du einen Rivalen hast, willst du\n"
	.string "dann nicht auch immer besser werden?$"

Route127_Text_1C18CC:: @ 81C18CC
	.string "Durch das Angeln habe ich eine\n"
	.string "gelassene Heiterkeit entwickelt...\l"
	.string "Bitte lass mich sie dir zeigen...$"

Route127_Text_1C1930:: @ 81C1930
	.string "Auch wenn ich verloren habe, so bleibt\n"
	.string "mein Herz doch ruhig...$"

Route127_Text_1C195D:: @ 81C195D
	.string "Es macht nichts, wenn ich nichts fange.\n"
	.string "Die Schnur bleibt im Wasser.$"

Route127_Text_1C19A3:: @ 81C19A3
	.string "Hups! Jetzt sag nicht, dass ich ein\n"
	.string "SURFENDES POKéMON am Haken habe?$"

Route127_Text_1C19D6:: @ 81C19D6
	.string "Ich kann so nicht weitermachen!$"

Route127_Text_1C19E7:: @ 81C19E7
	.string "Deine POKéMON sehen stark aus! Und\n"
	.string "doch wären sie nur ein Häppchen, wenn\l"
	.string "ich sie als Köder am Haken hätte.$"

Route127_Text_1C1A2E:: @ 81C1A2E
	.string "Nun! Das ist ein Kampf zwischen einem\n"
	.string "POKéMON-Fan und einem Angel-Fan.$"

Route127_Text_1C1A73:: @ 81C1A73
	.string "Nein! Meine Schnur hat sich verheddert.\n"
	.string "Die Party ist vorbei!$"

Route127_Text_1C1AA0:: @ 81C1AA0
	.string "Meine Angelschnur tanzt im Wasser!\n"
	.string "Sie tanzt Tango! Hahahah, hiiiks!$"

Route127_Text_1C1AE2:: @ 81C1AE2
	.string "Das, was ich in der ARENA von\n"
	.string "FAUSTAUHAVEN gelernt habe,\l"
	.string "wende ich jetzt an.$"

Route127_Text_1C1B2A:: @ 81C1B2A
	.string "Ich wurde weggeschwemmt.$"

Route127_Text_1C1B39:: @ 81C1B39
	.string "KAMILLO, der ARENALEITER von\n"
	.string "FAUSTAUHAVEN, soll mit einem Typen\l"
	.string "namens BRUNO in KANTO trainiert haben.$"

Route127_Text_1C1B92:: @ 81C1B92
	.string "VOGEL-POKéMON haben exzellente Augen.\n"
	.string "Sie erspähen Beute aus großer Höhe.$"

Route127_Text_1C1BD9:: @ 81C1BD9
	.string "Huuh... Ich gebe auf.$"

Route127_Text_1C1BEC:: @ 81C1BEC
	.string "Hier gibt es viele Plätze, an denen man\n"
	.string "sehr gut tauchen kann.\p"
	.string "Aus der Luft sind sie leicht zu\n"
	.string "erkennen, da sie dunkler sind.$"

Route128_Text_1C1C67:: @ 81C1C67
	.string "PRACHTPOLIS CITY ist weit entfernt...$"

Route128_Text_1C1C95:: @ 81C1C95
	.string "Mein erster Sieg scheint weit entfernt\n"
	.string "zu sein...$"

Route128_Text_1C1CC3:: @ 81C1CC3
	.string "Mein ganzes Leben ist eine einzige\n"
	.string "Niederlage, aber ich gebe nicht auf!$"

Route128_Text_1C1D02:: @ 81C1D02
	.string "Ich fühle mich gut. Ich werde weiter\n"
	.string "Richtung PRACHTPOLIS CITY schwimmen.$"

Route128_Text_1C1D45:: @ 81C1D45
	.string "Ich möchte sehr gerne einmal vom Sieg\n"
	.string "kosten...$"

Route128_Text_1C1D6B:: @ 81C1D6B
	.string "Ich werde PRACHTPOLIS CITY eventuell\n"
	.string "erreichen und dort eventuell gewinnen...$"

Route128_Text_1C1DB0:: @ 81C1DB0
	.string "In einem Triathlon musst du schwimmen,\n"
	.string "Rad fahren und einen Marathon laufen.\p"
	.string "Es ist ein mörderisches Rennen, das aus\n"
	.string "drei Disziplinen besteht.$"

Route128_Text_1C1E25:: @ 81C1E25
	.string "Ein POKéMON-Kampf ist auch mörderisch.$"

Route128_Text_1C1E4A:: @ 81C1E4A
	.string "Ich muss als Nächstes mit dem RAD\n"
	.string "fahren, aber... Ich möchte eigentlich\l"
	.string "das Handtuch werfen.$"

Route128_Text_1C1E90:: @ 81C1E90
	.string "Ein Triathlon ist lang. Aber ich glaube,\n"
	.string "um POKéMON CHAMP zu werden, hat\l"
	.string "man auch einen langen Weg vor sich.$"

Route128_Text_1C1EFA:: @ 81C1EFA
	.string "Ein POKéMON-Kampf ist hart und \n"
	.string "unbarmherzig...$"

Route128_Text_1C1F2E:: @ 81C1F2E
	.string "Du solltest ernsthaft darüber nach-\n"
	.string "denken, die SIEGESSTRASSE zu betreten.$"

Route128_Text_1C1F6D:: @ 81C1F6D
	.string "Wir haben hart dafür gearbeitet, die\n"
	.string "POKéMON LIGA herauszufordern...\p"
	.string "Wir können es uns nicht erlauben,\n"
	.string "jetzt zu verlieren!$"

Route128_Text_1C1FCC:: @ 81C1FCC
	.string "Oh!\n"
	.string "Wie konnte das passieren?$"

Route128_Text_1C1FE8:: @ 81C1FE8
	.string "Ich bin so weit gekommen, ich gebe\n"
	.string "jetzt bestimmt nicht auf.$"

Route128_Text_1C202C:: @ 81C202C
	.string "Es gibt keinen stärkeren TRAINER als\n"
	.string "mich!$"

Route128_Text_1C2051:: @ 81C2051
	.string "Das darf nicht wahr sein!$"

Route128_Text_1C2060:: @ 81C2060
	.string "Es gibt wohl keinen stärkeren TRAINER\n"
	.string "als dich!$"

Route128_Text_1C2090:: @ 81C2090
	.string "Ich will nach PRACHTPOLIS CITY, daher\n"
	.string "habe ich ein POKéMON gefangen, das\p"
	.string "weiß, wie man mit KASKADE den Wasserfall\n"
	.string "erklimmt.$"

Route128_Text_1C20FC:: @ 81C20FC
	.string "Ich bin abgestürzt.$"

Route128_Text_1C210D:: @ 81C210D
	.string "Ooh, jeeeeh!\p"
	.string "Mein POKéMON kennt KASKADE, aber mir\n"
	.string "fehlt der ORDEN der ARENA von\l"
	.string "XENEROVILLE!$"

Route129_Text_1C2161:: @ 81C2161
	.string "Das ist mein erster Triathlon.\n"
	.string "Ich bin schon ganz hibbelig und nervös!$"

Route129_Text_1C2198:: @ 81C2198
	.string "Wooooaaaaaargh! Ich habe es\n"
	.string "nicht geschafft, zu gewinnen.$"

Route129_Text_1C21B4:: @ 81C21B4
	.string "Wenn ich so hibbelig bin, kann ich nicht\n"
	.string "alles geben.$"

Route129_Text_1C21ED:: @ 81C21ED
	.string "Ich bin mitten in einem Triathlon, aber\n"
	.string "warum sollten wir nicht kämpfen?$"

Route129_Text_1C222F:: @ 81C222F
	.string "Ich war sicher, ich würde gewinnen!$"

Route129_Text_1C2243:: @ 81C2243
	.string "Weißt du, was das Beste am Triathlon\n"
	.string "ist?\p"
	.string "Man kommt an seine eigenen Grenzen und\n"
	.string "zeigt seine Ausdauer gegenüber Mutter\l"
	.string "Natur.$"

Route129_Text_1C22C8:: @ 81C22C8
	.string "Sag: Hey, hey!\n"
	.string "Los geht’s!$"

Route129_Text_1C22EC:: @ 81C22EC
	.string "Geschlagen, ich wurde geschlagen.\n"
	.string "Das war’s. Fertig!$"

Route129_Text_1C230F:: @ 81C230F
	.string "Hier gibt es für Verlierer nichts zu tun.\n"
	.string "Zeit für mich, nach Hause zu gehen.$"

Route129_Text_1C2349:: @ 81C2349
	.string "Warum so eilig?\n"
	.string "Immer mit der Ruhe...$"

Route129_Text_1C2378:: @ 81C2378
	.string "Oh, meine Güte. Dabei wollte ich\n"
	.string "nur ein bisschen entspannen.$"

Route129_Text_1C23A3:: @ 81C23A3
	.string "Hasst du es nicht auch, Fehler zu\n"
	.string "machen, nur weil du es eilig hast?\p"
	.string "Daher gehe ich alles langsam an.$"

Route130_Text_1C2401:: @ 81C2401
	.string "Was für eine Überraschung! Ich habe im\n"
	.string "Meer keinen TRAINER erwartet.\p"
	.string "Ich denke, wir sollten kämpfen.$"

Route130_Text_1C245D:: @ 81C245D
	.string "Dieses Kind ist unglaublich stark.$"

Route130_Text_1C2479:: @ 81C2479
	.string "Deine Augen haben den Ausdruck eines\n"
	.string "Menschen, der harte Herausforderungen\l"
	.string "siegreich gemeistert hat. Das steht dir.$"

Route130_Text_1C24DC:: @ 81C24DC
	.string "Im tiefen, blauen Meer fand mein\n"
	.string "schwermütiges Herz Trost in den\l"
	.string "wogenden Wellen.$"

Route130_Text_1C2525:: @ 81C2525
	.string "Wie das weite Meer umspannt auch die \n"
	.string "Welt der POKéMON Weiten jenseits\l"
	.string "unseres Erfahrungshorizontes.$"

Route130_Text_1C256E:: @ 81C256E
	.string "Die Kinder dieser Welt träumen davon,\n"
	.string "eines Tages der POKéMON CHAMP zu\l"
	.string "werden.$"

Route131_Text_1C25B3:: @ 81C25B3
	.string "Das Meer wimmelt von POKéMON.\n"
	.string "Es ist nicht leicht, hier zu schwimmen.$"

Route131_Text_1C25F8:: @ 81C25F8
	.string "POKéMON, die von TRAINERN aufgezogen\n"
	.string "wurden, sind sehr stark...$"

Route131_Text_1C262A:: @ 81C262A
	.string "Keuch... Schnauf... Ich bin K.O.\p"
	.string "Der Hinweg ist leicht. Der Heimweg umso\n"
	.string "härter.\p"
	.string "Ob ich genug Energie für die Heimreise\n"
	.string "habe?$"

Route131_Text_1C26B9:: @ 81C26B9
	.string "Die See... Die See... Die See...\n"
	.string "Die See... So weit ich mit den Augen seh.\l"
	.string "Das Meer macht mich krank und müde.$"

Route131_Text_1C271F:: @ 81C271F
	.string "Bah!$"

Route131_Text_1C2726:: @ 81C2726
	.string "Gelangweilt bin ich von der See, aber\n"
	.string "ich muss schwimmen.\p"
	.string "Ich bin der geborene Schwimmer!\n"
	.string "Das bin ich.$"

Route131_Text_1C2774:: @ 81C2774
	.string "Hey, Engelchen, warte!\n"
	.string "Wir sollten kämpfen, du und ich!$"

Route131_Text_1C27A4:: @ 81C27A4
	.string "Du bist stärker, als du aussiehst.$"

Route131_Text_1C27CF:: @ 81C27CF
	.string "Hast du einen Typen gesehen, der heult,\n"
	.string "weil das Meer ihn langweilt?\p"
	.string "Das ist nur Gerede.\n"
	.string "Er liebt das Meer aus tiefstem Herzen!$"

Route131_Text_1C284A:: @ 81C284A
	.string "Warum lieben Männer Bikinis nur so?\p"
	.string "Sie starren alle meinen Bikini an.$"

Route131_Text_1C2883:: @ 81C2883
	.string "Ich bin erledigt.$"

Route131_Text_1C2898:: @ 81C2898
	.string "Vielleicht bewundern die Männer nicht\n"
	.string "meinen Bikini, sondern mich!$"

Route131_Text_1C28E2:: @ 81C28E2
	.string "UNA: Wir nehmen es als Geschwister mit\n"
	.string "dir auf!$"

Route131_Text_1C2918:: @ 81C2918
	.string "UNA: Wir konnten nicht gewinnen. Trotz\n"
	.string "unserer Zusammenarbeit.$"

Route131_Text_1C2950:: @ 81C2950
	.string "UNA: Die Menschen in FLOSSBRUNN\n"
	.string "leben von Geburt an mit POKéMON\l"
	.string "und dem Meer zusammen.$"

Route131_Text_1C29B2:: @ 81C29B2
	.string "UNA: Du hast keine zwei POKéMON?\n"
	.string "Dann werden wir keinen Spaß haben!$"

Route131_Text_1C29F3:: @ 81C29F3
	.string "TOBI: Ich gebe zusammen mit meiner\n"
	.string "Schwester mein Bestes!$"

Route131_Text_1C2A20:: @ 81C2A20
	.string "TOBI: Meine Schwester und ich gaben\n"
	.string "unser Bestes und haben doch verloren.$"

Route131_Text_1C2A5D:: @ 81C2A5D
	.string "TOBI: Du weißt, dass FLOSSBRUNN\n"
	.string "eine schwimmende Stadt ist?\p"
	.string "Wo immer auch das Meer ist, ist es Teil\n"
	.string "von FLOSSBRUNN!$"

Route131_Text_1C2ACA:: @ 81C2ACA
	.string "TOBI: Wenn du zwei POKéMON mitbringst,\n"
	.string "werden wir es mit dir aufnehmen!$"

Route132_Text_1C2AFB:: @ 81C2AFB
	.string "Als Kind war ich andauernd erkältet,\n"
	.string "aber seit ich mit dem Schwimmen\l"
	.string "angefangen habe, bin ich fit.$"

Route132_Text_1C2B5B:: @ 81C2B5B
	.string "Ich bitte um mehr Kraft...$"

Route132_Text_1C2B71:: @ 81C2B71
	.string "TRAINER reisen über Berg und Tal\n"
	.string "und müssen deshalb auch fit sein.$"

Route132_Text_1C2BB5:: @ 81C2BB5
	.string "Ich versuche, mich von den Strömungen\n"
	.string "fern zu halten.$"

Route132_Text_1C2BEA:: @ 81C2BEA
	.string "Oh, bitte, nein!$"

Route132_Text_1C2BFA:: @ 81C2BFA
	.string "Ich wurde weggespült. Ich habe voll-\n"
	.string "ständig die Orientierung verloren.$"

Route132_Text_1C2C32:: @ 81C2C32
	.string "Sieg oder Niederlage. Das weiß man\n"
	.string "erst, wenn man es ausprobiert hat.$"

Route132_Text_1C2C60:: @ 81C2C60
	.string "Aaah!\n"
	.string "Ich versinke in einer Niederlage.$"

Route132_Text_1C2C78:: @ 81C2C78
	.string "Ich kämpfe nie, wenn ich weiß, dass ich\n"
	.string "gewinne. Ich liebe den Kampf an der\l"
	.string "Grenze zwischen Sieg und Niederlage.$"

Route132_Text_1C2CD9:: @ 81C2CD9
	.string "Ich widme mich 24 Stunden am Tag den\n"
	.string "POKéMON. Ob du mich besiegen kannst?$"

Route132_Text_1C2D1F:: @ 81C2D1F
	.string "Ich habe verloren.\n"
	.string "Ich gestehe die Niederlage ein.$"

Route132_Text_1C2D3E:: @ 81C2D3E
	.string "Aargh...\n"
	.string "Du bist ein POKéMON-Fanatiker, oder?\p"
	.string "Du widmest dich den POKéMON\n"
	.string "24 Stunden am Tag, oder?$"

Route133_Text_1C2DA5:: @ 81C2DA5
	.string "Hat die Strömung dich hergebracht? Das\n"
	.string "nenne ich Schicksal. Lass uns kämpfen!$"

Route133_Text_1C2DF4:: @ 81C2DF4
	.string "Stark!\n"
	.string "Viel zu stark!$"

Route133_Text_1C2E09:: @ 81C2E09
	.string "Soll ich das jetzt Glück nennen, dass ich\n"
	.string "auf einen so starken TRAINER wie dich\l"
	.string "gestoßen bin? Ich bin verflucht...$"

Route133_Text_1C2E61:: @ 81C2E61
	.string "Ich führte ein Leben in Kummer und\n"
	.string "Elend. Es hat mich hierher verschlagen\l"
	.string "und hier bin ich gestrandet...$"

Route133_Text_1C2EBD:: @ 81C2EBD
	.string "Eine weitere Niederlage...$"

Route133_Text_1C2ECD:: @ 81C2ECD
	.string "Treibend auf dem Meer des Lebens...\n"
	.string "Ich habe dazu keine Lust mehr!$"

Route133_Text_1C2EF7:: @ 81C2EF7
	.string "Willkommen!\n"
	.string "Ich habe dich schon erwartet!$"

Route133_Text_1C2F19:: @ 81C2F19
	.string "Nein! Bitte!$"

Route133_Text_1C2F25:: @ 81C2F25
	.string "Ein Kind als starker TRAINER...\n"
	.string "Boh, ist das äääärgerlich!$"

Route133_Text_1C2F53:: @ 81C2F53
	.string "Ich möchte, wie jeder andere auch,\n"
	.string "gewinnen, aber ich ziehe meine POKéMON\l"
	.string "nicht auf wie jeder andere auch...$"

Route133_Text_1C2FA3:: @ 81C2FA3
	.string "Mist!\n"
	.string "Meine Art und Weise reicht nicht aus!$"

Route133_Text_1C2FC7:: @ 81C2FC7
	.string "Es macht mehr Spaß, die Dinge auf meine\n"
	.string "Art zu erledigen, als auf die Art aller\l"
	.string "anderen. Das ist doch klar!$"

Route133_Text_1C302D:: @ 81C302D
	.string "Ich bin mit meinen VOGEL-POKéMON\n"
	.string "hierher gekommen.$"

Route133_Text_1C305F:: @ 81C305F
	.string "Du...\n"
	.string "Du bist total cool!$"

Route133_Text_1C307E:: @ 81C307E
	.string "Ich könnte nach BAUMHAUSEN CITY zu-\n"
	.string "rückkehren, aber ich mag Orte wie diese.$"

Route134_Text_1C30C6:: @ 81C30C6
	.string "Selbst POKéMON, die schwimmen können,\n"
	.string "werden oft von der Strömung erfasst.$"

Route134_Text_1C3110:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_1C311A:: @ 81C311A
	.string "Ich glaube, POKéMON mögen diese\n"
	.string "schnellen Strömungen hier sehr.$"

Route134_Text_1C315E:: @ 81C315E
	.string "Meine LIEBISKUS möchten ihren Spaß\n"
	.string "bei einem Kampf haben. Machst du mit?$"

Route134_Text_1C3198:: @ 81C3198
	.string "Huupsie!$"

Route134_Text_1C31A0:: @ 81C31A0
	.string "Es gibt da einen Sammler, der sich für \n"
	.string "SCHUPPEN von LIEBISKUS interessiert.$"

Route134_Text_1C31D7:: @ 81C31D7
	.string "Okeydokey! Genug gerastet, Jungs!\n"
	.string "Zeit für ein Kämpfchen!$"

Route134_Text_1C3213:: @ 81C3213
	.string "Wir wurden wieder fertig gemacht.$"

Route134_Text_1C3229:: @ 81C3229
	.string "Mein VOGEL-POKéMON wird nach einem\n"
	.string "langen Flug schnell müde...$"

Route134_Text_1C3262:: @ 81C3262
	.string "Du bist ein POKéMON-TRAINER.\n"
	.string "Worte sind da überflüssig. Wir kämpfen.$"

Route134_Text_1C329E:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_1C32D6:: @ 81C32D6
	.string "Ich habe dich herausgefordert und\n"
	.string "doch verloren. Ich bin tief beschämt.$"

Route134_Text_1C3319:: @ 81C3319
	.string "Die wilde Strömung in dieser Region hilft\n"
	.string "uns dabei, stärker denn je zu werden.$"

Route134_Text_1C335C:: @ 81C335C
	.string "Ich gebe meine Niederlage zu.$"

Route134_Text_1C336E:: @ 81C336E
	.string "Wir werden für weiteres Training nach\n"
	.string "METEORFÄLLE zurückkehren.\p"
	.string "Wenn du magst, komm doch auch mit.\n"
	.string "Das wird auch dich stärker machen!$"
