gTrainerClassNames:: @ 81F0208
	.string "{PKMN}-TRAINER$", 13
	.string "{PKMN}-TRAINER$", 13
	.string "AQUA BOSS$", 13
	.string "TEAM AQUA$", 13
	.string "AQUA VORS.$", 13
	.string "AROMALADY$", 13
	.string "RUINENMANIAC$", 13
	.string "INTERVIEWER$", 13
	.string "PLANSCHER$", 13 @ うきわガール (Inner Tube Girl) in Japanese
	.string "PLANSCHER$", 13 @ うきわボーイ (Inner Tube Boy) in Japanese
	.string "ASS-TRAINER$", 13
	.string "HEXE$", 13
	.string "LADY$", 13
	.string "SCHÖNHEIT$", 13
	.string "SCHNÖSEL$", 13
	.string "POKéMANIAC$", 13
	.string "SCHWIMMER$", 13
	.string "SCHWARZGURT$", 13
	.string "GITARRIST$", 13
	.string "HITZKOPF$", 13
	.string "CAMPER$", 13
	.string "KÄFERMANIAC$", 13
	.string "PSYCHO$", 13
	.string "GENTLEMAN$", 13
	.string "TOP VIER$", 13
	.string "LEITER$", 13
	.string "SCHULKIND$", 13
	.string "SEN. & JUN.$", 13
	.string "SIHGERS,$", 13
	.string "POKéFAN$", 13
	.string "EXPERTE$", 13
	.string "TEENAGER$", 13
	.string "CHAMP$", 13
	.string "ANGLER$", 13
	.string "TRIATHLET$", 13
	.string "DRACHENPROFI$", 13
	.string "VOGELFÄNGER$", 13
	.string "NINJAJUNGE$", 13
	.string "KÄMPFERIN$", 13
	.string "SCHIRMDAME$", 13
	.string "SCHWIMMERIN$", 13
	.string "PICKNICKER$", 13
	.string "ZWIL.$", 13
	.string "MATROSE$", 13
	.string "SNOWBOARDER$", 13
	.string "{PKMN}-SAMMLER$", 13
	.string "{PKMN}-TRAINER$", 13
	.string "{PKMN}-ZÜCHTER$", 13
	.string "{PKMN}-RANGER$", 13
	.string "MAGMA BOSS$", 13
	.string "TEAM MAGMA$", 13
	.string "MAGMA VORS.$", 13
	.string "GÖRE$", 13
	.string "KÄFERSAMMLER$", 13
	.string "WANDERER$", 13
	.string "JUNGES GLÜCK$", 13
	.string "ALTES PAAR$", 13
	.string "GESCHWISTER$", 13
