FallarborTown_ContestLobby_Text_1A6F7C:: @ 81A6F7C
	.string "Du hast an einem POKéMON WETTBEWERB\n"
	.string "teilgenommen, stimmt’s?\p"
	.string "Da kannst du mir doch etwas über\n"
	.string "dein POKéMON erzählen.\p"
	.string "Ich bin Reporter. Ich arbeite an einer\n"
	.string "Geschichte über POKéMON WETTBEWERBE.\p"
	.string "Würdest du mir wohl einige Fragen\n"
	.string "beantworten?$"

FallarborTown_ContestLobby_Text_1A704E:: @ 81A704E
	.string "Oh, das machst du?\n"
	.string "Herzlichen Dank.\p"
	.string "Beschreibe mir doch kurz den WETTBE-\n"
	.string "WERB, an dem du gerade teilgenommen\l"
	.string "hast.$"

FallarborTown_ContestLobby_Text_1A70A5:: @ 81A70A5
	.string "Ah, ich verstehe.\n"
	.string "Das ist ein bewegender Kommentar.\p"
	.string "Man bekommt ein gutes Bild davon,\n"
	.string "wie dieser WETTBEWERB war.\p"
	.string "Ich habe eine letzte Frage.\p"
	.string "Wenn du das Wort “{STR_VAR_2}” hörst,\n"
	.string "was für ein Bild hast du dann vor Augen?$"

FallarborTown_ContestLobby_Text_1A7153:: @ 81A7153
	.string "Oh, hm.\p"
	.string "Das stellst du dir also unter dem\n"
	.string "Begriff “{STR_VAR_2}” vor.\p"
	.string "Danke schön!\n"
	.string "Du hast mir einige gute Ideen geliefert.\p"
	.string "Jetzt kann ich eine gute Geschichte\n"
	.string "über die POKéMON-WETTBEWERBE\l"
	.string "schreiben.\p"
	.string "Vielleicht, aber nur vielleicht, findet\n"
	.string "sie auch ihren Weg ins Fernsehen.\l"
	.string "Ich hoffe, du schaltest dann ein!$"

FallarborTown_ContestLobby_Text_1A7256:: @ 81A7256
	.string "Oh, das ist wirklich schade...\p"
	.string "Nun, wenn du eine gute Geschichte auf\n"
	.string "Lager hast, melde dich wieder bei mir.$"

FallarborTown_ContestLobby_Text_1A72A8:: @ 81A72A8
	.string "Ich freue mich schon auf deinen\n"
	.string "nächsten POKéMON-WETTBEWERB.$"

gTVBravoTrainerText1:: @ 81A72DE
	.string "Yeah!\n"
	.string "Es ist BRAVO TRAINER Zeit!\p"
	.string "Heute stellen wir ein POKéMON vor,\n"
	.string "das zu {STR_VAR_1} gehört.\p"
	.string "Dieses POKéMON hat eine {STR_VAR_2}-\n"
	.string "Wertung in der {STR_VAR_3} Klasse bekommen.$"

gTVBravoTrainerText2:: @ 81A736B
	.string "Begrüßt {STR_VAR_2},\n"
	.string "das {STR_VAR_1}!\p"
	.string "Der Kosename {STR_VAR_2}...\p"
	.string "Selbst dieser Kosename strahlt die\n"
	.string "Aura von “{STR_VAR_3}” aus!$"

gTVBravoTrainerText3:: @ 81A73CA
	.string "Als der TRAINER {STR_VAR_1} sein POKéMON\n"
	.string "in einem WETTBEWERB antreten ließ,\l"
	.string "haben wir es geschafft, einige leiden-\l"
	.string "schaftliche Aussagen zu erhalten.$"

gTVBravoTrainerText4:: @ 81A744D
	.string "Als {STR_VAR_1} nach dem WETTBEWERB über\n"
	.string "diesen befragt wurde, bekamen wir ein\l"
	.string "breites Grinsen und folgende Antwort:\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Nun, sicher, das POKéMON von {STR_VAR_1}\n"
	.string "kam auf Platz {STR_VAR_3} im WETTBEWERB.\p"
	.string "Die Aussage passt absolut zu {STR_VAR_1},\n"
	.string "das ist meine Meinung!$"

gTVBravoTrainerText5:: @ 81A7508
	.string "Als {STR_VAR_1} nach dem WETTBEWERB über\n"
	.string "diesen befragt wurde, bekamen wir die\l"
	.string "bittere Antwort: “{STR_VAR_2}!”\p"
	.string "Nun, sicher, das POKéMON von {STR_VAR_1}\n"
	.string "kam auf Platz {STR_VAR_3} im WETTBEWERB.\p"
	.string "Die Enttäuschung von {STR_VAR_1} wird hier\n"
	.string "mehr als deutlich, das ist meine Meinung.$"

gTVBravoTrainerText6:: @ 81A75CE
	.string "Möchtet ihr auch wissen, was {STR_VAR_1}\n"
	.string "sich unter {STR_VAR_2} vorstellt?\p"
	.string "Ihr könnt darauf wetten, dass wir\n"
	.string "danach gefragt haben! Natürlich!\p"
	.string "Die Antwort war klipp und klar:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Das ist es, was {STR_VAR_2} für {STR_VAR_1}\n"
	.string "repräsentiert!$"

gTVBravoTrainerText7:: @ 81A768D
	.string "Die letzte Attacke, {STR_VAR_2}, die\n"
	.string "von {STR_VAR_1} eingesetzt wurde,\l"
	.string "ist ganz klar “{STR_VAR_3}!”$"

gTVBravoTrainerText8:: @ 81A76C5
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Wir hoffen, dass {STR_VAR_1} noch höhere\n"
	.string "Gipfel erklimmen wird!\p"
	.string "Unsere Zeit ist mal wieder abgelaufen!\n"
	.string "Bis zum nächsten Mal! Tschüss!$"

gTVBravoTrainerText9:: @ 81A774F
	.string "Wir stellen vor: TRAINERS {STR_VAR_1}!$"

BattleTower_Lobby_Text_1A776D:: @ 81A776D
	.string "Hallo! Du bist der TRAINER, der gerade\n"
	.string "gekämpft hat, richtig?\p"
	.string "Ich interviewe TRAINER in der ganzen\n"
	.string "Welt.\p"
	.string "Würdest du mir deine Eindrücke über\n"
	.string "das Kämpfen schildern?$"

BattleTower_Lobby_Text_1A7823:: @ 81A7823
	.string "Ja? Wirklich?\n"
	.string "Danke schön!\l"
	.string "Dann, äh...\p"
	.string "Wie war es heute im DUELLTURM?\p"
	.string "Warst du mit dem Kampf zufrieden?\n"
	.string "Oder bist du unzufrieden?$"

BattleTower_Lobby_Text_1A78B7:: @ 81A78B7
	.string "Oh...\n"
	.string "Tut mir Leid, dich zu stören.\p"
	.string "Bitte gib uns ein Interview, wenn du\n"
	.string "wieder im DUELLTURM kämpfst.$"

BattleTower_Lobby_Text_1A791B:: @ 81A791B
	.string "Ja, natürlich!\p"
	.string "Da ist dieser untrügliche Ausdruck der\n"
	.string "Zufriedenheit auf deinem Gesicht...\p"
	.string "Ganz offensichtlich hattest du einen\n"
	.string "großartigen Kampf!$"

BattleTower_Lobby_Text_1A7990:: @ 81A7990
	.string "Oh, ich verstehe...\p"
	.string "Nun, es ist immer schwer, den Kampf so\n"
	.string "zu beeinflussen, wie man es möchte.$"

BattleTower_Lobby_Text_1A79EB:: @ 81A79EB
	.string "Darf ich dir noch eine Frage stellen?\p"
	.string "Wenn du deine Eindrücke über diesen\n"
	.string "Kampf beschreiben müsstest, was\l"
	.string "würdest du dann sagen?$"

BattleTower_Lobby_Text_1A7A6E:: @ 81A7A6E
	.string "Das ist erstaunlich cool!\p"
	.string "Eine großartige Sache! Ich wünsche dir\n"
	.string "im nächsten Kampf genauso viel Glück!\p"
	.string "Ich hoffe, wir treffen uns bald wieder!$"

BattleTower_Lobby_Text_1A7AE0:: @ 81A7AE0
	.string "Oh, ich verstehe...\p"
	.string "Nun, auch die ruhigen Typen sind cool,\n"
	.string "nicht wahr?\p"
	.string "Ich hoffe, du gibst mir bald wieder die\n"
	.string "Möglichkeit, deine Eindrücke\l"
	.string "festzuhalten!$"

BattleTower_Lobby_Text_1A7B66:: @ 81A7B66
	.string "Ich freue mich schon auf deinen\n"
	.string "nächsten Kampf!$"

gTVBravoTrainerBattleTowerText1:: @ 81A7B93
	.string "Yeah!\n"
	.string "Es ist BRAVO TRAINER Zeit!\p"
	.string "Heute stellen wir {STR_VAR_1} vor. {STR_VAR_1}\n"
	.string "hat sich der Herausforderung im\l"
	.string "DUELLTURM gestellt!\p"
	.string "Bei dieser Begegnung hat {STR_VAR_1}\n"
	.string "das listige {STR_VAR_2} mitgebracht.$"

gTVBravoTrainerBattleTowerText2:: @ 81A7C26
	.string "Das Paar stellte einen neuen Rekord von\n"
	.string "{STR_VAR_2} Siegen in Folge in einer Level {STR_VAR_1}-\l"
	.string "Konkurrenz auf! Bravo, TRAINER!$"

gTVBravoTrainerBattleTowerText3:: @ 81A7C7D
	.string "Die beiden scheiterten schließlich an\n"
	.string "{STR_VAR_1} im Kampf Nummer {STR_VAR_2}.\l"
	.string "Netter Versuch, TRAINER!\p"
	.string "Es war einfach nur großes Pech, so\n"
	.string "früh während dieser Herausforderung\l"
	.string "auf {STR_VAR_1} zu treffen.\p"
	.string "Wir fragten den TRAINER nach den\n"
	.string "Eindrücken, die der Kampf gegen\l"
	.string "{STR_VAR_1} hinterlassen hat.$"

gTVBravoTrainerBattleTowerText4:: @ 81A7D4A
	.string "Die beiden haben gewonnen, indem sie\n"
	.string "{STR_VAR_2} von {STR_VAR_1} klar\l"
	.string "besiegt haben. Bravo, TRAINER!\p"
	.string "Sogar {STR_VAR_1} wurde besiegt...\n"
	.string "Das ist unglaublich! Einfach unglaublich!\p"
	.string "Wir haben den TRAINER nach den\n"
	.string "Eindrücken im Moment des Sieges\l"
	.string "gefragt.$"

gTVBravoTrainerBattleTowerText5:: @ 81A7E0C
	.string "Nach einer Reihe von Siegen musste sich\n"
	.string "das Paar schließlich doch {STR_VAR_2}\l"
	.string "von {STR_VAR_1} geschlagen geben.\p"
	.string "Netter Versuch, TRAINER!\p"
	.string "Man sieht nicht oft so ein wunderbares\n"
	.string "Team wie {STR_VAR_1} und\l"
	.string "{STR_VAR_2}. Das könnt ihr glauben!\p"
	.string "Wir haben den TRAINER gefragt, wie es\n"
	.string "war, gegen dieses Super-Paar zu\l"
	.string "kämpfen.$"

gTVBravoTrainerBattleTowerText6:: @ 81A7F0E
	.string "Und das hat uns der TRAINER gesagt:\n"
	.string "“Ich bin zufrieden!”\p"
	.string "Ist das nicht eine erfrischend offene\n"
	.string "Antwort? Bravo, TRAINER!\p"
	.string "Aber ist ein so eingefleischter TRAINER\n"
	.string "überhaupt in der Lage, mit einem Kampf\l"
	.string "zufrieden zu sein?\p"
	.string "Ich habe herausgefunden, wie zufrieden\n"
	.string "der TRAINER war, als ich diese Worte\l"
	.string "hörte:$"

gTVBravoTrainerBattleTowerText7:: @ 81A8004
	.string "Und das hat uns der TRAINER verraten:\n"
	.string "“Ich bin nicht zufrieden...”\p"
	.string "Unser TRAINER war wohl gerade etwas\n"
	.string "niedergeschlagen, als er das sagte.\p"
	.string "Und es ist nicht immer leicht, nach einem\n"
	.string "Kampf voll zufrieden zu sein, richtig?\p"
	.string "Nun, wir haben nachgehakt und heraus-\n"
	.string "gefunden, wie unzufrieden der TRAINER\l"
	.string "tatsächlich war:$"

gTVBravoTrainerBattleTowerText8:: @ 81A8119
	.string "Nichts$"

gTVBravoTrainerBattleTowerText9:: @ 81A811E
	.string "Nichts$"

gTVBravoTrainerBattleTowerText10:: @ 81A8123
	.string "Nichts$"

gTVBravoTrainerBattleTowerText11:: @ 81A8128
	.string "Nichts$"

gTVBravoTrainerBattleTowerText12:: @ 81A812D
	.string "“{STR_VAR_1}”.$"

gTVBravoTrainerBattleTowerText13:: @ 81A8133
	.string "“{STR_VAR_1}”.\n"
	.string "Ist das nicht großartig?\p"
	.string "Das drückt wahrhaftig {STR_VAR_2}s Freude\n"
	.string "aus. Das würde ich doch sagen!\p"
	.string "Am Ende noch der Kampf gegen\n"
	.string "{STR_VAR_3}... Das war wirklich das, was\l"
	.string "man “{STR_VAR_1}” nennt!$"

gTVBravoTrainerBattleTowerText14:: @ 81A81BC
	.string "“{STR_VAR_1}”.\n"
	.string "Eine treffende Aussage!\p"
	.string "Das Ende des Kampfes gegen\n"
	.string "{STR_VAR_3}... Man kann es nur\l"
	.string "“{STR_VAR_1}” nennen!\p"
	.string "Ich finde, die Enttäuschung von\n"
	.string "{STR_VAR_2} wird mehr als deutlich.$"

gTVBravoTrainerBattleTowerText15:: @ 81A8267
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Ich hoffe, wir sehen {STR_VAR_1} noch\n"
	.string "höhere Gipfel erklimmen!\p"
	.string "Das war’s für den Moment!\n"
	.string "Bis zur nächsten Sendung!$"

SlateportCity_PokemonFanClub_Text_1A82F1:: @ 81A82F1
	.string "Wow!\p"
	.string "Es ist ganz offensichtlich, dass du\n"
	.string "deine Liebe {STR_VAR_1} schenkst.\p"
	.string "Okay, es heißt {STR_VAR_2}.\p"
	.string "Darf ich dich um einen Gefallen bitten?\p"
	.string "Ich bin TV-Reporter und mache eine\n"
	.string "Umfrage zum Thema POKéMON.\p"
	.string "Würdest du mir bitte ein paar einfache\n"
	.string "Fragen beantworten?$"

SlateportCity_PokemonFanClub_Text_1A83D0:: @ 81A83D0
	.string "Großartig! Danke schön!\p"
	.string "Okay, los geht’s. Ich brauche\n"
	.string "kurze, knappe Antworten, okay?$"

SlateportCity_PokemonFanClub_Text_1A8414:: @ 81A8414
	.string "Als du {STR_VAR_1} zum ersten Mal ge-\n"
	.string "sehen hast, was war das für\l"
	.string "ein Gefühl?\p"
	.string "Wie würdest du die Gefühle zu dem\n"
	.string "Zeitpunkt beschreiben?$"

SlateportCity_PokemonFanClub_Text_1A8470:: @ 81A8470
	.string "Du kümmerst dich liebevoll um\n"
	.string "{STR_VAR_1}.\p"
	.string "Wenn du es mit etwas vergleichen\n"
	.string "würdest, das du magst, was wäre das?$"

SlateportCity_PokemonFanClub_Text_1A84D5:: @ 81A84D5
	.string "Diese Frage bezieht sich auch auf dein\n"
	.string "geliebtes {STR_VAR_1}.\p"
	.string "Was hat dich an {STR_VAR_1} angezogen?$"

SlateportCity_PokemonFanClub_Text_1A852D:: @ 81A852D
	.string "Okay, das ergibt einen Sinn.\p"
	.string "Diese Frage mag vielleicht etwas schwer\n"
	.string "sein, um sie kurz zu beantworten.\p"
	.string "Also...\p"
	.string "Was bedeuten POKéMON für dich?$"

SlateportCity_PokemonFanClub_Text_1A85A6:: @ 81A85A6
	.string "Ich verstehe!\p"
	.string "Hmhm...\p"
	.string "Das war’s! Danke, dass du mir deine\n"
	.string "Zeit zur Verfügung gestellt hast!\p"
	.string "Es hat mir viel Spaß gemacht, mich mit\n"
	.string "dir zu unterhalten.\p"
	.string "Vielleicht kannst du dieses Interview\n"
	.string "bald im Fernsehen sehen. Achte darauf!\p"
	.string "Okay, das ist alles.\n"
	.string "Vielen Dank und leb wohl.$"

SlateportCity_PokemonFanClub_Text_1A8667:: @ 81A8667
	.string "Oh, okay...\p"
	.string "Nun, wenn du mir doch etwas über\n"
	.string "POKéMON erzählen willst, ich bin hier.$"

SlateportCity_PokemonFanClub_Text_1A86B5:: @ 81A86B5
	.string "Ich liebe meinen Job - ich lerne so viel\n"
	.string "über POKéMON während der Interviews.$"

SlateportCity_PokemonFanClub_Text_1A8704:: @ 81A8704
	.string "Hallo, du scheinst deinem {STR_VAR_1}\n"
	.string "sehr nahe zu stehen.\p"
	.string "Weißt du was?\n"
	.string "Ich bin ein TV-Reporter.\p"
	.string "Ich reise herum und interviewe Leute,\n"
	.string "befrage sie zu POKéMON.\p"
	.string "Darf ich dich auch etwas über dein\n"
	.string "{STR_VAR_1} fragen?$"

SlateportCity_PokemonFanClub_Text_1A87CA:: @ 81A87CA
	.string "Wow, danke schön!\p"
	.string "Dann erzähl mir doch einfach alles, was\n"
	.string "dir an {STR_VAR_1} gefällt.$"

SlateportCity_PokemonFanClub_Text_1A8818:: @ 81A8818
	.string "Wow...\n"
	.string "Das ist ja ein interessanter Bericht.\p"
	.string "Du stehst deinem {STR_VAR_1} sehr nahe,\n"
	.string "nicht wahr?\p"
	.string "Ich denke, dein Bericht wird sich\n"
	.string "großartig im Fernsehen machen.\p"
	.string "Ich verspreche, ich mache daraus eine\n"
	.string "unterhaltsame Sendung. Die darfst\l"
	.string "du nicht verpassen!\p"
	.string "Okay, das war’s.\n"
	.string "Danke und leb wohl.$"

gTVFanClubOpinionsText1:: @ 81A8917
	.string "WIR SIND DER POKéMON-FANCLUB.\p"
	.string "Wir sind live auf Sendung!\p"
	.string "Hier ist eure Meinung gefragt und ich\n"
	.string "spreche sie öffentlich laut für euch\l"
	.string "aus. Ist das nicht fantastisch?\p"
	.string "Heute bringen wir euch eine Reportage\n"
	.string "unseres Reporters ins Haus, der im Auf-\l"
	.string "trag des POKéMON-FANCLUBS unter-\l"
	.string "wegs war.\p"
	.string "Wer ist heute der glückliche\n"
	.string "POKéMON-Fan, den wir hier vorstellen?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "{STR_VAR_1}!\p"
	.string "So, was hat uns {STR_VAR_1} wohl über\n"
	.string "{STR_VAR_3}, dem {STR_VAR_2},\l"
	.string "zu sagen?\p"
	.string "Und ich... Ich werde die Worte der Zu-\n"
	.string "neigung laut im Fernsehen herausrufen!\p"
	.string "Huuh-haa!\p"
	.string "Lasst uns alle laut rufen!$"

gTVFanClubOpinionsText2:: @ 81A8AE5
	.string "Wir haben {STR_VAR_1} gefragt: “Als du\n"
	.string "{STR_VAR_2} das erste Mal gesehen hast,\l"
	.string "was war das für ein Gefühl?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Juhuhuu! Das ist eine super Aussage!\p"
	.string "Bringt sie euch nicht auch Erinnerungen\n"
	.string "an längst vergangene Zeiten wieder?$"

gTVFanClubOpinionsText3:: @ 81A8B9D
	.string "Wir haben {STR_VAR_1} gefragt: “Wenn du\n"
	.string "{STR_VAR_2} mit etwas vergleichen\l"
	.string "würdest, das du magst, was wäre das?”\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Huhuhuuu! Was für ein origineller\n"
	.string "Vergleich!\p"
	.string "Man spürt gleich das intensive Gefühl,\n"
	.string "das der TRAINER für {STR_VAR_2}\l"
	.string "empfindet!$"

gTVFanClubOpinionsText4:: @ 81A8C77
	.string "Sehen wir mal weiter...\n"
	.string "Und was genau findet {STR_VAR_1} so\l"
	.string "anziehend an {STR_VAR_2}?\p"
	.string "... ... ... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Heiaaa! Was für eine spektakuläre\n"
	.string "Erklärung!\p"
	.string "Die Liebe dieses TRAINERS zu seinem\n"
	.string "{STR_VAR_2} wird mehr als deutlich!$"

gTVFanClubOpinionsText5:: @ 81A8D45
	.string "Hm? Oh, da gibt es noch mehr.\n"
	.string "Dem müssen wir mal nachgehen.\p"
	.string "Lasst uns mal sehen...\p"
	.string "Wir haben {STR_VAR_1} gefragt: “Was be-\n"
	.string "deuten dir POKéMON?”\p"
	.string "... ... ... ... ... ...\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "Das ist das Beste des heutigen Tages!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Man will das immer und immer wieder\n"
	.string "laut herausrufen!\p"
	.string "Nach diesem großartigen Ausruf ist es\n"
	.string "auch schon wieder Zeit, sich zu\l"
	.string "verabschieden!\p"
	.string "Also rufen wir jetzt zum Abschluss\n"
	.string "alle zusammen...\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText1:: @ 81A8EC9
	.string "WIR SIND DER POKéMON-FANCLUB.\p"
	.string "Wir sind live auf Sendung!\p"
	.string "Heute steht unsere Sendung ganz im\n"
	.string "Zeichen unserer POKéMON-UMFRAGE. \p"
	.string "Welcher der Geschichten, die TRAINER\n"
	.string "und POKéMON uns liefern, wird heute\l"
	.string "unsere Aufmerksamkeit gehören?\p"
	.string "Mal sehen...\p"
	.string "Diese hier!\p"
	.string "Wir fangen mit diesem Brief an!\p"
	.string "Dies ist ein Brief von {STR_VAR_1} über\n"
	.string "ein geliebtes {STR_VAR_2}.\p"
	.string "Mal sehen, wie leidenschaftlich der\n"
	.string "Schreiber seine Liebe zu {STR_VAR_2}\l"
	.string "ausdrückt! Hmhm...$"

gTVFanClubText2:: @ 81A9048
	.string "Hui!\n"
	.string "Was für ein wunderbarer Brief!$"

gTVFanClubText3:: @ 81A9067
	.string "Ich liebe ihn, ich muss ihn nochmal lesen!$"

gTVFanClubText4:: @ 81A9088
	.string "Ein großartiger Brief, den man immer und\n"
	.string "immer wieder lesen muss.$"

gTVFanClubText5:: @ 81A90B4
	.string "Dieses kleine “{STR_VAR_3}!” zeigt\n"
	.string "die unglaublich emotionale Bindung!\p"
	.string "Ein großartiger Brief mit einer das Herz\n"
	.string "erwärmenden Tiefe!$"

gTVFanClubText6:: @ 81A911F
	.string "Besonders das kleine “{STR_VAR_3}”!\p"
	.string "Ich liebe es, wie “{STR_VAR_3}” hier\n"
	.string "gebraucht wird!$"

gTVFanClubText7:: @ 81A9152
	.string "Übrigens, auch wenn es nicht wirklich\n"
	.string "wichtig ist, “{STR_VAR_3}” ist\l"
	.string "eine super Aussage.\p"
	.string "Ich werde “{STR_VAR_3}” ab sofort in\n"
	.string "meiner Konversation einsetzen.$"

gTVFanClubText8:: @ 81A91C6
	.string "Wenn ich diesen Brief bewerten müsste,\n"
	.string "bekäme er {STR_VAR_3} Punkte von mir.\p"
	.string "Und für das nächste Mal erwarte ich\n"
	.string "einen noch besseren Brief, {STR_VAR_1}!\p"
	.string "Hui je, schaut euch nur die Uhrzeit an!\n"
	.string "Für heute sage ich Tschüss. Bis zum\l"
	.string "nächsten Mal.$"

SlateportCity_OceanicMuseum_1F_Text_1A927F:: @ 81A927F
	.string "Ach!\n"
	.string "Magst du vielleicht POKéMON?\p"
	.string "Ich habe einen Vertrag mit einem Fern-\n"
	.string "sehsender.\p"
	.string "Ich sammle aktuelle Geschichten von\n"
	.string "POKéMON und ihren TRAINERN.\p"
	.string "Hättest du Lust, mir etwas von dir zu\n"
	.string "erzählen?$"

SlateportCity_OceanicMuseum_1F_Text_1A934C:: @ 81A934C
	.string "Ich sammle aktuelle Geschichten von\n"
	.string "POKéMON und ihren TRAINERN.\p"
	.string "Hättest du Lust, mir etwas von dir zu\n"
	.string "erzählen?$"

SlateportCity_OceanicMuseum_1F_Text_1A93D1:: @ 81A93D1
	.string "Oh, du hast Lust dazu?!?\n"
	.string "Wunderbar! Danke schön!\p"
	.string "Dann erzähl mir doch bitte von\n"
	.string "interessanten Begebenheiten, in denen\l"
	.string "POKéMON eine Rolle spielen.$"

SlateportCity_OceanicMuseum_1F_Text_1A9446:: @ 81A9446
	.string "Oh, ich versteh’ schon...\p"
	.string "Nun, wenn du mir eine interessante\n"
	.string "Geschichte erzählen kannst, sag es mir.$"

SlateportCity_OceanicMuseum_1F_Text_1A949A:: @ 81A949A
	.string "Hach, eine erhebende Geschichte!\p"
	.string "Ich bin sicher, deine Geschichte wird\n"
	.string "im Fernsehen ausgestrahlt.\p"
	.string "Irgendwann bestimmt. Also, verpasse\n"
	.string "sie nicht!$"

SlateportCity_OceanicMuseum_1F_Text_1A952E:: @ 81A952E
	.string "Hmmm... Da habe ich eine wirklich gute\n"
	.string "Geschichte für das Fernsehprogramm.\p"
	.string "Ich sollte sie schnell aufschreiben!$"

gTVRecentHappeningsText1:: @ 81A9581
	.string "Hallo, es ist Zeit für INTERESSANTE\n"
	.string "GESCHICHTEN.\p"
	.string "Für einen POKéMON-TRAINER ist jeder\n"
	.string "Tag ein Tag voller Geschichten.\p"
	.string "Wir möchten heute einige dieser \n"
	.string "POKéMON-Geschichten erzählen.\p"
	.string "Heute erzählen wir die Geschichte von\n"
	.string "TRAINER {STR_VAR_1}.\p"
	.string "Was mag {STR_VAR_1} wohl erlebt haben?\n"
	.string "Lasst es uns herausfinden.\p"
	.string "Mal sehen...$"

gTVRecentHappeningsText2:: @ 81A9694
	.string "War das nicht aufschlussreich?\p"
	.string "Diese Geschichte gibt genau wieder, was\n"
	.string "{STR_VAR_1} vor kurzem erlebt hat. So, als\l"
	.string "hätten wir es selber erlebt.$"

gTVRecentHappeningsText3:: @ 81A971B
	.string "“{STR_VAR_3}”. Das gibt\n"
	.string "der Geschichte Akzente und Tiefe.$"

gTVRecentHappeningsText4:: @ 81A974B
	.string "“{STR_VAR_3}.” Das gibt\n"
	.string "uns einen Eindruck von dem Schauplatz.\l"
	.string "Wir können uns alles besser vorstellen.$"

gTVRecentHappeningsText5:: @ 81A979F
	.string "“{STR_VAR_3}” war die\n"
	.string "eindrucksvollste Stelle der Geschichte.$"

gTVRecentHappeningsText6:: @ 81A97D0
	.string "{STR_VAR_1} hat uns eine wundervolle Ge-\n"
	.string "schichte mit POKéMON erzählt.\p"
	.string "Und nun hat sich diese Geschichte tief\n"
	.string "in unsere Seelen eingebrannt.\p"
	.string "Das war es für heute. Bitte schaltet\n"
	.string "auch nächstes Mal wieder ein.$"

gTVPokemonOutbreakText:: @ 81A986F
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Wir haben soeben von einem sehr\n"
	.string "seltenen Ereignis erfahren.\p"
	.string "Es wird berichtet, dass es in der Umge-\n"
	.string "bung von {STR_VAR_1} zu einem Massen-\l"
	.string "aufkommen der {STR_VAR_2} kam.\p"
	.string "{STR_VAR_2}, das ist bestimmt jedem be-\n"
	.string "kannt, ist ein seltenes POKéMON,\l"
	.string "das nur sehr schwer zu finden ist.\p"
	.string "Das scheint eine seltene Gelegenheit zu\n"
	.string "sein, den Ausbruch von wilden\l"
	.string "{STR_VAR_2} zu beobachten.\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"

gTVNameRaterText1:: @ 81A99D9
	.string "Und nun ist es wieder Zeit für...\n"
	.string "DIE NAMENBEWERTER SHOW\p"
	.string "Ich sage die Zukunft eures POKéMON\n"
	.string "anhand seines Kosenamens vorher.\p"
	.string "Ratschläge habe ich zu geben und\n"
	.string "hilfreiche Ratschläge biete ich an.\p"
	.string "Heute basiert meine Prophezeiung auf\n"
	.string "dem Kosenamen {STR_VAR_3} von dem\l"
	.string "POKéMON {STR_VAR_2} von {STR_VAR_1}.\p"
	.string "Hmhm...\p"
	.string "Hmm...\n"
	.string "Dieser Kosename...$"

gTVNameRaterText2:: @ 81A9AF0
	.string "Ein Kosename, der auf ein vielfältiges\n"
	.string "Talent hindeutet.\p"
	.string "Ich rate dem TRAINER, mutig zu sein\n"
	.string "und sich vielen Herausforderungen\l"
	.string "zu stellen.$"

gTVNameRaterText3:: @ 81A9B69
	.string "Dieser Kosename passt perfekt\n"
	.string "zu {STR_VAR_1}, dem Namen des TRAINERS!\p"
	.string "Ich sehe eine starke Partnerschaft, in\n"
	.string "der das Timing perfekt ist.$"

gTVNameRaterText4:: @ 81A9BEF
	.string "Dieser Kosename betont die einzig-\n"
	.string "artige Persönlichkeit des POKéMON.\p"
	.string "Wird das POKéMON gut aufgezogen, ent-\n"
	.string "wickelt sich seine Einzigartigkeit voll.$"

gTVNameRaterText5:: @ 81A9C6A
	.string "Dieser Kosename zeigt die mitfühlende\n"
	.string "und fürsorgliche Seite der POKéMON.\p"
	.string "Wird dieses POKéMON gut aufgezogen,\n"
	.string "wird es sehr warmherzig sein!$"

gTVNameRaterText6:: @ 81A9CF8
	.string "Ein schöner Kosename, der auf die\n"
	.string "zukünftige Größe hindeutet.\p"
	.string "Mich würde es schon interessieren, was\n"
	.string "die Zukunft für dieses POKéMON bringt.$"

gTVNameRaterText7:: @ 81A9D74
	.string "Dieser gute Kosename sollte das\n"
	.string "POKéMON kräftig und herzlich\l"
	.string "werden lassen!\p"
	.string "Dieses POKéMON wird für lange, lange\n"
	.string "Zeit gesund und fit sein.$"

gTVNameRaterText8:: @ 81A9DF3
	.string "Dieser gute Kosename sollte das\n"
	.string "POKéMON sehr aktiv machen!\p"
	.string "Ich denke, das POKéMON wird in\n"
	.string "Kämpfen stark auftreten.$"

gTVNameRaterText9:: @ 81A9E75
	.string "Ein ansprechender Kosename, der dem\n"
	.string "POKéMON Charme verleihen wird!\p"
	.string "Ich bezweifle nicht, dass das POKéMON\n"
	.string "in einem POKéMON WETTBEWERB alle\l"
	.string "mit seinem Charme betören wird!$"

gTVNameRaterText10:: @ 81A9F06
	.string "Der Kosename {STR_VAR_1} wurzelt in\n"
	.string "dem Buchstaben “{STR_VAR_3}”.\p"
	.string "Der Buchstabe wird noch verstärkt\n"
	.string "durch den Anfangsbuchstaben “{STR_VAR_2}”,\p"
	.string "wodurch der Kosename eine starke\n"
	.string "Ausstrahlung bekommt.$"

gTVNameRaterText11:: @ 81A9F9F
	.string "Der Kosename {STR_VAR_1} ist auf \n"
	.string "ansprechende Weise wohlklingend.\p"
	.string "Die Ausstrahlung der Buchstaben “{STR_VAR_2}”\n"
	.string "und “{STR_VAR_3}” - einfach bemerkenswert!$"

gTVNameRaterText12:: @ 81AA01E
	.string "Der Kosename {STR_VAR_1} - er strahlt\n"
	.string "ein sublimes, fließendes Gefühl aus.\p"
	.string "Der Fluss des ersten Buchstaben “{STR_VAR_2}”\n"
	.string "bis hin zum “{STR_VAR_3}” ist wunderbar.$"

gTVNameRaterText13:: @ 81AA09D
	.string "Lasst uns weitere Beispiele für gute\n"
	.string "Kosenamen untersuchen.$"

gTVNameRaterText14:: @ 81AA0D7
	.string "Nehmen wir zum Beispiel einen Teil des\n"
	.string "Namens von TRAINER {STR_VAR_1}. Wir er-\l"
	.string "halten den schönen Kosenamen {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText15:: @ 81AA138
	.string "Natürlich wäre der Kosename {STR_VAR_2}{STR_VAR_3}\n"
	.string "genauso schön.$"

gTVNameRaterText16:: @ 81AA166
	.string "Der Name der POKéMON-Kategorie\n"
	.string "{STR_VAR_2} kann ebenfalls als Basis für\l"
	.string "den Kosenamen {STR_VAR_1}{STR_VAR_3} dienen.$"

gTVNameRaterText17:: @ 81AA1C0
	.string "{STR_VAR_1}{STR_VAR_3} ist ebenfalls ein anziehender\n"
	.string "Kosename.$"

gTVNameRaterText18:: @ 81AA1EA
	.string "Man sollte niemals einem POKéMON die\n"
	.string "Kategoriebezeichnung eines anderen\l"
	.string "POKéMON als Kosenamen geben!\p"
	.string "Zum Beispiel sollte der Name von\n"
	.string "{STR_VAR_2} nicht für den Namen {STR_VAR_1}{STR_VAR_3}\l"
	.string "verwendet werden.$"

gTVNameRaterText19:: @ 81AA28A
	.string "Aber ich gebe zu, {STR_VAR_2}\n"
	.string "liegt die Vergabe der Namen geradezu\l"
	.string "im Blut.\p"
	.string "Und ich hoffe, dass der TRAINER\n"
	.string "{STR_VAR_1} weiter liebevoll behandelt.\p"
	.string "Das war unsere heutige Show.\n"
	.string "Wir sehen uns hoffentlich bald wieder.$"


gTVFishingGuruAdviceText1:: @ 81AA344
	.string " {STR_VAR_2}-ANGLER\p"
	.string "MODERATOR: Hallo! Heute gibt uns\n"
	.string "{STR_VAR_2} Tipps zum Angeln.\p"
	.string "GURU, welchen Ratschlag haben\n"
	.string "Sie für uns?\p"
	.string "GURU: Hm? Ein {STR_VAR_2} fangen?\n"
	.string "Nun, zunächst sind Geduld und Ausdauer\l"
	.string "gefragt. Das ist das Wichtigste.\p"
	.string "Sehen Sie {STR_VAR_1} dort drüben?\n"
	.string "Dieser TRAINER ist ein gutes Beispiel.\p"
	.string "Der TRAINER hat bereits {STR_VAR_3}\n"
	.string "POKéMON entkommen lassen.\p"
	.string "Aber {STR_VAR_1} wartet ab. Gibt nicht auf.\n"
	.string "Das ist die erste Regel beim Angeln von\l"
	.string "{STR_VAR_2}.\p"
	.string "MODERATOR: Ich verstehe...\p"
	.string "Oh! {STR_VAR_1} hat endlich das extrem\n"
	.string "schnelle {STR_VAR_2} gefangen!\p"
	.string "Der TRAINER ist den Tränen nahe vor\n"
	.string "Freude!\p"
	.string "Wenn ich diesen begeisterten Ausdruck\n"
	.string "sehe, möchte ich auch Angeln gehen.\p"
	.string "Zuschauer, warum nutzen Sie nicht die\n"
	.string "Chance, einige {STR_VAR_2} zu fischen?\p"
	.string "Bis zur nächsten Sendung leben Sie wohl\n"
	.string "und Petri heil!$"


gTVFishingGuruAdviceText2:: @ 81AA5F3
	.string " {STR_VAR_2}-ANGLER\p"
	.string "MODERATOR: Hallo! Heute gibt uns\n"
	.string "{STR_VAR_2} Tipps für das Angeln.\p"
	.string "GURU, welchen Ratschlag haben\n"
	.string "Sie für uns?\p"
	.string "GURU: Hm? {STR_VAR_2} fangen?\n"
	.string "Nun, setzen Sie Ihre ANGEL mit viel\l"
	.string "Kraft ein.\p"
	.string "Sehen Sie {STR_VAR_1} dort drüben?\n"
	.string "Wie hier die ANGEL gehandhabt wird?\p"
	.string "Der TRAINER hat bereits {STR_VAR_3}\n"
	.string "fangen können.\p"
	.string "MODERATOR: Das ist unglaublich!\n"
	.string "Es wirkt wie ein Sturm...\p"
	.string "Wenn ich solche Techniken beobachte,\n"
	.string "möchte ich auch sofort Angeln gehen.\p"
	.string "Zuschauer, warum nutzen Sie nicht die\n"
	.string "Chance, einige {STR_VAR_2} zu fischen?\p"
	.string "Bis zur nächsten Sendung leben Sie wohl\n"
	.string "und Petri heil!$"


gTVPokemonTodayFailedCaptureText1:: @ 81AA814
	.string "Hallo!\p"
	.string "Willkommen bei POKéMON HEUTE!\p"
	.string "SCHWESTER: Hallo! Alles gesund\n"
	.string "und munter?\p"
	.string "Heute werfen wir einen Blick auf das\n"
	.string "POKéMON {STR_VAR_2} von {STR_VAR_1}!\p"
	.string "BRUDER: Yeah! Genau das werden wir tun!$"

gTVPokemonTodayFailedCaptureText2:: @ 81AA8C6
	.string "Oh!\n"
	.string "Da wir gerade über {STR_VAR_1} sprechen...\p"
	.string "SCHWESTER, ich habe den TRAINER mit\n"
	.string "eigenen Augen gesehen!\p"
	.string "SCHWESTER: Und was hast du\n"
	.string "beobachtet?\p"
	.string "BRUDER: Nun, ich war gerade unterwegs\n"
	.string "nach {STR_VAR_2}.\p"
	.string "Da sah ich, wie {STR_VAR_1} versuchte, das \n"
	.string "POKéMON {STR_VAR_3} zu fangen, aber...$"

gTVPokemonTodayFailedCaptureText3:: @ 81AA9B2
	.string "Das POKéMON konnte flüchten!\p"
	.string "Und wie viele POKéBÄLLE wurden am Ende\n"
	.string "verbraucht? {STR_VAR_2}! Und das für nichts!\p"
	.string "Du hättest den frustrierten Ausdruck\n"
	.string "im Gesicht von {STR_VAR_1} sehen\p"
	.string "sollen, als das POKéMON sich aus dem\n"
	.string "Staub machte!$"

gTVPokemonTodayFailedCaptureText4:: @ 81AAA5C
	.string "Aber {STR_VAR_1} hat zu lange daneben-\n"
	.string "geworfen, bis das POKéMON\l"
	.string "kampfunfähig wurde!\p"
	.string "Und wie viele POKéBÄLLE wurden am Ende\n"
	.string "verbraucht? {STR_VAR_2}! Und das für nichts!\p"
	.string "Du hättest den Ausdruck fassungsloser\n"
	.string "Bestürzung auf dem Gesicht von\l"
	.string "{STR_VAR_1}\p"
	.string "sehen sollen, als das POKéMON plötzlich\n"
	.string "kampfunfähig wurde!$"

gTVPokemonTodayFailedCaptureText5:: @ 81AAB11
	.string "SCHWESTER: Hey, du da!\n"
	.string "Das ist aber nicht nett!\p"
	.string "Du solltest dich nicht über das Unglück\n"
	.string "anderer lustig machen!\p"
	.string "Oh, mir tut {STR_VAR_1} Leid.\n"
	.string "Was für eine Schande!\p"
	.string "BRUDER: Da hast du Recht!\n"
	.string "Tut mir Leid, dass ich gelacht habe.$"

gTVPokemonTodayFailedCaptureText6:: @ 81AABB4
	.string "SCHWESTER: Räusper Haha Räusper Haha...\p"
	.string "BRUDER: HEY!\n"
	.string "Du lachst ja!\p"
	.string "SCHWESTER: Ich???\p"
	.string "Ich habe doch nicht gelacht!\n"
	.string "Ehrlich nicht!\p"
	.string "Mir tut {STR_VAR_1} echt Leid.\n"
	.string "Was für eine Schande!\p"
	.string "BRUDER: ...$"

gTVPokemonTodayFailedCaptureText7:: @ 81AAC47
	.string "SCHWESTER: Schluss jetzt mit dem\n"
	.string "Blödsinn! Lasst uns das heutige\l"
	.string "POKéMON betrachten...\p"
	.string "Wie?\n"
	.string "Wir haben keine Zeit mehr dafür?\p"
	.string "Oooh! Dann haben wir heute ja gar kein\n"
	.string "POKéMON vorgestellt!\p"
	.string "BRUDER: Also, bis zum nächsten Mal!\p"
	.string "SCHWESTER: Hey, du kannst die Show\n"
	.string "doch nicht einfach ohne mich beenden!$"

gTVPokemonTodayText1:: @ 81AAD23
	.string "Hallo!\p"
	.string "Willkommen bei POKéMON HEUTE!\p"
	.string "SCHWESTER: Hallo! Alles gesund\n"
	.string "und munter?\p"
	.string "Heute werfen wir einen Blick auf das\n"
	.string "POKéMON {STR_VAR_2} von {STR_VAR_1}!\p"
	.string "BRUDER: Yeah! Genau das werden wir tun!$"

gTVPokemonTodayText2:: @ 81AADD5
	.string "SCHWESTER: {STR_VAR_1} hat {STR_VAR_2} den\n"
	.string "Kosenamen {STR_VAR_3} gegeben!\p"
	.string "{STR_VAR_3} scheint wirklich liebevoll\n"
	.string "behandelt zu werden.$"

gTVPokemonTodayText3:: @ 81AAE31
	.string "BRUDER: Und wie viele BÄLLE musste der\n"
	.string "TRAINER werfen, um es zu fangen? {STR_VAR_3}!\p"
	.string "Ein {STR_VAR_2} brachte den\n"
	.string "gewünschten Erfolg!$"

gTVPokemonTodayText4:: @ 81AAE9D
	.string "SCHWESTER: Wenn das Fangen so einfach\n"
	.string "war, wollte das Schicksal {STR_VAR_1} und\l"
	.string "{STR_VAR_2} wohl zusammenführen!$"

gTVPokemonTodayText5:: @ 81AAF03
	.string "SCHWESTER: Wow! Wie aufregend!\p"
	.string "Man sagt, dass ein POKéMON, das schwer\n"
	.string "zu fangen ist, die Liebe seines\l"
	.string "TRAINERS verdient!$"

gTVPokemonTodayText6:: @ 81AAF8A
	.string "SCHWESTER: {STR_VAR_2} von {STR_VAR_1} ist\n"
	.string "ein bemerkenswertes POKéMON, da\p"
	.string "es nur mit dem unfehlbaren\n"
	.string "MEISTERBALL gefangen werden konnte!\p"
	.string "BRUDER: Wow! Das ist\n"
	.string "mega-beeindruckend!\p"
	.string "SCHWESTER: {STR_VAR_1} muss {STR_VAR_2} \n"
	.string "wirklich gewollt haben! Mit Sicherheit!$"

gTVPokemonTodayText7:: @ 81AB040
	.string "BRUDER: Und dann erhält {STR_VAR_2}\n"
	.string "auch noch den Kosenamen {STR_VAR_3}...\p"
	.string "Das ermöglicht einen guten Einblick in\n"
	.string "die Einstellung von TRAINER {STR_VAR_1}.\p"
	.string "SCHWESTER: Das sehe ich auch so!$"

gTVPokemonTodayText8:: @ 81AB0C8
	.string "Ich würde diesen Kosenamen einem\n"
	.string "{STR_VAR_3} geben!\p"
	.string "BRUDER: Hui! Das wäre der Anfang von\n"
	.string "etwas ganz Neuem.$"

gTVPokemonTodayText9:: @ 81AB13D
	.string "{STR_VAR_2}, das {STR_VAR_1}?\n"
	.string "Hört sich das nicht einfach perfekt an?\p"
	.string "Die Buchstaben und alles - wie\n"
	.string "geschaffen für das POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "BRUDER: Yeah! Stimmt! Absolut!$"

gTVPokemonTodayText10:: @ 81AB1C6
	.string "Soweit ich weiß, hat noch kein TRAINER\n"
	.string "jemals seinem {STR_VAR_1} den\l"
	.string "Kosenamen {STR_VAR_2} gegeben!\p"
	.string "BRUDER: Das zeigt doch nur, welch einen\n"
	.string "hervorragenden Geschmack der TRAINER\l"
	.string "bei der Wahl des Kosenamens bewies!$"

gTVPokemonTodayText11:: @ 81AB266
	.string "Mein nächstes POKéMON bekommt den\n"
	.string "Kosenamen {STR_VAR_2}.\p"
	.string "BRUDER: Wie? Meines auch!\n"
	.string "Ich werde es auch {STR_VAR_2} nennen!$"

gTVPokemonTodayText12:: @ 81AB2DB
	.string "SCHWESTER: Oh je!\n"
	.string "Schau dir nur die Uhrzeit an!\p"
	.string "Nun, Freunde, das war es für heute.\n"
	.string "Wir sehen uns das nächste Mal wieder!\p"
	.string "BRUDER: Denkt daran, es könnte euer\n"
	.string "POKéMON sein, das wir hier vorstellen!$"


gTVSmartShopperText1:: @ 81AB381
	.string "Hallo!\p"
	.string "Zeit für den heutigen CLEVERKAUF!\p"
	.string "INTERVIEWER: Wie geht es euch?\p"
	.string "Heute besuchen wir ein Geschäft\n"
	.string "in {STR_VAR_2}.\p"
	.string "Schauen wir doch mal, welche Artikel\n"
	.string "dort besonders begehrt sind.$"

gTVSmartShopperText2:: @ 81AB435
	.string "Fragen wir doch einfach den Verkäufer\n"
	.string "hier.\p"
	.string "Hallo, wie läuft das Geschäft?\p"
	.string "VERKÄUFER: Oh, ausgezeichnet!\p"
	.string "Im Moment verkaufen wir {STR_VAR_2}\n"
	.string "besonders gut.\p"
	.string "Und gerade hat ein TRAINER namens\n"
	.string "{STR_VAR_1} {STR_VAR_3} gekauft.$"

gTVSmartShopperText3:: @ 81AB507
	.string "INTERVIEWER: Der TRAINER hat {STR_VAR_3}-mal\n"
	.string "{STR_VAR_2} gekauft? Wow!\p"
	.string "Mir scheint es, als ob {STR_VAR_1} sich\n"
	.string "für eine längere Reise rüstet.\p"
	.string "Auf Reisen ist {STR_VAR_2} einfach\n"
	.string "unverzichtbar.$"

gTVSmartShopperText4:: @ 81AB5B8
	.string "INTERVIEWER: Da wir gerade von\n"
	.string "{STR_VAR_2} sprechen...\l"
	.string "Ich habe {STR_VAR_3} gekauft.\p"
	.string "{STR_VAR_2} ist ein großartiges Item!$"

gTVSmartShopperText5:: @ 81AB61F
	.string "INTERVIEWER: {STR_VAR_2}?!?\n"
	.string "Und gleich {STR_VAR_3} davon?!?\p"
	.string "Ich hätte nicht gedacht, dass jemand\n"
	.string "so viel davon kauft.\p"
	.string "Meine Güte, ich könnte mir höchstens\n"
	.string "ein oder zwei auf einmal davon leisten...$"

gTVSmartShopperText6:: @ 81AB6B0
	.string "INTERVIEWER: Ich habe erst ein Mal\n"
	.string "sehr viel gekauft. Eine große\l"
	.string "Stückzahl des Items {STR_VAR_2}.\p"
	.string "Aber schließlich war auch das zu viel.\n"
	.string "Ich habe es hinterher echt bereut...\p"
	.string "Seitdem kaufe ich grundsätzlich nur\n"
	.string "noch das, was ich wirklich brauche...\p"
	.string "Huups!\p"
	.string "Wir wollen doch hier nicht über mich\n"
	.string "reden!$"

gTVSmartShopperText7:: @ 81AB78D
	.string "VERKÄUFER: {STR_VAR_1} hat auch von dem\n"
	.string "Item {STR_VAR_2} gleich {STR_VAR_3} Exemplare\l"
	.string "gekauft.\p"
	.string "INTERVIEWER: Oh, das ist clever.\n"
	.string "{STR_VAR_2} ist ein sehr gutes Item...$"

gTVSmartShopperText8:: @ 81AB7FE
	.string "VERKÄUFER: Und der TRAINER kaufte\n"
	.string "von dem Item {STR_VAR_2} {STR_VAR_3}\l"
	.string "Exemplare.$"

gTVSmartShopperText9:: @ 81AB835
	.string "VERKÄUFER: Und zwar als es im Sonder-\n"
	.string "angebot war. Clever!!!$"

gTVSmartShopperText10:: @ 81AB873
	.string "INTERVIEWER: Hmm... {STR_VAR_1} scheint ein\n"
	.string "richtiger Schnäppchenjäger zu sein!\p"
	.string "{STR_VAR_1} brauchte also für alles nur...\p"
	.string "¥{STR_VAR_2} zu bezahlen?!?\n"
	.string "Wie unglaublich günstig!\p"
	.string "Oh! Wir sind am Ende unserer Sendung!\n"
	.string "Bis zum nächsten Mal! Auf Wiedersehen!$"

gTVSmartShopperText11:: @ 81AB92E
	.string "VERKÄUFER: {STR_VAR_1} ist ein VIP-Kunde,\n"
	.string "daran besteht kein Zweifel.$"

gTVSmartShopperText12:: @ 81AB95E
	.string "Fragen wir doch mal den Verkäufer.\p"
	.string "Hallo, wie läuft das Geschäft?\p"
	.string "VERKÄUFER: Oh, es ist einfach un-\n"
	.string "glaublich. Einfach überwältigend.\p"
	.string "Vor kurzem hat ein TRAINER namens\n"
	.string "{STR_VAR_1} das Item {STR_VAR_2}\l"
	.string "in großer Stückzahl gekauft.\p"
	.string "Er hat fast das ganze Regal mit\n"
	.string "{STR_VAR_2} leergeräumt.\p"
	.string "Ich hätte nie gedacht, dass es einen\n"
	.string "TRAINER gibt, der {STR_VAR_2} \l"
	.string "in so großen Mengen benötigt!\p"
	.string "INTERVIEWER: Das waren dann ja 100\n"
	.string "oder 200 Exemplare!?!\p"
	.string "VERKÄUFER: Oh, nein. Viel, viel mehr!\p"
	.string "INTERVIEWER: Du meine Güte! {STR_VAR_1}\n"
	.string "muss ein ganz besonderer Kunde sein!\p"
	.string "VERKÄUFER: {STR_VAR_1} ist ein VIP-Kunde,\n"
	.string "daran besteht gar kein Zweifel!$"

gTVSmartShopperText13:: @ 81ABB75
	.string "INTERVIEWER: Hmm...\n"
	.string "Das ist unglaublich.\p"
	.string "Aber warum hat der TRAINER wohl gleich\n"
	.string "so viel auf einmal gekauft?\p"
	.string "... ...\p"
	.string "Ein Mysterium... Aber leider haben wir\n"
	.string "keine Zeit mehr, hinter das Geheimnis\l"
	.string "zu kommen. Bis zur nächsten Sendung!\p"
	.string "{STR_VAR_1} muss ein Rätsel bleiben...$"


gTVWorldOfMastersText1:: @ 81ABC51
	.string "DIE WELT DER MEISTER\p"
	.string "Hallo, liebe Zuschauer.\p"
	.string "Vielleicht ist Ihnen schon einmal der\n"
	.string "TRAINER {STR_VAR_1} begegnet.\p"
	.string "{STR_VAR_1} ist berühmt als Meister im\n"
	.string "Fangen von POKéMON.\p"
	.string "Der Erfolg von {STR_VAR_1} im Fangen von\n"
	.string "POKéMON basiert auf einer gründlichen\l"
	.string "Suche, die zu Fuß stattfindet.\p"
	.string "Eines denkwürdigen Tages machte\n"
	.string "der TRAINER  {STR_VAR_2} Schritte.\p"
	.string "Die Gesamtzahl der an diesem Tag\n"
	.string "gefangenen POKéMON betrug {STR_VAR_3}!$"

gTVWorldOfMastersText2:: @ 81ABD94
	.string "Diese bemerkenswerte Leistung war nur\n"
	.string "möglich, weil zwischen dem TRAINER und\l"
	.string "{STR_VAR_1} tiefes Vertrauen besteht.$"

gTVWorldOfMastersText3:: @ 81ABDF2
	.string "Der Meister hat das letzte {STR_VAR_3}\n"
	.string "an diesem Tage in der Nähe von\l"
	.string "{STR_VAR_2} gefangen.\p"
	.string "Dieses POKéMON kann sich nun an\n"
	.string "dem besonderen Rang des Rekordhalters\l"
	.string "erfreuen.\p"
	.string "Talentierte TRAINER sollten versuchen,\n"
	.string "diesen Rekord zu brechen.\p"
	.string "Das war’s für heute.\n"
	.string "Bis zum nächsten Mal.$"

	.include "data/text/gabby_and_ty.inc"
	.include "data/text/pokemon_news.inc"
