MauvilleCity_GameCorner_Text_ThisIsMauvilleGameCorner:: @ 8181C35
	.string "This is MAUVILLE GAME CORNER.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseForCoins:: @ 8181C53
	.string "Okay, you wanted some COINS for\n"
	.string "the games?\p"
	.string "But you don't have a COIN CASE for\n"
	.string "stowing the COINS.$"

MauvilleCity_GameCorner_Text_WereYouLookingForCoins:: @ 8181CB4
	.string "Were you looking for COINS?\p"
	.string "It's ¥1000 for 50 COINS.\n"
	.string "Would you like some?$"

MauvilleCity_GameCorner_Text_ThankYouHereAreYourCoins:: @ 8181CFE
	.string "Thank you very much!\n"
	.string "Here are your COINS!$"

MauvilleCity_GameCorner_Text_DontHaveEnoughMoney:: @ 8181D28
	.string "Um... You don't appear to have\n"
	.string "enough money...$"

MauvilleCity_GameCorner_Text_CoinCaseIsFull:: @ 8181D57
	.string "Oh?\n"
	.string "Your COIN CASE is full.$"

MauvilleCity_GameCorner_Text_DontNeedCoinsThen:: @ 8181D73
	.string "Oh... You don't need COINS, then?\n"
	.string "Good luck on your adventure!$"

UnknownString_8181DB2: @ 8181DB2
	.string "It's ¥1,000 for 50 COINS.\n"
	.string "Would you like some?$"

MauvilleCity_GameCorner_Text_ExchangeCoinsForPrizes:: @ 8181DE1
	.string "Welcome.\p"
	.string "You can exchange your COINS for\n"
	.string "prizes here.$"

MauvilleCity_GameCorner_Text_WhichPrize:: @ 8181E17
	.string "Which prize would you like?$"

MauvilleCity_GameCorner_Text_SoYourChoiceIsX:: @ 8181E33
	.string "So your choice is {STR_VAR_1}?$"

MauvilleCity_GameCorner_Text_SendToYourHomePC:: @ 8181E49
	.string "Thank you!\n"
	.string "We'll send it to your PC at home.$"

MauvilleCity_GameCorner_Text_NotEnoughCoins:: @ 8181E76
	.string "You don't have enough COINS.$"

UnknownString_8181E93: @ 8181E93
	.string "There isn't any room available for\n"
	.string "placing {STR_VAR_1}.$"

MauvilleCity_GameCorner_Text_OhIsThatSo:: @ 8181EC2
	.string "Oh, is that so? \n"
	.string "You need to save some COINS before\l"
	.string "coming back here.$"

MauvilleCity_GameCorner_Text_HereYouGo:: @ 8181F08
	.string "Here you go!$"

UnknownString_8181F15: @ 8181F15
	.string "Oh, you can't carry any more than that.$"

MauvilleCity_GameCorner_Text_GotTwoOfSameDollWantOne:: @ 8181F3D
	.string "I made a mistake and got two of the\n"
	.string "same DOLLS.\p"
	.string "Would you like one of them?$"

MauvilleCity_GameCorner_Text_HereYouGo2:: @ 8181F89
	.string "There you go!$"

MauvilleCity_GameCorner_Text_YouWantItButNotNow:: @ 8181F97
	.string "Huh?\n"
	.string "You want it, but not right now?$"

MauvilleCity_GameCorner_Text_DontBeNegative:: @ 8181FBC
	.string "Oh, don't be so negative!\n"
	.string "You can have this!$"

MauvilleCity_GameCorner_Text_CantWinJackpot:: @ 8181FE9
	.string "There's a prize I want, but I can't win\n"
	.string "the jackpot.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseGoNextDoor:: @ 818201E
	.string "Hey, kid, if you want to play here,\n"
	.string "you need a COIN CASE.\p"
	.string "I think the young lady next door\n"
	.string "had one. Go see her!$"

MauvilleCity_GameCorner_Text_LuckOnlyLastSoLongTakeCoins:: @ 818208E
	.string "My luck can only last so long.\n"
	.string "This is too much for me.\l"
	.string "Here, take some COINS!$"

MauvilleCity_GameCorner_Text_MauvilleSomethingForEveryone:: @ 81820DD
	.string "MAUVILLE has something for\n"
	.string "everyone.\p"
	.string "For me, it's the GAME CORNER.$"

MauvilleCity_GameCorner_Text_RouletteTablesDifferentRates:: @ 8182120
	.string "The ROULETTE tables have different\n"
	.string "rates.\p"
	.string "Check your COINS if you're going to\n"
	.string "pick a table.$"

MauvilleCity_GameCorner_Text_EasyToLoseTrackOfTime:: @ 818217C
	.string "It's easy to lose track of time in here. \n"
	.string "I should get back to work.$"

MauvilleCity_GameCorner_Text_CoinsAreNeededToPlay:: @ 81821C1
	.string "COINS are needed to play here in the\n"
	.string "GAME CORNER.$"

MauvilleCity_GameCorner_Text_RouletteOnlyLuck:: @ 81821F3
	.string "This ROULETTE thing...\n"
	.string "It's rather demanding.\p"
	.string "Win or lose, it's only by luck.$"

MauvilleCity_GameCorner_Text_UpTo3CoinsCanBeUsed:: @ 8182241
	.string "Up to three COINS can be used to play\n"
	.string "the SLOTS.$"

MauvilleCity_GameCorner_Text_DifficultToStopOn7:: @ 8182272
	.string "It's very difficult to make it stop\n"
	.string "right on “7.”\p"
	.string "If it stops on “7” during the REEL TIME\n"
	.string "bonus game, you'll receive extra COINS.$"

MauvilleCity_GameCorner_Text_HeresSomeSlotsInfo:: @ 81822F4
	.string "Here's some information for you\n"
	.string "about the SLOTS.\p"
	.string "The more lightning bolts you stock, the\n"
	.string "more REEL TIME chances you get.\p"
	.string "In a game with the maximum five REEL\n"
	.string "TIME chances...\p"
	.string "It is possible to receive four regular\n"
	.string "bonuses, then a big bonus.\p"
	.string "The big bonus is 660 COINS, but it's\n"
	.string "very difficult to get.$"

MauvilleCity_GameCorner_Text_CantPlayWithNoCoinCase:: @ 8182420
	.string "You can't play if you don't have a\n"
	.string "COIN CASE.$"
