RustboroCity_House3_Text_IGivePerfectlySuitedNicknames:: @ 8185584
	.string "Meinen eigenen POKéMON habe ich\n"
	.string "perfekt passende Kosenamen gegeben!\p"
	.string "Das ist mein Ausdruck von... äh...\n"
	.string "Originalität. Genau! Originalität!$"

RustboroCity_House3_Text_NamingPikachuPekachu:: @ 81855FA
	.string "Aber ein PIKACHU einfach PEKACHU zu\n"
	.string "nennen? Das haut einen nicht gerade\l"
	.string "vom Hocker.\p"
	.string "Ich glaube ja auch, man sollte einen\n"
	.string "leicht verständlichen Kosenamen wählen,\l"
	.string "aber irgendwie...$"

RustboroCity_House3_Text_Pekachu:: @ 818567D
	.string "PEKACHU: Peka!$"
