Route110_SeasideCyclingRoadSouthEntrance_Text_19E326:: @ 819E326
	.string "Auf dem RADWEG kannst du so\n"
	.string "schnell fahren, wie du willst.\p"
	.string "Schnell fahren macht Spaß, pass aber\n"
	.string "auf, dass du mit niemandem\l"
	.string "zusammenstößt.$"

Route110_SeasideCyclingRoadNorthEntrance_Text_19E3AD:: @ 819E3AD
Route110_SeasideCyclingRoadSouthEntrance_Text_19E3AD:: @ 819E3AD
	.string "Tut mir Leid, aber auf dem RADWEG\n"
	.string "sind Fußgänger nicht gestattet.\p"
	.string "Das ist gefährlich. Bring dein RAD mit...$"
