MossdeepCity_SpaceCenter_2F_Text_MossdeepIdealForRockets:: @ 818E483
	.string "MOOSBACH CITY hat meistens sonniges\n"
	.string "Wetter und einen beständigen Wind.\p"
	.string "Ein idealer Ort, um Raketen ins All zu\n"
	.string "schicken.$"

MossdeepCity_SpaceCenter_2F_Text_WouldveLikedToBeAstronaut:: @ 818E4EE
	.string "Wenn ich jünger wäre, würde ich mit\n"
	.string "Sicherheit Astronaut...\p"
	.string "Nein... Dazu ist es nie zu spät!\n"
	.string "Ich werde es versuchen!!!$"

MossdeepCity_SpaceCenter_2F_Text_WishOrdinaryPeopleCouldGoIntoSpace:: @ 818E564
	.string "Ich wünschte, auch normale Leute\n"
	.string "könnten eines Tages ins All reisen...$"
