ContestHall_Text_OnlyRegister4Players:: @ 818848C
	.string "Nur vier Spieler können sich für den\n"
	.string "POKéMON WETTBEWERB registrieren.\p"
	.string "Wenn die anderen drei Spieler via\n"
	.string "Link hinzukommen, können alle\l"
	.string "an dem gleichen WETTBEWERB teilnehmen.\p"
	.string "Möchtest du auch teilnehmen?$"

LilycoveCity_ContestLobby_Text_ProgressWillBeSaved:: @ 8188521
	.string "Bevor du an einem WETTBEWERB teil-\n"
	.string "nimmst, wird dein Spiel gespeichert.$"

LilycoveCity_ContestLobby_Text_ParticipateAnotherTime:: @ 8188559
	.string "Wir hoffen, du nimmst ein anderes Mal\n"
	.string "teil.$"

LilycoveCity_ContestLobby_Text_EnterContest:: @ 8188584
	.string "Möchtest du am WETTBEWERB teilnehmen?$"

LilycoveCity_ContestLobby_Text_Explain4PlayerContest:: @ 81885A7
	.string "Wenn die vier Spieler bereit sind,\n"
	.string "verbindet euch via Verbindungskabel\l"
	.string "und registriert euch bitte bei mir.\p"
	.string "Bitte wähle den gleichen WETTBEWERB\n"
	.string "wie deine vier Mitspieler.\p"
	.string "Der WETTBEWERB beginnt, sobald \n"
	.string "alle Spieler registriert wurden.\p"
	.string "Danach werden die üblichen Regeln\n"
	.string "des WETTBEWERBS erklärt.$"

UnknownString_81886A8: @ 81886A8
	.string "Sobald ihr per Link verbunden seid,\n"
	.string "wählt bitte den WETTBEWERB aus.$"

LilycoveCity_ContestLobby_Text_EnterWhichContest:: @ 81886DC
	.string "An welchem WETTBEWERB möchtest du\n"
	.string "teilnehmen?$"

LilycoveCity_ContestLobby_Text_EnterWhichPokemon1:: @ 8188703
	.string "Welches POKéMON soll teilnehmen?$"

LilycoveCity_ContestLobby_Text_Transmitting:: @ 818872A
	.string "Übertragung... $"

LilycoveCity_ContestLobby_Text_TransmissionError:: @ 818873A
	.string "Übertragungsfehler.$"

LilycoveCity_ContestLobby_Text_PlayersChoseDifferentContest:: @ 8188750
	.string "Du hast wohl einen anderen WETTBEWERB\n"
	.string "gewählt als ein anderer Teilnehmer.$"

LilycoveCity_ContestLobby_Text_PlayersMadeDifferentChoice:: @ 818878D
	.string "Du hast wohl eine andere Entscheidung\n"
	.string "getroffen als ein anderer Teilnehmer.$"

LilycoveCity_ContestLobby_Text_PleaseWaitBButtonCancel:: @ 81887C7
	.string "Bitte warten.\n"
	.string "Drücke den B-Knopf, um abzubrechen...$"

LilycoveCity_ContestLobby_Text_ParticipateAnotherTime2:: @ 81887F4
	.string "Wir hoffen, du nimmst ein anderes Mal\n"
	.string "teil.$"

LilycoveCity_ContestLobby_Text_TransmissionErrorTryAgain:: @ 818881F
	.string "Übertragungsfehler.\n"
	.string "Bitte versuche es erneut.$"

LilycoveCity_ContestLobby_Text_YourMonIsEntryNumX:: @ 8188845
	.string "Dein POKéMON wird an dem WETTBEWERB\n"
	.string "teilnehmen.\p"
	.string "Dein POKéMON hat die Nummer {STR_VAR_2}.$"

UnknownString_8188890: @ 8188890
	.string "Nummer {STR_VAR_2} hat diese Farbe für\n"
	.string "den WETTBEWERB zugewiesen bekommen.$"

LilycoveCity_ContestLobby_Text_ContestBeginShortly:: @ 81888C6
	.string "Der WETTBEWERB wird bald beginnen.$"

UnknownString_81888E6: @ 81888E6
	.string "Bitte hier entlang.\n"
	.string "Viel Glück!$"

LilycoveCity_ContestLobby_Text_YourPokemonSpurredMeToPaint:: @ 818890F
	.string "Herzlichen Glückwunsch!\p"
	.string "Ich habe dein POKéMON gezeichnet, zum\n"
	.string "Andenken an seinen Sieg...\p"
	.string "Nun, der Auftritt deines POKéMON war so\n"
	.string "fantastisch, dass er mich zu einer\l"
	.string "künstlerischen Hochleistung anspornte.\l"
	.string "Siehst du?$"

UnknownString_81889D0: @ 81889D0
	.string "Das Gemälde wird auf den Bildschirm\n"
	.string "gerufen.$"

LilycoveCity_ContestLobby_Text_ShouldITakePaintingToMuseum:: @ 81889FD
	.string "Was meinst du? Ich bin mit meiner Arbeit\n"
	.string "zufrieden, aber gefällt sie auch dir?\p"
	.string "Eine Arbeit dieses Formats würde sich\n"
	.string "bestimmt gut in einem Museum machen.\p"
	.string "Ach? Es gibt ein Museum, das nach neuen\n"
	.string "Gemälden sucht?\p"
	.string "Meinst du, ich sollte das Bild anbieten?$"

LilycoveCity_ContestLobby_Text_IllTakePaintingToMuseum:: @ 8188AE8
	.string "Nein, wirklich? Dann werde ich das Bild\n"
	.string "natürlich sofort dort hinbringen.\p"
	.string "Ich werde ihm einen angemessenen Titel\n"
	.string "geben.\p"
	.string "Ich hoffe, es gefällt ihnen, und sie\n"
	.string "werden es ausstellen.\p"
	.string "Bitte, schau es dir mal an, wenn sie es\n"
	.string "ausgestellt haben. Vielen, vielen Dank!$"

LilycoveCity_ContestLobby_Text_TakeMementoOfPainting:: @ 8188BB5
	.string "Oh, richtig!\p"
	.string "Da ich dein POKéMON malen durfte,\n"
	.string "möchte ich dir dies gerne geben.$"

LilycoveCity_ContestLobby_Text_ReceivedARibbon:: @ 8188C03
	.string "{PLAYER} erhält ein BAND.$"

LilycoveCity_ContestLobby_Text_PutTheRibbonOnMon:: @ 8188C19
	.string "{PLAYER} befestigt das BAND an\n"
	.string "{STR_VAR_1}.$"

LilycoveCity_ContestLobby_Text_OkaySeeYou:: @ 8188C32
	.string "Okay, man sieht sich!$"

LilycoveCity_ContestLobby_Text_TakeHomeButIdLikeToTakeToMuseum:: @ 8188C41
	.string "Oh... Ich glaube, dann nehme ich das mit\n"
	.string "zu mir nach Hause...\p"
	.string "Aber weißt du, eigentlich möchte ich das\n"
	.string "viel lieber einem Kunstmuseum\l"
	.string "schenken... Ja?$"

LilycoveCity_ContestLobby_Text_FineThatsTheWayItIs:: @ 8188CBD
	.string "Oh, fein. Genauso soll es sein.\n"
	.string "Ich hänge das bei mir zu Hause auf.\p"
	.string "Nächstes Mal muss ich mir mehr Mühe\n"
	.string "geben. Bis bald mal.$"

LilycoveCity_ContestLobby_Text_MasterRankHereICome:: @ 8188D3C
	.string "Hoo, Junge. WETTBEWERB der\n"
	.string "MASTER-KLASSE, jetzt komme ich.\p"
	.string "Bald wird die Welt wissen, dass mein\n"
	.string "POKéMON das niedlichste aller POKéMON\l"
	.string "ist. Die Zeit ist reif!\l"
	.string "Ahahahaha.$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere:: @ 8188DDA
	.string "Hier sieht man eine ganze Reihe der\n"
	.string "unterschiedlichsten POKéMON.\p"
	.string "Daher mache ich hier jeden Tag eine\n"
	.string "kurze Stippvisite.$"

LilycoveCity_ContestLobby_Text_GetContestPassVerdanturf:: @ 8188E47
	.string "Oh, du liebe Güte! Sie haben dir noch\n"
	.string "keine WETTBEWERBSKARTE gegeben?\p"
	.string "Du solltest sofort nach WIESENFLUR\n"
	.string "gehen. Dort bekommst du eine.\p"
	.string "Es ist unwahrscheinlich aufregend,\n"
	.string "anderen ein POKéMON zu präsentieren,\l"
	.string "das man mit Liebe aufgezogen hat.$"

LilycoveCity_ContestLobby_Text_EyesOpenToMon:: @ 8188F07
	.string "Wenn du erstmals am WETTBEWERB\n"
	.string "der MASTER-KLASSE teilnimmst, wirst du\l"
	.string "POKéMON sehen, die schreien geradezu\l"
	.string "danach, gemalt zu werden.$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme:: @ 8188F81
	.string "Der WETTBEWERB der STÄRKE ist tierisch\n"
	.string "hart!\p"
	.string "Dieses Muskelspiel... Schweiß, der\n"
	.string "rinnt... Da fall ich glatt in Ohnmacht!$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon:: @ 8188FE3
	.string "Tag für Tag habe ich dieses POKéMON mit\n"
	.string "meiner Liebe und Fürsorge überhäuft.\p"
	.string "Seine Kondition ist einfach unver-\n"
	.string "gleichbar. Heute gehört der Sieg uns!$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily:: @ 818904D
	.string "Ich habe {POKEBLOCK} mit Mama, Papa und\n"
	.string "meiner Schwester gemacht. Sie sind\l"
	.string "sehr gut geworden!\p"
	.string "Ich glaube, je mehr Leute dir bei der\n"
	.string "Herstellung von {POKEBLOCK} helfen, desto\l"
	.string "besser ist die Qualität.$"
