FallarborTown_ContestHall_MapScripts:: @ 8153ACE
	.byte 0

FallarborTown_ContestHall_EventScript_153ACF:: @ 8153ACF
	msgbox FallarborTown_ContestHall_Text_177335, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_153AD8:: @ 8153AD8
	msgbox FallarborTown_ContestHall_Text_1773C6, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_153AE1:: @ 8153AE1
	msgbox FallarborTown_ContestHall_Text_177437, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_153AEA:: @ 8153AEA
	msgbox FallarborTown_ContestHall_Text_1774B1, MSGBOX_SIGN
	end
