FallarborTown_ContestHall_MapScripts:: @ 8153ACE
	.byte 0

FallarborTown_ContestHall_EventScript_DoAllRightInPreliminary:: @ 8153ACF
	msgbox FallarborTown_ContestHall_Text_DoAllRightInPreliminary, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_MonAllTheseRibbons:: @ 8153AD8
	msgbox FallarborTown_ContestHall_Text_MonAllTheseRibbons, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_CantWinEverywhere:: @ 8153AE1
	msgbox FallarborTown_ContestHall_Text_CantWinEverywhere, MSGBOX_NPC
	end

FallarborTown_ContestHall_EventScript_SuperRankStage:: @ 8153AEA
	msgbox FallarborTown_ContestHall_Text_SuperRankStage, MSGBOX_SIGN
	end
