Route110_TrickHousePuzzle8_Text_VincentIntro:: @ 819E178
	.string "Not many TRAINERS have made it\n"
	.string "this far.$"

Route110_TrickHousePuzzle8_Text_VincentDefeat:: @ 819E1A1
	.string "That must mean you're tough, too...$"

Route110_TrickHousePuzzle8_Text_VincentPostBattle:: @ 819E1C5
	.string "You've beaten the POKéMON LEAGUE\n"
	.string "CHAMPION? That's too much!$"

Route110_TrickHousePuzzle8_Text_ElaineIntro:: @ 819E201
	.string "Consider yourself lucky to be\n"
	.string "battling me!$"

Route110_TrickHousePuzzle8_Text_ElaineDefeat:: @ 819E22C
	.string "This isn't right!\n"
	.string "I can't lose!$"

Route110_TrickHousePuzzle8_Text_ElainePostBattle:: @ 819E24C
	.string "It's a miracle that you beat me.\n"
	.string "You can brag about it.$"

Route110_TrickHousePuzzle8_Text_LeroyIntro:: @ 819E284
	.string "You've been slugging through the TRICK\n"
	.string "HOUSE challenge, too.$"

Route110_TrickHousePuzzle8_Text_LeroyDefeat:: @ 819E2C1
	.string "I see...\n"
	.string "You possess an extraordinary style.$"

Route110_TrickHousePuzzle8_Text_LeroyPostBattle:: @ 819E2EE
	.string "Seeing someone like you should please\n"
	.string "the TRICK MASTER.$"
