EverGrandeCity_PokemonCenter_1F_Text_LeagueAfterVictoryRoad:: @ 8191967
	.string "Die POKéMON LIGA triffst du kurz hinter\n"
	.string "der SIEGESSTRASSE.\p"
	.string "Wenn du schon so weit gekommen bist,\n"
	.string "musst du einfach weitergehen.$"

EverGrandeCity_PokemonCenter_1F_Text_BelieveInYourPokemon:: @ 81919EF
	.string "Die lange und qualvolle SIEGESSTRASSE...\p"
	.string "Es ist fast so, als würde man sein\n"
	.string "ganzes Leben noch einmal leben...\p"
	.string "Glaube an deine POKéMON und gib\n"
	.string "dein Bestes!$"
