#include "global.h"
#include "menu.h"

#if DEBUG

__attribute__((naked))
int debug_sub_813C404()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._1\n"
        "	ldr	r4, ._1 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._2:\n"
        "	.align	2, 0\n"
        "._1:\n"
        "	.word	gUnknown_Debug_845DDB2\n"
        "	.word	gUnknown_Debug_845DAE1\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C430()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._3\n"
        "	ldr	r4, ._3 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._4:\n"
        "	.align	2, 0\n"
        "._3:\n"
        "	.word	gUnknown_Debug_845E402\n"
        "	.word	gUnknown_Debug_845E3E0\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C45C()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._5\n"
        "	ldr	r4, ._5 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._6:\n"
        "	.align	2, 0\n"
        "._5:\n"
        "	.word	gUnknown_Debug_845E443\n"
        "	.word	gUnknown_Debug_845E422\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C488()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._7\n"
        "	ldr	r4, ._7 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._8:\n"
        "	.align	2, 0\n"
        "._7:\n"
        "	.word	gUnknown_Debug_845E422\n"
        "	.word	gUnknown_Debug_845E402\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C4B4()
{
    asm(
        "	push	{r4, lr}\n"
        "	ldr	r4, ._9\n"
        "	ldr	r1, ._9 + 4\n"
        "	sub	r4, r4, r1\n"
        "	add	r2, r4, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r4, #0\n"
        "	pop	{r4}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._10:\n"
        "	.align	2, 0\n"
        "._9:\n"
        "	.word	gUnknown_Debug_845E619\n"
        "	.word	gUnknown_Debug_845E606\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C4D4()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._11\n"
        "	ldr	r4, ._11 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_81261B4\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._12:\n"
        "	.align	2, 0\n"
        "._11:\n"
        "	.word	gUnknown_Debug_845E712\n"
        "	.word	gUnknown_Debug_845E619\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C500()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._13\n"
        "	ldr	r4, ._13 + 4\n"
        "	sub	r5, r5, r4\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._14:\n"
        "	.align	2, 0\n"
        "._13:\n"
        "	.word	gUnknown_Debug_845E797\n"
        "	.word	gUnknown_Debug_845E712\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_813C52C()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, r9\n"
        "	mov	r5, r8\n"
        "	push	{r5, r6}\n"
        "	mov	r8, r0\n"
        "	lsl	r5, r1, #0x10\n"
        "	lsr	r0, r5, #0x10\n"
        "	mov	r9, r0\n"
        "	ldr	r6, ._15\n"
        "	ldr	r4, ._15 + 4\n"
        "	sub	r6, r6, r4\n"
        "	mov	r0, r8\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r6, #0\n"
        "	bl	memcpy\n"
        "	ldr	r0, ._15 + 8\n"
        "	sub	r0, r0, r4\n"
        "	add r0, r0, r8\n"
        "	add	r0, r0, #0x3\n"
        "	mov	r1, r9\n"
        "	strb	r1, [r0]\n"
        "	lsr	r5, r5, #0x18\n"
        "	strb	r5, [r0, #0x1]\n"
        "	mov	r0, r8\n"
        "	add	r1, r4, #0\n"
        "	bl	unref_sub_812620C\n"
        "	add	r0, r6, #0\n"
        "	pop	{r3, r4}\n"
        "	mov	r8, r3\n"
        "	mov	r9, r4\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._16:\n"
        "	.align	2, 0\n"
        "._15:\n"
        "	.word	gUnknown_Debug_845E7BB\n"
        "	.word	gUnknown_Debug_845E797\n"
        "	.word	gUnknown_Debug_845E7B5\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C580()
{
    asm(
        "	push	{lr}\n"
        "	mov	r1, #0xd\n"
        "	bl	debug_sub_813C52C\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C58C()
{
    asm(
        "	push	{lr}\n"
        "	mov	r1, #0x4\n"
        "	bl	debug_sub_813C52C\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C598()
{
    asm(
        "	push	{lr}\n"
        "	mov	r1, #0x85\n"
        "	bl	debug_sub_813C52C\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C5A4()
{
    asm(
        "	push	{lr}\n"
        "	ldr	r1, ._17\n"
        "	bl	debug_sub_813C52C\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._18:\n"
        "	.align	2, 0\n"
        "._17:\n"
        "	.word	0x121\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C5B4()
{
    asm(
        "	push	{r4, r5, r6, r7, lr}\n"
        "	add	r4, r0, #0\n"
        "	ldr	r7, ._23\n"
        "	ldr	r0, ._23 + 4\n"
        "	ldr	r1, ._23 + 8\n"
        "	sub	r0, r0, r1\n"
        "	add	r6, r0, r4\n"
        "	ldr	r0, ._23 + 12\n"
        "	sub	r5, r0, r1\n"
        "	ldr	r0, ._23 + 16\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x0\n"
        "	bl	GetEnigmaBerryChecksum\n"
        "	mov	r2, #0x0\n"
        "	ldr	r3, ._23 + 20\n"
        "	mov	r1, #0x0\n"
        "._19:\n"
        "	add	r0, r4, r2\n"
        "	strb	r1, [r0]\n"
        "	add	r2, r2, #0x1\n"
        "	cmp	r2, r3\n"
        "	ble	._19	@cond_branch\n"
        "	mov	r2, #0x0\n"
        "	cmp	r2, r5\n"
        "	bcs	._20	@cond_branch\n"
        "	ldr	r3, ._23 + 8\n"
        "._21:\n"
        "	add	r0, r4, r2\n"
        "	add	r1, r2, r3\n"
        "	ldrb	r1, [r1]\n"
        "	strb	r1, [r0]\n"
        "	add	r2, r2, #0x1\n"
        "	cmp	r2, r5\n"
        "	bcc	._21	@cond_branch\n"
        "._20:\n"
        "	mov	r2, #0x0\n"
        "	ldr	r3, ._23 + 24\n"
        "._22:\n"
        "	add	r0, r6, r2\n"
        "	add	r1, r7, r2\n"
        "	ldrb	r1, [r1]\n"
        "	strb	r1, [r0]\n"
        "	add	r2, r2, #0x1\n"
        "	cmp	r2, r3\n"
        "	bls	._22	@cond_branch\n"
        "	bl	ClearEnigmaBerries\n"
        "	ldr	r1, ._23 + 8\n"
        "	add	r0, r4, #0\n"
        "	bl	unref_sub_81261B4\n"
        "	add	r0, r5, #0\n"
        "	pop	{r4, r5, r6, r7}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._24:\n"
        "	.align	2, 0\n"
        "._23:\n"
        "	.word	gSaveBlock1+0x3160\n"
        "	.word	gUnknown_Debug_845DDD6\n"
        "	.word	gUnknown_Debug_845DDB2\n"
        "	.word	gUnknown_Debug_845E306\n"
        "	.word	Str_842E23C\n"
        "	.word	0xfff\n"
        "	.word	0x52f\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_813C638()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, r8\n"
        "	push	{r6}\n"
        "	add	sp, sp, #0xffffffec\n"
        "	mov	r8, r0\n"
        "	add	r4, r1, #0\n"
        "	add	r5, r2, #0\n"
        "	add	r6, r3, #0\n"
        "	lsl	r4, r4, #0x10\n"
        "	lsr	r4, r4, #0x10\n"
        "	lsl	r5, r5, #0x18\n"
        "	lsr	r5, r5, #0x18\n"
        "	lsl	r6, r6, #0x10\n"
        "	lsr	r6, r6, #0x10\n"
        "	bl	ZeroMonData\n"
        "	mov	r0, #0x0\n"
        "	str	r0, [sp]\n"
        "	str	r0, [sp, #0x4]\n"
        "	mov	r0, #0x1\n"
        "	str	r0, [sp, #0x8]\n"
        "	ldr	r0, ._25\n"
        "	str	r0, [sp, #0xc]\n"
        "	mov	r0, r8\n"
        "	add	r1, r4, #0\n"
        "	add	r2, r5, #0\n"
        "	mov	r3, #0x20\n"
        "	bl	CreateMon\n"
        "	ldr	r2, ._25 + 4\n"
        "	mov	r0, r8\n"
        "	mov	r1, #0x7\n"
        "	bl	SetMonData\n"
        "	ldr	r2, ._25 + 8\n"
        "	mov	r0, r8\n"
        "	mov	r1, #0x2\n"
        "	bl	SetMonData\n"
        "	str	r6, [sp, #0x10]\n"
        "	mov	r0, r8\n"
        "	mov	r1, #0xc\n"
        "	add	r2, sp, #0x10\n"
        "	bl	SetMonData\n"
        "	add	sp, sp, #0x14\n"
        "	pop	{r3}\n"
        "	mov	r8, r3\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._26:\n"
        "	.align	2, 0\n"
        "._25:\n"
        "	.word	0x270f\n"
        "	.word	Str_842E240\n"
        "	.word	Str_842E248\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_813C6AC()
{
    asm(
        "	push	{r4, r5, r6, r7, lr}\n"
        "	mov	r7, r8\n"
        "	push	{r7}\n"
        "	add	sp, sp, #0xfffffff8\n"
        "	add	r6, r0, #0\n"
        "	add	r5, r1, #0\n"
        "	add	r0, r5, #0\n"
        "	bl	ClearMailStruct\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0xc\n"
        "	bl	GetMonData\n"
        "	lsl	r0, r0, #0x10\n"
        "	lsr	r0, r0, #0x10\n"
        "	mov	r8, r0\n"
        "	bl	ItemIsMail\n"
        "	lsl	r0, r0, #0x18\n"
        "	cmp	r0, #0\n"
        "	beq	._27	@cond_branch\n"
        "	add	r4, r5, #0\n"
        "	add	r4, r4, #0x12\n"
        "	add	r7, r5, #0\n"
        "	add	r7, r7, #0x1a\n"
        "	mov	r1, #0x9\n"
        "	add	r0, r5, #0\n"
        "	add	r0, r0, #0x10\n"
        "._28:\n"
        "	strh	r1, [r0]\n"
        "	sub	r1, r1, #0x1\n"
        "	sub	r0, r0, #0x2\n"
        "	cmp	r0, r5\n"
        "	bge	._28	@cond_branch\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0x7\n"
        "	mov	r2, sp\n"
        "	bl	GetMonData\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	mov	r2, #0x8\n"
        "	bl	StringCopyN\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0x1\n"
        "	bl	GetMonData\n"
        "	add	r1, r7, #0\n"
        "	bl	write_word_to_mem\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0xb\n"
        "	bl	GetMonData\n"
        "	add	r4, r0, #0\n"
        "	lsl	r4, r4, #0x10\n"
        "	lsr	r4, r4, #0x10\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0x0\n"
        "	bl	GetMonData\n"
        "	add	r1, r0, #0\n"
        "	add	r0, r4, #0\n"
        "	bl	SpeciesToMailSpecies\n"
        "	strh	r0, [r5, #0x1e]\n"
        "	mov	r0, r8\n"
        "	strh	r0, [r5, #0x20]\n"
        "._27:\n"
        "	add	sp, sp, #0x8\n"
        "	pop	{r3}\n"
        "	mov	r8, r3\n"
        "	pop	{r4, r5, r6, r7}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C740()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, sl\n"
        "	mov	r5, r9\n"
        "	mov	r4, r8\n"
        "	push	{r4, r5, r6}\n"
        "	add	sp, sp, #0xffffffd0\n"
        "	add	r6, r0, #0\n"
        "	ldr	r0, ._29\n"
        "	mov	r8, r0\n"
        "	ldr	r1, ._29 + 4\n"
        "	ldr	r5, ._29 + 8\n"
        "	sub	r1, r1, r0\n"
        "	mov	r9, r1\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, r8\n"
        "	mov	r2, r9\n"
        "	bl	memcpy\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x19\n"
        "	mov	r2, #0x5\n"
        "	mov	r3, #0x0\n"
        "	bl	debug_sub_813C638\n"
        "	add	r4, sp, #0x24\n"
        "	mov	r0, #0x1\n"
        "	mov	sl, r0\n"
        "	mov	r1, sl\n"
        "	strb	r1, [r4]\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x2d\n"
        "	add	r2, r4, #0\n"
        "	bl	SetMonData\n"
        "	mov	r0, #0x3\n"
        "	strb	r0, [r4]\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x20\n"
        "	add	r2, r4, #0\n"
        "	bl	SetMonData\n"
        "	mov	r0, #0xff\n"
        "	strb	r0, [r4]\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x23\n"
        "	add	r2, r4, #0\n"
        "	bl	SetMonData\n"
        "	ldr	r1, ._29 + 12\n"
        "	add	r0, r4, #0\n"
        "	mov	r2, #0xb\n"
        "	bl	StringCopyN\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x2\n"
        "	add	r2, r4, #0\n"
        "	bl	SetMonData\n"
        "	mov	r0, sl\n"
        "	strb	r0, [r4]\n"
        "	add	r0, r5, #0\n"
        "	mov	r1, #0x3\n"
        "	add	r2, r4, #0\n"
        "	bl	SetMonData\n"
        "	ldr	r0, ._29 + 16\n"
        "	add	r0, r6, r0\n"
        "	mov	r1, r8\n"
        "	sub	r0, r0, r1\n"
        "	add	r1, r5, #0\n"
        "	mov	r2, #0x64\n"
        "	bl	memcpy\n"
        "	ldr	r0, ._29 + 20\n"
        "	add	r6, r6, r0\n"
        "	mov	r0, r8\n"
        "	sub	r6, r6, r0\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, sp\n"
        "	mov	r2, #0x24\n"
        "	bl	memcpy\n"
        "	mov	r0, r9\n"
        "	add	sp, sp, #0x30\n"
        "	pop	{r3, r4, r5}\n"
        "	mov	r8, r3\n"
        "	mov	r9, r4\n"
        "	mov	sl, r5\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._30:\n"
        "	.align	2, 0\n"
        "._29:\n"
        "	.word	gUnknown_Debug_845E443\n"
        "	.word	gUnknown_Debug_845E4EF\n"
        "	.word	gEnemyParty\n"
        "	.word	Str_842E238\n"
        "	.word	gUnknown_Debug_845E467\n"
        "	.word	gUnknown_Debug_845E4CB\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C810()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, r8\n"
        "	push	{r6}\n"
        "	add	sp, sp, #0xffffffdc\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._31\n"
        "	ldr	r0, ._31 + 4\n"
        "	ldr	r4, ._31 + 8\n"
        "	sub	r0, r0, r5\n"
        "	mov	r8, r0\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r5, #0\n"
        "	mov	r2, r8\n"
        "	bl	memcpy\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0xc9\n"
        "	mov	r2, #0x15\n"
        "	mov	r3, #0x82\n"
        "	bl	debug_sub_813C638\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	bl	debug_sub_813C6AC\n"
        "	ldr	r0, ._31 + 12\n"
        "	add	r0, r6, r0\n"
        "	sub	r0, r0, r5\n"
        "	add	r1, r4, #0\n"
        "	mov	r2, #0x64\n"
        "	bl	memcpy\n"
        "	ldr	r0, ._31 + 16\n"
        "	add	r0, r6, r0\n"
        "	sub	r0, r0, r5\n"
        "	mov	r1, sp\n"
        "	mov	r2, #0x24\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r5, #0\n"
        "	bl	unref_sub_812620C\n"
        "	mov	r0, r8\n"
        "	add	sp, sp, #0x24\n"
        "	pop	{r3}\n"
        "	mov	r8, r3\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._32:\n"
        "	.align	2, 0\n"
        "._31:\n"
        "	.word	gUnknown_Debug_845E443\n"
        "	.word	gUnknown_Debug_845E4EF\n"
        "	.word	gEnemyParty\n"
        "	.word	gUnknown_Debug_845E467\n"
        "	.word	gUnknown_Debug_845E4CB\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C888()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, r8\n"
        "	push	{r6}\n"
        "	add	sp, sp, #0xffffffdc\n"
        "	add	r6, r0, #0\n"
        "	ldr	r5, ._33\n"
        "	ldr	r0, ._33 + 4\n"
        "	ldr	r4, ._33 + 8\n"
        "	sub	r0, r0, r5\n"
        "	mov	r8, r0\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r5, #0\n"
        "	mov	r2, r8\n"
        "	bl	memcpy\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0xc9\n"
        "	mov	r2, #0x15\n"
        "	mov	r3, #0x82\n"
        "	bl	debug_sub_813C638\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	bl	debug_sub_813C6AC\n"
        "	mov	r0, #0x0\n"
        "	strh	r0, [r4, #0x1c]\n"
        "	ldr	r0, ._33 + 12\n"
        "	add	r0, r6, r0\n"
        "	sub	r0, r0, r5\n"
        "	add	r1, r4, #0\n"
        "	mov	r2, #0x64\n"
        "	bl	memcpy\n"
        "	ldr	r0, ._33 + 16\n"
        "	add	r0, r6, r0\n"
        "	sub	r0, r0, r5\n"
        "	mov	r1, sp\n"
        "	mov	r2, #0x24\n"
        "	bl	memcpy\n"
        "	add	r0, r6, #0\n"
        "	add	r1, r5, #0\n"
        "	bl	unref_sub_812620C\n"
        "	mov	r0, r8\n"
        "	add	sp, sp, #0x24\n"
        "	pop	{r3}\n"
        "	mov	r8, r3\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._34:\n"
        "	.align	2, 0\n"
        "._33:\n"
        "	.word	gUnknown_Debug_845E443\n"
        "	.word	gUnknown_Debug_845E4EF\n"
        "	.word	gEnemyParty\n"
        "	.word	gUnknown_Debug_845E467\n"
        "	.word	gUnknown_Debug_845E4CB\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_813C904()
{
    asm(
        "	push	{r4, lr}\n"
        "	ldr	r4, ._35\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0x5\n"
        "	mov	r2, #0x32\n"
        "	mov	r3, #0xb7\n"
        "	bl	debug_sub_813C638\n"
        "	add	r0, r4, #0\n"
        "	add	r0, r0, #0x64\n"
        "	mov	r1, #0x8\n"
        "	mov	r2, #0x32\n"
        "	mov	r3, #0xc4\n"
        "	bl	debug_sub_813C638\n"
        "	add	r4, r4, #0xc8\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0x2\n"
        "	mov	r2, #0x32\n"
        "	mov	r3, #0x8d\n"
        "	bl	debug_sub_813C638\n"
        "	pop	{r4}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._36:\n"
        "	.align	2, 0\n"
        "._35:\n"
        "	.word	gPlayerParty\n"
        "\n"
    );
}

__attribute__((naked))
int debug_sub_813C93C()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	sp, sp, #0xffffff44\n"
        "	add	r4, r0, #0\n"
        "	ldr	r6, ._37\n"
        "	ldr	r5, ._37 + 4\n"
        "	sub	r5, r5, r6\n"
        "	add	r1, r6, #0\n"
        "	add	r2, r5, #0\n"
        "	bl	memcpy\n"
        "	bl	SavePlayerParty\n"
        "	bl	debug_sub_813C904\n"
        "	ldr	r1, ._37 + 8\n"
        "	ldr	r2, ._37 + 12\n"
        "	mov	r0, sp\n"
        "	bl	debug_sub_8075DB4\n"
        "	bl	LoadPlayerParty\n"
        "	ldr	r0, ._37 + 16\n"
        "	add	r4, r4, r0\n"
        "	sub	r4, r4, r6\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	mov	r2, #0xbc\n"
        "	bl	memcpy\n"
        "	add	r0, r5, #0\n"
        "	add	sp, sp, #0xbc\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._38:\n"
        "	.align	2, 0\n"
        "._37:\n"
        "	.word	gUnknown_Debug_845E4EF\n"
        "	.word	gUnknown_Debug_845E606\n"
        "	.word	Str_842E253+5  @ weird...\n"
        "	.word	0x270f\n"
        "	.word	gUnknown_Debug_845E506\n"
        "\n"
    );
}

#endif

