LilycoveCity_PokemonCenter_1F_Text_189FC9:: @ 8189FC9
	.string "Ich frage mich, wie viele Arten von\n"
	.string "POKéMON es in der Welt wohl gibt?\p"
	.string "Es muss toll sein, die Meere zu über-\n"
	.string "queren und POKéMON mit Leuten zu\l"
	.string "tauschen, die weit weg leben.$"

LilycoveCity_PokemonCenter_1F_Text_18A048:: @ 818A048
	.string "Ich habe von einigen Schurken gehört,\n"
	.string "die POKéMON stehlen und METEORITEN\l"
	.string "klauen.$"

LilycoveCity_PokemonCenter_1F_Text_18A0A1:: @ 818A0A1
	.string "Diese verkommenen Schurken, die\n"
	.string "POKéMON stehlen und METEORITEN\l"
	.string "klauen...\p"
	.string "Ich habe sie in letzter Zeit nicht\n"
	.string "gesehen.$"

UnknownString_818A10A: @ 818A10A
	.string "Ich besorge mir X-ANGRIFF, um meine\n"
	.string "ATTACKEN im Kampf zu verstärken.\p"
	.string "Auf diese Weise gewinne ich garantiert.$"

UnknownString_818A168: @ 818A168
	.string "HYPERHEILER ist etwas teuer, aber sehr\n"
	.string "nützlich.\p"
	.string "Einer davon kann alle Statusprobleme\n"
	.string "eines POKéMON heilen.$"
