PetalburgCity_WallysHouse_EventObjects:: @ 8387114
	object_event 1, EVENT_OBJ_GFX_MAN_3, 0, 3, 4, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, PetalburgCity_WallysHouse_EventScript_1543C4, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_5, 0, 7, 5, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 0, 0, PetalburgCity_WallysHouse_EventScript_154445, 0

PetalburgCity_WallysHouse_MapWarps:: @ 8387144
	warp_def 3, 7, 0, 1, MAP_PETALBURG_CITY
	warp_def 4, 7, 0, 1, MAP_PETALBURG_CITY

PetalburgCity_WallysHouse_MapEvents:: @ 8387154
	map_events PetalburgCity_WallysHouse_EventObjects, PetalburgCity_WallysHouse_MapWarps, 0x0, 0x0
