VictoryRoad_B1F_MapScripts:: @ 815DFB4
	.byte 0

VictoryRoad_B1F_EventScript_15DFB5:: @ 815DFB5
	trainerbattle 0, TRAINER_SAMUEL, 0, VictoryRoad_B1F_Text_197CE9, VictoryRoad_B1F_Text_197D42
	msgbox VictoryRoad_B1F_Text_197D5B, 6
	end

VictoryRoad_B1F_EventScript_15DFCC:: @ 815DFCC
	trainerbattle 0, TRAINER_SHANNON, 0, VictoryRoad_B1F_Text_197D98, VictoryRoad_B1F_Text_197DE8
	msgbox VictoryRoad_B1F_Text_197E13, 6
	end

VictoryRoad_B1F_EventScript_15DFE3:: @ 815DFE3
	trainerbattle 0, TRAINER_MICHELLE, 0, VictoryRoad_B1F_Text_197E5D, VictoryRoad_B1F_Text_197EA6
	msgbox VictoryRoad_B1F_Text_197EB6, 6
	end
