VictoryRoad_B1F_Text_SamuelIntro:: @ 8197CE9
	.string "The thought that I'm getting closer to\n"
	.string "the POKéMON LEAGUE...\p"
	.string "I'm getting stage fright...$"

VictoryRoad_B1F_Text_SamuelDefeat:: @ 8197D42
	.string "I couldn't do a thing...$"

VictoryRoad_B1F_Text_SamuelPostBattle:: @ 8197D5B
	.string "The POKéMON LEAGUE became distant\n"
	.string "again... What a letdown...$"

VictoryRoad_B1F_Text_ShannonIntro:: @ 8197D98
	.string "To win your way through the POKéMON\n"
	.string "LEAGUE, you need the trust of your\l"
	.string "POKéMON.$"

VictoryRoad_B1F_Text_ShannonDefeat:: @ 8197DE8
	.string "Your relationship is based on\n"
	.string "solid trust.$"

VictoryRoad_B1F_Text_ShannonPostBattle:: @ 8197E13
	.string "By being together all the time, trust\n"
	.string "grows between POKéMON and TRAINERS.$"

VictoryRoad_B1F_Text_MichelleIntro:: @ 8197E5D
	.string "This isn't the goal. It's only a place\n"
	.string "on the way to the POKéMON LEAGUE.$"

VictoryRoad_B1F_Text_MichelleDefeat:: @ 8197EA6
	.string "That's the way!$"

VictoryRoad_B1F_Text_MichellePostBattle:: @ 8197EB6
	.string "You'll do fine, for sure!\n"
	.string "Your POKéMON are all eager to go!$"
