MauvilleCity_Mart_Text_ItemsToTemporarilyElevateStats:: @ 81827D3
	.string "There are items that temporarily\n"
	.string "elevate the stats of POKéMON.\p"
	.string "The ones I know you use in battle\n"
	.string "are X ATTACK and X DEFEND...\p"
	.string "I do believe that there are others\n"
	.string "like them.$"

MauvilleCity_Mart_Text_DecisionsDetermineBattle:: @ 818287F
	.string "Use a certain move, or use an item\n"
	.string "instead...\p"
	.string "The TRAINER's decisions determine how\n"
	.string "battles turn out, I think.$"
