LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon:: @ 818C24B
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK, and CALCIUM\n"
	.string "raises SP. ATK.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance:: @ 818C2B5
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon:: @ 818C32E
	.string "I gave a CARBOS to my POKéMON and its\n"
	.string "SPEED went up.$"

LilycoveCity_DepartmentStore_3F_Text_UnusedFloorInfo: @ 818C363
	.string "ESSENTIALS FOR UNBEATABLE TRAINERS\n"
	.string "3F: BATTLE COLLECTION$"
