Route104_PrototypePrettyPetalFlowerShop_EventObjects:: @ 8392080
	object_event 1, EVENT_OBJ_GFX_GIRL_1, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, Route104_PrototypePrettyPetalFlowerShop_EventScript_160DC1, 0

Route104_PrototypePrettyPetalFlowerShop_MapWarps:: @ 8392098
	warp_def 2, 8, 0, 0, MAP_ROUTE104_PROTOTYPE
	warp_def 3, 8, 0, 0, MAP_ROUTE104_PROTOTYPE

Route104_PrototypePrettyPetalFlowerShop_MapEvents:: @ 83920A8
	map_events Route104_PrototypePrettyPetalFlowerShop_EventObjects, Route104_PrototypePrettyPetalFlowerShop_MapWarps, 0x0, 0x0
