gEasyChatGroupName_Pokemon:: @ 842C7DB
	.string "POKéMON$"

gEasyChatGroupName_Trainer:: @ 842C7E3
	.string "TRAINER$"

gEasyChatGroupName_Status:: @ 842C7EB
	.string "STATUS$"

gEasyChatGroupName_Battle:: @ 842C7F2
	.string "BATTLE$"

gEasyChatGroupName_Greetings:: @ 842C7F9
	.string "GREETINGS$"

gEasyChatGroupName_People:: @ 842C803
	.string "PEOPLE$"

gEasyChatGroupName_Voices:: @ 842C80A
	.string "VOICES$"

gEasyChatGroupName_Speech:: @ 842C811
	.string "SPEECH$"

gEasyChatGroupName_Endings:: @ 842C818
	.string "ENDINGS$"

gEasyChatGroupName_Feelings:: @ 842C820
	.string "FEELINGS$"

gEasyChatGroupName_Conditions:: @ 842C829
	.string "CONDITIONS$"

gEasyChatGroupName_Actions:: @ 842C834
	.string "ACTIONS$"

gEasyChatGroupName_Lifestyle:: @ 842C83C
	.string "LIFESTYLE$"

gEasyChatGroupName_Hobbies:: @ 842C846
	.string "HOBBIES$"

gEasyChatGroupName_Time:: @ 842C84E
	.string "TIME$"

gEasyChatGroupName_Misc:: @ 842C853
	.string "MISC.$"

gEasyChatGroupName_Adjectives:: @ 842C859
	.string "ADJECTIVES$"

gEasyChatGroupName_Events:: @ 842C864
	.string "EVENT.$"

gEasyChatGroupName_Move1:: @ 842C86B
	.string "MOVE 1$"

gEasyChatGroupName_Move2:: @ 842C872
	.string "MOVE 2$"

gEasyChatGroupName_TrendySaying:: @ 842C879
	.string "TRENDY SAYING$"

gEasyChatGroupName_Pokemon2:: @ 842C887
	.string "POKéMON2$"
