MauvilleCity_GameCorner_Text_ThisIsMauvilleGameCorner:: @ 8181C35
	.string "Willkommen in unserer SPIELHALLE.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseForCoins:: @ 8181C53
	.string "Okay, du möchtest MÜNZEN für die\n"
	.string "Spiele haben?\p"
	.string "Aber du hast keinen MÜNZKORB für die\n"
	.string "MÜNZEN.$"

MauvilleCity_GameCorner_Text_WereYouLookingForCoins:: @ 8181CB4
	.string "Suchst du nach MÜNZEN?\p"
	.string "Das macht ¥1000 für 50 MÜNZEN.\n"
	.string "Möchtest du welche haben?$"

MauvilleCity_GameCorner_Text_ThankYouHereAreYourCoins:: @ 8181CFE
	.string "Vielen Dank!\n"
	.string "Hier sind deine MÜNZEN!$"

MauvilleCity_GameCorner_Text_DontHaveEnoughMoney:: @ 8181D28
	.string "Ähm... Es scheint, du hast nicht\n"
	.string "genügend Geld dabei...$"

MauvilleCity_GameCorner_Text_CoinCaseIsFull:: @ 8181D57
	.string "Oh?\n"
	.string "Dein MÜNZKORB ist voll.$"

MauvilleCity_GameCorner_Text_DontNeedCoinsThen:: @ 8181D73
	.string "Oh... Dann brauchst du keine MÜNZEN?\n"
	.string "Viel Glück bei deinem Abenteuer!$"

UnknownString_8181DB2: @ 8181DB2
	.string "Das macht ¥1000 für 50 MÜNZEN.\n"
	.string "Möchtest du welche haben?$"

MauvilleCity_GameCorner_Text_ExchangeCoinsForPrizes:: @ 8181DE1
	.string "Willkommen.\p"
	.string "Hier kannst du deine MÜNZEN gegen\n"
	.string "Preise eintauschen.$"

MauvilleCity_GameCorner_Text_WhichPrize:: @ 8181E17
	.string "Welchen Preis hättest du gerne?$"

MauvilleCity_GameCorner_Text_SoYourChoiceIsX:: @ 8181E33
	.string "Du möchtest also {STR_VAR_1}?$"

MauvilleCity_GameCorner_Text_SendToYourHomePC:: @ 8181E49
	.string "Danke!\n"
	.string "Wir senden das auf deinen PC.$"

MauvilleCity_GameCorner_Text_NotEnoughCoins:: @ 8181E76
	.string "Du hast nicht genügend MÜNZEN.$"

UnknownString_8181E93: @ 8181E93
	.string "Du hast nicht genügend Platz, um\n"
	.string "{STR_VAR_1} zu lagern.$"

MauvilleCity_GameCorner_Text_OhIsThatSo:: @ 8181EC2
	.string "Oh, wirklich?\n"
	.string "Du musst einige MÜNZEN sparen, bevor\l"
	.string "du wiederkommst.$"

MauvilleCity_GameCorner_Text_HereYouGo:: @ 8181F08
	.string "Bitte schön!$"

UnknownString_8181F15: @ 8181F15
	.string "Oh, du kannst nicht mehr tragen.$"

MauvilleCity_GameCorner_Text_GotTwoOfSameDollWantOne:: @ 8181F3D
	.string "Ich habe mich vertan und zweimal die\n"
	.string "gleiche PUPPE genommen.\p"
	.string "Möchtest du eine davon haben?$"

MauvilleCity_GameCorner_Text_HereYouGo2:: @ 8181F89
	.string "Bitte schön!$"

MauvilleCity_GameCorner_Text_YouWantItButNotNow:: @ 8181F97
	.string "Bitte?\n"
	.string "Du möchtest sie, aber nicht jetzt???$"

MauvilleCity_GameCorner_Text_DontBeNegative:: @ 8181FBC
	.string "Oh, sei doch nicht so negativ drauf!\n"
	.string "Du kannst sie wirklich gerne haben!$"

MauvilleCity_GameCorner_Text_CantWinJackpot:: @ 8181FE9
	.string "Es gibt einen Preis, den ich haben\n"
	.string "möchte, aber ich kann den Jackpot\l"
	.string "nicht knacken.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseGoNextDoor:: @ 818201E
	.string "Hey, Kindchen, wenn du hier spielen\n"
	.string "willst, brauchst du einen MÜNZKORB.\p"
	.string "Ich glaube, die junge Dame nebenan hat\n"
	.string "einen. Besuche sie mal!$"

MauvilleCity_GameCorner_Text_LuckOnlyLastSoLongTakeCoins:: @ 818208E
	.string "Mein Glück wird nicht immer anhalten.\n"
	.string "Das ist zu viel für mich.\l"
	.string "Hier, nimm die MÜNZEN!$"

MauvilleCity_GameCorner_Text_MauvilleSomethingForEveryone:: @ 81820DD
	.string "Immer wenn ich in MALVENFROH CITY bin,\n"
	.string "gehe ich in die SPIELHALLE.\p"
	.string "MALVENFROH CITY bringt mir einfach\n"
	.string "Glück.$"

MauvilleCity_GameCorner_Text_RouletteTablesDifferentRates:: @ 8182120
	.string "Beim ROULETTE gibt es verschiedene\n"
	.string "Einsatzhöhen.\p"
	.string "Überprüf deine MÜNZEN, bevor du dich\n"
	.string "für einen Tisch entscheidest.$"

MauvilleCity_GameCorner_Text_EasyToLoseTrackOfTime:: @ 818217C
	.string "Hier kann man leicht die Zeit vergessen.\n"
	.string "Ich sollte wieder an die Arbeit gehen.$"

MauvilleCity_GameCorner_Text_CoinsAreNeededToPlay:: @ 81821C1
	.string "MÜNZEN werden gebraucht, um hier in der\n"
	.string "SPIELHALLE spielen zu können.$"

MauvilleCity_GameCorner_Text_RouletteOnlyLuck:: @ 81821F3
	.string "Dieses ROULETTE-Dingens...\n"
	.string "Es ist ziemlich anstrengend.\p"
	.string "Ich versuche, zu gewinnen. Aber ich\n"
	.string "verliere immer. Doch ich gebe nicht auf.$"

MauvilleCity_GameCorner_Text_UpTo3CoinsCanBeUsed:: @ 8182241
	.string "Bis zu drei MÜNZEN können an den EIN-\n"
	.string "ARMIGEN BANDITEN eingesetzt werden.\p"
	.string "Je mehr Münzen du einsetzt, desto\n"
	.string "höher ist deine Chance auf den Jackpot.$"

MauvilleCity_GameCorner_Text_DifficultToStopOn7:: @ 8182272
	.string "Kannst du es genau bei “7” stoppen?\p"
	.string "Wenn es bei “7” stoppt,\n"
	.string "während ein REEL TIME gespielt wird,\l"
	.string "erhältst du Extra-MÜNZEN.$"

MauvilleCity_GameCorner_Text_HeresSomeSlotsInfo:: @ 81822F4
	.string "Ich kann dir einige nützliche Tipps zu\n"
	.string "den EINARMIGEN BANDITEN geben.\p"
	.string "Je mehr Blitze du anhältst, desto größer\n"
	.string "die Chance auf ein REEL TIME, eine\l"
	.string "Glücksrunde!\p"
	.string "In einem Spiel mit fünf möglichen\n"
	.string "Glücksrunden...\p"
	.string "Ist es möglich, vier reguläre Boni und\n"
	.string "dann einen Big Bonus zu gewinnen.\p"
	.string "Der Big Bonus bringt 660 MÜNZEN,\n"
	.string "aber der ist sehr schwer zu gewinnen.$"

MauvilleCity_GameCorner_Text_CantPlayWithNoCoinCase:: @ 8182420
	.string "Du kannst ohne MÜNZKORB nicht spielen.$"
