EverGrandeCity_ChampionsRoom_Text_IntroSpeech:: @ 8190F9C
	.string "TROY: Willkommen, {PLAYER}{KUN}!\p"
	.string "Ich habe schon darauf gewartet, dich\n"
	.string "eines Tages hier zu sehen.\p"
	.string "Und? Was hast du alles auf deiner Reise\n"
	.string "mit den POKéMON erlebt?\p"
	.string "Was hast du gefühlt, als du auf so viele\n"
	.string "andere TRAINER getroffen bist?\p"
	.string "Was wurde in dir erweckt? Ich will, dass\n"
	.string "du all das im Kampf gegen mich einsetzt!\p"
	.string "Nun, zeig es mir!$"

EverGrandeCity_ChampionsRoom_Text_Defeat:: @ 81910A0
	.string "Ich, der CHAMP, habe verloren...\p"
	.string "Dir gebührt alle Ehre, {PLAYER}{KUN}!\p"
	.string "Du bist wahrhaft ein edler POKéMON-\n"
	.string "TRAINER!$"

EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech:: @ 81910FE
	.string "TROY: Herzlichen Glückwunsch!\p"
	.string "Die Gefühle, die du deinen POKéMON\n"
	.string "entgegenbringst...\p"
	.string "Und die POKéMON, die auf diese Gefühle\n"
	.string "mit all ihrer Kraft antworten...\p"
	.string "Sie werden eins und bringen eine weit\n"
	.string "größere Stärke hervor.\p"
	.string "Und so gehört der Sieg heute dir!\p"
	.string "Du bist mit Recht HOENNS neuer...$"

EverGrandeCity_ChampionsRoom_Text_MayAdvice:: @ 8191225
	.string "MAIKE: {PLAYER}{KUN}!\p"
	.string "Ich muss dir unbedingt einen Rat geben,\n"
	.string "bevor du gegen den CHAMP antrittst!$"

EverGrandeCity_ChampionsRoom_Text_MayItsAlreadyOver:: @ 8191268
	.string "MAIKE: Wie? Waswaswas?\p"
	.string "{PLAYER}{KUN}...\n"
	.string "Das kann nicht sein...\l"
	.string "Es ist schon vorbei?$"

EverGrandeCity_ChampionsRoom_Text_BrendanAdvice:: @ 81912B3
	.string "BRIX: {PLAYER}!\p"
	.string "Möchtest du nicht ein paar Tipps, bevor\n"
	.string "du den CHAMP herausforderst?$"

EverGrandeCity_ChampionsRoom_Text_BrendanYouveWon:: @ 8191305
	.string "BRIX: {PLAYER}!\p"
	.string "Willst du mir etwa sagen...\n"
	.string "Du hast den CHAMP besiegt?!?!?!$"

EverGrandeCity_ChampionsRoom_Text_BirchArriveRatePokedex:: @ 819134D
	.string "PROF. BIRK: Siehst du?\n"
	.string "Was habe ich dir gesagt, {RIVAL}?\p"
	.string "Ich wusste, du brauchst dir keine\n"
	.string "Sorgen um {PLAYER}{KUN} zu machen!\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "{PLAYER}{KUN}, du hast es geschafft.\p"
	.string "Als ich hörte, dass du deinen Vater in\n"
	.string "der ARENA von BLÜTENBURG CITY\p"
	.string "besiegt hast, wusste ich, dass du eine\n"
	.string "Chance hast...\p"
	.string "Aber, dass du dann sogar CHAMP\n"
	.string "geworden bist!\p"
	.string "Oh, ja!\p"
	.string "Was ist aus deinem POKéDEX geworden?\n"
	.string "Lass mich mal sehen...$"

EverGrandeCity_ChampionsRoom_Text_BirchCongratulations:: @ 81914C6
	.string "PROF. BIRK: Also, dann sage ich:\n"
	.string "Herzlichen Glückwunsch!\p"
	.string "Nun kannst du mit Stolz den letzten\n"
	.string "Raum betreten!$"

EverGrandeCity_ChampionsRoom_Text_StevenComeWithMe:: @ 8191512
	.string "TROY: {PLAYER}{KUN}...\p"
	.string "Nein! Neuer CHAMP!\p"
	.string "Komm mit mir.$"

EverGrandeCity_ChampionsRoom_Text_StevenWaitOutside:: @ 8191546
	.string "TROY: Tut mir Leid, aber...\p"
	.string "Diesen Raum dürfen nur TRAINER\n"
	.string "betreten, die CHAMPS geworden sind.\p"
	.string "Warte bitte draußen mit dem PROFESSOR.$"

EverGrandeCity_ChampionsRoom_Text_MayCongratulations:: @ 81915D7
	.string "MAIKE: Grummel...\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ich mache nur Spaß! Ist schon okay!\n"
	.string "So sind die Regeln!\p"
	.string "{PLAYER}{KUN}!\n"
	.string "Ehrlich. Herzlichen Glückwunsch!$"

EverGrandeCity_ChampionsRoom_Text_BrendanCongratulations:: @ 8191675
	.string "BRIX: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Na, wenn es die Regeln so bestimmen...\p"
	.string "{PLAYER}, das ist dein Tag!\n"
	.string "Herzlichen Glückwunsch!$"
