FortreeCity_Gym_Text_GymGuideAdvice:: @ 818589C
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "Die LEITERIN der ARENA von BAUMHAUSEN\n"
	.string "CITY, WIBKE, ist eine Meisterin der\l"
	.string "FLUG-POKéMON.\p"
	.string "Sie wartet hinten in der ARENA auf dich,\n"
	.string "hinter den Drehtüren.\p"
	.string "Sie wartet auf neue Herausforderer,\n"
	.string "denen sie die Flügel stutzen kann!\p"
	.string "Okay, dann viel Glück!$"

FortreeCity_Gym_Text_GymGuidePostVictory:: @ 8185994
	.string "Du hast es geschafft!\n"
	.string "Du hast Startfreigabe!$"

FortreeCity_Gym_Text_JaredIntro:: @ 81859B9
	.string "Bewundere den eleganten Kampfstil der\n"
	.string "VOGEL-POKéMON!$"

FortreeCity_Gym_Text_JaredDefeat:: @ 81859EA
	.string "Du...\n"
	.string "Du bist stark...$"

FortreeCity_Gym_Text_JaredPostBattle:: @ 8185A02
	.string "Ein TRAINER muss clever genug sein, mit\n"
	.string "den Wendungen im Kampf fertig zu\l"
	.string "werden.\p"
	.string "Mal sehen, ob du clever genug bist, bis\n"
	.string "zu unserer LEITERIN vorzudringen.$"

FortreeCity_Gym_Text_WillIntro:: @ 8185A7F
	.string "Liebhaber von VOGEL-POKéMON streben\n"
	.string "danach, dieser ARENA beizutreten.\p"
	.string "Als Mitglied der ARENA von BAUMHAUSEN\n"
	.string "CITY darf ich nicht verlieren!$"

FortreeCity_Gym_Text_WillDefeat:: @ 8185AEC
	.string "Das war doch etwas zu schwer für mich\n"
	.string "zu tragen...$"

FortreeCity_Gym_Text_WillPostBattle:: @ 8185B18
	.string "Die Welt ist groß und es gibt zahlreiche\n"
	.string "starke TRAINER.\p"
	.string "Ich werde weiter trainieren und so\n"
	.string "immer stärker werden!$"

FortreeCity_Gym_Text_TerrellIntro:: @ 8185B8D
	.string "Es gibt keinen Grund, dass WIBKE,\n"
	.string "unsere ARENALEITERIN, sich mit dir\l"
	.string "abgibt!\p"
	.string "Ich bin schon stark genug für dich!$"

FortreeCity_Gym_Text_TerrellDefeat:: @ 8185BEB
	.string "WIBKE... Ich...\n"
	.string "Ich habe verlooooren!$"

FortreeCity_Gym_Text_TerrellPostBattle:: @ 8185C00
	.string "WIBKE ist süß, aber auch stark.\n"
	.string "Sie ist die ultimative LEITERIN!\p"
	.string "Hups... Wie peinlich. Ich werde nicht rot!$"

FortreeCity_Gym_Text_KyleeIntro:: @ 8185C45
	.string "WIBKE hat mich persönlich geschult!\n"
	.string "Du wirst kein leichtes Spiel haben!$"

FortreeCity_Gym_Text_KyleeDefeat:: @ 8185C7C
	.string "Ich wurde geschlagen...$"

FortreeCity_Gym_Text_KyleePostBattle:: @ 8185C8C
	.string "Dank WIBKE leben die Einwohner von\n"
	.string "BAUMHAUSEN CITY ohne Furcht.$"

FortreeCity_Gym_Text_WinonaIntro:: @ 8185CCB
	.string "Ich bin WIBKE, die LEITERIN der ARENA\n"
	.string "von BAUMHAUSEN CITY.\p"
	.string "Ich wurde das mit Hilfe meiner VOGEL-\n"
	.string "POKéMON und habe den Himmel berührt.\p"
	.string "Wie anstrengend der Kampf auch war, wir\n"
	.string "haben mit Grazie gewonnen...\p"
	.string "Werde Zeuge der eleganten Choreo-\n"
	.string "graphie meiner VOGEL-POKéMON!$"

FortreeCity_Gym_Text_WinonaDefeat:: @ 8185DBA
	.string "Ich habe noch nie einen TRAINER ge-\n"
	.string "sehen, der seine POKéMON mit mehr\l"
	.string "Grazie trainiert als ich...\p"
	.string "In Anbetracht deiner Fähigkeiten\n"
	.string "überreiche ich dir diesen ARENAORDEN.$"

FortreeCity_Gym_Text_ReceivedFeatherBadge:: @ 8185E48
	.string "{PLAYER} erhält den FEDERORDEN von\n"
	.string "WIBKE.$"

FortreeCity_Gym_Text_ExplainFeatherBadgeTakeThis:: @ 8185E73
	.string "Mit dem FEDERORDEN gehorchen dir alle\n"
	.string "POKéMON bis Lv. 70, auch die, die du\l"
	.string "durch Tausch bekommen hast.\p"
	.string "Außerdem kannst du nun die VM FLIEGEN\n"
	.string "außerhalb eines Kampfes einsetzen.\p"
	.string "Und dies...\n"
	.string "Dies ist ein Geschenk von mir.$"

FortreeCity_Gym_Text_ExplainAerialAce:: @ 8185F4A
	.string "TM40 enthält AERO-ASS.\p"
	.string "Diese Geschwindigkeit...\n"
	.string "Kein POKéMON kann ihr entgehen.$"

FortreeCity_Gym_Text_WinonaPostBattle:: @ 8185F98
	.string "Auch wenn ich gegen dich verloren habe,\n"
	.string "gehört meine Liebe den VOGEL-POKéMON.$"

FortreeCity_Gym_Text_GymStatue:: @ 8185FD5
	.string "POKéMON ARENA von BAUMHAUSEN CITY$"

FortreeCity_Gym_Text_GymStatueCertified:: @ 8185FEE
	.string "POKéMON ARENA von BAUMHAUSEN CITY\p"
	.string "WIBKES ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
