MtChimney_Text_195760:: @ 8195760
	.string "LAVAKEKSE sind die Spezialität am\n"
	.string "SCHLOTBERG.\p"
	.string "Nimm einen. Er kostet nur ¥200.$"

MtChimney_Text_1957A9:: @ 81957A9
	.string "Vielen Dank, Herzchen!$"

MtChimney_Text_1957BA:: @ 81957BA
	.string "Oh je. Du kannst nichts kaufen, wenn\n"
	.string "du nicht genug Geld bei dir hast.$"

MtChimney_Text_1957F7:: @ 81957F7
	.string "Oh, ist gut.$"

MtChimney_Text_195806:: @ 8195806
	.string "Ein METEORIT steckt in dieser\n"
	.string "mysteriösen Vorrichtung...\p"
	.string "Die Maschine scheint den METEORITEN\n"
	.string "mit Energie zu versorgen.$"

MtChimney_Text_195870:: @ 8195870
	.string "Ein METEORIT steckt in dieser\n"
	.string "mysteriösen Vorrichtung...\p"
	.string "Willst du den METEORITEN nehmen?$"

MtChimney_Text_1958C6:: @ 81958C6
	.string "{PLAYER} entfernt den METEORITEN aus\n"
	.string "der mysteriösen Vorrichtung.$"

MtChimney_Text_1958FC:: @ 81958FC
	.string "{PLAYER} fasst den METEORITEN nicht an.$"

MtChimney_Text_195920:: @ 8195920
	.string "Diese mysteriöse Vorrichtung...\n"
	.string "Sie reagiert in keinster Weise.$"

MtChimney_Text_19595C:: @ 819595C
	.string "{DOWN_ARROW} STEILPASS\n"
	.string "BAD LAVASTADT GERADEAUS$"

MtChimney_Text_19597F:: @ 819597F
	.string "Ich war bei den Heißen Quellen und habe\n"
	.string "meine müden Knochen erfrischt.\l"
	.string "Jetzt fühle ich mich richtig stark!$"

MtChimney_Text_1959D8:: @ 81959D8
	.string "Oh, du meine Güte!\n"
	.string "Wer bist du denn?!?$"

MtChimney_Text_195A04:: @ 8195A04
	.string "Nun, ich habe verloren. Ich darf mich\n"
	.string "nun nicht mehr EXPERTE nennen, oder?$"

MtChimney_Text_195A45:: @ 8195A45
	.string "Wenn du in deinem Herzen Platz für deine\n"
	.string "POKéMON hast, dann kannst du auch\l"
	.string "große Dinge erreichen.$"

MtChimney_Text_195AAD:: @ 8195AAD
	.string "Oh, du meine Güte!\n"
	.string "Wer bist du denn!$"

MtChimney_Text_195AD9:: @ 8195AD9
	.string "Vielleicht schlägt dein Herz im Gleich-\n"
	.string "klang mit den POKéMON.$"

MtChimney_Text_195B1C:: @ 8195B1C
	.string "Ich habe Feuer in mir, Baby.\n"
	.string "Ich halt’s nicht aus! Ich muss kämpfen!$"

MtChimney_Text_195B5F:: @ 8195B5F
	.string "Oh, was für ein kochend heißer Kampf!$"

MtChimney_Text_195B84:: @ 8195B84
	.string "Die Hitze vom SCHLOTBERG bringt mein\n"
	.string "Feuer in Gang.$"

MtChimney_Text_195BB2:: @ 8195BB2
	.string "Endlich bin ich am SCHLOTBERG ange-\n"
	.string "kommen. Jetzt will ich kämpfen!!!$"

MtChimney_Text_195BF9:: @ 8195BF9
	.string "Wie du kämpfst...\n"
	.string "Als würde der SCHLOTBERG ausbrechen!$"

MtChimney_Text_195C31:: @ 8195C31
	.string "Wie ich schon sagte, endlich bin ich am\n"
	.string "SCHLOTBERG. Wäre doch blödsinnig, wenn\l"
	.string "ich nur zum Sightseeing hier wäre...\p"
	.string "Ich will ein bisschen kämpfen und KEKSE\n"
	.string "als Andenken kaufen.$"

MtChimney_Text_195CD8:: @ 8195CD8
	.string "Seit ich in den Heißen Quellen gebadet\n"
	.string "habe, fühle ich mich großartig!\l"
	.string "Ich bin sicher, ich werde gewinnen!$"

MtChimney_Text_195D2F:: @ 8195D2F
	.string "Huaah!\n"
	.string "Außerhalb des Wassers ist es saukalt.$"

MtChimney_Text_195D5C:: @ 8195D5C
	.string "Ich werde mich wieder in die Heiße\n"
	.string "Quelle setzen. Kommst du mit?\p"
	.string "Kleiner Scherz am Rande... Hähähä.$"
