DewfordTown_Gym_Text_174D98:: @ 8174D98
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "FAUSTAUHAVENS ARENALEITER KAMILLO\n"
	.string "besitzt KAMPF-POKéMON.\p"
	.string "Wenn du dort NORMAL-POKéMON antreten\n"
	.string "lässt, sind Probleme vorprogrammiert!\p"
	.string "KAMPF-POKéMON schlagen die NORMALEN\n"
	.string "POKéMON einfach nieder. Pass gut auf!\p"
	.string "Und das Schlimme ist: Die ARENA ist\n"
	.string "dunkel wie die Tiefsee!\p"
	.string "Aber mit jedem TRAINER, den du auf dem\n"
	.string "Weg zum ARENALEITER besiegst, wird sie\l"
	.string "heller!\p"
	.string "Also, dann leg mal los!$"

DewfordTown_Gym_Text_174F1E:: @ 8174F1E
	.string "Huuh! Das ist mir hier aber schon zu hell!\p"
	.string "Deine Zukunft wird strahlend hell sein!$"

DewfordTown_Gym_Text_174F61:: @ 8174F61
	.string "Die Macht bestimmt alles!\n"
	.string "Komm schon!$"

DewfordTown_Gym_Text_174F7A:: @ 8174F7A
	.string "Nicht genug Macht...$"

DewfordTown_Gym_Text_174F8E:: @ 8174F8E
	.string "Gegen dein Talent ist meine Macht\n"
	.string "machtlos. Deine Technik ist super!$"

DewfordTown_Gym_Text_174FCE:: @ 8174FCE
	.string "Man muss doch KAMILLO nicht mit so\n"
	.string "etwas Nichtigem belästigen!\p"
	.string "Ich mache dich fertig!$"

DewfordTown_Gym_Text_175009:: @ 8175009
	.string "Aber... Wie...?\n"
	.string "Wie konnte ich nur so schnell verlieren?$"

DewfordTown_Gym_Text_175031:: @ 8175031
	.string "Ich werde diese Niederlage nicht ab-\n"
	.string "haken. Sie wird mich beim Training\l"
	.string "motivieren!\p"
	.string "Eines Tages werde ich auch ein\n"
	.string "ARENALEITER sein!\p"
	.string "Nein! Ich werde der CHAMP der\n"
	.string "POKéMON LIGA!$"

DewfordTown_Gym_Text_1750C9:: @ 81750C9
	.string "Du forderst mich heraus? Dann wundere\n"
	.string "dich nicht, wenn du weinst wie ein Baby!$"

DewfordTown_Gym_Text_175104:: @ 8175104
	.string "Waaaaahaaaaaa!\n"
	.string "Schluchz! Schnief! Ich habe verloooren!$"

DewfordTown_Gym_Text_175117:: @ 8175117
	.string "Ich kämpfe im Dunkeln, das macht mich\n"
	.string "mutiger und trainiert mein Herz.\p"
	.string "Weil es hier so dunkel ist, habe ich noch\n"
	.string "nie das Gesicht von KAMILLO gesehen.$"

DewfordTown_Gym_Text_175182:: @ 8175182
	.string "Ich bin KAMILLO!\n"
	.string "Der ARENALEITER von FAUSTAUHAVEN!\p"
	.string "Ich habe die wilden Strudel dieser\n"
	.string "Gegend gemeistert und bin in dieser\l"
	.string "pechschwarzen Höhle stark geworden.\p"
	.string "Du willst mich wirklich herausfordern?\n"
	.string "Dann zeig mir, woraus du gemacht bist!$"

DewfordTown_Gym_Text_175246:: @ 8175246
	.string "Huihuihui! Du hast eine größere Welle\n"
	.string "produziert, als ich dir zugetraut hätte.\p"
	.string "Du hast mich absaufen lassen!\p"
	.string "Okay, du hast mich erwischt!\n"
	.string "Nimm den ORDEN dieser ARENA!$"

DewfordTown_Gym_Text_1752BB:: @ 81752BB
	.string "{PLAYER} erhält den KNÖCHELORDEN von\n"
	.string "KAMILLO.$"

DewfordTown_Gym_Text_1752E6:: @ 81752E6
	.string "Dank des KNÖCHELORDENS werden dir alle\n"
	.string "POKéMON bis Level 30 gehorchen, auch\l"
	.string "die, die du durch Tausch erhalten hast.\p"
	.string "Und du kannst die VM BLITZ auch\n"
	.string "außerhalb eines Kampfes anwenden.\p"
	.string "Und wenn du magst, kannst du auch diese\n"
	.string "TECHNISCHE MASCHINE anwenden.$"

DewfordTown_Gym_Text_1753BF:: @ 81753BF
	.string "Die TM08 enthält PROTZER.\p"
	.string "Diese Attacke hebt den Status des\n"
	.string "ANGRIFFS und der VERTEIDIGUNG.$"

DewfordTown_Gym_Text_175412:: @ 8175412
	.string "Ich sehe in dir ein Talent, das eines\n"
	.string "Tages zu einer riesigen Welle wird und\l"
	.string "einen Sturm des Erstaunens bei anderen\l"
	.string "TRAINERN entfachen wird!$"

DewfordTown_Gym_Text_175477:: @ 8175477
	.string "POKéMON ARENA von FAUSTAUHAVEN$"

DewfordTown_Gym_Text_175490:: @ 8175490
	.string "POKéMON ARENA von FAUSTAUHAVEN\p"
	.string "KAMILLOS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
