Route134_EventObjects:: @ 838548C
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 52, 9, 1, MOVEMENT_TYPE_WALK_SEQUENCE_UP_RIGHT_DOWN_LEFT, 3, 5, 1, 2, Route134_EventScript_1525C4, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 45, 5, 1, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 1, 3, Route134_EventScript_1525DB, 0
	object_event 3, EVENT_OBJ_GFX_MAN_4, 0, 41, 23, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 1, Route134_EventScript_152609, 0
	object_event 4, EVENT_OBJ_GFX_MAN_6, 0, 65, 14, 3, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 0, 0, 1, 2, Route134_EventScript_1525F2, 0
	object_event 5, EVENT_OBJ_GFX_BLACK_BELT, 0, 56, 16, 3, MOVEMENT_TYPE_WALK_LEFT_AND_RIGHT, 10, 0, 1, 3, Route134_EventScript_152620, 0

Route134_MapEvents:: @ 8385504
	map_events Route134_EventObjects, 0x0, 0x0, 0x0
