PacifidlogTown_House3_EventObjects:: @ 8387000
	object_event 1, EVENT_OBJ_GFX_GIRL_2, 0, 3, 5, 3, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 0, 0, 0, 0, PacifidlogTown_House3_EventScript_154342, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_5, 0, 4, 2, 3, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 0, 0, PacifidlogTown_House3_EventScript_15429E, 0

PacifidlogTown_House3_MapWarps:: @ 8387030
	warp_def 4, 8, 0, 3, MAP_PACIFIDLOG_TOWN
	warp_def 5, 8, 0, 3, MAP_PACIFIDLOG_TOWN

PacifidlogTown_House3_MapEvents:: @ 8387040
	map_events PacifidlogTown_House3_EventObjects, PacifidlogTown_House3_MapWarps, 0x0, 0x0
