PacifidlogTown_House3_Text_WillingToTradeIt:: @ 817940E
	.string "Hello, TRAINER. Would you do me a favor\n"
	.string "and trade POKéMON with me?\p"
	.string "Living in PACIFIDLOG, I can only catch\n"
	.string "certain kinds of POKéMON.\p"
	.string "{STR_VAR_1}? Do you have one?\n"
	.string "I'll trade you my {STR_VAR_2} for it.$"

PacifidlogTown_House3_Text_MonIsSoFluffy:: @ 81794C4
	.string "Wow!\n"
	.string "This {STR_VAR_1} is so fluffy!$"

PacifidlogTown_House3_Text_ThatsNoMon:: @ 81794DF
	.string "That's no {STR_VAR_1}.$"

PacifidlogTown_House3_Text_ImDisappointed:: @ 81794ED
	.string "I'm a little disappointed...$"

PacifidlogTown_House3_Text_NowWereFriends:: @ 817950A
	.string "Since we traded, you and me,\n"
	.string "we're friends, aren't we?$"

PacifidlogTown_House3_Text_IsThatAPokedex:: @ 8179541
	.string "Is that a POKéDEX?\p"
	.string "Did you get to meet a lot of different\n"
	.string "POKéMON?\p"
	.string "I wish I was like you.$"
