gEasyChatGroupWords_People: @ 83DC85A
	.string "FEIND$"
	.string "ICH$"
	.string "DU$"
	.string "DEINE$"
	.string "DEIN$"
	.string "DEINER$"
	.string "DU BIST$"
	.string "DU HAST$"
	.string "MUTTER$"
	.string "GROSSVATER$"
	.string "ONKEL$"
	.string "VATER$"
	.string "JUNGE$"
	.string "ERWACHSENER$"
	.string "BRUDER$"
	.string "SCHWESTER$"
	.string "GROSSMUTTER$"
	.string "TANTE$"
	.string "ELTERN$"
	.string "MAN$"
	.string "MICH$"
	.string "MÄDCHEN$"
	.string "DICH$"
	.string "FAMILIE$"
	.string "IHR$"
	.string "IHM$"
	.string "ER$"
	.string "ORT$"
	.string "TOCHTER$"
	.string "SEIN$"
	.string "ER IST$"
	.string "SIND NICHT$"
	.string "GESCHWISTER$"
	.string "KINDCHEN$"
	.string "KINDER$"
	.string "HERR$"
	.string "FRAU$"
	.string "MIR$"
	.string "ICH WAR$"
	.string "ZU MIR$"
	.string "MEIN$"
	.string "ICH BIN$"
	.string "ICH HABE$"
	.string "WER$"
	.string "JEMAND$"
	.string "MEINE$"
	.string "FÜR WEN$"
	.string "WESSEN$"
	.string "WER IST$"
	.string "DAS IST$"
	.string "DAME$"
	.string "FREUND$"
	.string "VERBÜNDETER$"
	.string "PERSON$"
	.string "TYPE$"
	.string "IHNEN$"
	.string "SIE WAREN$"
	.string "FÜR SIE$"
	.string "EUCH$"
	.string "SIE SIND$"
	.string "SIE HABEN$"
	.string "WIR$"
	.string "WAREN$"
	.string "FÜR UNS$"
	.string "UNSER$"
	.string "WIR SIND$"
	.string "RIVALE$"
	.string "WIR HABEN$"
	.string "SIE KONNTEN$"
	.string "SIE$"
	.string "SIE WAR$"
	.string "FÜR ALLE$"
	.string "EURE$"
	.string "SIE IST$"
	.string "SIE HATTE$"
	.string "$"
