EverGrandeCity_PokemonLeague_1F_Text_MustHaveAllGymBadges:: @ 81916FD
	.string "Ab hier haben nur die TRAINER, die alle\n"
	.string "ORDEN der ARENEN erhalten haben,\l"
	.string "Zutritt.\p"
	.string "TRAINER, lass uns sicherstellen, dass\n"
	.string "du auch alle ORDEN hast.$"

EverGrandeCity_PokemonLeague_1F_Text_HaventObtainedAllBadges:: @ 819179C
	.string "Du hast noch nicht alle ORDEN erhalten.\p"
	.string "Wenn du zur POKéMON LIGA willst,\n"
	.string "musst du alle ORDEN vorweisen können.$"

EverGrandeCity_PokemonLeague_1F_Text_GoForth:: @ 8191804
	.string "TRAINER! Glaube an dich und deine\n"
	.string "POKéMON und gehe weiter!$"
