PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon:: @ 817959B
	.string "Die Menschen sagen, sie hätten ein \n"
	.string "POKéMON über HOENN FLIEGEN sehen.\p"
	.string "FLIEGT es die ganze Zeit über herum?\n"
	.string "Muss es sich nicht ausruhen?$"

PacifidlogTown_House4_Text_SkyPokemon:: @ 817961F
	.string "Ein Himmels-POKéMON!\n"
	.string "Ein Himmels-POKéMON!$"

PacifidlogTown_House4_Text_WhereDidYouComeFrom:: @ 817963D
	.string "Woher kommst du?$"

PacifidlogTown_House4_Text_YesTown:: @ 8179656
	.string "Ja?\n"
	.string "JA-Stadt???\p"
	.string "Davon habe ich ja noch nie gehört!$"

PacifidlogTown_House4_Text_YouHaveToComeFromSomewhere:: @ 817968C
	.string "Nein? Das ergibt doch gar keinen Sinn.\n"
	.string "Du musst doch von irgendwo herkommen!\p"
	.string "Oh! Warte! Du willst doch nicht etwa be-\n"
	.string "haupten, du wärest in den Tiefen des\l"
	.string "Meeres geboren???$"
