Route117_PokemonDayCare_EventObjects:: @ 838B9F8
	object_event 1, EVENT_OBJ_GFX_OLD_WOMAN_2, 0, 2, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, Route117_PokemonDayCare_EventScript_1B2327, 0

Route117_PokemonDayCare_MapWarps:: @ 838BA10
	warp_def 2, 8, 0, 0, MAP_ROUTE117
	warp_def 3, 8, 0, 0, MAP_ROUTE117

Route117_PokemonDayCare_MapEvents:: @ 838BA20
	map_events Route117_PokemonDayCare_EventObjects, Route117_PokemonDayCare_MapWarps, 0x0, 0x0
