PetalburgCity_House2_EventObjects:: @ 8387498
	object_event 1, EVENT_OBJ_GFX_WOMAN_2, 0, 2, 5, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, PetalburgCity_House2_EventScript_1551F2, 0
	object_event 2, EVENT_OBJ_GFX_SCHOOL_KID_M, 0, 7, 5, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, PetalburgCity_House2_EventScript_1551FB, 0

PetalburgCity_House2_MapWarps:: @ 83874C8
	warp_def 3, 7, 0, 4, MAP_PETALBURG_CITY
	warp_def 4, 7, 0, 4, MAP_PETALBURG_CITY

PetalburgCity_House2_MapEvents:: @ 83874D8
	map_events PetalburgCity_House2_EventObjects, PetalburgCity_House2_MapWarps, 0x0, 0x0
