PetalburgCity_House2_Text_NormanBecameGymLeader:: @ 817BC4F
	.string "NORMAN became our town's new GYM\n"
	.string "LEADER.\p"
	.string "I think he called his family over from\n"
	.string "the JOHTO region.$"

PetalburgCity_House2_Text_BattledNormanOnce:: @ 817BCB1
	.string "I battled NORMAN once, but, whew,\n"
	.string "he was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he\n"
	.string "lives for POKéMON.$"
