FortreeCity_House3_Text_186624:: @ 8186624
	.string "Da wir gerade vom POKéDEX reden... Ich\n"
	.string "erinnere mich...\p"
	.string "Ich habe diesen TRAINER, TROY,\n"
	.string "getroffen, als ich seltene Steine\l"
	.string "suchte.\p"
	.string "Oh Junge, der hatte vielleicht\n"
	.string "interessante POKéMON bei sich!\p"
	.string "Die waren nicht nur selten, sondern\n"
	.string "auch ausgesprochen gut trainiert!\p"
	.string "Er ist bestimmt stärker als die ARENA-\n"
	.string "LEITERIN in diesem Ort...$"

FortreeCity_House3_Text_186745:: @ 8186745
	.string "Was ist das da? Was hast du da?\p"
	.string "... ... ... ... ... ...\p"
	.string "Oh, das ist also ein POKéDEX?\n"
	.string "Der ist aber wirklich klasse!$"
