EverGrandeCity_PhoebesRoom_EventObjects:: @ 838B280
	object_event 1, EVENT_OBJ_GFX_PHOEBE, 0, 6, 5, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, EverGrandeCity_PhoebesRoom_EventScript_15B630, 0

EverGrandeCity_PhoebesRoom_MapWarps:: @ 838B298
	warp_def 6, 13, 3, 1, MAP_EVER_GRANDE_CITY_CORRIDOR1
	warp_def 6, 2, 0, 0, MAP_EVER_GRANDE_CITY_CORRIDOR2

EverGrandeCity_PhoebesRoom_MapEvents:: @ 838B2A8
	map_events EverGrandeCity_PhoebesRoom_EventObjects, EverGrandeCity_PhoebesRoom_MapWarps, 0x0, 0x0
