ClosedSootopolisDoorText: @ 8169690
	.string "Die Tür ist zu.$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "Wer bist du denn wohl?\p"
	.string "Dies ist die URZEITHÖHLE.\p"
	.string "Die Geister der POKéMON, zur Ruhe\n"
	.string "gebettet am PYROBERG, erwachen\l"
	.string "hier zum Leben, sagt man.\p"
	.string "Bitte verlasse diesen Ort.$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "Im Meer tauchen. Treppenstufen auf und\n"
	.string "ab rennen...\p"
	.string "Wenn du in diesem Ort lebst, wirst du\n"
	.string "körperlich fit.$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "Ich... Ich war noch nie außerhalb der\n"
	.string "Stadt.\p"
	.string "Ich frage mich, wie die Welt hinter\n"
	.string "diesem Horizont aussieht?$"

SootopolisCity_Text_169813:: @ 8169813
	.string "Hm! Du bist den ganzen Weg nach\n"
	.string "XENEROVILLE gekommen? Du bist\l"
	.string "kein normaler Tourist.\p"
	.string "Aber das macht dich auch nicht zu einem\n"
	.string "außergewöhnlichen Touristen.$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "XENEROVILLE entwickelte sich im Krater\n"
	.string "eines Vulkans.\p"
	.string "Wenn du in den Himmel schaust, kannst\n"
	.string "du den Rand des Kraters über dir\l"
	.string "erkennen. Der Himmel wird zum Kreis.\p"
	.string "Aber das macht den Himmel über\n"
	.string "XENEROVILLE zum schönsten Himmel.$"

SootopolisCity_Text_169988:: @ 8169988
	.string "TROY: {PLAYER}{KUN}, du bist auch hier?\n"
	.string "Bei diesem schrecklichen Regen...\p"
	.string "Oh, ja, kannst du verstehen, was mein\n"
	.string "Freund gerade sagt?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "Mein Name ist WASSILI.\n"
	.string "Ich bin der hiesige ARENALEITER.\p"
	.string "Ich bin auch damit beauftragt, die\n"
	.string "URZEITHÖHLE zu schützen.\p"
	.string "Diese Regenschauer werden durch eine\n"
	.string "Kraft in der Höhle verursacht.$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "Das... Das ist die BLAUE KUGEL.\p"
	.string "Ich verstehe.\n"
	.string "Folge mir.$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "TROY: Dieser Regen...\p"
	.string "Menschen und POKéMON brauchen\n"
	.string "Wasser zum Leben...\p"
	.string "Aber warum verursacht dieser Regen\n"
	.string "so viele Probleme?\p"
	.string "Immer mehr Regenwolken werden sich\n"
	.string "über XENEROVILLE bilden und sich über\l"
	.string "die ganze HOENN-Region ausbreiten.$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "WASSILI: Die URZEITHÖHLE ist dort\n"
	.string "drüben.\p"
	.string "Niemandem in XENEROVILLE ist es\n"
	.string "erlaubt, die URZEITHÖHLE zu betreten.\p"
	.string "Aber du musst hineingehen.\n"
	.string "Zusammen mit der BLAUEN KUGEL.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "TROY: {PLAYER}{KUN}, ich hätte nie ver-\n"
	.string "mutet, dass du die BLAUE KUGEL bei dir\l"
	.string "hast.\p"
	.string "Dir wird nichts passieren. Mit deinen\n"
	.string "POKéMON an deiner Seite schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "WASSILI: Du musst deine BLAUE KUGEL\n"
	.string "mitnehmen.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der HÖHLE erwartet...$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "TROY: Dir wird nichts passieren.\n"
	.string "Mit deinen POKéMON an deiner Seite\l"
	.string "schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "TROY: {PLAYER}{KUN}, du bist auch hier?\n"
	.string "Bei diesem heißen Sonnenschein...\p"
	.string "Oh, ja, kannst du verstehen, was mein\n"
	.string "Freund gerade sagt?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "Mein Name ist WASSILI.\n"
	.string "Ich bin der hiesige ARENALEITER.\p"
	.string "Ich bin auch damit beauftragt, die\n"
	.string "URZEITHÖHLE zu schützen.\p"
	.string "Dieser Sonnenschein wird durch eine\n"
	.string "Kraft in der Höhle verursacht.$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "Das... Das ist die ROTE KUGEL.\p"
	.string "Ich verstehe.\n"
	.string "Folge mir.$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "TROY: Dieser Sonnenschein...\p"
	.string "Menschen und POKéMON brauchen\n"
	.string "Sonnenlicht zum Leben...\p"
	.string "Aber warum verursacht dieses Licht\n"
	.string "so viele Probleme?\p"
	.string "Die Sonnenstrahlen über XENEROVILLE\n"
	.string "werden immer intensiver und bald\l"
	.string "wird es in ganz HOENN zu heiß.\p"
	.string "Und wenn das passiert...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "WASSILI: Die URZEITHÖHLE ist dort\n"
	.string "drüben.\p"
	.string "Niemandem in XENEROVILLE ist es\n"
	.string "erlaubt, die URZEITHÖHLE zu betreten.\p"
	.string "Aber du musst hineingehen.\n"
	.string "Zusammen mit der ROTEN KUGEL.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "TROY: {PLAYER}{KUN}, ich hätte nie ver-\n"
	.string "mutet, dass du die ROTE KUGEL bei dir\l"
	.string "hast.\p"
	.string "Dir wird nichts passieren. Mit deinen\n"
	.string "POKéMON an deiner Seite schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "WASSILI: Du musst deine ROTE KUGEL\n"
	.string "mitnehmen.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "TROY: Dir wird nichts passieren. Mit\n"
	.string "deinen POKéMON an deiner Seite\l"
	.string "schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "Die Legende, die der alte Mann am PYRO-\n"
	.string "BERG erzählt hat... war kein Märchen.$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "Das natürliche Gleichgewicht von HOENN\n"
	.string "verändert sich dramatisch...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "TROY: {PLAYER}{KUN}, dir verdanken\n"
	.string "wir alles.\p"
	.string "Der Himmel über XENEROVILLE ist\n"
	.string "wieder normal. Dafür dankt dir auch\l"
	.string "WASSILI.\p"
	.string "Und genau dieser WASSILI\n"
	.string "erwartet dich dort drinnen.\p"
	.string "Er ist stark. Aber auf dem Weg, auf dem\n"
	.string "du dich jetzt befindest, solltest du\l"
	.string "keine Probleme haben, ihn zu besiegen.\p"
	.string "Gib dein Bestes.$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "Alles Leben beginnt in der URZEITHÖHLE\n"
	.string "und endet am PYROBERG...\p"
	.string "Woher kommen die Menschen und\n"
	.string "POKéMON? Wohin gehen wir?$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "Lass mich raten! Du wirst WASSILI\n"
	.string "herausfordern?!?\p"
	.string "Wirklich?\n"
	.string "Du bist wirklich mutig!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "Lass mich raten! Du hast WASSILI\n"
	.string "besiegt!?! Wirklich!?!\p"
	.string "Dann werde ich vielleicht dein Fan!$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "Hm! Du bist den ganzen Weg nach\n"
	.string "XENEROVILLE gekommen? Du bist\l"
	.string "kein gewöhnlicher Tourist.\p"
	.string "Aber das macht dich auch nicht zu einem\n"
	.string "außergewöhnlichen Touristen.$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "Ein Stück des Nachthimmels, umgeben\n"
	.string "vom Rund des Vulkankraters...\p"
	.string "Und in diesem runden Stück Himmel\n"
	.string "strahlen und blinken die Sterne, als\l"
	.string "wären sie lebendig. Ich liebe das...$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "Huch! Wo ist mein Haus?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "POKéMON ARENA von XENEROVILLE\n"
	.string "LEITER: WASSILI\p"
	.string "“Künstler und Liebhaber des WASSERS.”$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "XENEROVILLE\p"
	.string "“Die mystische Stadt, in der die\n"
	.string "Geschichte stillsteht.”$"
