PetalburgWoods_Text_194D71:: @ 8194D71
	.string "Hmmm...\n"
	.string "Kein Einziges zu finden.$"

PetalburgWoods_Text_194D92:: @ 8194D92
	.string "Hallo, du hast nicht zufällig einige\n"
	.string "POKéMON namens KNILZ hier\p"
	.string "gesehen? Ich liebe diese POKéMON.$"

PetalburgWoods_Text_194DED:: @ 8194DED
	.string "Ich wollte dich eigentlich aus dem\n"
	.string "Hinterhalt angreifen, aber du trödelst\l"
	.string "wohl auf ewig im BLÜTENBURGWALD\l"
	.string "herum, oder?\p"
	.string "Das Warten machte mich ganz krank.\n"
	.string "Also, hier bin ich.$"

PetalburgWoods_Text_194E6B:: @ 8194E6B
	.string "He, du! FORSCHER von DEVON!\p"
	.string "Gib sofort die Papiere her!$"

PetalburgWoods_Text_194E9A:: @ 8194E9A
	.string "Attackeee!\p"
	.string "Du bist ein POKéMON-TRAINER, oder?\n"
	.string "Du musst mir bitte helfen!$"

PetalburgWoods_Text_194EE8:: @ 8194EE8
	.string "Huch. Was machst du da eigentlich???\n"
	.string "Was?!? Du schützt ihn???\p"
	.string "Niemand, der sich TEAM {EVIL_TEAM} in den Weg\n"
	.string "stellt, kann auf Gnade hoffen. Niemand!\p"
	.string "Los, kämpfe gegen uns!$"

PetalburgWoods_Text_194F83:: @ 8194F83
	.string "Du hast mich geleimt! Du bist stark!$"

PetalburgWoods_Text_194FA4:: @ 8194FA4
	.string "Grrr... Du hast vielleicht Nerven, dich\n"
	.string "mit TEAM {EVIL_TEAM} anzulegen!\l"
	.string "Los, kämpfen wir noch einmal!\p"
	.string "Hm, das würde ich jetzt zu gerne sagen,\n"
	.string "aber ich habe keine POKéMON mehr...\p"
	.string "Außerdem sind wir, TEAM {EVIL_TEAM}, auf dem\n"
	.string "Weg nach METAROST CITY.\p"
	.string "Für heute lasse ich dich gehen.$"

PetalburgWoods_Text_19507E:: @ 819507E
	.string "Huuuh...\n"
	.string "Das war aber mehr als knapp!\p"
	.string "Dank dir konnte er mir diese\n"
	.string "wichtigen Papiere nicht rauben.\p"
	.string "Ich weiß! Ich gebe dir diesen\n"
	.string "SUPERBALL als Dankeschön!$"

PetalburgWoods_Text_19510A:: @ 819510A
	.string "Hat dieser Schuft von TEAM {EVIL_TEAM} nicht\n"
	.string "gesagt, dass sie irgendetwas in\l"
	.string "METAROST CITY erledigen wollen?$"

PetalburgWoods_Text_195153:: @ 8195153
	.string "Oh oh! Das ist ein Notfall!\n"
	.string "Ich darf keine Zeit verlieren!$"

PetalburgWoods_Text_195182:: @ 8195182
	.string "Du bist mit Items überfrachtet.\n"
	.string "Ich kann dir den SUPERBALL nicht geben.$"

PetalburgWoods_Text_1951BE:: @ 81951BE
	.string "Ich habe eine Menge POKéMON gefangen!\p"
	.string "Los, los, los!\n"
	.string "Mein KÄFER-POKéMON Team!$"

PetalburgWoods_Text_195202:: @ 8195202
	.string "Ich habe all diese POKéMON, aber ich\n"
	.string "konnte doch nicht gewinnen...$"

PetalburgWoods_Text_195232:: @ 8195232
	.string "Ich habe eine Menge POKéMON gefangen.\n"
	.string "Nun habe ich keine POKéBÄLLE mehr.$"

PetalburgWoods_Text_19526A:: @ 819526A
	.string "Wenn du ein KÄFER-POKéMON mit zur\n"
	.string "Schule bringst, bist du sofort beliebt.$"

PetalburgWoods_Text_1952AE:: @ 81952AE
	.string "Wenn ich verliere, kann ich nicht\n"
	.string "beliebt werden.$"

PetalburgWoods_Text_1952CC:: @ 81952CC
	.string "Hast du ein großes KÄFER-POKéMON,\n"
	.string "werden die Leute dich respektieren.$"

PetalburgWoods_Text_195306:: @ 8195306
	.string "Meine KÄFER-POKéMON sind gewachsen.\n"
	.string "Ich werde wieder beliebt sein.$"

PetalburgWoods_Text_195338:: @ 8195338
	.string "Ich werde nie beliebt, wenn ich\n"
	.string "immer verliere.$"

PetalburgWoods_Text_195356:: @ 8195356
	.string "Du wirst beliebt, wenn du starke\n"
	.string "POKéMON besitzt, oder?\l"
	.string "Daher trainiere ich bis zum Umfallen.$"

PetalburgWoods_Text_1953AC:: @ 81953AC
	.string "Hey, du!\n"
	.string "Geht es deinen POKéMON gut?\p"
	.string "Wenn deine POKéMON schwach sind und\n"
	.string "du Kämpfe vermeiden willst, solltest du\l"
	.string "dich von hohem Gras fernhalten.$"

PetalburgWoods_Text_19542B:: @ 819542B
	.string "Manchmal liegen auf dem Boden Dinge, die\n"
	.string "einem auf Anhieb gar nicht auffallen.\p"
	.string "Daher schaue ich mich bei jedem Schritt\n"
	.string "sorgfältig um.$"

PetalburgWoods_Text_19549E:: @ 819549E
	.string "Oh, hübsch! Das ist der ORDEN\n"
	.string "der ARENA in METAROST CITY!\p"
	.string "Du siehst wie ein TRAINER aus. Dann\n"
	.string "musst du dieses Item ausprobieren.$"

PetalburgWoods_Text_195503:: @ 8195503
	.string "Das ist WUNDERSAAT.\n"
	.string "Wenn ein POKéMON sie trägt, werden\l"
	.string "die PFLANZEN-Attacken stärker.\p"
	.string "Neben der WUNDERSAAT gibt es bestimmt\n"
	.string "noch andere nützliche Items, die von\l"
	.string "POKéMON getragen werden können.$"

PetalburgWoods_Text_1955B0:: @ 81955B0
	.string "TIPPS für TRAINER\p"
	.string "Jedes POKéMON, das am Kampf teilnimmt,\n"
	.string "erhält ERFAHRUNGSPUNKTE, auch wenn es\l"
	.string "nur ganz kurz dabei ist.\p"
	.string "Setze eines deiner schwachen POKéMON\n"
	.string "daher an die Spitze der Liste.\p"
	.string "Sobald der Kampf beginnt, wechselst du\n"
	.string "es aus. Es wird E-Punkte bekommen und\l"
	.string "bleibt trotzdem immer unbeschadet.$"

PetalburgWoods_Text_1956A6:: @ 81956A6
	.string "TIPPS für TRAINER\p"
	.string "Neben den Kraftpunkten (KP) besitzt\n"
	.string "ein POKéMON auch Angriffspunkte (AP),\l"
	.string "die für die Attacken im Kampf gebraucht\l"
	.string "werden.\p"
	.string "Wenn ein POKéMON keine AP mehr besitzt,\n"
	.string "muss es in ein POKéMON-CENTER gebracht\l"
	.string "werden.$"
