AbandonedShip_CaptainsOffice_Text_198C85:: @ 8198C85
	.string "Ich untersuche das Schiff im Auftrag\n"
	.string "von KAPT. BRIGG.\p"
	.string "Er hat mich auch beauftragt, einen\n"
	.string "SCANNER zu finden, aber ich habe \l"
	.string "ihn noch nicht gefunden.$"

AbandonedShip_CaptainsOffice_Text_198D00:: @ 8198D00
	.string "Oh! Das ist der SCANNER!\p"
	.string "Würdest du den bitte für mich zu\n"
	.string "KAPT. BRIGG bringen? Das wäre nett.\p"
	.string "Ich möchte das Schiff noch weiter\n"
	.string "untersuchen.$"

AbandonedShip_CaptainsOffice_Text_198D7B:: @ 8198D7B
	.string "Dieses Schiff heißt MS CACTUS. Es\n"
	.string "scheint aus einer früheren Epoche zu\l"
	.string "stammen.$"
