DewfordTown_Text_16B23B:: @ 816B23B
	.string "FAUSTAUHAVEN ist eine kleine\n"
	.string "Inselgemeinschaft. Wenn hier etwas in\l"
	.string "Mode kommt, will jeder es haben.$"

DewfordTown_Text_16B2A7:: @ 816B2A7
	.string "FAUSTAUHAVEN\n"
	.string "“Eine kleine Insel im blauen Meer.”$"

DewfordTown_Text_16B2D5:: @ 816B2D5
	.string "POKéMON ARENA von FAUSTAUHAVEN\n"
	.string "LEITER: KAMILLO\l"
	.string "“Eine große Welle des Kampfes!”$"

DewfordTown_Text_16B317:: @ 816B317
	.string "FAUSTAUHAVEN HALLE\n"
	.string "“Die Informationsbörse für jedermann!”$"

Route104_Text_16B347:: @ 816B347
	.string "MR. BRACK: Ahoi! Wir haben in\n"
	.string "FAUSTAUHAVEN Anker geworfen.\p"
	.string "Ich vermute, du wirst diesen BRIEF\n"
	.string "jetzt diesem... TROY bringen!?!$"

DewfordTown_Text_16B3BC:: @ 816B3BC
	.string "MR. BRACK: Hast du den BRIEF\n"
	.string "überbracht?\p"
	.string "Oder meinst du, wir müssen zurück\n"
	.string "nach BLÜTENBURG CITY segeln?$"

DewfordTown_Text_16B417:: @ 816B417
	.string "MR. BRACK: BLÜTENBURG CITY...\n"
	.string "In Ordnung.\p"
	.string "Anker gelichtet!\n"
	.string "PECKO, mein Schatz, wir setzen Segel!$"

DewfordTown_Text_16B471:: @ 816B471
	.string "MR. BRACK: Dann bring den BRIEF zu\n"
	.string "seinem Empfänger. Ich warte hier.$"

Route104_Text_16B4B5:: @ 816B4B5
Route109_Text_16B4B5:: @ 816B4B5
	.string "MR. BRACK: Ahoi! Wir haben in\n"
	.string "FAUSTAUHAVEN Anker geworfen!\p"
	.string "Komm, wenn wir wieder Segel\n"
	.string "setzen sollen.$"

DewfordTown_Text_16B522:: @ 816B522
	.string "MR. BRACK: Ahoi! Für dich segle ich zu\n"
	.string "jeder Zeit überall hin.\p"
	.string "Nun, mein Freund, wohin soll es gehen?$"

DewfordTown_Text_16B57D:: @ 816B57D
	.string "MR. BRACK: BLÜTENBURG CITY soll es sein?\p"
	.string "Anker gelichtet!\n"
	.string "PECKO, mein Schatz, wir setzen Segel!$"

DewfordTown_Text_16B5D2:: @ 816B5D2
	.string "MR. BRACK: GRAPHITPORT CITY soll\n"
	.string "es sein?\p"
	.string "Anker gelichtet!\n"
	.string "PECKO, mein Schatz, wir setzen Segel!$"

DewfordTown_Text_16B627:: @ 816B627
	.string "MR. BRACK: Sag mir, wenn wir wieder\n"
	.string "Segel setzen sollen.$"

DewfordTown_Text_16B665:: @ 816B665
	.string "Dies ist ein berühmter Angelplatz.\n"
	.string "Hast du Lust zu angeln?$"

DewfordTown_Text_16B6A8:: @ 816B6A8
	.string "Ich habe dir genau zugehört und mir\n"
	.string "gefällt, was du gesagt hast!\p"
	.string "Ich werde dir eine meiner ANGELN\n"
	.string "geben.$"

DewfordTown_Text_16B6F9:: @ 816B6F9
	.string "Und, als kleine Zugabe, gebe ich dir noch\n"
	.string "einige Tipps zum Angeln!\p"
	.string "Schau dir zuerst das Wasser an und dann\n"
	.string "benutze deine ANGEL.\p"
	.string "Konzentriere dich... Wenn etwas anbeißt,\n"
	.string "hol die ANGEL ein.\p"
	.string "Manchmal kannst du mit einem Mal etwas\n"
	.string "Großes fangen, manchmal musst du\l"
	.string "immer wieder kurz die ANGEL anheben,\l"
	.string "um etwas an Land zu ziehen.$"

DewfordTown_Text_16B828:: @ 816B828
	.string "Oh, wirklich?\n"
	.string "Das ist aber schade.$"

DewfordTown_Text_16B84E:: @ 816B84E
	.string "Yeah!\n"
	.string "Wie steht’s mit deinen Angelkünsten?$"

DewfordTown_Text_16B866:: @ 816B866
	.string "Also, wenn das stimmt... Das wäre\n"
	.string "großartig! Petri heil!$"

DewfordTown_Text_16B89A:: @ 816B89A
	.string "Hey, lass den Kopf nicht hängen! Ich\n"
	.string "gebe dir einige Tipps zum Angeln!\p"
	.string "Schau dir zuerst das Wasser an\n"
	.string "und dann benutze deine ANGEL.\p"
	.string "Konzentriere dich... Wenn etwas\n"
	.string "anbeißt, hol die ANGEL ein.\p"
	.string "Manchmal kannst du mit einem Mal etwas\n"
	.string "Großes fangen, manchmal musst du\l"
	.string "immer wieder kurz die ANGEL anheben,\l"
	.string "um etwas an Land zu ziehen.$"

DewfordTown_Text_16B9CE:: @ 816B9CE
	.string "Ich mag, was hip, aufregend und modern\n"
	.string "ist. So etwas probiere ich immer aus.\p"
	.string "Hast du schon einmal was von\n"
	.string "“{STR_VAR_1}” gehört?\p"
	.string "Wusste ich es doch!\n"
	.string "Natürlich hast du schon davon gehört!\p"
	.string "Oh, meine Güte,\n"
	.string "“{STR_VAR_1}”...\l"
	.string "Das ist das Coolste überhaupt!\p"
	.string "Wo immer du auch herkommst,\n"
	.string "“{STR_VAR_1}”\l"
	.string "ist das Aufregendste überhaupt!$"

DewfordTown_Text_16BADC:: @ 816BADC
	.string "Wie bitte?\n"
	.string "Es ist nicht hip und aufregend?\p"
	.string "Nun, hey, dann verrate mir aber, was\n"
	.string "wirklich cool und “in” ist?$"

DewfordTown_Text_16BB44:: @ 816BB44
	.string "Was?\n"
	.string "“{STR_VAR_2}”?\p"
	.string "... ...\p"
	.string "...Hm... Äh... Yeah! Das stimmt!\n"
	.string "Yeah, ich wusste das! Schon lange!\p"
	.string "Natürlich weiß ich das!\n"
	.string "“{STR_VAR_2}”, richtig?\p"
	.string "Yeah, das ist es, das ist es!\n"
	.string "Ist “{STR_VAR_2}”\l"
	.string "nicht das Coolste?\p"
	.string "Das ist die hippeste Sache überhaupt.\n"
	.string "Und du dachtest, ich wüsste das nicht?\p"
	.string "“{STR_VAR_1}”...\n"
	.string "Das ist doch schon uralt und unmodern.\p"
	.string "“{STR_VAR_2}” ist das,\n"
	.string "was vital und zeitgemäß ist!$"

DewfordTown_Text_16BCA2:: @ 816BCA2
	.string "Hmm...\n"
	.string "“{STR_VAR_2}”, oder?\p"
	.string "Aber ich persönlich finde,\n"
	.string "“{STR_VAR_1}”\l"
	.string "ist das Coolste überhaupt!$"

DewfordTown_Text_16BCE9:: @ 816BCE9
	.string "Wenn du irgendetwas über neue, auf-\n"
	.string "regende Sachen hörst, erzähl mir davon!$"

DewfordTown_Text_16BD37:: @ 816BD37
	.string "Yeah, absolut richtig!\p"
	.string "“{STR_VAR_1}” ist die\n"
	.string "Definition von “in”.$"

DewfordTown_Text_16BD79: @ 816BD79
	.string "“{STR_VAR_2}” ist\n"
	.string "die Spitze der Coolness im Moment.$"
