FortreeCity_DecorationShop_Text_186A61:: @ 8186A61
	.string "Die Artikel, die du hier kaufst, werden\n"
	.string "sofort auf deinen PC gesendet.\p"
	.string "Das ist großartig! Ich wünschte, ich\n"
	.string "könnte mich so auch nach Hause\l"
	.string "senden lassen.$"

FortreeCity_DecorationShop_Text_186AD6:: @ 8186AD6
	.string "Ich kaufe mir einen schönen Tisch, auf\n"
	.string "den ich meine PUPPEN setze.\p"
	.string "Wenn ich das nicht tue, werden meine\n"
	.string "PUPPEN schmutzig, wenn ich damit meine\l"
	.string "GEHEIMBASIS dekoriere.$"
