JaggedPass_Text_195DAC:: @ 8195DAC
	.string "SCHLOTBERG STEILPASS...\p"
	.string "Davon habe ich immer geträumt, wenn ich\n"
	.string "in den Bergen unterwegs war.\p"
	.string "Zerklüftete Massive...\n"
	.string "Das bringt meine Seele zum Erbeben.$"

JaggedPass_Text_195E27:: @ 8195E27
	.string "Verlieren ist bitter.$"

JaggedPass_Text_195E3E:: @ 8195E3E
	.string "Ja, ich bin im Umgang mit POKéMON nicht\n"
	.string "gerade talentiert.\p"
	.string "Aber wenn es um die Leidenschaft für\n"
	.string "die Berge geht, stecke ich dich locker\l"
	.string "in die Tasche!$"

JaggedPass_Text_195E9E:: @ 8195E9E
	.string "Dich habe ich hier noch nie gesehen.\n"
	.string "Dieser Platz eignet sich nicht für ein\l"
	.string "Picknick.$"

JaggedPass_Text_195EDF:: @ 8195EDF
	.string "Oooh, nein!\n"
	.string "Das liegt am Boden. Er ist zu uneben!$"

JaggedPass_Text_195F04:: @ 8195F04
	.string "Stell dir mal vor!\p"
	.string "Einige fahren tatsächlich mit ihren\n"
	.string "Fahrrädern diesen zerklüfteten Pass\l"
	.string "hinauf.$"

JaggedPass_Text_195F58:: @ 8195F58
	.string "Picknicke machen überall und immer Spaß.\n"
	.string "Und PKMN leisten mir dabei Gesellschaft!$"

JaggedPass_Text_195F8C:: @ 8195F8C
	.string "Ich habe nur verloren, weil der Boden\n"
	.string "wirklich sehr uneben ist.$"

JaggedPass_Text_195FB9:: @ 8195FB9
	.string "Ich werde meine Niederlage einfach\n"
	.string "vergessen und mit dem Rad den Pass\l"
	.string "entlangdüsen.$"

JaggedPass_Text_195FF2:: @ 8195FF2
	.string "Der STEILPASS ist sehr schwer zu Fuß\n"
	.string "zu meistern. Aber ein guter Ort zum\l"
	.string "Trainieren.$"

JaggedPass_Text_196032:: @ 8196032
	.string "Schon vorbei? Ich habe überhaupt\n"
	.string "keinen sicheren Stand gehabt.$"

JaggedPass_Text_196077:: @ 8196077
	.string "Wenn ich ein KUNSTRAD hätte, könnte\n"
	.string "ich die Abhänge einfach überspringen.$"

JaggedPass_Text_1960AA:: @ 81960AA
	.string "Ich habe mich an die Unebenheiten ge-\n"
	.string "wöhnt. Ich singe beim Klettern.$"

JaggedPass_Text_1960E2:: @ 81960E2
	.string "Auf diesem unebenen Boden ist es wirk-\n"
	.string "lich nicht leicht, gut zu kämpfen.$"

JaggedPass_Text_196118:: @ 8196118
	.string "Ich sollte mir ein KUNSTRAD von RADLA\n"
	.string "in MALVENFROH CITY besorgen...$"
