LilycoveCity_MoveDeletersHouse_Text_18B622:: @ 818B622
	.string "Äh...\n"
	.string "Oh, ja. Ich bin der ATTACKEN-VERLERNER.\p"
	.string "Ich sorge dafür, dass die POKéMON ihre\n"
	.string "Attacken vergessen.\p"
	.string "Möchtest du, dass ich dir helfe?$"

LilycoveCity_MoveDeletersHouse_Text_18B68C:: @ 818B68C
	.string "Welches POKéMON soll eine Attacke\n"
	.string "vergessen?$"

LilycoveCity_MoveDeletersHouse_Text_18B6B0:: @ 818B6B0
	.string "Welche Attacke soll vergessen werden?$"

LilycoveCity_MoveDeletersHouse_Text_18B6D0:: @ 818B6D0
	.string "{STR_VAR_1} kennt scheinbar nur eine\n"
	.string "einzige Attacke...$"

LilycoveCity_MoveDeletersHouse_Text_18B6F2:: @ 818B6F2
	.string "Hm! {STR_VAR_2} von {STR_VAR_1}?\n"
	.string "Diese Attacke soll vergessen werden?$"

LilycoveCity_MoveDeletersHouse_Text_18B71E:: @ 818B71E
	.string "Das klappte doch perfekt!\p"
	.string "{STR_VAR_1} hat {STR_VAR_2}\n"
	.string "komplett vergessen.$"

LilycoveCity_MoveDeletersHouse_Text_18B757:: @ 818B757
	.string "Komm wieder, wenn es andere Attacken\n"
	.string "gibt, die vergessen werden sollen.$"

LilycoveCity_MoveDeletersHouse_Text_18B78C:: @ 818B78C
	.string "Was?\n"
	.string "Ein EI kennt doch keine Attacken!$"
