MossdeepCity_Gym_Text_18C7E3:: @ 818C7E3
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "Die ARENALEITER hier setzen PSYCHO-\n"
	.string "POKéMON ein.\p"
	.string "Setzt du KAMPF- oder GIFT-POKéMON ein,\n"
	.string "werden diese großen Schaden nehmen!\p"
	.string "Und außerdem wirst du dich gegen eine\n"
	.string "außergewöhnliche Kombination von\l"
	.string "Attacken behaupten müssen.\p"
	.string "Wenn du gewinnen willst, musst du ihnen\n"
	.string "beweisen, wie sehr du mit deinen\l"
	.string "POKéMON verbunden bist! Und nun los!$"

MossdeepCity_Gym_Text_18C938:: @ 818C938
	.string "Wow, du bist erstaunlich!\n"
	.string "Du bist ein großartiger TRAINER!$"

MossdeepCity_Gym_Text_18C96A:: @ 818C96A
	.string "Kämpfe hängen von der Stärke deines\n"
	.string "Geistes ab! Die mit schwachem Geist\l"
	.string "werden niemals gewinnen.$"

MossdeepCity_Gym_Text_18C9BA:: @ 818C9BA
	.string "Ich habe verloren! Ich muss meinen\n"
	.string "Geist stärken!$"

MossdeepCity_Gym_Text_18C9E1:: @ 818C9E1
	.string "Eine nichtssagende Niederlage.\n"
	.string "Das war doch nur eine Warnung an dich.$"

MossdeepCity_Gym_Text_18CA10:: @ 818CA10
	.string "Zeig mir, ob du Talent hast.$"

MossdeepCity_Gym_Text_18CA28:: @ 818CA28
	.string "Du besitzt offensichtlich Talent.$"

MossdeepCity_Gym_Text_18CA48:: @ 818CA48
	.string "Wenn es überhaupt Wunderkinder gibt, \n"
	.string "dann sind es unsere ARENALEITER.\p"
	.string "Aber du scheinst doch talentierter\n"
	.string "als sie zu sein...$"

MossdeepCity_Gym_Text_18CAC0:: @ 818CAC0
	.string "Hihihihi... Achtung! Ich lasse meinen\n"
	.string "POKéBALL durch Telekinese schweben!\p"
	.string "Wuhuuuuuuuhuiii!\n"
	.string "... ... ... ... ... ... ...\p"
	.string "Äh, manchmal fehlt es mir etwas an\n"
	.string "Balance...$"

MossdeepCity_Gym_Text_18CB46:: @ 818CB46
	.string "Meine POKéMON kämpften nicht synchron!$"

MossdeepCity_Gym_Text_18CB77:: @ 818CB77
	.string "Ein POKéBALL ist doch etwas zu schwer,\n"
	.string "um ihn schweben zu lassen!\l"
	.string "Aber ein Staubknäuel...\p"
	.string "Wuhuuuuuuuhu!\n"
	.string "... ... ... ... ... ... ...\p"
	.string "Das ist kein Trick!\n"
	.string "Da ist kein Luftstrom! Ehrlich!$"

MossdeepCity_Gym_Text_18CC1E:: @ 818CC1E
	.string "Solltest du gegen mich verlieren, darfst\n"
	.string "du dir das nicht so zu Herzen nehmen.\p"
	.string "Du bist nicht zu schwach - ich bin nur\n"
	.string "zu stark für dich!$"

MossdeepCity_Gym_Text_18CC83:: @ 818CC83
	.string "Du bist nur zu stark für mich!$"

MossdeepCity_Gym_Text_18CC9B:: @ 818CC9B
	.string "Ich lasse mich von dieser Niederlage\n"
	.string "nicht herunterziehen. Ich werde härter\l"
	.string "trainieren.\p"
	.string "Positives Denken - das ist meine\n"
	.string "Stärke!$"

MossdeepCity_Gym_Text_18CD14:: @ 818CD14
	.string "Ich kann sie sehen...\n"
	.string "Ich sehe deine Zukunft...\p"
	.string "Wenn du mich besiegen kannst, sage ich\n"
	.string "dir deine Zukunft voraus.$"

MossdeepCity_Gym_Text_18CD66:: @ 818CD66
	.string "Ich ergebe mich!$"

MossdeepCity_Gym_Text_18CD73:: @ 818CD73
	.string "Du wirst einen irrsinnigen Kampf gegen\n"
	.string "unsere ARENALEITER führen...\p"
	.string "Der Ausgang dieses Kampfes...\n"
	.string "Meine Lippen sind versiegelt.$"

MossdeepCity_Gym_Text_18CDE0:: @ 818CDE0
	.string "Die Straßen, die du gewandert bist...\n"
	.string "Das, was du erfahren hast...\p"
	.string "Leg mir alles, was du gelernt hast,\n"
	.string "zu Füßen.$"

MossdeepCity_Gym_Text_18CE47:: @ 818CE47
	.string "Du wandelst auf dem Pfad der Größe!$"

MossdeepCity_Gym_Text_18CE6C:: @ 818CE6C
	.string "Eine glänzende Zukunft erwartet die,\n"
	.string "die fleißig sind.\p"
	.string "Die, die dem Müßiggang frönen, erwartet\n"
	.string "am Ende des Weges nur die Verzweiflung.\p"
	.string "Man erntet das, was man sät.$"

MossdeepCity_Gym_Text_18CF02:: @ 818CF02
	.string "BEN: Hähähä... Bist du überrascht?\p"
	.string "SVENJA: Hihihi... Bist du überrascht?\p"
	.string "BEN: Dass es hier 2 ARENALEITER gibt?\n"
	.string "SVENJA: Dass es hier 2 ARENALEITER\l"
	.string "gibt?\p"
	.string "BEN: Wir sind Zwillinge!\n"
	.string "SVENJA: Wir sind Zwillinge!\p"
	.string "BEN: Wir brauchen nicht zu sprechen...\n"
	.string "SVENJA: Wir wissen, was...\p"
	.string "BEN: Der andere gerade denkt...\n"
	.string "SVENJA: Gedankenübertragung!\p"
	.string "BEN: Diese doppelte Stärke...\n"
	.string "SVENJA: Kannst du sie besiegen?$"

MossdeepCity_Gym_Text_18D077:: @ 818D077
	.string "BEN: Was?!? Unsere Kombination...\n"
	.string "SVENJA: Wurde auseinander gerissen!\p"
	.string "BEN: So sieht’s aus. Du hast gewonnen.\n"
	.string "SVENJA: Daher überreichen wir dir dies.$"

MossdeepCity_Gym_Text_18D0F9:: @ 818D0F9
	.string "{PLAYER} erhält den MENTALORDEN von\n"
	.string "SVENJA und BEN.$"

MossdeepCity_Gym_Text_18D128:: @ 818D128
	.string "BEN: Der MENTALORDEN erhöht den SP.\n"
	.string "ANG. und die SP. VER. von POKéMON.\p"
	.string "SVENJA: Und du kannst damit die VM\n"
	.string "TAUCHER außerhalb eines Kampfes\l"
	.string "einsetzen.\p"
	.string "BEN: Dies ist ebenfalls für dich.$"

MossdeepCity_Gym_Text_18D1CF:: @ 818D1CF
	.string "BEN: TM04 enthält...\n"
	.string "SVENJA: GEDANKENGUT!\p"
	.string "BEN: Dies erhöht den SP. ANG. und...\n"
	.string "SVENJA: Erhöht die SP. VER.!\p"
	.string "BEN: Eine Attacke, die perfekt...\n"
	.string "SVENJA: Für PSYCHO-POKéMON ist!$"

MossdeepCity_Gym_Text_18D273:: @ 818D273
	.string "BEN: Es scheint, als sei das Band\n"
	.string "zwischen dir und deinen POKéMON viel\l"
	.string "stärker als zwischen uns Zwillingen.\p"
	.string "SVENJA: Und du wirst noch stärker\n"
	.string "werden! Wir haben gegen dich gekämpft,\l"
	.string "daher können wir das vorhersagen.$"

MossdeepCity_Gym_Text_18D324:: @ 818D324
	.string "BEN: Hähähä... Bist du überrascht?\p"
	.string "SVENJA: Dass es hier 2 ARENALEITER\n"
	.string "gibt?\p"
	.string "BEN: Hups, du hast nur ein...\n"
	.string "SVENJA: POKéMON für den Kampf.\p"
	.string "BEN: So können wir nicht kämpfen!\p"
	.string "SVENJA: Wenn du uns herausfordern\n"
	.string "willst, dann musst du mehr POKéMON\l"
	.string "haben.$"

MossdeepCity_Gym_Text_18D40A:: @ 818D40A
	.string "POKéMON ARENA von MOOSBACH CITY$"

MossdeepCity_Gym_Text_18D424:: @ 818D424
	.string "POKéMON ARENA von MOOSBACH CITY\p"
	.string "SVENJA UND BENS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
