MtPyre_2F_Text_1962C6:: @ 81962C6
	.string "LEIF: Wir machen hier eine Mutprobe.\p"
	.string "Hähä, wenn ich zeige, wie cool ich bin,\n"
	.string "wird sie sich sicher in mich verlieben!\p"
	.string "Besser: Ich werde dich vernichtend\n"
	.string "schlagen. Dann bin ich echt cool!$"

MtPyre_2F_Text_196358:: @ 8196358
	.string "LEIF: Huups!$"

MtPyre_2F_Text_196368:: @ 8196368
	.string "LEIF: Wir haben verloren, aber das macht\n"
	.string "nichts! Solange ich nur bei ihr bin. Wir\l"
	.string "werden diese Mutprobe bestehen!$"

MtPyre_2F_Text_1963CB:: @ 81963CB
	.string "LEIF: Wenn du es mit mir aufnehmen\n"
	.string "willst, brauchst du mehr POKéMON.\p"
	.string "Hast du die nicht, kann ich meiner An-\n"
	.string "gebeteten nicht beweisen, wie cool ich\l"
	.string "bin!$"

MtPyre_2F_Text_196449:: @ 8196449
	.string "INA: Ich bin hier, um mit meinem Freund\n"
	.string "eine Mutprobe zu bestehen.\p"
	.string "Es ist unheimlich hier, aber zusammen\n"
	.string "mit meinem Freund ist es schon okay.\p"
	.string "Ich hab’s: Mein Freund soll zeigen, wie\n"
	.string "cool er ist, indem er dich besiegt!$"

MtPyre_2F_Text_1964EB:: @ 81964EB
	.string "INA: Uuuaaa! Ich habe Angst.$"

MtPyre_2F_Text_196504:: @ 8196504
	.string "INA: Wir sind ineinander verliebt, daher\n"
	.string "stört uns eine Niederlage nicht.$"

MtPyre_2F_Text_196539:: @ 8196539
	.string "INA: Wenn du gegen uns antreten willst,\n"
	.string "solltest du mindestens zwei POKéMON\l"
	.string "besitzen.\p"
	.string "Mein Freund ist stark. Daher wirst du\n"
	.string "mit einem POKéMON nichts ausrichten.$"

MtPyre_2F_Text_1965BB:: @ 81965BB
	.string "Die Erinnerungen an meinen Liebling\n"
	.string "ENECO... Ich könnte weinen...$"

MtPyre_2F_Text_196600:: @ 8196600
	.string "Au au au au... Der Boden hat an einigen\n"
	.string "Stellen Löcher.\p"
	.string "Ich habe das nicht gesehen und bin ins\n"
	.string "untere Stockwerk gefallen. Autsch, aua.$"

MtPyre_2F_Text_196674:: @ 8196674
	.string "Hey! Suchst du nach POKéMON? Du bist\n"
	.string "mir hinterhergeschlichen! Fiesling!$"

MtPyre_2F_Text_1966BE:: @ 81966BE
	.string "Oweiowei.\n"
	.string "Tut mir Leid. Entschuldige bitte!$"

MtPyre_2F_Text_1966E7:: @ 81966E7
	.string "Hier sind nie viele Leute. Daher soll es\n"
	.string "hier seltene POKéMON geben.$"
