PacifidlogTown_PokemonCenter_1F_Text_178E47:: @ 8178E47
	.string "Welche Farbe hat dein TRAINERPASS?\n"
	.string "Meiner ist kupferrot.$"

PacifidlogTown_PokemonCenter_1F_Text_178E79:: @ 8178E79
	.string "FLOSSBRUNN schwimmt auf einer\n"
	.string "Kolonie von CORASONN.\p"
	.string "Glaubst du mir das?$"

PacifidlogTown_PokemonCenter_1F_Text_178ED9:: @ 8178ED9
	.string "Man sagt, die Vorfahren der Menschen in\n"
	.string "FLOSSBRUNN wurden an Bord von\l"
	.string "Schiffen geboren, lebten und starben\l"
	.string "auch dort.\p"
	.string "Diese Lebensart ist verständlich, denn\n"
	.string "sie waren auf der Suche nach etwas.$"
