PetalburgCity_PokemonCenter_1F_Text_17BD30:: @ 817BD30
	.string "Computerbasiertes POKéMON-Lagerungs-\n"
	.string "System...\p"
	.string "Wer auch immer dies entwickelt hat, muss\n"
	.string "ein wahrer Zauberer sein!$"

PetalburgCity_PokemonCenter_1F_Text_17BD92:: @ 817BD92
	.string "Als mein POKéMON eine SINELBEERE\n"
	.string "aß, wurden seine KP aufgefüllt!$"

PetalburgCity_PokemonCenter_1F_Text_17BDC5:: @ 817BDC5
	.string "Es gibt viele Typen von POKéMON.\p"
	.string "Jeder Typ hat seine Stärken und\n"
	.string "Schwächen gegenüber anderen Typen.\p"
	.string "Je nach Typ des POKéMON kann der\n"
	.string "Kampf leicht oder schwer sein.$"

PetalburgCity_PokemonCenter_1F_Text_17BE6C:: @ 817BE6C
	.string "Dein GECKARBOR ist beispielsweise ein\n"
	.string "PFLANZEN-Typ.\p"
	.string "Es ist stark gegenüber dem WASSER-\n"
	.string "und BODEN-Typ.\p"
	.string "Aber es ist schwach gegenüber den\n"
	.string "FEUER-POKéMON.$"

PetalburgCity_PokemonCenter_1F_Text_17BEF1:: @ 817BEF1
	.string "Dein FLEMMLI ist beispielsweise ein\n"
	.string "FEUER-Typ.\p"
	.string "Es ist stark gegenüber dem PFLANZEN-\n"
	.string "und KÄFER-Typ.\p"
	.string "Aber es ist schwach gegenüber den\n"
	.string "WASSER-POKéMON.$"

PetalburgCity_PokemonCenter_1F_Text_17BF73:: @ 817BF73
	.string "Dein HYDROPI ist beispielsweise ein\n"
	.string "WASSER-Typ.\p"
	.string "Es ist stark gegenüber dem FEUER-Typ.\p"
	.string "Aber es ist schwach gegenüber den\n"
	.string "PFLANZEN- und ELEKTRO-POKéMON.$"
