PetalburgCity_House2_Text_17BC4F:: @ 817BC4F
	.string "NORMAN ist unser neuer ARENALEITER.\p"
	.string "Ich glaube, er ist mit seiner Familie aus\n"
	.string "der JOHTO-Region hier hergezogen.$"

PetalburgCity_House2_Text_17BCB1:: @ 817BCB1
	.string "Ich bin erst einmal gegen NORMAN\n"
	.string "angetreten. Wow, war der stark!\p"
	.string "Wie soll ich es sagen?\p"
	.string "Ich habe den Eindruck, er lebt für\n"
	.string "seine POKéMON.$"
