Route104_MrBrineysHouse_Text_191A82:: @ 8191A82
	.string "MR. BRACK: Warte, Mädchen!\n"
	.string "Immer langsam, PECKO!$"

Route104_MrBrineysHouse_Text_191AAD:: @ 8191AAD
	.string "Hm? Du bist {PLAYER}{KUN}!\n"
	.string "Du hast meinen Liebling PECKO gerettet!\l"
	.string "Wir verdanken dir sehr viel!\p"
	.string "Wie bitte?\n"
	.string "Du möchtest mit mir segeln?\p"
	.string "Hmhm...\p"
	.string "Du musst einen BRIEF in FAUSTAUHAVEN\n"
	.string "und ein Paket in GRAPHITPORT CITY\l"
	.string "abgeben?\p"
	.string "Da bist du aber gut beschäftigt!\p"
	.string "Aber deine Bitte ist überhaupt kein\n"
	.string "Problem für mich.\p"
	.string "Bei mir bist du richtig! Wir setzen\n"
	.string "Segel Richtung FAUSTAUHAVEN!$"

Route104_MrBrineysHouse_Text_191BFD:: @ 8191BFD
	.string "MR. BRACK: FAUSTAUHAVEN, wir kommen!\p"
	.string "Anker gelichtet!\n"
	.string "PECKO, mein Liebling, wir setzen Segel!$"

Route104_MrBrineysHouse_Text_191C57:: @ 8191C57
	.string "MR. BRACK: Wirklich?\n"
	.string "Deine Besorgungen können warten?\p"
	.string "Lass dir Zeit. Ein Wort genügt und wir\n"
	.string "setzen Segel.$"

Route104_MrBrineysHouse_Text_191CC3:: @ 8191CC3
	.string "MR. BRACK: Ahoi! Ich weiß genau,\n"
	.string "was du jetzt sagen willst!\p"
	.string "Du musst einen BRIEF in FAUSTAUHAVEN\n"
	.string "und ein Paket in GRAPHITPORT CITY\l"
	.string "abgeben.\p"
	.string "Nun, ich bin der richtige Mann für\n"
	.string "diesen Job!\p"
	.string "Dann segeln wir zuerst Richtung\n"
	.string "FAUSTAUHAVEN.$"

Route104_MrBrineysHouse_Text_191DA6:: @ 8191DA6
	.string "MR. BRACK: Ahoi! Ich weiß genau,\n"
	.string "was du jetzt sagen willst!\p"
	.string "Du musst KAPT. BRIGG in\n"
	.string "GRAPHITPORT CITY ein Paket bringen.\p"
	.string "Nun, ich bin der richtige Mann für\n"
	.string "diesen Job!\p"
	.string "Dann segeln wir zuerst Richtung\n"
	.string "FAUSTAUHAVEN.$"

Route104_MrBrineysHouse_Text_191E80:: @ 8191E80
	.string "MR. BRACK: Ahoi! Für dich fahre ich\n"
	.string "jederzeit wieder raus!\p"
	.string "Nun, wo soll es hingehen?$"

Route104_MrBrineysHouse_Text_191EDB:: @ 8191EDB
	.string "MR. BRACK: Wirklich?\n"
	.string "Nun, PECKO verdankt dir ihr Leben.\p"
	.string "Lass dir Zeit. Ein Wort genügt und wir\n"
	.string "setzen Segel.$"

UnknownString_8191F4F: @ 8191F4F
	.string "MR. BRACK: Ahoi!\n"
	.string "Wir haben in BLÜTENBURG CITY angelegt.\p"
	.string "Lass dir Zeit. Ein Wort genügt und wir\n"
	.string "setzen Segel.$"

Route104_MrBrineysHouse_Text_191FB9:: @ 8191FB9
	.string "PECKO: Pii pihyoroo!$"
