Route103_Text_16D57A:: @ 816D57A
	.string "MAIKE: Mal seh’n... Das POKéMON von\n"
	.string "ROUTE 103 besitzt...$"

Route103_Text_16D5B6:: @ 816D5B6
	.string "Oh, hi {PLAYER}{KUN}!\p"
	.string "...Oh... Ich seh’ schon. Mein Vater hat dir\n"
	.string "ein POKéMON geschenkt.\p"
	.string "Wenn wir schon mal hier sind, lass uns\n"
	.string "doch kämpfen!\p"
	.string "Ich gebe dir einen Vorgeschmack auf\n"
	.string "das Leben als TRAINER.$"

Route103_Text_16D65B:: @ 816D65B
	.string "Wow! Das war spitze!\n"
	.string "{PLAYER}{KUN}, du bist ein Naturtalent!$"

Route103_Text_16D688:: @ 816D688
	.string "MAIKE: Ich glaube, ich weiß jetzt, warum\n"
	.string "mein Vater dich ausgesucht hat.\p"
	.string "Ich meine, du hast dein POKéMON erst\n"
	.string "sehr kurze Zeit und es mag dich bereits.\p"
	.string "Du wirst es einfach haben, dich mit\n"
	.string "jeder Art von POKéMON anzufreunden.\p"
	.string "Nun wird es aber Zeit, zurück ins LABOR\n"
	.string "zu gehen!$"

Route103_Text_16D762:: @ 816D762
	.string "BRIX: So... Dieses und dieses lebt an\n"
	.string "der ROUTE 103...$"

Route103_Text_16D7A9:: @ 816D7A9
	.string "Hey, da ist ja {PLAYER}!\p"
	.string "...Oh ja. Mein Vater hat dir ein POKéMON\n"
	.string "geschenkt, nicht wahr?\p"
	.string "Wenn wir schon mal hier sind, lass uns\n"
	.string "doch einen kleinen Kampf austragen.\p"
	.string "Ich bringe dir bei, was ein TRAINER\n"
	.string "wissen muss.$"

Route103_Text_16D836:: @ 816D836
	.string "Hey, {PLAYER}, das war gar nicht so übel.$"

Route103_Text_16D856:: @ 816D856
	.string "BRIX: Ich denke, ich habe es kapiert.\n"
	.string "Ich weiß jetzt, warum mein Vater dich\l"
	.string "ausgesucht hat.\p"
	.string "Du hast dein POKéMON noch nicht lange,\n"
	.string "und doch mag es dich schon.\p"
	.string "{PLAYER}, ich glaube, du kannst mit jedem\n"
	.string "POKéMON Freundschaft schließen.\p"
	.string "Wir sollten nun zurück zum LABOR gehen.$"

Route103_Text_16D950:: @ 816D950
	.string "Mein POKéMON ist unglaublich müde...\n"
	.string "Ich hätte einen TRANK mitnehmen sollen.$"

Route103_Text_16D996:: @ 816D996
	.string "Wenn du von hier das Meer überquerst,\n"
	.string "nimmst du eine Abkürzung nach\l"
	.string "ROSALTSTADT.\p"
	.string "Hahaha, ist das kein praktischer Tipp?$"

Route103_Text_16D9FB:: @ 816D9FB
	.string "ROUTE 103\n"
	.string "{DOWN_ARROW} ROSALTSTADT$"
