Route114_FossilManiacsTunnel_Text_192795:: @ 8192795
	.string "Ich bin der FOSSILMANIAC... Ich bin\n"
	.string "ein netter Typ, der Fossilien liebt...\p"
	.string "Möchtest du ein Fossil haben?\p"
	.string "Die Fossilien in dieser Gegend gehören\n"
	.string "allerdings alle mir! Keines ist für dich...\p"
	.string "Wenn du unbedingt ein Fossil haben\n"
	.string "möchtest, geh in die Wüste bei\l"
	.string "ROUTE 111...\p"
	.string "Ich habe gehört, dass dort Fossilien,\n"
	.string "die im Boden versteckt liegen, manchmal\l"
	.string "durch Sandstürme freigelegt werden.$"

Route114_FossilManiacsTunnel_Text_1928DE:: @ 81928DE
	.string "Du hast ein FOSSIL gefunden, stimmt’s?\n"
	.string "Das ist schön... Traumhaft...\p"
	.string "Was wirst du mit dem FOSSIL machen?\p"
	.string "Ich habe gehört, dass DEVON versucht,\n"
	.string "aus den FOSSILIEN POKéMON zum\l"
	.string "Leben zu erwecken...\p"
	.string "Ich liebe FOSSILIEN, daher würde ich\n"
	.string "so etwas niemals machen...$"

Route114_FossilManiacsTunnel_Text_1929DC:: @ 81929DC
	.string "FOSSILIEN sind so... Wundervoll...\n"
	.string "Einfach traumhaft...$"
