Route109_SeashoreHouse_Text_19B4D9:: @ 819B4D9
	.string "Ich bin der Besitzer des STRANDHAUSES.\n"
	.string "Du kannst MR. MARE zu mir sagen.\p"
	.string "Heißen POKéMON-Kämpfen zuzusehen\n"
	.string "liebe ich über alles!\p"
	.string "Zeig mir, wie heiß dein Herz lodert!\p"
	.string "Wenn du alle TRAINER besiegen kannst,\n"
	.string "werde ich dich belohnen!$"

Route109_SeashoreHouse_Text_19B5B9:: @ 819B5B9
	.string "Zeig mir heiße Kämpfe!\p"
	.string "Nur für diese habe ich das STRANDHAUS\n"
	.string "überhaupt geöffnet!$"

Route109_SeashoreHouse_Text_19B609:: @ 819B609
	.string "Du bist brandheiß!\n"
	.string "Die Kämpfe glühen geradezu!\l"
	.string "Ich bin mehr als zufrieden!\p"
	.string "Du hast deine Fertigkeiten bewiesen.\n"
	.string "Zum Dank schenke ich dir etwas.\p"
	.string "Es sind sechs Flaschen SPRUDEL!$"

Route109_SeashoreHouse_Text_19B6BE:: @ 819B6BE
	.string "Aber dein BEUTEL ist ja gerammelt voll.\n"
	.string "Ich werde sie für dich aufbewahren.$"

Route109_SeashoreHouse_Text_19B702:: @ 819B702
	.string "Möchtest du etwas SPRUDEL kaufen?\n"
	.string "POKéMON lieben ihn!\p"
	.string "Nur ¥300 pro Flasche!\n"
	.string "Kauf doch welchen!$"

Route109_SeashoreHouse_Text_19B74C:: @ 819B74C
	.string "Hier, bitte schön!$"

Route109_SeashoreHouse_Text_19B759:: @ 819B759
	.string "Du hast nicht genügend Geld.$"

Route109_SeashoreHouse_Text_19B773:: @ 819B773
	.string "Nein?\n"
	.string "Das ist aber wirklich schade.$"

UnknownString_819B787: @ 819B787
	.string "SPRUDEL! POKéMONs Liebling!\n"
	.string "Nur ¥300 pro Flasche! Möchtest du eine?$"

UnknownString_819B7C5: @ 819B7C5
	.string "Hier, bitte schön!$"

UnknownString_819B7D2: @ 819B7D2
	.string "Oh je!\n"
	.string "Du hast nicht genügend Geld.$"

UnknownString_819B7F9: @ 819B7F9
	.string "Das ist wirklich sehr schade.$"

Route109_SeashoreHouse_Text_19B809:: @ 819B809
	.string "Wenn du Lust auf einen heißen Kampf\n"
	.string "auf hoher See hast, findest du keinen\l"
	.string "lodernderen TRAINER als mich!$"

Route109_SeashoreHouse_Text_19B869:: @ 819B869
	.string "Das war ein heißer Kampf!\n"
	.string "Ich kann die Niederlage verkraften!$"

Route109_SeashoreHouse_Text_19B89F:: @ 819B89F
	.string "Immer wenn ich in GRAPHITPORT CITY bin,\n"
	.string "genieße ich heiße Kämpfe und\l"
	.string "eisgekühlten SPRUDEL!$"

Route109_SeashoreHouse_Text_19B8E5:: @ 819B8E5
	.string "Langweilige Kämpfe lohnen sich nicht.\p"
	.string "Feurig heiße Kämpfe aber stählen\n"
	.string "TRAINER und POKéMON.$"

Route109_SeashoreHouse_Text_19B949:: @ 819B949
	.string "Das war brandheiß!$"

Route109_SeashoreHouse_Text_19B955:: @ 819B955
	.string "Puh, ich bin am Verdursten.\n"
	.string "Ich sollte SPRUDEL trinken.$"

Route109_SeashoreHouse_Text_19B988:: @ 819B988
	.string "Ich werde dir zeigen, wie toll meine\n"
	.string "POKéMON sind. Aber heul bloß nicht los!$"

Route109_SeashoreHouse_Text_19B9C7:: @ 819B9C7
	.string "Ich habe verloren. Aber ich heule nicht!$"

Route109_SeashoreHouse_Text_19B9E5:: @ 819B9E5
	.string "Wenn doch nur eines meiner POKéMON\n"
	.string "wüsste, wie es mich über das Wasser\l"
	.string "tragen kann. Dann wäre ich den\l"
	.string "ollen Schwimmreifen los.$"
