PetalburgCity_Text_16D361:: @ 816D361
	.string "HEIKO: {PLAYER}...\n"
	.string "POKéMON verstecken sich in hohem Gras\l"
	.string "wie diesem hier, oder?\p"
	.string "Bitte bleib hier und schau, ob ich sie\n"
	.string "auch richtig fange.\p"
	.string "...Whoa!$"

PetalburgCity_Text_16D3DE:: @ 816D3DE
	.string "HEIKO: Ich habe es geschafft... Es\n"
	.string "gehört mir... Mein POKéMON!!!$"

PetalburgCity_Text_16D408:: @ 816D408
	.string "{PLAYER}, danke schön!\n"
	.string "Lass uns zurück zur ARENA gehen!$"

Route102_Text_16D431:: @ 816D431
	.string "Ich... bin nicht groß, ich versinke im\n"
	.string "hohen Gras.\p"
	.string "Das Gras erreicht meine Nase und...\n"
	.string "Hahahaha...\p"
	.string "Haaatschiiii!$"

UnknownString_816D4A5: @ 816D4A5
	.string "Hähähä...\n"
	.string "Beobachte mich gut.$"

UnknownString_816D4BB: @ 816D4BB
	.string "Ta-daaaaah! Unglaublich, oder?\p"
	.string "Es gibt einige Absätze, die man nicht\n"
	.string "hochklettern, aber von denen man\l"
	.string "herunterspringen kann.$"

Route102_Text_16D51A:: @ 816D51A
	.string "Ich werde jede Menge POKéMON fangen!$"

Route102_Text_16D547:: @ 816D547
	.string "ROUTE 102\n"
	.string "{RIGHT_ARROW} ROSALTSTADT$"

Route102_Text_16D55F:: @ 816D55F
	.string "ROUTE 102\n"
	.string "{LEFT_ARROW} BLÜTENBURG CITY$"
