RustboroCity_Text_16689D:: @ 816689D
	.string "Die DEVON CORPORATION...\n"
	.string "Wir nennen sie kurz DEVON.\p"
	.string "Die Firma stellt viele praktische\n"
	.string "Dinge her.$"

RustboroCity_Text_16690C:: @ 816690C
	.string "Hm? Ein verschlagen wirkender Mann?\p"
	.string "Wenn ich so darüber nachdenke, fällt mir\n"
	.string "ein, dass ich einen zwielichtigen Typen\l"
	.string "eben hier an der Ecke gesehen habe.$"

RustboroCity_Text_16696D:: @ 816696D
	.string "Hast du schon die Herausforderung der\n"
	.string "POKéMON ARENA angenommen?\p"
	.string "Ich glaube, wenn sie den glänzenden\n"
	.string "ORDEN der ARENA in der Hand halten, wird\l"
	.string "den TRAINERN klar, was von ihnen\l"
	.string "verlangt wird.$"

RustboroCity_Text_1669FE:: @ 81669FE
	.string "Hey, das ist der ORDEN der ARENA von\n"
	.string "METAROST CITY!\p"
	.string "Von allen ARENA-ORDEN ist der von\n"
	.string "METAROST CITY der coolste, sage ich dir.$"

RustboroCity_Text_166A67:: @ 8166A67
	.string "Oh? Wer magst du wohl sein?\n"
	.string "Ein neues Gesicht in dieser Gegend.\p"
	.string "Bist du gerade in die POKéMON TRAINER-\n"
	.string "SCHULE gekommen?$"

RustboroCity_Text_166AE0:: @ 8166AE0
	.string "Ich habe den ARENALEITER heraus-\n"
	.string "gefordert, aber...\p"
	.string "Es ist nicht einfach, mit meinen FEUER-\n"
	.string "POKéMON zu gewinnen...\p"
	.string "FEUER-POKéMON haben keinen guten\n"
	.string "Stand gegenüber GESTEINS-POKéMON.$"

RustboroCity_Text_166B86:: @ 8166B86
	.string "Der alte Seebär MR. BRACK lebt in einer\n"
	.string "Hütte am Meer.\p"
	.string "Er geht sehr oft in dem Tunnel\n"
	.string "spazieren.$"

RustboroCity_Text_166BEF:: @ 8166BEF
	.string "Der alte Seebär MR. BRACK lebt in einer\n"
	.string "Hütte am Meer.\p"
	.string "Er sagt, er wäre in GRAPHITPORT CITY\n"
	.string "gewesen, um etwas für sein Haustier,\l"
	.string "PECKO, zu kaufen.\p"
	.string "Der alte Seebär muss sein PECKO wirklich\n"
	.string "sehr lieben.$"

RustboroCity_Text_166C98:: @ 8166C98
	.string "Wow, du hast ja auch POKéMON dabei.\p"
	.string "Wenn ich größer bin, werde ich auch\n"
	.string "immer POKéMON dabeihaben.$"

RustboroCity_Text_166CFA:: @ 8166CFA
	.string "POKéMON TRAINERSCHULE!\p"
	.string "Wenn ich in diese Schule gehe, werde ich\n"
	.string "später seltene POKéMON fangen können?$"

RustboroCity_Text_166D59:: @ 8166D59
	.string "Wenn ein POKéMON Erfahrungen im Kampf\n"
	.string "sammelt, kann es vorkommen, dass es\l"
	.string "irgendwann sein Aussehen verändert.$"

RustboroCity_Text_166DB0:: @ 8166DB0
	.string "Ein POKéMON verändert sein Aussehen?!?\n"
	.string "Wenn es das tun würde, wäre ich zu Tode\l"
	.string "erschrocken!$"

RustboroCity_Text_166DEE:: @ 8166DEE
	.string "Ein POKéMON, das du durch Tausch\n"
	.string "erhältst, wächst schnell.\p"
	.string "Aber wenn dir ORDEN von bestimmten\n"
	.string "ARENEN fehlen, wird es dir eventuell\l"
	.string "nicht gehorchen.$"

RustboroCity_Text_166E65:: @ 8166E65
	.string "Geh weg! Aus dem Weg!!!$"

RustboroCity_Text_166E7E:: @ 8166E7E
	.string "Warte! Waaaaarte doch! Bitte!\p"
	.string "Du kannst doch nicht einfach meine\n"
	.string "WAREN stehlen!!!$"

RustboroCity_Text_166EA5:: @ 8166EA5
	.string "Oh, du bist das!\p"
	.string "Du bist dieser großartige TRAINER, der\n"
	.string "mir im BLÜTENBURGWALD geholfen hat.\p"
	.string "Hilf mir! Das TEAM {EVIL_TEAM} hat mich aus-\n"
	.string "geraubt! Ich muss die DEVON-WAREN\l"
	.string "zurückbekommen.\p"
	.string "Wenn ich sie nicht bekomme...\n"
	.string "Dann habe ich ein riesiges Problem.$"

RustboroCity_Text_166F6B:: @ 8166F6B
	.string "Ich glaube, dieser zwielichtige Typ ist\n"
	.string "in Richtung Tunnel gelaufen.$"

RustboroCity_Text_166FB4:: @ 8166FB4
	.string "Oh! Und? Wie sieht es aus?\n"
	.string "Die DEVON-WAREN?\p"
	.string "Du hast es geschafft!\n"
	.string "Du hast sie zurückbekommen!\p"
	.string "Du bist wirklich ein großer TRAINER!\n"
	.string "Ich weiß! Ich werde dir zum Dank einen\l"
	.string "weiteren SUPERBALL schenken!$"

RustboroCity_Text_16704C:: @ 816704C
	.string "Dein BEUTEL ist voll.\n"
	.string "Ich kann dir den SUPERBALL nicht geben.$"

RustboroCity_Text_16707F:: @ 816707F
	.string "Bitte entschuldige!\n"
	.string "Würdest du mir bitte folgen?$"

RustboroCity_Text_1670A7:: @ 81670A7
	.string "MAIKE: Oh, hi {PLAYER}{KUN}!\n"
	.string "Wie geht es mit deinem POKéDEX voran?\p"
	.string "Meiner sieht schon ganz anständig aus.\p"
	.string "Ich habe im BLÜTENBURGWALD\n"
	.string "POKéMON gefangen, bis ich keine\l"
	.string "POKéBÄLLE mehr hatte.$"

RustboroCity_Text_16713C:: @ 816713C
	.string "MAIKE: Ach, übrigens. Ich habe MR.\n"
	.string "BRACK im BLÜTENBURGWALD gesehen.\p"
	.string "Ich glaube, er ist auf dem Weg zu seiner\n"
	.string "Hütte am Meer.\p"
	.string "{PLAYER}{KUN}, du bist gerade hierher\n"
	.string "gezogen, daher kannst du das nicht\l"
	.string "wissen, aber MR. BRACK war Seefahrer.$"

RustboroCity_Text_167213:: @ 8167213
	.string "BRIX: {PLAYER}, wie sieht es mit\n"
	.string "deinem POKéDEX aus?\p"
	.string "Meiner ist eine Wucht.\p"
	.string "Ich habe im BLÜTENBURGWALD jede\n"
	.string "Menge POKéMON gefangen, bis ich keine\l"
	.string "POKéBÄLLE mehr hatte.$"

RustboroCity_Text_1672B8:: @ 81672B8
	.string "BRIX: Übrigens habe ich dort auch\n"
	.string "MR. BRACK gesehen.\p"
	.string "Ich wette, er ist auf dem Weg zu seiner\n"
	.string "Hütte am Meer.\p"
	.string "Und ich wette, du weißt nicht, dass er\n"
	.string "immer ein POKéMON bei sich hat.$"

RustboroCity_Text_167374:: @ 8167374
	.string "“Tunnel zur Abkürzung steht vor\n"
	.string "Fertigstellung!”\p"
	.string "...Das steht auf dem Schild, aber darüber\n"
	.string "wurde ein “X” in roter Farbe gemalt...$"

RustboroCity_Text_1673FA:: @ 81673FA
	.string "DEVON CORPORATION\p"
	.string "“Alles, was man im Leben braucht - \n"
	.string "wir stellen es her.”$"

RustboroCity_Text_167439:: @ 8167439
	.string "POKéMON ARENA von METAROST CITY\n"
	.string "LEITER: FELIZIA\p"
	.string "“GESTEINS-Liebhaberin und\n"
	.string "ihre Schüler!”$"

RustboroCity_Text_167485: @ 8167485
	.string "DEVON CORP. FILIALE\p"
	.string "“Zutritt nur für Angestellte von DEVON\n"
	.string "und autorisierte Personen.”$"

RustboroCity_Text_1674DD:: @ 81674DD
	.string "METAROST CITY\p"
	.string "“Diese Stadt steht im Zeichen der Inte-\n"
	.string "gration von Natur und Wissenschaften.”$"

RustboroCity_Text_167525:: @ 8167525
	.string "POKéMON TRAINERSCHULE\p"
	.string "“Wir bringen dir alles über die\n"
	.string "POKéMON bei!”$"

RustboroCity_Text_167568:: @ 8167568
	.string "HAUS DES ZERSCHNEIDERS$"
