SlateportCity_House1_Text_17D46A:: @ 817D46A
	.string "Hallo! Ich bin der NAMENBEWERTER!\n"
	.string "Ich bin das Orakel der Namen!\p"
	.string "Ich würde mich freuen, die Kosenamen\n"
	.string "deiner POKéMON bewerten zu dürfen.$"

SlateportCity_House1_Text_17D4DB:: @ 817D4DB
	.string "Für welches POKéMON soll ich den\n"
	.string "Kosenamen bewerten?$"

SlateportCity_House1_Text_17D505:: @ 817D505
	.string "Hmmm... {STR_VAR_1}, nicht wahr? Da hast\n"
	.string "du aber einen schönen Namen verliehen.\p"
	.string "Aber! Was hältst du davon, wenn ich ihm\n"
	.string "einen etwas besseren Namen gebe?$"

SlateportCity_House1_Text_17D580:: @ 817D580
	.string "Sehr schön! Und wie soll der neue\n"
	.string "Kosename lauten?$"

SlateportCity_House1_Text_17D5B0:: @ 817D5B0
	.string "Fertig! Von nun an heißt dein POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Das ist ein besserer Name als der\n"
	.string "vorherige. Welch ein Glück für dich!$"

SlateportCity_House1_Text_17D61E:: @ 817D61E
	.string "Ich verstehe.\n"
	.string "Komm mich mal wieder besuchen.$"

SlateportCity_House1_Text_17D63A:: @ 817D63A
	.string "Fertig! Von nun an heißt dein POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Eigentlich unterscheidet sich der Name\n"
	.string "nicht von dem vorherigen, und doch ist\l"
	.string "er um einiges besser! Welch ein Glück!$"

SlateportCity_House1_Text_17D6CC:: @ 817D6CC
	.string "Hmmm... {STR_VAR_1}!\p"
	.string "Das ist ein wundervoller Kosename!\n"
	.string "Ein Name ohne Fehl und Tadel!\p"
	.string "Du tust gut daran, {STR_VAR_1} auch\n"
	.string "weiterhin liebevoll zu behandeln!$"

SlateportCity_House1_Text_17D752:: @ 817D752
	.string "Mhm, mhm...\n"
	.string "Das ist eigentlich ein EI!$"
