SlateportCity_OceanicMuseum_1F_Text_17E18D:: @ 817E18D
	.string "Willkommen im OZEANMUSEUM.\p"
	.string "Der Eintritt kostet ¥50.\n"
	.string "Hast du Interesse?$"

SlateportCity_OceanicMuseum_1F_Text_17E1DE:: @ 817E1DE
	.string "Viel Vergnügen!$"

SlateportCity_OceanicMuseum_1F_Text_17E1F5:: @ 817E1F5
	.string "Oh. Tut mir Leid, aber du hast\n"
	.string "anscheinend nicht genug Geld bei dir.$"

SlateportCity_OceanicMuseum_1F_Text_17E22D:: @ 817E22D
	.string "Oh. Du gehörst zu der Gruppe, die gerade\n"
	.string "hineingegangen ist?\p"
	.string "Sie sind alle schon drin. Beeil dich,\n"
	.string "sonst verlierst du die Gruppe.$"

UnknownString_817E2A0: @ 817E2A0
	.string "Bitte komm ein anderes Mal wieder!$"

SlateportCity_OceanicMuseum_1F_Text_17E2BB:: @ 817E2BB
	.string "Wir, TEAM {EVIL_TEAM}, bestehen zum Besten\n"
	.string "für alle!$"

SlateportCity_OceanicMuseum_1F_Text_17E2E3:: @ 817E2E3
	.string "Uns wurde befohlen, uns hier zu\n"
	.string "versammeln. Das taten wir, aber...\p"
	.string "Unser BOSS, der Galgenvogel, ist nicht\n"
	.string "hier.$"

SlateportCity_OceanicMuseum_1F_Text_17E338:: @ 817E338
	.string "Wenn ich diese ganzen Sachen an mich\n"
	.string "reißen würde, wäre ich dann reich?$"

SlateportCity_OceanicMuseum_1F_Text_17E36F:: @ 817E36F
	.string "Was ich hier lerne, kann ich für meine\n"
	.string "ruchlosen Taten gut gebrauchen...$"

SlateportCity_OceanicMuseum_1F_Text_17E3A9:: @ 817E3A9
	.string "Wenn dieser Idiot die Sache in\n"
	.string "METAROST CITY nicht vermasselt hätte,\l"
	.string "wären wir jetzt nicht hier.$"

SlateportCity_OceanicMuseum_1F_Text_17E3ED:: @ 817E3ED
	.string "Ich hatte keine ¥50, daher habe ich\n"
	.string "Ewigkeiten gebraucht, an der Rezeption\l"
	.string "vorbeizukommen.$"

SlateportCity_OceanicMuseum_1F_Text_17E434:: @ 817E434
	.string "Ich möchte etwas über das Meer lernen\n"
	.string "und dieses Wissen in Kämpfen einsetzen.$"

SlateportCity_OceanicMuseum_1F_Text_17E477:: @ 817E477
	.string "Mir wird ganz schwindelig und rühr-\n"
	.string "selig, wenn ich das Meer erblicke!\p"
	.string "Für mich ist KAPT. BRIGG das absolute\n"
	.string "Vorbild!$"

SlateportCity_OceanicMuseum_1F_Text_17E4D7:: @ 817E4D7
	.string "Das Meer ist erbarmungslos rau und\n"
	.string "unendlich tief...\p"
	.string "In ihm müssen viele POKéMON leben, die\n"
	.string "wir bisher noch nicht kennen.$"

SlateportCity_OceanicMuseum_1F_Text_17E540:: @ 817E540
	.string "Ich möchte ein POKéMON aus dem Meer\n"
	.string "haben.\p"
	.string "Wenn man das umarmt, ist es bestimmt\n"
	.string "schön kalt und wunderbar glitschig.$"

SlateportCity_OceanicMuseum_1F_Text_17E582:: @ 817E582
	.string "Aiyeeh!\n"
	.string "Was machst du hier?\p"
	.string "Ich? Ich bin vom TEAM {EVIL_TEAM}. Du hast\n"
	.string "mich in den Boden gestampft. Erinnerst\l"
	.string "du dich?\p"
	.string "Hier, das ist für dich!\n"
	.string "Vergeben und vergessen!$"

SlateportCity_OceanicMuseum_1F_Text_17E606:: @ 817E606
	.string "Au, verdammt!\n"
	.string "Du hast unsere Pläne zunichte gemacht!\p"
	.string "Ich wollte als Ausgleich etwas mitgehen\n"
	.string "lassen, aber...\p"
	.string "Warte!\n"
	.string "Du bekommst deine Belohnung auch noch!$"

SlateportCity_OceanicMuseum_1F_Text_17E695:: @ 817E695
	.string "Oooch, komm schon!\n"
	.string "Nimm es und lass mich gehen!$"

SlateportCity_OceanicMuseum_1F_Text_17E6C9:: @ 817E6C9
	.string "Eine blaue Flüssigkeit bewegt sich\n"
	.string "spiralförmig in einem Glasgefäß.\p"
	.string "“Dies ist ein Experiment, das einen\n"
	.string "künstlichen WHIRLPOOL mit Hilfe von\l"
	.string "Wind erzeugt.”$"

SlateportCity_OceanicMuseum_1F_Text_17E741:: @ 817E741
	.string "Ein roter Ball hüpft in dem Glasgefäß\n"
	.string "auf und ab.\p"
	.string "“Dies ist ein Experiment, das eine\n"
	.string "künstliche KASKADE mit Hilfe des\l"
	.string "Ballauftriebs erzeugt.”$"

SlateportCity_OceanicMuseum_1F_Text_17E7C4:: @ 817E7C4
	.string "Dies ist eine Probe vom Meeresboden.\p"
	.string "“Über viele Jahre haben sich die Spuren\n"
	.string "allen Lebens als Sedimente auf dem\l"
	.string "Grund des Meeres abgelagert.\p"
	.string "Analysen dieser Proben geben einen\n"
	.string "Einblick in längst vergangenes Leben.”$"

SlateportCity_OceanicMuseum_1F_Text_17E892:: @ 817E892
	.string "Dies ist eine Probe vom Sand der Küste.\p"
	.string "“Die Gesteinsschichten der Berge\n"
	.string "wurden im Laufe der Jahre durch Wasser\l"
	.string "abgetragen und am Boden abgelagert.\p"
	.string "Nun sind sie nur noch kleine Körnchen,\n"
	.string "die den Sand an der Küste bilden.”$"

SlateportCity_OceanicMuseum_1F_Text_17E944:: @ 817E944
	.string "“MEERESKUNDE FAKT 1”\n"
	.string "Warum ist das Wasser im Meer blau?\p"
	.string "“Licht setzt sich aus vielen\n"
	.string "Farben zusammen.\p"
	.string "Scheint das Licht durch Wasser, so\n"
	.string "gehen einige Farben verloren.\p"
	.string "Der Blauanteil des Lichts bleibt aber\n"
	.string "erhalten, das Wasser erscheint blau.”$"

SlateportCity_OceanicMuseum_1F_Text_17EA19:: @ 817EA19
	.string "“MEERESKUNDE FAKT 2”\n"
	.string "Warum ist das Meer salzig?\p"
	.string "“Meerwasser enthält gelöste Salzionen\n"
	.string "in Form von Natrium und Chlorid.\p"
	.string "Diese Ionen wurden durch den Regen\n"
	.string "aus Gesteinsschichten herausgespült.\p"
	.string "Die Konzentration des aufgelösten\n"
	.string "Salzes macht das Meer salzig.”$"

SlateportCity_OceanicMuseum_1F_Text_17EB0D:: @ 817EB0D
	.string "“MEERESKUNDE FAKT 3”\n"
	.string "Was ist größer? Das Meer oder das Land?\p"
	.string "“Die Erde ist zu 70% von Wasser\n"
	.string "bedeckt, der Rest ist Land.\p"
	.string "Das Meer ist also mehr als doppelt\n"
	.string "so groß wie das Land.”$"

SlateportCity_OceanicMuseum_1F_Text_17EBBC:: @ 817EBBC
	.string "Das ist ein Fossil mit vielen Furchen.\p"
	.string "“Das Erdreich des Meeresbodens wird\n"
	.string "durch die Gezeiten abgetragen.\p"
	.string "Die Bewegungen des Wassers zeichnen\n"
	.string "Rillen und Wellen in den Meeresboden.\p"
	.string "Wenn der Meeresboden versteinert, wird\n"
	.string "ein Bodenrelief sichtbar.”$"

SlateportCity_OceanicMuseum_1F_Text_17EC98:: @ 817EC98
	.string "Eine seltsame Vorrichtung rotiert unter\n"
	.string "einer Glaskuppel.\p"
	.string "Vielleicht misst sie die Tiefe von\n"
	.string "irgendetwas...$"
