SSTidalLowerDeck_Text_1993C1:: @ 81993C1
	.string "Arrgh! Ich habe die Schnauze voll und\n"
	.string "bin hundemüde vom Putzen.\p"
	.string "Ein Kampf ist jetzt genau das Richtige!$"

SSTidalLowerDeck_Text_19941A:: @ 819941A
	.string "Brüderchen, ich habe verloren!$"

SSTidalLowerDeck_Text_19942E:: @ 819942E
	.string "Wir sind die GEBRÜDER SAUBERMANN!\p"
	.string "Der Ältere verteilt die Schmierseife und\n"
	.string "der Jüngere schrubbt das Deck!$"

SSTidalLowerDeck_Text_199491:: @ 8199491
	.string "Dies ist der untere Bereich des Schiffs.\n"
	.string "Hier gibt es sehr viel Platz.\l"
	.string "Genau richtig für einen POKéMON-Kampf.$"

SSTidalLowerDeck_Text_1994F7:: @ 81994F7
	.string "Oh, großer Bruder. Ich habe verloren.$"

SSTidalLowerDeck_Text_199508:: @ 8199508
	.string "Wir sind die GEBRÜDER SAUBERMANN!\p"
	.string "Der Ältere verteilt die Schmierseife und\n"
	.string "der Jüngere schrubbt das Deck!$"
