VerdanturfTown_FriendshipRatersHouse_Text_178A9C:: @ 8178A9C
	.string "Zeig mir doch mal dein POKéMON.\n"
	.string "Ich prüfe, wie sehr es dich mag.\p"
	.string "Oh.\n"
	.string "Dein POKéMON...$"

VerdanturfTown_FriendshipRatersHouse_Text_178AF2:: @ 8178AF2
	.string "Es liebt dich über alles.\n"
	.string "Mehr lieben könnte es dich gar nicht.\l"
	.string "Das zu sehen, macht mich glücklich.$"

VerdanturfTown_FriendshipRatersHouse_Text_178B43:: @ 8178B43
	.string "Es scheint sehr glücklich zu sein.\n"
	.string "Es mag dich wirklich sehr.$"

VerdanturfTown_FriendshipRatersHouse_Text_178B82:: @ 8178B82
	.string "Es mag dich.\n"
	.string "Es möchte von dir verwöhnt werden.$"

VerdanturfTown_FriendshipRatersHouse_Text_178BC4:: @ 8178BC4
	.string "Es gewöhnt sich langsam an dich.\n"
	.string "Es glaubt an dich.$"

VerdanturfTown_FriendshipRatersHouse_Text_178BFA:: @ 8178BFA
	.string "Es hat sich noch nicht an dich gewöhnt.\n"
	.string "Weder liebt es dich, noch hasst es dich.$"

VerdanturfTown_FriendshipRatersHouse_Text_178C39:: @ 8178C39
	.string "Es schwankt in seinen Gefühlen.\n"
	.string "Es hat eine beängstigende Bösartigkeit\l"
	.string "in den Augen. Es mag dich nicht.$"

VerdanturfTown_FriendshipRatersHouse_Text_178C90:: @ 8178C90
	.string "Es fällt mir schwer, das zu sagen...\p"
	.string "Dein POKéMON hasst dich. Das ist nicht\n"
	.string "gerade angenehm für dich, oder?$"

VerdanturfTown_FriendshipRatersHouse_Text_178CFD:: @ 8178CFD
	.string "PIKACHU: Pika pika!$"
