PacifidlogTown_House3_Text_WillingToTradeIt:: @ 817940E
	.string "Hallo, TRAINER. Würdest du POKéMON\n"
	.string "mit mir tauschen?\p"
	.string "Da ich in FLOSSBRUNN lebe, kann ich nur\n"
	.string "bestimmte POKéMON fangen.\p"
	.string "{STR_VAR_1}? Hast du das POKéMON?\n"
	.string "Ich gebe dir mein {STR_VAR_2} dafür.$"

PacifidlogTown_House3_Text_MonIsSoFluffy:: @ 81794C4
	.string "Wow!\n"
	.string "Das {STR_VAR_1} ist so weich!$"

PacifidlogTown_House3_Text_ThatsNoMon:: @ 81794DF
	.string "Das ist kein {STR_VAR_1}.$"

PacifidlogTown_House3_Text_ImDisappointed:: @ 81794ED
	.string "Ich bin ein bisschen enttäuscht.$"

PacifidlogTown_House3_Text_NowWereFriends:: @ 817950A
	.string "Seit wir POKéMON getauscht haben, sind\n"
	.string "wir Freunde, nicht wahr?$"

PacifidlogTown_House3_Text_IsThatAPokedex:: @ 8179541
	.string "Ist das ein POKéDEX?\p"
	.string "Hast du schon viele verschiedene\n"
	.string "POKéMON getroffen?\p"
	.string "Ich wollte, ich wäre wie du.$"
