Route110_TrickHousePuzzle1_Text_SallyIntro:: @ 819CB4F
	.string "Ich habe mir den Weg zum Sieg mit dem\n"
	.string "ZERSCHNEIDER, den wir gerade gelernt\l"
	.string "haben, gebahnt.$"

Route110_TrickHousePuzzle1_Text_SallyDefeat:: @ 819CB93
	.string "Warum nimmst du das so ernst?$"

Route110_TrickHousePuzzle1_Text_SallyPostBattle:: @ 819CBAB
	.string "Ich werde des Hackens und\n"
	.string "Schneidens nie müde!$"

Route110_TrickHousePuzzle1_Text_EddieIntro:: @ 819CBD6
	.string "Ich bin nur zufällig in diesem\n"
	.string "verrückten Haus gelandet...$"

Route110_TrickHousePuzzle1_Text_EddieDefeat:: @ 819CC06
	.string "Und nun habe ich verloren...$"

Route110_TrickHousePuzzle1_Text_EddiePostBattle:: @ 819CC1B
	.string "Ich bin vom Weg abgekommen, ich habe\n"
	.string "verloren und bin verloren. Ich finde den\l"
	.string "Ausgang nicht mehr...$"

Route110_TrickHousePuzzle1_Text_RobinIntro:: @ 819CC68
	.string "Wer ist dieser RÄTSELMEISTER bloß?$"

Route110_TrickHousePuzzle1_Text_RobinDefeat:: @ 819CC86
	.string "Ich verlor ganz gedankenverloren.$"

Route110_TrickHousePuzzle1_Text_RobinPostBattle:: @ 819CCAA
	.string "Du bist stark!\n"
	.string "Wer bist du eigentlich?$"

Route110_TrickHousePuzzle1_Text_WroteSecretCodeLockOpened: @ 819CCCB
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist gewieft.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
