OldaleTown_House1_EventObjects:: @ 8385C4C
	object_event 1, EVENT_OBJ_GFX_WOMAN_3, 0, 6, 4, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, OldaleTown_House1_EventScript_152EEC, 0

OldaleTown_House1_MapWarps:: @ 8385C64
	warp_def 3, 8, 0, 0, MAP_OLDALE_TOWN
	warp_def 4, 8, 0, 0, MAP_OLDALE_TOWN

OldaleTown_House1_MapEvents:: @ 8385C74
	map_events OldaleTown_House1_EventObjects, OldaleTown_House1_MapWarps, 0x0, 0x0
