MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree:: @ 818D536
	.string "My little sister exchanges MAIL with\n"
	.string "her boyfriend in FORTREE.\p"
	.string "I don't envy her one bit at all.$"

MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth:: @ 818D596
	.string "Even though I can't see my friend in\n"
	.string "FORTREE, my POKéMON carries MAIL back\l"
	.string "and forth for us.\p"
	.string "I'm not lonesome, even though we're\n"
	.string "apart.$"

MossdeepCity_House2_Text_Wingull:: @ 818D61E
	.string "WINGULL: Pihyoh!$"
