AbandonedShip_Corridors_1F_MapScripts:: @ 815E964
	.byte 0

AbandonedShip_Corridors_1F_EventScript_15E965:: @ 815E965
	msgbox AbandonedShip_Corridors_1F_Text_1984D8, 2
	end

AbandonedShip_Corridors_1F_EventScript_15E96E:: @ 815E96E
	trainerbattle 0, TRAINER_CHARLIE, 0, AbandonedShip_Corridors_1F_Text_19843D, AbandonedShip_Corridors_1F_Text_198479
	msgbox AbandonedShip_Corridors_1F_Text_198493, 6
	end
