AbandonedShip_Corridors_1F_Text_CharlieIntro:: @ 819843D
	.string "What's so funny about having my inner\n"
	.string "tube aboard the ship?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat:: @ 8198479
	.string "Whoa, you overwhelmed me!$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle:: @ 8198493
	.string "It's not easy throwing POKé BALLS\n"
	.string "while hanging on to an inner tube!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere:: @ 81984D8
	.string "Isn't it fun here?\n"
	.string "I get excited just being here!$"
