RustboroCity_Flat2_2F_Text_185421:: @ 8185421
	.string "Vor langer, langer Zeit war DEVON eine\n"
	.string "kleine, überschaubare Firma.$"

RustboroCity_Flat2_2F_Text_185461:: @ 8185461
	.string "Mein Papa arbeitet für die CORPORATION.\p"
	.string "Mein Papa hat dies gemacht! Ich kann\n"
	.string "damit aber nichts anfangen, daher\l"
	.string "schenke ich es dir.$"

RustboroCity_Flat2_2F_Text_1854C4:: @ 81854C4
	.string "Mein Papa arbeitet für die CORPORATION.\p"
	.string "Wenn ich groß bin, werde ich auch für\n"
	.string "DEVON arbeiten.$"
