LilycoveCity_House3_EventObjects:: @ 838A110
	object_event 1, EVENT_OBJ_GFX_BOY_5, 0, 3, 4, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, LilycoveCity_House3_EventScript_159CE5, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_2, 0, 7, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 0, 0, LilycoveCity_House3_EventScript_159BF3, 0
	object_event 3, EVENT_OBJ_GFX_BOY_5, 0, 1, 4, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, LilycoveCity_House3_EventScript_159C7D, 0
	object_event 4, EVENT_OBJ_GFX_BOY_5, 0, 2, 5, 3, MOVEMENT_TYPE_FACE_UP, 1, 1, 0, 0, LilycoveCity_House3_EventScript_159CB1, 0
	object_event 5, EVENT_OBJ_GFX_BOY_5, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, LilycoveCity_House3_EventScript_159C49, 0
	object_event 6, EVENT_OBJ_GFX_MAN_1, 0, 7, 5, 3, MOVEMENT_TYPE_FACE_LEFT, 1, 1, 0, 0, LilycoveCity_House3_EventScript_159C32, 0

LilycoveCity_House3_MapWarps:: @ 838A1A0
	warp_def 3, 7, 0, 10, MAP_LILYCOVE_CITY
	warp_def 4, 7, 0, 10, MAP_LILYCOVE_CITY

LilycoveCity_House3_MapEvents:: @ 838A1B0
	map_events LilycoveCity_House3_EventObjects, LilycoveCity_House3_MapWarps, 0x0, 0x0
