VerdanturfTown_ContestHall_Text_177FB4:: @ 8177FB4
	.string "An welchem WETTBEWERB nimmst du teil?\n"
	.string "Darf ich dir einen Rat geben?\p"
	.string "In jedem WETTBEWERB, zum Beispiel im\n"
	.string "WETTBEWERB für ANMUT, bewerten sie im\l"
	.string "ersten Durchlauf nicht nur die Anmut.\p"
	.string "Du solltest daher Wege finden, deine\n"
	.string "POKéMON besser aufzuziehen.$"

VerdanturfTown_ContestHall_Text_178091:: @ 8178091
	.string "Ich habe meine POKéMON zur Anmut\n"
	.string "erzogen.\p"
	.string "Man kann seine POKéMON an einem WETT-\n"
	.string "BEWERB für ANMUT teilnehmen lassen!\p"
	.string "Ich bin so froh, dass ich meine POKéMON\n"
	.string "liebevoll aufgezogen habe.$"

VerdanturfTown_ContestHall_Text_178120:: @ 8178120
	.string "Mein POKéMON ist der Kracher!\p"
	.string "Es ist cool, stark, schön, anmutig und\n"
	.string "klug. Alles in einem!\p"
	.string "Ich werde mit ihm sämtliche\n"
	.string "WETTBEWERBE gewinnen!$"

VerdanturfTown_ContestHall_Text_1781A5:: @ 81781A5
	.string "POKéMON WETTBEWERBE\n"
	.string "BÜHNE für die NORMAL-KLASSE!$"
