gAbilityDescription_None: @ 81F99CC
	.string "Keine Spezial-Fähigkeit.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Wehrt wilde POKéMON ab.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Ruft im Kampf Regen herbei.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Erhöht INIT. nach und nach.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "Wehrt Volltreffer ab.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Keine 1-Treffer-K.O.-Att.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Gegen Selbstzerstörung.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Verhindert Paralyse.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "Erh. Fluchtw. i. Sandsturm.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "Paralysiert bei Berührung.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Wandelt Elektriz. in KP um.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Wandelt Wasser in KP um.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Verhindert Anziehung.$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "Keine Wetter-Effekte.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Steigert Genauigkeit.$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "Verhindert Einschlafen.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Ändert Att.-Typ d. Gegners.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Verhindert Vergiftungen.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Steigt, wenn v. Feuer getr.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Gegen Zusatz-Effekte.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Verhindert Verwirrung.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Verankert den Körper.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Senkt ANGR. des Gegners.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Hindert Gegner an Flucht.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Verletzt bei Berührung.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "Nur sehr eff. Treff. schad.$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "Kein Treffer b. BODEN-Att.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "Gibt bei Kontakt Sporen ab.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Gibt Stat.-Probleme weiter.$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "Verhindert Fähigk.-Reduk.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Heilt bei Austausch.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Zieht Elektro-Attacken an.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Verstärkt Zusatz-Effekte.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Steigert INIT. bei Regen.$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "INIT. + bei Sonnenschein.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Mehr PKMN-Begegnungen.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Kopiert Spezial-Attacke.$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "Steigert ANGR.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "Vergiftet bei Berührung.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Verhindert Zurückschreck.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Verhindert Einfrieren.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Verhindert Verbrennungen.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Fängt STAHL-POKéMON.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Immun gg. Lärm-Attacken.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "KP-Anstieg bei Regen.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Erzeugt einen Sandsturm.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Steigert AP des Gegners.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Schutz vor Hitze und Kälte.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Schnelles Aufwachen.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "Verbrennt bei Berührung.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Erleichtert das Entkommen.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Verhindert Verl. d. Genauig.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Verhindert ANGR.-Reduz.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "Kann Objekte aufnehmen.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Greift in jedem 2. Zug an.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Tauscht Genauigk. u. Kraft.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "Wirkt bei Kontakt betörend.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Bildet ein Team mit MINUN.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Bildet ein Team mit PLUSLE.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Ist vom Wetter abhängig.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Verhindert ITEM-Diebstahl.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "Heilt durch Häutung.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "Steigert ANGR. bei Leiden.$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "Steigert VERT. bei Leiden.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Saug-Attacken schädigen.$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "Erhöht PFL.-Att. i. d. Not.$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "Erhöht FEUER-Att. in Not.$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "Erhöht WASSER-Att. in Not.$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "Erhöht KÄFER-Att. in Not.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Verh. Rückstoß-Schaden.$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Erzeugt Sonne im Kampf.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Verhindert Flucht.$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Verhindert Einschlafen.$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Verhindert Fähigk.-Reduz.$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "Steigert ANGR.$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Wehrt Volltreffer ab.$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "Immun gg. Lärm-Attacken.$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "Kehrt Wetter-Effekte um.$"

	.align 2
gAbilityDescriptions:: @ 81FA110
	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Cacophony
	.4byte gAbilityDescription_AirLock
