MtChimney_Text_1B2DEE:: @ 81B2DEE
	.string "Die Kraft, die in diesem METEORITEN\n"
	.string "steckt...\p"
	.string "Wenn man diese Kraft mit dieser\n"
	.string "Maschine verstärkt, kann man die\l"
	.string "Aktivität des SCHLOTBERGs stoppen.\p"
	.string "Hahaha... Und dann füllt sich der ausge-\n"
	.string "kühlte Krater mit Regenwasser und gibt\l"
	.string "den WASSER-POKéMON Lebensraum.$"

MtChimney_Text_1B2ED9:: @ 81B2ED9
	.string "ADRIAN: Du schon wieder...\p"
	.string "Hör gut zu.\n"
	.string "Das Meer bringt alles Leben hervor.\p"
	.string "Wasser bedeutet Leben!\n"
	.string "Es besitzt absolute Priorität!\p"
	.string "Daher widmet sich TEAM AQUA der Auf-\n"
	.string "gabe, die Meere zu vergrößern.\p"
	.string "So können sich neue POKéMON-Arten\n"
	.string "entwickeln.\p"
	.string "Wir wollen die Welt zum Wohle der\n"
	.string "POKéMON umgestalten.\p"
	.string "Das ist die große Vision von TEAM AQUA!\p"
	.string "Ich kann einem sturen Kind wie dir nicht\n"
	.string "erlauben, sich uns in den Weg zu stellen.\p"
	.string "Ich, ADRIAN, werde dir zeigen, was\n"
	.string "passiert, wenn du uns aufhalten willst!$"

MtChimney_Text_1B3099:: @ 81B3099
	.string "Wie bitte?!?\p"
	.string "Ich, ADRIAN, wurde ganz hinterhältig\n"
	.string "besiegt?!?$"

MtChimney_Text_1B30C2:: @ 81B30C2
	.string "ADRIAN: Ach, was soll’s.\n"
	.string "Ich werde für heute meine Pläne am\l"
	.string "SCHLOTBERG vergessen. Für heute!\p"
	.string "Niemand wird uns jemals stoppen!\n"
	.string "TEAM AQUA wird siegen!!!\p"
	.string "Vergiss das nicht!!!$"

MtChimney_Text_1B3168:: @ 81B3168
	.string "Hahahaha!\p"
	.string "Hast du dich den ganzen Weg hier\n"
	.string "heraufgequält?\p"
	.string "So ein Jammer. Du kommst zu spät.\n"
	.string "Ich habe den METEORITEN aus METEOR-\l"
	.string "FÄLLE bereits unserem BOSS gegeben!$"

MtChimney_Text_1B31EA:: @ 81B31EA
	.string "Hahaha...\n"
	.string "Da habe ich wohl verloren...\p"
	.string "Gut, dass ich dich nicht schon in\n"
	.string "METEORFÄLLE herausgefordert habe.$"

MtChimney_Text_1B3239:: @ 81B3239
	.string "Hahaha!\p"
	.string "Du hast mich besiegt, aber gegen\n"
	.string "unseren BOSS hast du keine Chance!\p"
	.string "Wenn du dich jetzt leise aus dem Staub\n"
	.string "machst, vermeidest du jede Menge Ärger.$"

MtChimney_Text_1B32C8:: @ 81B32C8
	.string "Wir vom TEAM AQUA setzen unsere\n"
	.string "Energie zum Wohle aller ein.\p"
	.string "Wenn es mehr Wasser gibt, sind die\n"
	.string "WASSER-POKéMON glücklicher und die\l"
	.string "Menschen hätten mehr Platz zum\l"
	.string "Schwimmen.$"

MtChimney_Text_1B336E:: @ 81B336E
	.string "Bitte?\n"
	.string "Was heißt das? Ich habe verloren?$"

MtChimney_Text_1B338D:: @ 81B338D
	.string "Unser BOSS sagt: “So wird jeder\n"
	.string "glücklich sein...”\p"
	.string "Aber warum versucht dann jeder, uns\n"
	.string "aufzuhalten?$"

MtChimney_Text_1B33EA:: @ 81B33EA
	.string "Dieses nervtötende TEAM MAGMA! Jedes\n"
	.string "Mal versuchen sie, uns zu stoppen!$"

MtChimney_Text_1B3427:: @ 81B3427
	.string "METEORITEN stecken voller Energie.$"

MtChimney_Text_1B3446:: @ 81B3446
	.string "Los! Stampfen wir TEAM MAGMA in den\n"
	.string "Boden! Und vergrößern die Meere!$"

MtChimney_Text_1B3470:: @ 81B3470
	.string "Komm uns nicht in die Quere, okay?\p"
	.string "Wir versuchen, das Meer zum Wohle aller\n"
	.string "zu vergrößern!$"

MtChimney_Text_1B34C6:: @ 81B34C6
	.string "Yeah!\n"
	.string "Jeder wird nass!$"

MtChimney_Text_1B34DC:: @ 81B34DC
	.string "Wir werden die Meere vergrößern.$"

MtChimney_Text_1B3503:: @ 81B3503
	.string "Bushaa!$"

MtChimney_Text_1B350B:: @ 81B350B
	.string "MARC: Oh, {PLAYER}{KUN}!\p"
	.string "Bitte, halte TEAM AQUA für mich auf!\p"
	.string "Sie versuchen, mit der Kraft des\n"
	.string "gestohlenen METEORITEN den Vulkan\l"
	.string "zu inaktivieren!$"

MtChimney_Text_1B3598:: @ 81B3598
	.string "MARC: Oh, {PLAYER}{KUN}!\p"
	.string "Bitte, halte TEAM AQUA für mich auf!\p"
	.string "Diese drei Schurken sind selbst für mich\n"
	.string "eine harte Nuss!$"

MtChimney_Text_1B3608:: @ 81B3608
	.string "MARC: {PLAYER}{KUN}!\p"
	.string "Mit deiner Hilfe konnte ich die Pläne\n"
	.string "von TEAM AQUA durchkreuzen!\p"
	.string "Aber... Dieser Sieg bedeutet nicht, dass\n"
	.string "sie ihre üblen Pläne aufgeben werden.\p"
	.string "Wir werden ein wachsames Auge auf TEAM\n"
	.string "AQUA haben und sie weiter verfolgen.\p"
	.string "{PLAYER}{KUN}, wir werden uns wieder sehen!$"

MtChimney_Text_1B36F1:: @ 81B36F1
	.string "Mist... TEAM AQUA ist uns zahlenmäßig\n"
	.string "überlegen! Wir können es nicht mit ihnen\l"
	.string "aufnehmen!$"

MtChimney_Text_1B372E:: @ 81B372E
	.string "Wenn sie die Meere vergrößern, gibt es\n"
	.string "weniger Lebensraum für POKéMON und\l"
	.string "Menschen!$"

MtChimney_Text_1B3778:: @ 81B3778
	.string "TEAM AQUA versucht, die Meere zu ver-\n"
	.string "größern... Sind die krank im Hirn?$"

MtChimney_Text_1B37B4:: @ 81B37B4
	.string "Bufoh!$"
