FallarborTown_ContestLobby_Text_1A5DFC:: @ 81A5DFC
	.string "Hallo! Wir nehmen Anmeldungen für die\n"
	.string "{STR_VAR_1}-KLASSE POKéMON\l"
	.string "WETTBEWERBE entgegen.$"

FallarborTown_ContestLobby_Text_1A5E46:: @ 81A5E46
	.string "Soll eines deiner POKéMON an einem der\n"
	.string "WETTBEWERBE teilnehmen?$"

FallarborTown_ContestLobby_Text_1A5E7C:: @ 81A5E7C
	.string "Welches Thema möchtest du dir ansehen?$"

FallarborTown_ContestLobby_Text_1A5E98:: @ 81A5E98
	.string "In einem POKéMON WETTBEWERB zeigen\n"
	.string "4 TRAINER jeweils eines ihrer POKéMON\l"
	.string "einer Jury.\p"
	.string "Der WETTBEWERB besteht aus zwei\n"
	.string "Durchläufen.\p"
	.string "Im ersten Durchlauf wird geprüft, wie\n"
	.string "gut das POKéMON beim Publikum ankommt.\p"
	.string "Im zweiten Durchlauf muss das POKéMON\n"
	.string "mit der Ausdruckskraft seiner Attacken\l"
	.string "überzeugen.\p"
	.string "Die Attacken müssen sorgfältig gewählt\n"
	.string "werden, damit sie dem JUROR ins Auge\l"
	.string "fallen und das Publikum begeistern. Ver-\l"
	.string "suche, die Attacken gut zu platzieren.\p"
	.string "Am Ende werden die Ergebnisse beider\n"
	.string "Durchläufe addiert.\p"
	.string "Das POKéMON mit dem besten Ergebnis\n"
	.string "wird zum Gewinner erklärt.$"

FallarborTown_ContestLobby_Text_1A609B:: @ 81A609B
	.string "Es gibt fünf verschiedene WETTBEWERBE.\p"
	.string "COOLNESS, SCHÖNHEIT, ANMUT, KLUGHEIT\n"
	.string "und STÄRKE heißen die Kategorien.\p"
	.string "Wähle einen WETTBEWERB, der deinem\n"
	.string "POKéMON am besten liegt.$"

FallarborTown_ContestLobby_Text_1A613F:: @ 81A613F
	.string "Die POKéMON WETTBEWERBE sind in vier\n"
	.string "Klassen aufgeteilt.\p"
	.string "NORMAL, SUPER, HYPER und MASTER.\p"
	.string "In der NORMAL-KLASSE kann jedes\n"
	.string "POKéMON antreten.\p"
	.string "Jedes POKéMON, das die NORMAL-KLASSE\n"
	.string "gewonnen hat, kann in der SUPER-KLASSE\l"
	.string "derselben Kategorie antreten.\p"
	.string "Genauso kann das POKéMON, das in der\n"
	.string "SUPER-KLASSE gewonnen hat, in der\l"
	.string "HYPER-KLASSE und nach einem Sieg\p"
	.string "dort in der MASTER-KLASSE antreten.\n"
	.string "Immer in derselben Kategorie.\p"
	.string "Ein POKéMON, das in der MASTER-KLASSE\n"
	.string "gewonnen hat, kann sooft es sein\l"
	.string "TRAINER mag, wieder dort antreten.$"

FallarborTown_ContestLobby_Text_1A6319:: @ 81A6319
	.string "Welches POKéMON soll teilnehmen?$"

FallarborTown_ContestLobby_Text_1A6340:: @ 81A6340
	.string "Jeder, der eine WETTBEWERBSKARTE\n"
	.string "besitzt, darf teilnehmen.\p"
	.string "Du bekommst die WETTBEWERBSKARTE\n"
	.string "kostenlos in der WETTBEWERBSHALLE für\l"
	.string "die NORMAL-KLASSE in WIESENFLUR.\p"
	.string "Bitte hol dir die KARTE dort ab und komm\n"
	.string "dann wieder.$"

LilycoveCity_ContestLobby_Text_1A63F4:: @ 81A63F4
	.string "Ich akzeptiere nur Anmeldungen von\n"
	.string "vier Spielern, die via Link verbunden\l"
	.string "sind und am POKéMON WETTBEWERB\l"
	.string "teilnehmen wollen.\p"
	.string "Jeder, der eine WETTBEWERBSKARTE\n"
	.string "besitzt, darf teilnehmen.\p"
	.string "Du bekommst die WETTBEWERBSKARTE\n"
	.string "kostenlos in der WETTBEWERBSHALLE für\l"
	.string "die NORMAL-KLASSE in WIESENFLUR.\p"
	.string "Bitte hol dir die KARTE dort ab und komm\n"
	.string "dann wieder.$"

FallarborTown_ContestLobby_Text_1A64F4:: @ 81A64F4
	.string "Jeder, der eine WETTBEWERBSKARTE\n"
	.string "besitzt, darf teilnehmen.\p"
	.string "Wenn du keine hast, kann ich dir sofort\n"
	.string "eine ausstellen.\p"
	.string "Möchtest du eine WETTBEWERBSKARTE\n"
	.string "haben?$"

FallarborTown_ContestLobby_Text_1A6583:: @ 81A6583
	.string "Bitte schön!$"

FallarborTown_ContestLobby_Text_1A6590:: @ 81A6590
	.string "Oh!\p"
	.string "Aber du besitzt ja bereits eine WETT-\n"
	.string "BEWERBSKARTE, {PLAYER}.\p"
	.string "Bitte bring die KARTE das nächste Mal\n"
	.string "mit.$"

FallarborTown_ContestLobby_Text_1A65EA:: @ 81A65EA
	.string "Bitte komm vorbei, wann immer du an\n"
	.string "einem WETTBEWERB teilnehmen möchtest.$"

FallarborTown_ContestLobby_Text_1A6623:: @ 81A6623
	.string "An welchem WETTBEWERB möchtest du\n"
	.string "teilnehmen?$"

FallarborTown_ContestLobby_Text_1A664A:: @ 81A664A
LilycoveCity_ContestLobby_Text_1A664A:: @ 81A664A
	.string "Tut mir schrecklich Leid, aber dein\n"
	.string "POKéMON kann hier noch nicht\l"
	.string "antreten...$"

FallarborTown_ContestLobby_Text_1A669F:: @ 81A669F
LilycoveCity_ContestLobby_Text_1A669F:: @ 81A669F
	.string "Tut mit Leid, aber ein EI kann nicht an\n"
	.string "einem WETTBEWERB teilnehmen.$"

FallarborTown_ContestLobby_Text_1A66DC:: @ 81A66DC
LilycoveCity_ContestLobby_Text_1A66DC:: @ 81A66DC
	.string "Dein POKéMON ist nicht in der Lage, an\n"
	.string "einem WETTBEWERB teilzunehmen...$"

FallarborTown_ContestLobby_Text_1A6724:: @ 81A6724
	.string "Oh, aber das BAND...\p"
	.string "Dein POKéMON hat diesen WETTBEWERB\n"
	.string "schon einmal gewonnen, oder?\p"
	.string "Möchtest du es trotzdem für diesen\n"
	.string "WETTBEWERB anmelden?$"

FallarborTown_ContestLobby_Text_1A67A3:: @ 81A67A3
LilycoveCity_ContestLobby_Text_1A67A3:: @ 81A67A3
	.string "Ist das dein WETTBEWERBS-POKéMON?$"

FallarborTown_ContestLobby_Text_1A67C1:: @ 81A67C1
	.string "Okay, dein POKéMON wird an diesem\n"
	.string "WETTBEWERB teilnehmen.\p"
	.string "Dein POKéMON ist die Nummer 4.\n"
	.string "Der WETTBEWERB wird in Kürze starten.$"

FallarborTown_ContestLobby_Text_1A6832:: @ 81A6832
LilycoveCity_ContestLobby_Text_1A6832:: @ 81A6832
SlateportCity_ContestLobby_Text_1A6832:: @ 81A6832
VerdanturfTown_ContestLobby_Text_1A6832:: @ 81A6832
	.string "Bitte folge mir, und viel Glück!$"

FallarborTown_ContestLobby_Text_1A685A:: @ 81A685A
	.string "Herzlichen Glückwunsch! Dein POKéMON\n"
	.string "hat den WETTBEWERB gewonnen!\p"
	.string "Und hier haben wir deinen Preis.\n"
	.string "Bitte, komm hier herüber!$"

FallarborTown_ContestLobby_Text_1A68C6:: @ 81A68C6
	.string "Bitte hole deinen Preis später ab.$"

LinkContestRoom1_Text_1A68F0:: @ 81A68F0
	.string "MC: Hallo! Wir fangen nun mit einem \n"
	.string "{STR_VAR_3}-KLASSE POKéMON {STR_VAR_2}-\l"
	.string "WETTBEWERB an!\p"
	.string "Die folgenden TRAINER und ihre POKéMON\n"
	.string "nehmen teil:$"

LinkContestRoom1_Text_1A6976:: @ 81A6976
	.string "MC: Hallo! Wir fangen nun mit einem \n"
	.string "4-Spieler POKéMON {STR_VAR_2}-\l"
	.string "WETTBEWERB via Link an!\p"
	.string "Die folgenden TRAINER und ihre POKéMON\n"
	.string "nehmen teil:$"

LinkContestRoom1_Text_1A6A04:: @ 81A6A04
	.string "MC: Teilnehmer Nr. {STR_VAR_2}!\n"
	.string "{STR_VAR_3} von {STR_VAR_1}!$"

LinkContestRoom1_Text_1A6A1F:: @ 81A6A1F
	.string "MC: Nun haben wir alle vier teilnehmenden\n"
	.string "POKéMON gesehen.\p"
	.string "Zeit für die erste Bewertung!\p"
	.string "Das Publikum entscheidet, welches\n"
	.string "POKéMON am besten gefällt.\p"
	.string "Und ohne weitere Verzögerung kommen\n"
	.string "wir zu der Bewertung!$"

LinkContestRoom1_Text_1A6AE1:: @ 81A6AE1
	.string "Bewertung läuft...$"

LinkContestRoom1_Text_1A6AF5:: @ 81A6AF5
	.string "Die Bewertung ist nun abgeschlossen!\p"
	.string "Während diese ausgewertet wird, kommen\n"
	.string "wir zum zweiten Durchlauf!\p"
	.string "Im zweiten Durchlauf zeigen uns die\n"
	.string "Kontrahenten die Ausdruckskraft\l"
	.string "ihrer Attacken!\p"
	.string "Hoffen wir, dass sie uns mit ihren Vor-\n"
	.string "führungen den Atem rauben!\p"
	.string "Hoffen wir auf Enthusiasmus!\n"
	.string "Lasst die Vorführung beginnen!$"

LinkContestRoom1_Text_1A6C06:: @ 81A6C06
	.string "MC: Die Bewertung ist auch hier beendet!$"

LinkContestRoom1_Text_1A6C21:: @ 81A6C21
	.string "Herzlichen Dank an die Teilnehmer für\n"
	.string "ihre wunderbare Vorführung!\p"
	.string "Damit ist die Bewertung abgeschlossen!\n"
	.string "Vielen Dank für alles!$"

LinkContestRoom1_Text_1A6C9D:: @ 81A6C9D
	.string "Kommen wir nun zu dem, was unseren Puls\n"
	.string "höher schlagen lässt: Die Bekanntgabe\l"
	.string "der Gewinner.\p"
	.string "Der JUROR scheint für die Bekanntgabe\n"
	.string "bereit zu sein!$"

LinkContestRoom1_Text_1A6D16:: @ 81A6D16
	.string "JUROR: Ich werde nun den Sieger\n"
	.string "bekannt geben!$"

LinkContestRoom1_Text_1A6D3C:: @ 81A6D3C
	.string "MC: Teilnehmer Nr. {STR_VAR_2}!\p"
	.string "{STR_VAR_3} und {STR_VAR_1}!\n"
	.string "Herzlichen Glückwunsch!$"

LinkContestRoom1_Text_1A6D6A:: @ 81A6D6A
	.string "Wir überreichen dir hiermit dieses BAND\n"
	.string "als Zeichen deines Sieges!$"

LinkContestRoom1_Text_1A6D96:: @ 81A6D96
	.string "{PLAYER} erhält ein BAND.$"

LinkContestRoom1_Text_1A6DAC:: @ 81A6DAC
	.string "{PLAYER} steckt {STR_VAR_1} das\n"
	.string "BAND an.$"

LinkContestRoom1_Text_1A6DC5:: @ 81A6DC5
	.string "MC: Bitte schön!\n"
	.string "Bitte, dies ist dein Preis!$"

LinkContestRoom1_Text_1A6DF1:: @ 81A6DF1
	.string "MC: Herzlichen Glückwunsch!\n"
	.string "Komm bald wieder!$"

LinkContestRoom1_Text_1A6E1F:: @ 81A6E1F
	.string "Bitte hole deinen Preis später an der\n"
	.string "Rezeption ab.\l"
	.string "Und nimm bald wieder teil!$"
