UnknownString_81C5033: @ 81C5033
	.string "VATER: {PLAYER}! Schön, dich zu sehen!\n"
	.string "Hier habe ich einen Brief für dich.$"

UnknownString_81C5070: @ 81C5070
	.string "VATER: Das muss ein FAHRSCHEIN\n"
	.string "für ein Schiff sein. Aber für welches?\p"
	.string "In SEEGRASULB CITY kann dir bestimmt\n"
	.string "jemand mehr dazu sagen.$"

LilycoveCity_Harbor_Text_1C50F2:: @ 81C50F2
	.string "Die Fähre nach GRAPHITPORT CITY ist...\p"
	.string "Oh!\n"
	.string "Der FAHRSCHEIN...$"

LilycoveCity_Harbor_Text_1C5120:: @ 81C5120
	.string "Aye, Maat, hast du den alten FAHRSCHEIN\n"
	.string "mitgebracht?\p"
	.string "Ich sage dir, du bist auf dem Weg zu\n"
	.string "einer briefmarkengroßen Insel im Süden.\p"
	.string "Niemand kann sagen, was uns dort er-\n"
	.string "warten wird, aye. Und das erschüttert\l"
	.string "meine alten Knochen!\p"
	.string "Alle Mann an Bord!$"

SouthernIsland_Exterior_Text_1C5215:: @ 81C5215
	.string "Aye, Maat, auf dieser gottverlassenen\n"
	.string "Insel gibt’s nichts zu sehen und zu tun.\p"
	.string "Sollen wir nicht nach SEEGRASULB CITY\n"
	.string "zurücksegeln?$"

SouthernIsland_Exterior_Text_1C5281:: @ 81C5281
	.string "Aye, alles klar!\n"
	.string "Segeln wir nach Hause!$"

SouthernIsland_Exterior_Text_1C52A6:: @ 81C52A6
	.string "Aye, ganz wie du willst.$"

SouthernIsland_Interior_Text_1C52C5:: @ 81C52C5
	.string "“Alle Träume sind nur eine andere\n"
	.string "Realität. Vergiss das nicht...”$"

SouthernIsland_Exterior_Text_1C52FB:: @ 81C52FB
	.string "“Die, denen die Erinnerung verblasst,\n"
	.string "versuchen sie im Herzen zu halten.”$"
