MauvilleCity_PokemonCenter_1F_Text_1B092A:: @ 81B092A
	.string "Ich bin MÄRCHEN-MAN! Ich habe eine sehr\n"
	.string "geistreiche Geschichte für dich!\p"
	.string "Soll ich sie dir erzählen?$"

MauvilleCity_PokemonCenter_1F_Text_1B097C:: @ 81B097C
	.string "Oh...\n"
	.string "Du hast mir die Luft rausgelassen...$"

MauvilleCity_PokemonCenter_1F_Text_1B0998:: @ 81B0998
	.string "Und ich war in Gedanken vertieft...$"

MauvilleCity_PokemonCenter_1F_Text_1B09B0:: @ 81B09B0
	.string "Das wäre alles, glaube ich...\p"
	.string "Wir sollten bald wieder ein Schwätzchen\n"
	.string "halten! Tschüss!$"
