PetalburgCity_PokemonCenter_1F_Text_1B1C97:: @ 81B1C97
	.string "Hallo, du! TRAINER!\n"
	.string "Du hast ein wundervolles Lächeln.\p"
	.string "Ich habe ein Hobby: Ich sammle die\n"
	.string "Profile von POKéMON-TRAINERN.$"

PetalburgCity_PokemonCenter_1F_Text_1B1D10:: @ 81B1D10
	.string "Nun, wie sieht es aus?\n"
	.string "Darf ich dein Profil sehen?$"

PetalburgCity_PokemonCenter_1F_Text_1B1D3A:: @ 81B1D3A
	.string "Du erstellst dir dein eigenes Profil,\n"
	.string "indem du 4 Worte oder Phrasen\l"
	.string "zusammenstellst.\p"
	.string "Ich gebe dir ein Beispiel für ein Profil\n"
	.string "mit vier Begriffen.\p"
	.string "Du kannst diese vier Begriffe mit\n"
	.string "anderen Begriffen tauschen, ganz\l"
	.string "so, wie du dein Profil haben möchtest.\p"
	.string "Dir stehen sehr viele Begriffe\n"
	.string "zur Verfügung.\p"
	.string "Sie sind nach Gruppen sortiert, wie\n"
	.string "POKéMON, Lifestyle und Hobbies. So\l"
	.string "hast du einen besseren Überblick.\p"
	.string "Wähle zunächst eine Gruppe aus, um\n"
	.string "eine Liste entsprechender Begriffe\p"
	.string "zu öffnen. Dann triffst du deine Wahl.\p"
	.string "Suche dir beliebige Begriffe aus den\n"
	.string "Gruppen aus, um dein ganz persönliches\l"
	.string "Profil zu erstellen.$"

UnknownString_81B1F7A: @ 81B1F7A
	.string "$"

PetalburgCity_PokemonCenter_1F_Text_1B1F7B:: @ 81B1F7B
	.string "Ja! Danke schön!\n"
	.string "Zeigst du mir jetzt dein Profil?$"

PetalburgCity_PokemonCenter_1F_Text_1B1FA3:: @ 81B1FA3
	.string "Oh, nein, ehrlich?\p"
	.string "Ich dachte, jemand wie du hätte ein\n"
	.string "wundervolles Profil...$"

PetalburgCity_PokemonCenter_1F_Text_1B1FF0:: @ 81B1FF0
	.string "Oh! Du bist noch nicht so weit?\p"
	.string "Nun, dann zeig es mir doch später!$"

PetalburgCity_PokemonCenter_1F_Text_1B202F:: @ 81B202F
	.string "Hallo, da drüben! TRAINER!\p"
	.string "Du hast ein wundervolles Lächeln.$"

PetalburgCity_PokemonCenter_1F_Text_1B2063:: @ 81B2063
	.string "Darf ich dein neues Profil sehen?$"

PetalburgCity_PokemonCenter_1F_Text_1B207F:: @ 81B207F
	.string "Ja? Danke schön!\p"
	.string "Ich hoffe, das Profil ist besser als das\n"
	.string "vorhergehende.$"

PetalburgCity_PokemonCenter_1F_Text_1B20CE:: @ 81B20CE
	.string "Oh, du magst dein Profil, wie es ist?\p"
	.string "Ich mache dir keine Vorwürfe - so, wie\n"
	.string "es jetzt ist, ist das Profil wunderbar.$"

PetalburgCity_PokemonCenter_1F_Text_1B2137:: @ 81B2137
	.string "Fa-fantastisch!\p"
	.string "Dein Profil... Einfach wunderbar!\n"
	.string "Es sagt wirklich alles über dich aus.\p"
	.string "Jeder, der dieses Profil sieht, wird\n"
	.string "von dir entzückt sein!\p"
	.string "Danke schön.$"

PetalburgCity_PokemonCenter_1F_Text_1B21CC:: @ 81B21CC
	.string "Oh!\n"
	.string "Du kennst die Losung!!\p"
	.string "Das bedeutet, dass du ein Mitglied des\n"
	.string "CLUB des GEHEIMGESCHEHENS bist!$"
