gNatureName_Hardy: @ 83C0F60
	.string "ROBUST$"

gNatureName_Lonely: @ 83C0F66
	.string "SOLO$"

gNatureName_Brave: @ 83C0F6D
	.string "MUTIG$"

gNatureName_Adamant: @ 83C0F73
	.string "HART$"

gNatureName_Naughty: @ 83C0F7B
	.string "FRECH$"

gNatureName_Bold: @ 83C0F83
	.string "KÜHN$"

gNatureName_Docile: @ 83C0F88
	.string "SANFT$"

gNatureName_Relaxed: @ 83C0F8F
	.string "LOCKER$"

gNatureName_Impish: @ 83C0F97
	.string "PFIFFIG$"

gNatureName_Lax: @ 83C0F9E
	.string "LASCH$"

gNatureName_Timid: @ 83C0FA2
	.string "SCHEU$"

gNatureName_Hasty: @ 83C0FA8
	.string "HASTIG$"

gNatureName_Serious: @ 83C0FAE
	.string "ERNST$"

gNatureName_Jolly: @ 83C0FB6
	.string "FROH$"

gNatureName_Naive: @ 83C0FBC
	.string "NAIV$"

gNatureName_Modest: @ 83C0FC2
	.string "MÄSSIG$"

gNatureName_Mild: @ 83C0FC9
	.string "MILD$"

gNatureName_Quiet: @ 83C0FCE
	.string "RUHIG$"

gNatureName_Bashful: @ 83C0FD4
	.string "ZAGHAFT$"

gNatureName_Rash: @ 83C0FDC
	.string "HITZIG$"

gNatureName_Calm: @ 83C0FE1
	.string "STILL$"

gNatureName_Gentle: @ 83C0FE6
	.string "ZART$"

gNatureName_Sassy: @ 83C0FED
	.string "FORSCH$"

gNatureName_Careful: @ 83C0FF3
	.string "SACHT$"

gNatureName_Quirky: @ 83C0FFB
	.string "KAUZIG$"

	.align 2
gNatureNames:: @ 83C1004
	.4byte gNatureName_Hardy
	.4byte gNatureName_Lonely
	.4byte gNatureName_Brave
	.4byte gNatureName_Adamant
	.4byte gNatureName_Naughty
	.4byte gNatureName_Bold
	.4byte gNatureName_Docile
	.4byte gNatureName_Relaxed
	.4byte gNatureName_Impish
	.4byte gNatureName_Lax
	.4byte gNatureName_Timid
	.4byte gNatureName_Hasty
	.4byte gNatureName_Serious
	.4byte gNatureName_Jolly
	.4byte gNatureName_Naive
	.4byte gNatureName_Modest
	.4byte gNatureName_Mild
	.4byte gNatureName_Quiet
	.4byte gNatureName_Bashful
	.4byte gNatureName_Rash
	.4byte gNatureName_Calm
	.4byte gNatureName_Gentle
	.4byte gNatureName_Sassy
	.4byte gNatureName_Careful
	.4byte gNatureName_Quirky
