Route101_Text_1C4449:: @ 81C4449
	.string "PROF. BIRK: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte mit\n"
	.string "dem POKéDEX zeigen?$"

Route101_Text_1C449B:: @ 81C449B
	.string "Ach? Du hast erst so wenige POKéMON\n"
	.string "gefangen, dass es sich nicht lohnt,\l"
	.string "ihn mir zu zeigen?$"

Route101_Text_1C44DC:: @ 81C44DC
	.string "Hmhm...\p"
	.string "Oh, du hast {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen...$"

gBirchDexRatingText_LessThan10:: @ 81C4520
	.string "Du solltest mehr ins hohe Gras gehen\n"
	.string "und mehr auf POKéMON achten.$"

gBirchDexRatingText_LessThan20:: @ 81C456A
	.string "So langsam bekommst du den Bogen raus.\n"
	.string "Aber es wird immer schwieriger werden!$"

gBirchDexRatingText_LessThan30:: @ 81C45B0
	.string "Einige POKéMON tauchen nur in be-\n"
	.string "stimmten Regionen auf. Hab nur Geduld.$"

gBirchDexRatingText_LessThan40:: @ 81C45F9
	.string "Nun, er könnte mehr Einträge enthalten,\n"
	.string "aber es sieht schon eher nach einem\l"
	.string "POKéDEX aus.$"

gBirchDexRatingText_LessThan50:: @ 81C4648
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gBirchDexRatingText_LessThan60:: @ 81C467E
	.string "Verwendest du irgendwelche ANGELN?\n"
	.string "Hier gibt es viele POKéMON im Meer.$"

gBirchDexRatingText_LessThan70:: @ 81C46B9
	.string "Statt die POKéMON nur zu fangen, wie\n"
	.string "wäre es, sie sich entwickeln zu lassen?$"

gBirchDexRatingText_LessThan80:: @ 81C46FE
	.string "Der POKéDEX wird einfach fantastisch.\n"
	.string "Das habe ich im Gefühl...$"

gBirchDexRatingText_LessThan90:: @ 81C4747
	.string "Du hast so viele gefangen...\n"
	.string "Du hast ein außergewöhnliches Talent!$"

gBirchDexRatingText_LessThan100:: @ 81C4780
	.string "Warst du schon mal in der SAFARI-ZONE?\p"
	.string "Ich habe gehört, es gibt POKéMON,\n"
	.string "die man nur dort finden kann.$"

gBirchDexRatingText_LessThan110:: @ 81C47DF
	.string "Du hast die 100er Marke überschritten!\n"
	.string "Das ist ein beeindruckender POKéDEX!$"

gBirchDexRatingText_LessThan120:: @ 81C4828
	.string "Es gibt auch POKéMON, die man durch den\n"
	.string "Einsatz von ZERTRÜMMERER findet.$"

gBirchDexRatingText_LessThan130:: @ 81C4863
	.string "Du solltest einige POKéMON fangen und\n"
	.string "sie mit anderen tauschen.$"

gBirchDexRatingText_LessThan140:: @ 81C489C
	.string "Ich habe von POKéMON gehört, die sich\n"
	.string "entwickeln, wenn sie ihren TRAINER sehr\l"
	.string "lieben.$"

gBirchDexRatingText_LessThan150:: @ 81C48EB
	.string "Ich hatte keine Ahnung, dass es in der\n"
	.string "HOENN-Region so viele verschiedene\l"
	.string "POKéMON-Arten gibt.$"

gBirchDexRatingText_LessThan160:: @ 81C4936
	.string "Manchmal erscheinen einige POKéMON in\n"
	.string "großer Anzahl, wie bei einem Ausbruch.\l"
	.string "Das solltest du nicht verpassen!$"

gBirchDexRatingText_LessThan170:: @ 81C49A2
	.string "Dein POKéDEX liefert einen erstaunlich\n"
	.string "guten Einblick in die POKéMON der\l"
	.string "HOENN-Region!$"

gBirchDexRatingText_LessThan180:: @ 81C4A06
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter POKéMON-PROFESSOR qualifiziert.$"

gBirchDexRatingText_LessThan190:: @ 81C4A4F
	.string "Mit diesem POKéDEX, der schon so weit\n"
	.string "gediehen ist, bist du ein echter Profi.$"

gBirchDexRatingText_LessThan200:: @ 81C4A91
	.string "Du bist sehr nahe dran, den POKéDEX zu\n"
	.string "vervollständigen. Das fühle ich einfach.$"

gBirchDexRatingText_DexCompleted:: @ 81C4ADA
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein POKéDEX ist vollständig!$"

Route101_Text_1C4B05:: @ 81C4B05
	.string "Hmhm...\n"
	.string "Auf nationaler Ebene...\p"
	.string "Hast du {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen...$"
