gSaveText_WouldYouLikeToSave:: @ 81C6C85
	.string "Möchtest du das Spiel speichern?$"

UnknownString_81C6CA6: @ 81C6CA6
gSaveText_ThereIsAlreadyAFile:: @ 81C6CA6
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Spielstand überschreiben?$"

BattleTower_BattleRoom_Text_1C6CE1:: @ 81C6CE1
gSaveText_DontTurnOff:: @ 81C6CE1
	.string "SPEICHERN...\n"
	.string "BITTE DAS GERÄT NICHT AUSSCHALTEN.$"

BattleTower_BattleRoom_Text_1C6D05:: @ 81C6D05
gSaveText_PlayerSavedTheGame:: @ 81C6D05
	.string "{PLAYER} hat das Spiel gespeichert.$"

UnknownString_81C6D18: @ 81C6D18
	.string "Fehler beim Speichern...$"

UnknownString_81C6D26: @ 81C6D26
gSaveText_ThereIsADifferentFile:: @ 81C6D26
	.string "Es gibt schon einen anderen Spielstand.\p"
	.string "Soll er überschrieben werden?$"
