TrainerEyeDescription_0:
	.string "Emotionen beruhigen.$"
	.string "Duftende PFLANZEN-PKMN.$"
	.string "Beruhigende Aromen reini-$"
	.string "gen Körper und Geist.$"
TrainerEyeDescription_1:
	.string "Durch Stärke überzeugen!$"
	.string "Felsige GESTEINS-PKMN.$"
	.string "Während des Studiums der$"
	.string "Antike sehe ich die Welt.$"
TrainerEyeDescription_2:
	.string "Ich strenge mich stets an!$"
	.string "PKMN, die gut schwimmen.$"
	.string "Ich würde gerne ohne den$"
	.string "Reifen schwimmen können.$"
TrainerEyeDescription_3:
	.string "Ich versuche einfach alles.$"
	.string "WASSER-PKMN sind Kumpel.$"
	.string "Ich kann schwimmen! Ich$"
	.string "mag halt den Schwimmreifen!$"
TrainerEyeDescription_4:
	.string "Wir teilen die Arbeit auf.$"
	.string "Wir lieben freundliche PKMN.$"
	.string "Wir teilen die Liebe zu den$"
	.string "PKMN. Wir sind Geschwister!$"
TrainerEyeDescription_5:
	.string "Schwächen erkennen.$"
	.string "Gleichgewicht ist wichtig.$"
	.string "Mein Ziel ist es, der$"
	.string "PKMN-CHAMP zu werden.$"
TrainerEyeDescription_6:
	.string "Den Gegner umwerfen.$"
	.string "Der PKMN-Typ ist unwichtig.$"
	.string "Ich bin der beste Schüler$"
	.string "der PKMN TRAINERSCHULE.$"
TrainerEyeDescription_7:
	.string "Langsames Niederringen.$"
	.string "Nachts Furcht einflößend.$"
	.string "Ich sehe Dinge, die den$"
	.string "anderen verborgen sind...$"
TrainerEyeDescription_8:
	.string "Alles, was zum Sieg führt.$"
	.string "Hinreißende Wesen!$"
	.string "Ich habe zu Hause einen$"
	.string "Pool für meine PKMN.$"
TrainerEyeDescription_9:
	.string "Ich bringe dich vom Weg ab.$"
	.string "Niedlich, natürlich!$"
	.string "Ich liebe die SAFARI-ZONE,$"
	.string "dort werde ich bleiben.$"
TrainerEyeDescription_10:
	.string "Wer braucht Strategie?!?$"
	.string "Alle, die gut und teuer sind.$"
	.string "Ich bin reich. Und daher$"
	.string "besitze ich ein PKMN-Bett.$"
TrainerEyeDescription_11:
	.string "Durch Stärke gewinnen!$"
	.string "Habe sie nachts gefangen...$"
	.string "Große, kräftige und zähe$"
	.string "POKéMON sind die besten...$"
TrainerEyeDescription_12:
	.string "Volle Pulle zuschlagen!$"
	.string "Funky WASSER-PKMN!$"
	.string "Wenn ich nicht schwimme,$"
	.string "stemme ich Gewichte!$"
TrainerEyeDescription_13:
	.string "Immer gewinnen!$"
	.string "KAMPF-PKMN!$"
	.string "Ohne zu prahlen: Ich kann$"
	.string "10 Ziegel zerschmettern!$"
TrainerEyeDescription_14:
	.string "Ich elektrisiere dich!$"
	.string "Es sind ELEKTRO-PKMN.$"
	.string "Ich bringe die Menschen mit$"
	.string "meinen Liedern zum Weinen.$"
TrainerEyeDescription_15:
	.string "Alles niederbrennen!$"
	.string "Feuergefährliche POKéMON!$"
	.string "Neben einem Lagerfeuer$"
	.string "sollte stets Wasser stehen!$"
TrainerEyeDescription_16:
	.string "Man muss hartnäckig sein.$"
	.string "Jede Art von POKéMON.$"
	.string "PKMN, die in der Wildnis auf-$"
	.string "wachsen, werden stark!$"
TrainerEyeDescription_17:
	.string "Unsere Liebe schlägt alles.$"
	.string "Wir haben sie seit Jahren.$"
	.string "In 50 Jahren Ehe waren$"
	.string "wir den PKMN immer treu.$"
TrainerEyeDescription_18:
	.string "Wellenförmiger Angriff!$"
	.string "KÄFER-PKMN sind cool!$"
	.string "Ich gehe jeden Tag in den$"
	.string "Wald, KÄFER-PKMN fangen.$"
TrainerEyeDescription_19:
	.string "Schwächen und verwirren!$"
	.string "Solche mit irren Kräften.$"
	.string "Ich kann deine Gedanken$"
	.string "klar und deutlich lesen.$"
TrainerEyeDescription_20:
	.string "Mit vollem Einsatz kämpfen.$"
	.string "Geheimnisvolle POKéMON.$"
	.string "Wenn ich spreche,$"
	.string "setze ich Telepathie ein.$"
TrainerEyeDescription_21:
	.string "Ruhig, gesammelt vorgehen.$"
	.string "Ganz verschiedene PKMN.$"
	.string "Wir genießen die tägliche$"
	.string "Tasse Tee.$"
TrainerEyeDescription_22:
	.string "Ich kämpfe mit Köpfchen.$"
	.string "Ich liebe jedes PKMN.$"
	.string "Schreibe ich gute Noten,$"
	.string "gibt Papi mir Geld.$"
TrainerEyeDescription_23:
	.string "Mein Wissen ist Macht!$"
	.string "Jedes clevere PKMN.$"
	.string "Ich will später ein großer$"
	.string "PKMN-Forscher werden.$"
TrainerEyeDescription_24:
	.string "Wir sprechen uns ab.$"
	.string "PKMN, die wir beide mögen.$"
	.string "Wir sind Senior und Junior$"
	.string "im Studium der PKMN.$"
TrainerEyeDescription_25:
	.string "Los geht’s, meine Lieben!$"
	.string "Ich mag sie alle!$"
	.string "Auch beim Einkaufen lasse$"
	.string "ich keinen Kampf aus!$"
TrainerEyeDescription_26:
	.string "Ich kämpfe mit dem Herzen.$"
	.string "PKMN, die Liebe erfahren!$"
	.string "PKMN und Menschen müssen$"
	.string "Vertrauen aufbauen!$"
TrainerEyeDescription_27:
	.string "Ich durchschaue Gegner!$"
	.string "Die Basis des Kampfes.$"
	.string "Ich bin noch nicht bereit,$"
	.string "Jüngeren Platz zu machen.$"
TrainerEyeDescription_28:
	.string "Angriff als Verteidigung!$"
	.string "KAMPF-PKMN!$"
	.string "Ich bin alt und habe daher$"
	.string "meinen eigenen Stil.$"
TrainerEyeDescription_29:
	.string "Ich tue, was ich kann.$"
	.string "Verschiedene Arten.$"
	.string "Ich will irgendwann einen$"
	.string "ARENALEITER besiegen!$"
TrainerEyeDescription_30:
	.string "Geduld und Spucke.$"
	.string "WASSER-PKMN!$"
	.string "Niemand vor mir hat je$"
	.string "etwas Größeres gefangen!$"
TrainerEyeDescription_31:
	.string "Verteidigung ist die Basis.$"
	.string "Kraftvolle PKMN!$"
	.string "Dies war als Diät gedacht,$"
	.string "jetzt ist es mein Hobby.$"
TrainerEyeDescription_32:
	.string "Weiter, immer weiter!$"
	.string "Die Stärke von STAHL...$"
	.string "Wenn du schwitzt, musst du$"
	.string "regelmäßig etwas trinken!$"
TrainerEyeDescription_33:
	.string "Die Umgebung erforschen.$"
	.string "WASSER-PKMN!$"
	.string "Ich lasse mich nicht von$"
	.string "Strandhäschen besiegen.$"
TrainerEyeDescription_34:
	.string "Stets Offensive zeigen!$"
	.string "Nur WASSER-PKMN...$"
	.string "Ich muss jeden Tag$"
	.string "10 Kilometer schwimmen.$"
TrainerEyeDescription_35:
	.string "Geschwindigkeit ist alles!$"
	.string "Ich liebe schnelle PKMN.$"
	.string "Beim Marathon forderst du$"
	.string "dich selbst heraus.$"
TrainerEyeDescription_36:
	.string "Schneller als andere sein.$"
	.string "Ein rasend schnelles PKMN!$"
	.string "Rennt man rasend schnell,$"
	.string "wird man eins mit dem Wind.$"
TrainerEyeDescription_37:
	.string "Die Stärke der PKMN nutzen.$"
	.string "Sieh die Macht der DRACHEN!$"
	.string "Eines Tages werde ich zur$"
	.string "Legende!!!$"
TrainerEyeDescription_38:
	.string "Ich zeige dir die Technik!$"
	.string "Elegant kreisende VÖGEL.$"
	.string "Meine VOGEL-PKMN bringen$"
	.string "dem Mädchen meine Liebe!$"
TrainerEyeDescription_39:
	.string "Du wirst Gift schmecken!$"
	.string "Giftige PKMN.$"
	.string "Ich trainiere hart, um ein$"
	.string "Ninja zu werden.$"
TrainerEyeDescription_40:
	.string "Der Erstschlag siegt!$"
	.string "Schnelle KAMPF-PKMN.$"
	.string "Wenn mein PKMN verliert,$"
	.string "kämpfe ich doch weiter.$"
TrainerEyeDescription_41:
	.string "Los, los, meine PKMN!$"
	.string "Ich mag alle PKMN.$"
	.string "UV-Strahlen sind die Feinde$"
	.string "der Haut. Creme dich ein!$"
TrainerEyeDescription_42:
	.string "Keine Gnade!$"
	.string "Niedliche WASSER-PKMN.$"
	.string "Ich habe zu viele Fans, ich$"
	.string "war nämlich im Fernsehen.$"
TrainerEyeDescription_43:
	.string "Ich probiere dies und das.$"
	.string "Ich liebe alle PKMN.$"
	.string "Was liegt hinter diesem$"
	.string "hohen Berg dort?$"
TrainerEyeDescription_44:
	.string "Wir kämpfen zusammen!$"
	.string "Wir trainieren zusammen!$"
	.string "Wir lieben die gleichen PKMN$"
	.string "und verschiedene Desserts.$"
TrainerEyeDescription_45:
	.string "Ich setze Stärke ein.$"
	.string "WASSER- und KAMPF-PKMN.$"
	.string "Matrosen sind raue Typen!$"
	.string "Irgendwelche Einwände?$"
TrainerEyeDescription_46:
	.string "PKMN vor Schaden bewahren.$"
	.string "Ich liebe seltene PKMN.$"
	.string "Ich möchte seltene PKMN$"
	.string "aus aller Welt sammeln.$"
TrainerEyeDescription_47:
	.string "Meine Stärke...$"
	.string "PKMN sind meine Kinder.$"
	.string "Man benötigt Wissen und$"
	.string "Liebe im Umgang mit PKMN.$"
TrainerEyeDescription_48:
	.string "Angriff aus vollen Rohren!$"
	.string "Jedes PKMN kommt in Frage.$"
	.string "Ich gebe ihnen {POKEBLOCK}, um$"
	.string "in WETTBEWERBEN zu siegen.$"
TrainerEyeDescription_49:
	.string "Ich glaube an meine PKMN.$"
	.string "Ich liebe starke PKMN.$"
	.string "Ich bilde meine PKMN zu$"
	.string "einem Rettungsteam aus.$"
TrainerEyeDescription_50:
	.string "Ich greife in Etappen an.$"
	.string "Verschiedene Arten.$"
	.string "Umweltverschmutzern darf$"
	.string "man niemals vergeben!$"
TrainerEyeDescription_51:
	.string "Ich zeige meinen Mut.$"
	.string "Ich liebe niedliche PKMN!$"
	.string "Nach einem Kampf gehe ich$"
	.string "mit meinen PKMN schwimmen.$"
TrainerEyeDescription_52:
	.string "Blitzschnelle Attacken.$"
	.string "KÄFER-PKMN sind das Beste!$"
	.string "Um KÄFER-PKMN zu fangen,$"
	.string "musst du früh aufstehen.$"
TrainerEyeDescription_53:
	.string "Ich kämpfe mit Stärke.$"
	.string "PKMN mit hartem Körper.$"
	.string "Ich habe diese Wanderung$"
	.string "einen Monat vorbereitet.$"
TrainerEyeDescription_54:
	.string "Liebevolle Strategie!$"
	.string "Liebevolle PKMN!$"
	.string "Wir sind liebevoll!$"
	.string "Immer liebevoll!$"
TrainerEyeDescription_55:
	.string "Wir lassen alles raus.$"
	.string "Das 1. PKMN, das ich fing.$"
	.string "Die PKMN und ich sind$"
	.string "zusammen gewachsen.$"
TrainerEyeDescription_56:
	.string "Steinharte Attacken.$"
	.string "Steinharte PKMN...$"
	.string "Ich möchte durch Kämpfe$"
	.string "alles über PKMN lernen.$"
TrainerEyeDescription_57:
	.string "Direkte physische Attacke.$"
	.string "Ich baue auf KAMPF-PKMN.$"
	.string "Die Welt erwartet mich, als$"
	.string "neuen, starken Kämpfer.$"
TrainerEyeDescription_58:
	.string "Elektrisieren... Britzel...$"
	.string "Elektrizität bestimmt alles.$"
	.string "Hahahahaha! Lachen hält$"
	.string "gesund und jung!$"
TrainerEyeDescription_59:
	.string "Aggressiv kämpfen.$"
	.string "Brennen vor Leidenschaft!$"
	.string "Spül die tägliche Müdigkeit$"
	.string "in den Heißen Quellen ab.$"
TrainerEyeDescription_60:
	.string "Mein Stil ist flexibel.$"
	.string "Gleichmäßig gewachsen.$"
	.string "PKMN sind mein Leben. Mein$"
	.string "Weg des Lebens ist steinig.$"
TrainerEyeDescription_61:
	.string "Ich nutze die Initiative.$"
	.string "Anmutige Himmelstänzer.$"
	.string "Ich sehe das Auf und Ab$"
	.string "der Winde.$"
TrainerEyeDescription_62:
	.string "Wir kämpfen zusammen.$"
	.string "Immer freundliche PKMN.$"
	.string "Wir verstehen uns.$"
	.string "Und wir verstehen andere.$"
TrainerEyeDescription_63:
	.string "Würde und Respekt.$"
	.string "Ich liebe anmutige PKMN.$"
	.string "Wasserillusionen unter-$"
	.string "streichen meinen Stil.$"
TrainerEyeDescription_64:
	.string "Offensive vor Defensive.$"
	.string "Das Schöne des UNLICHTS.$"
	.string "Du kannst sagen, was du$"
	.string "willst, Macht ist alles!$"
TrainerEyeDescription_65:
	.string "Verwirrend verwirren.$"
	.string "Keine besondere Vorliebe.$"
	.string "Wie es wohl meiner Oma am$"
	.string "PYROBERG geht?$"
TrainerEyeDescription_66:
	.string "Ich setze Items ein.$"
	.string "Flammendes Inferno in Eis.$"
	.string "Der EIS-Typ entwickelt$"
	.string "sich gut an warmen Orten.$"
TrainerEyeDescription_67:
	.string "Starke Fähigkeiten nutzen.$"
	.string "Die rohe Kraft der DRACHEN.$"
	.string "Beim täglichen Kampf lerne$"
	.string "ich alles über PKMN.$"
TrainerEyeDescription_68:
	.string "Die gegn. Schwäche nutzen.$"
	.string "Das ultimative STAHL-PKMN.$"
	.string "Wenn es drauf ankommt,$"
	.string "bin ich am stärksten!$"

	.align 2
gTrainerEyeDescriptions:: @ 83E309C
	.4byte TrainerEyeDescription_0
	.4byte TrainerEyeDescription_1
	.4byte TrainerEyeDescription_2
	.4byte TrainerEyeDescription_3
	.4byte TrainerEyeDescription_4
	.4byte TrainerEyeDescription_5
	.4byte TrainerEyeDescription_6
	.4byte TrainerEyeDescription_7
	.4byte TrainerEyeDescription_8
	.4byte TrainerEyeDescription_9
	.4byte TrainerEyeDescription_10
	.4byte TrainerEyeDescription_11
	.4byte TrainerEyeDescription_12
	.4byte TrainerEyeDescription_13
	.4byte TrainerEyeDescription_14
	.4byte TrainerEyeDescription_15
	.4byte TrainerEyeDescription_16
	.4byte TrainerEyeDescription_17
	.4byte TrainerEyeDescription_18
	.4byte TrainerEyeDescription_19
	.4byte TrainerEyeDescription_20
	.4byte TrainerEyeDescription_21
	.4byte TrainerEyeDescription_22
	.4byte TrainerEyeDescription_23
	.4byte TrainerEyeDescription_24
	.4byte TrainerEyeDescription_25
	.4byte TrainerEyeDescription_26
	.4byte TrainerEyeDescription_27
	.4byte TrainerEyeDescription_28
	.4byte TrainerEyeDescription_29
	.4byte TrainerEyeDescription_30
	.4byte TrainerEyeDescription_31
	.4byte TrainerEyeDescription_32
	.4byte TrainerEyeDescription_33
	.4byte TrainerEyeDescription_34
	.4byte TrainerEyeDescription_35
	.4byte TrainerEyeDescription_36
	.4byte TrainerEyeDescription_37
	.4byte TrainerEyeDescription_38
	.4byte TrainerEyeDescription_39
	.4byte TrainerEyeDescription_40
	.4byte TrainerEyeDescription_41
	.4byte TrainerEyeDescription_42
	.4byte TrainerEyeDescription_43
	.4byte TrainerEyeDescription_44
	.4byte TrainerEyeDescription_45
	.4byte TrainerEyeDescription_46
	.4byte TrainerEyeDescription_47
	.4byte TrainerEyeDescription_48
	.4byte TrainerEyeDescription_49
	.4byte TrainerEyeDescription_50
	.4byte TrainerEyeDescription_51
	.4byte TrainerEyeDescription_52
	.4byte TrainerEyeDescription_53
	.4byte TrainerEyeDescription_54
	.4byte TrainerEyeDescription_55
	.4byte TrainerEyeDescription_56
	.4byte TrainerEyeDescription_57
	.4byte TrainerEyeDescription_58
	.4byte TrainerEyeDescription_59
	.4byte TrainerEyeDescription_60
	.4byte TrainerEyeDescription_61
	.4byte TrainerEyeDescription_62
	.4byte TrainerEyeDescription_63
	.4byte TrainerEyeDescription_64
	.4byte TrainerEyeDescription_65
	.4byte TrainerEyeDescription_66
	.4byte TrainerEyeDescription_67
	.4byte TrainerEyeDescription_68
