SootopolisCity_Mart_Text_PPUpIsGreat:: @ 818F890
	.string "PP UP is great!\p"
	.string "It raises the POWER POINTS, the PP,\n"
	.string "of a POKéMON move.$"

SootopolisCity_Mart_Text_TooScaryOutside:: @ 818F8D7
	.string "What... What is happening?$"

SootopolisCity_Mart_Text_FullRestoreItemOfDreams:: @ 818F8F2
	.string "Do you know FULL RESTORE?\p"
	.string "Full restoration of HP!\n"
	.string "Eradication of all status problems!\p"
	.string "It's truly an item of your dreams!$"

SootopolisCity_Mart_Text_DidSomethingAwaken:: @ 818F96B
	.string "This weather...\n"
	.string "Did something awaken?$"
