gEasyChatGroupWords_Battle: @ 83DC53C
	.string "HARMONIEREN$"
	.string "LOS$"
	.string "NR. 1$"
	.string "ENTSCHEIDEN$"
	.string "ICH SIEGE!$"
	.string "GEWINNEN$"
	.string "GEWINNE$"
	.string "GEWONNEN$"
	.string "GEWINNE ICH$"
	.string "SIEGE ICH$"
	.string "SIEG UNMÖGL.$"
	.string "KANN SIEGEN$"
	.string "UNTERLEGEN$"
	.string "SEELE$"
	.string "ENTSCHIEDEN$"
	.string "TRUMPFKARTE$"
	.string "NIMM DAS$"
	.string "KOMM SCHON$"
	.string "ANGRIFF$"
	.string "ERGEBEN$"
	.string "MUTIG$"
	.string "TALENTIERT$"
	.string "STRATEGIE$"
	.string "SCHLAGEN$"
	.string "PARTIE$"
	.string "SIEG$"
	.string "OFFENSIV$"
	.string "SINN$"
	.string "GEGEN$"
	.string "STREITEN$"
	.string "KRAFT$"
	.string "HERAUSFORDRG$"
	.string "STARKEN$"
	.string "ZU STARK$"
	.string "SCHONEN$"
	.string "GEGNER$"
	.string "GENIE$"
	.string "LEGENDE$"
	.string "FLUCHT$"
	.string "ZIEL$"
	.string "KÄMPFE$"
	.string "KÄMPFEN$"
	.string "BELEBEN$"
	.string "PUNKTE$"
	.string "ERNSTHAFT$"
	.string "AUFGEBEN$"
	.string "VERLUST$"
	.string "VERLIERE ICH$"
	.string "VERLOREN$"
	.string "VERLIEREN$"
	.string "WACHE$"
	.string "PARTNER$"
	.string "ABLEHNEN$"
	.string "AKZEPTIEREN$"
	.string "UNSCHLAGBAR$"
	.string "ERHALTEN$"
	.string "LEICHT$"
	.string "SCHWACH$"
	.string "ZU SCHWACH$"
	.string "LAPPALIE$"
	.string "LEITER$"
	.string "REGEL$"
	.string "ATTACKE$"
	.string "$"
