DewfordTown_House1_Text_174BA5:: @ 8174BA5
	.string "Über das harmonische Leben mit den\n"
	.string "POKéMON und der Familie auf diesem\l"
	.string "kleinen Eiland ließe sich viel erzählen.$"

DewfordTown_House1_Text_174C0D:: @ 8174C0D
	.string "Bevor ich meinen Mann geheiratet habe,\n"
	.string "lebte ich in der großen Hafenstadt\l"
	.string "GRAPHITPORT CITY.\p"
	.string "Hier auf der Insel verläuft das Leben\n"
	.string "geruhsamer. Vom wunderbaren Meer um-\l"
	.string "geben - das ist die pure Glückseligkeit!$"

DewfordTown_House1_Text_174CC8:: @ 8174CC8
	.string "ZIGZACHS: Guguuh!$"
