Common_Movement_QuestionMark:: @ 81A0831
	emote_question_mark
	step_end

Common_Movement_ExclamationMark:: @ 81A0833
	emote_exclamation_mark
	step_end

Common_Movement_Delay48:: @ 81A0835
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:: @ 81A0839
	face_player
	step_end

Common_Movement_FaceAwayPlayer:: @ 81A083B
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:: @ 81A083D
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFastestLeft:: @ 81A083F
	walk_in_place_fastest_left
	step_end

Common_Movement_WalkInPlaceFastestUp:: @ 81A0841
	walk_in_place_fastest_up
	step_end

Common_Movement_WalkInPlaceFastestRight:: @ 81A0843
	walk_in_place_fastest_right
	step_end

Common_Movement_WalkInPlaceFastestDown:: @ 81A0845
	walk_in_place_fastest_down
	step_end

Common_Movement_WalkUp6:: @ 81A0847
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:: @ 81A084E
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:: @ 81A0853
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp:: @ 81A0856
	walk_up
	step_end

Common_Movement_WalkUp2:: @ 81A0858
	walk_up
	walk_up
	step_end
