SootopolisCity_House3_Text_WallaceHasManyFansDoYou:: @ 818FB36
	.string "Du bist ein POKéMON-TRAINER, oder?\p"
	.string "Der ARENALEITER von XENEROVILLE, \n"
	.string "WASSILI, hat viele Fans.\l"
	.string "Hast du auch Fans?$"

SootopolisCity_House3_Text_YouMustBePrettyStrong:: @ 818FB9C
	.string "Oh, dann musst du aber sehr stark sein.$"

SootopolisCity_House3_Text_LonesomeTryWorkingHarder:: @ 818FBC0
	.string "Oh, meine Güte...\n"
	.string "Dann stehst du ja ganz alleine da.\p"
	.string "Streng dich einfach mehr an, dann\n"
	.string "bekommst du auch einen Fan.$"

SootopolisCity_House3_Text_TrainerFanClubWasWild:: @ 818FC1A
	.string "Die Fans strömen sogar aus KANTO und\n"
	.string "JOHTO herbei.\p"
	.string "Ich habe den TRAINER-FANCLUB in\n"
	.string "SEEGRASULB CITY besucht.\l"
	.string "Verrückte Sache...$"
