MossdeepCity_GameCorner_1F_Text_18E59A:: @ 818E59A
	.string "Als ich noch jung war, bin ich als\n"
	.string "POKéMON-TRAINER durch die Welt\l"
	.string "gereist.\p"
	.string "Nun, da ich ein alter Knabe geworden bin,\n"
	.string "beobachte ich mit Freuden die jungen\l"
	.string "TRAINER bei ihren Kämpfen.$"

MossdeepCity_GameCorner_1F_Text_18E631:: @ 818E631
	.string "Diese Tür ist verschlossen.$"

MossdeepCity_GameCorner_1F_Text_18E650:: @ 818E650
	.string "Ein TRAINER namens {STR_VAR_1} ist bei\n"
	.string "mir zu Besuch.\p"
	.string "Möchtest du einmal gegen {STR_VAR_1}\n"
	.string "antreten?$"

MossdeepCity_GameCorner_1F_Text_18E698:: @ 818E698
	.string "Du möchtest nicht kämpfen? Es ent-\n"
	.string "täuscht mich, dass ich dich nicht\l"
	.string "kämpfen sehen kann.$"

MossdeepCity_GameCorner_1F_Text_18E6DA:: @ 818E6DA
	.string "Oh, sehr gut!\p"
	.string "Aber mein Haus ist nicht sehr stabil.\p"
	.string "Könntet ihr einen 3-gegen-3-Kampf\n"
	.string "ausfechten?$"

MossdeepCity_GameCorner_1F_Text_18E741:: @ 818E741
	.string "Bevor ihr gegeneinander antretet,\n"
	.string "solltet ihr eure Spiele speichern!$"

MossdeepCity_GameCorner_1F_Text_18E777:: @ 818E777
	.string "Ich hoffe, einen guten Kampf zu sehen!$"

UnknownString_818E793: @ 818E793
	.string "{STR_VAR_1}$"

MossdeepCity_GameCorner_B1F_Text_18E796:: @ 818E796
	.string "Der Kampf endet unentschieden.$"

MossdeepCity_GameCorner_1F_Text_18E7B1:: @ 818E7B1
	.string "So, also ist es ein Unentschieden.\p"
	.string "Ein brillanter Kampf, in dem niemand\n"
	.string "auch nur einen Schritt ausgewichen ist.$"

UnknownString_818E80B: @ 818E80B
	.string "{STR_VAR_1}$"

MossdeepCity_GameCorner_1F_Text_18E80E:: @ 818E80E
	.string "Das war absolute Spitzenklasse!\p"
	.string "Ich habe mich wieder erkannt - mich in\n"
	.string "meinen jungen Jahren!$"

UnknownString_818E856: @ 818E856
	.string "{STR_VAR_1}$"

MossdeepCity_GameCorner_1F_Text_18E859:: @ 818E859
	.string "Ach, wie bedauerlich für dich!\p"
	.string "Aber es war ein guter Kampf.\n"
	.string "Ich hoffe, das nächste Mal gewinnst du.$"
