RustboroCity_House3_Text_IGivePerfectlySuitedNicknames:: @ 8185584
	.string "For my own POKéMON, I give them\n"
	.string "perfectly suited nicknames!\p"
	.string "It's my expression of, uh...\n"
	.string "originality, yes, that's it!$"

RustboroCity_House3_Text_NamingPikachuPekachu:: @ 81855FA
	.string "But giving the name PEKACHU to a\n"
	.string "PIKACHU? It seems pointless.\p"
	.string "I suppose it is good to use a name\n"
	.string "that's easy to understand, but...$"

RustboroCity_House3_Text_Pekachu:: @ 818567D
	.string "PEKACHU: Peka!$"
