Route132_MapScripts:: @ 81524E4
	.byte 0

Route132_EventScript_1524E5:: @ 81524E5
	trainerbattle_single TRAINER_GILBERT, Route132_Text_1C2AFB, Route132_Text_1C2B5B
	msgbox Route132_Text_1C2B71, MSGBOX_AUTOCLOSE
	end

Route132_EventScript_1524FC:: @ 81524FC
	trainerbattle_single TRAINER_DANA, Route132_Text_1C2BB5, Route132_Text_1C2BEA
	msgbox Route132_Text_1C2BFA, MSGBOX_AUTOCLOSE
	end

Route132_EventScript_152513:: @ 8152513
	trainerbattle_single TRAINER_RONALD, Route132_Text_1C2C32, Route132_Text_1C2C60
	msgbox Route132_Text_1C2C78, MSGBOX_AUTOCLOSE
	end

Route132_EventScript_15252A:: @ 815252A
	trainerbattle_single TRAINER_KIYO, Route132_Text_1C2CD9, Route132_Text_1C2D1F
	msgbox Route132_Text_1C2D3E, MSGBOX_AUTOCLOSE
	end
