Route132_MapScripts:: @ 81524E4
	.byte 0

Route132_EventScript_1524E5:: @ 81524E5
	trainerbattle 0, TRAINER_GILBERT, 0, Route132_Text_1C2AFB, Route132_Text_1C2B5B
	msgbox Route132_Text_1C2B71, 6
	end

Route132_EventScript_1524FC:: @ 81524FC
	trainerbattle 0, TRAINER_DANA, 0, Route132_Text_1C2BB5, Route132_Text_1C2BEA
	msgbox Route132_Text_1C2BFA, 6
	end

Route132_EventScript_152513:: @ 8152513
	trainerbattle 0, TRAINER_RONALD, 0, Route132_Text_1C2C32, Route132_Text_1C2C60
	msgbox Route132_Text_1C2C78, 6
	end

Route132_EventScript_15252A:: @ 815252A
	trainerbattle 0, TRAINER_KIYO, 0, Route132_Text_1C2CD9, Route132_Text_1C2D1F
	msgbox Route132_Text_1C2D3E, 6
	end
