AquaHideout_B1F_Text_196E6F:: @ 8196E6F
	.string "Wenn du das Geheimnis unseres\n"
	.string "VERSTECKS erfahren willst, musst du\l"
	.string "mich besiegen!$"

AquaHideout_B1F_Text_196EB6:: @ 8196EB6
	.string "Ich kann anscheinend nicht gewinnen...$"

AquaHideout_B1F_Text_196ECC:: @ 8196ECC
	.string "Das Geheimnis unseres VERSTECKS?\p"
	.string "Nun, sagen wir mal soooo...\n"
	.string "Am Ende befindet sich ein U-Boot!\p"
	.string "Aber, im Moment...\n"
	.string "Hehehehe...$"

AquaHideout_B1F_Text_196F39:: @ 8196F39
	.string "Tankbefüllung... OKAY!\n"
	.string "Proviant... OKAY!\p"
	.string "Nichts anderes mehr zu tun, als eine\n"
	.string "Nervensäge aus dem Weg zu räumen.$"

AquaHideout_B1F_Text_196F9B:: @ 8196F9B
	.string "Das war ein Schuss vor den Bug.$"

AquaHideout_B1F_Text_196FB5:: @ 8196FB5
	.string "Pah!\n"
	.string "Meine Niederlage war geplant.\p"
	.string "Ich sollte dich eh nur aufhalten!$"

AquaHideout_B1F_Text_196FFD:: @ 8196FFD
	.string "Gääähn... Hier im VERSTECK Wache zu\n"
	.string "stehen, ist ermüdend. Ich muss kämpfen.$"

AquaHideout_B1F_Text_197040:: @ 8197040
	.string "Gähn...\n"
	.string "Oh, da habe ich wohl verloren...$"

AquaHideout_B1F_Text_197056:: @ 8197056
	.string "Wenn du weiter hier herumschleichst, \n"
	.string "schnappt dich das TEAM {EVIL_TEAM}.$"
