Route110_TrickHousePuzzle2_Text_19CD46:: @ 819CD46
	.string "Welcher Schalter schließt welches Loch?$"

Route110_TrickHousePuzzle2_Text_19CD66:: @ 819CD66
	.string "Nach diesem Kampf bin ich nur noch\n"
	.string "verwirrter!$"

Route110_TrickHousePuzzle2_Text_19CD91:: @ 819CD91
	.string "Kannst du nicht alle Schalter für mich\n"
	.string "betätigen?$"

Route110_TrickHousePuzzle2_Text_19CDBF:: @ 819CDBF
	.string "Oh! Du forderst das RÄTSELHAUS schon\n"
	.string "zum zweiten Mal heraus!?!$"

Route110_TrickHousePuzzle2_Text_19CDF0:: @ 819CDF0
	.string "Du bist auch im Kämpfen so gut!?!$"

Route110_TrickHousePuzzle2_Text_19CE0D:: @ 819CE0D
	.string "Der RÄTSELMEISTER tüftelt alle Tricks\n"
	.string "in diesem Haus selber aus.$"

Route110_TrickHousePuzzle2_Text_19CE52:: @ 819CE52
	.string "Eines Tages gründe ich meine eigene\n"
	.string "ARENA. Und hier studiere ich die Fallen.$"

Route110_TrickHousePuzzle2_Text_19CE98:: @ 819CE98
	.string "Ich habe das Kämpfen nicht genug\n"
	.string "studiert!$"

Route110_TrickHousePuzzle2_Text_19CEB8:: @ 819CEB8
	.string "Du bist stark, nicht wahr?\n"
	.string "Stark genug, ein ARENALEITER zu sein.$"

UnknownString_819CEF9: @ 819CEF9
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist gefragt.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
