FortreeCity_Mart_Text_SuperRepelBetter:: @ 81861EF
	.string "SUPERSCHUTZ hält lange an, und ist auch\n"
	.string "äußerst nützlich.\p"
	.string "Es ist viel besser als normaler SCHUTZ.$"

FortreeCity_Mart_Text_StockUpOnItems:: @ 8186251
	.string "Ich horte immer mehr Items, als ich\n"
	.string "eigentlich benötige.\p"
	.string "Man weiß ja nie, was einem passieren\n"
	.string "kann. Vorsicht ist die Mutter der\l"
	.string "Porzellankiste!$"

FortreeCity_Mart_Text_RareCandyMakesMonGrow:: @ 81862CA
	.string "Ein SONDERBONBON erhöht den Level\n"
	.string "eines POKéMON sofort um 1.$"
