SootopolisCity_House1_Text_DevelopedThisTM:: @ 818F991
	.string "Seit 30 Jahren lebe ich in XENEROVILLE\n"
	.string "und verbessere meine Fähigkeiten.\p"
	.string "Ich habe eine alles erschütternde TM\n"
	.string "entwickelt. Die schenke ich dir!$"

SootopolisCity_House1_Text_ExplainBrickBreak:: @ 818FA03
	.string "TM31 enthält DURCHBRUCH! Eine schier\n"
	.string "unbeschreibliche Attacke. Horror!$"

SootopolisCity_House1_Text_Kecleon:: @ 818FA50
	.string "KECLEON: Puu puhyaah.$"
