LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "MUTTER: Siehst du, {PLAYER}?\n"
	.string "Hier ist es doch auch schön, oder nicht?$"

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "Die POKéMON machen für uns den Umzug,\n"
	.string "räumen alles ein und machen sauber.\l"
	.string "Das ist doch so etwas von praktisch!\p"
	.string "{PLAYER}, dein Zimmer ist oben.\n"
	.string "Schau es dir doch mal an, Spatz!\p"
	.string "VATI hat dir eine neue Uhr zur\n"
	.string "Begrüßung geschenkt.\l"
	.string "Vergiss nicht, sie einzustellen!$"

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "MUTTER: Nun, {PLAYER}?\p"
	.string "Bist du nicht neugierig, dein neues\n"
	.string "Zimmer zu sehen?$"

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "MUTTER: {PLAYER}, Schatz!\p"
	.string "Stell bitte die Uhr in deinem Zimmer ein.$"

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "MUTTER: Oh! {PLAYER}! {PLAYER}!\n"
	.string "Schnell! Komm schnell her!$"

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "MUTTER: Da! Da ist die ARENA von BLÜTEN-\n"
	.string "BURG CITY! Ich glaube, VATI ist im\l"
	.string "Fernsehen!$"

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "MUTTER: Oh... Schon vorbei.\p"
	.string "Ich glaube, VATI war im Fernsehen und\n"
	.string "wir haben ihn verpasst. Schade!$"

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "Ach ja.\n"
	.string "Einer von VATIS Freunden lebt hier.\p"
	.string "PROF. BIRK ist sein Name.\p"
	.string "Er lebt gleich nebenan, daher solltest\n"
	.string "du hinübergehen und dich vorstellen.$"

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "MUTTER: Bis später, Spatz!$"

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "MUTTER: Hast du dich bei PROF. BIRK\n"
	.string "vorgestellt?$"

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "MUTTER: Wie geht es dir, {PLAYER}?\n"
	.string "Du siehst müde aus.\p"
	.string "Ich denke, du solltest dich etwas\n"
	.string "ausruhen.$"

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "MUTTER: Pass auf dich auf, Schatz!$"

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "MUTTER: Oh! Hat VATI dir den ORDEN\n"
	.string "gegeben?\p"
	.string "Dann ist das hier von deiner MUTTI!$"

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "Überanstreng dich nicht, Liebes.\n"
	.string "Du kannst jederzeit nach Hause kommen.\p"
	.string "Und jetzt nichts wie los, Schatz!$"

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "Gyao, gyao gyaoh...$"

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "Gwagwah gwah...$"

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "INTERVIEWER: Das war unsere Reportage\n"
	.string "über die ARENA in BLÜTENBURG CITY.$"

UnknownString_817288C: @ 817288C
	.string "Da läuft gerade ein Film.\p"
	.string "Zwei Männer tanzen auf riesengroßen\n"
	.string "Klaviertasten.\p"
	.string "Aber es wird Zeit aufzubrechen!$"

UnknownString_81728E3: @ 81728E3
	.string "Das ist die Bedienungsanleitung für\n"
	.string "die TURBOTRETER.\p"
	.string "“Halte den B-Knopf gedrückt, um\n"
	.string "zu rennen, während du deine\l"
	.string "TURBOTRETER anhast.\p"
	.string "Binde dir die TURBOTRETER zu und wirble\n"
	.string "den Staub der Straße auf!”$"

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "VATER: Hm?\p"
	.string "Hey, das ist ja {PLAYER}!\p"
	.string "Du hast uns ja schon lange nicht mehr\n"
	.string "besucht... Du siehst irgendwie\l"
	.string "stärker aus.\p"
	.string "Das ist zumindest mein Eindruck. Aber\n"
	.string "dein alter Herr gibt noch nicht auf.\p"
	.string "Oh, ich habe hier etwas für dich.\n"
	.string "Das soll ich dir von einem MR. BRACK\l"
	.string "geben.$"

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "VATER: Hm, ein TICKET für eine Fähre?\p"
	.string "Ich weiß, dass es in GRAPHITPORT CITY\n"
	.string "und SEEGRASULB CITY Anlegestellen für\l"
	.string "Fähren gibt.\p"
	.string "{PLAYER}, wenn du den Ehrgeiz eines\n"
	.string "TRAINERS hast, dann geh zum DUELLTURM.\p"
	.string "Dort wirst du lernen, dass der Weg eines\n"
	.string "TRAINERS niemals ein Ende findet.$"

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "Ich muss jetzt wieder in die ARENA von\n"
	.string "BLÜTENBURG CITY.\p"
	.string "Ich danke dir, dass du dich während\n"
	.string "meiner Abwesenheit um das Haus\l"
	.string "kümmerst.$"

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "MUTTER: Das ist wieder typisch dein\n"
	.string "VATER...\p"
	.string "Da kommt er das erste Mal nach ewigen\n"
	.string "Zeiten nach Hause und spricht nur über\l"
	.string "POKéMON.\p"
	.string "Er sollte sich lieber ausruhen und etwas\n"
	.string "hier bleiben!$"

UnknownString_8172C50: @ 8172C50
	.string "Hier sind die Sondernachrichten.\p"
	.string "Wir haben die Meldung erhalten, dass in\n"
	.string "der HOENN-Region ein blaues FLIEGENDES\l"
	.string "POKéMON gesichtet wurde.\p"
	.string "Die Identität des POKéMON konnte\n"
	.string "bisher nicht festgestellt werden.\p"
	.string "Und damit schalten wir wieder um in\n"
	.string "unser laufendes Programm.$"

UnknownString_8172D30: @ 8172D30
	.string "Hier sind die Sondernachrichten.\p"
	.string "Wir haben die Meldung erhalten, dass in\n"
	.string "der HOENN-Region ein rotes FLIEGENDES\l"
	.string "POKéMON gesichtet wurde.\p"
	.string "Die Identität des POKéMON konnte\n"
	.string "bisher nicht festgestellt werden.\p"
	.string "Und damit schalten wir wieder um in\n"
	.string "unser laufendes Programm.$"

UnknownString_8172E0F: @ 8172E0F
	.string "Gau gau!$"
