PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon:: @ 817959B
	.string "People were saying they saw a POKéMON\n"
	.string "FLYING high above HOENN.\p"
	.string "Is it FLYING around all the time?\n"
	.string "Doesn't it need to rest somewhere?$"

PacifidlogTown_House4_Text_SkyPokemon:: @ 817961F
	.string "A sky POKéMON!\n"
	.string "A sky POKéMON!$"

PacifidlogTown_House4_Text_WhereDidYouComeFrom:: @ 817963D
	.string "Where did you come from?$"

PacifidlogTown_House4_Text_YesTown:: @ 8179656
	.string "Yes?\n"
	.string "YES TOWN?\p"
	.string "I've never heard of a place like that.$"

PacifidlogTown_House4_Text_YouHaveToComeFromSomewhere:: @ 817968C
	.string "No? That doesn't make any sense.\n"
	.string "You have to come from somewhere.\p"
	.string "Oh! Wait! You're not going to say you\n"
	.string "were born at the bottom of the sea?$"
