FallarborTown_CozmosHouse_Text_MeteoriteWillNeverBeMineNow:: @ 8177755
	.string "PROF. KOSMO: Oh...\n"
	.string "Ich hätte mich nie dazu verleiten\l"
	.string "lassen dürfen, TEAM {EVIL_TEAM} zu verraten,\l"
	.string "wo METEORITEN zu finden sind...\p"
	.string "Der METEORIT von METEORFÄLLE...\n"
	.string "Nun wird er niemals mir gehören...$"

FallarborTown_CozmosHouse_Text_IsThatMeteoriteMayIHaveIt:: @ 817780E
	.string "Oh!\n"
	.string "Oooh?\p"
	.string "Dieses Item...\p"
	.string "Kann es sein?\p"
	.string "Ist das der METEORIT, den TEAM {EVIL_TEAM}\n"
	.string "aus METEORFÄLLE entwendet hat?\p"
	.string "Bitte, darf ich den haben?\p"
	.string "Du bekommst auch etwas dafür.\n"
	.string "Was hältst du von dieser TM?$"

FallarborTown_CozmosHouse_Text_PleaseUseThisTM:: @ 81778C4
	.string "PROF. KOSMO: Mit dieser TM möchte ich\n"
	.string "dir meine Dankbarkeit ausdrücken.\l"
	.string "Bitte, nimm sie an!$"

FallarborTown_CozmosHouse_Text_ReallyGoingToHelpMyResearch:: @ 8177910
	.string "PROF. KOSMO: Oh, ich kann es einfach\n"
	.string "nicht glauben! Das ist nett! So nett!!!\p"
	.string "Das wird mir bei meinen Forschungen\n"
	.string "enorm weiterhelfen!$"

FallarborTown_CozmosHouse_Text_CrushedWithDisappointment:: @ 817797D
	.string "PROF. KOSMO: Oh, aber...\n"
	.string "Das enttäuscht mich jetzt maßlos...$"

FallarborTown_CozmosHouse_Text_MayIHaveMeteorite:: @ 81779B8
	.string "PROF. KOSMO: Bitte, darf ich den\n"
	.string "METEORITEN haben?\p"
	.string "Ich möchte ihn nicht umsonst haben! Wie\n"
	.string "wäre es mit dieser TM im Tausch dafür?$"

FallarborTown_CozmosHouse_Text_CozmoWentToMeteorFalls:: @ 8177A2B
	.string "PROF. KOSMO ist unterwegs zu\n"
	.string "METEORFÄLLE an der ROUTE 114. Einige\l"
	.string "Leute von TEAM {EVIL_TEAM} begleiten ihn.$"

FallarborTown_CozmosHouse_Text_FeelSorryForCozmo:: @ 8177A7C
	.string "Armer PROF. KOSMO...\n"
	.string "Er ist so deprimiert... Er tut mir Leid.$"

FallarborTown_CozmosHouse_Text_CozmoIsSoHappy:: @ 8177ABB
	.string "Schau dir nur PROF. KOSMO an...\n"
	.string "Er ist so glücklich! Richtig niedlich.$"
