SootopolisCity_Mart_Text_PPUpIsGreat:: @ 818F890
	.string "AP-PLUS ist sehr nützlich!\p"
	.string "Es steigert die ANGRIFFSPUNKTE, die AP\n"
	.string "einer POKéMON-Attacke.$"

SootopolisCity_Mart_Text_TooScaryOutside:: @ 818F8D7
	.string "Was... Was ist passiert?$"

SootopolisCity_Mart_Text_FullRestoreItemOfDreams:: @ 818F8F2
	.string "Kennst du TOP-GENESUNG?\p"
	.string "Alle KP werden aufgefüllt!\n"
	.string "Alle Statusprobleme werden aufgehoben!\p"
	.string "Ein wundervolles Item!$"

SootopolisCity_Mart_Text_DidSomethingAwaken:: @ 818F96B
	.string "Dieses Wetter...\n"
	.string "Wurde etwas aufgeweckt?$"
