MtPyre_1F_Text_196151:: @ 8196151
	.string "Auf den Pfaden des PYROBERG kreucht\n"
	.string "und fleucht alles Mögliche...\p"
	.string "Niemand kann sagen, was passieren wird.\n"
	.string "Dies ist für dich, es wird dir helfen.$"

MtPyre_1F_Text_1961CE:: @ 81961CE
	.string "Lass ein POKéMON das SCHUTZBAND\n"
	.string "tragen.\p"
	.string "Das hilft, wilde POKéMON fern zu halten.$"

MtPyre_1F_Text_196218:: @ 8196218
	.string "Bist du hier, um den verstorbenen\n"
	.string "POKéMON deinen Respekt zu zollen?\p"
	.string "Du musst immer sehr fürsorglich zu\n"
	.string "deinen POKéMON sein.$"

MtPyre_1F_Text_196283:: @ 8196283
	.string "Hier ruht mein ZIGZACHS. Ich habe\n"
	.string "es wirklich sehr geliebt...$"
