Route110_TrickHousePuzzle4_Text_CoraIntro:: @ 819D1DE
	.string "Ich habe keine Zeit, das zu verstehen.\n"
	.string "Ich will nur kämpfen!$"

Route110_TrickHousePuzzle4_Text_CoraDefeat:: @ 819D21F
	.string "Auch wenn ich verloren habe, liebe ich\n"
	.string "das Kämpfen.$"

Route110_TrickHousePuzzle4_Text_CoraPostBattle:: @ 819D253
	.string "Stimmst du mir zu? Du würdest überall\n"
	.string "hingehen, wo man TRAINER findet.$"

Route110_TrickHousePuzzle4_Text_YujiIntro:: @ 819D295
	.string "Hey! Felsen wie diese räume ich mit\n"
	.string "dem kleinen Finger aus dem Weg.$"

Route110_TrickHousePuzzle4_Text_YujiDefeat:: @ 819D2D1
	.string "Ich kann Felsen bewegen, aber ein\n"
	.string "Rätsel zu lösen ist mir zu schwer...$"

Route110_TrickHousePuzzle4_Text_YujiPostBattle:: @ 819D306
	.string "Muskeln alleine sind nicht alles... Auch\n"
	.string "Gehirnschmalz ist wichtig. Sei helle!$"

Route110_TrickHousePuzzle4_Text_JillIntro:: @ 819D351
	.string "Das RÄTSELHAUS wird immer\n"
	.string "verrätselter... äh, komplizierter, oder?$"

Route110_TrickHousePuzzle4_Text_JillDefeat:: @ 819D380
	.string "Aaaak!$"

Route110_TrickHousePuzzle4_Text_JillPostBattle:: @ 819D386
	.string "Hat es jemand schon mal bis zum\n"
	.string "Ende geschafft?$"

Route110_TrickHousePuzzle4_Text_WroteSecretCodeLockOpened: @ 819D3A5
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist ein Genie.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
