AbandonedShip_HiddenFloorCorridors_Text_Rm1DoorIsLocked::
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 1” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm2DoorIsLocked::
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 2” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm4DoorIsLocked::
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 4” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm6DoorIsLocked::
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 6” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_InsertedKey::
	.string "{PLAYER} steckt den SCHLÜSSEL ins\n"
	.string "Schloss und dreht ihn um.\p"
	.string "Der SCHLÜSSEL ist schwergängig, aber\n"
	.string "die Tür öffnet sich.$"
