VictoryRoad_B2F_Text_197EF2:: @ 8197EF2
	.string "Ich habe mit meiner Familie trainiert,\n"
	.string "mit jedem einzelnen Mitglied!\l"
	.string "Ich verliere gegen niemanden!$"

VictoryRoad_B2F_Text_197F46:: @ 8197F46
	.string "Besser als meine Familie?\n"
	.string "Ist das möglich?$"

VictoryRoad_B2F_Text_197F71:: @ 8197F71
	.string "Ich war besser als jeder andere aus\n"
	.string "meiner Familie. Ich habe nie verloren!\p"
	.string "Ich habe mein Selbstvertrauen ver-\n"
	.string "loren. Ich gehe nach Hause...$"

VictoryRoad_B2F_Text_197FE5:: @ 8197FE5
	.string "Ich habe gehört, dass sich hier ein sehr\n"
	.string "starkes Kind herumtreibt. Bist du das?$"

VictoryRoad_B2F_Text_19802B:: @ 819802B
	.string "Diese kleine Kröte ist echt stark!$"

VictoryRoad_B2F_Text_198047:: @ 8198047
	.string "Das Gerücht sagt, das Kind käme aus\n"
	.string "BLÜTENBURG CITY.$"

VictoryRoad_B2F_Text_198089:: @ 8198089
	.string "Du musst doch langsam mal müde werden.$"

VictoryRoad_B2F_Text_1980AD:: @ 81980AD
	.string "Keine Anzeichen von Müdigkeit...$"

VictoryRoad_B2F_Text_1980C8:: @ 81980C8
	.string "Die SIEGESSTRASSE und die POKéMON\n"
	.string "LIGA sind große und langwierige Heraus-\l"
	.string "forderungen. Werde bloß nicht müde!!!$"

VictoryRoad_B2F_Text_198121:: @ 8198121
	.string "Du solltest nicht selbstzufrieden\n"
	.string "werden, nur weil du viele ORDEN der\l"
	.string "ARENEN besitzt.\p"
	.string "Es wird immer jemanden geben, der\n"
	.string "besser ist als du!$"

VictoryRoad_B2F_Text_1981A3:: @ 81981A3
	.string "Du bist besser als ich!$"

VictoryRoad_B2F_Text_1981BA:: @ 81981BA
	.string "Schau dir deine ORDEN an - erinnere dich\n"
	.string "an die TRAINER, die du getroffen hast.$"
