RustboroCity_Flat2_3F_EventObjects:: @ 8388EF4
	object_event 1, EVENT_OBJ_GFX_MAN_7, 0, 7, 3, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 2, 0, 0, 0, RustboroCity_Flat2_3F_EventScript_157DDA, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_1, 0, 12, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, RustboroCity_Flat2_3F_EventScript_157DE3, 0

RustboroCity_Flat2_3F_MapWarps:: @ 8388F24
	warp_def 1, 1, 0, 1, MAP_RUSTBORO_CITY_FLAT2_2F

RustboroCity_Flat2_3F_MapEvents:: @ 8388F2C
	map_events RustboroCity_Flat2_3F_EventObjects, RustboroCity_Flat2_3F_MapWarps, 0x0, 0x0
