UnknownString_81B41B8: @ 81B41B8
	.string "ADRIAN: Bleib sofort stehen!$"

UnknownString_81B41D5: @ 81B41D5
	.string "ADRIAN: Hahahaha...\n"
	.string "Du warst das also die ganze Zeit.$"

UnknownString_81B4201: @ 81B4201
	.string "ADRIAN: Schau nur, schau nur!\p"
	.string "Schau, wie schön die schlafende Gestalt\n"
	.string "des antiken POKéMON KYOGRE ist!\p"
	.string "Ich habe so lange auf diesen Tag\n"
	.string "gewartet...$"

UnknownString_81B4289: @ 81B4289
	.string "ADRIAN: Es überrascht mich, wie du es\n"
	.string "geschafft hast, mir zu folgen.\p"
	.string "Aber das ist nun alles Nebensache.\p"
	.string "Damit meine Träume wahr werden, musst\n"
	.string "du leider verschwinden!$"

UnknownString_81B4319: @ 81B4319
	.string "Ich...\n"
	.string "Ich habe wieder verloren?$"

UnknownString_81B432C: @ 81B432C
	.string "ADRIAN: Hahahaha...\p"
	.string "Ich empfehle mich. Ich muss sagen, du\n"
	.string "bist wirklich sehr talentiert.\p"
	.string "Aber!\n"
	.string "Ich habe dieses hier in meinem Besitz!\p"
	.string "Mit dieser ROTEN KUGEL kann ich\n"
	.string "KYOGRE...$"

UnknownString_81B43C4: @ 81B43C4
	.string "Die ROTE KUGEL beginnt plötzlich von\n"
	.string "innen heraus zu leuchten!$"

UnknownString_81B43F2: @ 81B43F2
	.string "ADRIAN: Was?!?\p"
	.string "Ich habe doch gar nichts gemacht.\n"
	.string "Die ROTE KUGEL... Warum...\p"
	.string "Wo ist KYOGRE geblieben?$"

UnknownString_81B4443: @ 81B4443
	.string "ADRIAN: Hm? Dies ist eine Nachricht\n"
	.string "unserer Mitglieder draußen...$"

UnknownString_81B447A: @ 81B447A
	.string "ADRIAN: Ja, was ist denn jetzt los?\p"
	.string "Hm...\n"
	.string "Es regnet? So heftig?\p"
	.string "Gut... Genau darauf habe ich gewartet.\n"
	.string "Deshalb haben wir KYOGRE erweckt.\l"
	.string "Um TEAM AQUAS Vision von der Erweite-\l"
	.string "rung der Meere zu realisieren.\p"
	.string "Was?!?\p"
	.string "Es regnet stärker, als wir es voraus-\n"
	.string "gesagt haben? Wir sind in Gefahr?\p"
	.string "Das kann nicht sein...\n"
	.string "Das ist unmöglich...\p"
	.string "Bleib wo du bist und behalte die\n"
	.string "Situation im Auge!$"

UnknownString_81B45C6: @ 81B45C6
	.string "ADRIAN: Irgendetwas stimmt da ganz und\n"
	.string "gar nicht...\p"
	.string "Die ROTE KUGEL sollte KYOGRE auf-\n"
	.string "wecken und unter Kontrolle halten...\p"
	.string "Aber... Warum?\n"
	.string "Warum ist KYOGRE verschwunden?\p"
	.string "Warum?!?$"

UnknownString_81B464D: @ 81B464D
	.string "MARC: Was hast du da nur herauf-\n"
	.string "beschworen?\p"
	.string "ADRIAN... Du hast KYOGRE aufge-\n"
	.string "weckt, stimmt’s?\p"
	.string "Was wird nur aus der Welt, wenn es\n"
	.string "bis in alle Ewigkeit regnen wird?\p"
	.string "Das Land wird untergehen und im\n"
	.string "Meer verschwinden...$"

UnknownString_81B4723: @ 81B4723
	.string "ADRIAN: Was sagst du da?\p"
	.string "Die ROTE KUGEL sollte mir die Kontrolle\n"
	.string "über KYOGRE verschaffen...\l"
	.string "Das kann einfach nicht wahr sein...$"

UnknownString_81B4786: @ 81B4786
	.string "MARC: Wir haben keine Zeit für\n"
	.string "Diskussionen!\p"
	.string "Geh nach draußen und sieh es dir\n"
	.string "selber an!\p"
	.string "Sieh, ob das, was du heraufbeschworen\n"
	.string "hast, das ist, was du wolltest!$"

UnknownString_81B4818: @ 81B4818
	.string "MARC: {PLAYER}{KUN}, komm, du musst\n"
	.string "ebenfalls von hier verschwinden!$"
