gTextBard_BardTesting: @ 81B0A83
	.string "BARDEN Test.$"

gTextBard_HiImTheBard:: @ 81B0A91
	.string "Hallo, ich bin der BARDE.\n"
	.string "Möchtest du meinem Lied lauschen?$"

gTextBard_OhYouveLeftMe:: @ 81B0AC3
	.string "Oh...\n"
	.string "Du überlässt mich meinem Blues?$"

gTextBard_OhWhatAMovingSong:: @ 81B0AED
	.string "Hach, was für ein bewegendes Lied...\n"
	.string "Ich wünschte, ich könnte es für\l"
	.string "andere spielen...$"

gTextBard_SoHowDoYouLikeMySong:: @ 81B0B2C
	.string "So?\n"
	.string "Wie fandest du mein Lied?\p"
	.string "Ich bin noch nicht ganz zufrieden mit\n"
	.string "dem Text.\p"
	.string "Hast du nicht Lust, den Text für mich\n"
	.string "neu zu schreiben?$"

gTextBard_OhYouveLeftMe2:: @ 81B0BA6
	.string "Oh... Und wieder werde ich meinem\n"
	.string "Blues überlassen.$"

gTextBard_ThankYouKindly:: @ 81B0BD0
	.string "Vielen herzlichen Dank!\n"
	.string "Ich möchte für dich singen.$"

gTextBard_WasThatHowYouWanted:: @ 81B0BFA
	.string "Hast du dir dein Lied so vorgestellt?$"

gTextBard_OkayThatsIt:: @ 81B0C23
	.string "Okay! Das ist es! Dieses Lied werde\n"
	.string "ich nun für eine Weile singen.$"
