BattleText_UnknownString:
	.string "{STRING 33}$"
BattleText_GainExpPoints:
	.string "{STRING 0} erhält{PLAYER}\n"
	.string "{STRING 42} E-Punkte!\p"
	.string "$"
BattleText_Terminator:
	.string "$"
BattleText_BoostedExp:
	.string " spezielle$"
BattleText_GrewLevel:
	.string "{STRING 0} erreicht\n"
	.string "Lv. {PLAYER}!{UNKNOWN_A}\p"
	.string "$"
BattleText_LearnedMove:
	.string "{STRING 0} erlernt\n"
	.string "{PLAYER}!{UNKNOWN_A}\p"
	.string "$"
BattleText_TryingToLearnMove:
	.string "{STRING 0} versucht,\n"
	.string "{PLAYER} zu lernen.\p"
	.string "$"
BattleText_CantLearnMore:
	.string "Aber {STRING 0} kann nicht\n"
	.string "mehr als vier Attacken erlernen.\p"
	.string "$"
BattleText_DeleteMove:
	.string "Soll eine Attacke zu Gunsten von\n"
	.string "{PLAYER} vergessen werden?$"
BattleText_DeletedMove:
	.string "{STRING 0} hat\n"
	.string "{PLAYER} vergessen!\p"
	.string "$"
BattleText_StopLearning:
	.string "{PAUSE 32}{PLAYER}\n"
	.string "nicht erlernen?$"
BattleText_DidNotLearn:
	.string "{STRING 0} hat {PLAYER}\n"
	.string "nicht erlernt.\p"
	.string "$"
BattleText_UseNext:
	.string "Nächstes POKéMON einsetzen?$"
BattleText_AttackMissed:
	.string "Attacke von {EVIL_LEGENDARY}\n"
	.string "ging daneben!$"
BattleText_ProtectedItself:
	.string "{GOOD_LEGENDARY}\n"
	.string "schützt sich selbst!$"
BattleText_AvoidedDamage:
	.string "{GOOD_LEGENDARY} vermeidet\n"
	.string "Schaden mit {STRING 22}!$"
BattleText_GroundMoveNegate:
	.string "{GOOD_LEGENDARY} wehrt BODEN-\n"
	.string "Attacken mit {STRING 22} ab!$"
BattleText_AvoidedAttack:
	.string "{GOOD_LEGENDARY} wehrt die\n"
	.string "Attacke ab!$"
BattleText_DoesntAffect:
	.string "Es hat keine Wirkung auf\n"
	.string "{GOOD_LEGENDARY}...$"
BattleText_AttackingFainted:
	.string "{EVIL_LEGENDARY}\n"
	.string "wurde besiegt!\p"
	.string "$"
BattleText_DefendingFainted:
	.string "{GOOD_LEGENDARY}\n"
	.string "wurde besiegt!\p"
	.string "$"
BattleText_WinningPrize:
	.string "{STRING 32} gewinnt ¥{STRING 0}!\p"
	.string "$"
BattleText_OutOfUsablePoke:
	.string "{STRING 32} hat kein\n"
	.string "kampffähiges POKéMON mehr!\p"
	.string "$"
BattleText_WhitedOut:
	.string "{STRING 32} fällt in Ohnmacht!{PAUSE_UNTIL_PRESS}$"
BattleText_PreventEscape:
	.string "{STRING 16} verhindert\n"
	.string "eine Flucht mit {STRING 23}!\p"
	.string "$"
BattleText_CantEscape:
	.string "Flucht unmöglich!\p"
	.string "$"
BattleText_AttackingCantEscape:
	.string "{EVIL_LEGENDARY}\n"
	.string "kann nicht fliehen!$"
BattleText_HitMulti:
	.string "{STRING 0}-mal getroffen!$"
BattleText_FellAsleep:
	.string "{STRING 14}\n"
	.string "ist eingeschlafen!$"
BattleText_MadeAsleep:
	.string "{STRING 23} von\n"
	.string "{STRING 16} lässt\l"
	.string "{STRING 14} einschlafen!$"
BattleText_DefendingAsleep:
	.string "{GOOD_LEGENDARY} schläft\n"
	.string "bereits!$"
BattleText_AttackingAsleep:
	.string "{EVIL_LEGENDARY} schläft\n"
	.string "bereits!$"
BattleText_WasntAffected:
	.string "{GOOD_LEGENDARY}\n"
	.string "ist unversehrt!$"
BattleText_Poisoned:
	.string "{STRING 14}\n"
	.string "wurde vergiftet!$"
BattleText_Poisoned2:
	.string "{STRING 23} von\n"
	.string "{STRING 16} vergiftete\l"
	.string "{STRING 14}!$"
BattleText_PoisonHurt:
	.string "{EVIL_LEGENDARY} wurde durch\n"
	.string "Gift verletzt!$"
BattleText_AlreadyPoisoned:
	.string "{GOOD_LEGENDARY} ist bereits\n"
	.string "vergiftet.$"
BattleText_BadlyPoisoned:
	.string "{STRING 14} wurde schwer\n"
	.string "vergiftet!$"
BattleText_EnergyDrained:
	.string "{GOOD_LEGENDARY} wurde\n"
	.string "Energie abgesaugt!$"
BattleText_Burned:
	.string "{STRING 14} brennt!$"
BattleText_Burned2:
	.string "{STRING 23} von\n"
	.string "{STRING 16} verbrennt\l"
	.string "{STRING 14}!$"
BattleText_BurnHurt:
	.string "Die Verbrennung schadet\n"
	.string "{EVIL_LEGENDARY}!$"
BattleText_AlreadyBurned:
	.string "{GOOD_LEGENDARY} brennt\n"
	.string "bereits.$"
BattleText_Frozen:
	.string "{STRING 14} erstarrt\n"
	.string "zu Eis!$"
BattleText_Frozen2:
	.string "{STRING 14} wurde durch\n"
	.string "{STRING 23} von\l"
	.string "{STRING 16} eingefroren!$"
BattleText_FrozenSolid:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "eingefroren!$"
BattleText_DefendingDefrosted:
	.string "{GOOD_LEGENDARY} wurde\n"
	.string "aufgetaut!$"
BattleText_AttackingDefrosted:
	.string "{EVIL_LEGENDARY} wurde\n"
	.string "aufgetaut!$"
BattleText_Defrosted:
	.string "{EVIL_LEGENDARY} wurde\n"
	.string "durch {STRING 17} aufgetaut!$"
BattleText_Paralyzed:
	.string "{STRING 14} ist\n"
	.string "paralysiert! Es greift\l"
	.string "eventuell nicht an!$"
BattleText_Paralyzed2:
	.string "{STRING 23} von\n"
	.string "{STRING 16} paralysierte\p"
	.string "{STRING 14}!\n"
	.string "Es greift eventuell nicht an!$"
BattleText_Paralyzed3:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "paralysiert! Es kann\l"
	.string "nicht angreifen!$"
BattleText_AlreadyParalyzed:
	.string "{GOOD_LEGENDARY} ist\n"
	.string "bereits paralysiert!$"
BattleText_ParalysisHealed:
	.string "{GOOD_LEGENDARY} wurde von der\n"
	.string "Paralyse geheilt!$"
BattleText_DreamEaten:
	.string "Der Traum von {GOOD_LEGENDARY}\n"
	.string "wurde gefressen!$"
BattleText_AttackingStatNoHigher:
	.string "{STRING 0} von\n"
	.string "{EVIL_LEGENDARY} kann nicht\l"
	.string "mehr erhöht werden!$"
BattleText_DefendingStatNoHigher:
	.string "{STRING 0} von\n"
	.string "{GOOD_LEGENDARY} kann nicht\l"
	.string "weiter gesenkt werden!$"
BattleText_StoppedWorking:
	.string "{STRING 0} in deinem Team\n"
	.string "funktioniert nicht mehr!$"
BattleText_StoppedWorking2:
	.string "{STRING 0} des Gegners\n"
	.string "funktioniert nicht mehr!$"
BattleText_Confused:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "verwirrt!$"
BattleText_ConfusionSnapOut:
	.string "{EVIL_LEGENDARY} ist nicht\n"
	.string "mehr verwirrt!$"
BattleText_BecameConfused:
	.string "{STRING 14} wurde\n"
	.string "verwirrt!$"
BattleText_AlreadyConfused:
	.string "{GOOD_LEGENDARY} ist\n"
	.string "bereits verwirrt!$"
BattleText_FellLove:
	.string "{GOOD_LEGENDARY}\n"
	.string "hat sich verliebt!$"
BattleText_InLoveWith:
	.string "{EVIL_LEGENDARY} hat sich in\n"
	.string "{STRING 16} verliebt!$"
BattleText_ImmobilizedBy:
	.string "{EVIL_LEGENDARY} ist starr\n"
	.string "vor Liebe!$"
BattleText_BlownAway:
	.string "{GOOD_LEGENDARY} wurde\n"
	.string "weggeweht!$"
BattleText_TypeTransform:
	.string "{EVIL_LEGENDARY} verwandelt\n"
	.string "sich zu Typ {STRING 0}!$"
BattleText_Flinched:
	.string "{EVIL_LEGENDARY} schreckt\n"
	.string "zurück!$"
BattleText_RegainedHealth:
	.string "{GOOD_LEGENDARY} erholt sich!$"
BattleText_HPFull:
	.string "{GOOD_LEGENDARY} hat alle KP!$"
BattleText_RaisedSpDef:
	.string "{STRING 17} von\n"
	.string "{STRING 38} erhöht\l"
	.string "die SP. VER.$"
BattleText_RaisedSpDefLittle:
	.string "Die SP. VER. wird etwas durch\n"
	.string "{STRING 17} von\l"
	.string "{STRING 38} erhöht.$"
BattleText_RaisedDefense:
	.string "{STRING 17} von\n"
	.string "{STRING 38}\l"
	.string "erhöht die VERTEIDIGUNG!$"
BattleText_RaisedDefenseLittle:
	.string "{STRING 17} von\n"
	.string "{STRING 38}\l"
	.string "erhöht etwas die VERTEIDIGUNG!$"
BattleText_CoveredVeil:
	.string "{STRING 38} wird von\n"
	.string "einem Schleier umhüllt!$"
BattleText_SafeguardActive:
	.string "{GOOD_LEGENDARY} wird durch\n"
	.string "BODYGUARD geschützt!$"
BattleText_SafeguardFaded:
	.string "BODYGUARD von\n"
	.string "{STRING 40} lässt nach!$"
BattleText_WentToSleep:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "eingeschlafen!$"
BattleText_SpeltHealthy:
	.string "{EVIL_LEGENDARY} schläft und\n"
	.string "erholt sich!$"
BattleText_WhipWhirlwind:
	.string "{EVIL_LEGENDARY} entfacht\n"
	.string "einen Wirbelwind!$"
BattleText_TookSunlight:
	.string "{EVIL_LEGENDARY} absorbiert\n"
	.string "Sonnenlicht!$"
BattleText_LoweredHead:
	.string "{EVIL_LEGENDARY} zieht seinen\n"
	.string "Kopf ein!$"
BattleText_IsGlowing:
	.string "{EVIL_LEGENDARY} leuchtet!$"
BattleText_FlewHigh:
	.string "{EVIL_LEGENDARY} fliegt\n"
	.string "hoch empor!$"
BattleText_DugHole:
	.string "{EVIL_LEGENDARY} gräbt sich\n"
	.string "ein!$"
BattleText_HidUnderwater:
	.string "{EVIL_LEGENDARY} taucht\n"
	.string "unter!$"
BattleText_SprangUp:
	.string "{EVIL_LEGENDARY} springt auf!$"
BattleText_SqueezedBind:
	.string "{EVIL_LEGENDARY} setzt bei\n"
	.string "{GOOD_LEGENDARY}\l"
	.string "KLAMMERGRIFF ein!$"
BattleText_TrappedVortex:
	.string "{GOOD_LEGENDARY} wurde in\n"
	.string "einem Strudel gefangen!$"
BattleText_SandTombTrapped:
	.string "{GOOD_LEGENDARY} wurde durch\n"
	.string "SANDGRAB gefangen!$"
BattleText_Wrapped:
	.string "{GOOD_LEGENDARY} wurde von\n"
	.string "{EVIL_LEGENDARY} umWICKELt!$"
BattleText_Clamped:
	.string "{GOOD_LEGENDARY} wurde von\n"
	.string "{EVIL_LEGENDARY} geSCHNAPPT!$"
BattleText_HurtBy:
	.string "{EVIL_LEGENDARY} wurde durch\n"
	.string "{STRING 0} verletzt!$"
BattleText_FreedFrom:
	.string "{EVIL_LEGENDARY} wurde von\n"
	.string "{STRING 0} befreit!$"
BattleText_KeptGoingCrash:
	.string "{EVIL_LEGENDARY} macht weiter\n"
	.string "und bricht zusammen!$"

gUnknown_083FEE5D:: @ 83FEE5D
BattleText_MistShroud:
	.string "{STRING 38} wird in\n"
	.string "WEISSNEBEL gehüllt!$"
BattleText_MistProtect:
	.string "{STRING 16} wird durch\n"
	.string "WEISSNEBEL geschützt!$"

gUnknown_083FEE92:: @ 83FEE92
BattleText_GetPumped:
	.string "{EVIL_LEGENDARY} pumpt\n"
	.string "sich auf!$"
BattleText_HitRecoil:
	.string "{EVIL_LEGENDARY} wurde vom\n"
	.string "Rückstoß getroffen!$"
BattleText_ProtectedItself2:
	.string "{EVIL_LEGENDARY} schützt\n"
	.string "sich selbst!$"
BattleText_SandBuffeted:
	.string "{EVIL_LEGENDARY} wird vom\n"
	.string "Sandsturm getroffen!$"
BattleText_HailStricken:
	.string "{EVIL_LEGENDARY} wird vom\n"
	.string "HAGELSTURM getroffen!$"
BattleText_WoreOff:
	.string "{STRING 0} von\n"
	.string "{STRING 36} lässt nach!$"
BattleText_WasSeeded:
	.string "{GOOD_LEGENDARY} wurde\n"
	.string "bepflanzt!$"
BattleText_EvadedAttack:
	.string "{GOOD_LEGENDARY} ist\n"
	.string "ausgewichen!$"
BattleText_HealthSapped:
	.string "EGELSAMEN schadet\n"
	.string "{EVIL_LEGENDARY}!$"
BattleText_FastAsleep:
	.string "{EVIL_LEGENDARY} schläft tief\n"
	.string "und fest.$"
BattleText_WokeUp:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "aufgewacht!$"
BattleText_UproarAwake:
	.string "AUFRUHR von {STRING 16}\n"
	.string "hält es wach!$"
BattleText_UproarWoke:
	.string "{EVIL_LEGENDARY} wird durch\n"
	.string "AUFRUHR wach!$"
BattleText_UproarCaused:
	.string "{EVIL_LEGENDARY} verursacht\n"
	.string "AUFRUHR!$"
BattleText_UproarMaking:
	.string "{EVIL_LEGENDARY} macht\n"
	.string "einen AUFRUHR!$"
BattleText_CalmedDown:
	.string "{EVIL_LEGENDARY}\n"
	.string "beruhigt sich.$"
BattleText_UproarCantSleep:
	.string "{GOOD_LEGENDARY} kann bei dem\n"
	.string "AUFRUHR nicht schlafen!$"
BattleText_Stockpiled:
	.string "{EVIL_LEGENDARY} HORTET\n"
	.string "{STRING 0}!$"
BattleText_StockpiledCant:
	.string "{EVIL_LEGENDARY} kann nicht\n"
	.string "weiter HORTEN!$"
BattleText_UproarCantSleep2:
	.string "{GOOD_LEGENDARY} kann bei dem\n"
	.string "AUFRUHR nicht schlafen!$"
BattleText_UproarKeptAwake:
	.string "Aber der AUFRUHR hält\n"
	.string "{GOOD_LEGENDARY} wach!$"
BattleText_StayedAwake:
	.string "{GOOD_LEGENDARY} hält sich mit\n"
	.string "{STRING 22} wach!$"
BattleText_StoringEnergy:
	.string "{EVIL_LEGENDARY} speichert\n"
	.string "Energie!$"
BattleText_UnleashedEnergy:
	.string "{EVIL_LEGENDARY} erzeugt\n"
	.string "Energie!$"
BattleText_FatigueConfuse:
	.string "{EVIL_LEGENDARY} ist vor\n"
	.string "Erschöpfung verwirrt!$"
BattleText_PickedUpYen:
	.string "{STRING 32} hebt\n"
	.string "¥{STRING 0} auf!\p"
	.string "$"
BattleText_Unaffected:
	.string "{GOOD_LEGENDARY} ist\n"
	.string "unversehrt!$"
BattleText_Transformed:
	.string "{EVIL_LEGENDARY} verwandelt\n"
	.string "sich in {STRING 0}!$"
BattleText_SubMade:
	.string "{EVIL_LEGENDARY} setzt einen\n"
	.string "DELEGATOR ein!$"
BattleText_SubAlready:
	.string "{EVIL_LEGENDARY} hat bereits\n"
	.string "einen DELEGATOR!$"
BattleText_SubTookDamage:
	.string "Der DELEGATOR steckt den\n"
	.string "Schlag für {GOOD_LEGENDARY}\l"
	.string "ein!\p"
	.string "$"
BattleText_SubFaded:
	.string "DELEGATOR von\n"
	.string "{GOOD_LEGENDARY} lässt nach!\p"
	.string "$"
BattleText_MustRecharge:
	.string "{EVIL_LEGENDARY} muss sich\n"
	.string "wieder aufladen!$"
BattleText_RageBuilding:
	.string "{GOOD_LEGENDARY} verfällt in\n"
	.string "RASEREI!$"
BattleText_MoveWasDisabled:
	.string "{STRING 0} von\n"
	.string "{GOOD_LEGENDARY}\l"
	.string "wurde blockiert!$"
BattleText_DisabledNoMore:
	.string "{EVIL_LEGENDARY} ist nicht\n"
	.string "mehr blockiert!$"
BattleText_EncoreGot:
	.string "{GOOD_LEGENDARY} gibt\n"
	.string "eine ZUGABE!$"
BattleText_EncoreEnded:
	.string "ZUGABE von {EVIL_LEGENDARY}\n"
	.string "ist beendet!$"
BattleText_TookAim:
	.string "{EVIL_LEGENDARY} zielt\n"
	.string "auf {GOOD_LEGENDARY}!$"
BattleText_SketchedMove:
	.string "{EVIL_LEGENDARY} setzt\n"
	.string "NACHAHMER bei {STRING 0} ein!$"
BattleText_DestinyBondTake:
	.string "{EVIL_LEGENDARY} versucht den\n"
	.string "Gegner mit sich zu nehmen!$"
BattleText_DestinyBondTaken:
	.string "{GOOD_LEGENDARY} nimmt\n"
	.string "{EVIL_LEGENDARY} mit sich!$"
BattleText_ReducedBy:
	.string "{STRING 0} von\n"
	.string "{GOOD_LEGENDARY} wird um\l"
	.string "{PLAYER} reduziert!$"
BattleText_StoleSomething:
	.string "{EVIL_LEGENDARY} stiehlt\n"
	.string "{STRING 19} von\l"
	.string "{GOOD_LEGENDARY}!$"
BattleText_CantEscapeNow:
	.string "{GOOD_LEGENDARY} kann\n"
	.string "nicht fliehen!$"
BattleText_NightmareStart:
	.string "{GOOD_LEGENDARY} bekommt\n"
	.string "NACHTMAHR!$"
BattleText_NightmareLock:
	.string "{EVIL_LEGENDARY} ist in\n"
	.string "NACHTMAHR gefangen!$"
BattleText_CurseLay:
	.string "{EVIL_LEGENDARY} nimmt einen\n"
	.string "Teil seiner KP und legt einen\l"
	.string "FLUCH auf {GOOD_LEGENDARY}!$"
BattleText_CurseAfflict:
	.string "{EVIL_LEGENDARY} wurde durch\n"
	.string "FLUCH verletzt!$"
BattleText_SpikesScattered:
	.string "POKéMON-Team von {STRING 37}\n"
	.string "verteilt STACHELN um sich!$"
BattleText_SpikesHurt:
	.string "{STRING 16} wurde durch\n"
	.string "STACHLER verletzt!$"
BattleText_IdentifiedPoke:
	.string "{EVIL_LEGENDARY} erkennt\n"
	.string "{GOOD_LEGENDARY}!$"
BattleText_PerishSongFell:
	.string "ABGESANG von {EVIL_LEGENDARY}\n"
	.string "steht bei {STRING 0}!$"
BattleText_BracedItself:
	.string "{EVIL_LEGENDARY} macht sich\n"
	.string "bereit!$"
BattleText_EnduredHit:
	.string "{GOOD_LEGENDARY} setzt\n"
	.string "AUSDAUER ein!$"
BattleText_MagnitudeCount:
	.string "INTENSITÄT {STRING 0}!$"
BattleText_CutHPMaxATK:
	.string "{EVIL_LEGENDARY} nutzt seine\n"
	.string "KP und hebt den ANGR-Wert!$"
BattleText_CopyStatChanges:
	.string "{EVIL_LEGENDARY} kopiert die\n"
	.string "Statusveränderungen\l"
	.string "von {GOOD_LEGENDARY}!$"
BattleText_GotFreeFrom:
	.string "{EVIL_LEGENDARY} befreit\n"
	.string "sich von {STRING 0}\l"
	.string "von {GOOD_LEGENDARY}!$"
BattleText_LeechShed:
	.string "{EVIL_LEGENDARY} befreit sich\n"
	.string "von EGELSAMEN!$"
BattleText_SpikesBlownAway:
	.string "{EVIL_LEGENDARY} blies den\n"
	.string "STACHLER weg!$"
BattleText_FledBattle:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "geflüchtet!$"
BattleText_ForesawAttack:
	.string "{EVIL_LEGENDARY} sah eine\n"
	.string "Attacke voraus!$"
BattleText_TookAttack:
	.string "{GOOD_LEGENDARY} wurde von\n"
	.string "der Attacke {STRING 0} getroffen!$"
BattleText_ChoseDestiny:
	.string "{EVIL_LEGENDARY} wählte\n"
	.string "{STRING 17} als Vorhersehung aus!$"
BattleText_PokeAttack:
	.string "Angriff von {STRING 0}!$"
BattleText_CenterAttention:
	.string "{EVIL_LEGENDARY} zieht alle\n"
	.string "Aufmerksamkeit auf sich!$"
BattleText_ChargingPower:
	.string "{EVIL_LEGENDARY} lädt\n"
	.string "sich auf!$"
BattleText_NaturePower:
	.string "NATUR-KRAFT wurde zu\n"
	.string "{STRING 17}!$"
BattleText_StatusNormal:
	.string "Status von {EVIL_LEGENDARY}\n"
	.string "wird normal!$"
BattleText_TormentSubject:
	.string "{GOOD_LEGENDARY} wird von\n"
	.string "FOLTERKNECHT unterworfen!$"
BattleText_TightenFocus:
	.string "{EVIL_LEGENDARY} verstärkt\n"
	.string "seinen Fokus!$"
BattleText_TauntFell:
	.string "{GOOD_LEGENDARY} fällt auf\n"
	.string "VERHÖHNER herein!$"
BattleText_ReadyToHelp:
	.string "{EVIL_LEGENDARY} will\n"
	.string "{GOOD_LEGENDARY} helfen!$"
BattleText_SwitchedItems:
	.string "{EVIL_LEGENDARY} tauscht\n"
	.string "Items mit anderem PKMN!$"
BattleText_Obtained1:
	.string "{EVIL_LEGENDARY} erhält\n"
	.string "{STRING 0}.$"
BattleText_Obtained2:
	.string "{GOOD_LEGENDARY} erhält\n"
	.string "{PLAYER}.$"
BattleText_Obtained3:
	.string "{EVIL_LEGENDARY} erhält\n"
	.string "{STRING 0}.\p"
	.string "{GOOD_LEGENDARY} erhält\n"
	.string "{PLAYER}.$"
BattleText_CopiedObject:
	.string "{EVIL_LEGENDARY}\n"
	.string "kopiert {STRING 22} von\l"
	.string "{GOOD_LEGENDARY}!$"
BattleText_WishMade:
	.string "{EVIL_LEGENDARY} spricht einen\n"
	.string "WUNSCHTRAUM aus!$"
BattleText_WishTrue:
	.string "WUNSCHTRAUM von\n"
	.string "{STRING 0} erfüllt sich!$"
BattleText_PlantedRoots:
	.string "{EVIL_LEGENDARY} pflanzt seine\n"
	.string "Wurzeln!$"
BattleText_AbsorbNutrients:
	.string "{EVIL_LEGENDARY} nimmt über\n"
	.string "seine Wurzeln Nährstoffe auf!$"
BattleText_AnchoredItself:
	.string "{GOOD_LEGENDARY}\n"
	.string "verankert sich mit seinen Wurzeln!$"
BattleText_DrowsyMade:
	.string "{EVIL_LEGENDARY} macht\n"
	.string "{GOOD_LEGENDARY} schläfrig!$"
BattleText_KnockedOffItem:
	.string "{EVIL_LEGENDARY}\n"
	.string "entreißt {STRING 19} von\l"
	.string "{GOOD_LEGENDARY}!$"
BattleText_AbilitySwap:
	.string "{EVIL_LEGENDARY} tauscht die\n"
	.string "Fähigkeiten mit einem PKMN!$"
BattleText_SealedMove:
	.string "{EVIL_LEGENDARY} versiegelt\n"
	.string "die Attacke/n des Gegners!$"
BattleText_GrudgeBear:
	.string "{EVIL_LEGENDARY} möchte, dass\n"
	.string "der Gegner ein NACHSPIEL erträgt!$"
BattleText_GrudgeLosePP:
	.string "{STRING 0} von\n"
	.string "{EVIL_LEGENDARY} hat aufgrund\l"
	.string "von NACHSPIEL alle AP verloren!$"
BattleText_ShroudedItself:
	.string "{EVIL_LEGENDARY} verhüllt sich\n"
	.string "selbst in {STRING 17}!$"
BattleText_MagicCoatBounce:
	.string "{STRING 17} von\n"
	.string "{EVIL_LEGENDARY} prallte am\l"
	.string "MAGIEMANTEL ab!$"
BattleText_AwaitMove:
	.string "{EVIL_LEGENDARY} wartet auf\n"
	.string "eine gegnerische Attacke!$"
BattleText_SnatchedMove:
	.string "{GOOD_LEGENDARY} ÜBERNAHM\n"
	.string "Attacke von {STRING 16}!$"
BattleText_ElecWeakened:
	.string "Die Stärke der Elektrizität\n"
	.string "wurde geschwächt!$"
BattleText_FireWeakened:
	.string "Die Stärke des Feuers\n"
	.string "wurde geschwächt!$"
BattleText_FoundOne:
	.string "{EVIL_LEGENDARY} hat 1\n"
	.string "{STRING 19} gefunden!$"
BattleText_SoothingAroma:
	.string "Ein wohltuendes Aroma\n"
	.string "breitet sich aus!$"
BattleText_CantUseItems:
	.string "Hier können Items nicht eingesetzt\n"
	.string "werden.{PAUSE 64}$"
BattleText_UnknownString2:
	.string "Für {STRING 16} war\n"
	.string "{STRING 19} {STRING 0}$"
BattleText_HustleUse:
	.string "{STRING 16} setzt\n"
	.string "{STRING 19} ein, um zu drängeln!$"
BattleText_LostFocus:
	.string "{EVIL_LEGENDARY} hat seinen\n"
	.string "Fokus verloren und kann\l"
	.string "nicht angreifen!$"
BattleText_DraggedOut:
	.string "{GOOD_LEGENDARY} wurde\n"
	.string "auserwählt!\p"
	.string "$"
BattleText_BrokeWall:
	.string "Die Mauer brach zusammen!$"
BattleText_NoEffect:
	.string "Es ist wirkungslos!$"
BattleText_NoMovesLeft:
	.string "{STRING 15} hat keine\n"
	.string "Attacken mehr übrig!\p"
	.string "$"
BattleText_MoveIsDisabled:
	.string "{STRING 17} von\n"
	.string "{STRING 15} ist blockiert!\p"
	.string "$"
BattleText_TormentNoUse:
	.string "{STRING 15} kann\n"
	.string "aufgrund von FOLTERKNECHT\p"
	.string "die Attacke nicht 2-mal\n"
	.string "hintereinander einsetzen!$"
BattleText_TauntNoUse:
	.string "{STRING 15} kann\n"
	.string "{STRING 17} nach VERHÖHNER\l"
	.string "nicht einsetzen!\p"
	.string "$"
BattleText_SealedNoUse:
	.string "{STRING 15} kann die ver-\n"
	.string "siegelte Attacke {STRING 17}\l"
	.string "nicht einsetzen!\p"
	.string "$"
BattleText_RainMade:
	.string "{STRING 23} von\n"
	.string "{STRING 16} lässt\l"
	.string "es regnen!$"
BattleText_SpeedRisen:
	.string "{STRING 23} von\n"
	.string "{STRING 16} erhöht\l"
	.string "seine INIT.!$"
BattleText_ProtectedBy:
	.string "{GOOD_LEGENDARY} wurde durch\n"
	.string "{STRING 22} geschützt!$"
BattleText_PreventedBy:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} hindert\p"
	.string "{EVIL_LEGENDARY} daran,\n"
	.string "{STRING 17} einzusetzen!$"
BattleText_HPRestoredUsing:
	.string "{GOOD_LEGENDARY} füllt KP mit\n"
	.string "Hilfe von {STRING 22} auf!$"
BattleText_MadeUseless:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} hebt die\l"
	.string "Wirkung von {STRING 17} auf!$"
BattleText_MadeType:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} macht es zu\l"
	.string "einem {STRING 0}-Typ!$"
BattleText_PreventedPara:
	.string "{STRING 22} von\n"
	.string "{STRING 14} verhindert\l"
	.string "eine Paralyse!$"
BattleText_PreventedRomance:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} verhindert\l"
	.string "eine Romanze!$"
BattleText_PreventedPoison:
	.string "{STRING 22} von\n"
	.string "{STRING 14} verhindert\l"
	.string "eine Vergiftung!$"
BattleText_PreventedConfusion:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} verhindert\l"
	.string "Verwirrung!$"
BattleText_RaisedFirePower:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} erhöht die\l"
	.string "FEUER-Kraft!$"
BattleText_AnchorsItself:
	.string "{GOOD_LEGENDARY} verankert\n"
	.string "sich mit Hilfe von {STRING 22}!$"
BattleText_CutsAttack:
	.string "{STRING 23} von\n"
	.string "{STRING 16} vermindert\l"
	.string "ANGRIFF von {GOOD_LEGENDARY}!$"
BattleText_PreventedStatLoss:
	.string "{STRING 23} von\n"
	.string "{STRING 16} verhindert\l"
	.string "Statusveränderungen!$"
BattleText_HurtOther:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} verletzt\l"
	.string "{EVIL_LEGENDARY}!$"
BattleText_Traced:
	.string "FÄHRTE von\n"
	.string "{STRING 16}\p"
	.string "erkennt {PLAYER}\n"
	.string "von {STRING 0}!$"
BattleText_PreventedBurn:
	.string "{STRING 24} von\n"
	.string "{STRING 14} verhindert\l"
	.string "Verbrennung!$"
BattleText_BlocksOther:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} blockiert\l"
	.string "{STRING 17}!$"
BattleText_BlocksOther2:
	.string "{STRING 23} von\n"
	.string "{STRING 16} blockiert\l"
	.string "{STRING 17}!$"
BattleText_RestoredHPByItem:
	.string "{STRING 21} von\n"
	.string "{EVIL_LEGENDARY} füllt\l"
	.string "einige KP auf!$"
BattleText_WhipSandstorm:
	.string "{STRING 23} von\n"
	.string "{STRING 16} entfacht\l"
	.string "einen Sandsturm!$"
BattleText_SunIntensified:
	.string "{STRING 23} von\n"
	.string "{STRING 16} intensiviert\l"
	.string "die Sonnenstrahlen!$"
BattleText_PreventedLoss:
	.string "{STRING 23} von\n"
	.string "{STRING 16} verhindert \l"
	.string "den Verlust von {STRING 0}!$"
BattleText_InfatuatedPoke:
	.string "{EVIL_LEGENDARY} ist vernarrt\n"
	.string "in {STRING 22} von\l"
	.string "{GOOD_LEGENDARY}!$"
BattleText_MadeIneffective:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} macht\l"
	.string "{STRING 17} wirkungslos!$"
BattleText_CuredProblem:
	.string "{STRING 23} von\n"
	.string "{STRING 16} heilte sein\l"
	.string "Problem mit {STRING 0}!$"
BattleText_OozeSuckup:
	.string "Es saugte\n"
	.string "KLOAKENSOSSE auf!$"
BattleText_Transformed2:
	.string "{STRING 16}\n"
	.string "verwandelte sich!$"
BattleText_TookAttack2:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} übernahm\l"
	.string "den Angriff!$"

gUnknown_083FFCCA:: @ 83FFCCA
BattleText_PreventedSwitch::
	.string "{STRING 20} von\n"
	.string "{STRING 0} verhindert\p"
	.string "Wechsel!\p"
	.string "$"
BattleText_PreventedOther:
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} macht\p"
	.string "{STRING 0} von\n"
	.string "{STRING 16} wirkungslos!$"
BattleText_MadeIneffective2:
	.string "{STRING 23} von\n"
	.string "{STRING 16} machte\l"
	.string "es wirkungslos!$"
BattleText_PreventedFlinching:
	.string "{STRING 24} von\n"
	.string "{STRING 14} verhindert\l"
	.string "ein Zurückschrecken!$"
BattleText_PreventedOther2:
	.string "{STRING 21} von\n"
	.string "{EVIL_LEGENDARY} macht\p"
	.string "{STRING 22} von\n"
	.string "{GOOD_LEGENDARY} wirkungslos!$"
BattleText_CuredOfProblem:
	.string "{STRING 23} von\n"
	.string "{STRING 16} heilte sein\l"
	.string "Problem mit {STRING 0}!$"
BattleText_NoEffectOn:
	.string "{STRING 23} von\n"
	.string "{STRING 16} hat keine\l"
	.string "Wirkung auf {STRING 14}!$"
BattleText_Sharply:
	.string "steigt stark!$"

gUnknown_083FFDB3:: @ 83FFDB3
BattleText_Rose:
	.string "steigt.$"
BattleText_Harshly:
	.string "sinkt stark!$"
BattleText_Fell:
	.string "sinkt.$"
BattleText_UnknownString7:
	.string "{STRING 0} von\n"
	.string "{EVIL_LEGENDARY} {PLAYER}$"

gUnknown_083FFDD3:: @ 83FFDD3
BattleText_UnknownString3:
	.string "{STRING 0} von\n"
	.string "{GOOD_LEGENDARY} {PLAYER}$"
BattleText_UnknownString4:
	.string "{STRING 19}: {STRING 0} von\n"
	.string "{STRING 16} {PLAYER}$"
BattleText_UnknownString5:
	.string "{STRING 0} von\n"
	.string "{EVIL_LEGENDARY} {PLAYER}$"
BattleText_UnknownString6:
	.string "{STRING 0} von\n"
	.string "{GOOD_LEGENDARY} {PLAYER}$"
BattleText_StatNoHigher:
	.string "Status von {EVIL_LEGENDARY}\n"
	.string "kann nicht weiter erhöht werden!$"
BattleText_StatNoLower:
	.string "Status von {GOOD_LEGENDARY}\n"
	.string "kann nicht weiter sinken!$"
BattleText_Critical:
	.string "Ein Volltreffer!$"
BattleText_GrandSlam:
	.string "Ein K.O.-Treffer!$"
BattleText_MoveForget123:
	.string "{PAUSE 32}1, {PAUSE 15}2 und...{PAUSE 15} ...{PAUSE 15} ...{PAUSE 15}\n"
	.string "{PAUSE 15}{PLAY_SE 0x38 0x00}Schwupp!\p"
	.string "$"
BattleText_MoveForgetAnd:
	.string "Und...\p"
	.string "$"
BattleText_CantForgetHM:
	.string "VM-Attacken können jetzt \n"
	.string "nicht vergessen werden.\p"
	.string "$"
BattleText_NotEffective:
	.string "Das ist nicht sehr effektiv...$"
BattleText_SuperEffective:
	.string "Das ist sehr effektiv!$"

gUnknown_083FFEFC:: @ 83FFEFC
BattleText_GotAwaySafely:
	.string "{PLAY_SE 0x11 0x00}Du bist entkommen!\p"
	.string "$"
BattleText_FledUsingItem:
	.string "{PLAY_SE 0x11 0x00}{EVIL_LEGENDARY} floh\n"
	.string "durch Einsatz von {STRING 19}!\p"
	.string "$"
BattleText_FledUsingOther:
	.string "{PLAY_SE 0x11 0x00}{EVIL_LEGENDARY} floh\n"
	.string "durch Einsatz von {STRING 21}!\p"
	.string "$"
BattleText_FledWild:
	.string "{PLAY_SE 0x11 0x00}Wildes {STRING 0} floh!$"

gUnknown_083FFF56:: @ 83FFF56
BattleText_PlayerDefeatedTrainer:
	.string "Spieler besiegte\n"
	.string "{STRING 29}!$"

gUnknown_083FFF6A:: @ 83FFF6A
BattleText_PlayerDefeatedTrainers:
	.string "Spieler besiegte\n"
	.string "{STRING 30} und {STRING 29}!$"

gUnknown_083FFF81:: @ 83FFF81
BattleText_PlayerLostTrainer:
	.string "Spieler verlor gegen\n"
	.string "{STRING 29}!$"

gUnknown_083FFF99:: @ 83FFF99
BattleText_PlayerLostTrainers:
	.string "Spieler verlor gegen\n"
	.string "{STRING 30} und {STRING 29}!$"

gUnknown_083FFFB3:: @ 83FFFB3
BattleText_PlayerTiedTrainer:
	.string "Patt zwischen Spieler und\n"
	.string "{STRING 29}!$"

gUnknown_083FFFCB:: @ 83FFFCB
BattleText_PlayerTiedTrainers:
	.string "Patt zwischen Spieler, {STRING 30}\n"
	.string "und {STRING 29}!$"

gUnknown_083FFFEA:: @ 83FFFEA
BattleText_FledSingle:
	.string "{PLAY_SE 0x11 0x00}{STRING 29} floh!$"

gUnknown_083FFFF7:: @ 83FFFF7
BattleText_FledDouble:
	.string "{PLAY_SE 0x11 0x00}{STRING 29} und\n"
	.string "{STRING 30} flohen!$"
BattleText_NoRunning:
	.string "Du kannst aus TRAINER-Kämpfen\n"
	.string "nicht fliehen!\p"
	.string "$"
BattleText_CantEscape2:
	.string "Flucht unmöglich!\p"
	.string "$"
BattleText_BirchDontLeaveMe:
	.string "PROF. BIRK: Du... Du kannst mich doch\n"
	.string "nicht einfach im Stich lassen!\p"
	.string "$"
BattleText_Nothing:
	.string "Nichts geschieht!$"
BattleText_Failed:
	.string "Es schlug fehl!$"
BattleText_HurtItself:
	.string "Es hat sich vor Verwirrung\n"
	.string "selbst verletzt!$"
BattleText_MirrorFail:
	.string "Der SPIEGELTRICK schlug fehl!$"
BattleText_RainStart:
	.string "Es fängt an zu regnen!$"
BattleText_PourStart:
	.string "Ein Wolkenbruch!$"
BattleText_RainCont1:
	.string "Es regnet weiter.$"
BattleText_PourCont:
	.string "Der Wolkenbruch hält an.$"
BattleText_RainStop:
	.string "Es hat aufgehört zu regnen.$"
BattleText_SandBrewed:
	.string "Ein Sandsturm kommt auf!$"
BattleText_SandRages:
	.string "Der Sandsturm tobt.$"
BattleText_SandSubsided:
	.string "Der Sandsturm legt sich.$"
BattleText_SunBright:
	.string "Das Sonnenlicht wird stärker!$"
BattleText_SunStrong:
	.string "Gleißendes Sonnenlicht!$"
BattleText_SunFaded:
	.string "Das Sonnenlicht lässt nach!$"
BattleText_HailStart:
	.string "Es fängt an zu hageln!$"
BattleText_HailCont:
	.string "Es hagelt!$"
BattleText_HailStop:
	.string "Es hat aufgehört zu hageln.$"
BattleText_SpitUpFail:
	.string "Aber es konnte nichts\n"
	.string "ENTFESSELN!$"
BattleText_SwallowFail:
	.string "Aber es konnte nichts\n"
	.string "VERZEHREN!$"
BattleText_WindHeatWave:
	.string "Der Wind wurde zu einer\n"
	.string "HITZEWELLE!$"
BattleText_StatElim:
	.string "Alle Statusveränderungen wurden\n"
	.string "entfernt!$"
BattleText_CoinScatter:
	.string "Es liegen überall Münzen verstreut!$"
BattleText_SubWeak:
	.string "Zu schwach, um einen DELEGATOR\n"
	.string "einzusetzen!$"
BattleText_PainSplit:
	.string "Die Kontrahenten teilen\n"
	.string "ihr Leid!$"
BattleText_BellChime:
	.string "Eine Glocke läutet!$"
BattleText_PerishSong:
	.string "Alle betroffenen POKéMON werden\n"
	.string "in 3 Runden K.O. gehen!$"
BattleText_NoPP1:
	.string "Es sind keine AP mehr für\n"
	.string "diese Attacke übrig!\p"
	.string "$"
BattleText_NoPP2:
	.string "Aber es waren keine AP mehr\n"
	.string "für diese Attacke übrig!$"
BattleText_IgnoredOrdersSLP:
	.string "{EVIL_LEGENDARY} ignoriert die\n"
	.string "Befehle. Es schläft!$"
BattleText_IgnoredOrders:
	.string "{EVIL_LEGENDARY} ignoriert den\n"
	.string "Befehl!$"
BattleText_BeganNap:
	.string "{EVIL_LEGENDARY} macht\n"
	.string "ein Nickerchen!$"
BattleText_LoafingAround:
	.string "{EVIL_LEGENDARY} faulenzt!$"
BattleText_WontObey:
	.string "{EVIL_LEGENDARY} ist\n"
	.string "ungehorsam!$"
BattleText_TurnedAway:
	.string "{EVIL_LEGENDARY} wendet\n"
	.string "sich ab!$"
BattleText_NotNotice:
	.string "{EVIL_LEGENDARY} gibt vor,\n"
	.string "nichts zu bemerken!$"
BattleText_WillSwitch:
	.string "Als Nächstes wird {PLAYER} von\n"
	.string "{STRING 25} {STRING 26} eingesetzt.\p"
	.string "Wird {STRING 32} das\n"
	.string "POKéMON wechseln?$"
BattleText_LearnedMove2:
	.string "{EVIL_LEGENDARY} hat\n"
	.string "{STRING 0} gelernt!$"
BattleText_PlayerDefeatedTrainer2:
	.string "Spieler besiegte\n"
	.string "{STRING 25} {STRING 26}!\p"
	.string "$"
BattleText_CreptCloser:
	.string "{STRING 32} schleicht sich näher an\n"
	.string "{STR_VAR_2} heran!$"
BattleText_CantGetCloser:
	.string "{STRING 32} kann nicht näher herangehen!$"
BattleText_WatchingCarefully:
	.string "{STR_VAR_2} beobachtet\n"
	.string "alles aufmerksam!$"
BattleText_CuriousAbout:
	.string "{STR_VAR_2} ist\n"
	.string "neugierig auf {STRING 0}!$"
BattleText_EnthralledBy:
	.string "{STR_VAR_2} ist begeistert\n"
	.string "von {STRING 0}!$"
BattleText_IgnoredThing:
	.string "{STR_VAR_2} ignoriert\n"
	.string "{STRING 0} völlig!$"
BattleText_ThrewBlock:
	.string "{STRING 32} wirft {STR_VAR_2} einen\n"
	.string "{POKEBLOCK} zu!$"
BattleText_SafariOver:
	.string "{PLAY_SE 0x49 0x00}ANSAGE: Du hast keine\n"
	.string "SAFARIBÄLLE mehr! Game over!\p"
	.string "$"

gUnknown_08400555:: @ 8400555
BattleText_WildAppeared1:
	.string "Ein wildes {STR_VAR_2} erscheint!\p"
	.string "$"

gUnknown_08400568:: @ 8400568
BattleText_WildAppeared2:
	.string "Ein wildes {STR_VAR_2} erscheint!\p"
	.string "$"

gUnknown_0840057B:: @ 840057B
BattleText_WildAppeared3:
	.string "Ein wildes {STR_VAR_2} erscheint!{PAUSE 127}$"

gUnknown_08400590:: @ 8400590
BattleText_WildDoubleAppeared:
	.string "Ein wildes {KUN} und\n"
	.string "ein wildes {STR_VAR_2} erscheinen!\p"
	.string "$"

gUnknown_084005AA:: @ 84005AA
BattleText_SingleWantToBattle1:
	.string "Eine Herausforderung von\n"
	.string "{STRING 25} {STRING 26}!\p"
	.string "$"

gUnknown_084005C7:: @ 84005C7
BattleText_SingleWantToBattle2:
	.string "Eine Herausforderung von\n"
	.string "{STRING 29}!$"

gUnknown_084005DB:: @ 84005DB
BattleText_DoubleWantToBattle:
	.string "{STRING 29} und {STRING 30}\n"
	.string "möchten kämpfen!$"

gUnknown_084005F5:: @ 84005F5
BattleText_SentOutSingle1:
	.string "{STR_VAR_2} wird von\n"
	.string "{STRING 25} {STRING 26} in den\l"
	.string "Kampf geschickt!$"

gUnknown_08400608:: @ 8400608
BattleText_SentOutDouble1:
	.string "{STR_VAR_2} und {KUN}\n"
	.string "werden von\p"
	.string "{STRING 25} {STRING 26}\n"
	.string "in den Kampf geschickt!$"

gUnknown_08400622:: @ 8400622
BattleText_SentOutSingle2:
	.string "{STRING 0} wird von\n"
	.string "{STRING 25} {STRING 26}\l"
	.string "in den Kampf geschickt!$"

gUnknown_08400635:: @ 8400635
BattleText_SentOutSingle3:
	.string "{STRING 29} schickt\n"
	.string "{STR_VAR_2} in den Kampf!$"

gUnknown_08400645:: @ 8400645
BattleText_SentOutDouble2:
	.string "{STRING 29} schickt\n"
	.string "{STR_VAR_2} und {KUN}!$"

gUnknown_0840065C:: @ 840065C
BattleText_SentOutDouble3:
	.string "{STRING 29} schickt\n"
	.string "{VERSION}!\p"
	.string "{STRING 30} schickt\n"
	.string "{GOOD_TEAM}!$"

gUnknown_0840067C:: @ 840067C
BattleText_SentOutSingle4:
	.string "{STRING 29} schickt\n"
	.string "{STRING 0}!$"

gUnknown_0840068C:: @ 840068C
BattleText_SentOutSingle5:
	.string "{STRING 31} schickt\n"
	.string "{STRING 0}!$"

gUnknown_0840069C:: @ 840069C
BattleText_SentOutSingle6:
	.string "Los! {STR_VAR_1}!$"

gUnknown_084006A4:: @ 84006A4
BattleText_SentOutDouble4:
	.string "Los! {STR_VAR_1} und\n"
	.string "{STR_VAR_3}!$"

gUnknown_084006B3:: @ 84006B3
BattleText_SentOutSingle7:
	.string "Los! {STRING 0}!$"

gUnknown_084006BB:: @ 84006BB
BattleText_SentOutSingle8:
	.string "Du schaffst es! {STRING 0}!$"

gUnknown_084006C6:: @ 84006C6
BattleText_SentOutSingle9:
	.string "Streng dich an, {STRING 0}!$"

gUnknown_084006D5:: @ 84006D5
BattleText_SentOutSingle10:
	.string "Mach es fertig!\n"
	.string "Los, {STRING 0}!$"

gUnknown_084006F1:: @ 84006F1
BattleText_SentOutSingle11:
	.string "{STRING 28} schickt\n"
	.string "{EVIL_TEAM}!\p"
	.string "Los! {RIVAL}!$"

gUnknown_08400709:: @ 8400709
BattleText_ComeBackSingle1:
	.string "{STRING 0}, genug!\n"
	.string "Komm zurück!$"

gUnknown_08400727:: @ 8400727
BattleText_ComeBackSingle2:
	.string "{STRING 0}, komm zurück!$"

gUnknown_08400736:: @ 8400736
BattleText_ComeBackSingle3:
	.string "{STRING 0}, O.K.!\n"
	.string "Komm zurück!$"

gUnknown_08400749:: @ 8400749
BattleText_ComeBackSingle4:
	.string "{STRING 0}, gut!\n"
	.string "Komm zurück!$"

gUnknown_0840075E:: @ 840075E
BattleText_WithdrewPoke1:
	.string "{STRING 0} wurde\n"
	.string "von {STRING 25} {STRING 26}\l"
	.string "zurückgerufen!$"

gUnknown_08400771:: @ 8400771
BattleText_WithdrewPoke2:
	.string "{STRING 29} ruft\n"
	.string "{STRING 0} zurück!$"

gUnknown_08400781:: @ 8400781
BattleText_WithdrewPoke3:
	.string "{STRING 31} ruft\n"
	.string "{STRING 0} zurück!$"

gUnknown_08400791:: @ 8400791
BattleText_Wild:
	.string " (Wild)$"

gUnknown_08400797:: @ 8400797
BattleText_Foe:
	.string " (Gegner)$"

gUnknown_0840079C:: @ 840079C
BattleText_Foe2:
	.string "Gegner$"

gUnknown_084007A1:: @ 84007A1
BattleText_Ally:
	.string "Anwender$"

gUnknown_084007A7:: @ 84007A7
BattleText_Foe3:
	.string "Gegner$"

gUnknown_084007AC:: @ 84007AC
BattleText_Ally2:
	.string "Anwender$"

gUnknown_084007B2:: @ 84007B2
BattleText_Foe4:
	.string "Gegner$"

gUnknown_084007B7:: @ 84007B7
BattleText_Ally3:
	.string "Anwender$"

gUnknown_084007BD:: @ 84007BD
BattleText_OpponentUsedMove:
	.string "{EVIL_LEGENDARY} setzt\n"
	.string "{PLAYER} ein!$"

gUnknown_084007C8:: @ 84007C8
BattleText_Exclamation2:
	.string "$"

gUnknown_084007CA:: @ 84007CA
BattleText_Exclamation3:
	.string "$"

gUnknown_084007CC:: @ 84007CC
BattleText_Exclamation4:
	.string "$"

gUnknown_084007CE:: @ 84007CE
BattleText_Exclamation5:
	.string "$"

gUnknown_084007D0:: @ 84007D0
BattleText_Exclamation:
	.string "$"

BattleStatText_HP: @ 84007D2
	.string "KP$"

BattleStatText_Attack: @ 84007D5
	.string "ANGRIFF$"

BattleStatText_Defense: @ 84007DC
	.string "VERT.$"

BattleStatText_Speed: @ 84007E4
	.string "INIT.$"

BattleStatText_SpAtk: @ 84007EA
	.string "SP.ANG.$"

BattleStatText_SpDef: @ 84007F2
	.string "SP.VER.$"

BattleStatText_Accuracy: @ 84007FA
	.string "GENAUIGKEIT$"

BattleStatText_Evasion: @ 8400803
	.string "FLUCHTWERT$"

ContestStatText_TooSpicy: @ 840080F
	.string "zu scharf!$"

ContestStatText_TooDry: @ 840081E
	.string "zu trocken!$"

ContestStatText_TooSweet: @ 840082B
	.string "zu süß!$"

ContestStatText_TooBitter: @ 840083A
	.string "zu bitter!$"

ContestStatText_TooSour: @ 840084A
	.string "zu sauer!$"
BattleText_Used1:
	.string "{STRING 32} setzt\n"
	.string "{STRING 19} ein!$"
BattleText_TutorialUsed:
	.string "HEIKO setzt\n"
	.string "{STRING 19} ein!$"
BattleText_Used2:
	.string "{STRING 19} wird von\n"
	.string "{STRING 25} {STRING 26} eingesetzt!$"
BattleText_BlockBall:
	.string "Der TRAINER hat den BALL abgeblockt!$"
BattleText_DontBeAThief:
	.string "Sei kein Dieb!$"
BattleText_DodgeBall:
	.string "Es ist dem BALL ausgewichen! Dieses\n"
	.string "POKéMON kann nicht gefangen werden!$"
BattleText_MissPoke:
	.string "Du hast das POKéMON verfehlt!$"
BattleText_BallBrokeOhNo:
	.string "Mist!\n"
	.string "Das POKéMON hat sich befreit!$"
BattleText_BallBrokeAppeared:
	.string "Oh!\n"
	.string "Fast hätte es geklappt!$"
BattleText_BallBrokeAlmost:
	.string "Mist!\n"
	.string "Das war knapp!$"
BattleText_BallBrokeSoClose:
	.string "Verflixt!\n"
	.string "Es hätte beinahe geklappt!$"
BattleText_BallCaught1:
	.string "Toll!\n"
	.string "{STR_VAR_2} wurde gefangen!{UNKNOWN_A}{PLAY_BGM 0x60 0x01}\p"
	.string "$"
BattleText_BallCaught2:
	.string "Toll!\n"
	.string "{STR_VAR_2} wurde gefangen!{UNKNOWN_A}{PLAY_BGM 0x60 0x01}{PAUSE 127}$"
BattleText_GiveNickname:
	.string "Möchtest du dem {STR_VAR_2}\n"
	.string "einen Spitznamen geben?$"
BattleText_SentToPC:
	.string "{STR_VAR_2} wurde auf\n"
	.string "{STRING 35} PC übertragen.$"

gUnknown_084009ED:: @ 84009ED
BattleText_Someone:
	.string "einen$"

gUnknown_084009F7:: @ 84009F7
BattleText_Lanette:
	.string "LANETTES$"
BattleText_AddedToDex:
	.string "Für {STR_VAR_2} wurde ein Eintrag\n"
	.string "im POKéDEX angelegt.\p"
	.string "$"
BattleText_Raining:
	.string "Es regnet.$"
BattleText_Sandstorm:
	.string "Ein Sandsturm tobt.$"
BattleText_BoxFull:
	.string "Die BOXEN sind voll!\n"
	.string "Du kannst keines mehr fangen!\p"
	.string "$"

gUnknown_08400A78:: @ 8400A78
BattleText_EnigmaBerry:
	.string "ENIGMABEERE$"

gUnknown_08400A85:: @ 8400A85
BattleText_Berry:
	.string "{STR_VAR_1}BEERE$"
BattleText_CuredParalysis:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\l"
	.string "heilte die Paralyse!$"
BattleText_CuredPoison:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\l"
	.string "heilte die Vergiftung!$"
BattleText_CuredBurn:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\l"
	.string "heilte die Verbrennung!$"
BattleText_CuredFreeze:
	.string "{STRING 19} von\n"
	.string "{STRING 16} taute es auf!$"
BattleText_CuredSleep:
	.string "{STRING 19} von\n"
	.string "{STRING 16} \l"
	.string "weckte es auf!$"
BattleText_CuredConfusion:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\l"
	.string "hebt die Verwirrung auf!$"
BattleText_CuredStatus:
	.string "{STRING 19} von\n"
	.string "{STRING 16} \l"
	.string "heilte sein {STRING 0}-Problem!$"
BattleText_NormalizedStatus:
	.string "{STRING 19} von\n"
	.string "{STRING 16} normalisierte\l"
	.string "seine Statuswerte!$"
BattleText_RestoredHealth:
	.string "{STRING 19} füllte\n"
	.string "KP von {STRING 16} auf!$"
BattleText_RestoredPP:
	.string "{STRING 19} von\n"
	.string "{STRING 16} füllte AP von\l"
	.string "{STRING 0} auf!$"
BattleText_RestoredStatus:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\p"
	.string "stellte seine\n"
	.string "Statuswerte wieder her!$"
BattleText_RestoredHPLittle:
	.string "{STRING 19} von\n"
	.string "{STRING 16}\l"
	.string "füllte einige KP auf!$"
BattleText_ChoiceBand:
	.string "{STRING 19} erlaubt\n"
	.string "nur den Einsatz von {STRING 17}!\p"
	.string "$"
BattleText_FocusSash:
	.string "{GOOD_LEGENDARY} hält\n"
	.string "mit Hilfe von\l"
	.string "{STRING 19} durch!$"
BattleText_Terminator2:
	.string "$"
BattleText_WallyBall:
	.string "Nun muss man einen BALL werfen, oder?\n"
	.string "Ich... Ich werde mein Bestes geben!$"

gUnknown_08400C4A:: @ 8400C4A
BattleText_StartEvo:
	.string "Hey?\n"
	.string "{STR_VAR_1} entwickelt sich!$"

gUnknown_08400C60:: @ 8400C60
BattleText_FinishEvo:
	.string "Glückwunsch! Dein {STR_VAR_1}\n"
	.string "wurde zu {STR_VAR_2}!{UNKNOWN_A}\p"
	.string "$"

gUnknown_08400C8D:: @ 8400C8D
BattleText_StopEvo:
	.string "Hm? Die Entwicklung\n"
	.string "wurde abgebrochen!\p"
	.string "$"

gUnknown_08400CA8:: @ 8400CA8
BattleText_OtherMenu:
	.string "Was soll\n"
	.string "{STRING 15} tun?$"

gUnknown_08400CBB:: @ 8400CBB
BattleText_PlayerMenu:
	.string "Was wird {STRING 32}\n"
	.string "tun?$"

gUnknown_08400CCC:: @ 8400CCC
BattleText_WallyMenu:
	.string "Was wird\n"
	.string "HEIKO tun?$"

gUnknown_08400CE0:: @ 8400CE0
BattleText_LinkStandby:
	.string "{PAUSE 16}Verbindung...$"

gUnknown_08400CF3:: @ 8400CF3
BattleText_MenuOptions:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}KAMPF{CLEAR_TO 46}BEUTEL\n"
	.string "POKéMON{CLEAR_TO 46}FLUCHT$"

gUnknown_08400D15:: @ 8400D15
BattleText_MenuOptionsSafari:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}BALL{CLEAR_TO 46}{POKEBLOCK}\n"
	.string "NÄHER{CLEAR_TO 46}FLUCHT$"

gUnknown_08400D38:: @ 8400D38
BattleText_PP:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}AP\n"
	.string "TYP/$"

gUnknown_08400D49:: @ 8400D49
BattleText_Format:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}$"

gUnknown_08400D52:: @ 8400D52
BattleText_ForgetMove:
	.string "{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}{PALETTE 5}Welche Attacke soll vergessen werden?$"

gUnknown_08400D7A:: @ 8400D7A
BattleText_YesNo:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}Ja\n"
	.string "Nein$"

gUnknown_08400D89:: @ 8400D89
BattleText_SwitchWhich:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}\n"
	.string "Wohin?$"

gUnknown_08400D9F:: @ 8400D9F
BattleText_Format2:
	.string "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW SKY_BLUE LIGHT_BLUE WHITE2}$"
BattleText_RightArrow:
	.string "{RIGHT_ARROW}$"

gUnknown_08400DAA:: @ 8400DAA
BattleText_Plus:
	.string "+$"

gUnknown_08400DAC:: @ 8400DAC
BattleText_Dash:
	.string "-$"
BattleText_HP:
	.string "KP     $"
BattleText_Attack:
	.string "ANGR. $"
BattleText_Defense:
	.string "VERT.$"
BattleText_SpAtk:
	.string "SP.ANG.$"
BattleText_SpDef:
	.string "SP.VER.$"

gUnknown_08400DD6:: @ 8400DD6
BattleText_SafariBalls::
	.string "{HIGHLIGHT RED}SAFARIBÄLLE$"

gUnknown_08400DE6:: @ 8400DE6
BattleText_SafariBallsLeft::
	.string "{HIGHLIGHT RED}Übrig: $"

gUnknown_08400DF0:: @ 8400DF0
BattleText_HighlightRed::
	.string "{HIGHLIGHT RED}$"

BattleText_Sleep::
	.string "Schlaf$"
BattleText_PoisonStatus::
	.string "Gift$"
BattleText_Burn::
	.string "Verbrennung$"
BattleText_Paralysis::
	.string "Paralyse$"
BattleText_IceStatus::
	.string "Eis$"
BattleText_Confusion::
	.string "Verwirrung$"
BattleText_Love::
	.string "Liebe$"

gUnknown_08400E23:: @ 8400E23
BattleText_Format3:
	.string " und $"

gUnknown_08400E29:: @ 8400E29
BattleText_Format4:
	.string ", $"

gUnknown_08400E2C:: @ 8400E2C
BattleText_Format5:
	.string " $"

gUnknown_08400E2E:: @ 8400E2E
BattleText_Format6:
	.string "\l"
	.string "$"

gUnknown_08400E30:: @ 8400E30
BattleText_Format7:
	.string "\n"
	.string "$"

gUnknown_08400E32:: @ 8400E32
BattleText_Format8:
	.string "sind$"

gUnknown_08400E36:: @ 8400E36
BattleText_Format9:
	.string "sind$"

gBadEggNickname:: @ 8400E3A
	.string "Schl. EI$"

gUnknown_08400E42:: @ 8400E42
BattleText_Wally::
	.string "HEIKO$"

BattleText_Win:: @ 8400E48
	.string "{HIGHLIGHT TRANSPARENT}Sieg$"

BattleText_Loss:: @ 8400E4F
	.string "{HIGHLIGHT TRANSPARENT}Ndrl.$"

BattleText_Tie:: @ 8400E57
	.string "{HIGHLIGHT TRANSPARENT}Patt$"

gUnknown_08400E5E:: @ 8400E5E
BattleText_Format10:
	.string " ist$"

gUnknown_08400E62:: @ 8400E62
BattleText_Format11:
	.string "$"
BattleText_Normal:
	.string "eine NORMALE Att.$"
BattleText_Fighting:
	.string "eine KAMPF-Att.$"
BattleText_Flying:
	.string "eine FLUG-Att.$"
BattleText_Poison:
	.string "eine GIFT-Att.$"
BattleText_Ground:
	.string "eine BODEN-Att.$"
BattleText_Rock:
	.string "eine GESTEINS-Att.$"
BattleText_Bug:
	.string "eine KÄFER-Att.$"
BattleText_Ghost:
	.string "eine GEIST-Att.$"
BattleText_Steel:
	.string "eine STAHL-Att.$"
BattleText_Typeless:
	.string "eine ???-Attacke$"
BattleText_Fire:
	.string "eine FEUER-Att.$"
BattleText_Water:
	.string "eine WASSER-Att.$"
BattleText_Grass:
	.string "eine PFLANZEN-Att.$"
BattleText_Electric:
	.string "eine ELEKTRO-Att.$"
BattleText_Psychic:
	.string "eine PSYCHO-Att.$"
BattleText_Ice:
	.string "eine EIS-Att.$"
BattleText_Dragon:
	.string "eine DRACHEN-Att.$"
BattleText_Dark:
	.string "eine UNLICHT-Att.$"

	.align 2
gUnknown_08400F58:: @ 8400F58
	.4byte BattleStatText_HP
	.4byte BattleStatText_Attack
	.4byte BattleStatText_Defense
	.4byte BattleStatText_Speed
	.4byte BattleStatText_SpAtk
	.4byte BattleStatText_SpDef
	.4byte BattleStatText_Accuracy
	.4byte BattleStatText_Evasion

	.align 2
gUnknown_08400F78:: @ 8400F78
	.4byte ContestStatText_TooSpicy
	.4byte ContestStatText_TooDry
	.4byte ContestStatText_TooSweet
	.4byte ContestStatText_TooBitter
	.4byte ContestStatText_TooSour

	.align 2
gBattleStringsTable:: @ 8400F8C
	.4byte BattleText_UnknownString
	.4byte BattleText_GainExpPoints
	.4byte BattleText_GrewLevel
	.4byte BattleText_LearnedMove
	.4byte BattleText_TryingToLearnMove
	.4byte BattleText_CantLearnMore
	.4byte BattleText_DeleteMove
	.4byte BattleText_DeletedMove
	.4byte BattleText_StopLearning
	.4byte BattleText_DidNotLearn
	.4byte BattleText_LearnedMove2
	.4byte BattleText_AttackMissed
	.4byte BattleText_ProtectedItself
	.4byte BattleText_StatNoHigher
	.4byte BattleText_AvoidedDamage
	.4byte BattleText_DoesntAffect
	.4byte BattleText_AttackingFainted
	.4byte BattleText_DefendingFainted
	.4byte BattleText_WinningPrize
	.4byte BattleText_OutOfUsablePoke
	.4byte BattleText_WhitedOut
	.4byte BattleText_PreventEscape
	.4byte BattleText_HitMulti
	.4byte BattleText_FellAsleep
	.4byte BattleText_MadeAsleep
	.4byte BattleText_DefendingAsleep
	.4byte BattleText_AttackingAsleep
	.4byte BattleText_WasntAffected
	.4byte BattleText_Poisoned
	.4byte BattleText_Poisoned2
	.4byte BattleText_PoisonHurt
	.4byte BattleText_AlreadyPoisoned
	.4byte BattleText_BadlyPoisoned
	.4byte BattleText_EnergyDrained
	.4byte BattleText_Burned
	.4byte BattleText_Burned2
	.4byte BattleText_BurnHurt
	.4byte BattleText_Frozen
	.4byte BattleText_Frozen2
	.4byte BattleText_FrozenSolid
	.4byte BattleText_DefendingDefrosted
	.4byte BattleText_AttackingDefrosted
	.4byte BattleText_Defrosted
	.4byte BattleText_Paralyzed
	.4byte BattleText_Paralyzed2
	.4byte BattleText_Paralyzed3
	.4byte BattleText_AlreadyParalyzed
	.4byte BattleText_ParalysisHealed
	.4byte BattleText_DreamEaten
	.4byte BattleText_AttackingStatNoHigher
	.4byte BattleText_DefendingStatNoHigher
	.4byte BattleText_StoppedWorking
	.4byte BattleText_StoppedWorking2
	.4byte BattleText_Confused
	.4byte BattleText_ConfusionSnapOut
	.4byte BattleText_BecameConfused
	.4byte BattleText_AlreadyConfused
	.4byte BattleText_FellLove
	.4byte BattleText_InLoveWith
	.4byte BattleText_ImmobilizedBy
	.4byte BattleText_BlownAway
	.4byte BattleText_TypeTransform
	.4byte BattleText_Flinched
	.4byte BattleText_RegainedHealth
	.4byte BattleText_HPFull
	.4byte BattleText_RaisedSpDef
	.4byte BattleText_RaisedDefense
	.4byte BattleText_CoveredVeil
	.4byte BattleText_SafeguardActive
	.4byte BattleText_SafeguardFaded
	.4byte BattleText_WentToSleep
	.4byte BattleText_SpeltHealthy
	.4byte BattleText_WhipWhirlwind
	.4byte BattleText_TookSunlight
	.4byte BattleText_LoweredHead
	.4byte BattleText_IsGlowing
	.4byte BattleText_FlewHigh
	.4byte BattleText_DugHole
	.4byte BattleText_SqueezedBind
	.4byte BattleText_TrappedVortex
	.4byte BattleText_Wrapped
	.4byte BattleText_Clamped
	.4byte BattleText_HurtBy
	.4byte BattleText_FreedFrom
	.4byte BattleText_KeptGoingCrash
	.4byte BattleText_MistShroud
	.4byte BattleText_MistProtect
	.4byte BattleText_GetPumped
	.4byte BattleText_HitRecoil
	.4byte BattleText_ProtectedItself2
	.4byte BattleText_SandBuffeted
	.4byte BattleText_HailStricken
	.4byte BattleText_WasSeeded
	.4byte BattleText_EvadedAttack
	.4byte BattleText_HealthSapped
	.4byte BattleText_FastAsleep
	.4byte BattleText_WokeUp
	.4byte BattleText_UproarAwake
	.4byte BattleText_UproarWoke
	.4byte BattleText_UproarCaused
	.4byte BattleText_UproarMaking
	.4byte BattleText_CalmedDown
	.4byte BattleText_UproarCantSleep
	.4byte BattleText_Stockpiled
	.4byte BattleText_StockpiledCant
	.4byte BattleText_UproarCantSleep2
	.4byte BattleText_UproarKeptAwake
	.4byte BattleText_StayedAwake
	.4byte BattleText_StoringEnergy
	.4byte BattleText_UnleashedEnergy
	.4byte BattleText_FatigueConfuse
	.4byte BattleText_PickedUpYen
	.4byte BattleText_Unaffected
	.4byte BattleText_Transformed
	.4byte BattleText_SubMade
	.4byte BattleText_SubAlready
	.4byte BattleText_SubTookDamage
	.4byte BattleText_SubFaded
	.4byte BattleText_MustRecharge
	.4byte BattleText_RageBuilding
	.4byte BattleText_MoveWasDisabled
	.4byte BattleText_MoveIsDisabled
	.4byte BattleText_DisabledNoMore
	.4byte BattleText_EncoreGot
	.4byte BattleText_EncoreEnded
	.4byte BattleText_TookAim
	.4byte BattleText_SketchedMove
	.4byte BattleText_DestinyBondTake
	.4byte BattleText_DestinyBondTaken
	.4byte BattleText_ReducedBy
	.4byte BattleText_StoleSomething
	.4byte BattleText_CantEscapeNow
	.4byte BattleText_NightmareStart
	.4byte BattleText_NightmareLock
	.4byte BattleText_CurseLay
	.4byte BattleText_CurseAfflict
	.4byte BattleText_SpikesScattered
	.4byte BattleText_SpikesHurt
	.4byte BattleText_IdentifiedPoke
	.4byte BattleText_PerishSongFell
	.4byte BattleText_BracedItself
	.4byte BattleText_EnduredHit
	.4byte BattleText_MagnitudeCount
	.4byte BattleText_CutHPMaxATK
	.4byte BattleText_CopyStatChanges
	.4byte BattleText_GotFreeFrom
	.4byte BattleText_LeechShed
	.4byte BattleText_SpikesBlownAway
	.4byte BattleText_FledBattle
	.4byte BattleText_ForesawAttack
	.4byte BattleText_TookAttack
	.4byte BattleText_PokeAttack
	.4byte BattleText_CenterAttention
	.4byte BattleText_ChargingPower
	.4byte BattleText_NaturePower
	.4byte BattleText_StatusNormal
	.4byte BattleText_NoMovesLeft
	.4byte BattleText_TormentSubject
	.4byte BattleText_TormentNoUse
	.4byte BattleText_TightenFocus
	.4byte BattleText_TauntFell
	.4byte BattleText_TauntNoUse
	.4byte BattleText_ReadyToHelp
	.4byte BattleText_SwitchedItems
	.4byte BattleText_CopiedObject
	.4byte BattleText_WishMade
	.4byte BattleText_WishTrue
	.4byte BattleText_PlantedRoots
	.4byte BattleText_AbsorbNutrients
	.4byte BattleText_AnchoredItself
	.4byte BattleText_DrowsyMade
	.4byte BattleText_KnockedOffItem
	.4byte BattleText_AbilitySwap
	.4byte BattleText_SealedMove
	.4byte BattleText_SealedNoUse
	.4byte BattleText_GrudgeBear
	.4byte BattleText_GrudgeLosePP
	.4byte BattleText_ShroudedItself
	.4byte BattleText_MagicCoatBounce
	.4byte BattleText_AwaitMove
	.4byte BattleText_SnatchedMove
	.4byte BattleText_RainMade
	.4byte BattleText_SpeedRisen
	.4byte BattleText_ProtectedBy
	.4byte BattleText_PreventedBy
	.4byte BattleText_HPRestoredUsing
	.4byte BattleText_MadeType
	.4byte BattleText_PreventedPara
	.4byte BattleText_PreventedRomance
	.4byte BattleText_PreventedPoison
	.4byte BattleText_PreventedConfusion
	.4byte BattleText_RaisedFirePower
	.4byte BattleText_AnchorsItself
	.4byte BattleText_CutsAttack
	.4byte BattleText_PreventedStatLoss
	.4byte BattleText_HurtOther
	.4byte BattleText_Traced
	.4byte BattleText_Sharply
	.4byte BattleText_Rose
	.4byte BattleText_Harshly
	.4byte BattleText_Fell
	.4byte BattleText_UnknownString7
	.4byte BattleText_UnknownString3
	.4byte BattleText_UnknownString5
	.4byte BattleText_UnknownString6
	.4byte BattleText_Critical
	.4byte BattleText_GrandSlam
	.4byte BattleText_MoveForget123
	.4byte BattleText_MoveForgetAnd
	.4byte BattleText_NotEffective
	.4byte BattleText_SuperEffective
	.4byte BattleText_GotAwaySafely
	.4byte BattleText_FledWild
	.4byte BattleText_NoRunning
	.4byte BattleText_CantEscape2
	.4byte BattleText_BirchDontLeaveMe
	.4byte BattleText_Nothing
	.4byte BattleText_Failed
	.4byte BattleText_HurtItself
	.4byte BattleText_MirrorFail
	.4byte BattleText_RainStart
	.4byte BattleText_PourStart
	.4byte BattleText_RainCont1
	.4byte BattleText_PourCont
	.4byte BattleText_RainStop
	.4byte BattleText_SandBrewed
	.4byte BattleText_SandRages
	.4byte BattleText_SandSubsided
	.4byte BattleText_SunBright
	.4byte BattleText_SunStrong
	.4byte BattleText_SunFaded
	.4byte BattleText_HailStart
	.4byte BattleText_HailCont
	.4byte BattleText_HailStop
	.4byte BattleText_SpitUpFail
	.4byte BattleText_SwallowFail
	.4byte BattleText_WindHeatWave
	.4byte BattleText_StatElim
	.4byte BattleText_CoinScatter
	.4byte BattleText_SubWeak
	.4byte BattleText_PainSplit
	.4byte BattleText_BellChime
	.4byte BattleText_PerishSong
	.4byte BattleText_NoPP1
	.4byte BattleText_NoPP2
	.4byte BattleText_Used1
	.4byte BattleText_TutorialUsed
	.4byte BattleText_BlockBall
	.4byte BattleText_DontBeAThief
	.4byte BattleText_DodgeBall
	.4byte BattleText_MissPoke
	.4byte BattleText_BallBrokeOhNo
	.4byte BattleText_BallBrokeAppeared
	.4byte BattleText_BallBrokeAlmost
	.4byte BattleText_BallBrokeSoClose
	.4byte BattleText_BallCaught1
	.4byte BattleText_BallCaught2
	.4byte BattleText_GiveNickname
	.4byte BattleText_SentToPC
	.4byte BattleText_AddedToDex
	.4byte BattleText_Raining
	.4byte BattleText_Sandstorm
	.4byte BattleText_CantEscape
	.4byte BattleText_IgnoredOrdersSLP
	.4byte BattleText_IgnoredOrders
	.4byte BattleText_BeganNap
	.4byte BattleText_LoafingAround
	.4byte BattleText_WontObey
	.4byte BattleText_TurnedAway
	.4byte BattleText_NotNotice
	.4byte BattleText_WillSwitch
	.4byte BattleText_CreptCloser
	.4byte BattleText_CantGetCloser
	.4byte BattleText_WatchingCarefully
	.4byte BattleText_CuriousAbout
	.4byte BattleText_EnthralledBy
	.4byte BattleText_IgnoredThing
	.4byte BattleText_ThrewBlock
	.4byte BattleText_SafariOver
	.4byte BattleText_CuredParalysis
	.4byte BattleText_CuredPoison
	.4byte BattleText_CuredBurn
	.4byte BattleText_CuredFreeze
	.4byte BattleText_CuredSleep
	.4byte BattleText_CuredConfusion
	.4byte BattleText_CuredStatus
	.4byte BattleText_RestoredHealth
	.4byte BattleText_RestoredPP
	.4byte BattleText_RestoredStatus
	.4byte BattleText_RestoredHPLittle
	.4byte BattleText_ChoiceBand
	.4byte BattleText_FocusSash
	.4byte BattleText_Terminator2 @ terminator?
	.4byte BattleText_PreventedBurn
	.4byte BattleText_BlocksOther
	.4byte BattleText_RestoredHPByItem
	.4byte BattleText_WhipSandstorm
	.4byte BattleText_PreventedLoss
	.4byte BattleText_InfatuatedPoke
	.4byte BattleText_MadeIneffective
	.4byte BattleText_CuredProblem
	.4byte BattleText_OozeSuckup
	.4byte BattleText_Transformed2
	.4byte BattleText_ElecWeakened
	.4byte BattleText_FireWeakened
	.4byte BattleText_HidUnderwater
	.4byte BattleText_SprangUp
	.4byte BattleText_CantForgetHM
	.4byte BattleText_FoundOne
	.4byte BattleText_PlayerDefeatedTrainer2
	.4byte BattleText_SoothingAroma
	.4byte BattleText_CantUseItems
	.4byte BattleText_UnknownString2
	.4byte BattleText_UnknownString4
	.4byte BattleText_HustleUse
	.4byte BattleText_MadeUseless
	.4byte BattleText_SandTombTrapped @ sand tomb
	.4byte BattleText_Terminator
	.4byte BattleText_BoostedExp
	.4byte BattleText_SunIntensified
	.4byte BattleText_GroundMoveNegate
	.4byte BattleText_WallyBall
	.4byte BattleText_TookAttack2
	.4byte BattleText_ChoseDestiny
	.4byte BattleText_LostFocus
	.4byte BattleText_UseNext
	.4byte BattleText_FledUsingItem
	.4byte BattleText_FledUsingOther
	.4byte BattleText_DraggedOut
	.4byte BattleText_PreventedOther
	.4byte BattleText_NormalizedStatus
	.4byte BattleText_Used2
	.4byte BattleText_BoxFull
	.4byte BattleText_AvoidedAttack
	.4byte BattleText_MadeIneffective2
	.4byte BattleText_PreventedFlinching
	.4byte BattleText_AlreadyBurned
	.4byte BattleText_StatNoLower
	.4byte BattleText_BlocksOther2
	.4byte BattleText_WoreOff
	.4byte BattleText_RaisedDefenseLittle
	.4byte BattleText_RaisedSpDefLittle
	.4byte BattleText_BrokeWall
	.4byte BattleText_PreventedOther2
	.4byte BattleText_CuredOfProblem
	.4byte BattleText_AttackingCantEscape
	.4byte BattleText_Obtained1
	.4byte BattleText_Obtained2
	.4byte BattleText_Obtained3
	.4byte BattleText_NoEffect
	.4byte BattleText_NoEffectOn

	.align 1
gMissStrings:: @ 8401508
@ Each entry refers to a text pointer in gUnknown_08400F8C, but the values are offset
@ by 0xc. For example, 0x0017 refers to BattleText_AttackMissed because it is the
@ 11th entry in the pointer table.
	.2byte BATTLE_TEXT_AttackMissed
	.2byte BATTLE_TEXT_ProtectedItself
	.2byte BATTLE_TEXT_AvoidedAttack
	.2byte BATTLE_TEXT_AvoidedDamage
	.2byte BATTLE_TEXT_GroundMoveNegate

BattleTextList_401512:: @ 8401512
	.2byte BATTLE_TEXT_CantEscape2
	.2byte BATTLE_TEXT_BirchDontLeaveMe
	.2byte BATTLE_TEXT_PreventEscape
	.2byte BATTLE_TEXT_CantEscape
	.2byte BATTLE_TEXT_AttackingCantEscape

BattleTextList_40151C:: @ 840151C
	.2byte BATTLE_TEXT_RainStart
	.2byte BATTLE_TEXT_PourStart
	.2byte BATTLE_TEXT_Failed
	.2byte BATTLE_TEXT_SandBrewed
	.2byte BATTLE_TEXT_SunBright
	.2byte BATTLE_TEXT_HailStart

BattleTextList_401528:: @ 8401528
	.2byte BATTLE_TEXT_SandRages
	.2byte BATTLE_TEXT_HailCont

BattleTextList_40152C:: @ 840152C
	.2byte BATTLE_TEXT_SandBuffeted
	.2byte BATTLE_TEXT_HailStricken

BattleTextList_401530:: @ 8401530
	.2byte BATTLE_TEXT_SandSubsided
	.2byte BATTLE_TEXT_HailStop

BattleTextList_401534:: @ 8401534
	.2byte BATTLE_TEXT_RainCont1
	.2byte BATTLE_TEXT_PourCont
	.2byte BATTLE_TEXT_RainStop

BattleTextList_40153A:: @ 840153A
	.2byte BATTLE_TEXT_ProtectedItself2
	.2byte BATTLE_TEXT_BracedItself
	.2byte BATTLE_TEXT_Failed

BattleTextList_401540:: @ 8401540
	.2byte BATTLE_TEXT_Failed
	.2byte BATTLE_TEXT_RaisedDefense
	.2byte BATTLE_TEXT_RaisedDefenseLittle
	.2byte BATTLE_TEXT_RaisedSpDef
	.2byte BATTLE_TEXT_RaisedSpDefLittle
	.2byte BATTLE_TEXT_CoveredVeil

BattleTextList_40154C:: @ 840154C
	.2byte BATTLE_TEXT_WasSeeded
	.2byte BATTLE_TEXT_EvadedAttack
	.2byte BATTLE_TEXT_DoesntAffect
	.2byte BATTLE_TEXT_HealthSapped
	.2byte BATTLE_TEXT_OozeSuckup

BattleTextList_401556:: @ 8401556
	.2byte BATTLE_TEXT_WentToSleep
	.2byte BATTLE_TEXT_SpeltHealthy

BattleTextList_40155A:: @ 840155A
	.2byte BATTLE_TEXT_UproarMaking
	.2byte BATTLE_TEXT_CalmedDown

BattleTextList_40155E:: @ 840155E
	.2byte BATTLE_TEXT_Stockpiled
	.2byte BATTLE_TEXT_StockpiledCant

BattleTextList_401562:: @ 8401562
	.2byte BATTLE_TEXT_WokeUp
	.2byte BATTLE_TEXT_UproarWoke

BattleTextList_401566:: @ 8401566
	.2byte BATTLE_TEXT_SwallowFail
	.2byte BATTLE_TEXT_HPFull

BattleTextList_40156A:: @ 840156A
	.2byte BATTLE_TEXT_UproarCantSleep2
	.2byte BATTLE_TEXT_UproarKeptAwake
	.2byte BATTLE_TEXT_StayedAwake

BattleTextList_401570:: @ 8401570
	.2byte BATTLE_TEXT_UnknownString7
	.2byte BATTLE_TEXT_UnknownString3
	.2byte BATTLE_TEXT_AttackingStatNoHigher
	.2byte BATTLE_TEXT_Terminator2
	.2byte BATTLE_TEXT_UnknownString4
	.2byte BATTLE_TEXT_HustleUse

BattleTextList_40157C:: @ 840157C
	.2byte BATTLE_TEXT_UnknownString5
	.2byte BATTLE_TEXT_UnknownString6
	.2byte BATTLE_TEXT_DefendingStatNoHigher
	.2byte BATTLE_TEXT_Terminator2

BattleTextList_401584:: @ 8401584
	.2byte BATTLE_TEXT_WhipWhirlwind
	.2byte BATTLE_TEXT_TookSunlight
	.2byte BATTLE_TEXT_LoweredHead
	.2byte BATTLE_TEXT_IsGlowing
	.2byte BATTLE_TEXT_FlewHigh
	.2byte BATTLE_TEXT_DugHole
	.2byte BATTLE_TEXT_HidUnderwater
	.2byte BATTLE_TEXT_SprangUp

BattleTextList_401594:: @ 8401594
	.2byte BATTLE_TEXT_SqueezedBind
	.2byte BATTLE_TEXT_Wrapped
	.2byte BATTLE_TEXT_TrappedVortex
	.2byte BATTLE_TEXT_Clamped
	.2byte BATTLE_TEXT_TrappedVortex
	.2byte BATTLE_TEXT_SandTombTrapped

BattleTextList_4015A0:: @ 84015A0
	.2byte BATTLE_TEXT_MistShroud
	.2byte BATTLE_TEXT_Failed

BattleTextList_4015A4:: @ 84015A4
	.2byte BATTLE_TEXT_GetPumped
	.2byte BATTLE_TEXT_Failed

BattleTextList_4015A8:: @ 84015A8
	.2byte BATTLE_TEXT_Transformed
	.2byte BATTLE_TEXT_Failed

BattleTextList_4015AC:: @ 84015AC
	.2byte BATTLE_TEXT_SubMade
	.2byte BATTLE_TEXT_SubWeak

BattleTextList_4015B0:: @ 84015B0
	.2byte BATTLE_TEXT_Poisoned
	.2byte BATTLE_TEXT_Poisoned2

BattleTextList_4015B4:: @ 84015B4
	.2byte BATTLE_TEXT_Paralyzed
	.2byte BATTLE_TEXT_Paralyzed2

BattleTextList_4015B8:: @ 84015B8
	.2byte BATTLE_TEXT_FellAsleep
	.2byte BATTLE_TEXT_MadeAsleep

BattleTextList_4015BC:: @ 84015BC
	.2byte BATTLE_TEXT_Burned
	.2byte BATTLE_TEXT_Burned2

BattleTextList_4015C0:: @ 84015C0
	.2byte BATTLE_TEXT_Frozen
	.2byte BATTLE_TEXT_Frozen2

BattleTextList_4015C4:: @ 84015C4
	.2byte BATTLE_TEXT_AttackingDefrosted
	.2byte BATTLE_TEXT_Defrosted

BattleTextList_4015C8:: @ 84015C8
	.2byte BATTLE_TEXT_AttackMissed
	.2byte BATTLE_TEXT_Unaffected
	.2byte BATTLE_TEXT_FellLove
	.2byte BATTLE_TEXT_InfatuatedPoke

BattleTextList_4015D0:: @ 84015D0
	.2byte BATTLE_TEXT_EnergyDrained
	.2byte BATTLE_TEXT_OozeSuckup

BattleTextList_4015D4:: @ 84015D4
	.2byte BATTLE_TEXT_ElecWeakened
	.2byte BATTLE_TEXT_FireWeakened

BattleTextList_4015D8:: @ 84015D8
	.2byte BATTLE_TEXT_BellChime
	.2byte BATTLE_TEXT_BellChime
	.2byte BATTLE_TEXT_BellChime
	.2byte BATTLE_TEXT_BellChime
	.2byte BATTLE_TEXT_SoothingAroma

BattleTextList_4015E2:: @ 84015E2
	.2byte BATTLE_TEXT_ForesawAttack
	.2byte BATTLE_TEXT_ChoseDestiny

BattleTextList_4015E6:: @ 84015E6
	.2byte BATTLE_TEXT_BallBrokeOhNo
	.2byte BATTLE_TEXT_BallBrokeAppeared
	.2byte BATTLE_TEXT_BallBrokeAlmost
	.2byte BATTLE_TEXT_BallBrokeSoClose

BattleTextList_4015EE:: @ 84015EE
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Sandstorm
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_SunStrong
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining
	.2byte BATTLE_TEXT_Raining

BattleTextList_40160E:: @ 840160E
	.2byte BATTLE_TEXT_LoafingAround
	.2byte BATTLE_TEXT_WontObey
	.2byte BATTLE_TEXT_TurnedAway
	.2byte BATTLE_TEXT_NotNotice

BattleTextList_401616:: @ 8401616
	.2byte BATTLE_TEXT_CreptCloser
	.2byte BATTLE_TEXT_CantGetCloser

BattleTextList_40161A:: @ 840161A
	.2byte BATTLE_TEXT_CuriousAbout
	.2byte BATTLE_TEXT_EnthralledBy
	.2byte BATTLE_TEXT_IgnoredThing

BattleTextList_401620:: @ 8401620
	.2byte BATTLE_TEXT_CuredConfusion
	.2byte BATTLE_TEXT_CuredParalysis
	.2byte BATTLE_TEXT_CuredFreeze
	.2byte BATTLE_TEXT_CuredBurn
	.2byte BATTLE_TEXT_CuredPoison
	.2byte BATTLE_TEXT_CuredSleep

BattleTextList_40162C:: @ 840162C
	.2byte BATTLE_TEXT_CuredStatus
	.2byte BATTLE_TEXT_NormalizedStatus

BattleTextList_401630:: @ 8401630
	.2byte BATTLE_TEXT_PreventedBurn
	.2byte BATTLE_TEXT_PreventedOther2
	.2byte BATTLE_TEXT_NoEffectOn

BattleTextList_401636:: @ 8401636
	.2byte BATTLE_TEXT_PreventedPara
	.2byte BATTLE_TEXT_PreventedOther2
	.2byte BATTLE_TEXT_NoEffectOn

BattleTextList_40163C:: @ 840163C
	.2byte BATTLE_TEXT_PreventedPoison
	.2byte BATTLE_TEXT_PreventedOther2
	.2byte BATTLE_TEXT_NoEffectOn

BattleTextList_401642:: @ 8401642
	.2byte BATTLE_TEXT_Obtained1
	.2byte BATTLE_TEXT_Obtained2
	.2byte BATTLE_TEXT_Obtained3

BattleTextList_401648:: @ 8401648
	.2byte BATTLE_TEXT_RaisedFirePower
	.2byte BATTLE_TEXT_MadeIneffective

gTrappingMoves:: @ 840164C
	.2byte BATTLE_TEXT_StopLearning
	.2byte BATTLE_TEXT_FellAsleep
	.2byte BATTLE_TEXT_SpeltHealthy
	.2byte BATTLE_TEXT_SubTookDamage
	.2byte BATTLE_TEXT_CoinScatter
	.2byte BATTLE_TEXT_SandTombTrapped
	.2byte 0xFFFF

	.align 2
gUnknown_0840165C:: @ 840165C
	.4byte BattleText_HP
	.4byte BattleText_SpAtk
	.4byte BattleText_Attack
	.4byte BattleText_SpDef
	.4byte BattleText_Defense
	.4byte BattleStatText_Speed

	.align 2
gUnknown_08401674:: @ 8401674
	.4byte BattleText_Normal
	.4byte BattleText_Fighting
	.4byte BattleText_Flying
	.4byte BattleText_Poison
	.4byte BattleText_Ground
	.4byte BattleText_Rock
	.4byte BattleText_Bug
	.4byte BattleText_Ghost
	.4byte BattleText_Steel
	.4byte BattleText_Typeless
	.4byte BattleText_Fire
	.4byte BattleText_Water
	.4byte BattleText_Grass
	.4byte BattleText_Electric
	.4byte BattleText_Psychic
	.4byte BattleText_Ice
	.4byte BattleText_Dragon
	.4byte BattleText_Dark
