Underwater_SealedChamber_Braille_1C533D:: @ 81C533D
	.string "ÀÉëÒÂÌÒÉÌë ÒÉéÀ{0x31}Ê{0x3F}Œ$"

SealedChamber_OuterRoom_Braille_1C534F:: @ 81C534F
	.string "ÊÉßÒÎÌÀÈÂÎ$"

SealedChamber_OuterRoom_Braille_1C5359:: @ 81C5359
	.string "ÊÉßÒÎÌÉÓÙß$"

SealedChamber_OuterRoom_Braille_1C5363:: @ 81C5363
	.string "ÊÉßÒÎÌ{0x1F}ëàì$"

SealedChamber_OuterRoom_Braille_1C536D:: @ 81C536D
	.string "ÌÉÛÒÒÌ{0x3B}{0x39}$"

SealedChamber_OuterRoom_Braille_1C5377:: @ 81C5377
	.string "ÊÉßÒÎÌÌÊÔÒ$"

SealedChamber_OuterRoom_Braille_1C5381:: @ 81C5381
	.string "ÊÉßÒÎÌÛéçá$"

SealedChamber_OuterRoom_Braille_1C538B:: @ 81C538B
	.string "ÊÉßÒÎÌ{0x31}=+{0x33}$"

SealedChamber_OuterRoom_Braille_1C5396:: @ 81C5396
	.string "ÌÉÛÒÒÌ{0x3F}Œ$"

SealedChamber_OuterRoom_Braille_1C539E:: @ 81C539E
	.string "ËÉÑÒÏÌèù&$"

SealedChamber_OuterRoom_Braille_1C53A9:: @ 81C53A9
	.string "ÌÉÛÒÒÌ{0x3F}Ç$"

SealedChamber_OuterRoom_Braille_1C53B1:: @ 81C53B1
	.string "ÉÇ{0x18}ÔËÊàÂÒÀ{0x31}ÊßÌ\n"
	.string "ÒÉÌë{0x3F}Œ$"

SealedChamber_InnerRoom_Braille_1C53C1:: @ 81C53C1
	.string "È çÛÊÂëÌßÉÂÀéìÒ\n"
	.string "{0x39}{0x31}Ìëàì{0x3F}Ç\n"
	.string "+ÀÉßçëÎ\n"
	.string "{0x39}{0x31}ßÌì{0x39}ì{0x3F}Œ$"

SealedChamber_InnerRoom_Braille_1C53F2:: @ 81C53F2
	.string "ÁÁêÙÇÈÉé ÎÉÌàÌë\n"
	.string "ÒùÒßÌ ÒÀÈÌé\n"
	.string "+Éë ÔÌßÌÈì{0x3F}Œ$"

SealedChamber_InnerRoom_Braille_1C5414:: @ 81C5414
	.string "ÀÁëÙÂÈ+Éë =ÌëÎÀéÙÌé\n"
	.string "ÀßßÌà ÎÌé\n"
	.string "áçÙÌÛçé{0x3F}Ç$"

SealedChamber_InnerRoom_Braille_1C5435:: @ 81C5435
	.string "Á êÛÇÂÎÌééçÂÒ\n"
	.string "àáÌëëìÌé +Éë\n"
	.string "ÎÉÌ áçÙÌÛçé\n"
	.string "+ÌÔ{0x3F}Œ$"

SealedChamber_InnerRoom_Braille_1C545C:: @ 81C545C
	.string "ÇÇèÔÉÊ+Éë ÒÀììÌé\n"
	.string "ÀéÔàì{0x3F}Œ$"

SealedChamber_InnerRoom_Braille_1C5470:: @ 81C5470
	.string "  ëÛÀÂÎÌéÓÌéÉÔÌé{0x3F}Ç\n"
	.string "ÎÉÌ ÒçÊÊÌé {0x31}éÎ\n"
	.string "Û{0x31}ìÉÔ àÉéÎ{0x3F}Ç\n"
	.string "+ÉëÎ àÉÂÒ$"

SealedChamber_InnerRoom_Braille_1C549B:: @ 81C549B
	.string "Á êÛÇÂÌÉéÌ ì&ëÌ {0x39}{0x31}\n"
	.string "ÌÉéÌÛ Ì+ÉÔÌé\n"
	.string "áçÙÌÛçé\n"
	.string "ùÊÊéÌé{0x3F}Œ$"

DesertRuins_Braille_1C54C8:: @ 81C54C8
	.string "  ëÛÀÂ{0x39}+ÌÉÛÀß ëÌÂÒìà\n"
	.string "{0x31}éÎ {0x39}+ÌÉ\n"
	.string "ÒÉé{0x31}éìÌë{0x3F}Ç\n"
	.string "ÎÀéé àìèëÙÌ{0x3F}Œ$"

IslandCave_Braille_1C54FC:: @ 81C54FC
	.string "Â éÛÈÂ+ÀëìÌ{0x3F}Ç ÈÉà\n"
	.string "ÎÉÌ {0x39}ÌÉì\n"
	.string "{0x39}+ÌÉÛÀß\n"
	.string "Î{0x31}ëÂÒ Éàì{0x3F}Œ$"

AncientTomb_Braille_1C552E:: @ 81C552E
	.string "  ëÛÀÂéÌ{0x31}Ì {0x39}ÌÉì{0x3F}Ç\n"
	.string "ÒçÊÊé{0x31}éÔ {0x31}éÎ\n"
	.string "ßÉÌÈÌ àÉéÎ ÎÉÌ\n"
	.string "ÒÉÛÛÌßàÛÉììÌ{0x3F}Œ$"
