OldaleTown_PokemonCenter_2F_Text_1A4510:: @ 81A4510
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "KOLOSSEUM.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "kämpfen.\p"
	.string "Möchtest du jetzt kämpfen?$"

OldaleTown_PokemonCenter_2F_Text_1A457E:: @ 81A457E
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "HANDELSCENTER.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "POKéMON tauschen.\p"
	.string "Möchtest du jetzt POKéMON tauschen?$"

OldaleTown_PokemonCenter_2F_Text_1A45FE:: @ 81A45FE
	.string "Willkommen beim POKéMON KABEL-CLUB-\n"
	.string "STATISTIKTAUSCH.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "die Rekorde als TRAINER austauschen.\p"
	.string "Möchtest du Rekorde austauschen?$"

OldaleTown_PokemonCenter_2F_Text_1A4696:: @ 81A4696
	.string "Es gibt drei Arten des Kampfes\n"
	.string "via Verbindungskabel.\p"
	.string "EINZELKAMPF ist für zwei TRAINER, die\n"
	.string "jeder ein oder mehrere POKéMON\l"
	.string "besitzen.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.\p"
	.string "DOPPELKAMPF ist für zwei TRAINER mit\n"
	.string "zwei oder mehr POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde zwei\n"
	.string "POKéMON in den Kampf.\p"
	.string "MULTIKÄMPFE sind für vier TRAINER mit\n"
	.string "einem oder mehr POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde ein\n"
	.string "POKéMON in den Kampf.$"

OldaleTown_PokemonCenter_2F_Text_1A4826:: @ 81A4826
	.string "Möchtest du kämpfen?$"

OldaleTown_PokemonCenter_2F_Text_1A4840:: @ 81A4840
	.string "Welche Art des Kampfes?$"

OldaleTown_PokemonCenter_2F_Text_1A486A:: @ 81A486A
	.string "Für einen DOPPELKAMPF brauchst du\n"
	.string "mindestens zwei POKéMON.$"

OldaleTown_PokemonCenter_2F_Text_1A48A3:: @ 81A48A3
	.string "Für einen Tausch musst du mindestens\n"
	.string "zwei POKéMON bei dir haben.$"

OldaleTown_PokemonCenter_2F_Text_1A48DD:: @ 81A48DD
	.string "Dein POKéMON trägt eine {STR_VAR_1}-\n"
	.string "BEERE und kann nicht getauscht werden.$"

OldaleTown_PokemonCenter_2F_Text_1A490C:: @ 81A490C
gUnknown_081A490C:: @ 81A490C
	.string "Bitte warten.\n"
	.string "... ... B-Knopf: Abbruch$"

UnknownString_81A4932: @ 81A4932
gUnknown_081A4932:: @ 81A4932
	.string "Wenn die Spieler bereit sind...\n"
	.string "A-Knopf: Bestätigen  B-Knopf: Abbruch$"

UnknownString_81A4975: @ 81A4975
gUnknown_081A4975:: @ 81A4975
	.string "Verbindung für {STR_VAR_1} Spieler aufbauen.\n"
	.string "A-Knopf: Bestätigen  B-Knopf: Abbruch$"

UnknownString_81A49B6: @ 81A49B6
gUnknown_081A49B6:: @ 81A49B6
	.string "Verbindungsaufbau...\n"
	.string "... ... B-Knopf: Abbruch$"

UnknownString_81A49E2: @ 81A49E2
	.string "Dein Spiel muss vor Verbindungsaufbau\n"
	.string "gespeichert werden. Speichern?$"

OldaleTown_PokemonCenter_2F_Text_1A4A22:: @ 81A4A22
	.string "Bitte eintreten.$"

FallarborTown_ContestLobby_Text_1A4A30:: @ 81A4A30
OldaleTown_PokemonCenter_2F_Text_1A4A30:: @ 81A4A30
	.string "Ein Spieler ist noch nicht bereit\n"
	.string "für den Link.\p"
	.string "Bitte kommt wieder, wenn jeder seine\n"
	.string "Vorbereitungen getroffen hat.$"

FallarborTown_ContestLobby_Text_1A4A85:: @ 81A4A85
OldaleTown_PokemonCenter_2F_Text_1A4A85:: @ 81A4A85
	.string "Verbindungsfehler...\n"
	.string "Die Kabelverbindungen überprüfen und\l"
	.string "die Geräte aus- und wieder einschalten.$"

OldaleTown_PokemonCenter_2F_Text_1A4AC8:: @ 81A4AC8
	.string "Tut uns Leid. Hier liegt ein Über-\n"
	.string "tragungsfehler vor. Rekorde können\l"
	.string "nicht in unterschiedlichen Sprachen\l"
	.string "ausgetauscht werden.$"

FallarborTown_ContestLobby_Text_1A4B1D:: @ 81A4B1D
OldaleTown_PokemonCenter_2F_Text_1A4B1D:: @ 81A4B1D
	.string "Die Link-Partner haben eine unter-\n"
	.string "schiedliche Auswahl getroffen.$"

OldaleTown_PokemonCenter_2F_Text_1A4B59:: @ 81A4B59
	.string "Bitte komm bald wieder.$"

OldaleTown_PokemonCenter_2F_Text_1A4B6C:: @ 81A4B6C
	.string "Die Anzahl der Teilnehmer ist nicht\n"
	.string "korrekt.$"

OldaleTown_PokemonCenter_2F_Text_1A4B95:: @ 81A4B95
	.string "Ein EINZELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

OldaleTown_PokemonCenter_2F_Text_1A4BCC:: @ 81A4BCC
	.string "Ein DOPPELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

OldaleTown_PokemonCenter_2F_Text_1A4C03:: @ 81A4C03
	.string "Für diesen Kampfmodus werden vier\n"
	.string "Spieler benötigt.$"

OldaleTown_PokemonCenter_2F_Text_1A4C38:: @ 81A4C38
	.string "Bitte überprüfe die Anzahl der Spieler\n"
	.string "und fange noch einmal an.$"

TradeRoom_WillLinkBeTerminated: @ 81A4C6E
	.string "Wenn du den Raum verlässt, wird die Ver-\n"
	.string "bindung abgebrochen. Einverstanden?$"

TradeRoom_TerminatingLink: @ 81A4CAF
	.string "Verbindung wird abgebrochen... Du wirst\n"
	.string "aus dem Raum begleitet. Bitte warten.$"

CableClub_TooBusyToNotice: @ 81A4CF6
	.string "Dieser TRAINER ist zu beschäftigt...$"

CableClub_LookAtTrainerCard1: @ 81A4D1C
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an!$"

CableClub_LookAtTrainerCard2: @ 81A4D45
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an! Es ist ein\l"
	.string "{STR_VAR_2}PASS.$"

SingleBattleColosseum_Text_1A4D7E:: @ 81A4D7E
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Kampf.$"

TradeCenter_Text_1A4DAB:: @ 81A4DAB
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Tausch.$"

RecordCorner_Text_1A4DD7:: @ 81A4DD7
	.string "Bitte geh in Position und warte.$"

RecordCorner_Text_1A4DF7:: @ 81A4DF7
	.string "Danke für den Besuch!$"

UnknownString_81A4E0A: @ 81A4E0A
	.string "Bitte wähle die POKéMON für den\n"
	.string "MULTIKAMPF.$"

RecordCorner_Text_1A4E3B:: @ 81A4E3B
	.string "{STR_VAR_1} hat ein {STR_VAR_2}\n"
	.string "versendet.$"

OldaleTown_PokemonCenter_2F_Text_1A4E50:: @ 81A4E50
	.string "Der Eintrag auf dem TRAINERPASS wird\n"
	.string "geändert.$"

OldaleTown_PokemonCenter_2F_Text_1A4E79:: @ 81A4E79
	.string "Ich hoffe, du kommst bald wieder vorbei.$"
