Text_PictureBookshelf: @ 81C6A69
	.string "Eine Sammlung von POKéMON-Büchern.$"

Text_Bookshelf: @ 81C6A91
	.string "Hier stehen jede Menge Bücher.$"

Text_PokemonCenterBookshelf: @ 81C6AB6
	.string "POKéMON-Magazine!\n"
	.string "DER POKéMON FREUND...\p"
	.string "POKéMON HANDBUCH...\n"
	.string "GELIEBTE POKéMON...$"

Text_Vase: @ 81C6B00
	.string "Diese Vase sieht sehr teuer aus...\n"
	.string "Schauen wir mal hinein...\p"
	.string "Och, sie ist leer.$"

Text_EmptyTrashCan: @ 81C6B41
	.string "Leer...$"

Text_ShopShelf: @ 81C6B4D
	.string "Die Regale biegen sich unter dem\n"
	.string "Gewicht von POKéMON-Artikeln.$"

Text_Blueprint: @ 81C6B85
	.string "Sind das Blaupausen?\n"
	.string "Die sind zu kompliziert zu lesen.$"
