ContestString_DescHighlyAppealing: @ 83CA4EC
	.string "Eine sehr ansprechende\n"
	.string "Vorführung.$"
ContestString_DescStartled1: @ 83CA505
	.string "Einsatz der Attacke macht\n"
	.string "PKMN leichter irritierbar.$"
ContestString_DescGreatLock: @ 83CA538
	.string "Großartiger Ausdruck, der\n"
	.string "sich nicht steigern lässt.$"
ContestString_DescRepeatable: @ 83CA56D
	.string "Langweilt den JUROR auch\n"
	.string "bei Wiederholung nicht.$"
ContestString_DescStartled2: @ 83CA59E
	.string "Kann Irritation durch\n"
	.string "andere einmal verhindern.$"
ContestString_DescStartled3: @ 83CA5C7
	.string "Kann Irritation durch\n"
	.string "andere verhindern.$"
ContestString_DescStartled4: @ 83CA5EB
	.string "Kann Irritation durch an-\n"
	.string "dere ein wenig eindämmen.$"
ContestString_DescStartled5: @ 83CA618
	.string "Einsatz der Attacke dämmt\n"
	.string "danach Irritation ein.$"
ContestString_DescStartled6: @ 83CA651
	.string "Irritiert das vordere\n"
	.string "POKéMON ein wenig.$"
ContestString_DescStartled7: @ 83CA679
	.string "Irritiert die POKéMON ein\n"
	.string "wenig, die schon auftraten.$"
ContestString_DescStartled8: @ 83CA6A9
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"
ContestString_DescStartled9: @ 83CA6DD
	.string "Irritiert alle POKéMON,\n"
	.string "die bisher auftraten.$"
ContestString_DescStartled10: @ 83CA710
	.string "Irritiert das vordere\n"
	.string "POKéMON sehr stark.$"
ContestString_DescStartled11: @ 83CA735
	.string "Irritiert die POKéMON, die\n"
	.string "schon aufgetreten sind.$"
ContestString_DescStartled12: @ 83CA762
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"
ContestString_DescStartled13: @ 83CA796
	.string "Irritiert alle POKéMON, die\n"
	.string "vorher aufgetreten sind.$"
ContestString_DescAttentionShift: @ 83CA7CA
	.string "Lenkt den JUROR von den\n"
	.string "anderen POKéMON ab.$"
ContestString_DescStartled14: @ 83CA7F4
	.string "Irritiert PKMN, bes. die,\n"
	.string "auf die der JUROR achtet.$"
ContestString_DescJamOthersMissTurn: @ 83CA829
	.string "Stört die anderen und An-\n"
	.string "wender setzt 1 Runde aus.$"
ContestString_DescStartled15: @ 83CA85A
	.string "Irritiert PKMN, bes. die, die\n"
	.string "Ausdruck gl. Typs zeigten.$"
ContestString_DescStartled16: @ 83CA889
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs COOL vorführten.$"
ContestString_DescStartled17: @ 83CA8B8
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs SCHÖN vorführten.$"
ContestString_DescStartled18: @ 83CA8E9
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs ANMUT vorführten.$"
ContestString_DescStartled19: @ 83CA918
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs KLUG vorführten.$"
ContestString_DescStartled20: @ 83CA948
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs STARK vorführten.$"

ContestString_DescNervousOne: @ 83CA978
	.string "Macht nachfolgendes\n"
	.string "POKéMON nervös.$"

ContestString_DescNervousAllAfter: @ 83CA9A2
	.string "Macht alle nachfolgenden\n"
	.string "POKéMON nervös.$"

ContestString_DescConditionWorseBefore: @ 83CA9CC
	.string "Schwächt Kondition der\n"
	.string "PKMN, die bisher auftraten.$"

ContestString_DescStartled21: @ 83CA9FE
	.string "Irritiert POKéMON, die eine\n"
	.string "gute Kondition haben.$"
ContestString_DescGreatWhenFirst: @ 83CAA28
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn als Erster vorgeführt.$"
ContestString_DescGreatWhenLast: @ 83CAA53
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn zuletzt vorgeführt.$"
ContestString_DescAppealGoodBeforeAll: @ 83CAA7D
	.string "Ausdruck gelingt so gut\n"
	.string "wie die der Vorgänger.$"
ContestString_DescAppealGoodBeforeOne: @ 83CAAAA
	.string "Ausdruck gelingt so gut\n"
	.string "wie der des Vorgängers.$"
ContestString_DescBetterWhenLater: @ 83CAAD9
	.string "Je später der Auftritt,\n"
	.string "desto besser der Ausdruck.$"
ContestString_DescAffectedByTiming: @ 83CAB0C
	.string "Die Qualität des Ausdrucks\n"
	.string "hängt vom Timing ab.$"
ContestString_DescBetterWhenSameType: @ 83CAB41
	.string "Gelingt gut, wenn vom\n"
	.string "selben Typ wie der vorige.$"
ContestString_DescBetterWhenDiffType: @ 83CAB75
	.string "Gelingt gut, wenn vom\n"
	.string "anderen Typ als der vorige.$"
ContestString_DescAffectedByFront: @ 83CABAA
	.string "Hängt von Qualität des Aus-\n"
	.string "drucks des Vorgängers ab.$"
ContestString_DescConditionUp: @ 83CABD9
	.string "Verbessert die Kondition\n"
	.string "und verhindert Nervosität.$"
ContestString_DescAffectedByCondition: @ 83CAC0E
	.string "Ausdruck gelingt gut, wenn\n"
	.string "Kondition des PKMN gut ist.$"
ContestString_DescAppealEarlier: @ 83CAC45
	.string "Der nächste Ausdruck kann\n"
	.string "früher vorgeführt werden.$"
ContestString_DescAppealLater: @ 83CAC74
	.string "Der nächste Ausdruck kann\n"
	.string "später vorgeführt werden.$"
ContestString_DescRandomOrderEasier: @ 83CACA1
	.string "Ändert die Reihenfolge der\n"
	.string "nächst. Auftritte leichter.$"
ContestString_DescRandomOrder: @ 83CACD4
	.string "Ändert die Reihenfolge der\n"
	.string "nächsten Auftritte.$"
ContestString_DescAnyExcitement: @ 83CAD05
	.string "Verzückt das Publikum in \n"
	.string "jedem WETTBEWERB.$"
ContestString_DescStartled22: @ 83CAD39
	.string "Irritiert alle POKéMON,\n"
	.string "deren Ausdruck gut war.$"
ContestString_DescScaleWithExcitement: @ 83CAD6C
	.string "Gelingt am besten, wenn\n"
	.string "das Publikum gespannt ist.$"
ContestString_DescStopExcitement: @ 83CADA1
	.string "Bremst zeitweise Begeis-\n"
	.string "terung des Publikums.$"

	.align 2
gContestEffectStrings:: @ 83CADD4
	.4byte ContestString_DescHighlyAppealing
	.4byte ContestString_DescStartled1
	.4byte ContestString_DescGreatLock
	.4byte ContestString_DescRepeatable
	.4byte ContestString_DescStartled2
	.4byte ContestString_DescStartled3
	.4byte ContestString_DescStartled4
	.4byte ContestString_DescStartled5
	.4byte ContestString_DescStartled6
	.4byte ContestString_DescStartled7
	.4byte ContestString_DescStartled8
	.4byte ContestString_DescStartled9
	.4byte ContestString_DescStartled10
	.4byte ContestString_DescStartled11
	.4byte ContestString_DescStartled12
	.4byte ContestString_DescStartled13
	.4byte ContestString_DescAttentionShift
	.4byte ContestString_DescStartled14
	.4byte ContestString_DescJamOthersMissTurn
	.4byte ContestString_DescStartled15
	.4byte ContestString_DescStartled16
	.4byte ContestString_DescStartled17
	.4byte ContestString_DescStartled18
	.4byte ContestString_DescStartled19
	.4byte ContestString_DescStartled20
	.4byte ContestString_DescNervousOne
	.4byte ContestString_DescNervousAllAfter
	.4byte ContestString_DescConditionWorseBefore
	.4byte ContestString_DescStartled21
	.4byte ContestString_DescGreatWhenFirst
	.4byte ContestString_DescGreatWhenLast
	.4byte ContestString_DescAppealGoodBeforeAll
	.4byte ContestString_DescAppealGoodBeforeOne
	.4byte ContestString_DescBetterWhenLater
	.4byte ContestString_DescAffectedByTiming
	.4byte ContestString_DescBetterWhenSameType
	.4byte ContestString_DescBetterWhenDiffType
	.4byte ContestString_DescAffectedByFront
	.4byte ContestString_DescConditionUp
	.4byte ContestString_DescAffectedByCondition
	.4byte ContestString_DescAppealEarlier
	.4byte ContestString_DescAppealLater
	.4byte ContestString_DescRandomOrderEasier
	.4byte ContestString_DescRandomOrder
	.4byte ContestString_DescAnyExcitement
	.4byte ContestString_DescStartled22
	.4byte ContestString_DescScaleWithExcitement
	.4byte ContestString_DescStopExcitement

ContestString_MoveRainDance: @ 83CAE94
	.string "REGENTANZ$"
ContestString_MoveRage: @ 83CAE9F
	.string "RASEREI$"
ContestString_MoveFocusEnergy: @ 83CAEA4
	.string "ENERGIEFOKUS$"
ContestString_MoveHypnosis: @ 83CAEB1
	.string "HYPNOSE$"
ContestString_MoveSoftboiled: @ 83CAEBA
	.string "WEICHEI$"
ContestString_MoveHornAttack: @ 83CAEC5
	.string "HORNATTACKE$"
ContestString_MoveSwordsDance: @ 83CAED1
	.string "SCHWERTTANZ$"
ContestString_MoveConversion: @ 83CAEDE
	.string "UMWANDLUNG$"
ContestString_MoveSunnyDay: @ 83CAEE9
	.string "SONNENTAG$"
ContestString_MoveRest: @ 83CAEF3
	.string "ERHOLUNG$"
ContestString_MoveVicegrip: @ 83CAEF8
	.string "KLAMMER$"
ContestString_MoveDefenseCurl: @ 83CAF01
	.string "EINIGLER$"
ContestString_MoveLockOn: @ 83CAF0E
	.string "ZIELSCHUSS$"

	.align 2
	.4byte ContestString_MoveRainDance
	.4byte ContestString_MoveRainDance
	.4byte ContestString_MoveRage
	.4byte ContestString_MoveFocusEnergy
	.4byte ContestString_MoveHypnosis
	.4byte ContestString_MoveSoftboiled
	.4byte ContestString_MoveHornAttack
	.4byte ContestString_MoveSwordsDance
	.4byte ContestString_MoveConversion
	.4byte ContestString_MoveSunnyDay
	.4byte ContestString_MoveRest
	.4byte ContestString_MoveVicegrip
	.4byte ContestString_MoveDefenseCurl
	.4byte ContestString_MoveLockOn

ContestString_Cool:
	.string "COOL.$"
ContestString_Beauty:
	.string "SCHÖN.$"
ContestString_Cute:
	.string "ANMUT$"
ContestString_Smart:
	.string "KLUG.$"
ContestString_Tough:
	.string "STÄRKE$"

	.align 2
gContestCategoryNames:: @ 83CAF70
	.4byte ContestString_Cool
	.4byte ContestString_Beauty
	.4byte ContestString_Cute
	.4byte ContestString_Smart
	.4byte ContestString_Tough

gText_Contest_WhichMoveWillBePlayed:: @ 83CAF84
	.string "Ausdruck {NAME_END}! Welche\n"
	.string "Attacke wird gezeigt?$"

gText_Contest_ButItCantParticipate:: @ 83CAFAE
	.string "Ausdruck {NAME_END}! Aber es\n"
	.string "kann nicht teilnehmen!$"

gUnknown_083CAFD7:: @ 83CAFD7
	.string "{STR_VAR_1} führt\n"
	.string "{STR_VAR_2} vor!$"

	.string "Die anderen POKéMON\n"
	.string "zeigten ihre Attacken!$"

gUnknown_083CB00D:: @ 83CB00D
	.string "{STR_VAR_1} beobachtet\n"
	.string "die anderen.{PAUSE 60}$"

gUnknown_083CB02C:: @ 83CB02C
	.string "Soweit zur\n"
	.string "Ausdruckskraft!{PAUSE 60}$"

	.string "{STR_VAR_3}-\n"
	.string "Att. {STR_VAR_2}\n"
	.string "von {STR_VAR_1}!$"

	.string "TRICK$"

	.string "SPEZIAL$"

ContestString_AppealJammed:
	.string "Der Auftritt\n"
	.string "wurde gestört.$"
ContestString_FollowLead:
	.string "Es folgte einem\n"
	.string "anderen POKéMON.$"
ContestString_MessedUp:
	.string "Es scheiterte.$"
ContestString_BetterUsual:
	.string "Das lief besser\n"
	.string "als sonst.$"
ContestString_JudgeLookAway:
	.string "Der JUROR war\n"
	.string "irgendwie abgelenkt.$"
ContestString_WorkHard:
	.string "Es strengte sich an,\n"
	.string "Fehler auszubügeln.$"
ContestString_NoMoreMoves:
	.string "Es kann keine Attacken\n"
	.string "mehr ausführen.$"
ContestString_WorkReallyWell:
	.string "Das lief unheimlich gut.$"
ContestString_WorkHardStandout:
	.string "Es strengte sich genauso\n"
	.string "wie das beste POKéMON an.$"
ContestString_JudgeExpectantly:
	.string "Der JUROR schaute es\n"
	.string "besonders aufmerksam an.$"
ContestString_WorkRatherWell:
	.string "Das lief bedeutend\n"
	.string "besser.$"
ContestString_WorkBetter:
	.string "Es lief etwas besser\n"
	.string "als sonst.$"

	.align 2
	.4byte ContestString_AppealJammed
	.4byte ContestString_FollowLead
	.4byte ContestString_MessedUp
	.4byte ContestString_BetterUsual
	.4byte ContestString_BetterUsual
	.4byte ContestString_JudgeLookAway
	.4byte ContestString_WorkHard
	.4byte ContestString_NoMoreMoves
	.4byte ContestString_WorkReallyWell
	.4byte ContestString_WorkHardStandout
	.4byte ContestString_JudgeExpectantly
	.4byte ContestString_WorkRatherWell
	.4byte ContestString_WorkBetter

ContestString_StandOutNone:
	.string "{STR_VAR_1} stach\n"
	.string "überhaupt nicht hervor...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutNotMuch:
	.string "{STR_VAR_1} stach nicht\n"
	.string "besonders hervor...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLittle:
	.string "{STR_VAR_1} erregte ein\n"
	.string "wenig Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLot:
	.string "{STR_VAR_1} erregte eine\n"
	.string "Menge Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutTotal:
	.string "{STR_VAR_1} erhielt die\n"
	.string "volle Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutDidnt:
	.string "{STR_VAR_1} konnte\n"
	.string "keinen Ausdruck zeigen.{PAUSE_UNTIL_PRESS}$"

	.align 2
gContestStandOutStrings:: @ 83CB2F0
	.4byte ContestString_StandOutNone
	.4byte ContestString_StandOutNotMuch
	.4byte ContestString_StandOutLittle
	.4byte ContestString_StandOutLot
	.4byte ContestString_StandOutTotal
	.4byte ContestString_StandOutDidnt

ContestString_AppealAnticipation3:
	.string "Heiß ersehnt: Der Aus-\n"
	.string "druck von {STR_VAR_1}.$"
ContestString_JudgeSatisfied:
	.string "Der JUROR war sehr\n"
	.string "zufrieden.$"
ContestString_Terminator:
	.string "$"
ContestString_JudgeHeldFirm:
	.string "Der JUROR behält\n"
	.string "{STR_VAR_1} fest im Blick.$"
ContestString_ChangedPerceptions:
	.string "{STR_VAR_3} von {STR_VAR_1}\n"
	.string "ändert die Wahrnehmung.$"
ContestString_AppealWoreOff:
	.string "Wirkung von {STR_VAR_1}\n"
	.string "lässt nach.$"
ContestString_AppealWoreOff2:
	.string "Die besondere Wirkung\n"
	.string "lässt nach.$"
ContestString_AppealLookSame:
	.string "Jeder Ausdruck wird sich\n"
	.string "nun gleichen.$"
ContestString_AppealCheapened:
	.string "Ausdruck von {STR_VAR_2}\n"
	.string "wurde abgewertet.$"
ContestString_AppealCheapened2:
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen PKMN ab.$"
ContestString_AppealAttentionStolen:
	.string "Es stahl {STR_VAR_2} die\n"
	.string "Aufmerksamkeit.$"
ContestString_AppealCheapened3:
	.string "Es wertete Ausdruck\n"
	.string "von {STR_VAR_2} ab.$"
ContestString_AppealCheapened4:
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen stark ab.$"
ContestString_AppealAnticipation:
	.string "Alle warten sehnsüchtig\n"
	.string "auf {STR_VAR_1}.$"
ContestString_AppealCheapened5:
	.string "Es wertete den Ausdruck\n"
	.string "der PKMN vor ihm ab.$"
ContestString_AppealCheapened6:
	.string "Es wertete den Lieblings-\n"
	.string "ausdruck des JURORS ab.$"
ContestString_AppealCheapened7:
	.string "Der Ausdruckswert der\n"
	.string "anderen wurde halbiert.$"
ContestString_JammedStoodOut:
	.string "Es macht sich bereit, die\n"
	.string "anderen zu beeindrucken.$"
ContestString_AppealNoMore:
	.string "Es kann an keiner Vor-\n"
	.string "führung mehr teilnehmen.$"
ContestString_AppealTouched:
	.string "Der fantastische Aus-\n"
	.string "druck berührte den JUROR.$"
ContestString_AppealAnticipation2:
	.string "Die Erwartung für die fol-\n"
	.string "genden Ausdrücke steigt.$"
ContestString_AppealStoodOut2:
	.string "Es war so beeindruckend\n"
	.string "wie ein Spezialausdruck.$"
ContestString_AppealStoodOut3:
	.string "Es war so beeindruckend\n"
	.string "wie {STR_VAR_1}.$"
ContestString_JammedAppealsNotice:
	.string "Ein Ausdruck, der gestört\n"
	.string "wurde, ist unauffälliger.$"
ContestString_AppealSame:
	.string "Jeder Teilnehmer hat nun\n"
	.string "den gleichen Ausdruck.$"
ContestString_AppealFullWorse:
	.string "{STR_VAR_1} ist voll. Der\n"
	.string "Ausdruck wird schlechter.$"

	.align 2
	.4byte ContestString_JudgeHeldFirm
	.4byte ContestString_ChangedPerceptions
	.4byte ContestString_Terminator
	.4byte ContestString_AppealWoreOff
	.4byte ContestString_AppealWoreOff2
	.4byte ContestString_AppealLookSame
	.4byte ContestString_AppealCheapened
	.4byte ContestString_AppealCheapened2
	.4byte ContestString_AppealAttentionStolen
	.4byte ContestString_AppealCheapened3
	.4byte ContestString_AppealCheapened4
	.4byte ContestString_AppealAnticipation
	.4byte ContestString_AppealCheapened5
	.4byte ContestString_AppealCheapened6
	.4byte ContestString_AppealCheapened7
	.4byte ContestString_JammedStoodOut
	.4byte ContestString_AppealNoMore
	.4byte ContestString_AppealTouched
	.4byte ContestString_AppealAnticipation2
	.4byte ContestString_AppealStoodOut2
	.4byte ContestString_AppealStoodOut3
	.4byte ContestString_Terminator
	.4byte ContestString_Terminator
	.4byte ContestString_Terminator
	.4byte ContestString_JammedAppealsNotice
	.4byte ContestString_AppealSame
ContestString_MoreConscious:
	.string "Es wird sich der anderen\n"
	.string "PKMN mehr bewusst.{PAUSE 60}$"
ContestString_NoAppeal:
	.string "{STR_VAR_1} kann danach\n"
	.string "keinen Ausdruck zeigen.{PAUSE 60}$"
ContestString_SettleDown:
	.string "Es kommt ein wenig\n"
	.string "zur Ruhe.{PAUSE 60}$"
ContestString_ObliviousToOthers:
	.string "Die anderen PKMN nehmen\n"
	.string "es überhaupt nicht wahr.{PAUSE 60}$"
ContestString_LessAware:
	.string "Es ist sich der anderen\n"
	.string "PKMN kaum bewusst.{PAUSE 60}$"
ContestString_StoppedCaring:
	.string "Es kümmert sich nicht\n"
	.string "mehr viel um andere PKMN.{PAUSE 60}$"
ContestString_StartleAttempt:
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 60}$"
ContestString_DazzleAttempt:
	.string "Es versucht, die anderen\n"
	.string "PKMN zu blenden.{PAUSE 60}$"
ContestString_JudgeLookAway2:
	.string "Der JUROR schaut\n"
	.string "{STR_VAR_1} nicht mehr an.{PAUSE 60}$"
ContestString_UnnerveAttempt:
	.string "Es versucht, die folgenden\n"
	.string "PKMN zu entnerven.{PAUSE 60}$"
ContestString_Nervous:
	.string "{STR_VAR_1} wird\n"
	.string "nervös.{PAUSE 60}$"
ContestString_UnnerveWaiting:
	.string "Dieser Ausdruck soll die\n"
	.string "anderen PKMN entnerven.{PAUSE 60}$"
ContestString_TauntWell:
	.string "Es verhöhnt die\n"
	.string "besseren PKMN.{PAUSE 60}$"
ContestString_RegainedForm:
	.string "{STR_VAR_1} findet zu\n"
	.string "seiner Form zurück.{PAUSE 60}$"
ContestString_JamWell:
	.string "Es versucht, die besseren\n"
	.string "PKMN zu beeindrucken.{PAUSE 60}$"
ContestString_HustleStandout:
	.string "{STR_VAR_1} an der Spitze\n"
	.string "engagiert sich noch mehr.{PAUSE 60}$"
ContestString_WorkHardUnnoticed:
	.string "Das bisher unauffällige\n"
	.string "{STR_VAR_1} gibt alles.$"
ContestString_WorkBefore:
	.string "Es strengt sich genauso\n"
	.string "an wie die PKMN vor ihm.{PAUSE 60}$"
ContestString_AppealNotWell:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam nicht gut an.{PAUSE 60}$"
ContestString_WorkPreceding:
	.string "Es strengt sich an wie die\n"
	.string "vorangegangenen PKMN.{PAUSE 60}$"
ContestString_AppealNotWell2:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 60}$"
ContestString_AppealNotShownWell:
	.string "Ausdruck v. {STR_VAR_1}: \n"
	.string "Wurde gestört.{PAUSE 60}$"
ContestString_AppealSlightlyWell:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 60}$"
ContestString_AppealPrettyWell:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 60}$"
ContestString_AppealExcellently:
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 60}$"
ContestString_AppealDud:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war absolut mies.{PAUSE 60}$"
ContestString_AppealNotVeryWell:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war nicht so gut.{PAUSE 60}$"
ContestString_AppealSlightlyWell2:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war nicht schlecht.{PAUSE 60}$"
ContestString_AppealPrettyWell2:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war recht gut.{PAUSE 60}$"
ContestString_AppealVeryWell:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war sehr gut.{PAUSE 60}$"
ContestString_AppealExcellently2:
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war exzellent.{PAUSE 60}$"
ContestString_SameTypeGood:
	.string "Der gleiche Typ wie das\n"
	.string "vorhergehende PKMN - gut!{PAUSE 60}$"
ContestString_DiffTypeGood:
	.string "Nicht der gleiche Typ wie\n"
	.string "das vorherige PKMN - gut!{PAUSE 60}$"
ContestString_StoodOutAsMuch:
	.string "Es ist viel besser als die\n"
	.string "vorhergehenden PKMN.{PAUSE 60}$"
ContestString_NotAsWell:
	.string "Es war nicht so gut wie\n"
	.string "das PKMN vor ihm.{PAUSE 60}$"
ContestString_ConditionRose:
	.string "Die Kondition von\n"
	.string "{STR_VAR_1} stieg.{PAUSE 60}$"
ContestString_HotStatus:
	.string "Status von {STR_VAR_1}:\n"
	.string "Bewirkt guten Ausdruck!{PAUSE 60}$"
ContestString_MoveUpLine:
	.string "Es steigt in der Reihen-\n"
	.string "folge auf.{PAUSE 60}$"
ContestString_MoveBackLine:
	.string "Es fällt in der Reihen-\n"
	.string "folge zurück.{PAUSE 60}$"
ContestString_ScrambleOrder:
	.string "Es bringt die Reihenfolge\n"
	.string "durcheinander.{PAUSE 60}$"

gUnknown_083CBD52:: @ 83CBD52
ContestString_JudgeExpectantly2::
	.string "Der JUROR betrachtet\n"
	.string "{STR_VAR_1} interessiert.{PAUSE 60}$"

gUnknown_083CBD79:: @ 83CBD79
ContestString_WentOverWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam gut an.{PAUSE 60}$"

gUnknown_083CBD9D:: @ 83CBD9D
ContestString_WentOverVeryWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam sehr gut an.{PAUSE 60}$"

gUnknown_083CBDC6:: @ 83CBDC6
ContestString_AppealComboExcellently::
	.string "Die Combo der Ausdrücke\n"
	.string "kam exzellent an.{PAUSE 60}$"
ContestString_AvertGaze:
	.string "{STR_VAR_1} gelingt es,\n"
	.string "den Blick abzuwenden.{PAUSE 60}$"
ContestString_AvoidSeeing:
	.string "{STR_VAR_1} wandte den\n"
	.string "Blick erfolgreich ab.{PAUSE 60}$"
ContestString_NotFazed:
	.string "{STR_VAR_1} lässt sich\n"
	.string "davon nicht ablenken.{PAUSE 60}$"
ContestString_LittleDistracted:
	.string "{STR_VAR_1} wurde etwas\n"
	.string "unruhig.{PAUSE 60}$"
ContestString_AttemptStartle:
	.string "Es versucht, die anderen\n"
	.string "PKMN zu verschrecken.{PAUSE 60}$"
ContestString_LookedDown:
	.string "{STR_VAR_1} blickt\n"
	.string "irritiert zu Boden.{PAUSE 60}$"
ContestString_TurnedBack:
	.string "{STR_VAR_1} dreht sich\n"
	.string "irritiert um.{PAUSE 60}$"
ContestString_UtterCry:
	.string "{STR_VAR_1} kann einen \n"
	.string "Laut nicht unterdrücken.{PAUSE 60}$"
ContestString_LeaptUp:
	.string "{STR_VAR_1} kann nicht\n"
	.string "anders und springt auf.{PAUSE 60}$"
ContestString_TrippedOver:
	.string "{STR_VAR_1} ist so irri-\n"
	.string "tiert, dass es stolpert.{PAUSE 60}$"

gUnknown_083CBF60:: @ 83CBF60
ContestString_TooNervous:
	.string "{STR_VAR_1} ist zu nervös,\n"
	.string "um etwas vorzuführen.{PAUSE 60}$"
ContestString_MessedUp2:
	.string "Es hatte keinen Erfolg.{PAUSE 60}$"
ContestString_FailedTargetNervous:
	.string "Es konnte keine\n"
	.string "Nervosität erzeugen.{PAUSE 60}$"
ContestString_FailedAnyoneNervous:
	.string "Aber es konnte niemanden\n"
	.string "nervös machen.{PAUSE 60}$"
ContestString_Ignored:
	.string "Es wurde ignoriert...{PAUSE 60}$"
ContestString_NoConditionImprove:
	.string "Es konnte seinen Aus-\n"
	.string "druck nicht verstärken...{PAUSE 60}$"
ContestString_BadConditionWeakAppeal:
	.string "Schwacher Ausdruck we-\n"
	.string "gen schlechter Konditon.{PAUSE 60}$"
ContestString_Unaffected:
	.string "{STR_VAR_1} blieb\n"
	.string "unbeeindruckt.{PAUSE 60}$"

gUnknown_083CC075:: @ 83CC075
ContestString_DissapointedRepeat::
	.string "{STR_VAR_1} enttäuscht\n"
	.string "durch Wiederholung.{PAUSE 60}$"

gUnknown_083CC0A0:: @ 83CC0A0
ContestString_WentOverGreat::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war sehr gut.{PAUSE 60}$"

gUnknown_083CC0BC:: @ 83CC0BC
ContestString_DidntGoWell::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war nicht gut.{PAUSE 60}$"

gUnknown_083CC0E3:: @ 83CC0E3
ContestString_GotCrowdGoing::
	.string "{STR_VAR_1} begeistert\n"
	.string "Publikum mit {STR_VAR_3}.{PAUSE 60}$"

gUnknown_083CC103:: @ 83CC103
ContestString_CantAppealNextTurn::
	.string "{STR_VAR_1} setzt in der \n"
	.string "folgenden Runde aus.{PAUSE 60}$"
ContestString_AttractedAttention::
	.string "Die Aufmerksamkeit des\n"
	.string "Publikums liegt auf ihm.{PAUSE 60}$"

gUnknown_083CC14A:: @ 83CC14A
ContestString_CrowdWatches::
	.string "Das Publikum beobachtet\n"
	.string "weiterhin {STR_VAR_3}.{PAUSE 60}$"

gUnknown_083CC16E:: @ 83CC16E
ContestString_Ignored2::
	.string "{STR_VAR_2} von\n"
	.string "{STR_VAR_1} ist ignoriert.{PAUSE 60}$"

	.align 2
gUnknown_083CC188:: @ 83CC188
	.4byte ContestString_MoreConscious
	.4byte ContestString_NoAppeal
	.4byte ContestString_SettleDown
	.4byte ContestString_ObliviousToOthers
	.4byte ContestString_LessAware
	.4byte ContestString_StoppedCaring
	.4byte ContestString_StartleAttempt
	.4byte ContestString_DazzleAttempt
	.4byte ContestString_JudgeLookAway2
	.4byte ContestString_UnnerveAttempt
	.4byte ContestString_Nervous
	.4byte ContestString_UnnerveWaiting
	.4byte ContestString_TauntWell
	.4byte ContestString_RegainedForm
	.4byte ContestString_JamWell
	.4byte ContestString_HustleStandout
	.4byte ContestString_WorkHardUnnoticed
	.4byte ContestString_WorkBefore
	.4byte ContestString_AppealNotWell
	.4byte ContestString_WorkPreceding
	.4byte ContestString_AppealNotWell2
	.4byte ContestString_AppealNotShownWell
	.4byte ContestString_AppealSlightlyWell
	.4byte ContestString_AppealPrettyWell
	.4byte ContestString_AppealExcellently
	.4byte ContestString_AppealDud
	.4byte ContestString_AppealNotVeryWell
	.4byte ContestString_AppealSlightlyWell2
	.4byte ContestString_AppealPrettyWell2
	.4byte ContestString_AppealVeryWell
	.4byte ContestString_AppealExcellently2
	.4byte ContestString_SameTypeGood
	.4byte ContestString_DiffTypeGood
	.4byte ContestString_StoodOutAsMuch
	.4byte ContestString_NotAsWell
	.4byte ContestString_ConditionRose
	.4byte ContestString_HotStatus
	.4byte ContestString_MoveUpLine
	.4byte ContestString_MoveBackLine
	.4byte ContestString_ScrambleOrder
	.4byte ContestString_JudgeExpectantly2 @ expectantly
	.4byte ContestString_WentOverWell
	.4byte ContestString_WentOverVeryWell
	.4byte ContestString_AppealComboExcellently
	.4byte ContestString_AvertGaze
	.4byte ContestString_AvoidSeeing
	.4byte ContestString_NotFazed
	.4byte ContestString_LittleDistracted
	.4byte ContestString_AttemptStartle
	.4byte ContestString_LookedDown
	.4byte ContestString_TurnedBack
	.4byte ContestString_UtterCry
	.4byte ContestString_LeaptUp
	.4byte ContestString_TrippedOver
	.4byte ContestString_MessedUp2
	.4byte ContestString_FailedTargetNervous
	.4byte ContestString_FailedAnyoneNervous
	.4byte ContestString_Ignored
	.4byte ContestString_NoConditionImprove
	.4byte ContestString_BadConditionWeakAppeal
	.4byte ContestString_Unaffected
	.4byte ContestString_AttractedAttention

gText_Contest_Shyness:: @ 83CC280
	.string "Scheu$"

gText_Contest_Anxiety:: @ 83CC288
	.string "Besorgnis$"

gText_Contest_Laziness:: @ 83CC290
	.string "Faulheit$"

gText_Contest_Hesitancy:: @ 83CC299
	.string "Zögern$"

gText_Contest_Fear:: @ 83CC2A3
	.string "Furcht$"

ContestString_Coolness:
	.string "Coolness$"
ContestString_Beauty2:
	.string "Schönheit$"
ContestString_Cuteness:
	.string "Anmut$"
ContestString_Smartness:
	.string "Klugheit$"
ContestString_Toughness:
	.string "Stärke$"

	.align 2
gContestCategoryStrings:: @ 83CC2D8
	.4byte ContestString_Coolness
	.4byte ContestString_Beauty2
	.4byte ContestString_Cuteness
	.4byte ContestString_Smartness
	.4byte ContestString_Toughness

gUnknown_083CC2EC:: @ 83CC2EC
	.string "SPANNUNG:$"

ContestString_CoolMove:
	.string "COOLE Att.$"

ContestString_BeautyMove:
	.string "SCHÖNE Att.$"

ContestString_CuteMove:
	.string "ANMUT-Att.$"

ContestString_SmartMove:
	.string "KLUGE Att.$"

ContestString_ToughMove:
	.string "STARKE Att.$"

ContestString_UnknownMoveType:
	.string "???$"

	.align 2
gUnknown_083CC330:: @ 83CC330
	.4byte ContestString_CoolMove
	.4byte ContestString_BeautyMove
	.4byte ContestString_CuteMove
	.4byte ContestString_SmartMove
	.4byte ContestString_ToughMove
	.4byte ContestString_UnknownMoveType

@ unused?
ContestString_Rank:
	.string "KLASSE$"

	.string "{HIGHLIGHT TRANSPARENT}{COLOR MAGENTA} $"
