LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:: @ 81C4B5E
	.string "Dies ist die POKéMON-LOTTERIE.\p"
	.string "Alle Besucher des EINKAUFSZENTRUMS\n"
	.string "können einen POKéMON-LOTTOSCHEIN\l"
	.string "ziehen.\p"
	.string "Wenn die Nummer des LOTTOSCHEINS mit\n"
	.string "der ID-Nummer eines deiner POKéMON\l"
	.string "übereinstimmt, gewinnst du einen Preis.\p"
	.string "Möchtest du einen\n"
	.string "POKéMON-LOTTOSCHEIN ziehen?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:: @ 81C4C6A
	.string "Bitte, komme morgen wieder.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:: @ 81C4C85
	.string "Bitte, besuche uns bald wieder.$"

UnknownString_81C4C9F: @ 81C4C9F
	.string "Bitte, ziehe einen LOTTOSCHEIN.\n"
	.string "... ... ...$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:: @ 81C4CC6
	.string "Bitte, ziehe einen LOTTOSCHEIN.\n"
	.string "...{0xFC}Ë{0x39} ...{0xFC}Ë{0x39} ...{0xFC}Ë{0x39}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:: @ 81C4CF6
	.string "Der LOTTOSCHEIN hat die Nummer {STR_VAR_1}.\p"
	.string "Ich muss diese Nummer jetzt prüfen,\n"
	.string "um zu sehen, ob sie mit der ID-Nummer\l"
	.string "eines deiner POKéMON übereinstimmt.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:: @ 81C4D7D
	.string "Herzlichen Glückwunsch!\p"
	.string "Die ID-Nummer deines {STR_VAR_1} im\n"
	.string "Team stimmt mit der des LOTTO-\l"
	.string "SCHEINS überein!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:: @ 81C4DD1
	.string "Herzlichen Glückwunsch!\p"
	.string "Die ID-Nummer deines {STR_VAR_1} in\n"
	.string "der Box des PCs stimmt mit der des\l"
	.string "LOTTOSCHEINS überein!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:: @ 81C4E27
	.string "Tut mir Leid.\n"
	.string "Keine der Nummern stimmt überein.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:: @ 81C4E4F
	.string "Zwei Ziffern stimmen überein,\n"
	.string "daher bekommst du den dritten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:: @ 81C4E92
	.string "Drei Ziffern stimmen überein,\n"
	.string "daher bekommst du den zweiten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:: @ 81C4ED8
	.string "Vier Ziffern stimmen überein,\n"
	.string "daher bekommst du den ersten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:: @ 81C4F1C
	.string "Meine Güte! Alle fünf Ziffern stimmen\n"
	.string "überein!\p"
	.string "Du hast den Jackpot geknackt!\n"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:: @ 81C4F77
	.string "Oh! Du scheinst keinen Platz\n"
	.string "dafür zu haben.\p"
	.string "Wenn du wieder Platz in deinem BEUTEL\n"
	.string "hast, lass es mich wissen.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:: @ 81C4FCC
	.string "{PLAYER}?\n"
	.string "Ja, ich habe dich schon erwartet.\p"
	.string "Diesen Preis habe ich für dich\n"
	.string "aufbewahrt.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:: @ 81C501C
	.string "Bitte, besuche uns bald wieder.$"
