SeafloorCavern_Room9_Text_1B4850:: @ 81B4850
	.string "MARC: Bleib sofort stehen!$"

SeafloorCavern_Room9_Text_1B486C:: @ 81B486C
	.string "MARC: Hahahaha...\n"
	.string "Du warst das also die ganze Zeit!$"

SeafloorCavern_Room9_Text_1B4897:: @ 81B4897
	.string "MARC: Schau nur, schau nur!\p"
	.string "Schau, wie schön die schlafende Gestalt\n"
	.string "des antiken POKéMON GROUDON ist!\p"
	.string "Ich habe so lange auf diesen Tag\n"
	.string "gewartet...$"

SeafloorCavern_Room9_Text_1B491F:: @ 81B491F
	.string "MARC: Es überrascht mich, wie du es ge-\n"
	.string "schafft hast, mir zu folgen.\p"
	.string "Aber das ist nun alles Nebensache.\p"
	.string "Damit meine Träume wahr werden, musst\n"
	.string "du leider verschwinden!$"

SeafloorCavern_Room9_Text_1B49AE:: @ 81B49AE
	.string "Ich...\n"
	.string "Ich habe wieder verloren?$"

SeafloorCavern_Room9_Text_1B49C1:: @ 81B49C1
	.string "MARC: Kicher...\p"
	.string "Ich empfehle mich. Ich muss sagen, du\n"
	.string "bist wirklich sehr talentiert.\p"
	.string "Aber!\n"
	.string "Ich habe dieses hier in meinem Besitz!\p"
	.string "Mit dieser BLAUEN KUGEL kann ich\n"
	.string "GROUDON...$"

SeafloorCavern_Room9_Text_1B4A5A:: @ 81B4A5A
	.string "Die BLAUE KUGEL beginnt plötzlich von\n"
	.string "innen heraus zu leuchten!$"

SeafloorCavern_Room9_Text_1B4A89:: @ 81B4A89
	.string "MARC: Was?!?\p"
	.string "Ich habe doch gar nichts gemacht.\n"
	.string "Die BLAUE KUGEL... Warum...\p"
	.string "Wo ist GROUDON geblieben?$"

SeafloorCavern_Room9_Text_1B4ADB:: @ 81B4ADB
	.string "MARC: Hm? Dies ist eine Nachricht\n"
	.string "unserer Mitglieder draußen...$"

SeafloorCavern_Room9_Text_1B4B11:: @ 81B4B11
	.string "MARC: Ja, was ist denn jetzt los?\p"
	.string "Hm...\n"
	.string "Die Sonne scheint? So extrem?\p"
	.string "Gut... Genau darauf habe ich gewartet.\n"
	.string "Deshalb haben wir GROUDON erweckt.\l"
	.string "Um TEAM MAGMAS Vision von der Erweite-\l"
	.string "rung der Landmassen zu realisieren.\p"
	.string "Was?!?\p"
	.string "Es ist heißer, als wir es vorausgesagt\n"
	.string "haben? Die Hitze ist sogar gefährlich?\p"
	.string "Das kann nicht sein...\n"
	.string "Das ist unmöglich...\p"
	.string "Bleib wo du bist und behalte die\n"
	.string "Situation im Auge!$"

SeafloorCavern_Room9_Text_1B4C79:: @ 81B4C79
	.string "MARC: Irgendetwas stimmt da ganz und\n"
	.string "gar nicht...\p"
	.string "Die BLAUE KUGEL sollte GROUDON auf-\n"
	.string "wecken und unter Kontrolle halten...\p"
	.string "Aber... Warum?\n"
	.string "Warum ist GROUDON verschwunden?\p"
	.string "Warum?!?$"

SeafloorCavern_Room9_Text_1B4D02:: @ 81B4D02
	.string "ADRIAN: Was hast du da nur herauf-\n"
	.string "beschworen?\p"
	.string "MARC... Du hast GROUDON aufge-\n"
	.string "weckt, stimmt’s?\p"
	.string "Was wird nur aus der Welt, wenn die\n"
	.string "Sonne bis in alle Ewigkeit mit dieser\l"
	.string "Kraft scheint?\p"
	.string "Die Meere werden austrocknen und\n"
	.string "verschwinden...$"

SeafloorCavern_Room9_Text_1B4DD3:: @ 81B4DD3
	.string "MARC: Was sagst du da?\p"
	.string "Die BLAUE KUGEL sollte mir die Kontrolle\n"
	.string "über GROUDON verschaffen...\l"
	.string "Das kann einfach nicht wahr sein...$"

SeafloorCavern_Room9_Text_1B4E37:: @ 81B4E37
	.string "ADRIAN: Wir haben keine Zeit für\n"
	.string "Diskussionen!\p"
	.string "Geh nach draußen und sieh es dir\n"
	.string "selber an!\p"
	.string "Sieh, ob das, was du heraufbeschworen\n"
	.string "hast, das ist, was du wolltest!$"

SeafloorCavern_Room9_Text_1B4ECA:: @ 81B4ECA
	.string "ADRIAN: {PLAYER}{KUN}, komm, du musst\n"
	.string "ebenfalls von hier verschwinden!$"
