MtChimney_Text_1B37BB:: @ 81B37BB
	.string "Die Kraft, die in dem METEORITEN\n"
	.string "steckt...\p"
	.string "Wenn man die mit dieser Maschine\n"
	.string "verstärkt, würde die Aktivität des\l"
	.string "SCHLOTBERGS enorm verstärkt...\p"
	.string "Hahaha... Der Vulkan würde ausbrechen,\n"
	.string "Lava würde erkalten und hart werden.\l"
	.string "Und so entsteht neues Land...$"

MtChimney_Text_1B38B3:: @ 81B38B3
	.string "MARC: Du schon wieder...\p"
	.string "Hör gut zu.\n"
	.string "Wir Menschen sind an Land groß\l"
	.string "geworden.\p"
	.string "Land bedeutet Leben!\n"
	.string "Es besitzt absolute Priorität!\p"
	.string "Daher widmet sich TEAM MAGMA der Auf-\n"
	.string "gabe, die Landmassen zu vergrößern.\p"
	.string "So entsteht mehr Raum für neue Arten\n"
	.string "von POKéMON.\p"
	.string "Und die Menschheit erhält mehr Raum,\n"
	.string "sich zu entwickeln.\p"
	.string "Das ist die große Vision von TEAM MAGMA!\p"
	.string "Ich kann einem sturen Kind wie dir nicht\n"
	.string "erlauben, sich uns in den Weg zu stellen.\p"
	.string "Ich, MARC, werde dir zeigen, was\n"
	.string "passiert, wenn du uns aufhalten willst!$"

MtChimney_Text_1B3A68:: @ 81B3A68
	.string "Wie bitte?!?\p"
	.string "Ich, MARC, wurde ganz hinterhältig\n"
	.string "besiegt?!?$"

MtChimney_Text_1B3A90:: @ 81B3A90
	.string "MARC: Ach, was soll’s.\n"
	.string "Ich werde für heute meine Pläne am\l"
	.string "SCHLOTBERG vergessen. Für heute!\p"
	.string "Niemand wird uns jemals stoppen!\n"
	.string "TEAM MAGMA wird siegen!!!\p"
	.string "Vergiss das nicht!!!$"

MtChimney_Text_1B3B36:: @ 81B3B36
	.string "Hahahahaha!\p"
	.string "Da bist du also den weiten Weg hier\n"
	.string "hoch gelatscht.\p"
	.string "Tja, du kommst leider zu spät. Ich habe\n"
	.string "den METEORITEN aus METEORFÄLLE\l"
	.string "bereits bei meinem BOSS abgeliefert!$"

MtChimney_Text_1B3BB8:: @ 81B3BB8
	.string "Hahahaha...\n"
	.string "Da hab ich wohl verloren...\p"
	.string "Ich kann nur froh sein, dass ich mich\n"
	.string "nicht in METEORFÄLLE mit dir einge-\l"
	.string "lassen habe!$"

MtChimney_Text_1B3C07:: @ 81B3C07
	.string "Hahaha...\p"
	.string "Du hast mich vielleicht besiegt, aber\n"
	.string "gegen unseren BOSS hast du keine\l"
	.string "Schnitte!\p"
	.string "Wenn du dich jetzt verkrümelst, ent-\n"
	.string "gehst du einer saftigen Tracht Prügel!$"

MtChimney_Text_1B3C96:: @ 81B3C96
	.string "Wir vom TEAM MAGMA setzen alles daran,\n"
	.string "zum Wohle aller zu handeln.\p"
	.string "Wenn es mehr Land gibt, gibt es auch\n"
	.string "mehr Platz zum Leben.\l"
	.string "Und jeder wäre glücklich!$"

MtChimney_Text_1B3D1E:: @ 81B3D1E
	.string "Bitte?\n"
	.string "Was sagst du? Ich habe verloren???$"

MtChimney_Text_1B3D3D:: @ 81B3D3D
	.string "Unser BOSS sagt: “Jeder wird glücklich\n"
	.string "sein.”\p"
	.string "Aber warum will uns dann jeder\n"
	.string "aufhalten?$"

MtChimney_Text_1B3D9A:: @ 81B3D9A
	.string "Dieses lästige TEAM AQUA... Sie ver-\n"
	.string "suchen alles, unsere Pläne zu vereiteln.$"

MtChimney_Text_1B3DD6: @ 81B3DD6
	.string "METEORITEN stecken voller Energie.$"

MtChimney_Text_1B3DF5:: @ 81B3DF5
	.string "Los! Stampfen wir TEAM AQUA in den\n"
	.string "Boden! Und vergrößern die Landmassen!$"

MtChimney_Text_1B3E1F:: @ 81B3E1F
	.string "Geh uns aus dem Weg, okay?\p"
	.string "Wir wollen die Landmassen zum Wohle\n"
	.string "aller vergrößern!$"

MtChimney_Text_1B3E7A:: @ 81B3E7A
	.string "Yeah!\n"
	.string "Taucht sie ins Feuer!$"

UnknownString_81B3E94: @ 81B3E94
	.string "Wir werden weiter für mehr Land sorgen!$"

MtChimney_Text_1B3EBA:: @ 81B3EBA
	.string "Hahoh!$"

MtChimney_Text_1B3EC1:: @ 81B3EC1
	.string "ADRIAN: Oh, {PLAYER}{KUN}!\p"
	.string "Bitte, hilf mir, TEAM MAGMA zu stoppen!\p"
	.string "Sie wollen den Vulkan mit Hilfe der Kraft\n"
	.string "des gestohlenen METEORITEN zum\l"
	.string "Ausbruch bringen!\p"
	.string "Das gehört alles zu ihrem Plan, die Land-\n"
	.string "massen der Welt zu vergrößern!$"

MtChimney_Text_1B3F8C:: @ 81B3F8C
	.string "ADRIAN: {PLAYER}{KUN}!\p"
	.string "Bitte, hilf mir TEAM MAGMA zu stoppen!\p"
	.string "Sich mit diesen drei Schurken aus-\n"
	.string "einander zu setzen, ist selbst für mich\l"
	.string "kaum zu schaffen!$"

MtChimney_Text_1B3FFE:: @ 81B3FFE
	.string "ADRIAN: {PLAYER}{KUN}!\p"
	.string "Mit deiner Hilfe konnte ich die Pläne\n"
	.string "von TEAM MAGMA durchkreuzen!\p"
	.string "Aber... Dieser Sieg bedeutet nicht, dass\n"
	.string "es seine üblen Pläne aufgeben wird.\p"
	.string "Wir werden ein wachsames Auge auf TEAM\n"
	.string "MAGMA haben und es weiter verfolgen.\p"
	.string "{PLAYER}{KUN}, wir werden uns wieder sehen!$"

MtChimney_Text_1B40EA:: @ 81B40EA
	.string "Mist... TEAM MAGMA ist uns zahlenmäßig\n"
	.string "überlegen! Wir können es nicht mit ihm\l"
	.string "aufnehmen!$"

MtChimney_Text_1B4128:: @ 81B4128
	.string "Wenn sie die Landmassen vergrößern,\n"
	.string "gibt es weniger Lebensraum für\l"
	.string "WASSER-POKéMON!$"

MtChimney_Text_1B416E:: @ 81B416E
	.string "TEAM MAGMA will die Landmassen ver-\n"
	.string "größern... Wie krank sind die eigentlich?$"

MtChimney_Text_1B41B0:: @ 81B41B0
	.string "Bushaa!$"
