Text_HowMayIServeYou:: @ 81A0BE4
	.string "Willkommen!\p"
	.string "Kann ich dir helfen?$"

Text_PleaseComeAgain:: @ 81A0C02
	.string "Bitte komm bald wieder!$"

@ Unused
Text_DiscountSaleToday: @ 81A0C15
	.string "Willkommen!\p"
	.string "Wir bieten heute Sonderangebote an!$"

Text_PlayerWhatCanIDoForYou:: @ 81A0C42
	.string "{PLAYER}{KUN}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"
