Text_ObtainedTheItem: @ 81A0C68
	.string "{STR_VAR_2} erhalten!$"

Text_TheBagIsFull:: @ 81A0C79
	.string "Der BEUTEL ist voll...$"

Text_PutItemInPocket: @ 81A0C8C
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"

Text_FoundOneItem: @ 81A0CB1
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"

Text_TooBadBagIsFull:
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll...$"

Text_ObtainedTheDecor: @ 81A0CDE
	.string "{STR_VAR_2} erhalten.$"

Text_NoRoomLeftForAnother:: @ 81A0CEF
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}...$"

Text_TheDecorWasTransferredToThePC: @ 81A0D1F
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"
