Text_BootUpPC: @ 81A09EC
	.string "{PLAYER} schaltet den PC ein.$"

Text_WhichPCShouldBeAccessed:: @ 81A0A01
	.string "Zugriff auf wessen PC?$"

Text_AccessedSomeonesPC: @ 81A0A1E
	.string "Verbindung zu jemandes PC hergestellt.$"

Text_StorageSystemOpened: @ 81A0A35
	.string "POKéMON-Lagerungs-System geöffnet.$"

Text_AccessedPlayersPC: @ 81A0A54
	.string "Verbindung mit PC von {PLAYER}.$"

Text_AccessedLanettesPC: @ 81A0A66
	.string "Verbindung zu LANETTES PC hergestellt.$"
