FallarborTown_ContestLobby_Text_1B6E63:: @ 81B6E63
	.string "Oh? Möchtest du mit diesem alten Herrn\n"
	.string "ein paar {POKEBLOCK} herstellen?$"

FallarborTown_ContestLobby_Text_1B6E9D:: @ 81B6E9D
	.string "Ausgezeichnet!$"

FallarborTown_ContestLobby_Text_1B6EA8:: @ 81B6EA8
	.string "Oh...\n"
	.string "Das macht diesen alten Herrn traurig.$"

FallarborTown_ContestLobby_Text_1B6ED0:: @ 81B6ED0
	.string "Weißt du, wie man {POKEBLOCK} herstellt?$"

FallarborTown_ContestLobby_Text_1B6EF1:: @ 81B6EF1
	.string "Dann lass uns loslegen!\p"
	.string "Lass uns BEEREN MIXEN!$"

FallarborTown_ContestLobby_Text_1B6F1F:: @ 81B6F1F
	.string "Okay, ich gebe dir eine kurze Erklärung.\p"
	.string "Keine Angst, es ist ganz einfach.\p"
	.string "Erreicht der rotierende Pfeil deine\n"
	.string "Markierung, dann drücke den A-Knopf.\p"
	.string "Das ist schon alles. Probier es mal, du\n"
	.string "wirst sehen, wie einfach das ist.$"

FallarborTown_ContestLobby_Text_1B6FF0:: @ 81B6FF0
	.string "Oh!\n"
	.string "Du hast keine BEEREN dabei?\p"
	.string "Wenn du keine BEEREN hast, kannst du\n"
	.string "keine {POKEBLOCK} machen.$"

FallarborTown_ContestLobby_Text_1B704A:: @ 81B704A
	.string "Nun, das hilft uns jetzt nicht weiter.\p"
	.string "Wenn du nichts gegen Reste hast,\n"
	.string "kannst du diese BEERE haben.\p"
	.string "Dann können wir mit dem BEERENMIXER\n"
	.string "{POKEBLOCK} herstellen.$"

FallarborTown_ContestLobby_Text_1B70F6:: @ 81B70F6
	.string "Hätte ich BEEREN übrig, würde ich dir\n"
	.string "gerne eine abgeben...\p"
	.string "Aber heute habe ich keine übrig. Wir\n"
	.string "müssen das ein anderes Mal machen.$"

FallarborTown_ContestLobby_Text_1B717C:: @ 81B717C
	.string "Aber deine {POKEBLOCK}BOX ist voll.\p"
	.string "Du solltest einige {POKEBLOCK} verwenden\n"
	.string "und dann wiederkommen.$"

FallarborTown_ContestLobby_Text_1B71D2:: @ 81B71D2
	.string "Aber du hast keine {POKEBLOCK}BOX.\p"
	.string "Besorg dir eine {POKEBLOCK}BOX und\n"
	.string "komm dann wieder.$"

LilycoveCity_ContestLobby_Text_1B7225:: @ 81B7225
SlateportCity_ContestLobby_Text_1B7225:: @ 81B7225
	.string "Dann lass uns mal mixen.$"

LilycoveCity_ContestLobby_Text_1B7241:: @ 81B7241
	.string "Ich bin mal gespannt, welchen {POKEBLOCK}\n"
	.string "ich bekomme. Das ist ja total aufregend!$"

FallarborTown_ContestLobby_Text_1B727C:: @ 81B727C
	.string "{POKEBLOCK} können mit Hilfe deiner Freunde\n"
	.string "im BEERENMIXER aus BEEREN gemacht\l"
	.string "werden.\p"
	.string "Soll das Spiel gespeichert werden, bevor\n"
	.string "du dich mit Freunden verbindest?$"

FallarborTown_ContestLobby_Text_1B7304:: @ 81B7304
	.string "Verbindung zu Freunden wird aufgebaut.\n"
	.string "...B-Knopf: Abbruch$"

FallarborTown_ContestLobby_Text_1B733B:: @ 81B733B
	.string "{STR_VAR_1} ist eingetroffen.$"

FallarborTown_ContestLobby_Text_1B7347:: @ 81B7347
	.string "{STR_VAR_1} und {STR_VAR_2} sind\n"
	.string "eingetroffen.$"

FallarborTown_ContestLobby_Text_1B735A:: @ 81B735A
	.string "{STR_VAR_1}, {STR_VAR_2} und\n"
	.string "{STR_VAR_3} sind eingetroffen.$"

UnknownString_81B7372: @ 81B7372
	.string "Keiner da...$"

FallarborTown_ContestLobby_Text_1B7381:: @ 81B7381
	.string "Du hast keine BEEREN. Du kannst\n"
	.string "den BEERENMIXER nicht benutzen.$"

FallarborTown_ContestLobby_Text_1B73B7:: @ 81B73B7
	.string "Deine {POKEBLOCK}BOX ist voll. Du kannst\n"
	.string "den BEERENMIXER nicht benutzen.$"

FallarborTown_ContestLobby_Text_1B73F1:: @ 81B73F1
	.string "Du hast keine {POKEBLOCK}BOX und\n"
	.string "kannst den BEERENMIXER nicht nutzen.$"

FallarborTown_ContestLobby_Text_1B742F:: @ 81B742F
	.string "Ich liebe es, {POKEBLOCK}\n"
	.string "herzustellen!\p"
	.string "Ich habe immer einige BEEREN dabei.$"

FallarborTown_ContestLobby_Text_1B7469:: @ 81B7469
	.string "Wenn du magst, können wir einige\n"
	.string "{POKEBLOCK} zusammen am BEERENMIXER\l"
	.string "herstellen.$"

FallarborTown_ContestLobby_Text_1B74B4:: @ 81B74B4
	.string "Oh?\n"
	.string "Du hast keine BEEREN?\p"
	.string "Na, dann klappt das dieses Mal nicht.\p"
	.string "Aber... Wenn du nichts gegen Reste\n"
	.string "einzuwenden hast, dann kannst du eine\l"
	.string "meiner BEEREN haben.$"

FallarborTown_ContestLobby_Text_1B753A:: @ 81B753A
	.string "Aus den BEEREN stellen wir im\n"
	.string "BEERENMIXER {POKEBLOCK} her.$"

FallarborTown_ContestLobby_Text_1B7578:: @ 81B7578
	.string "Oh?\n"
	.string "Du hast keine BEEREN?\p"
	.string "Wenn ich welche übrig hätte, würde ich\n"
	.string "dir gerne eine abgeben...\p"
	.string "Aber leider habe ich heute keine übrig.\n"
	.string "Das tut mir echt Leid.$"
