gUnknown_081C40DF:: @ 81C40DF
	.string "Der Einsatz an diesem Tisch ist\n"
	.string "{STR_VAR_1}. Möchtest du spielen?$"

UnknownString_81C411C: @ 81C411C
gUnknown_081C411C:: @ 81C411C
	.string "Du hast nicht genug MÜNZEN.$"

UnknownString_81C4139: @ 81C4139
gUnknown_081C4139:: @ 81C4139
	.string "Und nun eine Bonusrunde!$"

gUnknown_081C4157:: @ 81C4157
	.string "Mache deinen Einsatz mit dem + Steuer-\n"
	.string "kreuz und drücke dann den A-Knopf.$"

UnknownString_81C4199: @ 81C4199
gUnknown_081C4199:: @ 81C4199
	.string "Ein Treffer!$"

UnknownString_81C41A5: @ 81C41A5
gUnknown_081C41A5:: @ 81C41A5
	.string "Jackpot!$"

UnknownString_81C41AE: @ 81C41AE
gUnknown_081C41AE:: @ 81C41AE
	.string "Das war nichts!$"

UnknownString_81C41BD: @ 81C41BD
gUnknown_081C41BD:: @ 81C41BD
	.string "Du hast {STR_VAR_1} MÜNZEN gewonnen!$"

UnknownString_81C41D2: @ 81C41D2
gUnknown_081C41D2:: @ 81C41D2
	.string "Nicht mehr genug MÜNZEN übrig...$"

UnknownString_81C41E3: @ 81C41E3
gUnknown_081C41E3:: @ 81C41E3
	.string "Weiterspielen?$"

UnknownString_81C41F1: @ 81C41F1
gUnknown_081C41F1:: @ 81C41F1
	.string "Der ROULETTE-Tisch wird abgeräumt.$"

UnknownString_81C4215: @ 81C4215
	.string "Du hast keinen MÜNZKORB.$"

UnknownString_81C4231: @ 81C4231
gUnknown_081C4231:: @ 81C4231
	.string "Dein MÜNZKORB ist voll! Münzen können\n"
	.string "gegen Preise eingetauscht werden.$"
