Text_SampleMessage1:: @ 81A089A
	.string "Dies ist Beispiel 1.\p"
	.string "Willkommen in der Welt von\n"
	.string "POKéMON AGB!\l"
	.string "Wir hoffen, dir gefällt es hier!$"

Text_SampleMessage2:: @ 81A08F1
	.string "Dies ist Beispiel 2.\p"
	.string "Willkommen in der Welt von\n"
	.string "POKéMON AGB!\l"
	.string "Wir hoffen, dir gefällt es hier!$"

Text_SampleMessage3:: @ 81A0948
	.string "Dies ist Beispiel 3.\p"
	.string "Willkommen in der Welt von\n"
	.string "POKéMON AGB!\l"
	.string "Wir hoffen, dir gefällt es hier!$"
