SecretBase_Text_AllDecorationsWillBeReturned: @ 81A38FB
	.string "Alle Dekorationsgegenstände und das\n"
	.string "Mobiliar aus deiner GEHEIMBASIS werden\l"
	.string "auf deinen PC gesendet.\p"
	.string "Einverstanden?$"

SecretBase_Text_WantToRegisterSecretBase: @ 81A3958
	.string "Möchtest du GEHEIMBASIS von\n"
	.string "{STR_VAR_1} eintragen?$"

SecretBase_Text_AlreadyRegisteredDelete: @ 81A3982
	.string "Diese Daten wurden bereits\n"
	.string "eingetragen. Möchtest du sie löschen?$"

SecretBase_Text_TooManyBasesDeleteSome: @ 81A39C0
	.string "Bis zu 10 Orte können eingetragen\n"
	.string "werden.\p"
	.string "Lösche einen Ort, um einen neuen\n"
	.string "eintragen zu können.$"

SecretBase_Text_RegistrationCompleted: @ 81A3A22
	.string "Registrierung abgeschlossen.$"

SecretBase_Text_DataUnregistered: @ 81A3A3A
	.string "Daten wurden aus der Registrierung\n"
	.string "genommen.$"

UnknownString_81A3A56: @ 81A3A56
	.string "Es sind keine Dekorationen vorhanden.$"

SecretBase_Text_BootUpPC: @ 81A3A72
	.string "{PLAYER} schaltet den PC ein.$"

SecretBase_Text_WhatWouldYouLikeToDo: @ 81A3A87
	.string "Was möchtest du tun?$"

SecretBase_Text_RegistryInfo: @ 81A3AA2
	.string "Die eingetragene GEHEIMBASIS bleibt\n"
	.string "erhalten, bis der Eigentümer umzieht.\p"
	.string "Wird sie aus dem Grundbuch ent-\n"
	.string "fernt, kann eine andere GEHEIMBASIS\l"
	.string "diesen Platz einnehmen.\p"
	.string "Bis zu 10 Orte können eingetragen\n"
	.string "werden.{0xFC}Ì$"

SecretBase_Text_BattleTowerShield: @ 81A3B5B
	.string "Ein Schild aus {STR_VAR_2}, welches zeigt,\n"
	.string "dass {STR_VAR_1}-mal hintereinander im\l"
	.string "DUELLTURM ein Kampf gewonnen wurde.$"

SecretBase_Text_ToyTV: @ 81A3BA4
	.string "Ein sehr realistischer Spielzeug-\n"
	.string "Fernseher. Man könnte ihn glatt mit\l"
	.string "einem echten Gerät verwechseln.$"

SecretBase_Text_SeedotTV: @ 81A3BE8
	.string "Ein Spielzeug-Fernseher, der aussieht\n"
	.string "wie ein SAMURZEL. Er scheint von\l"
	.string "alleine davonrollen zu wollen...$"

SecretBase_Text_SkittyTV: @ 81A3C31
	.string "Ein Spielzeug-Fernseher, der aussieht\n"
	.string "wie ein ENECO. Es scheint, als wolle\l"
	.string "er sich langsam davonschleichen ...$"

UnknownString_81A3C71: @ 81A3C71
	.string "Du kannst dir nur eine GEHEIMBASIS\n"
	.string "einrichten.\p"
	.string "Möchtest du deine GEHEIMBASIS in der\n"
	.string "Nähe von {STR_VAR_1} hierher\l"
	.string "verlegen?$"

UnknownString_81A3CC9: @ 81A3CC9
	.string "Umzug wurde abgeschlossen.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"
