UnknownString_81A1948: @ 81A1948
	.string "Wenn einige Äste herunterhängen, kann\n"
	.string "man auf den Baum klettern.$"

UnknownString_81A197B: @ 81A197B
	.string "Wenn einige Äste herunterhängen, kann\n"
	.string "man auf den Baum klettern.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

UnknownString_81A19C4: @ 81A19C4
	.string "Ein dicker Ast fällt herunter!$"

UnknownString_81A19DF: @ 81A19DF
	.string "Möchtest du hier deine GEHEIMBASIS\n"
	.string "einrichten?$"

UnknownString_81A1A03: @ 81A1A03
	.string "Dieser Busch kann bewegt werden,\n"
	.string "so dass man hineinklettern kann.$"

UnknownString_81A1A4B: @ 81A1A4B
	.string "Dieser Busch kann bewegt werden,\n"
	.string "so dass man hineinklettern kann.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

UnknownString_81A1AA9: @ 81A1AA9
	.string "Ein kleiner Eingang wird sichtbar.$"

UnknownString_81A1AC6: @ 81A1AC6
	.string "Möchtest du hier deine GEHEIMBASIS\n"
	.string "einrichten?$"

SecretBase_RedCave1_Text_1A1AEA:: @ 81A1AEA
	.string "Hast du dir schon eine GEHEIMBASIS\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Da du schon mal hier bist... Hast du\n"
	.string "Lust zu kämpfen?$"

SecretBase_RedCave1_Text_1A1B83:: @ 81A1B83
	.string "Okay!\n"
	.string "Jetzt kommen wir!$"

SecretBase_RedCave1_Text_1A1B97:: @ 81A1B97
	.string "Wie? Was? Wo?\n"
	.string "Du kannst doch nicht...$"

UnknownString_81A1BB2:: @ 81A1BB2
	.string "Ahaaargh! Du bist zu stark für mich! Ich\n"
	.string "habe verloren, aber verrate das nicht!$"

SecretBase_RedCave1_Text_1A1BF8:: @ 81A1BF8
	.string "Was hältst du von meiner GEHEIMBASIS?\n"
	.string "Komm mich doch morgen wieder besuchen!$"

SecretBase_RedCave1_Text_1A1C3B:: @ 81A1C3B
	.string "Hast du dir schon eine GEHEIMBASIS\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Schau dich ruhig in aller Ruhe um.$"

SecretBase_RedCave1_Text_1A1CB2:: @ 81A1CB2
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine GEHEIMBASIS einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?\p"
	.string "Oh, hast du Lust auf einen Kampf?$"

SecretBase_RedCave1_Text_1A1D48:: @ 81A1D48
	.string "Okay, los geht's!$"

SecretBase_RedCave1_Text_1A1D59:: @ 81A1D59
	.string "Oh...\n"
	.string "Du hast gerade keine Zeit.$"

UnknownString_81A1D74:: @ 81A1D74
	.string "Hmm... Das ist unsere Niederlage...\n"
	.string "Aber erzähl das bloß nicht weiter!\l"
	.string "Das ist ein streng geheimes Geheimnis!$"

SecretBase_RedCave1_Text_1A1DC0:: @ 81A1DC0
	.string "Wenn du wieder mal in der Nähe bist,\n"
	.string "komm mich doch besuchen!$"

SecretBase_RedCave1_Text_1A1DF6:: @ 81A1DF6
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine GEHEIMBASIS einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?$"

SecretBase_RedCave1_Text_1A1E67:: @ 81A1E67
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ach, du wolltest dich hier auch\n"
	.string "häuslich niederlassen?\p"
	.string "Ich sag dir was: Du kannst den Platz\n"
	.string "haben, wenn du mich besiegen kannst.$"

SecretBase_RedCave1_Text_1A1F04:: @ 81A1F04
	.string "Okay! Ich werde meine\n"
	.string "GEHEIMBASIS verteidigen!$"

SecretBase_RedCave1_Text_1A1F2E:: @ 81A1F2E
	.string "Was? Stimmt das? Du hast gar\n"
	.string "kein Interesse an diesem Platz?!?$"

UnknownString_81A1F67:: @ 81A1F67
	.string "Ich kann nicht mehr!\n"
	.string "Ich gebe mich geschlagen!$"

SecretBase_RedCave1_Text_1A1F88:: @ 81A1F88
	.string "Okay, wenn ich eines Tages von hier\n"
	.string "fortziehe, kannst du den Platz haben.$"

SecretBase_RedCave1_Text_1A1FBD:: @ 81A1FBD
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ich habe ewig gewartet, bis er wieder\n"
	.string "frei wurde. Endlich ist es soweit!$"

SecretBase_RedCave1_Text_1A2026:: @ 81A2026
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.\p"
	.string "Möchtest du sehen, wie stark ich bin?$"

SecretBase_RedCave1_Text_1A2095:: @ 81A2095
	.string "Das war ja wohl nichts!$"

SecretBase_RedCave1_Text_1A20AE:: @ 81A20AE
	.string "Oh.\n"
	.string "Ein anderes Mal vielleicht...$"

UnknownString_81A20C9:: @ 81A20C9
	.string "Hm... Ich muss noch viel lernen.\n"
	.string "Ich muss fleißiger studieren.$"

SecretBase_RedCave1_Text_1A2109:: @ 81A2109
	.string "Danke, dass du mit mir gekämpft hast.\n"
	.string "Komm doch bitte morgen wieder.$"

SecretBase_RedCave1_Text_1A2147:: @ 81A2147
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.$"

SecretBase_RedCave1_Text_1A218F:: @ 81A218F
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.\p"
	.string "So. Wie wäre es mit einem Kampf?$"

SecretBase_RedCave1_Text_1A2220:: @ 81A2220
	.string "Genauso muss es laufen!$"

SecretBase_RedCave1_Text_1A2230:: @ 81A2230
	.string "Wenn du bereit bist, sag Bescheid.$"

UnknownString_81A2254:: @ 81A2254
	.string "Ooch! Ich hab's vergeigt!\n"
	.string "Aber es hat sehr viel Spaß gemacht!$"

SecretBase_RedCave1_Text_1A2280:: @ 81A2280
	.string "Egal. Ich sollte mir auf jeden Fall einige\n"
	.string "Dekorationen und Möbel zulegen.\p"
	.string "Ich möchte, dass sich auch andere in\n"
	.string "meiner GEHEIMBASIS wohl fühlen.$"

SecretBase_RedCave1_Text_1A22FA:: @ 81A22FA
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.$"

SecretBase_RedCave1_Text_1A236A:: @ 81A236A
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!\p"
	.string "Wärest du so nett, mit meinen\n"
	.string "POKéMON zu kämpfen?$"

SecretBase_RedCave1_Text_1A2405:: @ 81A2405
	.string "Danke schön.\n"
	.string "Bist du bereit?$"

SecretBase_RedCave1_Text_1A2420:: @ 81A2420
	.string "Oh.\n"
	.string "Was für eine Enttäuschung.$"

UnknownString_81A2439:: @ 81A2439
	.string "Ich kapituliere...$"

SecretBase_RedCave1_Text_1A2446:: @ 81A2446
	.string "Das war vielleicht ein Spaß! Und nun\n"
	.string "sollte ich mich dem Einkaufen widmen.$"

SecretBase_RedCave1_Text_1A2480:: @ 81A2480
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!$"

SecretBase_RedCave1_Text_1A24E1:: @ 81A24E1
	.string "Einige Leute richten ihre GEHEIMBASIS\n"
	.string "an gut versteckten Orten ein.\l"
	.string "Wollen sie sich nicht mehr sehen lassen?\p"
	.string "Da du mich gefunden hast, lass uns\n"
	.string "doch gleich mal kämpfen.$"

SecretBase_RedCave1_Text_1A256F:: @ 81A256F
	.string "Ich bin nicht einfach zu besiegen!$"

SecretBase_RedCave1_Text_1A258A:: @ 81A258A
	.string "Oh. Sag bloß, du bist müde von der Suche\n"
	.string "nach diesem Platz?$"

UnknownString_81A25C3:: @ 81A25C3
	.string "Ich bin untergegangen...$"

SecretBase_RedCave1_Text_1A25D2:: @ 81A25D2
	.string "Wo ist deine GEHEIMBASIS?\n"
	.string "Ich sollte dich dort mal besuchen.$"

SecretBase_RedCave1_Text_1A2609:: @ 81A2609
	.string "Einige Leute richten ihre GEHEIMBASIS\n"
	.string "an gut versteckten Orten ein.\l"
	.string "Wollen sie sich nicht mehr sehen lassen?$"

SecretBase_RedCave1_Text_1A2663:: @ 81A2663
	.string "Einige Leute haben mir erzählt, dass man\n"
	.string "auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.\p"
	.string "Aber zuerst lass uns kämpfen.$"

SecretBase_RedCave1_Text_1A2710:: @ 81A2710
	.string "Das ist meine GEHEIMBASIS.\n"
	.string "Ich kann hier gar nicht verlieren!$"

SecretBase_RedCave1_Text_1A2736:: @ 81A2736
	.string "Ich kämpfe jederzeit mit dir.$"

UnknownString_81A2754:: @ 81A2754
	.string "Wie?\n"
	.string "Ich habe doch verloren?$"

SecretBase_RedCave1_Text_1A276A:: @ 81A276A
	.string "Ich werde den Wettbewerb um die\n"
	.string "schönsten Dekorationen nicht ver-\l"
	.string "lieren. Überzeuge dich selbst!$"

SecretBase_RedCave1_Text_1A27A4:: @ 81A27A4
	.string "Einige Leute haben mir erzählt, dass man\n"
	.string "auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.$"

SecretBase_RedCave1_Text_1A2830:: @ 81A2830
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieblings-\l"
	.string "dekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Genau das mache ich.\n"
	.string "Möchtest du mit mir kämpfen?$"

SecretBase_RedCave1_Text_1A28D7:: @ 81A28D7
	.string "Zeig mir, aus welchem Holz du\n"
	.string "geschnitzt bist.$"

SecretBase_RedCave1_Text_1A28F4:: @ 81A28F4
	.string "Ich glaube, es gibt immer wieder Zeiten,\n"
	.string "in denen man nicht so gut drauf ist.$"

UnknownString_81A2925:: @ 81A2925
	.string "Ich weiß jetzt genau, aus welchem Holz\n"
	.string "du geschnitzt bist.$"

SecretBase_RedCave1_Text_1A294D:: @ 81A294D
	.string "Wir können beide noch stärker werden!\n"
	.string "Das macht doch Mut!$"

SecretBase_RedCave1_Text_1A297C:: @ 81A297C
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieblings-\l"
	.string "dekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Jeder Tag ist mein Lieblingstag.$"

SecretBase_RedCave1_Text_1A2A13:: @ 81A2A13
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi...\p"
	.string "Willst du mal meinen Kampfstil sehen?$"

SecretBase_RedCave1_Text_1A2AE2:: @ 81A2AE2
	.string "Es gibt kein Zurück mehr.$"

SecretBase_RedCave1_Text_1A2AFB:: @ 81A2AFB
	.string "Ich zeige dir gerne jederzeit wieder \n"
	.string "meinen erlesenen Kampfstil!$"

UnknownString_81A2B2A:: @ 81A2B2A
	.string "Du bist hoch talentiert! Deine Stärke\n"
	.string "scheint grenzenlos zu sein.$"

SecretBase_RedCave1_Text_1A2B69:: @ 81A2B69
	.string "Was hältst du von meinem Stil?\n"
	.string "Ich muss ihn noch mehr aufpolieren.$"

SecretBase_RedCave1_Text_1A2BA4:: @ 81A2BA4
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi...$"
