gTextStoryteller_Introduction:: @ 81AECC6
	.string "Ich bin der GESCHICHTENERZÄHLER.\n"
	.string "Ich erzähle dir die Geschichten von\l"
	.string "legendären TRAINERN.\p"
	.string "Soll ich dir etwas erzählen?$"

gTextStoryteller_OhIFeelStifled:: @ 81AED1D
	.string "Oh...\n"
	.string "Keiner mag mich...$"

gTextStoryteller_WhichTale:: @ 81AED35
	.string "Ich kenne viele dieser Legenden.\n"
	.string "Welche möchtest du hören?$"

gTextStoryteller_ButIKnowOfNoLegendaryTrainers:: @ 81AED70
	.string "Aber ich weiß nichts über legendäre\n"
	.string "TRAINER. Also habe ich keine Ge-\l"
	.string "schichte auf Lager.\p"
	.string "Wo findet man wohl einen TRAINER, der\n"
	.string "einer lebenden Legende gleicht?$"

gTextStoryteller_BirthOfANewLegend:: @ 81AEDE8
	.string "Was ist?\n"
	.string "Du... Du...\p"
	.string "{STR_VAR_2}\n"
	.string "{STR_VAR_1}-mal?\p"
	.string "Das ist einfach großartig!\n"
	.string "Die Geburt einer neuen Legende!$"

gTextStoryteller_CouldThereBeOtherTrainers:: @ 81AEE50
	.string "Ich überlege, ob es nicht noch andere\n"
	.string "TRAINER gibt, die mir beeindruckende\l"
	.string "Geschichten erzählen können.$"

gTextStoryteller_HaveYouAnyTales:: @ 81AEEB4
	.string "Bist du ein TRAINER?\p"
	.string "Dann sag mir, ob du Geschichten\n"
	.string "für mich hast, die legendär sind?$"

gTextStoryteller_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "Übrigens... Möchtest du eine weitere\n"
	.string "legendäre Geschichte hören?$"

gTextStoryteller_ImNotSatisfied:: @ 81AEF49
	.string "Hmm...\n"
	.string "Ich bin nicht zufrieden...\p"
	.string "Ich wünschte, du würdest mir Neuig-\n"
	.string "keiten erzählen, die den Titel Legende\l"
	.string "verdienen.$"

gTextStoryteller_WishMorePeopleWould:: @ 81AEFA5
	.string "Ich wollte, mehr Leute würden sich für\n"
	.string "meine epischen Geschichten über\l"
	.string "legendäre TRAINER interessieren.$"

gTextStoryteller_Story1Title:: @ 81AEFFC
	.string "Der speicherfreudige TRAINER$"

gTextStoryteller_Story1Action:: @ 81AF013
	.string "Hast das Spiel gespeichert?$"

gTextStoryteller_Story1Text:: @ 81AF022
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat das Spiel\n"
	.string "{STR_VAR_1}-mal gespeichert!\p"
	.string "Einen vorsichtigeren TRAINER als\n"
	.string "{STR_VAR_3} wird man nicht finden!$"

gTextStoryteller_Story2Title:: @ 81AF0A3
	.string "Der TRAINER als Trendsetter$"

gTextStoryteller_Story2Action:: @ 81AF0BB
	.string "Hast Trends gesetzt?$"

gTextStoryteller_Story2Text:: @ 81AF0CA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "neue Trends gesetzt!\p"
	.string "{STR_VAR_3} setzt den Trend für alle - in\n"
	.string "der ganzen HOENN-Region!$"

gTextStoryteller_Story3Title:: @ 81AF149
	.string "Der BEEREN pflanzende TRAINER$"

gTextStoryteller_Story3Action:: @ 81AF164
	.string "Hast BEEREN gepflanzt?$"

gTextStoryteller_Story3Text:: @ 81AF174
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "BEEREN gepflanzt!\p"
	.string "{STR_VAR_3} ist ein legendärer Lieb-\n"
	.string "haber von BEEREN!$"

gTextStoryteller_Story4Title:: @ 81AF1E5
	.string "Der RAD verrückte TRAINER$"

gTextStoryteller_Story4Action:: @ 81AF1FD
	.string "Hast RÄDER getauscht?$"

gTextStoryteller_Story4Text:: @ 81AF20A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "das RAD getauscht!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "Passion das RADfahren ist!$"

gTextStoryteller_Story5Title:: @ 81AF281
	.string "Der Interviews gebende TRAINER$"

gTextStoryteller_Story5Action:: @ 81AF299
	.string "Hast Interviews gegeben?$"

gTextStoryteller_Story5Text:: @ 81AF2A9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "interviewt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der überall\n"
	.string "Aufmerksamkeit erregt!$"

gTextStoryteller_Story6Title:: @ 81AF32C
	.string "Der kampfliebende TRAINER$"

gTextStoryteller_Story6Action:: @ 81AF345
	.string "Hast oft gekämpft?$"

gTextStoryteller_Story6Text:: @ 81AF34D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "gekämpft!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der zu\n"
	.string "einem Kampf nicht nein sagt!$"

gTextStoryteller_Story7Title:: @ 81AF3D0
	.string "Der POKéMON fangende TRAINER$"

gTextStoryteller_Story7Action:: @ 81AF3ED
	.string "Hast POKéMON gefangen?$"

gTextStoryteller_Story7Text:: @ 81AF3FC
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Fänger\n"
	.string "von POKéMON!$"

gTextStoryteller_Story8Title:: @ 81AF46D
	.string "Der angelnde TRAINER$"

gTextStoryteller_Story8Action:: @ 81AF481
	.string "Hast POKéMON mit einer ANGEL gefangen?$"

gTextStoryteller_Story8Text:: @ 81AF49B
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON beim Angeln gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Angel-\n"
	.string "experte!$"

gTextStoryteller_Story9Title:: @ 81AF511
	.string "Der EIER wärmende TRAINER$"

gTextStoryteller_Story9Action:: @ 81AF529
	.string "Hast EIER ausgebrütet?$"

gTextStoryteller_Story9Text:: @ 81AF536
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Es passierte {STR_VAR_1}-mal, dass der TRAINER\n"
	.string "ein POKéMON aus einem EI schlüpfen ließ!\p"
	.string "{STR_VAR_3} ist ein legendärer Pfleger\n"
	.string "von EIERN!$"

gTextStoryteller_Story10Title:: @ 81AF5A9
	.string "Der TRAINER der Entwicklungen$"

gTextStoryteller_Story10Action:: @ 81AF5BD
	.string "Hast POKéMON sich entwickeln lassen?$"

gTextStoryteller_Story10Text:: @ 81AF5CD
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON zur Entwicklung gebracht!\p"
	.string "{STR_VAR_3} ist der ultimative Ent-\n"
	.string "wickler von POKéMON!$"

gTextStoryteller_Story11Title:: @ 81AF63F
	.string "Der PKMN-CENTER liebende TRAINER$"

gTextStoryteller_Story11Action:: @ 81AF661
	.string "Gingst in ein POKéMON-CENTER?$"

gTextStoryteller_Story11Text:: @ 81AF676
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal in einem POKéMON-CENTER\l"
	.string "heilen lassen!\p"
	.string "Es gibt keinen größeren Fan der\n"
	.string "POKéMON-CENTER als {STR_VAR_3}!$"

gTextStoryteller_Story12Title:: @ 81AF711
	.string "Der gastfreundliche TRAINER$"

gTextStoryteller_Story12Action:: @ 81AF726
	.string "POKéMON haben sich bei dir erholt?$"

gTextStoryteller_Story12Text:: @ 81AF73D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal bei sich zu Hause ausruhen\l"
	.string "und heilen lassen.\p"
	.string "Kein TRAINER ist so gastfreundlich\n"
	.string "wie {STR_VAR_3}!$"

gTextStoryteller_Story13Title:: @ 81AF7BF
	.string "Der SAFARI liebende TRAINER$"

gTextStoryteller_Story13Action:: @ 81AF7D9
	.string "Bist in die SAFARI-ZONE gegangen?$"

gTextStoryteller_Story13Text:: @ 81AF7F1
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal in die\n"
	.string "SAFARI-ZONE gegangen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "wilde Seite in der SAFARI-ZONE zum\l"
	.string "Vorschein kommt!$"

gTextStoryteller_Story14Title:: @ 81AF88A
	.string "Der TRAINER als ZERSCHNEIDER$"

gTextStoryteller_Story14Action:: @ 81AF8A1
	.string "Hast ZERSCHNEIDER eingesetzt?$"

gTextStoryteller_Story14Text:: @ 81AF8AA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERSCHNEIDER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, etwas zu ZERSCHNEIDEN.$"

gTextStoryteller_Story15Title:: @ 81AF91B
	.string "Der TRAINER als ZERTRÜMMERER$"

gTextStoryteller_Story15Action:: @ 81AF935
	.string "Hast Felsen ZERTRÜMMERT?$"

gTextStoryteller_Story15Text:: @ 81AF943
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERTRÜMMERER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der keinen\n"
	.string "Felsen unbeschädigt lassen kann.$"

gTextStoryteller_Story16Title:: @ 81AF9C8
	.string "Der Umzüge liebende TRAINER$"

gTextStoryteller_Story16Action:: @ 81AF9E0
	.string "Bist du mit der GEHEIMBASIS umgezogen?$"

gTextStoryteller_Story16Text:: @ 81AF9F6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal mit\n"
	.string "seiner GEHEIMBASIS umgezogen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, sich ein neues Haus einzurichten.$"

gTextStoryteller_Story17Title:: @ 81AFA79
	.string "Der PLATSCHER des TRAINERS$"

gTextStoryteller_Story17Action:: @ 81AFA92
	.string "Hast PLATSCHER eingesetzt?$"

gTextStoryteller_Story17Text:: @ 81AFA9E
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "PLATSCHER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, zu PLATSCHEN.$"

gTextStoryteller_Story18Title:: @ 81AFB17
	.string "Der verbissene TRAINER$"

gTextStoryteller_Story18Action:: @ 81AFB2D
	.string "Hast VERZWEIFLER angewendet?$"

gTextStoryteller_Story18Text:: @ 81AFB48
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat sich {STR_VAR_1}-mal\n"
	.string "auf VERZWEIFLER verlassen!\p"
	.string "{STR_VAR_3}... Ein verbissener TRAINER,\n"
	.string "der auch in der Not nicht aufgibt.$"

gTextStoryteller_Story19Title:: @ 81AFBD8
	.string "Der König der EINARMIGEN BANDITEN$"

gTextStoryteller_Story19Action:: @ 81AFBE7
	.string "Hast den EINARMIGEN BANDITEN besiegt?$"

gTextStoryteller_Story19Text:: @ 81AFC04
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "am EINARMIGEN BANDITEN gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der am\n"
	.string "EINARMIGEN BANDITEN Glück hat.$"

gTextStoryteller_Story20Title:: @ 81AFC8A
	.string "Der König des ROULETTES$"

gTextStoryteller_Story20Action:: @ 81AFC9D
	.string "Hast in Folge beim ROULETTE gewonnen,$"

gTextStoryteller_Story20Text:: @ 81AFCBE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal in Folge\n"
	.string "beim ROULETTE gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, dem die Kugel\n"
	.string "beim ROULETTE gehorcht.$"

gTextStoryteller_Story21Title:: @ 81AFD44
	.string "Der Herausforderer im DUELLTURM$"

gTextStoryteller_Story21Action:: @ 81AFD60
	.string "Hast Gegner im DUELLTURM gefordert?$"

gTextStoryteller_Story21Text:: @ 81AFD80
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal Gegner\n"
	.string "im DUELLTURM herausgefordert!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der im DUELL-\n"
	.string "TURM nach Perfektion strebt.$"

gTextStoryteller_Story22Title:: @ 81AFE1D
	.string "Der mixende TRAINER$"

gTextStoryteller_Story22Action:: @ 81AFE36
	.string "Hast {POKEBLOCK} hergestellt?$"

gTextStoryteller_Story22Text:: @ 81AFE42
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "{POKEBLOCK} hergestellt!\p"
	.string "Niemand bedient den BEERENMIXER\n"
	.string "besser als {STR_VAR_3}.$"

gTextStoryteller_Story23Title:: @ 81AFEC2
	.string "Der Fan der WETTBEWERBE$"

gTextStoryteller_Story23Action:: @ 81AFEDD
	.string "Hast an WETTBEWERBEN teilgenommen?$"

gTextStoryteller_Story23Text:: @ 81AFEEE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "an einem WETTBEWERB teilgenommen!\p"
	.string "{STR_VAR_3} liebt es, anderen seine\n"
	.string "POKéMON zu zeigen.$"

gTextStoryteller_Story24Title:: @ 81AFF68
	.string "Der Meister der WETTBEWERBE$"

gTextStoryteller_Story24Action:: @ 81AFF7B
	.string "Hast WETTBEWERBE gewonnen?$"

gTextStoryteller_Story24Text:: @ 81AFF88
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "einen WETTBEWERB gewonnen!\p"
	.string "{STR_VAR_3} ist ein unvergleichlicher\n"
	.string "Meister der WETTBEWERBE.$"

gTextStoryteller_Story25Title:: @ 81AFFFB
	.string "Der glückliche Einkäufer$"

gTextStoryteller_Story25Action:: @ 81B000D
	.string "Bist einkaufen gegangen?$"

gTextStoryteller_Story25Text:: @ 81B0015
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in einem Geschäft Items gekauft!\p"
	.string "{STR_VAR_3} ein geborener Einkäufer.$"

gTextStoryteller_Story26Title:: @ 81B009D
	.string "Der TRAINER, der Items findet$"

gTextStoryteller_Story26Action:: @ 81B00B6
	.string "Hast den DETEKTOR eingesetzt?$"

gTextStoryteller_Story26Text:: @ 81B00C9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "den DETEKTOR eingesetzt!\p"
	.string "{STR_VAR_3} liebt es, den Boden nach\n"
	.string "verborgenen Items abzusuchen.$"

gTextStoryteller_Story27Title:: @ 81B014D
	.string "Der regennasse TRAINER$"

gTextStoryteller_Story27Action:: @ 81B0165
	.string "Wurdest nass geregnet?$"

gTextStoryteller_Story27Text:: @ 81B0173
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "nass geregnet!\p"
	.string "Das Charisma von {STR_VAR_3} zieht\n"
	.string "sogar den Regen an.$"

gTextStoryteller_Story28Title:: @ 81B01E9
	.string "Der passionierte POKéDEX-Leser$"

gTextStoryteller_Story28Action:: @ 81B0201
	.string "Hast im POKéDEX nachgeschlagen?$"

gTextStoryteller_Story28Text:: @ 81B0213
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "im POKéDEX nachgeschlagen!\p"
	.string "{STR_VAR_3} liebt es, alles über\n"
	.string "POKéMON im POKéDEX nachzulesen.$"

gTextStoryteller_Story29Title:: @ 81B0290
	.string "Der Sammler der BÄNDER$"

gTextStoryteller_Story29Action:: @ 81B02A5
	.string "Hast BÄNDER erhalten?$"

gTextStoryteller_Story29Text:: @ 81B02B6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "BÄNDER erhalten!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, BÄNDER zu sammeln.$"

gTextStoryteller_Story30Title:: @ 81B0337
	.string "Der springende TRAINER$"

gTextStoryteller_Story30Action:: @ 81B0351
	.string "Bist Absätze heruntergesprungen?$"

gTextStoryteller_Story30Text:: @ 81B0364
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "einen Absatz hinabgesprungen!\p"
	.string "Sobald er an einen Absatz kommt, muss\n"
	.string "TRAINER {STR_VAR_3} einfach hinab-\l"
	.string "springen.$"

gTextStoryteller_Story31Title:: @ 81B03E9
	.string "Der legendäre Fernsehzuschauer$"

gTextStoryteller_Story31Action:: @ 81B0401
	.string "Hast ferngeschaut?$"

gTextStoryteller_Story31Text:: @ 81B040C
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "Fernsehen geschaut!\p"
	.string "{STR_VAR_3} liebt es, fernzusehen.$"

gTextStoryteller_Story32Title:: @ 81B046E
	.string "Der zeitbewusste TRAINER$"

gTextStoryteller_Story32Action:: @ 81B0489
	.string "Hast nach der Uhrzeit gesehen?$"

gTextStoryteller_Story32Text:: @ 81B049A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "nach der Uhrzeit geschaut!\p"
	.string "{STR_VAR_3} ist ein pünktlicher\n"
	.string "TRAINER, der sich der Zeit bewusst ist.$"

gTextStoryteller_Story33Title:: @ 81B0523
	.string "Der Zauberer der POKéMON-LOTTERIE$"

gTextStoryteller_Story33Action:: @ 81B053E
	.string "Hast in der LOTTERIE gewonnen?$"

gTextStoryteller_Story33Text:: @ 81B0554
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in der POKéMON-LOTTERIE gewonnen!\p"
	.string "TRAINER {STR_VAR_3} hat viele Freunde,\n"
	.string "die mit ihm POKéMON tauschen.$"

gTextStoryteller_Story34Title:: @ 81B05D8
	.string "Der TRAINER und die PENSION$"

gTextStoryteller_Story34Action:: @ 81B05F3
	.string "Hast POKéMON in die PENSION gebracht?$"

gTextStoryteller_Story34Text:: @ 81B0610
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "seine POKéMON in die PENSION gegeben!\p"
	.string "{STR_VAR_3} ist ein Ellenbogentyp, der\n"
	.string "alles für die Entwicklung seiner\l"
	.string "POKéMON tut.$"

gTextStoryteller_Story35Title:: @ 81B06A9
	.string "Der SEILBAHN verrückte TRAINER$"

gTextStoryteller_Story35Action:: @ 81B06C6
	.string "Bist mit der SEILBAHN gefahren?$"

gTextStoryteller_Story35Text:: @ 81B06D9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "mit der SEILBAHN gefahren!\p"
	.string "{STR_VAR_3} ein sehr beschäftigter\n"
	.string "TRAINER, der ständig rauf und runter\l"
	.string "fährt.$"

gTextStoryteller_Story36Title:: @ 81B0763
	.string "Der Liebhaber der Heißen Quellen$"

gTextStoryteller_Story36Action:: @ 81B0781
	.string "Hast in den Heißen Quellen gebadet?$"

gTextStoryteller_Story36Text:: @ 81B0797
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in den Heißen Quellen gebadet!\p"
	.string "{STR_VAR_3} wird eine babyweiche Haut\n"
	.string "haben.$"
