gTextTrader_Introduction:: @ 81AE88F
	.string "Hallo! Ich bin der HÄNDLER. Möchtest\n"
	.string "du Dekorationen mit mir tauschen?$"

gTextTrader_FeelUnwanted1:: @ 81AE8C6
	.string "Oh...\n"
	.string "Ich fühle mich überflüssig...$"

gTextTrader_TradedAlready:: @ 81AE8DF
	.string "Aber wir beide haben doch bereits\n"
	.string "Dekorationen ausgetauscht.$"

gTextTrader_MenuPrompt:: @ 81AE910
	.string "Wenn du etwas Dekoratives siehst, das\n"
	.string "du haben möchtest, lass es mich wissen.$"

gTextTrader_DontWantAnything:: @ 81AE950
	.string "Du möchtest nichts haben?\n"
	.string "Ich fühle mich so überflüssig...$"

gTextTrader_ItemOnceBelongedTo:: @ 81AE97C
	.string "Das dekorative Item gehörte einst\n"
	.string "{STR_VAR_1}.\p"
	.string "Möchtest du es haben?$"

gTextTrader_YouDontHaveDecorations:: @ 81AE9B6
	.string "Äh... Warte eine Sekunde. Du hast über-\n"
	.string "haupt kein dekoratives Item!$"

gTextTrader_PickDecorationYoullTrade:: @ 81AE9F8
	.string "Okay, wähle die Dekoration aus, die du\n"
	.string "mit mir tauschen willst.$"

gTextTrader_FeelUnwanted2:: @ 81AEA2B
	.string "Du willst nicht mit mir tauschen?\n"
	.string "Ich fühle mich überflüssig...$"

gTextTrader_NoRoomForThis:: @ 81AEA57
	.string "Du hast keinen Platz mehr für eine/n\n"
	.string "{STR_VAR_2}.$"

gTextTrader_SoWellTrade:: @ 81AEA9B
	.string "Okay, dann lass uns tauschen:\n"
	.string "{STR_VAR_3} gegen\l"
	.string "{STR_VAR_2}!$"

gTextTrader_InUseYouCantTradeIt:: @ 81AEAC3
	.string "Dieses Dekorationsstück ist im Ge-\n"
	.string "brauch. Das kannst du nicht tauschen.$"

gTextTrader_ThenWellTrade:: @ 81AEAFB
	.string "Dann lass uns tauschen! Ich werde meine\n"
	.string "Dekorationen auf deinen PC senden.$"

gTextTrader_ICantTradeThatOneAway:: @ 81AEB31
	.string "Huups! Tut mir Leid!\n"
	.string "Das ist ein ganz seltenes Stück!\l"
	.string "Das kann ich nicht tauschen!\p"
	.string "Kann ich dich für etwas anderes\n"
	.string "begeistern?$"
