MauvilleCity_PokemonCenter_1F_Text_1AE88F:: @ 81AE88F
	.string "Hallo! Ich bin der HÄNDLER. Möchtest\n"
	.string "du Dekorationen mit mir tauschen?$"

MauvilleCity_PokemonCenter_1F_Text_1AE8C6:: @ 81AE8C6
	.string "Oh...\n"
	.string "Ich fühle mich überflüssig...$"

MauvilleCity_PokemonCenter_1F_Text_1AE8DF:: @ 81AE8DF
	.string "Aber wir beide haben doch bereits\n"
	.string "Dekorationen ausgetauscht.$"

MauvilleCity_PokemonCenter_1F_Text_1AE910:: @ 81AE910
	.string "Wenn du etwas Dekoratives siehst, das\n"
	.string "du haben möchtest, lass es mich wissen.$"

MauvilleCity_PokemonCenter_1F_Text_1AE950:: @ 81AE950
	.string "Du möchtest nichts haben?\n"
	.string "Ich fühle mich so überflüssig...$"

MauvilleCity_PokemonCenter_1F_Text_1AE97C:: @ 81AE97C
	.string "Das dekorative Item gehörte einst\n"
	.string "{STR_VAR_1}.\p"
	.string "Möchtest du es haben?$"

MauvilleCity_PokemonCenter_1F_Text_1AE9B6:: @ 81AE9B6
	.string "Äh... Warte eine Sekunde. Du hast über-\n"
	.string "haupt kein dekoratives Item!$"

MauvilleCity_PokemonCenter_1F_Text_1AE9F8:: @ 81AE9F8
	.string "Okay, wähle die Dekoration aus, die du\n"
	.string "mit mir tauschen willst.$"

MauvilleCity_PokemonCenter_1F_Text_1AEA2B:: @ 81AEA2B
	.string "Du willst nicht mit mir tauschen?\n"
	.string "Ich fühle mich überflüssig...$"

MauvilleCity_PokemonCenter_1F_Text_1AEA57:: @ 81AEA57
	.string "Du hast keinen Platz mehr für eine/n\n"
	.string "{STR_VAR_2}.$"

MauvilleCity_PokemonCenter_1F_Text_1AEA9B:: @ 81AEA9B
	.string "Okay, dann lass uns tauschen:\n"
	.string "{STR_VAR_3} gegen\l"
	.string "{STR_VAR_2}!$"

MauvilleCity_PokemonCenter_1F_Text_1AEAC3:: @ 81AEAC3
	.string "Dieses Dekorationsstück ist im Ge-\n"
	.string "brauch. Das kannst du nicht tauschen.$"

MauvilleCity_PokemonCenter_1F_Text_1AEAFB:: @ 81AEAFB
	.string "Dann lass uns tauschen! Ich werde meine\n"
	.string "Dekorationen auf deinen PC senden.$"

MauvilleCity_PokemonCenter_1F_Text_1AEB31:: @ 81AEB31
	.string "Huups! Tut mir Leid!\n"
	.string "Das ist ein ganz seltenes Stück!\l"
	.string "Das kann ich nicht tauschen!\p"
	.string "Kann ich dich für etwas anderes\n"
	.string "begeistern?$"
