FallarborTown_CozmosHouse_Text_MeteoriteWillNeverBeMineNow:: @ 8177755
	.string "PROF. COZMO: Oh...\n"
	.string "I never should have let myself be\l"
	.string "conned into telling TEAM {EVIL_TEAM} where\l"
	.string "you can find METEORITES...\p"
	.string "That METEORITE from METEOR FALLS...\n"
	.string "It's never going to be mine now...$"

FallarborTown_CozmosHouse_Text_IsThatMeteoriteMayIHaveIt:: @ 817780E
	.string "Oh!\n"
	.string "Hah?\p"
	.string "That item...\p"
	.string "Could it be?\p"
	.string "Is it the METEORITE that TEAM {EVIL_TEAM}\n"
	.string "took from METEOR FALLS?\p"
	.string "Please, may I have it?\p"
	.string "I'm not asking for it for free.\n"
	.string "How about in exchange for this TM?$"

FallarborTown_CozmosHouse_Text_PleaseUseThisTM:: @ 81778C4
	.string "PROF. COZMO: This TM, it represents\n"
	.string "my feeling of gratitude.\l"
	.string "Please use it!$"

FallarborTown_CozmosHouse_Text_ReallyGoingToHelpMyResearch:: @ 8177910
	.string "PROF. COZMO: Oh, I can't believe it.\n"
	.string "This is really, really great!\p"
	.string "This is really going to help my research!$"

FallarborTown_CozmosHouse_Text_CrushedWithDisappointment:: @ 817797D
	.string "PROF. COZMO: Oh, but...\n"
	.string "I'm crushed with disappointment...$"

FallarborTown_CozmosHouse_Text_MayIHaveMeteorite:: @ 81779B8
	.string "PROF. COZMO: Please, may I have that\n"
	.string "METEORITE?\p"
	.string "I'm not asking for it for free.\n"
	.string "How about in exchange for this TM?$"

FallarborTown_CozmosHouse_Text_CozmoWentToMeteorFalls:: @ 8177A2B
	.string "PROF. COZMO went off to METEOR FALLS\n"
	.string "on ROUTE 114 with some people from\l"
	.string "TEAM {EVIL_TEAM}.$"

FallarborTown_CozmosHouse_Text_FeelSorryForCozmo:: @ 8177A7C
	.string "Poor PROF. COZMO...\n"
	.string "He's so depressed... I feel sorry for him.$"

FallarborTown_CozmosHouse_Text_CozmoIsSoHappy:: @ 8177ABB
	.string "Look at PROF. COZMO...\n"
	.string "He's so happy! I think it's cute.$"
