LilycoveCity_MoveDeletersHouse_EventObjects:: @ 838A044
	object_event 1, EVENT_OBJ_GFX_OLD_MAN_1, 0, 4, 4, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, LilycoveCity_MoveDeletersHouse_EventScript_159AAE, 0

LilycoveCity_MoveDeletersHouse_MapWarps:: @ 838A05C
	warp_def 3, 7, 0, 7, MAP_LILYCOVE_CITY
	warp_def 4, 7, 0, 7, MAP_LILYCOVE_CITY

LilycoveCity_MoveDeletersHouse_MapEvents:: @ 838A06C
	map_events LilycoveCity_MoveDeletersHouse_EventObjects, LilycoveCity_MoveDeletersHouse_MapWarps, 0x0, 0x0
