SlateportCity_House_Text_NatureToDoWithStatGains:: @ 81804CF
	.string "My POKéMON has a HASTY nature.\p"
	.string "It has higher SPEED compared to my\n"
	.string "other POKéMON.\p"
	.string "Maybe their nature has something to\n"
	.string "do with the stat gains of POKéMON.$"

SlateportCity_House_Text_NeedContestPass:: @ 8180567
	.string "You need a CONTEST PASS to enter a\n"
	.string "CONTEST.\p"
	.string "It's easy to get. They give it to\n"
	.string "anyone who has POKéMON.$"

SlateportCity_House_Text_HaveContestPass:: @ 81805CD
	.string "Oh, a CONTEST PASS!\n"
	.string "You're going to be a contestant?$"
