MeteorFalls_B1F_2R_EventObjects:: @ 838BCF8
	object_event 1, EVENT_OBJ_GFX_ITEM_BALL, 0, 5, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, MeteorFalls_B1F_2R_EventScript_1B182F, FLAG_ITEM_METEOR_FALLS_B1F_2R_1

MeteorFalls_B1F_2R_MapWarps:: @ 838BD10
	warp_def 5, 15, 3, 3, MAP_METEOR_FALLS_B1F_1R

MeteorFalls_B1F_2R_MapEvents:: @ 838BD18
	map_events MeteorFalls_B1F_2R_EventObjects, MeteorFalls_B1F_2R_MapWarps, 0x0, 0x0
