LilycoveCity_DepartmentStore_2F_Text_18C162:: @ 818C162
	.string "Lerne, mit Items vernünftig umzugehen.\n"
	.string "Das ist essentiell. Ehrlich.$"

LilycoveCity_DepartmentStore_2F_Text_18C195:: @ 818C195
	.string "Mein Mann wartet zu Hause auf mich.\n"
	.string "Was wäre wohl ein passendes Geschenk\l"
	.string "für ihn?$"

LilycoveCity_DepartmentStore_2F_Text_18C1D9:: @ 818C1D9
	.string "Ich werde bald auf eine lange Reise\n"
	.string "gehen. Ich muss daher Items kaufen.$"

UnknownString_818C21A: @ 818C21A
	.string "FÜR DEINE REISEBEGLEITER\n"
	.string "1S: ALLES FÜR DEN TRAINER$"
