MossdeepCity_PokemonCenter_1F_Text_GymLeaderDuoFormidable:: @ 818D62F
	.string "Die ARENALEITER dieses Ortes sind ein\n"
	.string "ausgezeichnetes Team.\p"
	.string "Die Kombination ihrer Attacken ist\n"
	.string "einfach exzellent und... wow!$"

MossdeepCity_PokemonCenter_1F_Text_AbilitiesMightChangeMoves:: @ 818D69A
	.string "Abhängig von den speziellen Fähigkeiten\n"
	.string "eines POKéMON, werden einige Attacken\p"
	.string "in ihrer Wirkung verändert oder\n"
	.string "sogar wirkungslos.$"
