debug_unk_0::
@ 0x821F3B8
    .incbin "baserom-debug.gba", 0x21F3B8, 620

Str_821F624:: @ 0x821F624
	.string "ーーーーーーーーーーーー$"

str_821F631:: @ 0x821F631
	.string "ジュンイチ$"
	.string "ダイゴロウ$"
	.string "バレンシア$"
	.string "ハルコマチ$"

Str_821F649:: @ 0x821F649
	.string "てつじ$"

debug_unk_0b::
@ 0x821F64D
	.string "　　オン$"

@ 0x821F652
	.string "オフ$"

@ 0x821F655
	.string "モノラル$"

@ 0x821F65A
	.string "ステレオ$"

@ 0x821F65F
	.string "テストです$"

@ 0x821F665
	.string "うけとったって$"

@ 0x821F66D
	.string "せつぞくエラー$"

.incbin "baserom-debug.gba", 0x21F675, 323

Str_821F7B8:: @ 0x821F7B8
	.string "たかさ　$"

Str_821F7BD:: @ 0x821F7BD
	.string "{PALETTE 1}{COLOR_HIGHLIGHT_SHADOW BLUE YELLOW MAGENTA}たかさ　　　ひこう\n"
	.string "ポケモン　　ファイル$"

Str_821F7DA:: @ 0x821F7DA
	.string "{PALETTE 1}{COLOR_HIGHLIGHT_SHADOW BLUE YELLOW MAGENTA}ロード\n"
	.string "セーブ$"

Str_821F7EA:: @ 0x821F7EA
	.string "ロードしますか？$"

@ 0x821F7F3
gUnknown_Debug_821F7F3::
	.string "セーブしますか？$"
