DecorDesc_SMALL_DESK: @ 83E9FD0
	.string "Ein kleiner Tisch\n"
	.string "für eine Person.$"

DecorDesc_POKEMON_DESK: @ 83E9FEC
	.string "Ein kleiner Tisch,\n"
	.string "geformt wie ein\n"
	.string "POKéBALL.$"

DecorDesc_HEAVY_DESK: @ 83EA01C
	.string "Ein großer Tisch\n"
	.string "aus Stahl. Für\n"
	.string "Dekorationen.$"

DecorDesc_RAGGED_DESK: @ 83EA054
	.string "Ein großer Tisch\n"
	.string "aus Holz. Für\n"
	.string "Dekorationen.$"

DecorDesc_COMFORT_DESK: @ 83EA08B
	.string "Ein riesiger Tisch\n"
	.string "aus Blättern. Für\n"
	.string "Dekorationen.$"

DecorDesc_PRETTY_DESK: @ 83EA0C4
	.string "Ein riesiger Tisch\n"
	.string "aus Glas. Trägt\n"
	.string "viele Dekorationen.$"

DecorDesc_BRICK_DESK: @ 83EA0FA
	.string "Ein riesiger Tisch\n"
	.string "aus Backstein. Für\n"
	.string "viele Dekorationen.$"

DecorDesc_CAMP_DESK: @ 83EA130
	.string "Ein riesiger Tisch\n"
	.string "aus Baumstämmen.\n"
	.string "Für Dekorationen.$"

DecorDesc_HARD_DESK: @ 83EA169
	.string "Ein riesiger Tisch\n"
	.string "aus Stein. Trägt\n"
	.string "viele Dekorationen.$"

DecorDesc_SMALL_CHAIR: @ 83EA19C
	.string "Ein kleiner Stuhl\n"
	.string "für eine Person.$"

DecorDesc_POKEMON_CHAIR: @ 83EA1B8
	.string "Ein kleiner Stuhl\n"
	.string "in der Form eines\n"
	.string "POKéBALLS.$"

DecorDesc_HEAVY_CHAIR: @ 83EA1E9
	.string "Ein kleiner Stuhl\n"
	.string "aus Stahl.$"

DecorDesc_PRETTY_CHAIR: @ 83EA206
	.string "Ein kleiner Stuhl\n"
	.string "aus Glas.$"

DecorDesc_COMFORT_CHAIR: @ 83EA223
	.string "Ein kleiner Stuhl\n"
	.string "aus Blättern.$"

DecorDesc_RAGGED_CHAIR: @ 83EA241
	.string "Ein kleiner Stuhl\n"
	.string "aus Holz.$"

DecorDesc_BRICK_CHAIR: @ 83EA25D
	.string "Ein kleiner Stuhl\n"
	.string "aus Backstein.$"

DecorDesc_CAMP_CHAIR: @ 83EA27A
	.string "Ein kleiner Stuhl\n"
	.string "aus Baumstämmen.$"

DecorDesc_HARD_CHAIR: @ 83EA296
	.string "Ein kleiner Stuhl\n"
	.string "aus Stein.$"

DecorDesc_RED_PLANT: @ 83EA2B2
	.string "Eine leuchtend\n"
	.string "rote Pflanze.$"

DecorDesc_TROPICAL_PLANT: @ 83EA2CC
	.string "Eine blühende,\n"
	.string "tropische Pflanze\n"
	.string "in einem Übertopf.$"

DecorDesc_PRETTY_FLOWERS: @ 83EA2F1
	.string "Ein Topf mit\n"
	.string "hübschen Blumen.$"

DecorDesc_COLORFUL_PLANT: @ 83EA308
	.string "Ein großer Topf mit\n"
	.string "vielen, farben-\n"
	.string "prächtigen Blumen.$"

DecorDesc_BIG_PLANT: @ 83EA330
	.string "Eine große, schirm-\n"
	.string "förmige Pflanze in\n"
	.string "einem großen Topf.$"

DecorDesc_GORGEOUS_PLANT: @ 83EA35E
	.string "Eine beeindruckend\n"
	.string "große Pflanze in\n"
	.string "einem großen Topf.$"

DecorDesc_RED_BRICK: @ 83EA386
	.string "Ein roter Back-\n"
	.string "stein. Stelle Deko-\n"
	.string "rationen darauf.$"

DecorDesc_YELLOW_BRICK: @ 83EA3BD
	.string "Ein gelber Back-\n"
	.string "stein. Stelle Deko-\n"
	.string "rationen darauf.$"

DecorDesc_BLUE_BRICK: @ 83EA3F2
	.string "Ein blauer Back-\n"
	.string "stein. Stelle Deko-\n"
	.string "rationen darauf.$"

DecorDesc_RED_BALLOON: @ 83EA425
	.string "Ein roter Ballon mit\n"
	.string "Wasser. Platzt beim\n"
	.string "Drauftreten.$"

DecorDesc_BLUE_BALLOON: @ 83EA45C
	.string "Ein blauer Ballon\n"
	.string "mit Wasser. Platzt\n"
	.string "beim Drauftreten.$"

DecorDesc_YELLOW_BALLOON: @ 83EA494
	.string "Ein gelber Ballon\n"
	.string "mit Wasser. Platzt\n"
	.string "beim Drauftreten.$"

DecorDesc_RED_TENT: @ 83EA4CC
	.string "Ein großes, rotes\n"
	.string "Zelt. Darin kann man\n"
	.string "sich verstecken.$"

DecorDesc_BLUE_TENT: @ 83EA4F6
	.string "Ein großes, blaues\n"
	.string "Zelt. Darin kann man\n"
	.string "sich verstecken.$"

DecorDesc_SOLID_BOARD: @ 83EA521
	.string "Leg es über ein\n"
	.string "Loch, um die andere\n"
	.string "Seite zu erreichen.$"

DecorDesc_SLIDE: @ 83EA54F
	.string "Nützlich, um von der\n"
	.string "Plattform hinab-\n"
	.string "gleiten zu können.$"

DecorDesc_FENCE_LENGTH: @ 83EA574
	.string "Ein kleiner Zaun,\n"
	.string "der den Durchgang\n"
	.string "versperrt.$"

DecorDesc_FENCE_WIDTH: @ 83EA597
	.string "Ein kleiner Zaun,\n"
	.string "der den Durchgang\n"
	.string "versperrt.$"

DecorDesc_TIRE: @ 83EA5BA
	.string "Ein großer, alter\n"
	.string "Reifen. Für\n"
	.string "Dekorationen.$"

DecorDesc_STAND: @ 83EA5EF
	.string "Ein Podest mit\n"
	.string "Stufen.$"

DecorDesc_MUD_BALL: @ 83EA60C
	.string "Ein großer Ball aus\n"
	.string "Lehm. Geht kaputt\n"
	.string "beim Drauftreten.$"

DecorDesc_BREAKABLE_DOOR: @ 83EA639
	.string "Eine verrückte Tür,\n"
	.string "durch die man hin-\n"
	.string "durchlaufen kann.$"

DecorDesc_SAND_ORNAMENT: @ 83EA66A
	.string "Ein Ornament aus\n"
	.string "Sand. Fällt bei\n"
	.string "Kontakt zusammen.$"

DecorDesc_SILVER_SHIELD: @ 83EA699
	.string "Belohnung für\n"
	.string "50 Siege in Folge im\n"
	.string "DUELLTURM.$"

DecorDesc_GOLD_SHIELD: @ 83EA6CB
	.string "Belohnung für\n"
	.string "100 Siege in Folge\n"
	.string "im DUELLTURM.$"

DecorDesc_GLASS_ORNAMENT: @ 83EA6FE
	.string "Das Replikat einer\n"
	.string "berühmten Skulptur\n"
	.string "des KUNSTMUSEUMS.$"

DecorDesc_TV: @ 83EA737
	.string "Ein kleiner, grauer\n"
	.string "Spielzeug-\n"
	.string "Fernseher.$"

DecorDesc_ROUND_TV: @ 83EA756
	.string "Ein Spielzeug-\n"
	.string "Fernseher in der\n"
	.string "Form von SAMURZEL.$"

DecorDesc_CUTE_TV: @ 83EA781
	.string "Ein Spielzeug-\n"
	.string "Fernseher in der\n"
	.string "Form eines ENECO.$"

DecorDesc_GLITTER_MAT: @ 83EA7AC
	.string "Eine seltsame\n"
	.string "Matte. Glitzert\n"
	.string "beim Drauftreten.$"

DecorDesc_JUMP_MAT: @ 83EA7D4
	.string "Eine Trick-Matte,\n"
	.string "die hüpft, wenn man\n"
	.string "drauftritt.$"

DecorDesc_SPIN_MAT: @ 83EA802
	.string "Eine Trick-Matte,\n"
	.string "die sich beim\n"
	.string "Drauftreten dreht.$"

DecorDesc_C_LOW_NOTE_MAT: @ 83EA831
	.string "Eine Matte, die das\n"
	.string "tiefe C spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_D_NOTE_MAT: @ 83EA860
	.string "Eine Matte, die\n"
	.string "ein D spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_E_NOTE_MAT: @ 83EA88B
	.string "Eine Matte, die\n"
	.string "ein E spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_F_NOTE_MAT: @ 83EA8B7
	.string "Eine Matte, die\n"
	.string "ein F spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_G_NOTE_MAT: @ 83EA8E3
	.string "Eine Matte, die\n"
	.string "ein G spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_A_NOTE_MAT: @ 83EA90E
	.string "Eine Matte, die\n"
	.string "ein A spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_B_NOTE_MAT: @ 83EA93A
	.string "Eine Matte, die\n"
	.string "ein H spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_C_HIGH_NOTE_MAT: @ 83EA965
	.string "Eine Matte, die das\n"
	.string "hohe C spielt, wenn\n"
	.string "man drauftritt.$"

DecorDesc_SURF_MAT: @ 83EA995
	.string "Eine Matte mit\n"
	.string "einem SURFER-\n"
	.string "Muster. Für Items.$"

DecorDesc_THUNDER_MAT: @ 83EA9C9
	.string "Eine Matte mit\n"
	.string "einem DONNER-\n"
	.string "Muster. Für Items.$"

DecorDesc_FIRE_BLAST_MAT: @ 83EAA00
	.string "Eine Matte mit\n"
	.string "FEUERSTURM-\n"
	.string "Muster. Für Items.$"

DecorDesc_POWDER_SNOW_MAT: @ 83EAA3A
	.string "Eine Matte mit\n"
	.string "PULVERSCHNEE-\n"
	.string "Muster. Für Items.$"

DecorDesc_ATTRACT_MAT: @ 83EAA73
	.string "Eine Matte mit\n"
	.string "ANZIEHUNG-\n"
	.string "Muster. Für Items.$"

DecorDesc_FISSURE_MAT: @ 83EAAAB
	.string "Eine Matte mit\n"
	.string "GEOFISSUR-\n"
	.string "Muster. Für Items.$"

DecorDesc_SPIKES_MAT: @ 83EAAE2
	.string "Eine Matte mit\n"
	.string "STACHLER-\n"
	.string "Muster. Für Items.$"

DecorDesc_BALL_POSTER: @ 83EAB18
	.string "Ein kleines Poster\n"
	.string "von POKéBÄLLEN.$"

DecorDesc_GREEN_POSTER: @ 83EAB40
	.string "Ein kleines Poster\n"
	.string "von GECKARBOR.$"

DecorDesc_RED_POSTER: @ 83EAB65
	.string "Ein kleines Poster\n"
	.string "von FLEMMLI.$"

DecorDesc_BLUE_POSTER: @ 83EAB8A
	.string "Ein kleines Poster\n"
	.string "von HYDROPI.$"

DecorDesc_CUTE_POSTER: @ 83EABAE
	.string "Ein kleines Poster\n"
	.string "von AZURILL.$"

DecorDesc_PIKA_POSTER: @ 83EABD4
	.string "Ein großes Poster\n"
	.string "von PIKACHU und\n"
	.string "PICHU.$"

DecorDesc_LONG_POSTER: @ 83EAC03
	.string "Ein großes Poster\n"
	.string "von VIPITIS.$"

DecorDesc_SEA_POSTER: @ 83EAC28
	.string "Ein großes Poster\n"
	.string "von RELICANTH.$"

DecorDesc_SKY_POSTER: @ 83EAC4F
	.string "Ein großes Poster\n"
	.string "von WINGULL.$"

DecorDesc_KISS_POSTER: @ 83EAC74
	.string "Ein großes Poster\n"
	.string "von KUSSILLA.$"

DecorDesc_PICHU_DOLL: @ 83EAC9A
	.string "PICHU-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_PIKACHU_DOLL: @ 83EACC5
	.string "PIKACHU-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_MARILL_DOLL: @ 83EACF2
	.string "MARILL-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_TOGEPI_DOLL: @ 83EAD1E
	.string "TOGEPI-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_CYNDAQUIL_DOLL: @ 83EAD4B
	.string "FEURIGEL-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_CHIKORITA_DOLL: @ 83EAD7A
	.string "ENDIVIE-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_TOTODILE_DOLL: @ 83EADA9
	.string "KARNIMANI-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_JIGGLYPUFF_DOLL: @ 83EADD7
	.string "PUMMELUFF-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_MEOWTH_DOLL: @ 83EAE07
	.string "MAUZI-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_CLEFAIRY_DOLL: @ 83EAE33
	.string "PIEPI-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_DITTO_DOLL: @ 83EAE61
	.string "DITTO-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_SMOOCHUM_DOLL: @ 83EAE8C
	.string "KUSSILLA-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_TREECKO_DOLL: @ 83EAEBA
	.string "GECKARBOR-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_TORCHIC_DOLL: @ 83EAEE7
	.string "FLEMMLI-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_MUDKIP_DOLL: @ 83EAF14
	.string "HYDROPI-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_DUSKULL_DOLL: @ 83EAF40
	.string "ZWIRRLICHT-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_WYNAUT_DOLL: @ 83EAF6D
	.string "ISSO-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_BALTOY_DOLL: @ 83EAF99
	.string "PUPPANCE-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_KECLEON_DOLL: @ 83EAFC5
	.string "KECLEON-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_AZURILL_DOLL: @ 83EAFF2
	.string "AZURILL-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_SKITTY_DOLL: @ 83EB020
	.string "ENECO-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_SWABLU_DOLL: @ 83EB04C
	.string "WABLU-Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder einen Tisch.$"

DecorDesc_GULPIN_DOLL: @ 83EB078
	.string "SCHLUPPUCK-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_LOTAD_DOLL: @ 83EB0A4
	.string "LOTURZEL-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_SEEDOT_DOLL: @ 83EB0CF
	.string "SAMURZEL-Puppe.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_PIKA_CUSHION: @ 83EB0FB
	.string "PIKACHU-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_ROUND_CUSHION: @ 83EB12B
	.string "MARILL-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_KISS_CUSHION: @ 83EB15A
	.string "KUSSILLA-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_ZIGZAG_CUSHION: @ 83EB18B
	.string "ZIGZACHS-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_SPIN_CUSHION: @ 83EB1BD
	.string "PANDIR-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_DIAMOND_CUSHION: @ 83EB1EC
	.string "ZOBIRIS-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_BALL_CUSHION: @ 83EB21C
	.string "BALL-Kissen.\n"
	.string "Für eine Matte oder\n"
	.string "den Tisch.$"

DecorDesc_GRASS_CUSHION: @ 83EB249
	.string "Kissen mit Gras-\n"
	.string "muster. Für\n"
	.string "Matte oder Tisch.$"

DecorDesc_FIRE_CUSHION: @ 83EB27C
	.string "Kissen mit Feuer-\n"
	.string "muster. Für\n"
	.string "Matte oder Tisch.$"

DecorDesc_WATER_CUSHION: @ 83EB2AE
	.string "Kissen mit Wasser-\n"
	.string "muster. Für\n"
	.string "Matte oder Tisch.$"

DecorDesc_SNORLAX_DOLL: @ 83EB2E1
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_RHYDON_DOLL: @ 83EB30C
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_LAPRAS_DOLL: @ 83EB337
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_VENUSAUR_DOLL: @ 83EB362
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_CHARIZARD_DOLL: @ 83EB38D
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_BLASTOISE_DOLL: @ 83EB3B8
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_WAILMER_DOLL: @ 83EB3E3
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_REGIROCK_DOLL: @ 83EB40E
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_REGICE_DOLL: @ 83EB439
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

DecorDesc_REGISTEEL_DOLL: @ 83EB464
	.string "Große Puppe. Leg\n"
	.string "sie auf eine Matte\n"
	.string "oder den Tisch.$"

	.align 1
DecorGfx_SMALL_DESK: @ 83EB490
	.2byte 0x87

	.align 1
DecorGfx_POKEMON_DESK: @ 83EB492
	.2byte 0x8F

	.align 1
DecorGfx_HEAVY_DESK: @ 83EB494
	.2byte 0x90
	.2byte 0x91
	.2byte 0x92
	.2byte 0x98
	.2byte 0x99
	.2byte 0x9A

	.align 1
DecorGfx_RAGGED_DESK: @ 83EB4A0
	.2byte 0x93
	.2byte 0x94
	.2byte 0x95
	.2byte 0x9B
	.2byte 0x9C
	.2byte 0x9D

	.align 1
DecorGfx_COMFORT_DESK: @ 83EB4AC
	.2byte 0x96
	.2byte 0x97
	.2byte 0xA3
	.2byte 0x9E
	.2byte 0x9F
	.2byte 0xAB

	.align 1
DecorGfx_PRETTY_DESK: @ 83EB4B8
	.2byte 0xBD
	.2byte 0xBE
	.2byte 0xBF
	.2byte 0xC5
	.2byte 0xC6
	.2byte 0xC7
	.2byte 0xCD
	.2byte 0xCE
	.2byte 0xCF

	.align 1
DecorGfx_BRICK_DESK: @ 83EB4CA
	.2byte 0xA0
	.2byte 0xA1
	.2byte 0xA2
	.2byte 0xA8
	.2byte 0xA9
	.2byte 0xAA
	.2byte 0xB0
	.2byte 0xB1
	.2byte 0xB2

	.align 1
DecorGfx_CAMP_DESK: @ 83EB4DC
	.2byte 0xA4
	.2byte 0xA5
	.2byte 0xA6
	.2byte 0xAC
	.2byte 0xAD
	.2byte 0xAE
	.2byte 0xB4
	.2byte 0xB5
	.2byte 0xB6

	.align 1
DecorGfx_HARD_DESK: @ 83EB4EE
	.2byte 0xA7
	.2byte 0xBB
	.2byte 0xBC
	.2byte 0xAF
	.2byte 0xC3
	.2byte 0xC4
	.2byte 0xB7
	.2byte 0xCB
	.2byte 0xCC

	.align 1
DecorGfx_SMALL_CHAIR: @ 83EB500
	.2byte 0xB8

	.align 1
DecorGfx_POKEMON_CHAIR: @ 83EB502
	.2byte 0xB9

	.align 1
DecorGfx_HEAVY_CHAIR: @ 83EB504
	.2byte 0xBA

	.align 1
DecorGfx_PRETTY_CHAIR: @ 83EB506
	.2byte 0xC0

	.align 1
DecorGfx_COMFORT_CHAIR: @ 83EB508
	.2byte 0xC1

	.align 1
DecorGfx_RAGGED_CHAIR: @ 83EB50A
	.2byte 0xC2

	.align 1
DecorGfx_BRICK_CHAIR: @ 83EB50C
	.2byte 0xC8

	.align 1
DecorGfx_CAMP_CHAIR: @ 83EB50E
	.2byte 0xC9

	.align 1
DecorGfx_HARD_CHAIR: @ 83EB510
	.2byte 0xCA

	.align 1
DecorGfx_RED_PLANT: @ 83EB512
	.2byte 0xD0
	.2byte 0xD8

	.align 1
DecorGfx_TROPICAL_PLANT: @ 83EB516
	.2byte 0xD2
	.2byte 0xDA

	.align 1
DecorGfx_PRETTY_FLOWERS: @ 83EB51A
	.2byte 0xD4
	.2byte 0xDC

	.align 1
DecorGfx_COLORFUL_PLANT: @ 83EB51E
	.2byte 0xE0
	.2byte 0xE2
	.2byte 0xE8
	.2byte 0xE9

	.align 1
DecorGfx_BIG_PLANT: @ 83EB526
	.2byte 0xE4
	.2byte 0xE6
	.2byte 0xEC
	.2byte 0xED

	.align 1
DecorGfx_GORGEOUS_PLANT: @ 83EB52E
	.2byte 0xF0
	.2byte 0xF2
	.2byte 0xF8
	.2byte 0xF9

	.align 1
DecorGfx_RED_BRICK: @ 83EB536
	.2byte 0x25
	.2byte 0x2D

	.align 1
DecorGfx_YELLOW_BRICK: @ 83EB53A
	.2byte 0x26
	.2byte 0x2E

	.align 1
DecorGfx_BLUE_BRICK: @ 83EB53E
	.2byte 0x27
	.2byte 0x2F

	.align 1
DecorGfx_RED_BALLOON: @ 83EB542
	.2byte 0x138

	.align 1
DecorGfx_BLUE_BALLOON: @ 83EB544
	.2byte 0x13C

	.align 1
DecorGfx_YELLOW_BALLOON: @ 83EB546
	.2byte 0x140

	.align 1
DecorGfx_RED_TENT: @ 83EB548
	.2byte 0x30
	.2byte 0x31
	.2byte 0x32
	.2byte 0x38
	.2byte 0x39
	.2byte 0x3A
	.2byte 0x40
	.2byte 0x41
	.2byte 0x3B

	.align 1
DecorGfx_BLUE_TENT: @ 83EB55A
	.2byte 0x48
	.2byte 0x49
	.2byte 0x68
	.2byte 0x50
	.2byte 0x51
	.2byte 0x70
	.2byte 0x58
	.2byte 0x59
	.2byte 0x69

	.align 1
DecorGfx_SOLID_BOARD: @ 83EB56C
	.2byte 0x34
	.2byte 0x3C

	.align 1
DecorGfx_SLIDE: @ 83EB570
	.2byte 0x35
	.2byte 0x36
	.2byte 0x3D
	.2byte 0x3E
	.2byte 0x63
	.2byte 0x64
	.2byte 0x6F
	.2byte 0x77

	.align 1
DecorGfx_FENCE_LENGTH: @ 83EB580
	.2byte 0x33

	.align 1
DecorGfx_FENCE_WIDTH: @ 83EB582
	.2byte 0x2C

	.align 1
DecorGfx_TIRE: @ 83EB584
	.2byte 0x80
	.2byte 0x81
	.2byte 0x88
	.2byte 0x89

	.align 1
DecorGfx_STAND: @ 83EB58C
	.2byte 0x6A
	.2byte 0x6B
	.2byte 0x6C
	.2byte 0x6D
	.2byte 0x72
	.2byte 0x73
	.2byte 0x74
	.2byte 0x75

	.align 1
DecorGfx_MUD_BALL: @ 83EB59C
	.2byte 0x28

	.align 1
DecorGfx_BREAKABLE_DOOR: @ 83EB59E
	.2byte 0x37
	.2byte 0x3F

	.align 1
DecorGfx_SAND_ORNAMENT: @ 83EB5A2
	.2byte 0x85
	.2byte 0x8D

	.align 1
DecorGfx_SILVER_SHIELD: @ 83EB5A6
	.2byte 0xD6
	.2byte 0xDE

	.align 1
DecorGfx_GOLD_SHIELD: @ 83EB5AA
	.2byte 0x12E
	.2byte 0x136

	.align 1
DecorGfx_GLASS_ORNAMENT: @ 83EB5AE
	.2byte 0x82
	.2byte 0x8A

	.align 1
DecorGfx_TV: @ 83EB5B2
	.2byte 0xF4

	.align 1
DecorGfx_ROUND_TV: @ 83EB5B4
	.2byte 0xF5

	.align 1
DecorGfx_CUTE_TV: @ 83EB5B6
	.2byte 0xF6

	.align 1
DecorGfx_GLITTER_MAT: @ 83EB5B8
	.2byte 0x60

	.align 1
DecorGfx_JUMP_MAT: @ 83EB5BA
	.2byte 0x61

	.align 1
DecorGfx_SPIN_MAT: @ 83EB5BC
	.2byte 0x62

	.align 1
DecorGfx_C_LOW_NOTE_MAT: @ 83EB5BE
	.2byte 0x78

	.align 1
DecorGfx_D_NOTE_MAT: @ 83EB5C0
	.2byte 0x79

	.align 1
DecorGfx_E_NOTE_MAT: @ 83EB5C2
	.2byte 0x7A

	.align 1
DecorGfx_F_NOTE_MAT: @ 83EB5C4
	.2byte 0x7B

	.align 1
DecorGfx_G_NOTE_MAT: @ 83EB5C6
	.2byte 0x7C

	.align 1
DecorGfx_A_NOTE_MAT: @ 83EB5C8
	.2byte 0x7D

	.align 1
DecorGfx_B_NOTE_MAT: @ 83EB5CA
	.2byte 0x7E

	.align 1
DecorGfx_C_HIGH_NOTE_MAT: @ 83EB5CC
	.2byte 0xB3

	.align 1
DecorGfx_SURF_MAT: @ 83EB5CE
	.2byte 0x42
	.2byte 0x43
	.2byte 0x44
	.2byte 0x4A
	.2byte 0x4B
	.2byte 0x4C
	.2byte 0x52
	.2byte 0x53
	.2byte 0x54

	.align 1
DecorGfx_THUNDER_MAT: @ 83EB5E0
	.2byte 0x45
	.2byte 0x46
	.2byte 0x47
	.2byte 0x4D
	.2byte 0x4E
	.2byte 0x4F
	.2byte 0x55
	.2byte 0x56
	.2byte 0x57

	.align 1
DecorGfx_FIRE_BLAST_MAT: @ 83EB5F2
	.2byte 0x5A
	.2byte 0x5B
	.2byte 0x5C
	.2byte 0x5D
	.2byte 0x5E
	.2byte 0x5F
	.2byte 0x65
	.2byte 0x66
	.2byte 0x67

	.align 1
DecorGfx_POWDER_SNOW_MAT: @ 83EB604
	.2byte 0x100
	.2byte 0x101
	.2byte 0x102
	.2byte 0x108
	.2byte 0x109
	.2byte 0x10A
	.2byte 0x110
	.2byte 0x111
	.2byte 0x112

	.align 1
DecorGfx_ATTRACT_MAT: @ 83EB616
	.2byte 0x103
	.2byte 0x104
	.2byte 0x105
	.2byte 0x10B
	.2byte 0x10C
	.2byte 0x10D
	.2byte 0x113
	.2byte 0x114
	.2byte 0x115

	.align 1
DecorGfx_FISSURE_MAT: @ 83EB628
	.2byte 0x106
	.2byte 0x107
	.2byte 0x118
	.2byte 0x10E
	.2byte 0x10F
	.2byte 0x120
	.2byte 0x116
	.2byte 0x117
	.2byte 0x128

	.align 1
DecorGfx_SPIKES_MAT: @ 83EB63A
	.2byte 0x119
	.2byte 0x11A
	.2byte 0x11B
	.2byte 0x121
	.2byte 0x122
	.2byte 0x123
	.2byte 0x129
	.2byte 0x12A
	.2byte 0x12B

	.align 1
DecorGfx_BALL_POSTER: @ 83EB64C
	.2byte 0x130

	.align 1
DecorGfx_GREEN_POSTER: @ 83EB64E
	.2byte 0x131

	.align 1
DecorGfx_RED_POSTER: @ 83EB650
	.2byte 0x132

	.align 1
DecorGfx_BLUE_POSTER: @ 83EB652
	.2byte 0x133

	.align 1
DecorGfx_CUTE_POSTER: @ 83EB654
	.2byte 0x134

	.align 1
DecorGfx_PIKA_POSTER: @ 83EB656
	.2byte 0x11C
	.2byte 0x11D

	.align 1
DecorGfx_LONG_POSTER: @ 83EB65A
	.2byte 0x11E
	.2byte 0x11F

	.align 1
DecorGfx_SEA_POSTER: @ 83EB65E
	.2byte 0x124
	.2byte 0x125

	.align 1
DecorGfx_SKY_POSTER: @ 83EB662
	.2byte 0x126
	.2byte 0x127

	.align 1
DecorGfx_KISS_POSTER: @ 83EB666
	.2byte 0x12C
	.2byte 0x12D

	.align 1
DecorGfx_PICHU_DOLL: @ 83EB66A
	.2byte MAP_OBJ_GFX_PICHU_DOLL

	.align 1
DecorGfx_PIKACHU_DOLL: @ 83EB66C
	.2byte MAP_OBJ_GFX_PIKACHU_DOLL

	.align 1
DecorGfx_MARILL_DOLL: @ 83EB66E
	.2byte MAP_OBJ_GFX_MARILL_DOLL

	.align 1
DecorGfx_TOGEPI_DOLL: @ 83EB670
	.2byte MAP_OBJ_GFX_TOGEPI_DOLL

	.align 1
DecorGfx_CYNDAQUIL_DOLL: @ 83EB672
	.2byte MAP_OBJ_GFX_CYNDAQUIL_DOLL

	.align 1
DecorGfx_CHIKORITA_DOLL: @ 83EB674
	.2byte MAP_OBJ_GFX_CHIKORITA_DOLL

	.align 1
DecorGfx_TOTODILE_DOLL: @ 83EB676
	.2byte MAP_OBJ_GFX_TOTODILE_DOLL

	.align 1
DecorGfx_JIGGLYPUFF_DOLL: @ 83EB678
	.2byte MAP_OBJ_GFX_JIGGLYPUFF_DOLL

	.align 1
DecorGfx_MEOWTH_DOLL: @ 83EB67A
	.2byte MAP_OBJ_GFX_MEOWTH_DOLL

	.align 1
DecorGfx_CLEFAIRY_DOLL: @ 83EB67C
	.2byte MAP_OBJ_GFX_CLEFAIRY_DOLL

	.align 1
DecorGfx_DITTO_DOLL: @ 83EB67E
	.2byte MAP_OBJ_GFX_DITTO_DOLL

	.align 1
DecorGfx_SMOOCHUM_DOLL: @ 83EB680
	.2byte MAP_OBJ_GFX_SMOOCHUM_DOLL

	.align 1
DecorGfx_TREECKO_DOLL: @ 83EB682
	.2byte MAP_OBJ_GFX_TREECKO_DOLL

	.align 1
DecorGfx_TORCHIC_DOLL: @ 83EB684
	.2byte MAP_OBJ_GFX_TORCHIC_DOLL

	.align 1
DecorGfx_MUDKIP_DOLL: @ 83EB686
	.2byte MAP_OBJ_GFX_MUDKIP_DOLL

	.align 1
DecorGfx_DUSKULL_DOLL: @ 83EB688
	.2byte MAP_OBJ_GFX_DUSKULL_DOLL

	.align 1
DecorGfx_WYNAUT_DOLL: @ 83EB68A
	.2byte MAP_OBJ_GFX_WYNAUT_DOLL

	.align 1
DecorGfx_BALTOY_DOLL: @ 83EB68C
	.2byte MAP_OBJ_GFX_BALTOY_DOLL

	.align 1
DecorGfx_KECLEON_DOLL: @ 83EB68E
	.2byte MAP_OBJ_GFX_KECLEON_DOLL

	.align 1
DecorGfx_AZURILL_DOLL: @ 83EB690
	.2byte MAP_OBJ_GFX_AZURILL_DOLL

	.align 1
DecorGfx_SKITTY_DOLL: @ 83EB692
	.2byte MAP_OBJ_GFX_SKITTY_DOLL

	.align 1
DecorGfx_SWABLU_DOLL: @ 83EB694
	.2byte MAP_OBJ_GFX_SWABLU_DOLL

	.align 1
DecorGfx_GULPIN_DOLL: @ 83EB696
	.2byte MAP_OBJ_GFX_GULPIN_DOLL

	.align 1
DecorGfx_LOTAD_DOLL: @ 83EB698
	.2byte MAP_OBJ_GFX_LOTAD_DOLL

	.align 1
DecorGfx_SEEDOT_DOLL: @ 83EB69A
	.2byte MAP_OBJ_GFX_SEEDOT_DOLL

	.align 1
DecorGfx_PIKA_CUSHION: @ 83EB69C
	.2byte MAP_OBJ_GFX_PIKA_CUSHION

	.align 1
DecorGfx_ROUND_CUSHION: @ 83EB69E
	.2byte MAP_OBJ_GFX_ROUND_CUSHION

	.align 1
DecorGfx_KISS_CUSHION: @ 83EB6A0
	.2byte MAP_OBJ_GFX_KISS_CUSHION

	.align 1
DecorGfx_ZIGZAG_CUSHION: @ 83EB6A2
	.2byte MAP_OBJ_GFX_ZIGZAG_CUSHION

	.align 1
DecorGfx_SPIN_CUSHION: @ 83EB6A4
	.2byte MAP_OBJ_GFX_SPIN_CUSHION

	.align 1
DecorGfx_DIAMOND_CUSHION: @ 83EB6A6
	.2byte MAP_OBJ_GFX_DIAMOND_CUSHION

	.align 1
DecorGfx_BALL_CUSHION: @ 83EB6A8
	.2byte MAP_OBJ_GFX_BALL_CUSHION

	.align 1
DecorGfx_GRASS_CUSHION: @ 83EB6AA
	.2byte MAP_OBJ_GFX_GRASS_CUSHION

	.align 1
DecorGfx_FIRE_CUSHION: @ 83EB6AC
	.2byte MAP_OBJ_GFX_FIRE_CUSHION

	.align 1
DecorGfx_WATER_CUSHION: @ 83EB6AE
	.2byte MAP_OBJ_GFX_WATER_CUSHION

	.align 1
DecorGfx_SNORLAX_DOLL: @ 83EB6B0
	.2byte MAP_OBJ_GFX_BIG_SNORLAX_DOLL

	.align 1
DecorGfx_RHYDON_DOLL: @ 83EB6B2
	.2byte MAP_OBJ_GFX_BIG_RHYDON_DOLL

	.align 1
DecorGfx_LAPRAS_DOLL: @ 83EB6B4
	.2byte MAP_OBJ_GFX_BIG_LAPRAS_DOLL

	.align 1
DecorGfx_VENUSAUR_DOLL: @ 83EB6B6
	.2byte MAP_OBJ_GFX_BIG_VENUSAUR_DOLL

	.align 1
DecorGfx_CHARIZARD_DOLL: @ 83EB6B8
	.2byte MAP_OBJ_GFX_BIG_CHARIZARD_DOLL

	.align 1
DecorGfx_BLASTOISE_DOLL: @ 83EB6BA
	.2byte MAP_OBJ_GFX_BIG_BLASTOISE_DOLL

	.align 1
DecorGfx_WAILMER_DOLL: @ 83EB6BC
	.2byte MAP_OBJ_GFX_BIG_WAILMER_DOLL

	.align 1
DecorGfx_REGIROCK_DOLL: @ 83EB6BE
	.2byte MAP_OBJ_GFX_BIG_REGIROCK_DOLL

	.align 1
DecorGfx_REGICE_DOLL: @ 83EB6C0
	.2byte MAP_OBJ_GFX_BIG_REGICE_DOLL

	.align 1
DecorGfx_REGISTEEL_DOLL: @ 83EB6C2
	.2byte MAP_OBJ_GFX_BIG_REGISTEEL_DOLL

	.align 2
gDecorations:: @ 83EB6C4
	.byte DECOR_NONE
	.string "KLEINER TISCH$", 16
	.byte 0
	.byte 0
	.byte 0
	.2byte 0
	.space 2
	.4byte DecorDesc_SMALL_DESK
	.4byte DecorGfx_SMALL_DESK

	.byte DECOR_SMALL_DESK
	.string "KLEINER TISCH$", 16
	.byte 0
	.byte 0
	.byte 0
	.2byte 3000
	.space 2
	.4byte DecorDesc_SMALL_DESK
	.4byte DecorGfx_SMALL_DESK

	.byte DECOR_POKEMON_DESK
	.string "POKéMONTISCH$", 16
	.byte 0
	.byte 0
	.byte 0
	.2byte 3000
	.space 2
	.4byte DecorDesc_POKEMON_DESK
	.4byte DecorGfx_POKEMON_DESK

	.byte DECOR_HEAVY_DESK
	.string "SCHWERER TISCH$", 16
	.byte 0
	.byte 9
	.byte 0
	.2byte 6000
	.space 2
	.4byte DecorDesc_HEAVY_DESK
	.4byte DecorGfx_HEAVY_DESK

	.byte DECOR_RAGGED_DESK
	.string "INTARSIENTISCH$", 16
	.byte 0
	.byte 9
	.byte 0
	.2byte 6000
	.space 2
	.4byte DecorDesc_RAGGED_DESK
	.4byte DecorGfx_RAGGED_DESK

	.byte DECOR_COMFORT_DESK
	.string "NATURTISCH$", 16
	.byte 0
	.byte 9
	.byte 0
	.2byte 6000
	.space 2
	.4byte DecorDesc_COMFORT_DESK
	.4byte DecorGfx_COMFORT_DESK

	.byte DECOR_PRETTY_DESK
	.string "EDLER TISCH$", 16
	.byte 0
	.byte 8
	.byte 0
	.2byte 9000
	.space 2
	.4byte DecorDesc_PRETTY_DESK
	.4byte DecorGfx_PRETTY_DESK

	.byte DECOR_BRICK_DESK
	.string "BACKSTEINTISCH$", 16
	.byte 0
	.byte 8
	.byte 0
	.2byte 9000
	.space 2
	.4byte DecorDesc_BRICK_DESK
	.4byte DecorGfx_BRICK_DESK

	.byte DECOR_CAMP_DESK
	.string "CAMPINGTISCH$", 16
	.byte 0
	.byte 8
	.byte 0
	.2byte 9000
	.space 2
	.4byte DecorDesc_CAMP_DESK
	.4byte DecorGfx_CAMP_DESK

	.byte DECOR_HARD_DESK
	.string "MASSIVER TISCH$", 16
	.byte 0
	.byte 8
	.byte 0
	.2byte 9000
	.space 2
	.4byte DecorDesc_HARD_DESK
	.4byte DecorGfx_HARD_DESK

	.byte DECOR_SMALL_CHAIR
	.string "KLEINER STUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_SMALL_CHAIR
	.4byte DecorGfx_SMALL_CHAIR

	.byte DECOR_POKEMON_CHAIR
	.string "POKéMON STUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_POKEMON_CHAIR
	.4byte DecorGfx_POKEMON_CHAIR

	.byte DECOR_HEAVY_CHAIR
	.string "SCHWERER STUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_HEAVY_CHAIR
	.4byte DecorGfx_HEAVY_CHAIR

	.byte DECOR_PRETTY_CHAIR
	.string "EDLER STUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_PRETTY_CHAIR
	.4byte DecorGfx_PRETTY_CHAIR

	.byte DECOR_COMFORT_CHAIR
	.string "NATURSTUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_COMFORT_CHAIR
	.4byte DecorGfx_COMFORT_CHAIR

	.byte DECOR_RAGGED_CHAIR
	.string "INTARSIENSTUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_RAGGED_CHAIR
	.4byte DecorGfx_RAGGED_CHAIR

	.byte DECOR_BRICK_CHAIR
	.string "BACKSTEINSTUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_BRICK_CHAIR
	.4byte DecorGfx_BRICK_CHAIR

	.byte DECOR_CAMP_CHAIR
	.string "CAMPINGSTUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_CAMP_CHAIR
	.4byte DecorGfx_CAMP_CHAIR

	.byte DECOR_HARD_CHAIR
	.string "MASSIVER STUHL$", 16
	.byte 1
	.byte 0
	.byte 1
	.2byte 2000
	.space 2
	.4byte DecorDesc_HARD_CHAIR
	.4byte DecorGfx_HARD_CHAIR

	.byte DECOR_RED_PLANT
	.string "ROTE PFLANZE$", 16
	.byte 2
	.byte 5
	.byte 2
	.2byte 3000
	.space 2
	.4byte DecorDesc_RED_PLANT
	.4byte DecorGfx_RED_PLANT

	.byte DECOR_TROPICAL_PLANT
	.string "TROPENPFLANZE$", 16
	.byte 2
	.byte 5
	.byte 2
	.2byte 3000
	.space 2
	.4byte DecorDesc_TROPICAL_PLANT
	.4byte DecorGfx_TROPICAL_PLANT

	.byte DECOR_PRETTY_FLOWERS
	.string "HÜBSCHE BLUMEN$", 16
	.byte 2
	.byte 5
	.byte 2
	.2byte 3000
	.space 2
	.4byte DecorDesc_PRETTY_FLOWERS
	.4byte DecorGfx_PRETTY_FLOWERS

	.byte DECOR_COLORFUL_PLANT
	.string "BUNTE PFLANZE$", 16
	.byte 2
	.byte 4
	.byte 2
	.2byte 5000
	.space 2
	.4byte DecorDesc_COLORFUL_PLANT
	.4byte DecorGfx_COLORFUL_PLANT

	.byte DECOR_BIG_PLANT
	.string "GROSSE PFLANZE$", 16
	.byte 2
	.byte 4
	.byte 2
	.2byte 5000
	.space 2
	.4byte DecorDesc_BIG_PLANT
	.4byte DecorGfx_BIG_PLANT

	.byte DECOR_GORGEOUS_PLANT
	.string "ZIERPFLANZE$", 16
	.byte 2
	.byte 4
	.byte 2
	.2byte 5000
	.space 2
	.4byte DecorDesc_GORGEOUS_PLANT
	.4byte DecorGfx_GORGEOUS_PLANT

	.byte DECOR_RED_BRICK
	.string "ROTER STEIN$", 16
	.byte 0
	.byte 5
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_RED_BRICK
	.4byte DecorGfx_RED_BRICK

	.byte DECOR_YELLOW_BRICK
	.string "GELBER STEIN$", 16
	.byte 0
	.byte 5
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_YELLOW_BRICK
	.4byte DecorGfx_YELLOW_BRICK

	.byte DECOR_BLUE_BRICK
	.string "BLAUER STEIN$", 16
	.byte 0
	.byte 5
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_BLUE_BRICK
	.4byte DecorGfx_BLUE_BRICK

	.byte DECOR_RED_BALLOON
	.string "ROTER BALLON$", 16
	.byte 1
	.byte 0
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_RED_BALLOON
	.4byte DecorGfx_RED_BALLOON

	.byte DECOR_BLUE_BALLOON
	.string "BLAUER BALLON$", 16
	.byte 1
	.byte 0
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_BLUE_BALLOON
	.4byte DecorGfx_BLUE_BALLOON

	.byte DECOR_YELLOW_BALLOON
	.string "GELBER BALLON$", 16
	.byte 1
	.byte 0
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_YELLOW_BALLOON
	.4byte DecorGfx_YELLOW_BALLOON

	.byte DECOR_RED_TENT
	.string "ROTES ZELT$", 16
	.byte 1
	.byte 8
	.byte 3
	.2byte 10000
	.space 2
	.4byte DecorDesc_RED_TENT
	.4byte DecorGfx_RED_TENT

	.byte DECOR_BLUE_TENT
	.string "BLAUES ZELT$", 16
	.byte 1
	.byte 8
	.byte 3
	.2byte 10000
	.space 2
	.4byte DecorDesc_BLUE_TENT
	.4byte DecorGfx_BLUE_TENT

	.byte DECOR_SOLID_BOARD
	.string "SOLIDES BRETT$", 16
	.byte 1
	.byte 5
	.byte 3
	.2byte 3000
	.space 2
	.4byte DecorDesc_SOLID_BOARD
	.4byte DecorGfx_SOLID_BOARD

	.byte DECOR_SLIDE
	.string "RUTSCHE$", 16
	.byte 1
	.byte 7
	.byte 3
	.2byte 8000
	.space 2
	.4byte DecorDesc_SLIDE
	.4byte DecorGfx_SLIDE

	.byte DECOR_FENCE_LENGTH
	.string "ZAUN VERTIKAL$", 16
	.byte 0
	.byte 0
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_FENCE_LENGTH
	.4byte DecorGfx_FENCE_LENGTH

	.byte DECOR_FENCE_WIDTH
	.string "ZAUN HORIZONTAL$", 16
	.byte 0
	.byte 0
	.byte 3
	.2byte 500
	.space 2
	.4byte DecorDesc_FENCE_WIDTH
	.4byte DecorGfx_FENCE_WIDTH

	.byte DECOR_TIRE
	.string "REIFEN$", 16
	.byte 0
	.byte 4
	.byte 3
	.2byte 800
	.space 2
	.4byte DecorDesc_TIRE
	.4byte DecorGfx_TIRE

	.byte DECOR_STAND
	.string "PODEST$", 16
	.byte 1
	.byte 3
	.byte 3
	.2byte 7000
	.space 2
	.4byte DecorDesc_STAND
	.4byte DecorGfx_STAND

	.byte DECOR_MUD_BALL
	.string "LEHMBALL$", 16
	.byte 1
	.byte 0
	.byte 3
	.2byte 200
	.space 2
	.4byte DecorDesc_MUD_BALL
	.4byte DecorGfx_MUD_BALL

	.byte DECOR_BREAKABLE_DOOR
	.string "BRECHBARE TÜR$", 16
	.byte 1
	.byte 5
	.byte 3
	.2byte 3000
	.space 2
	.4byte DecorDesc_BREAKABLE_DOOR
	.4byte DecorGfx_BREAKABLE_DOOR

	.byte DECOR_SAND_ORNAMENT
	.string "SANDORNAMENT$", 16
	.byte 2
	.byte 5
	.byte 3
	.2byte 3000
	.space 2
	.4byte DecorDesc_SAND_ORNAMENT
	.4byte DecorGfx_SAND_ORNAMENT

	.byte DECOR_SILVER_SHIELD
	.string "SILBERSCHILD$", 16
	.byte 2
	.byte 5
	.byte 3
	.2byte 0
	.space 2
	.4byte DecorDesc_SILVER_SHIELD
	.4byte DecorGfx_SILVER_SHIELD

	.byte DECOR_GOLD_SHIELD
	.string "GOLDSCHILD$", 16
	.byte 2
	.byte 5
	.byte 3
	.2byte 0
	.space 2
	.4byte DecorDesc_GOLD_SHIELD
	.4byte DecorGfx_GOLD_SHIELD

	.byte DECOR_GLASS_ORNAMENT
	.string "GLASORNAMENT$", 16
	.byte 2
	.byte 5
	.byte 3
	.2byte 0
	.space 2
	.4byte DecorDesc_GLASS_ORNAMENT
	.4byte DecorGfx_GLASS_ORNAMENT

	.byte DECOR_TV
	.string "FERNSEHER$", 16
	.byte 0
	.byte 0
	.byte 3
	.2byte 3000
	.space 2
	.4byte DecorDesc_TV
	.4byte DecorGfx_TV

	.byte DECOR_ROUND_TV
	.string "RUNDER TV$", 16
	.byte 0
	.byte 0
	.byte 3
	.2byte 4000
	.space 2
	.4byte DecorDesc_ROUND_TV
	.4byte DecorGfx_ROUND_TV

	.byte DECOR_CUTE_TV
	.string "HÜBSCHER TV$", 16
	.byte 0
	.byte 0
	.byte 3
	.2byte 4000
	.space 2
	.4byte DecorDesc_CUTE_TV
	.4byte DecorGfx_CUTE_TV

	.byte DECOR_GLITTER_MAT
	.string "GLITZER-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 2000
	.space 2
	.4byte DecorDesc_GLITTER_MAT
	.4byte DecorGfx_GLITTER_MAT

	.byte DECOR_JUMP_MAT
	.string "SPRUNG-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 2000
	.space 2
	.4byte DecorDesc_JUMP_MAT
	.4byte DecorGfx_JUMP_MAT

	.byte DECOR_SPIN_MAT
	.string "DREH-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 2000
	.space 2
	.4byte DecorDesc_SPIN_MAT
	.4byte DecorGfx_SPIN_MAT

	.byte DECOR_C_LOW_NOTE_MAT
	.string "Tiefes C-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_C_LOW_NOTE_MAT
	.4byte DecorGfx_C_LOW_NOTE_MAT

	.byte DECOR_D_NOTE_MAT
	.string "D-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_D_NOTE_MAT
	.4byte DecorGfx_D_NOTE_MAT

	.byte DECOR_E_NOTE_MAT
	.string "E-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_E_NOTE_MAT
	.4byte DecorGfx_E_NOTE_MAT

	.byte DECOR_F_NOTE_MAT
	.string "F-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_F_NOTE_MAT
	.4byte DecorGfx_F_NOTE_MAT

	.byte DECOR_G_NOTE_MAT
	.string "G-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_G_NOTE_MAT
	.4byte DecorGfx_G_NOTE_MAT

	.byte DECOR_A_NOTE_MAT
	.string "A-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_A_NOTE_MAT
	.4byte DecorGfx_A_NOTE_MAT

	.byte DECOR_B_NOTE_MAT
	.string "H-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_B_NOTE_MAT
	.4byte DecorGfx_B_NOTE_MAT

	.byte DECOR_C_HIGH_NOTE_MAT
	.string "Hohes C-MATTE$", 16
	.byte 1
	.byte 0
	.byte 4
	.2byte 500
	.space 2
	.4byte DecorDesc_C_HIGH_NOTE_MAT
	.4byte DecorGfx_C_HIGH_NOTE_MAT

	.byte DECOR_SURF_MAT
	.string "SURFER-MATTE$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_SURF_MAT
	.4byte DecorGfx_SURF_MAT

	.byte DECOR_THUNDER_MAT
	.string "DONNER-MATTE$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_THUNDER_MAT
	.4byte DecorGfx_THUNDER_MAT

	.byte DECOR_FIRE_BLAST_MAT
	.string "FEUER-MATTE$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_FIRE_BLAST_MAT
	.4byte DecorGfx_FIRE_BLAST_MAT

	.byte DECOR_POWDER_SNOW_MAT
	.string "SCHNEE-MATTE$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_POWDER_SNOW_MAT
	.4byte DecorGfx_POWDER_SNOW_MAT

	.byte DECOR_ATTRACT_MAT
	.string "ANZIEHUNG-MAT.$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_ATTRACT_MAT
	.4byte DecorGfx_ATTRACT_MAT

	.byte DECOR_FISSURE_MAT
	.string "GEOFISSUR-MAT.$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_FISSURE_MAT
	.4byte DecorGfx_FISSURE_MAT

	.byte DECOR_SPIKES_MAT
	.string "STACHLER-MATTE$", 16
	.byte 1
	.byte 8
	.byte 4
	.2byte 4000
	.space 2
	.4byte DecorDesc_SPIKES_MAT
	.4byte DecorGfx_SPIKES_MAT

	.byte DECOR_BALL_POSTER
	.string "BALLPOSTER$", 16
	.byte 3
	.byte 0
	.byte 5
	.2byte 1000
	.space 2
	.4byte DecorDesc_BALL_POSTER
	.4byte DecorGfx_BALL_POSTER

	.byte DECOR_GREEN_POSTER
	.string "GRÜNES POSTER$", 16
	.byte 3
	.byte 0
	.byte 5
	.2byte 1000
	.space 2
	.4byte DecorDesc_GREEN_POSTER
	.4byte DecorGfx_GREEN_POSTER

	.byte DECOR_RED_POSTER
	.string "ROTES POSTER$", 16
	.byte 3
	.byte 0
	.byte 5
	.2byte 1000
	.space 2
	.4byte DecorDesc_RED_POSTER
	.4byte DecorGfx_RED_POSTER

	.byte DECOR_BLUE_POSTER
	.string "BLAUES POSTER$", 16
	.byte 3
	.byte 0
	.byte 5
	.2byte 1000
	.space 2
	.4byte DecorDesc_BLUE_POSTER
	.4byte DecorGfx_BLUE_POSTER

	.byte DECOR_CUTE_POSTER
	.string "HÜBSCHES POSTER$", 16
	.byte 3
	.byte 0
	.byte 5
	.2byte 1000
	.space 2
	.4byte DecorDesc_CUTE_POSTER
	.4byte DecorGfx_CUTE_POSTER

	.byte DECOR_PIKA_POSTER
	.string "PICHUKA-POSTER$", 16
	.byte 3
	.byte 1
	.byte 5
	.2byte 1500
	.space 2
	.4byte DecorDesc_PIKA_POSTER
	.4byte DecorGfx_PIKA_POSTER

	.byte DECOR_LONG_POSTER
	.string "SCHLANG-POSTER$", 16
	.byte 3
	.byte 1
	.byte 5
	.2byte 1500
	.space 2
	.4byte DecorDesc_LONG_POSTER
	.4byte DecorGfx_LONG_POSTER

	.byte DECOR_SEA_POSTER
	.string "MEER-POSTER$", 16
	.byte 3
	.byte 1
	.byte 5
	.2byte 1500
	.space 2
	.4byte DecorDesc_SEA_POSTER
	.4byte DecorGfx_SEA_POSTER

	.byte DECOR_SKY_POSTER
	.string "HIMMEL-POSTER$", 16
	.byte 3
	.byte 1
	.byte 5
	.2byte 1500
	.space 2
	.4byte DecorDesc_SKY_POSTER
	.4byte DecorGfx_SKY_POSTER

	.byte DECOR_KISS_POSTER
	.string "KUSS-POSTER$", 16
	.byte 3
	.byte 1
	.byte 5
	.2byte 1500
	.space 2
	.4byte DecorDesc_KISS_POSTER
	.4byte DecorGfx_KISS_POSTER

	.byte DECOR_PICHU_DOLL
	.string "PICHU-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_PICHU_DOLL
	.4byte DecorGfx_PICHU_DOLL

	.byte DECOR_PIKACHU_DOLL
	.string "PIKACHU-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_PIKACHU_DOLL
	.4byte DecorGfx_PIKACHU_DOLL

	.byte DECOR_MARILL_DOLL
	.string "MARILL-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_MARILL_DOLL
	.4byte DecorGfx_MARILL_DOLL

	.byte DECOR_TOGEPI_DOLL
	.string "TOGEPI-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_TOGEPI_DOLL
	.4byte DecorGfx_TOGEPI_DOLL

	.byte DECOR_CYNDAQUIL_DOLL
	.string "FEURIGEL-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_CYNDAQUIL_DOLL
	.4byte DecorGfx_CYNDAQUIL_DOLL

	.byte DECOR_CHIKORITA_DOLL
	.string "ENDIVIE-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_CHIKORITA_DOLL
	.4byte DecorGfx_CHIKORITA_DOLL

	.byte DECOR_TOTODILE_DOLL
	.string "KARNIMANIPUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_TOTODILE_DOLL
	.4byte DecorGfx_TOTODILE_DOLL

	.byte DECOR_JIGGLYPUFF_DOLL
	.string "PUMMELUFFPUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_JIGGLYPUFF_DOLL
	.4byte DecorGfx_JIGGLYPUFF_DOLL

	.byte DECOR_MEOWTH_DOLL
	.string "MAUZI-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_MEOWTH_DOLL
	.4byte DecorGfx_MEOWTH_DOLL

	.byte DECOR_CLEFAIRY_DOLL
	.string "PIEPI-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_CLEFAIRY_DOLL
	.4byte DecorGfx_CLEFAIRY_DOLL

	.byte DECOR_DITTO_DOLL
	.string "DITTO-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_DITTO_DOLL
	.4byte DecorGfx_DITTO_DOLL

	.byte DECOR_SMOOCHUM_DOLL
	.string "KUSSILLA-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_SMOOCHUM_DOLL
	.4byte DecorGfx_SMOOCHUM_DOLL

	.byte DECOR_TREECKO_DOLL
	.string "GECKARBOR-PUPP.$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_TREECKO_DOLL
	.4byte DecorGfx_TREECKO_DOLL

	.byte DECOR_TORCHIC_DOLL
	.string "FLEMMLI-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_TORCHIC_DOLL
	.4byte DecorGfx_TORCHIC_DOLL

	.byte DECOR_MUDKIP_DOLL
	.string "HYDROPI-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_MUDKIP_DOLL
	.4byte DecorGfx_MUDKIP_DOLL

	.byte DECOR_DUSKULL_DOLL
	.string "ZWIRRLICHTPUP.$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_DUSKULL_DOLL
	.4byte DecorGfx_DUSKULL_DOLL

	.byte DECOR_WYNAUT_DOLL
	.string "ISSO-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_WYNAUT_DOLL
	.4byte DecorGfx_WYNAUT_DOLL

	.byte DECOR_BALTOY_DOLL
	.string "PUPPANCE-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_BALTOY_DOLL
	.4byte DecorGfx_BALTOY_DOLL

	.byte DECOR_KECLEON_DOLL
	.string "KECLEON-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_KECLEON_DOLL
	.4byte DecorGfx_KECLEON_DOLL

	.byte DECOR_AZURILL_DOLL
	.string "AZURILL-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_AZURILL_DOLL
	.4byte DecorGfx_AZURILL_DOLL

	.byte DECOR_SKITTY_DOLL
	.string "ENECO-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_SKITTY_DOLL
	.4byte DecorGfx_SKITTY_DOLL

	.byte DECOR_SWABLU_DOLL
	.string "WABLU-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_SWABLU_DOLL
	.4byte DecorGfx_SWABLU_DOLL

	.byte DECOR_GULPIN_DOLL
	.string "SCHLUPPUCKPUP.$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_GULPIN_DOLL
	.4byte DecorGfx_GULPIN_DOLL

	.byte DECOR_LOTAD_DOLL
	.string "LOTURZEL-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_LOTAD_DOLL
	.4byte DecorGfx_LOTAD_DOLL

	.byte DECOR_SEEDOT_DOLL
	.string "SAMURZEL-PUPPE$", 16
	.byte 4
	.byte 0
	.byte 6
	.2byte 3000
	.space 2
	.4byte DecorDesc_SEEDOT_DOLL
	.4byte DecorGfx_SEEDOT_DOLL

	.byte DECOR_PIKA_CUSHION
	.string "PIKA-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_PIKA_CUSHION
	.4byte DecorGfx_PIKA_CUSHION

	.byte DECOR_ROUND_CUSHION
	.string "RUNDES KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_ROUND_CUSHION
	.4byte DecorGfx_ROUND_CUSHION

	.byte DECOR_KISS_CUSHION
	.string "KUSS-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_KISS_CUSHION
	.4byte DecorGfx_KISS_CUSHION

	.byte DECOR_ZIGZAG_CUSHION
	.string "ZIGZACHS-KISS.$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_ZIGZAG_CUSHION
	.4byte DecorGfx_ZIGZAG_CUSHION

	.byte DECOR_SPIN_CUSHION
	.string "KREISEL-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_SPIN_CUSHION
	.4byte DecorGfx_SPIN_CUSHION

	.byte DECOR_DIAMOND_CUSHION
	.string "DIAMANT-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_DIAMOND_CUSHION
	.4byte DecorGfx_DIAMOND_CUSHION

	.byte DECOR_BALL_CUSHION
	.string "BALL-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_BALL_CUSHION
	.4byte DecorGfx_BALL_CUSHION

	.byte DECOR_GRASS_CUSHION
	.string "PFLANZEN-KISS.$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_GRASS_CUSHION
	.4byte DecorGfx_GRASS_CUSHION

	.byte DECOR_FIRE_CUSHION
	.string "FEUER-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_FIRE_CUSHION
	.4byte DecorGfx_FIRE_CUSHION

	.byte DECOR_WATER_CUSHION
	.string "WASSER-KISSEN$", 16
	.byte 4
	.byte 0
	.byte 7
	.2byte 2000
	.space 2
	.4byte DecorDesc_WATER_CUSHION
	.4byte DecorGfx_WATER_CUSHION

	.byte DECOR_SNORLAX_DOLL
	.string "RELAXO-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_SNORLAX_DOLL
	.4byte DecorGfx_SNORLAX_DOLL

	.byte DECOR_RHYDON_DOLL
	.string "RIZEROS-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_RHYDON_DOLL
	.4byte DecorGfx_RHYDON_DOLL

	.byte DECOR_LAPRAS_DOLL
	.string "LAPRAS-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_LAPRAS_DOLL
	.4byte DecorGfx_LAPRAS_DOLL

	.byte DECOR_VENUSAUR_DOLL
	.string "BISAFLOR-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_VENUSAUR_DOLL
	.4byte DecorGfx_VENUSAUR_DOLL

	.byte DECOR_CHARIZARD_DOLL
	.string "GLURAK-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_CHARIZARD_DOLL
	.4byte DecorGfx_CHARIZARD_DOLL

	.byte DECOR_BLASTOISE_DOLL
	.string "TURTOK-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_BLASTOISE_DOLL
	.4byte DecorGfx_BLASTOISE_DOLL

	.byte DECOR_WAILMER_DOLL
	.string "WAILMER-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_WAILMER_DOLL
	.4byte DecorGfx_WAILMER_DOLL

	.byte DECOR_REGIROCK_DOLL
	.string "REGIROCK-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_REGIROCK_DOLL
	.4byte DecorGfx_REGIROCK_DOLL

	.byte DECOR_REGICE_DOLL
	.string "REGICE-PUPPE$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_REGICE_DOLL
	.4byte DecorGfx_REGICE_DOLL

	.byte DECOR_REGISTEEL_DOLL
	.string "REGISTEEL-PUPP.$", 16
	.byte 4
	.byte 5
	.byte 6
	.2byte 10000
	.space 2
	.4byte DecorDesc_REGISTEEL_DOLL
	.4byte DecorGfx_REGISTEEL_DOLL

