	.align 2
Landmark_FlowerShop:
	.4byte gLandmarkName_FlowerShop
	.2byte 2108 @ flag num.

	.align 2
Landmark_PetalburgWoods:
	.4byte gLandmarkName_PetalburgWoods
	.2byte -1 @ flag num.

	.align 2
Landmark_MrBrineysCottage:
	.4byte gLandmarkName_MrBrineysCottage
	.2byte 2109 @ flag num.

	.align 2
Landmark_AbandonedShip:
	.4byte gLandmarkName_AbandonedShip
	.2byte 2110 @ flag num.

	.align 2
Landmark_SeashoreHouse:
	.4byte gLandmarkName_SeashoreHouse
	.2byte 2111 @ flag num.

	.align 2
Landmark_SlateportBeach:
	.4byte gLandmarkName_SlateportBeach
	.2byte -1 @ flag num.

	.align 2
Landmark_CyclingRoad:
	.4byte gLandmarkName_CyclingRoad
	.2byte -1 @ flag num.

	.align 2
Landmark_NewMauville:
	.4byte gLandmarkName_NewMauville
	.2byte 2112 @ flag num.

	.align 2
Landmark_TrickHouse:
	.4byte gLandmarkName_TrickHouse
	.2byte 2114 @ flag num.

	.align 2
Landmark_OldLadysRestShop:
	.4byte gLandmarkName_OldLadysRestShop
	.2byte 2113 @ flag num.

	.align 2
Landmark_Desert:
	.4byte gLandmarkName_Desert
	.2byte -1 @ flag num.

	.align 2
Landmark_WinstrateFamily:
	.4byte gLandmarkName_WinstrateFamily
	.2byte 2115 @ flag num.

	.align 2
Landmark_CableCar:
	.4byte gLandmarkName_CableCar
	.2byte -1 @ flag num.

	.align 2
Landmark_GlassWorkshop:
	.4byte gLandmarkName_GlassWorkshop
	.2byte 2116 @ flag num.

	.align 2
Landmark_WeatherInstitute:
	.4byte gLandmarkName_WeatherInstitute
	.2byte -1 @ flag num.

	.align 2
Landmark_MeteorFalls:
	.4byte gLandmarkName_MeteorFalls
	.2byte -1 @ flag num.

	.align 2
Landmark_TunnelersRestHouse:
	.4byte gLandmarkName_TunnelersRestHouse
	.2byte 2138 @ flag num.

	.align 2
Landmark_RusturfTunnel:
	.4byte gLandmarkName_RusturfTunnel
	.2byte -1 @ flag num.

	.align 2
Landmark_PokemonDayCare:
	.4byte gLandmarkName_PokemonDayCare
	.2byte 2118 @ flag num.

	.align 2
Landmark_SafariZoneEntrance:
	.4byte gLandmarkName_SafariZoneEntrance
	.2byte -1 @ flag num.

	.align 2
Landmark_MtPyre:
	.4byte gLandmarkName_MtPyre
	.2byte -1 @ flag num.

	.align 2
Landmark_ShoalCave:
	.4byte gLandmarkName_ShoalCave
	.2byte -1 @ flag num.

	.align 2
Landmark_SeafloorCavern:
	.4byte gLandmarkName_SeafloorCavern
	.2byte 2119 @ flag num.

	.align 2
Landmark_GraniteCave:
	.4byte gLandmarkName_GraniteCave
	.2byte -1 @ flag num.

	.align 2
Landmark_OceanCurrent:
	.4byte gLandmarkName_OceanCurrent
	.2byte -1 @ flag num.

	.align 2
Landmark_LanettesHouse:
	.4byte gLandmarkName_LanettesHouse
	.2byte 2117 @ flag num.

	.align 2
Landmark_FieryPath:
	.4byte gLandmarkName_FieryPath
	.2byte 2122 @ flag num.

	.align 2
Landmark_JaggedPass:
	.4byte gLandmarkName_JaggedPass
	.2byte -1 @ flag num.

	.align 2
Landmark_BerryMastersHouse:
	.4byte gLandmarkName_BerryMastersHouse
	.2byte 2147 @ flag num.

	.align 2
Landmark_IslandCave:
	.4byte gLandmarkName_IslandCave
	.2byte 2133 @ flag num.

	.align 2
Landmark_DesertRuins:
	.4byte gLandmarkName_DesertRuins
	.2byte 2134 @ flag num.

	.align 2
Landmark_ScorchedSlab:
	.4byte gLandmarkName_ScorchedSlab
	.2byte 2136 @ flag num.

	.align 2
Landmark_AncientTomb:
	.4byte gLandmarkName_AncientTomb
	.2byte 2137 @ flag num.

	.align 2
Landmark_SealedChamber:
	.4byte gLandmarkName_SealedChamber
	.2byte 2140 @ flag num.

	.align 2
Landmark_FossilManiacsHouse:
	.4byte gLandmarkName_FossilManiacsHouse
	.2byte 2135 @ flag num.

	.align 2
Landmark_HuntersHouse:
	.4byte gLandmarkName_HuntersHouse
	.2byte 2139 @ flag num.

	.align 2
Landmark_SkyPillar:
	.4byte gLandmarkName_SkyPillar
	.2byte 2142 @ flag num.

	.align 2
Landmarks_Route104_0:
	.4byte Landmark_FlowerShop
	.4byte NULL

	.align 2
Landmarks_Route104_1:
	.4byte Landmark_PetalburgWoods
	.4byte Landmark_MrBrineysCottage
	.4byte NULL

	.align 2
Landmarks_Route105_0:
	.4byte Landmark_IslandCave
	.4byte NULL

	.align 2
Landmarks_Route106_1:
	.4byte Landmark_GraniteCave
	.4byte NULL

	.align 2
Landmarks_Route108_0:
	.4byte Landmark_AbandonedShip
	.4byte NULL

	.align 2
Landmarks_Route109_0:
	.4byte Landmark_SeashoreHouse
	.4byte Landmark_SlateportBeach
	.4byte NULL

	.align 2
Landmarks_Route110_0:
	.4byte Landmark_CyclingRoad
	.4byte Landmark_NewMauville
	.4byte NULL

	.align 2
Landmarks_Route110_1:
	.4byte Landmark_CyclingRoad
	.4byte NULL

	.align 2
Landmarks_Route110_2:
	.4byte Landmark_CyclingRoad
	.4byte Landmark_TrickHouse
	.4byte NULL

	.align 2
Landmarks_Route111_0:
	.4byte Landmark_OldLadysRestShop
	.4byte NULL

	.align 2
Landmarks_Route111_1:
	.4byte Landmark_Desert
	.4byte NULL

	.align 2
Landmarks_Route111_3:
	.4byte Landmark_DesertRuins
	.4byte Landmark_Desert
	.4byte NULL

	.align 2
Landmarks_Route111_4:
	.4byte Landmark_WinstrateFamily
	.4byte Landmark_Desert
	.4byte NULL

	.align 2
Landmarks_Route112_0:
	.4byte Landmark_FieryPath
	.4byte Landmark_JaggedPass
	.4byte NULL

	.align 2
Landmarks_Route112_1:
	.4byte Landmark_CableCar
	.4byte Landmark_FieryPath
	.4byte NULL

	.align 2
Landmarks_Route113_1:
	.4byte Landmark_GlassWorkshop
	.4byte NULL

	.align 2
Landmarks_Route114_1:
	.4byte Landmark_FossilManiacsHouse
	.4byte NULL

	.align 2
Landmarks_Route114_2:
	.4byte Landmark_LanettesHouse
	.4byte NULL

	.align 2
Landmarks_MeteorFalls:
	.4byte Landmark_MeteorFalls
	.4byte NULL

	.align 2
Landmarks_Route116_1:
	.4byte Landmark_TunnelersRestHouse
	.4byte Landmark_RusturfTunnel
	.4byte NULL

	.align 2
Landmarks_Route116_2:
	.4byte Landmark_RusturfTunnel
	.4byte NULL

	.align 2
Landmarks_Route117_2:
	.4byte Landmark_PokemonDayCare
	.4byte NULL

	.align 2
Landmarks_Route119_1:
	.4byte Landmark_WeatherInstitute
	.4byte NULL

	.align 2
Landmarks_Route120_0:
	.4byte Landmark_ScorchedSlab
	.4byte NULL

	.align 2
Landmarks_Route120_2:
	.4byte Landmark_AncientTomb
	.4byte NULL

	.align 2
Landmarks_Route121_2:
	.4byte Landmark_SafariZoneEntrance
	.4byte NULL

	.align 2
Landmarks_Route122_0:
	.4byte Landmark_MtPyre
	.4byte NULL

	.align 2
Landmarks_Route123_0:
	.4byte Landmark_BerryMastersHouse
	.4byte NULL

	.align 2
Landmarks_Route124_7:
	.4byte Landmark_HuntersHouse
	.4byte NULL

	.align 2
Landmarks_Route125_2:
	.4byte Landmark_ShoalCave
	.4byte NULL

	.align 2
Landmarks_Route128_1:
	.4byte Landmark_SeafloorCavern
	.4byte NULL

	.align 2
Landmarks_Route131_1:
	.4byte Landmark_SkyPillar
	.4byte NULL

	.align 2
Landmarks_OceanCurrent:
	.4byte Landmark_OceanCurrent
	.4byte NULL

	.align 2
Landmarks_Route134_2:
	.4byte Landmark_SealedChamber
	.4byte Landmark_OceanCurrent
	.4byte NULL

	.align 2
Landmarks_MtChimney_2:
	.4byte Landmark_CableCar
	.4byte Landmark_JaggedPass
	.4byte NULL

	.align 2
gLandmarkLists:: @ 83FBA18
	.byte MAPSEC_Route104, 0
	.space 2
	.4byte Landmarks_Route104_0

	.byte MAPSEC_Route104, 1
	.space 2
	.4byte Landmarks_Route104_1

	.byte MAPSEC_Route105, 0
	.space 2
	.4byte Landmarks_Route105_0

	.byte MAPSEC_Route106, 1
	.space 2
	.4byte Landmarks_Route106_1

	.byte MAPSEC_Route108, 0
	.space 2
	.4byte Landmarks_Route108_0

	.byte MAPSEC_Route109, 0
	.space 2
	.4byte Landmarks_Route109_0

	.byte MAPSEC_Route110, 0
	.space 2
	.4byte Landmarks_Route110_0

	.byte MAPSEC_Route110, 1
	.space 2
	.4byte Landmarks_Route110_1

	.byte MAPSEC_Route110, 2
	.space 2
	.4byte Landmarks_Route110_2

	.byte MAPSEC_Route111, 0
	.space 2
	.4byte Landmarks_Route111_0

	.byte MAPSEC_Route111, 1
	.space 2
	.4byte Landmarks_Route111_1

	.byte MAPSEC_Route111, 2
	.space 2
	.4byte Landmarks_Route111_1

	.byte MAPSEC_Route111, 3
	.space 2
	.4byte Landmarks_Route111_3

	.byte MAPSEC_Route111, 4
	.space 2
	.4byte Landmarks_Route111_4

	.byte MAPSEC_Route112, 0
	.space 2
	.4byte Landmarks_Route112_0

	.byte MAPSEC_Route112, 1
	.space 2
	.4byte Landmarks_Route112_1

	.byte MAPSEC_Route113, 1
	.space 2
	.4byte Landmarks_Route113_1

	.byte MAPSEC_Route114, 1
	.space 2
	.4byte Landmarks_Route114_1

	.byte MAPSEC_Route114, 2
	.space 2
	.4byte Landmarks_Route114_2

	.byte MAPSEC_Route114, 3
	.space 2
	.4byte Landmarks_MeteorFalls

	.byte MAPSEC_Route115, 0
	.space 2
	.4byte Landmarks_MeteorFalls

	.byte MAPSEC_Route115, 1
	.space 2
	.4byte Landmarks_MeteorFalls

	.byte MAPSEC_Route116, 1
	.space 2
	.4byte Landmarks_Route116_1

	.byte MAPSEC_Route116, 2
	.space 2
	.4byte Landmarks_Route116_2

	.byte MAPSEC_Route117, 2
	.space 2
	.4byte Landmarks_Route117_2

	.byte MAPSEC_Route119, 1
	.space 2
	.4byte Landmarks_Route119_1

	.byte MAPSEC_Route120, 0
	.space 2
	.4byte Landmarks_Route120_0

	.byte MAPSEC_Route120, 2
	.space 2
	.4byte Landmarks_Route120_2

	.byte MAPSEC_Route121, 2
	.space 2
	.4byte Landmarks_Route121_2

	.byte MAPSEC_Route122, 0
	.space 2
	.4byte Landmarks_Route122_0

	.byte MAPSEC_Route123, 0
	.space 2
	.4byte Landmarks_Route123_0

	.byte MAPSEC_Route122, 1
	.space 2
	.4byte Landmarks_Route122_0

	.byte MAPSEC_Route124, 7
	.space 2
	.4byte Landmarks_Route124_7

	.byte MAPSEC_Route125, 2
	.space 2
	.4byte Landmarks_Route125_2

	.byte MAPSEC_Route128, 1
	.space 2
	.4byte Landmarks_Route128_1

	.byte MAPSEC_Route131, 1
	.space 2
	.4byte Landmarks_Route131_1

	.byte MAPSEC_Route132, 0
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route132, 1
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route133, 0
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route133, 1
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route133, 2
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route134, 0
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route134, 1
	.space 2
	.4byte Landmarks_OceanCurrent

	.byte MAPSEC_Route134, 2
	.space 2
	.4byte Landmarks_Route134_2

	.byte MAPSEC_MtChimney, 2
	.space 2
	.4byte Landmarks_MtChimney_2

	.byte MAPSEC_Nothing, 0
	.space 2
	.4byte NULL
