gMapName_LittlerootTown: @ 83E6FF4
	.string "WURZELHEIM$"

gMapName_OldaleTown: @ 83E7006
	.string "ROSALTSTADT$"

gMapName_DewfordTown: @ 83E7014
	.string "FAUSTAUHAVEN$"

gMapName_LavaridgeTown: @ 83E7023
	.string "BAD LAVASTADT$"

gMapName_FallarborTown: @ 83E7034
	.string "LAUBWECHSEL{NAME_END}FELD$"

gMapName_VerdanturfTown: @ 83E7045
	.string "WIESENFLUR$"

gMapName_PacifidlogTown: @ 83E7057
	.string "FLOSSBRUNN$"

gMapName_PetalburgCity: @ 83E7069
	.string "BLÜTENBURG{NAME_END} CITY$"

gMapName_SlateportCity: @ 83E707A
	.string "GRAPHITPORT{NAME_END} CITY$"

gMapName_MauvilleCity: @ 83E708B
	.string "MALVENFROH{NAME_END} CITY$"

gMapName_RustboroCity: @ 83E709B
	.string "METAROST{NAME_END} CITY$"

gMapName_FortreeCity: @ 83E70AB
	.string "BAUMHAUSEN{NAME_END} CITY$"

gMapName_LilycoveCity: @ 83E70BA
	.string "SEEGRASULB{NAME_END} CITY$"

gMapName_MossdeepCity: @ 83E70CA
	.string "MOOSBACH{NAME_END} CITY$"

gMapName_SootopolisCity: @ 83E70DA
	.string "XENEROVILLE$"

gMapName_EverGrandeCity: @ 83E70EC
	.string "PRACHTPOLIS{NAME_END} CITY$"

gMapName_Route101: @ 83E70FF
	.string "ROUTE 101$"

gMapName_Route102: @ 83E7109
	.string "ROUTE 102$"

gMapName_Route103: @ 83E7113
	.string "ROUTE 103$"

gMapName_Route104: @ 83E711D
	.string "ROUTE 104$"

gMapName_Route105: @ 83E7127
	.string "ROUTE 105$"

gMapName_Route106: @ 83E7131
	.string "ROUTE 106$"

gMapName_Route107: @ 83E713B
	.string "ROUTE 107$"

gMapName_Route108: @ 83E7145
	.string "ROUTE 108$"

gMapName_Route109: @ 83E714F
	.string "ROUTE 109$"

gMapName_Route110: @ 83E7159
	.string "ROUTE 110$"

gMapName_Route111: @ 83E7163
	.string "ROUTE 111$"

gMapName_Route112: @ 83E716D
	.string "ROUTE 112$"

gMapName_Route113: @ 83E7177
	.string "ROUTE 113$"

gMapName_Route114: @ 83E7181
	.string "ROUTE 114$"

gMapName_Route115: @ 83E718B
	.string "ROUTE 115$"

gMapName_Route116: @ 83E7195
	.string "ROUTE 116$"

gMapName_Route117: @ 83E719F
	.string "ROUTE 117$"

gMapName_Route118: @ 83E71A9
	.string "ROUTE 118$"

gMapName_Route119: @ 83E71B3
	.string "ROUTE 119$"

gMapName_Route120: @ 83E71BD
	.string "ROUTE 120$"

gMapName_Route121: @ 83E71C7
	.string "ROUTE 121$"

gMapName_Route122: @ 83E71D1
	.string "ROUTE 122$"

gMapName_Route123: @ 83E71DB
	.string "ROUTE 123$"

gMapName_Route124: @ 83E71E5
	.string "ROUTE 124$"

gMapName_Route125: @ 83E71EF
	.string "ROUTE 125$"

gMapName_Route126: @ 83E71F9
	.string "ROUTE 126$"

gMapName_Route127: @ 83E7203
	.string "ROUTE 127$"

gMapName_Route128: @ 83E720D
	.string "ROUTE 128$"

gMapName_Route129: @ 83E7217
	.string "ROUTE 129$"

gMapName_Route130: @ 83E7221
	.string "ROUTE 130$"

gMapName_Route131: @ 83E722B
	.string "ROUTE 131$"

gMapName_Route132: @ 83E7235
	.string "ROUTE 132$"

gMapName_Route133: @ 83E723F
	.string "ROUTE 133$"

gMapName_Route134: @ 83E7249
	.string "ROUTE 134$"

gMapName_Underwater: @ 83E7253
	.string "UNTERWASSER$"

gMapName_GraniteCave: @ 83E725E
	.string "GRANITHÖHLE$"

gMapName_MtChimney: @ 83E726B
	.string "SCHLOTBERG$"

gMapName_SafariZone: @ 83E7277
	.string "SAFARI-ZONE$"

gMapName_BattleTower: @ 83E7283
	.string "DUELLTURM$"

gMapName_PetalburgWoods: @ 83E7290
	.string "BLÜTENBURGWALD$"

gMapName_RusturfTunnel: @ 83E72A0
	.string "METAFLURTUNNEL$"

gMapName_AbandonedShip: @ 83E72AF
	.string "SCHIFFSWRACK$"

gMapName_NewMauville: @ 83E72BE
	.string "NEU MALVENFROH$"

gMapName_MeteorFalls: @ 83E72CB
	.string "METEORFÄLLE$"

gMapName_MtPyre: @ 83E72D8
	.string "PYROBERG$"

gMapName_EvilTeamHideout: @ 83E72E1
	.string "{EVIL_TEAM}s VERSTECK$"

gMapName_ShoalCave: @ 83E72EC
	.string "KÜSTENHÖHLE$"

gMapName_SeafloorCavern: @ 83E72F7
	.string "TIEFSEEHÖHLE$"

gMapName_VictoryRoad: @ 83E7307
	.string "SIEGESSTRASSE$"

gMapName_MirageIsland: @ 83E7314
	.string "WUNDEREILAND$"

gMapName_CaveOfOrigin: @ 83E7322
	.string "URZEITHÖHLE$"

gMapName_SouthernIsland: @ 83E7331
	.string "INSEL IM SÜDEN$"

gMapName_FieryPath: @ 83E7341
	.string "FEURIGER PFAD$"

gMapName_JaggedPass: @ 83E734C
	.string "STEILPASS$"

gMapName_SealedChamber: @ 83E7358
	.string "SIEGELKAMMER$"

gMapName_ScorchedSlab: @ 83E7367
	.string "SONNENGROTTE$"

gMapName_IslandCave: @ 83E7375
	.string "INSELHÖHLE$"

gMapName_DesertRuins: @ 83E7381
	.string "WÜSTENRUINE$"

gMapName_AncientTomb: @ 83E738E
	.string "GRABMAL$"

gMapName_InsideOfTruck: @ 83E739B
	.string "IM MÖBELWAGEN$"

gMapName_SkyPillar: @ 83E73AB
	.string "HIMMELTURM$"

gMapName_SecretBase: @ 83E73B6
	.string "GEHEIMBASIS$"

gMapName_None: @ 83E73C2
	.string "$"

	.align 2
gRegionMapLocations:: @ 83E73C4
	region_map_location  4, 11, 1, 1, LittlerootTown
	region_map_location  4,  9, 1, 1, OldaleTown
	region_map_location  2, 14, 1, 1, DewfordTown
	region_map_location  5,  3, 1, 1, LavaridgeTown
	region_map_location  3,  0, 1, 1, FallarborTown
	region_map_location  4,  6, 1, 1, VerdanturfTown
	region_map_location 17, 10, 1, 1, PacifidlogTown
	region_map_location  1,  9, 1, 1, PetalburgCity
	region_map_location  8, 10, 1, 2, SlateportCity
	region_map_location  8,  6, 2, 1, MauvilleCity
	region_map_location  0,  5, 1, 2, RustboroCity
	region_map_location 12,  0, 1, 1, FortreeCity
	region_map_location 18,  3, 2, 1, LilycoveCity
	region_map_location 24,  5, 2, 1, MossdeepCity
	region_map_location 21,  7, 1, 1, SootopolisCity
	region_map_location 27,  8, 1, 2, EverGrandeCity
	region_map_location  4, 10, 1, 1, Route101
	region_map_location  2,  9, 2, 1, Route102
	region_map_location  4,  8, 4, 1, Route103
	region_map_location  0,  7, 1, 3, Route104
	region_map_location  0, 10, 1, 3, Route105
	region_map_location  0, 13, 2, 1, Route106
	region_map_location  3, 14, 3, 1, Route107
	region_map_location  6, 14, 2, 1, Route108
	region_map_location  8, 12, 1, 3, Route109
	region_map_location  8,  7, 1, 3, Route110
	region_map_location  8,  0, 1, 6, Route111
	region_map_location  6,  3, 2, 1, Route112
	region_map_location  4,  0, 4, 1, Route113
	region_map_location  1,  0, 2, 3, Route114
	region_map_location  0,  2, 1, 3, Route115
	region_map_location  1,  5, 4, 1, Route116
	region_map_location  5,  6, 3, 1, Route117
	region_map_location 10,  6, 2, 1, Route118
	region_map_location 11,  0, 1, 6, Route119
	region_map_location 13,  0, 1, 4, Route120
	region_map_location 14,  3, 4, 1, Route121
	region_map_location 16,  4, 1, 2, Route122
	region_map_location 12,  6, 5, 1, Route123
	region_map_location 20,  3, 4, 3, Route124
	region_map_location 24,  3, 2, 2, Route125
	region_map_location 20,  6, 3, 3, Route126
	region_map_location 23,  6, 3, 3, Route127
	region_map_location 23,  9, 4, 1, Route128
	region_map_location 24, 10, 2, 1, Route129
	region_map_location 21, 10, 3, 1, Route130
	region_map_location 18, 10, 3, 1, Route131
	region_map_location 15, 10, 2, 1, Route132
	region_map_location 12, 10, 3, 1, Route133
	region_map_location  9, 10, 3, 1, Route134
	region_map_location 20,  3, 4, 3, Underwater
	region_map_location 20,  6, 3, 3, Underwater
	region_map_location 23,  6, 3, 3, Underwater
	region_map_location 23,  9, 4, 1, Underwater
	region_map_location 21,  7, 1, 1, Underwater
	region_map_location  1, 13, 1, 1, GraniteCave
	region_map_location  6,  2, 1, 1, MtChimney
	region_map_location 16,  2, 1, 1, SafariZone
	region_map_location 22, 12, 1, 1, BattleTower
	region_map_location  0,  8, 1, 1, PetalburgWoods
	region_map_location  2,  5, 1, 1, RusturfTunnel
	region_map_location  6, 14, 1, 1, AbandonedShip
	region_map_location  8,  7, 1, 1, NewMauville
	region_map_location  0,  3, 1, 1, MeteorFalls
	region_map_location  1,  2, 1, 1, MeteorFalls
	region_map_location 16,  4, 1, 1, MtPyre
	region_map_location 19,  3, 1, 1, EvilTeamHideout
	region_map_location 24,  4, 1, 1, ShoalCave
	region_map_location 24,  9, 1, 1, SeafloorCavern
	region_map_location 24,  9, 1, 1, Underwater
	region_map_location 27,  9, 1, 1, VictoryRoad
	region_map_location 17, 10, 1, 1, MirageIsland
	region_map_location 21,  7, 1, 1, CaveOfOrigin
	region_map_location 12, 14, 1, 1, SouthernIsland
	region_map_location  6,  3, 1, 1, FieryPath
	region_map_location  7,  3, 1, 1, FieryPath
	region_map_location  6,  3, 1, 1, JaggedPass
	region_map_location  7,  2, 1, 1, JaggedPass
	region_map_location 11, 10, 1, 1, SealedChamber
	region_map_location 11, 10, 1, 1, Underwater
	region_map_location 13,  0, 1, 1, ScorchedSlab
	region_map_location  0, 10, 1, 1, IslandCave
	region_map_location  8,  3, 1, 1, DesertRuins
	region_map_location 13,  2, 1, 1, AncientTomb
	region_map_location  0,  0, 1, 1, InsideOfTruck
	region_map_location 19, 10, 1, 1, SkyPillar
	region_map_location  0,  0, 1, 1, SecretBase
	region_map_location  0,  0, 1, 1, None
