
	.align 2
gWildMonHeaders::
	map PetalburgCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte PetalburgCity_WaterMonsInfo
	.4byte NULL
	.4byte PetalburgCity_FishingMonsInfo

	map SlateportCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte SlateportCity_WaterMonsInfo
	.4byte NULL
	.4byte SlateportCity_FishingMonsInfo

	map LilycoveCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte LilycoveCity_WaterMonsInfo
	.4byte NULL
	.4byte LilycoveCity_FishingMonsInfo

	map MossdeepCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte MossdeepCity_WaterMonsInfo
	.4byte NULL
	.4byte MossdeepCity_FishingMonsInfo

	map SootopolisCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte SootopolisCity_WaterMonsInfo
	.4byte NULL
	.4byte SootopolisCity_FishingMonsInfo

	map EverGrandeCity
	.2byte 0 @ padding
	.4byte NULL
	.4byte EverGrandeCity_WaterMonsInfo
	.4byte NULL
	.4byte EverGrandeCity_FishingMonsInfo

	map MeteorFalls_1F_1R
	.2byte 0 @ padding
	.4byte MeteorFalls_1F_1R_LandMonsInfo
	.4byte MeteorFalls_1F_1R_WaterMonsInfo
	.4byte NULL
	.4byte MeteorFalls_1F_1R_FishingMonsInfo

	map MeteorFalls_1F_2R
	.2byte 0 @ padding
	.4byte MeteorFalls_1F_2R_LandMonsInfo
	.4byte MeteorFalls_1F_2R_WaterMonsInfo
	.4byte NULL
	.4byte MeteorFalls_1F_2R_FishingMonsInfo

	map MeteorFalls_B1F_1R
	.2byte 0 @ padding
	.4byte MeteorFalls_B1F_1R_LandMonsInfo
	.4byte MeteorFalls_B1F_1R_WaterMonsInfo
	.4byte NULL
	.4byte MeteorFalls_B1F_1R_FishingMonsInfo

	map MeteorFalls_B1F_2R
	.2byte 0 @ padding
	.4byte MeteorFalls_B1F_2R_LandMonsInfo
	.4byte MeteorFalls_B1F_2R_WaterMonsInfo
	.4byte NULL
	.4byte MeteorFalls_B1F_2R_FishingMonsInfo

	map RusturfTunnel
	.2byte 0 @ padding
	.4byte RusturfTunnel_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map GraniteCave_1F
	.2byte 0 @ padding
	.4byte GraniteCave_1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map GraniteCave_B1F
	.2byte 0 @ padding
	.4byte GraniteCave_B1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map GraniteCave_B2F
	.2byte 0 @ padding
	.4byte GraniteCave_B2F_LandMonsInfo
	.4byte NULL
	.4byte GraniteCave_B2F_RockSmashMonsInfo
	.4byte NULL

	map GraniteCave_StevensRoom
	.2byte 0 @ padding
	.4byte GraniteCave_StevensRoom_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map PetalburgWoods
	.2byte 0 @ padding
	.4byte PetalburgWoods_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map JaggedPass
	.2byte 0 @ padding
	.4byte JaggedPass_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map FieryPath
	.2byte 0 @ padding
	.4byte FieryPath_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_1F
	.2byte 0 @ padding
	.4byte MtPyre_1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_2F
	.2byte 0 @ padding
	.4byte MtPyre_2F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_3F
	.2byte 0 @ padding
	.4byte MtPyre_3F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_4F
	.2byte 0 @ padding
	.4byte MtPyre_4F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_5F
	.2byte 0 @ padding
	.4byte MtPyre_5F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_6F
	.2byte 0 @ padding
	.4byte MtPyre_6F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_Exterior
	.2byte 0 @ padding
	.4byte MtPyre_Exterior_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map MtPyre_Summit
	.2byte 0 @ padding
	.4byte MtPyre_Summit_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Entrance
	.2byte 0 @ padding
	.4byte NULL
	.4byte SeafloorCavern_Entrance_WaterMonsInfo
	.4byte NULL
	.4byte SeafloorCavern_Entrance_FishingMonsInfo

	map SeafloorCavern_Room1
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room1_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Room2
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room2_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Room3
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room3_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Room4
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room4_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Room5
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room5_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SeafloorCavern_Room6
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room6_LandMonsInfo
	.4byte SeafloorCavern_Room6_WaterMonsInfo
	.4byte NULL
	.4byte SeafloorCavern_Room6_FishingMonsInfo

	map SeafloorCavern_Room7
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room7_LandMonsInfo
	.4byte SeafloorCavern_Room7_WaterMonsInfo
	.4byte NULL
	.4byte SeafloorCavern_Room7_FishingMonsInfo

	map SeafloorCavern_Room8
	.2byte 0 @ padding
	.4byte SeafloorCavern_Room8_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map CaveOfOrigin_Entrance
	.2byte 0 @ padding
	.4byte CaveOfOrigin_Entrance_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map CaveOfOrigin_1F
	.2byte 0 @ padding
	.4byte CaveOfOrigin_1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map CaveOfOrigin_B1F
	.2byte 0 @ padding
	.4byte CaveOfOrigin_B1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map CaveOfOrigin_B2F
	.2byte 0 @ padding
	.4byte CaveOfOrigin_B2F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map CaveOfOrigin_B3F
	.2byte 0 @ padding
	.4byte CaveOfOrigin_B3F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map VictoryRoad_1F
	.2byte 0 @ padding
	.4byte VictoryRoad_1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map VictoryRoad_B1F
	.2byte 0 @ padding
	.4byte VictoryRoad_B1F_LandMonsInfo
	.4byte NULL
	.4byte VictoryRoad_B1F_RockSmashMonsInfo
	.4byte NULL

	map VictoryRoad_B2F
	.2byte 0 @ padding
	.4byte VictoryRoad_B2F_LandMonsInfo
	.4byte VictoryRoad_B2F_WaterMonsInfo
	.4byte NULL
	.4byte VictoryRoad_B2F_FishingMonsInfo

	map ShoalCave_LowTideEntranceRoom
	.2byte 0 @ padding
	.4byte ShoalCave_LowTideEntranceRoom_LandMonsInfo
	.4byte ShoalCave_LowTideEntranceRoom_WaterMonsInfo
	.4byte NULL
	.4byte ShoalCave_LowTideEntranceRoom_FishingMonsInfo

	map ShoalCave_LowTideInnerRoom
	.2byte 0 @ padding
	.4byte ShoalCave_LowTideInnerRoom_LandMonsInfo
	.4byte ShoalCave_LowTideInnerRoom_WaterMonsInfo
	.4byte NULL
	.4byte ShoalCave_LowTideInnerRoom_FishingMonsInfo

	map ShoalCave_LowTideStairsRoom
	.2byte 0 @ padding
	.4byte ShoalCave_LowTideStairsRoom_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map ShoalCave_LowTideLowerRoom
	.2byte 0 @ padding
	.4byte ShoalCave_LowTideLowerRoom_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map ShoalCave_LowTideIceRoom
	.2byte 0 @ padding
	.4byte ShoalCave_LowTideIceRoom_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map NewMauville_Entrance
	.2byte 0 @ padding
	.4byte NewMauville_Entrance_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map NewMauville_Inside
	.2byte 0 @ padding
	.4byte NewMauville_Inside_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map AbandonedShip_Rooms_B1F
	.2byte 0 @ padding
	.4byte NULL
	.4byte AbandonedShip_Rooms_B1F_WaterMonsInfo
	.4byte NULL
	.4byte AbandonedShip_Rooms_B1F_FishingMonsInfo

	map AbandonedShip_HiddenFloorCorridors
	.2byte 0 @ padding
	.4byte NULL
	.4byte AbandonedShip_HiddenFloorCorridors_WaterMonsInfo
	.4byte NULL
	.4byte AbandonedShip_HiddenFloorCorridors_FishingMonsInfo

	map SkyPillar_1F
	.2byte 0 @ padding
	.4byte SkyPillar_1F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SkyPillar_3F
	.2byte 0 @ padding
	.4byte SkyPillar_3F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map SkyPillar_5F
	.2byte 0 @ padding
	.4byte SkyPillar_5F_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map Route101
	.2byte 0 @ padding
	.4byte Route101_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map Route102
	.2byte 0 @ padding
	.4byte Route102_LandMonsInfo
	.4byte Route102_WaterMonsInfo
	.4byte NULL
	.4byte Route102_FishingMonsInfo

	map Route103
	.2byte 0 @ padding
	.4byte Route103_LandMonsInfo
	.4byte Route103_WaterMonsInfo
	.4byte NULL
	.4byte Route103_FishingMonsInfo

	map Route104
	.2byte 0 @ padding
	.4byte Route104_LandMonsInfo
	.4byte Route104_WaterMonsInfo
	.4byte NULL
	.4byte Route104_FishingMonsInfo

	map Route105
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route105_WaterMonsInfo
	.4byte NULL
	.4byte Route105_FishingMonsInfo

	map Route106
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route106_WaterMonsInfo
	.4byte NULL
	.4byte Route106_FishingMonsInfo

	map Route107
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route107_WaterMonsInfo
	.4byte NULL
	.4byte Route107_FishingMonsInfo

	map Route108
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route108_WaterMonsInfo
	.4byte NULL
	.4byte Route108_FishingMonsInfo

	map Route109
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route109_WaterMonsInfo
	.4byte NULL
	.4byte Route109_FishingMonsInfo

	map Route110
	.2byte 0 @ padding
	.4byte Route110_LandMonsInfo
	.4byte Route110_WaterMonsInfo
	.4byte NULL
	.4byte Route110_FishingMonsInfo

	map Route111
	.2byte 0 @ padding
	.4byte Route111_LandMonsInfo
	.4byte Route111_WaterMonsInfo
	.4byte Route111_RockSmashMonsInfo
	.4byte Route111_FishingMonsInfo

	map Route112
	.2byte 0 @ padding
	.4byte Route112_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map Route113
	.2byte 0 @ padding
	.4byte Route113_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map Route114
	.2byte 0 @ padding
	.4byte Route114_LandMonsInfo
	.4byte Route114_WaterMonsInfo
	.4byte Route114_RockSmashMonsInfo
	.4byte Route114_FishingMonsInfo

	map Route115
	.2byte 0 @ padding
	.4byte Route115_LandMonsInfo
	.4byte Route115_WaterMonsInfo
	.4byte NULL
	.4byte Route115_FishingMonsInfo

	map Route116
	.2byte 0 @ padding
	.4byte Route116_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map Route117
	.2byte 0 @ padding
	.4byte Route117_LandMonsInfo
	.4byte Route117_WaterMonsInfo
	.4byte NULL
	.4byte Route117_FishingMonsInfo

	map Route118
	.2byte 0 @ padding
	.4byte Route118_LandMonsInfo
	.4byte Route118_WaterMonsInfo
	.4byte NULL
	.4byte Route118_FishingMonsInfo

	map Route119
	.2byte 0 @ padding
	.4byte Route119_LandMonsInfo
	.4byte Route119_WaterMonsInfo
	.4byte NULL
	.4byte Route119_FishingMonsInfo

	map Route120
	.2byte 0 @ padding
	.4byte Route120_LandMonsInfo
	.4byte Route120_WaterMonsInfo
	.4byte NULL
	.4byte Route120_FishingMonsInfo

	map Route121
	.2byte 0 @ padding
	.4byte Route121_LandMonsInfo
	.4byte Route121_WaterMonsInfo
	.4byte NULL
	.4byte Route121_FishingMonsInfo

	map Route122
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route122_WaterMonsInfo
	.4byte NULL
	.4byte Route122_FishingMonsInfo

	map Route123
	.2byte 0 @ padding
	.4byte Route123_LandMonsInfo
	.4byte Route123_WaterMonsInfo
	.4byte NULL
	.4byte Route123_FishingMonsInfo

	map Route124
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route124_WaterMonsInfo
	.4byte NULL
	.4byte Route124_FishingMonsInfo

	map Route125
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route125_WaterMonsInfo
	.4byte NULL
	.4byte Route125_FishingMonsInfo

	map Route126
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route126_WaterMonsInfo
	.4byte NULL
	.4byte Route126_FishingMonsInfo

	map Route127
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route127_WaterMonsInfo
	.4byte NULL
	.4byte Route127_FishingMonsInfo

	map Route128
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route128_WaterMonsInfo
	.4byte NULL
	.4byte Route128_FishingMonsInfo

	map Route129
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route129_WaterMonsInfo
	.4byte NULL
	.4byte Route129_FishingMonsInfo

	map Route130
	.2byte 0 @ padding
	.4byte Route130_LandMonsInfo
	.4byte Route130_WaterMonsInfo
	.4byte NULL
	.4byte Route130_FishingMonsInfo

	map Route131
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route131_WaterMonsInfo
	.4byte NULL
	.4byte Route131_FishingMonsInfo

	map Route132
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route132_WaterMonsInfo
	.4byte NULL
	.4byte Route132_FishingMonsInfo

	map Route133
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route133_WaterMonsInfo
	.4byte NULL
	.4byte Route133_FishingMonsInfo

	map Route134
	.2byte 0 @ padding
	.4byte NULL
	.4byte Route134_WaterMonsInfo
	.4byte NULL
	.4byte Route134_FishingMonsInfo

	map SafariZone_Northwest
	.2byte 0 @ padding
	.4byte SafariZone_Northwest_LandMonsInfo
	.4byte SafariZone_Northwest_WaterMonsInfo
	.4byte NULL
	.4byte SafariZone_Northwest_FishingMonsInfo

	map SafariZone_Northeast
	.2byte 0 @ padding
	.4byte SafariZone_Northeast_LandMonsInfo
	.4byte NULL
	.4byte SafariZone_Northeast_RockSmashMonsInfo
	.4byte NULL

	map SafariZone_Southwest
	.2byte 0 @ padding
	.4byte SafariZone_Southwest_LandMonsInfo
	.4byte SafariZone_Southwest_WaterMonsInfo
	.4byte NULL
	.4byte SafariZone_Southwest_FishingMonsInfo

	map SafariZone_Southeast
	.2byte 0 @ padding
	.4byte SafariZone_Southeast_LandMonsInfo
	.4byte NULL
	.4byte NULL
	.4byte NULL

	map DewfordTown
	.2byte 0 @ padding
	.4byte NULL
	.4byte DewfordTown_WaterMonsInfo
	.4byte NULL
	.4byte DewfordTown_FishingMonsInfo

	map PacifidlogTown
	.2byte 0 @ padding
	.4byte NULL
	.4byte PacifidlogTown_WaterMonsInfo
	.4byte NULL
	.4byte PacifidlogTown_FishingMonsInfo

	map Underwater1
	.2byte 0 @ padding
	.4byte NULL
	.4byte Underwater1_WaterMonsInfo
	.4byte NULL
	.4byte NULL

	map Underwater2
	.2byte 0 @ padding
	.4byte NULL
	.4byte Underwater2_WaterMonsInfo
	.4byte NULL
	.4byte NULL

	map UNDEFINED
	.2byte 0 @ padding
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.4byte NULL
