Route110_TrickHousePuzzle3_Text_JustinIntro:: @ 819CF76
	.string "Ich laufe und laufe und lande immer\n"
	.string "wieder hier.$"

Route110_TrickHousePuzzle3_Text_JustinDefeat:: @ 819CF9D
	.string "Ich habe eh schon Probleme und dann\n"
	.string "musst du mich auch noch besiegen? Pfui.$"

Route110_TrickHousePuzzle3_Text_JustinPostBattle:: @ 819CFE6
	.string "Hier sieht man vor lauter Türen den Aus-\n"
	.string "gang nicht! Ich bin total verwirrt...$"

Route110_TrickHousePuzzle3_Text_MarthaIntro:: @ 819D026
	.string "Ich weiß nicht, was hier vorgeht.\n"
	.string "Ich habe ein ganz schlechtes Gefühl...$"

Route110_TrickHousePuzzle3_Text_MarthaDefeat:: @ 819D065
	.string "Du... Du bist furchtbar!$"

Route110_TrickHousePuzzle3_Text_MarthaPostBattle:: @ 819D07A
	.string "Ich weiß, ich bin schwach! Ich weiß\n"
	.string "nicht, in welche Richtung es weitergeht.$"

Route110_TrickHousePuzzle3_Text_AlanIntro:: @ 819D0AE
	.string "Ich verstehe es nicht. Was macht einer\n"
	.string "mit so einem bizarren Haus???$"

Route110_TrickHousePuzzle3_Text_AlanDefeat:: @ 819D0F0
	.string "Ich verstehe es wieder nicht.\n"
	.string "Wie konnte ich jetzt verlieren?$"

Route110_TrickHousePuzzle3_Text_AlanPostBattle:: @ 819D110
	.string "Ich habe absolut keine Ahnung...\n"
	.string "Wie viele Fallen gibt es in diesem Haus?\p"
	.string "Du kannst mir das bestimmt\n"
	.string "beantworten!$"

Route110_TrickHousePuzzle3_Text_WroteSecretCodeLockOpened: @ 819D164
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist cool.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
