SootopolisCity_MonSizeRecordHouse_Text_PleaseShowMeBigShroomish:: @ 81900F7
	.string "Kennst du das POKéMON KNILZ?\n"
	.string "In XENEROVILLE wird es kaum gesehen.\p"
	.string "Aber ich liebe große KNILZ.\n"
	.string "Je größer, desto besser.\p"
	.string "Aber mein jüngerer Bruder sagt, dass\n"
	.string "SCHMERBE größer ist.\p"
	.string "Verrückt! KNILZ muss einfach\n"
	.string "größer sein!\p"
	.string "Wie? Du hast ein KNILZ dabei???\n"
	.string "B-b-bitte zeig es mir!$"

SootopolisCity_MonSizeRecordHouse_Text_GoshMightBeBiggerThanBarboach:: @ 819021D
	.string "{STR_VAR_2}cm!\n"
	.string "Meine Güte, ist das aber groß!\p"
	.string "Das wird sogar größer als das SCHMERBE\n"
	.string "sein, das mein Bruder gesehen hat!\p"
	.string "Danke, dass du es mir gezeigt hast.\n"
	.string "Hier, ein kleines Dankeschön!$"

UnknownString_81902AE: @ 81902AE
	.string "{PLAYER} erhält einen TRANK.$"

SootopolisCity_MonSizeRecordHouse_Text_BagCrammedFull1:: @ 81902C4
	.string "Huch.\n"
	.string "Dein BEUTEL ist ja randvoll.$"

SootopolisCity_MonSizeRecordHouse_Text_SeenBiggerShroomish:: @ 81902E4
	.string "{STR_VAR_2}cm, nicht wahr?\p"
	.string "Hmm... Ich habe schon größere\n"
	.string "KNILZ als dieses gesehen.$"

SootopolisCity_MonSizeRecordHouse_Text_ThatsNotShroomish:: @ 8190329
	.string "Na, das ist doch schon ganz ordentlich...\n"
	.string "Aber das ist kein KNILZ!$"

SootopolisCity_MonSizeRecordHouse_Text_DontHaveBigShroomish:: @ 8190366
	.string "Du hast gar kein großes KNILZ?\n"
	.string "Och, wie schade...\p"
	.string "Wenn du ein großes KNILZ hast,\n"
	.string "dann komm bitte wieder und zeig es mir.$"

SootopolisCity_MonSizeRecordHouse_Text_BiggestShroomishInHistory:: @ 81903C9
	.string "Das größte KNILZ aller Zeiten!\n"
	.string "Der {STR_VAR_3}cm-Gigant von {STR_VAR_2}!\p"
	.string "Ein KNILZ so groß, wie ein\n"
	.string "SCHMERBE gerne sein würde!$"

SootopolisCity_MonSizeRecordHouse_Text_PleaseShowMeBigBarboach:: @ 8190431
	.string "Kennst du das POKéMON SCHMERBE?\n"
	.string "Das ist bisher selten in XENEROVILLE\l"
	.string "aufgetaucht.\p"
	.string "Ich liebe große SCHMERBE.\p"
	.string "Mein großer Bruder sagt, dass\n"
	.string "KNILZ größer ist.\p"
	.string "Aber das stimmt gar nicht! Jeder weiß\n"
	.string "doch, dass SCHMERBE viel größer\l"
	.string "ist.\p"
	.string "Wie? Oh, du hast ein SCHMERBE?\n"
	.string "Bitte, bitte zeig es mir!$"

SootopolisCity_MonSizeRecordHouse_Text_WowMightBeBiggerThanBarboach:: @ 8190536
	.string "{STR_VAR_2}cm!\n"
	.string "Wow, das ist aber groß!\p"
	.string "Das ist bestimmt größer als das\n"
	.string "KNILZ, das mein Bruder gesehen\l"
	.string "hat.\p"
	.string "Danke, dass ich es anschauen durfte.\n"
	.string "Hier, ein kleines Dankeschön!$"

SootopolisCity_House8_Text_BagIsFull:: @ 81905C1
	.string "Huups, dein BEUTEL ist voll.$"

SootopolisCity_MonSizeRecordHouse_Text_SeenBiggerBarboach:: @ 81905E6
	.string "{STR_VAR_2}cm?\p"
	.string "Ach... Da habe ich aber schon ein\n"
	.string "größeres SCHMERBE gesehen.$"

SootopolisCity_MonSizeRecordHouse_Text_ThatsNotBarboach:: @ 8190628
	.string "Nun, das ist ganz stattlich.\n"
	.string "Aber es ist kein SCHMERBE!$"

SootopolisCity_MonSizeRecordHouse_Text_DontHaveBigBarboach:: @ 819065A
	.string "Hast du kein großes SCHMERBE?\n"
	.string "Och, wie enttäuschend...\p"
	.string "Wenn du ein großes SCHMERBE hast,\n"
	.string "dann komm bitte wieder her.$"

SootopolisCity_MonSizeRecordHouse_Text_BiggestBarboachInHistory:: @ 81906BE
	.string "Das größte SCHMERBE aller Zeiten!\n"
	.string "Der {STR_VAR_3}cm-Koloss von {STR_VAR_2}!\p"
	.string "Ein SCHMERBE so groß, wie ein\n"
	.string "KNILZ gerne sein würde.$"
