AbandonedShip_HiddenFloorCorridors_Text_198DC0:: @ 8198DC0
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 1” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_198DF4:: @ 8198DF4
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 2” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_198E28:: @ 8198E28
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 4” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_198E5C:: @ 8198E5C
	.string "Die Tür ist verschlossen.\p"
	.string "“K. 6” steht auf der Tür.$"

AbandonedShip_HiddenFloorCorridors_Text_198E90:: @ 8198E90
	.string "{PLAYER} steckt den SCHLÜSSEL ins\n"
	.string "Schloss und dreht ihn um.\p"
	.string "Der SCHLÜSSEL ist schwergängig, aber\n"
	.string "die Tür öffnet sich.$"

AbandonedShip_HiddenFloorRooms_Text_198EE2:: @ 8198EE2
	.string "Es ist hell und glänzend!\n"
	.string "Aber es ist trotzdem nur Müll...$"

UnknownString_8198F10: @ 8198F10
	.string "In der Wand ist eine kleine Einkerbung.$"

UnknownString_8198F34: @ 8198F34
	.string "In der Wand ist eine kleine Einkerbung.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

UnknownString_8198F6E: @ 8198F6E
	.string "Eine kleine Höhle wird sichtbar.$"
