AbandonedShip_Corridors_1F_Text_CharlieIntro:: @ 819843D
	.string "Was ist so lustig daran, dass ich meinen\n"
	.string "Schwimmreifen mit an Bord habe?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat:: @ 8198479
	.string "Hui, du hast mir die Luft rausgelassen!$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle:: @ 8198493
	.string "Es ist gar nicht so einfach, POKéBÄLLE\n"
	.string "zu werfen, wenn man einen Schwimmreifen\l"
	.string "trägt!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere:: @ 81984D8
	.string "Hier ist es doch wirklich lustig, nicht\n"
	.string "wahr? Ich bin total aufgeregt.$"
