FortreeCity_House5_Text_TreeHousesAreGreat:: @ 818696D
	.string "The tree houses of FORTREE are great!\p"
	.string "I think it's the number one town for\n"
	.string "living together with POKéMON.$"

FortreeCity_House5_Text_AdaptedToNature:: @ 81869D6
	.string "POKéMON and people have adapted to\n"
	.string "nature to survive.\p"
	.string "There's no need to make nature\n"
	.string "conform to the way we want to live.$"

FortreeCity_House5_Text_Zigzagoon:: @ 8186A4F
	.string "ZIGZAGOON: Bufuu!$"
