gEasyChatGroupWords_Misc: @ 83DD860
	.string "HÖHEN$"
	.string "TIEFEN$"
	.string "ÄH$"
	.string "HINTEN$"
	.string "SACHEN$"
	.string "DING$"
	.string "UNTERHALB$"
	.string "OBERHALB$"
	.string "ZURÜCK$"
	.string "HOCH$"
	.string "HIER$"
	.string "INNEN$"
	.string "AUSSEN$"
	.string "NEBEN$"
	.string "DAS IST ES!$"
	.string "DIES$"
	.string "ALLES$"
	.string "DIESE$"
	.string "DIESE WAREN$"
	.string "HINUNTER$"
	.string "DAS$"
	.string "SCHON$"
	.string "GENUG$"
	.string "DAS IST’S!$"
	.string "DAS SIND$"
	.string "DAS WAR$"
	.string "VORNE$"
	.string "OBEN$"
	.string "WAHL$"
	.string "WEIT$"
	.string "FORT$"
	.string "NAHE$"
	.string "WO$"
	.string "GLEICH$"
	.string "WAS$"
	.string "TIEF$"
	.string "SEICHT$"
	.string "WARUM$"
	.string "VERWIRRT$"
	.string "GEGENÜBER$"
	.string "LINKS$"
	.string "RECHTS$"
	.string "$"
