MossdeepCity_PokemonCenter_1F_Text_GymLeaderDuoFormidable:: @ 818D62F
	.string "The GYM LEADERS in this town are a\n"
	.string "formidable duo.\p"
	.string "Their combination attacks are, like,\n"
	.string "excellent and wow!$"

MossdeepCity_PokemonCenter_1F_Text_AbilitiesMightChangeMoves:: @ 818D69A
	.string "Depending on the special abilities of\n"
	.string "POKéMON, some moves might change\l"
	.string "or not work at all.$"
