VictoryRoad_B2F_MapScripts:: @ 815DFFA
	.byte 0

VictoryRoad_B2F_EventScript_15DFFB:: @ 815DFFB
	trainerbattle 0, TRAINER_VITO, 0, VictoryRoad_B2F_Text_197EF2, VictoryRoad_B2F_Text_197F46
	msgbox VictoryRoad_B2F_Text_197F71, 6
	end

VictoryRoad_B2F_EventScript_15E012:: @ 815E012
	trainerbattle 0, TRAINER_OWEN, 0, VictoryRoad_B2F_Text_197FE5, VictoryRoad_B2F_Text_19802B
	msgbox VictoryRoad_B2F_Text_198047, 6
	end

VictoryRoad_B2F_EventScript_15E029:: @ 815E029
	trainerbattle 0, TRAINER_CAROLINE, 0, VictoryRoad_B2F_Text_198089, VictoryRoad_B2F_Text_1980AD
	msgbox VictoryRoad_B2F_Text_1980C8, 6
	end

VictoryRoad_B2F_EventScript_15E040:: @ 815E040
	trainerbattle 0, TRAINER_JULIE, 0, VictoryRoad_B2F_Text_198121, VictoryRoad_B2F_Text_1981A3
	msgbox VictoryRoad_B2F_Text_1981BA, 6
	end
