VictoryRoad_B2F_MapScripts:: @ 815DFFA
	.byte 0

VictoryRoad_B2F_EventScript_15DFFB:: @ 815DFFB
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_197EF2, VictoryRoad_B2F_Text_197F46
	msgbox VictoryRoad_B2F_Text_197F71, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_15E012:: @ 815E012
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_197FE5, VictoryRoad_B2F_Text_19802B
	msgbox VictoryRoad_B2F_Text_198047, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_15E029:: @ 815E029
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_198089, VictoryRoad_B2F_Text_1980AD
	msgbox VictoryRoad_B2F_Text_1980C8, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_15E040:: @ 815E040
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_198121, VictoryRoad_B2F_Text_1981A3
	msgbox VictoryRoad_B2F_Text_1981BA, MSGBOX_AUTOCLOSE
	end
