SlateportCity_PokemonFanClub_Text_MeetChairman:: @ 817D773
	.string "Äh-hm. Ich bin der VORSITZENDE des\n"
	.string "POKéMON-FANCLUBS!\p"
	.string "Als VORSITZENDER bin ich natürlich die\n"
	.string "wichtigste Person hier!\p"
	.string "Keiner kann mir im Umgang mit POKéMON\n"
	.string "das Wasser reichen! Keiner!!!\p"
	.string "Und in jedem WETTBEWERB bin ich\n"
	.string "natürlich der Sieger!\p"
	.string "Aber dadurch enthalte ich den anderen\n"
	.string "ihr Vergnügen vor.\p"
	.string "Und deshalb beschränke ich mich darauf,\n"
	.string "die POKéMON der anderen zu beurteilen.\p"
	.string "Es ist toll, zu sehen, wie andere ihre\n"
	.string "POKéMON aufziehen.\p"
	.string "Die zufriedenen Gesichter der POKéMON,\n"
	.string "die gut behandelt werden...\p"
	.string "Die fürsorgliche und liebevolle Art ihrer\n"
	.string "Trainer...\p"
	.string "Mein Herz geht über vor Freude - da\n"
	.string "gibt es so viel Glück.\p"
	.string "Oh je! Entschuldige, ich schwatze hier\n"
	.string "die ganze Zeit vor mich hin!\p"
	.string "Bitte, erlaube mir einen Blick auf deine\n"
	.string "POKéMON. Wie sind sie gewachsen?$"

SlateportCity_PokemonFanClub_Text_HowIsYourPokemonGrowing:: @ 817DA14
	.string "Wie sehen deine POKéMON aus? Wie sind\n"
	.string "sie gewachsen? Erlaube mir einen Blick!$"

SlateportCity_PokemonFanClub_Text_HmHmISee:: @ 817DA49
	.string "Hm, hm...\n"
	.string "Verstehe...$"

SlateportCity_PokemonFanClub_Text_GiveMonMorePokeblocks:: @ 817DA5C
	.string "Hmmm... Das ist weder gut noch\n"
	.string "schlecht...\p"
	.string "Du bist der TRAINER. Streng dich bei der\n"
	.string "Aufzucht dieses POKéMON mehr an!\p"
	.string "Dürfte ich vorschlagen, ihm mehr\n"
	.string "{POKEBLOCK} zu geben?$"

SlateportCity_PokemonFanClub_Text_NoSpaceForReward:: @ 817DB0B
	.string "Oh, hey...\p"
	.string "Dein POKéMON macht einen guten Ein-\n"
	.string "druck. Ich möchte dir eine Belohnung\l"
	.string "geben.\p"
	.string "Leider hast du in deinem BEUTEL nicht\n"
	.string "mehr genügend Platz.$"

SlateportCity_PokemonFanClub_Text_MonMostImpressiveGiveItThis:: @ 817DB89
	.string "Dein {STR_VAR_1} ist wirklich sehr\n"
	.string "beeindruckend! Das ist wirklich ein\l"
	.string "wunderbares Exemplar!\p"
	.string "Und wenn du ihm dies gibst, wird\n"
	.string "es noch besser wachsen! Wirklich!$"

SlateportCity_PokemonFanClub_Text_ExplainRedScarf:: @ 817DC1B
	.string "Lass ein POKéMON einen ROTEN SCHAL\n"
	.string "tragen.\p"
	.string "Dadurch wird die Coolness deines\n"
	.string "POKéMON unübersehbar!$"

SlateportCity_PokemonFanClub_Text_ExplainBlueScarf:: @ 817DC74
	.string "Lass ein POKéMON einen BLAUEN SCHAL\n"
	.string "tragen.\p"
	.string "Dadurch wird die Schönheit deines\n"
	.string "POKéMON unübersehbar!$"

SlateportCity_PokemonFanClub_Text_ExplainPinkScarf:: @ 817DCCB
	.string "Lass ein POKéMON einen ROSA SCHAL\n"
	.string "tragen.\p"
	.string "Dadurch wird die Anmut deines\n"
	.string "POKéMON unübersehbar!$"

SlateportCity_PokemonFanClub_Text_ExplainGreenScarf:: @ 817DD27
	.string "Lass ein POKéMON einen GRÜNEN SCHAL\n"
	.string "tragen.\p"
	.string "Dadurch wird die Klugheit deines\n"
	.string "POKéMON unübersehbar!$"

SlateportCity_PokemonFanClub_Text_ExplainYellowScarf:: @ 817DD78
	.string "Lass ein POKéMON einen GELBEN SCHAL\n"
	.string "tragen.\p"
	.string "Dadurch wird die Stärke deines\n"
	.string "POKéMON unübersehbar!$"

SlateportCity_PokemonFanClub_Text_NothingElseToGiveYou:: @ 817DDD5
	.string "Tut mir Leid, mehr kann ich dir leider\n"
	.string "nicht geben! Ich habe nichts mehr!\p"
	.string "Aber du besitzt etwas viel Wertvolleres:\n"
	.string "Das Talent, POKéMON ohne Zuhilfenahme\l"
	.string "von Items perfekt aufzuziehen!$"

SlateportCity_PokemonFanClub_Text_ShowMePokemonThatLoveYou:: @ 817DE6B
	.string "Ich freue mich immer, POKéMON zu sehen,\n"
	.string "die ihre TRAINER lieben.\p"
	.string "POKéMON haben ein sensibles Gespür\n"
	.string "für die Gefühle ihrer TRAINER.\p"
	.string "Wenn du einem POKéMON Liebe und\n"
	.string "Achtung entgegenbringst, werden die\l"
	.string "Gefühle erwidert.\p"
	.string "Sobald dein POKéMON dich liebt, komm und\n"
	.string "besuche mich nochmals.$"

SlateportCity_PokemonFanClub_Text_PokemonAdoresYou:: @ 817DF57
	.string "Dein POKéMON betet dich geradezu an.\p"
	.string "Für einen so mitfühlenden TRAINER\n"
	.string "hat der FANCLUB ein Geschenk!$"

SlateportCity_PokemonFanClub_Text_TreatPokemonWithLove:: @ 817DFB8
	.string "POKéMON haben ein sensibles Gespür\n"
	.string "für die Gefühle ihrer TRAINER.\p"
	.string "Wenn du einem POKéMON Liebe und\n"
	.string "Achtung entgegenbringst, werden die\l"
	.string "Gefühle erwidert.$"

SlateportCity_PokemonFanClub_Text_PokemonDontLikeFainting:: @ 817E03B
	.string "Wenn ein POKéMON in einem Kampf besiegt\n"
	.string "wird, nimmt es das übel.\p"
	.string "Und bald wird es dem TRAINER weniger\n"
	.string "Vertrauen schenken.\p"
	.string "Mit anderen Worten: Es wird dich nicht\n"
	.string "mehr so sehr mögen.$"

SlateportCity_PokemonFanClub_Text_MonEnjoyedProtein:: @ 817E0ED
	.string "Mögen POKéMON Items?\p"
	.string "Mein POKéMON hat sich sehr gefreut,\n"
	.string "als ich ihm PROTEIN gegeben habe.$"

SlateportCity_PokemonFanClub_Text_Skitty:: @ 817E14E
	.string "ENECO: Fffnyaaaah...$"

SlateportCity_PokemonFanClub_Text_Zigzagoon:: @ 817E164
	.string "ZIGZACHS: Kyuuu...$"

SlateportCity_PokemonFanClub_Text_Azumarill:: @ 817E178
	.string "AZUMARILL: Marimari?$"
