DewfordTown_House1_Text_LotToBeSaidForLivingOnIsland:: @ 8174BA5
	.string "There's a lot to be said for living on\n"
	.string "a small island like this in harmony with\l"
	.string "POKéMON and the family.$"

DewfordTown_House1_Text_LifeGoesSlowlyOnIsland:: @ 8174C0D
	.string "I came from the large port of SLATEPORT\n"
	.string "CITY when I married my husband here.\p"
	.string "Life goes by slowly on this little\n"
	.string "island. But being surrounded by the\l"
	.string "beautiful sea - that's happiness, too.$"

DewfordTown_House1_Text_Zigzagoon:: @ 8174CC8
	.string "ZIGZAGOON: Guguuh!$"
