LilycoveCity_DepartmentStoreRooftop_Text_SetDatesForClearOutSales:: @ 818C61F
	.string "Haben sie noch nicht bekannt gegeben,\n"
	.string "wann sie den Ausverkauf starten?\p"
	.string "Ich achte immer auf die Werbung im\n"
	.string "Fernsehen, aber bisher war da nichts.$"

LilycoveCity_DepartmentStoreRooftop_Text_BeenWaitingForClearOutSale:: @ 818C685
	.string "Ja! Ich habe schon lange auf diesen\n"
	.string "Ausverkauf gewartet.\p"
	.string "Hier gibt es Items, die findest du sonst\n"
	.string "nirgends. Ich decke mich damit ein!$"

LilycoveCity_DepartmentStoreRooftop_Text_BoneDryThirsty:: @ 818C70E
	.string "Ooh... Ich bin am Verdursten!$"

LilycoveCity_DepartmentStoreRooftop_Text_WhichDrinkWouldYouLike:: @ 818C72B
	.string "Das ist ein GETRÄNKEAUTOMAT.\n"
	.string "Möchtest du etwas trinken?$"

LilycoveCity_DepartmentStoreRooftop_Text_CanOfDrinkDroppedDown:: @ 818C75F
	.string "Deng!\p"
	.string "Eine Dose {STR_VAR_1} fällt heraus.$"

LilycoveCity_DepartmentStoreRooftop_Text_ExtraCanOfDrinkDroppedDown:: @ 818C780
	.string "Deng!\p"
	.string "Treffer! Eine weitere Dose\n"
	.string "{STR_VAR_1} fällt heraus!$"

LilycoveCity_DepartmentStoreRooftop_Text_NotEnoughMoney:: @ 818C7AF
	.string "Nicht genug Geld...$"

LilycoveCity_DepartmentStoreRooftop_Text_DecidedAgainstBuyingDrink:: @ 818C7C3
	.string "Es wird kein Getränk gekauft.$"
