GraniteCave_StevensRoom_EventObjects:: @ 838C118
	object_event 1, EVENT_OBJ_GFX_STEVEN, 0, 7, 8, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, GraniteCave_StevensRoom_EventScript_15CBFA, FLAG_HIDE_STEVEN_GRANITE_CAVE

GraniteCave_StevensRoom_MapWarps:: @ 838C130
	warp_def 7, 3, 3, 3, MAP_GRANITE_CAVE_1F

GraniteCave_StevensRoom_MapEvents:: @ 838C138
	map_events GraniteCave_StevensRoom_EventObjects, GraniteCave_StevensRoom_MapWarps, 0x0, 0x0
