SootopolisCity_House3_Text_WallaceHasManyFansDoYou:: @ 818FB36
	.string "You're a POKéMON TRAINER, aren't you?\p"
	.string "SOOTOPOLIS's GYM LEADER WALLACE has\n"
	.string "many fans.\l"
	.string "Do you have any?$"

SootopolisCity_House3_Text_YouMustBePrettyStrong:: @ 818FB9C
	.string "Oh, then you must be pretty strong.$"

SootopolisCity_House3_Text_LonesomeTryWorkingHarder:: @ 818FBC0
	.string "Oh, dear...\n"
	.string "That's a little lonesome.\p"
	.string "Try working a little harder to get a\n"
	.string "fan following.$"

SootopolisCity_House3_Text_TrainerFanClubWasWild:: @ 818FC1A
	.string "Dedicated fans come over from even\n"
	.string "KANTO and JOHTO.\p"
	.string "It was really wild when I went to the\n"
	.string "TRAINER FAN CLUB in LILYCOVE.$"
