gEasyChatGroupWords_Voices: @ 83DCA20
	.string "!$"
	.string "!!!$"
	.string "?!$"
	.string "?$"
	.string "…$"
	.string "…!$"
	.string "………$"
	.string "-$"
	.string "- - -$"
	.string "OH OH$"
	.string "WAAAH$"
	.string "AHAHAHA$"
	.string "OH?$"
	.string "NÖ$"
	.string "ARGH$"
	.string "HMM$"
	.string "OOOH$"
	.string "WOOOAR$"
	.string "WOW$"
	.string "KICHER$"
	.string "SEUFZ$"
	.string "UNGLAUBLICH$"
	.string "SCHREIT$"
	.string "RICHTIG!$"
	.string "HÄH?$"
	.string "SCHREI$"
	.string "HÄHÄHÄ$"
	.string "OJE OJE$"
	.string "OH, YEAH$"
	.string "OH$"
	.string "HUPS$"
	.string "GESCHOCKT$"
	.string "IGITT$"
	.string "GRAAAH$"
	.string "GWAHAHAHA$"
	.string "ART$"
	.string "TSE$"
	.string "HÄHÄ$"
	.string "HAH$"
	.string "JAJAJA$"
	.string "HAHAHA$"
	.string "AIYEEH$"
	.string "HIYAH$"
	.string "FÖFÖFÖ$"
	.string "BRÜLL LACH$"
	.string "PRUST$"
	.string "HMPF$"
	.string "HEHEHE$"
	.string "HEH$"
	.string "HOHOHO$"
	.string "UI UI$"
	.string "MEINE GÜTE$"
	.string "AARRGH$"
	.string "HIHIHI$"
	.string "MMMH$"
	.string "OKAY$"
	.string "DURCHSCHNITT$"
	.string "LALALA$"
	.string "JAHA$"
	.string "UFF$"
	.string "JUCHEE$"
	.string "GRRR$"
	.string "WAHAHAHA$"
	.string "$"
