gEasyChatGroupWords_Endings: @ 83DCD23
	.string "WERDEN$"
	.string "WIRD DA SEIN$"
	.string "ODER$"
	.string "ZEITEN$"
	.string "WUNDER$"
	.string "ES IST$"
	.string "SEI$"
	.string "GIB MIR$"
	.string "KÖNNTE$"
	.string "VERMUTLICH$"
	.string "WÜRDE$"
	.string "IST$"
	.string "NICHT WAHR?$"
	.string "LASS UNS$"
	.string "ANDERE$"
	.string "BIST$"
	.string "WAR$"
	.string "WURDEN$"
	.string "SIND$"
	.string "IST KEIN$"
	.string "WERDE NICHT$"
	.string "KANNST$"
	.string "KÖNNEN$"
	.string "NICHT$"
	.string "MACHE$"
	.string "TUT$"
	.string "WEM$"
	.string "WELCHE$"
	.string "WAR NICHT$"
	.string "SOLLTEN$"
	.string "HABE$"
	.string "HABEN NICHT$"
	.string "EIN$"
	.string "EINE$"
	.string "NICHT NUR$"
	.string "DA$"
	.string "O.K.?$"
	.string "SO$"
	.string "VIELLEICHT$"
	.string "UMHER$"
	.string "ÜBER$"
	.string "ES$"
	.string "ALLE$"
	.string "FÜR$"
	.string "AN$"
	.string "AUS$"
	.string "GENAUSO$"
	.string "ZU$"
	.string "MIT$"
	.string "BESSER$"
	.string "JEMALS$"
	.string "SEIT$"
	.string "EINEN$"
	.string "GEHÖRT ZU$"
	.string "BEI$"
	.string "IN$"
	.string "AUF$"
	.string "AUCH$"
	.string "ÄHNLICH$"
	.string "GETAN$"
	.string "NICHT GETAN$"
	.string "MACHT$"
	.string "OHNE$"
	.string "NACH$"
	.string "VORHER$"
	.string "WÄHREND$"
	.string "ALS$"
	.string "EINMAL$"
	.string "IRGENDWO$"
	.string "$"
