Route110_TrickHousePuzzle2_Text_TedIntro:: @ 819CD46
	.string "Which switch closes which hole?$"

Route110_TrickHousePuzzle2_Text_TedDefeat:: @ 819CD66
	.string "After that battle, I'm even more\n"
	.string "confused!$"

Route110_TrickHousePuzzle2_Text_TedPostBattle:: @ 819CD91
	.string "Can I get you to push all the buttons\n"
	.string "for me?$"

Route110_TrickHousePuzzle2_Text_PaulIntro:: @ 819CDBF
	.string "Oh! You're on your second TRICK HOUSE\n"
	.string "challenge!$"

Route110_TrickHousePuzzle2_Text_PaulDefeat:: @ 819CDF0
	.string "You're good at battling too?$"

Route110_TrickHousePuzzle2_Text_PaulPostBattle:: @ 819CE0D
	.string "The TRICK MASTER rigged all the tricks\n"
	.string "in this house all by himself.$"

Route110_TrickHousePuzzle2_Text_GeorgiaIntro:: @ 819CE52
	.string "I want to make my own GYM one day.\n"
	.string "So, I'm studying how to set traps.$"

Route110_TrickHousePuzzle2_Text_GeorgiaDefeat:: @ 819CE98
	.string "I didn't study battling enough!$"

Route110_TrickHousePuzzle2_Text_GeorgiaPostBattle:: @ 819CEB8
	.string "You're strong, aren't you?\n"
	.string "Maybe even enough to be a GYM LEADER!$"

Route110_TrickHousePuzzle2_Text_WroteSecretCodeLockOpened: @ 819CEF9
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is coveted.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "The lock clicked open!$"
