DewfordTown_Hall_Text_1754C9:: @ 81754C9
	.string "Was in ist? Nun, mit Sicherheit\n"
	.string "“{STR_VAR_1}”!\p"
	.string "Ich kann mir ein Leben ohne\n"
	.string "“{STR_VAR_1}” nicht\l"
	.string "vorstellen!$"

DewfordTown_Hall_Text_175528:: @ 8175528
	.string "Was in ist? Nun, mit Sicherheit\n"
	.string "“{STR_VAR_1}”!\p"
	.string "Aber so langsam langweilt es mich.\p"
	.string "Ich sollte mich nach neuen Sachen\n"
	.string "umsehen.$"

DewfordTown_Hall_Text_17559E:: @ 817559E
	.string "Ich bringe meinen POKéMON etwas über\n"
	.string "“{STR_VAR_1}” bei,\l"
	.string "aber es klappt nicht so recht.\p"
	.string "Scheinbar sind sie damit überfordert.$"

DewfordTown_Hall_Text_1755F9:: @ 81755F9
	.string "Ich vertiefe mich gerade in ein hippes\n"
	.string "“{STR_VAR_1}”.\p"
	.string "Gibt es eine enge Verbindung\n"
	.string "zwischen “{STR_VAR_1}”\l"
	.string "und “{STR_VAR_2}”?$"

DewfordTown_Hall_Text_175664:: @ 8175664
	.string "Oh!\n"
	.string "Da lag ich ja absolut richtig!\p"
	.string "Ich bin einen Schritt weiter in meinen\n"
	.string "Bemühungen, hip und aufregend zu sein!$"

DewfordTown_Hall_Text_1756B7:: @ 81756B7
	.string "Was?!?\n"
	.string "Wirklich?!?\p"
	.string "Für einen alten Menschen ist es gar\n"
	.string "nicht so leicht, mit der Mode zu gehen!$"

DewfordTown_Hall_Text_17570D:: @ 817570D
	.string "Diese ganze Sache mit\n"
	.string "“{STR_VAR_1}”...\l"
	.string "Gibt es da nicht eine Sendung drüber?$"

DewfordTown_Hall_Text_17574C:: @ 817574C
	.string "Jenseits des Meeres...\p"
	.string "Ist dort “{STR_VAR_1}”\n"
	.string "noch beliebter?$"

DewfordTown_Hall_Text_175779:: @ 8175779
	.string "Ich sammle lizenzierte\n"
	.string "“{STR_VAR_1}”-\l"
	.string "Artikel.\p"
	.string "Ich habe die offiziellen\n"
	.string "“{STR_VAR_1}”-Puppen.\p"
	.string "Offizielle\n"
	.string "“{STR_VAR_1}”-\l"
	.string "Kleidung...\p"
	.string "Und die offiziellen\n"
	.string "“{STR_VAR_1}”-\l"
	.string "Bilderbücher.\p"
	.string "Hähähä, das besitze ich alles!\n"
	.string "Und ich gebe dir nichts ab! Ätsch!$"

DewfordTown_Hall_Text_175842:: @ 8175842
	.string "GUTE “{STR_VAR_1}” &\n"
	.string "SCHLECHTE\l"
	.string "“{STR_VAR_1}”...\p"
	.string "DAS BAND ZWISCHEN\n"
	.string "“{STR_VAR_1}”\l"
	.string "UND POKéMON...\p"
	.string "HILFREICHE\n"
	.string "“{STR_VAR_1}”...\p"
	.string "Es ist total vollgestopft mit Büchern\n"
	.string "über “{STR_VAR_1}”.$"

DewfordTown_Hall_Text_1758C4:: @ 81758C4
	.string "“DER RUF VON\n"
	.string "{STR_VAR_1}”\l"
	.string "ist der Titel.$"

DewfordTown_Hall_Text_1758E0:: @ 81758E0
	.string "“DAS LÄCHELN VON\n"
	.string "{STR_VAR_1}”\l"
	.string "ist der Titel.$"

DewfordTown_Hall_Text_1758FB:: @ 81758FB
	.string "Es heißt “DAS LETZTE\n"
	.string "{STR_VAR_1}”.$"

DewfordTown_Hall_Text_175916:: @ 8175916
	.string "Es heißt “DIE GEBURT EINES\n"
	.string "{STR_VAR_1}”.$"

DewfordTown_Hall_Text_175935:: @ 8175935
	.string "Ich habe “{STR_VAR_1}”\n"
	.string "gesehen! Cool, was?\p"
	.string "Das Coolste überhaupt, würde ich sagen!\p"
	.string "Es war unglaublich!\n"
	.string "Das war das absolut Wahre, oh yeah!$"

DewfordTown_Hall_Text_1759A1:: @ 81759A1
	.string "Oh, nein, nein, nein.\p"
	.string "Das vermeintliche\n"
	.string "“{STR_VAR_1}”,\l"
	.string "das du gesehen hast - war nicht echt.\p"
	.string "Das echte ist...\n"
	.string "Wie soll ich sagen?\l"
	.string "Ist spitzer und wohlgeformter!\p"
	.string "Aber egal. Es ist erstaunlich!$"

DewfordTown_Hall_Text_175A5C:: @ 8175A5C
	.string "Hey, hör zu! Ich habe ein Leitmotiv\n"
	.string "für “{STR_VAR_1}”\l"
	.string "komponiert.\p"
	.string "“{STR_VAR_1}”\n"
	.string "ist gerade sehr populär.\p"
	.string "Okay, hör zu!\n"
	.string "... ...\p"
	.string "Oh!\n"
	.string "{STR_VAR_1}!\p"
	.string "Wundervolles\n"
	.string "{STR_VAR_1}!$"

DewfordTown_Hall_Text_175AD9:: @ 8175AD9
	.string "... ...\p"
	.string "Ich würde sagen, du solltest erst einmal\n"
	.string "Gesangsunterricht nehmen, bevor du es\l"
	.string "mit “{STR_VAR_1}”\l"
	.string "aufnimmst.$"

DewfordTown_Hall_Text_175B46:: @ 8175B46
	.string "Wie ich vorhin schon sagte, sollten wir\n"
	.string "uns zusammentun und eine\l"
	.string "“{STR_VAR_1}”-Party\l"
	.string "auf der Insel veranstalten.$"

DewfordTown_Hall_Text_175BA7:: @ 8175BA7
	.string "Oh, was für eine gute Idee!\p"
	.string "Nun stellen wir ein für alle Mal fest, wer\n"
	.string "der Beste in\l"
	.string "“{STR_VAR_1}” ist.\l"
	.string "Brillant, wirklich!\p"
	.string "Von heute an dreht sich unser Leben\n"
	.string "um “{STR_VAR_1}”!$"

DewfordTown_Hall_Text_175C41:: @ 8175C41
	.string "Ich habe nachgedacht...\p"
	.string "Stimmst du mir zu, dass\n"
	.string "“{STR_VAR_1}” von\l"
	.string "etwas Modernem zu einem Teil unseres\l"
	.string "Lebens geworden ist?$"

DewfordTown_Hall_Text_175CC2:: @ 8175CC2
	.string "Bitte?\n"
	.string "So dominant?\p"
	.string "Nun ja, natürlich bestimmt\n"
	.string "“{STR_VAR_1}” auch\l"
	.string "unsere Gedanken, im Wachen und\l"
	.string "im Schlafen.\p"
	.string "Du bist mit Sicherheit der\n"
	.string "“{STR_VAR_1}”-\l"
	.string "PROFESSOR!$"

DewfordTown_Hall_Text_175D6B:: @ 8175D6B
	.string "Wenn du und ich ein Team bilden,\n"
	.string "sind wir unverwundbar gegen\l"
	.string "“{STR_VAR_1}”!$"

DewfordTown_Hall_Text_175DC3:: @ 8175DC3
	.string "Licht an, mein Freund!\p"
	.string "Wir sind das\n"
	.string "“{STR_VAR_1}”-DUO!\p"
	.string "Ist das nicht eine irre Vorstellung?\n"
	.string "Hahahaha!$"

DewfordTown_Hall_Text_175E13:: @ 8175E13
	.string "Für mich ist MATSCHBOMBE das absolut\n"
	.string "Größte!\p"
	.string "Wie? Du willst mir doch nicht weismachen,\n"
	.string "dass du MATSCHBOMBE nicht kennst?\p"
	.string "Das ist aber jammerschade.\n"
	.string "Ich werde dir eine geben.$"

DewfordTown_Hall_Text_175EBE:: @ 8175EBE
	.string "Ich liebe MATSCHBOMBE.\p"
	.string "Aber POKéMON, die die Attacke\n"
	.string "“{STR_VAR_1}” kennen,\l"
	.string "sind auch absolut angesagt.$"
