FortreeCity_PokemonCenter_1F_Text_186027:: @ 8186027
	.string "Na, Kindchen, arbeitest du an einem\n"
	.string "POKéDEX?\p"
	.string "Hmm... Ich an deiner Stelle würde mal\n"
	.string "die SAFARI-ZONE auf der ROUTE 121\l"
	.string "besuchen.$"

FortreeCity_PokemonCenter_1F_Text_186086:: @ 8186086
	.string "Hast du schon mal eine\n"
	.string "STATISTIK GETAUSCHT?\p"
	.string "Sehr nützliche Einrichtung! Die Erfolge\n"
	.string "eines jeden TRAINERS werden dort\l"
	.string "gespeichert und miteinander verglichen.\p"
	.string "Ich weiß zwar nicht, wie das passiert,\n"
	.string "aber es ist einfach irre. Und aufregend!$"

FortreeCity_PokemonCenter_1F_Text_186138:: @ 8186138
	.string "Hey, du hast einen POKéNAV!\n"
	.string "Ich habe auch so einen.\p"
	.string "Schau dir mal die TRAINER an.\p"
	.string "Dort kannst du sehen, welche TRAINER\n"
	.string "erneut gegen dich antreten möchten.\p"
	.string "Ist das nicht einfach super?\n"
	.string "Das muss man DEVON wirklich lassen!$"
