FortreeCity_House5_Text_18696D:: @ 818696D
	.string "Die Baumhäuser von BAUMHAUSEN\n"
	.string "CITY sind fantastisch!\p"
	.string "Ich glaube, es ist der beste Platz, um\n"
	.string "mit seinen POKéMON zusammenzuleben.$"

FortreeCity_House5_Text_1869D6:: @ 81869D6
	.string "POKéMON und Menschen sind auf die\n"
	.string "Natur angewiesen, um zu überleben.\p"
	.string "Es gibt überhaupt keinen Grund, die\n"
	.string "Natur nach unserem Willen zu formen.$"

FortreeCity_House5_Text_186A4F:: @ 8186A4F
	.string "ZIGZACHS: Bufuu!$"
