FortreeCity_House1_Text_18568C:: @ 818568C
	.string "Hi! Da gibt es dieses POKéMON, nach\n"
	.string "dem ich suche.\p"
	.string "Ich möchte ein {STR_VAR_1} haben.\n"
	.string "Hast du eines?\p"
	.string "Würdest du es gegen mein {STR_VAR_2}\n"
	.string "tauschen?$"

FortreeCity_House1_Text_1856F7:: @ 81856F7
	.string "Danke schön!\p"
	.string "Ich werde gut zu deinem {STR_VAR_1}\n"
	.string "sein, also sei auch gut zu meinem\l"
	.string "{STR_VAR_2}!$"

FortreeCity_House1_Text_185737:: @ 8185737
	.string "Warte!\n"
	.string "Das ist kein {STR_VAR_1}.\p"
	.string "Ich glaube, du willst gar nicht mit mir\n"
	.string "tauschen.$"

FortreeCity_House1_Text_18577F:: @ 818577F
	.string "Oh, okay. Wenn du es dir anders über-\n"
	.string "legst, komm wieder vorbei.\p"
	.string "Ich werde hier warten!$"

FortreeCity_House1_Text_1857C7:: @ 81857C7
	.string "Danke, dass du mit mir getauscht hast!\p"
	.string "Dieses POKéMON habe ich mir schon lange\n"
	.string "gewünscht. Bei mir wird’s ihm gut gehen!$"

FortreeCity_House1_Text_18582A:: @ 818582A
	.string "Mit anderen sein POKéMON tauschen...\p"
	.string "Das ist, als ob du die Erinnerungen mit\n"
	.string "anderen Menschen teilst.$"

FortreeCity_House1_Text_185888:: @ 8185888
	.string "ZIGZACHS: Gumomoh?$"
