GraniteCave_1F_Text_194917:: @ 8194917
	.string "Hey, du!\n"
	.string "Hier ist es schrecklich dunkel.\l"
	.string "Eine Erforschung wird damit schwierig.\p"
	.string "Der Typ, der vorher schon mal hier war...\n"
	.string "TROY heißt er, glaube ich...\p"
	.string "Der weiß, wie man BLITZ einsetzt, daher\n"
	.string "wird es ihm wohl gut gehen, aber...\p"
	.string "Das Motto unter uns WANDERERN heißt:\n"
	.string "Jedem aus der Klemme helfen.\p"
	.string "Deshalb bekommst du dies von mir.$"

GraniteCave_1F_Text_194A3E:: @ 8194A3E
	.string "Bringe einem POKéMON die VM BLITZ\n"
	.string "bei und setze sie ein.\p"
	.string "Damit wird selbst die dunkelste Höhle\n"
	.string "von Licht erfüllt.\p"
	.string "Aber um das zu können, brauchst du den\n"
	.string "ORDEN der ARENA von FAUSTAUHAVEN.$"
