LavaridgeTown_Mart_Text_176DA6:: @ 8176DA6
	.string "Mit X-TEMPO kannst du die INITIATIVE\n"
	.string "im Kampf erhöhen.\p"
	.string "So kann man eventuell den ersten\n"
	.string "Angriff ausführen - ein entscheidender\l"
	.string "Vorteil!$"

LavaridgeTown_Mart_Text_176E1A:: @ 8176E1A
	.string "Auf dem Gipfel des SCHLOTBERGS wird\n"
	.string "eine lokale Spezialität angeboten.\p"
	.string "Gib sie einem POKéMON und es wird\n"
	.string "begeistert sein.$"
