LilycoveCity_LilycoveMuseum_2F_Text_187C42:: @ 8187C42
	.string "Dies ist unser besonderer Ausstellungs-\n"
	.string "raum.$"

LilycoveCity_LilycoveMuseum_2F_Text_187C64:: @ 8187C64
	.string "Wie du klar erkennen kannst, gibt es\n"
	.string "hier nicht ein einziges Gemälde.\p"
	.string "Ich möchte hier auch nicht einfach die\n"
	.string "Gemälde der so genannten Klassiker\l"
	.string "ausstellen.\p"
	.string "Hier soll Kunst zu sehen sein, die\n"
	.string "weit von den Klassikern entfernt ist.\p"
	.string "Kunst ist doch nicht nur auf alte,\n"
	.string "berühmte Werke begrenzt!\p"
	.string "In diesem Ausstellungsraum will ich...\p"
	.string "Moderne und lebendige Kunst über\n"
	.string "POKéMON sehen, die bereit sind, in\l"
	.string "ein ruhmreiches Leben zu treten!$"

LilycoveCity_LilycoveMuseum_2F_Text_187E1D:: @ 8187E1D
	.string "Oh, entschuldige. Ich wollte dich nicht\n"
	.string "mit meinen Monologen langweilen.\p"
	.string "Nun, du bist jung und offensichtlich\n"
	.string "weit gereist...\p"
	.string "Du hast bestimmt schon viele POKéMON\n"
	.string "gesehen und Bilder, die sie darstellen.\p"
	.string "Wenn du ein solches Bild siehst, kannst\n"
	.string "du den Künstler bitte fragen, ob wir\l"
	.string "sein Werk hier ausstellen dürfen?$"

LilycoveCity_LilycoveMuseum_2F_Text_187F4E:: @ 8187F4E
	.string "Ich möchte diesen Ausstellungsraum mit\n"
	.string "modernen und lebendigen Gemälden von\l"
	.string "POKéMON füllen.$"

LilycoveCity_LilycoveMuseum_2F_Text_187F9D:: @ 8187F9D
	.string "Dank dir konnten wir ein neues Gemälde\n"
	.string "für unsere Kollektion erwerben!\p"
	.string "Ich habe gehört, es stellt dein POKéMON\n"
	.string "dar. Wirklich einzigartig!\p"
	.string "Vielen, vielen Dank!$"

LilycoveCity_LilycoveMuseum_2F_Text_18802F:: @ 818802F
	.string "Ah! Du bist es!\n"
	.string "{PLAYER}!$"

LilycoveCity_LilycoveMuseum_2F_Text_188041:: @ 8188041
	.string "Ist das nicht fantastisch?\n"
	.string "Diese Sammlung von Gemälden!\p"
	.string "Jedes einzelne makellos!\n"
	.string "Keines besser als das andere!\p"
	.string "Diese Gemälde ziehen viele neue\n"
	.string "Besucher für unser KUNSTMUSEUM an.\p"
	.string "Ehrlich, ich danke dir, {PLAYER}.\n"
	.string "Mein Traum ist wahr geworden!$"

LilycoveCity_LilycoveMuseum_2F_Text_188120:: @ 8188120
	.string "Dies ist nur ein kleines Dankeschön.$"

UnknownString_8188148: @ 8188148
	.string "{PLAYER} erhält das GLASORNAMENT.$"

LilycoveCity_LilycoveMuseum_2F_Text_188166:: @ 8188166
	.string "Ich werde das für dich aufbewahren, bis\n"
	.string "wir uns wieder sehen.$"

LilycoveCity_LilycoveMuseum_2F_Text_188194:: @ 8188194
	.string "Ah, schön dich zu sehen, {PLAYER}!\p"
	.string "Es ist eine Ehre für uns, dass du uns\n"
	.string "trotz deiner vielen Aufgaben besuchst.\p"
	.string "Bitte, entspanne dich und genieße\n"
	.string "deinen Besuch bei uns.$"

LilycoveCity_LilycoveMuseum_2F_Text_188219:: @ 8188219
	.string "Ein Bilderrahmen mit pinkfarbenen\n"
	.string "Verzierungen.$"

LilycoveCity_LilycoveMuseum_2F_Text_18824C:: @ 818824C
	.string "Ein Bilderrahmen mit gelben\n"
	.string "Verzierungen.$"

LilycoveCity_LilycoveMuseum_2F_Text_188281:: @ 8188281
	.string "Ein Bilderrahmen mit blauen\n"
	.string "Verzierungen.$"

LilycoveCity_LilycoveMuseum_2F_Text_1882B4:: @ 81882B4
	.string "Ein Bilderrahmen mit roten\n"
	.string "Verzierungen.$"

LilycoveCity_LilycoveMuseum_2F_Text_1882E6:: @ 81882E6
	.string "Ein Bilderrahmen mit grünen\n"
	.string "Verzierungen.$"

LilycoveCity_LilycoveMuseum_2F_Text_18831A:: @ 818831A
	.string "Ein Bild eines POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_188336:: @ 8188336
	.string "Ich war eine Weile nicht hier, daher\n"
	.string "haben mich die neuen Gemälde über-\l"
	.string "rascht.\p"
	.string "Ich wünschte, jemand würde mein\n"
	.string "POKéMON so wunderbar porträtieren.$"

LilycoveCity_LilycoveMuseum_2F_Text_1883AB:: @ 81883AB
	.string "Nun... Hier stellen sie also Werke zum\n"
	.string "Thema POKéMON aus.\p"
	.string "Ich sehe schon. Die Gemälde sind\n"
	.string "wirklich amüsant.$"

LilycoveCity_LilycoveMuseum_2F_Text_188423:: @ 8188423
	.string "Wow, ehrlich?\n"
	.string "Das sind Gemälde deiner POKéMON?\p"
	.string "Ist das nicht die absolute Freude für\n"
	.string "einen TRAINER?$"
