LilycoveCity_Harbor_Text_18B306:: @ 818B306
	.string "Bitte?\n"
	.string "Du suchst ein Schiff?\p"
	.string "Tut mir Leid, aber die Fähre ist\n"
	.string "momentan nicht in Betrieb...$"

LilycoveCity_Harbor_Text_18B36F:: @ 818B36F
	.string "Hallo, du willst mit der Fähre fahren?\n"
	.string "Zeigst du mir dann bitte dein TICKET?$"

LilycoveCity_Harbor_Text_18B3A9:: @ 818B3A9
	.string "{PLAYER} besitzt kein TICKET.\p"
	.string "Das tut mir Leid!\p"
	.string "Du benötigst ein TICKET, um mit der\n"
	.string "Fähre fahren zu können.$"

LilycoveCity_Harbor_Text_18B406:: @ 818B406
	.string "{PLAYER} zeigt das TICKET.\p"
	.string "Perfekt! Das ist alles, was du brauchst!\p"
	.string "Und wo soll die Reise hingehen?$"

LilycoveCity_Harbor_Text_18B45B:: @ 818B45B
	.string "Bitte fahre bald mit uns!$"

LilycoveCity_Harbor_Text_18B47D:: @ 818B47D
	.string "Nach GRAPHITPORT CITY, einverstanden?$"

LilycoveCity_Harbor_Text_18B499:: @ 818B499
	.string "Zum DUELLTURM, einverstanden?$"

LilycoveCity_Harbor_Text_18B4B3:: @ 818B4B3
	.string "Bitte komm an Bord. Wir legen bald ab.$"

LilycoveCity_Harbor_Text_18B4E2:: @ 818B4E2
	.string "Und? Wo soll die Reise hingehen?$"

LilycoveCity_Harbor_Text_18B504:: @ 818B504
	.string "Solange die Fähre noch nicht see-\n"
	.string "tüchtig ist, haben wir Seeleute\l"
	.string "nichts zu tun...\p"
	.string "Ich wünschte, sie würden sich ein\n"
	.string "bisschen beeilen - die Leute von der\l"
	.string "WERFT von GRAPHITPORT CITY.$"

LilycoveCity_Harbor_Text_18B58E:: @ 818B58E
	.string "Die Fähre MS TIDE ist endlich in\n"
	.string "Betrieb.\p"
	.string "Die Leute von der WERFT in\n"
	.string "GRAPHITPORT CITY müssen wirklich\l"
	.string "hart gearbeitet haben.\p"
	.string "Nun, jetzt ist meine Arbeit gefragt!$"
