LilycoveCity_Text_1679BF:: @ 81679BF
	.string "MAIKE: Oh, hey?\n"
	.string "{PLAYER}{KUN}, bist du auch am Einkaufen?\p"
	.string "Ich habe eine Menge PUPPEN und POSTER\n"
	.string "gekauft.\p"
	.string "Natürlich habe ich auch POKéMON\n"
	.string "gefangen und die ziehe ich geradezu\l"
	.string "vorbildlich auf.\p"
	.string "Ich habe eher Bedenken, dass du dich um\n"
	.string "deine POKéMON nicht richtig kümmerst.\p"
	.string "Ich werde gegen dich kämpfen, dann\n"
	.string "sehe ich, ob du sie gut behandelst.$"

LilycoveCity_Text_167AEB:: @ 8167AEB
	.string "MAIKE: Oh, hui. Hast du dich denn nicht\n"
	.string "um deine POKéMON gekümmert, {PLAYER}{KUN}?\p"
	.string "Als Trainer machst du wirklich keinen\n"
	.string "guten Eindruck!$"

LilycoveCity_Text_167B55:: @ 8167B55
	.string "MAIKE: Komm, kämpfe mit mir, dann kann\n"
	.string "ich deine POKéMON beurteilen.$"

LilycoveCity_Text_167B94:: @ 8167B94
	.string "MAIKE: Die POKéMON, die ich aufgezogen\n"
	.string "habe, sind mit Sicherheit unbesiegbar.$"

LilycoveCity_Text_167BD5:: @ 8167BD5
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ich kann mich noch gut an unseren\n"
	.string "Kampf auf der ROUTE 103 erinnern,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Dieser Kampf hat dir enorm geholfen,\n"
	.string "stärker zu werden, oder?$"

LilycoveCity_Text_167C6B:: @ 8167C6B
	.string "MAIKE: Ich überlege, ob ich bald nach\n"
	.string "WURZELHEIM zurückgehe.\p"
	.string "Ich habe eine anständige Gruppe von\n"
	.string "POKéMON gefangen und mein POKéDEX\p"
	.string "sieht immer besser aus. Ich gehe nach\n"
	.string "Hause und zeige das meinem Papa.$"

LilycoveCity_Text_167D08:: @ 8167D08
	.string "{PLAYER}{KUN}, was wirst du machen?\p"
	.string "Alle ORDEN der ARENEN sammeln und die\n"
	.string "POKéMON LIGA herausfordern?\p"
	.string "Nun, während du deine ORDEN sammelst,\n"
	.string "werde ich weiter an meinem POKéDEX\l"
	.string "arbeiten. Ich werde ihn eher vollständig\l"
	.string "haben als du, wetten?\p"
	.string "Bis dann!$"

LilycoveCity_Text_167DDD:: @ 8167DDD
	.string "Und, {PLAYER}{KUN}, was wirst du machen?\p"
	.string "Wirst du die POKéMON LIGA heraus-\n"
	.string "fordern?\p"
	.string "Oder wirst du deinen POKéDEX vervoll-\n"
	.string "ständigen?\p"
	.string "Ich habe gegen dich verloren, aber den\n"
	.string "POKéDEX werde ich eher vollständig\l"
	.string "haben als du!!\p"
	.string "Man sieht sich!$"

LilycoveCity_Text_167EAA:: @ 8167EAA
	.string "Und, {PLAYER}{KUN}, was wirst du machen?\p"
	.string "Wirst du im DUELLTURM antreten?\p"
	.string "Oder wirst du deinen POKéDEX vervoll-\n"
	.string "ständigen?\p"
	.string "Ich habe gegen dich verloren, aber den\n"
	.string "POKéDEX werde ich eher vollständig\l"
	.string "haben als du!\p"
	.string "Man sieht sich!$"

LilycoveCity_Text_167F75:: @ 8167F75
	.string "BRIX: Oh, du bist es, {PLAYER}.\p"
	.string "Ich mache Besorgungen für meinen\n"
	.string "Vater. Nein, ich kaufe keine PUPPEN!\p"
	.string "Wir haben uns lange nicht mehr gesehen.\p"
	.string "Sollen wir kämpfen, um zu sehen, wer\n"
	.string "seine POKéMON besser trainiert?$"

LilycoveCity_Text_16802C:: @ 816802C
	.string "BRIX: Oh, hast du ein Problem? Nicht\n"
	.string "genügend Selbstbewusstsein, was?$"

LilycoveCity_Text_168067:: @ 8168067
	.string "BRIX: Sollen wir kämpfen, um zu\n"
	.string "sehen, wer seine POKéMON besser\l"
	.string "trainiert?$"

LilycoveCity_Text_1680A9:: @ 81680A9
	.string "BRIX: Aah, ich werde doch nicht\n"
	.string "gegen {PLAYER} verlieren! Niemals!$"

LilycoveCity_Text_1680E4:: @ 81680E4
	.string "Ach...\n"
	.string "Du hast dich stark verbessert.\p"
	.string "Das schmerzt - und dabei hatte ich als\n"
	.string "TRAINER sogar einen Vorsprung...$"

LilycoveCity_Text_168149:: @ 8168149
	.string "BRIX: Ich...\n"
	.string "Ich gehe nach Hause, nach WURZELHEIM.\p"
	.string "Weißt du, ich helfe meinem Vater bei dem\n"
	.string "POKéDEX. Es geht ganz anständig voran\l"
	.string "und ich sollte ihm das mal zeigen.$"

LilycoveCity_Text_1681EA:: @ 81681EA
	.string "Und, {PLAYER}, was wirst du tun?\p"
	.string "Wirst du alle ORDEN der ARENEN sammeln\n"
	.string "und die POKéMON LIGA herausfordern?\p"
	.string "Vielleicht werde ich das auch machen...\p"
	.string "Gut, bleib am Ball!$"

LilycoveCity_Text_168282:: @ 8168282
	.string "Und, {PLAYER}, was wirst du tun?\p"
	.string "Da du so stark geworden bist, wirst du\n"
	.string "die POKéMON LIGA herausfordern?\p"
	.string "Hey, ich habe meine POKéMON bestimmt\n"
	.string "viel besser trainiert und sollte\l"
	.string "eigentlich stärker sein als du...\p"
	.string "Nun ja, bleib am Ball!$"

LilycoveCity_Text_16835A:: @ 816835A
	.string "Und, {PLAYER}, was machst du nun?\p"
	.string "Da du so stark geworden bist, wirst du\n"
	.string "zum DUELLTURM gehen?\p"
	.string "Ich habe meine POKéMON viel besser\n"
	.string "trainiert und sollte eigentlich stärker\l"
	.string "sein als du...\l"
	.string "Vielleicht gehe ich zum DUELLTURM...\p"
	.string "Nun, bleib am Ball!$"

LilycoveCity_Text_168455:: @ 8168455
	.string "Hähähä...\p"
	.string "Heute haben wir noch mehr Beute in\n"
	.string "unser VERSTECK gebracht...\p"
	.string "We...wer bist du denn??? Ich... äh, habe\n"
	.string "mit mir selbst gesprochen!$"

LilycoveCity_Text_1684C2:: @ 81684C2
	.string "Ich bin nur ein RÜPEL, ich weiß nicht,\n"
	.string "was unser BOSS so vorhat...\p"
	.string "Aber als Mitglied vom TEAM {EVIL_TEAM} habe\n"
	.string "ich die Möglichkeit, große Dinge zu tun!\p"
	.string "Ww...wer bist du denn??? I-Ich... hähähä,\n"
	.string "habe nur mit mir selber gesprochen!$"

LilycoveCity_Text_168573:: @ 8168573
	.string "Hey, du da!\p"
	.string "Komm bloß nicht in die Nähe der Höhle in\n"
	.string "der Bucht!\p"
	.string "Warum nicht? Das geht dich nichts an!\n"
	.string "Ich bin ein Erwachsener, also gehorche!$"

LilycoveCity_Text_1685EB:: @ 81685EB
	.string "Wenn die ganze Welt erst einmal uns\n"
	.string "gehört, dem TEAM {EVIL_TEAM}, dann wird sie\l"
	.string "ein besserer Ort für POKéMON sein.$"

LilycoveCity_Text_16864A:: @ 816864A
	.string "Hier, WAILMER!!!\n"
	.string "Springt aus dem Wasser!$"

LilycoveCity_Text_168675:: @ 8168675
	.string "Häh? Was willst du?\p"
	.string "Du störst uns beim Training, also würde\n"
	.string "ich vorschlagen, du verschwindest!$"

LilycoveCity_Text_1686C9:: @ 81686C9
	.string "Die POKéMON, die in diese WETTBEWERBS-\n"
	.string "HALLE kommen, sind alle preisgekrönt.\l"
	.string "Sie kommen aus dem ganzen Land.\p"
	.string "Mein Herz strömt über vor Begeisterung!$"

LilycoveCity_Text_168750:: @ 8168750
	.string "Hast du die seltsame Höhle in der Bucht\n"
	.string "am Ende des Ortes gesehen?$"

LilycoveCity_Text_168791:: @ 8168791
	.string "Ich werde meinem POKéMON einige neue\n"
	.string "Attacken für den WETTBEWERB\l"
	.string "beibringen.\p"
	.string "Daher werde ich den ATTACKEN-\n"
	.string "VERLERNER besuchen, damit einige\l"
	.string "VM verlernt werden.$"

LilycoveCity_Text_168819:: @ 8168819
	.string "Ich komme aus KANTO.\p"
	.string "Die HOENN-Region ist wunderschön mit\n"
	.string "all dem Wasser und dem Grün.\p"
	.string "Hey, warte mal!\p"
	.string "Ob es seltene POKéMON gibt, die nur in\n"
	.string "dieser Region leben???$"

LilycoveCity_Text_1688C1:: @ 81688C1
	.string "TEAM {EVIL_TEAM} trainieren ihre WAILMER\n"
	.string "drüben in der Bucht.\p"
	.string "Wir MATROSEN können nicht auslaufen,\n"
	.string "da sie uns im Weg sind.$"

LilycoveCity_Text_168934:: @ 8168934
	.string "Ahoi, hast du das mitbekommen?\p"
	.string "Jemand hat für uns TEAM {EVIL_TEAM} aus\n"
	.string "unserer Fahrrinne verjagt!\p"
	.string "Die WAILMER befinden sich nicht mehr in\n"
	.string "der Bucht und wir haben freie Fahrt.$"

LilycoveCity_Text_1689BF:: @ 81689BF
	.string "Ich habe ein entspannendes Nickerchen\n"
	.string "im Gasthof am Meer gehalten. Das\l"
	.string "Rauschen der Wellen war so angenehm.\p"
	.string "Und da hat mir jemand mein POKéMON\n"
	.string "gestohlen!\p"
	.string "Wer ist der schändliche Dieb?\n"
	.string "TEAM {EVIL_TEAM}? Es war TEAM {EVIL_TEAM}?!?$"

LilycoveCity_Text_168A55:: @ 8168A55
	.string "Mein gestohlenes POKéMON...\n"
	.string "Es kam zurück, ohne dass ich es merkte.$"

LilycoveCity_Text_168A8D:: @ 8168A8D
	.string "Ich bin ein KUNSTHÄNDLER.\p"
	.string "Ich kaufe und verkaufe Kunstgegen-\n"
	.string "stände. Vorzugsweise Gemälde.\p"
	.string "Ich habe gehört, dass das hiesige\n"
	.string "MUSEUM ständig erstklassige Werke\l"
	.string "ausstellt.$"

LilycoveCity_Text_168B1F:: @ 8168B1F
	.string "Auch wenn ich alt und grau werde, das\n"
	.string "Meer wird immer jung und voll von Leben\l"
	.string "sein...\p"
	.string "Hahahahaha... Haaahahahaha...$"

LilycoveCity_Text_168B9B:: @ 8168B9B
	.string "Vor 60 Jahren hat mein Mann hier um\n"
	.string "meine Hand angehalten. Und das Meer\l"
	.string "ist immer noch genauso schön.\p"
	.string "Hahahahaha... Haaahahahaha...$"

LilycoveCity_Text_168C16:: @ 8168C16
	.string "Hm, kennst du diese besondere Höhle in\n"
	.string "der Bucht?\p"
	.string "Das ist eine natürlich Formation, aber\n"
	.string "TEAM {EVIL_TEAM} kam und hat das Aussehen\l"
	.string "verändert.\p"
	.string "Sie nennen sich selber “Naturliebendes\n"
	.string "TEAM {EVIL_TEAM}”!\p"
	.string "Aber was sie sagen und was sie tun,\n"
	.string "passt überhaupt nicht zusammen!$"

LilycoveCity_Text_168D15:: @ 8168D15
	.string "Die Höhle in der Bucht...\n"
	.string "Jemand scheint den Eingang versiegelt\l"
	.string "zu haben, niemand kommt hinein.\p"
	.string "TEAM {EVIL_TEAM} muss verschwunden sein.$"

LilycoveCity_Text_168DA9:: @ 8168DA9
	.string "SEEGRASULB CITY\p"
	.string "“Wo das Land endet und das\n"
	.string "Meer beginnt.”$"

LilycoveCity_Text_168DE1:: @ 8168DE1
	.string "POKéMON WETTBEWERB\n"
	.string "MASTER-KLASSE REGISTRIERUNGEN\p"
	.string "“Nimm mit deinen FREUNDEN am\n"
	.string "WETTBEWERB teil!”$"

LilycoveCity_Text_168E2F:: @ 8168E2F
	.string "GRASSEE MOTEL\p"
	.string "“Behalte uns als Rose der\n"
	.string "SEEGRASULB CITY in Erinnerung.”$"

LilycoveCity_Text_168E67:: @ 8168E67
	.string "SEEGRASULB CITY MUSEUM\p"
	.string "“Ausstellung von\n"
	.string "POKéMON-Meisterwerken!”$"

LilycoveCity_Text_168EA4:: @ 8168EA4
	.string "SEEGRASULB CITY MUSEUM\p"
	.string "“Aktuelle Ausstellung:\n"
	.string "Die POKéMON-Sammlung von {PLAYER}!”$"

LilycoveCity_Text_168EDA:: @ 8168EDA
	.string "HAFEN SEEGRASULB CITY\p"
	.string "“Die Fähre MS TIDE wird momentan\n"
	.string "in der WERFT gebaut.\p"
	.string "Die Fähre wird so bald wie möglich ihren\n"
	.string "Dienst aufnehmen.”$"

LilycoveCity_Text_168F57:: @ 8168F57
	.string "HAFEN SEEGRASULB CITY\p"
	.string "“Genießen Sie die entspannende Fahrt\n"
	.string "mit der Fähre MS TIDE.”$"

LilycoveCity_Text_168FA1:: @ 8168FA1
	.string "POKéMON TRAINER-FANCLUB\p"
	.string "Die Namen von TRAINERN sind auf dem\n"
	.string "Schild eingeritzt...$"

LilycoveCity_Text_168FF3:: @ 8168FF3
	.string "SEEGRASULB CITY EINKAUFSZENTRUM\p"
	.string "“Ein Überfluss an Waren und\n"
	.string "Überraschungen!\p"
	.string "Ein Ort, an dem man alles findet, was\n"
	.string "das Herz begehrt!”$"

LilycoveCity_Text_169072:: @ 8169072
	.string "HAUS des ATTACKEN-VERLERNERS\p"
	.string "“Hier werden POKéMON-Attacken\n"
	.string "verlernt.”$"
