LittlerootTown_BrendansHouse_2F_Text_172E18:: @ 8172E18
	.string "Die Uhr ist stehen geblieben...\p"
	.string "Stelle sie besser ein und ziehe sie auf.$"

LittlerootTown_BrendansHouse_2F_Text_172E4C:: @ 8172E4C
	.string "MUTTER: {PLAYER}, wie gefällt dir dein\n"
	.string "neues Zimmer?\p"
	.string "Gut! Alles ist wunderbar aufgeräumt!\p"
	.string "Auch im Erdgeschoss ist alles\n"
	.string "komplett eingerichtet.\p"
	.string "POKéMON-Umzugshelfer sind so\n"
	.string "praktisch.\p"
	.string "Oh, du solltest prüfen, ob dein Schreib-\n"
	.string "tisch vollständig eingeräumt ist!$"

UnknownString_8172F31: @ 8172F31
	.string "Im Regal stehen Bücher über POKéMON.\n"
	.string "Das ist die wertvolle Sammlung\l"
	.string "von {PLAYER}.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER} schaltet den PC ein.$"

LittlerootTown_BrendansHouse_2F_Text_172F9A:: @ 8172F9A
	.string "{PLAYER} schlägt das Notizbuch auf.\p"
	.string "REGEL NR. 1 FÜR ABENTEURER\n"
	.string "Öffne das MENÜ mit START.\p"
	.string "REGEL NR. 2 FÜR ABENTEURER\n"
	.string "Speichere den Fortschritt mit SICHERN.\p"
	.string "Die übrigen Seiten sind leer.$"

UnknownString_817303D: @ 817303D
	.string "{PLAYER} schaut sich die Karte der\n"
	.string "HOENN-Region genauer an.$"

LittlerootTown_BrendansHouse_2F_Text_17306C:: @ 817306C
	.string "Das ist ein Nintendo GameCube.\p"
	.string "Ein Game Boy Advance ist angeschlossen\n"
	.string "und dient als Controller.$"
