MauvilleCity_PokemonCenter_1F_Text_1825BD:: @ 81825BD
	.string "Der Mann dort drüben, der sagt\n"
	.string "vielleicht verrückte Dinge!\p"
	.string "Auf seltsame Weise ist er aber amüsant.\n"
	.string "Den werde ich wohl nicht vergessen!$"

MauvilleCity_PokemonCenter_1F_Text_182622:: @ 8182622
	.string "Wenn ich auf STATISTIKTAUSCH Zugriff\n"
	.string "nehme, werden die neuesten Nachrichten\l"
	.string "aus FAUSTAUHAVEN hochgeladen.\p"
	.string "Diese Daten decken sich nun mit denen\n"
	.string "meines Freundes!$"

MauvilleCity_PokemonCenter_1F_Text_1826A6:: @ 81826A6
	.string "Im oberen Stockwerk des POKéMON-\n"
	.string "CENTERS wurde die Möglichkeit des\l"
	.string "STATISTIKTAUSCHES eingerichtet.\p"
	.string "Ich weiß nicht genau, was das ist. Aber\n"
	.string "das werde ich herausfinden! Ist\l"
	.string "bestimmt lustig!$"
