MauvilleCity_Gym_Text_180815:: @ 8180815
	.string "Hey, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "WALTER, der ARENALEITER von\n"
	.string "MALVENFROH CITY, setzt\l"
	.string "ELEKTRO-POKéMON ein.\p"
	.string "Wenn du ihn mit WASSER-POKéMON\n"
	.string "angreifst, macht er sie fertig! Britzel!\p"
	.string "Und die Türen lassen sich nur mit\n"
	.string "Schaltern öffnen! Wahnsinn!\p"
	.string "Nun, dann mal los!$"

MauvilleCity_Gym_Text_18091D:: @ 818091D
	.string "Aah, du bist elektrifizierend!\n"
	.string "Du hast die Tür offen gezwungen!$"

MauvilleCity_Gym_Text_180956:: @ 8180956
	.string "Die Spannung meiner Seele, sie setzt\n"
	.string "alle deine Träume unter Strom! Ja-haha!$"

MauvilleCity_Gym_Text_180997:: @ 8180997
	.string "Da wurde der Stromkreis geschlossen\n"
	.string "und bis zum Kurzschluss belastet!$"

MauvilleCity_Gym_Text_1809D1:: @ 81809D1
	.string "POKéMON und Rock... Alles, was ins Herz\n"
	.string "trifft, boh yeah!$"

MauvilleCity_Gym_Text_180A05:: @ 8180A05
	.string "Ich habe unter WALTER trainiert!\n"
	.string "So einfach verliere ich nicht.$"

MauvilleCity_Gym_Text_180A42:: @ 8180A42
	.string "Stecker raus und ausgeschaltet...$"

MauvilleCity_Gym_Text_180A5E:: @ 8180A5E
	.string "WALTER, unser ARENALEITER, ist schon\n"
	.string "sehr sehr lange hier ansässig.\p"
	.string "Er kämpfte schon, da war dein Vater\n"
	.string "noch nicht geboren.$"

MauvilleCity_Gym_Text_180AE0:: @ 8180AE0
	.string "Diese ARENA stellt dir eine Knobel-\n"
	.string "aufgabe. Ist das nicht lustig?$"

MauvilleCity_Gym_Text_180B06:: @ 8180B06
	.string "Verlieren ist gar nicht lustig...$"

MauvilleCity_Gym_Text_180B1D:: @ 8180B1D
	.string "WALTER sagt, er liebt es, Fallen mit\n"
	.string "Schaltern zu installieren.$"

MauvilleCity_Gym_Text_180B5A:: @ 8180B5A
	.string "Mein Charme und die Attacken meiner\n"
	.string "POKéMON werden dich schocken!$"

MauvilleCity_Gym_Text_180B93:: @ 8180B93
	.string "Ich bin geschockt von deiner Stärke!$"

MauvilleCity_Gym_Text_180BAE:: @ 8180BAE
	.string "Ich habe gehört, dass MALVENFROH CITY\n"
	.string "von WALTER gegründet wurde.\p"
	.string "Er war TRAINER, lange bevor wir geboren\n"
	.string "wurden. Er muss ein umfangreiches\l"
	.string "Wissen besitzen.$"

MauvilleCity_Gym_Text_180C32:: @ 8180C32
	.string "Ich habe es aufgegeben, die Stadt\n"
	.string "umpolen zu wollen.\p"
	.string "Stattdessen verwende ich meine Energie\n"
	.string "lieber auf das Installieren von Fallen in\l"
	.string "meiner Arena.\p"
	.string "Oh? Was machst du denn hier?\p"
	.string "Was ist das? Du hast es geschafft, alle\n"
	.string "meine Schalter zu finden?\p"
	.string "Uahahahaha!\n"
	.string "Das ist wirklich amüsant!\p"
	.string "Dann ist es nun an mir - dem\n"
	.string "ARENALEITER von MALVENFROH CITY\l"
	.string "- dich unter Spannung zu setzen!$"

MauvilleCity_Gym_Text_180D64:: @ 8180D64
	.string "Uahahahaha!\n"
	.string "Schön, ich habe verloren!\p"
	.string "Du hast es geschafft, meinen Strom-\n"
	.string "kreis zu unterbrechen! Nimm diesen\l"
	.string "ORDEN!$"

MauvilleCity_Gym_Text_180DAF:: @ 8180DAF
	.string "{PLAYER} hat den DYNAMO-ORDEN von\n"
	.string "WALTER erhalten.$"

MauvilleCity_Gym_Text_180DDA:: @ 8180DDA
	.string "Mit dem DYNAMO-ORDEN können POKéMON\n"
	.string "ZERTRÜMMERER auch außerhalb eines\l"
	.string "Kampfes einsetzen.\p"
	.string "Und außerdem werden deine POKéMON ein\n"
	.string "kleines bisschen schneller.\p"
	.string "Hmm...\n"
	.string "Dies hier solltest du auch nehmen!$"

MauvilleCity_Gym_Text_180E76:: @ 8180E76
	.string "Dies ist TM34 - SCHOCKWELLE.\p"
	.string "Eine verlässliche Attacke, die niemals\n"
	.string "daneben geht! Verlass dich drauf!$"

MauvilleCity_Gym_Text_180EDB:: @ 8180EDB
	.string "Optimismus erfüllt mich, wenn ich einen\n"
	.string "so viel versprechenden TRAINER wie dich\l"
	.string "sehe!$"

MauvilleCity_Gym_Text_180F1D:: @ 8180F1D
	.string "Ahahahaha!\n"
	.string "Mach weiter so, streng dich an, Kind!$"

MauvilleCity_Gym_Text_180F4A:: @ 8180F4A
	.string "POKéMON ARENA von MALVENFROH CITY$"

MauvilleCity_Gym_Text_180F64:: @ 8180F64
	.string "POKéMON ARENA von MALVENFROH CITY\p"
	.string "WALTERS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
