MossdeepCity_House4_Text_18E0E3:: @ 818E0E3
	.string "Mein kleiner Bruder liebt es, die GEHEIM-\n"
	.string "BASEN der anderen zu finden.$"

MossdeepCity_House4_Text_18E125:: @ 818E125
	.string "Mein kleiner Bruder sagt, er liebt es, die\n"
	.string "GEHEIMBASEN der anderen zu finden und\l"
	.string "Kämpfe mit POKéMON auszutragen.$"

MossdeepCity_House4_Text_18E17E:: @ 818E17E
	.string "Hast du dir eine GEHEIMBASIS in\n"
	.string "{STR_VAR_1} eingerichtet?$"

MossdeepCity_House4_Text_18E1A7:: @ 818E1A7
	.string "Solltest du dir irgendwo eine GEHEIM-\n"
	.string "BASIS einrichten, werde ich sie sicher\l"
	.string "finden.$"

MossdeepCity_House4_Text_18E1E1:: @ 818E1E1
	.string "ENEKORO: Miyaan?$"
