MtPyre_5F_Text_196939:: @ 8196939
	.string "Ich mag gruselige Horrordinge...\n"
	.string "Es ist wie eine Sucht...\p"
	.string "Sobald ich hier bin...\n"
	.string "Stehen mir die Haare zu Berge.$"

MtPyre_5F_Text_196997:: @ 8196997
	.string "Ich hasse Niederlagen...$"

MtPyre_5F_Text_1969AC:: @ 81969AC
	.string "Ich will unheimliche Dinge sehen...\n"
	.string "Ich kann nicht weggehen...\p"
	.string "Muss bleiben...\n"
	.string "Willst du nicht bei mir bleiben?$"
