OldaleTown_Text_16AEC0:: @ 816AEC0
	.string "Ich möchte eine Pause einlegen, daher\n"
	.string "speichere ich mein Spiel.$"

OldaleTown_Text_16AEF2:: @ 816AEF2
	.string "Hi!\n"
	.string "Ich arbeite in einem PKMN-SUPERMARKT.\p"
	.string "Kommst du bitte einmal mit mir?$"

OldaleTown_Text_16AF2F:: @ 816AF2F
	.string "Dies ist ein PKMN-SUPERMARKT.\n"
	.string "Er ist an dem blauen Dach erkennbar.\p"
	.string "Wir verkaufen eine Menge nützlicher\n"
	.string "Dinge, wie POKéBÄLLE, mit denen man\l"
	.string "POKéMON fängt.\p"
	.string "Hier, dies ist ein Item, quasi als Werbe-\n"
	.string "geschenk für dich.$"

OldaleTown_Text_16AFE1:: @ 816AFE1
	.string "Ein TRANK kann zu jeder Zeit eingesetzt\n"
	.string "werden, daher ist er in manchen\l"
	.string "Situationen wertvoller als ein POKéMON-\l"
	.string "CENTER.$"

OldaleTown_Text_16B045:: @ 816B045
	.string "Aaaah! Warte!\n"
	.string "Bitte nicht dort entlang laufen!\p"
	.string "Ich habe dort die Fußspuren eines\n"
	.string "seltenen POKéMON gesehen!\p"
	.string "Warte bis ich fertig bin, sie\n"
	.string "abzuzeichnen, okay?$"

OldaleTown_Text_16B0CC:: @ 816B0CC
	.string "Ich habe dort die Fußspuren eines\n"
	.string "seltenen POKéMON gesehen!\p"
	.string "Warte, bis ich fertig bin, sie\n"
	.string "abzuzeichnen, okay?$"

OldaleTown_Text_16B12A:: @ 816B12A
	.string "Ich habe die Fußspuren eines seltenen\n"
	.string "POKéMON abgezeichnet.\p"
	.string "Aber hinterher habe ich festgestellt,\n"
	.string "dass es meine eigenen Spuren waren...$"

OldaleTown_Text_16B196:: @ 816B196
	.string "MAIKE: {PLAYER}{KUN}!\n"
	.string "Hier entlang!\l"
	.string "Lass uns nach Hause gehen!$"

OldaleTown_Text_16B1BE:: @ 816B1BE
	.string "BRIX: Ich gehe nun in das LABOR\n"
	.string "meines Vaters.\l"
	.string "{PLAYER}, du solltest auch zurücklaufen.$"

OldaleTown_Text_16B20E:: @ 816B20E
	.string "ROSALTSTADT\n"
	.string "“Wo Dinge selten ihren Anfang nehmen.”$"
