PacifidlogTown_House2_Text_1790C1:: @ 81790C1
	.string "Ähhäm!\p"
	.string "Ich bin die wichtigste Person des\n"
	.string "POKéMON-FANCLUBS, ich bin der kleine\l"
	.string "Bruder des VORSITZENDEN.\p"
	.string "Ich genieße hier die Ferien mit meinen\n"
	.string "POKéMON. Ja, das tue ich.$"

PacifidlogTown_House2_Text_179155:: @ 8179155
	.string "Ah!\n"
	.string "Dein POKéMON...$"

PacifidlogTown_House2_Text_179169:: @ 8179169
	.string "Es mag dich offensichtlich sehr.\p"
	.string "Ein derart liebevolles und wunderbares\n"
	.string "POKéMON verdient eine TM wie diese!$"

PacifidlogTown_House2_Text_1791CA:: @ 81791CA
	.string "Hmm...\n"
	.string "Nicht schlecht... Aber auch nicht gut.\p"
	.string "Du musst dich als TRAINER mehr\n"
	.string "anstrengen.$"

PacifidlogTown_House2_Text_17922D:: @ 817922D
	.string "Es hat einen bösartigen Blick.\p"
	.string "Ein Furcht erregendes POKéMON wie\n"
	.string "dieses verdient eine TM wie diese!$"

PacifidlogTown_House2_Text_179283:: @ 8179283
	.string "Wenn ein POKéMON dich sehr mag, wird die\n"
	.string "Kraft von RÜCKKEHR verstärkt.\p"
	.string "Wenn es dich nicht mag, wird die Kraft\n"
	.string "von FRUSTRATION verstärkt.$"

PacifidlogTown_House2_Text_1792F2:: @ 81792F2
	.string "Oh, ja. In {STR_VAR_1} Tag/en müsste\n"
	.string "ich eine gute TM bekommen haben.\p"
	.string "Komm doch dann wieder vorbei.\n"
	.string "Ich werde dir dann eine TM geben, die\l"
	.string "wunderbar zu deinem POKéMON passt.$"

PacifidlogTown_House2_Text_17938B:: @ 817938B
	.string "AZURILL: Rurii.$"

PacifidlogTown_House2_Text_17939B:: @ 817939B
	.string "Es scheint freundschaftlich mit dem\n"
	.string "TRAINER umzugehen.$"

PacifidlogTown_House2_Text_1793CC:: @ 81793CC
	.string "AZURILL: Rururi!$"

PacifidlogTown_House2_Text_1793DD:: @ 81793DD
	.string "Es scheint den TRAINER nicht\n"
	.string "sonderlich zu mögen.$"
