PacifidlogTown_House5_Text_179718:: @ 8179718
	.string "Ich kann WUNDEREILAND heute\n"
	.string "nicht sehen...$"

PacifidlogTown_House5_Text_17973B:: @ 817973B
	.string "Oh! Oh! Heute kann ich WUNDEREILAND\n"
	.string "sehen!$"

PacifidlogTown_House5_Text_179765:: @ 8179765
	.string "WUNDEREILAND...\p"
	.string "Die Insel ist sichtbar oder nicht\n"
	.string "sichtbar. Das hängt vom Wetter ab, das\l"
	.string "Fata Morganen möglich macht oder nicht.\p"
	.string "Oder verschwindet die Insel tatsächlich\n"
	.string "manchmal?$"
