PetalburgCity_Text_16433E:: @ 816433E
	.string "Wohin ist unser HEIKO nur gegangen?\p"
	.string "Wir müssen doch bald nach WIESENFLUR\n"
	.string "aufbrechen...$"

PetalburgCity_Text_16438A:: @ 816438A
	.string "He da! Bist du vielleicht...\n"
	.string "Ein Anfänger unter den TRAINERN?\p"
	.string "Weißt du, was POKéMON-TRAINER machen,\n"
	.string "wenn sie in einen neuen Ort kommen?\p"
	.string "Sie sehen sich als Erstes die ARENA\n"
	.string "im Ort an.$"

PetalburgCity_Text_164426:: @ 8164426
	.string "Schau. Das ist die ARENA von\n"
	.string "BLÜTENBURG CITY.$"

PetalburgCity_Text_164449:: @ 8164449
	.string "Das ist das Logo der ARENA. Daran\n"
	.string "kannst du immer eine ARENA erkennen.$"

PetalburgCity_Text_164490:: @ 8164490
	.string "Mein Gesicht spiegelt sich im Wasser...\p"
	.string "Ein schimmerndes Lächeln der Hoffnung.\p"
	.string "Oder ist es der Ausdruck düsterer\n"
	.string "Stille, an der die Angst nagt...\p"
	.string "Was siehst du in deinem Spiegelbild?$"

PetalburgCity_Text_16453F:: @ 816453F
	.string "Nehmen wir an, du hättest 6 POKéMON.\n"
	.string "Wenn du jetzt ein weiteres fängst...\p"
	.string "wird es automatisch in das POKéMON-\n"
	.string "LAGERUNGS-SYSTEM gesendet.$"

PetalburgCity_Text_1645BB:: @ 81645BB
	.string "POKéMON ARENA von BLÜTENBURG CITY\n"
	.string "LEITER: NORMAN\l"
	.string "“Ein Mann, der nach Stärke strebt!”$"

PetalburgCity_Text_164602:: @ 8164602
	.string "BLÜTENBURG CITY\n"
	.string "“Wo Menschen Hand in Hand\l"
	.string "mit der Natur gehen.”$"

PetalburgCity_Text_164634:: @ 8164634
	.string "HEIKOS HAUS$"
