Route117_Text_170C26:: @ 8170C26
	.string "Ich habe mein POKéMON in der PENSION\n"
	.string "abgegeben.\p"
	.string "Als ich es wieder abholte, kannte es\n"
	.string "eine Attacke, die ich ihm nicht beige-\l"
	.string "bracht habe. Ich war total überrascht.$"

Route117_Text_170CA7:: @ 8170CA7
	.string "Was meinst du?\n"
	.string "Sind diese Blumen nicht wunderhübsch?\p"
	.string "Ich habe sie alle selber gepflanzt.$"

Route117_Text_170CEB:: @ 8170CEB
	.string "Die Luft hier ist wunderbar frisch.$"

Route117_Text_170D02:: @ 8170D02
	.string "ROUTE 117\n"
	.string "{LEFT_ARROW} WIESENFLUR$"

Route117_Text_170D1E:: @ 8170D1E
	.string "ROUTE 117\n"
	.string "{RIGHT_ARROW} MALVENFROH CITY$"

Route117_Text_170D38:: @ 8170D38
	.string "POKéMON-PENSION\n"
	.string "“Lass uns deine POKéMON aufziehen.”$"
