Route112_Text_16FDF0:: @ 816FDF0
	.string "Grummel...\p"
	.string "Wo bleiben nur die anderen, die in LAUB-\n"
	.string "WECHSELFELD waren? Sie sind spät dran.$"

Route112_Text_16FE3E:: @ 816FE3E
	.string "Grummel...\p"
	.string "Ich möchte auch mit der SEILBAHN nach\n"
	.string "oben auf den Gipfel fahren...$"

Route112_Text_16FE7A:: @ 816FE7A
	.string "Ich würde gerne nach MALVENFROH CITY,\n"
	.string "aber wenn ich diese Stufen hinunter-\p"
	.string "gehe, komme ich kaum wieder nach\n"
	.string "BAD LAVASTADT.$"

Route112_Text_16FEED:: @ 816FEED
	.string "SEILBAHN ZUM SCHLOTBERG\n"
	.string "“Ein kurzer Weg nach {UP_ARROW}!”$"

Route112_Text_16FF19:: @ 816FF19
	.string "SCHLOTBERG\p"
	.string "“BAD LAVASTADT oder den Gipfel\n"
	.string "erreichen Sie mit der SEILBAHN.”$"

Route112_Text_16FF64:: @ 816FF64
	.string "ROUTE 112\n"
	.string "{LEFT_ARROW} BAD LAVASTADT$"
