Route128_Text_171EE0:: @ 8171EE0
	.string "{EVIL_LEADER}: Was ist passiert... Was für\n"
	.string "ein Furcht erregendes Szenario...\p"
	.string "Habe ich... einen schrecklichen Fehler\n"
	.string "begangen?$"

Route128_Text_171F35:: @ 8171F35
	.string "Ich...\n"
	.string "Ich wollte doch nur...$"

Route128_Text_171F4B:: @ 8171F4B
	.string "{GOOD_LEADER}: Begreifst du es nun,\n"
	.string "{EVIL_LEADER}?\p"
	.string "Begreifst du nun die schrecklichen\n"
	.string "Folgen deines katastrophalen Traums?\p"
	.string "Wir müssen uns beeilen! Wir müssen etwas\n"
	.string "unternehmen, bevor die Situation völlig\l"
	.string "außer Kontrolle gerät!$"

Route128_Text_172008:: @ 8172008
	.string "{GOOD_LEADER}: {PLAYER}{KUN}...\p"
	.string "Wir, TEAM {GOOD_TEAM}, verfolgen TEAM {EVIL_TEAM}\n"
	.string "schon lange, weil wir dies verhindern\l"
	.string "wollten.\p"
	.string "Du warst uns eine große Hilfe, aber ich\n"
	.string "fürchte, das Schlimmste ist passiert...\p"
	.string "Für ein Kind wie dich ist die Sache viel\n"
	.string "zu weit gegangen...\p"
	.string "Überlass die Sache uns und lauf weg,\n"
	.string "solange es noch geht!$"

Route128_Text_17210B:: @ 817210B
	.string "{GOOD_LEADER}: Das ist ja unglaublich...\p"
	.string "Ein super-antikes POKéMON...\p"
	.string "Seine Kraft ist unglaublich. Es hat\n"
	.string "das Gleichgewicht der Natur verändert.$"

Route128_Text_172181:: @ 8172181
	.string "TROY: {PLAYER}{KUN}!\n"
	.string "Was geht hier vor?$"

Route128_Text_1721A2:: @ 81721A2
	.string "Das ist schrecklich...\p"
	.string "Wenn das nicht aufhört, wird ganz\n"
	.string "HOENN... Nein, die ganze Welt wird\l"
	.string "untergehen.\p"
	.string "Diese riesige Regenwolke kommt\n"
	.string "aus Richtung XENEROVILLE?\p"
	.string "Was um Himmels Willen geht dort vor?\p"
	.string "Es bleibt keine Zeit für Spekulationen...\n"
	.string "In XENEROVILLE erfahren wir mehr...$"

Route128_Text_1722A1:: @ 81722A1
	.string "Das ist schrecklich...\p"
	.string "Wenn das nicht aufhört, wird ganz\n"
	.string "HOENN... Nein, die ganze Welt wird\l"
	.string "vertrocknen.\p"
	.string "Die strahlende Sonne steht über\n"
	.string "XENEROVILLE?\p"
	.string "Was um Himmels Willen geht dort vor?\p"
	.string "Es bleibt keine Zeit für Spekulationen...\n"
	.string "In XENEROVILLE erfahren wir mehr...$"

Route128_Text_1723BE:: @ 81723BE
	.string "{PLAYER}{KUN}...\n"
	.string "Ich weiß nicht, was du vorhast, aber tue\l"
	.string "nichts Unüberlegtes.\p"
	.string "Okay.\n"
	.string "Ich gehe nach XENEROVILLE.$"
