Route104_Text_16DA13:: @ 816DA13
	.string "In dieser Hütte am Meer lebt MR. BRACK.\p"
	.string "Er war einst ein stolzer Seemann, der\n"
	.string "niemals Angst vor dem Meer hatte.$"

Route104_Text_16DA89:: @ 816DA89
	.string "Das Meer, was?\p"
	.string "Ich möchte zu gerne wissen, wie es auf\n"
	.string "dem Meeresgrund aussieht...$"

Route104_Text_16DAC9:: @ 816DAC9
	.string "Bevor du einen POKéBALL wirfst,\n"
	.string "schwäche das POKéMON erst.\p"
	.string "Wenn es vergiftet ist, eine Verbrennung\n"
	.string "hat oder schläft, kann es leichter\l"
	.string "gefangen werden.$"

Route104_Text_16DB5C:: @ 816DB5C
	.string "Du bist ein gemeiner Dieb, wenn du ver-\n"
	.string "suchst, das POKéMON eines anderen zu\l"
	.string "stehlen.\p"
	.string "Du solltest deine POKéBÄLLE nur auf\n"
	.string "wilde POKéMON werfen.$"

Route104_Text_16DBC9:: @ 816DBC9
	.string "Oh, nein, ich bin kein TRAINER.\p"
	.string "Aber es stimmt schon, wenn TRAINER sich\n"
	.string "in die Augen schauen, ist das eine\l"
	.string "Herausforderung zum Kampf.\p"
	.string "Willst du nicht kämpfen, weiche ihren\n"
	.string "Blicken aus.$"

Route104_Text_16DC5F:: @ 816DC5F
	.string "Ich liebe es, meinen Mund voller\n"
	.string "Saatkörner zu nehmen und sie dann in\l"
	.string "hohem Bogen auszuspucken.\p"
	.string "Du kannst dies hier haben, versuch es\n"
	.string "einfach mal!\p"
	.string "Wende es an einem POKéMON an und es\n"
	.string "wird lernen, in schneller Folge\l"
	.string "Saatkörner auszuspucken.$"

Route104_Text_16DD0E:: @ 816DD0E
	.string "Ein Hinweis noch!\p"
	.string "Eine TM, eine TECHNISCHE MASCHINE,\n"
	.string "kann nur einmal beigebracht werden.\p"
	.string "Einmal verwendet, ist sie weg. Denke\n"
	.string "zweimal nach, bevor du eine TM nutzt.$"

Route104_Text_16DD91:: @ 816DD91
	.string "Der BLUMENLADEN verkauft seit kurzem\n"
	.string "junge Bäume.\p"
	.string "Das macht mich so glücklich, dass ich\n"
	.string "ganz viele gekauft habe. Dieses SCHLOH-\l"
	.string "KRAUT brauche ich nicht, das schenke\l"
	.string "ich dir.$"

Route104_Text_16DE36:: @ 816DE36
	.string "Der BLUMENLADEN verkauft seit kurzem\n"
	.string "junge Bäume.\p"
	.string "Das macht mich so glücklich, dass ich\n"
	.string "ganz viele gekauft habe. Wohin damit?$"

Route104_Text_16DEB3:: @ 816DEB3
	.string "MR. BRACKS HÜTTE$"

Route104_Text_16DEC8:: @ 816DEC8
	.string "ROUTE 104\n"
	.string "{RIGHT_ARROW} BLÜTENBURG CITY$"

Route104_Text_16DEE3:: @ 816DEE3
	.string "ROUTE 104\n"
	.string "{UP_ARROW} METAROST CITY$"

Route104_Text_16DEFD:: @ 816DEFD
	.string "BLÜTENTRAUM BLUMENLADEN$"

Route104_Text_16DF16:: @ 816DF16
	.string "TIPPS für TRAINER\p"
	.string "In der HOENN-Region gibt es Paare von\n"
	.string "TRAINERN, die andere zu einem\l"
	.string "2-gegen-2 POKéMON-Kampf, einem\l"
	.string "DOPPELKAMPF, herausfordern.\p"
	.string "In einem DOPPELKAMPF muss der TRAINER\n"
	.string "zwei POKéMON antreten lassen. Das \l"
	.string "POKéMON links neben der Liste und das\l"
	.string "an der Spitze der Liste. Achte also auf\l"
	.string "die Reihenfolge der POKéMON.$"
