Route123_Text_171D83:: @ 8171D83
	.string "Ich liebe PFLANZEN-POKéMON!\p"
	.string "Hast du einige PFLANZEN-POKéMON?$"

Route123_Text_171DC2:: @ 8171DC2
	.string "Oh?\p"
	.string "Du magst PFLANZEN-POKéMON auch sehr\n"
	.string "gerne, habe ich Recht?\p"
	.string "Das freut mich sehr. Ich schenke dir \n"
	.string "ein Zeichen unserer Freundschaft.$"

Route123_Text_171E34:: @ 8171E34
	.string "Ich prüfe die Bäume mit Hilfe meiner\n"
	.string "PFLANZEN-POKéMON. Ich bin so etwas wie\l"
	.string "ein Baumdoktor.$"

Route123_Text_171E76:: @ 8171E76
	.string "{RIGHT_ARROW} ROUTE 123\n"
	.string "{LEFT_ARROW} ROUTE 118$"

Route123_Text_171E8E:: @ 8171E8E
	.string "{UP_ARROW} PYROBERG\n"
	.string "“Für Zaghafte verboten.”$"

Route123_Text_171EBC:: @ 8171EBC
	.string "VILLA DES BEERENMEISTERS$"
