Route110_TrickHouseEntrance_Text_19BA56:: @ 819BA56
	.string "Du wirst beobachtet...$"

Route110_TrickHouseEntrance_Text_19BA6E:: @ 819BA6E
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich unter\n"
	.string "dem Tisch versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BAC0:: @ 819BAC0
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich hinter\n"
	.string "dem Baum versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BB11:: @ 819BB11
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich in\n"
	.string "der Kommode versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BB61:: @ 819BB61
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich über\n"
	.string "dem Fenster versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BBB4:: @ 819BBB4
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich in\n"
	.string "der Pflanze versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BC04:: @ 819BC04
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich\n"
	.string "im Schrank versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BC55:: @ 819BC55
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich hinter\n"
	.string "dem Fenster versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BCA8:: @ 819BCA8
	.string "Was? Grrrr...\p"
	.string "Woher wusstest du, dass ich mich unter\n"
	.string "dem Kissen versteckt hatte? Clever!$"

Route110_TrickHouseEntrance_Text_19BCFD:: @ 819BCFD
	.string "Sehe und staune!\p"
	.string "Ich bin das größte lebende menschliche\n"
	.string "Mysterium in ganz HOENN!\l"
	.string "Man nennt mich...\p"
	.string "RÄTSELMEISTER!\n"
	.string "Hahaha! Erfreut dich kennen zu lernen!$"

Route110_TrickHouseEntrance_Text_19BD82:: @ 819BD82
	.string "Du, du bist hier, um mein RÄTSELHAUS\n"
	.string "herauszufordern, oder?\p"
	.string "Deshalb bist du doch hier?\n"
	.string "Ja, ja, so muss es sein!\p"
	.string "Betrachte deine Herausforderung als\n"
	.string "angenommen!\p"
	.string "Trete hinter diese Schriftrolle und\n"
	.string "die Herausforderung beginnt!\p"
	.string "Ich warte im hinteren Bereich!$"

Route110_TrickHouseEntrance_Text_19BE6E:: @ 819BE6E
	.string "Das ist eine Schriftrolle.$"

Route110_TrickHouseEntrance_Text_19BE7D:: @ 819BE7D
	.string "Hinter der Schriftrolle ist ein Loch!\p"
	.string "Möchtest du hindurchgehen?$"

Route110_TrickHouseEntrance_Text_19BEB3:: @ 819BEB3
	.string "Auf der Schriftrolle steht etwas...\p"
	.string "“Ich bin auf eine Reise gegangen.\n"
	.string "Sucht mich nicht. RÄTSELMEISTER”$"

Route110_TrickHouseEntrance_Text_19BF19:: @ 819BF19
	.string "Nächstes Mal nehme ich diesen Trick,\n"
	.string "nach diesem Schema und mit List und...\p"
	.string "Ähähähä... Ich muss sagen, ich habe mich\n"
	.string "in meiner Brillanz mal wieder selbst\l"
	.string "übertroffen!$"

Route110_TrickHouseEntrance_Text_19BFAB:: @ 819BFAB
	.string "Hah! Was???\n"
	.string "Ach, du bist das!\p"
	.string "Ich bin gerade dabei, mir neue Tricks\n"
	.string "und Herausforderungen auszudenken!\p"
	.string "Es ist doch nicht zu viel verlangt, mir\n"
	.string "noch etwas Zeit zum Nachdenken zu\l"
	.string "geben, oder? Das ist mir doch gegönnt,\l"
	.string "oder? Danke. Komm später wieder!$"

Route110_TrickHouseEntrance_Text_19C07E:: @ 819C07E
	.string "Ah, du bist es! Du willst dir deine\n"
	.string "Belohnung von eben abholen, habe ich\l"
	.string "Recht? Natürlich habe ich Recht!\p"
	.string "Hier!\n"
	.string "Das ist für dich!$"

Route110_TrickHouseEntrance_Text_19C0FC:: @ 819C0FC
	.string "Was? Du kommst nicht, um deine\n"
	.string "Belohnung abzuholen?$"

Route110_TrickHouseEntrance_Text_19C128:: @ 819C128
	.string "ROBOPUPPE 5 BIN ICH!\n"
	.string "HOLST DU DIE BELOHNUNG NICHT AB,\l"
	.string "DANN KANNST DU RÄTSELMEISTER NICHT\l"
	.string "FOLGEN!$"

Route110_TrickHouseEntrance_Text_19C17E:: @ 819C17E
	.string "DANN LEBE WOHL.$"

Route110_TrickHouseEntrance_Text_19C18D:: @ 819C18D
	.string "PC-STATUS: WIEDER VOLL.\n"
	.string "GEMEIN DU BIST.$"
