Route116_TunnelersRestHouse_Text_192F33:: @ 8192F33
	.string "Der METAFLURTUNNEL...\p"
	.string "Zunächst hatten wir ein großes Team,\n"
	.string "das mit schweren Maschinen durch den\l"
	.string "Felsen brechen sollte. Dann mussten wir\l"
	.string "die Arbeit stoppen.\p"
	.string "Es stellte sich heraus, dass sich unsere\n"
	.string "Arbeit negativ auf die wilden\l"
	.string "POKéMON in dieser Gegend auswirkte.\p"
	.string "Und daher haben wir nun nichts mehr zu\n"
	.string "tun, außer hier faul herumzuhängen.$"

Route116_TunnelersRestHouse_Text_193049:: @ 8193049
	.string "Da ist ein Mann, der sich ganz alleine\n"
	.string "seinen Weg nach WIESENFLUR gräbt. Er\l"
	.string "versucht verzweifelt durchzukommen.\p"
	.string "Er sagt, wenn er Schritt für Schritt\n"
	.string "ohne laute Maschinen gräbt, werden die\l"
	.string "POKéMON nicht gestört und ihr natür-\l"
	.string "licher Lebensraum bleibt erhalten.$"

Route116_TunnelersRestHouse_Text_193135:: @ 8193135
	.string "Um ohne diesen Tunnel nach WIESENFLUR\n"
	.string "zu kommen, muss man das Meer bei\p"
	.string "FAUSTAUHAVEN überqueren, nach\n"
	.string "GRAPHITPORT CITY segeln und durch\l"
	.string "MALVENFROH CITY reisen.$"

Route116_TunnelersRestHouse_Text_1931C1:: @ 81931C1
	.string "Hast du schon gehört!?! Der TUNNEL bei\n"
	.string "WIESENFLUR ist fertig!\p"
	.string "Wenn man nur fest an seine Träume\n"
	.string "glaubt, werden sie irgendwann wahr.$"
