DewfordTown_Text_16E080:: @ 816E080
	.string "MR. BRACK: Ahoi!\n"
	.string "Wir haben in GRAPHITPORT CITY angelegt.\p"
	.string "Ich vermute, du gehst jetzt zu KAPT.\n"
	.string "BRIGG und bringst ihm die DEVON-\l"
	.string "WAREN?$"

Route109_Text_16E0F9:: @ 816E0F9
	.string "MR. BRACK: Überbringst du nicht die\n"
	.string "DEVON-WAREN?\p"
	.string "Heißt das, du willst nach FAUSTAUHAVEN\n"
	.string "zurücksegeln?$"

Route109_Text_16E159:: @ 816E159
	.string "MR. BRACK: Also, auf nach FAUSTAUHAVEN!\p"
	.string "Anker gelichtet!\n"
	.string "PECKO, wir setzen Segel, mein Liebling!$"

Route109_Text_16E1B1:: @ 816E1B1
	.string "MR. BRACK: Dann geh und überbringe die\n"
	.string "DEVON-WAREN. Ich warte hier.$"

DewfordTown_Text_16E1FA:: @ 816E1FA
	.string "MR. BRACK: Ahoi! Wir haben in\n"
	.string "GRAPHITPORT CITY angelegt!\p"
	.string "Wann immer du magst, können wir wieder\n"
	.string "die Segel setzen.$"

Route109_Text_16E26A:: @ 816E26A
	.string "MR. BRACK: Ahoi! Für dich fahre ich\n"
	.string "jederzeit wieder raus!\p"
	.string "Nun, wo soll es hingehen?$"

Route109_Text_16E2C5:: @ 816E2C5
	.string "MR. BRACK: Sag mir einfach Bescheid,\n"
	.string "wenn wir wieder Segel setzen sollen.$"

Route109_Text_16E307:: @ 816E307
	.string "Yo, TRAINER!\n"
	.string "Seid ihr in Eile,\l"
	.string "müsst wieder fort,\l"
	.string "erfrischt euch doch an Papas Ort!$"

Route109_Text_16E35B:: @ 816E35B
	.string "Kleine Kinder sind blitzschnell und flink.\p"
	.string "Du darfst sie nicht eine Sekunde aus\n"
	.string "den Augen lassen. Das strengt an.\p"
	.string "Meine Kinder sind mit meinen POKéMON\n"
	.string "zusammen, da sind sie gut aufgehoben.$"

Route109_Text_16E405:: @ 816E405
	.string "Wir brauchen ganz lange, um unsere\n"
	.string "Sandburg zu bauen.$"

Route109_Text_16E433:: @ 816E433
	.string "Das schenk ich dir!$"

Route109_Text_16E446:: @ 816E446
	.string "Wir nehmen allen Sand vom Strand\n"
	.string "und bauen damit eine gaaanz große Burg.\p"
	.string "Und dann sind wir Königin und König!\p"
	.string "Und du darfst unser Diener sein.$"

Route109_Text_16E4D5:: @ 816E4D5
	.string "Das Wasser in diesen Breiten ist sauber.\p"
	.string "Aber ich sammle zusammen mit meinem\n"
	.string "ZIGZACHS den Müll am Ufer auf.\p"
	.string "Verschmutztes Wasser wird zu Regen und\n"
	.string "gelangt in die Flüsse, aus denen wir\l"
	.string "unser Trinkwasser gewinnen...\p"
	.string "Verschmutzen wir das Meer, bekommen\n"
	.string "wir den Schmutz wieder zurück.$"

Route109_Text_16E5CA:: @ 816E5CA
	.string "ZIGZACHS: Guguu?$"

Route109_Text_16E5DC:: @ 816E5DC
	.string "STRANDHAUS\p"
	.string "“Mögen heiße Kämpfe im heißen Sand\n"
	.string "stattfinden! Heiße TRAINER willkommen!”$"

Route109_Text_16E62C:: @ 816E62C
	.string "TIPPS für TRAINER\p"
	.string "POKéMON mit gleichem Level haben nicht\n"
	.string "unbedingt identische Statuswerte.\p"
	.string "POKéMON, die von TRAINERN aufgezogen\n"
	.string "werden, wachsen schneller als wilde\l"
	.string "POKéMON.$"
