Route101_Text_16D10E:: @ 816D10E
	.string "HI... HIIIILFE!!!$"

Route101_Text_16D119:: @ 816D119
	.string "HILFE!!! Du dort drüben!\n"
	.string "Bitte! HILFE!!!\p"
	.string "In meinem BEUTEL...\n"
	.string "Da findest du einen POKéBALL!$"

Route101_Text_16D15E:: @ 816D15E
	.string "Wo-Wo wi-willst du hin?\n"
	.string "Lass mich nicht im Stich!!!$"

Route101_Text_16D191:: @ 816D191
	.string "PROF. BIRK: Puuuh...\p"
	.string "Ich habe im hohen Gras POKéMON\n"
	.string "studiert, als ich angesprungen wurde.\p"
	.string "Du hast mich gerettet.\n"
	.string "Vielen, vielen Dank!\p"
	.string "Oh?\p"
	.string "Hi, du bist doch {PLAYER}{KUN}!\p"
	.string "Aber dies ist nicht der Ort für ein\n"
	.string "Schwätzchen, komm doch mit \l"
	.string "in mein POKéMON-LABOR, okay?$"

Route101_Text_16D25E:: @ 816D25E
	.string "Sind deine POKéMON müde, bring sie in\n"
	.string "ein POKéMON-CENTER.\p"
	.string "In ROSALTSTADT, gleich hier um die\n"
	.string "Ecke, gibt es ein POKéMON-CENTER.$"

Route101_Text_16D2CB:: @ 816D2CB
	.string "Wilde POKéMON springen dich in hohem\n"
	.string "Gras gerne an.\p"
	.string "Wenn du POKéMON fangen willst, musst\n"
	.string "du ins hohe Gras gehen und sie suchen.$"

Route101_Text_16D349:: @ 816D349
	.string "ROUTE 101\n"
	.string "{UP_ARROW} ROSALTSTADT$"
