Route110_TrickHousePuzzle6_Text_19DC87:: @ 819DC87
	.string "Als ich von dem seltsamen Haus hörte,\n"
	.string "musste ich mir das sofort ansehen.$"

Route110_TrickHousePuzzle6_Text_19DCC6:: @ 819DCC6
	.string "Ich habe einen starken TRAINER\n"
	.string "entdeckt!$"

Route110_TrickHousePuzzle6_Text_19DCE7:: @ 819DCE7
	.string "Es hat viel Spaß gemacht, diesen Ort zu\n"
	.string "erforschen.\p"
	.string "Eine Herausforderung, die ich gerne\n"
	.string "wiederholen möchte!$"

Route110_TrickHousePuzzle6_Text_19DD49:: @ 819DD49
	.string "Vielleicht kann mein VOGEL-POKéMON\n"
	.string "über die Mauer fliegen...$"

Route110_TrickHousePuzzle6_Text_19DD83:: @ 819DD83
	.string "Uaah! Ich hab’s vermasselt!$"

Route110_TrickHousePuzzle6_Text_19DD96:: @ 819DD96
	.string "Hihihihi... Ich habe doch nur verloren,\n"
	.string "weil ich bescheißen wollte.$"

Route110_TrickHousePuzzle6_Text_19DDCF:: @ 819DDCF
	.string "Mir wird ganz schwindelig von diesen\n"
	.string "rotierenden Türen... Huuh...$"

Route110_TrickHousePuzzle6_Text_19DDFE:: @ 819DDFE
	.string "Bei mir dreht sich alles. Mir wird übel.\n"
	.string "Ich kann nicht mehr...$"

Route110_TrickHousePuzzle6_Text_19DE44:: @ 819DE44
	.string "Dir scheint das gar nichts auszumachen.\n"
	.string "Oder ist das nur Show?$"

UnknownString_819DE8D: @ 819DE8D
	.string "{PLAYER} hat den geheimen Code auf die\n"
	.string "Tür geschrieben.\p"
	.string "“RÄTSELMEISTER ist riesig.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das Schloss geht klickend auf.$"
