RustboroCity_Gym_Text_183A4B:: @ 8183A4B
	.string "Hi, wie geht’s?\p"
	.string "Hör zu, mein Freund!\n"
	.string "Würdest du gerne CHAMP werden?\p"
	.string "Ich bin kein TRAINER. Ich nicht. Aber\n"
	.string "ich kann dir trotzdem einen nützlichen\l"
	.string "Rat geben.\p"
	.string "Also, abgemacht! Wir werden zusammen\n"
	.string "nach der POKéMON MEISTERSCHAFT\l"
	.string "streben!\p"
	.string "Als TRAINER musst du die ORDEN der\n"
	.string "ARENEN sammeln, habe ich Recht?\p"
	.string "Aber die ARENALEITER sind nicht gerade\n"
	.string "einfach zu besiegen!\p"
	.string "Und hier komme ich ins Spiel!\n"
	.string "Ich werde dir einen Expertentipp geben!\p"
	.string "FELIZIA, die ARENALEITERIN, setzt\n"
	.string "GESTEINS-POKéMON ein.\p"
	.string "Ein GESTEINS-POKéMON ist sehr zäh,\n"
	.string "hat aber gegen WASSER- und PFLANZEN-\l"
	.string "Attacken keine Chance.\p"
	.string "Komm wieder vorbei, wenn du die ARENA-\n"
	.string "LEITERIN besiegt hast.\p"
	.string "Nun zeig, was du drauf hast!$"

RustboroCity_Gym_Text_183C90:: @ 8183C90
	.string "Hui! Was für ein atemberaubender Sieg!\n"
	.string "Meine Zurufe müssen gewirkt haben!\p"
	.string "Großartig!\n"
	.string "Schau mal auf deinen TRAINERPASS.\p"
	.string "Der STEINORDEN, den du gerade bekommen\n"
	.string "hast, müsste dort schon vermerkt sein.\p"
	.string "Nun hast du den ersten Schritt zur\n"
	.string "MEISTERSCHAFT schon erfolgreich\l"
	.string "hinter dir!\p"
	.string "Ein großartiges Gefühl!$"

RustboroCity_Gym_Text_183D99:: @ 8183D99
	.string "Unterschätze die TRAINER einer ARENA\n"
	.string "nicht! Ich zeige dir, warum wir die\l"
	.string "Besten sind!$"

RustboroCity_Gym_Text_183DDD:: @ 8183DDD
	.string "Du warst viel zu gut für mich...$"

RustboroCity_Gym_Text_183DF9:: @ 8183DF9
	.string "Du hast noch gar nicht gesehen, was\n"
	.string "GESTEINS-POKéMON alles können.$"

RustboroCity_Gym_Text_183E38:: @ 8183E38
	.string "Wenn du mich nicht besiegen kannst,\n"
	.string "hast du keine Chance gegen FELIZIA.$"

RustboroCity_Gym_Text_183E78:: @ 8183E78
	.string "Wow! Du hast wirklich Talent!$"

RustboroCity_Gym_Text_183E98:: @ 8183E98
	.string "FELIZIA ist um ein Vielfaches stärker\n"
	.string "als ich.\p"
	.string "Du solltest dich besser wappnen!$"

RustboroCity_Gym_Text_183EE5:: @ 8183EE5
	.string "Hallo, ich bin FELIZIA, die LEITERIN der\n"
	.string "ARENA von METAROST CITY.\p"
	.string "Ich wurde ARENALEITERIN, um mein\n"
	.string "Wissen, das ich in der POKéMON TRAINER-\l"
	.string "SCHULE erworben habe, umzusetzen.\p"
	.string "Würdest du mir bitte zeigen, wie du\n"
	.string "kämpfst und mit welchen POKéMON?$"

RustboroCity_Gym_Text_183FC4:: @ 8183FC4
	.string "So...\n"
	.string "Ich habe verloren...\p"
	.string "Es scheint, ich muss noch eine ganze\n"
	.string "Menge lernen...\p"
	.string "Ich verstehe schon.\p"
	.string "Die Regeln der POKéMON LIGA schreiben\n"
	.string "vor, dass TRAINER, die einen ARENA-\l"
	.string "LEITER besiegt haben, dieses erhalten.\p"
	.string "Bitte nimm den offiziellen POKéMON LIGA\n"
	.string "STEINORDEN an!$"

RustboroCity_Gym_Text_1840AB:: @ 81840AB
	.string "{PLAYER} hat den STEINORDEN von\n"
	.string "FELIZIA erhalten.$"

RustboroCity_Gym_Text_1840D5:: @ 81840D5
	.string "Der STEINORDEN erhöht die Kraft der\n"
	.string "ATTACKEN deiner POKéMON.\p"
	.string "Außerdem sind sie nun in der Lage, die\n"
	.string "VM ZERSCHNEIDER auch außerhalb eines\l"
	.string "Kampfes einzusetzen.\p"
	.string "Dies möchte ich dir auch noch geben.$"

RustboroCity_Gym_Text_184170:: @ 8184170
	.string "Diese TM39 enthält FELSGRAB.\p"
	.string "Sie richtet nicht nur durch das Fallen\n"
	.string "von Steinen Schaden an, sondern\l"
	.string "reduziert auch die INITIATIVE.\p"
	.string "Sobald du eine TM aktivierst, wird die\n"
	.string "Attacke einem POKéMON beigebracht.\p"
	.string "Aber vergiss nicht, dass eine TM nur\n"
	.string "einmal beigebracht werden kann. Ihr\l"
	.string "Einsatz will also überlegt sein.$"

RustboroCity_Gym_Text_184252:: @ 8184252
	.string "Da du so stark bist, solltest du auch die\n"
	.string "anderen ARENALEITER herausfordern.\p"
	.string "Du lernst wertvolle Dinge dazu, wenn du\n"
	.string "gegen viele TRAINER antrittst.$"

RustboroCity_Gym_Text_1842CC:: @ 81842CC
	.string "POKéMON ARENA von METAROST CITY$"

RustboroCity_Gym_Text_1842E6:: @ 81842E6
	.string "POKéMON ARENA von METAROST CITY\p"
	.string "FELIZIAS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
