RustboroCity_House1_Text_184EBA:: @ 8184EBA
	.string "Gibst du deinen POKéMON Kosenamen?\n"
	.string "Ich habe meinem einen coolen Namen\l"
	.string "gegeben.\p"
	.string "Aber wenn ich es nun beim Namen rufe,\n"
	.string "rollen sich die Leute vor Lachen ab...\p"
	.string "Hast du Lust, dein {STR_VAR_1} gegen\n"
	.string "mein {STR_VAR_2} zu tauschen?$"

RustboroCity_House1_Text_184F6B:: @ 8184F6B
	.string "Hihihihihi, oooh, ist das aufregend!$"

RustboroCity_House1_Text_184F8F:: @ 8184F8F
	.string "Aber das ist kein {STR_VAR_1}.\n"
	.string "Tse, wie enttäuschend.$"

RustboroCity_House1_Text_184FC1:: @ 8184FC1
	.string "Ooh, das ist ein gutes POKéMON...$"

RustboroCity_House1_Text_184FDD:: @ 8184FDD
	.string "Willst du nicht wissen, wie andere\n"
	.string "Leute ihre POKéMON nennen?$"

RustboroCity_House1_Text_185020:: @ 8185020
	.string "An allen Orten gibt es alle Sorten von\n"
	.string "POKéMON und Menschen.\p"
	.string "Ich finde das faszinierend, daher\n"
	.string "besuche ich alle möglichen Orte.$"
