RustboroCity_PokemonSchool_Text_184321:: @ 8184321
	.string "Auf der Tafel sind die Statusverände-\n"
	.string "rungen von POKéMON aufgelistet.$"

RustboroCity_PokemonSchool_Text_184368:: @ 8184368
	.string "Welches Thema möchtest du lesen?$"

RustboroCity_PokemonSchool_Text_184389:: @ 8184389
	.string "Wenn ein POKéMON vergiftet wurde, wird\n"
	.string "es ständig KP verlieren.\p"
	.string "Die Auswirkungen des Giftes halten\n"
	.string "auch nach dem Kampf an.\p"
	.string "Die KP eines vergifteten POKéMON\n"
	.string "werden auch unterwegs weiter sinken.\p"
	.string "Mit einem GEGENGIFT kann das POKéMON\n"
	.string "geheilt werden.$"

RustboroCity_PokemonSchool_Text_184447:: @ 8184447
	.string "Wurde ein POKéMON paralysiert, sinkt\n"
	.string "seine INITIATIVE.\p"
	.string "Es kann passieren, dass es während des\n"
	.string "Kampfes bewegungsunfähig wird.\p"
	.string "Die Paralyse hält auch nach dem Kampf\n"
	.string "an. Heile das POKéMON mit PARA-HEILER.$"

RustboroCity_PokemonSchool_Text_1844EC:: @ 81844EC
	.string "Wenn ein POKéMON einschläft, kann es\n"
	.string "nicht mehr angreifen.\p"
	.string "Das POKéMON wird vielleicht von selber\n"
	.string "wieder wach, aber wenn der Kampf endet\l"
	.string "und es noch schläft, schläft es weiter.\p"
	.string "Wecke es mit AUFWECKER auf.$"

RustboroCity_PokemonSchool_Text_1845A5:: @ 81845A5
	.string "Eine Verbrennung senkt die Kraft des\n"
	.string "ANGRIFFS. Die KP nehmen ständig ab.\p"
	.string "Eine Verbrennung hält auch nach dem\n"
	.string "Kampf an. Setze FEUERHEILER ein!$"

RustboroCity_PokemonSchool_Text_184627:: @ 8184627
	.string "Wurde ein POKéMON eingefroren, so ist\n"
	.string "es völlig hilflos.\p"
	.string "Auch nach dem Kampf hält der Zustand\n"
	.string "an. Setze dann EISHEILER ein.$"

RustboroCity_PokemonSchool_Text_1846A2:: @ 81846A2
	.string "Schüler, die nicht aufpassen, bekommen\n"
	.string "meine FLINKKLAUE zu spüren.\p"
	.string "Wie du dieses Item einsetzt, zeigt,\n"
	.string "ob du ein guter Schüler bist oder nicht.$"

RustboroCity_PokemonSchool_Text_184737:: @ 8184737
	.string "Ein POKéMON, das die FLINKKLAUE trägt,\n"
	.string "steigert seine Schnelligkeit und greift\l"
	.string "eventuell schneller an als sein Gegner.\p"
	.string "Es gibt noch viele andere Items, die von\n"
	.string "einem POKéMON getragen werden können.\p"
	.string "Du kannst also noch viel lernen.$"

RustboroCity_PokemonSchool_Text_18480E:: @ 818480E
	.string "Ich tausche gerade mit meinem Freund\n"
	.string "POKéMON.$"

RustboroCity_PokemonSchool_Text_18483C:: @ 818483C
	.string "Ich wollte schon immer ein SAMURZEL\n"
	.string "haben - und endlich habe ich eines!$"

RustboroCity_PokemonSchool_Text_184873:: @ 8184873
	.string "POKéMON können Items tragen, aber sie\n"
	.string "wissen nicht, was sie mit Items von\l"
	.string "Menschen wie TRANK oder GEGENGIFT\l"
	.string "machen sollen.$"

RustboroCity_PokemonSchool_Text_1848D8:: @ 81848D8
	.string "Weißt du, wie man mit einigen POKéMON-\n"
	.string "Attacken ein POKéMON verwirren kann?\p"
	.string "Ein verwirrtes POKéMON wird manchmal\n"
	.string "sich selber verletzen, ohne es zu wollen.\p"
	.string "Aber sobald es aus dem Kampf genommen\n"
	.string "wird, ist es wieder normal.$"

RustboroCity_PokemonSchool_Text_184988:: @ 8184988
	.string "Ein POKéMON, das eine BEERE trägt, wird\n"
	.string "sich selber heilen...\p"
	.string "Es gibt viele Items, die ein POKéMON\n"
	.string "tragen kann...\p"
	.string "Junge, Junge, ist das alles schwer\n"
	.string "zu merken...$"

RustboroCity_PokemonSchool_Text_184A17:: @ 8184A17
	.string "Das ist das Heft eines Schülers...\p"
	.string "POKéMON werden mit POKéBÄLLEN\n"
	.string "gefangen.\p"
	.string "Bis zu sechs POKéMON können den\n"
	.string "TRAINER begleiten.\p"
	.string "Ein TRAINER ist jemand, der POKéMON\n"
	.string "fängt, sie aufzieht, und mit ihnen\l"
	.string "kämpft.\p"
	.string "Die Aufgabe eines TRAINERS ist es, die\n"
	.string "starken TRAINER, die ihn in den ARENEN\l"
	.string "erwarten, zu besiegen.$"
