SlateportCity_Text_164642:: @ 8164642
	.string "Ich bin der STATUSWERTE GURU!\n"
	.string "Ich werde dir verkaufen, was du\l"
	.string "brauchst!$"

SlateportCity_Text_164682:: @ 8164682
	.string "Oh?\n"
	.string "Dein {STR_VAR_1}...$"

SlateportCity_Text_164691:: @ 8164691
	.string "Es hat sich enorm angestrengt!\p"
	.string "Gib ihm als Belohnung bitte dieses\n"
	.string "FLEISS-BAND.$"

SlateportCity_Text_1646DD:: @ 81646DD
	.string "{PLAYER} erhält das FLEISS-BAND.$"

SlateportCity_Text_1646FC:: @ 81646FC
	.string "{PLAYER} steckt {STR_VAR_1} das\n"
	.string "FLEISS-BAND an.$"

SlateportCity_Text_16471C:: @ 816471C
	.string "Du musst dich mehr anstrengen.\p"
	.string "Dann gebe ich dir und deinen POKéMON\n"
	.string "ein schönes Geschenk.$"

SlateportCity_Text_164775:: @ 8164775
	.string "Oh! Dein {STR_VAR_1} sieht gut mit dem\n"
	.string "FLEISS-BAND aus!$"

SlateportCity_Text_1647A7:: @ 81647A7
	.string "Das Licht dieses Leuchtturms sieht man\n"
	.string "dutzende von Kilometern weit.\p"
	.string "Ich frage mich, ob es nicht die POKéMON\n"
	.string "im Meer verwirrt.$"

SlateportCity_Text_164814:: @ 8164814
	.string "Ooh, schau dir das an!\p"
	.string "Das Seegras hier in dieser Gegend sieht\n"
	.string "frisch und fast lebendig aus.\p"
	.string "Es sieht aus, als könne es sich auf-\n"
	.string "richten und angreifen!$"

SlateportCity_Text_1648A0:: @ 81648A0
	.string "Wo das Wasser sauber ist, geben die\n"
	.string "Früchte eine reiche Ernte.\p"
	.string "Und wo es eine reiche Ernte gibt, gibt\n"
	.string "es auch bald einen Markt.\p"
	.string "So entsteht und wächst eine Stadt.$"

SlateportCity_Text_164937:: @ 8164937
	.string "Einkaufen, wo man die salzige Luft des\n"
	.string "Meeres einatmen kann...\p"
	.string "GRAPHITPORT CITY ist so ein toller Ort!$"

SlateportCity_Text_164995:: @ 8164995
	.string "Wenn du PUPPEN oder KISSEN einfach auf\n"
	.string "den Boden legst, werden sie schmutzig.\p"
	.string "Ich kaufe mir einige BACKSTEINE, auf\n"
	.string "die ich meine PUPPEN und KISSEN lege.\l"
	.string "So bleiben sie schön sauber.$"

SlateportCity_Text_164A30:: @ 8164A30
	.string "Yeah! Darauf habe ich lange gewartet!\n"
	.string "WETTBEWERBE für POKéMON!\l"
	.string "Ich werde mit Sicherheit teilnehmen!\p"
	.string "Aber vorher muss ich mir einige\n"
	.string "POKéMON fangen!$"

SlateportCity_Text_164AA9:: @ 8164AA9
	.string "Puuuh... Ich bin fix und fertig...\p"
	.string "Ich komme aus MALVENFROH CITY. Diese\n"
	.string "Stadt ist vielleicht groß! Riesengroß!\p"
	.string "Hätte ich das gewusst, wäre ich mit dem\n"
	.string "RAD gekommen.$"

SlateportCity_Text_164B34:: @ 8164B34
	.string "Der Typ, der das MUSEUM gebaut\n"
	.string "hat, ist auch der Leiter eines Teams zur\l"
	.string "Erforschung der Tiefsee.\p"
	.string "Daher nennt ihn jeder KAPT. BRIGG.$"

SlateportCity_Text_164BBF:: @ 8164BBF
	.string "Was ist das dort drüben?\n"
	.string "Diese Menschenansammlung...$"

SlateportCity_Text_164BEA:: @ 8164BEA
	.string "Als ich noch ein Kind war, war ich oft in\n"
	.string "dem MUSEUM.\p"
	.string "Ich habe danach immer von den\n"
	.string "Mysterien des Meeres geträumt.$"

SlateportCity_Text_164C64:: @ 8164C64
	.string "Hey, du da! Hör auf zu drängeln!\n"
	.string "Wir stehen hier ordentlich an!$"

SlateportCity_Text_164C9F:: @ 8164C9F
	.string "TEAM {EVIL_TEAM} verfolgt die Strategie des\n"
	.string "Versammelns und Verteilens.$"

SlateportCity_Text_164CE8:: @ 8164CE8
	.string "Unser BOSS ist brillant.\p"
	.string "Wozu er jetzt wohl Interesse am\n"
	.string "MUSEUM zeigt?$"

SlateportCity_Text_164D2B:: @ 8164D2B
	.string "Was hat diese neue Masche zu bedeuten?\p"
	.string "Unser BOSS ist richtig Furcht ein-\n"
	.string "flößend, wenn er so abgedreht ist. Ich\l"
	.string "halte lieber Abstand und frage nicht...$"

SlateportCity_Text_164D92:: @ 8164D92
	.string "Wenn es im MUSEUM etwas Brauchbares\n"
	.string "gibt, dann müssen wir das an uns nehmen!$"

SlateportCity_Text_164DD5:: @ 8164DD5
	.string "Hey, du! Du willst dich doch wohl\n"
	.string "nicht vordrängeln!?!$"

SlateportCity_Text_164DF4:: @ 8164DF4
	.string "Eine lange Schlange, was?\p"
	.string "Erinnert mich an die Zeiten, als ich\n"
	.string "Ewigkeiten anstand, um mir die neuesten\l"
	.string "brandheißen Spiele zu kaufen...$"

SlateportCity_Text_164E46:: @ 8164E46
	.string "Warum stehen wir hier eigentlich an und\n"
	.string "bezahlen? Wir sollten einfach\l"
	.string "hineingehen.$"

SlateportCity_Text_164E85:: @ 8164E85
	.string "Das Meer ist wirklich überwältigend...\p"
	.string "Ob es durch die vergossenen Tränen der\n"
	.string "POKéMON entstanden ist?$"

SlateportCity_Text_164EDB:: @ 8164EDB
	.string "Weißt du, was mit alten, nicht mehr\n"
	.string "seetüchtigen Schiffen gemacht wird?\p"
	.string "Sie werden im Meer versenkt und so\n"
	.string "zu Lebensraum für die POKéMON.$"

SlateportCity_Text_164F62:: @ 8164F62
	.string "Immer wenn ich hier herkomme, vergesse\n"
	.string "ich mich und kaufe wie bescheuert ein.$"

SlateportCity_Text_164F9E:: @ 8164F9E
	.string "Wenn du die Kosenamen deiner POKéMON\n"
	.string "ändern willst, solltest du den NAMEN-\l"
	.string "BEWERTER um Hilfe bitten.$"

SlateportCity_Text_164FFC:: @ 8164FFC
	.string "Erhältst du ein POKéMON durch Tausch,\n"
	.string "kannst du den Kosenamen nicht ändern.\p"
	.string "Die Liebe des ursprünglichen TRAINERS\n"
	.string "drückt sich in dem Kosenamen aus.$"

SlateportCity_Text_16507C:: @ 816507C
	.string "Eine WETTBEWERBSHALLE für POKéMON\n"
	.string "wurde kürzlich in GRAPHITPORT CITY\l"
	.string "eröffnet.\p"
	.string "Ich plane dort hinzugehen, wenn ich\n"
	.string "meine POKéMON besser trainiert habe.$"

SlateportCity_Text_1650F1:: @ 81650F1
	.string "Hast du schon mal etwas über den\n"
	.string "BEERENMIXER gehört?$"

SlateportCity_Text_16511E:: @ 816511E
	.string "Man muss mit anderen zusammenarbeiten,\n"
	.string "um ihn schneller drehen zu können.\p"
	.string "Ich habe gehört, je schneller man ihn\n"
	.string "dreht, desto besser werden die {POKEBLOCK}.$"

SlateportCity_Text_1651A1:: @ 81651A1
	.string "Damit stellt man eine Leckerei her, die\n"
	.string "{POKEBLOCK} genannt wird.\p"
	.string "Wenn du einem POKéMON einen guten\n"
	.string "{POKEBLOCK} gibst, verbessern sich seine\l"
	.string "Eigenschaften.$"

SlateportCity_Text_165222:: @ 8165222
	.string "Ich habe gehofft, es wäre ein berühmter\n"
	.string "Star. Dann hätte ich mir ein Autogramm\l"
	.string "geben lassen.\p"
	.string "Aber wer wird denn da interviewt?\n"
	.string "Ist das nicht KAPT. BRIGG?$"

SlateportCity_Text_1652A0:: @ 81652A0
	.string "Die Interviewerin ist so cool und\n"
	.string "hübsch.\p"
	.string "Wenn ich groß bin, werde ich ein\n"
	.string "weltberühmter Journalist.$"

SlateportCity_Text_16530A:: @ 816530A
	.string "KAPT. BRIGG sagt, sie hätten etwas auf\n"
	.string "dem Meeresgrund entdeckt.\p"
	.string "Ich frage mich, was das wohl ist.\n"
	.string "Was könnte das sein???$"

SlateportCity_Text_165376:: @ 8165376
	.string "Was ist denn hier los?\p"
	.string "Hat KAPT. BRIGG etwa einen Riesen-\n"
	.string "fisch vom Meeresgrund mitgebracht?$"

SlateportCity_Text_1653D1:: @ 81653D1
	.string "Hey! Nimmst du mich auf?\n"
	.string "Komm ich jetzt ins Fernsehen?$"

SlateportCity_Text_1653F4:: @ 81653F4
	.string "Ein TV-Interview! Hier!!!\n"
	.string "Der KAPITÄN ist ein Star!$"

SlateportCity_Text_165425:: @ 8165425
	.string "UDO: Okay, KAPT. BRIGG, schenken Sie\n"
	.string "unserer Kamera Ihr schönstes Lächeln!$"

SlateportCity_Text_165458:: @ 8165458
	.string "PIA: Ich verstehe, ich verstehe. Sie\n"
	.string "haben eine unschätzbare Entdeckung\l"
	.string "gemacht...$"

SlateportCity_Text_165498:: @ 8165498
	.string "KAPT. BRIGG: Ja, genau. Wir haben vor,\n"
	.string "unsere Expedition weiter fortzuführen.$"

SlateportCity_Text_1654E0:: @ 81654E0
	.string "PIA: Das ist wunderbar, KAPT. BRIGG!\n"
	.string "Vielen Dank, dass Sie trotz Ihres vollen\l"
	.string "Terminkalenders Zeit für uns gefunden\l"
	.string "haben!\p"
	.string "Wir hoffen, Sie bald wieder zu neuen\n"
	.string "aufregenden Funden interviewen zu\l"
	.string "dürfen!$"

SlateportCity_Text_16558D:: @ 816558D
	.string "KAPT. BRIGG: Puuh...\p"
	.string "Das war das erste Mal, dass ich für eine\n"
	.string "Fernsehsendung interviewt wurde. Ich\l"
	.string "war vielleicht nervööös!$"

SlateportCity_Text_1655E7:: @ 81655E7
	.string "Oh! {PLAYER}{KUN}!\n"
	.string "Gut siehst du aus!\p"
	.string "Wir haben bei unserer letzten Tiefsee-\n"
	.string "Expedition eine großartige Entdeckung\l"
	.string "gemacht.\p"
	.string "Wir haben auf der ROUTE 128 eine Unter-\n"
	.string "wasserhöhle entdeckt.\p"
	.string "Wir glauben, es ist die Höhle eines\n"
	.string "POKéMON, das schon lange ausge-\l"
	.string "storben ist.$"

SlateportCity_Text_1656BC:: @ 81656BC
	.string "Hähähä...\n"
	.string "KAPT. BRIGG, nehme ich an.\p"
	.string "Wir vom TEAM {EVIL_TEAM} werden das U-Boot\n"
	.string "in unsere Gewalt nehmen!\p"
	.string "Eure Einwände sind bedeutungslos!\n"
	.string "Wir erwarten absolute Kooperation!\p"
	.string "Hähähä...\n"
	.string "Mal sehen, was ihr zu den Plänen von\l"
	.string "TEAM {EVIL_TEAM} sagt!$"

SlateportCity_Text_16578F:: @ 816578F
	.string "KAPT. BRIGG: Was soll das Ganze?\p"
	.string "Sieht aus, als benutze jemand ein\n"
	.string "Megaphon...\p"
	.string "Wo kommt das her?$"

SlateportCity_Text_1657FA:: @ 81657FA
	.string "Das kommt von der Anlegestelle!\p"
	.string "Das U-Boot!\n"
	.string "Jemand versucht, es zu stehlen!$"

SlateportCity_Text_16583A:: @ 816583A
	.string "{PLAYER}{KUN}!\n"
	.string "Bitte, komm mit mir!$"

SlateportCity_Text_165856:: @ 8165856
	.string "POKéMON WETTBEWERBE\n"
	.string "HYPER-KLASSE REGISTRIERUNGEN\l"
	.string "“Lasst es krachen! POKéMON-\l"
	.string "TRAINER!”$"

SlateportCity_Text_1658A0:: @ 81658A0
	.string "BRIGGWERFT\p"
	.string "“Gesucht: Ein erfahrener Seemann,\n"
	.string "der die Gefahr nicht scheut.”$"

SlateportCity_Text_1658E8:: @ 81658E8
	.string "BRIGGWERFT\p"
	.string "“Die Fähre MS TIDE wird bald fertig\n"
	.string "gestellt sein und die Häfen von\l"
	.string "GRAPHITPORT CITY und SEEGRASULB CITY\l"
	.string "bedienen.”$"

SlateportCity_Text_165952:: @ 8165952
	.string "BRIGGWERFT\p"
	.string "“Bordkarten für die GRAPHITPORT CITY-\n"
	.string "SEEGRASULB CITY Fähre MS TIDE werden\l"
	.string "am HAFEN ausgegeben.”$"

SlateportCity_Text_1659B3:: @ 81659B3
	.string "POKéMON-FANCLUB\n"
	.string "“Wir rufen alle Fans der POKéMON!”$"

SlateportCity_Text_1659E3:: @ 81659E3
	.string "“Das unendliche Meer erhält\n"
	.string "alles Leben.”\p"
	.string "OZEANMUSEUM$"

SlateportCity_Text_165A17:: @ 8165A17
	.string "GRAPHITPORT CITY\p"
	.string "“Der Hafen, an dem sich Menschen\n"
	.string "und POKéMON begegnen.”$"

SlateportCity_Text_165A57:: @ 8165A57
	.string "GRAPHITPORT CITY MARKT\n"
	.string "“Einzigartige Items, die es\l"
	.string "nirgendwo sonst gibt!”$"

SlateportCity_Text_165A8B:: @ 8165A8B
	.string "HAFEN GRAPHITPORT CITY\p"
	.string "“Die Fähre MS TIDE wird momentan\n"
	.string "in der WERFT gebaut.\p"
	.string "Die Fähre wird so bald wie möglich ihren\n"
	.string "Dienst aufnehmen.”$"

SlateportCity_Text_165B02:: @ 8165B02
	.string "HAFEN GRAPHITPORT CITY\p"
	.string "“Genießen Sie die entspannende Fahrt\n"
	.string "mit der Fähre MS TIDE.”$"

SlateportCity_Text_165B48:: @ 8165B48
	.string "HAUS DES NAMENBEWERTERS\n"
	.string "“Bewertung von POKéMON-Kosenamen.”$"
