SootopolisCity_House4_Text_18FC92:: @ 818FC92
	.string "Hör mir zu und ich verrate dir etwas.\p"
	.string "Unter Wasser soll sich eine antike\n"
	.string "Ruine befinden.\p"
	.string "Da gibt es bestimmt Schätze, die nur\n"
	.string "darauf warten, gehoben zu werden.$"

SootopolisCity_House4_Text_18FD41:: @ 818FD41
	.string "Antike Schätze...\p"
	.string "Wäre das schön, wenn es die tatsächlich\n"
	.string "gäbe. Aber auch ohne Schätze wäre eine\p"
	.string "Reise unter Wasser zusammen mit\n"
	.string "meinen POKéMON herrlich.$"

SootopolisCity_House4_Text_18FDD8:: @ 818FDD8
	.string "AZUMARILL: Marurii.$"
