ClosedSootopolisDoorText: @ 8169690
	.string "The door is closed.$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "Who might you be?\p"
	.string "This is the CAVE OF ORIGIN.\p"
	.string "The spirits of POKéMON, becalmed at\n"
	.string "MT. PYRE, are said to be revived here.\p"
	.string "Please leave.$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "Diving in the sea. Climbing up and\n"
	.string "down stairs all the time...\p"
	.string "If you live in this town, you end up\n"
	.string "getting physically fit.$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "I... I’ve never been out of this city.\p"
	.string "I wonder what the world is like on the\n"
	.string "other side of this round sky?$"

SootopolisCity_Text_169813:: @ 8169813
	.string "Hm!\n"
	.string "You’ve come all the way to SOOTOPOLIS?\l"
	.string "You’re no ordinary tourist.\p"
	.string "But I suppose that doesn’t make you an\n"
	.string "extraordinary tourist, either.$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "SOOTOPOLIS sprang up as a town in the\n"
	.string "crater of a volcano.\p"
	.string "If you look up at the sky, the lip of\n"
	.string "the crater is also visible.\l"
	.string "So, all you see is the sky in a circle.\p"
	.string "But that’s what makes the sky above\n"
	.string "SOOTOPOLIS the most beautiful.$"

SootopolisCity_Text_169988:: @ 8169988
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "In this terrible rainstorm, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "My name is WALLACE.\n"
	.string "I’m this town’s GYM LEADER.\p"
	.string "I’ve also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This downpour is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "That... That is the BLUE ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "STEVEN: This rain...\p"
	.string "People and POKéMON need water to live...\p"
	.string "But why does this rain fill us with\n"
	.string "so much dread?\p"
	.string "The rain clouds over SOOTOPOLIS will\n"
	.string "keep building and soon extend all\l"
	.string "over HOENN...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go.\n"
	.string "Together with your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "STEVEN: {PLAYER}{KUN}, I never expected you\n"
	.string "to be holding the BLUE ORB.\p"
	.string "You’ll be okay. With your POKéMON,\n"
	.string "you’ll get things done no matter what.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "WALLACE: You must go together with\n"
	.string "your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "STEVEN: You’ll be okay. With your\n"
	.string "POKéMON, you’ll get things done\l"
	.string "whatever happens.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "Under this scorching sun, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "My name is WALLACE.\n"
	.string "I’m this town’s GYM LEADER.\p"
	.string "I’ve also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This sunshine is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "That... That is the RED ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "STEVEN: This sunlight...\p"
	.string "People and POKéMON need sunlight\n"
	.string "to live...\p"
	.string "But why does this sunlight fill us\n"
	.string "with so much dread?\p"
	.string "The blazing sun over SOOTOPOLIS is\n"
	.string "intensifying... Soon, all of HOENN\l"
	.string "will be under its withering glare...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go. \n"
	.string "Together with your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "STEVEN: {PLAYER}{KUN}, I never expected you\n"
	.string "to be holding the RED ORB.\p"
	.string "You’ll be okay. With your POKéMON,\n"
	.string "you’ll get things done no matter what.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "WALLACE: You must go together with\n"
	.string "your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "STEVEN: You’ll be okay. With your\n"
	.string "POKéMON, you’ll get things done\l"
	.string "whatever happens.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "The legend told by the old man on\n"
	.string "MT. PYRE... It wasn’t a made-up story.$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "The natural balance of HOENN is going\n"
	.string "through a wrenching shift...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "STEVEN: {PLAYER}{KUN}, we owe it all to you.\p"
	.string "The sky above SOOTOPOLIS has returned\n"
	.string "to normal. For that, WALLACE sends his\l"
	.string "thanks, too.\p"
	.string "And, that same WALLACE is waiting for\n"
	.string "you inside.\p"
	.string "He’s strong.\n"
	.string "But the way you are now, you should be\l"
	.string "on equal footing with him.\p"
	.string "Give it your best shot.$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "All life starts at the CAVE OF ORIGIN,\n"
	.string "and it all ends on MT. PYRE...\p"
	.string "Where do people and POKéMON come\n"
	.string "from? Where are we bound?$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "Let me guess, you’re going to challenge\n"
	.string "WALLACE?\p"
	.string "Oh, you are really?\n"
	.string "You’re awfully brave!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "Let me guess, you’ve beaten WALLACE!\n"
	.string "Oh, you did, really?\p"
	.string "Maybe I’ll become your fan!$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "Hm!\n"
	.string "You’ve come all the way to SOOTOPOLIS?\l"
	.string "You’re no ordinary tourist.\p"
	.string "But I suppose that doesn’t make you an\n"
	.string "extraordinary tourist, either.$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "A circle of a night sky framed by the\n"
	.string "crater of a volcano...\p"
	.string "And in that ring, stars flicker and\n"
	.string "blink as if they were alive...\l"
	.string "It’s my favorite scenery.$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "Hunh? Where is my house?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "SOOTOPOLIS CITY POKéMON GYM\n"
	.string "LEADER: WALLACE\p"
	.string "“Artist, and lover of WATER.”$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "SOOTOPOLIS CITY\p"
	.string "“The mystical city where history\n"
	.string "slumbers.”$"
