SootopolisCity_House7_Text_18FFA9:: @ 818FFA9
	.string "Ein Unterwasservulkan brach aus\n"
	.string "und schob sich an die Oberfläche.\p"
	.string "Der Krater lag über der Meeresober-\n"
	.string "fläche und konnte sich so mit Regen-\p"
	.string "wasser füllen.\n"
	.string "Und so entstand XENEROVILLE.$"

SootopolisCity_House7_Text_19005B:: @ 819005B
	.string "Die Höhle, die XENEROVILLE mit der Welt\n"
	.string "verbindet...\p"
	.string "Sie sollte ursprünglich wohl etwas\n"
	.string "in der Stadt festhalten.\p"
	.string "Oder bilde ich mir das nur ein?$"
