VerdanturfTown_WandasHouse_Text_1783F6:: @ 81783F6
	.string "HEIKO: Ich habe gegen dich verloren,\n"
	.string "{PLAYER}. Aber das betrübt mich nicht.\p"
	.string "Ich habe ein neues Ziel in meinem Leben.\n"
	.string "Zusammen mit meinem TRASLA mache\p"
	.string "ich mich auf, die ARENEN herauszu-\n"
	.string "fordern und ein großer TRAINER zu\l"
	.string "werden.\p"
	.string "Behalte mich ruhig im Auge, {PLAYER}.\n"
	.string "Bald bin ich stärker als du!\p"
	.string "Und dann werde ich dich zu einem neuen\n"
	.string "Kampf herausfordern.$"

VerdanturfTown_WandasHouse_Text_178521:: @ 8178521
	.string "HEIKO: Behalte mich ruhig im Auge,\n"
	.string "{PLAYER}. Bald bin ich stärker als du!\p"
	.string "Und dann werde ich dich zu einem neuen\n"
	.string "Kampf herausfordern.$"

VerdanturfTown_WandasHouse_Text_17859A:: @ 817859A
	.string "ONKEL: Oh! {PLAYER}{KUN}!\n"
	.string "Du findest HEIKO nebenan.\p"
	.string "Aber es gibt etwas, das ich dir sagen\n"
	.string "muss.\p"
	.string "Diese natürliche Umgebung hat Wunder\n"
	.string "gewirkt bei HEIKOS Gesundheit.\p"
	.string "Und nicht nur die natürliche Umgebung!\n"
	.string "Ich denke, auch die Freundschaft zu\l"
	.string "den POKéMON hat ihm geholfen...$"

VerdanturfTown_WandasHouse_Text_178683:: @ 8178683
	.string "HEIKO ist weggegangen...\n"
	.string "Er ist nun auf seinem eigenen Weg...$"

VerdanturfTown_WandasHouse_Text_1786B5:: @ 81786B5
	.string "ONKEL: Stimmt das?\n"
	.string "HEIKO ist ganz alleine in die Welt\l"
	.string "hinausgezogen...\p"
	.string "Ich sollte ihn unterstützen - er ist der\n"
	.string "Sohn meines kleinen Bruders...$"

VerdanturfTown_WandasHouse_Text_178739:: @ 8178739
	.string "HEIKE: Wer bist du?\n"
	.string "Oh, ja, ich weiß schon...\p"
	.string "Du bist {PLAYER}. HEIKO hat mir schon\n"
	.string "viel von dir erzählt.\p"
	.string "Ich bin HEIKOS Cousine.\n"
	.string "Nett, dich kennen zu lernen!\p"
	.string "Ich finde, seit HEIKO hier lebt, ist er\n"
	.string "viel gesünder und lebendiger geworden.$"

VerdanturfTown_WandasHouse_Text_1787FB:: @ 81787FB
	.string "HEIKE: Mach dir keine Sorgen um HEIKO.\n"
	.string "Ihm geht es mit Sicherheit gut.\p"
	.string "Ich kenne doch meinen kleinen Vetter.\n"
	.string "Außerdem hat er sein POKéMON dabei.$"

VerdanturfTown_WandasHouse_Text_17886A:: @ 817886A
	.string "Dank dir kann ich meine Freundin jetzt\n"
	.string "jeden Tag sehen. Ob ich glücklich bin?\l"
	.string "Darauf kannst du wetten!$"

VerdanturfTown_WandasHouse_Text_1788B1:: @ 81788B1
	.string "Der Freund meiner Tochter besitzt viel\n"
	.string "Schwung und Energie.\p"
	.string "Er gräbt ununterbrochen einen Tunnel,\n"
	.string "damit er meine Tochter sehen kann.\p"
	.string "Meine Tochter ist etwas besorgt des-\n"
	.string "wegen und schaut jeden Tag nach ihm.$"

VerdanturfTown_WandasHouse_Text_178983:: @ 8178983
	.string "Es ist unglaublich! Der Freund meiner \n"
	.string "Tochter hat den Tunnel\p"
	.string "von Hand gegraben! Einfach sagenhaft!$"

VerdanturfTown_WandasHouse_Text_1789DD:: @ 81789DD
	.string "Sollte HEIKO irgendetwas passieren,\n"
	.string "könnte ich seinen Eltern in BLÜTENBURG\l"
	.string "CITY nicht mehr in die Augen schauen...$"

VerdanturfTown_WandasHouse_Text_178A47:: @ 8178A47
	.string "HEIKO war in PRACHTPOLIS CITY?\p"
	.string "Seine Eltern in BLÜTENBURG CITY werden\n"
	.string "erstaunt sein, das zu hören.$"
