#ifndef GUARD_CONTEST_INTERNAL_H
#define GUARD_CONTEST_INTERNAL_H

void sub_80AB350(void);
void sub_80AB5D4(u8);
void sub_80AB604(u8);
void sub_80AB678(u8);
void sub_80AB694(u8);
void sub_80AB6B4(u8);
u8 sub_80AB70C(u8 *);
void sub_80AB960(u8);
void sub_80AB9A0(u8);
void ContestMainCallback2(void);
void ContestVBlankCallback(void);
void sub_80ABB70(u8);
void sub_80ABC3C(u8);
void sub_80ABC70(u8);
void sub_80ABCDC(u8);
void sub_80ABEA0(u8);
void sub_80AC0AC(s8);
void nullsub_17(s8);
void sub_80AC0C8(u8);
void sub_80AC15C(u8);
void sub_80AC188(u8);
void sub_80AC204(u8);
void sub_80AC250(u8);
void sub_80AC284(u8);
void sub_80AC2CC(u8);
void Task_EndWaitForLink(u8 taskId);
void sub_80AD8FC(struct Sprite *);
void sub_80AD92C(struct Sprite *);
void sub_80AD960(u8);
void sub_80ADA1C(u8);
void sub_80ADA4C(u8);
void sub_80ADAD8(u8);
void sub_80ADB04(u8);
void sub_80ADB48(u8);
void sub_80ADB88(u8);
void sub_80ADC10(u8);
void sub_80ADC4C(u8);
void sub_80ADC84(u8);
void sub_80ADCB4(u8);
void sub_80ADD04(u8);
void sub_80ADD74(u8);
void sub_80ADDA4(u8);
void sub_80ADE54(u8);
void sub_80ADEAC(u8);
void sub_80ADEEC(u8);
void sub_80ADF4C(u8);
void sub_80ADF98(u8);
void sub_80ADFD8(u8);
void sub_80AE010(void);
void InsertStringDigit(u8 *, s32);
bool8 IsPlayerLinkLeader(void);
void __copy_tilemap(void *);
void PrintContestantTrainerName(u8 contestant);
void PrintContestantTrainerNameWithColor(u8 contestant, u8 color);
void PrintContestantMonName(u8 contestant);
void PrintContestantMonNameWithColor(u8 contestant, u8 color);
u8 CreateJudgeSprite(void);
u8 CreateJudgeSpeechBubbleSprite(void);
u8 CreateContestantSprite(u16, u32, u32);
void SwapMoveDescAndContestTilemaps(void);
void PrintContestMoveDescription(u16);
void sub_80AED58(void);
bool8 UpdateConditionStars(u8, u8);
bool8 DrawStatusSymbol(u8);
void DrawStatusSymbols(void);
void ContestClearGeneralTextWindow(void);
u16 GetChosenMove(u8);
void GetAllChosenMoves(void);
void sub_80AF2A0(u8);
void RankContestants(void);
void SetAttentionLevels(void);
s16 GetContestantRound2Points(u8 a);
void DetermineFinalStandings(void);
bool8 DidContestantPlaceHigher(s32 a, s32 b, struct ContestFinalStandings *c);
void ContestPrintLinkStandby(void);
void sub_80AF94C(u8);
void FillContestantWindowBgs(void);
u16 GetAppealHeartTileOffset(u8 a);
s8 GetNumHeartsFromAppealPoints(s16 a);
u8 UpdateAppealHearts(s16 startAppeal, s16 appealDelta, u8 contestant);
void Task_UpdateAppealHearts(u8 taskId);
void CreateSliderHeartSprites(void);
void sub_80AFF10(void);
bool8 sub_80AFF28(void);
void sub_80AFF60(struct Sprite *);
void sub_80AFFE0(bool8);
void sub_80B0034(void);
void CreateApplauseMeterSprite(void);
void nullsub_18(s8);
void sub_80B0238(struct Sprite *);
void sub_80B0280(struct Sprite *);
void sub_80B02A8(struct Sprite *);
void sub_80B02F4(struct Sprite *);
void sub_80B0324(void);
void sub_80B03A8(u8);
void sub_80B03D8(u8);
void sub_80B0458(u8);
void sub_80B0518(void);
void sub_80B0548(u8);
void sub_80B05A4(u8);
void nullsub_19(int);
void sub_80B05FC(u8);
void Task_UnusedBlend(u8);
void StartStopFlashJudgeAttentionEye(u8);
u8 CreateContestantBoxBlinkSprites(u8);
void BlinkContestantBox(u8, bool8);
void SpriteCB_BlinkContestantBox(struct Sprite *);
void SpriteCB_EndBlinkContestantBox(struct Sprite *);
void Unused_EndBlinkingState(u8 a, int unused);
void ContestDebugTogglePointTotal(void);
void ContestDebugDoPrint(void);
void DrawContestantWindows(void);
void CalculateAppealMoveImpact(u8 contestant);
void PrintAppealMoveResultText(u8, u8);
void ApplyNextTurnOrder(void);
void DoJudgeSpeechBubble(u8);
void UpdateApplauseMeter(void);
u8 StartApplauseOverflowAnimation(void);
void Task_ApplauseOverflowAnimation(u8);
void SlideApplauseMeterIn(void);
void Task_SlideApplauseMeterIn(u8);
void SlideApplauseMeterOut(void);
void Task_SlideApplauseMeterOut(u8);
void ShowAndUpdateApplauseMeter(s8);
void Task_ShowAndUpdateApplauseMeter(u8);
void AnimateAudience(void);
void Task_AnimateAudience(u8);
void BlendAudienceBackground(s8 excitementDir, s8 blendDir);
void Task_BlendAudienceBackground(u8 taskId);
void ShowHideNextTurnGfx(bool8 a);
const u8 *GetTurnOrderNumberGfx(u8);
void DrawUnnervedSymbols(void);
void SetBgForCurtainDrop(void);
void UpdateContestantBoxOrder(void);
void Task_StartDropCurtainAtRoundEnd(u8 taskId);
void Task_UpdateCurtainDropAtRoundEnd(u8 taskId);
void Task_ResetForNextRound(u8 taskId);
void Task_WaitRaiseCurtainAtRoundEnd(u8 taskId);
void Task_StartRaiseCurtainAtRoundEnd(u8 taskId);
void AnimateSliderHearts(u8 animId);
void Task_WaitForSliderHeartAnim(u8 taskId);
u16 SanitizeMove(u16 move);
u16 SanitizeSpecies(u16 species);
void SetMoveSpecificAnimData(u8 contestant);
void ClearMoveAnimData(u8 contestant);
void SetMoveAnimAttackerData(u8 contestant);
void CreateInvisibleBattleTargetSprite(void);
void SetBattleTargetSpritePosition(void);
void SelectContestMoveBankTarget(u16);

#endif //GUARD_CONTEST_INTERNAL_H
