// clang-format off
#ifndef GUARD_MAP_CONSTANTS_H
#define GUARD_MAP_CONSTANTS_H

//--------------------------------------------------
// Map Group 0
//--------------------------------------------------

enum
{
    MAP_ID_PETALBURG_CITY,
    MAP_ID_SLATEPORT_CITY,
    MAP_ID_MAUVILLE_CITY,
    MAP_ID_RUSTBORO_CITY,
    MAP_ID_FORTREE_CITY,
    MAP_ID_LILYCOVE_CITY,
    MAP_ID_MOSSDEEP_CITY,
    MAP_ID_SOOTOPOLIS_CITY,
    MAP_ID_EVER_GRANDE_CITY,
    MAP_ID_LITTLEROOT_TOWN,
    MAP_ID_OLDALE_TOWN,
    MAP_ID_DEWFORD_TOWN,
    MAP_ID_LAVARIDGE_TOWN,
    MAP_ID_FALLARBOR_TOWN,
    MAP_ID_VERDANTURF_TOWN,
    MAP_ID_PACIFIDLOG_TOWN,
    MAP_ID_ROUTE101,
    MAP_ID_ROUTE102,
    MAP_ID_ROUTE103,
    MAP_ID_ROUTE104,
    MAP_ID_ROUTE105,
    MAP_ID_ROUTE106,
    MAP_ID_ROUTE107,
    MAP_ID_ROUTE108,
    MAP_ID_ROUTE109,
    MAP_ID_ROUTE110,
    MAP_ID_ROUTE111,
    MAP_ID_ROUTE112,
    MAP_ID_ROUTE113,
    MAP_ID_ROUTE114,
    MAP_ID_ROUTE115,
    MAP_ID_ROUTE116,
    MAP_ID_ROUTE117,
    MAP_ID_ROUTE118,
    MAP_ID_ROUTE119,
    MAP_ID_ROUTE120,
    MAP_ID_ROUTE121,
    MAP_ID_ROUTE122,
    MAP_ID_ROUTE123,
    MAP_ID_ROUTE124,
    MAP_ID_ROUTE125,
    MAP_ID_ROUTE126,
    MAP_ID_ROUTE127,
    MAP_ID_ROUTE128,
    MAP_ID_ROUTE129,
    MAP_ID_ROUTE130,
    MAP_ID_ROUTE131,
    MAP_ID_ROUTE132,
    MAP_ID_ROUTE133,
    MAP_ID_ROUTE134,
    MAP_ID_UNDERWATER1,
    MAP_ID_UNDERWATER2,
    MAP_ID_UNDERWATER3,
    MAP_ID_UNDERWATER4,
};

#define MAP_GROUP_PETALBURG_CITY   0
#define MAP_GROUP_SLATEPORT_CITY   0
#define MAP_GROUP_MAUVILLE_CITY    0
#define MAP_GROUP_RUSTBORO_CITY    0
#define MAP_GROUP_FORTREE_CITY     0
#define MAP_GROUP_LILYCOVE_CITY    0
#define MAP_GROUP_MOSSDEEP_CITY    0
#define MAP_GROUP_SOOTOPOLIS_CITY  0
#define MAP_GROUP_EVER_GRANDE_CITY 0
#define MAP_GROUP_LITTLEROOT_TOWN  0
#define MAP_GROUP_OLDALE_TOWN      0
#define MAP_GROUP_DEWFORD_TOWN     0
#define MAP_GROUP_LAVARIDGE_TOWN   0
#define MAP_GROUP_FALLARBOR_TOWN   0
#define MAP_GROUP_VERDANTURF_TOWN  0
#define MAP_GROUP_PACIFIDLOG_TOWN  0
#define MAP_GROUP_ROUTE101         0
#define MAP_GROUP_ROUTE102         0
#define MAP_GROUP_ROUTE103         0
#define MAP_GROUP_ROUTE104         0
#define MAP_GROUP_ROUTE105         0
#define MAP_GROUP_ROUTE106         0
#define MAP_GROUP_ROUTE107         0
#define MAP_GROUP_ROUTE108         0
#define MAP_GROUP_ROUTE109         0
#define MAP_GROUP_ROUTE110         0
#define MAP_GROUP_ROUTE111         0
#define MAP_GROUP_ROUTE112         0
#define MAP_GROUP_ROUTE113         0
#define MAP_GROUP_ROUTE114         0
#define MAP_GROUP_ROUTE115         0
#define MAP_GROUP_ROUTE116         0
#define MAP_GROUP_ROUTE117         0
#define MAP_GROUP_ROUTE118         0
#define MAP_GROUP_ROUTE119         0
#define MAP_GROUP_ROUTE120         0
#define MAP_GROUP_ROUTE121         0
#define MAP_GROUP_ROUTE122         0
#define MAP_GROUP_ROUTE123         0
#define MAP_GROUP_ROUTE124         0
#define MAP_GROUP_ROUTE125         0
#define MAP_GROUP_ROUTE126         0
#define MAP_GROUP_ROUTE127         0
#define MAP_GROUP_ROUTE128         0
#define MAP_GROUP_ROUTE129         0
#define MAP_GROUP_ROUTE130         0
#define MAP_GROUP_ROUTE131         0
#define MAP_GROUP_ROUTE132         0
#define MAP_GROUP_ROUTE133         0
#define MAP_GROUP_ROUTE134         0
#define MAP_GROUP_UNDERWATER1      0
#define MAP_GROUP_UNDERWATER2      0
#define MAP_GROUP_UNDERWATER3      0
#define MAP_GROUP_UNDERWATER4      0

//--------------------------------------------------
// Map Group 1
//--------------------------------------------------

enum
{
    MAP_ID_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F,
    MAP_ID_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    MAP_ID_LITTLEROOT_TOWN_MAYS_HOUSE_1F,
    MAP_ID_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    MAP_ID_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB,
};

#define MAP_GROUP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    1
#define MAP_GROUP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    1
#define MAP_GROUP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        1
#define MAP_GROUP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        1
#define MAP_GROUP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB 1

//--------------------------------------------------
// Map Group 2
//--------------------------------------------------

enum
{
    MAP_ID_OLDALE_TOWN_HOUSE1,
    MAP_ID_OLDALE_TOWN_HOUSE2,
    MAP_ID_OLDALE_TOWN_POKEMON_CENTER_1F,
    MAP_ID_OLDALE_TOWN_POKEMON_CENTER_2F,
    MAP_ID_OLDALE_TOWN_MART,
};

#define MAP_GROUP_OLDALE_TOWN_HOUSE1            2
#define MAP_GROUP_OLDALE_TOWN_HOUSE2            2
#define MAP_GROUP_OLDALE_TOWN_POKEMON_CENTER_1F 2
#define MAP_GROUP_OLDALE_TOWN_POKEMON_CENTER_2F 2
#define MAP_GROUP_OLDALE_TOWN_MART              2

//--------------------------------------------------
// Map Group 3
//--------------------------------------------------

enum
{
    MAP_ID_DEWFORD_TOWN_HOUSE1,
    MAP_ID_DEWFORD_TOWN_POKEMON_CENTER_1F,
    MAP_ID_DEWFORD_TOWN_POKEMON_CENTER_2F,
    MAP_ID_DEWFORD_TOWN_GYM,
    MAP_ID_DEWFORD_TOWN_HALL,
    MAP_ID_DEWFORD_TOWN_HOUSE2,
};

#define MAP_GROUP_DEWFORD_TOWN_HOUSE1            3
#define MAP_GROUP_DEWFORD_TOWN_POKEMON_CENTER_1F 3
#define MAP_GROUP_DEWFORD_TOWN_POKEMON_CENTER_2F 3
#define MAP_GROUP_DEWFORD_TOWN_GYM               3
#define MAP_GROUP_DEWFORD_TOWN_HALL              3
#define MAP_GROUP_DEWFORD_TOWN_HOUSE2            3

//--------------------------------------------------
// Map Group 4
//--------------------------------------------------

enum
{
    MAP_ID_LAVARIDGE_TOWN_HERB_SHOP,
    MAP_ID_LAVARIDGE_TOWN_GYM_1F,
    MAP_ID_LAVARIDGE_TOWN_GYM_B1F,
    MAP_ID_LAVARIDGE_TOWN_HOUSE,
    MAP_ID_LAVARIDGE_TOWN_MART,
    MAP_ID_LAVARIDGE_TOWN_POKEMON_CENTER_1F,
    MAP_ID_LAVARIDGE_TOWN_POKEMON_CENTER_2F,
};

#define MAP_GROUP_LAVARIDGE_TOWN_HERB_SHOP         4
#define MAP_GROUP_LAVARIDGE_TOWN_GYM_1F            4
#define MAP_GROUP_LAVARIDGE_TOWN_GYM_B1F           4
#define MAP_GROUP_LAVARIDGE_TOWN_HOUSE             4
#define MAP_GROUP_LAVARIDGE_TOWN_MART              4
#define MAP_GROUP_LAVARIDGE_TOWN_POKEMON_CENTER_1F 4
#define MAP_GROUP_LAVARIDGE_TOWN_POKEMON_CENTER_2F 4

//--------------------------------------------------
// Map Group 5
//--------------------------------------------------

enum
{
    MAP_ID_FALLARBOR_TOWN_MART,
    MAP_ID_FALLARBOR_TOWN_CONTEST_LOBBY,
    MAP_ID_FALLARBOR_TOWN_CONTEST_HALL,
    MAP_ID_FALLARBOR_TOWN_POKEMON_CENTER_1F,
    MAP_ID_FALLARBOR_TOWN_POKEMON_CENTER_2F,
    MAP_ID_FALLARBOR_TOWN_HOUSE1,
    MAP_ID_FALLARBOR_TOWN_HOUSE2,
};

#define MAP_GROUP_FALLARBOR_TOWN_MART              5
#define MAP_GROUP_FALLARBOR_TOWN_CONTEST_LOBBY     5
#define MAP_GROUP_FALLARBOR_TOWN_CONTEST_HALL      5
#define MAP_GROUP_FALLARBOR_TOWN_POKEMON_CENTER_1F 5
#define MAP_GROUP_FALLARBOR_TOWN_POKEMON_CENTER_2F 5
#define MAP_GROUP_FALLARBOR_TOWN_HOUSE1            5
#define MAP_GROUP_FALLARBOR_TOWN_HOUSE2            5

//--------------------------------------------------
// Map Group 6
//--------------------------------------------------

enum
{
    MAP_ID_VERDANTURF_TOWN_CONTEST_LOBBY,
    MAP_ID_VERDANTURF_TOWN_CONTEST_HALL,
    MAP_ID_VERDANTURF_TOWN_MART,
    MAP_ID_VERDANTURF_TOWN_POKEMON_CENTER_1F,
    MAP_ID_VERDANTURF_TOWN_POKEMON_CENTER_2F,
    MAP_ID_VERDANTURF_TOWN_WANDAS_HOUSE,
    MAP_ID_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE,
    MAP_ID_VERDANTURF_TOWN_HOUSE,
};

#define MAP_GROUP_VERDANTURF_TOWN_CONTEST_LOBBY           6
#define MAP_GROUP_VERDANTURF_TOWN_CONTEST_HALL            6
#define MAP_GROUP_VERDANTURF_TOWN_MART                    6
#define MAP_GROUP_VERDANTURF_TOWN_POKEMON_CENTER_1F       6
#define MAP_GROUP_VERDANTURF_TOWN_POKEMON_CENTER_2F       6
#define MAP_GROUP_VERDANTURF_TOWN_WANDAS_HOUSE            6
#define MAP_GROUP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE 6
#define MAP_GROUP_VERDANTURF_TOWN_HOUSE                   6

//--------------------------------------------------
// Map Group 7
//--------------------------------------------------

enum
{
    MAP_ID_PACIFIDLOG_TOWN_POKEMON_CENTER_1F,
    MAP_ID_PACIFIDLOG_TOWN_POKEMON_CENTER_2F,
    MAP_ID_PACIFIDLOG_TOWN_HOUSE1,
    MAP_ID_PACIFIDLOG_TOWN_HOUSE2,
    MAP_ID_PACIFIDLOG_TOWN_HOUSE3,
    MAP_ID_PACIFIDLOG_TOWN_HOUSE4,
    MAP_ID_PACIFIDLOG_TOWN_HOUSE5,
};

#define MAP_GROUP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F 7
#define MAP_GROUP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F 7
#define MAP_GROUP_PACIFIDLOG_TOWN_HOUSE1            7
#define MAP_GROUP_PACIFIDLOG_TOWN_HOUSE2            7
#define MAP_GROUP_PACIFIDLOG_TOWN_HOUSE3            7
#define MAP_GROUP_PACIFIDLOG_TOWN_HOUSE4            7
#define MAP_GROUP_PACIFIDLOG_TOWN_HOUSE5            7

//--------------------------------------------------
// Map Group 8
//--------------------------------------------------

enum
{
    MAP_ID_PETALBURG_CITY_WALLYS_HOUSE,
    MAP_ID_PETALBURG_CITY_GYM,
    MAP_ID_PETALBURG_CITY_HOUSE1,
    MAP_ID_PETALBURG_CITY_HOUSE2,
    MAP_ID_PETALBURG_CITY_POKEMON_CENTER_1F,
    MAP_ID_PETALBURG_CITY_POKEMON_CENTER_2F,
    MAP_ID_PETALBURG_CITY_MART,
};

#define MAP_GROUP_PETALBURG_CITY_WALLYS_HOUSE      8
#define MAP_GROUP_PETALBURG_CITY_GYM               8
#define MAP_GROUP_PETALBURG_CITY_HOUSE1            8
#define MAP_GROUP_PETALBURG_CITY_HOUSE2            8
#define MAP_GROUP_PETALBURG_CITY_POKEMON_CENTER_1F 8
#define MAP_GROUP_PETALBURG_CITY_POKEMON_CENTER_2F 8
#define MAP_GROUP_PETALBURG_CITY_MART              8

//--------------------------------------------------
// Map Group 9
//--------------------------------------------------

enum
{
    MAP_ID_SLATEPORT_CITY_STERNS_SHIPYARD_1F,
    MAP_ID_SLATEPORT_CITY_STERNS_SHIPYARD_2F,
    MAP_ID_SLATEPORT_CITY_CONTEST_LOBBY,
    MAP_ID_SLATEPORT_CITY_CONTEST_HALL,
    MAP_ID_SLATEPORT_CITY_HOUSE1,
    MAP_ID_SLATEPORT_CITY_POKEMON_FAN_CLUB,
    MAP_ID_SLATEPORT_CITY_OCEANIC_MUSEUM_1F,
    MAP_ID_SLATEPORT_CITY_OCEANIC_MUSEUM_2F,
    MAP_ID_SLATEPORT_CITY_HARBOR,
    MAP_ID_SLATEPORT_CITY_HOUSE2,
    MAP_ID_SLATEPORT_CITY_POKEMON_CENTER_1F,
    MAP_ID_SLATEPORT_CITY_POKEMON_CENTER_2F,
    MAP_ID_SLATEPORT_CITY_MART,
};

#define MAP_GROUP_SLATEPORT_CITY_STERNS_SHIPYARD_1F 9
#define MAP_GROUP_SLATEPORT_CITY_STERNS_SHIPYARD_2F 9
#define MAP_GROUP_SLATEPORT_CITY_CONTEST_LOBBY      9
#define MAP_GROUP_SLATEPORT_CITY_CONTEST_HALL       9
#define MAP_GROUP_SLATEPORT_CITY_HOUSE1             9
#define MAP_GROUP_SLATEPORT_CITY_POKEMON_FAN_CLUB   9
#define MAP_GROUP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F  9
#define MAP_GROUP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F  9
#define MAP_GROUP_SLATEPORT_CITY_HARBOR             9
#define MAP_GROUP_SLATEPORT_CITY_HOUSE2             9
#define MAP_GROUP_SLATEPORT_CITY_POKEMON_CENTER_1F  9
#define MAP_GROUP_SLATEPORT_CITY_POKEMON_CENTER_2F  9
#define MAP_GROUP_SLATEPORT_CITY_MART               9

//--------------------------------------------------
// Map Group 10
//--------------------------------------------------

enum
{
    MAP_ID_MAUVILLE_CITY_GYM,
    MAP_ID_MAUVILLE_CITY_BIKE_SHOP,
    MAP_ID_MAUVILLE_CITY_HOUSE1,
    MAP_ID_MAUVILLE_CITY_GAME_CORNER,
    MAP_ID_MAUVILLE_CITY_HOUSE2,
    MAP_ID_MAUVILLE_CITY_POKEMON_CENTER_1F,
    MAP_ID_MAUVILLE_CITY_POKEMON_CENTER_2F,
    MAP_ID_MAUVILLE_CITY_MART,
};

#define MAP_GROUP_MAUVILLE_CITY_GYM               10
#define MAP_GROUP_MAUVILLE_CITY_BIKE_SHOP         10
#define MAP_GROUP_MAUVILLE_CITY_HOUSE1            10
#define MAP_GROUP_MAUVILLE_CITY_GAME_CORNER       10
#define MAP_GROUP_MAUVILLE_CITY_HOUSE2            10
#define MAP_GROUP_MAUVILLE_CITY_POKEMON_CENTER_1F 10
#define MAP_GROUP_MAUVILLE_CITY_POKEMON_CENTER_2F 10
#define MAP_GROUP_MAUVILLE_CITY_MART              10

//--------------------------------------------------
// Map Group 11
//--------------------------------------------------

enum
{
    MAP_ID_RUSTBORO_CITY_DEVON_CORP_1F,
    MAP_ID_RUSTBORO_CITY_DEVON_CORP_2F,
    MAP_ID_RUSTBORO_CITY_DEVON_CORP_3F,
    MAP_ID_RUSTBORO_CITY_GYM,
    MAP_ID_RUSTBORO_CITY_POKEMON_SCHOOL,
    MAP_ID_RUSTBORO_CITY_POKEMON_CENTER_1F,
    MAP_ID_RUSTBORO_CITY_POKEMON_CENTER_2F,
    MAP_ID_RUSTBORO_CITY_MART,
    MAP_ID_RUSTBORO_CITY_FLAT1_1F,
    MAP_ID_RUSTBORO_CITY_FLAT1_2F,
    MAP_ID_RUSTBORO_CITY_HOUSE1,
    MAP_ID_RUSTBORO_CITY_CUTTERS_HOUSE,
    MAP_ID_RUSTBORO_CITY_HOUSE2,
    MAP_ID_RUSTBORO_CITY_FLAT2_1F,
    MAP_ID_RUSTBORO_CITY_FLAT2_2F,
    MAP_ID_RUSTBORO_CITY_FLAT2_3F,
    MAP_ID_RUSTBORO_CITY_HOUSE3,
};

#define MAP_GROUP_RUSTBORO_CITY_DEVON_CORP_1F     11
#define MAP_GROUP_RUSTBORO_CITY_DEVON_CORP_2F     11
#define MAP_GROUP_RUSTBORO_CITY_DEVON_CORP_3F     11
#define MAP_GROUP_RUSTBORO_CITY_GYM               11
#define MAP_GROUP_RUSTBORO_CITY_POKEMON_SCHOOL    11
#define MAP_GROUP_RUSTBORO_CITY_POKEMON_CENTER_1F 11
#define MAP_GROUP_RUSTBORO_CITY_POKEMON_CENTER_2F 11
#define MAP_GROUP_RUSTBORO_CITY_MART              11
#define MAP_GROUP_RUSTBORO_CITY_FLAT1_1F          11
#define MAP_GROUP_RUSTBORO_CITY_FLAT1_2F          11
#define MAP_GROUP_RUSTBORO_CITY_HOUSE1            11
#define MAP_GROUP_RUSTBORO_CITY_CUTTERS_HOUSE     11
#define MAP_GROUP_RUSTBORO_CITY_HOUSE2            11
#define MAP_GROUP_RUSTBORO_CITY_FLAT2_1F          11
#define MAP_GROUP_RUSTBORO_CITY_FLAT2_2F          11
#define MAP_GROUP_RUSTBORO_CITY_FLAT2_3F          11
#define MAP_GROUP_RUSTBORO_CITY_HOUSE3            11

//--------------------------------------------------
// Map Group 12
//--------------------------------------------------

enum
{
    MAP_ID_FORTREE_CITY_HOUSE1,
    MAP_ID_FORTREE_CITY_GYM,
    MAP_ID_FORTREE_CITY_POKEMON_CENTER_1F,
    MAP_ID_FORTREE_CITY_POKEMON_CENTER_2F,
    MAP_ID_FORTREE_CITY_MART,
    MAP_ID_FORTREE_CITY_HOUSE2,
    MAP_ID_FORTREE_CITY_HOUSE3,
    MAP_ID_FORTREE_CITY_HOUSE4,
    MAP_ID_FORTREE_CITY_HOUSE5,
    MAP_ID_FORTREE_CITY_DECORATION_SHOP,
};

#define MAP_GROUP_FORTREE_CITY_HOUSE1            12
#define MAP_GROUP_FORTREE_CITY_GYM               12
#define MAP_GROUP_FORTREE_CITY_POKEMON_CENTER_1F 12
#define MAP_GROUP_FORTREE_CITY_POKEMON_CENTER_2F 12
#define MAP_GROUP_FORTREE_CITY_MART              12
#define MAP_GROUP_FORTREE_CITY_HOUSE2            12
#define MAP_GROUP_FORTREE_CITY_HOUSE3            12
#define MAP_GROUP_FORTREE_CITY_HOUSE4            12
#define MAP_GROUP_FORTREE_CITY_HOUSE5            12
#define MAP_GROUP_FORTREE_CITY_DECORATION_SHOP   12

//--------------------------------------------------
// Map Group 13
//--------------------------------------------------

enum
{
    MAP_ID_LILYCOVE_CITY_COVE_LILY_MOTEL_1F,
    MAP_ID_LILYCOVE_CITY_COVE_LILY_MOTEL_2F,
    MAP_ID_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F,
    MAP_ID_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F,
    MAP_ID_LILYCOVE_CITY_CONTEST_LOBBY,
    MAP_ID_LILYCOVE_CITY_CONTEST_HALL,
    MAP_ID_LILYCOVE_CITY_POKEMON_CENTER_1F,
    MAP_ID_LILYCOVE_CITY_POKEMON_CENTER_2F,
    MAP_ID_LILYCOVE_CITY_UNUSED_MART,
    MAP_ID_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB,
    MAP_ID_LILYCOVE_CITY_HARBOR,
    MAP_ID_LILYCOVE_CITY_EMPTY_MAP,
    MAP_ID_LILYCOVE_CITY_MOVE_DELETERS_HOUSE,
    MAP_ID_LILYCOVE_CITY_HOUSE1,
    MAP_ID_LILYCOVE_CITY_HOUSE2,
    MAP_ID_LILYCOVE_CITY_HOUSE3,
    MAP_ID_LILYCOVE_CITY_HOUSE4,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_1F,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_2F,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_3F,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_4F,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_5F,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP,
    MAP_ID_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR,
};

#define MAP_GROUP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        13
#define MAP_GROUP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        13
#define MAP_GROUP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        13
#define MAP_GROUP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        13
#define MAP_GROUP_LILYCOVE_CITY_CONTEST_LOBBY             13
#define MAP_GROUP_LILYCOVE_CITY_CONTEST_HALL              13
#define MAP_GROUP_LILYCOVE_CITY_POKEMON_CENTER_1F         13
#define MAP_GROUP_LILYCOVE_CITY_POKEMON_CENTER_2F         13
#define MAP_GROUP_LILYCOVE_CITY_UNUSED_MART               13
#define MAP_GROUP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  13
#define MAP_GROUP_LILYCOVE_CITY_HARBOR                    13
#define MAP_GROUP_LILYCOVE_CITY_EMPTY_MAP                 13
#define MAP_GROUP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       13
#define MAP_GROUP_LILYCOVE_CITY_HOUSE1                    13
#define MAP_GROUP_LILYCOVE_CITY_HOUSE2                    13
#define MAP_GROUP_LILYCOVE_CITY_HOUSE3                    13
#define MAP_GROUP_LILYCOVE_CITY_HOUSE4                    13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  13
#define MAP_GROUP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR 13

//--------------------------------------------------
// Map Group 14
//--------------------------------------------------

enum
{
    MAP_ID_MOSSDEEP_CITY_GYM,
    MAP_ID_MOSSDEEP_CITY_HOUSE1,
    MAP_ID_MOSSDEEP_CITY_HOUSE2,
    MAP_ID_MOSSDEEP_CITY_POKEMON_CENTER_1F,
    MAP_ID_MOSSDEEP_CITY_POKEMON_CENTER_2F,
    MAP_ID_MOSSDEEP_CITY_MART,
    MAP_ID_MOSSDEEP_CITY_HOUSE3,
    MAP_ID_MOSSDEEP_CITY_STEVENS_HOUSE,
    MAP_ID_MOSSDEEP_CITY_HOUSE4,
    MAP_ID_MOSSDEEP_CITY_SPACE_CENTER_1F,
    MAP_ID_MOSSDEEP_CITY_SPACE_CENTER_2F,
    MAP_ID_MOSSDEEP_CITY_GAME_CORNER_1F,
    MAP_ID_MOSSDEEP_CITY_GAME_CORNER_B1F,
};

#define MAP_GROUP_MOSSDEEP_CITY_GYM               14
#define MAP_GROUP_MOSSDEEP_CITY_HOUSE1            14
#define MAP_GROUP_MOSSDEEP_CITY_HOUSE2            14
#define MAP_GROUP_MOSSDEEP_CITY_POKEMON_CENTER_1F 14
#define MAP_GROUP_MOSSDEEP_CITY_POKEMON_CENTER_2F 14
#define MAP_GROUP_MOSSDEEP_CITY_MART              14
#define MAP_GROUP_MOSSDEEP_CITY_HOUSE3            14
#define MAP_GROUP_MOSSDEEP_CITY_STEVENS_HOUSE     14
#define MAP_GROUP_MOSSDEEP_CITY_HOUSE4            14
#define MAP_GROUP_MOSSDEEP_CITY_SPACE_CENTER_1F   14
#define MAP_GROUP_MOSSDEEP_CITY_SPACE_CENTER_2F   14
#define MAP_GROUP_MOSSDEEP_CITY_GAME_CORNER_1F    14
#define MAP_GROUP_MOSSDEEP_CITY_GAME_CORNER_B1F   14

//--------------------------------------------------
// Map Group 15
//--------------------------------------------------

enum
{
    MAP_ID_SOOTOPOLIS_CITY_GYM_1F,
    MAP_ID_SOOTOPOLIS_CITY_GYM_B1F,
    MAP_ID_SOOTOPOLIS_CITY_POKEMON_CENTER_1F,
    MAP_ID_SOOTOPOLIS_CITY_POKEMON_CENTER_2F,
    MAP_ID_SOOTOPOLIS_CITY_MART,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE1,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE2,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE3,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE4,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE5,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE6,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE7,
    MAP_ID_SOOTOPOLIS_CITY_HOUSE8,
};

#define MAP_GROUP_SOOTOPOLIS_CITY_GYM_1F            15
#define MAP_GROUP_SOOTOPOLIS_CITY_GYM_B1F           15
#define MAP_GROUP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F 15
#define MAP_GROUP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F 15
#define MAP_GROUP_SOOTOPOLIS_CITY_MART              15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE1            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE2            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE3            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE4            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE5            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE6            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE7            15
#define MAP_GROUP_SOOTOPOLIS_CITY_HOUSE8            15

//--------------------------------------------------
// Map Group 16
//--------------------------------------------------

enum
{
    MAP_ID_EVER_GRANDE_CITY_SIDNEYS_ROOM,
    MAP_ID_EVER_GRANDE_CITY_PHOEBES_ROOM,
    MAP_ID_EVER_GRANDE_CITY_GLACIAS_ROOM,
    MAP_ID_EVER_GRANDE_CITY_DRAKES_ROOM,
    MAP_ID_EVER_GRANDE_CITY_CHAMPIONS_ROOM,
    MAP_ID_EVER_GRANDE_CITY_CORRIDOR1,
    MAP_ID_EVER_GRANDE_CITY_CORRIDOR2,
    MAP_ID_EVER_GRANDE_CITY_CORRIDOR3,
    MAP_ID_EVER_GRANDE_CITY_CORRIDOR4,
    MAP_ID_EVER_GRANDE_CITY_CORRIDOR5,
    MAP_ID_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    MAP_ID_EVER_GRANDE_CITY_HALL_OF_FAME,
    MAP_ID_EVER_GRANDE_CITY_POKEMON_CENTER_1F,
    MAP_ID_EVER_GRANDE_CITY_POKEMON_CENTER_2F,
};

#define MAP_GROUP_EVER_GRANDE_CITY_SIDNEYS_ROOM      16
#define MAP_GROUP_EVER_GRANDE_CITY_PHOEBES_ROOM      16
#define MAP_GROUP_EVER_GRANDE_CITY_GLACIAS_ROOM      16
#define MAP_GROUP_EVER_GRANDE_CITY_DRAKES_ROOM       16
#define MAP_GROUP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    16
#define MAP_GROUP_EVER_GRANDE_CITY_CORRIDOR1         16
#define MAP_GROUP_EVER_GRANDE_CITY_CORRIDOR2         16
#define MAP_GROUP_EVER_GRANDE_CITY_CORRIDOR3         16
#define MAP_GROUP_EVER_GRANDE_CITY_CORRIDOR4         16
#define MAP_GROUP_EVER_GRANDE_CITY_CORRIDOR5         16
#define MAP_GROUP_EVER_GRANDE_CITY_POKEMON_LEAGUE    16
#define MAP_GROUP_EVER_GRANDE_CITY_HALL_OF_FAME      16
#define MAP_GROUP_EVER_GRANDE_CITY_POKEMON_CENTER_1F 16
#define MAP_GROUP_EVER_GRANDE_CITY_POKEMON_CENTER_2F 16

//--------------------------------------------------
// Map Group 17
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE104_MR_BRINEYS_HOUSE,
    MAP_ID_ROUTE104_PRETTY_PETAL_FLOWER_SHOP,
};

#define MAP_GROUP_ROUTE104_MR_BRINEYS_HOUSE         17
#define MAP_GROUP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP 17

//--------------------------------------------------
// Map Group 18
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE111_WINSTRATE_FAMILYS_HOUSE,
    MAP_ID_ROUTE111_OLD_LADYS_REST_STOP,
};

#define MAP_GROUP_ROUTE111_WINSTRATE_FAMILYS_HOUSE 18
#define MAP_GROUP_ROUTE111_OLD_LADYS_REST_STOP     18

//--------------------------------------------------
// Map Group 19
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE112_CABLE_CAR_STATION,
    MAP_ID_MT_CHIMNEY_CABLE_CAR_STATION,
};

#define MAP_GROUP_ROUTE112_CABLE_CAR_STATION   19
#define MAP_GROUP_MT_CHIMNEY_CABLE_CAR_STATION 19

//--------------------------------------------------
// Map Group 20
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE114_FOSSIL_MANIACS_HOUSE,
    MAP_ID_ROUTE114_FOSSIL_MANIACS_TUNNEL,
    MAP_ID_ROUTE114_LANETTES_HOUSE,
};

#define MAP_GROUP_ROUTE114_FOSSIL_MANIACS_HOUSE  20
#define MAP_GROUP_ROUTE114_FOSSIL_MANIACS_TUNNEL 20
#define MAP_GROUP_ROUTE114_LANETTES_HOUSE        20

//--------------------------------------------------
// Map Group 21
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE116_TUNNELERS_REST_HOUSE,
};

#define MAP_GROUP_ROUTE116_TUNNELERS_REST_HOUSE 21

//--------------------------------------------------
// Map Group 22
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE117_POKEMON_DAY_CARE,
};

#define MAP_GROUP_ROUTE117_POKEMON_DAY_CARE 22

//--------------------------------------------------
// Map Group 23
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE121_SAFARI_ZONE_ENTRANCE,
};

#define MAP_GROUP_ROUTE121_SAFARI_ZONE_ENTRANCE 23

//--------------------------------------------------
// Map Group 24
//--------------------------------------------------

enum
{
    MAP_ID_METEOR_FALLS_1F_1R,
    MAP_ID_METEOR_FALLS_1F_2R,
    MAP_ID_METEOR_FALLS_B1F_1R,
    MAP_ID_METEOR_FALLS_B1F_2R,
    MAP_ID_RUSTURF_TUNNEL,
    MAP_ID_UNDERWATER_SOOTOPOLIS_CITY,
    MAP_ID_DESERT_RUINS,
    MAP_ID_GRANITE_CAVE_1F,
    MAP_ID_GRANITE_CAVE_B1F,
    MAP_ID_GRANITE_CAVE_B2F,
    MAP_ID_GRANITE_CAVE_STEVENS_ROOM,
    MAP_ID_PETALBURG_WOODS,
    MAP_ID_MT_CHIMNEY,
    MAP_ID_JAGGED_PASS,
    MAP_ID_FIERY_PATH,
    MAP_ID_MT_PYRE_1F,
    MAP_ID_MT_PYRE_2F,
    MAP_ID_MT_PYRE_3F,
    MAP_ID_MT_PYRE_4F,
    MAP_ID_MT_PYRE_5F,
    MAP_ID_MT_PYRE_6F,
    MAP_ID_MT_PYRE_EXTERIOR,
    MAP_ID_MT_PYRE_SUMMIT,
    MAP_ID_AQUA_HIDEOUT_1F,
    MAP_ID_AQUA_HIDEOUT_B1F,
    MAP_ID_AQUA_HIDEOUT_B2F,
    MAP_ID_UNDERWATER_SEAFLOOR_CAVERN,
    MAP_ID_SEAFLOOR_CAVERN_ENTRANCE,
    MAP_ID_SEAFLOOR_CAVERN_ROOM1,
    MAP_ID_SEAFLOOR_CAVERN_ROOM2,
    MAP_ID_SEAFLOOR_CAVERN_ROOM3,
    MAP_ID_SEAFLOOR_CAVERN_ROOM4,
    MAP_ID_SEAFLOOR_CAVERN_ROOM5,
    MAP_ID_SEAFLOOR_CAVERN_ROOM6,
    MAP_ID_SEAFLOOR_CAVERN_ROOM7,
    MAP_ID_SEAFLOOR_CAVERN_ROOM8,
    MAP_ID_SEAFLOOR_CAVERN_ROOM9,
    MAP_ID_CAVE_OF_ORIGIN_ENTRANCE,
    MAP_ID_CAVE_OF_ORIGIN_1F,
    MAP_ID_CAVE_OF_ORIGIN_B1F,
    MAP_ID_CAVE_OF_ORIGIN_B2F,
    MAP_ID_CAVE_OF_ORIGIN_B3F,
    MAP_ID_CAVE_OF_ORIGIN_B4F,
    MAP_ID_VICTORY_ROAD_1F,
    MAP_ID_VICTORY_ROAD_B1F,
    MAP_ID_VICTORY_ROAD_B2F,
    MAP_ID_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM,
    MAP_ID_SHOAL_CAVE_LOW_TIDE_INNER_ROOM,
    MAP_ID_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM,
    MAP_ID_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM,
    MAP_ID_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM,
    MAP_ID_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM,
    MAP_ID_NEW_MAUVILLE_ENTRANCE,
    MAP_ID_NEW_MAUVILLE_INSIDE,
    MAP_ID_ABANDONED_SHIP_DECK,
    MAP_ID_ABANDONED_SHIP_CORRIDORS_1F,
    MAP_ID_ABANDONED_SHIP_ROOMS_1F,
    MAP_ID_ABANDONED_SHIP_CORRIDORS_B1F,
    MAP_ID_ABANDONED_SHIP_ROOMS_B1F,
    MAP_ID_ABANDONED_SHIP_ROOMS2_B1F,
    MAP_ID_ABANDONED_SHIP_UNDERWATER1,
    MAP_ID_ABANDONED_SHIP_ROOM_B1F,
    MAP_ID_ABANDONED_SHIP_ROOMS2_1F,
    MAP_ID_ABANDONED_SHIP_CAPTAINS_OFFICE,
    MAP_ID_ABANDONED_SHIP_UNDERWATER2,
    MAP_ID_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS,
    MAP_ID_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS,
    MAP_ID_ISLAND_CAVE,
    MAP_ID_ANCIENT_TOMB,
    MAP_ID_UNDERWATER_ROUTE134,
    MAP_ID_UNDERWATER_SEALED_CHAMBER,
    MAP_ID_SEALED_CHAMBER_OUTER_ROOM,
    MAP_ID_SEALED_CHAMBER_INNER_ROOM,
    MAP_ID_SCORCHED_SLAB,
    MAP_ID_MAGMA_HIDEOUT_1F,
    MAP_ID_MAGMA_HIDEOUT_B1F,
    MAP_ID_MAGMA_HIDEOUT_B2F,
    MAP_ID_SKY_PILLAR_ENTRANCE,
    MAP_ID_SKY_PILLAR_OUTSIDE,
    MAP_ID_SKY_PILLAR_1F,
    MAP_ID_SKY_PILLAR_2F,
    MAP_ID_SKY_PILLAR_3F,
    MAP_ID_SKY_PILLAR_4F,
    MAP_ID_SHOAL_CAVE_LOW_TIDE_ICE_ROOM,
    MAP_ID_SKY_PILLAR_5F,
    MAP_ID_SKY_PILLAR_TOP,
};

#define MAP_GROUP_METEOR_FALLS_1F_1R                    24
#define MAP_GROUP_METEOR_FALLS_1F_2R                    24
#define MAP_GROUP_METEOR_FALLS_B1F_1R                   24
#define MAP_GROUP_METEOR_FALLS_B1F_2R                   24
#define MAP_GROUP_RUSTURF_TUNNEL                        24
#define MAP_GROUP_UNDERWATER_SOOTOPOLIS_CITY            24
#define MAP_GROUP_DESERT_RUINS                          24
#define MAP_GROUP_GRANITE_CAVE_1F                       24
#define MAP_GROUP_GRANITE_CAVE_B1F                      24
#define MAP_GROUP_GRANITE_CAVE_B2F                      24
#define MAP_GROUP_GRANITE_CAVE_STEVENS_ROOM             24
#define MAP_GROUP_PETALBURG_WOODS                       24
#define MAP_GROUP_MT_CHIMNEY                            24
#define MAP_GROUP_JAGGED_PASS                           24
#define MAP_GROUP_FIERY_PATH                            24
#define MAP_GROUP_MT_PYRE_1F                            24
#define MAP_GROUP_MT_PYRE_2F                            24
#define MAP_GROUP_MT_PYRE_3F                            24
#define MAP_GROUP_MT_PYRE_4F                            24
#define MAP_GROUP_MT_PYRE_5F                            24
#define MAP_GROUP_MT_PYRE_6F                            24
#define MAP_GROUP_MT_PYRE_EXTERIOR                      24
#define MAP_GROUP_MT_PYRE_SUMMIT                        24
#define MAP_GROUP_AQUA_HIDEOUT_1F                       24
#define MAP_GROUP_AQUA_HIDEOUT_B1F                      24
#define MAP_GROUP_AQUA_HIDEOUT_B2F                      24
#define MAP_GROUP_UNDERWATER_SEAFLOOR_CAVERN            24
#define MAP_GROUP_SEAFLOOR_CAVERN_ENTRANCE              24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM1                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM2                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM3                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM4                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM5                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM6                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM7                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM8                 24
#define MAP_GROUP_SEAFLOOR_CAVERN_ROOM9                 24
#define MAP_GROUP_CAVE_OF_ORIGIN_ENTRANCE               24
#define MAP_GROUP_CAVE_OF_ORIGIN_1F                     24
#define MAP_GROUP_CAVE_OF_ORIGIN_B1F                    24
#define MAP_GROUP_CAVE_OF_ORIGIN_B2F                    24
#define MAP_GROUP_CAVE_OF_ORIGIN_B3F                    24
#define MAP_GROUP_CAVE_OF_ORIGIN_B4F                    24
#define MAP_GROUP_VICTORY_ROAD_1F                       24
#define MAP_GROUP_VICTORY_ROAD_B1F                      24
#define MAP_GROUP_VICTORY_ROAD_B2F                      24
#define MAP_GROUP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM     24
#define MAP_GROUP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM        24
#define MAP_GROUP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM       24
#define MAP_GROUP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM        24
#define MAP_GROUP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM    24
#define MAP_GROUP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM       24
#define MAP_GROUP_NEW_MAUVILLE_ENTRANCE                 24
#define MAP_GROUP_NEW_MAUVILLE_INSIDE                   24
#define MAP_GROUP_ABANDONED_SHIP_DECK                   24
#define MAP_GROUP_ABANDONED_SHIP_CORRIDORS_1F           24
#define MAP_GROUP_ABANDONED_SHIP_ROOMS_1F               24
#define MAP_GROUP_ABANDONED_SHIP_CORRIDORS_B1F          24
#define MAP_GROUP_ABANDONED_SHIP_ROOMS_B1F              24
#define MAP_GROUP_ABANDONED_SHIP_ROOMS2_B1F             24
#define MAP_GROUP_ABANDONED_SHIP_UNDERWATER1            24
#define MAP_GROUP_ABANDONED_SHIP_ROOM_B1F               24
#define MAP_GROUP_ABANDONED_SHIP_ROOMS2_1F              24
#define MAP_GROUP_ABANDONED_SHIP_CAPTAINS_OFFICE        24
#define MAP_GROUP_ABANDONED_SHIP_UNDERWATER2            24
#define MAP_GROUP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS 24
#define MAP_GROUP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS     24
#define MAP_GROUP_ISLAND_CAVE                           24
#define MAP_GROUP_ANCIENT_TOMB                          24
#define MAP_GROUP_UNDERWATER_ROUTE134                   24
#define MAP_GROUP_UNDERWATER_SEALED_CHAMBER             24
#define MAP_GROUP_SEALED_CHAMBER_OUTER_ROOM             24
#define MAP_GROUP_SEALED_CHAMBER_INNER_ROOM             24
#define MAP_GROUP_SCORCHED_SLAB                         24
#define MAP_GROUP_MAGMA_HIDEOUT_1F                      24
#define MAP_GROUP_MAGMA_HIDEOUT_B1F                     24
#define MAP_GROUP_MAGMA_HIDEOUT_B2F                     24
#define MAP_GROUP_SKY_PILLAR_ENTRANCE                   24
#define MAP_GROUP_SKY_PILLAR_OUTSIDE                    24
#define MAP_GROUP_SKY_PILLAR_1F                         24
#define MAP_GROUP_SKY_PILLAR_2F                         24
#define MAP_GROUP_SKY_PILLAR_3F                         24
#define MAP_GROUP_SKY_PILLAR_4F                         24
#define MAP_GROUP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM          24
#define MAP_GROUP_SKY_PILLAR_5F                         24
#define MAP_GROUP_SKY_PILLAR_TOP                        24

//--------------------------------------------------
// Map Group 25
//--------------------------------------------------

enum
{
    MAP_ID_SECRET_BASE_RED_CAVE1,
    MAP_ID_SECRET_BASE_BROWN_CAVE1,
    MAP_ID_SECRET_BASE_BLUE_CAVE1,
    MAP_ID_SECRET_BASE_YELLOW_CAVE1,
    MAP_ID_SECRET_BASE_TREE1,
    MAP_ID_SECRET_BASE_SHRUB1,
    MAP_ID_SECRET_BASE_RED_CAVE2,
    MAP_ID_SECRET_BASE_BROWN_CAVE2,
    MAP_ID_SECRET_BASE_BLUE_CAVE2,
    MAP_ID_SECRET_BASE_YELLOW_CAVE2,
    MAP_ID_SECRET_BASE_TREE2,
    MAP_ID_SECRET_BASE_SHRUB2,
    MAP_ID_SECRET_BASE_RED_CAVE3,
    MAP_ID_SECRET_BASE_BROWN_CAVE3,
    MAP_ID_SECRET_BASE_BLUE_CAVE3,
    MAP_ID_SECRET_BASE_YELLOW_CAVE3,
    MAP_ID_SECRET_BASE_TREE3,
    MAP_ID_SECRET_BASE_SHRUB3,
    MAP_ID_SECRET_BASE_RED_CAVE4,
    MAP_ID_SECRET_BASE_BROWN_CAVE4,
    MAP_ID_SECRET_BASE_BLUE_CAVE4,
    MAP_ID_SECRET_BASE_YELLOW_CAVE4,
    MAP_ID_SECRET_BASE_TREE4,
    MAP_ID_SECRET_BASE_SHRUB4,
    MAP_ID_SINGLE_BATTLE_COLOSSEUM,
    MAP_ID_TRADE_CENTER,
    MAP_ID_RECORD_CORNER,
    MAP_ID_DOUBLE_BATTLE_COLOSSEUM,
    MAP_ID_LINK_CONTEST_ROOM1,
    MAP_ID_UNKNOWN_MAP_25_29,
    MAP_ID_UNKNOWN_MAP_25_30,
    MAP_ID_UNKNOWN_MAP_25_31,
    MAP_ID_UNKNOWN_MAP_25_32,
    MAP_ID_UNKNOWN_MAP_25_33,
    MAP_ID_UNKNOWN_MAP_25_34,
    MAP_ID_LINK_CONTEST_ROOM2,
    MAP_ID_LINK_CONTEST_ROOM3,
    MAP_ID_LINK_CONTEST_ROOM4,
    MAP_ID_LINK_CONTEST_ROOM5,
    MAP_ID_LINK_CONTEST_ROOM6,
    MAP_ID_INSIDE_OF_TRUCK,
    MAP_ID_SS_TIDAL_CORRIDOR,
    MAP_ID_SS_TIDAL_LOWER_DECK,
    MAP_ID_SS_TIDAL_ROOMS,
};

#define MAP_GROUP_SECRET_BASE_RED_CAVE1    25
#define MAP_GROUP_SECRET_BASE_BROWN_CAVE1  25
#define MAP_GROUP_SECRET_BASE_BLUE_CAVE1   25
#define MAP_GROUP_SECRET_BASE_YELLOW_CAVE1 25
#define MAP_GROUP_SECRET_BASE_TREE1        25
#define MAP_GROUP_SECRET_BASE_SHRUB1       25
#define MAP_GROUP_SECRET_BASE_RED_CAVE2    25
#define MAP_GROUP_SECRET_BASE_BROWN_CAVE2  25
#define MAP_GROUP_SECRET_BASE_BLUE_CAVE2   25
#define MAP_GROUP_SECRET_BASE_YELLOW_CAVE2 25
#define MAP_GROUP_SECRET_BASE_TREE2        25
#define MAP_GROUP_SECRET_BASE_SHRUB2       25
#define MAP_GROUP_SECRET_BASE_RED_CAVE3    25
#define MAP_GROUP_SECRET_BASE_BROWN_CAVE3  25
#define MAP_GROUP_SECRET_BASE_BLUE_CAVE3   25
#define MAP_GROUP_SECRET_BASE_YELLOW_CAVE3 25
#define MAP_GROUP_SECRET_BASE_TREE3        25
#define MAP_GROUP_SECRET_BASE_SHRUB3       25
#define MAP_GROUP_SECRET_BASE_RED_CAVE4    25
#define MAP_GROUP_SECRET_BASE_BROWN_CAVE4  25
#define MAP_GROUP_SECRET_BASE_BLUE_CAVE4   25
#define MAP_GROUP_SECRET_BASE_YELLOW_CAVE4 25
#define MAP_GROUP_SECRET_BASE_TREE4        25
#define MAP_GROUP_SECRET_BASE_SHRUB4       25
#define MAP_GROUP_SINGLE_BATTLE_COLOSSEUM  25
#define MAP_GROUP_TRADE_CENTER             25
#define MAP_GROUP_RECORD_CORNER            25
#define MAP_GROUP_DOUBLE_BATTLE_COLOSSEUM  25
#define MAP_GROUP_LINK_CONTEST_ROOM1       25
#define MAP_GROUP_UNKNOWN_MAP_25_29        25
#define MAP_GROUP_UNKNOWN_MAP_25_30        25
#define MAP_GROUP_UNKNOWN_MAP_25_31        25
#define MAP_GROUP_UNKNOWN_MAP_25_32        25
#define MAP_GROUP_UNKNOWN_MAP_25_33        25
#define MAP_GROUP_UNKNOWN_MAP_25_34        25
#define MAP_GROUP_LINK_CONTEST_ROOM2       25
#define MAP_GROUP_LINK_CONTEST_ROOM3       25
#define MAP_GROUP_LINK_CONTEST_ROOM4       25
#define MAP_GROUP_LINK_CONTEST_ROOM5       25
#define MAP_GROUP_LINK_CONTEST_ROOM6       25
#define MAP_GROUP_INSIDE_OF_TRUCK          25
#define MAP_GROUP_SS_TIDAL_CORRIDOR        25
#define MAP_GROUP_SS_TIDAL_LOWER_DECK      25
#define MAP_GROUP_SS_TIDAL_ROOMS           25

//--------------------------------------------------
// Map Group 26
//--------------------------------------------------

enum
{
    MAP_ID_SAFARI_ZONE_NORTHWEST,
    MAP_ID_SAFARI_ZONE_NORTHEAST,
    MAP_ID_SAFARI_ZONE_SOUTHWEST,
    MAP_ID_SAFARI_ZONE_SOUTHEAST,
    MAP_ID_BATTLE_TOWER_OUTSIDE,
    MAP_ID_BATTLE_TOWER_LOBBY,
    MAP_ID_BATTLE_TOWER_ELEVATOR,
    MAP_ID_BATTLE_TOWER_CORRIDOR,
    MAP_ID_BATTLE_TOWER_BATTLE_ROOM,
    MAP_ID_SOUTHERN_ISLAND_EXTERIOR,
    MAP_ID_SOUTHERN_ISLAND_INTERIOR,
    MAP_ID_SAFARI_ZONE_REST_HOUSE,
};

#define MAP_GROUP_SAFARI_ZONE_NORTHWEST    26
#define MAP_GROUP_SAFARI_ZONE_NORTHEAST    26
#define MAP_GROUP_SAFARI_ZONE_SOUTHWEST    26
#define MAP_GROUP_SAFARI_ZONE_SOUTHEAST    26
#define MAP_GROUP_BATTLE_TOWER_OUTSIDE     26
#define MAP_GROUP_BATTLE_TOWER_LOBBY       26
#define MAP_GROUP_BATTLE_TOWER_ELEVATOR    26
#define MAP_GROUP_BATTLE_TOWER_CORRIDOR    26
#define MAP_GROUP_BATTLE_TOWER_BATTLE_ROOM 26
#define MAP_GROUP_SOUTHERN_ISLAND_EXTERIOR 26
#define MAP_GROUP_SOUTHERN_ISLAND_INTERIOR 26
#define MAP_GROUP_SAFARI_ZONE_REST_HOUSE   26

//--------------------------------------------------
// Map Group 27
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE104_PROTOTYPE,
    MAP_ID_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP,
};

#define MAP_GROUP_ROUTE104_PROTOTYPE                          27
#define MAP_GROUP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP 27

//--------------------------------------------------
// Map Group 28
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE109_SEASHORE_HOUSE,
};

#define MAP_GROUP_ROUTE109_SEASHORE_HOUSE 28

//--------------------------------------------------
// Map Group 29
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE110_TRICK_HOUSE_ENTRANCE,
    MAP_ID_ROUTE110_TRICK_HOUSE_END,
    MAP_ID_ROUTE110_TRICK_HOUSE_CORRIDOR,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE1,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE2,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE3,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE4,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE5,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE6,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE7,
    MAP_ID_ROUTE110_TRICK_HOUSE_PUZZLE8,
    MAP_ID_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE,
    MAP_ID_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE,
};

#define MAP_GROUP_ROUTE110_TRICK_HOUSE_ENTRANCE                29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_END                     29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_CORRIDOR                29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE1                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE2                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE3                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE4                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE5                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE6                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE7                 29
#define MAP_GROUP_ROUTE110_TRICK_HOUSE_PUZZLE8                 29
#define MAP_GROUP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE 29
#define MAP_GROUP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE 29

//--------------------------------------------------
// Map Group 30
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE113_GLASS_WORKSHOP,
};

#define MAP_GROUP_ROUTE113_GLASS_WORKSHOP 30

//--------------------------------------------------
// Map Group 31
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE123_BERRY_MASTERS_HOUSE,
};

#define MAP_GROUP_ROUTE123_BERRY_MASTERS_HOUSE 31

//--------------------------------------------------
// Map Group 32
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE119_WEATHER_INSTITUTE_1F,
    MAP_ID_ROUTE119_WEATHER_INSTITUTE_2F,
    MAP_ID_ROUTE119_HOUSE,
};

#define MAP_GROUP_ROUTE119_WEATHER_INSTITUTE_1F 32
#define MAP_GROUP_ROUTE119_WEATHER_INSTITUTE_2F 32
#define MAP_GROUP_ROUTE119_HOUSE                32

//--------------------------------------------------
// Map Group 33
//--------------------------------------------------

enum
{
    MAP_ID_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE,
};

#define MAP_GROUP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE 33

#endif // GUARD_MAP_CONSTANTS_H
