#ifndef GUARD_POKEMON_MENU_H
#define GUARD_POKEMON_MENU_H

#define POKEMENU_FIRST_FIELD_MOVE_ID 10

enum
{
    POKEMENU_SUMMARY,       // 0
    POKEMENU_SWITCH,        // 1
    POKEMENU_ITEM,          // 2
    POKEMENU_CANCEL,        // 3
    POKEMENU_MAIL = 7,
    POKEMENU_CUT = 10,
	POKEMENU_FLASH,
	POKEMENU_ROCK_SMASH,
	POKEMENU_STRENGTH,
	POKEMENU_SURF,
	POKEMENU_FLY,
	POKEMENU_DIVE,
	POKEMENU_WATERFALL,
	POKEMENU_TELEPORT,
	POKEMENU_DIG,
	POKEMENU_SECRET_POWER,
	POKEMENU_MILK_DRINK,
	POKEMENU_SOFT_BOILED,
	POKEMENU_SWEET_SCENT,
};

void sub_8089A70(void);
void sub_808A004();
void sub_808AB90(void);
void sub_808AB90(void); // unknown args
void sub_808AB90(void);
void sub_808AD58(void);
void sub_808B020(void);
void sub_808B0C0(u8);
void sub_808B508(u8);
void sub_808B564();

#endif // GUARD_POKEMON_MENU_H
