#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

enum
{
    MAPSEC_LittlerootTown,          // 0x00
    MAPSEC_OldaleTown,              // 0x01
    MAPSEC_DewfordTown,             // 0x02
    MAPSEC_LavaridgeTown,           // 0x03
    MAPSEC_FallarborTown,           // 0x04
    MAPSEC_VerdanturfTown,          // 0x05
    MAPSEC_PacifidlogTown,          // 0x06
    MAPSEC_PetalburgCity,           // 0x07
    MAPSEC_SlateportCity,           // 0x08
    MAPSEC_MauvilleCity,            // 0x09
    MAPSEC_RustboroCity,            // 0x0A
    MAPSEC_FortreeCity,             // 0x0B
    MAPSEC_LilycoveCity,            // 0x0C
    MAPSEC_MossdeepCity,            // 0x0D
    MAPSEC_SootopolisCity,          // 0x0E
    MAPSEC_EverGrandeCity,          // 0x0F
    MAPSEC_Route101,                // 0x10
    MAPSEC_Route102,                // 0x11
    MAPSEC_Route103,                // 0x12
    MAPSEC_Route104,                // 0x13
    MAPSEC_Route105,                // 0x14
    MAPSEC_Route106,                // 0x15
    MAPSEC_Route107,                // 0x16
    MAPSEC_Route108,                // 0x17
    MAPSEC_Route109,                // 0x18
    MAPSEC_Route110,                // 0x19
    MAPSEC_Route111,                // 0x1A
    MAPSEC_Route112,                // 0x1B
    MAPSEC_Route113,                // 0x1C
    MAPSEC_Route114,                // 0x1D
    MAPSEC_Route115,                // 0x1E
    MAPSEC_Route116,                // 0x1F
    MAPSEC_Route117,                // 0x20
    MAPSEC_Route118,                // 0x21
    MAPSEC_Route119,                // 0x22
    MAPSEC_Route120,                // 0x23
    MAPSEC_Route121,                // 0x24
    MAPSEC_Route122,                // 0x25
    MAPSEC_Route123,                // 0x26
    MAPSEC_Route124,                // 0x27
    MAPSEC_Route125,                // 0x28
    MAPSEC_Route126,                // 0x29
    MAPSEC_Route127,                // 0x2A
    MAPSEC_Route128,                // 0x2B
    MAPSEC_Route129,                // 0x2C
    MAPSEC_Route130,                // 0x2D
    MAPSEC_Route131,                // 0x2E
    MAPSEC_Route132,                // 0x2F
    MAPSEC_Route133,                // 0x30
    MAPSEC_Route134,                // 0x31
    MAPSEC_Underwater124,           // 0x32
    MAPSEC_Underwater125,           // 0x33
    MAPSEC_Underwater126,           // 0x34
    MAPSEC_Underwater127,           // 0x35
    MAPSEC_UnderwaterSootopolis,    // 0x36
    MAPSEC_GraniteCave,             // 0x37
    MAPSEC_MtChimney,               // 0x38
    MAPSEC_SafariZone,              // 0x39
    MAPSEC_BattleFrontier,          // 0x3A
    MAPSEC_PetalburgWoods,          // 0x3B
    MAPSEC_RusturfTunnel,           // 0x3C
    MAPSEC_AbandonedShip,           // 0x3D
    MAPSEC_NewMauville,             // 0x3E
    MAPSEC_MeteorFalls,             // 0x3F
    MAPSEC_MeteorFalls2,            // 0x40
    MAPSEC_MtPyre,                  // 0x41
    MAPSEC_AquaHideoutOld,          // 0x42
    MAPSEC_ShoalCave,               // 0x43
    MAPSEC_SeafloorCavern,          // 0x44
    MAPSEC_Underwater128,           // 0x45
    MAPSEC_VictoryRoad,             // 0x46
    MAPSEC_MirageIsland,            // 0x47
    MAPSEC_CaveOfOrigin,            // 0x48
    MAPSEC_SouthernIsland,          // 0x49
    MAPSEC_FieryPath,               // 0x4A
    MAPSEC_FieryPath2,              // 0x4B
    MAPSEC_JaggedPass,              // 0x4C
    MAPSEC_JaggedPass2,             // 0x4D
    MAPSEC_SealedChamber,           // 0x4E
    MAPSEC_UnderwaterSealedChamber, // 0x4F
    MAPSEC_ScorchedSlab,            // 0x50
    MAPSEC_IslandCave,              // 0x51
    MAPSEC_DesertRuins,             // 0x52
    MAPSEC_AncientTomb,             // 0x53
    MAPSEC_InsideOfTruck,           // 0x54
    MAPSEC_SkyPillar,               // 0x55
    MAPSEC_SecretBase,              // 0x56
    MAPSEC_Dynamic,                 // 0x57
    MAPSEC_Nothing                  // 0x58
};

#endif // GUARD_REGIONMAPSEC_H
