//
// Created by Scott Norton on 5/18/17.
//

#ifndef POKERUBY_TV_H
#define POKERUBY_TV_H
enum
{
    TVSHOW_FAN_CLUB_LETTER = 1,
    TVSHOW_RECENT_HAPPENINGS = 2,
    TVSHOW_PKMN_FAN_CLUB_OPINIONS = 3,
    TVSHOW_UNKN_SHOWTYPE_04 = 4,
    TVSHOW_NAME_RATER_SHOW = 5,
    TVSHOW_UNK_SHOWTYPE_06 = 6,
    TVSHOW_UNK_SHOWTYPE_07 = 7,
    TVSHOW_MASS_OUTBREAK = 41,
};
#endif //POKERUBY_TV_H
