FallarborTown_Mart_Text_DecidingSkittyEvolve:: @ 8176FF0
	.string "Ich habe lange überlegt, ob sich mein\n"
	.string "ENECO entwickeln soll oder nicht.\p"
	.string "Ich müsste nur diesen MONDSTEIN ein-\n"
	.string "setzen, aber das ist eine schwere\l"
	.string "Entscheidung...\p"
	.string "Würde es sich entwickeln, wäre es viel\n"
	.string "stärker.\p"
	.string "Aber es würde auch anders aussehen.$"

FallarborTown_Mart_Text_Skitty:: @ 81770D3
	.string "ENECO: Miyao?$"

FallarborTown_Mart_Text_SellNuggetIFound:: @ 81770E2
	.string "Ich habe hier ein NUGGET gefunden...\n"
	.string "Das werde ich wohl verkaufen. Was soll\l"
	.string "ich sonst damit machen?$"
