MauvilleCity_House2_EventObjects:: @ 8388624
	object_event 1, EVENT_OBJ_GFX_WOMAN_4, 0, 4, 5, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 0, 0, MauvilleCity_House2_EventScript_1572C0, 0

MauvilleCity_House2_MapWarps:: @ 838863C
	warp_def 3, 8, 0, 6, MAP_MAUVILLE_CITY
	warp_def 4, 8, 0, 6, MAP_MAUVILLE_CITY

MauvilleCity_House2_MapEvents:: @ 838864C
	map_events MauvilleCity_House2_EventObjects, MauvilleCity_House2_MapWarps, 0x0, 0x0
