LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls:: @ 818C4F9
	.string "Hier gibt es viele niedliche PUPPEN.\p"
	.string "Ich sollte lieber mir selbst welche\n"
	.string "kaufen, anstatt immer für meine Kinder.$"

LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon:: @ 818C556
	.string "Ich bin noch zu klein, um POKéMON auf-\n"
	.string "zuziehen, daher bekomme ich eine PUPPE.$"

LilycoveCity_DepartmentStore_5F_Text_SellManyCuteMatsHere:: @ 818C59F
	.string "Sie verkaufen viele hübsche MATTEN.\p"
	.string "Welche soll ich nur kaufen?\n"
	.string "Ich sollte sie alle kaufen...$"

LilycoveCity_DepartmentStore_5F_Text_UnusedFloorInfo: @ 818C5FA
	.string "ANBETUNGSWÜRDIGE FREUNDE\n"
	.string "4S: POKéPUPPEN$"
