LinkContestRoom1_EventObjects:: @ 839149C
	object_event 1, EVENT_OBJ_GFX_WOMAN_4, 0, 6, 4, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 2, EVENT_OBJ_GFX_CONTEST_JUDGE, 0, 7, 4, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 3, EVENT_OBJ_GFX_VAR_0, 0, 4, 7, 3, 7, 0, 0, 0, 0, 0x0, 0
	object_event 4, EVENT_OBJ_GFX_VAR_1, 0, 6, 7, 3, 7, 0, 0, 0, 0, 0x0, 0
	object_event 5, EVENT_OBJ_GFX_VAR_2, 0, 8, 7, 3, 7, 0, 0, 0, 0, 0x0, 0
	object_event 6, EVENT_OBJ_GFX_VAR_4, 0, 2, 6, 3, 10, 0, 0, 0, 0, 0x0, 0
	object_event 7, EVENT_OBJ_GFX_VAR_6, 0, 4, 2, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 8, EVENT_OBJ_GFX_VAR_7, 0, 5, 2, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 9, EVENT_OBJ_GFX_VAR_8, 0, 9, 2, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 10, EVENT_OBJ_GFX_VAR_9, 0, 10, 2, 3, 8, 0, 0, 0, 0, 0x0, 0
	object_event 11, EVENT_OBJ_GFX_VAR_A, 0, 12, 5, 3, 9, 0, 0, 0, 0, 0x0, 0
	object_event 12, EVENT_OBJ_GFX_VAR_5, 0, 2, 5, 3, 10, 0, 0, 0, 0, 0x0, 0
	object_event 13, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 5, 3, 1, 0, 0, 0, 0, 0x0, FLAG_LINK_CONTEST_ROOM_POKEBALL
	object_event 14, EVENT_OBJ_GFX_VAR_3, 0, 10, 7, 3, 7, 0, 0, 0, 0, 0x0, 0
	object_event 15, EVENT_OBJ_GFX_ARTIST, 0, 12, 6, 3, 9, 0, 0, 0, 0, 0x0, 0

LinkContestRoom1_MapEvents:: @ 8391604
