MauvilleCity_House1_Text_181B1A:: @ 8181B1A
	.string "Woohoo, deine POKéMON sehen wirklich\n"
	.string "sehr stark aus.\p"
	.string "Das sehe ich gerne!\n"
	.string "Hier, nimm diese VM!$"

MauvilleCity_House1_Text_181B64:: @ 8181B64
	.string "Diese VM enthält ZERTRÜMMERER.\p"
	.string "Wenn du unterwegs auf große\n"
	.string "Felsbrocken stößt...\p"
	.string "Dann nutze diese VM, um dir den Weg\n"
	.string "freizumachen.$"

MauvilleCity_House1_Text_181BF6:: @ 8181BF6
	.string "Oh ja, wenn du einen Felsen\n"
	.string "zertrümmerst, könnte ein POKéMON\l"
	.string "zum Vorschein kommen.$"
