SlateportCity_ContestLobby_Text_17C937:: @ 817C937
	.string "Ich möchte ein POKéMON aufziehen, das\n"
	.string "im Kampf und im WETTBEWERB\l"
	.string "“unbesiegbar” ist.\p"
	.string "Es ist schon verwirrend, herauszu-\n"
	.string "finden, welche Attacken es lernen soll.$"

SlateportCity_ContestLobby_Text_17C9D5:: @ 817C9D5
	.string "Haben einige deiner Freunde BEEREN?\p"
	.string "Du kannst den BEERENMIXER benutzen\n"
	.string "und zusammen mit ihnen {POKEBLOCK}\l"
	.string "herstellen.\p"
	.string "Das macht sehr viel Spaß!$"

SlateportCity_ContestLobby_Text_17CA67:: @ 817CA67
	.string "Ich habe zwei. Du kannst eine haben.$"

SlateportCity_ContestLobby_Text_17CA88:: @ 817CA88
	.string "Stelle {POKEBLOCK} her und verstaue sie\n"
	.string "darin.\p"
	.string "Wenn ihr einen {POKEBLOCK} herstellt, muss\n"
	.string "jeder eine andere BEERE einsetzen.$"

SlateportCity_ContestLobby_Text_17CAEC:: @ 817CAEC
	.string "Wenn du einen WETTBEWERB gewinnst,\n"
	.string "wird ein Bild deines POKéMON an die\l"
	.string "Wand gehängt.\p"
	.string "Das Porträt deines POKéMON wird\n"
	.string "außerdem mit deinem Namen versehen.$"
