SootopolisCity_Gym_B1F_EventObjects:: @ 838AD64
	object_event 1, EVENT_OBJ_GFX_LASS, 0, 7, 19, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 1, SootopolisCity_Gym_B1F_EventScript_15B0D8, 0
	object_event 2, EVENT_OBJ_GFX_BEAUTY, 0, 9, 17, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 1, 1, SootopolisCity_Gym_B1F_EventScript_15B11D, 0
	object_event 3, EVENT_OBJ_GFX_WOMAN_3, 0, 9, 14, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 1, 1, SootopolisCity_Gym_B1F_EventScript_15B106, 0
	object_event 4, EVENT_OBJ_GFX_BEAUTY, 0, 6, 13, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 5, SootopolisCity_Gym_B1F_EventScript_15B134, 0
	object_event 5, EVENT_OBJ_GFX_BEAUTY, 0, 3, 9, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 4, SootopolisCity_Gym_B1F_EventScript_15B162, 0
	object_event 6, EVENT_OBJ_GFX_WOMAN_2, 0, 11, 9, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 1, 2, SootopolisCity_Gym_B1F_EventScript_15B179, 0
	object_event 7, EVENT_OBJ_GFX_LASS, 0, 8, 7, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 1, 2, SootopolisCity_Gym_B1F_EventScript_15B0EF, 0
	object_event 8, EVENT_OBJ_GFX_BEAUTY, 0, 12, 7, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, 1, 3, SootopolisCity_Gym_B1F_EventScript_15B14B, 0

SootopolisCity_Gym_B1F_MapWarps:: @ 838AE24
	warp_def 11, 22, 3, 2, MAP_SOOTOPOLIS_CITY_GYM_1F

SootopolisCity_Gym_B1F_MapEvents:: @ 838AE2C
	map_events SootopolisCity_Gym_B1F_EventObjects, SootopolisCity_Gym_B1F_MapWarps, 0x0, 0x0
