SootopolisCity_Gym_B1F_MapScripts:: @ 815B0D7
	.byte 0

SootopolisCity_Gym_B1F_EventScript_15B0D8:: @ 815B0D8
	trainerbattle 0, TRAINER_ANDREA, 0, SootopolisCity_Gym_B1F_Text_18EA87, SootopolisCity_Gym_B1F_Text_18EACF
	msgbox SootopolisCity_Gym_B1F_Text_18EAED, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B0EF:: @ 815B0EF
	trainerbattle 0, TRAINER_CRISSY, 0, SootopolisCity_Gym_B1F_Text_18EB22, SootopolisCity_Gym_B1F_Text_18EB81
	msgbox SootopolisCity_Gym_B1F_Text_18EBB1, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B106:: @ 815B106
	trainerbattle 0, TRAINER_BRIANNA_2, 0, SootopolisCity_Gym_B1F_Text_18EBFA, SootopolisCity_Gym_B1F_Text_18EC5E
	msgbox SootopolisCity_Gym_B1F_Text_18EC92, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B11D:: @ 815B11D
	trainerbattle 0, TRAINER_CONNIE, 0, SootopolisCity_Gym_B1F_Text_18ECEB, SootopolisCity_Gym_B1F_Text_18ED18
	msgbox SootopolisCity_Gym_B1F_Text_18ED2B, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B134:: @ 815B134
	trainerbattle 0, TRAINER_BRIDGET, 0, SootopolisCity_Gym_B1F_Text_18ED91, SootopolisCity_Gym_B1F_Text_18EDE8
	msgbox SootopolisCity_Gym_B1F_Text_18EE03, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B14B:: @ 815B14B
	trainerbattle 0, TRAINER_OLIVIA, 0, SootopolisCity_Gym_B1F_Text_18EE96, SootopolisCity_Gym_B1F_Text_18EEDC
	msgbox SootopolisCity_Gym_B1F_Text_18EEF7, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B162:: @ 815B162
	trainerbattle 0, TRAINER_TIFFANY, 0, SootopolisCity_Gym_B1F_Text_18EF39, SootopolisCity_Gym_B1F_Text_18EFB8
	msgbox SootopolisCity_Gym_B1F_Text_18EFCA, 6
	end

SootopolisCity_Gym_B1F_EventScript_15B179:: @ 815B179
	trainerbattle 0, TRAINER_MARISSA, 0, SootopolisCity_Gym_B1F_Text_18F037, SootopolisCity_Gym_B1F_Text_18F07F
	msgbox SootopolisCity_Gym_B1F_Text_18F085, 6
	end
