MauvilleCity_House1_EventObjects:: @ 8388384
	object_event 1, EVENT_OBJ_GFX_SCIENTIST_1, 0, 4, 4, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, MauvilleCity_House1_EventScript_1569FD, 0

MauvilleCity_House1_MapWarps:: @ 838839C
	warp_def 3, 7, 0, 4, MAP_MAUVILLE_CITY
	warp_def 4, 7, 0, 4, MAP_MAUVILLE_CITY

MauvilleCity_House1_MapEvents:: @ 83883AC
	map_events MauvilleCity_House1_EventObjects, MauvilleCity_House1_MapWarps, 0x0, 0x0
