#ifndef	__ZOKUSEI_H_

#define	__ZOKUSEI_H_

const	u8	TypeCheckTable[]={
	NORMAL_TYPE,	IWA_TYPE,		5,	// NORMAL Ç≈ IWA Ç…çUåÇÇ∑ÇÈÇ∆ÅA
										// à–óÕÇOÅDÇTî{
	NORMAL_TYPE,	METAL_TYPE,		5,	// new!!

	FIRE_TYPE,		FIRE_TYPE,		5,
	FIRE_TYPE,		WATER_TYPE,		5,
	FIRE_TYPE,		KUSA_TYPE,		20,	
	FIRE_TYPE,		KOORI_TYPE,		20,	
	FIRE_TYPE,		MUSHI_TYPE,		20,
	FIRE_TYPE,		IWA_TYPE,		5,
	FIRE_TYPE,		DRAGON_TYPE,	5,
	FIRE_TYPE,		METAL_TYPE,		20,	// new!! 99/09/22 sige

	WATER_TYPE,		FIRE_TYPE,		20,
	WATER_TYPE,		WATER_TYPE,		5,
	WATER_TYPE,		KUSA_TYPE,		5,
	WATER_TYPE,		JIMEN_TYPE,		20,
	WATER_TYPE,		IWA_TYPE,		20,
	WATER_TYPE,		DRAGON_TYPE,	5,

	ELECTRIC_TYPE,	WATER_TYPE,		20,
	ELECTRIC_TYPE,	ELECTRIC_TYPE,	5,
	ELECTRIC_TYPE,	KUSA_TYPE,		5,
	ELECTRIC_TYPE,	JIMEN_TYPE,		0,
	ELECTRIC_TYPE,	HIKOU_TYPE,		20,
	ELECTRIC_TYPE,	DRAGON_TYPE,	5,

	KUSA_TYPE,		FIRE_TYPE,		5,
	KUSA_TYPE,		WATER_TYPE,		20,
	KUSA_TYPE,		KUSA_TYPE,		5,
	KUSA_TYPE,		POISON_TYPE,	5,
	KUSA_TYPE,		JIMEN_TYPE,		20,
	KUSA_TYPE,		HIKOU_TYPE,		5,
	KUSA_TYPE,		MUSHI_TYPE,		5,
	KUSA_TYPE,		IWA_TYPE,		20,
	KUSA_TYPE,		DRAGON_TYPE,	5,
	KUSA_TYPE,		METAL_TYPE,		5,

	KOORI_TYPE,		WATER_TYPE,		5,
	KOORI_TYPE,		KUSA_TYPE,		20,
	KOORI_TYPE,		KOORI_TYPE,		5,
	KOORI_TYPE,		JIMEN_TYPE,		20,
	KOORI_TYPE,		HIKOU_TYPE,		20,
	KOORI_TYPE,		DRAGON_TYPE,	20,
	KOORI_TYPE,		METAL_TYPE,		5,	// new!!
	KOORI_TYPE,		FIRE_TYPE,		5,	// new!!

	BATTLE_TYPE,	NORMAL_TYPE,	20,
	BATTLE_TYPE,	KOORI_TYPE,		20,
	BATTLE_TYPE,	POISON_TYPE,	5,
	BATTLE_TYPE,	HIKOU_TYPE,		5,
	BATTLE_TYPE,	SP_TYPE,		5,
	BATTLE_TYPE,	MUSHI_TYPE,		5,
	BATTLE_TYPE,	IWA_TYPE,		20,
	BATTLE_TYPE,	AKU_TYPE,		20,	// new!!
	BATTLE_TYPE,	METAL_TYPE,		20,	// new!!

	POISON_TYPE,	KUSA_TYPE,		20,
	POISON_TYPE,	POISON_TYPE,	5,
	POISON_TYPE,	JIMEN_TYPE,		5,
	POISON_TYPE,	IWA_TYPE,		5,
	POISON_TYPE,	GHOST_TYPE,		5,
	POISON_TYPE,	METAL_TYPE,		0,	// new!!

	JIMEN_TYPE,		FIRE_TYPE,		20,
	JIMEN_TYPE,		ELECTRIC_TYPE,	20,
	JIMEN_TYPE,		KUSA_TYPE,		5,
	JIMEN_TYPE,		POISON_TYPE,	20,
	JIMEN_TYPE,		HIKOU_TYPE,		0,
	JIMEN_TYPE,		MUSHI_TYPE,		5,
	JIMEN_TYPE,		IWA_TYPE,		20,
	JIMEN_TYPE,		METAL_TYPE,		20,	// new!!

	HIKOU_TYPE,		ELECTRIC_TYPE,	5,
	HIKOU_TYPE,		KUSA_TYPE,		20,
	HIKOU_TYPE,		BATTLE_TYPE,	20,
	HIKOU_TYPE,		MUSHI_TYPE,		20,
	HIKOU_TYPE,		IWA_TYPE,		5,
	HIKOU_TYPE,		METAL_TYPE,		5,	// new!!

	SP_TYPE,		BATTLE_TYPE,	20,
	SP_TYPE,		POISON_TYPE,	20,
	SP_TYPE,		SP_TYPE,		5,
	SP_TYPE,		AKU_TYPE,		0,		// new!!
	SP_TYPE,		METAL_TYPE,		5,	

	MUSHI_TYPE,		FIRE_TYPE,		5,
	MUSHI_TYPE,		KUSA_TYPE,		20,
	MUSHI_TYPE,		BATTLE_TYPE,	5,
	MUSHI_TYPE,		POISON_TYPE,	5,	// new!!
	MUSHI_TYPE,		HIKOU_TYPE,		5,
	MUSHI_TYPE,		SP_TYPE,		20,
	MUSHI_TYPE,		GHOST_TYPE,		5,
	MUSHI_TYPE,		AKU_TYPE,		20,		// new!!
	MUSHI_TYPE,		METAL_TYPE,		5,	// new!!

	IWA_TYPE,		FIRE_TYPE,		20,
	IWA_TYPE,		KOORI_TYPE,		20,
	IWA_TYPE,		BATTLE_TYPE,	5,
	IWA_TYPE,		JIMEN_TYPE,		5,
	IWA_TYPE,		HIKOU_TYPE,		20,
	IWA_TYPE,		MUSHI_TYPE,		20,
	IWA_TYPE,		METAL_TYPE,		5,	// new!!

	GHOST_TYPE,		NORMAL_TYPE,	0,
	GHOST_TYPE,		SP_TYPE,		20,
	GHOST_TYPE,		AKU_TYPE,		5,		// new!!
	GHOST_TYPE,		METAL_TYPE,		5,	// new!!
	GHOST_TYPE,		GHOST_TYPE,		20,	

	DRAGON_TYPE,	DRAGON_TYPE,	20,
	DRAGON_TYPE,	METAL_TYPE,		5,	// new!!

	AKU_TYPE,		BATTLE_TYPE,	5,	// new!!
	AKU_TYPE,		SP_TYPE,		20,		// new!!
	AKU_TYPE,		GHOST_TYPE,		20	,	// new!!
	AKU_TYPE,		AKU_TYPE,		5,		// new!!
	AKU_TYPE,		METAL_TYPE,		5,		// new!!

	METAL_TYPE,		FIRE_TYPE,		5,	// new!!
	METAL_TYPE,		WATER_TYPE,		5,	// new!!
	METAL_TYPE,		ELECTRIC_TYPE,	5,	// new!!
	METAL_TYPE,		KOORI_TYPE,		20,	// new!!
	METAL_TYPE,		IWA_TYPE,		20,	// new!!
	METAL_TYPE,		METAL_TYPE,		5,	// new!!

	0xfe,			0xfe,			0,	// miyaburi check

	NORMAL_TYPE,	GHOST_TYPE,		0,
	BATTLE_TYPE,	GHOST_TYPE,		0,

	0xff,			0xff,			0,
};

#define	TYPE_CHECK_TABLE_MAX	(sizeof(TypeCheckTable)/3)

const u8 ZokuseiMsg[][5]={
		{NO_,bou_,MA_,RU_,EOM_},
		{ka_,ku_,to_,u_,EOM_},
		{hi_,ko_,u_,EOM_,EOM_},
		{do_,ku_,EOM_,EOM_,EOM_},
		{zi_,me_,n_,EOM_,EOM_},
		{i_,wa_,EOM_,EOM_,EOM_},
		{mu_,si_,EOM_,EOM_,EOM_},
		{GO_,bou_,SU_,TO_,EOM_},
		{ha_,ga_,ne_,EOM_,EOM_},
		{hate_,hate_,hate_,EOM_,EOM_},
		{ho_,no_,o_,EOM_,EOM_},
		{mi_,zu_,EOM_,EOM_,EOM_},
		{ku_,sa_,EOM_,EOM_,EOM_},
		{de_,n_,ki_,EOM_,EOM_},
		{E_,SU_,PA_,bou_,EOM_},
		{ko_,o_,ri_,EOM_,EOM_},
		{DO_,RA_,GO_,N_,EOM_},
		{a_,ku_,EOM_,EOM_,EOM_},
};

#endif
