Route129_MapScripts:: @ 8152365
	.byte 0

Route129_EventScript_152366:: @ 8152366
	trainerbattle_single TRAINER_CHASE, Route129_Text_1C2161, Route129_Text_1C2198
	msgbox Route129_Text_1C21B4, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_15237D:: @ 815237D
	trainerbattle_single TRAINER_ALLISON, Route129_Text_1C21ED, Route129_Text_1C222F
	msgbox Route129_Text_1C2243, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_152394:: @ 8152394
	trainerbattle_single TRAINER_REED, Route129_Text_1C22C8, Route129_Text_1C22EC
	msgbox Route129_Text_1C230F, MSGBOX_AUTOCLOSE
	end

Route129_EventScript_1523AB:: @ 81523AB
	trainerbattle_single TRAINER_TISHA, Route129_Text_1C2349, Route129_Text_1C2378
	msgbox Route129_Text_1C23A3, MSGBOX_AUTOCLOSE
	end
