	.align 2

gTilesetTiles_Petalburg:: @ 82166E0
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Petalburg:: @ 8216ED4
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2

gTilesetTiles_Rustboro:: @ 82170D4
	.incbin "data/tilesets/secondary/rustboro/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Rustboro:: @ 8218484
	.incbin "data/tilesets/secondary/rustboro/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/15.gbapal"

	.align 2

gTilesetTiles_Dewford:: @ 8218684
	.incbin "data/tilesets/secondary/dewford/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Dewford:: @ 8219120
	.incbin "data/tilesets/secondary/dewford/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/15.gbapal"

	.align 2

gTilesetTiles_Slateport:: @ 8219320
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Slateport:: @ 821AB54
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2

gTilesetTiles_Mauville:: @ 821AD54
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Mauville:: @ 821C12C
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2

gTilesetTiles_Lavaridge:: @ 821C32C
	.incbin "data/tilesets/secondary/lavaridge/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Lavaridge:: @ 821D190
	.incbin "data/tilesets/secondary/lavaridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/15.gbapal"

	.align 2

gTilesetTiles_Fallarbor:: @ 821D390
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Fallarbor:: @ 821E630
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2

gTilesetTiles_Fortree:: @ 821E830
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Fortree:: @ 821FB9C
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2

gTilesetTiles_Lilycove:: @ 821FD9C
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Lilycove:: @ 82210B4
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2

gTilesetTiles_Mossdeep:: @ 82212B4
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Mossdeep:: @ 82222BC
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2

gTilesetTiles_EverGrande:: @ 82224BC
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_EverGrande:: @ 82230D4
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2

gTilesetTiles_Pacifidlog:: @ 82232D4
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Pacifidlog:: @ 82249CC
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2

gTilesetTiles_Sootopolis:: @ 8224BCC
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Sootopolis:: @ 8225420
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2

gTilesetTiles_Building:: @ 8225620
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Building:: @ 8225FA4
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

.ifndef GERMAN
	.align 2
gTilesetTiles_Shop:: @ 82261A4
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop:: @ 8227788
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"
.endif

	.align 2

gTilesetTiles_PokemonCenter:: @ 8227988
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PokemonCenter:: @ 8228AAC
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2

gTilesetTiles_Cave:: @ 8228CAC
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Cave:: @ 822A814
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2

gTilesetTiles_PokemonSchool:: @ 822AA14
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PokemonSchool:: @ 822B15C
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2

gTilesetTiles_PokemonFanClub:: @ 822B35C
	.incbin "data/tilesets/secondary/pokemon_fan_club/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PokemonFanClub:: @ 822BC88
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/15.gbapal"

	.align 2

gTilesetTiles_Unused1:: @ 822BE88
	.incbin "data/tilesets/secondary/unused_1/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Unused1:: @ 822BED4
	.incbin "data/tilesets/secondary/unused_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/15.gbapal"

	.align 2

gTilesetTiles_MeteorFalls:: @ 822C0D4
	.incbin "data/tilesets/secondary/meteor_falls/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_MeteorFalls:: @ 822DC1C
	.incbin "data/tilesets/secondary/meteor_falls/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/15.gbapal"

	.align 2

gTilesetTiles_OceanicMuseum:: @ 822DE1C
	.incbin "data/tilesets/secondary/oceanic_museum/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_OceanicMuseum:: @ 822EDA8
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/15.gbapal"

	.align 2

gTilesetTiles_CableClub:: @ 822EFA8
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2

	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2

gTilesetPalettes_CableClub:: @ 8233EA8
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2

gTilesetTiles_SeashoreHouse:: @ 82340A8
	.incbin "data/tilesets/secondary/seashore_house/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SeashoreHouse:: @ 8234984
	.incbin "data/tilesets/secondary/seashore_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/15.gbapal"

	.align 2

gTilesetTiles_PrettyPetalFlowerShop:: @ 8234B84
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PrettyPetalFlowerShop:: @ 823577C
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/15.gbapal"

	.align 2

gTilesetTiles_PokemonDayCare:: @ 823597C
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PokemonDayCare:: @ 82363B8
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2

gTilesetTiles_Facility:: @ 82365B8
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Facility:: @ 8238140
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2

gTilesetTiles_BikeShop:: @ 8238340
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_BikeShop:: @ 8239670
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2

gTilesetTiles_RusturfTunnel:: @ 8239870
	.incbin "data/tilesets/secondary/rusturf_tunnel/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_RusturfTunnel:: @ 823A264
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseBrownCave:: @ 823A9E4
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseTree:: @ 823B108
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseShrub:: @ 823B870
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseBlueCave:: @ 823BE8C
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseYellowCave:: @ 823C5C4
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2

@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SecretBaseRedCave:: @ 823CBFC
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2

gTilesetTiles_SecretBaseBrownCave:: @ 823CDFC
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2

gTilesetTiles_SecretBaseTree:: @ 823D85C
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2

gTilesetTiles_SecretBaseShrub:: @ 823E2BC
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2

gTilesetTiles_SecretBaseBlueCave:: @ 823ED1C
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2

gTilesetTiles_SecretBaseYellowCave:: @ 823F77C
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2

gTilesetTiles_SecretBaseRedCave:: @ 82401DC
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2

gTilesetTiles_InsideOfTruck:: @ 8240C3C
	.incbin "data/tilesets/secondary/inside_of_truck/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_InsideOfTruck:: @ 8240E98
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/15.gbapal"

	.align 2

gTilesetTiles_Contest:: @ 8241098
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Contest:: @ 8241BEC
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2

gTilesetTiles_LilycoveMuseum:: @ 8241DEC
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_LilycoveMuseum:: @ 8243108
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2

gTilesetTiles_BrendansMaysHouse:: @ 8243308
	.incbin "data/tilesets/secondary/brendans_mays_house/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_BrendansMaysHouse:: @ 82442BC
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/15.gbapal"

	.align 2

gTilesetTiles_Lab:: @ 82444BC
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Lab:: @ 8245510
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2

gTilesetTiles_Underwater:: @ 8245710
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Underwater:: @ 82468CC
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2

gTilesetTiles_GenericBuilding:: @ 8246ACC
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_GenericBuilding:: @ 8248494
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2

gTilesetTiles_MauvilleGameCorner:: @ 8248694
	.incbin "data/tilesets/secondary/mauville_game_corner/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_MauvilleGameCorner:: @ 8249358
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/15.gbapal"

	.align 2

gTilesetTiles_Unused2:: @ 8249558
	.incbin "data/tilesets/secondary/unused_2/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Unused2:: @ 8249A80
	.incbin "data/tilesets/secondary/unused_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/15.gbapal"

	.align 2

gTilesetTiles_RustboroGym:: @ 8249C80
	.incbin "data/tilesets/secondary/rustboro_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_RustboroGym:: @ 824A114
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_DewfordGym:: @ 824A314
	.incbin "data/tilesets/secondary/dewford_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_DewfordGym:: @ 824A570
	.incbin "data/tilesets/secondary/dewford_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_MauvilleGym:: @ 824A770
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_MauvilleGym:: @ 824AD9C
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_LavaridgeGym:: @ 824AF9C
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_LavaridgeGym:: @ 824B2A8
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_PetalburgGym:: @ 824B4A8
	.incbin "data/tilesets/secondary/petalburg_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_PetalburgGym:: @ 824BE08
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_FortreeGym:: @ 824C008
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_FortreeGym:: @ 824C2C8
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_MossdeepGym:: @ 824C4C8
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_MossdeepGym:: @ 824CA00
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_SootopolisGym:: @ 824CC00
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_SootopolisGym:: @ 824E030
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2

gTilesetTiles_TrickHousePuzzle:: @ 824E230
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_TrickHousePuzzle:: @ 824EEA8
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2

gTilesetTiles_Ship:: @ 824F0A8
	.incbin "data/tilesets/secondary/ship/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_Ship:: @ 824FC78
	.incbin "data/tilesets/secondary/ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ship/palettes/15.gbapal"

	.align 2

gTilesetTiles_SecretBase:: @ 824FE78
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2

	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2

gTilesetPalettes_SecretBase:: @ 8257E78
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2

gTilesetTiles_EliteFour:: @ 8258078
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_EliteFour:: @ 82590F4
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2

gTilesetTiles_BattleTower:: @ 82592F4
	.incbin "data/tilesets/secondary/battle_tower/tiles.4bpp.lz"

	.align 2

gTilesetPalettes_BattleTower:: @ 8259A1C
	.incbin "data/tilesets/secondary/battle_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tower/palettes/15.gbapal"
