LavaridgeTown_Gym_1F_Text_GymGuideAdvice:: @ 8176312
	.string "Hey, how's it going, CHAMPION-\n"
	.string "bound {PLAYER}?\p"
	.string "LAVARIDGE's GYM LEADER FLANNERY\n"
	.string "uses FIRE-type POKéMON.\p"
	.string "Her passion for POKéMON burns stronger\n"
	.string "and hotter than a volcano.\p"
	.string "Don't get too close to her - you'll burn!\n"
	.string "Hose her down with water and then\l"
	.string "go for it!$"

LavaridgeTown_Gym_1F_Text_GymGuidePostVictory:: @ 817640C
	.string "Yow! That was a scorching hot battle!$"

LavaridgeTown_Gym_1F_Text_ColeIntro:: @ 8176432
	.string "Owowowowow!\n"
	.string "Yikes, it's hot!$"

LavaridgeTown_Gym_1F_Text_ColeDefeat:: @ 817644F
	.string "I'm blinded by sweat in my eyes...$"

LavaridgeTown_Gym_1F_Text_ColePostBattle:: @ 8176472
	.string "Being buried in hot sand promotes\n"
	.string "circulation.\p"
	.string "It's effective for healing pain in\n"
	.string "your joints.$"

LavaridgeTown_Gym_1F_Text_AxleIntro:: @ 81764D1
	.string "I'm trying to relieve my stress.\n"
	.string "Don't come along and stress me out!$"

LavaridgeTown_Gym_1F_Text_AxleDefeat:: @ 8176516
	.string "I hope FLANNERY flames you good!$"

LavaridgeTown_Gym_1F_Text_AxlePostBattle:: @ 8176537
	.string "Haaah... Whew...\p"
	.string "If you spend too much time buried in\n"
	.string "hot sand, it tuckers you out...$"

LavaridgeTown_Gym_B1F_Text_AndyIntro:: @ 817658D
	.string "You must be getting tired by now.\n"
	.string "You'd like to rest in the hot sand,\l"
	.string "wouldn't you?\p"
	.string "But you should know that maintaining\n"
	.string "your willpower is an important ability\l"
	.string "for all TRAINERS.$"

LavaridgeTown_Gym_B1F_Text_AndyDefeat:: @ 817663F
	.string "Play with fire, and be burned...$"

LavaridgeTown_Gym_B1F_Text_AndyPostBattle:: @ 8176660
	.string "Your skill is real...\n"
	.string "But our LEADER FLANNERY is strong.\p"
	.string "If you don't watch yourself, you'll be\n"
	.string "burned seriously.$"

LavaridgeTown_Gym_1F_Text_ZaneIntro:: @ 81766D2
	.string "Can your POKéMON withstand\n"
	.string "392-degree heat?$"

LavaridgeTown_Gym_1F_Text_ZaneDefeat:: @ 81766FE
	.string "It didn't burn hotly enough...$"

LavaridgeTown_Gym_1F_Text_ZanePostBattle:: @ 817671D
	.string "The temperature of magma is\n"
	.string "392 degrees.\p"
	.string "Your POKéMON beat me, so they should\n"
	.string "easily survive in magma.$"

LavaridgeTown_Gym_1F_Text_SadieIntro:: @ 8176784
	.string "Um...\n"
	.string "Okay, I'll battle with you.$"

LavaridgeTown_Gym_1F_Text_SadieDefeat:: @ 81767A6
	.string "Oh, but you're too strong.$"

LavaridgeTown_Gym_1F_Text_SadiePostBattle:: @ 81767C1
	.string "I'm going to be a pretty and strong\n"
	.string "TRAINER just like FLANNERY.$"

LavaridgeTown_Gym_1F_Text_FlanneryIntro:: @ 8176801
	.string "Welcome... No, wait.\p"
	.string "Puny TRAINER, how good to see you've\n"
	.string "made it here!\p"
	.string "I have been entrusted with the...\n"
	.string "No, wait.\p"
	.string "I am FLANNERY, and I'm the GYM\n"
	.string "LEADER here!\p"
	.string "Uh...\n"
	.string "Dare not underestimate me, though\l"
	.string "I have been LEADER only a short time!\p"
	.string "With skills inherited from my grand-\n"
	.string "father, I shall, uh...demonstrate the\l"
	.string "hot moves we have honed on this land!$"

LavaridgeTown_Gym_1F_Text_FlanneryDefeat:: @ 8176960
	.string "Oh...\n"
	.string "I guess I was trying too hard...\p"
	.string "I... I've only recently become a GYM\n"
	.string "LEADER.\p"
	.string "I tried too hard to be someone I'm not.\p"
	.string "I have to do things my natural way.\n"
	.string "If I don't, my POKéMON will be confused.\p"
	.string "Thanks for teaching me that.\n"
	.string "For that, you deserve this.$"

LavaridgeTown_Gym_1F_Text_ReceivedHeatBadge:: @ 8176A62
	.string "{PLAYER} received the HEAT BADGE\n"
	.string "from FLANNERY.$"

LavaridgeTown_Gym_1F_Text_ExplainHeatBadgeTakeThis:: @ 8176A8C
	.string "If you have a HEAT BADGE, all POKéMON\n"
	.string "up to Level 50, even those you get in\l"
	.string "trades from other people, will obey\l"
	.string "you completely.\p"
	.string "And, it lets POKéMON use the HM move\n"
	.string "STRENGTH outside of battle.\p"
	.string "This is a token of my appreciation.\n"
	.string "Don't be shy about taking it!$"

LavaridgeTown_Gym_1F_Text_ExplainOverheat:: @ 8176B8F
	.string "That TM50 contains OVERHEAT.\p"
	.string "That move inflicts serious damage on\n"
	.string "the opponent.\p"
	.string "But it also sharply cuts the SP. ATK\n"
	.string "of the POKéMON using it. It might not\l"
	.string "be suitable for longer battles.$"

LavaridgeTown_Gym_1F_Text_FlanneryPostBattle:: @ 8176C4A
	.string "Your power reminds me of someone...\p"
	.string "Oh! I know! You battle like NORMAN,\n"
	.string "the GYM LEADER of PETALBURG.$"

LavaridgeTown_Gym_1F_Text_GymStatue:: @ 8176CAF
	.string "LAVARIDGE TOWN POKéMON GYM$"

LavaridgeTown_Gym_1F_Text_GymStatueCertified:: @ 8176CCA
	.string "LAVARIDGE TOWN POKéMON GYM\p"
	.string "FLANNERY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
