FallarborTown_MoveRelearnersHouse_Text_ImTheMoveTutor:: @ 8177AF4
	.string "Ich bin der ATTACKEN-HELFER.\p"
	.string "Ich kenne alle Attacken, die ein\n"
	.string "POKéMON lernen kann - und ich kann sie\l"
	.string "ihnen beibringen.\p"
	.string "Ich kann auch deinen POKéMON neue\n"
	.string "Attacken beibringen, wenn du magst.\p"
	.string "Als Gegenleistung hätte ich gerne eine\n"
	.string "HERZSCHUPPE. Die sammle ich nämlich.$"

FallarborTown_MoveRelearnersHouse_Text_ThatsAHeartScaleWantMeToTeachMove:: @ 8177BDB
	.string "Oh! Das ist es! Das ist ehrlich und\n"
	.string "wahrhaftig eine HERZSCHUPPE!\p"
	.string "Lass mich raten... Ich soll einem POKéMON\n"
	.string "eine neue Attacke beibringen?!?$"

FallarborTown_MoveRelearnersHouse_Text_TutorWhichMon:: @ 8177C3F
	.string "Welches POKéMON soll sie lernen?$"

FallarborTown_MoveRelearnersHouse_Text_TeachWhichMove:: @ 8177C5D
	.string "Welche Attacke soll ich es lehren?$"

FallarborTown_MoveRelearnersHouse_Text_DontHaveMoveToTeachPokemon:: @ 8177C78
	.string "Tut mir Leid...\p"
	.string "Scheinbar gibt es keine Attacke, die ich\n"
	.string "diesem POKéMON beibringen kann.$"

FallarborTown_MoveRelearnersHouse_Text_HandedOverHeartScale:: @ 8177CC3
	.string "{PLAYER} tauscht eine HERZSCHUPPE ein.$"

FallarborTown_MoveRelearnersHouse_Text_ComeBackWithHeartScale:: @ 8177CEF
	.string "Falls deine POKéMON neue Attacken\n"
	.string "lernen sollen, komm mit einer\l"
	.string "HERZSCHUPPE wieder.$"

FallarborTown_MoveRelearnersHouse_Text_CantTeachEgg:: @ 8177D33
	.string "Bitte? Ich kann einem EI nicht eine\n"
	.string "einzige Attacke beibringen!$"
