MossdeepCity_House1_Text_18D465:: @ 818D465
	.string "Hmm!\n"
	.string "Dein {STR_VAR_1}...$"

MossdeepCity_House1_Text_18D475:: @ 818D475
	.string "Es mag {STR_VAR_1},\n"
	.string "nicht wahr?\p"
	.string "Nein, ich bin mir sicher. Es mag mit\n"
	.string "Sicherheit {STR_VAR_1}!$"

MossdeepCity_House1_Text_18D4C0:: @ 818D4C0
	.string "Es scheint {POKEBLOCK}\n"
	.string "weder zu lieben noch abzulehnen.$"

MossdeepCity_House1_Text_18D4F1:: @ 818D4F1
	.string "Mein Mann weiß auf den ersten Blick,\n"
	.string "welche Art von {POKEBLOCK}\l"
	.string "ein POKéMON mag und welche nicht.$"
