LilycoveCity_House4_Text_MysteriesAtBottomOfSea:: @ 818BEE8
	.string "This planet's biggest mysteries are\n"
	.string "at the bottom of the sea.\p"
	.string "Somebody said that, but I don't know...$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:: @ 818BF4E
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"
